&nbsp;

# figshare registration process

- 登録する前に、きちんとファイルの中身を確認し、確認できたら [../../out/figshare/](../../out/figshare/) に移動させる

In [2]:
import polars as pl
from IPython.display import display

&nbsp;

&nbsp;

## 1. HN-ratio file

In [3]:
HNratio = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/HNratio_gencode_261001_all.tsv",
    separator="\t",
    n_threads=16
)

display(HNratio)

shape: (517_038, 407)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transcrip ┆ SRR276819 ┆ SRR276819 ┆ SRR249737 ┆ … ┆ HRR255909 ┆ HRR255910 ┆ HRR255913 ┆ HRR25591 │
│ t_id      ┆ 84        ┆ 83        ┆ 72        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 4        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 832824.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 832825.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 832826.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 832827.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 832828.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENST00000 ┆ 13.724599 ┆ 0.078243  ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 0.264248 │
│ 797950.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 819228.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 819229.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 18.658653 ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 751368.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ 839853.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# # 確認できたので圧縮して ../../out/figshare/HNscore/ に移動させる
# HNratio.write_csv(
#     "../../out/figshare/HNscore/HNratio_gencode_261001_all.tsv.gz",
#     separator="\t",
#     compression="gzip",
#     compression_level=9
# )

&nbsp;

&nbsp;

&nbsp;

## 2. HN-score file (Parquet Format)

In [6]:
HNscore_all = pl.read_parquet(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HNscore_gencode_human_261001_HN2_transcript_all_gencode_annotation.parquet"
).with_columns(
    # Join every list[str] column so write_csv can emit TSV.
    pl.col(pl.List(pl.String)).list.join(", ") # TSV で保存するために、list[str] を str に変換
)

display(HNscore_all)

shape: (517_038, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆             ┆ str        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ null        ┆ ensembl_hav ┆ MANE_selec ┆ 1          │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ t          ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ polya_site  ┆ ensembl_hav ┆ alternativ ┆ 3          │
│ 9223.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ e 5' UTR,  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ inferred   ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ t…         ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ null        ┆ ensembl_hav ┆ non        ┆ 1          │
│ 0260.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ canonical  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ TEC        ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ null        ┆ ensembl_hav ┆ intropolis ┆ 4          │
│ 6231.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ _filtered, ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ Snaptron_… ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ polya_site, ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0762.5      ┆     ┆       ┆            ┆   ┆ polya_signa ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ l           ┆ mo_sapie…   ┆            ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ polya_site, ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ polya_signa ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ l           ┆ mo_sapie…   ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ ensembl_hav ┆ RNA-Seq    ┆ 1          │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapie…   ┆ partial    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# # parquet format から、TSV format に変換して ../../out/figshare/HNscore/ に移動させる

# HNscore_all.write_csv(
#     "../../out/figshare/HNscore/HNscore_gencode_human_261001_HN2_transcript_all_gencode_annotation.tsv",
#     separator="\t",
#     # compression="gzip",
#     # compression_level=9
# )

&nbsp;

&nbsp;

## 2. HN-score file (UP, DOWN, UNCHANGE)

In [9]:
HNscore_classification = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/HNratio_categorized_2.tsv.gz",
    separator="\t",
    n_threads=16
)

display(HNscore_classification)

shape: (517_038, 407)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transcrip ┆ SRR276819 ┆ SRR276819 ┆ SRR249737 ┆ … ┆ HRR255909 ┆ HRR255910 ┆ HRR255913 ┆ HRR25591 │
│ t_id      ┆ 84_catego ┆ 83_catego ┆ 72_catego ┆   ┆ _category ┆ _category ┆ _category ┆ 4_catego │
│ ---       ┆ ry        ┆ ry        ┆ ry        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ry       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832824.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832825.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832826.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832827.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832828.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENST00000 ┆ UP        ┆ DOWN      ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ DOWN     │
│ 797950.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 819228.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 819229.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UP        ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 751368.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 839853.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# HNscore_classification.write_csv(
#     "../../out/figshare/HNscore/HNratio_categorized_2.tsv.gz",
#     separator="\t",
#     compression="gzip",
#     compression_level=9
# )

&nbsp;

&nbsp;

## 2. HN-score file (no caluculation list)

In [11]:
HNscore_no_calculation = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/transcript_with_no_HNscore.tsv",
    separator="\t",
    n_threads=16
)

display(HNscore_no_calculation)

shape: (16_702, 2)
┌───────────────────┬───────────────────┐
│ transcript_id     ┆ gene_id           │
│ ---               ┆ ---               │
│ str               ┆ str               │
╞═══════════════════╪═══════════════════╡
│ ENST00000612080.1 ┆ ENSG00000273874.1 │
│ ENST00000614007.1 ┆ ENSG00000278757.1 │
│ ENST00000332831.5 ┆ ENSG00000284662.2 │
│ ENST00000377898.4 ┆ ENSG00000173673.9 │
│ ENST00000384780.1 ┆ ENSG00000207511.1 │
│ …                 ┆ …                 │
│ ENST00000797714.1 ┆ ENSG00000303867.1 │
│ ENST00000797716.1 ┆ ENSG00000303867.1 │
│ ENST00000797721.1 ┆ ENSG00000303867.1 │
│ ENST00000797957.1 ┆ ENSG00000303902.1 │
│ ENST00000797959.1 ┆ ENSG00000303902.1 │
└───────────────────┴───────────────────┘

In [ ]:
# HNscore_no_calculation.write_csv(
#     "../../out/figshare/HNscore/transcript_with_no_HNscore.tsv",
#     separator="\t"
# )

&nbsp;

&nbsp;

&nbsp;

## 3. up5p transcript list

In [13]:
up5p = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HN2_top5p_transcripts_annotation_261001.tsv",
    separator="\t",
    n_threads=16
)

display(up5p)

shape: (26_354, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ …          ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ i64         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ MANE_select ┆ 1           ┆ MANE_selec ┆ protein_co │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆ t          ┆ ding       │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ alternative ┆ 3           ┆ Other      ┆ protein_co │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ 5' UTR,     ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ inferred t… ┆             ┆            ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ 0           ┆ no         ┆ protein_co │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ non         ┆ 1           ┆ Other      ┆ others     │
│ 0260.1      ┆     ┆       ┆            ┆   ┆ canonical   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ TEC         ┆             ┆            ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ intropolis_ ┆ 4           ┆ Other      ┆ protein_co │
│ 6231.2      ┆     ┆       ┆            ┆   ┆ filtered,   ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ Snaptron_…  ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000037 ┆ 112 ┆ 68    ┆ 226        ┆ … ┆ MANE_select ┆ 3           ┆ MANE_selec ┆ protein_co │
│ 7777.6      ┆     ┆       ┆            ┆   ┆ , novel     ┆             ┆ t          ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ histone 2B  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ …           ┆             ┆            ┆            │
│ ENST0000043 ┆ 71  ┆ 27    ┆ 308        ┆ … ┆ phosphoribo ┆ 1           ┆ Other      ┆ others     │
│ 0496.1      ┆     ┆       ┆            ┆   ┆ syl pyropho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ sphate s…   ┆             ┆            ┆            │
│ ENST0000048 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0008.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# up5p.write_csv(
#     "../../out/figshare/HNscore/HN2_top5p_transcripts_annotation_261001.tsv",
#     separator="\t"
# )

&nbsp;

&nbsp;

&nbsp;

## down5p

In [15]:
down5p = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HN2_bottom5p_transcripts_annotation_261001.tsv",
    separator="\t",
    n_threads=16
)

display(down5p)

shape: (26_643, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ …          ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ i64         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000053 ┆ 84  ┆ 132   ┆ 190        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 5641.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000094 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ ENCODE_tiss ┆ 1           ┆ Other      ┆ protein_co │
│ 3010.1      ┆     ┆       ┆            ┆   ┆ ue          ┆             ┆            ┆ ding       │
│ ENST0000051 ┆ 64  ┆ 112   ┆ 230        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0365.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000082 ┆ 85  ┆ 133   ┆ 188        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9178.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0762.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 6094.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ RNA-Seq     ┆ 1           ┆ Other      ┆ others     │
│ 0179.2      ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ partial     ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [ ]:
# down5p.write_csv(
#     "../../out/figshare/HNscore/HN2_bottom5p_transcripts_annotation_261001.tsv",
#     separator="\t"
# )