&nbsp;

# Metadata Integration and Visualization

- 様々な公共データベースから取得したデータを統合する

In [1]:
import os
import datetime
import pathlib
# import numpy as np
# import pandas as pd
import polars as pl
import plotly.express as px

from IPython.display import display

pl.Config.set_tbl_rows(6)
pl.Config.set_fmt_str_lengths(500)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
Execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {Execute_date}")

# create directory
pathlib.Path(f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 0. HN-score Table Integration

- 収集した全てのデータから算出した HN-score と、`stranded` と判定したデータのみから算出した HN-score を統合する

In [3]:
count_all = pl.read_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/HNscore_gencode_human_261001_HN2_transcript_all.tsv",
    separator="\t"
).with_columns(
    # Add temporary key for RNAcentral join
    pl.col("transcript_id").str.replace(r"\.\d+$", "").alias("transcript_id_no_version")
)

display(count_all)

shape: (517_038, 8)
┌────────────────┬─────┬───────┬────────────┬──────┬───────────────┬───────────────┬───────────────┐
│ transcript_id  ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ HN2  ┆ UPcount+1 /   ┆ log2(UPcount+ ┆ transcript_id │
│ ---            ┆ --- ┆ ---   ┆ ---        ┆ ---  ┆ DOWNcount+1 2 ┆ 1 /           ┆ _no_version   │
│ str            ┆ i64 ┆ i64   ┆ i64        ┆ i64  ┆ ---           ┆ DOWNcount+1)  ┆ ---           │
│                ┆     ┆       ┆            ┆      ┆ f64           ┆ 2             ┆ str           │
│                ┆     ┆       ┆            ┆      ┆               ┆ ---           ┆               │
│                ┆     ┆       ┆            ┆      ┆               ┆ f64           ┆               │
╞════════════════╪═════╪═══════╪════════════╪══════╪═══════════════╪═══════════════╪═══════════════╡
│ ENST0000030975 ┆ 352 ┆ 17    ┆ 37         ┆ 335  ┆ 19.611111     ┆ 4.293599      ┆ ENST000003097 │
│ 8.6            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 58            │
│ ENST0000067922 ┆ 338 ┆ 8     ┆ 60         ┆ 330  ┆ 37.666667     ┆ 5.235216      ┆ ENST000006792 │
│ 3.2            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 23            │
│ ENST0000045074 ┆ 335 ┆ 13    ┆ 58         ┆ 322  ┆ 24.0          ┆ 4.584963      ┆ ENST000004507 │
│ 4.1            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 44            │
│ …              ┆ …   ┆ …     ┆ …          ┆ …    ┆ …             ┆ …             ┆ …             │
│ ENST0000054954 ┆ 11  ┆ 265   ┆ 130        ┆ -254 ┆ 0.045113      ┆ -4.47032      ┆ ENST000005495 │
│ 5.1            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 45            │
│ ENST0000042609 ┆ 11  ┆ 265   ┆ 130        ┆ -254 ┆ 0.045113      ┆ -4.47032      ┆ ENST000004260 │
│ 4.5            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 94            │
│ ENST0000056017 ┆ 11  ┆ 272   ┆ 123        ┆ -261 ┆ 0.043956      ┆ -4.507795     ┆ ENST000005601 │
│ 9.2            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 79            │
└────────────────┴─────┴───────┴────────────┴──────┴───────────────┴───────────────┴───────────────┘

In [4]:
count_stranded = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/HNscore_gencode_human_261001_HN2_transcript_all_stranded.tsv",
    separator="\t",
    n_threads=16
).with_columns(
    # Add temporary key for RNAcentral join
    pl.col("transcript_id").str.replace(r"\.\d+$", "").alias("transcript_id_no_version")
)

display(count_stranded)

shape: (517_038, 8)
┌────────────────┬─────┬───────┬────────────┬──────┬───────────────┬───────────────┬───────────────┐
│ transcript_id  ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ HN2  ┆ UPcount+1 /   ┆ log2(UPcount+ ┆ transcript_id │
│ ---            ┆ --- ┆ ---   ┆ ---        ┆ ---  ┆ DOWNcount+1 2 ┆ 1 /           ┆ _no_version   │
│ str            ┆ i64 ┆ i64   ┆ i64        ┆ i64  ┆ ---           ┆ DOWNcount+1)  ┆ ---           │
│                ┆     ┆       ┆            ┆      ┆ f64           ┆ 2             ┆ str           │
│                ┆     ┆       ┆            ┆      ┆               ┆ ---           ┆               │
│                ┆     ┆       ┆            ┆      ┆               ┆ f64           ┆               │
╞════════════════╪═════╪═══════╪════════════╪══════╪═══════════════╪═══════════════╪═══════════════╡
│ ENST0000030975 ┆ 232 ┆ 4     ┆ 15         ┆ 228  ┆ 46.6          ┆ 5.542258      ┆ ENST000003097 │
│ 8.6            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 58            │
│ ENST0000067922 ┆ 222 ┆ 1     ┆ 28         ┆ 221  ┆ 111.5         ┆ 6.8009        ┆ ENST000006792 │
│ 3.2            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 23            │
│ ENST0000045074 ┆ 223 ┆ 4     ┆ 24         ┆ 219  ┆ 44.8          ┆ 5.485427      ┆ ENST000004507 │
│ 4.1            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 44            │
│ …              ┆ …   ┆ …     ┆ …          ┆ …    ┆ …             ┆ …             ┆ …             │
│ ENST0000029923 ┆ 8   ┆ 181   ┆ 62         ┆ -173 ┆ 0.049451      ┆ -4.33787      ┆ ENST000002992 │
│ 8.7            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 38            │
│ ENST0000063892 ┆ 8   ┆ 183   ┆ 60         ┆ -175 ┆ 0.048913      ┆ -4.353637     ┆ ENST000006389 │
│ 9.1            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 29            │
│ ENST0000056017 ┆ 5   ┆ 181   ┆ 65         ┆ -176 ┆ 0.032967      ┆ -4.922832     ┆ ENST000005601 │
│ 9.2            ┆     ┆       ┆            ┆      ┆               ┆               ┆ 79            │
└────────────────┴─────┴───────┴────────────┴──────┴───────────────┴───────────────┴───────────────┘

In [5]:
count_integration = count_all.join(
    count_stranded,
    on=["transcript_id", "transcript_id_no_version"],
    how="inner",
    suffix="_stranded"
).select(
    "transcript_id",
    "UP2",
    "DOWN2",
    "UNCHANGED2",
    "HN2",
    "UPcount+1 / DOWNcount+1 2",
    "log2(UPcount+1 / DOWNcount+1) 2",
    "UP2_stranded",
    "DOWN2_stranded",
    "UNCHANGED2_stranded",
    "HN2_stranded",
    "UPcount+1 / DOWNcount+1 2_stranded",
    "log2(UPcount+1 / DOWNcount+1) 2_stranded",
    "transcript_id_no_version"
)

count_integration.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/HNscore_gencode_human_{Execute_date}_HN2_transcript_all_integration.tsv",
    separator="\t"
)

display(count_integration)

shape: (517_038, 14)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ HN2_strande ┆ UPcount+1 / ┆ log2(UPcou ┆ transcript │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ d           ┆ DOWNcount+1 ┆ nt+1 / DOW ┆ _id_no_ver │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ 2_stranded  ┆ Ncount+1)  ┆ sion       │
│ str         ┆     ┆       ┆            ┆   ┆ i64         ┆ ---         ┆ 2_stranded ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ f64         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ f64        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ 228         ┆ 46.6        ┆ 5.542258   ┆ ENST000003 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 09758      │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ 221         ┆ 111.5       ┆ 6.8009     ┆ ENST000006 │
│ 9223.2      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 79223      │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ 219         ┆ 44.8        ┆ 5.485427   ┆ ENST000004 │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 50744      │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000029 ┆ 9   ┆ 245   ┆ 152        ┆ … ┆ -173        ┆ 0.049451    ┆ -4.33787   ┆ ENST000002 │
│ 9238.7      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 99238      │
│ ENST0000063 ┆ 18  ┆ 259   ┆ 129        ┆ … ┆ -175        ┆ 0.048913    ┆ -4.353637  ┆ ENST000006 │
│ 8929.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 38929      │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ -176        ┆ 0.032967    ┆ -4.922832  ┆ ENST000005 │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 60179      │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

# Add Meta-data

## 1. GENCODE metadata

&nbsp;

&nbsp;

## 1-1. transcript - gene correspondence

In [6]:
# using ../Tools/06_pytximport_tx2gene.cwl to get tx2gene from gencode.v49.chr_patch_hapl_scaff.annotation.gtf file

tx2gene = pl.read_csv(
    "../../Data/Database/GENCODE_v49/gencode_v49_tx2gene_chr_patch_hapl_scaff_v260909.tsv",
    separator="\t",
    n_threads=16
)

pl.Config.set_tbl_rows(4)
display(tx2gene)

shape: (533_740, 2)
┌───────────────────┬───────────────────┐
│ transcript_id     ┆ gene_id           │
│ ---               ┆ ---               │
│ str               ┆ str               │
╞═══════════════════╪═══════════════════╡
│ ENST00000832824.1 ┆ ENSG00000290825.2 │
│ ENST00000832825.1 ┆ ENSG00000290825.2 │
│ …                 ┆ …                 │
│ ENST00000751368.1 ┆ ENSG00000297844.1 │
│ ENST00000839853.1 ┆ ENSG00000309258.1 │
└───────────────────┴───────────────────┘

&nbsp;

&nbsp;

&nbsp;

## 1-2. transcript type retrieved from [gencode.v49.chr_patch_hapl_scaff.annotation.gtf](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.chr_patch_hapl_scaff.annotation.gtf.gz)

- (2026-09-04) strand 情報をここで統合することにした
- (2026-09-08) [tags](https://www.gencodegenes.org/pages/tags.html) のデータもGTFファイルから取得することにした

In [7]:
# For more information, see https://www.gencodegenes.org/pages/biotypes.html
tx2type = pl.read_csv(
    "../../Data/Database/GENCODE_v49/gencode.v49.chr_patch_hapl_scaff.annotation.gtf",
    separator='\t',
    has_header=False,
    comment_prefix='#',
    new_columns=['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attributes'],
    n_threads=16
).filter(
    pl.col('feature') == 'transcript'
).with_columns(
    # Unique keys: extract the first (and only) quoted value
    pl.col("attributes").str.extract(r'gene_id "([^"]+)"', 1).alias("gene_id"),
    pl.col("attributes").str.extract(r'transcript_id "([^"]+)"', 1).alias("transcript_id"),
    pl.col("attributes").str.extract(r'transcript_type "([^"]+)"', 1).alias("transcript_type"),
    # tag can appear multiple times; extract_all returns full matches like tag "basic"
    pl.col("attributes")
        .str.extract_all(r'tag "[^"]+"')
        .list.eval(pl.element().str.extract(r'"([^"]+)"', 1))
        .alias("tags")
).select([
    pl.col("transcript_id"),
    pl.col("transcript_type"),
    pl.col("gene_id"),
    pl.col("tags"),
    pl.col("strand")
]).with_columns(
    pl.col("tags").list.n_unique().alias("number_of_tags")
).unique(
    subset=["transcript_id", "transcript_type", "gene_id", "tags", "number_of_tags", "strand"]
).join(
    # きちんと transcript_id と gene_id の対応が保持されているかを確認する
    tx2gene,
    on=["transcript_id", "gene_id"],
    how="inner"
)

display(tx2type)

shape: (533_740, 6)
┌──────────────────┬─────────────────┬─────────────────┬─────────────────┬────────┬────────────────┐
│ transcript_id    ┆ transcript_type ┆ gene_id         ┆ tags            ┆ strand ┆ number_of_tags │
│ ---              ┆ ---             ┆ ---             ┆ ---             ┆ ---    ┆ ---            │
│ str              ┆ str             ┆ str             ┆ list[str]       ┆ str    ┆ u32            │
╞══════════════════╪═════════════════╪═════════════════╪═════════════════╪════════╪════════════════╡
│ ENST00000832824. ┆ lncRNA          ┆ ENSG00000290825 ┆ ["TAGENE"]      ┆ +      ┆ 1              │
│ 1                ┆                 ┆ .2              ┆                 ┆        ┆                │
│ ENST00000832825. ┆ lncRNA          ┆ ENSG00000290825 ┆ ["TAGENE"]      ┆ +      ┆ 1              │
│ 1                ┆                 ┆ .2              ┆                 ┆        ┆                │
│ …                ┆ …               ┆ …               ┆ …               ┆ …      ┆ …              │
│ ENST00000751368. ┆ lncRNA          ┆ ENSG00000297844 ┆ ["basic", "Ense ┆ +      ┆ 4              │
│ 1                ┆                 ┆ .1              ┆ mbl_canonical", ┆        ┆                │
│                  ┆                 ┆                 ┆ … "TAGENE"]     ┆        ┆                │
│ ENST00000839853. ┆ lncRNA          ┆ ENSG00000309258 ┆ ["basic", "Ense ┆ +      ┆ 4              │
│ 1                ┆                 ┆ .1              ┆ mbl_canonical", ┆        ┆                │
│                  ┆                 ┆                 ┆ … "TAGENE"]     ┆        ┆                │
└──────────────────┴─────────────────┴─────────────────┴─────────────────┴────────┴────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1-3. GENCODE promoter windows (v48)

- ~~(2026-09-04) このメタデータには、GENCODE の promoter 情報は統合しないことにした~~
- (2026-09-08) 後続の解析である `fanta.bio`における promoter の証拠としても使用できるため、統合する
- (2026-09-08) `fanta.bio`の BEDファイルと後で `bedtools intersect` しておくので、BEDファイルを作成しておく
- → `gffread` では、どうやら [gencode.v48.promoter_windows.gff3.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/gencode.v48.promoter_windows.gff3.gz) の feature の タイプ名のところが Sequence Ontology Feature Annotation (SOFA) に該当しない？ ため、うまく変換できないので、データフレームとして操作して変換する
- [../02_fantabio/02_5_ensembl_promoter_intersect.ipynb](../02_fantabio/02_5_ensembl_promoter_intersect.ipynb)に処理を移動
- https://www.gencodegenes.org/pages/promoter_windows/
- [gencode.v48.promoter_windows.gff3.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/gencode.v48.promoter_windows.gff3.gz)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1−4. annotation remark 

- [ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Annotation_remark.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Annotation_remark.gz)

In [8]:
annotation_remark = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.Annotation_remark.gz",
    separator="\t",
    has_header=False,
    n_threads=16,
    new_columns=[
        "transcript_id",
        "annotation_remark"
    ],
    quote_char=None,
    infer_schema=False,
    ignore_errors=True
).sort(
    by="transcript_id",
    descending=False
).group_by(
    "transcript_id"
).agg(
    pl.col("annotation_remark").alias("annotation_remarks"),
    pl.col("annotation_remark").count().fill_null(0).alias("annotation_remark_count")
)

display(annotation_remark)

shape: (388_763, 3)
┌───────────────────┬────────────────────┬─────────────────────────┐
│ transcript_id     ┆ annotation_remarks ┆ annotation_remark_count │
│ ---               ┆ ---                ┆ ---                     │
│ str               ┆ list[str]          ┆ u32                     │
╞═══════════════════╪════════════════════╪═════════════════════════╡
│ ENST00000920101.1 ┆ ["LRGASP"]         ┆ 1                       │
│ ENST00000783444.1 ┆ ["CLS3 project"]   ┆ 1                       │
│ …                 ┆ …                  ┆ …                       │
│ ENST00000834112.1 ┆ ["CLS3 project"]   ┆ 1                       │
│ ENST00000885842.1 ┆ ["DanaFarber"]     ┆ 1                       │
└───────────────────┴────────────────────┴─────────────────────────┘

In [9]:
annotation_remark_list = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.Annotation_remark.gz",
    separator="\t",
    has_header=False,
    n_threads=16,
    new_columns=[
        "transcript_id",
        "annotation_remark"
    ],
    quote_char=None,
    infer_schema=False,
    ignore_errors=True
).sort(
    by="transcript_id",
    descending=False
).select(
    "annotation_remark"
).group_by(
    "annotation_remark"
).agg(
    pl.col("annotation_remark").count().alias("annotation_remark_count")
).sort(
    by="annotation_remark_count",
    descending=True
)

annotation_remark_list.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/gencode.v49.metadata.Annotation_remark_list.tsv",
    separator="\t"
)

pl.Config.set_tbl_rows(4)
display(annotation_remark_list)

shape: (12_843, 2)
┌──────────────────────────────────────┬─────────────────────────┐
│ annotation_remark                    ┆ annotation_remark_count │
│ ---                                  ┆ ---                     │
│ str                                  ┆ u32                     │
╞══════════════════════════════════════╪═════════════════════════╡
│ CLS3 project                         ┆ 146072                  │
│ DanaFarber                           ┆ 60225                   │
│ …                                    ┆ …                       │
│ H2B histone family, member K (H2B/k) ┆ 1                       │
│ IGLV3-10*01, V2-7                    ┆ 1                       │
└──────────────────────────────────────┴─────────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1−5. Transcript supporting feature

- [ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Transcript_supporting_feature.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Transcript_supporting_feature.gz)

In [10]:
# # Piece of evidence used in the annotation of the transcript (GENCODE v49)
# transcript_support_feature = pl.read_csv(
#     "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.Transcript_supporting_feature.gz",
#     separator="\t",
#     has_header=False,
#     n_threads=16,
#     new_columns=[
#         "transcript_id",
#         "transcript_support_id",
#         "transcript_annotation_evidence"
#     ]
# ).group_by(
#     "transcript_id"
# ).agg(
#     pl.col("transcript_support_id").alias("transcript_support_ids"),
#     pl.col("transcript_annotation_evidence").alias("transcript_annotation_evidences")
# )

# pl.Config.set_tbl_rows(4)
# display(transcript_support_feature)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1−6. Gene Source

- [ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Gene_source.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.Gene_source.gz)

In [11]:
gene_source = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.Gene_source.gz",
    separator="\t",
    has_header=False,
    n_threads=16,
    new_columns=[
        "gene_id",
        "gene_source"
    ]
)

display(gene_source)

shape: (86_369, 2)
┌────────────────────┬──────────────────────────────────┐
│ gene_id            ┆ gene_source                      │
│ ---                ┆ ---                              │
│ str                ┆ str                              │
╞════════════════════╪══════════════════════════════════╡
│ ENSG00000142611.17 ┆ ensembl_havana_gene_homo_sapiens │
│ ENSG00000284616.1  ┆ havana_homo_sapiens              │
│ …                  ┆ …                                │
│ ENSG00000297844.1  ┆ havana_tagene_homo_sapiens       │
│ ENSG00000309258.1  ┆ havana_tagene_homo_sapiens       │
└────────────────────┴──────────────────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1−7. HGNC symbol

- [ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.HGNC.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.HGNC.gz)

In [12]:
tx2symbol = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.HGNC.gz",
    separator="\t",
    has_header=False,
    n_threads=16,
    new_columns=[
        "transcript_id",
        "gene_symbol",
        "HGNC_ID"
    ]
)

display(tx2symbol)

shape: (412_781, 3)
┌───────────────────┬─────────────┬────────────┐
│ transcript_id     ┆ gene_symbol ┆ HGNC_ID    │
│ ---               ┆ ---         ┆ ---        │
│ str               ┆ str         ┆ str        │
╞═══════════════════╪═════════════╪════════════╡
│ ENST00000511072.5 ┆ PRDM16      ┆ HGNC:14000 │
│ ENST00000607632.1 ┆ PRDM16      ┆ HGNC:14000 │
│ …                 ┆ …           ┆ …          │
│ ENST00000611446.1 ┆ RNA5-8SN5   ┆ HGNC:53533 │
│ ENST00000616292.1 ┆ RNA5-8SN4   ┆ HGNC:53529 │
└───────────────────┴─────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## 1−8. poly-A feature

- 詳細な場所ではなく、poly-A position が GENCODE でアノテーションされているflagとして使用
- [ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.PolyA_feature.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.metadata.PolyA_feature.gz)

In [13]:
polyA_feature = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v49.metadata.PolyA_feature.gz",
    separator="\t",
    has_header=False,
    n_threads=16
).select(
    "column_1",
    "column_8"
).rename(
    {
        "column_1": "transcript_id",
        "column_8": "polyA_feature"
    }
).unique().group_by(
    "transcript_id"
).agg(
    pl.col("polyA_feature").alias("polyA_features")
)

display(polyA_feature)

shape: (94_746, 2)
┌───────────────────┬────────────────────────────────┐
│ transcript_id     ┆ polyA_features                 │
│ ---               ┆ ---                            │
│ str               ┆ list[str]                      │
╞═══════════════════╪════════════════════════════════╡
│ ENST00000484161.5 ┆ ["polya_site", "polya_signal"] │
│ ENST00000955461.1 ┆ ["polya_signal", "polya_site"] │
│ …                 ┆ …                              │
│ ENST00000360506.6 ┆ ["polya_signal", "polya_site"] │
│ ENST00000895099.1 ┆ ["polya_site"]                 │
└───────────────────┴────────────────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. RNACentral ID correspondence (for lncRNA information)

- RNACentral release 27 からダウンロード (2026-10-01 access)
- https://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/27.0/id_mapping/database_mappings/ensembl_gencode.tsv
- transcript id は、バージョンがない状態でなければ結合できないことに注意！

In [14]:
# caution: transcript id is not versioned !
# curl -O https://ftp.ebi.ac.uk/pub/databases/RNAcentral/releases/27.0/id_mapping/database_mappings/ensembl_gencode.tsv (2026-10-01)
rnacentral_id = pl.read_csv(
    "../../Data/Database/RNACentral/release27/database_mapping/ensembl_gencode.tsv",
    separator="\t",
    has_header=False,
    n_threads=16
).rename(
    {
        "column_1": "RNACentral_ID",
        "column_2": "corrrespondence",
        "column_3": "transcript_id_no_version",
        "column_4": "taxonomy_id",
        "column_5": "transcript_type",
        "column_6": "gene_id"
    }
).filter(
    pl.col("taxonomy_id") == 9606
).select(
    "RNACentral_ID",
    "corrrespondence",
    "transcript_id_no_version"
).unique()

display(rnacentral_id)

shape: (182_408, 3)
┌───────────────┬─────────────────┬──────────────────────────┐
│ RNACentral_ID ┆ corrrespondence ┆ transcript_id_no_version │
│ ---           ┆ ---             ┆ ---                      │
│ str           ┆ str             ┆ str                      │
╞═══════════════╪═════════════════╪══════════════════════════╡
│ URS0002A322D2 ┆ ENSEMBL_GENCODE ┆ ENST00000842269          │
│ URS0002A6B04F ┆ ENSEMBL_GENCODE ┆ ENST00000570344          │
│ …             ┆ …               ┆ …                        │
│ URS0002A50320 ┆ ENSEMBL_GENCODE ┆ ENST00000725801          │
│ URS000055A804 ┆ ENSEMBL_GENCODE ┆ ENST00000446022          │
└───────────────┴─────────────────┴──────────────────────────┘

&nbsp;

&nbsp;

## JOIN

- これまでに収集したメタデータを全て `join`
- `salmon` の index 作成時に 短すぎて 発現定量できていない transcript はここで落ちている

In [15]:
HNscore_add_metadata = count_integration.join(
    tx2symbol,
    on="transcript_id",
    how="left"
).join(
    tx2type,
    on="transcript_id",
    how="left"
).join(
    rnacentral_id,
    on="transcript_id_no_version", # caution: transcript id is not versioned !
    how="left"
).join(
    polyA_feature,
    on="transcript_id",
    how="left"
).join(
    gene_source,
    on="gene_id",
    how="left"
).drop(
    "UPcount+1 / DOWNcount+1 2",
    "UPcount+1 / DOWNcount+1 2_stranded",
    "log2(UPcount+1 / DOWNcount+1) 2",
    "log2(UPcount+1 / DOWNcount+1) 2_stranded"
).join(
    annotation_remark,
    on="transcript_id",
    how="left"
).with_columns([
    pl.col("annotation_remark_count").fill_null(0)
]).sort(
    by="HN2",
    descending=True
).drop(
    "transcript_id_no_version"
)

pl.Config.set_tbl_rows(20)
display(HNscore_add_metadata)

shape: (517_038, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ null        ┆ ensembl_hav ┆ ["MANE_sel ┆ 1          │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ ect"]      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ ["alternat ┆ 3          │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ e"]         ┆ ana_gene_ho ┆ ive 5'     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ UTR",      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "inferred  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ transcript ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ model",    ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "RNA-Seq   ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ null        ┆ ensembl_hav ┆ ["non      ┆ 1          │
│ 0260.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ canonical  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ TEC"]      ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ null        ┆ ensembl_hav ┆ ["intropol ┆ 4          │
│ 6231.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ is_filtere ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ d", "Snapt ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ ron_GTEX", ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ … "RNA-Seq ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000040 ┆ 334 ┆ 17    ┆ 55         ┆ … ┆ null        ┆ ensembl_hav ┆ ["not orga ┆ 1          │
│ 1903.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ nism-suppo ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ rted"]     ┆            │
│ ENST0000095 ┆ 328 ┆ 14    ┆ 64         ┆ … ┆ null        ┆ ensembl_hav ┆ ["ENCODE_t ┆ 1          │
│ 4442.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ issue"]    ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000055 ┆ 329 ┆ 18    ┆ 59         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 5662.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000085 ┆ 317 ┆ 6     ┆ 83         ┆ … ┆ null        ┆ havana_tage ┆ ["CLS3     ┆ 2          │
│ 0140.1      ┆     ┆       ┆            ┆   ┆             ┆ ne_homo_sap ┆ project",  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ iens        ┆ "overlaps  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ pseudogene ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "]         ┆            │
│ ENST0000055 ┆ 326 ┆ 16    ┆ 64         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 8243.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000055 ┆ 17  ┆ 264   ┆ 125        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9522.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000041 ┆ 21  ┆ 268   ┆ 117        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 3097.6      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000047 ┆ 16  ┆ 264   ┆ 126        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 4699.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000052 ┆ 17  ┆ 268   ┆ 121        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 4291.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000054 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0567.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0762.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ ensembl_hav ┆ ["RNA-Seq  ┆ 1          │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ partial"]  ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [16]:
threshold = 2

In [17]:
HNscore_add_metadata.write_parquet(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/HNscore_gencode_human_{Execute_date}_HN{threshold}_transcript_all_gencode_annotation.parquet"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Filtered Transcripts with no HN-score

In [18]:
transcript_with_no_HNscore = tx2gene.join(
    count_integration.select("transcript_id"),
    on="transcript_id",
    how="anti",
)

transcript_with_no_HNscore.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/transcript_with_no_HNscore.tsv",
    separator="\t"
)

display(transcript_with_no_HNscore)

shape: (16_702, 2)
┌───────────────────┬────────────────────┐
│ transcript_id     ┆ gene_id            │
│ ---               ┆ ---                │
│ str               ┆ str                │
╞═══════════════════╪════════════════════╡
│ ENST00000612080.1 ┆ ENSG00000273874.1  │
│ ENST00000614007.1 ┆ ENSG00000278757.1  │
│ ENST00000332831.5 ┆ ENSG00000284662.2  │
│ ENST00000377898.4 ┆ ENSG00000173673.9  │
│ ENST00000384780.1 ┆ ENSG00000207511.1  │
│ ENST00000384782.1 ┆ ENSG00000207513.1  │
│ ENST00000849135.1 ┆ ENSG00000282740.2  │
│ ENST00000384659.1 ┆ ENSG00000207389.1  │
│ ENST00000384278.1 ┆ ENSG00000207005.1  │
│ ENST00000674426.1 ┆ ENSG00000092847.15 │
│ …                 ┆ …                  │
│ ENST00000797665.1 ┆ ENSG00000303867.1  │
│ ENST00000797673.1 ┆ ENSG00000303867.1  │
│ ENST00000797682.1 ┆ ENSG00000303867.1  │
│ ENST00000797692.1 ┆ ENSG00000303867.1  │
│ ENST00000797696.1 ┆ ENSG00000303867.1  │
│ ENST00000797714.1 ┆ ENSG00000303867.1  │
│ ENST00000797716.1 ┆ ENSG00000303867.1  │
│ ENST00000797721.1 ┆ ENSG00000303867.1  │
│ ENST00000797957.1 ┆ ENSG00000303902.1  │
│ ENST00000797959.1 ┆ ENSG00000303902.1  │
└───────────────────┴────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Assign the Original Flags

In [19]:
HNscore_add_metadata_with_score = HNscore_add_metadata.filter(
    pl.col(f"HN{threshold}").is_not_null()
).with_columns([
    pl.col("annotation_remarks").list.join(", ").alias("annotation_remarks"),
    pl.col("polyA_features").list.join(", ").alias("polyA_features"),
    pl.col("tags").list.join(", ").alias("tags")
]).with_columns( # For pie chart
    pl.when(
        pl.col("annotation_remarks").str.contains("CLS3 project") |
        pl.col("annotation_remarks").str.contains("Assembled from PacBio CLS3 reads")
    ).then(pl.lit("derived from CLS3 project"))
    .when(
        pl.col("annotation_remarks").str.contains("MANE_select")
    ).then(pl.lit("MANE_select"))
    .when(
        pl.col("annotation_remarks").str.contains("LRGASP")
    ).then(pl.lit("derived from LRGASP"))
    .when(
        pl.col("annotation_remarks").is_null()
    ).then(pl.lit("no annotation remark"))
    .otherwise(pl.lit("Other"))
    .alias("representative_annotation_remarks")
).with_columns(
    pl.when(
        (pl.col("transcript_type") == "protein_coding") 
    ).then(pl.lit("protein_coding"))

    .when( # For more information, see https://www.gencodegenes.org/pages/biotypes.html
        (pl.col("transcript_type") == "lncRNA") |
        (pl.col("transcript_type") == "bidirectional_promoter_lncRNA") |
        (pl.col("transcript_type") == "macro_lncRNA") |
        (pl.col("transcript_type") == "lincRNA")
    ).then(pl.lit("lncRNA"))
    .otherwise(pl.lit("others"))
    .alias("representative_transcript_type")
)

HNscore_add_metadata_with_score.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/HNscore_gencode_human_{Execute_date}_HN{threshold}_transcript_all_gencode_annotation.tsv",
    separator="\t"
)

pl.Config.set_tbl_rows(10)
# print(HNscore_add_metadata_with_score.select("transcript_type").unique())
display(HNscore_add_metadata_with_score)

shape: (517_038, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ u32         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ MANE_select ┆ 1           ┆ MANE_selec ┆ protein_co │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆ t          ┆ ding       │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ alternative ┆ 3           ┆ Other      ┆ protein_co │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ 5' UTR,     ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ inferred    ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ transcript  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ model,      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ RNA-Seq     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ only        ┆             ┆            ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ 0           ┆ no         ┆ protein_co │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ non         ┆ 1           ┆ Other      ┆ others     │
│ 0260.1      ┆     ┆       ┆            ┆   ┆ canonical   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ TEC         ┆             ┆            ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ intropolis_ ┆ 4           ┆ Other      ┆ protein_co │
│ 6231.2      ┆     ┆       ┆            ┆   ┆ filtered,   ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ Snaptron_GT ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ EX,         ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ inferred    ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ exon combin ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ ation,      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ RNA-Seq     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ only        ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0762.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 6094.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ RNA-Seq     ┆ 1           ┆ Other      ┆ others     │
│ 0179.2      ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ partial     ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Upregulated Gene Groups

- データが多すぎて`join`が難しいので、選抜してから行う

In [20]:
top5_genes_list = pl.read_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/HN{threshold}_top_5_percent_transcripts.tsv",
    separator="\t"
)

# Use semi join to filter rows where transcript_id exists in top1_genes_list
top5_genes = HNscore_add_metadata_with_score.join(
    top5_genes_list.select("transcript_id"),
    on="transcript_id",
    how="semi" # Returns rows from the left table that have a match in the right table.
)

top5_genes.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/HN{threshold}_top5p_transcripts_annotation_{Execute_date}.tsv",
    separator="\t"
)

display(top5_genes)

shape: (26_354, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ u32         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ MANE_select ┆ 1           ┆ MANE_selec ┆ protein_co │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆ t          ┆ ding       │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ alternative ┆ 3           ┆ Other      ┆ protein_co │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ 5' UTR,     ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ inferred    ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ transcript  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ model,      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ RNA-Seq     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ only        ┆             ┆            ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ 0           ┆ no         ┆ protein_co │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ non         ┆ 1           ┆ Other      ┆ others     │
│ 0260.1      ┆     ┆       ┆            ┆   ┆ canonical   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ TEC         ┆             ┆            ┆            │
│ ENST0000067 ┆ 324 ┆ 7     ┆ 75         ┆ … ┆ intropolis_ ┆ 4           ┆ Other      ┆ protein_co │
│ 6231.2      ┆     ┆       ┆            ┆   ┆ filtered,   ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ Snaptron_GT ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ EX,         ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ inferred    ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ exon combin ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ ation,      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ RNA-Seq     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ only        ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000037 ┆ 112 ┆ 68    ┆ 226        ┆ … ┆ MANE_select ┆ 3           ┆ MANE_selec ┆ protein_co │
│ 7777.6      ┆     ┆       ┆            ┆   ┆ , novel     ┆             ┆ t          ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ histone 2B  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ family      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ member,     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ variant 2,  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ alternative ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ ly spliced  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ in 3' UTR   ┆             ┆            ┆            │
│ ENST0000043 ┆ 71  ┆ 27    ┆ 308        ┆ … ┆ phosphoribo ┆ 1           ┆ Other      ┆ others     │
│ 0496.1      ┆     ┆       ┆            ┆   ┆ syl pyropho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ sphate      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ synthetase  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ 1 (PRPS1)   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ pseudogene  ┆             ┆            ┆            │
│ ENST0000048 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0008.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## Downregulated Gene Group

In [21]:
bottom5_genes_list = pl.read_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/HN{threshold}_bottom_5_percent_transcripts.tsv",
    separator="\t"
)

# Use semi join to filter rows where transcript_id exists in top1_genes_list
bottom5_genes = HNscore_add_metadata_with_score.join(
    bottom5_genes_list.select("transcript_id"),
    on="transcript_id",
    how="semi" # Returns rows from the left table that have a match in the right table.
)

bottom5_genes.write_csv(
    f"../../Data/HNscore/HNscore_transcript/HNscore_gencode_{VERSION}/annotation/HN{threshold}_bottom5p_transcripts_annotation_{Execute_date}.tsv",
    separator="\t"
)

display(bottom5_genes)

shape: (26_643, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ u32         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000053 ┆ 84  ┆ 132   ┆ 190        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 5641.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000094 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ ENCODE_tiss ┆ 1           ┆ Other      ┆ protein_co │
│ 3010.1      ┆     ┆       ┆            ┆   ┆ ue          ┆             ┆            ┆ ding       │
│ ENST0000051 ┆ 64  ┆ 112   ┆ 230        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0365.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000082 ┆ 85  ┆ 133   ┆ 188        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9178.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000049 ┆ 15  ┆ 266   ┆ 125        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 7231.7      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000049 ┆ 12  ┆ 265   ┆ 129        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0762.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 6094.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ RNA-Seq     ┆ 1           ┆ Other      ┆ others     │
│ 0179.2      ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ partial     ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Pie Chart (transcript category)

In [22]:
# Define custom colors for each gene category
transcript_category_colors = {
    'protein_coding': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'others': '#D3D3D3',  # LightGray (薄い灰色)
    'lncRNA': '#AB63FA'  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    # 'p-lncRNA, intergenic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    # 'e-lncRNA': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_up = (
    top5_genes
    .group_by("representative_transcript_type")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_up.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_transcript_type',
    title='Transcript Type Distribution (Upregulated genes)',
    color='representative_transcript_type',  # Add color parameter
    color_discrete_map=transcript_category_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()

In [23]:
# Define custom colors for each gene category
transcript_category_colors = {
    'protein_coding': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'others': '#D3D3D3',  # LightGray (薄い灰色)
    'lncRNA': '#AB63FA'  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    # 'p-lncRNA, intergenic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    # 'e-lncRNA': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_down = (
    bottom5_genes
    .group_by("representative_transcript_type")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_down.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_transcript_type',
    title='Transcript Type Distribution (Downregulated genes)',
    color='representative_transcript_type',  # Add color parameter
    color_discrete_map=transcript_category_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Pie Chart (lncRNA annotation remarks)

In [24]:
top5_genes_lncRNA = top5_genes.filter(
    pl.col("representative_transcript_type") == "lncRNA"
)

print(f"top5 lncRNA transcript count: {top5_genes_lncRNA.select('transcript_id').n_unique()}")
display(top5_genes_lncRNA)

top5 lncRNA transcript count: 4716

shape: (4_716, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ u32         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000085 ┆ 317 ┆ 6     ┆ 83         ┆ … ┆ CLS3        ┆ 2           ┆ derived    ┆ lncRNA     │
│ 0140.1      ┆     ┆       ┆            ┆   ┆ project,    ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆ overlaps    ┆             ┆ project    ┆            │
│             ┆     ┆       ┆            ┆   ┆ pseudogene  ┆             ┆            ┆            │
│ ENST0000073 ┆ 312 ┆ 9     ┆ 85         ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 8043.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000072 ┆ 315 ┆ 20    ┆ 71         ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9765.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000077 ┆ 306 ┆ 17    ┆ 83         ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 8743.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000057 ┆ 303 ┆ 19    ┆ 84         ┆ … ┆ null        ┆ 0           ┆ no         ┆ lncRNA     │
│ 0843.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000078 ┆ 87  ┆ 43    ┆ 276        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9046.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000054 ┆ 60  ┆ 16    ┆ 330        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 7282.2      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000080 ┆ 52  ┆ 8     ┆ 346        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 8863.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [25]:
bottom5_genes_lncRNA = bottom5_genes.filter(
    pl.col("representative_transcript_type") == "lncRNA"
)

print(f"bottom5 lncRNA transcript count: {bottom5_genes_lncRNA.select('transcript_id').n_unique()}")
display(bottom5_genes_lncRNA)

bottom5 lncRNA transcript count: 3223

shape: (3_223, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ u32         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000082 ┆ 85  ┆ 133   ┆ 188        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9178.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000052 ┆ 27  ┆ 75    ┆ 304        ┆ … ┆ null        ┆ 0           ┆ no         ┆ lncRNA     │
│ 4304.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000073 ┆ 68  ┆ 116   ┆ 222        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 9605.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000073 ┆ 45  ┆ 93    ┆ 268        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 0725.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000080 ┆ 35  ┆ 227   ┆ 144        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 3049.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000069 ┆ 12  ┆ 207   ┆ 187        ┆ … ┆ Assembled   ┆ 2           ┆ derived    ┆ lncRNA     │
│ 2499.2      ┆     ┆       ┆            ┆   ┆ from PacBio ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆ CLS3 reads, ┆             ┆ project    ┆            │
│             ┆     ┆       ┆            ┆   ┆ CLS3        ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ project     ┆             ┆            ┆            │
│ ENST0000061 ┆ 11  ┆ 209   ┆ 186        ┆ … ┆ CLS3        ┆ 2           ┆ derived    ┆ lncRNA     │
│ 9697.3      ┆     ┆       ┆            ┆   ┆ project,    ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆ Assembled   ┆             ┆ project    ┆            │
│             ┆     ┆       ┆            ┆   ┆ from PacBio ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ CLS3 reads  ┆             ┆            ┆            │
│ ENST0000079 ┆ 26  ┆ 226   ┆ 154        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 7527.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000044 ┆ 22  ┆ 237   ┆ 147        ┆ … ┆ CLS3        ┆ 2           ┆ derived    ┆ lncRNA     │
│ 6521.2      ┆     ┆       ┆            ┆   ┆ project,    ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆ readthrough ┆             ┆ project    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [26]:
# Define custom colors for each gene category
annotation_remark_colors = {
    'MANE_select': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'no annotation remark': '#D3D3D3',  # LightGray (薄い灰色)
    'derived from CLS3 project': '#AB63FA',  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    'derived from LRGASP': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    'Other': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_up = (
    top5_genes_lncRNA
    .group_by("representative_annotation_remarks")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_up.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_annotation_remarks',
    title='LncRNA Representative Annotation Remarks Distribution (Upregulated genes)',
    color='representative_annotation_remarks',  # Add color parameter
    color_discrete_map=annotation_remark_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()

In [27]:
# Define custom colors for each gene category
annotation_remark_colors = {
    'MANE_select': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'no annotation remark': '#D3D3D3',  # LightGray (薄い灰色)
    'derived from CLS3 project': '#AB63FA',  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    'derived from LRGASP': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    'Other': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_down = (
    bottom5_genes_lncRNA
    .group_by("representative_annotation_remarks")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_down.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_annotation_remarks',
    title='LncRNA Representative Annotation Remarks Distribution (Downregulated genes)',
    color='representative_annotation_remarks',  # Add color parameter
    color_discrete_map=annotation_remark_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()