&nbsp;

# HN-score Visualization Process

-

In [1]:
import os
import datetime
import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import polars as pl
import plotly.express as px

from matplotlib import rcParams
from IPython.display import display

pl.Config.set_tbl_rows(6)
pl.Config.set_fmt_str_lengths(500)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
Execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {Execute_date}")

Execute Date: 261024

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## HN-score All Table

In [3]:
HNscore_transcript = pl.read_parquet(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HNscore_gencode_human_261001_HN2_transcript_all_gencode_annotation.parquet"
)

display(HNscore_transcript)

shape: (517_038, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ null        ┆ ensembl_hav ┆ ["MANE_sel ┆ 1          │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ ect"]      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ ["alternat ┆ 3          │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ e"]         ┆ ana_gene_ho ┆ ive 5'     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ UTR",      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "inferred  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ transcript ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ model",    ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "RNA-Seq   ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ ensembl_hav ┆ ["RNA-Seq  ┆ 1          │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ partial"]  ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## up5p & down5p

- These datasets has no "tag" information derived from GTF file

In [4]:
up5p = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HN2_top5p_transcripts_annotation_261001.tsv",
    separator="\t"
)

down5p = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HN2_bottom5p_transcripts_annotation_261001.tsv",
    separator="\t"
)


display(up5p)
display(down5p)

shape: (26_354, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ i64         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ MANE_select ┆ 1           ┆ MANE_selec ┆ protein_co │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆             ┆ t          ┆ ding       │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ alternative ┆ 3           ┆ Other      ┆ protein_co │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ 5' UTR,     ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ inferred    ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ transcript  ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ model,      ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ RNA-Seq     ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ only        ┆             ┆            ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ 0           ┆ no         ┆ protein_co │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000048 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 0008.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

shape: (26_643, 24)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ annotation_ ┆ annotation_ ┆ representa ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ remarks     ┆ remark_coun ┆ tive_annot ┆ tive_trans │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ t           ┆ ation_rema ┆ cript_type │
│ str         ┆     ┆       ┆            ┆   ┆ str         ┆ ---         ┆ rks        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆ i64         ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ str        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000053 ┆ 84  ┆ 132   ┆ 190        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 5641.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ CLS3        ┆ 1           ┆ derived    ┆ lncRNA     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ project     ┆             ┆ from CLS3  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ project    ┆            │
│ ENST0000094 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ ENCODE_tiss ┆ 1           ┆ Other      ┆ protein_co │
│ 3010.1      ┆     ┆       ┆            ┆   ┆ ue          ┆             ┆            ┆ ding       │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 6094.5      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ 0           ┆ no         ┆ others     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆             ┆ annotation ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ remark     ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ RNA-Seq     ┆ 1           ┆ Other      ┆ others     │
│ 0179.2      ┆     ┆       ┆            ┆   ┆ supported   ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ partial     ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Select

- tag 情報を用いるため、全ての HN-score 表から、選抜する

In [5]:
up5p_complete = HNscore_transcript.filter(
    # Fold the Series into one scalar list before the membership test.
    pl.col("transcript_id").is_in(up5p["transcript_id"].implode())
)

down5p_complete = HNscore_transcript.filter(
    pl.col("transcript_id").is_in(down5p["transcript_id"].implode())
)

# Each source id is unique, so equal height means every row was recovered.
print(f"up5p rows: complete={up5p_complete.height}, source={up5p.height}")
assert up5p_complete.height == up5p.height

print(f"down5p rows: complete={down5p_complete.height}, source={down5p.height}")
assert down5p_complete.height == down5p.height


display(up5p_complete)
display(down5p_complete)

up5p rows: complete=26354, source=26354
down5p rows: complete=26643, source=26643

shape: (26_354, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ null        ┆ ensembl_hav ┆ ["MANE_sel ┆ 1          │
│ 9758.6      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ ect"]      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ ["alternat ┆ 3          │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ e"]         ┆ ana_gene_ho ┆ ive 5'     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ UTR",      ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "inferred  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ transcript ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ model",    ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ "RNA-Seq   ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000048 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ ["polya_sig ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0008.1      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 6985.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ null        ┆ havana_tage ┆ ["CLS3     ┆ 1          │
│ 4581.1      ┆     ┆       ┆            ┆   ┆             ┆ ne_homo_sap ┆ project"]  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ iens        ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

shape: (26_643, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000053 ┆ 84  ┆ 132   ┆ 190        ┆ … ┆ ["polya_sig ┆ ensembl_hav ┆ null       ┆ 0          │
│ 5641.5      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 4029.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000094 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ ["polya_sig ┆ ensembl_hav ┆ ["ENCODE_t ┆ 1          │
│ 3010.1      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ ana_gene_ho ┆ issue"]    ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆ mo_sapiens  ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 9545.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ null        ┆ ensembl_hav ┆ ["RNA-Seq  ┆ 1          │
│ 0179.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆ partial"]  ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## Scatter Plots

- For Figure

In [6]:
# Rank every transcript by HN2. Red and blue are the lists selected above.
threshold = 2
count = HNscore_transcript.sort(f"HN{threshold}", descending=True)

# The saved lists must be the same tails as a fresh 5% cutoff, including ties.
n_rows = count.height
tail_n = int(n_rows * 0.05)
hn_score_series = count.get_column(f"HN{threshold}")
top_5_percent_threshold = hn_score_series.top_k(tail_n).min()
bottom_5_percent_threshold = hn_score_series.bottom_k(tail_n).max()

threshold_up_ids = (
    count.filter(pl.col(f"HN{threshold}") >= top_5_percent_threshold)
    .select("transcript_id")
    .sort("transcript_id")
)

threshold_down_ids = (
    count.filter(pl.col(f"HN{threshold}") <= bottom_5_percent_threshold)
    .select("transcript_id")
    .sort("transcript_id")
)

In [7]:
# 既に選抜した transcript_id list と同じかどうかを確認
assert up5p_complete.select("transcript_id").sort("transcript_id").equals(threshold_up_ids)
assert down5p_complete.select("transcript_id").sort("transcript_id").equals(threshold_down_ids)

In [8]:
# Row number after the HN2 sort is the x-axis rank.
ranked = count.with_row_index("rank")
hn_col = f"HN{threshold}"
x_data = ranked.get_column("rank").to_numpy()
y_data = ranked.get_column(hn_col).to_numpy()

upregulated = ranked.filter(
    pl.col("transcript_id").is_in(up5p_complete.get_column("transcript_id").implode())
)
upregulated_indices = upregulated.get_column("rank").to_numpy()
y_data_up = upregulated.get_column(hn_col).to_numpy()

downregulated = ranked.filter(
    pl.col("transcript_id").is_in(down5p_complete.get_column("transcript_id").implode())
)
downregulated_indices = downregulated.get_column("rank").to_numpy()
y_data_down = downregulated.get_column(hn_col).to_numpy()

In [9]:
# ggplot supplies the light grid; white face matches the figure.
plt.style.use("ggplot")
plt.rcParams["figure.figsize"] = [10, 16]

ax = plt.axes()
ax.set_facecolor('white')

#All genes
plt.scatter(
            x_data,
            y_data,
            s = 30,
            c="grey",
            edgecolors="black",
            linewidths=0.01,
            alpha=0.5,
            label="all genes"
            )

# upregulated genes
plt.scatter(
            upregulated_indices,
            y_data_up,
            s=100,
            c="red",
            edgecolors="black",
            linewidths=0.2,
            alpha=1,
            label="upregulated"
            )

#downregulated genes
plt.scatter(
            downregulated_indices,
            y_data_down,
            s=100,
            c="blue",
            edgecolors="white",
            linewidths=0.2,
            alpha=1,
            label="downregulated"
            )

plt.grid(color='b', linestyle=':', linewidth=0.1)
plt.xlabel("Transcript ranking based on HN-score (GENCODE release49)", fontsize=18) 
plt.ylabel("HN-score (human) ", fontsize=18)
plt.tick_params(labelsize=12)

plt.savefig(
    "../../out/main_figure/HNscore_all_transcript_scatter_plot.png",
    dpi=500,
    bbox_inches="tight"
)
plt.show()

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# Pie Chart

&nbsp;

&nbsp;

## Transcript Type Check

- 多い順にソートする

In [12]:
up5p_complete_type_count = (
    up5p_complete
    .group_by("transcript_type")
    .agg(
        pl.col("transcript_id").n_unique().alias("count")
    )
    .sort("count", descending=True)
)

pl.Config.set_tbl_rows(10)
display(up5p_complete_type_count)

shape: (29, 2)
┌────────────────────────────────┬───────┐
│ transcript_type                ┆ count │
│ ---                            ┆ ---   │
│ str                            ┆ u32   │
╞════════════════════════════════╪═══════╡
│ protein_coding                 ┆ 12340 │
│ lncRNA                         ┆ 4716  │
│ retained_intron                ┆ 3878  │
│ nonsense_mediated_decay        ┆ 2429  │
│ protein_coding_CDS_not_defined ┆ 2074  │
│ …                              ┆ …     │
│ protein_coding_LoF             ┆ 2     │
│ rRNA_pseudogene                ┆ 1     │
│ Mt_rRNA                        ┆ 1     │
│ processed_transcript           ┆ 1     │
│ IG_C_pseudogene                ┆ 1     │
└────────────────────────────────┴───────┘

In [11]:
down5p_complete_type_count = (
    down5p_complete
    .group_by("transcript_type")
    .agg(
        pl.col("transcript_id").n_unique().alias("count")
    )
    .sort("count", descending=True)
)

display(down5p_complete_type_count)

shape: (21, 2)
┌────────────────────┬───────┐
│ transcript_type    ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ protein_coding     ┆ 12807 │
│ retained_intron    ┆ 6751  │
│ lncRNA             ┆ 3223  │
│ …                  ┆ …     │
│ IG_V_gene          ┆ 1     │
│ protein_coding_LoF ┆ 1     │
│ unitary_pseudogene ┆ 1     │
└────────────────────┴───────┘

&nbsp;

&nbsp;

## Assign Original Flag

- `protein_coding`, `lncRNA`, `other` の 3つに大きく分ける

In [11]:
up5p_complete_classification = (
    up5p_complete
    .with_columns(
        pl.when(pl.col("transcript_type") == "protein_coding")
        .then(pl.lit("protein_coding"))
        .when(pl.col("transcript_type") == "lncRNA")
        .then(pl.lit("lncRNA"))
        .otherwise(pl.lit("others"))
        .alias("original_flag")
    )
)

down5p_complete_classification = (
    down5p_complete
    .with_columns(
        pl.when(pl.col("transcript_type") == "protein_coding")
        .then(pl.lit("protein_coding"))
        .when(pl.col("transcript_type") == "lncRNA")
        .then(pl.lit("lncRNA"))
        .otherwise(pl.lit("others"))
        .alias("original_flag")
    )
)

display(up5p_complete_classification)
display(down5p_complete_classification)

shape: (26_354, 23)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ gene_source ┆ annotation_ ┆ annotation ┆ original_f │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ remarks     ┆ _remark_co ┆ lag        │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str         ┆ ---         ┆ unt        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ u32        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ ensembl_hav ┆ ["MANE_sele ┆ 1          ┆ protein_co │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆ ct"]        ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ ENST0000067 ┆ 338 ┆ 8     ┆ 60         ┆ … ┆ ensembl_hav ┆ ["alternati ┆ 3          ┆ protein_co │
│ 9223.2      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆ ve 5' UTR", ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆ "inferred   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ transcript  ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ model",     ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ "RNA-Seq    ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ only"]      ┆            ┆            │
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ ensembl_hav ┆ null        ┆ 0          ┆ protein_co │
│ 0744.1      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆             ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000048 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ ensembl_hav ┆ null        ┆ 0          ┆ others     │
│ 0008.1      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 1          ┆ lncRNA     │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project"]   ┆            ┆            │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ lncRNA     │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

shape: (26_643, 23)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ gene_source ┆ annotation_ ┆ annotation ┆ original_f │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ remarks     ┆ _remark_co ┆ lag        │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str         ┆ ---         ┆ unt        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ ---        ┆ str        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ u32        ┆            │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000053 ┆ 84  ┆ 132   ┆ 190        ┆ … ┆ ensembl_hav ┆ null        ┆ 0          ┆ others     │
│ 5641.5      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 1          ┆ lncRNA     │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project"]   ┆            ┆            │
│ ENST0000094 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ ensembl_hav ┆ ["ENCODE_ti ┆ 1          ┆ protein_co │
│ 3010.1      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆ ssue"]      ┆            ┆ ding       │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000042 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ensembl_hav ┆ null        ┆ 0          ┆ others     │
│ 6094.5      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ ENST0000054 ┆ 11  ┆ 265   ┆ 130        ┆ … ┆ ensembl_hav ┆ null        ┆ 0          ┆ others     │
│ 9545.1      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆             ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆             ┆            ┆            │
│ ENST0000056 ┆ 11  ┆ 272   ┆ 123        ┆ … ┆ ensembl_hav ┆ ["RNA-Seq   ┆ 1          ┆ others     │
│ 0179.2      ┆     ┆       ┆            ┆   ┆ ana_gene_ho ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ mo_sapiens  ┆ partial"]   ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Pie Chart (transcript category)

&nbsp;

### up5p

In [12]:
# Define custom colors for each gene category
transcript_category_colors = {
    'protein_coding': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'others': '#D3D3D3',  # LightGray (薄い灰色)
    'lncRNA': '#AB63FA'  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    # 'p-lncRNA, intergenic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    # 'e-lncRNA': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_up = (
    up5p_complete_classification
    .group_by("original_flag")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_up.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='original_flag',
    title='Transcript Type Distribution (Upregulated genes)',
    color='original_flag',  # Add color parameter
    color_discrete_map=transcript_category_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()

&nbsp;

&nbsp;

&nbsp;

### Down5p

In [13]:
# Define custom colors for each gene category
transcript_category_colors = {
    'protein_coding': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'others': '#D3D3D3',  # LightGray (薄い灰色)
    'lncRNA': '#AB63FA'  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    # 'p-lncRNA, intergenic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    # 'e-lncRNA': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_down = (
    down5p_complete_classification
    .group_by("original_flag")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_down.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='original_flag',
    title='Transcript Type Distribution (Downregulated genes)',
    color='original_flag',  # Add color parameter
    color_discrete_map=transcript_category_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>'
)

# Update layout for better appearance
fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="left",
        x=1.01
    )
)

fig_basic.show()

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Pie Chart (lncRNA annotation remarks)

- 新たに remark をつける

In [35]:
top5_genes_lncRNA = (
    up5p_complete.filter(
        pl.col("transcript_type") == "lncRNA"
    )
    .with_columns(
        # when() is only a builder; then/otherwise makes the Expr with_columns accepts.
        pl
        .when(pl.col("HGNC_ID").is_not_null() & pl.col("annotation_remarks").list.eval(pl.element().str.contains("CLS3 project")).list.any() & pl.col("tags").list.eval(pl.element().str.contains("TAGENE")).list.any())
        .then(pl.lit("Gene Symbol + CLS3 project"))

        .when(pl.col("HGNC_ID").is_null() & pl.col("annotation_remarks").list.eval(pl.element().str.contains("CLS3 project")).list.any())
        .then(pl.lit("No Gene Symbol + CLS3 project"))

        .when(pl.col("HGNC_ID").is_not_null() & pl.col("tags").list.eval(pl.element().str.contains("basic")).list.any())
        .then(pl.lit("Gene Symbol + basic"))

        .when(pl.col("tags").list.eval(pl.element().str.contains("basic")).list.any())
        .then(pl.lit("basic"))

        .otherwise(pl.lit("Other"))
        .alias("representative_annotation_remarks")
    )
)

print(f"top5 lncRNA transcript count: {top5_genes_lncRNA.select('transcript_id').n_unique()}")
display(top5_genes_lncRNA)

top5 lncRNA transcript count: 4716

shape: (4_716, 23)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ gene_source ┆ annotation_ ┆ annotation ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ remarks     ┆ _remark_co ┆ tive_annot │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str         ┆ ---         ┆ unt        ┆ ation_rema │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ ---        ┆ rks        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ u32        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000085 ┆ 317 ┆ 6     ┆ 83         ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 2          ┆ No Gene    │
│ 0140.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project",   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆ "overlaps   ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆ pseudogene" ┆            ┆ project    │
│             ┆     ┆       ┆            ┆   ┆             ┆ ]           ┆            ┆            │
│ ENST0000073 ┆ 312 ┆ 9     ┆ 85         ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 8043.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000072 ┆ 315 ┆ 20    ┆ 71         ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 9765.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000080 ┆ 52  ┆ 8     ┆ 346        ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 8863.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 1          ┆ Gene       │
│ 6985.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000077 ┆ 101 ┆ 57    ┆ 248        ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 4581.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [36]:
# check
top5_genes_lncRNA_other = top5_genes_lncRNA.filter(pl.col("representative_annotation_remarks") == "Other")
display(top5_genes_lncRNA_other)

shape: (421, 23)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ gene_source ┆ annotation_ ┆ annotation ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ remarks     ┆ _remark_co ┆ tive_annot │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str         ┆ ---         ┆ unt        ┆ ation_rema │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ ---        ┆ rks        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ u32        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000067 ┆ 278 ┆ 14    ┆ 114        ┆ … ┆ havana_homo ┆ ["RNA-Seq   ┆ 1          ┆ Other      │
│ 3634.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ only"]      ┆            ┆            │
│ ENST0000044 ┆ 263 ┆ 19    ┆ 124        ┆ … ┆ havana_homo ┆ ["RNA-Seq   ┆ 1          ┆ Other      │
│ 6336.2      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ partial"]   ┆            ┆            │
│ ENST0000064 ┆ 265 ┆ 31    ┆ 110        ┆ … ┆ ensembl_hav ┆ ["overlaps  ┆ 1          ┆ Other      │
│ 7519.1      ┆     ┆       ┆            ┆   ┆ ana_lincrna ┆ pseudogene" ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ _homo_sapie ┆ ]           ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ ns          ┆             ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000071 ┆ 84  ┆ 40    ┆ 282        ┆ … ┆ havana_homo ┆ ["RNA-Seq   ┆ 1          ┆ Other      │
│ 0875.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ only"]      ┆            ┆            │
│ ENST0000071 ┆ 97  ┆ 53    ┆ 256        ┆ … ┆ havana_homo ┆ ["RNA-Seq   ┆ 1          ┆ Other      │
│ 7219.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ supported   ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ only"]      ┆            ┆            │
│ ENST0000063 ┆ 65  ┆ 21    ┆ 320        ┆ … ┆ havana_homo ┆ null        ┆ 0          ┆ Other      │
│ 5373.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [37]:
down5_genes_lncRNA = (
    down5p_complete.filter(
        pl.col("transcript_type") == "lncRNA"
    )
    .with_columns(
        # when() is only a builder; then/otherwise makes the Expr with_columns accepts.
        pl
        .when(pl.col("HGNC_ID").is_not_null() & pl.col("annotation_remarks").list.eval(pl.element().str.contains("CLS3 project")).list.any() & pl.col("tags").list.eval(pl.element().str.contains("TAGENE")).list.any())
        .then(pl.lit("Gene Symbol + CLS3 project"))

        .when(pl.col("HGNC_ID").is_null() & pl.col("annotation_remarks").list.eval(pl.element().str.contains("CLS3 project")).list.any())
        .then(pl.lit("No Gene Symbol + CLS3 project"))

        .when(pl.col("HGNC_ID").is_not_null() & pl.col("tags").list.eval(pl.element().str.contains("basic")).list.any())
        .then(pl.lit("Gene Symbol + basic"))

        .when(pl.col("tags").list.eval(pl.element().str.contains("basic")).list.any())
        .then(pl.lit("basic"))

        .otherwise(pl.lit("Other"))
        .alias("representative_annotation_remarks")
    )
)

print(f"bottom5 lncRNA transcript count: {down5_genes_lncRNA.select('transcript_id').n_unique()}")
display(down5_genes_lncRNA)

bottom5 lncRNA transcript count: 3223

shape: (3_223, 23)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ gene_source ┆ annotation_ ┆ annotation ┆ representa │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ remarks     ┆ _remark_co ┆ tive_annot │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str         ┆ ---         ┆ unt        ┆ ation_rema │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ ---        ┆ rks        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ u32        ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ str        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 1          ┆ Gene       │
│ 4029.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000082 ┆ 85  ┆ 133   ┆ 188        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 9178.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000052 ┆ 27  ┆ 75    ┆ 304        ┆ … ┆ havana_homo ┆ null        ┆ 0          ┆ Gene       │
│ 4304.1      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆             ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ basic      │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000061 ┆ 11  ┆ 209   ┆ 186        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 2          ┆ No Gene    │
│ 9697.3      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project",   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆ "Assembled  ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆ from PacBio ┆            ┆ project    │
│             ┆     ┆       ┆            ┆   ┆             ┆ CLS3        ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ reads"]     ┆            ┆            │
│ ENST0000079 ┆ 26  ┆ 226   ┆ 154        ┆ … ┆ havana_tage ┆ ["CLS3      ┆ 1          ┆ No Gene    │
│ 7527.1      ┆     ┆       ┆            ┆   ┆ ne_homo_sap ┆ project"]   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆ iens        ┆             ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ project    │
│ ENST0000044 ┆ 22  ┆ 237   ┆ 147        ┆ … ┆ havana_homo ┆ ["CLS3      ┆ 2          ┆ Gene       │
│ 6521.2      ┆     ┆       ┆            ┆   ┆ _sapiens    ┆ project",   ┆            ┆ Symbol +   │
│             ┆     ┆       ┆            ┆   ┆             ┆ "readthroug ┆            ┆ CLS3       │
│             ┆     ┆       ┆            ┆   ┆             ┆ h"]         ┆            ┆ project    │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [38]:
# Define custom colors for each gene category
annotation_remark_colors = {
    'Gene Symbol + CLS3 project': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'Other': '#D3D3D3',  # LightGray (薄い灰色)
    'No Gene Symbol + CLS3 project': '#AB63FA',  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    'Gene Symbol + basic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    'basic': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}

transcript_category_counts_up = (
    top5_genes_lncRNA
    .group_by("representative_annotation_remarks")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_up.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_annotation_remarks',
    title='LncRNA Representative Annotation Remarks Distribution (Upregulated genes)',
    color='representative_annotation_remarks',  # Add color parameter
    color_discrete_map=annotation_remark_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>',
    # Inset the pie so long labels sit in the margin instead of on each other.
    domain=dict(x=[0.28, 0.72], y=[0.08, 0.92]),
)

# Update layout for better appearance.
# The slice labels already name each category, so a side legend would cover them.
fig_basic.update_layout(
    font_size=15,
    showlegend=False,
    width=1000,
    height=640,
    margin=dict(l=10, r=10, t=70, b=30),
)

fig_basic.show()

In [41]:
# Define custom colors for each gene category
annotation_remark_colors = {
    'Gene Symbol + CLS3 project': '#EF553B',  # Red-orange (画像のmRNAに合わせて赤みがかったオレンジ色)
    'Other': '#D3D3D3',  # LightGray (薄い灰色)
    'No Gene Symbol + CLS3 project': '#AB63FA',  # Purple (画像のDivergent p-lncRNAに合わせて紫色)
    'Gene Symbol + basic': '#4682B4',  # Steelblue (画像のIntergenic p-lncRNAに合わせてsteelblue)
    'basic': '#00CC96'  # Teal-green (画像のe-lncRNAに合わせて緑色)
}


transcript_category_counts_down = (
    down5_genes_lncRNA
    .group_by("representative_annotation_remarks")  # Group by gene category column
    .agg(pl.len().alias("count"))  # Count occurrences
    .sort("count", descending=True)  # Sort by count in descending order
)

# Enhanced pie chart with custom colors
fig_basic = px.pie(
    transcript_category_counts_down.to_pandas(),  # Convert Polars to Pandas for plotly
    values='count',
    names='representative_annotation_remarks',
    title='LncRNA Representative Annotation Remarks Distribution (Downregulated genes)',
    color='representative_annotation_remarks',  # Add color parameter
    color_discrete_map=annotation_remark_colors  # Apply custom color mapping
)

# Customize the appearance
fig_basic.update_traces(
    textposition='outside',  # Place text outside pie slices
    textinfo='value+percent+label',  # Show value, percentage and label
    hovertemplate='<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>',
    # Inset the pie so long labels sit in the margin instead of on each other.
    domain=dict(x=[0.28, 0.72], y=[0.08, 0.92]),
)

# Update layout for better appearance.
# The slice labels already name each category, so a side legend would cover them.
fig_basic.update_layout(
    font_size=15,
    showlegend=False,
    width=1000,
    height=640,
    margin=dict(l=10, r=10, t=70, b=30),
)

fig_basic.show()