&nbsp;

# Metadata Concat Process

- sankey plot を作るためのデータフレーム作成に使用

In [1]:
import plotly.graph_objects as go
import polars as pl
import pandas as pd
import plotly.colors as pc
import plotly.io as pio
import numpy as np
from typing import Any
from IPython.display import display


pio.renderers.default = "vscode"

&nbsp;

&nbsp;

# Metadata

In [2]:
# (GENCODE v49) 現在発現定量できていないアクセッションのペアを除く
# failed_accession_pairs_gencode = pl.read_csv(
#     "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2605/failed_pairs_gencode_260511.tsv",
#     separator="\t"
# )

rnaseq_all_metadata = pl.read_csv(
    "../../Data/metadata/metadata_2610/rnaseq_all_complete/rnaseq_all_metadata_modified_simple_261014.tsv",
    separator="\t",
    infer_schema_length=100000
).with_columns(
    pl.lit("heat-stress vs control pair").alias("pair_type")
).with_columns(
    (
     pl.col("stress treatment temperature") + ", " + 
     pl.col("stress treatment time")
     ).alias("study_with_conditions")
)


display(rnaseq_all_metadata)

shape: (406, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_ti ┆ experimen ┆ … ┆ control   ┆ reference ┆ pair_type ┆ study_wi │
│ at_id     ┆ ntrol_id  ┆ tle       ┆ t_accessi ┆   ┆ treatment ┆ _doi      ┆ ---       ┆ th_condi │
│ ---       ┆ ---       ┆ ---       ┆ on        ┆   ┆ temperatu ┆ ---       ┆ str       ┆ tions    │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ re        ┆ str       ┆           ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆           ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 37~53 C, │
│ 72        ┆ 76        ┆ 1_RNA_seq ┆ 24 vs SRX ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 15 min.  │
│           ┆           ┆ vs        ┆ 20731421  ┆   ┆           ┆ .1016/j.x ┆ control   ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆ crm…      ┆ pair      ┆          │
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 37~53 C, │
│ 74        ┆ 75        ┆ 2_RNA_seq ┆ 25 vs SRX ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 15 min.  │
│           ┆           ┆ vs        ┆ 20731422  ┆   ┆           ┆ .1016/j.x ┆ control   ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆ crm…      ┆ pair      ┆          │
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 37~53 C, │
│ 71        ┆ 73        ┆ 3_RNA_seq ┆ 26 vs SRX ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 15 min.  │
│           ┆           ┆ vs        ┆ 20731423  ┆   ┆           ┆ .1016/j.x ┆ control   ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆ crm…      ┆ pair      ┆          │
│ SRR239893 ┆ SRR239893 ┆ SY5609_12 ┆ SRX197932 ┆ … ┆ 37 C      ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 79        ┆ 90        ┆ 0_R3 vs   ┆ 86 vs SRX ┆   ┆           ┆ oi.org/10 ┆ ss vs     ┆ 120 min. │
│           ┆           ┆ SY5609_0_ ┆ 19793296  ┆   ┆           ┆ .1126/sci ┆ control   ┆          │
│           ┆           ┆ R3        ┆           ┆   ┆           ┆ adv…      ┆ pair      ┆          │
│ SRR239893 ┆ SRR239893 ┆ DMSO_30_R ┆ SRX197932 ┆ … ┆ 37 C      ┆ https://d ┆ heat-stre ┆ 42 C, 30 │
│ 91        ┆ 85        ┆ 1 vs      ┆ 97 vs SRX ┆   ┆           ┆ oi.org/10 ┆ ss vs     ┆ min.     │
│           ┆           ┆ DMSO_0_R1 ┆ 19793283  ┆   ┆           ┆ .1126/sci ┆ control   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ adv…      ┆ pair      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRR129261 ┆ SRR129261 ┆ 2hAux_4h4 ┆ SRX939032 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 87        ┆ 83        ┆ 2C_Double ┆ 2 vs SRX9 ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 240 min. │
│           ┆           ┆ AID_rep2  ┆ 390320    ┆   ┆           ┆ .1101/gad ┆ control   ┆          │
│           ┆           ┆ vs …      ┆           ┆   ┆           ┆ .34…      ┆ pair      ┆          │
│ SRR129261 ┆ SRR129261 ┆ 2hH2O_4h4 ┆ SRX939031 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 78        ┆ 74        ┆ 2C_Double ┆ 7 vs SRX9 ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 240 min. │
│           ┆           ┆ AID_rep1  ┆ 390315    ┆   ┆           ┆ .1101/gad ┆ control   ┆          │
│           ┆           ┆ vs …      ┆           ┆   ┆           ┆ .34…      ┆ pair      ┆          │
│ SRR129261 ┆ SRR129261 ┆ 2hH2O_4h4 ┆ SRX939031 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 77        ┆ 73        ┆ 2C_Double ┆ 7 vs SRX9 ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 240 min. │
│           ┆           ┆ AID_rep1  ┆ 390315    ┆   ┆           ┆ .1101/gad ┆ control   ┆          │
│           ┆           ┆ vs …      ┆           ┆   ┆           ┆ .34…      ┆ pair      ┆          │
│ SRR129261 ┆ SRR129261 ┆ 2hAux_4h4 ┆ SRX939032 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 88        ┆ 84        ┆ 2C_Double ┆ 2 vs SRX9 ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 240 min. │
│           ┆           ┆ AID_rep2  ┆ 390320    ┆   ┆           ┆ .1101/gad ┆ control   ┆          │
│           ┆           ┆ vs …      ┆           ┆   ┆           ┆ .34…      ┆ pair      ┆          │
│ SRR129261 ┆ SRR129261 ┆ 2hH2O_4h4 ┆ SRX939031 ┆ … ┆ 37 C (inf ┆ https://d ┆ heat-stre ┆ 42 C,    │
│ 80        ┆ 76        ┆ 2C_Double ┆ 8 vs SRX9 ┆   ┆ erred)    ┆ oi.org/10 ┆ ss vs     ┆ 240 min. │
│           ┆           ┆ AID_rep2  ┆ 390316    ┆   ┆           ┆ .1101/gad ┆ control   ┆          │
│           ┆           ┆ vs …      ┆           ┆   ┆           ┆ .34…      ┆ pair      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## Parallel Object

In [3]:
def create_parcats_from_polars(df, dimensions, color_column=None, title="Parallel Categories Diagram", width=1200, height=800):
    """
    Function to create Parallel Categories plot from Polars DataFrame.
    Uses distinct categorical colors to avoid overlap.
    """
    
    # 1. Prepare dimensions
    parcats_dimensions = []
    for col in dimensions:
        parcats_dimensions.append(dict[str, Any](
            label=col,
            values=df[col].to_list()
        ))
        
    # 2. Configure line styling
    line_props = dict[str, Any](
        color='gray',
        shape='hspline'
    )
    
    if color_column:
        # Get unique values
        unique_vals = df[color_column].unique().sort().to_list()
        n_categories = len(unique_vals)
        
        # Map categories to integer indices
        val2idx = {v: i for i, v in enumerate[Any](unique_vals)}
        color_vals = [val2idx[v] for v in df[color_column].to_list()]
        
        # --- 色の生成ロジック変更点 ---
        # 多数のカテゴリに対応するため、複数のパレットを結合して大きなパレットを作成します
        # Alphabet(26色) + Dark24(24色) + Light24(24色) ...
        distinct_palette = pc.qualitative.Alphabet + pc.qualitative.Dark24 + pc.qualitative.Light24
        
        # カテゴリ数がパレットより多い場合は繰り返す
        if n_categories > len(distinct_palette):
            distinct_palette = distinct_palette * (n_categories // len(distinct_palette) + 1)
        
        # 必要な数だけ切り出す
        custom_colorscale = distinct_palette[:n_categories]

        line_props: dict[str, Any] = dict[str, Any]()
        
        line_props.update(dict[str, Any](
            color=color_vals,
            colorscale=custom_colorscale, # カスタムパレットを適用
            cmin=0,
            cmax=n_categories - 1,
            showscale=False,
            shape='hspline'
        ))

    # 3. Create the Figure
    fig = go.Figure(data=[go.Parcats(
        dimensions=parcats_dimensions,
        line=line_props,
        hoveron='color',
        hoverinfo='count+probability',
        arrangement='freeform',
        bundlecolors=True
    )])
    
    fig.update_layout(
        title_text=title,
        font_size=18,
        width=width,
        height=height,
        margin=dict[str, int](l=80, r=80, t=80, b=80)
    )
    
    return fig

In [4]:
print(rnaseq_all_metadata.columns)

['sample_heat_id', 'sample_control_id', 'sample_title', 'experiment_accession', 'experiment_alias', 'secondary_sample_accession', 'study_accession', 'first_public', 'study_alias', 'instrument_platform', 'instrument_model', 'library_source', 'library_layout', 'sample_molecule_ch1', 'rna_library', 'normalized_label', 'item_type', 'strandness', 'strandness_evidence', 'expected_format_heat', 'expected_format_control', 'strand_mapping_bias_heat', 'strand_mapping_bias_control', 'format_pair_comparison', 'expected_library_strandedness', 'sample', 'url', 'Biosample term id', 'Biosample term name', 'other term id', 'genotype_normalization', 'genotype_class', 'stress treatment temperature', 'stress treatment time', 'control treatment temperature', 'reference_doi', 'pair_type', 'study_with_conditions']

In [5]:
fig = create_parcats_from_polars(
    df=rnaseq_all_metadata, 
    dimensions=["study_accession", "strandness", "sample_molecule_ch1", "stress treatment temperature", "stress treatment time", "Biosample term name"], 
    color_column="study_accession",
    title="Metadata Flow",
    height=1200,
    width=1800
)

fig.show()

&nbsp;

&nbsp;

&nbsp;

## HN-score Category

- transcript level で、`UP`, `DOWN`, `UNCHANGED` も積み上げで可視化するための処理

In [6]:
HNratio_categorized = pl.read_csv(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/HNratio_categorized_2.tsv",
    separator="\t",
    n_threads=16
)

display(HNratio_categorized)

shape: (517_038, 407)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transcrip ┆ SRR276819 ┆ SRR276819 ┆ SRR249737 ┆ … ┆ HRR255909 ┆ HRR255910 ┆ HRR255913 ┆ HRR25591 │
│ t_id      ┆ 84_catego ┆ 83_catego ┆ 72_catego ┆   ┆ _category ┆ _category ┆ _category ┆ 4_catego │
│ ---       ┆ ry        ┆ ry        ┆ ry        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ry       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832824.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832825.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832826.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832827.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 832828.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENST00000 ┆ UP        ┆ DOWN      ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ DOWN     │
│ 797950.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 819228.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 819229.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UP        ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 751368.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ ENST00000 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 839853.1  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Create a dictionary for renaming columns, removing the '_category' suffix from all columns except 'GENEID'.
rename_mapping = {
    col: col.removesuffix('_category') 
    for col in HNratio_categorized.columns 
    if col != 'transcript_id'
}

# Chain the rename and transpose operations.
# 'transpose' makes rows into columns and vice-versa.
# 'include_header=True' keeps the original column names as a new column.
# 'header_name' gives a name to that new column.
# 'column_names' uses values from this column as the new headers.
HNratio_transposed = HNratio_categorized.rename(rename_mapping).transpose(
    include_header=True, 
    header_name="sample_heat_id", 
    column_names="transcript_id"
)

display(HNratio_transposed)

shape: (406, 517_039)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ ENST00000 ┆ ENST00000 ┆ ENST00000 ┆ … ┆ ENST00000 ┆ ENST00000 ┆ ENST00000 ┆ ENST0000 │
│ at_id     ┆ 832824.1  ┆ 832825.1  ┆ 832826.1  ┆   ┆ 819228.1  ┆ 819229.1  ┆ 751368.1  ┆ 0839853. │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 84        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ SRR276819 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 83        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ SRR249737 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UP        ┆ UNCHANGE │
│ 72        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ SRR249737 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 74        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ SRR249737 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UP        ┆ UNCHANGED ┆ UP        ┆ UP       │
│ 71        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255906 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ HRR255909 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ HRR255910 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ HRR255913 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
│ HRR255914 ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
rnaseq_all_metadata_join = rnaseq_all_metadata.join(
    HNratio_transposed,
    on="sample_heat_id",
    how="inner"
)

display(rnaseq_all_metadata_join)

shape: (406, 517_076)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_ti ┆ experimen ┆ … ┆ ENST00000 ┆ ENST00000 ┆ ENST00000 ┆ ENST0000 │
│ at_id     ┆ ntrol_id  ┆ tle       ┆ t_accessi ┆   ┆ 819228.1  ┆ 819229.1  ┆ 751368.1  ┆ 0839853. │
│ ---       ┆ ---       ┆ ---       ┆ on        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ SRR276819 ┆ WI-38-hTE ┆ SRX233492 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 84        ┆ 86        ┆ RT, 40°C, ┆ 32 vs SRX ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ RNA-seq,  ┆ 23349230  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR276819 ┆ SRR276819 ┆ WI-38-hTE ┆ SRX233492 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 83        ┆ 85        ┆ RT, 40°C, ┆ 33 vs SRX ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ RNA-seq,  ┆ 23349231  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UP        ┆ UNCHANGE │
│ 72        ┆ 76        ┆ 1_RNA_seq ┆ 24 vs SRX ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ vs        ┆ 20731421  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│ 74        ┆ 75        ┆ 2_RNA_seq ┆ 25 vs SRX ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ vs        ┆ 20731422  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ M3D_Heat_ ┆ SRX207314 ┆ … ┆ UP        ┆ UNCHANGED ┆ UP        ┆ UP       │
│ 71        ┆ 73        ┆ 3_RNA_seq ┆ 26 vs SRX ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs        ┆ 20731423  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ M3D_Ctrl… ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255906 ┆ HRR255904 ┆ RNAseq_VS ┆ HRX214093 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆ MC_39_rep ┆ vs        ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ 2 vs      ┆ HRX214091 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAseq_…  ┆           ┆   ┆           ┆           ┆           ┆          │
│ HRR255909 ┆ HRR255907 ┆ RNAseq_CM ┆ HRX214096 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆ C_39_rep1 ┆ vs        ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ vs        ┆ HRX214094 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAseq_C… ┆           ┆   ┆           ┆           ┆           ┆          │
│ HRR255910 ┆ HRR255908 ┆ RNAseq_CM ┆ HRX214097 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆ C_39_rep2 ┆ vs        ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ vs        ┆ HRX214095 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAseq_C… ┆           ┆   ┆           ┆           ┆           ┆          │
│ HRR255913 ┆ HRR255911 ┆ RNAseq_Ne ┆ HRX214100 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆ uron_39_r ┆ vs        ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ ep1 vs    ┆ HRX214098 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAse…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ HRR255914 ┆ HRR255912 ┆ RNAseq_Ne ┆ HRX214101 ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆           ┆ uron_39_r ┆ vs        ┆   ┆           ┆           ┆           ┆ D        │
│           ┆           ┆ ep2 vs    ┆ HRX214099 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAse…    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

## Case Study 1: _NEAT1_

In [10]:
# NEAT1 の transcript の一覧を取得
HNscore_NEAT1 = pl.read_parquet(
    "../../Data/HNscore/HNscore_transcript/HNscore_gencode_2610/annotation/HNscore_gencode_human_261001_HN2_transcript_all_gencode_annotation.parquet",
).filter(
    pl.col("gene_id").str.contains("ENSG00000245532")
)

pl.Config.set_tbl_rows(100)
display(HNscore_NEAT1)

shape: (16, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000061 ┆ 42  ┆ 22    ┆ 342        ┆ … ┆ null        ┆ havana_homo ┆ null       ┆ 0          │
│ 6315.2      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆            ┆            │
│ ENST0000050 ┆ 63  ┆ 53    ┆ 290        ┆ … ┆ ["polya_sig ┆ havana_homo ┆ ["CLS3     ┆ 4          │
│ 1122.4      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ _sapiens    ┆ project",  ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆             ┆ "MANE_sele ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ ct"…       ┆            │
│ ENST0000081 ┆ 50  ┆ 41    ┆ 315        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3135.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000081 ┆ 30  ┆ 29    ┆ 347        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3134.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000064 ┆ 89  ┆ 93    ┆ 224        ┆ … ┆ null        ┆ havana_homo ┆ ["RNA-Seq  ┆ 1          │
│ 2367.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000081 ┆ 25  ┆ 39    ┆ 342        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3132.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000071 ┆ 45  ┆ 63    ┆ 298        ┆ … ┆ ["polya_sig ┆ havana_homo ┆ null       ┆ 0          │
│ 7968.1      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ _sapiens    ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆             ┆            ┆            │
│ ENST0000067 ┆ 74  ┆ 93    ┆ 239        ┆ … ┆ null        ┆ havana_homo ┆ ["Assemble ┆ 1          │
│ 0617.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ d from     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ SLRseq     ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ reads …    ┆            │
│ ENST0000081 ┆ 41  ┆ 65    ┆ 300        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3130.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000061 ┆ 78  ┆ 104   ┆ 224        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 2303.3      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000081 ┆ 32  ┆ 60    ┆ 314        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3131.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000081 ┆ 30  ┆ 62    ┆ 314        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 3133.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
│ ENST0000064 ┆ 72  ┆ 105   ┆ 229        ┆ … ┆ null        ┆ havana_homo ┆ ["RNA-Seq  ┆ 1          │
│ 5023.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000060 ┆ 46  ┆ 82    ┆ 278        ┆ … ┆ null        ┆ havana_homo ┆ null       ┆ 0          │
│ 1801.3      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆            ┆            │
│ ENST0000064 ┆ 52  ┆ 97    ┆ 257        ┆ … ┆ null        ┆ havana_homo ┆ ["RNA-Seq  ┆ 1          │
│ 6243.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ supported  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆ only"]     ┆            │
│ ENST0000049 ┆ 72  ┆ 118   ┆ 216        ┆ … ┆ ["polya_sit ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 9732.4      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ _sapiens    ┆ project"]  ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆             ┆            ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [13]:
NEAT1_transcripts = rnaseq_all_metadata_join.select(
    "sample_heat_id",
    "study_accession",
    "sample_molecule_ch1",
    "Biosample term name",
    "stress treatment temperature",
    "stress treatment time",
    "ENST00000813135.1",
    "ENST00000813134.1",
    "ENST00000616315.2",
    "ENST00000501122.4",
    "ENST00000642367.1",
    "ENST00000813132.1",
    "ENST00000670617.1",
    "ENST00000717968.1",
    "ENST00000612303.3",
    "ENST00000813130.1",
    "ENST00000813131.1",
    "ENST00000813133.1",
    "ENST00000601801.3",
    "ENST00000645023.1",
    "ENST00000646243.1",
    "ENST00000499732.4"
)

pl.Config.set_tbl_rows(2)
display(NEAT1_transcripts)

shape: (406, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ study_acc ┆ sample_mo ┆ Biosample ┆ … ┆ ENST00000 ┆ ENST00000 ┆ ENST00000 ┆ ENST0000 │
│ at_id     ┆ ession    ┆ lecule_ch ┆ term name ┆   ┆ 601801.3  ┆ 645023.1  ┆ 646243.1  ┆ 0499732. │
│ ---       ┆ ---       ┆ 1         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 4        │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ PRJNA1067 ┆ total RNA ┆ WI 38     ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ DOWN      ┆ UNCHANGE │
│ 84        ┆ 599       ┆           ┆ cell      ┆   ┆           ┆           ┆           ┆ D        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255914 ┆ PRJCA0054 ┆ total RNA ┆ neuron    ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆ 46        ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
DRR321029 = NEAT1_transcripts.filter(
    pl.col("sample_heat_id").str.contains("DRR321029")
)

display(DRR321029)

shape: (1, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ study_acc ┆ sample_mo ┆ Biosample ┆ … ┆ ENST00000 ┆ ENST00000 ┆ ENST00000 ┆ ENST0000 │
│ at_id     ┆ ession    ┆ lecule_ch ┆ term name ┆   ┆ 601801.3  ┆ 645023.1  ┆ 646243.1  ┆ 0499732. │
│ ---       ┆ ---       ┆ 1         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 4        │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR321029 ┆ PRJDB1238 ┆ total RNA ┆ HAP-1     ┆ … ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGED ┆ UNCHANGE │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ D        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
fig = create_parcats_from_polars(
    df=NEAT1_transcripts, 
    dimensions=["ENST00000501122.4", "Biosample term name", "sample_molecule_ch1"], 
    color_column="study_accession",
    title="Metadata Flow",
    height=1200,
    width=1800
)

fig.show()

&nbsp;

&nbsp;

&nbsp;

## Case Study 2: