&nbsp;

## [ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) Result Parse Notebook (Heat stress-related datasets)

- [config_biosamples_hs_atacseq_hic_list.tsv](../../out/ENCODE_rE2G/config/config_biosamples_hs_atacseq_hic_list.tsv)で定義した14個のデータセットでの enhancer-gene interaction の相互作用の結果をパースする notebook

In [1]:
import datetime
import os
import pathlib

import polars as pl
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
execute_date = datetime.datetime.now().strftime("%y%m%d")  # noqa: DTZ005
print(f"Execute Date: {execute_date}")

Execute Date: 261003

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. Parse Target Bed file (Information included: "G"; Gene)

- Target となる領域は [RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed](https://github.com/EngreitzLab/ENCODE_rE2G/blob/main/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed) で定義されている (Download date: 2026-07-31)
- この領域 (TSS 500bp)を通常では遺伝子レベルで表現されているが、これを fanta.bio のBEDファイルとintersect しておくことで、後々の解析をしやすくする
- この領域 (TSS 500bp) と fanta.bio で定義された CRE の重なり具合を算出し、この領域 (TSS 500bp) 側から見たときの割合も算出する (フィルタリング条件に活用するため)
- `ENCODE-rE2G` 側では、範囲が 500 bp と決まっており、この範囲を起点に相互作用が予測されているため、fanta.bio のCREがどの程度カバーしているかを計算しておく
- 同一 `TargetGene` に複数 `cre_id` が紐づく場合は、`tss_cre_overlap_frac_of_tss` が最大の CRE を残す（`pl.when` で明示）
- 同点時は `fantabio_cre_class == "PLA"` を優先し、それでも残る同点は `cre_id` で決定的に1行にする
- 実行コマンド: `cwltool --outdir ./out/ENCODE_rE2G/bedtools_intersect/ ./Tools/bedtools_intersect_v2.cwl ./config/ENCODE_rE2G/encodere2g_refseq_promoter_intersect_fantabio_cre.yml`

In [3]:
# Download https://github.com/EngreitzLab/ENCODE_rE2G/blob/main/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp.bed
encodere2g_tatget_refseq_intersect_fantabio_cre = (
    pl.read_csv(
        "../../out/ENCODE_rE2G/bedtools_intersect/RefSeqCurated.170308.bed.CollapsedGeneBounds.hg38.TSS500bp_intersecting_human-CREv1.2.1.hg38.cre-peaks.bed",
        separator="\t",
        has_header=False,
        new_columns=[
            "tss_chr", "tss_start", "tss_end", "TargetGene", "tss_score", "tss_strand",
            "cre_chr", "cre_start", "cre_end", "cre_id", "cre_score", "cre_strand",
            "cre_thick_start", "cre_thick_end", "cre_rgb", "cre_name", "pooled_cre_scores",
            "overlap_bp",  # last column from bedtools -wo
        ]
    ).with_columns(
        pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
        pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
        pl.col("overlap_bp").alias("tss_cre_overlap_bp"),
    ).with_columns(
        (pl.col("tss_cre_overlap_bp") / (pl.col("tss_end") - pl.col("tss_start")))
        .alias("tss_cre_overlap_frac_of_tss"),
    ).with_columns(
        pl.lit("tss_overlap").alias("target_cre_evidence"),
    ).drop("overlap_bp")
)

pl.Config.set_tbl_rows(2)
display(encodere2g_tatget_refseq_intersect_fantabio_cre)

shape: (38_074, 22)
┌─────────┬───────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ tss_chr ┆ tss_start ┆ tss_end  ┆ TargetGene ┆ … ┆ fantabio_c ┆ tss_cre_o ┆ tss_cre_o ┆ target_cr │
│ ---     ┆ ---       ┆ ---      ┆ ---        ┆   ┆ re_class   ┆ verlap_bp ┆ verlap_fr ┆ e_evidenc │
│ str     ┆ i64       ┆ i64      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ac_of_tss ┆ e         │
│         ┆           ┆          ┆            ┆   ┆ str        ┆ i64       ┆ ---       ┆ ---       │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆ f64       ┆ str       │
╞═════════╪═══════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ chr1    ┆ 29120     ┆ 29620    ┆ WASH7P     ┆ … ┆ ELA        ┆ 41        ┆ 0.082     ┆ tss_overl │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆           ┆ ap        │
│ …       ┆ …         ┆ …        ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ chrY    ┆ 20575460  ┆ 20575960 ┆ EIF1AY     ┆ … ┆ PLA        ┆ 452       ┆ 0.904     ┆ tss_overl │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆           ┆ ap        │
└─────────┴───────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

## 1-1: Filter (Information: "G")

- 同一 `TargetGene` に複数 `cre_id` が紐づく場合は、`tss_cre_overlap_frac_of_tss` が最大の CRE を残す（`pl.when` で明示）
- overlap が同点のときは `fantabio_cre_class == "PLA"` を優先する（`pl.when` で `pla_rank` を付与）
- それでも同点のときは `cre_id` の辞書順で決定的に 1 行にする（`sort` + `unique(keep="first")`）
- 分母は ENCODE-rE2G の TSS 500 bp（`tss_end - tss_start`）。閾値による除外は行わず、遺伝子ごとに代表 CRE を 1 本選ぶ

In [4]:
# Keep the CRE with the highest TSS overlap fraction per TargetGene
encodere2g_tatget_refseq_best_cre = (
    encodere2g_tatget_refseq_intersect_fantabio_cre
    .with_columns(
        # Max overlap fraction within each TargetGene
        pl.col("tss_cre_overlap_frac_of_tss")
        .max()
        .over("TargetGene")
        .alias("max_tss_cre_overlap_frac_of_tss"),
    )
    .with_columns(
        # True only for the row(s) that achieve that max
        pl.when(
            pl.col("tss_cre_overlap_frac_of_tss") == pl.col("max_tss_cre_overlap_frac_of_tss")
        )
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("is_best_cre_for_target_gene"),
    )
    .filter(pl.col("is_best_cre_for_target_gene")) # flag

    .with_columns(
        # On ties, prefer PLA (0) over other classes (1)
        pl.when(pl.col("fantabio_cre_class") == "PLA")
        .then(pl.lit(0))
        .otherwise(pl.lit(1))
        .alias("pla_rank"),
    )
    # Tie-break: PLA first, then cre_id for a deterministic single row
    .sort("TargetGene", "pla_rank", "cre_id")
    .unique(subset=["TargetGene"], keep="first")
    .drop("max_tss_cre_overlap_frac_of_tss", "is_best_cre_for_target_gene", "pla_rank")
)

print(
    f"Rows before: {encodere2g_tatget_refseq_intersect_fantabio_cre.height} \n"
    f"Rows after: {encodere2g_tatget_refseq_best_cre.height} \n"
    f"UniqueGenes: {encodere2g_tatget_refseq_best_cre.select('TargetGene').n_unique()}"
)

display(encodere2g_tatget_refseq_best_cre)

Rows before: 38074
Rows after: 20766
UniqueGenes: 20766

shape: (20_766, 22)
┌─────────┬───────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ tss_chr ┆ tss_start ┆ tss_end  ┆ TargetGene ┆ … ┆ fantabio_c ┆ tss_cre_o ┆ tss_cre_o ┆ target_cr │
│ ---     ┆ ---       ┆ ---      ┆ ---        ┆   ┆ re_class   ┆ verlap_bp ┆ verlap_fr ┆ e_evidenc │
│ str     ┆ i64       ┆ i64      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ac_of_tss ┆ e         │
│         ┆           ┆          ┆            ┆   ┆ str        ┆ i64       ┆ ---       ┆ ---       │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆ f64       ┆ str       │
╞═════════╪═══════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ chr19   ┆ 58353249  ┆ 58353749 ┆ A1BG       ┆ … ┆ PLA        ┆ 318       ┆ 0.636     ┆ tss_overl │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆           ┆ ap        │
│ …       ┆ …         ┆ …        ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ chr1    ┆ 77682408  ┆ 77682908 ┆ ZZZ3       ┆ … ┆ PLA        ┆ 445       ┆ 0.89      ┆ tss_overl │
│         ┆           ┆          ┆            ┆   ┆            ┆           ┆           ┆ ap        │
└─────────┴───────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

## Example: LINC00115 / ADAMTS19

In [5]:
# Example: LINC00115 (1行のみ残る)
display(
    encodere2g_tatget_refseq_intersect_fantabio_cre
    .filter(pl.col("TargetGene") == "LINC00115")
    .select("TargetGene", "cre_id", "fantabio_cre_class", "tss_cre_overlap_frac_of_tss")
    .sort("tss_cre_overlap_frac_of_tss", descending=True)
)

display(
    encodere2g_tatget_refseq_best_cre
    .filter(pl.col("TargetGene") == "LINC00115")
    .select("TargetGene", "cre_id", "fantabio_cre_class", "tss_cre_overlap_frac_of_tss")
)


# Example 2: ADAMTS19 (1行のみ残る)
display(
    encodere2g_tatget_refseq_intersect_fantabio_cre
    .filter(pl.col("TargetGene") == "ADAMTS19")
    .select("TargetGene", "cre_id", "fantabio_cre_class", "tss_cre_overlap_frac_of_tss")
    .sort("tss_cre_overlap_frac_of_tss", descending=True)
)

display(
    encodere2g_tatget_refseq_best_cre
    .filter(pl.col("TargetGene") == "ADAMTS19")
    .select("TargetGene", "cre_id", "fantabio_cre_class", "tss_cre_overlap_frac_of_tss")
    .sort("tss_cre_overlap_frac_of_tss", descending=True)
)

shape: (2, 4)
┌────────────┬─────────┬────────────────────┬─────────────────────────────┐
│ TargetGene ┆ cre_id  ┆ fantabio_cre_class ┆ tss_cre_overlap_frac_of_tss │
│ ---        ┆ ---     ┆ ---                ┆ ---                         │
│ str        ┆ str     ┆ str                ┆ f64                         │
╞════════════╪═════════╪════════════════════╪═════════════════════════════╡
│ LINC00115  ┆ FCHS_26 ┆ PLA                ┆ 0.872                       │
│ LINC00115  ┆ FCHS_25 ┆ ELA                ┆ 0.278                       │
└────────────┴─────────┴────────────────────┴─────────────────────────────┘

shape: (1, 4)
┌────────────┬─────────┬────────────────────┬─────────────────────────────┐
│ TargetGene ┆ cre_id  ┆ fantabio_cre_class ┆ tss_cre_overlap_frac_of_tss │
│ ---        ┆ ---     ┆ ---                ┆ ---                         │
│ str        ┆ str     ┆ str                ┆ f64                         │
╞════════════╪═════════╪════════════════════╪═════════════════════════════╡
│ LINC00115  ┆ FCHS_26 ┆ PLA                ┆ 0.872                       │
└────────────┴─────────┴────────────────────┴─────────────────────────────┘

shape: (2, 4)
┌────────────┬─────────────┬────────────────────┬─────────────────────────────┐
│ TargetGene ┆ cre_id      ┆ fantabio_cre_class ┆ tss_cre_overlap_frac_of_tss │
│ ---        ┆ ---         ┆ ---                ┆ ---                         │
│ str        ┆ str         ┆ str                ┆ f64                         │
╞════════════╪═════════════╪════════════════════╪═════════════════════════════╡
│ ADAMTS19   ┆ FCHS_337546 ┆ PLA                ┆ 1.0                         │
│ ADAMTS19   ┆ FCHS_337547 ┆ ELA                ┆ 1.0                         │
└────────────┴─────────────┴────────────────────┴─────────────────────────────┘

shape: (1, 4)
┌────────────┬─────────────┬────────────────────┬─────────────────────────────┐
│ TargetGene ┆ cre_id      ┆ fantabio_cre_class ┆ tss_cre_overlap_frac_of_tss │
│ ---        ┆ ---         ┆ ---                ┆ ---                         │
│ str        ┆ str         ┆ str                ┆ f64                         │
╞════════════╪═════════════╪════════════════════╪═════════════════════════════╡
│ ADAMTS19   ┆ FCHS_337546 ┆ PLA                ┆ 1.0                         │
└────────────┴─────────────┴────────────────────┴─────────────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. Integrate `fanta.bio` data (Information included: "E"; enhancer)

- [ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G) で得られたエンハンサー候補と、`fanta.bio`のデータを `bedtools intersect` した後の結果をデータフレームとして読み込む
- scatter 版: 複数サンプルの enhancer BED を、共通の fanta.bio CRE peaks と一括 intersect する
- 実行コマンド: `cwltool --outdir ./out/ENCODE_rE2G/bedtools_intersect/enhancer/ ./Workflow/bedtools_intersect_v2_scatter.cwl ./config/ENCODE_rE2G/hs_atacseq_hic_list_re2g_enhancer_intersect_fantabio_cre.yml`
- 単一サンプルのみの場合: `cwltool --outdir ./out/ENCODE_rE2G/bedtools_intersect/enhancer/ ./Tools/bedtools_intersect_v2.cwl ./config/ENCODE_rE2G/gse105028_hs_re2g_enhancer_intersect_fantabio_cre.yml`
- 各行に `re2g_dataset` / `source_bed_file` を付与し、同一 CRE でも由来サンプルを区別できるようにする

In [9]:
# Parse bedtools intersect (-wo) outputs for all enhancer datasets
BED_INTERSECT_ENHANCER_DIR = pathlib.Path("../../out/ENCODE_rE2G/bedtools_intersect/enhancer_hs")

ENHANCER_INTERSECT_COLUMNS = [
    "re2g_chr",
    "re2g_start",
    "re2g_end",
    "cre_chr",
    "cre_start",
    "cre_end",
    "cre_id",
    "cre_score",
    "cre_strand",
    "cre_thick_start",
    "cre_thick_end",
    "cre_rgb",
    "cre_name",
    "pooled_cre_scores",
    "overlap_bp",  # last column from bedtools -wo
]


def read_enhancer_intersect_bed(bed_path: pathlib.Path) -> pl.DataFrame:
    """
    Read one enhancer x fanta.bio intersect BED and tag dataset ID from filename.
    Example stem prefix: GSE101731_HFF_44C_60min
    """
    re2g_dataset = bed_path.stem.split("_encode_e2g_predictions_", 1)[0]

    return (
        pl.read_csv(
            bed_path,
            separator="\t",
            has_header=False,
            new_columns=ENHANCER_INTERSECT_COLUMNS,
            n_threads=16,
        )
        .with_columns(
            pl.col("pooled_cre_scores")
            .str.extract(r"directionality:([^|]+)", 1)
            .cast(pl.Float64, strict=False)
            .alias("directionality"),
            pl.col("pooled_cre_scores")
            .str.extract(r"class:([^|]+)", 1)
            .alias("fantabio_cre_class"),
            pl.col("overlap_bp").alias("enhancer_cre_overlap_bp"),
        )
        .with_columns(
            (pl.col("enhancer_cre_overlap_bp") / (pl.col("cre_end") - pl.col("cre_start"))).alias("enhancer_cre_overlap_frac_of_fantabio_cre"),
            pl.lit(re2g_dataset).alias("re2g_dataset"),
            pl.lit(bed_path.name).alias("source_bed_file"),
        )
        .drop(
            "cre_score",
            "cre_strand",
            "cre_rgb",
            "cre_thick_start",
            "cre_thick_end",
            "pooled_cre_scores",
            "overlap_bp",
        )
    )


bed_paths = sorted(BED_INTERSECT_ENHANCER_DIR.glob("*_intersecting_*.bed"))

enhancer_fanta_intersect = pl.concat(
    [read_enhancer_intersect_bed(p) for p in bed_paths],
    how="vertical_relaxed",
).sort("cre_chr", "cre_start", "re2g_dataset")

print(f"files: {len(bed_paths)}")
print(f"datasets: {enhancer_fanta_intersect.select('re2g_dataset').n_unique()}")

pl.Config.set_tbl_rows(14)
display(
    enhancer_fanta_intersect.group_by("re2g_dataset")
    .len()
    .sort("re2g_dataset")
)
pl.Config.set_tbl_rows(2)
display(enhancer_fanta_intersect)

files: 14
datasets: 14

shape: (14, 2)
┌───────────────────────────────────────┬────────┐
│ re2g_dataset                          ┆ len    │
│ ---                                   ┆ ---    │
│ str                                   ┆ u32    │
╞═══════════════════════════════════════╪════════╡
│ GSE101731_HFF_44C_120min              ┆ 94003  │
│ GSE101731_HFF_44C_60min               ┆ 92584  │
│ GSE105028_hESC_42C_60min              ┆ 111014 │
│ GSE154744_K562_42C_12_5min            ┆ 80467  │
│ GSE154744_K562_42C_25min              ┆ 79740  │
│ GSE154744_K562_42C_30min              ┆ 83920  │
│ GSE154744_K562_42C_30min_intact_hic   ┆ 79142  │
│ GSE154744_K562_42C_40min              ┆ 68579  │
│ GSE154744_K562_42C_60min              ┆ 95337  │
│ GSE173536_lymphblastoid_d21_42C_60min ┆ 110012 │
│ GSE173536_lymphblastoid_t21_42C_60min ┆ 109099 │
│ GSE209675_MCF7_42C_60min              ┆ 94460  │
│ GSE267931_HUVEC_39C_120min            ┆ 109899 │
│ GSE280307_THP1_42C_120min             ┆ 105862 │
└───────────────────────────────────────┴────────┘

shape: (1_314_118, 14)
┌──────────┬────────────┬───────────┬─────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ re2g_chr ┆ re2g_start ┆ re2g_end  ┆ cre_chr ┆ … ┆ enhancer_c ┆ enhancer_ ┆ re2g_data ┆ source_be │
│ ---      ┆ ---        ┆ ---       ┆ ---     ┆   ┆ re_overlap ┆ cre_overl ┆ set       ┆ d_file    │
│ str      ┆ i64        ┆ i64       ┆ str     ┆   ┆ _bp        ┆ ap_frac_o ┆ ---       ┆ ---       │
│          ┆            ┆           ┆         ┆   ┆ ---        ┆ f_fantabi ┆ str       ┆ str       │
│          ┆            ┆           ┆         ┆   ┆ i64        ┆ o_cre     ┆           ┆           │
│          ┆            ┆           ┆         ┆   ┆            ┆ ---       ┆           ┆           │
│          ┆            ┆           ┆         ┆   ┆            ┆ f64       ┆           ┆           │
╞══════════╪════════════╪═══════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ chr1     ┆ 778460     ┆ 779061    ┆ chr1    ┆ … ┆ 392        ┆ 1.0       ┆ GSE101731 ┆ GSE101731 │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆ _HFF_44C_ ┆ _HFF_44C_ │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆ 60min     ┆ 60min_enc │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ode_e2g_p │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ rediction │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ s_thresho │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ld0.179_o │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ nly_enhan │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ cer_inter │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ secting_h │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ uman-CREv │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ 1.2.1.hg3 │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ 8.cre-pea │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ks.bed    │
│ …        ┆ …          ┆ …         ┆ …       ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ chrX     ┆ 155612271  ┆ 155613230 ┆ chrX    ┆ … ┆ 182        ┆ 0.556575  ┆ GSE280307 ┆ GSE280307 │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆ _THP1_42C ┆ _THP1_42C │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆ _120min   ┆ _120min_e │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ncode_e2g │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ _predicti │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ons_thres │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ hold0.179 │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ _only_enh │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ancer_int │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ ersecting │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ _human-CR │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ Ev1.2.1.h │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ g38.cre-p │
│          ┆            ┆           ┆         ┆   ┆            ┆           ┆           ┆ eaks.bed  │
└──────────┴────────────┴───────────┴─────────┴───┴────────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. ENCODE rE2G TSV file (Information Included: "E" / "G")

- このデータは、予測された enhancer - gene interaction が記載されており、`join` する際の 核となるデータセットとして使用される
- `bedpe` 形式とは別の`.tsv.gz` データを読みこんで解析することで、`fanta.bio`との `bedtools intersect`したデータフレームと、それぞれ`join`するための核となるデータとする
- 入力: threshold 適用後の [`../../out/ENCODE_rE2G/hs_atacseq_hic_list/**/encode_e2g_predictions_threshold*.tsv.gz`](../../out/ENCODE_rE2G/hs_atacseq_hic_list)
- 未フィルタ TSV は score 分布が 0 付近に極端に偏るため、プロジェクト既定の threshold 適用後ファイルを用いる
- セクション2の `enhancer_fanta_intersect` と join できるよう、同じ規則で `re2g_dataset` を付与する（例: `GSE101731_HFF_44C_60min`）

In [10]:
# Parse ENCODE-rE2G prediction TSVs for all hs_atacseq_hic_list datasets
RE2G_TSV_ROOT = pathlib.Path("../../out/ENCODE_rE2G/hs_atacseq_hic_list")


def re2g_dataset_from_tsv_path(tsv_path: pathlib.Path) -> str:
    """
    Derive re2g_dataset IDs identical to section 2 enhancer BED tags.
    Examples:
      .../GSE101731_HFF_44C_60min_atacseq/atac_megamap/...
        -> GSE101731_HFF_44C_60min
      .../GSE154744_K562_42C_30min_atacseq_GSE130758_.../atac_intact_hic/...
        -> GSE154744_K562_42C_30min_intact_hic
    """
    biosample_dir = tsv_path.parents[1].name
    mode_dir = tsv_path.parent.name
    if mode_dir == "atac_intact_hic":
        return biosample_dir.split("_atacseq", 1)[0] + "_intact_hic"
    return biosample_dir.split("_atacseq", 1)[0]


def read_re2g_prediction_tsv(tsv_path: pathlib.Path) -> pl.DataFrame:
    """
    Read one thresholded encode_e2g_predictions_threshold*.tsv.gz and tag re2g_dataset.
    Keep normalizedATAC_prom / normalizedH3K27ac_prom as separate columns;
    fill the missing one with null.
    """
    re2g_dataset = re2g_dataset_from_tsv_path(tsv_path)
    df = pl.read_csv(tsv_path, separator="\t", n_threads=16)

    if "normalizedATAC_prom" not in df.columns:
        df = df.with_columns(pl.lit(None).cast(pl.Float64).alias("normalizedATAC_prom"))
    if "normalizedH3K27ac_prom" not in df.columns:
        df = df.with_columns(pl.lit(None).cast(pl.Float64).alias("normalizedH3K27ac_prom"))

    return (
        df.select(
            pl.col("chr").alias("re2g_chr"),
            pl.col("start").alias("re2g_start"),
            pl.col("end").alias("re2g_end"),
            "class",
            "TargetGene",
            "isSelfPromoter",
            "distanceToTSS",
            pl.col("ENCODE-rE2G.Score"),
            pl.struct(
                "TargetGeneTSS",
                "TargetGeneEnsembl_ID",
                "normalizedATAC_prom",
                "normalizedH3K27ac_prom",
                "contactFrequency",
                "numCandidateEnhGene",
                "numTSSEnhGene",
                "sumNearbyEnhancers",
            ).alias("re2g_features"),
            pl.lit(re2g_dataset).alias("re2g_dataset"),
            pl.lit(str(tsv_path)).alias("source_tsv_file"),
        )
        .unique()
    )

In [11]:
# Prefer thresholded predictions; require one file per biosample directory
biosample_dirs = sorted(
    p for p in RE2G_TSV_ROOT.iterdir()
    if p.is_dir() and p.name.startswith("GSE")
)
tsv_paths = sorted(RE2G_TSV_ROOT.glob("**/encode_e2g_predictions_threshold*.tsv.gz"))

missing = []
for biosample_dir in biosample_dirs:
    hits = list(biosample_dir.glob("**/encode_e2g_predictions_threshold*.tsv.gz"))
    if not hits:
        missing.append(biosample_dir.name)

if missing:
    raise FileNotFoundError(
        "Thresholded encode_e2g_predictions_threshold*.tsv.gz missing for: "
        + ", ".join(missing)
    )
if len(tsv_paths) != len(biosample_dirs):
    raise RuntimeError(
        f"Expected {len(biosample_dirs)} thresholded TSVs, found {len(tsv_paths)}"
    )

encode_re2g_predictions = pl.concat(
    [read_re2g_prediction_tsv(p) for p in tsv_paths],
    how="vertical_relaxed",
).sort(["re2g_chr", "re2g_start", "re2g_dataset", "TargetGene"])

pl.Config.set_tbl_rows(14)
print(f"biosamples: {len(biosample_dirs)}")
print(f"files: {len(tsv_paths)}")
print(f"datasets: {encode_re2g_predictions.select('re2g_dataset').n_unique()}")
display(
    encode_re2g_predictions.group_by("re2g_dataset")
    .len()
    .sort("re2g_dataset")
)

# Optional sanity check against section 2 dataset IDs
if "enhancer_fanta_intersect" in globals():
    bed_ids = set(enhancer_fanta_intersect["re2g_dataset"].unique().to_list())
    tsv_ids = set(encode_re2g_predictions["re2g_dataset"].unique().to_list())
    print(f"dataset ID match with section 2: {bed_ids == tsv_ids}")
    if bed_ids != tsv_ids:
        print("only in BED:", sorted(bed_ids - tsv_ids))
        print("only in TSV:", sorted(tsv_ids - bed_ids))

display(encode_re2g_predictions)

biosamples: 14
files: 14
datasets: 14

shape: (14, 2)
┌───────────────────────────────────────┬────────┐
│ re2g_dataset                          ┆ len    │
│ ---                                   ┆ ---    │
│ str                                   ┆ u32    │
╞═══════════════════════════════════════╪════════╡
│ GSE101731_HFF_44C_120min              ┆ 75736  │
│ GSE101731_HFF_44C_60min               ┆ 68326  │
│ GSE105028_hESC_42C_60min              ┆ 84031  │
│ GSE154744_K562_42C_12_5min            ┆ 82497  │
│ GSE154744_K562_42C_25min              ┆ 81946  │
│ GSE154744_K562_42C_30min              ┆ 87683  │
│ GSE154744_K562_42C_30min_intact_hic   ┆ 73543  │
│ GSE154744_K562_42C_40min              ┆ 78520  │
│ GSE154744_K562_42C_60min              ┆ 95664  │
│ GSE173536_lymphblastoid_d21_42C_60min ┆ 85446  │
│ GSE173536_lymphblastoid_t21_42C_60min ┆ 88060  │
│ GSE209675_MCF7_42C_60min              ┆ 78055  │
│ GSE267931_HUVEC_39C_120min            ┆ 100913 │
│ GSE280307_THP1_42C_120min             ┆ 87366  │
└───────────────────────────────────────┴────────┘

dataset ID match with section 2: True

shape: (1_167_786, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ re2g_chr ┆ re2g_star ┆ re2g_end  ┆ class     ┆ … ┆ ENCODE-rE ┆ re2g_feat ┆ re2g_data ┆ source_ts │
│ ---      ┆ t         ┆ ---       ┆ ---       ┆   ┆ 2G.Score  ┆ ures      ┆ set       ┆ v_file    │
│ str      ┆ ---       ┆ i64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ i64       ┆           ┆           ┆   ┆ f64       ┆ struct[8] ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr1     ┆ 778160    ┆ 779409    ┆ intergeni ┆ … ┆ 0.686411  ┆ {817370," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 177757",0 ┆ stoid_d21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .309228,n ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ull,0.058 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 239,2,2,6 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ 2.138468} ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_d21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778160    ┆ 779409    ┆ intergeni ┆ … ┆ 0.484514  ┆ {827522," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 225880",0 ┆ stoid_d21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .55434,nu ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ll,0.0990 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 37,4,4,62 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ .138468}  ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_d21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778160    ┆ 779409    ┆ intergeni ┆ … ┆ 0.48617   ┆ {827590," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 228794",0 ┆ stoid_d21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .550566,n ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ull,0.099 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 048,4,4,6 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ 2.138468} ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_d21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778163    ┆ 779660    ┆ intergeni ┆ … ┆ 0.187157  ┆ {876802," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 230368",0 ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .32222,nu ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ll,0.0136 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 26,7,5,72 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ .786715}  ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_t21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778163    ┆ 779660    ┆ intergeni ┆ … ┆ 0.458608  ┆ {827522," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 225880",0 ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .532662,n ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ull,0.099 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 016,3,4,7 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ 2.786715} ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_t21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778163    ┆ 779660    ┆ intergeni ┆ … ┆ 0.458959  ┆ {827590," ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 228794",0 ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .531404,n ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ull,0.099 ┆ n         ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 027,3,4,7 ┆           ┆ 173536_ly │
│          ┆           ┆           ┆           ┆   ┆           ┆ 2.786715} ┆           ┆ mphblasto │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ id_t21_42 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr1     ┆ 778168    ┆ 779084    ┆ intergeni ┆ … ┆ 0.305417  ┆ {827522," ┆ GSE209675 ┆ ../../out │
│          ┆           ┆           ┆ c         ┆   ┆           ┆ ENSG00000 ┆ _MCF7_42C ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 225880",0 ┆ _60min    ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ .475999,n ┆           ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ ull,0.099 ┆           ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 063,3,4,5 ┆           ┆ 209675_MC │
│          ┆           ┆           ┆           ┆   ┆           ┆ 0.59386}  ┆           ┆ F7_42C_60 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ min_atacs │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ chrX     ┆ 155612271 ┆ 155613230 ┆ promoter  ┆ … ┆ 0.999893  ┆ {15561296 ┆ GSE280307 ┆ ../../out │
│          ┆           ┆           ┆           ┆   ┆           ┆ 1,"ENSG00 ┆ _THP1_42C ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 000185973 ┆ _120min   ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ ",0.60272 ┆           ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ 9,null,0. ┆           ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 232393,0, ┆           ┆ 280307_TH │
│          ┆           ┆           ┆           ┆   ┆           ┆ 0,56.0270 ┆           ┆ P1_42C_12 │
│          ┆           ┆           ┆           ┆   ┆           ┆ 67}       ┆           ┆ 0min_atac │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ seq/atac_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ megamap/e │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ncode_e2g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _predicti │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ons_thres │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ hold0.179 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .tsv.gz   │
│ chrX     ┆ 155612298 ┆ 155613215 ┆ promoter  ┆ … ┆ 0.997377  ┆ {15561296 ┆ GSE105028 ┆ ../../out │
│          ┆           ┆           ┆           ┆   ┆           ┆ 1,"ENSG00 ┆ _hESC_42C ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 000185973 ┆ _60min    ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ ",null,0. ┆           ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ 78542,0.1 ┆           ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 8645,0,0, ┆           ┆ 105028_hE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 0.0}      ┆           ┆ SC_42C_60 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ min_atacs │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eq_hic_ch │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ romap_chi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ pseq/atac │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _h3k27ac_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ intact_hi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ c/encode_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 259.tsv.g │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chrX     ┆ 155612299 ┆ 155613211 ┆ promoter  ┆ … ┆ 0.99978   ┆ {15561296 ┆ GSE154744 ┆ ../../out │
│          ┆           ┆           ┆           ┆   ┆           ┆ 1,"ENSG00 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 000185973 ┆ _30min    ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ ",0.82543 ┆           ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ 8,null,0. ┆           ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 232393,0, ┆           ┆ 154744_K5 │
│          ┆           ┆           ┆           ┆   ┆           ┆ 0,0.0}    ┆           ┆ 62_42C_30 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ min_atacs │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chrX     ┆ 155612299 ┆ 155613211 ┆ promoter  ┆ … ┆ 0.995955  ┆ {15561296 ┆ GSE154744 ┆ ../../out │
│          ┆           ┆           ┆           ┆   ┆           ┆ 1,"ENSG00 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 000185973 ┆ _30min_in ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ ",0.82543 ┆ tact_hic  ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ 8,null,0. ┆           ┆ _list/GSE │
│          ┆           ┆           ┆           ┆   ┆           ┆ 151266,0, ┆           ┆ 154744_K5 │
│          ┆           ┆           ┆           ┆   ┆           ┆ 0,0.0}    ┆           ┆ 62_42C_30 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ min_atacs │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ eq_GSE130 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 758_K562_ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 42C_30min │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _hic/atac │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _intact_h │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ic/encode │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _e2g_pred │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ictions_t │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ hreshold0 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .232.tsv. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gz        │
│ chrX     ┆ 155612423 ┆ 155613591 ┆ promoter  ┆ … ┆ 0.999976  ┆ {15561296 ┆ GSE173536 ┆ ../../out │
│          ┆           ┆           ┆           ┆   ┆           ┆ 1,"ENSG00 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆           ┆           ┆           ┆   ┆           ┆ 000185973 ┆ stoid_d21 ┆ E2G/hs_at │
│          ┆           ┆           ┆           ┆   ┆           ┆ ",0.60021 ┆ _42C_60mi ┆ acseq_hic │
│          ┆           ┆           ┆           ┆   ┆           ┆ 3,null,0. ┆ n         ┆ _list/GSE │

In [12]:
#check
HSPA1A = encode_re2g_predictions.filter(pl.col("TargetGene") == "HSPA1A")
display(HSPA1A)

shape: (71, 11)
┌──────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ re2g_chr ┆ re2g_start ┆ re2g_end ┆ class     ┆ … ┆ ENCODE-rE ┆ re2g_feat ┆ re2g_data ┆ source_ts │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ 2G.Score  ┆ ures      ┆ set       ┆ v_file    │
│ str      ┆ i64        ┆ i64      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆          ┆           ┆   ┆ f64       ┆ struct[8] ┆ str       ┆ str       │
╞══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr6     ┆ 31812100   ┆ 31813016 ┆ genic     ┆ … ┆ 0.240285  ┆ {31815513 ┆ GSE173536 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.971693 ┆ _42C_60mi ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆ n         ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,1,2 ┆           ┆ 173536_ly │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,10221.39 ┆           ┆ mphblasto │
│          ┆            ┆          ┆           ┆   ┆           ┆ 0285}     ┆           ┆ id_t21_42 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr6     ┆ 31813242   ┆ 31813742 ┆ genic     ┆ … ┆ 0.319299  ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _40min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.850697 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,1,2 ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,3881.480 ┆           ┆ 62_42C_40 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 526}      ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31813335   ┆ 31813835 ┆ genic     ┆ … ┆ 0.183925  ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _25min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.887327 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,1,2 ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,4436.004 ┆           ┆ 62_42C_25 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 236}      ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31814090   ┆ 31815815 ┆ promoter  ┆ … ┆ 0.999676  ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _60min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.943966 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,0,0 ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,4702.115 ┆           ┆ 62_42C_60 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 493}      ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31814094   ┆ 31815763 ┆ promoter  ┆ … ┆ 0.999673  ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _40min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.850697 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,0,0 ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,609.9166 ┆           ┆ 62_42C_40 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 26}       ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31814101   ┆ 31815798 ┆ promoter  ┆ … ┆ 0.999667  ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _12_5min  ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.91411, ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ null,0.16 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 8784,0,0, ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 1171.8999 ┆           ┆ 62_42C_12 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 7}        ┆           ┆ _5min_ata │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ cseq/atac │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ _megamap/ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ encode_e2 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ g_predict │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ions_thre │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ shold0.17 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ 9.tsv.gz  │
│ chr6     ┆ 31814112   ┆ 31815815 ┆ promoter  ┆ … ┆ 0.99967   ┆ {31815513 ┆ GSE154744 ┆ ../../out │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,"ENSG000 ┆ _K562_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _25min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.887327 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.1 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 68784,0,0 ┆           ┆ 154744_K5 │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,382.1599 ┆           ┆ 62_42C_25 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 06}       ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ …        ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ chr6     ┆ 31831543   ┆ 31832656 ┆ intergeni ┆ … ┆ 0.539364  ┆ {31815513 ┆ GSE101731 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _HFF_44C_ ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ 120min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.850794 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.0 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 61341,5,2 ┆           ┆ 101731_HF │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,18060.67 ┆           ┆ F_44C_120 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 1126}     ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31831550   ┆ 31832674 ┆ intergeni ┆ … ┆ 0.324067  ┆ {31815513 ┆ GSE267931 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _HUVEC_39 ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ C_120min  ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.984177 ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.0 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 61332,7,2 ┆           ┆ 267931_HU │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,19507.39 ┆           ┆ VEC_39C_1 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 2848}     ┆           ┆ 20min_ata │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ cseq/atac │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ _megamap/ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ encode_e2 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ g_predict │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ions_thre │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ shold0.17 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ 9.tsv.gz  │
│ chr6     ┆ 31831567   ┆ 31832067 ┆ intergeni ┆ … ┆ 0.253181  ┆ {31815513 ┆ GSE209675 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _MCF7_42C ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ _60min    ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.76938, ┆           ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ null,0.06 ┆           ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 1555,9,2, ┆           ┆ 209675_MC │
│          ┆            ┆          ┆           ┆   ┆           ┆ 5142.2477 ┆           ┆ F7_42C_60 │
│          ┆            ┆          ┆           ┆   ┆           ┆ 37}       ┆           ┆ min_atacs │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ eq/atac_m │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ egamap/en │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ code_e2g_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ predictio │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ns_thresh │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ old0.179. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tsv.gz    │
│ chr6     ┆ 31831635   ┆ 31832594 ┆ intergeni ┆ … ┆ 0.258373  ┆ {31815513 ┆ GSE173536 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.971693 ┆ _42C_60mi ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.0 ┆ n         ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 6133,6,2, ┆           ┆ 173536_ly │
│          ┆            ┆          ┆           ┆   ┆           ┆ 22378.325 ┆           ┆ mphblasto │
│          ┆            ┆          ┆           ┆   ┆           ┆ 565}      ┆           ┆ id_t21_42 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr6     ┆ 31832161   ┆ 31833155 ┆ intergeni ┆ … ┆ 0.221269  ┆ {31815513 ┆ GSE173536 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ stoid_d21 ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.928675 ┆ _42C_60mi ┆ acseq_hic │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,null,0.0 ┆ n         ┆ _list/GSE │
│          ┆            ┆          ┆           ┆   ┆           ┆ 60945,5,2 ┆           ┆ 173536_ly │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,16941.75 ┆           ┆ mphblasto │
│          ┆            ┆          ┆           ┆   ┆           ┆ 4584}     ┆           ┆ id_d21_42 │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ C_60min_a │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tacseq/at │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ac_megama │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ p/encode_ │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ e2g_predi │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ ctions_th │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ reshold0. │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ 179.tsv.g │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ z         │
│ chr6     ┆ 31832666   ┆ 31833481 ┆ intergeni ┆ … ┆ 0.18974   ┆ {31815513 ┆ GSE173536 ┆ ../../out │
│          ┆            ┆          ┆ c         ┆   ┆           ┆ ,"ENSG000 ┆ _lymphbla ┆ /ENCODE_r │
│          ┆            ┆          ┆           ┆   ┆           ┆ 00204389" ┆ stoid_t21 ┆ E2G/hs_at │
│          ┆            ┆          ┆           ┆   ┆           ┆ ,0.971693 ┆ _42C_60mi ┆ acseq_hic │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. Join (1) (Information: "E")

- E-G relationships のうち、enhancer 側での統合を以下のセルで実行する

In [13]:
enhancer_fantabio_join = (
    enhancer_fanta_intersect.join(
        encode_re2g_predictions,
        on=["re2g_chr", "re2g_start", "re2g_end", "re2g_dataset"],
        how="inner"
    ).select(
        "cre_id", "cre_name", "cre_chr", "fantabio_cre_class","enhancer_cre_overlap_bp", "enhancer_cre_overlap_frac_of_fantabio_cre","TargetGene", "class","isSelfPromoter", "distanceToTSS", "ENCODE-rE2G.Score", "re2g_dataset",
        pl.struct("re2g_chr", "re2g_start", "re2g_end").alias("re2g_enhancer_locus"), # まとめる
        pl.struct("cre_start", "cre_end", "directionality").alias("fantabio_enhancer_cre"), # まとめる
        "re2g_features"  # already a struct from encode side
    )
).sort(["cre_id", "cre_name", "TargetGene", "re2g_dataset"])

display(enhancer_fantabio_join)

shape: (1_887_907, 15)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id     ┆ cre_name  ┆ cre_chr ┆ fantabio_ ┆ … ┆ re2g_data ┆ re2g_enha ┆ fantabio_ ┆ re2g_feat │
│ ---        ┆ ---       ┆ ---     ┆ cre_class ┆   ┆ set       ┆ ncer_locu ┆ enhancer_ ┆ ures      │
│ str        ┆ str       ┆ str     ┆ ---       ┆   ┆ ---       ┆ s         ┆ cre       ┆ ---       │
│            ┆           ┆         ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ struct[8] │
│            ┆           ┆         ┆           ┆   ┆           ┆ struct[3] ┆ struct[3] ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE105028 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _hESC_42C ┆ 60336,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 751}      ┆ 483871}   ┆ 187961",n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.576 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 527,0.236 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 217,0,0,1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 70.367064 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _K562_42C ┆ 60302,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _25min    ┆ 023}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ .512267,n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 44.856436 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _K562_42C ┆ 60315,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _40min    ┆ 025}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ .572631,n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 82.531976 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _K562_42C ┆ 60322,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 067}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ .503581,n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,3 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 13.411192 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _lymphbla ┆ 60335,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_d21 ┆ 565}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆           ┆ .478225,n │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 09.961424 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _lymphbla ┆ 60323,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_t21 ┆ 242}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆           ┆ .461337,n │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 33.348032 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE209675 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _MCF7_42C ┆ 60325,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 036}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ .377504,n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 28.99544} │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE101731 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _HFF_44C_ ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ 60min     ┆ 85037164} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.464773 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE105028 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _hESC_42C ┆ 85035799, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 85036619} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,null,0.4 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 49942,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 52177,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _lymphbla ┆ 85035800, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_d21 ┆ 85036788} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆ }         ┆ ,0.399473 │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _lymphbla ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_t21 ┆ 85036799} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆ }         ┆ ,0.408836 │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE209675 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _MCF7_42C ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 85036791} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.724572 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99995 ┆ FCHS_9999 ┆ chr12   ┆ ELA       ┆ … ┆ GSE101731 ┆ {"chr12", ┆ {85036875 ┆ {85036320 │
│            ┆ 5         ┆         ┆           ┆   ┆ _HFF_44C_ ┆ 85036027, ┆ ,85037490 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ 60min     ┆ 85037164} ┆ ,0.83908} ┆ 00133640" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.470943 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99995 ┆ FCHS_9999 ┆ chr12   ┆ ELA       ┆ … ┆ GSE101731 ┆ {"chr12", ┆ {85036875 ┆ {85036277 │
│            ┆ 5         ┆         ┆           ┆   ┆ _HFF_44C_ ┆ 85036027, ┆ ,85037490 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ 60min     ┆ 85037164} ┆ ,0.83908} ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.464773 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
print(f"ENCODE-rE2G overlap 1st quartile: {enhancer_fantabio_join.select("enhancer_cre_overlap_frac_of_fantabio_cre").to_series().quantile(0.25)}")
print(f"ENCODE-rE2G overlap median: {enhancer_fantabio_join.select("enhancer_cre_overlap_frac_of_fantabio_cre").to_series().median()}")
print(f"ENCODE-rE2G overlap 3rd quartile: {enhancer_fantabio_join.select("enhancer_cre_overlap_frac_of_fantabio_cre").to_series().quantile(0.75)}")

print(f"ENCODE-rE2G overlap mean: {enhancer_fantabio_join.select("ENCODE-rE2G.Score").to_series().mean()}")
print(f"ENCODE-rE2G overlap standard deviation: {enhancer_fantabio_join.select("ENCODE-rE2G.Score").to_series().std()}")

ENCODE-rE2G overlap 1st quartile: 0.6130790190735694
ENCODE-rE2G overlap median: 0.9851485148514851
ENCODE-rE2G overlap 3rd quartile: 1.0
ENCODE-rE2G overlap mean: 0.6655196171701648
ENCODE-rE2G overlap standard deviation: 0.32213403720084915

&nbsp;

&nbsp;

### ENCODE rE2G score

- 中央値、第3四分位数などを調べておき、フィルタリングの条件に使用する
- ただし、それぞれのデータセットでは、異なる機械学習モデルを使用しており、あくまで参考程度に留めるべき値だと考えられる

In [15]:
print(f"ENCODE-rE2G score 1st quartile: {enhancer_fantabio_join['ENCODE-rE2G.Score'].quantile(0.25)}")
print(f"ENCODE-rE2G score median: {enhancer_fantabio_join['ENCODE-rE2G.Score'].median()}")
print(f"ENCODE-rE2G score 3rd quartile: {enhancer_fantabio_join['ENCODE-rE2G.Score'].quantile(0.75)}")
print(f"ENCODE-rE2G score mean: {enhancer_fantabio_join['ENCODE-rE2G.Score'].mean()}")
print(f"ENCODE-rE2G score standard deviation: {enhancer_fantabio_join['ENCODE-rE2G.Score'].std()}")

ENCODE-rE2G score 1st quartile: 0.3254861794176
ENCODE-rE2G score median: 0.7179793744815547
ENCODE-rE2G score 3rd quartile: 0.999678266372826
ENCODE-rE2G score mean: 0.6655196171701648
ENCODE-rE2G score standard deviation: 0.32213403720084915

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. Filter (1) (Information: "E") (IMPORTANT!)

- `ENCODE-rE2G`で予測された enhancer 領域と、`fanta.bio`で定義されているCREのカバー率に基づいてフィルタリング
- fanta.bio の CRE とのカバー率でフィルタリング
- `enhancer_cre_overlap_bp` / (`cre_end` - `cre_start`)

In [16]:
enhancer_fantabio_join_filter = enhancer_fantabio_join.filter(
    pl.col("enhancer_cre_overlap_frac_of_fantabio_cre") >= 0.5
)

display(enhancer_fantabio_join_filter)

shape: (1_507_996, 15)
┌────────────┬───────────┬─────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id     ┆ cre_name  ┆ cre_chr ┆ fantabio_ ┆ … ┆ re2g_data ┆ re2g_enha ┆ fantabio_ ┆ re2g_feat │
│ ---        ┆ ---       ┆ ---     ┆ cre_class ┆   ┆ set       ┆ ncer_locu ┆ enhancer_ ┆ ures      │
│ str        ┆ str       ┆ str     ┆ ---       ┆   ┆ ---       ┆ s         ┆ cre       ┆ ---       │
│            ┆           ┆         ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ struct[8] │
│            ┆           ┆         ┆           ┆   ┆           ┆ struct[3] ┆ struct[3] ┆           │
╞════════════╪═══════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE105028 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _hESC_42C ┆ 60336,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 751}      ┆ 483871}   ┆ 187961",n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.576 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 527,0.236 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 217,0,0,1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 70.367064 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _lymphbla ┆ 60335,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_d21 ┆ 565}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆           ┆ .478225,n │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 09.961424 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _lymphbla ┆ 60323,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_t21 ┆ 242}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆           ┆ .461337,n │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,2 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 33.348032 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_100   ┆ cp6@KLHL1 ┆ chr1    ┆ ELA       ┆ … ┆ GSE267931 ┆ {"chr1",9 ┆ {960949,9 ┆ {960586," │
│            ┆ 7         ┆         ┆           ┆   ┆ _HUVEC_39 ┆ 60336,961 ┆ 61425,-0. ┆ ENSG00000 │
│            ┆           ┆         ┆           ┆   ┆ C_120min  ┆ 578}      ┆ 483871}   ┆ 187961",0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ .501016,n │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ull,0.259 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 602,0,0,4 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 15.927582 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ }         │
│ FCHS_1000  ┆ cp2@RER1  ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",2 ┆ {2392324, ┆ {2391751, │
│            ┆           ┆         ┆           ┆   ┆ _K562_42C ┆ 392202,23 ┆ 2392982,0 ┆ "ENSG0000 │
│            ┆           ┆         ┆           ┆   ┆ _25min    ┆ 92702}    ┆ .0}       ┆ 0116151", │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0.859092, │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ null,0.20 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 7712,0,0, │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 1270.7477 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 82}       │
│ FCHS_1000  ┆ cp2@RER1  ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",2 ┆ {2392324, ┆ {2391774, │
│            ┆           ┆         ┆           ┆   ┆ _K562_42C ┆ 392202,23 ┆ 2392982,0 ┆ "ENSG0000 │
│            ┆           ┆         ┆           ┆   ┆ _25min    ┆ 92702}    ┆ .0}       ┆ 0157916", │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 0.859842, │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ null,0.20 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 7712,0,0, │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 1270.7477 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 82}       │
│ FCHS_10001 ┆ FCHS_1000 ┆ chr1    ┆ ELA       ┆ … ┆ GSE154744 ┆ {"chr1",3 ┆ {33097084 ┆ {33082177 │
│            ┆ 1         ┆         ┆           ┆   ┆ _K562_42C ┆ 3097150,3 ┆ ,33097503 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ _25min    ┆ 3097650}  ┆ ,0.614679 ┆ 00142920" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.383964 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 44833,2,1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,220.5978 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 81}       │
│ …          ┆ …         ┆ …       ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr12", ┆ {85036596 ┆ {85036320 │
│            ┆ 1         ┆         ┆           ┆   ┆ _lymphbla ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_t21 ┆ 85036799} ┆ ,0.333333 ┆ 00133640" │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆ }         ┆ ,0.409078 │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE209675 ┆ {"chr12", ┆ {85036596 ┆ {85036320 │
│            ┆ 1         ┆         ┆           ┆   ┆ _MCF7_42C ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 85036791} ┆ ,0.333333 ┆ 00133640" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.728491 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE101731 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _HFF_44C_ ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ 120min    ┆ 85036819} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.410312 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE101731 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _HFF_44C_ ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ 60min     ┆ 85037164} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.464773 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _lymphbla ┆ 85035800, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_d21 ┆ 85036788} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆ }         ┆ ,0.399473 │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE173536 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _lymphbla ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ stoid_t21 ┆ 85036799} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆ _42C_60mi ┆           ┆ }         ┆ ,0.408836 │
│            ┆           ┆         ┆           ┆   ┆ n         ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
│ FCHS_99994 ┆ cp1@LRRIQ ┆ chr12   ┆ ELA       ┆ … ┆ GSE209675 ┆ {"chr12", ┆ {85036596 ┆ {85036277 │
│            ┆ 1         ┆         ┆           ┆   ┆ _MCF7_42C ┆ 85036027, ┆ ,85036692 ┆ ,"ENSG000 │
│            ┆           ┆         ┆           ┆   ┆ _60min    ┆ 85036791} ┆ ,0.333333 ┆ 00231738" │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆ }         ┆ ,0.724572 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,null,0.1 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ 92534,0,0 │
│            ┆           ┆         ┆           ┆   ┆           ┆           ┆           ┆ ,0.0}     │
└────────────┴───────────┴─────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 6. Join (2) (Information: "G")

- target 側のデータ (fanta.bio との統合をおこなった状態)を統合する

&nbsp;

## 6-1: Fomatting for `join`

In [17]:
encodere2g_tatget_refseq_best_cre_select = encodere2g_tatget_refseq_best_cre.select(
    "TargetGene",
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    pl.struct("tss_chr", "tss_start", "tss_end", "tss_score", "tss_strand").alias("target_tss_info"),
    pl.struct("cre_chr", "cre_start", "cre_end", "cre_score", "cre_strand", "cre_thick_start", "cre_thick_end", "cre_rgb", "pooled_cre_scores", "directionality").alias("target_cre_info"),
    pl.struct("tss_cre_overlap_bp", "tss_cre_overlap_frac_of_tss").alias("target_cre_overlap_info")
).rename(
    {
        "cre_id": "target_cre_id",
        "cre_name": "target_cre_name",
        "fantabio_cre_class": "target_fantabio_cre_class"      
    }
)

display(encodere2g_tatget_refseq_best_cre_select)

shape: (20_766, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ TargetGene ┆ target_cre_i ┆ target_cre_n ┆ target_fant ┆ target_tss_ ┆ target_cre_ ┆ target_cre_ │
│ ---        ┆ d            ┆ ame          ┆ abio_cre_cl ┆ info        ┆ info        ┆ overlap_inf │
│ str        ┆ ---          ┆ ---          ┆ ass         ┆ ---         ┆ ---         ┆ o           │
│            ┆ str          ┆ str          ┆ ---         ┆ struct[5]   ┆ struct[10]  ┆ ---         │
│            ┆              ┆              ┆ str         ┆             ┆             ┆ struct[2]   │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ A1BG       ┆ FCHS_214135  ┆ cp1@A1BG     ┆ PLA         ┆ {"chr19",58 ┆ {"chr19",58 ┆ {318,0.636} │
│            ┆              ┆              ┆             ┆ 353249,5835 ┆ 353431,5835 ┆             │
│            ┆              ┆              ┆             ┆ 3749,0,"-"} ┆ 3819,0,".", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 58353468,58 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 353803,"0,0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ,204","dire ┆             │
│            ┆              ┆              ┆             ┆             ┆ ctionality: ┆             │
│            ┆              ┆              ┆             ┆             ┆ -0.999634|c ┆             │
│            ┆              ┆              ┆             ┆             ┆ lass:PLA",- ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.999634}   ┆             │
│ A1CF       ┆ FCHS_49959   ┆ cp1@A1CF     ┆ PLA         ┆ {"chr10",50 ┆ {"chr10",50 ┆ {246,0.492} │
│            ┆              ┆              ┆             ┆ 885425,5088 ┆ 885528,5088 ┆             │
│            ┆              ┆              ┆             ┆ 5925,0,"-"} ┆ 5774,0,".", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 50885634,50 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 885770,"0,0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ,204","dire ┆             │
│            ┆              ┆              ┆             ┆             ┆ ctionality: ┆             │
│            ┆              ┆              ┆             ┆             ┆ -0.999645|c ┆             │
│            ┆              ┆              ┆             ┆             ┆ lass:PLA",- ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.999645}   ┆             │
│ A2M        ┆ FCHS_88190   ┆ cp1@A2M      ┆ PLA         ┆ {"chr12",91 ┆ {"chr12",91 ┆ {473,0.946} │
│            ┆              ┆              ┆             ┆ 15979,91164 ┆ 15751,91164 ┆             │
│            ┆              ┆              ┆             ┆ 79,0,"-"}   ┆ 52,0,".",91 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 15913,91162 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 83,"0,0,204 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ","directio ┆             │
│            ┆              ┆              ┆             ┆             ┆ nality:-0.9 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 99764|class ┆             │
│            ┆              ┆              ┆             ┆             ┆ :PLA",-0.99 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 9764}       ┆             │
│ A2M-AS1    ┆ FCHS_88157   ┆ cp2@A2M-AS1, ┆ PLA         ┆ {"chr12",90 ┆ {"chr12",90 ┆ {459,0.918} │
│            ┆              ┆ cp1@LINC0061 ┆             ┆ 64926,90654 ┆ 64873,90653 ┆             │
│            ┆              ┆ 2            ┆             ┆ 26,0,"+"}   ┆ 85,0,".",90 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 65079,90652 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 68,"0,0,102 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ","directio ┆             │
│            ┆              ┆              ┆             ┆             ┆ nality:-0.4 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 80891|class ┆             │
│            ┆              ┆              ┆             ┆             ┆ :PLA",-0.48 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0891}       ┆             │
│ A2ML1      ┆ FCHS_88093   ┆ cp7@A2ML1    ┆ PLA         ┆ {"chr12",88 ┆ {"chr12",88 ┆ {277,0.554} │
│            ┆              ┆              ┆             ┆ 22221,88227 ┆ 22444,88227 ┆             │
│            ┆              ┆              ┆             ┆ 21,0,"+"}   ┆ 25,0,".",88 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 22444,88226 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 20,"255,0,0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ","directio ┆             │
│            ┆              ┆              ┆             ┆             ┆ nality:1|cl ┆             │
│            ┆              ┆              ┆             ┆             ┆ ass:PLA",1. ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0}          ┆             │
│ A4GALT     ┆ FCHS_276044  ┆ cp4@A4GALT,c ┆ PLA         ┆ {"chr22",42 ┆ {"chr22",42 ┆ {461,0.922} │
│            ┆              ┆ p5@CYB5R3    ┆             ┆ 720660,4272 ┆ 720635,4272 ┆             │
│            ┆              ┆              ┆             ┆ 1160,0,"-"} ┆ 1121,0,".", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 42720828,42 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 720942,"0,0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ,204","dire ┆             │
│            ┆              ┆              ┆             ┆             ┆ ctionality: ┆             │
│            ┆              ┆              ┆             ┆             ┆ -0.999079|c ┆             │
│            ┆              ┆              ┆             ┆             ┆ lass:PLA",- ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.999079}   ┆             │
│ AAAS       ┆ FCHS_95187   ┆ cp11@AAAS    ┆ PLA         ┆ {"chr12",53 ┆ {"chr12",53 ┆ {418,0.836} │
│            ┆              ┆              ┆             ┆ 321378,5332 ┆ 321460,5332 ┆             │
│            ┆              ┆              ┆             ┆ 1878,0,"-"} ┆ 2000,0,".", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 53321591,53 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 321702,"0,0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ,204","dire ┆             │
│            ┆              ┆              ┆             ┆             ┆ ctionality: ┆             │
│            ┆              ┆              ┆             ┆             ┆ -0.989867|c ┆             │
│            ┆              ┆              ┆             ┆             ┆ lass:PLA",- ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.989867}   ┆             │
│ …          ┆ …            ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           │
│ ZXDB       ┆ FCHS_440127  ┆ cp3@ZXDB     ┆ ELA         ┆ {"chrX",575 ┆ {"chrX",575 ┆ {268,0.536} │
│            ┆              ┆              ┆             ┆ 91585,57592 ┆ 91492,57591 ┆             │
│            ┆              ┆              ┆             ┆ 085,0,"+"}  ┆ 853,0,".",5 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 7591614,575 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 91733,"255, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 202,74","di ┆             │
│            ┆              ┆              ┆             ┆             ┆ rectionalit ┆             │
│            ┆              ┆              ┆             ┆             ┆ y:0.939394| ┆             │
│            ┆              ┆              ┆             ┆             ┆ class:ELA", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.939394}   ┆             │
│ ZXDC       ┆ FCHS_294087  ┆ cp5@ZXDC     ┆ PLA         ┆ {"chr3",126 ┆ {"chr3",126 ┆ {436,0.872} │
│            ┆              ┆              ┆             ┆ 475669,1264 ┆ 475733,1264 ┆             │
│            ┆              ┆              ┆             ┆ 76169,0,"-" ┆ 76398,0,"." ┆             │
│            ┆              ┆              ┆             ┆ }           ┆ ,126475886, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 126476245," ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0,0,204","d ┆             │
│            ┆              ┆              ┆             ┆             ┆ irectionali ┆             │
│            ┆              ┆              ┆             ┆             ┆ ty:-0.91113 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 9|class:PLA ┆             │
│            ┆              ┆              ┆             ┆             ┆ ",-0.911139 ┆             │
│            ┆              ┆              ┆             ┆             ┆ }           ┆             │
│ ZYG11A     ┆ FCHS_14185   ┆ cp3@ZYG11A   ┆ PLA         ┆ {"chr1",528 ┆ {"chr1",528 ┆ {242,0.484} │
│            ┆              ┆              ┆             ┆ 42260,52842 ┆ 42518,52843 ┆             │
│            ┆              ┆              ┆             ┆ 760,0,"+"}  ┆ 050,0,".",5 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 2842663,528 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 42847,"204, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0,0","direc ┆             │
│            ┆              ┆              ┆             ┆             ┆ tionality:0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ .983865|cla ┆             │
│            ┆              ┆              ┆             ┆             ┆ ss:PLA",0.9 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 83865}      ┆             │
│ ZYG11B     ┆ FCHS_14172   ┆ cp5@ZYG11B   ┆ PLA         ┆ {"chr1",527 ┆ {"chr1",527 ┆ {280,0.56}  │
│            ┆              ┆              ┆             ┆ 26208,52726 ┆ 26374,52726 ┆             │
│            ┆              ┆              ┆             ┆ 708,0,"+"}  ┆ 654,0,".",5 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 2726374,527 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 26463,"255, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0,0","direc ┆             │
│            ┆              ┆              ┆             ┆             ┆ tionality:1 ┆             │
│            ┆              ┆              ┆             ┆             ┆ |class:PLA" ┆             │
│            ┆              ┆              ┆             ┆             ┆ ,1.0}       ┆             │
│ ZYX        ┆ FCHS_393394  ┆ cp3@FAM131B- ┆ PLA         ┆ {"chr7",143 ┆ {"chr7",143 ┆ {500,1.0}   │
│            ┆              ┆ AS2,cp6@ZYX  ┆             ┆ 381016,1433 ┆ 380745,1433 ┆             │
│            ┆              ┆              ┆             ┆ 81516,0,"+" ┆ 81545,0,"." ┆             │
│            ┆              ┆              ┆             ┆ }           ┆ ,143380966, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 143381350," ┆             │
│            ┆              ┆              ┆             ┆             ┆ 204,0,0","d ┆             │
│            ┆              ┆              ┆             ┆             ┆ irectionali ┆             │
│            ┆              ┆              ┆             ┆             ┆ ty:0.92677| ┆             │
│            ┆              ┆              ┆             ┆             ┆ class:PLA", ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.92677}    ┆             │
│ ZZEF1      ┆ FCHS_165180  ┆ cp2@CYB5D2,c ┆ PLA         ┆ {"chr17",41 ┆ {"chr17",41 ┆ {385,0.77}  │
│            ┆              ┆ p2@ZZEF1     ┆             ┆ 42709,41432 ┆ 42824,41434 ┆             │
│            ┆              ┆              ┆             ┆ 09,0,"-"}   ┆ 16,0,".",41 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 43022,41432 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 06,"0,0,153 ┆             │
│            ┆              ┆              ┆             ┆             ┆ ","directio ┆             │
│            ┆              ┆              ┆             ┆             ┆ nality:-0.6 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 47921|class ┆             │
│            ┆              ┆              ┆             ┆             ┆ :PLA",-0.64 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 7921}       ┆             │
│ ZZZ3       ┆ FCHS_17233   ┆ cp3@ZZZ3     ┆ PLA         ┆ {"chr1",776 ┆ {"chr1",776 ┆ {445,0.89}  │
│            ┆              ┆              ┆             ┆ 82408,77682 ┆ 82463,77683 ┆             │
│            ┆              ┆              ┆             ┆ 908,0,"-"}  ┆ 068,0,".",7 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 7682658,776 ┆             │
│            ┆              ┆              ┆             ┆             ┆ 82722,"0,0, ┆             │
│            ┆              ┆              ┆             ┆             ┆ 204","direc ┆             │
│            ┆              ┆              ┆             ┆             ┆ tionality:- ┆             │
│            ┆              ┆              ┆             ┆             ┆ 0.993424|cl ┆             │
│            ┆              ┆              ┆             ┆             ┆ ass:PLA",-0 ┆             │
│            ┆              ┆              ┆             ┆             ┆ .993424}    ┆             │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

&nbsp;

&nbsp;

## 6-2: Join

In [18]:
e2g_join = enhancer_fantabio_join_filter.join(
    encodere2g_tatget_refseq_best_cre_select,
    on=["TargetGene"],
    how="inner"
).select(
    # 見やすいように列順を変更
    "ENCODE-rE2G.Score",
    "re2g_dataset",
    "cre_id",
    "cre_name",
    "cre_chr",
    "fantabio_cre_class",
    "enhancer_cre_overlap_bp",
    "enhancer_cre_overlap_frac_of_fantabio_cre",
    "TargetGene",
    "target_cre_id",
    "target_cre_name",
    "target_fantabio_cre_class",
    "class",
    "isSelfPromoter",
    "distanceToTSS",
    "re2g_enhancer_locus",
    "fantabio_enhancer_cre",
    "re2g_features",
    "target_tss_info",
    "target_cre_info",
    "target_cre_overlap_info"
)

e2g_join.write_parquet(
    # 保存するのは、フィルタリング後のデータ
    f"../../out/ENCODE_rE2G/parquet_file/encode_re2g_hs_join_v{execute_date}.parquet"
)

display(e2g_join)

shape: (1_468_274, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENCODE-rE ┆ re2g_data ┆ cre_id    ┆ cre_name  ┆ … ┆ re2g_feat ┆ target_ts ┆ target_cr ┆ target_c │
│ 2G.Score  ┆ set       ┆ ---       ┆ ---       ┆   ┆ ures      ┆ s_info    ┆ e_info    ┆ re_overl │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ap_info  │
│ f64       ┆ str       ┆           ┆           ┆   ┆ struct[8] ┆ struct[5] ┆ struct[10 ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ]         ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.999461  ┆ GSE105028 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _hESC_42C ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ _60min    ┆           ┆           ┆   ┆ 187961",n ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆           ┆   ┆ ull,0.576 ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 527,0.236 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 217,0,0,1 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 70.367064 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999857  ┆ GSE173536 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _lymphbla ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ .478225,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,2 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 09.961424 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999926  ┆ GSE173536 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _lymphbla ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ stoid_t21 ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ .461337,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,2 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 33.348032 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999851  ┆ GSE267931 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _HUVEC_39 ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆           ┆   ┆ .501016,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,4 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 15.927582 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999568  ┆ GSE154744 ┆ FCHS_1000 ┆ cp2@RER1  ┆ … ┆ {2391751, ┆ {"chr1",2 ┆ {"chr1",2 ┆ {500,1.0 │
│           ┆ _K562_42C ┆           ┆           ┆   ┆ "ENSG0000 ┆ 391501,23 ┆ 391399,23 ┆ }        │
│           ┆ _25min    ┆           ┆           ┆   ┆ 0116151", ┆ 92001,0," ┆ 92038,0," ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.859092, ┆ -"}       ┆ .",239155 ┆          │
│           ┆           ┆           ┆           ┆   ┆ null,0.20 ┆           ┆ 4,2391837 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7712,0,0, ┆           ┆ ,"0,0,0", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1270.7477 ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆ 82}       ┆           ┆ nality:-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .131564|c ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lass:PLA" ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ,-0.13156 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4}        ┆          │
│ 0.998301  ┆ GSE154744 ┆ FCHS_1000 ┆ cp2@RER1  ┆ … ┆ {2391774, ┆ {"chr1",2 ┆ {"chr1",2 ┆ {500,1.0 │
│           ┆ _K562_42C ┆           ┆           ┆   ┆ "ENSG0000 ┆ 391524,23 ┆ 391399,23 ┆ }        │
│           ┆ _25min    ┆           ┆           ┆   ┆ 0157916", ┆ 92024,0," ┆ 92038,0," ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.859842, ┆ +"}       ┆ .",239155 ┆          │
│           ┆           ┆           ┆           ┆   ┆ null,0.20 ┆           ┆ 4,2391837 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7712,0,0, ┆           ┆ ,"0,0,0", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1270.7477 ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆ 82}       ┆           ┆ nality:-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .131564|c ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lass:PLA" ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ,-0.13156 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4}        ┆          │
│ 0.342709  ┆ GSE154744 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _K562_42C ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ _25min    ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.383964 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44833,2,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,220.5978 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 81}       ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.99996   ┆ GSE173536 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036320 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _lymphbla ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036070, ┆ 85036236, ┆ 24}      │
│           ┆ stoid_t21 ┆           ┆           ┆   ┆ 00133640" ┆ 85036570, ┆ 85036498, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.409078 ┆ 0,"+"}    ┆ 0,".",850 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999926  ┆ GSE209675 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036320 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _MCF7_42C ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036070, ┆ 85036236, ┆ 24}      │
│           ┆ _60min    ┆           ┆           ┆   ┆ 00133640" ┆ 85036570, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.728491 ┆ 0,"+"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999937  ┆ GSE101731 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.410312 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999844  ┆ GSE101731 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.464773 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999993  ┆ GSE173536 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _lymphbla ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.399473 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999942  ┆ GSE173536 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _lymphbla ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ stoid_t21 ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.408836 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999891  ┆ GSE209675 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _MCF7_42C ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ _60min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.724572 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 7.  Enhancer-target Region Unique Count

- enhancer 側で統合した `fanta.bio` の `cre_id` と Target 側の領域として統合した `fanta.bio`の `target_cre_id` の unique pair をカウントする
- `re2g_dataset` カラムのカウントも行う

In [19]:
e2g_join_unique_count = e2g_join.group_by(
    "cre_id",
    "fantabio_cre_class",
    "target_cre_id",
    "target_fantabio_cre_class",
    # "isSelfPromoter" (この値は遺伝子ごとに異なるのでグループ化しない)
).agg(
    pl.col("re2g_dataset").unique().alias("re2g_dataset"),
    pl.col("re2g_dataset").n_unique().alias("re2g_dataset_count"),
    pl.col("ENCODE-rE2G.Score").alias("ENCODE-rE2G.Score"),
    
    pl.col("ENCODE-rE2G.Score").min().alias("ENCODE-rE2G.Score_min"),
    pl.col("ENCODE-rE2G.Score").max().alias("ENCODE-rE2G.Score_max"),
    pl.col("ENCODE-rE2G.Score").mean().alias("ENCODE-rE2G.Score_mean"),

    # pl.col("ENCODE-rE2G.Score").quantile(0.25).alias("ENCODE-rE2G.Score_q1"),
    # pl.col("ENCODE-rE2G.Score").median().alias("ENCODE-rE2G.Score_median"),
    # pl.col("ENCODE-rE2G.Score").quantile(0.75).alias("ENCODE-rE2G.Score_q3"),
    # pl.col("ENCODE-rE2G.Score").std().alias("ENCODE-rE2G.Score_std"),
    
).sort(
    by=["re2g_dataset_count"],
    descending=True
)


print(f"ENCODE-rE2G enhancer - target region interaction unique pair count: {e2g_join_unique_count.select(['cre_id', 'target_cre_id']).n_unique()}")
display(e2g_join_unique_count)

ENCODE-rE2G enhancer - target region interaction unique pair count: 423357

shape: (423_357, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ fantabio_ ┆ target_cr ┆ target_fa ┆ … ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-r │
│ ---       ┆ cre_class ┆ e_id      ┆ ntabio_cr ┆   ┆ 2G.Score  ┆ 2G.Score_ ┆ 2G.Score_ ┆ E2G.Scor │
│ str       ┆ ---       ┆ ---       ┆ e_class   ┆   ┆ ---       ┆ min       ┆ max       ┆ e_mean   │
│           ┆ str       ┆ str       ┆ ---       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_3552 ┆ PLA       ┆ FCHS_3552 ┆ PLA       ┆ … ┆ [0.999932 ┆ 0.99825   ┆ 1.0       ┆ 0.999756 │
│ 23        ┆           ┆ 23        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999914, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999907] ┆           ┆           ┆          │
│ FCHS_4595 ┆ ELA       ┆ FCHS_3921 ┆ PLA       ┆ … ┆ [0.999839 ┆ 0.985544  ┆ 0.999864  ┆ 0.998699 │
│ 87        ┆           ┆ 9         ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999454, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999725] ┆           ┆           ┆          │
│ FCHS_3731 ┆ PLA       ┆ FCHS_3731 ┆ PLA       ┆ … ┆ [0.999796 ┆ 0.996349  ┆ 0.999864  ┆ 0.999531 │
│ 66        ┆           ┆ 66        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999728, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999864] ┆           ┆           ┆          │
│ FCHS_2310 ┆ ELA       ┆ FCHS_2310 ┆ PLA       ┆ … ┆ [0.998943 ┆ 0.991033  ┆ 0.999879  ┆ 0.998553 │
│ 27        ┆           ┆ 26        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999308, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999576] ┆           ┆           ┆          │
│ FCHS_1746 ┆ PLA       ┆ FCHS_1746 ┆ PLA       ┆ … ┆ [0.999951 ┆ 0.997844  ┆ 0.999973  ┆ 0.999627 │
│ 97        ┆           ┆ 97        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999967, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999962] ┆           ┆           ┆          │
│ FCHS_1894 ┆ PLA       ┆ FCHS_1894 ┆ PLA       ┆ … ┆ [0.999919 ┆ 0.998462  ┆ 0.99997   ┆ 0.999701 │
│ 31        ┆           ┆ 33        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999912, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.99986]  ┆           ┆           ┆          │
│ FCHS_2574 ┆ PLA       ┆ FCHS_2574 ┆ ELA       ┆ … ┆ [0.999758 ┆ 0.997888  ┆ 0.999844  ┆ 0.99958  │
│ 69        ┆           ┆ 70        ┆           ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.999452, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.99945]  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_5851 ┆ ELA       ┆ FCHS_4200 ┆ PLA       ┆ … ┆ [0.213788 ┆ 0.213788  ┆ 0.213788  ┆ 0.213788 │
│ 35        ┆           ┆ 37        ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_2029 ┆ ELA       ┆ FCHS_2028 ┆ PLA       ┆ … ┆ [0.267417 ┆ 0.267417  ┆ 0.267417  ┆ 0.267417 │
│ 01        ┆           ┆ 85        ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_5714 ┆ ELA       ┆ FCHS_5712 ┆ PLA       ┆ … ┆ [0.225833 ┆ 0.225833  ┆ 0.225833  ┆ 0.225833 │
│ 0         ┆           ┆ 9         ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_9736 ┆ ELA       ┆ FCHS_9743 ┆ PLA       ┆ … ┆ [0.513856 ┆ 0.513856  ┆ 0.513856  ┆ 0.513856 │
│ 2         ┆           ┆ 7         ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_4907 ┆ ELA       ┆ FCHS_1350 ┆ PLA       ┆ … ┆ [0.365376 ┆ 0.365376  ┆ 0.365376  ┆ 0.365376 │
│ 32        ┆           ┆ 77        ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_5241 ┆ ELA       ┆ FCHS_2346 ┆ PLA       ┆ … ┆ [0.280275 ┆ 0.280275  ┆ 0.280275  ┆ 0.280275 │
│ 51        ┆           ┆ 05        ┆           ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_1244 ┆ ELA       ┆ FCHS_1245 ┆ PLA       ┆ … ┆ [0.324521 ┆ 0.324521  ┆ 0.324521  ┆ 0.324521 │
│ 33        ┆           ┆ 25        ┆           ┆   ┆ ]         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8. Check `isSelfPromoter`

&nbsp;

&nbsp;

&nbsp;

## 8-0: Selection of proximal enhancer

- `isSelfPromoter == True` でフィルタリングする

In [32]:
e2g_join_self_promoter = e2g_join.filter(
    pl.col("isSelfPromoter") == True
)

e2g_join_self_promoter.write_parquet(
    f"../../out/ENCODE_rE2G/parquet_file/encode_re2g_hs_join_self_promoter_v{execute_date}.parquet"
)

display(e2g_join_self_promoter)

shape: (566_063, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENCODE-rE ┆ re2g_data ┆ cre_id    ┆ cre_name  ┆ … ┆ re2g_feat ┆ target_ts ┆ target_cr ┆ target_c │
│ 2G.Score  ┆ set       ┆ ---       ┆ ---       ┆   ┆ ures      ┆ s_info    ┆ e_info    ┆ re_overl │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ap_info  │
│ f64       ┆ str       ┆           ┆           ┆   ┆ struct[8] ┆ struct[5] ┆ struct[10 ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ]         ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.999461  ┆ GSE105028 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _hESC_42C ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ _60min    ┆           ┆           ┆   ┆ 187961",n ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆           ┆   ┆ ull,0.576 ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 527,0.236 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 217,0,0,1 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 70.367064 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999857  ┆ GSE173536 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _lymphbla ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ .478225,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,2 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 09.961424 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999926  ┆ GSE173536 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _lymphbla ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ stoid_t21 ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ .461337,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,2 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 33.348032 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999851  ┆ GSE267931 ┆ FCHS_100  ┆ cp6@KLHL1 ┆ … ┆ {960586," ┆ {"chr1",9 ┆ {"chr1",9 ┆ {455,0.9 │
│           ┆ _HUVEC_39 ┆           ┆ 7         ┆   ┆ ENSG00000 ┆ 60336,960 ┆ 60174,960 ┆ 1}       │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 187961",0 ┆ 836,0,"+" ┆ 791,0,"." ┆          │
│           ┆           ┆           ┆           ┆   ┆ .501016,n ┆ }         ┆ ,960534,9 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ull,0.259 ┆           ┆ 60591,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 602,0,0,4 ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆ 15.927582 ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ lity:0.86 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4177|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 864177}   ┆          │
│ 0.999568  ┆ GSE154744 ┆ FCHS_1000 ┆ cp2@RER1  ┆ … ┆ {2391751, ┆ {"chr1",2 ┆ {"chr1",2 ┆ {500,1.0 │
│           ┆ _K562_42C ┆           ┆           ┆   ┆ "ENSG0000 ┆ 391501,23 ┆ 391399,23 ┆ }        │
│           ┆ _25min    ┆           ┆           ┆   ┆ 0116151", ┆ 92001,0," ┆ 92038,0," ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.859092, ┆ -"}       ┆ .",239155 ┆          │
│           ┆           ┆           ┆           ┆   ┆ null,0.20 ┆           ┆ 4,2391837 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7712,0,0, ┆           ┆ ,"0,0,0", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1270.7477 ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆ 82}       ┆           ┆ nality:-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .131564|c ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lass:PLA" ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ,-0.13156 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4}        ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.999937  ┆ GSE101731 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.410312 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999844  ┆ GSE101731 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.464773 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999993  ┆ GSE173536 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _lymphbla ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.399473 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999942  ┆ GSE173536 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _lymphbla ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ stoid_t21 ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.408836 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.999891  ┆ GSE209675 ┆ FCHS_9999 ┆ cp1@LRRIQ ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _MCF7_42C ┆ 4         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ _60min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.724572 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.1 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 92534,0,0 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## 8-1: Selection of distal enhancer (Important!)

- `TargetGene` の近傍ではない enhancer を標的とする
- `isSelfPromoter` == False でフィルタリング

In [31]:
e2g_join_filter = e2g_join.filter(
    pl.col("isSelfPromoter") == False
)

e2g_join_filter.write_parquet(
    f"../../out/ENCODE_rE2G/parquet_file/encode_re2g_hs_join_filter_distal_enhancer_v{execute_date}.parquet"
)

display(e2g_join_filter)

shape: (902_211, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENCODE-rE ┆ re2g_data ┆ cre_id    ┆ cre_name  ┆ … ┆ re2g_feat ┆ target_ts ┆ target_cr ┆ target_c │
│ 2G.Score  ┆ set       ┆ ---       ┆ ---       ┆   ┆ ures      ┆ s_info    ┆ e_info    ┆ re_overl │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ap_info  │
│ f64       ┆ str       ┆           ┆           ┆   ┆ struct[8] ┆ struct[5] ┆ struct[10 ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ]         ┆ struct[2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.342709  ┆ GSE154744 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _K562_42C ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ _25min    ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.383964 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44833,2,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,220.5978 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 81}       ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.320048  ┆ GSE154744 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _K562_42C ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ _60min    ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.402521 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44762,4,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,253.0904 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ }         ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.312414  ┆ GSE267931 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33082177 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {390,0.7 │
│           ┆ _HUVEC_39 ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3081927,3 ┆ 3081878,3 ┆ 8}       │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 00142920" ┆ 3082427,0 ┆ 3082317,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.466515 ┆ ,"+"}     ┆ ,".",3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 1878,3308 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 44839,4,1 ┆           ┆ 2179,"255 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,506.0419 ┆           ┆ ,202,74", ┆          │
│           ┆           ┆           ┆           ┆   ┆ 96}       ┆           ┆ "directio ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ nality:1| ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ class:ELA ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1.0}    ┆          │
│ 0.194134  ┆ GSE267931 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {33182070 ┆ {"chr1",3 ┆ {"chr1",3 ┆ {461,0.9 │
│           ┆ _HUVEC_39 ┆ 1         ┆ 1         ┆   ┆ ,"ENSG000 ┆ 3181820,3 ┆ 3181859,3 ┆ 22}      │
│           ┆ C_120min  ┆           ┆           ┆   ┆ 00116525" ┆ 3182320,0 ┆ 3182582,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.524194 ┆ ,"-"}     ┆ ,".",3318 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 2047,3318 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 13442,13, ┆           ┆ 2188,"0,0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 1,506.041 ┆           ┆ ,204","di ┆          │
│           ┆           ┆           ┆           ┆   ┆ 996}      ┆           ┆ rectional ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ity:-0.99 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9247|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .999247}  ┆          │
│ 0.291194  ┆ GSE173536 ┆ FCHS_1000 ┆ FCHS_1000 ┆ … ┆ {85836540 ┆ {"chr12", ┆ {"chr12", ┆ {442,0.8 │
│           ┆ _lymphbla ┆ 26        ┆ 26        ┆   ┆ ,"ENSG000 ┆ 85836290, ┆ 85836188, ┆ 84}      │
│           ┆ stoid_d21 ┆           ┆           ┆   ┆ 00198774" ┆ 85836790, ┆ 85836732, ┆          │
│           ┆ _42C_60mi ┆           ┆           ┆   ┆ ,0.357834 ┆ 0,"-"}    ┆ 0,".",858 ┆          │
│           ┆ n         ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36213,858 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0446,9,1, ┆           ┆ 36732,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.0}      ┆           ┆ 0,255","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-1|c ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lass:PLA" ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ,-1.0}    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.644669  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036320 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036070, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00133640" ┆ 85036570, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.470943 ┆ 0,"+"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36875,2,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.311435  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {84912829 ┆ {"chr12", ┆ {"chr12", ┆ {500,1.0 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 84912579, ┆ 84912565, ┆ }        │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00072041" ┆ 84913079, ┆ 84913337, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.486403 ┆ 0,"-"}    ┆ 0,".",849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 12757,849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 14404,3,1 ┆           ┆ 12903,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 0,204","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-0.9 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9533|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .99533}   ┆          │
│ 0.291244  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {84912829 ┆ {"chr12", ┆ {"chr12", ┆ {500,1.0 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 84912579, ┆ 84912565, ┆ }        │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00072041" ┆ 84913079, ┆ 84913337, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.581099 ┆ 0,"-"}    ┆ 0,".",849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 12757,849 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 14404,6,1 ┆           ┆ 12903,"0, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 0,204","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:-0.9 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 9533|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ .99533}   ┆          │
│ 0.634666  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 120min    ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.410312 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36906,1,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
│ 0.648746  ┆ GSE101731 ┆ FCHS_9998 ┆ cp1@TSPAN ┆ … ┆ {85036277 ┆ {"chr12", ┆ {"chr12", ┆ {262,0.5 │
│           ┆ _HFF_44C_ ┆ 7         ┆ 19        ┆   ┆ ,"ENSG000 ┆ 85036027, ┆ 85036236, ┆ 24}      │
│           ┆ 60min     ┆           ┆           ┆   ┆ 00231738" ┆ 85036527, ┆ 85036498, ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.464773 ┆ 0,"-"}    ┆ 0,".",850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,null,0.0 ┆           ┆ 36260,850 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 36903,2,2 ┆           ┆ 36344,"20 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,0.0}     ┆           ┆ 4,0,0","d ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ irectiona ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ lity:0.97 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0459|clas ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ s:PLA",0. ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 970459}   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
e2g_join_filter_unique_count = e2g_join_filter.group_by(
    "cre_id",
    "cre_name",
    "fantabio_cre_class",
    "target_cre_id",
    "target_cre_name",
    "target_fantabio_cre_class"
).agg(
    pl.col("re2g_dataset").unique().alias("re2g_dataset"),
    pl.col("re2g_dataset").n_unique().alias("re2g_dataset_count"),
    pl.col("ENCODE-rE2G.Score").alias("ENCODE-rE2G.Score"),
    
    pl.col("ENCODE-rE2G.Score").min().alias("ENCODE-rE2G.Score_min"),
    pl.col("ENCODE-rE2G.Score").max().alias("ENCODE-rE2G.Score_max"),
    pl.col("ENCODE-rE2G.Score").mean().alias("ENCODE-rE2G.Score_mean"),

    # pl.col("ENCODE-rE2G.Score").quantile(0.25).alias("ENCODE-rE2G.Score_q1"),
    # pl.col("ENCODE-rE2G.Score").median().alias("ENCODE-rE2G.Score_median"),
    # pl.col("ENCODE-rE2G.Score").quantile(0.75).alias("ENCODE-rE2G.Score_q3"),
    # pl.col("ENCODE-rE2G.Score").std().alias("ENCODE-rE2G.Score_std"),
).sort(
    by=["re2g_dataset_count"],
    descending=True
)

pl.Config.set_tbl_rows(10)
print(f"ENCODE-rE2G enhancer - target region interaction unique pair count: {e2g_join_filter_unique_count.select(['cre_id', 'target_cre_id']).n_unique()}")
display(e2g_join_filter_unique_count)

ENCODE-rE2G enhancer - target region interaction unique pair count: 368398

shape: (368_398, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_name  ┆ fantabio_ ┆ target_cr ┆ … ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-rE ┆ ENCODE-r │
│ ---       ┆ ---       ┆ cre_class ┆ e_id      ┆   ┆ 2G.Score  ┆ 2G.Score_ ┆ 2G.Score_ ┆ E2G.Scor │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ min       ┆ max       ┆ e_mean   │
│           ┆           ┆ str       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_2358 ┆ cp13@NR4A ┆ PLA       ┆ FCHS_2358 ┆ … ┆ [0.930365 ┆ 0.872632  ┆ 0.971833  ┆ 0.949118 │
│ 07        ┆ 2         ┆           ┆ 01        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.953361, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.957654] ┆           ┆           ┆          │
│ FCHS_2699 ┆ cp2@LOC10 ┆ PLA       ┆ FCHS_2699 ┆ … ┆ [0.394801 ┆ 0.317749  ┆ 0.817551  ┆ 0.518851 │
│ 18        ┆ 7985532   ┆           ┆ 08        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.601796, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.364564] ┆           ┆           ┆          │
│ FCHS_5871 ┆ FCHS_5871 ┆ ELA       ┆ FCHS_5871 ┆ … ┆ [0.634674 ┆ 0.415113  ┆ 0.908999  ┆ 0.62206  │
│ 0         ┆ 0         ┆           ┆ 9         ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.505039, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.672167] ┆           ┆           ┆          │
│ FCHS_2801 ┆ cp5@SLC6A ┆ PLA       ┆ FCHS_2801 ┆ … ┆ [0.658301 ┆ 0.29959   ┆ 0.979908  ┆ 0.688886 │
│ 50        ┆ 6         ┆           ┆ 26        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.760305, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.908059] ┆           ┆           ┆          │
│ FCHS_4140 ┆ cp3@ASTIL ┆ PLA       ┆ FCHS_4140 ┆ … ┆ [0.481073 ┆ 0.481073  ┆ 0.890794  ┆ 0.755901 │
│ 59        ┆ CS,cp14@P ┆           ┆ 48        ┆   ┆ ,         ┆           ┆           ┆          │
│           ┆ TP4A3     ┆           ┆           ┆   ┆ 0.701595, ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 0.848789] ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_1477 ┆ cp2@HBM   ┆ ELA       ┆ FCHS_1477 ┆ … ┆ [0.180577 ┆ 0.180577  ┆ 0.180577  ┆ 0.180577 │
│ 80        ┆           ┆           ┆ 91        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_4188 ┆ FCHS_4188 ┆ ELA       ┆ FCHS_4189 ┆ … ┆ [0.281531 ┆ 0.281531  ┆ 0.281531  ┆ 0.281531 │
│ 92        ┆ 92        ┆           ┆ 24        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_5145 ┆ FCHS_5145 ┆ ELA       ┆ FCHS_2062 ┆ … ┆ [0.2057]  ┆ 0.2057    ┆ 0.2057    ┆ 0.2057   │
│ 77        ┆ 77        ┆           ┆ 13        ┆   ┆           ┆           ┆           ┆          │
│ FCHS_4366 ┆ FCHS_4366 ┆ ELA       ┆ FCHS_4366 ┆ … ┆ [0.278818 ┆ 0.278818  ┆ 0.278818  ┆ 0.278818 │
│ 93        ┆ 93        ┆           ┆ 72        ┆   ┆ ]         ┆           ┆           ┆          │
│ FCHS_1079 ┆ FCHS_1079 ┆ ELA       ┆ FCHS_4478 ┆ … ┆ [0.302149 ┆ 0.302149  ┆ 0.302149  ┆ 0.302149 │
│           ┆           ┆           ┆ 13        ┆   ┆ ]         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## 8-2: Join

In [ ]:
# fantabio_HN2_up5p_diff_analysis_atac = pl.read_parquet(
#     "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/fantabio_HN2_up5p_v260721_diff_analysis_atac.parquet"
# )

# pl.Config.set_tbl_rows(2)
# display(fantabio_HN2_up5p_diff_analysis_atac)

In [ ]:
# # Keep fantabio rows whose cre_id appears in e2g_join
# e2g_cre_ids = e2g_join_filter_unique_count.select("cre_id").unique()


# # Use implode() so is_in receives a List (avoids DeprecationWarning in Polars 1.40+)
# fantabio_HN2_up5p_in_e2g = fantabio_HN2_up5p_diff_analysis_atac.filter(
#     pl.col("cre_id").is_in(pl.lit(e2g_cre_ids.get_column("cre_id")).implode())
# )

# print(
#     f"up5p transcript - CRE pairs: {fantabio_HN2_up5p_diff_analysis_atac.select(["cre_id", "transcript_id", "HN2"]).unique().n_unique()} \n"
#     f"e2g unique cre_id (after filtering): {e2g_cre_ids.select(["cre_id"]).n_unique()} \n"
#     f"Filtered up5p transcript - CRE pairs: {fantabio_HN2_up5p_in_e2g.select(["cre_id", "transcript_id", "HN2"]).unique().n_unique()}"
# )

# pl.Config.set_tbl_rows(2)
# display(fantabio_HN2_up5p_in_e2g)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8-3: Enhancer-derived lncRNA

- `fantabio_HN2_up5p_in_e2g` データフレームから、[../integrated_analysis/enhancer_derived_lncRNA.ipynb](../integrated_analysis/enhancer_derived_lncRNA.ipynb) で作成した enhancer-derived lncRNA のエントリーのみを選択する

In [ ]:
# enhancer_derived_lncRNA = pl.read_csv(
#     "../../out/integrated_analysis/enhancer_derived_lncRNA/enhancer_derived_lncrna_transcript_list.tsv",
#     separator="\t",
#     has_header=False,
#     new_columns=["cre_id", "transcript_id"]
# )

# print(f"unique lncRNA transcript_id: {enhancer_derived_lncRNA.select('transcript_id').n_unique()}")
# display(enhancer_derived_lncRNA)

In [ ]:
# # only lncRNA
# fantabio_HN2_up5p_in_e2g_lncRNA = fantabio_HN2_up5p_in_e2g.filter(
#     (pl.col("transcript_type") == "lncRNA") &
#     (pl.col("fantabio_cre_class") == "ELA")
# ).filter(
#     pl.col("transcript_id").is_in(enhancer_derived_lncRNA.get_column("transcript_id").implode())
# )


# pl.Config.set_tbl_rows(6)
# print(f"unique lncRNA cre_id: {fantabio_HN2_up5p_in_e2g_lncRNA.select('cre_id').n_unique()}")
# print(f"unique lncRNA transcript_id: {fantabio_HN2_up5p_in_e2g_lncRNA.select('transcript_id').n_unique()}")
# display(fantabio_HN2_up5p_in_e2g_lncRNA)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8-4: JOIN (lncRNA - CRE pair level)

- 具体的に、どの lncRNA - CRE pair が ENCODE-rE2G で予測されているのかを見せるためのデータフレーム
- このデータフレームは、ENCODE-rE2G 側で予測された enhancer 情報を元に `join`している

In [ ]:
# fantabio_HN2_up5p_lncRNA_join_e2g = fantabio_HN2_up5p_in_e2g_lncRNA.select(
#     "transcript_id",
#     "HN2",
#     "gene_id",
#     "gene_symbol",
#     "RNACentral_ID",
#     "annotation_remarks",
#     "cre_id",
#     "cre_name",
#     "screen_ccres",
#     "chip_atlas_antigens",
#     "silencerdbs",
#     "fantom5_cage_peaks",
#     "fantom5_enhancers",
#     "fantabio_cre_class"
# ).join(
#     e2g_join_filter_unique_count,
#     on=["cre_id", "cre_name", "fantabio_cre_class"],
#     how="inner"
# ).sort("HN2", descending=True)


# pl.Config.set_tbl_rows(2)
# display(fantabio_HN2_up5p_lncRNA_join_e2g)

In [ ]:
# # check
# FCHS_354475 = fantabio_HN2_up5p_lncRNA_join_e2g.filter(
#     pl.col("cre_id") == "FCHS_354475"
# )

# display(FCHS_354475)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8-5: Target Gene Selection

- 8-4 で得た lncRNA - CRE pair（enhancer として他遺伝子を制御）のうち、target 側も upregulated な例を残す
- 出発点は `e2g_join_unique_count` ではなく、8-4 の `fantabio_HN2_up5p_lncRNA_join_e2g`（すでに `isSelfPromoter == False`）
- 照合キーは rE2G の `target_cre_id` と、fantabio の `cre_id`（TSS 側で選んだ代表 CRE）

&nbsp;

&nbsp;

## 8-5-1: Target CRE 上の upregulated transcript

- 8-4 の `target_cre_id` が、HN2 up5p + ATAC diff analysis の `cre_id` に含まれるか確認する
- このセルは target 側の transcript 一覧であり、enhancer 側の絞り込みではない

In [ ]:
# # 上記の enhancer として機能している CRE のうち、標的となっている CRE (target_cre_id) が、HN2 の up5p の diff analysis で upregulated transcripts として含まれているか確認する
# e2g_lncRNA_target = fantabio_HN2_up5p_diff_analysis_atac.filter(
#     pl.col("cre_id").is_in(fantabio_HN2_up5p_lncRNA_join_e2g.get_column("target_cre_id").implode())
# )

# pl.Config.set_tbl_rows(70)
# print(f"e2g_lncRNA_target: {e2g_lncRNA_target.select('gene_symbol', "transcript_id", "gene_id", "HN2").unique().sort('HN2', descending=True)}")

# pl.Config.set_tbl_rows(2)
# display(e2g_lncRNA_target)

&nbsp;

&nbsp;

&nbsp;

## 8-5-2: 8-4 pair に戻して絞る

- 8-4 の lncRNA-enhancer pair を、8-5-1 の target CRE で `inner` join する
- enhancer-derived lncRNA と target 側 transcript の両方を 1 行に残す
- `e2g_join_unique_count` は使わない（self-promoter と、lncRNA 以外の enhancer が混ざるため）

In [ ]:
# # Attach upregulated target transcripts onto the 8-4 lncRNA-enhancer pairs
# e2g_lncRNA_target_filter = fantabio_HN2_up5p_lncRNA_join_e2g.join(
#     e2g_lncRNA_target.select(
#         pl.col("cre_id").alias("target_cre_id"),
#         pl.col("transcript_id").alias("target_transcript_id"),
#         pl.col("gene_symbol").alias("target_gene_symbol"),
#         pl.col("gene_id").alias("target_gene_id"),
#         pl.col("transcript_type").alias("target_transcript_type"),
#         pl.col("HN2").alias("target_HN2"),
#     ),
#     on="target_cre_id",
#     how="inner",
# ).sort("HN2", descending=True)


# pl.Config.set_tbl_rows(2)
# print(f"lncRNA-enhancer pairs with upregulated target CRE: {e2g_lncRNA_target_filter.select(['cre_id', 'target_cre_id']).n_unique()}")
# display(e2g_lncRNA_target_filter)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8-5: Target Gene Selection (Permissive)

- 8-4 の lncRNA - CRE pair のうち、target 側が upregulated かを、diff analysis 適用前の up5p 全体で見る
- 8-5-2 では target CRE も ATAC diff でシグナルがあるものに限っていた。ここではその制約を外す
- 出発点は同じく 8-4 の `fantabio_HN2_up5p_lncRNA_join_e2g`

&nbsp;

&nbsp;

## 8-5-1 (Permissive): Target CRE 上の upregulated transcript

- 8-4 の `target_cre_id` が、HN2 up5p（diff analysis 前）の `cre_id` に含まれるか確認する
- このセルは target 側の transcript 一覧であり、enhancer 側の絞り込みではない

In [ ]:
# fantabio_HN2_up5p = pl.read_parquet(
#     "../../out/fantabio/parquet_file/fantabio_HN2_up5p_v260721.parquet"
# )


# pl.Config.set_tbl_rows(2)
# display(fantabio_HN2_up5p)

In [ ]:
# # 上記の enhancer として機能している CRE のうち、標的となっている CRE (target_cre_id) が、HN2 の up5p transcript lists (diff analysis 適用前)で upregulated transcripts として含まれているか確認する
# e2g_lncRNA_target_permissive = fantabio_HN2_up5p.filter(
#     pl.col("cre_id").is_in(fantabio_HN2_up5p_lncRNA_join_e2g.get_column("target_cre_id").implode())
# )

# pl.Config.set_tbl_rows(110)
# print(f"e2g_lncRNA_target: {e2g_lncRNA_target_permissive.select('gene_symbol', "transcript_id", "gene_id", "HN2").unique().sort('HN2', descending=True)}")

# pl.Config.set_tbl_rows(2)
# display(e2g_lncRNA_target_permissive)

&nbsp;

&nbsp;

&nbsp;

## 8-5-2 (Permissive): 8-4 pair に戻して絞る

- 8-4 の lncRNA-enhancer pair を、8-5-1 (Permissive) の target CRE で `inner` join する
- enhancer-derived lncRNA と target 側 transcript の両方を 1 行に残す
- 8-5-2 と同じ形だが、target 側は ATAC diff analysis を課さない

In [ ]:
# # Attach permissive upregulated target transcripts onto the 8-4 lncRNA-enhancer pairs
# e2g_lncRNA_target_permissive_filter = fantabio_HN2_up5p_lncRNA_join_e2g.join(
#     e2g_lncRNA_target_permissive.select(
#         pl.col("cre_id").alias("target_cre_id"),
#         pl.col("transcript_id").alias("target_transcript_id"),
#         pl.col("gene_symbol").alias("target_gene_symbol"),
#         pl.col("gene_id").alias("target_gene_id"),
#         pl.col("transcript_type").alias("target_transcript_type"),
#         pl.col("HN2").alias("target_HN2"),
#     ),
#     on="target_cre_id",
#     how="inner",
# ).sort("HN2", descending=True)

# pl.Config.set_tbl_rows(2)
# print(
#     f"lncRNA-enhancer pairs with permissive upregulated target CRE: "
#     f"{e2g_lncRNA_target_permissive_filter.select(['cre_id', 'target_cre_id']).n_unique()}"
# )
# display(e2g_lncRNA_target_permissive_filter)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 9. Architectural RNA 

- この enhancer derived lncRNA が Architectural RNA の機能を持っていそうか調べる

In [ ]:
# prjdb12380_prjdb9451_heat_result = pl.read_csv(
#     "../../out/integrated_analysis/prjdb12380_prjdb9541/pydeseq2_heat_impr_vs_conv_results.tsv",
#     separator="\t",
#     n_threads=16
# ).filter(
#     (pl.col("log2FoldChange") > 0) &
#     (pl.col("padj") < 0.05)
# )

# display(prjdb12380_prjdb9451_heat_result)

In [ ]:
# prjdb12380_prjdb9451_heat_result_join = prjdb12380_prjdb9451_heat_result.join(
#     fantabio_HN2_up5p_in_e2g_lncRNA,
#     on="gene_id",
#     how="inner"
# )


# display(prjdb12380_prjdb9451_heat_result_join)