&nbsp;

## ChIP-Atlas Diff Analysis Parse Notebook

- 既に `diff Analysis` を実行済みだった heat-stress related ATAC-seq dataset に対し、`bedtools intersect` を行い、その結果をparse するための notebook

In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl

from IPython.display import display


os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### この notebook を実行するために必要な手順

1. [ChIP-Atlas Diff Analysis](https://chip-atlas.org/diff_analysis) を実行する
    1. 事前に定義した heat-stress (dataset A) vs. ctrl (dataset B) のデータに従ってペアを作成し、実行する
2. `bedtools intersect -wo`を実行する CWLファイル [../../Workflow/bedtools_intersect_v2_scatter.cwl](../../Workflow/bedtools_intersect_v2_scatter.cwl)を実行する

&nbsp;

```bash
cwltool --outdir ./out/ChIP-Atlas_diff/ATACseq/bedfile_intersect_v2/ \
./Workflow/bedtools_intersect_v2_scatter.cwl \
./config/bedtools_intersect/chipatlas_diff_atacseq_v2.yml
```

&nbsp;

#### WARNING

- 以下の処理では、q-value < 0.01 でフィルタリングしている

In [2]:
INTERSECT_DIFF_COLUMNS = [
    # A: ChIP-Atlas diff DPR (8 cols)  <- query (-a)
    "dpr_chrom", "dpr_start", "dpr_end",
    "norm_count_A", "norm_count_B",  # dataset A → Heat stress, B → Control
    "log2fc", "p_value", "q_value",
    # B: fanta.bio CRE (11 cols)       <- database (-b)
    "cre_chrom", "cre_start", "cre_end", "cre_id",
    "cre_score", "cre_strand", "thickStart", "thickEnd",
    "itemRgb", "cre_name", "pooled_cre_scores",
    # -wo
    "overlap_bp",
]

In [3]:
#繰り返し処理を行う
BED_INTERSECT_DIR = pathlib.Path("../../out/ChIP-Atlas_diff/ATACseq/bedfile_intersect_v2")

def read_intersect_bed(bed_path: pathlib.Path, q_threshold: float = 0.01) -> pl.DataFrame:
    """
    Read one bedtools intersect -wo output and tag with diff dataset ID from filename.
    default q-value threshold is 0.01.
    """
    # v2 filename: <dataset>_intersecting_<cre-peaks>.bed
    diff_dataset = bed_path.stem.split("_intersecting_", 1)[0]

    return (
        pl.read_csv(
            bed_path,
            separator="\t",
            has_header=False,
            new_columns=INTERSECT_DIFF_COLUMNS,
            # Force float dtypes: leading "1" q-values can make Polars infer Int64
            # and drop scientific-notation significant hits under ignore_errors.
            schema_overrides={
                "dpr_start": pl.Int64,
                "dpr_end": pl.Int64,
                "log2fc": pl.Float64,
                "p_value": pl.Float64,
                "q_value": pl.Float64,
                "cre_start": pl.Int64,
                "cre_end": pl.Int64,
                "cre_score": pl.Int64,
                "thickStart": pl.Int64,
                "thickEnd": pl.Int64,
                "overlap_bp": pl.Int64,
            },
            n_threads=16,
            ignore_errors=True,
        )
        .filter(pl.col("q_value") < q_threshold)
        .with_columns(
            # Fraction of CRE length covered by the DPR overlap (-wo)
            (pl.col("overlap_bp") / (pl.col("cre_end") - pl.col("cre_start"))).alias("overlap_frac_of_fantabio_cre"),
            pl.struct(
                "dpr_start",
                "dpr_end",
                "dpr_chrom"
            ).alias("dpr_interval")
        )
        .with_columns(
            pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
            pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
        )
        .with_columns(
            pl.lit(diff_dataset).alias("diff_dataset"),
            pl.lit(bed_path.name).alias("source_bed_file"),
        )
        .drop("cre_score", "cre_strand", "thickStart", "thickEnd", "itemRgb", "pooled_cre_scores", "norm_count_A", "norm_count_B", "dpr_start", "dpr_end", "dpr_chrom")
    )

bed_paths = sorted(
    BED_INTERSECT_DIR.glob("*_intersecting_*.bed")
)

all_diff_df = (
    pl.concat(
        [read_intersect_bed(p) for p in bed_paths],
        how="vertical_relaxed",
    )
    .sort(
        "cre_chrom",
        descending=False,
    )
)


# mismatch = all_diff_df.filter(pl.col("cre_chrom") != pl.col("dpr_chrom"))
# print(f"mismatch rows: {mismatch.height}")
pl.Config.set_tbl_rows(10)
pl.Config.set_fmt_str_lengths(100)
display(all_diff_df)

shape: (13_364, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ log2fc    ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ ed_file  │
│ f64       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.346413  ┆ 5.4291e-5 ┆ 7.6313e-5 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.363021  ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.520449  ┆ 1.7373e-2 ┆ 4.2758e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 0         ┆ 8         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.470083  ┆ 4.9866e-9 ┆ 2.4993e-7 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.510948  ┆ 3.2981e-1 ┆ 6.1358e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 7         ┆ 5         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.782456  ┆ 0.000625  ┆ 0.005354  ┆ chrY      ┆ … ┆ -0.979798 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 0.966208  ┆ 0.000259  ┆ 0.004473  ┆ chrY      ┆ … ┆ -0.884058 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ 1.249991  ┆ 0.000216  ┆ 0.003874  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

# Selection of Differencially Peaked Region (DPR)

&nbsp;

## (1) Filtering Condition

- `log2(Fold Change) < -0.5`
- [script/diff-analysis/diff_analysis_for_ChIP_ATAC_DNase.sh](https://github.com/inutano/chip-atlas/blob/master/script/diff-analysis/diff_analysis_for_ChIP_ATAC_DNase.sh)

In [4]:
all_diff_down = all_diff_df.filter(
    pl.col("log2fc") < -0.5
)

display(all_diff_down)

shape: (4_745, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ log2fc    ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ ed_file  │
│ f64       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -1.231767 ┆ 0.000066  ┆ 0.000855  ┆ chr1      ┆ … ┆ 0.317889  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.86908  ┆ 2.2899e-8 ┆ 9.2754e-7 ┆ chr1      ┆ … ┆ -0.777778 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.780242 ┆ 3.3117e-9 ┆ 1.7312e-7 ┆ chr1      ┆ … ┆ 0.614679  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.724787 ┆ 0.000897  ┆ 0.007128  ┆ chr1      ┆ … ┆ 0.278195  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.39651  ┆ 2.7891e-8 ┆ 0.000001  ┆ chr1      ┆ … ┆ 0.278195  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ -2.598487 ┆ 2.7698e-8 ┆ 0.000001  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.512691 ┆ 0.000264  ┆ 0.002643  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.512691 ┆ 0.000264  ┆ 0.002643  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## (2) Filter by Overlap Fraction

- 対象は直前の `log2fc < -0.5` 通過後（`all_diff_down`）
- 同一 `diff_dataset` × `cre_id` で複数 DPR が重なる場合、`overlap_frac_of_fantabio_cre` が最大の行のみ残す
- check: `FCHS_447246` の before / after を表示

In [5]:
# Among downregulated DPRs (log2fc < -0.5), keep max CRE-cover fraction
# per (diff_dataset, cre_id). Ties keep multiple rows.
CHECK_CRE_ID = "FCHS_447246"

fchs_before = all_diff_down.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(f"[before] {CHECK_CRE_ID}: {fchs_before.height} rows")
display(fchs_before)

all_diff_down_filtered = all_diff_down.filter(
    pl.col("overlap_frac_of_fantabio_cre")
    == pl.col("overlap_frac_of_fantabio_cre").max().over("diff_dataset", "cre_id")
)

fchs_after = all_diff_down_filtered.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(
    f"[after]  {CHECK_CRE_ID}: {fchs_after.height} rows "
    f"(all_diff_down {all_diff_down.height} -> {all_diff_down_filtered.height})"
)
display(fchs_after)

[before] FCHS_447246: 3 rows

shape: (3, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc    ┆ p_value   ┆ q_value  ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64       ┆ f64       ┆ f64      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -2.598487 ┆ 2.7698e-8 ┆ 0.000001 ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ -2.512691 ┆ 0.000264  ┆ 0.002643 ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013 ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

[after]  FCHS_447246: 2 rows (all_diff_down 4745 -> 4319)

shape: (2, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc    ┆ p_value   ┆ q_value  ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64       ┆ f64       ┆ f64      ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ -2.598487 ┆ 2.7698e-8 ┆ 0.000001 ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013 ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

## After Filtering

In [6]:
display(all_diff_down_filtered)

shape: (4_319, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ log2fc    ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ ed_file  │
│ f64       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -1.231767 ┆ 0.000066  ┆ 0.000855  ┆ chr1      ┆ … ┆ 0.317889  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.86908  ┆ 2.2899e-8 ┆ 9.2754e-7 ┆ chr1      ┆ … ┆ -0.777778 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.780242 ┆ 3.3117e-9 ┆ 1.7312e-7 ┆ chr1      ┆ … ┆ 0.614679  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.39651  ┆ 2.7891e-8 ┆ 0.000001  ┆ chr1      ┆ … ┆ 0.278195  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -1.724822 ┆ 0.000897  ┆ 0.007128  ┆ chr1      ┆ … ┆ 0.355212  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ -1.724613 ┆ 0.000034  ┆ 0.000928  ┆ chrX      ┆ … ┆ -0.61123  ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.598487 ┆ 2.7698e-8 ┆ 0.000001  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.512691 ┆ 0.000264  ┆ 0.002643  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
# Aggregate downregulated + max-overlap DPRs to CRE level
all_diff_down_select = all_diff_down_filtered.group_by(
    [
        "cre_chrom",
        "cre_start",
        "cre_end",
        "cre_id",
        "cre_name",
        # "dpr_chrom",
        "directionality",
        "fantabio_cre_class"
    ]
).agg(
    pl.col("overlap_frac_of_fantabio_cre").alias("overlap_frac_of_fantabio_cre"),
    pl.col("dpr_interval").alias("dpr_interval"),
    pl.col("log2fc").alias("log2fc"),
    pl.col("p_value").alias("p_value"),
    pl.col("q_value").alias("q_value"),
    pl.col("diff_dataset").unique().alias("diff_dataset"),
    pl.col("diff_dataset").unique().count().alias("diff_dataset_count"),
    pl.col("source_bed_file").alias("source_bed_file"),
).sort(
    "cre_chrom",
    "cre_start",
    "cre_end",
    descending=False
)

pl.Config.set_tbl_rows(6)
display(all_diff_down_select)

shape: (3_384, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_start ┆ cre_end   ┆ cre_id    ┆ … ┆ q_value   ┆ diff_data ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ set       ┆ set_count ┆ ed_file  │
│ str       ┆ i64       ┆ i64       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ list[str] ┆ u32       ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 2199175   ┆ 2199643   ┆ FCHS_892  ┆ … ┆ [0.000855 ┆ ["GSE1017 ┆ 2         ┆ ["GSE101 │
│           ┆           ┆           ┆           ┆   ┆ ,         ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆ 0.000479] ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min",    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ in"]      ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ , "GSE10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1731_ata │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ c_hf…    │
│ chr1      ┆ 2208274   ┆ 2208556   ┆ FCHS_4477 ┆ … ┆ [9.2754e- ┆ ["GSE1017 ┆ 1         ┆ ["GSE101 │
│           ┆           ┆           ┆ 10        ┆   ┆ 7]        ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆           ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min"]    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
│ chr1      ┆ 2246149   ┆ 2246455   ┆ FCHS_4477 ┆ … ┆ [1.7312e- ┆ ["GSE1017 ┆ 2         ┆ ["GSE101 │
│           ┆           ┆           ┆ 26        ┆   ┆ 7, 6.3413 ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆ e-7]      ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min",    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ in"]      ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ , "GSE10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1731_ata │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ c_hf…    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrX      ┆ 155613048 ┆ 155613375 ┆ FCHS_4468 ┆ … ┆ [0.000098 ┆ ["GSE1017 ┆ 1         ┆ ["GSE101 │
│           ┆           ┆           ┆ 59        ┆   ┆ ]         ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆           ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min"]    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
│ chrY      ┆ 19077163  ┆ 19077775  ┆ FCHS_4472 ┆ … ┆ [0.000001 ┆ ["GSE1017 ┆ 2         ┆ ["GSE101 │
│           ┆           ┆           ┆ 46        ┆   ┆ ,         ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆ 0.000013] ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min",    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ in"]      ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ , "GSE10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1731_ata │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ c_hf…    │
│ chrY      ┆ 19077586  ┆ 19077787  ┆ FCHS_4472 ┆ … ┆ [0.002643 ┆ ["GSE1017 ┆ 2         ┆ ["GSE101 │
│           ┆           ┆           ┆ 47        ┆   ┆ ,         ┆ 31_atac_h ┆           ┆ 731_atac │
│           ┆           ┆           ┆           ┆   ┆ 0.000013] ┆ ff_44C_12 ┆           ┆ _hff_44C │
│           ┆           ┆           ┆           ┆   ┆           ┆ 0min",    ┆           ┆ _120min_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ intersec │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ ting_hum │
│           ┆           ┆           ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ an-CREv1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ in"]      ┆           ┆ .2.1.hg3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pe │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ aks.bed" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ , "GSE10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1731_ata │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ c_hf…    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
all_diff_down_select.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/only_cre/fantabio_cre_list_diff_analysis_atac_down.parquet"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Intergration (downregulated transcripts)

In [9]:
# down5p transcript lists + CRE
fantabio_HN2_down5p_transcripts_cre = pl.read_parquet(
    "../../out/fantabio/parquet_file/bottom5p_transcript_fantabio_v261001.parquet"
).join(
    all_diff_down_select,
    on=["cre_id", "cre_chrom", "cre_name", "directionality", "fantabio_cre_class"],
    how="inner",
    coalesce=True
)

fantabio_HN2_down5p_transcripts_cre.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_bottom5p_v261002_diff_analysis_atac.parquet"
)

print(f"down5p_fantabio transcript count: {fantabio_HN2_down5p_transcripts_cre.select('transcript_id').n_unique()}")
print(f"down5p_fantabio transcript-CRE pairs count: {fantabio_HN2_down5p_transcripts_cre.select(['transcript_id', 'cre_id']).n_unique()}")
pl.Config.set_tbl_rows(4)
display(fantabio_HN2_down5p_transcripts_cre)

down5p_fantabio transcript count: 1380
down5p_fantabio transcript-CRE pairs count: 1925

shape: (1_925, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000048 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ [0.00734]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 9344.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000087 ┆ 77  ┆ 125   ┆ 204        ┆ … ┆ [0.008142]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 0205.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000067 ┆ 10  ┆ 217   ┆ 179        ┆ … ┆ [0.00029]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8149.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_60min"]  ┆            ┆ _44C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ ENST0000046 ┆ 15  ┆ 233   ┆ 158        ┆ … ┆ [0.00744,   ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 0307.1      ┆     ┆       ┆            ┆   ┆ 0.0073]     ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

## Protein-coding Transcripts

In [11]:
# (check whether the protein-coding transcripts - CREs are heat stress-responsive related transcripts)
fantabio_HN2_down5p_transcripts_cre_pc = fantabio_HN2_down5p_transcripts_cre.filter(
    pl.col("transcript_type") == "protein_coding"
)

down5p_pc_list = fantabio_HN2_down5p_transcripts_cre_pc.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/down5p/HN2_down5p_fantabio_check_diff_analysis_atac_pc_v261002.tsv",
    separator="\t",
    include_header=False
)

print(f"down5p_fantabio protein-coding transcript count: {fantabio_HN2_down5p_transcripts_cre_pc.select("transcript_id").n_unique()}")
print(f"down5p_fantabio protein-coding transcript-CRE pairs count: {fantabio_HN2_down5p_transcripts_cre_pc.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_down5p_transcripts_cre_pc)

down5p_fantabio protein-coding transcript count: 772
down5p_fantabio protein-coding transcript-CRE pairs count: 1059

shape: (1_059, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000087 ┆ 77  ┆ 125   ┆ 204        ┆ … ┆ [0.008142]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 0205.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000067 ┆ 37  ┆ 85    ┆ 284        ┆ … ┆ [0.002781]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 6271.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000052 ┆ 12  ┆ 200   ┆ 194        ┆ … ┆ [0.000033,  ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7436.5      ┆     ┆       ┆            ┆   ┆ 0.000074]   ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000052 ┆ 12  ┆ 200   ┆ 194        ┆ … ┆ [0.000033,  ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7436.5      ┆     ┆       ┆            ┆   ┆ 0.000074]   ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## lncRNA

In [12]:
fantabio_HN2_down5p_transcripts_cre_lncrna = fantabio_HN2_down5p_transcripts_cre.filter(
    pl.col("transcript_type") == "lncRNA"
).sort(
    pl.col([
        "HN2",
        "transcript_id"
    ]),
    descending=True
)

down5p_lncrna_list = fantabio_HN2_down5p_transcripts_cre_lncrna.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/down5p/HN2_down5p_fantabio_check_diff_analysis_atac_lncrna_v261002.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(4)
print(f"down5p_fantabio lncRNA transcript count: {fantabio_HN2_down5p_transcripts_cre_lncrna.select("transcript_id").n_unique()}")
print(f"down5p_fantabio lncRNA transcript-CRE pairs count: {fantabio_HN2_down5p_transcripts_cre_lncrna.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_down5p_transcripts_cre_lncrna)

down5p_fantabio lncRNA transcript count: 229
down5p_fantabio lncRNA transcript-CRE pairs count: 346

shape: (346, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000083 ┆ 50  ┆ 98    ┆ 258        ┆ … ┆ [0.000877,  ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7435.1      ┆     ┆       ┆            ┆   ┆ 0.000959]   ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000083 ┆ 77  ┆ 125   ┆ 204        ┆ … ┆ [0.000948]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 6881.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000056 ┆ 22  ┆ 193   ┆ 191        ┆ … ┆ [1.4368e-8] ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 4063.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000077 ┆ 13  ┆ 185   ┆ 208        ┆ … ┆ [0.001131]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 4717.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## Other Transcripts

In [13]:
fantabio_HN2_down5p_transcripts_cre_other = fantabio_HN2_down5p_transcripts_cre.filter(
    (pl.col("transcript_type") != "lncRNA") & (pl.col("transcript_type") != "protein_coding")
).sort(
    pl.col("HN2"),
    descending=True
)

down5p_other_list = fantabio_HN2_down5p_transcripts_cre_other.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/down5p/HN2_down5p_fantabio_check_diff_analysis_atac_other_v261002.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(10)
print(fantabio_HN2_down5p_transcripts_cre_other.select("transcript_id").n_unique())
print(fantabio_HN2_down5p_transcripts_cre_other.group_by("transcript_type").agg(pl.col("transcript_id").n_unique().alias("transcript_type_count")))
display(fantabio_HN2_down5p_transcripts_cre_other)

379
shape: (6, 2)
┌────────────────────────────────────┬───────────────────────┐
│ transcript_type                    ┆ transcript_type_count │
│ ---                                ┆ ---                   │
│ str                                ┆ u32                   │
╞════════════════════════════════════╪═══════════════════════╡
│ non_stop_decay                     ┆ 2                     │
│ protein_coding_CDS_not_defined     ┆ 78                    │
│ nonsense_mediated_decay            ┆ 91                    │
│ TEC                                ┆ 6                     │
│ transcribed_unprocessed_pseudogene ┆ 1                     │
│ retained_intron                    ┆ 201                   │
└────────────────────────────────────┴───────────────────────┘

shape: (520, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000048 ┆ 69  ┆ 117   ┆ 220        ┆ … ┆ [0.00734]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 9344.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000035 ┆ 27  ┆ 75    ┆ 304        ┆ … ┆ [8.7537e-10 ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7434.3      ┆     ┆       ┆            ┆   ┆ , 0.000136] ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000035 ┆ 27  ┆ 75    ┆ 304        ┆ … ┆ [8.7537e-10 ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 7434.3      ┆     ┆       ┆            ┆   ┆ , 0.000136] ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000062 ┆ 51  ┆ 99    ┆ 256        ┆ … ┆ [0.007804]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 4106.2      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_60min"]  ┆            ┆ _44C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ ENST0000055 ┆ 79  ┆ 127   ┆ 200        ┆ … ┆ [0.005177]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3160.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000046 ┆ 22  ┆ 208   ┆ 176        ┆ … ┆ [0.003029]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3866.2      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_60min"]  ┆            ┆ _44C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ ENST0000048 ┆ 26  ┆ 216   ┆ 164        ┆ … ┆ [0.00734]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 5213.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000047 ┆ 9   ┆ 199   ┆ 198        ┆ … ┆ [0.000535]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3371.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000067 ┆ 10  ┆ 217   ┆ 179        ┆ … ┆ [0.00029]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8149.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_60min"]  ┆            ┆ _44C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ ENST0000046 ┆ 15  ┆ 233   ┆ 158        ┆ … ┆ [0.00744,   ┆ ["GSE101731 ┆ 2          ┆ ["GSE10173 │
│ 0307.1      ┆     ┆       ┆            ┆   ┆ 0.0073]     ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE101731_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_hff_44 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ , "GSE1017 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 31_atac_hf │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘