&nbsp;

## ChIP-Atlas Diff Analysis Parse Notebook (histone modification)

- 既に ChIP-Atlas `diff Analysis` を実行済みの heat-stress related ChIP-seq dataset に対し、`bedtools intersect` を行い、その結果をparse するための notebook

In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import plotly.express as px
import matplotlib.pyplot as plt # type: ignore
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from upsetplot import UpSet, from_contents # type: ignore


os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### この notebook を実行するために必要な手順

1. [ChIP-Atlas Diff Analysis](https://chip-atlas.org/diff_analysis) を実行する
    1. 事前に定義した heat-stress (dataset A) vs. ctrl (dataset B) のデータに従ってペアを作成し、実行する
2. `bedtools intersect -wo`を実行する CWLファイル [../../Workflow/bedtools_intersect_v2_scatter.cwl](../../Workflow/bedtools_intersect_v2_scatter.cwl)を実行する

In [2]:
INTERSECT_DIFF_COLUMNS = [
    # A: ChIP-Atlas diff DPR (8 cols)  <- query (-a)
    "dpr_chrom", "dpr_start", "dpr_end",
    "norm_count_A", "norm_count_B",  # dataset A → Heat stress, B → Control
    "log2fc", "p_value", "q_value",
    # B: fanta.bio CRE (11 cols)       <- database (-b)
    "cre_chrom", "cre_start", "cre_end", "cre_id",
    "cre_score", "cre_strand", "thickStart", "thickEnd",
    "itemRgb", "cre_name", "pooled_cre_scores",
    # -wo
    "overlap_bp",
]

In [3]:
#繰り返し処理を行う
BED_INTERSECT_DIR = pathlib.Path("../../out/ChIP-Atlas_diff/ChIPseq_histone/bedfile_intersect_v2/")

def read_intersect_bed(bed_path: pathlib.Path, q_threshold: float = 0.01) -> pl.DataFrame:
    """
    Read one bedtools intersect -wo output and tag with diff dataset ID from filename.
    default q-value threshold is 0.01.
    """
    # v2 filename: <dataset>_intersecting_<cre-peaks>.bed
    diff_dataset = bed_path.stem.split("_intersecting_", 1)[0]

    return (
        pl.read_csv(
            bed_path,
            separator="\t",
            has_header=False,
            new_columns=INTERSECT_DIFF_COLUMNS,
            # Force float dtypes: leading "1" q-values can make Polars infer Int64
            # and drop scientific-notation significant hits under ignore_errors.
            schema_overrides={
                "dpr_start": pl.Int64,
                "dpr_end": pl.Int64,
                "log2fc": pl.Float64,
                "p_value": pl.Float64,
                "q_value": pl.Float64,
                "cre_start": pl.Int64,
                "cre_end": pl.Int64,
                "cre_score": pl.Int64,
                "thickStart": pl.Int64,
                "thickEnd": pl.Int64,
                "overlap_bp": pl.Int64,
            },
            n_threads=16,
            ignore_errors=True,
        )
        .filter(pl.col("q_value") < q_threshold)
        .with_columns(
            # Fraction of CRE length covered by the DPR overlap (-wo)
            (pl.col("overlap_bp") / (pl.col("cre_end") - pl.col("cre_start"))).alias("overlap_frac_of_fantabio_cre"),
            pl.struct(
                "dpr_start",
                "dpr_end",
                "dpr_chrom"
            ).alias("dpr_interval")
        )
        .with_columns(
            pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
            pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
        )
        .with_columns(
            pl.lit(diff_dataset).alias("diff_dataset"),
            pl.lit(bed_path.name).alias("source_bed_file"),
        )
        .drop("cre_score", "cre_strand", "thickStart", "thickEnd", "itemRgb", "pooled_cre_scores", "norm_count_A", "norm_count_B", "dpr_start", "dpr_end", "dpr_chrom")
    )

bed_paths = sorted(
    BED_INTERSECT_DIR.glob("*_intersecting_*.bed")
)

all_diff_df = (
    pl.concat(
        [read_intersect_bed(p) for p in bed_paths],
        how="vertical_relaxed",
    )
    .sort(
        "cre_chrom",
        descending=False,
    )
)

# mismatch = all_diff_df.filter(pl.col("cre_chrom") != pl.col("dpr_chrom"))
# print(f"mismatch rows: {mismatch.height}")
pl.Config.set_tbl_rows(10)
pl.Config.set_fmt_str_lengths(100)
display(all_diff_df)

shape: (5_989, 15)
┌───────────┬──────────┬──────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ log2fc    ┆ p_value  ┆ q_value  ┆ cre_chrom ┆ … ┆ directiona ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---       ┆ ---      ┆ ---      ┆ ---       ┆   ┆ lity       ┆ cre_class ┆ set       ┆ d_file    │
│ f64       ┆ f64      ┆ f64      ┆ str       ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆          ┆           ┆   ┆ f64        ┆ str       ┆ str       ┆ str       │
╞═══════════╪══════════╪══════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ -1.272021 ┆ 0.00138  ┆ 0.009665 ┆ chr1      ┆ … ┆ 0.8        ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.272021 ┆ 0.00138  ┆ 0.009665 ┆ chr1      ┆ … ┆ 1.0        ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.272021 ┆ 0.00138  ┆ 0.009665 ┆ chr1      ┆ … ┆ 0.818182   ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.272021 ┆ 0.00138  ┆ 0.009665 ┆ chr1      ┆ … ┆ 0.928974   ┆ PLA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.152493 ┆ 0.001205 ┆ 0.008716 ┆ chr1      ┆ … ┆ 0.28169    ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ …         ┆ …        ┆ …        ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ -1.516931 ┆ 0.000511 ┆ 0.004434 ┆ chrX      ┆ … ┆ -0.982428  ┆ PLA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ 1.213783  ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 1.0        ┆ PLA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ 1.213783  ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 0.668966   ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.468718 ┆ 0.000169 ┆ 0.001842 ┆ chrX      ┆ … ┆ 0.815385   ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
│ -1.672098 ┆ 0.000456 ┆ 0.004053 ┆ chrX      ┆ … ┆ -1.0       ┆ ELA       ┆ GSE105028 ┆ GSE105028 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ _chip_h3k ┆ _chip_h3k │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆ 2C_60min  ┆ 2C_60min_ │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ intersect │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ing_human │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ -CREv1.2. │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ 1.hg38.cr │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ e-peaks.b │
│           ┆          ┆          ┆           ┆   ┆            ┆           ┆           ┆ ed        │
└───────────┴──────────┴──────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

# Selection of Differencially Peaked Region (DPR)

&nbsp;

## (1) Filtering Condition

- `log2(Fold Change) > 0.5`

In [4]:
all_diff_up = all_diff_df.filter(
    pl.col("log2fc") > 0.5
)

display(all_diff_up)

shape: (2_434, 15)
┌──────────┬──────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ log2fc   ┆ p_value  ┆ q_value  ┆ cre_chrom ┆ … ┆ directiona ┆ fantabio_c ┆ diff_data ┆ source_be │
│ ---      ┆ ---      ┆ ---      ┆ ---       ┆   ┆ lity       ┆ re_class   ┆ set       ┆ d_file    │
│ f64      ┆ f64      ┆ f64      ┆ str       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│          ┆          ┆          ┆           ┆   ┆ f64        ┆ str        ┆ str       ┆ str       │
╞══════════╪══════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1.162215 ┆ 0.000026 ┆ 0.000425 ┆ chr1      ┆ … ┆ -0.925156  ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.162215 ┆ 0.000026 ┆ 0.000425 ┆ chr1      ┆ … ┆ -0.176471  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.188244 ┆ 0.000055 ┆ 0.000751 ┆ chr1      ┆ … ┆ -0.823529  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.188244 ┆ 0.000055 ┆ 0.000751 ┆ chr1      ┆ … ┆ 0.903509   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.363975 ┆ 0.000306 ┆ 0.002942 ┆ chr1      ┆ … ┆ -0.764322  ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ …        ┆ …        ┆ …        ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 1.057816 ┆ 0.000045 ┆ 0.000644 ┆ chrX      ┆ … ┆ 0.384615   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.823036 ┆ 0.000006 ┆ 0.000134 ┆ chrX      ┆ … ┆ -0.372549  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.332147 ┆ 0.001114 ┆ 0.008196 ┆ chrX      ┆ … ┆ 0.997353   ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.213783 ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 1.0        ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.213783 ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 0.668966   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
└──────────┴──────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

## Filter by Overlap Fraction

- 対象は直前の `log2fc > 0.5` 通過後（`all_diff_up`）
- 同一 `diff_dataset` × `cre_id` で複数 DPR が重なる場合、`overlap_frac_of_fantabio_cre` が最大の行のみ残す
- check: `FCHS_5` の before / after を表示

In [8]:
# Among upregulated DPRs (log2fc > 0.5), keep max CRE-cover fraction
# per (diff_dataset, cre_id). Ties keep multiple rows.
CHECK_CRE_ID = "FCHS_571903"

fchs5_before = all_diff_up.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(f"[before] {CHECK_CRE_ID}: {fchs5_before.height} rows")
display(fchs5_before)

all_diff_up_filtered = all_diff_up.filter(
    pl.col("overlap_frac_of_fantabio_cre")
    == pl.col("overlap_frac_of_fantabio_cre").max().over("diff_dataset", "cre_id")
)

fchs5_after = all_diff_up_filtered.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(
    f"[after]  {CHECK_CRE_ID}: {fchs5_after.height} rows "
    f"(all_diff_up {all_diff_up.height} -> {all_diff_up_filtered.height})"
)
display(fchs5_after)

[before] FCHS_571903: 0 rows

shape: (0, 15)
┌────────┬─────────┬─────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ log2fc ┆ p_value ┆ q_value ┆ cre_chrom ┆ … ┆ directional ┆ fantabio_cr ┆ diff_datas ┆ source_bed │
│ ---    ┆ ---     ┆ ---     ┆ ---       ┆   ┆ ity         ┆ e_class     ┆ et         ┆ _file      │
│ f64    ┆ f64     ┆ f64     ┆ str       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆         ┆         ┆           ┆   ┆ f64         ┆ str         ┆ str        ┆ str        │
╞════════╪═════════╪═════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
└────────┴─────────┴─────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

[after]  FCHS_571903: 0 rows (all_diff_up 2434 -> 2229)

shape: (0, 15)
┌────────┬─────────┬─────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ log2fc ┆ p_value ┆ q_value ┆ cre_chrom ┆ … ┆ directional ┆ fantabio_cr ┆ diff_datas ┆ source_bed │
│ ---    ┆ ---     ┆ ---     ┆ ---       ┆   ┆ ity         ┆ e_class     ┆ et         ┆ _file      │
│ f64    ┆ f64     ┆ f64     ┆ str       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│        ┆         ┆         ┆           ┆   ┆ f64         ┆ str         ┆ str        ┆ str        │
╞════════╪═════════╪═════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
└────────┴─────────┴─────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## After Filtering

In [9]:
display(all_diff_up_filtered)

shape: (2_229, 15)
┌──────────┬──────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ log2fc   ┆ p_value  ┆ q_value  ┆ cre_chrom ┆ … ┆ directiona ┆ fantabio_c ┆ diff_data ┆ source_be │
│ ---      ┆ ---      ┆ ---      ┆ ---       ┆   ┆ lity       ┆ re_class   ┆ set       ┆ d_file    │
│ f64      ┆ f64      ┆ f64      ┆ str       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│          ┆          ┆          ┆           ┆   ┆ f64        ┆ str        ┆ str       ┆ str       │
╞══════════╪══════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1.162215 ┆ 0.000026 ┆ 0.000425 ┆ chr1      ┆ … ┆ -0.925156  ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.162215 ┆ 0.000026 ┆ 0.000425 ┆ chr1      ┆ … ┆ -0.176471  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.188244 ┆ 0.000055 ┆ 0.000751 ┆ chr1      ┆ … ┆ -0.823529  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.188244 ┆ 0.000055 ┆ 0.000751 ┆ chr1      ┆ … ┆ 0.903509   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.363975 ┆ 0.000306 ┆ 0.002942 ┆ chr1      ┆ … ┆ -0.764322  ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ …        ┆ …        ┆ …        ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 1.057816 ┆ 0.000045 ┆ 0.000644 ┆ chrX      ┆ … ┆ 0.384615   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.823036 ┆ 0.000006 ┆ 0.000134 ┆ chrX      ┆ … ┆ -0.372549  ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.332147 ┆ 0.001114 ┆ 0.008196 ┆ chrX      ┆ … ┆ 0.997353   ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.213783 ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 1.0        ┆ PLA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
│ 1.213783 ┆ 0.00095  ┆ 0.007217 ┆ chrX      ┆ … ┆ 0.668966   ┆ ELA        ┆ GSE105028 ┆ GSE105028 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ _chip_h3k ┆ _chip_h3k │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 27ac_hs_4 ┆ 27ac_hs_4 │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆ 2C_60min  ┆ 2C_60min_ │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ intersect │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ing_human │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ -CREv1.2. │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ 1.hg38.cr │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ e-peaks.b │
│          ┆          ┆          ┆           ┆   ┆            ┆            ┆           ┆ ed        │
└──────────┴──────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [10]:
# Aggregate upregulated + max-overlap DPRs to CRE level
all_diff_up_select = all_diff_up_filtered.group_by(
    [
        "cre_chrom",
        "cre_start",
        "cre_end",
        "cre_id",
        "cre_name",
        # "dpr_chrom",
        "directionality",
        "fantabio_cre_class"
    ]
).agg(
    pl.col("overlap_frac_of_fantabio_cre").alias("overlap_frac_of_fantabio_cre"),
    pl.col("dpr_interval").alias("dpr_interval"),
    pl.col("log2fc").alias("log2fc"),
    pl.col("p_value").alias("p_value"),
    pl.col("q_value").alias("q_value"),
    pl.col("diff_dataset").unique().alias("diff_dataset"),
    pl.col("diff_dataset").unique().count().alias("diff_dataset_count"),
    pl.col("source_bed_file").alias("source_bed_file"),
).sort(
    "cre_chrom",
    "cre_start",
    "cre_end",
    descending=False
)

pl.Config.set_tbl_rows(6)
display(all_diff_up_select)

shape: (2_223, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_start ┆ cre_end   ┆ cre_id    ┆ … ┆ q_value   ┆ diff_data ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ set       ┆ set_count ┆ ed_file  │
│ str       ┆ i64       ┆ i64       ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ list[str] ┆ u32       ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 1858682   ┆ 1858895   ┆ FCHS_754  ┆ … ┆ [0.000425 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆           ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
│ chr1      ┆ 1859132   ┆ 1859890   ┆ FCHS_755  ┆ … ┆ [0.000425 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆           ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
│ chr1      ┆ 1888971   ┆ 1889672   ┆ FCHS_766  ┆ … ┆ [0.000751 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆           ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrX      ┆ 150568174 ┆ 150568813 ┆ FCHS_4458 ┆ … ┆ [0.008196 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆ 13        ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
│ chrX      ┆ 155025776 ┆ 155026125 ┆ FCHS_4468 ┆ … ┆ [0.007217 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆ 11        ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
│ chrX      ┆ 155026411 ┆ 155026727 ┆ FCHS_4468 ┆ … ┆ [0.007217 ┆ ["GSE1050 ┆ 1         ┆ ["GSE105 │
│           ┆           ┆           ┆ 12        ┆   ┆ ]         ┆ 28_chip_h ┆           ┆ 028_chip │
│           ┆           ┆           ┆           ┆   ┆           ┆ 3k27ac_hs ┆           ┆ _h3k27ac │
│           ┆           ┆           ┆           ┆   ┆           ┆ _42C_60mi ┆           ┆ _hs_42C_ │
│           ┆           ┆           ┆           ┆   ┆           ┆ n"]       ┆           ┆ 60min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed"]  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
all_diff_up_select.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/fantabio_cre_list_diff_analysis_chipseq_histone.parquet",
    use_pyarrow=True
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Intergration (upregulated transcripts)

In [12]:
# up5p transcript lists + CRE
fantabio_HN2_up5p_transcripts_cre = pl.read_parquet(
    "../../out/fantabio/parquet_file/fantabio_HN2_up5p_v260721.parquet"
).join(
    all_diff_up_select,
    on=["cre_id", "cre_chrom", "cre_name", "directionality", "fantabio_cre_class"],
    how="inner",
    coalesce=True
)

fantabio_HN2_up5p_transcripts_cre.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/fantabio_HN2_up5p_v260721_diff_analysis_chipseq_histone.parquet",
    use_pyarrow=True
)

print(f"up5p_fantabio transcript count: {fantabio_HN2_up5p_transcripts_cre.select('transcript_id').n_unique()}")
print(f"up5p_fantabio transcript-CRE pairs count: {fantabio_HN2_up5p_transcripts_cre.select(['transcript_id', 'cre_id']).n_unique()}")
pl.Config.set_tbl_rows(4)
display(fantabio_HN2_up5p_transcripts_cre)

up5p_fantabio transcript count: 938
up5p_fantabio transcript-CRE pairs count: 1519

shape: (1_519, 46)
┌─────────────┬─────┬───────┬────────────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value    ┆ diff_datase ┆ diff_datase ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t           ┆ t_count     ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]  ┆ ---         ┆ ---         ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆            ┆ list[str]   ┆ u32         ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
│ ENST0000054 ┆ 327 ┆ 9     ┆ 69         ┆ … ┆ [0.000248] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0260.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000067 ┆ 323 ┆ 7     ┆ 75         ┆ … ┆ [0.000164] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 6231.2      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …          ┆ …           ┆ …           ┆ …          │
│ ENST0000087 ┆ 108 ┆ 64    ┆ 233        ┆ … ┆ [0.001278] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0719.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000087 ┆ 108 ┆ 64    ┆ 233        ┆ … ┆ [0.001278] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0719.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
└─────────────┴─────┴───────┴────────────┴───┴────────────┴─────────────┴─────────────┴────────────┘

&nbsp;

## Protein-coding Transcripts

In [15]:
# (check whether the protein-coding transcripts - CREs are heat stress-responsive related transcripts)
fantabio_HN2_up5p_transcripts_cre_pc = fantabio_HN2_up5p_transcripts_cre.filter(
    pl.col("transcript_type") == "protein_coding"
)

up5p_pc_list_hsf = fantabio_HN2_up5p_transcripts_cre_pc.select("transcript_id").unique().write_csv(
    "../../out/ChIP-Atlas_diff/query_transcript_list/up5p_pc_list_check_diff_analysis_chipseq_histone.tsv",
    separator="\t",
    include_header=False
)

print(f"up5p_fantabio protein-coding transcript count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_pc.select("transcript_id").n_unique()}")
print(f"up5p_fantabio protein-coding transcript-CRE pairs count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_pc.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_up5p_transcripts_cre_pc)

up5p_fantabio protein-coding transcript count (ChIP-seq histone): 561
up5p_fantabio protein-coding transcript-CRE pairs count (ChIP-seq histone): 920

shape: (920, 46)
┌─────────────┬─────┬───────┬────────────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value    ┆ diff_datase ┆ diff_datase ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t           ┆ t_count     ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]  ┆ ---         ┆ ---         ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆            ┆ list[str]   ┆ u32         ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
│ ENST0000067 ┆ 323 ┆ 7     ┆ 75         ┆ … ┆ [0.000164] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 6231.2      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000067 ┆ 323 ┆ 7     ┆ 75         ┆ … ┆ [0.000164] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 6231.2      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …          ┆ …           ┆ …           ┆ …          │
│ ENST0000087 ┆ 108 ┆ 64    ┆ 233        ┆ … ┆ [0.001278] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0719.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000087 ┆ 108 ┆ 64    ┆ 233        ┆ … ┆ [0.001278] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0719.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
└─────────────┴─────┴───────┴────────────┴───┴────────────┴─────────────┴─────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## lncRNA

In [16]:
fantabio_HN2_up5p_transcripts_cre_lncrna = fantabio_HN2_up5p_transcripts_cre.filter(
    pl.col("transcript_type") == "lncRNA"
).sort(
    pl.col([
        "HN2",
        "transcript_id"
    ]),
    descending=True
)

up5p_lncrna_list_hsf = fantabio_HN2_up5p_transcripts_cre_lncrna.select("transcript_id").unique().write_csv(
    "../../out/ChIP-Atlas_diff/query_transcript_list/up5p_lncrna_list_check_diff_analysis_chipseq_histone.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(4)
print(f"up5p_fantabio lncRNA transcript count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_lncrna.select("transcript_id").n_unique()}")
print(f"up5p_fantabio lncRNA transcript-CRE pairs count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_lncrna.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_up5p_transcripts_cre_lncrna)

up5p_fantabio lncRNA transcript count (ChIP-seq histone): 133
up5p_fantabio lncRNA transcript-CRE pairs count (ChIP-seq histone): 212

shape: (212, 46)
┌─────────────┬─────┬───────┬────────────┬───┬────────────┬─────────────┬─────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value    ┆ diff_datase ┆ diff_datase ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---        ┆ t           ┆ t_count     ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]  ┆ ---         ┆ ---         ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆            ┆ list[str]   ┆ u32         ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪════════════╪═════════════╪═════════════╪════════════╡
│ ENST0000072 ┆ 315 ┆ 20    ┆ 70         ┆ … ┆ [0.007156] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 9765.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000072 ┆ 315 ┆ 20    ┆ 70         ┆ … ┆ [0.007156] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 9765.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …          ┆ …           ┆ …           ┆ …          │
│ ENST0000072 ┆ 96  ┆ 52    ┆ 257        ┆ … ┆ [0.000006] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 5679.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
│ ENST0000071 ┆ 84  ┆ 40    ┆ 281        ┆ … ┆ [0.003537] ┆ ["GSE105028 ┆ 1           ┆ ["GSE10502 │
│ 0875.1      ┆     ┆       ┆            ┆   ┆            ┆ _chip_h3k27 ┆             ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆            ┆ ac_hs_42C_6 ┆             ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆            ┆ 0min"]      ┆             ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆            ┆             ┆             ┆ s.bed"]    │
└─────────────┴─────┴───────┴────────────┴───┴────────────┴─────────────┴─────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## Other Transcripts

In [17]:
fantabio_HN2_up5p_transcripts_cre_other = fantabio_HN2_up5p_transcripts_cre.filter(
    (pl.col("transcript_type") != "lncRNA") & (pl.col("transcript_type") != "protein_coding")
).sort(
    pl.col("HN2"),
    descending=True
)

up5p_other_list_hsf = fantabio_HN2_up5p_transcripts_cre_other.select("transcript_id").unique().write_csv(
    "../../out/ChIP-Atlas_diff/query_transcript_list/up5p_other_list_check_diff_analysis_chipseq_histone.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(10)
print(f"up5p_fantabio other transcript count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_other.select("transcript_id").n_unique()}")
print(f"up5p_fantabio other transcript-CRE pairs count (ChIP-seq histone): {fantabio_HN2_up5p_transcripts_cre_other.group_by("transcript_type").agg(pl.col("transcript_id").n_unique().alias("transcript_type_count"))}")
display(fantabio_HN2_up5p_transcripts_cre_other)

up5p_fantabio other transcript count (ChIP-seq histone): 244
up5p_fantabio other transcript-CRE pairs count (ChIP-seq histone): shape: (6, 2)
┌────────────────────────────────┬───────────────────────┐
│ transcript_type                ┆ transcript_type_count │
│ ---                            ┆ ---                   │
│ str                            ┆ u32                   │
╞════════════════════════════════╪═══════════════════════╡
│ processed_pseudogene           ┆ 1                     │
│ miRNA                          ┆ 1                     │
│ nonsense_mediated_decay        ┆ 97                    │
│ protein_coding_CDS_not_defined ┆ 65                    │
│ retained_intron                ┆ 78                    │
│ TEC                            ┆ 2                     │
└────────────────────────────────┴───────────────────────┘

shape: (387, 46)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000054 ┆ 327 ┆ 9     ┆ 69         ┆ … ┆ [0.000248]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 0260.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000055 ┆ 328 ┆ 18    ┆ 59         ┆ … ┆ [5.2196e-8] ┆ ["GSE209667 ┆ 1          ┆ ["GSE20966 │
│ 5662.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k4m ┆            ┆ 7_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ e3_hs_42C_6 ┆            ┆ 4me3_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000055 ┆ 328 ┆ 18    ┆ 59         ┆ … ┆ [8.9280e-7] ┆ ["GSE209667 ┆ 1          ┆ ["GSE20966 │
│ 5662.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k4m ┆            ┆ 7_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ e3_hs_42C_6 ┆            ┆ 4me3_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000052 ┆ 321 ┆ 13    ┆ 71         ┆ … ┆ [0.009743]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 9402.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000052 ┆ 321 ┆ 13    ┆ 71         ┆ … ┆ [0.009743]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 9402.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000071 ┆ 111 ┆ 66    ┆ 228        ┆ … ┆ [0.000776]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 3869.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000068 ┆ 121 ┆ 76    ┆ 208        ┆ … ┆ [0.000563]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 4542.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000068 ┆ 121 ┆ 76    ┆ 208        ┆ … ┆ [0.000563]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 4542.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000056 ┆ 123 ┆ 79    ┆ 203        ┆ … ┆ [0.008285]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 2799.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
│ ENST0000056 ┆ 123 ┆ 79    ┆ 203        ┆ … ┆ [0.008285]  ┆ ["GSE105028 ┆ 1          ┆ ["GSE10502 │
│ 2799.1      ┆     ┆       ┆            ┆   ┆             ┆ _chip_h3k27 ┆            ┆ 8_chip_h3k │
│             ┆     ┆       ┆            ┆   ┆             ┆ ac_hs_42C_6 ┆            ┆ 27ac_hs_42 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 0min"]      ┆            ┆ C_60min_in │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ tersecting │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _human-CRE │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ v1.2.1.hg3 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 8.cre-peak │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ s.bed"]    │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘