&nbsp;

## ChIP-Atlas Diff Analysis Parse Notebook

- 既に `diff Analysis` を実行済みだった heat-stress related ATAC-seq dataset に対し、`bedtools intersect` を行い、その結果をparse するための notebook

In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import polars as pl
from IPython.display import display


os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### この notebook を実行するために必要な手順

1. [ChIP-Atlas Diff Analysis](https://chip-atlas.org/diff_analysis) を実行する
    1. 事前に定義した heat-stress (dataset A) vs. ctrl (dataset B) のデータに従ってペアを作成し、実行する
2. `bedtools intersect -wo`を実行する CWLファイル [../../Workflow/bedtools_intersect_v2_scatter.cwl](../../Workflow/bedtools_intersect_v2_scatter.cwl)を実行する

&nbsp;

```bash
cwltool --outdir ./out/ChIP-Atlas_diff/ATACseq/bedfile_intersect_v2/ \
./Workflow/bedtools_intersect_v2_scatter.cwl \
./config/bedtools_intersect/chipatlas_diff_atacseq_v2.yml
```

&nbsp;

#### WARNING

- 以下の処理では、q-value < 0.01 でフィルタリングしている

In [2]:
INTERSECT_DIFF_COLUMNS = [
    # A: ChIP-Atlas diff DPR (8 cols)  <- query (-a)
    "dpr_chrom", "dpr_start", "dpr_end",
    "norm_count_A", "norm_count_B",  # dataset A → Heat stress, B → Control
    "log2fc", "p_value", "q_value",
    # B: fanta.bio CRE (11 cols)       <- database (-b)
    "cre_chrom", "cre_start", "cre_end", "cre_id",
    "cre_score", "cre_strand", "thickStart", "thickEnd",
    "itemRgb", "cre_name", "pooled_cre_scores",
    # -wo
    "overlap_bp",
]

In [3]:
#繰り返し処理を行う
BED_INTERSECT_DIR = pathlib.Path("../../out/ChIP-Atlas_diff/ATACseq/bedfile_intersect_v2")

def read_intersect_bed(bed_path: pathlib.Path, q_threshold: float = 0.01) -> pl.DataFrame:
    """
    Read one bedtools intersect -wo output and tag with diff dataset ID from filename.
    default q-value threshold is 0.01.
    """
    # v2 filename: <dataset>_intersecting_<cre-peaks>.bed
    diff_dataset = bed_path.stem.split("_intersecting_", 1)[0]

    return (
        pl.read_csv(
            bed_path,
            separator="\t",
            has_header=False,
            new_columns=INTERSECT_DIFF_COLUMNS,
            # Force float dtypes: leading "1" q-values can make Polars infer Int64
            # and drop scientific-notation significant hits under ignore_errors.
            schema_overrides={
                "dpr_start": pl.Int64,
                "dpr_end": pl.Int64,
                "log2fc": pl.Float64,
                "p_value": pl.Float64,
                "q_value": pl.Float64,
                "cre_start": pl.Int64,
                "cre_end": pl.Int64,
                "cre_score": pl.Int64,
                "thickStart": pl.Int64,
                "thickEnd": pl.Int64,
                "overlap_bp": pl.Int64,
            },
            n_threads=16,
            ignore_errors=True,
        )
        .filter(pl.col("q_value") < q_threshold)
        .with_columns(
            # Fraction of CRE length covered by the DPR overlap (-wo)
            (pl.col("overlap_bp") / (pl.col("cre_end") - pl.col("cre_start"))).alias("overlap_frac_of_fantabio_cre"),
            pl.struct(
                "dpr_start",
                "dpr_end",
                "dpr_chrom"
            ).alias("dpr_interval")
        )
        .with_columns(
            pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
            pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
        )
        .with_columns(
            pl.lit(diff_dataset).alias("diff_dataset"),
            pl.lit(bed_path.name).alias("source_bed_file"),
        )
        .drop("cre_score", "cre_strand", "thickStart", "thickEnd", "itemRgb", "pooled_cre_scores", "norm_count_A", "norm_count_B", "dpr_start", "dpr_end", "dpr_chrom")
    )

bed_paths = sorted(
    BED_INTERSECT_DIR.glob("*_intersecting_*.bed")
)

all_diff_df = (
    pl.concat(
        [read_intersect_bed(p) for p in bed_paths],
        how="vertical_relaxed",
    )
    .sort(
        "cre_chrom",
        descending=False,
    )
)


# mismatch = all_diff_df.filter(pl.col("cre_chrom") != pl.col("dpr_chrom"))
# print(f"mismatch rows: {mismatch.height}")
pl.Config.set_tbl_rows(10)
pl.Config.set_fmt_str_lengths(100)
display(all_diff_df)

shape: (13_364, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ log2fc    ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_b │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ ed_file  │
│ f64       ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1.346413  ┆ 5.4291e-5 ┆ 7.6313e-5 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.363021  ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.520449  ┆ 1.7373e-2 ┆ 4.2758e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 0         ┆ 8         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.470083  ┆ 4.9866e-9 ┆ 2.4993e-7 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 1.510948  ┆ 3.2981e-1 ┆ 6.1358e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆ 7         ┆ 5         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.782456  ┆ 0.000625  ┆ 0.005354  ┆ chrY      ┆ … ┆ -0.979798 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ ff_44C_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ 20min_in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ng_human │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -CREv1.2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .1.hg38. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peak │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed    │
│ 0.966208  ┆ 0.000259  ┆ 0.004473  ┆ chrY      ┆ … ┆ -0.884058 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ 1.249991  ┆ 0.000216  ┆ 0.003874  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
│ -2.288707 ┆ 1.9434e-7 ┆ 0.000013  ┆ chrY      ┆ … ┆ -0.428571 ┆ ELA       ┆ GSE101731 ┆ GSE10173 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ 1_atac_h │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ ff_44C_6 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ 0min_int │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ersectin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CREv1.2. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.hg38.c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ re-peaks │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

# Selection of Differencially Peaked Region (DPR)

&nbsp;

## (1) Filtering Condition

- `log2(Fold Change) > 0.5`
- [script/diff-analysis/diff_analysis_for_ChIP_ATAC_DNase.sh](https://github.com/inutano/chip-atlas/blob/master/script/diff-analysis/diff_analysis_for_ChIP_ATAC_DNase.sh)

In [4]:
all_diff_up = all_diff_df.filter(
    pl.col("log2fc") > 0.5
)

display(all_diff_up)

shape: (8_536, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc   ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64      ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.346413 ┆ 5.4291e-5 ┆ 7.6313e-5 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.363021 ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.520449 ┆ 1.7373e-2 ┆ 4.2758e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 0         ┆ 8         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.470083 ┆ 4.9866e-9 ┆ 2.4993e-7 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.510948 ┆ 3.2981e-1 ┆ 6.1358e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 7         ┆ 5         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3.001242 ┆ 0.000002  ┆ 0.001012  ┆ chrX      ┆ … ┆ 0.997951  ┆ PLA       ┆ GSE209675 ┆ GSE209675 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _mcf7_42C ┆ _mcf7_42C │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _60min    ┆ _60min_in │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersectin │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human-C │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ REv1.2.1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ hg38.cre- │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ peaks.bed │
│ 0.895061 ┆ 0.000014  ┆ 0.000234  ┆ chrY      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.782456 ┆ 0.000625  ┆ 0.005354  ┆ chrY      ┆ … ┆ -0.979798 ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.966208 ┆ 0.000259  ┆ 0.004473  ┆ chrY      ┆ … ┆ -0.884058 ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
│ 1.249991 ┆ 0.000216  ┆ 0.003874  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## (2) Filter by Overlap Fraction

- 対象は直前の `log2fc > 0.5` 通過後（`all_diff_up`）
- 同一 `diff_dataset` × `cre_id` で複数 DPR が重なる場合、`overlap_frac_of_fantabio_cre` が最大の行のみ残す
- check: `FCHS_5` の before / after を表示

In [5]:
# Among upregulated DPRs (log2fc > 0.5), keep max CRE-cover fraction
# per (diff_dataset, cre_id). Ties keep multiple rows.
CHECK_CRE_ID = "FCHS_5"

fchs5_before = all_diff_up.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(f"[before] {CHECK_CRE_ID}: {fchs5_before.height} rows")
display(fchs5_before)

all_diff_up_filtered = all_diff_up.filter(
    pl.col("overlap_frac_of_fantabio_cre")
    == pl.col("overlap_frac_of_fantabio_cre").max().over("diff_dataset", "cre_id")
)

fchs5_after = all_diff_up_filtered.filter(pl.col("cre_id") == CHECK_CRE_ID).sort(
    "diff_dataset",
    "overlap_frac_of_fantabio_cre",
    descending=[False, True],
)
print(
    f"[after]  {CHECK_CRE_ID}: {fchs5_after.height} rows "
    f"(all_diff_up {all_diff_up.height} -> {all_diff_up_filtered.height})"
)
display(fchs5_after)

[before] FCHS_5: 9 rows

shape: (9, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc   ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64      ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.363021 ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.520449 ┆ 1.7373e-2 ┆ 4.2758e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 0         ┆ 8         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.346413 ┆ 5.4291e-5 ┆ 7.6313e-5 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.470083 ┆ 4.9866e-9 ┆ 2.4993e-7 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.510948 ┆ 3.2981e-1 ┆ 6.1358e-1 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 7         ┆ 5         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.971139 ┆ 2.8597e-2 ┆ 3.1055e-2 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 5         ┆ 2         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
│ 1.074398 ┆ 5.8290e-1 ┆ 8.0810e-8 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
│ 1.021146 ┆ 0.00015   ┆ 0.002939  ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
│ 0.990666 ┆ 3.6290e-7 ┆ 0.000022  ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

[after]  FCHS_5: 2 rows (all_diff_up 8536 -> 6851)

shape: (2, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc   ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64      ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.363021 ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.971139 ┆ 2.8597e-2 ┆ 3.1055e-2 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 5         ┆ 2         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

## After Filtering

In [6]:
display(all_diff_up_filtered)

shape: (6_851, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ log2fc   ┆ p_value   ┆ q_value   ┆ cre_chrom ┆ … ┆ direction ┆ fantabio_ ┆ diff_data ┆ source_be │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ality     ┆ cre_class ┆ set       ┆ d_file    │
│ f64      ┆ f64       ┆ f64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1.363021 ┆ 2.5793e-4 ┆ 3.1990e-4 ┆ chr1      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 9         ┆ 6         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.231145 ┆ 3.7728e-5 ┆ 5.4236e-5 ┆ chr1      ┆ … ┆ 0.999887  ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 3         ┆ 0         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.516768 ┆ 1.5953e-6 ┆ 5.3109e-6 ┆ chr1      ┆ … ┆ 0.771711  ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 5         ┆ 2         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.516768 ┆ 1.5953e-6 ┆ 5.3109e-6 ┆ chr1      ┆ … ┆ -1.0      ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 5         ┆ 2         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 1.250148 ┆ 5.5115e-4 ┆ 5.3634e-4 ┆ chr1      ┆ … ┆ 0.565217  ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆ 6         ┆ 3         ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3.001242 ┆ 0.000002  ┆ 0.001012  ┆ chrX      ┆ … ┆ 0.997951  ┆ PLA       ┆ GSE209675 ┆ GSE209675 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _mcf7_42C ┆ _mcf7_42C │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _60min    ┆ _60min_in │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tersectin │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g_human-C │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ REv1.2.1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ hg38.cre- │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ peaks.bed │
│ 0.895061 ┆ 0.000014  ┆ 0.000234  ┆ chrY      ┆ … ┆ 1.0       ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.782456 ┆ 0.000625  ┆ 0.005354  ┆ chrY      ┆ … ┆ -0.979798 ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_120m ┆ _44C_120m │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ in        ┆ in_inters │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ecting_hu │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ man-CREv1 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2.1.hg38 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .cre-peak │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s.bed     │
│ 0.966208 ┆ 0.000259  ┆ 0.004473  ┆ chrY      ┆ … ┆ -0.884058 ┆ ELA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
│ 1.249991 ┆ 0.000216  ┆ 0.003874  ┆ chrY      ┆ … ┆ -0.998313 ┆ PLA       ┆ GSE101731 ┆ GSE101731 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _atac_hff ┆ _atac_hff │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ _44C_60mi ┆ _44C_60mi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ n         ┆ n_interse │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cting_hum │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an-CREv1. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2.1.hg38. │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ cre-peaks │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ .bed      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# Aggregate upregulated + max-overlap DPRs to CRE level
all_diff_up_select = all_diff_up_filtered.group_by(
    [
        "cre_chrom",
        "cre_start",
        "cre_end",
        "cre_id",
        "cre_name",
        # "dpr_chrom",
        "directionality",
        "fantabio_cre_class"
    ]
).agg(
    pl.col("overlap_frac_of_fantabio_cre").alias("overlap_frac_of_fantabio_cre"),
    pl.col("dpr_interval").alias("dpr_interval"),
    pl.col("log2fc").alias("log2fc"),
    pl.col("p_value").alias("p_value"),
    pl.col("q_value").alias("q_value"),
    pl.col("diff_dataset").unique().alias("diff_dataset"),
    pl.col("diff_dataset").unique().count().alias("diff_dataset_count"),
    pl.col("source_bed_file").alias("source_bed_file"),
).sort(
    "cre_chrom",
    "cre_start",
    "cre_end",
    descending=False
)

pl.Config.set_tbl_rows(6)
display(all_diff_up_select)

shape: (5_511, 15)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_chrom ┆ cre_start ┆ cre_end  ┆ cre_id    ┆ … ┆ q_value   ┆ diff_data ┆ diff_data ┆ source_be │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ set       ┆ set_count ┆ d_file    │
│ str       ┆ i64       ┆ i64      ┆ str       ┆   ┆ list[f64] ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆ list[str] ┆ u32       ┆ list[str] │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr1      ┆ 629081    ┆ 629273   ┆ FCHS_5    ┆ … ┆ [3.1990e- ┆ ["GSE1017 ┆ 2         ┆ ["GSE1017 │
│           ┆           ┆          ┆           ┆   ┆ 46, 3.105 ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆ 5e-22]    ┆ ff_44C_12 ┆           ┆ ff_44C_12 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 0min",    ┆           ┆ 0min_inte │
│           ┆           ┆          ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ rsecting_ │
│           ┆           ┆          ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ human-CRE │
│           ┆           ┆          ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ v1.2.1.hg │
│           ┆           ┆          ┆           ┆   ┆           ┆ in"]      ┆           ┆ 38.cre-pe │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ aks.bed", │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ "GSE10173 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1_atac_hf │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ …         │
│ chr1      ┆ 629469    ┆ 630126   ┆ FCHS_6    ┆ … ┆ [5.4236e- ┆ ["GSE1017 ┆ 2         ┆ ["GSE1017 │
│           ┆           ┆          ┆           ┆   ┆ 50, 9.107 ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆ 2e-27]    ┆ ff_44C_12 ┆           ┆ ff_44C_12 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 0min",    ┆           ┆ 0min_inte │
│           ┆           ┆          ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ rsecting_ │
│           ┆           ┆          ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ human-CRE │
│           ┆           ┆          ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ v1.2.1.hg │
│           ┆           ┆          ┆           ┆   ┆           ┆ in"]      ┆           ┆ 38.cre-pe │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ aks.bed", │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ "GSE10173 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1_atac_hf │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ …         │
│ chr1      ┆ 629938    ┆ 630317   ┆ FCHS_7    ┆ … ┆ [5.3109e- ┆ ["GSE1017 ┆ 2         ┆ ["GSE1017 │
│           ┆           ┆          ┆           ┆   ┆ 62, 1.311 ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆ 4e-27]    ┆ ff_44C_12 ┆           ┆ ff_44C_12 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 0min",    ┆           ┆ 0min_inte │
│           ┆           ┆          ┆           ┆   ┆           ┆ "GSE10173 ┆           ┆ rsecting_ │
│           ┆           ┆          ┆           ┆   ┆           ┆ 1_atac_hf ┆           ┆ human-CRE │
│           ┆           ┆          ┆           ┆   ┆           ┆ f_44C_60m ┆           ┆ v1.2.1.hg │
│           ┆           ┆          ┆           ┆   ┆           ┆ in"]      ┆           ┆ 38.cre-pe │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ aks.bed", │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ "GSE10173 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1_atac_hf │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ …         │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ chrY      ┆ 11329762  ┆ 11329941 ┆ FCHS_4470 ┆ … ┆ [0.004473 ┆ ["GSE1017 ┆ 1         ┆ ["GSE1017 │
│           ┆           ┆          ┆ 44        ┆   ┆ ]         ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆           ┆ ff_44C_60 ┆           ┆ ff_44C_60 │
│           ┆           ┆          ┆           ┆   ┆           ┆ min"]     ┆           ┆ min_inter │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ secting_h │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ uman-CREv │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.2.1.hg3 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pea │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ks.bed"]  │
│ chrY      ┆ 19077163  ┆ 19077775 ┆ FCHS_4472 ┆ … ┆ [0.003874 ┆ ["GSE1017 ┆ 1         ┆ ["GSE1017 │
│           ┆           ┆          ┆ 46        ┆   ┆ ]         ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆           ┆ ff_44C_60 ┆           ┆ ff_44C_60 │
│           ┆           ┆          ┆           ┆   ┆           ┆ min"]     ┆           ┆ min_inter │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ secting_h │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ uman-CREv │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.2.1.hg3 │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.cre-pea │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ ks.bed"]  │
│ chrY      ┆ 26670966  ┆ 26671518 ┆ FCHS_4473 ┆ … ┆ [0.005354 ┆ ["GSE1017 ┆ 1         ┆ ["GSE1017 │
│           ┆           ┆          ┆ 08        ┆   ┆ ]         ┆ 31_atac_h ┆           ┆ 31_atac_h │
│           ┆           ┆          ┆           ┆   ┆           ┆ ff_44C_12 ┆           ┆ ff_44C_12 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 0min"]    ┆           ┆ 0min_inte │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ rsecting_ │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ human-CRE │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ v1.2.1.hg │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ 38.cre-pe │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ aks.bed"] │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
all_diff_up_select.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/only_cre/fantabio_cre_list_diff_analysis_atac.parquet"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Intergration (upregulated transcripts)

In [9]:
# up5p transcript lists + CRE
fantabio_HN2_up5p_transcripts_cre = pl.read_parquet(
    "../../out/fantabio/parquet_file/up5p_transcript_fantabio_v261001.parquet"
).join(
    all_diff_up_select,
    on=["cre_id", "cre_chrom", "cre_name", "directionality", "fantabio_cre_class"],
    how="inner",
    coalesce=True
)

fantabio_HN2_up5p_transcripts_cre.write_parquet(
    "../../out/ChIP-Atlas_diff/diff_analysis_filter_parquet/transcript_cre/fantabio_HN2_up5p_v261002_diff_analysis_atac.parquet"
)

print(f"up5p_fantabio transcript count: {fantabio_HN2_up5p_transcripts_cre.select('transcript_id').n_unique()}")
print(f"up5p_fantabio transcript-CRE pairs count: {fantabio_HN2_up5p_transcripts_cre.select(['transcript_id', 'cre_id']).n_unique()}")
pl.Config.set_tbl_rows(4)
display(fantabio_HN2_up5p_transcripts_cre)

up5p_fantabio transcript count: 2497
up5p_fantabio transcript-CRE pairs count: 4423

shape: (4_423, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 0.000487]   ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min",   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE209675_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf7_42C_60 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ min"]       ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 4          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ … 0.000487] ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min", … ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE209675_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf7_42C_60 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ min"]       ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Protein-coding Transcripts

In [14]:
# (check whether the protein-coding transcripts - CREs are heat stress-responsive related transcripts)
fantabio_HN2_up5p_transcripts_cre_pc = fantabio_HN2_up5p_transcripts_cre.filter(
    pl.col("transcript_type") == "protein_coding"
)

up5p_pc_list = fantabio_HN2_up5p_transcripts_cre_pc.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/up5p/HN2_up5p_fantabio_check_diff_analysis_atac_pc_v261002.tsv",
    separator="\t",
    include_header=False
)

print(f"up5p_fantabio protein-coding transcript count: {fantabio_HN2_up5p_transcripts_cre_pc.select("transcript_id").n_unique()}")
print(f"up5p_fantabio protein-coding transcript-CRE pairs count: {fantabio_HN2_up5p_transcripts_cre_pc.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_up5p_transcripts_cre_pc)

up5p_fantabio protein-coding transcript count: 1667
up5p_fantabio protein-coding transcript-CRE pairs count: 3018

shape: (3_018, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 0.000487]   ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min",   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE209675_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf7_42C_60 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ min"]       ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000030 ┆ 352 ┆ 17    ┆ 37         ┆ … ┆ [0.000001,  ┆ ["GSE101731 ┆ 4          ┆ ["GSE10173 │
│ 9758.6      ┆     ┆       ┆            ┆   ┆ 2.0457e-12, ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ … 0.000487] ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min", … ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE209675_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ mcf7_42C_60 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ min"]       ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000087 ┆ 98  ┆ 54    ┆ 254        ┆ … ┆ [0.00857]   ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3745.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000089 ┆ 91  ┆ 47    ┆ 268        ┆ … ┆ [0.000075]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 2645.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [12]:
# check HSPH1
HSPH1 = fantabio_HN2_up5p_transcripts_cre_pc.filter(
    pl.col("gene_symbol") == "HSPH1"
)

display(HSPH1)

shape: (13, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000095 ┆ 276 ┆ 13    ┆ 117        ┆ … ┆ [0.000003,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 4002.1      ┆     ┆       ┆            ┆   ┆ 6.8502e-7]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ ENST0000038 ┆ 243 ┆ 17    ┆ 146        ┆ … ┆ [0.005395]  ┆ ["GSE173536 ┆ 1          ┆ ["GSE17353 │
│ 0405.7      ┆     ┆       ┆            ┆   ┆             ┆ _atac_t21_4 ┆            ┆ 6_atac_t21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min"]  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed"] │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000095 ┆ 76  ┆ 2     ┆ 328        ┆ … ┆ [0.000003,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 4005.1      ┆     ┆       ┆            ┆   ┆ 6.8502e-7]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ ENST0000063 ┆ 120 ┆ 68    ┆ 218        ┆ … ┆ [0.000003,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 0972.2      ┆     ┆       ┆            ┆   ┆ 6.8502e-7]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## lncRNA

In [15]:
fantabio_HN2_up5p_transcripts_cre_lncrna = fantabio_HN2_up5p_transcripts_cre.filter(
    pl.col("transcript_type") == "lncRNA"
).sort(
    pl.col([
        "HN2",
        "transcript_id"
    ]),
    descending=True
)

up5p_lncrna_list = fantabio_HN2_up5p_transcripts_cre_lncrna.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/up5p/HN2_up5p_fantabio_check_diff_analysis_atac_lncrna_v261002.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(4)
print(f"up5p_fantabio lncRNA transcript count: {fantabio_HN2_up5p_transcripts_cre_lncrna.select("transcript_id").n_unique()}")
print(f"up5p_fantabio lncRNA transcript-CRE pairs count: {fantabio_HN2_up5p_transcripts_cre_lncrna.select(['transcript_id', 'cre_id']).n_unique()}")
display(fantabio_HN2_up5p_transcripts_cre_lncrna)

up5p_fantabio lncRNA transcript count: 291
up5p_fantabio lncRNA transcript-CRE pairs count: 459

shape: (459, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000072 ┆ 315 ┆ 20    ┆ 71         ┆ … ┆ [0.000003,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 9765.1      ┆     ┆       ┆            ┆   ┆ 6.8502e-7]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ ENST0000070 ┆ 300 ┆ 17    ┆ 89         ┆ … ┆ [1.6168e-7] ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 2650.2      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000066 ┆ 125 ┆ 81    ┆ 200        ┆ … ┆ [0.000005]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 0312.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000045 ┆ 55  ┆ 11    ┆ 340        ┆ … ┆ [6.8953e-19 ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3754.6      ┆     ┆       ┆            ┆   ┆ ]           ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

## Other Transcripts

In [16]:
fantabio_HN2_up5p_transcripts_cre_other = fantabio_HN2_up5p_transcripts_cre.filter(
    (pl.col("transcript_type") != "lncRNA") & (pl.col("transcript_type") != "protein_coding")
).sort(
    pl.col("HN2"),
    descending=True
)

up5p_other_list = fantabio_HN2_up5p_transcripts_cre_other.select("transcript_id").unique().write_csv(
    "../../out/metascape/transcript_list/up5p/HN2_up5p_fantabio_check_diff_analysis_atac_other_v261002.tsv",
    separator="\t",
    include_header=False
)

pl.Config.set_tbl_rows(10)
print(fantabio_HN2_up5p_transcripts_cre_other.select("transcript_id").n_unique())
print(fantabio_HN2_up5p_transcripts_cre_other.group_by("transcript_type").agg(pl.col("transcript_id").n_unique().alias("transcript_type_count")))
display(fantabio_HN2_up5p_transcripts_cre_other)

539
shape: (10, 2)
┌────────────────────────────────────┬───────────────────────┐
│ transcript_type                    ┆ transcript_type_count │
│ ---                                ┆ ---                   │
│ str                                ┆ u32                   │
╞════════════════════════════════════╪═══════════════════════╡
│ nonsense_mediated_decay            ┆ 220                   │
│ vault_RNA                          ┆ 1                     │
│ miRNA                              ┆ 1                     │
│ retained_intron                    ┆ 168                   │
│ Mt_rRNA                            ┆ 1                     │
│ protein_coding_CDS_not_defined     ┆ 140                   │
│ processed_pseudogene               ┆ 2                     │
│ transcribed_unprocessed_pseudogene ┆ 2                     │
│ snRNA                              ┆ 1                     │
│ TEC                                ┆ 3                     │
└────────────────────────────────────┴───────────────────────┘

shape: (946, 49)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ q_value     ┆ diff_datase ┆ diff_datas ┆ source_bed │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---         ┆ t           ┆ et_count   ┆ _file      │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ list[f64]   ┆ ---         ┆ ---        ┆ ---        │
│ str         ┆     ┆       ┆            ┆   ┆             ┆ list[str]   ┆ u32        ┆ list[str]  │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000054 ┆ 328 ┆ 9     ┆ 69         ┆ … ┆ [2.5591e-9, ┆ ["GSE101731 ┆ 3          ┆ ["GSE10173 │
│ 0260.1      ┆     ┆       ┆            ┆   ┆ 0.009422,   ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆ 2.1133e-15] ┆ 4C_120min", ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_d21_42 ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min",   ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ , "GSE1735 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ 36_atac_d2 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ …          │
│ ENST0000055 ┆ 329 ┆ 18    ┆ 59         ┆ … ┆ [1.2453e-19 ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 5662.1      ┆     ┆       ┆            ┆   ┆ ,           ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆ 1.4578e-12] ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ ENST0000053 ┆ 315 ┆ 21    ┆ 70         ┆ … ┆ [1.6592e-12 ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 3567.5      ┆     ┆       ┆            ┆   ┆ ]           ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000044 ┆ 300 ┆ 9     ┆ 97         ┆ … ┆ [0.005999,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 7574.1      ┆     ┆       ┆            ┆   ┆ 0.007112]   ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ ENST0000044 ┆ 300 ┆ 9     ┆ 97         ┆ … ┆ [0.000012,  ┆ ["GSE173536 ┆ 2          ┆ ["GSE17353 │
│ 7574.1      ┆     ┆       ┆            ┆   ┆ 4.9974e-8]  ┆ _atac_d21_4 ┆            ┆ 6_atac_d21 │
│             ┆     ┆       ┆            ┆   ┆             ┆ 2C_60min",  ┆            ┆ _42C_60min │
│             ┆     ┆       ┆            ┆   ┆             ┆ "GSE173536_ ┆            ┆ _intersect │
│             ┆     ┆       ┆            ┆   ┆             ┆ atac_t21_42 ┆            ┆ ing_human- │
│             ┆     ┆       ┆            ┆   ┆             ┆ C_60min"]   ┆            ┆ CREv1.2.1. │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ hg38.cre-p │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ eaks.bed", │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ "GSE173536 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ _atac_t21… │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000050 ┆ 116 ┆ 72    ┆ 218        ┆ … ┆ [5.9509e-8] ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 5125.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000050 ┆ 116 ┆ 72    ┆ 218        ┆ … ┆ [5.9509e-8] ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 5125.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000050 ┆ 116 ┆ 72    ┆ 218        ┆ … ┆ [5.9509e-8] ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 5125.5      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
│ ENST0000067 ┆ 102 ┆ 58    ┆ 246        ┆ … ┆ [0.008726]  ┆ ["GSE101731 ┆ 1          ┆ ["GSE10173 │
│ 8039.1      ┆     ┆       ┆            ┆   ┆             ┆ _atac_hff_4 ┆            ┆ 1_atac_hff │
│             ┆     ┆       ┆            ┆   ┆             ┆ 4C_120min"] ┆            ┆ _44C_120mi │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ n_intersec │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ting_human │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ -CREv1.2.1 │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ .hg38.cre- │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ peaks.bed" │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ ]          │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘