&nbsp;

# [`fanta.bio`](https://fanta.bio/) Pre-Process

- `BED` ファイルの加工などを行う

In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import matplotlib.pyplot as plt

from IPython.display import display


os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
Execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {Execute_date}")

Execute Date: 261001

In [3]:
# https://data.fanta.bio/cre/v1.2.1/00README_v1.2.1.txt
fantabio_bed = pl.read_csv(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks.bed",
    separator="\t",
    has_header=False,
    new_columns=[
        "cre_chrom",
        "cre_chrom_start",
        "cre_chrom_end",
        "cre_id",
        "score",
        "strand",
        "thickStart",
        "thickEnd",
        "itemRgb",
        "cre_name",
        "pooled_cre_scores"
    ]
).with_columns(
    pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
    pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
)

display(fantabio_bed)

shape: (513_895, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 10609     ┆ 10687     ┆ FCHS_1    ┆ … ┆ cp1@DDX11 ┆ direction ┆ -1.0      ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ L1        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:PLA ┆           ┆          │
│ chr1      ┆ 29398     ┆ 29439     ┆ FCHS_2    ┆ … ┆ cp1@WASH7 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ P         ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chr1      ┆ 181113    ┆ 181501    ┆ FCHS_4474 ┆ … ┆ cp1@DDX11 ┆ direction ┆ -0.684211 ┆ ELA      │
│           ┆           ┆           ┆ 16        ┆   ┆ L17       ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 684211|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ chr1      ┆ 190831    ┆ 191016    ┆ FCHS_4474 ┆ … ┆ FCHS_4474 ┆ direction ┆ 0.485714  ┆ ELA      │
│           ┆           ┆           ┆ 17        ┆   ┆ 17        ┆ ality:0.4 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 85714|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chr1      ┆ 588413    ┆ 588453    ┆ FCHS_3    ┆ … ┆ cp2@LOC10 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ 1928626   ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 56846801  ┆ 56846977  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆ 11        ┆   ┆ 11        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56855787  ┆ 56855988  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 0.0       ┆ ELA      │
│           ┆           ┆           ┆ 12        ┆   ┆ 12        ┆ ality:0|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56863206  ┆ 56863354  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 13        ┆   ┆ 13        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chrY      ┆ 56864544  ┆ 56864748  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 14        ┆   ┆ 14        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chrY      ┆ 56881614  ┆ 56881922  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.989305  ┆ PLA      │
│           ┆           ┆           ┆ 40        ┆   ┆ 40        ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 89305|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Only `PLA (Promoter Level Activity)` CRE BED file

- ChIP-Atlas の `Enrichment Analysis` 用に分離しておく
- GENCODE で定義されている transcript が近傍にないものであっても選抜している

In [4]:
fantabio_bed_pla = fantabio_bed.filter(
    pl.col("fantabio_cre_class") == "PLA"
)

fantabio_bed_pla.select(
    "cre_chrom",
    "cre_chrom_start",
    "cre_chrom_end"
).write_csv(
    "../../out/fantabio/BEDfile_ref/human-CREv1.2.1.hg38.cre-peaks_pla_all.bed",
    separator="\t",
    include_header=False
)

display(fantabio_bed_pla)

shape: (72_627, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 10609     ┆ 10687     ┆ FCHS_1    ┆ … ┆ cp1@DDX11 ┆ direction ┆ -1.0      ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ L1        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:PLA ┆           ┆          │
│ chr1      ┆ 629469    ┆ 630126    ┆ FCHS_6    ┆ … ┆ cp1@MTND2 ┆ direction ┆ 0.999887  ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ P28       ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 99887|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chr1      ┆ 629938    ┆ 630317    ┆ FCHS_7    ┆ … ┆ cp2@MTND2 ┆ direction ┆ 0.771711  ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ P28       ┆ ality:0.7 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 71711|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chr1      ┆ 631390    ┆ 631686    ┆ FCHS_4474 ┆ … ┆ cp3@LOC10 ┆ direction ┆ -0.654321 ┆ PLA      │
│           ┆           ┆           ┆ 19        ┆   ┆ 1928626   ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 654321|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ chr1      ┆ 633105    ┆ 633714    ┆ FCHS_13   ┆ … ┆ cp1@MTATP ┆ direction ┆ 0.999463  ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ 6P1,cp1@M ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ TATP8P1   ┆ 99463|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 21177265  ┆ 21177875  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ -0.90566  ┆ PLA      │
│           ┆           ┆           ┆ 29        ┆   ┆ 29        ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 90566|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chrY      ┆ 21254641  ┆ 21254810  ┆ FCHS_4472 ┆ … ┆ FCHS_4472 ┆ direction ┆ 1.0       ┆ PLA      │
│           ┆           ┆           ┆ 97        ┆   ┆ 97        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:PLA  ┆           ┆          │
│ chrY      ┆ 21404652  ┆ 21404951  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ -0.943641 ┆ PLA      │
│           ┆           ┆           ┆ 34        ┆   ┆ 34        ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 943641|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ chrY      ┆ 26408845  ┆ 26409331  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.638596  ┆ PLA      │
│           ┆           ┆           ┆ 37        ┆   ┆ 37        ┆ ality:0.6 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 38596|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chrY      ┆ 56881614  ┆ 56881922  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.989305  ┆ PLA      │
│           ┆           ┆           ┆ 40        ┆   ┆ 40        ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 89305|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Only `ELA (Enhancer-Level Activity)` CRE BED file

- ChIP-Atlas の `Enrichment Analysis` 用に分離しておく
- GENCODE で定義されている transcript が近傍にないものであっても選抜している

In [5]:
fantabio_bed_ela = fantabio_bed.filter(
    pl.col("fantabio_cre_class") == "ELA"
)

fantabio_bed_ela.select(
    "cre_chrom",
    "cre_chrom_start",
    "cre_chrom_end"
).write_csv(
    "../../out/fantabio/BEDfile_ref/human-CREv1.2.1.hg38.cre-peaks_ela_all.bed",
    separator="\t",
    include_header=False
)

display(fantabio_bed_ela)

shape: (441_268, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 29398     ┆ 29439     ┆ FCHS_2    ┆ … ┆ cp1@WASH7 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ P         ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chr1      ┆ 181113    ┆ 181501    ┆ FCHS_4474 ┆ … ┆ cp1@DDX11 ┆ direction ┆ -0.684211 ┆ ELA      │
│           ┆           ┆           ┆ 16        ┆   ┆ L17       ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 684211|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ chr1      ┆ 190831    ┆ 191016    ┆ FCHS_4474 ┆ … ┆ FCHS_4474 ┆ direction ┆ 0.485714  ┆ ELA      │
│           ┆           ┆           ┆ 17        ┆   ┆ 17        ┆ ality:0.4 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 85714|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chr1      ┆ 588413    ┆ 588453    ┆ FCHS_3    ┆ … ┆ cp2@LOC10 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ 1928626   ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chr1      ┆ 605408    ┆ 605588    ┆ FCHS_4    ┆ … ┆ FCHS_4    ┆ direction ┆ 0.575758  ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ality:0.5 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 75758|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 56833095  ┆ 56833397  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆ 39        ┆   ┆ 39        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56846801  ┆ 56846977  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆ 11        ┆   ┆ 11        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56855787  ┆ 56855988  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 0.0       ┆ ELA      │
│           ┆           ┆           ┆ 12        ┆   ┆ 12        ┆ ality:0|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56863206  ┆ 56863354  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 13        ┆   ┆ 13        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chrY      ┆ 56864544  ┆ 56864748  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 14        ┆   ┆ 14        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Only `PLA` and `ELA` CRE BED file (GENCODE-transcript-linked CREs)

- GENCODE version 49 の transcript が近傍にあるシスエレメントのみを選抜し、ChIP-Atlas Enrichment Analysis における background data とする

In [6]:
# Download from https://data.fanta.bio/cre/v1.2.0/human/ in 2026/03/10
fantabio_human_metadata = pl.read_ndjson(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks_annotation.jsonl.gz"
).drop(
    "cre_old_names",
    "tss_ncbi_geneids",
    "tss_hgnc_mgi_ids",
    "tss_uniprot_ids",
    "tss_gene_names",
    "tss_gene_symbols",
    "tss_gene_synonyms",
    "tss_gene_sources"
).with_columns(
    # Q-score は後々フィルタリングの条件に使うかもしれないため、cast(pl.Int64) で整数型に変換しておく
    # print(fanta_bio_human_metadata["chip_atlas_antigens"].dtype) で確認できる
    pl.col("chip_atlas_antigens").list.eval(
        pl.struct([
            pl.element().struct.field("antigen").alias("antigen"),
            pl.element().struct.field("maxqscore").cast(pl.Int64).alias("maxqscore"),
            pl.element().struct.field("experiments").list.eval(
                pl.struct([
                    pl.element().struct.field("id").alias("id"),
                    pl.element().struct.field("qscore").cast(pl.Int64).alias("qscore"),
                ])
            ).alias("experiments"),
        ])
    ).alias("chip_atlas_antigens"),
).explode(
    "tss_transcripts"
).unnest(
    "tss_transcripts"
).filter(
    (pl.col("transcript_id").str.contains("ENST")) # Point1: Ensembl Transcript ID のみに絞る
).with_columns(
    # Point2: "transcript_distance" は str 型で読み込まれるが, int 型に変換しておく
    pl.col("transcript_distance")
    .cast(pl.Float64, strict=False)
    .round(0) # 小数点以下を四捨五入 (8件のみ .5 が存在)
    .cast(pl.Int64)
)

pl.Config.set_tbl_rows(4)
print(fantabio_human_metadata.select("cre_id").n_unique()) # Ensembl Transcript ID のみに絞った場合のユニークな CRE ID 数
display(fantabio_human_metadata)

162925

shape: (1_121_578, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ … ┆ chip_atla ┆ silencerd ┆ fantom5_c ┆ fantom5_ │
│ ---       ┆ ---       ┆ _start    ┆ _end      ┆   ┆ s_antigen ┆ bs        ┆ age_peaks ┆ enhancer │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ s         ┆ ---       ┆ ---       ┆ s        │
│           ┆           ┆ i64       ┆ str       ┆   ┆ ---       ┆ list[stru ┆ list[stru ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[stru ┆ ct[5]]    ┆ ct[2]]    ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆ ct[3]]    ┆           ┆           ┆ uct[1]]  │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1    ┆ chr1      ┆ 10610     ┆ 10687     ┆ … ┆ [{"EGR1", ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 2552,[{"S ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ RX2282871 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 2",…      ┆           ┆           ┆          │
│ FCHS_1    ┆ chr1      ┆ 10610     ┆ 10687     ┆ … ┆ [{"EGR1", ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 2552,[{"S ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ RX2282871 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 2",…      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_5939 ┆ chrY      ┆ 26409259  ┆ 26409692  ┆ … ┆ [{"MYCN", ┆ null      ┆ null      ┆ null     │
│ 38        ┆           ┆           ┆           ┆   ┆ 537,[{"SR ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ X6935376" ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ,53…      ┆           ┆           ┆          │
│ FCHS_5939 ┆ chrY      ┆ 56881615  ┆ 56881922  ┆ … ┆ [{"RELA", ┆ null      ┆ [{"hg19:: ┆ null     │
│ 40        ┆           ┆           ┆           ┆   ┆ 1452,[{"S ┆           ┆ chrY:5902 ┆          │
│           ┆           ┆           ┆           ┆   ┆ RX5938177 ┆           ┆ 7988..590 ┆          │
│           ┆           ┆           ┆           ┆   ┆ ",1…      ┆           ┆ 280…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
fantabio_human_metadata_viz = fantabio_human_metadata.join(
    fantabio_bed.select("cre_id", "cre_name", "fantabio_cre_class"),
    on="cre_id",
    how="inner"
).with_columns(
    pl.col("transcript_distance").abs().alias("transcript_distance_abs") # Point: 絶対値に変換
).select(
    "cre_id",
    "transcript_id",
    "transcript_distance",
    "transcript_distance_abs",
    "fantabio_cre_class",
    "cre_name"
)

display(fantabio_human_metadata_viz)

shape: (1_121_578, 6)
┌─────────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┬─────────────┐
│ cre_id      ┆ transcript_id   ┆ transcript_dist ┆ transcript_dist ┆ fantabio_cre_c ┆ cre_name    │
│ ---         ┆ ---             ┆ ance            ┆ ance_abs        ┆ lass           ┆ ---         │
│ str         ┆ str             ┆ ---             ┆ ---             ┆ ---            ┆ str         │
│             ┆                 ┆ i64             ┆ i64             ┆ str            ┆             │
╞═════════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╪═════════════╡
│ FCHS_1      ┆ ENST00000832824 ┆ 434             ┆ 434             ┆ PLA            ┆ cp1@DDX11L1 │
│             ┆ .1              ┆                 ┆                 ┆                ┆             │
│ FCHS_1      ┆ ENST00000832825 ┆ 438             ┆ 438             ┆ PLA            ┆ cp1@DDX11L1 │
│             ┆ .1              ┆                 ┆                 ┆                ┆             │
│ …           ┆ …               ┆ …               ┆ …               ┆ …              ┆ …           │
│ FCHS_593938 ┆ ENST00000344424 ┆ 123             ┆ 123             ┆ ELA            ┆ FCHS_593938 │
│             ┆ .4              ┆                 ┆                 ┆                ┆             │
│ FCHS_593940 ┆ ENST00000810723 ┆ 0               ┆ 0               ┆ PLA            ┆ FCHS_593940 │
│             ┆ .1              ┆                 ┆                 ┆                ┆             │
└─────────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┴─────────────┘

In [8]:
plot_df = fantabio_human_metadata_viz.to_pandas()

# 5 bins: 0-100, 101-200, ..., 401-500
bin_edges = [0, 101, 201, 301, 401, 501]
bin_labels = ["0-100", "101-200", "201-300", "301-400", "401-500"]

plot_df["distance_bin"] = pd.cut(
    plot_df["transcript_distance_abs"],
    bins=bin_edges,
    labels=bin_labels,
    right=False,
    include_lowest=True,
)

count_df = (
    plot_df.groupby(["distance_bin", "fantabio_cre_class"], observed=True)
    .size()
    .to_frame("count")
    .reset_index()
)

pivot_df = (
    count_df.pivot(index="distance_bin", columns="fantabio_cre_class", values="count")
    .fillna(0)
    .astype(int)
    .reindex(bin_labels)
)

classes = pivot_df.columns.tolist()
palette = sns.color_palette("Set2", n_colors=len(classes))
color_map = dict(zip(classes, palette))

sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(16, 10))

bottom = np.zeros(len(pivot_df))
x = np.arange(len(pivot_df.index))

for cls in classes:
    heights = pivot_df[cls].to_numpy()
    ax.bar(
        x,
        heights,
        bottom=bottom,
        label=cls,
        color=color_map[cls],
        edgecolor="white",
        linewidth=0.5,
    )
    bottom += heights

ax.set_xticks(x)
ax.set_xticklabels(pivot_df.index, fontsize=14)
ax.set_xlabel("|transcript distance| bin (bp)", fontsize=18)
ax.set_ylabel("Count (lncRNA–CRE pairs)", fontsize=18)
ax.set_title("100 bp bins by GENCODE v49 transcript - CRE pairs", fontsize=18)
ax.legend(title="fantabio CRE class", bbox_to_anchor=(1.02, 1), loc="upper left")
ax.tick_params(axis="y", labelsize=14)

plt.tight_layout()
plt.show()

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Only `PLA (Promoter-Level Activity)` CRE BED file with GENCODE transcript

- Promoter Level Activity (PLA) CREs のうち、GENCODE-transcript-linked CREs を抽出する

In [9]:
fantabio_bed_pla_gencode_transcript_linked = fantabio_bed.filter(
    pl.col("fantabio_cre_class") == "PLA"
).join(
    fantabio_human_metadata.select("cre_id").unique(),
    on="cre_id",
    how="semi",
)

fantabio_bed_pla_gencode_transcript_linked.select(
    "cre_chrom",
    "cre_chrom_start",
    "cre_chrom_end"
).write_csv(
    "../../out/fantabio/BEDfile_ref/human-CREv1.2.1.hg38.cre-peaks_pla_gencode_transcript_linked.bed",
    separator="\t",
    include_header=False
)

print(fantabio_bed_pla.height)
print(
    fantabio_bed_pla.filter(
        ~pl.col("cre_id").is_in(fantabio_human_metadata["cre_id"]) # 近傍に GENCODE-transcript が存在しない CRE をカウント
    ).height
)

display(fantabio_bed_pla_gencode_transcript_linked)

72627

/tmp/ipykernel_75317/1286234112.py:21: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  fantabio_bed_pla.filter(

20789

shape: (51_838, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 10609     ┆ 10687     ┆ FCHS_1    ┆ … ┆ cp1@DDX11 ┆ direction ┆ -1.0      ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ L1        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:PLA ┆           ┆          │
│ chr1      ┆ 629469    ┆ 630126    ┆ FCHS_6    ┆ … ┆ cp1@MTND2 ┆ direction ┆ 0.999887  ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ P28       ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 99887|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 26408845  ┆ 26409331  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.638596  ┆ PLA      │
│           ┆           ┆           ┆ 37        ┆   ┆ 37        ┆ ality:0.6 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 38596|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chrY      ┆ 56881614  ┆ 56881922  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.989305  ┆ PLA      │
│           ┆           ┆           ┆ 40        ┆   ┆ 40        ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 89305|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Only `ELA (Enhancer-Level Activity)` CRE BED file with GENCODE transcript

- Enhancer Level Activity (ELA) CREs のうち、GENCODE-transcript-linked CREs を抽出する

In [10]:
fantabio_bed_ela_gencode_transcript_linked = fantabio_bed.filter(
    pl.col("fantabio_cre_class") == "ELA"
).join(
    fantabio_human_metadata.select("cre_id").unique(),
    on="cre_id",
    how="semi",
)

fantabio_bed_ela_gencode_transcript_linked.select(
    "cre_chrom",
    "cre_chrom_start",
    "cre_chrom_end"
).write_csv(
    "../../out/fantabio/BEDfile_ref/human-CREv1.2.1.hg38.cre-peaks_ela_gencode_transcript_linked.bed",
    separator="\t",
    include_header=False
)


print(fantabio_bed_ela.height)
print(
    fantabio_bed_ela.filter(
        ~pl.col("cre_id").is_in(fantabio_human_metadata["cre_id"]) # 近傍に GENCODE-transcript が存在しない CRE をカウント
    ).height
)

display(fantabio_bed_ela_gencode_transcript_linked)

441268

/tmp/ipykernel_75317/2787901369.py:22: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  fantabio_bed_ela.filter(

330181

shape: (111_087, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 29398     ┆ 29439     ┆ FCHS_2    ┆ … ┆ cp1@WASH7 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ P         ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chr1      ┆ 181113    ┆ 181501    ┆ FCHS_4474 ┆ … ┆ cp1@DDX11 ┆ direction ┆ -0.684211 ┆ ELA      │
│           ┆           ┆           ┆ 16        ┆   ┆ L17       ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 684211|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 26409025  ┆ 26409052  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆ 07        ┆   ┆ 07        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 26409258  ┆ 26409692  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.666667  ┆ ELA      │
│           ┆           ┆           ┆ 38        ┆   ┆ 38        ┆ ality:0.6 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 66667|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

In [11]:
# Inspect most frequent itemRgb values
# BED file に記載がある itemRgb の値を確認し、その値をもとにわかりやすいように色名をアサインしておく
# fantabio_bed_color = fantabio_bed.select("itemRgb").unique()

# pl.Config.set_tbl_rows(12)
# display(fantabio_bed_color)

In [12]:
# Map exact RGB strings to human-readable names
rgb_to_name = {
    "153,0,0": "dark_red",
    "101,0,0": "dark_red",
    "50,0,0": "dark_red",
    "204,0,0": "red",
    "255,0,0": "red",
    "0,0,51": "dark_blue",
    "0,0,102": "dark_blue",
    "0,0,153": "blue",
    "0,0,204": "blue",
    "0,0,255": "blue",
    "0,0,0": "black",
    "255,202,74": "yellow",
}

fantabio_bed_select = fantabio_bed.with_columns(
    pl.col("itemRgb").replace_strict(
        rgb_to_name,
        default="other"
    ).alias("itemRgb_name")
).select(
    "cre_id",
    "cre_name",
    "directionality",
    "fantabio_cre_class",
    "itemRgb",
    "itemRgb_name"
)

display(fantabio_bed_select)

shape: (513_895, 6)
┌─────────────┬─────────────┬────────────────┬────────────────────┬────────────┬──────────────┐
│ cre_id      ┆ cre_name    ┆ directionality ┆ fantabio_cre_class ┆ itemRgb    ┆ itemRgb_name │
│ ---         ┆ ---         ┆ ---            ┆ ---                ┆ ---        ┆ ---          │
│ str         ┆ str         ┆ f64            ┆ str                ┆ str        ┆ str          │
╞═════════════╪═════════════╪════════════════╪════════════════════╪════════════╪══════════════╡
│ FCHS_1      ┆ cp1@DDX11L1 ┆ -1.0           ┆ PLA                ┆ 0,0,255    ┆ blue         │
│ FCHS_2      ┆ cp1@WASH7P  ┆ 1.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ …           ┆ …           ┆ …              ┆ …                  ┆ …          ┆ …            │
│ FCHS_447314 ┆ FCHS_447314 ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_593940 ┆ FCHS_593940 ┆ 0.989305       ┆ PLA                ┆ 204,0,0    ┆ red          │
└─────────────┴─────────────┴────────────────┴────────────────────┴────────────┴──────────────┘