## No Proximal CRE transcripts analysis

- public transcriptome (bulk RNA-sequencing data) で選抜した transcripts と、[`fanta.bio`](https://fanta.bio/) を対応付けたとき、TSS ± 500 bp に CRE がない transcript がどのような状態なのかを調べるための notebook

In [1]:
import os
import datetime
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import matplotlib.pyplot as plt

from IPython.display import display


pl.Config.set_fmt_str_lengths(100)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
up5p_no_proximal_cre_transcripts = pl.read_parquet(
    "../../out/fantabio/no_proximal_cre_transcirpt_list/up5p_transcript_no_cre_v261001.parquet"
)

print(up5p_no_proximal_cre_transcripts.select("transcript_id").n_unique())
display(up5p_no_proximal_cre_transcripts)

4658

shape: (4_658, 22)
┌─────────────┬─────┬───────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ transcript_ ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ polyA_featu ┆ gene_source ┆ annotation ┆ annotation │
│ id          ┆ --- ┆ ---   ┆ ---        ┆   ┆ res         ┆ ---         ┆ _remarks   ┆ _remark_co │
│ ---         ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---         ┆ str         ┆ ---        ┆ unt        │
│ str         ┆     ┆       ┆            ┆   ┆ list[str]   ┆             ┆ list[str]  ┆ ---        │
│             ┆     ┆       ┆            ┆   ┆             ┆             ┆            ┆ u32        │
╞═════════════╪═════╪═══════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ ENST0000045 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0744.1      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000039 ┆ 320 ┆ 16    ┆ 70         ┆ … ┆ ["polya_sit ┆ ensembl_hav ┆ null       ┆ 0          │
│ 1555.1      ┆     ┆       ┆            ┆   ┆ e", "polya_ ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ signal"]    ┆ mo_sapiens  ┆            ┆            │
│ ENST0000062 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 6866.2      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000073 ┆ 312 ┆ 9     ┆ 85         ┆ … ┆ null        ┆ havana_tage ┆ ["CLS3     ┆ 1          │
│ 8043.1      ┆     ┆       ┆            ┆   ┆             ┆ ne_homo_sap ┆ project"]  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ iens        ┆            ┆            │
│ ENST0000040 ┆ 309 ┆ 12    ┆ 85         ┆ … ┆ ["polya_sig ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0040.1      ┆     ┆       ┆            ┆   ┆ nal", "poly ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆ a_site"]    ┆ mo_sapiens  ┆            ┆            │
│ …           ┆ …   ┆ …     ┆ …          ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ ENST0000048 ┆ 121 ┆ 77    ┆ 208        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 7173.5      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000079 ┆ 92  ┆ 48    ┆ 266        ┆ … ┆ null        ┆ havana_tage ┆ ["CLS3     ┆ 1          │
│ 7768.1      ┆     ┆       ┆            ┆   ┆             ┆ ne_homo_sap ┆ project"]  ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ iens        ┆            ┆            │
│ ENST0000046 ┆ 93  ┆ 49    ┆ 264        ┆ … ┆ null        ┆ ensembl_hav ┆ null       ┆ 0          │
│ 0240.5      ┆     ┆       ┆            ┆   ┆             ┆ ana_gene_ho ┆            ┆            │
│             ┆     ┆       ┆            ┆   ┆             ┆ mo_sapiens  ┆            ┆            │
│ ENST0000041 ┆ 57  ┆ 13    ┆ 336        ┆ … ┆ null        ┆ havana_homo ┆ null       ┆ 0          │
│ 5971.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆            ┆            │
│ ENST0000084 ┆ 72  ┆ 28    ┆ 306        ┆ … ┆ null        ┆ havana_homo ┆ ["CLS3     ┆ 1          │
│ 6985.1      ┆     ┆       ┆            ┆   ┆             ┆ _sapiens    ┆ project"]  ┆            │
└─────────────┴─────┴───────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [3]:
# https://data.fanta.bio/cre/v1.2.1/00README_v1.2.1.txt
fantabio_bed = pl.read_csv(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks.bed",
    separator="\t",
    has_header=False,
    new_columns=[
        "cre_chrom",
        "cre_chrom_start",
        "cre_chrom_end",
        "cre_id",
        "score",
        "strand",
        "thickStart",
        "thickEnd",
        "itemRgb",
        "cre_name",
        "pooled_cre_scores"
    ]
).with_columns(
    pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
    pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
).select(
    "cre_id",
    "cre_name",
    "fantabio_cre_class"
)

display(fantabio_bed)

shape: (513_895, 3)
┌─────────────┬──────────────────┬────────────────────┐
│ cre_id      ┆ cre_name         ┆ fantabio_cre_class │
│ ---         ┆ ---              ┆ ---                │
│ str         ┆ str              ┆ str                │
╞═════════════╪══════════════════╪════════════════════╡
│ FCHS_1      ┆ cp1@DDX11L1      ┆ PLA                │
│ FCHS_2      ┆ cp1@WASH7P       ┆ ELA                │
│ FCHS_447416 ┆ cp1@DDX11L17     ┆ ELA                │
│ FCHS_447417 ┆ FCHS_447417      ┆ ELA                │
│ FCHS_3      ┆ cp2@LOC101928626 ┆ ELA                │
│ …           ┆ …                ┆ …                  │
│ FCHS_447311 ┆ FCHS_447311      ┆ ELA                │
│ FCHS_447312 ┆ FCHS_447312      ┆ ELA                │
│ FCHS_447313 ┆ FCHS_447313      ┆ ELA                │
│ FCHS_447314 ┆ FCHS_447314      ┆ ELA                │
│ FCHS_593940 ┆ FCHS_593940      ┆ PLA                │
└─────────────┴──────────────────┴────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## `fanta.bio` (ver.1.2.0) gene level CRE association

- 粕川先生から、gene - CRE level relationship file をいただいた
- これは、ver.1.2.0 に該当する
- 10 kb までの対応

## gene–CRE distance の 100 bp ビン分布

- 各行は unique な `gene_id`–`cre_id` ペア（1,062,998 行 = 1,062,998 ペア）
- `distance` を 100 bp の左閉右開ビンに分割する: `[0, 100)`, `[100, 200)`, …, `[9900, 10000)`。`distance == 10000` は最後のビン
- 縦軸は、そのビンに入った gene–CRE ペア数

In [4]:
human_gene_cre_association = pl.read_csv(
    "../../Data/Database/fantabio/gene_neighbor/human_gene_cre_associate.csv.gz",
    separator=",",
    n_threads=16
).sort("distance").join(
    fantabio_bed,
    on="cre_id",
    how="inner"
)

display(human_gene_cre_association)

shape: (1_062_998, 7)
┌───────────────┬─────────────┬──────────┬──────────┬───────────────┬───────────────┬──────────────┐
│ gene_id       ┆ cre_id      ┆ distance ┆ organism ┆ genome_assemb ┆ cre_name      ┆ fantabio_cre │
│ ---           ┆ ---         ┆ ---      ┆ ---      ┆ ly            ┆ ---           ┆ _class       │
│ str           ┆ str         ┆ i64      ┆ str      ┆ ---           ┆ str           ┆ ---          │
│               ┆             ┆          ┆          ┆ str           ┆               ┆ str          │
╞═══════════════╪═════════════╪══════════╪══════════╪═══════════════╪═══════════════╪══════════════╡
│ ENSG000003105 ┆ FCHS_2      ┆ 0        ┆ human    ┆ hg38          ┆ cp1@WASH7P    ┆ ELA          │
│ 26.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000002434 ┆ FCHS_2      ┆ 0        ┆ human    ┆ hg38          ┆ cp1@WASH7P    ┆ ELA          │
│ 85.6          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000003105 ┆ FCHS_447416 ┆ 0        ┆ human    ┆ hg38          ┆ cp1@DDX11L17  ┆ ELA          │
│ 28.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000003084 ┆ FCHS_447416 ┆ 0        ┆ human    ┆ hg38          ┆ cp1@DDX11L17  ┆ ELA          │
│ 15.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000002418 ┆ FCHS_447416 ┆ 0        ┆ human    ┆ hg38          ┆ cp1@DDX11L17  ┆ ELA          │
│ 60.8          ┆             ┆          ┆          ┆               ┆               ┆              │
│ …             ┆ …           ┆ …        ┆ …        ┆ …             ┆ …             ┆ …            │
│ ENSG000002983 ┆ FCHS_253394 ┆ 10000    ┆ human    ┆ hg38          ┆ FCHS_253394   ┆ ELA          │
│ 75.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000002326 ┆ FCHS_533966 ┆ 10000    ┆ human    ┆ hg38          ┆ FCHS_533966   ┆ ELA          │
│ 87.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000003021 ┆ FCHS_413906 ┆ 10000    ┆ human    ┆ hg38          ┆ FCHS_413906   ┆ ELA          │
│ 88.1          ┆             ┆          ┆          ┆               ┆               ┆              │
│ ENSG000000824 ┆ FCHS_440713 ┆ 10000    ┆ human    ┆ hg38          ┆ cp3@LOC105373 ┆ PLA          │
│ 58.13         ┆             ┆          ┆          ┆               ┆ 244           ┆              │
│ ENSG000002688 ┆ FCHS_593563 ┆ 10000    ┆ human    ┆ hg38          ┆ FCHS_593563   ┆ ELA          │
│ 83.2          ┆             ┆          ┆          ┆               ┆               ┆              │
└───────────────┴─────────────┴──────────┴──────────┴───────────────┴───────────────┴──────────────┘

In [5]:
BIN_SIZE_BP = 100
MAX_DISTANCE_BP = 10_000

# Assign each distance to a 100 bp bin: [0,100), [100,200), ..., [9900,10000]
distance_binned = human_gene_cre_association.with_columns(
    pl.when(pl.col("distance") == MAX_DISTANCE_BP)
    .then(MAX_DISTANCE_BP - BIN_SIZE_BP)
    .otherwise((pl.col("distance") // BIN_SIZE_BP) * BIN_SIZE_BP)
    .alias("distance_bin_start")
)

count_df = (
    distance_binned.group_by("distance_bin_start", "fantabio_cre_class")
    .agg(pl.len().alias("count"))
    .sort("distance_bin_start", "fantabio_cre_class")
)

# Keep all 100 bp bins and CRE classes even when count is zero
all_distance_bins = pl.DataFrame(
    {"distance_bin_start": range(0, MAX_DISTANCE_BP, BIN_SIZE_BP)}
)
cre_classes = (
    human_gene_cre_association["fantabio_cre_class"]
    .unique()
    .sort()
    .to_list()
)
all_bins_classes = all_distance_bins.join(
    pl.DataFrame({"fantabio_cre_class": cre_classes}),
    how="cross",
)

gene_cre_distance_bin_counts = (
    all_bins_classes.join(
        count_df,
        on=["distance_bin_start", "fantabio_cre_class"],
        how="left",
    )
    .with_columns(pl.col("count").fill_null(0).cast(pl.Int64))
    .with_columns(
        pl.format(
            "{}-{}",
            pl.col("distance_bin_start"),
            pl.col("distance_bin_start") + BIN_SIZE_BP,
        ).alias("distance_bin")
    )
    .sort("distance_bin_start", "fantabio_cre_class")
)

display(gene_cre_distance_bin_counts)

# Pivot for stacked bar plot (style matched to 02_2_HNscore_up_transcript_fantabio.ipynb)
plot_df = gene_cre_distance_bin_counts.to_pandas()
bin_labels = [
    f"{b}-{b + BIN_SIZE_BP}" for b in range(0, MAX_DISTANCE_BP, BIN_SIZE_BP)
]

pivot_df = (
    plot_df.pivot(index="distance_bin", columns="fantabio_cre_class", values="count")
    .fillna(0)
    .astype(int)
    .reindex(bin_labels)
)

classes = pivot_df.columns.tolist()
palette = sns.color_palette("Set2", n_colors=len(classes))
color_map = dict(zip(classes, palette))

sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(16, 8))

bottom = np.zeros(len(pivot_df))
x = np.arange(len(pivot_df.index))

for cls in classes:
    heights = pivot_df[cls].to_numpy()
    ax.bar(
        x,
        heights,
        bottom=bottom,
        label=cls,
        color=color_map[cls],
        edgecolor="white",
        linewidth=0.5,
    )
    bottom += heights

# Show x-axis labels every 1 kb; use bin ranges (e.g. 0-100) so bars are not read as exact distances
TICK_STEP_BINS = 10
tick_idx = np.arange(0, len(pivot_df), TICK_STEP_BINS)

ax.set_xticks(x[tick_idx])
ax.set_xticklabels(
    [bin_labels[i] for i in tick_idx],
    fontsize=11,
    rotation=30,
    ha="right",
)
ax.set_xlabel("Distance bin (bp)", fontsize=18)
ax.set_ylabel("Count (gene–CRE pairs)", fontsize=18)
ax.set_title(
    "Gene–CRE association distance distribution (100 bp bins, up to 10 kb)",
    fontsize=18,
)
ax.legend(title="fantabio CRE class", bbox_to_anchor=(1.02, 1), loc="upper left")
ax.tick_params(axis="y", labelsize=14)

plt.tight_layout()
plt.show()

shape: (200, 4)
┌────────────────────┬────────────────────┬────────┬──────────────┐
│ distance_bin_start ┆ fantabio_cre_class ┆ count  ┆ distance_bin │
│ ---                ┆ ---                ┆ ---    ┆ ---          │
│ i64                ┆ str                ┆ i64    ┆ str          │
╞════════════════════╪════════════════════╪════════╪══════════════╡
│ 0                  ┆ ELA                ┆ 483514 ┆ 0-100        │
│ 0                  ┆ PLA                ┆ 103106 ┆ 0-100        │
│ 100                ┆ ELA                ┆ 6220   ┆ 100-200      │
│ 100                ┆ PLA                ┆ 1698   ┆ 100-200      │
│ 200                ┆ ELA                ┆ 6083   ┆ 200-300      │
│ …                  ┆ …                  ┆ …      ┆ …            │
│ 9700               ┆ PLA                ┆ 758    ┆ 9700-9800    │
│ 9800               ┆ ELA                ┆ 3467   ┆ 9800-9900    │
│ 9800               ┆ PLA                ┆ 753    ┆ 9800-9900    │
│ 9900               ┆ ELA                ┆ 3628   ┆ 9900-10000   │
│ 9900               ┆ PLA                ┆ 739    ┆ 9900-10000   │
└────────────────────┴────────────────────┴────────┴──────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## no proximal CRE transcirpts

- TSS ± 500 bp にない transcripts が、遺伝子レベルではどの範囲に CRE があるのか調査する

In [6]:
up5p_no_proximal_cre_transcripts_gene_cre_distance = up5p_no_proximal_cre_transcripts.join(
    human_gene_cre_association,
    on="gene_id",
    how="left"
).sort("distance")

print(f"up5p_no_proximal_cre_transcripts_gene_cre_distance: {up5p_no_proximal_cre_transcripts_gene_cre_distance.select('transcript_id').n_unique()}")
display(up5p_no_proximal_cre_transcripts_gene_cre_distance)

up5p_no_proximal_cre_transcripts_gene_cre_distance: 4658

shape: (102_147, 28)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬─────────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ organism ┆ genome_asse ┆ cre_name    ┆ fantabio_cr │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ mbly        ┆ ---         ┆ e_class     │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---         ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str         ┆             ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪═════════════╪═════════════╪═════════════╡
│ ENST00000450 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null     ┆ null        ┆ null        ┆ null        │
│ 744.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000391 ┆ 320 ┆ 16    ┆ 70         ┆ … ┆ null     ┆ null        ┆ null        ┆ null        │
│ 555.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000400 ┆ 309 ┆ 12    ┆ 85         ┆ … ┆ null     ┆ null        ┆ null        ┆ null        │
│ 040.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000391 ┆ 305 ┆ 15    ┆ 86         ┆ … ┆ null     ┆ null        ┆ null        ┆ null        │
│ 548.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000445 ┆ 279 ┆ 25    ┆ 102        ┆ … ┆ null     ┆ null        ┆ null        ┆ null        │
│ 736.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …           ┆ …           ┆ …           │
│ ENST00000312 ┆ 210 ┆ 29    ┆ 167        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 087.10       ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000514 ┆ 108 ┆ 27    ┆ 271        ┆ … ┆ human    ┆ hg38        ┆ FCHS_308964 ┆ ELA         │
│ 630.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000523 ┆ 122 ┆ 45    ┆ 239        ┆ … ┆ human    ┆ hg38        ┆ cp18@MAILR  ┆ ELA         │
│ 791.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000502 ┆ 125 ┆ 67    ┆ 214        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 425.5        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000503 ┆ 119 ┆ 71    ┆ 216        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 128.5        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴─────────────┴─────────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. 10 kb 範囲内に CRE が紐づかない transcript

In [7]:
no_cre_10kb_transcripts = up5p_no_proximal_cre_transcripts_gene_cre_distance.filter(
    pl.col("distance").is_null()
)

print(f"no_cre_10kb_transcripts: {no_cre_10kb_transcripts.select('transcript_id').n_unique()}")
display(no_cre_10kb_transcripts)

no_cre_10kb_transcripts: 580

shape: (580, 28)
┌───────────────┬─────┬───────┬────────────┬───┬──────────┬──────────────┬──────────┬──────────────┐
│ transcript_id ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ organism ┆ genome_assem ┆ cre_name ┆ fantabio_cre │
│ ---           ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ bly          ┆ ---      ┆ _class       │
│ str           ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---          ┆ str      ┆ ---          │
│               ┆     ┆       ┆            ┆   ┆          ┆ str          ┆          ┆ str          │
╞═══════════════╪═════╪═══════╪════════════╪═══╪══════════╪══════════════╪══════════╪══════════════╡
│ ENST000004507 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 44.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000003915 ┆ 320 ┆ 16    ┆ 70         ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 55.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000004000 ┆ 309 ┆ 12    ┆ 85         ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 40.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000003915 ┆ 305 ┆ 15    ┆ 86         ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 48.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000004457 ┆ 279 ┆ 25    ┆ 102        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 36.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ …             ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …            ┆ …        ┆ …            │
│ ENST000005762 ┆ 58  ┆ 14    ┆ 334        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 36.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000007815 ┆ 115 ┆ 71    ┆ 220        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 52.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000006409 ┆ 59  ┆ 15    ┆ 332        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 02.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000007977 ┆ 92  ┆ 48    ┆ 266        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 68.1          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
│ ENST000004602 ┆ 93  ┆ 49    ┆ 264        ┆ … ┆ null     ┆ null         ┆ null     ┆ null         │
│ 40.5          ┆     ┆       ┆            ┆   ┆          ┆              ┆          ┆              │
└───────────────┴─────┴───────┴────────────┴───┴──────────┴──────────────┴──────────┴──────────────┘

&nbsp;

&nbsp;

&nbsp;

## 1-2: Haplotype derived Gene

- ハプロタイプ由来のデータかどうかを調査

In [8]:
# For more information, see https://www.gencodegenes.org/pages/biotypes.html
gencode_gtf = pl.read_csv(
    "../../Data/Database/GENCODE_v49/gencode.v49.chr_patch_hapl_scaff.annotation.gtf",
    separator='\t',
    has_header=False,
    comment_prefix='#',
    new_columns=['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attributes'],
    n_threads=16
).filter(
    pl.col('feature') == "gene"
).with_columns(
    pl.col("attributes").str.extract(r'gene_id "([^"]+)"', 1).alias("gene_id"),
    pl.col("attributes").str.extract(r'gene_name "([^"]+)"', 1).alias("gene_name"),
).select([
    pl.col("seqname"),
    pl.col("gene_id"),
    pl.col("gene_name"),
])

display(gencode_gtf)

shape: (86_369, 3)
┌────────────┬───────────────────┬─────────────────┐
│ seqname    ┆ gene_id           ┆ gene_name       │
│ ---        ┆ ---               ┆ ---             │
│ str        ┆ str               ┆ str             │
╞════════════╪═══════════════════╪═════════════════╡
│ chr1       ┆ ENSG00000290825.2 ┆ DDX11L16        │
│ chr1       ┆ ENSG00000223972.6 ┆ DDX11L1         │
│ chr1       ┆ ENSG00000310526.1 ┆ WASH7P          │
│ chr1       ┆ ENSG00000227232.6 ┆ WASH7P          │
│ chr1       ┆ ENSG00000278267.1 ┆ MIR6859-1       │
│ …          ┆ …                 ┆ …               │
│ KI270751.1 ┆ ENSG00000303867.1 ┆ ENSG00000303867 │
│ KI270751.1 ┆ ENSG00000303902.1 ┆ ENSG00000303902 │
│ KI270751.1 ┆ ENSG00000306528.1 ┆ ENSG00000306528 │
│ KI270753.1 ┆ ENSG00000297844.1 ┆ ENSG00000297844 │
│ KI270755.1 ┆ ENSG00000309258.1 ┆ ENSG00000309258 │
└────────────┴───────────────────┴─────────────────┘

In [9]:
no_cre_10kb_transcripts_gtf = no_cre_10kb_transcripts.join(
    gencode_gtf,
    on="gene_id",
    how="left"
)

print(no_cre_10kb_transcripts_gtf.select("seqname").to_series().unique().to_list())
display(no_cre_10kb_transcripts_gtf)

['chr6', 'MU273375.1', 'GL383546.1', 'chr21', 'KI270831.1', 'GL000220.1', 'KI270895.1', 'GL949752.1', 'GL383581.2', 'KI270813.1', 'ML143376.1', 'chrY', 'KI270877.1', 'KI270866.1', 'chr14', 'KQ983257.1', 'GL000219.1', 'KI270902.1', 'GL000205.2', 'chr19', 'GL383564.2', 'chr13', 'KI270853.1', 'GL000250.2', 'ML143352.1', 'GL000255.2', 'KI270897.1', 'KI270744.1', 'KQ090021.1', 'GL000195.1', 'MU273380.1', 'KI270816.1', 'KN538364.1', 'KI270847.1', 'chr1', 'chr17', 'chrX', 'GL000251.2', 'KN196481.1', 'MU273338.1', 'GL949747.2', 'KI270809.1', 'KI270849.1', 'KI270879.1', 'ML143359.1', 'MU273394.1', 'MU273372.1', 'KV766196.1', 'chr5', 'KZ208914.1', 'MU273395.1', 'KI270850.1', 'KI270821.1', 'KQ031389.1', 'GL949746.1', 'GL000254.2', 'chr7', 'KI270872.1', 'KI270830.1', 'chr22', 'GL000252.2', 'chr11', 'KQ458386.1', 'MU273374.1', 'chr18', 'KN196474.1', 'KI270791.1', 'chr9', 'KQ983258.1', 'MU273330.1', 'ML143358.1', 'KI270846.1', 'GL339449.2', 'chr2', 'KI270903.1', 'GL000218.1', 'chr3', 'chr8', 'chr12', 'KZ208915.1', 'KI270862.1', 'KI270875.1', 'KI270860.1', 'KI270823.1', 'GL000256.2', 'KZ208911.1', 'chr15', 'MU273383.1', 'KI270792.1', 'KI270798.1', 'KI270871.1', 'KI270832.1', 'MU273369.1', 'chr20', 'GL000253.2', 'KI270733.1', 'chr10', 'KI270822.1', 'chr16', 'MU273333.1', 'KI270753.1', 'KI270857.1', 'KI270742.1', 'MU273387.1', 'KV880765.1', 'chr4', 'KI270938.1', 'GL000258.2', 'KV575244.1', 'KQ759759.2', 'KN196479.1', 'MU273351.1', 'KI270908.1', 'KI270803.1']

shape: (580, 30)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬──────────────┬────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ cre_name ┆ fantabio_cre ┆ seqname    ┆ gene_name   │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ _class       ┆ ---        ┆ ---         │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---          ┆ str        ┆ str         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str          ┆            ┆             │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪══════════════╪════════════╪═════════════╡
│ ENST00000450 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null     ┆ null         ┆ GL000250.2 ┆ HSPA1B      │
│ 744.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000391 ┆ 320 ┆ 16    ┆ 70         ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ HSPA1B      │
│ 555.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000400 ┆ 309 ┆ 12    ┆ 85         ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ HSPA1A      │
│ 040.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000391 ┆ 305 ┆ 15    ┆ 86         ┆ … ┆ null     ┆ null         ┆ GL000251.2 ┆ HSPA1B      │
│ 548.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000445 ┆ 279 ┆ 25    ┆ 102        ┆ … ┆ null     ┆ null         ┆ GL000252.2 ┆ HSPA1B      │
│ 736.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …            ┆ …          ┆ …           │
│ ENST00000576 ┆ 58  ┆ 14    ┆ 334        ┆ … ┆ null     ┆ null         ┆ GL383564.2 ┆ KRT33A      │
│ 236.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000781 ┆ 115 ┆ 71    ┆ 220        ┆ … ┆ null     ┆ null         ┆ GL000218.1 ┆ ENSG0000030 │
│ 552.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆ 1761        │
│ ENST00000640 ┆ 59  ┆ 15    ┆ 332        ┆ … ┆ null     ┆ null         ┆ KV766196.1 ┆ VPS53       │
│ 902.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000797 ┆ 92  ┆ 48    ┆ 266        ┆ … ┆ null     ┆ null         ┆ GL000195.1 ┆ ENSG0000030 │
│ 768.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆ 3875        │
│ ENST00000460 ┆ 93  ┆ 49    ┆ 264        ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ BRD2        │
│ 240.5        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴──────────────┴────────────┴─────────────┘

&nbsp;

&nbsp;

### 1-3: haplotype 由来

In [10]:
no_cre_10kb_transcripts_haplotype = no_cre_10kb_transcripts_gtf.filter(
    ~pl.col("seqname").str.contains("chr")
)

print(no_cre_10kb_transcripts_haplotype.select("transcript_id").n_unique())
display(no_cre_10kb_transcripts_haplotype)

293

shape: (293, 30)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬──────────────┬────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ cre_name ┆ fantabio_cre ┆ seqname    ┆ gene_name   │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ _class       ┆ ---        ┆ ---         │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---          ┆ str        ┆ str         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str          ┆            ┆             │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪══════════════╪════════════╪═════════════╡
│ ENST00000450 ┆ 335 ┆ 13    ┆ 58         ┆ … ┆ null     ┆ null         ┆ GL000250.2 ┆ HSPA1B      │
│ 744.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000391 ┆ 320 ┆ 16    ┆ 70         ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ HSPA1B      │
│ 555.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000400 ┆ 309 ┆ 12    ┆ 85         ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ HSPA1A      │
│ 040.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000391 ┆ 305 ┆ 15    ┆ 86         ┆ … ┆ null     ┆ null         ┆ GL000251.2 ┆ HSPA1B      │
│ 548.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000445 ┆ 279 ┆ 25    ┆ 102        ┆ … ┆ null     ┆ null         ┆ GL000252.2 ┆ HSPA1B      │
│ 736.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …            ┆ …          ┆ …           │
│ ENST00000576 ┆ 58  ┆ 14    ┆ 334        ┆ … ┆ null     ┆ null         ┆ GL383564.2 ┆ KRT33A      │
│ 236.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000781 ┆ 115 ┆ 71    ┆ 220        ┆ … ┆ null     ┆ null         ┆ GL000218.1 ┆ ENSG0000030 │
│ 552.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆ 1761        │
│ ENST00000640 ┆ 59  ┆ 15    ┆ 332        ┆ … ┆ null     ┆ null         ┆ KV766196.1 ┆ VPS53       │
│ 902.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
│ ENST00000797 ┆ 92  ┆ 48    ┆ 266        ┆ … ┆ null     ┆ null         ┆ GL000195.1 ┆ ENSG0000030 │
│ 768.1        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆ 3875        │
│ ENST00000460 ┆ 93  ┆ 49    ┆ 264        ┆ … ┆ null     ┆ null         ┆ GL000255.2 ┆ BRD2        │
│ 240.5        ┆     ┆       ┆            ┆   ┆          ┆              ┆            ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴──────────────┴────────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

### 1-4: 常染色体 + ChrX + Chr Y 由来

- 遺伝子レベルで、CREに紐づいているかどうかを調べる

In [11]:
no_cre_10kb_transcripts_chr = no_cre_10kb_transcripts_gtf.filter(
    pl.col("seqname").str.contains("chr")
)

print(no_cre_10kb_transcripts_chr.select("transcript_id").n_unique())
display(no_cre_10kb_transcripts_chr)

287

shape: (287, 30)
┌───────────────┬─────┬───────┬────────────┬───┬──────────┬───────────────┬─────────┬──────────────┐
│ transcript_id ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ cre_name ┆ fantabio_cre_ ┆ seqname ┆ gene_name    │
│ ---           ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ class         ┆ ---     ┆ ---          │
│ str           ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---           ┆ str     ┆ str          │
│               ┆     ┆       ┆            ┆   ┆          ┆ str           ┆         ┆              │
╞═══════════════╪═════╪═══════╪════════════╪═══╪══════════╪═══════════════╪═════════╪══════════════╡
│ ENST000006225 ┆ 241 ┆ 22    ┆ 143        ┆ … ┆ null     ┆ null          ┆ chr9    ┆ FOXD4L6      │
│ 88.2          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ ENST000003624 ┆ 249 ┆ 40    ┆ 117        ┆ … ┆ null     ┆ null          ┆ chr1    ┆ RNA5S1       │
│ 82.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ ENST000006240 ┆ 216 ┆ 15    ┆ 175        ┆ … ┆ null     ┆ null          ┆ chr3    ┆ ENSG00000279 │
│ 04.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆ 311          │
│ ENST000006019 ┆ 220 ┆ 20    ┆ 166        ┆ … ┆ null     ┆ null          ┆ chrX    ┆ ATF4P2       │
│ 44.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ ENST000003774 ┆ 210 ┆ 13    ┆ 183        ┆ … ┆ null     ┆ null          ┆ chr9    ┆ FOXD4L5      │
│ 20.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ …             ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …             ┆ …       ┆ …            │
│ ENST000003654 ┆ 70  ┆ 26    ┆ 310        ┆ … ┆ null     ┆ null          ┆ chr4    ┆ RNU6-652P    │
│ 88.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ ENST000005578 ┆ 106 ┆ 62    ┆ 238        ┆ … ┆ null     ┆ null          ┆ chr15   ┆ ENSG00000284 │
│ 32.2          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆ 540          │
│ ENST000004883 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null     ┆ null          ┆ chr12   ┆ RPL17P38     │
│ 71.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆              │
│ ENST000007512 ┆ 54  ┆ 10    ┆ 342        ┆ … ┆ null     ┆ null          ┆ chrX    ┆ ENSG00000297 │
│ 88.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆ 828          │
│ ENST000006076 ┆ 117 ┆ 73    ┆ 216        ┆ … ┆ null     ┆ null          ┆ chr1    ┆ ENSG00000271 │
│ 79.1          ┆     ┆       ┆            ┆   ┆          ┆               ┆         ┆ 992          │
└───────────────┴─────┴───────┴────────────┴───┴──────────┴───────────────┴─────────┴──────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1-5: 遺伝子レベルで CRE と紐づいているかチェック

In [12]:
cre_gene_ids = human_gene_cre_association.select(
    pl.col("gene_id").unique().implode()
).to_series()


no_cre_10kb_transcripts_chr_check = no_cre_10kb_transcripts_chr.with_columns(
    has_cre_gene=pl.col("gene_id").is_in(cre_gene_ids)
)

display(no_cre_10kb_transcripts_chr_check)

shape: (287, 31)
┌──────────────┬─────┬───────┬────────────┬───┬──────────────┬─────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ fantabio_cre ┆ seqname ┆ gene_name   ┆ has_cre_gen │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ _class       ┆ ---     ┆ ---         ┆ e           │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---          ┆ str     ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆ str          ┆         ┆             ┆ bool        │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════════╪═════════╪═════════════╪═════════════╡
│ ENST00000622 ┆ 241 ┆ 22    ┆ 143        ┆ … ┆ null         ┆ chr9    ┆ FOXD4L6     ┆ false       │
│ 588.2        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000362 ┆ 249 ┆ 40    ┆ 117        ┆ … ┆ null         ┆ chr1    ┆ RNA5S1      ┆ false       │
│ 482.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000624 ┆ 216 ┆ 15    ┆ 175        ┆ … ┆ null         ┆ chr3    ┆ ENSG0000027 ┆ false       │
│ 004.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 9311        ┆             │
│ ENST00000601 ┆ 220 ┆ 20    ┆ 166        ┆ … ┆ null         ┆ chrX    ┆ ATF4P2      ┆ false       │
│ 944.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000377 ┆ 210 ┆ 13    ┆ 183        ┆ … ┆ null         ┆ chr9    ┆ FOXD4L5     ┆ false       │
│ 420.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …            ┆ …       ┆ …           ┆ …           │
│ ENST00000365 ┆ 70  ┆ 26    ┆ 310        ┆ … ┆ null         ┆ chr4    ┆ RNU6-652P   ┆ false       │
│ 488.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000557 ┆ 106 ┆ 62    ┆ 238        ┆ … ┆ null         ┆ chr15   ┆ ENSG0000028 ┆ false       │
│ 832.2        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 4540        ┆             │
│ ENST00000488 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null         ┆ chr12   ┆ RPL17P38    ┆ false       │
│ 371.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000751 ┆ 54  ┆ 10    ┆ 342        ┆ … ┆ null         ┆ chrX    ┆ ENSG0000029 ┆ false       │
│ 288.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 7828        ┆             │
│ ENST00000607 ┆ 117 ┆ 73    ┆ 216        ┆ … ┆ null         ┆ chr1    ┆ ENSG0000027 ┆ false       │
│ 679.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 1992        ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────────┴─────────┴─────────────┴─────────────┘

In [13]:
no_cre_10kb_transcripts_chr_check_false = no_cre_10kb_transcripts_chr_check.filter(
    pl.col("has_cre_gene") == False
)

print(no_cre_10kb_transcripts_chr_check_false.select("transcript_id").n_unique())
display(no_cre_10kb_transcripts_chr_check_false)

287

shape: (287, 31)
┌──────────────┬─────┬───────┬────────────┬───┬──────────────┬─────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ fantabio_cre ┆ seqname ┆ gene_name   ┆ has_cre_gen │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ _class       ┆ ---     ┆ ---         ┆ e           │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---          ┆ str     ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆ str          ┆         ┆             ┆ bool        │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════════╪═════════╪═════════════╪═════════════╡
│ ENST00000622 ┆ 241 ┆ 22    ┆ 143        ┆ … ┆ null         ┆ chr9    ┆ FOXD4L6     ┆ false       │
│ 588.2        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000362 ┆ 249 ┆ 40    ┆ 117        ┆ … ┆ null         ┆ chr1    ┆ RNA5S1      ┆ false       │
│ 482.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000624 ┆ 216 ┆ 15    ┆ 175        ┆ … ┆ null         ┆ chr3    ┆ ENSG0000027 ┆ false       │
│ 004.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 9311        ┆             │
│ ENST00000601 ┆ 220 ┆ 20    ┆ 166        ┆ … ┆ null         ┆ chrX    ┆ ATF4P2      ┆ false       │
│ 944.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000377 ┆ 210 ┆ 13    ┆ 183        ┆ … ┆ null         ┆ chr9    ┆ FOXD4L5     ┆ false       │
│ 420.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …            ┆ …       ┆ …           ┆ …           │
│ ENST00000365 ┆ 70  ┆ 26    ┆ 310        ┆ … ┆ null         ┆ chr4    ┆ RNU6-652P   ┆ false       │
│ 488.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000557 ┆ 106 ┆ 62    ┆ 238        ┆ … ┆ null         ┆ chr15   ┆ ENSG0000028 ┆ false       │
│ 832.2        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 4540        ┆             │
│ ENST00000488 ┆ 114 ┆ 70    ┆ 222        ┆ … ┆ null         ┆ chr12   ┆ RPL17P38    ┆ false       │
│ 371.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆             ┆             │
│ ENST00000751 ┆ 54  ┆ 10    ┆ 342        ┆ … ┆ null         ┆ chrX    ┆ ENSG0000029 ┆ false       │
│ 288.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 7828        ┆             │
│ ENST00000607 ┆ 117 ┆ 73    ┆ 216        ┆ … ┆ null         ┆ chr1    ┆ ENSG0000027 ┆ false       │
│ 679.1        ┆     ┆       ┆            ┆   ┆              ┆         ┆ 1992        ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────────┴─────────┴─────────────┴─────────────┘

In [14]:
no_cre_10kb_transcripts_chr_check_true = no_cre_10kb_transcripts_chr_check.filter(
    pl.col("has_cre_gene") == True
)

print(no_cre_10kb_transcripts_chr_check_true.select("transcript_id").n_unique())
display(no_cre_10kb_transcripts_chr_check_true)

0

shape: (0, 31)
┌───────────────┬─────┬───────┬────────────┬───┬──────────────┬─────────┬───────────┬──────────────┐
│ transcript_id ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ fantabio_cre ┆ seqname ┆ gene_name ┆ has_cre_gene │
│ ---           ┆ --- ┆ ---   ┆ ---        ┆   ┆ _class       ┆ ---     ┆ ---       ┆ ---          │
│ str           ┆ i64 ┆ i64   ┆ i64        ┆   ┆ ---          ┆ str     ┆ str       ┆ bool         │
│               ┆     ┆       ┆            ┆   ┆ str          ┆         ┆           ┆              │
╞═══════════════╪═════╪═══════╪════════════╪═══╪══════════════╪═════════╪═══════════╪══════════════╡
└───────────────┴─────┴───────┴────────────┴───┴──────────────┴─────────┴───────────┴──────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. 10kb 以内であればCRE が紐づく transcripts

In [15]:
cre_10kb_transcripts = up5p_no_proximal_cre_transcripts_gene_cre_distance.filter(
    (pl.col("distance").is_not_null())
)

print(cre_10kb_transcripts.select("transcript_id").n_unique())
display(cre_10kb_transcripts)

4078

shape: (101_567, 28)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬─────────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ organism ┆ genome_asse ┆ cre_name    ┆ fantabio_cr │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ mbly        ┆ ---         ┆ e_class     │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---         ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str         ┆             ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪═════════════╪═════════════╪═════════════╡
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ FCHS_110499 ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ cp5@HSPH1   ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ cp6@HSPH1   ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ FCHS_110502 ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ FCHS_110503 ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …           ┆ …           ┆ …           │
│ ENST00000312 ┆ 210 ┆ 29    ┆ 167        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 087.10       ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000514 ┆ 108 ┆ 27    ┆ 271        ┆ … ┆ human    ┆ hg38        ┆ FCHS_308964 ┆ ELA         │
│ 630.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000523 ┆ 122 ┆ 45    ┆ 239        ┆ … ┆ human    ┆ hg38        ┆ cp18@MAILR  ┆ ELA         │
│ 791.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000502 ┆ 125 ┆ 67    ┆ 214        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 425.5        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ ENST00000503 ┆ 119 ┆ 71    ┆ 216        ┆ … ┆ human    ┆ hg38        ┆ cp2@NELFA   ┆ ELA         │
│ 128.5        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴─────────────┴─────────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

## 2-1: 500 bp 以内の CRE に紐づく transcripts

- 混乱しやすい原因は、gene level だからである
- つまり、上記のデータフレームで、500 bp 以内の CRE に紐づくということは、既に別のtranscript が CRE と紐づいている状態を意味している

In [22]:
cre_10kb_transcripts_500bp = cre_10kb_transcripts.filter(
    pl.col("distance") <= 500
).sort(
    pl.col("HN2"),
    descending=True
)

print(cre_10kb_transcripts_500bp.select("transcript_id").n_unique())

pl.Config.set_tbl_rows(20)
print(cre_10kb_transcripts_500bp.group_by("transcript_type").agg(pl.col("transcript_id").n_unique()).sort("transcript_id", descending=True))

pl.Config.set_tbl_rows(2)
display(cre_10kb_transcripts_500bp)

3287
shape: (18, 2)
┌────────────────────────────────────┬───────────────┐
│ transcript_type                    ┆ transcript_id │
│ ---                                ┆ ---           │
│ str                                ┆ u32           │
╞════════════════════════════════════╪═══════════════╡
│ retained_intron                    ┆ 1115          │
│ protein_coding                     ┆ 658           │
│ lncRNA                             ┆ 585           │
│ protein_coding_CDS_not_defined     ┆ 562           │
│ nonsense_mediated_decay            ┆ 288           │
│ processed_pseudogene               ┆ 25            │
│ TEC                                ┆ 16            │
│ transcribed_unprocessed_pseudogene ┆ 12            │
│ IG_C_gene                          ┆ 6             │
│ snoRNA                             ┆ 5             │
│ unprocessed_pseudogene             ┆ 4             │
│ miRNA                              ┆ 3             │
│ transcribed_unitary_pseudogene     ┆ 2             │
│ snRNA                              ┆ 2             │
│ misc_RNA                           ┆ 1             │
│ unitary_pseudogene                 ┆ 1             │
│ non_stop_decay                     ┆ 1             │
│ transcribed_processed_pseudogene   ┆ 1             │
└────────────────────────────────────┴───────────────┘

shape: (74_586, 28)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬─────────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ organism ┆ genome_asse ┆ cre_name    ┆ fantabio_cr │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ mbly        ┆ ---         ┆ e_class     │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---         ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str         ┆             ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪═════════════╪═════════════╪═════════════╡
│ ENST00000626 ┆ 316 ┆ 13    ┆ 77         ┆ … ┆ human    ┆ hg38        ┆ FCHS_110499 ┆ ELA         │
│ 866.2        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …           ┆ …           ┆ …           │
│ ENST00000673 ┆ 69  ┆ 25    ┆ 312        ┆ … ┆ human    ┆ hg38        ┆ FCHS_136185 ┆ ELA         │
│ 774.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴─────────────┴─────────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

## 2-1 (番外編): `retained_intron`

- `retained_intron` を調査する

In [43]:
cre_10kb_transcripts_500bp_retained_intron = cre_10kb_transcripts_500bp.filter(
    pl.col("transcript_type") == "retained_intron"
).select(
    "gene_id",
    "gene_symbol",
    "transcript_id",
    "HN2",
    "HN2_stranded",
    "transcript_type",
    "strand"
).unique(
    subset=["transcript_id", "HN2", "HN2_stranded", "transcript_type", "gene_id", "gene_symbol"]
).sort(
    pl.col("HN2"),
    descending=True
)

print(cre_10kb_transcripts_500bp_retained_intron.select("transcript_id").n_unique())
display(cre_10kb_transcripts_500bp_retained_intron)

1115

shape: (1_115, 7)
┌──────────────────┬─────────────┬─────────────────┬─────┬──────────────┬─────────────────┬────────┐
│ gene_id          ┆ gene_symbol ┆ transcript_id   ┆ HN2 ┆ HN2_stranded ┆ transcript_type ┆ strand │
│ ---              ┆ ---         ┆ ---             ┆ --- ┆ ---          ┆ ---             ┆ ---    │
│ str              ┆ str         ┆ str             ┆ i64 ┆ i64          ┆ str             ┆ str    │
╞══════════════════╪═════════════╪═════════════════╪═════╪══════════════╪═════════════════╪════════╡
│ ENSG00000120694. ┆ HSPH1       ┆ ENST00000626866 ┆ 303 ┆ 208          ┆ retained_intron ┆ -      │
│ 21               ┆             ┆ .2              ┆     ┆              ┆                 ┆        │
│ …                ┆ …           ┆ …               ┆ …   ┆ …            ┆ …               ┆ …      │
│ ENSG00000172575. ┆ RASGRP1     ┆ ENST00000697779 ┆ 44  ┆ 27           ┆ retained_intron ┆ -      │
│ 15               ┆             ┆ .1              ┆     ┆              ┆                 ┆        │
└──────────────────┴─────────────┴─────────────────┴─────┴──────────────┴─────────────────┴────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2-2: 500 bp 以内の CREにも紐づかない transcript

- 上記の条件でもひっかからないケース

In [24]:
cre_id_already_associated = cre_10kb_transcripts_500bp.select(
    pl.col("transcript_id").unique().implode()
).to_series()

cre_10kb_transcripts_500bp_no_cre_id = cre_10kb_transcripts.filter(
    ~pl.col("transcript_id").is_in(cre_id_already_associated)
).sort(
    pl.col("HN2"),
    descending=True
)


print(cre_10kb_transcripts_500bp_no_cre_id.select("transcript_id").n_unique())

pl.Config.set_tbl_rows(20)
print(cre_10kb_transcripts_500bp_no_cre_id.group_by("transcript_type").agg(pl.col("transcript_id").n_unique()).sort("transcript_id", descending=True))

pl.Config.set_tbl_rows(2)
display(cre_10kb_transcripts_500bp_no_cre_id)

791
shape: (20, 2)
┌────────────────────────────────────┬───────────────┐
│ transcript_type                    ┆ transcript_id │
│ ---                                ┆ ---           │
│ str                                ┆ u32           │
╞════════════════════════════════════╪═══════════════╡
│ lncRNA                             ┆ 328           │
│ processed_pseudogene               ┆ 250           │
│ protein_coding                     ┆ 56            │
│ TEC                                ┆ 39            │
│ transcribed_processed_pseudogene   ┆ 27            │
│ retained_intron                    ┆ 22            │
│ misc_RNA                           ┆ 20            │
│ unprocessed_pseudogene             ┆ 15            │
│ transcribed_unprocessed_pseudogene ┆ 8             │
│ nonsense_mediated_decay            ┆ 7             │
│ miRNA                              ┆ 5             │
│ snRNA                              ┆ 4             │
│ rRNA                               ┆ 2             │
│ IG_V_gene                          ┆ 2             │
│ rRNA_pseudogene                    ┆ 1             │
│ snoRNA                             ┆ 1             │
│ unitary_pseudogene                 ┆ 1             │
│ protein_coding_CDS_not_defined     ┆ 1             │
│ IG_C_pseudogene                    ┆ 1             │
│ transcribed_unitary_pseudogene     ┆ 1             │
└────────────────────────────────────┴───────────────┘

shape: (4_127, 28)
┌──────────────┬─────┬───────┬────────────┬───┬──────────┬─────────────┬─────────────┬─────────────┐
│ transcript_i ┆ UP2 ┆ DOWN2 ┆ UNCHANGED2 ┆ … ┆ organism ┆ genome_asse ┆ cre_name    ┆ fantabio_cr │
│ d            ┆ --- ┆ ---   ┆ ---        ┆   ┆ ---      ┆ mbly        ┆ ---         ┆ e_class     │
│ ---          ┆ i64 ┆ i64   ┆ i64        ┆   ┆ str      ┆ ---         ┆ str         ┆ ---         │
│ str          ┆     ┆       ┆            ┆   ┆          ┆ str         ┆             ┆ str         │
╞══════════════╪═════╪═══════╪════════════╪═══╪══════════╪═════════════╪═════════════╪═════════════╡
│ ENST00000738 ┆ 312 ┆ 9     ┆ 85         ┆ … ┆ human    ┆ hg38        ┆ FCHS_359461 ┆ ELA         │
│ 043.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
│ …            ┆ …   ┆ …     ┆ …          ┆ … ┆ …        ┆ …           ┆ …           ┆ …           │
│ ENST00000542 ┆ 55  ┆ 11    ┆ 340        ┆ … ┆ human    ┆ hg38        ┆ FCHS_76226  ┆ ELA         │
│ 775.1        ┆     ┆       ┆            ┆   ┆          ┆             ┆             ┆             │
└──────────────┴─────┴───────┴────────────┴───┴──────────┴─────────────┴─────────────┴─────────────┘

&nbsp;

&nbsp;

###