&nbsp;

## GENCODE promoter windows (GENCODE release 48)

- (2026-09-08) 後続の解析である `fanta.bio`における promoter の証拠としても使用できるため、統合する
- (2026-09-08) `fanta.bio`の BEDファイルと後で `bedtools intersect` しておくので、BEDファイルを作成しておく
- → `gffread` では、どうやら [gencode.v48.promoter_windows.gff3.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/gencode.v48.promoter_windows.gff3.gz) の feature の タイプ名のところが Sequence Ontology Feature Annotation (SOFA) に該当しない？ ため、うまく変換できないので、データフレームとして操作して変換する
- [../02_fantabio/02_5_ensembl_promoter_intersect.ipynb](../02_fantabio/02_5_ensembl_promoter_intersect.ipynb)に処理を移動
- https://www.gencodegenes.org/pages/promoter_windows/
- [gencode.v48.promoter_windows.gff3.gz](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/gencode.v48.promoter_windows.gff3.gz)

In [1]:
import os
import datetime
import pathlib
# import numpy as np
# import pandas as pd
import polars as pl
import plotly.express as px
from IPython.display import display

pl.Config.set_tbl_rows(6)
pl.Config.set_fmt_str_lengths(500)
os.environ["POLARS_MAX_THREADS"] = "16"

In [2]:
# https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/file-formats/annotation-files/about-ncbi-gff3/
# Caution: The information is based on GENCODE v48.
gencode_promoter_windows = pl.read_csv(
    "../../Data/Database/GENCODE_v49/metadata/gencode.v48.promoter_windows.gff3",
    separator="\t",
    comment_prefix="#",
    has_header=False,
    n_threads=16,
    new_columns=[
        "chromosome",
        "source",
        "feature",
        "start",
        "end",
        "score",
        "strand",
        "phase",
        "attribute"
    ]
)

display(gencode_promoter_windows)

shape: (19_466, 9)
┌────────────┬─────────┬─────────────────┬────────┬───┬───────┬────────┬───────┬───────────────────┐
│ chromosome ┆ source  ┆ feature         ┆ start  ┆ … ┆ score ┆ strand ┆ phase ┆ attribute         │
│ ---        ┆ ---     ┆ ---             ┆ ---    ┆   ┆ ---   ┆ ---    ┆ ---   ┆ ---               │
│ str        ┆ str     ┆ str             ┆ i64    ┆   ┆ str   ┆ str    ┆ str   ┆ str               │
╞════════════╪═════════╪═════════════════╪════════╪═══╪═══════╪════════╪═══════╪═══════════════════╡
│ chr1       ┆ GENCODE ┆ promoter_window ┆ 64419  ┆ … ┆ .     ┆ +      ┆ .     ┆ ID=ENSG0000018609 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 2_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=OR4F5_promo │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ter_window;gene_i │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ d=ENSG00000186092 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ .7;transcript_id= │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ENST00000641515.2 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;promoter_window_ │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ type=MANE_Select_ │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ with_TSS;window_s │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ize=1000          │
│ chr1       ┆ GENCODE ┆ promoter_window ┆ 451679 ┆ … ┆ .     ┆ -      ┆ .     ┆ ID=ENSG0000028473 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 3_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=OR4F29_prom │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ oter_window;gene_ │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ id=ENSG0000028473 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 3.2;transcript_id │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ =ENST00000426406. │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 4;promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ _type=MANE_Select │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ _without_TSS;wind │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ow_size=1000      │
│ chr1       ┆ GENCODE ┆ promoter_window ┆ 686655 ┆ … ┆ .     ┆ -      ┆ .     ┆ ID=ENSG0000028466 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 2_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=OR4F16_prom │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ oter_window;gene_ │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ id=ENSG0000028466 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 2.2;transcript_id │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ =ENST00000332831. │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 5;promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ _type=MANE_Select │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ _without_TSS;wind │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ow_size=1000      │
│ …          ┆ …       ┆ …               ┆ …      ┆ … ┆ …     ┆ …      ┆ …     ┆ …                 │
│ KI270734.1 ┆ GENCODE ┆ promoter_window ┆ 71411  ┆ … ┆ .     ┆ +      ┆ .     ┆ ID=ENSG0000027601 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 7_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=ENSG0000027 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 6017_promoter_win │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ dow;gene_id=ENSG0 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 0000276017.1;tran │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ script_id=ENST000 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00617983.1;promot │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ er_window_type=No │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ n_MANE_Select_mod │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ el;window_size=10 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00                │
│ KI270734.1 ┆ GENCODE ┆ promoter_window ┆ 130494 ┆ … ┆ .     ┆ +      ┆ .     ┆ ID=ENSG0000027881 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 7_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=ENSG0000027 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 8817_promoter_win │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ dow;gene_id=ENSG0 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 0000278817.1;tran │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ script_id=ENST000 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00613204.1;promot │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ er_window_type=No │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ n_MANE_Select_mod │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ el;window_size=10 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00                │
│ KI270734.1 ┆ GENCODE ┆ promoter_window ┆ 161853 ┆ … ┆ .     ┆ -      ┆ .     ┆ ID=ENSG0000027719 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 6_promoter_window │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ ;Name=ENSG0000027 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 7196_promoter_win │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ dow;gene_id=ENSG0 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 0000277196.4;tran │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ script_id=ENST000 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00621424.4;promot │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ er_window_type=No │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ n_MANE_Select_mod │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ el;window_size=10 │
│            ┆         ┆                 ┆        ┆   ┆       ┆        ┆       ┆ 00                │
└────────────┴─────────┴─────────────────┴────────┴───┴───────┴────────┴───────┴───────────────────┘

In [3]:
gencode_promoter_windows_parsed = gencode_promoter_windows.with_columns([
    pl.col("attribute").str.extract(r"ID=([^;]+)", group_index=1).alias("ID"),
    pl.col("attribute").str.extract(r"Name=([^;]+)", group_index=1).alias("Name"),
    pl.col("attribute").str.extract(r"gene_id=([^;]+)", group_index=1).alias("gene_id"),
    pl.col("attribute").str.extract(r"transcript_id=([^;]+)", group_index=1).alias("transcript_id"),
    pl.col("attribute").str.extract(r"promoter_window_type=([^;]+)", group_index=1).alias("promoter_window_type"),
    pl.col("attribute").str.extract(r"window_size=([^;]+)", group_index=1).alias("window_size"),
    pl.col("attribute").str.extract(r"ensembl_promoter_id=([^;]+)", group_index=1).alias("ensembl_promoter_id"),
]).drop(
    "attribute"
).sort(
    by="gene_id",
    descending=False
)

display(gencode_promoter_windows_parsed)

shape: (19_466, 15)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ chromosome ┆ source  ┆ feature   ┆ start     ┆ … ┆ transcrip ┆ promoter_ ┆ window_si ┆ ensembl_p │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ t_id      ┆ window_ty ┆ ze        ┆ romoter_i │
│ str        ┆ str     ┆ str       ┆ i64       ┆   ┆ ---       ┆ pe        ┆ ---       ┆ d         │
│            ┆         ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chrX       ┆ GENCODE ┆ promoter_ ┆ 100636807 ┆ … ┆ ENST00000 ┆ MANE_Sele ┆ 1000      ┆ ENSRX_93G │
│            ┆         ┆ window    ┆           ┆   ┆ 373020.9  ┆ ct_with_T ┆           ┆ XHH       │
│            ┆         ┆           ┆           ┆   ┆           ┆ SS        ┆           ┆           │
│ chrX       ┆ GENCODE ┆ promoter_ ┆ 100583936 ┆ … ┆ ENST00000 ┆ MANE_Sele ┆ 1000      ┆ null      │
│            ┆         ┆ window    ┆           ┆   ┆ 373031.5  ┆ ct_with_T ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆ SS        ┆           ┆           │
│ chr20      ┆ GENCODE ┆ promoter_ ┆ 50958533  ┆ … ┆ ENST00000 ┆ MANE_Sele ┆ 1000      ┆ ENSR20_9Q │
│            ┆         ┆ window    ┆           ┆   ┆ 371588.10 ┆ ct_with_T ┆           ┆ 84Z       │
│            ┆         ┆           ┆           ┆   ┆           ┆ SS        ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ chr14      ┆ GENCODE ┆ promoter_ ┆ 61320954  ┆ … ┆ ENST00000 ┆ Non_MANE_ ┆ 1000      ┆ ENSR14_BG │
│            ┆         ┆ window    ┆           ┆   ┆ 850887.1  ┆ Select_mo ┆           ┆ 6KQ       │
│            ┆         ┆           ┆           ┆   ┆           ┆ del       ┆           ┆           │
│ chrX       ┆ GENCODE ┆ promoter_ ┆ 45729995  ┆ … ┆ ENST00000 ┆ Non_MANE_ ┆ 1000      ┆ null      │
│            ┆         ┆ window    ┆           ┆   ┆ 850889.1  ┆ Select_mo ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆ del       ┆           ┆           │
│ chr19      ┆ GENCODE ┆ promoter_ ┆ 1274530   ┆ … ┆ ENST00000 ┆ MANE_Sele ┆ 1000      ┆ ENSR19_B8 │
│            ┆         ┆ window    ┆           ┆   ┆ 409293.6  ┆ ct_with_T ┆           ┆ SJ        │
│            ┆         ┆           ┆           ┆   ┆           ┆ SS        ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
gencode_promoter_windows_transcript = gencode_promoter_windows_parsed.select(
    pl.col("transcript_id"),
    pl.col("ID"),
    # pl.col("gene_id"),
    pl.col("promoter_window_type"),
    # pl.col("window_size"),
    pl.col("ensembl_promoter_id")
).unique(
    subset=["transcript_id", "promoter_window_type", "ensembl_promoter_id"]
)

display(gencode_promoter_windows_transcript)

shape: (19_466, 4)
┌────────────────────┬────────────────────────────────┬──────────────────────┬─────────────────────┐
│ transcript_id      ┆ ID                             ┆ promoter_window_type ┆ ensembl_promoter_id │
│ ---                ┆ ---                            ┆ ---                  ┆ ---                 │
│ str                ┆ str                            ┆ str                  ┆ str                 │
╞════════════════════╪════════════════════════════════╪══════════════════════╪═════════════════════╡
│ ENST00000369304.8  ┆ ENSG00000143127_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSR1_945WND        │
│                    ┆ w                              ┆                      ┆                     │
│ ENST00000221538.8  ┆ ENSG00000104941_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSR19_BC4HD        │
│                    ┆ w                              ┆                      ┆                     │
│ ENST00000243349.13 ┆ ENSG00000123612_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSR2_B369M5        │
│                    ┆ w                              ┆                      ┆                     │
│ …                  ┆ …                              ┆ …                    ┆ …                   │
│ ENST00000366690.5  ┆ ENSG00000168118_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSR1_7HH263        │
│                    ┆ w                              ┆                      ┆                     │
│ ENST00000395297.6  ┆ ENSG00000147724_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSR8_7B5TXR        │
│                    ┆ w                              ┆                      ┆                     │
│ ENST00000380833.9  ┆ ENSG00000073464_promoter_windo ┆ MANE_Select_with_TSS ┆ ENSRX_7L5DN         │
│                    ┆ w                              ┆                      ┆                     │
└────────────────────┴────────────────────────────────┴──────────────────────┴─────────────────────┘

In [5]:
# gffread ではうまく変換できないので、データフレームとして操作してBEDファイル (BED6 format)として保存しておく
gencode_promoter_windows_bed = gencode_promoter_windows_parsed.select(
    pl.col("chromosome"),
    (pl.col("start") - 1).alias("start"),  # GFF3 1-based inclusive -> BED 0-based half-open
    pl.col("end"),
    pl.col("ID"),
    pl.col("score"),
    pl.col("strand"),
    # pl.col("transcript_id"),
    # pl.col("promoter_window_type"),
    # pl.col("window_size"),
    # pl.col("ensembl_promoter_id").fill_null("."),
)

# gencode_promoter_windows_bed.write_csv(
#     "../../Data/Database/GENCODE_v49/metadata/gencode.v48.promoter_windows_v260908.bed",
#     include_header=False,
#     separator="\t",
#     null_value=".",
#     quote_style="never",
# )

display(gencode_promoter_windows_bed)

shape: (19_466, 6)
┌────────────┬───────────┬───────────┬─────────────────────────────────┬───────┬────────┐
│ chromosome ┆ start     ┆ end       ┆ ID                              ┆ score ┆ strand │
│ ---        ┆ ---       ┆ ---       ┆ ---                             ┆ ---   ┆ ---    │
│ str        ┆ i64       ┆ i64       ┆ str                             ┆ str   ┆ str    │
╞════════════╪═══════════╪═══════════╪═════════════════════════════════╪═══════╪════════╡
│ chrX       ┆ 100636806 ┆ 100637806 ┆ ENSG00000000003_promoter_window ┆ .     ┆ -      │
│ chrX       ┆ 100583935 ┆ 100584935 ┆ ENSG00000000005_promoter_window ┆ .     ┆ +      │
│ chr20      ┆ 50958532  ┆ 50959532  ┆ ENSG00000000419_promoter_window ┆ .     ┆ -      │
│ …          ┆ …         ┆ …         ┆ …                               ┆ …     ┆ …      │
│ chr14      ┆ 61320953  ┆ 61321953  ┆ ENSG00000310561_promoter_window ┆ .     ┆ +      │
│ chrX       ┆ 45729994  ┆ 45730994  ┆ ENSG00000310562_promoter_window ┆ .     ┆ +      │
│ chr19      ┆ 1274529   ┆ 1275529   ┆ ENSG00000310576_promoter_window ┆ .     ┆ +      │
└────────────┴───────────┴───────────┴─────────────────────────────────┴───────┴────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## `bedtools intersect`

- 実行コマンド
- `cwltool --outdir ./out/fantabio/bedtools_intersect/ ./Tools/bedtools_intersect_v2.cwl ./config/bedtools_intersect/gencode_v48_promoter_windows_intersect_fantabio_cre.yml`

In [6]:
fantabio_cre_intersect_gencode_v48_promoter_windows_bed = pl.read_csv(
    "../../out/fantabio/bedtools_intersect/gencode.v48.promoter_windows_v260908_intersecting_human-CREv1.2.1.hg38.cre-peaks.bed",
    separator="\t",
    has_header=False,
    n_threads=16,
    new_columns=[
        "chromosome_ensembl",
        "start_ensembl",
        "end_ensembl",
        "ensembl_promoter_accession",
        "score",
        "strand",
        "chromosome_fantabio",
        "start_fantabio",
        "end_fantabio",
        "cre_id",
        "score_cre",
        "strand_cre",
        "thick_start_cre",
        "thick_end_cre",
        "item_rgb",
        "cre_name",
        "pooled_cre_scores",
        "intersect_length"
    ]
).with_columns(
    # 念のため確認
    whether_promoter_window_is_contained_in_cre=pl.col("chromosome_ensembl") == pl.col("chromosome_fantabio")
).filter(
    pl.col("whether_promoter_window_is_contained_in_cre") == True
).drop(
    "whether_promoter_window_is_contained_in_cre"
).select(
    "chromosome_ensembl",
    "start_ensembl",
    "end_ensembl",
    "ensembl_promoter_accession",
    "strand",
    "chromosome_fantabio",
    "start_fantabio",
    "end_fantabio",
    "cre_id",
    "cre_name",
    "pooled_cre_scores",
    "intersect_length"
).with_columns(
    (pl.col("intersect_length") / (pl.col("end_ensembl") - pl.col("start_ensembl"))).alias("fantabio_cre_overlap_frac_of_ensembl_promoter_window"),
    pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
    pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
).drop(
    "pooled_cre_scores"
)

display(fantabio_cre_intersect_gencode_v48_promoter_windows_bed)

shape: (40_914, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chromosom ┆ start_ens ┆ end_ensem ┆ ensembl_p ┆ … ┆ intersect ┆ fantabio_ ┆ direction ┆ fantabio │
│ e_ensembl ┆ embl      ┆ bl        ┆ romoter_a ┆   ┆ _length   ┆ cre_overl ┆ ality     ┆ _cre_cla │
│ ---       ┆ ---       ┆ ---       ┆ ccession  ┆   ┆ ---       ┆ ap_frac_o ┆ ---       ┆ ss       │
│ str       ┆ i64       ┆ i64       ┆ ---       ┆   ┆ i64       ┆ f_ensembl ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ _promoter ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ _window   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ 314       ┆ 0.314     ┆ -0.998632 ┆ PLA      │
│           ┆           ┆           ┆ 000003_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ 155       ┆ 0.155     ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 000003_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100583935 ┆ 100584935 ┆ ENSG00000 ┆ … ┆ 178       ┆ 0.178     ┆ 1.0       ┆ PLA      │
│           ┆           ┆           ┆ 000005_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chr14     ┆ 61320953  ┆ 61321953  ┆ ENSG00000 ┆ … ┆ 108       ┆ 0.108     ┆ -0.333333 ┆ ELA      │
│           ┆           ┆           ┆ 310561_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ 310       ┆ 0.31      ┆ 0.908046  ┆ ELA      │
│           ┆           ┆           ┆ 310576_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ 166       ┆ 0.166     ┆ 0.991043  ┆ PLA      │
│           ┆           ┆           ┆ 310576_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
gencode_promoter_windows_parse_for_join = gencode_promoter_windows_parsed.select(
    "chromosome",
    "start",
    "end",
    "ID",
    "window_size",
    "strand",
    "ensembl_promoter_id",
    "Name",
    "gene_id",
    "transcript_id",
    "promoter_window_type"
).with_columns(
    (pl.col("start") - 1).alias("start"), # GFF3 1-based inclusive -> BED 0-based half-open
).rename(
    {
        "chromosome": "chromosome_ensembl",
        "start": "start_ensembl",
        "end": "end_ensembl",
        "ID": "ensembl_promoter_accession",
        "window_size": "ensembl_promoter_window_size"
    }
)

display(gencode_promoter_windows_parse_for_join)

shape: (19_466, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chromosom ┆ start_ens ┆ end_ensem ┆ ensembl_p ┆ … ┆ Name      ┆ gene_id   ┆ transcrip ┆ promoter │
│ e_ensembl ┆ embl      ┆ bl        ┆ romoter_a ┆   ┆ ---       ┆ ---       ┆ t_id      ┆ _window_ │
│ ---       ┆ ---       ┆ ---       ┆ ccession  ┆   ┆ str       ┆ str       ┆ ---       ┆ type     │
│ str       ┆ i64       ┆ i64       ┆ ---       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ TSPAN6_pr ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000003_pr ┆   ┆ omoter_wi ┆ 000003.16 ┆ 373020.9  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ndow      ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100583935 ┆ 100584935 ┆ ENSG00000 ┆ … ┆ TNMD_prom ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000005_pr ┆   ┆ oter_wind ┆ 000005.6  ┆ 373031.5  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ow        ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr20     ┆ 50958532  ┆ 50959532  ┆ ENSG00000 ┆ … ┆ DPM1_prom ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000419_pr ┆   ┆ oter_wind ┆ 000419.14 ┆ 371588.10 ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ow        ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chr14     ┆ 61320953  ┆ 61321953  ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENST00000 ┆ Non_MANE │
│           ┆           ┆           ┆ 310561_pr ┆   ┆ 310561_pr ┆ 310561.1  ┆ 850887.1  ┆ _Select_ │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ omoter_wi ┆           ┆           ┆ model    │
│           ┆           ┆           ┆ ndow      ┆   ┆ ndow      ┆           ┆           ┆          │
│ chrX      ┆ 45729994  ┆ 45730994  ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENST00000 ┆ Non_MANE │
│           ┆           ┆           ┆ 310562_pr ┆   ┆ 310562_pr ┆ 310562.1  ┆ 850889.1  ┆ _Select_ │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ omoter_wi ┆           ┆           ┆ model    │
│           ┆           ┆           ┆ ndow      ┆   ┆ ndow      ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ FAM174C_p ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 310576_pr ┆   ┆ romoter_w ┆ 310576.1  ┆ 409293.6  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ indow     ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
fantabio_cre_intersect_gencode_v48_promoter_windows_bed_join = fantabio_cre_intersect_gencode_v48_promoter_windows_bed.join(
    gencode_promoter_windows_parse_for_join,
    on=[
        "chromosome_ensembl",
        "start_ensembl",
        "end_ensembl",
        "ensembl_promoter_accession",
        "strand"
    ],
    how="inner",
    coalesce=True
)

display(fantabio_cre_intersect_gencode_v48_promoter_windows_bed_join)

shape: (40_914, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chromosom ┆ start_ens ┆ end_ensem ┆ ensembl_p ┆ … ┆ Name      ┆ gene_id   ┆ transcrip ┆ promoter │
│ e_ensembl ┆ embl      ┆ bl        ┆ romoter_a ┆   ┆ ---       ┆ ---       ┆ t_id      ┆ _window_ │
│ ---       ┆ ---       ┆ ---       ┆ ccession  ┆   ┆ str       ┆ str       ┆ ---       ┆ type     │
│ str       ┆ i64       ┆ i64       ┆ ---       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ TSPAN6_pr ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000003_pr ┆   ┆ omoter_wi ┆ 000003.16 ┆ 373020.9  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ndow      ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ TSPAN6_pr ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000003_pr ┆   ┆ omoter_wi ┆ 000003.16 ┆ 373020.9  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ndow      ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100583935 ┆ 100584935 ┆ ENSG00000 ┆ … ┆ TNMD_prom ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 000005_pr ┆   ┆ oter_wind ┆ 000005.6  ┆ 373031.5  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ ow        ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chr14     ┆ 61320953  ┆ 61321953  ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENST00000 ┆ Non_MANE │
│           ┆           ┆           ┆ 310561_pr ┆   ┆ 310561_pr ┆ 310561.1  ┆ 850887.1  ┆ _Select_ │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ omoter_wi ┆           ┆           ┆ model    │
│           ┆           ┆           ┆ ndow      ┆   ┆ ndow      ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ FAM174C_p ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 310576_pr ┆   ┆ romoter_w ┆ 310576.1  ┆ 409293.6  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ indow     ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ FAM174C_p ┆ ENSG00000 ┆ ENST00000 ┆ MANE_Sel │
│           ┆           ┆           ┆ 310576_pr ┆   ┆ romoter_w ┆ 310576.1  ┆ 409293.6  ┆ ect_with │
│           ┆           ┆           ┆ omoter_wi ┆   ┆ indow     ┆           ┆           ┆ _TSS     │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Check

- Prefer PLA, then the CRE with larger overlap of the promoter window.

In [10]:
# Prefer PLA, then the CRE with larger overlap of the promoter window.
fantabio_cre_one_per_promoter = (
    fantabio_cre_intersect_gencode_v48_promoter_windows_bed
    .sort(
        "ensembl_promoter_accession",
        pl.col("fantabio_cre_class") == "PLA",
        "fantabio_cre_overlap_frac_of_ensembl_promoter_window",
        descending=[False, True, True],
    )
    .unique(
        subset="ensembl_promoter_accession",
        keep="first",
        maintain_order=True,
    )
)

fantabio_cre_one_per_promoter.write_csv(
    "../../out/fantabio/ensembl_promoter/gencode.v48.promoter_windows_v260908_intersecting_human-CREv1.2.1.hg38.cre-peaks_v261003_one_per_promoter.tsv",
    separator="\t"
)

display(fantabio_cre_one_per_promoter)

shape: (17_645, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chromosom ┆ start_ens ┆ end_ensem ┆ ensembl_p ┆ … ┆ intersect ┆ fantabio_ ┆ direction ┆ fantabio │
│ e_ensembl ┆ embl      ┆ bl        ┆ romoter_a ┆   ┆ _length   ┆ cre_overl ┆ ality     ┆ _cre_cla │
│ ---       ┆ ---       ┆ ---       ┆ ccession  ┆   ┆ ---       ┆ ap_frac_o ┆ ---       ┆ ss       │
│ str       ┆ i64       ┆ i64       ┆ ---       ┆   ┆ i64       ┆ f_ensembl ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆ _promoter ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ _window   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chrX      ┆ 100636806 ┆ 100637806 ┆ ENSG00000 ┆ … ┆ 314       ┆ 0.314     ┆ -0.998632 ┆ PLA      │
│           ┆           ┆           ┆ 000003_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chrX      ┆ 100583935 ┆ 100584935 ┆ ENSG00000 ┆ … ┆ 178       ┆ 0.178     ┆ 1.0       ┆ PLA      │
│           ┆           ┆           ┆ 000005_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr20     ┆ 50958532  ┆ 50959532  ┆ ENSG00000 ┆ … ┆ 475       ┆ 0.475     ┆ -0.864704 ┆ PLA      │
│           ┆           ┆           ┆ 000419_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chr9      ┆ 136991421 ┆ 136992421 ┆ ENSG00000 ┆ … ┆ 454       ┆ 0.454     ┆ 0.970768  ┆ PLA      │
│           ┆           ┆           ┆ 310560_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr14     ┆ 61320953  ┆ 61321953  ┆ ENSG00000 ┆ … ┆ 796       ┆ 0.796     ┆ 0.91713   ┆ PLA      │
│           ┆           ┆           ┆ 310561_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
│ chr19     ┆ 1274529   ┆ 1275529   ┆ ENSG00000 ┆ … ┆ 166       ┆ 0.166     ┆ 0.991043  ┆ PLA      │
│           ┆           ┆           ┆ 310576_pr ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ omoter_wi ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ndow      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘