&nbsp;

&nbsp;

# (Experimental) [fanta.bio](https://fanta.bio/) Expression Specificity Calculation

- Tags Per Million (TPM) データ を元に、Expression Specificity の計算を行ってみる

&nbsp;

## 参考

1. [NET-CAGE characterizes the dynamics and topology of human transcribed cis-regulatory elements](https://doi.org/10.1038/s41588-019-0485-9)
2. [An atlas of human long non-coding RNAs with accurate 5′ ends](https://doi.org/10.1038/nature21374)
3. [Recounting the FANTOM CAGE-Associated Transcriptome](https://doi.org/10.1101/gr.254656.119)
    - Code: [04expressionSpecificity.R](https://github.com/eddieimada/fcr2/blob/master/GTEX/04expressionSpecificity.R)

In [1]:
import os
import datetime
import csv
import gzip
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import plotly.express as px
import matplotlib.pyplot as plt
from IPython.display import display

pl.show_versions()
print(pl.thread_pool_size())
os.environ["POLARS_MAX_THREADS"] = "16"

--------Version info---------
Polars:              1.40.1
Index type:          UInt32
Platform:            Linux-7.0.14-orbstack-00380-ga7e0a2dc9535-aarch64-with-glibc2.36
Python:              3.13.15 (main, Aug 25 2026, 03:44:12) [GCC 12.2.0]
Runtime:             rt32

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               5.5.0
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          3.1.2
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               2026.7.0
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.8.4
numpy                2.3.2
openpyxl             3.1.5
pandas               2.3.2
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             2.13.5
pyiceberg            <not installed>
sqlalchemy           2.0.52
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           3.2.9
16

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
Execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {Execute_date}")

Execute Date: 261016

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## `fanta.bio` `BED`file

In [3]:
# https://data.fanta.bio/cre/v1.2.1/00README_v1.2.1.txt
fantabio_bed = pl.read_csv(
    "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks.bed",
    separator="\t",
    has_header=False,
    new_columns=[
        "cre_chrom",
        "cre_chrom_start",
        "cre_chrom_end",
        "cre_id",
        "score",
        "strand",
        "thickStart",
        "thickEnd",
        "itemRgb",
        "cre_name",
        "pooled_cre_scores"
    ]
).with_columns(
    pl.col("pooled_cre_scores").str.extract(r"directionality:([^|]+)", 1).cast(pl.Float64, strict=False).alias("directionality"),
    pl.col("pooled_cre_scores").str.extract(r"class:([^|]+)", 1).alias("fantabio_cre_class"),
)

display(fantabio_bed)

shape: (513_895, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_chrom ┆ cre_chrom ┆ cre_chrom ┆ cre_id    ┆ … ┆ cre_name  ┆ pooled_cr ┆ direction ┆ fantabio │
│ ---       ┆ _start    ┆ _end      ┆ ---       ┆   ┆ ---       ┆ e_scores  ┆ ality     ┆ _cre_cla │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ss       │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ chr1      ┆ 10609     ┆ 10687     ┆ FCHS_1    ┆ … ┆ cp1@DDX11 ┆ direction ┆ -1.0      ┆ PLA      │
│           ┆           ┆           ┆           ┆   ┆ L1        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:PLA ┆           ┆          │
│ chr1      ┆ 29398     ┆ 29439     ┆ FCHS_2    ┆ … ┆ cp1@WASH7 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ P         ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chr1      ┆ 181113    ┆ 181501    ┆ FCHS_4474 ┆ … ┆ cp1@DDX11 ┆ direction ┆ -0.684211 ┆ ELA      │
│           ┆           ┆           ┆ 16        ┆   ┆ L17       ┆ ality:-0. ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 684211|cl ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ass…      ┆           ┆          │
│ chr1      ┆ 190831    ┆ 191016    ┆ FCHS_4474 ┆ … ┆ FCHS_4474 ┆ direction ┆ 0.485714  ┆ ELA      │
│           ┆           ┆           ┆ 17        ┆   ┆ 17        ┆ ality:0.4 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 85714|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
│ chr1      ┆ 588413    ┆ 588453    ┆ FCHS_3    ┆ … ┆ cp2@LOC10 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆           ┆   ┆ 1928626   ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ chrY      ┆ 56846801  ┆ 56846977  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 1.0       ┆ ELA      │
│           ┆           ┆           ┆ 11        ┆   ┆ 11        ┆ ality:1|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56855787  ┆ 56855988  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ 0.0       ┆ ELA      │
│           ┆           ┆           ┆ 12        ┆   ┆ 12        ┆ ality:0|c ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ lass:ELA  ┆           ┆          │
│ chrY      ┆ 56863206  ┆ 56863354  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 13        ┆   ┆ 13        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chrY      ┆ 56864544  ┆ 56864748  ┆ FCHS_4473 ┆ … ┆ FCHS_4473 ┆ direction ┆ -1.0      ┆ ELA      │
│           ┆           ┆           ┆ 14        ┆   ┆ 14        ┆ ality:-1| ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ class:ELA ┆           ┆          │
│ chrY      ┆ 56881614  ┆ 56881922  ┆ FCHS_5939 ┆ … ┆ FCHS_5939 ┆ direction ┆ 0.989305  ┆ PLA      │
│           ┆           ┆           ┆ 40        ┆   ┆ 40        ┆ ality:0.9 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 89305|cla ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ss:…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# Map exact RGB strings to human-readable names
rgb_to_name = {
    "153,0,0": "dark_red",
    "101,0,0": "dark_red",
    "50,0,0": "dark_red",
    "204,0,0": "red",
    "255,0,0": "red",
    "0,0,51": "dark_blue",
    "0,0,102": "dark_blue",
    "0,0,153": "blue",
    "0,0,204": "blue",
    "0,0,255": "blue",
    "0,0,0": "black",
    "255,202,74": "yellow",
}

fantabio_bed_select = fantabio_bed.with_columns(
    pl.col("itemRgb").replace_strict(
        rgb_to_name,
        default="other"
    ).alias("itemRgb_name")
).select(
    "cre_id",
    "cre_name",
    "directionality",
    "fantabio_cre_class",
    "itemRgb",
    "itemRgb_name"
)

display(fantabio_bed_select)

shape: (513_895, 6)
┌─────────────┬──────────────────┬────────────────┬────────────────────┬────────────┬──────────────┐
│ cre_id      ┆ cre_name         ┆ directionality ┆ fantabio_cre_class ┆ itemRgb    ┆ itemRgb_name │
│ ---         ┆ ---              ┆ ---            ┆ ---                ┆ ---        ┆ ---          │
│ str         ┆ str              ┆ f64            ┆ str                ┆ str        ┆ str          │
╞═════════════╪══════════════════╪════════════════╪════════════════════╪════════════╪══════════════╡
│ FCHS_1      ┆ cp1@DDX11L1      ┆ -1.0           ┆ PLA                ┆ 0,0,255    ┆ blue         │
│ FCHS_2      ┆ cp1@WASH7P       ┆ 1.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447416 ┆ cp1@DDX11L17     ┆ -0.684211      ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447417 ┆ FCHS_447417      ┆ 0.485714       ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_3      ┆ cp2@LOC101928626 ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ …           ┆ …                ┆ …              ┆ …                  ┆ …          ┆ …            │
│ FCHS_447311 ┆ FCHS_447311      ┆ 1.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447312 ┆ FCHS_447312      ┆ 0.0            ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447313 ┆ FCHS_447313      ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_447314 ┆ FCHS_447314      ┆ -1.0           ┆ ELA                ┆ 255,202,74 ┆ yellow       │
│ FCHS_593940 ┆ FCHS_593940      ┆ 0.989305       ┆ PLA                ┆ 204,0,0    ┆ red          │
└─────────────┴──────────────────┴────────────────┴────────────────────┴────────────┴──────────────┘

&nbsp;

&nbsp;

## `fanta.bio` resource (sample annotation data)

- 使用されたCAGEデータのサンプル一覧を読み込む

In [5]:
fantabio_sample_metadata = pl.read_csv(
    "../../Data/Database/fantabio/fanta.bio-CREv1.2.1.metadata.human.sdrf.txt.gz",
    separator="\t"
)

display(fantabio_sample_metadata)

shape: (2_644, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Character ┆ Character ┆ … ┆ Comment[C ┆ Comment[C ┆ Comment[C ┆ Comment[ │
│ Name      ┆ [biosampl ┆ istics    ┆ istics    ┆   ┆ TSS count ┆ TSS count ┆ TSS TPM   ┆ CTSS TPM │
│ ---       ┆ e_id]     ┆ [organism ┆ [sample   ┆   ┆ forward   ┆ reverse   ┆ forward   ┆ reverse  │
│ str       ┆ ---       ┆ ]         ┆ type]     ┆   ┆ fil…      ┆ fil…      ┆ file]     ┆ file]    │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CNhs10608 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 752       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1060 ┆ /CNhs1060 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 8.ctss.fw ┆ 8.ctss.re ┆ 0608.ctss ┆ s10608.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10610 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 009       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 0.ctss.fw ┆ 0.ctss.re ┆ 0610.ctss ┆ s10610.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10612 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 100       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 2.ctss.fw ┆ 2.ctss.re ┆ 0612.ctss ┆ s10612.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10615 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 635       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 5.ctss.fw ┆ 5.ctss.re ┆ 0615.ctss ┆ s10615.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10616 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 257       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 6.ctss.fw ┆ 6.ctss.re ┆ 0616.ctss ┆ s10616.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRX285511 ┆ SAMN48137 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 90        ┆ 815       ┆ sapiens   ┆ culture   ┆   ┆ /SRX28551 ┆ /SRX28551 ┆ Tpm/SRX28 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 190.ctss. ┆ 190.ctss. ┆ 551190.ct ┆ 28551190 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX285511 ┆ SAMN48137 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 89        ┆ 816       ┆ sapiens   ┆ culture   ┆   ┆ /SRX28551 ┆ /SRX28551 ┆ Tpm/SRX28 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 189.ctss. ┆ 189.ctss. ┆ 551189.ct ┆ 28551189 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX285511 ┆ SAMN48137 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 88        ┆ 817       ┆ sapiens   ┆ culture   ┆   ┆ /SRX28551 ┆ /SRX28551 ┆ Tpm/SRX28 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 188.ctss. ┆ 188.ctss. ┆ 551188.ct ┆ 28551188 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX285511 ┆ SAMN48137 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 87        ┆ 818       ┆ sapiens   ┆ culture   ┆   ┆ /SRX28551 ┆ /SRX28551 ┆ Tpm/SRX28 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 187.ctss. ┆ 187.ctss. ┆ 551187.ct ┆ 28551187 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX285511 ┆ SAMN48137 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 86        ┆ 819       ┆ sapiens   ┆ culture   ┆   ┆ /SRX28551 ┆ /SRX28551 ┆ Tpm/SRX28 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 186.ctss. ┆ 186.ctss. ┆ 551186.ct ┆ 28551186 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

## Sample Classification

- cell 由来のサンプルと、tissue 由来のサンプルに分ける

In [6]:
fantabio_sample_cell = fantabio_sample_metadata.filter(
    (pl.col("Characteristics [CL term]").is_not_null()) |
    (pl.col("Characteristics [cell line]").is_not_null())
).sort(
    by=["Term Accession Number"],
    descending=True
)

display(fantabio_sample_cell)

shape: (1_974, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Character ┆ Character ┆ … ┆ Comment[C ┆ Comment[C ┆ Comment[C ┆ Comment[ │
│ Name      ┆ [biosampl ┆ istics    ┆ istics    ┆   ┆ TSS count ┆ TSS count ┆ TSS TPM   ┆ CTSS TPM │
│ ---       ┆ e_id]     ┆ [organism ┆ [sample   ┆   ┆ forward   ┆ reverse   ┆ forward   ┆ reverse  │
│ str       ┆ ---       ┆ ]         ┆ type]     ┆   ┆ fil…      ┆ fil…      ┆ file]     ┆ file]    │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CNhs10722 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 753       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 2.ctss.fw ┆ 2.ctss.re ┆ 0722.ctss ┆ s10722.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10723 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 601       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 3.ctss.fw ┆ 3.ctss.re ┆ 0723.ctss ┆ s10723.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10724 ┆ SAMD00004 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 824       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 4.ctss.fw ┆ 4.ctss.re ┆ 0724.ctss ┆ s10724.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10726 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 224       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 6.ctss.fw ┆ 6.ctss.re ┆ 0726.ctss ┆ s10726.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10727 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 883       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 7.ctss.fw ┆ 7.ctss.re ┆ 0727.ctss ┆ s10727.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CNhs13227 ┆ SAMD00005 ┆ Homo      ┆ primary   ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 368       ┆ sapiens   ┆ cell      ┆   ┆ /CNhs1322 ┆ /CNhs1322 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 7.ctss.fw ┆ 7.ctss.re ┆ 3227.ctss ┆ s13227.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs12205 ┆ SAMD00005 ┆ Homo      ┆ primary   ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 630       ┆ sapiens   ┆ cell      ┆   ┆ /CNhs1220 ┆ /CNhs1220 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 5.ctss.fw ┆ 5.ctss.re ┆ 2205.ctss ┆ s12205.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs12552 ┆ SAMD00005 ┆ Homo      ┆ primary   ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 606       ┆ sapiens   ┆ cell      ┆   ┆ /CNhs1255 ┆ /CNhs1255 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 2.ctss.fw ┆ 2.ctss.re ┆ 2552.ctss ┆ s12552.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs12553 ┆ SAMD00005 ┆ Homo      ┆ primary   ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 703       ┆ sapiens   ┆ cell      ┆   ┆ /CNhs1255 ┆ /CNhs1255 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 3.ctss.fw ┆ 3.ctss.re ┆ 2553.ctss ┆ s12553.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs12588 ┆ SAMD00005 ┆ Homo      ┆ primary   ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 703       ┆ sapiens   ┆ cell      ┆   ┆ /CNhs1258 ┆ /CNhs1258 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 8.ctss.fw ┆ 8.ctss.re ┆ 2588.ctss ┆ s12588.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
fantabio_sample_uberon = fantabio_sample_metadata.filter(
    pl.col("Characteristics [tissue]").is_not_null()
).sort(
    by=["Term Accession Number"],
    descending=True
)

display(fantabio_sample_uberon)

shape: (404, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Character ┆ Character ┆ … ┆ Comment[C ┆ Comment[C ┆ Comment[C ┆ Comment[ │
│ Name      ┆ [biosampl ┆ istics    ┆ istics    ┆   ┆ TSS count ┆ TSS count ┆ TSS TPM   ┆ CTSS TPM │
│ ---       ┆ e_id]     ┆ [organism ┆ [sample   ┆   ┆ forward   ┆ reverse   ┆ forward   ┆ reverse  │
│ str       ┆ ---       ┆ ]         ┆ type]     ┆   ┆ fil…      ┆ fil…      ┆ file]     ┆ file]    │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRX233664 ┆ SAMN39578 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 60        ┆ 383       ┆ sapiens   ┆ sample    ┆   ┆ /SRX23366 ┆ /SRX23366 ┆ Tpm/SRX23 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 460.ctss. ┆ 460.ctss. ┆ 366460.ct ┆ 23366460 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX233664 ┆ SAMN39578 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 61        ┆ 382       ┆ sapiens   ┆ sample    ┆   ┆ /SRX23366 ┆ /SRX23366 ┆ Tpm/SRX23 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 461.ctss. ┆ 461.ctss. ┆ 366461.ct ┆ 23366461 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX233664 ┆ SAMN39578 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 62        ┆ 381       ┆ sapiens   ┆ sample    ┆   ┆ /SRX23366 ┆ /SRX23366 ┆ Tpm/SRX23 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 462.ctss. ┆ 462.ctss. ┆ 366462.ct ┆ 23366462 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX233664 ┆ SAMN39578 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 63        ┆ 380       ┆ sapiens   ┆ sample    ┆   ┆ /SRX23366 ┆ /SRX23366 ┆ Tpm/SRX23 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 463.ctss. ┆ 463.ctss. ┆ 366463.ct ┆ 23366463 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX233664 ┆ SAMN39578 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 64        ┆ 379       ┆ sapiens   ┆ sample    ┆   ┆ /SRX23366 ┆ /SRX23366 ┆ Tpm/SRX23 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 464.ctss. ┆ 464.ctss. ┆ 366464.ct ┆ 23366464 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CNhs10619 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 815       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 9.ctss.fw ┆ 9.ctss.re ┆ 0619.ctss ┆ s10619.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10618 ┆ SAMD00004 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 902       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 8.ctss.fw ┆ 8.ctss.re ┆ 0618.ctss ┆ s10618.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10617 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 144       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 7.ctss.fw ┆ 7.ctss.re ┆ 0617.ctss ┆ s10617.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10616 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 257       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 6.ctss.fw ┆ 6.ctss.re ┆ 0616.ctss ┆ s10616.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10615 ┆ SAMD00005 ┆ Homo      ┆ tissue    ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 635       ┆ sapiens   ┆ sample    ┆   ┆ /CNhs1061 ┆ /CNhs1061 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 5.ctss.fw ┆ 5.ctss.re ┆ 0615.ctss ┆ s10615.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## `fanta.bio` resource (Tags per million (TPM) data)

- 熱ストレス下のCAGEデータと比較できるかもしれないので、読み込んでおく
- 栂さんから教えてもらった[NET-CAGEの論文](https://doi.org/10.1038/s41588-019-0485-9)のFig.6に記載がある

In [8]:
tpm_path = "../../Data/Database/fantabio/human-CREv1.2.1.hg38.cre-peaks.tpm.txt.gz"
# Skip ## comment lines. read_csv n_rows counts those lines, so n_rows=1 returns no data.
with gzip.open(tpm_path, "rt") as handle:
    tpm_columns = next(
        csv.reader(
            (line for line in handle if not line.startswith("##")),
            delimiter="\t",
        )
    )

# Sample columns are TPM. Lock them to Float64 so integer-looking rows are not inferred as Int64.
fantabio_tpm = pl.read_csv(
    tpm_path,
    separator="\t",
    n_threads=16,
    comment_prefix="##",
    schema={
        name: pl.String if name == "creRegion" else pl.Float64
        for name in tpm_columns
    },
).with_columns(
    # "creRegion" カラムの内容を分割して、最初の要素 (fanta.bio の CRE ID) を "cre_id" カラムとして抽出
    pl.col(
        "creRegion"
    ).str.split(
        "|"
    ).list.first().alias(
        "creRegion"
    )
).rename(
    {
        "creRegion": "cre_id"
    }
)

display(fantabio_tpm)

shape: (513_895, 2_645)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cre_id    ┆ DRX199485 ┆ DRX199486 ┆ DRX199487 ┆ … ┆ CNhi10941 ┆ LShi10008 ┆ LShi10030 ┆ LShi1003 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _GCT      ┆ _ACAGTG-C ┆ _ACAGTG-C ┆ 0_ACTTGA │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ACTAGT    ┆ ACTATG    ┆ -CACTAGT │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ FCHS_1    ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.142706  ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ FCHS_2    ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.529031 │
│ FCHS_4474 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 16        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_4474 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 17        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_3    ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ FCHS_4473 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 11        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_4473 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 12        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_4473 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 13        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_4473 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 14        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ FCHS_5939 ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 40        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Test (1)

- 例えば、THP-1 cell について考える
- まず、THP-1 に該当する Source name をリストとして取得する
- その後、そのリストに該当するカラムを、`fanta.bio_tpm` データフレームから探す

In [9]:
THP1_cell = fantabio_sample_cell.filter(
    pl.col("Characteristics [EFO term]") == "THP-1"
)

THP1_cell_source_names = THP1_cell["Source Name"].to_list()

display(THP1_cell)

shape: (72, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Character ┆ Character ┆ … ┆ Comment[C ┆ Comment[C ┆ Comment[C ┆ Comment[ │
│ Name      ┆ [biosampl ┆ istics    ┆ istics    ┆   ┆ TSS count ┆ TSS count ┆ TSS TPM   ┆ CTSS TPM │
│ ---       ┆ e_id]     ┆ [organism ┆ [sample   ┆   ┆ forward   ┆ reverse   ┆ forward   ┆ reverse  │
│ str       ┆ ---       ┆ ]         ┆ type]     ┆   ┆ fil…      ┆ fil…      ┆ file]     ┆ file]    │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CNhs10722 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 753       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 2.ctss.fw ┆ 2.ctss.re ┆ 0722.ctss ┆ s10722.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10723 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 601       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 3.ctss.fw ┆ 3.ctss.re ┆ 0723.ctss ┆ s10723.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10724 ┆ SAMD00004 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 824       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 4.ctss.fw ┆ 4.ctss.re ┆ 0724.ctss ┆ s10724.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs14556 ┆ SAMD00022 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 299       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1455 ┆ /CNhs1455 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 6.ctss.fw ┆ 6.ctss.re ┆ 4556.ctss ┆ s14556.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ SRX658638 ┆ SRS515207 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 3         ┆ 8         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65863 ┆ /SRX65863 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 83.ctss.f ┆ 83.ctss.r ┆ 86383.cts ┆ 6586383. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRX658623 ┆ SRS515192 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 2         ┆ 7         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65862 ┆ /SRX65862 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 32.ctss.f ┆ 32.ctss.r ┆ 86232.cts ┆ 6586232. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
│ SRX658623 ┆ SRS515192 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 1         ┆ 6         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65862 ┆ /SRX65862 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 31.ctss.f ┆ 31.ctss.r ┆ 86231.cts ┆ 6586231. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
│ SRX658623 ┆ SRS515192 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 0         ┆ 5         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65862 ┆ /SRX65862 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 30.ctss.f ┆ 30.ctss.r ┆ 86230.cts ┆ 6586230. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
│ SRX658622 ┆ SRS515192 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 9         ┆ 4         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65862 ┆ /SRX65862 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 29.ctss.f ┆ 29.ctss.r ┆ 86229.cts ┆ 6586229. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
│ SRX658622 ┆ SRS515192 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 8         ┆ 3         ┆ sapiens   ┆ culture   ┆   ┆ /SRX65862 ┆ /SRX65862 ┆ Tpm/SRX65 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 28.ctss.f ┆ 28.ctss.r ┆ 86228.cts ┆ 6586228. │
│           ┆           ┆           ┆           ┆   ┆ wd.…      ┆ ev.…      ┆ sTp…      ┆ ctssTp…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

## Test (2)

- 平均のTPM値をサンプルごとに計算する (今回は THP-1)
- このデータフレーム、cre_id カラムと サンプルごとに計算した平均のTPM値 のカラムを持つデータフレームを作成し、それを cre_id をキーに `join` していくイメージ
- 最終的に、サンプルごとの平均TPM値を持つデータフレームを作成する
- この後に、エントロピーの計算、および、expression specificity を計算するイメージ

In [10]:
fantabio_tpm_thp1 = fantabio_tpm.select(
   "cre_id",
   # Same select expression as fantabio_tpm_mean. with_columns changes the float bits.
   pl.mean_horizontal(sorted(THP1_cell_source_names)).alias(
      "mean_tpm_" + THP1_cell.select("Term Accession Number_duplicated_0").unique().item()
   ),
)

display(fantabio_tpm_thp1)

shape: (513_895, 2)
┌─────────────┬────────────────────┐
│ cre_id      ┆ mean_tpm_CVCL_0006 │
│ ---         ┆ ---                │
│ str         ┆ f64                │
╞═════════════╪════════════════════╡
│ FCHS_1      ┆ 0.847295           │
│ FCHS_2      ┆ 0.0                │
│ FCHS_447416 ┆ 0.007199           │
│ FCHS_447417 ┆ 0.0                │
│ FCHS_3      ┆ 0.0                │
│ …           ┆ …                  │
│ FCHS_447311 ┆ 0.0                │
│ FCHS_447312 ┆ 0.0                │
│ FCHS_447313 ┆ 0.0                │
│ FCHS_447314 ┆ 0.0                │
│ FCHS_593940 ┆ 0.0                │
└─────────────┴────────────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 全てのサンプルへの拡張

### 1. サンプルと注釈を、見やすい列名の表にする

- THP-1 の元の列順を保つため、既存の cell 表 → tissue 表 → 残りの metadata の順で並べる。
- 重複して登場した同じ `Source Name` は一度だけ使う。元の metadata 自体に重複 ID があれば停止する。

In [11]:
assert fantabio_sample_metadata["Source Name"].null_count() == 0
assert fantabio_sample_metadata["Source Name"].n_unique() == fantabio_sample_metadata.height


fantabio_sample_ordered = (
    pl
    .concat(
        [
            fantabio_sample_cell, fantabio_sample_uberon, fantabio_sample_metadata,
        ]
    )
    .unique(
        subset="Source Name",
        keep="first",
        maintain_order=True
    )
)

display(fantabio_sample_ordered)

shape: (2_644, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Character ┆ Character ┆ … ┆ Comment[C ┆ Comment[C ┆ Comment[C ┆ Comment[ │
│ Name      ┆ [biosampl ┆ istics    ┆ istics    ┆   ┆ TSS count ┆ TSS count ┆ TSS TPM   ┆ CTSS TPM │
│ ---       ┆ e_id]     ┆ [organism ┆ [sample   ┆   ┆ forward   ┆ reverse   ┆ forward   ┆ reverse  │
│ str       ┆ ---       ┆ ]         ┆ type]     ┆   ┆ fil…      ┆ fil…      ┆ file]     ┆ file]    │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CNhs10722 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 753       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 2.ctss.fw ┆ 2.ctss.re ┆ 0722.ctss ┆ s10722.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10723 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 601       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 3.ctss.fw ┆ 3.ctss.re ┆ 0723.ctss ┆ s10723.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10724 ┆ SAMD00004 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 824       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 4.ctss.fw ┆ 4.ctss.re ┆ 0724.ctss ┆ s10724.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10726 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 224       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 6.ctss.fw ┆ 6.ctss.re ┆ 0726.ctss ┆ s10726.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ CNhs10727 ┆ SAMD00005 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│           ┆ 883       ┆ sapiens   ┆ culture   ┆   ┆ /CNhs1072 ┆ /CNhs1072 ┆ Tpm/CNhs1 ┆ sTpm/CNh │
│           ┆           ┆           ┆           ┆   ┆ 7.ctss.fw ┆ 7.ctss.re ┆ 0727.ctss ┆ s10727.c │
│           ┆           ┆           ┆           ┆   ┆ d.b…      ┆ v.b…      ┆ Tpm…      ┆ tssTpm…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRX111799 ┆ SAMN19775 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 53        ┆ 304       ┆ sapiens   ┆ culture   ┆   ┆ /SRX11179 ┆ /SRX11179 ┆ Tpm/SRX11 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 953.ctss. ┆ 953.ctss. ┆ 179953.ct ┆ 11179953 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX111799 ┆ SAMN19775 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 54        ┆ 303       ┆ sapiens   ┆ culture   ┆   ┆ /SRX11179 ┆ /SRX11179 ┆ Tpm/SRX11 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 954.ctss. ┆ 954.ctss. ┆ 179954.ct ┆ 11179954 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX111799 ┆ SAMN19775 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 55        ┆ 302       ┆ sapiens   ┆ culture   ┆   ┆ /SRX11179 ┆ /SRX11179 ┆ Tpm/SRX11 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 955.ctss. ┆ 955.ctss. ┆ 179955.ct ┆ 11179955 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX111799 ┆ SAMN19775 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 56        ┆ 301       ┆ sapiens   ┆ culture   ┆   ┆ /SRX11179 ┆ /SRX11179 ┆ Tpm/SRX11 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 956.ctss. ┆ 956.ctss. ┆ 179956.ct ┆ 11179956 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
│ SRX111799 ┆ SAMN19775 ┆ Homo      ┆ cell      ┆ … ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/ctss ┆ hg38/cts │
│ 57        ┆ 300       ┆ sapiens   ┆ culture   ┆   ┆ /SRX11179 ┆ /SRX11179 ┆ Tpm/SRX11 ┆ sTpm/SRX │
│           ┆           ┆           ┆           ┆   ┆ 957.ctss. ┆ 957.ctss. ┆ 179957.ct ┆ 11179957 │
│           ┆           ┆           ┆           ┆   ┆ fwd…      ┆ rev…      ┆ ssT…      ┆ .ctssT…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
fantabio_sample_annotation = (
    fantabio_sample_ordered
    .select(
        "Source Name",
        "Comment [biosample_id]",
        "Protocol Name",
        "Characteristics [sample type]",
        "Characteristics [description]",
        pl.col("Term Accession Number_duplicated_0").alias("cell_line_id"),
        pl.col("Term Accession Number").alias("cell_id"),
        pl.col("Term Accession Number_duplicated_2").alias("tissue_id"),
        pl.col("Term Accession Number_duplicated_1").alias("efo_id"),
        pl.col("Characteristics [cell line]").alias("cell_line_name"),
        pl.col("Characteristics [CL term]").alias("cell_name"),
        pl.col("Characteristics [tissue]").alias("tissue_name"),
        pl.col("Characteristics [EFO term]").alias("efo_name"),
    )
    .with_columns(
        pl.col("cell_line_id", "cell_id", "tissue_id", "efo_id")
        .str.strip_chars().replace("", None)
    )
)

display(fantabio_sample_annotation.head(5))

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Protocol  ┆ Character ┆ … ┆ cell_line ┆ cell_name ┆ tissue_na ┆ efo_name │
│ Name      ┆ [biosampl ┆ Name      ┆ istics    ┆   ┆ _name     ┆ ---       ┆ me        ┆ ---      │
│ ---       ┆ e_id]     ┆ ---       ┆ [sample   ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│ str       ┆ ---       ┆ str       ┆ type]     ┆   ┆ str       ┆           ┆ str       ┆          │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CNhs10722 ┆ SAMD00005 ┆ Heliscope ┆ cell      ┆ … ┆ THP-1     ┆ null      ┆ null      ┆ THP-1    │
│           ┆ 753       ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆          │
│ CNhs10723 ┆ SAMD00005 ┆ Heliscope ┆ cell      ┆ … ┆ THP-1     ┆ null      ┆ null      ┆ THP-1    │
│           ┆ 601       ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆          │
│ CNhs10724 ┆ SAMD00004 ┆ Heliscope ┆ cell      ┆ … ┆ THP-1     ┆ null      ┆ null      ┆ THP-1    │
│           ┆ 824       ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆          │
│ CNhs10726 ┆ SAMD00005 ┆ Heliscope ┆ cell      ┆ … ┆ PC-14     ┆ null      ┆ null      ┆ PC-14    │
│           ┆ 224       ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆          │
│ CNhs10727 ┆ SAMD00005 ┆ Heliscope ┆ cell      ┆ … ┆ KU812     ┆ null      ┆ null      ┆ KU812    │
│           ┆ 883       ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
SRX11179953 = fantabio_sample_annotation.filter(
    pl.col("Source Name") == "SRX11179953"
)

display(SRX11179953)

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Source    ┆ Comment   ┆ Protocol  ┆ Character ┆ … ┆ cell_line ┆ cell_name ┆ tissue_na ┆ efo_name │
│ Name      ┆ [biosampl ┆ Name      ┆ istics    ┆   ┆ _name     ┆ ---       ┆ me        ┆ ---      │
│ ---       ┆ e_id]     ┆ ---       ┆ [sample   ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│ str       ┆ ---       ┆ str       ┆ type]     ┆   ┆ str       ┆           ┆ str       ┆          │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRX111799 ┆ SAMN19775 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 53        ┆ 304       ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

### 2. sample を一つの集約群に割り当てる

- ID の優先順位は **Cellosaurus → CL → UBERON → EFO**。
- 例えば細胞株と由来組織の両方が注釈されていても、細胞株の群に一度だけ入れる。

In [14]:
name_only_cell_line = (
    pl.all_horizontal(pl.col("cell_line_id", "cell_id", "tissue_id", "efo_id").is_null())
    & pl.col("cell_line_name").is_not_null()
)

fantabio_sample_assignment = (
    fantabio_sample_annotation
    .with_columns(pl.coalesce(
        "cell_line_id", "cell_id", "tissue_id", "efo_id"
    ).alias("group_id"))

    .with_columns(
        pl
        .when(
            pl.col("cell_line_id").is_not_null()
        ).then(pl.lit("cell_line"))

        .when(
            pl.col("cell_id").is_not_null()
        ).then(pl.lit("cell"))

        .when(
            pl.col("tissue_id").is_not_null()
        ).then(pl.lit("tissue"))

        .when(
            pl.col("efo_id").is_not_null()
        ).then(pl.lit("EFO_only"))

        .when(
            name_only_cell_line
        ).then(pl.lit("cell_line"))

        .otherwise(None).alias("group_type"),
        
        pl
        .when(
            pl.col("cell_line_id").is_not_null()
        ).then(pl.col("cell_line_name"))
        
        .when(
            pl.col("cell_id").is_not_null()
        ).then(pl.col("cell_name"))
        
        .when(
            pl.col("tissue_id").is_not_null()
        ).then(pl.col("tissue_name"))

        .when(
            name_only_cell_line
        ).then(pl.col("cell_line_name"))
    
        .otherwise(
            pl.col("efo_name")
        ).fill_null(pl.col("group_id")).alias("group_name"),
        
        pl.col("Source Name").is_in(fantabio_tpm.columns).alias("in_tpm"),
    )


)

display(fantabio_sample_assignment)

shape: (2_644, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ Source     ┆ Comment    ┆ Protocol  ┆ Character ┆ … ┆ group_id  ┆ group_typ ┆ group_nam ┆ in_tpm │
│ Name       ┆ [biosample ┆ Name      ┆ istics    ┆   ┆ ---       ┆ e         ┆ e         ┆ ---    │
│ ---        ┆ _id]       ┆ ---       ┆ [sample   ┆   ┆ str       ┆ ---       ┆ ---       ┆ bool   │
│ str        ┆ ---        ┆ str       ┆ type]     ┆   ┆           ┆ str       ┆ str       ┆        │
│            ┆ str        ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆        │
│            ┆            ┆           ┆ str       ┆   ┆           ┆           ┆           ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ CNhs10722  ┆ SAMD000057 ┆ Heliscope ┆ cell      ┆ … ┆ CVCL_0006 ┆ cell_line ┆ THP-1     ┆ true   │
│            ┆ 53         ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ CNhs10723  ┆ SAMD000056 ┆ Heliscope ┆ cell      ┆ … ┆ CVCL_0006 ┆ cell_line ┆ THP-1     ┆ true   │
│            ┆ 01         ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ CNhs10724  ┆ SAMD000048 ┆ Heliscope ┆ cell      ┆ … ┆ CVCL_0006 ┆ cell_line ┆ THP-1     ┆ true   │
│            ┆ 24         ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ CNhs10726  ┆ SAMD000052 ┆ Heliscope ┆ cell      ┆ … ┆ CVCL_1640 ┆ cell_line ┆ PC-14     ┆ true   │
│            ┆ 24         ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ CNhs10727  ┆ SAMD000058 ┆ Heliscope ┆ cell      ┆ … ┆ CVCL_0379 ┆ cell_line ┆ KU812     ┆ true   │
│            ┆ 83         ┆ CAGE      ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ true   │
│ 3          ┆ 04         ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ true   │
│ 4          ┆ 03         ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ true   │
│ 5          ┆ 02         ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ true   │
│ 6          ┆ 01         ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆        │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE      ┆ cell      ┆ … ┆ null      ┆ null      ┆ null      ┆ true   │
│ 7          ┆ 00         ┆           ┆ culture   ┆   ┆           ┆           ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

&nbsp;

&nbsp;

&nbsp;

### 3. 対応しないサンプルを表示する

- `group_id`カラムに値がアサインされない行を表示する

In [16]:
fantabio_unassigned_samples = fantabio_sample_assignment.filter(pl.col("group_id").is_null())


pl.Config.set_tbl_rows(250)
pl.Config.set_fmt_str_lengths(200)
print(fantabio_unassigned_samples.select("Characteristics [description]").sort("Characteristics [description]").unique())

pl.Config.set_tbl_rows(2)
display(fantabio_unassigned_samples)

shape: (291, 1)
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Characteristics [description]                                                                    │
│ ---                                                                                              │
│ str                                                                                              │
╞══════════════════════════════════════════════════════════════════════════════════════════════════╡
│ 293SLAM rinderpest infection, 00hr, biol_rep1                                                    │
│ 293SLAM rinderpest infection, 00hr, biol_rep2                                                    │
│ 293SLAM rinderpest infection, 00hr, biol_rep3                                                    │
│ 293SLAM rinderpest infection, 06hr, biol_rep1                                                    │
│ 293SLAM rinderpest infection, 06hr, biol_rep2                                                    │
│ 293SLAM rinderpest infection, 06hr, biol_rep3                                                    │
│ 293SLAM rinderpest infection, 12hr, biol_rep1                                                    │
│ 293SLAM rinderpest infection, 12hr, biol_rep2                                                    │
│ 293SLAM rinderpest infection, 12hr, biol_rep3                                                    │
│ 293SLAM rinderpest infection, 24hr, biol_rep1                                                    │
│ 293SLAM rinderpest infection, 24hr, biol_rep2                                                    │
│ 293SLAM rinderpest infection, 24hr, biol_rep3                                                    │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) #1          │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) #2          │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) #3          │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1538) #1                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1538) #2                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1538) #3                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1539) #1                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1539) #2                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with AR siRNA (s1539) #3                                                                         │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with Control siRNA #1                                                                            │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with Control siRNA #2                                                                            │
│ AILNCaP14 cells (CRPC cell line from LNCaP cells under androgen-deprived conditions) transfected │
│ with Control siRNA #3                                                                            │
│ COBL-a rinderpest infection, 00hr, biol_rep1                                                     │
│ COBL-a rinderpest infection, 00hr, biol_rep2                                                     │
│ COBL-a rinderpest infection, 00hr, biol_rep3                                                     │
│ COBL-a rinderpest infection, 06hr, biol_rep1                                                     │
│ COBL-a rinderpest infection, 06hr, biol_rep2                                                     │
│ COBL-a rinderpest infection, 06hr, biol_rep3                                                     │
│ COBL-a rinderpest infection, 12hr, biol_rep1                                                     │
│ COBL-a rinderpest infection, 12hr, biol_rep2                                                     │
│ COBL-a rinderpest infection, 12hr, biol_rep3                                                     │
│ COBL-a rinderpest infection, 24hr, biol_rep1                                                     │
│ COBL-a rinderpest infection, 24hr, biol_rep2                                                     │
│ COBL-a rinderpest infection, 24hr, biol_rep3                                                     │
│ COBL-a rinderpest infection, 48hr, biol_rep1                                                     │
│ COBL-a rinderpest infection, 48hr, biol_rep2                                                     │
│ COBL-a rinderpest infection, 48hr, biol_rep3                                                     │
│ COBL-a rinderpest(-C) infection, 06hr, biol_rep1                                                 │
│ COBL-a rinderpest(-C) infection, 06hr, biol_rep2                                                 │
│ COBL-a rinderpest(-C) infection, 06hr, biol_rep3                                                 │
│ COBL-a rinderpest(-C) infection, 12hr, biol_rep1                                                 │
│ COBL-a rinderpest(-C) infection, 12hr, biol_rep2                                                 │
│ COBL-a rinderpest(-C) infection, 12hr, biol_rep3                                                 │
│ COBL-a rinderpest(-C) infection, 24hr, biol_rep1                                                 │
│ COBL-a rinderpest(-C) infection, 24hr, biol_rep2                                                 │
│ COBL-a rinderpest(-C) infection, 24hr, biol_rep3                                                 │
│ COBL-a rinderpest(-C) infection, 48hr, biol_rep1                                                 │
│ COBL-a rinderpest(-C) infection, 48hr, biol_rep2                                                 │
│ COBL-a rinderpest(-C) infection, 48hr, biol_rep3                                                 │
│ Clontech Human Universal Reference Total RNA, pool1                                              │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day03, biol_rep1                           │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day03, biol_rep2                           │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day03, biol_rep3                           │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day09, biol_rep1                           │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day09, biol_rep2                           │
│ H1 embryonic stem cells differentiation to CD34+ HSC, day09, biol_rep3                           │
│ H9 Embryoid body cells, melanocytic induction, day00, biol_rep1 (H9EB-1 d0)                      │
│ H9 Embryoid body cells, melanocytic induction, day00, biol_rep2 (H9EB-2 d0)                      │
│ H9 Embryoid body cells, melanocytic induction, day00, biol_rep3 (H9EB-3 d0)                      │
│ H9 Embryoid body cells, melanocytic induction, day01, biol_rep1 (H9EB-1 d1)                      │
│ H9 Embryoid body cells, melanocytic induction, day01, biol_rep2 (H9EB-2 d1)                      │
│ H9 Embryoid body cells, melanocytic induction, day01, biol_rep3 (H9EB-3 d1)                      │
│ H9 Embryoid body cells, melanocytic induction, day03, biol_rep1 (H9EB-1 d3)                      │
│ H9 Embryoid body cells, melanocytic induction, day03, biol_rep2 (H9EB-2 d3)                      │
│ H9 Embryoid body cells, melanocytic induction, day03, biol_rep3 (H9EB-3 d3)                      │
│ H9 Embryoid body cells, melanocytic induction, day06, biol_rep1 (H9EB-1 d6)                      │
│ H9 Embryoid body cells, melanocytic induction, day06, biol_rep2 (H9EB-2 d6)                      │
│ H9 Embryoid body cells, melanocytic induction, day06, biol_rep3 (H9EB-3 d6)                      │
│ H9 Embryoid body cells, melanocytic induction, day09, biol_rep1 (H9EB-1 d9)                      │
│ H9 Embryoid body cells, melanocytic induction, day09, biol_rep2 (H9EB-2 d9)                      │
│ H9 Embryoid body cells, melanocytic induction, day09, biol_rep3 (H9EB-3 d9)                      │
│ H9 Embryoid body cells, melanocytic induction, day12, biol_rep1 (H9EB-1 d12)                     │
│ H9 Embryoid body cells, melanocytic induction, day12, biol_rep2 (H9EB-2 d12)                     │
│ H9 Embryoid body cells, melanocytic induction, day12, biol_rep3 (H9EB-3 d12)                     │
│ H9 Embryoid body cells, melanocytic induction, day15, biol_rep1 (H9EB-1 d15)                     │
│ H9 Embryoid body cells, melanocytic induction, day15, biol_rep2 (H9EB-2 d15)                     │
│ H9 Embryoid body cells, melanocytic induction, day15, biol_rep3 (H9EB-3 d15)                     │
│ H9 Embryoid body cells, melanocytic induction, day18, biol_rep1 (H9EB-1 d18)                     │
│ H9 Embryoid body cells, melanocytic induction, day18, biol_rep2 (H9EB-2 d18)                     │
│ H9 Embryoid body cells, melanocytic induction, day18, biol_rep3 (H9EB-3 d18)                     │
│ H9 Embryoid body cells, melanocytic induction, day21, biol_rep1 (H9EB-1 d21)                     │
│ H9 Embryoid body cells, melanocytic induction, day21, biol_rep2 (H9EB-2 d21)                     │
│ H9 Embryoid body cells, melanocytic induction, day21, biol_rep3 (H9EB-3 d21)                     │
│ H9 Embryoid body cells, melanocytic induction, day24, biol_rep1 (H9EB-1 d24)                     │
│ H9 Embryoid body cells, melanocytic induction, day24, biol_rep2 (H9EB-2 d24)                     │
│ H9 Embryoid body cells, melanocytic induction, day24, biol_rep3 (H9EB-3 d24)                     │
│ H9 Embryoid body cells, melanocytic induction, day27, biol_rep1 (H9EB-1 d27)                     │
│ H9 Embryoid body cells, melanocytic induction, day27, biol_rep2 (H9EB-2 d27)                     │
│ H9 Embryoid body cells, melanocytic induction, day27, biol_rep3 (H9EB-3 d27)                     │
│ H9 Embryoid body cells, melanocytic induction, day30, biol_rep1 (H9EB-1 d30)                     │
│ H9 Embryoid body cells, melanocytic induction, day30, biol_rep2 (H9EB-2 d30)                     │
│ H9 Embryoid body cells, melanocytic induction, day30, biol_rep3 (H9EB-3 d30)                     │
│ H9 Embryoid body cells, melanocytic induction, day34, biol_rep1 (H9EB-1 d34)                     │
│ H9 Embryoid body cells, melanocytic induction, day34, biol_rep2 (H9EB-2 d34)                     │
│ H9 Embryoid body cells, melanocytic induction, day34, biol_rep3 (H9EB-3 d34)                     │
│ H9 Embryoid body cells, melanocytic induction, day41, biol_rep1 (H9EB-1 d41)                     │
│ H9 Embryoid body cells, melanocytic induction, day41, biol_rep2 (H9EB-2 d41)                     │
│ H9 Embryoid body cells, melanocytic induction, day41, biol_rep3 (H9EB-3 d41)                     │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day00, biol_rep1 (UH-1)                 │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day00, biol_rep2 (UH-2)                 │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day00, biol_rep3 (UH-3)                 │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day01, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day01, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day01, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day02, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day02, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day02, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day03, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day03, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day03, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day04, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day04, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day04, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day05, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day05, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day05, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day06, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day06, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day06, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day07, biol_rep1                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day07, biol_rep2                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day07, biol_rep3                        │
│ HES3-GFP Embryonic Stem cells, cardiomyocytic induction, day08, biol_rep1                        │
│ …                                                                                                │
│ chorionic membrane cells, donor2                                                                 │
│ chorionic membrane cells, donor3                                                                 │
│ cord blood derived cell line:COBL-a 24h infection                                                │
│ cord blood derived cell line:COBL-a 24h infection(-C)                                            │
│ cord blood derived cell line:COBL-a untreated                                                    │
│ embryonic kidney cell line: HEK293/SLAM infection, 24hr                                          │
│ embryonic kidney cell line: HEK293/SLAM untreated                                                │
│ hIPS +CCl2, biol_rep1                                                                            │
│ hIPS +CCl2, biol_rep2                                                                            │
│ hIPS +CCl2, biol_rep3                                                                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day06, rep1                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day06, rep2                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day06, rep3                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day12, rep1                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day12, rep2                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day12, rep3                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day18, rep1                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day18, rep2                            │
│ iPS differentiation to neuron, control donor C11-CRL2429, day18, rep3                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day00, rep1                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day00, rep2                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day00, rep3                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day06, rep1                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day06, rep2                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day06, rep3                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day12, rep1                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day12, rep2                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day12, rep3                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day18, rep1                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day18, rep2                            │
│ iPS differentiation to neuron, control donor C32-CRL1502, day18, rep3                            │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day06, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day06, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day06, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day12, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day12, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day12, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day18, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day18, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C11-CCL54, day18, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day00, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day00, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day00, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day06, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day06, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day06, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day12, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day12, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day12, rep3                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day18, rep1                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day18, rep2                        │
│ iPS differentiation to neuron, down-syndrome donor C18-CCL54, day18, rep3                        │
│ induced Nephron progenitor cells(ITGA8+PDGFRa-) from Normal_iPSCs_day14_rep1                     │
│ induced Nephron progenitor cells(ITGA8+PDGFRa-) from Normal_iPSCs_day14_rep2                     │
│ induced Nephron progenitor cells(ITGA8+PDGFRa-) from Normal_iPSCs_day14_rep3                     │
│ induced Nephron progenitor cells(ITGA8+PDGFRa-) from Renal coloboma syndrome (RCS)               │
│ patient-1-derived iPSCs_day14_rep1                                                               │

shape: (293, 17)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬───────────┬───────────┬────────┐
│ Source     ┆ Comment    ┆ Protocol   ┆ Character ┆ … ┆ group_id ┆ group_typ ┆ group_nam ┆ in_tpm │
│ Name       ┆ [biosample ┆ Name       ┆ istics    ┆   ┆ ---      ┆ e         ┆ e         ┆ ---    │
│ ---        ┆ _id]       ┆ ---        ┆ [sample   ┆   ┆ str      ┆ ---       ┆ ---       ┆ bool   │
│ str        ┆ ---        ┆ str        ┆ type]     ┆   ┆          ┆ str       ┆ str       ┆        │
│            ┆ str        ┆            ┆ ---       ┆   ┆          ┆           ┆           ┆        │
│            ┆            ┆            ┆ str       ┆   ┆          ┆           ┆           ┆        │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪════════╡
│ CNhs11045  ┆ SAMD000047 ┆ HeliscopeC ┆ cell      ┆ … ┆ null     ┆ cell_line ┆ COBL-a    ┆ true   │
│            ┆ 51         ┆ AGE        ┆ culture   ┆   ┆          ┆           ┆           ┆        │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …      │
│ SRX1117995 ┆ SAMN197753 ┆ CAGE       ┆ cell      ┆ … ┆ null     ┆ null      ┆ null      ┆ true   │
│ 7          ┆ 00         ┆            ┆ culture   ┆   ┆          ┆           ┆           ┆        │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴───────────┴───────────┴────────┘

&nbsp;

&nbsp;

&nbsp;

### 4. group ID → 対象サンプル column の対応表を作る

- `source_names` は Polars の List 列。THP-1 の `THP1_cell_source_names` に相当するリストを全群について保持する
- `n_samples` はライブラリー数であり、独立な donor 数ではない
- 同じ ID に複数のラベルがある場合も、`group_names` にすべて残す

In [17]:
fantabio_group_metadata = (
    fantabio_sample_assignment
    .filter(pl.col("group_id").is_not_null()) # 一旦グループに割り当てられたサンプルのみを対象にする
    
    .group_by("group_id", maintain_order=True)
    .agg(
        pl.col("group_name").unique(maintain_order=True).alias("group_names"),
        pl.col("group_type").first(),
        pl.col("Source Name").alias("source_names"),
        pl.len().alias("n_samples"),
        pl.col("Protocol Name").unique().sort().alias("protocols"),
        pl.col("Characteristics [sample type]").unique().sort().alias("sample_types"),
    )
    .with_columns(
    (pl.lit("mean_tpm_") + pl.col("group_id")).alias("mean_column"),
    pl.col("protocols").list.len().alias("n_protocols"),
    )

    .sort("n_samples", descending=True)
)


display(fantabio_group_metadata)
print("Group Count:", fantabio_group_metadata.height)

shape: (519, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ group_id  ┆ group_nam ┆ group_typ ┆ source_na ┆ … ┆ protocols ┆ sample_ty ┆ mean_colu ┆ n_protoc │
│ ---       ┆ es        ┆ e         ┆ mes       ┆   ┆ ---       ┆ pes       ┆ mn        ┆ ols      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ ---      │
│           ┆ list[str] ┆ str       ┆ list[str] ┆   ┆           ┆ list[str] ┆ str       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CVCL_0031 ┆ ["MCF-7"] ┆ cell_line ┆ ["CNhs119 ┆ … ┆ ["CAGE",  ┆ ["cell    ┆ mean_tpm_ ┆ 5        │
│           ┆           ┆           ┆ 43", "CNh ┆   ┆ "Heliscop ┆ culture"] ┆ CVCL_0031 ┆          │
│           ┆           ┆           ┆ s12564",  ┆   ┆ eCAGE", … ┆           ┆           ┆          │
│           ┆           ┆           ┆ … "SRX191 ┆   ┆ "nAnT-iCA ┆           ┆           ┆          │
│           ┆           ┆           ┆ 43101"]   ┆   ┆ GE"]      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ UBERON_00 ┆ ["urinary ┆ tissue    ┆ ["CNhs106 ┆ … ┆ ["Helisco ┆ ["tissue  ┆ mean_tpm_ ┆ 1        │
│ 01255     ┆ bladder"] ┆           ┆ 16"]      ┆   ┆ peCAGE"]  ┆ sample"]  ┆ UBERON_00 ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 01255     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Group Count: 519

&nbsp;

&nbsp;

&nbsp;

### 5.  Check TPM Value

- ここだけは、注釈に使う全サンプル・全 CRE を検査する。巨大な値の表を long format に変換するのではなく、サンプルごとの異常値の件数だけを小さい表にす
- `null`・NaN・Inf・負値があれば停止し、ゼロへの置換や無視はしない
- 元の THP-1 平均と同じ結果を検証する対象は、この検査を通る入力である

In [18]:
used_source_names = fantabio_sample_assignment["Source Name"].to_list()

fantabio_tpm_qc = (
    fantabio_tpm.lazy().select(used_source_names)
    .select((pl.all().is_null() | ~pl.all().is_finite() | (pl.all() < 0)).sum())
    .collect()
    .unpivot(variable_name="Source Name", value_name="n_invalid")
)

display(fantabio_tpm_qc.filter(pl.col("n_invalid") > 0))
assert fantabio_tpm_qc["n_invalid"].sum() == 0, "無効な TPM が含まれています。"
assert fantabio_tpm["cre_id"].null_count() == 0
assert fantabio_tpm["cre_id"].n_unique() == fantabio_tpm.height

shape: (0, 2)
┌─────────────┬───────────┐
│ Source Name ┆ n_invalid │
│ ---         ┆ ---       │
│ str         ┆ u32       │
╞═════════════╪═══════════╡
└─────────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 6. 全てのグループの mean TPM を持つ Dataframe を作成する

- THP-1 の `pl.mean_horizontal(source_names)` を、全群について同じように指定する
- 下の `for` は**小さい metadata 表から列の計算式を並べるだけ**で、CRE の数値を Python のループで計算しない
- 元の表の行順が共通なので、群ごとに `join` を繰り返す代わりに、一度の `select` で横に並べられる

In [19]:
fantabio_tpm_mean = fantabio_tpm.lazy().select(
    "cre_id",
    *[
        pl.mean_horizontal(sorted(source_names)).alias(mean_column)
        for mean_column, source_names in fantabio_group_metadata.select(
            "mean_column", "source_names"
        ).iter_rows()
    ],
)

display(fantabio_tpm_mean.head(5).collect())

shape: (5, 520)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id ┆ mean_tpm_C ┆ mean_tpm_U ┆ mean_tpm_ ┆ … ┆ mean_tpm_ ┆ mean_tpm_ ┆ mean_tpm_ ┆ mean_tpm_ │
│ ---    ┆ VCL_0031   ┆ BERON_0000 ┆ CL_000023 ┆   ┆ UBERON_00 ┆ UBERON_00 ┆ UBERON_00 ┆ UBERON_00 │
│ str    ┆ ---        ┆ 948        ┆ 5         ┆   ┆ 00992     ┆ 01043     ┆ 00002     ┆ 01255     │
│        ┆ f64        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│        ┆            ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_1 ┆ 0.900785   ┆ 0.401732   ┆ 0.001687  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_3 ┆ 0.048998   ┆ 0.0        ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

### 7. test で実行した THP-1 の計算との一致を確認する

- 最初に、EFO 名で選んだ元の試料群と、Cellosaurus ID で選んだ群が同じ試料集合か確認する
- 違っていれば、計算ライブラリーではなく**対象試料の違い**なので停止する
- 一致すれば全 CRE の THP-1 平均を元の DataFrame と比較する。入力値や集約順序を変更していないため、ここは完全一致で調査

In [20]:
from polars.testing import assert_frame_equal

thp1_mean_column = fantabio_tpm_thp1.columns[1]

thp1_sources_all = (
    fantabio_group_metadata.filter(pl.col("mean_column") == thp1_mean_column)
    .select("source_names").explode("source_names")["source_names"].to_list()
)
assert sorted(thp1_sources_all) == sorted(THP1_cell_source_names), "THP-1 の対象試料が違います。"

fantabio_thp1_check = fantabio_tpm_mean.select("cre_id", thp1_mean_column).collect(engine="in-memory")


# Horizontal means can differ by about 1e-16 when the Polars plan differs.
assert_frame_equal(
    fantabio_thp1_check,
    fantabio_tpm_thp1,
    abs_tol=1e-8,
    check_exact=False,
)


display(fantabio_thp1_check.head(5))
print("THP-1: 対象試料と全 CRE の平均 TPM が abs_tol=1e-8 で一致しました。")

shape: (5, 2)
┌────────┬────────────────────┐
│ cre_id ┆ mean_tpm_CVCL_0006 │
│ ---    ┆ ---                │
│ str    ┆ f64                │
╞════════╪════════════════════╡
│ FCHS_1 ┆ 0.847295           │
│ …      ┆ …                  │
│ FCHS_3 ┆ 0.0                │
└────────┴────────────────────┘

THP-1: 対象試料と全 CRE の平均 TPM が abs_tol=1e-8 で一致しました。

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 8. 特異性の比較対象を選ぶ

- 既定値は、上で作成した **全種類の annotation 付き biosample 群
- この混合集合での値は、あくまでサンプルレベルでまとめたものであり、純粋な組織特異性 ではないことに注意
- 組織だけの解析にする場合は下のコメント行に置き換える
- その場合、群数と比較対象が変わるためスコアも変わる

In [21]:
specificity_groups = fantabio_group_metadata
# 組織のみを比較する場合:
# specificity_groups = fantabio_group_metadata.filter(
#     pl.col("group_type") == "tissue"
# )

mean_tpm_columns = specificity_groups["mean_column"].to_list()

assert len(mean_tpm_columns) >= 2, "特異性の計算には2群以上が必要です。"

display(
    specificity_groups.select(
        "group_id", "group_names", "group_type", "n_samples"
    )
)

shape: (519, 4)
┌────────────────┬─────────────────────┬────────────┬───────────┐
│ group_id       ┆ group_names         ┆ group_type ┆ n_samples │
│ ---            ┆ ---                 ┆ ---        ┆ ---       │
│ str            ┆ list[str]           ┆ str        ┆ u32       │
╞════════════════╪═════════════════════╪════════════╪═══════════╡
│ CVCL_0031      ┆ ["MCF-7"]           ┆ cell_line  ┆ 256       │
│ …              ┆ …                   ┆ …          ┆ …         │
│ UBERON_0001255 ┆ ["urinary bladder"] ┆ tissue     ┆ 1         │
└────────────────┴─────────────────────┴────────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 9. 各 CRE の group 別平均を、一つの List 列にまとめる

- `group_tpm` は Python のリストへ変換したものではなく、**Polars の List 型の列**
- リストの要素の順番は `specificity_groups` の行順と対応する
- List にすることで、元の巨大な行列を `unpivot` せず、行ごとに entropy を計算する

In [22]:
fantabio_group_values = fantabio_tpm_mean.select(
    "cre_id", pl.concat_list(mean_tpm_columns).alias("group_tpm"),
)

display(fantabio_group_values.head(5).collect())

shape: (5, 2)
┌────────┬─────────────────────────────┐
│ cre_id ┆ group_tpm                   │
│ ---    ┆ ---                         │
│ str    ┆ list[f64]                   │
╞════════╪═════════════════════════════╡
│ FCHS_1 ┆ [0.900785, 0.401732, … 0.0] │
│ …      ┆ …                           │
│ FCHS_3 ┆ [0.048998, 0.0, … 0.0]      │
└────────┴─────────────────────────────┘

In [23]:
fantabio_group_values = fantabio_group_values.with_columns(
    pl.col("group_tpm").list.len().alias("n_groups"),
    pl.col("group_tpm").list.sum().alias("sum_group_tpm"),
    pl.col("group_tpm").list.max().alias("max_group_tpm"),
)

display(fantabio_group_values.head(5).collect())

shape: (5, 5)
┌────────┬─────────────────────────────┬──────────┬───────────────┬───────────────┐
│ cre_id ┆ group_tpm                   ┆ n_groups ┆ sum_group_tpm ┆ max_group_tpm │
│ ---    ┆ ---                         ┆ ---      ┆ ---           ┆ ---           │
│ str    ┆ list[f64]                   ┆ u32      ┆ f64           ┆ f64           │
╞════════╪═════════════════════════════╪══════════╪═══════════════╪═══════════════╡
│ FCHS_1 ┆ [0.900785, 0.401732, … 0.0] ┆ 519      ┆ 12.221825     ┆ 1.092198      │
│ …      ┆ …                           ┆ …        ┆ …             ┆ …             │
│ FCHS_3 ┆ [0.048998, 0.0, … 0.0]      ┆ 519      ┆ 0.481988      ┆ 0.386147      │
└────────┴─────────────────────────────┴──────────┴───────────────┴───────────────┘

&nbsp;

&nbsp;

&nbsp;

### 処理の追加

- 実装の参考にしている [04expressionSpecificity.R](https://github.com/eddieimada/fcr2/blob/master/GTEX/04expressionSpecificity.R) の `entropyFunc` では、グループでの平均が 0.1 TPM 未満なら 0 として扱う処理があるので、これを付け加える
- Rscript では、[entropy.empirical](https://www.rdocumentation.org/packages/entropy/versions/1.3.2/topics/entropy.empirical) が使用されている

In [24]:
fantabio_group_values = (
    fantabio_group_values
    .with_columns(
        pl.col("group_tpm")
        .list.eval(
            pl.when(pl.element() < 0.1)
            .then(0.0)
            .otherwise(pl.element())
        )
        .alias("group_tpm")
    )
    .with_columns(
        pl.col("group_tpm").list.sum().alias("sum_group_tpm")
    )
)

display(fantabio_group_values.head(5).collect())

shape: (5, 5)
┌────────┬─────────────────────────────┬──────────┬───────────────┬───────────────┐
│ cre_id ┆ group_tpm                   ┆ n_groups ┆ sum_group_tpm ┆ max_group_tpm │
│ ---    ┆ ---                         ┆ ---      ┆ ---           ┆ ---           │
│ str    ┆ list[f64]                   ┆ u32      ┆ f64           ┆ f64           │
╞════════╪═════════════════════════════╪══════════╪═══════════════╪═══════════════╡
│ FCHS_1 ┆ [0.900785, 0.401732, … 0.0] ┆ 519      ┆ 11.165756     ┆ 1.092198      │
│ …      ┆ …                           ┆ …        ┆ …             ┆ …             │
│ FCHS_3 ┆ [0.0, 0.0, … 0.0]           ┆ 519      ┆ 0.386147      ┆ 0.386147      │
└────────┴─────────────────────────────┴──────────┴───────────────┴───────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 10. Polars の `Expr.entropy` を使う

- `list.eval` の内側は CRE **一行分**の群別 TPM
- `normalize=True` により群間の比率へ正規化する
- 自然対数の entropy を求める
- `value_counts` やヒストグラムから計算するのではないことに注意！
- 0 は $0\log0=0$ なので entropy の内部では正の要素だけを渡す
- **`n_groups` はゼロの群を含む元の長さのまま** にしておく
- 群平均 TPM が 0.1 未満の値は、entropy 計算前にゼロへ置換する
- 閾値処理後に全群ゼロとなる CRE は、entropy を `null` にする
- ここで使うのは empirical Shannon entropy (底2の empirical Shannon entropy を求める（`base=2.0`）) であり、Chao–Shen 補正ではないことに注意

In [25]:
fantabio_entropy = (
    fantabio_group_values
    .with_columns(
        pl
        .when(pl.col("sum_group_tpm") > 0)
        .then(
        pl.col("group_tpm")
                    .list
                    .eval(pl.element().filter(pl.element() > 0) # ゼロは entropy に含めない
                    .entropy(
                        base=2,
                        normalize=True
                    )).list.first())
        
        .otherwise(None).alias("entropy"),
)
)

display(fantabio_entropy.head(5).collect())

shape: (5, 6)
┌────────┬─────────────────────────────┬──────────┬───────────────┬───────────────┬──────────┐
│ cre_id ┆ group_tpm                   ┆ n_groups ┆ sum_group_tpm ┆ max_group_tpm ┆ entropy  │
│ ---    ┆ ---                         ┆ ---      ┆ ---           ┆ ---           ┆ ---      │
│ str    ┆ list[f64]                   ┆ u32      ┆ f64           ┆ f64           ┆ f64      │
╞════════╪═════════════════════════════╪══════════╪═══════════════╪═══════════════╪══════════╡
│ FCHS_1 ┆ [0.900785, 0.401732, … 0.0] ┆ 519      ┆ 11.165756     ┆ 1.092198      ┆ 4.259368 │
│ …      ┆ …                           ┆ …        ┆ …             ┆ …             ┆ …        │
│ FCHS_3 ┆ [0.0, 0.0, … 0.0]           ┆ 519      ┆ 0.386147      ┆ 0.386147      ┆ 0.0      │
└────────┴─────────────────────────────┴──────────┴───────────────┴───────────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### 11. Expression specificity を計算する

$$S=1-\frac{H}{\ln K}$$

- 群平均 TPM を計算した後、0.1 未満の群平均をゼロへ置換する
- H は、閾値処理後の群平均に基づく empirical Shannon entropy
- K は `n_groups`。閾値処理でゼロになった群も含める
- 閾値処理後、全群で同じ正の値なら S=0、一群のみ正なら S=1
- 閾値処理後に全群ゼロとなる CRE は `null` とする
- pseudo-count の追加や、入力 TPM の log2 変換は行わない
- `clip` は丸め誤差による僅かな範囲外の値を防ぐ

In [26]:
fantabio_specificity = (
    fantabio_entropy
    .with_columns(
        (
            1.0
            - (
                pl.col("entropy")
                / (
                    pl.col("n_groups")
                    .cast(pl.Float64)
                    .log(base=2.0)
                )
            )
        )
        .clip(0.0, 1.0)
        .alias("specificity")
    )
    .drop("group_tpm")
).sort("specificity", descending=True)

display(fantabio_specificity.head(10).collect())

shape: (10, 6)
┌─────────────┬──────────┬───────────────┬───────────────┬─────────┬─────────────┐
│ cre_id      ┆ n_groups ┆ sum_group_tpm ┆ max_group_tpm ┆ entropy ┆ specificity │
│ ---         ┆ ---      ┆ ---           ┆ ---           ┆ ---     ┆ ---         │
│ str         ┆ u32      ┆ f64           ┆ f64           ┆ f64     ┆ f64         │
╞═════════════╪══════════╪═══════════════╪═══════════════╪═════════╪═════════════╡
│ FCHS_290690 ┆ 519      ┆ 0.0           ┆ 0.048227      ┆ null    ┆ null        │
│ …           ┆ …        ┆ …             ┆ …             ┆ …       ┆ …           │
│ FCHS_448642 ┆ 519      ┆ 0.0           ┆ 0.012048      ┆ null    ┆ null        │
└─────────────┴──────────┴───────────────┴───────────────┴─────────┴─────────────┘

&nbsp;

&nbsp;

&nbsp;

### 12. Join CRE  annotation 

- 結果の値を変える操作ではなく、`cre_id` による注釈の追加
- `validate="1:1"` によって重複キーによる行の増加を防ぐ

In [27]:
fantabio_specificity_bed = (
    fantabio_specificity
    .join(
    fantabio_bed_select.lazy(),
    on="cre_id",
    how="left",
    validate="1:1"
    )
).sort("specificity", descending=True)

fantabio_specificity_pla = fantabio_specificity_bed.filter(pl.col("fantabio_cre_class") == "PLA")
fantabio_specificity_ela = fantabio_specificity_bed.filter(pl.col("fantabio_cre_class") == "ELA")

display(fantabio_specificity_bed.head(5).collect())

shape: (5, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ n_groups ┆ sum_group ┆ max_group ┆ … ┆ direction ┆ fantabio_ ┆ itemRgb   ┆ itemRgb_n │
│ ---       ┆ ---      ┆ _tpm      ┆ _tpm      ┆   ┆ ality     ┆ cre_class ┆ ---       ┆ ame       │
│ str       ┆ u32      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ str       ┆           ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_2906 ┆ 519      ┆ 0.0       ┆ 0.048227  ┆ … ┆ -0.857143 ┆ ELA       ┆ 255,202,7 ┆ yellow    │
│ 90        ┆          ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_4481 ┆ 519      ┆ 0.0       ┆ 0.050555  ┆ … ┆ 1.0       ┆ ELA       ┆ 255,202,7 ┆ yellow    │
│ 12        ┆          ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
fantabio_non_specificity_bed= fantabio_specificity_bed.filter(pl.col("specificity").is_null())

display(fantabio_non_specificity_bed.collect())

shape: (1_974, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ n_groups ┆ sum_group ┆ max_group ┆ … ┆ direction ┆ fantabio_ ┆ itemRgb   ┆ itemRgb_n │
│ ---       ┆ ---      ┆ _tpm      ┆ _tpm      ┆   ┆ ality     ┆ cre_class ┆ ---       ┆ ame       │
│ str       ┆ u32      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ str       ┆           ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_4473 ┆ 519      ┆ 0.0       ┆ 0.034096  ┆ … ┆ -1.0      ┆ ELA       ┆ 255,202,7 ┆ yellow    │
│ 14        ┆          ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_500  ┆ 519      ┆ 0.0       ┆ 0.032055  ┆ … ┆ 0.2       ┆ ELA       ┆ 255,202,7 ┆ yellow    │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [29]:
fantabio_specificity_bed_filtered = fantabio_specificity_bed.filter(
    pl.col("specificity").is_not_null()
)

display(fantabio_specificity_bed_filtered.collect())

shape: (511_921, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cre_id    ┆ n_groups ┆ sum_group ┆ max_group ┆ … ┆ direction ┆ fantabio_ ┆ itemRgb   ┆ itemRgb_n │
│ ---       ┆ ---      ┆ _tpm      ┆ _tpm      ┆   ┆ ality     ┆ cre_class ┆ ---       ┆ ame       │
│ str       ┆ u32      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆ f64       ┆ str       ┆           ┆ str       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FCHS_3    ┆ 519      ┆ 0.386147  ┆ 0.386147  ┆ … ┆ -1.0      ┆ ELA       ┆ 255,202,7 ┆ yellow    │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ FCHS_1049 ┆ 519      ┆ 26032.850 ┆ 133.93553 ┆ … ┆ -0.999564 ┆ PLA       ┆ 0,0,204   ┆ blue      │
│ 6         ┆          ┆ 408       ┆ 2         ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
# check
FCHS_354464 = fantabio_specificity_bed_filtered.filter(pl.col("cre_id") == "FCHS_354464")
display(FCHS_354464.collect())

shape: (1, 11)
┌────────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ cre_id     ┆ n_groups ┆ sum_group_ ┆ max_group ┆ … ┆ direction ┆ fantabio_ ┆ itemRgb ┆ itemRgb_n │
│ ---        ┆ ---      ┆ tpm        ┆ _tpm      ┆   ┆ ality     ┆ cre_class ┆ ---     ┆ ame       │
│ str        ┆ u32      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str     ┆ ---       │
│            ┆          ┆ f64        ┆ f64       ┆   ┆ f64       ┆ str       ┆         ┆ str       │
╞════════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ FCHS_35446 ┆ 519      ┆ 145627.935 ┆ 19227.190 ┆ … ┆ 0.95538   ┆ PLA       ┆ 204,0,0 ┆ red       │
│ 4          ┆          ┆ 737        ┆ 798       ┆   ┆           ┆           ┆         ┆           │
└────────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘