# GEO Metadata validated and modified process (Gemini-2.0-flash TRUE & Infered has control TRUE)

- ヒトの熱ストレスに関連するRNA-Seqにおいて、Gemini-2.0-flash の判断と自分の判断の結果、解析に使用するに値するデータのメタデータを整理するnotebook
- 整理する際、なぜこのようなデータフレームの処理をするのかについても記載する
- `geofetch`から取得したデータと`iseq`から取得したデータ
- [../GenAI_validate/geo_metadata_genai_validation_true_control.tsv](../GenAI_validate/geo_metadata_genai_validation_true_control.tsv) に分類されたものについてここに記載する

- 2025-05-05: 全てのFASTQデータをダウンロード
- 2025-05-05: GSE124609のRibo-seqは現在の所除いているが、念の為集めといてもいいかもしれない
- 2025-05-09: 念の為、`library_strategy` が `RNA-seq`のものをconcatenateしておく
- 2025-05-15: 全てのFASTQデータをfastpで処理
- 2025-05-21: GSE124609,GSE32060 のRibo-seqのデータはまだ集めていないので注意
- 2025-06-02: 温度条件を追記
- 2026-02-20: [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)にbulk RNA-seq以外のデータの処理を移動 (`library_strategy` が `RNA-seq`のものも含む)

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_cols(100)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

## 1. GSE253874 (SINGLE) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-04-29
- [Histone H3.3 chaperone HIRA renders stress-responsive genes poised for prospective lethal stresses in acquired tolerance](https://doi.org/10.1111/gtc.13140)
- コントロールとなるデータ (37℃ で処理されたサンプル)が存在するため、今回の解析で使用する
- すべてのデータを使用する

#### sample discription from PEP format csv

- `heat stress treatment (40°C, 2 hours)`
- `control`

In [4]:
GSE253874_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE253874/GSE253874_PEP/GSE253874_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded Total RNA Library Prep Kit").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1111/gtc.13140").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("40 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE253874 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE253874_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE253874_filtered = GSE253874[[s.name for s in GSE253874 if not (s.null_count() == GSE253874.height)]]


GSE253874_combined = GSE253874_PEP.join(
    GSE253874_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left"
).sort(
    [
        "gsm_id"
    ],
    descending=False
)

GSE253874_combined = GSE253874_combined[[s.name for s in GSE253874_combined if not (s.null_count() == GSE253874_combined.height)]]

GSE253874_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE253874_modified_metadata.tsv",
    separator='\t'
)

# display(GSE253874_combined)

In [5]:
defined_pairs_gse253874 = [
    ("SRR27681984", "SRR27681986"), # heat-stress sample vs control sample
    ("SRR27681983", "SRR27681985") # heat-stress sample vs control sample
]

paired_metadata_df_gse253874 = create_paired_metadata(
    combined_df=GSE253874_combined, 
    defined_sample_pairs=defined_pairs_gse253874,
    sample_id_column_name="accession" # default value, but specified to clarify
)


# Guard against None so that write_csv is called only on a DataFrame
if paired_metadata_df_gse253874 is not None:
    paired_metadata_df_gse253874.write_csv(
        "../../Data/metadata/metadata_paired/GSE253874_paired_metadata.tsv",
        separator="\t"
    )
    display(paired_metadata_df_gse253874)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 83)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ map ┆ exp ┆ deg ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ pin ┆ res ┆ _an ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ g   ┆ sio ┆ aly ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ n_e ┆ sis ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sti ┆ --- ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ mat ┆ str ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ WI- ┆ Hom ┆ 960 ┆ tot ┆ 40C ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ WI- ┆ imm ┆ WT  ┆ hea ┆ STA ┆ RSE ┆ edg ┆ UCS ┆ exc ┆ SAM ┆ Tru ┆ htt ┆ 40  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ His ┆ SRA ┆ cDN ┆ 202 ┆ 670 ┆ 116 ┆ ILL ┆ mis ┆ Gen ┆ WI- ┆ SRP ┆ 360 ┆ His ┆ WI- ┆ Ill ┆ Ill ┆ imm ┆ 238 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ WI- ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 276 ┆ 276 ┆ 38- ┆ 38- ┆ 802 ┆ lic ┆ 22  ┆ 15  ┆     ┆     ┆ 38- ┆ o   ┆ 6   ┆ al  ┆ _RN ┆ 111 ┆ hik ┆ to  ┆ hid ┆ to- ┆ to  ┆ -85 ┆ an  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 802 ┆ E   ┆ 253 ┆     ┆ 233 ┆ 38- ┆ ort ┆     ┆ t   ┆ R   ┆ M   ┆ eR  ┆ C   ┆ el  ┆ N39 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 276 ┆ umi ┆ ton ┆ 178 ┆ A   ┆ 4-1 ┆ 528 ┆ 754 ┆ UMI ┆ sin ┆ eri ┆ 38- ┆ 485 ┆ 657 ┆ ton ┆ 38- ┆ umi ┆ umi ┆ ort ┆ 034 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 802 ┆ 802 ┆ al  ┆ sin ┆ 802 ┆ 38- ┆ 802 ┆ 4-1 ┆ NA1 ┆ 202 ┆ 4-1 ┆ 253 │
│ 819 ┆ 819 ┆ hte ┆ hTE ┆ 968 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ hTE ┆ sap ┆     ┆ RNA ┆ A-s ┆ 54  ┆ azu ┆ Uni ┆ a-K ┆ shi ┆     ┆ 01  ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 968 ┆     ┆ 874 ┆     ┆ 492 ┆ hTE ┆ ali ┆     ┆ str ┆ v2. ┆ v1. ┆     ┆ hg1 ┆ fil ┆ 538 ┆ Str ┆ //d ┆     ┆ .   ┆     ┆ 819 ┆ na  ┆ e   ┆ 973 ┆     ┆ 0-1 ┆ 655 ┆ 458 ┆ NA  ┆ g   ┆ c   ┆ hTE ┆ 229 ┆ 78  ┆ e   ┆ hTE ┆ na  ┆ na  ┆ ali ┆ 134 ┆ q   ┆ RIP ┆     ┆     ┆ 968 ┆ 968 ┆ RNA ┆ g   ┆ 968 ┆ hTE ┆ 968 ┆ 0-1 ┆ 067 ┆ 106 ┆ 0-1 ┆ 874 │
│ 84  ┆ 86  ┆ rt_ ┆ RT, ┆ 8   ┆ Oct ┆ 4   ┆ 4   ┆     ┆     ┆ RT  ┆ ien ┆     ┆     ┆ eq_ ┆     ┆ ,,N ┆ ver ┆ ono ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 8   ┆     ┆     ┆     ┆ 32  ┆ RT  ┆ zed ┆     ┆ ess ┆ 7.0 ┆ 3.1 ┆     ┆ 9   ┆ e   ┆ 492 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 84  ┆ HiS ┆ H3. ┆ 6   ┆     ┆ 6   ┆ vs  ┆ 4   ┆     ┆     ┆     ┆ RT, ┆     ┆ vs  ┆ H3. ┆ RT, ┆ HiS ┆ HiS ┆ zed ┆ 8   ┆     ┆ TOM ┆     ┆     ┆ 8   ┆ 8_r ┆ was ┆     ┆ 8_r ┆ RT  ┆ 8   ┆ 6   ┆ 599 ┆ 16  ┆ 6   ┆     │
│     ┆     ┆ 40° ┆ 40° ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ rep ┆     ┆ aga ┆ sit ┆ e-c ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ hum ┆     ┆ tre ┆ d   ┆     ┆     ┆     ┆ inc ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ eq  ┆ 3   ┆     ┆     ┆     ┆ 759 ┆ vs  ┆     ┆     ┆     ┆ 40° ┆     ┆ 409 ┆ 3   ┆ 40° ┆ eq  ┆ eq  ┆ hum ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ c_r ┆ C,  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆ gak ┆ y   ┆ ho, ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ an  ┆     ┆ atm ┆     ┆     ┆     ┆     ┆ lud ┆ SAM ┆ Tot ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ 200 ┆ cha ┆     ┆     ┆     ┆ 706 ┆ 132 ┆     ┆     ┆     ┆ C,  ┆     ┆ 456 ┆ cha ┆ C,  ┆ 200 ┆ 200 ┆ an  ┆ 270 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ na- ┆ RNA ┆ 802 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 201 ┆     ┆ i   ┆     ┆ Sak ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 802 ┆     ┆     ┆     ┆ 233 ┆     ┆ fib ┆     ┆ ent ┆     ┆     ┆     ┆     ┆ es  ┆ N39 ┆ al  ┆ .11 ┆     ┆     ┆     ┆ 276 ┆ 0   ┆ per ┆     ┆     ┆     ┆ 171 ┆ 719 ┆     ┆     ┆     ┆ RNA ┆     ┆ 48  ┆ per ┆ RNA ┆ 0   ┆ 0   ┆ fib ┆ 241 ┆     ┆     ┆     ┆     ┆ 802 ┆ GSM ┆ ted ┆     ┆ GSM ┆     ┆ 802 ┆     ┆     ┆ 202 ┆     ┆     │
│     ┆     ┆ seq ┆ -se ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_0 ┆     ┆     ┆     ┆ yo- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆     ┆ 492 ┆     ┆ rob ┆     ┆ (40 ┆     ┆     ┆     ┆     ┆ CPM ┆ 538 ┆ RNA ┆ 11/ ┆     ┆     ┆     ┆ 819 ┆ seq ┆ one ┆     ┆     ┆     ┆     ┆ 705 ┆     ┆     ┆     ┆ -se ┆     ┆     ┆ one ┆ -se ┆     ┆ seq ┆ rob ┆ 276 ┆     ┆     ┆     ┆     ┆ 968 ┆ 802 ┆ usi ┆     ┆ 802 ┆     ┆ 968 ┆     ┆     ┆ 106 ┆     ┆     │
│     ┆     ┆ _re ┆ q,  ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 05A ┆     ┆     ┆     ┆ ku  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 30  ┆     ┆ las ┆     ┆ °C, ┆     ┆     ┆     ┆     ┆ val ┆ 494 ┆ Lib ┆ gtc ┆     ┆     ┆     ┆ 86  ┆ uen ┆ HIR ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ q,  ┆     ┆     ┆ HIR ┆ q,  ┆     ┆ uen ┆ las ┆ 8   ┆     ┆     ┆     ┆     ┆ 6   ┆ 968 ┆ ng  ┆     ┆ 968 ┆     ┆ 6   ┆     ┆     ┆ 14  ┆     ┆     │
│     ┆     ┆ p1  ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _40 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆ ues ┆     ┆ rar ┆ .13 ┆     ┆     ┆     ┆     ┆ cin ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ A   ┆ rep ┆     ┆ cin ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6_r ┆ Qia ┆     ┆ 6_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ hou ┆     ┆     ┆     ┆     ┆ for ┆     ┆ y   ┆ 140 ┆     ┆     ┆     ┆     ┆ g:  ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ is  ┆ 1   ┆     ┆ g:  ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ gen ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ wi- ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ rs) ┆     ┆     ┆     ┆     ┆ eac ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ req ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ req ┆ vs  ┆     ┆ GSM ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 38- ┆ WI- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ 802 ┆ uir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WI- ┆     ┆     ┆ uir ┆ WI- ┆     ┆ 802 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hte ┆ 38- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆ sam ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 38- ┆     ┆     ┆ ed  ┆ 38- ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rt_ ┆ hTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8:  ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hTE ┆     ┆     ┆ for ┆ hTE ┆     ┆ 8:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 37° ┆ RT, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WI- ┆ acq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RT, ┆     ┆     ┆ acq ┆ RT, ┆     ┆ WI- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c_r ┆ 37° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 38- ┆ uir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆ uir ┆ 37° ┆     ┆ 38- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ na- ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hTE ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C,  ┆     ┆     ┆ ed  ┆ C,  ┆     ┆ hTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RT, ┆ tol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ tol ┆ RNA ┆     ┆ RT, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 40° ┆ era ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆ era ┆ -se ┆     ┆ 40° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ufa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆ q,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C,  ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q,  ┆     ┆     ┆ nce ┆ q,  ┆     ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ by  ┆ rep ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. GSE235351 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-04-29
- [Mechanical confinement promotes heat resistance of hepatocellular carcinoma via SP1/IL4I1/AHR axis](https://doi.org/10.1016/j.xcrm.2023.101128)
- keyword: `Thermal ablation`
- 熱処理の時間はおそらく15分だが、はっきりとした温度 (決められた温度帯か？) がわからなかったのでメールしてみた 
- おそらくgradient に温度を変化させていると思われる
- しかしながら、コントロールっぽいものと熱ストレス曝露条件のデータは見られるので念の為収集
- `M3D_Ctrl_{数字}_RNA_seq` と `M3D_heat_{数字}_RNA_seq` のサンプルを収集

In [6]:
regex_pattern_gse235351 = r'^m3d_(ctrl|heat)_\d+_rna_seq$' # Remove double quotes from the pattern

GSE235351_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE235351/GSE235351_PEP/GSE235351_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (Lianchuan Biotechnology Co., Ltd)
    pl.lit("https://doi.org/10.1016/j.xcrm.2023.101128").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("37~53 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("15 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
).filter(
    # Filter using the regex pattern without quotes
    pl.col("sample_name").str.contains(regex_pattern_gse235351) 
)

# metadata from iseq
GSE235351 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE235351_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE235351_filtered = GSE235351[[s.name for s in GSE235351 if not (s.null_count() == GSE235351.height)]]

GSE235351_combined = GSE235351_PEP.join(
    GSE235351_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE235351_combined = GSE235351_combined[[s.name for s in GSE235351_combined if not (s.null_count() == GSE235351_combined.height)]]

GSE235351_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE235351_modified_metadata.tsv",
    separator='\t'
)

# display(GSE235351_combined)

In [7]:
# Manual defined pairs
defined_pairs_gse235351 = [
    ("SRR24973772", "SRR24973776"), # heat-stress sample vs control sample
    ("SRR24973774", "SRR24973775"), # heat-stress sample vs control sample
    ("SRR24973771", "SRR24973773") # heat-stress sample vs control sample
]

paired_metadata_df_gse235351 = create_paired_metadata(
    combined_df=GSE235351_combined, 
    defined_sample_pairs=defined_pairs_gse235351,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse235351 is not None:
    paired_metadata_df_gse235351.write_csv(
        "../../Data/metadata/metadata_paired/GSE235351_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse235351)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ bio ┆ tre ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ log ┆ atm ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ ica ┆ ent ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ l_r ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ epl ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ ica ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ tes ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ g   ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ m3d ┆ M3D ┆ GSM ┆ Pub ┆ Jun ┆ Jun ┆ SRA ┆ 1   ┆ Hep ┆ Hom ┆ 960 ┆ tot ┆ HIS ┆ GPL ┆ Guo ┆ zha ┆ Sun ┆ 58  ┆ Gua ┆ 510 ┆ Chi ┆ MGI ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Hep ┆ MHC ┆ Hep ┆ bio ┆ MHC ┆ hg1 ┆ tex ┆ SAM ┆ unk ┆ htt ┆ 37~ ┆ 15  ┆ 37  ┆ SRR ┆ MGI ┆ Mec ┆ SRA ┆ cDN ┆ 202 ┆ 653 ┆ 582 ┆ BGI ┆ mis ┆ Gen ┆ M3D ┆ SRP ┆ 237 ┆ Mec ┆ M3D ┆ MGI ┆ MGI ┆ Hep ┆ 118 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ mis ┆ GSM ┆ MHC ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ Hep │
│ 249 ┆ 249 ┆ _he ┆ _He ┆ 750 ┆ lic ┆ 20  ┆ 25  ┆     ┆     ┆ ato ┆ o   ┆ 6   ┆ al  ┆ AT2 ┆ 302 ┆ pei ┆ ngg ┆ Yat ┆ Zho ┆ ngz ┆ 080 ┆ na  ┆ SEQ ┆ A   ┆ nsc ┆ -Se ┆ 750 ┆ E   ┆ 235 ┆     ┆ 207 ┆ ato ┆ C-9 ┆ ato ┆ log ┆ C-9 ┆ 9   ┆ t   ┆ N35 ┆ now ┆ ps: ┆ 53  ┆ min ┆ C   ┆ 249 ┆ SEQ ┆ han ┆ 165 ┆ A   ┆ 3-0 ┆ 569 ┆ 748 ┆ SEQ ┆ sin ┆ eri ┆ _He ┆ 444 ┆ 051 ┆ han ┆ _He ┆ SEQ ┆ SEQ ┆ ato ┆ 525 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 750 ┆ 750 ┆ of  ┆ sin ┆ 750 ┆ C-9 ┆ 750 ┆ 3-0 ┆ NA9 ┆ 180 ┆ 3-0 ┆ 235 ┆ ato │
│ 737 ┆ 737 ┆ at_ ┆ at_ ┆ 088 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆     ┆ 09  ┆ ,,Z ┆ p6@ ┆ -se ┆ ngs ┆ hou ┆     ┆     ┆ -20 ┆     ┆ rip ┆ q   ┆ 088 ┆     ┆ 351 ┆     ┆ 314 ┆ cel ┆ 7H  ┆ cel ┆ ica ┆ 7H  ┆     ┆ fil ┆ 809 ┆ n   ┆ //d ┆ C   ┆ .   ┆ (in ┆ 737 ┆ -20 ┆ ica ┆ 894 ┆     ┆ 6-2 ┆ 416 ┆ 331 ┆     ┆ g   ┆ c   ┆ at_ ┆ 919 ┆ 24  ┆ ica ┆ at_ ┆ -20 ┆ -20 ┆ cel ┆ 620 ┆ q   ┆ RIP ┆     ┆     ┆ 088 ┆ 088 ┆ the ┆ g   ┆ 088 ┆ 7H  ┆ 088 ┆ 6-2 ┆ 857 ┆ 223 ┆ 6-2 ┆ 351 ┆ cel │
│ 72  ┆ 76  ┆ 1_r ┆ 1_R ┆ 1   ┆ Jun ┆ 3   ┆ 3   ┆     ┆     ┆ lul ┆ ien ┆     ┆     ┆     ┆     ┆ han ┆ mai ┆ n   ┆ han ┆     ┆     ┆     ┆ 00R ┆     ┆ tom ┆     ┆ 1   ┆     ┆     ┆     ┆ 24  ┆ lul ┆     ┆ lul ┆ l   ┆ in  ┆     ┆ e   ┆ 839 ┆     ┆ oi. ┆     ┆     ┆ fer ┆ 72  ┆ 00R ┆ l   ┆ 6   ┆     ┆ 7   ┆ vs  ┆ vs  ┆     ┆     ┆     ┆ 1_R ┆     ┆ vs  ┆ l   ┆ 1_R ┆ 00R ┆ 00R ┆ lul ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ 2D, ┆     ┆ 1_r ┆     ┆ 1   ┆ 7   ┆ 30  ┆ 62  ┆ 7   ┆     ┆ lul │
│     ┆     ┆ na_ ┆ NA_ ┆ vs  ┆ 25  ┆     ┆     ┆     ┆     ┆ ar  ┆ s   ┆     ┆     ┆     ┆     ┆ g   ┆ l2. ┆ Uni ┆ Roa ┆     ┆     ┆     ┆ S   ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ ar  ┆     ┆ ar  ┆ rep ┆ the ┆     ┆ inc ┆ vs  ┆     ┆ org ┆     ┆     ┆ red ┆ vs  ┆ S   ┆ Con ┆     ┆     ┆     ┆ 648 ┆ 588 ┆     ┆     ┆     ┆ NA_ ┆     ┆ 238 ┆ Con ┆ NA_ ┆ S   ┆ S   ┆ ar  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ 3D, ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆ ar  │
│     ┆     ┆ seq ┆ seq ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆     ┆     ┆     ┆     ┆ sys ┆ ver ┆ d 2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ car ┆     ┆ Car ┆ lic ┆ 3D  ┆     ┆ lud ┆ SAM ┆     ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ seq ┆ fin ┆     ┆     ┆     ┆ 134 ┆ 809 ┆     ┆     ┆     ┆ seq ┆     ┆ 329 ┆ fin ┆ seq ┆     ┆ seq ┆ Car ┆ 119 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ and ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆ car │
│     ┆     ┆ vs  ┆ vs  ┆ 750 ┆ 3   ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ u.e ┆ sit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 750 ┆     ┆     ┆     ┆ 207 ┆ cin ┆     ┆ cin ┆ ate ┆ mod ┆     ┆ es  ┆ N35 ┆     ┆ .10 ┆     ┆     ┆     ┆ 249 ┆ uen ┆ eme ┆     ┆     ┆     ┆ 640 ┆ 244 ┆     ┆     ┆     ┆ vs  ┆     ┆ 19  ┆ eme ┆ vs  ┆     ┆ uen ┆ cin ┆ 164 ┆     ┆     ┆     ┆     ┆ 750 ┆ GSM ┆ ani ┆     ┆ GSM ┆     ┆ 750 ┆     ┆     ┆ 180 ┆     ┆     ┆ cin │
│     ┆     ┆ m3d ┆ M3D ┆ 087 ┆     ┆     ┆     ┆     ┆     ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆ du. ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 087 ┆     ┆     ┆     ┆ 314 ┆ oma ┆     ┆ oma ┆ _1  ┆ el- ┆     ┆ raw ┆ 809 ┆     ┆ 16/ ┆     ┆     ┆     ┆ 737 ┆ cin ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M3D ┆     ┆     ┆ nt  ┆ M3D ┆     ┆ cin ┆ oma ┆ 595 ┆     ┆     ┆     ┆     ┆ 087 ┆ 750 ┆ mal ┆     ┆ 750 ┆     ┆ 087 ┆     ┆     ┆ 223 ┆     ┆     ┆ oma │
│     ┆     ┆ _ct ┆ _Ct ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cn  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 21  ┆     ┆     ┆ Cel ┆     ┆ hea ┆     ┆ cou ┆ 842 ┆     ┆ j.x ┆     ┆     ┆     ┆ 76  ┆ g:  ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ct ┆     ┆     ┆ Pro ┆ _Ct ┆     ┆ g:  ┆ Cel ┆ 0   ┆     ┆     ┆     ┆     ┆ 8   ┆ 087 ┆ mod ┆     ┆ 087 ┆     ┆ 8   ┆     ┆     ┆ 60  ┆     ┆     ┆     │
│     ┆     ┆ rl_ ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ t   ┆     ┆ nts ┆     ┆     ┆ crm ┆     ┆     ┆     ┆     ┆ GSM ┆ mot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rl_ ┆     ┆     ┆ mot ┆ rl_ ┆     ┆ GSM ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8_r ┆ els ┆     ┆ 8_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_r ┆ 1_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆ tre ┆     ┆ for ┆     ┆     ┆ .20 ┆     ┆     ┆     ┆     ┆ 750 ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_R ┆     ┆     ┆ es  ┆ 1_R ┆     ┆ 750 ┆ Lin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ wer ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ na_ ┆ NA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ atm ┆     ┆ eac ┆     ┆     ┆ 23. ┆     ┆     ┆     ┆     ┆ 088 ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA_ ┆     ┆     ┆ Hea ┆ NA_ ┆     ┆ 088 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆ h   ┆     ┆     ┆ 101 ┆     ┆     ┆     ┆     ┆ 1:  ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆ t   ┆ seq ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ Sam ┆     ┆     ┆ 128 ┆     ┆     ┆     ┆     ┆ M3D ┆ Res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Res ┆     ┆     ┆ M3D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MHC ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _He ┆ ist ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ist ┆     ┆     ┆ _He ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-9 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆ anc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ anc ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7H  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_R ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 1_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA_ ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆ NA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆ Hep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hep ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3D  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ ato ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ato ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mod ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ el- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ lul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lul ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ ar  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ar  ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (74 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE165367 (SINGLE) 4sU-seq 

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (4sU-RNA標識法)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE165364 (SINGLE) TTchem-seq 

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (TTchem-seq)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- しかしながら、nacsent RNA のバイアスを考慮できているかが気になるので後でまた使用するかどうか検討する
- [Using TTchem-seq for profiling nascent transcription and measuring transcript elongation](https://doi.org/10.1038/s41596-019-0262-3) などの論文を見ると、STARのマッピングなどを使用しているため、おそらく発現定量の方法はRNA-seqと同じ？
- 120分の実験を行ったあと、追加で30,60,120min.の実験をしている
- 異なるペアで熱ストレスの条件が異なるので後で手入力
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE165366 (SINGLE) FP-TTchem-seq 

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (FP:Flavopiridol.TTchem-seq)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- しかしながら、nacsent RNA のバイアスを考慮できているかがきになるので後でまた使用するかどうか検討する
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE210563 (SINGLE) NO DOWNLOAD

- validate date 2025-04-29
- 熱ショックを加えているサンプルがヒトではなくマウスのMEFなのでこれは使用しない

#### sample discription from PEP format csv

- `MEF_heatshock-_GLORI+_rep1`
- `MEF_heatshock-_GLORI-,`
- ...

In [8]:
# GSE210563_PEP = pl.read_csv(
#     "../Data/metadata/metadata_geofetch/GSE210563/GSE210563_PEP/GSE210563_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_name").str.contains(r'heatshock')
# )

# # display(GSE210563_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. GSE124609 (SINGLE) RNA-seq

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-04-29
- [Cellular proteostasis decline in human senescence](https://doi.org/10.1073/pnas.2018138117)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- Ribo-seqのデータの処理を[./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

#### sample discription from PEP format csv

- `Young1_RNA_Seq`
- `Young_HS1_RNA_Seq`
- ...

In [9]:
GSE124609_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE124609/GSE124609_PEP/GSE124609_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina kit (TruSeq RNA)").alias("rna_library"), # add rna_library column (Illumina: from Article)
    pl.lit("https://doi.org/10.1073/pnas.2018138117").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("44 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# rna-seq
GSE124609_PEP_rna_seq = GSE124609_PEP.filter(
    pl.col("sample_name").str.contains(r'rna_seq')
)


# metadata from iseq
GSE124609 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE124609_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE124609_filtered = GSE124609[[s.name for s in GSE124609 if not (s.null_count() == GSE124609.height)]]

GSE124609_rna_seq_combined = GSE124609_PEP_rna_seq.join(
    GSE124609_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE124609_rna_seq_combined = GSE124609_rna_seq_combined[[s.name for s in GSE124609_rna_seq_combined if not (s.null_count() == GSE124609_rna_seq_combined.height)]]

GSE124609_rna_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE124609_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE124609_rna_seq_combined)

In [10]:
# Manual defined pairs
defined_pairs_gse124609_rna_seq = [
    ("SRR8392699", "SRR8392697"),
    ("SRR8392700", "SRR8392698"),
    ("SRR8392703", "SRR8392701"),
    ("SRR8392704", "SRR8392702")
]

paired_metadata_df_gse124609_rna_seq = create_paired_metadata(
    combined_df=GSE124609_rna_seq_combined, 
    defined_sample_pairs=defined_pairs_gse124609_rna_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse124609_rna_seq is not None:
    paired_metadata_df_gse124609_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE124609_paired_rna_seq_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse124609_rna_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ pas ┆ phe ┆ tre ┆ rep ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ sag ┆ not ┆ atm ┆ lic ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ e   ┆ ype ┆ ent ┆ ate ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ you ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ You ┆ GSM ┆ Pub ┆ Jan ┆ Dec ┆ SRA ┆ 1   ┆ WI3 ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Reu ┆ reu ┆ Fac ┆ Tec ┆ 1   ┆ Hai ┆ 310 ┆ Isr ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ WI3 ┆ hum ┆ 24  ┆ you ┆ Hea ┆ 1   ┆ hg1 ┆ Sam ┆ SAM ┆ Ill ┆ htt ┆ 44  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ Cel ┆ SRA ┆ cDN ┆ 202 ┆ 668 ┆ 111 ┆ ILL ┆ Gen ┆ You ┆ SRP ┆ 395 ┆ Cel ┆ You ┆ Ill ┆ Ill ┆ hum ┆ 201 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ WI3 ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 839 ┆ 839 ┆ ng_ ┆ A   ┆ o   ┆ GLE ┆     ┆ 839 ┆ 520 ┆ ng_ ┆ 353 ┆ lic ┆ 03  ┆ 09  ┆     ┆     ┆ 8   ┆ o   ┆ 6   ┆ al  ┆ 111 ┆ t,, ┆ tsh ┆ ult ┆ hni ┆ Efr ┆ fa  ┆ 96  ┆ ael ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 353 ┆ E   ┆ 124 ┆     ┆ 520 ┆ 8   ┆ an  ┆     ┆ ng  ┆ t   ┆     ┆ 9   ┆ ple ┆ N10 ┆ umi ┆ ps: ┆ C   ┆ min ┆ C   ┆ 839 ┆ umi ┆ lul ┆ 830 ┆ A   ┆ 1-0 ┆ 114 ┆ 231 ┆ UMI ┆ eri ┆ ng_ ┆ 175 ┆ 780 ┆ lul ┆ ng_ ┆ umi ┆ umi ┆ an  ┆ 847 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 353 ┆ 353 ┆ -Se ┆ 353 ┆     ┆ 8   ┆ 1-0 ┆ NA5 ┆ 420 ┆ 1-0 ┆ 124 │
│ 269 ┆ 269 ┆ hs1 ┆     ┆ sap ┆     ┆     ┆ 269 ┆ 241 ┆ HS1 ┆ 758 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆ 54  ┆ Sha ┆ alg ┆ y   ┆ on  ┆ on  ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 758 ┆     ┆ 609 ┆     ┆ 241 ┆     ┆ lun ┆     ┆     ┆ sho ┆     ┆     ┆ s   ┆ 689 ┆ na  ┆ //d ┆     ┆ .   ┆ (in ┆ 269 ┆ na  ┆ ar  ┆ 119 ┆     ┆ 1-0 ┆ 167 ┆ 139 ┆ NA  ┆ c   ┆ HS1 ┆ 158 ┆ 11  ┆ ar  ┆ HS1 ┆ na  ┆ na  ┆ lun ┆ 856 ┆ q   ┆ RIP ┆     ┆     ┆ 758 ┆ 758 ┆ q   ┆ 758 ┆     ┆     ┆ 1-0 ┆ 128 ┆ 756 ┆ 1-0 ┆ 609 │
│ 9   ┆ 7   ┆ _rn ┆     ┆ ien ┆     ┆     ┆ 9   ┆ 0   ┆ _RN ┆ 4   ┆ Dec ┆ 9   ┆ 0   ┆     ┆     ┆ ls  ┆ ien ┆     ┆     ┆     ┆ lgi ┆ i@t ┆ of  ┆     ┆ st. ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 4   ┆     ┆     ┆     ┆ 0   ┆     ┆ g   ┆     ┆     ┆ ck  ┆     ┆     ┆ rea ┆ 181 ┆ kit ┆ oi. ┆     ┆     ┆ fer ┆ 9   ┆ HiS ┆ pro ┆     ┆     ┆ 4   ┆ vs  ┆ 7   ┆     ┆     ┆ _RN ┆     ┆ vs  ┆ pro ┆ _RN ┆ HiS ┆ HiS ┆ g   ┆ 1   ┆     ┆ TOM ┆     ┆     ┆ 4   ┆ 4_r ┆ lib ┆ 4   ┆     ┆     ┆ 4   ┆ 37  ┆ 1   ┆ 4   ┆     │
│     ┆     ┆ a_s ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ A_S ┆ vs  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ ech ┆ Med ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ fib ┆     ┆     ┆ vs  ┆     ┆     ┆ d   ┆ vs  ┆ (Tr ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ teo ┆     ┆     ┆     ┆ 709 ┆ vs  ┆     ┆     ┆ A_S ┆     ┆ 419 ┆ teo ┆ A_S ┆ eq  ┆ eq  ┆ fib ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ rar ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ eq  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nio ┆ ici ┆     ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ rob ┆     ┆     ┆ Con ┆     ┆     ┆ cou ┆ SAM ┆ uSe ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 200 ┆ sta ┆     ┆     ┆     ┆ 782 ┆ 118 ┆     ┆     ┆ eq  ┆     ┆ 687 ┆ sta ┆ eq  ┆ 200 ┆ 200 ┆ rob ┆ 214 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ ies ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 839 ┆ 520 ┆ vs  ┆ 353 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n.a ┆ ne  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 353 ┆     ┆     ┆     ┆ 520 ┆     ┆ las ┆     ┆     ┆ tro ┆     ┆     ┆ nts ┆ N10 ┆ q   ┆ .10 ┆     ┆     ┆     ┆ 839 ┆ 0   ┆ sis ┆     ┆     ┆     ┆ 808 ┆ 168 ┆     ┆     ┆ vs  ┆     ┆ 49  ┆ sis ┆ vs  ┆ 0   ┆ 0   ┆ las ┆ 040 ┆     ┆     ┆     ┆     ┆ 353 ┆ GSM ┆ :   ┆ 353 ┆     ┆     ┆     ┆     ┆ 420 ┆     ┆     │
│     ┆     ┆ you ┆     ┆     ┆     ┆     ┆ 269 ┆ 240 ┆ You ┆ 758 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c.i ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 758 ┆     ┆     ┆     ┆ 240 ┆     ┆ ts  ┆     ┆     ┆ l   ┆     ┆     ┆ and ┆ 689 ┆ RNA ┆ 73/ ┆     ┆     ┆     ┆ 269 ┆ seq ┆ col ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆ You ┆     ┆     ┆ col ┆ You ┆     ┆ seq ┆ ts  ┆ 619 ┆     ┆     ┆     ┆     ┆ 758 ┆ 353 ┆ RNA ┆ 758 ┆     ┆     ┆     ┆     ┆ 755 ┆     ┆     │
│     ┆     ┆ ng1 ┆     ┆     ┆     ┆     ┆ 7   ┆ 8   ┆ ng1 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TPM ┆ 183 ┆ )   ┆ pna ┆     ┆     ┆     ┆ 7   ┆ uen ┆ lap ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ng1 ┆     ┆     ┆ lap ┆ ng1 ┆     ┆ uen ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ 2   ┆ 758 ┆ was ┆ 2   ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     │
│     ┆     ┆ _rn ┆     ┆     ┆     ┆     ┆     ┆     ┆ _RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ val ┆     ┆     ┆ s.2 ┆     ┆     ┆     ┆     ┆ cin ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _RN ┆     ┆     ┆ se  ┆ _RN ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ a_s ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ues ┆     ┆     ┆ 018 ┆     ┆     ┆     ┆     ┆ g:  ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_S ┆     ┆     ┆ in  ┆ A_S ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆ GSM ┆ mam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆ mam ┆ eq  ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 117 ┆     ┆     ┆     ┆     ┆ 353 ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆ 353 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 758 ┆ ian ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ian ┆     ┆     ┆ 758 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆ sen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sen ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ You ┆ esc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ esc ┆     ┆     ┆ You ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng_ ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ enc ┆     ┆     ┆ ng_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS1 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ HS1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE140053 (SINGLE) SLAM-seq

- validation date: 2025-04-29
- [Stress-induced nuclear condensation of NELF drives transcriptional downregulation](https://doi.org/10.1016/j.molcel.2021.01.016)
- これも以前の研究で使用したデータ (SLAM-seq)
- 定量できるかわからないが、これも集めよう...
- ChiP-seqのデータは取り除く ([./12_8_metadata_chipseq.ipynb](./12_8_metadata_chipseq.ipynb)に処理を移動)
- `hs_nelfa_didr_rep3` のデータがないので、ペアとなる`nhs_nelfa_wt_rep3` は今回は使用しない
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. GSE115973 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-04-29
- [Heat Shock Factor 2 Protects against Proteotoxicity by Maintaining Cell-Cell Adhesion](https://doi.org/10.1016/j.celrep.2019.12.037)
- これも以前の研究で使用したデータ
- heat shock 以外の処理も含まれているため、これらを取り除く
- HSF1,2 KO データ含む
- GEOのIDに対して、srrのIDが複数 (`srr`カラムが `multi`) なので対応するように気をつける

In [11]:
GSE115973_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE115973/GSE115973_PEP/GSE115973_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("treatment").str.contains(r'Bortezomib')) & # remove only Bortezomib treatment data
    ((pl.col("treatment").str.contains(r'control')) |
    (pl.col("treatment").str.contains(r'heat shock')))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina TruSeq Stranded mRNA Sample Preparation Guide").alias("rna_library"), # add rna_library column (Lexogen)
    pl.lit("https://doi.org/10.1016/j.celrep.2019.12.037").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE115973 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE115973_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE115973_filtered = GSE115973[[s.name for s in GSE115973 if not (s.null_count() == GSE115973.height)]]

GSE115973_combined = GSE115973_PEP.join(
    GSE115973_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).sort(
    "sample_geo_accession", descending=True
)

GSE115973_combined = GSE115973_combined[[s.name for s in GSE115973_combined if not (s.null_count() == GSE115973_combined.height)]]

GSE115973_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE115973_modified_metadata.tsv",
    separator='\t'
)

# display(GSE115973_PEP)

In [12]:
# Manual defined pairs
defined_pairs_gse115973 = [
    ("SRR7359799", "SRR7359790"),
    ("SRR7359798", "SRR7359789"),
    ("SRR7359797", "SRR7359788"),
    ("SRR7359787", "SRR7359778"),
    ("SRR7359786", "SRR7359777"),
    ("SRR7359785", "SRR7359776"),
    ("SRR7359775", "SRR7359766"),
    ("SRR7359774", "SRR7359765"),
    ("SRR7359773", "SRR7359764"),
    ("SRR7359763", "SRR7359754"),
    ("SRR7359762", "SRR7359753"),
    ("SRR7359761", "SRR7359752"),
    ("SRR7359751", "SRR7359742"),
    ("SRR7359750", "SRR7359741"),
    ("SRR7359749", "SRR7359740"),
    ("SRR7359739", "SRR7359730"),
    ("SRR7359738", "SRR7359729"),
    ("SRR7359737", "SRR7359728"),
    ("SRR7359727", "SRR7359718"),
    ("SRR7359726", "SRR7359717"),
    ("SRR7359725", "SRR7359716"), # 2026-01-17: SRR7359725 を発現定量し忘れていた
    ("SRR7359715", "SRR7359706"),
    ("SRR7359714", "SRR7359705"),
    ("SRR7359713", "SRR7359704"),
    ("SRR7359703", "SRR7359694"),
    ("SRR7359702", "SRR7359693"),
    ("SRR7359701", "SRR7359692"),
    ("SRR7359691", "SRR7359682"),
    ("SRR7359690", "SRR7359681"),
    ("SRR7359689", "SRR7359680"),
    ("SRR7359679", "SRR7359670"),
    ("SRR7359678", "SRR7359669"),
    ("SRR7359677", "SRR7359668"),
    ("SRR7359667", "SRR7359658"),
    ("SRR7359666", "SRR7359657"),
    ("SRR7359665", "SRR7359656")
]

paired_metadata_df_gse115973 = create_paired_metadata(
    combined_df=GSE115973_combined, 
    defined_sample_pairs=defined_pairs_gse115973,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse115973 is not None:
    paired_metadata_df_gse115973.write_csv(
        "../../Data/metadata/metadata_paired/GSE115973_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse115973)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (36, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ dis ┆ gen ┆ tre ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ eas ┆ oty ┆ atm ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ e   ┆ pe  ┆ ent ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆ e_3 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ mul ┆ SRX ┆ HS_ ┆ GSM ┆ Pub ┆ Jun ┆ Jan ┆ SRA ┆ 1   ┆ cel ┆ Hom ┆ 960 ┆ tot ┆ seq ┆ GPL ┆ Jen ┆ jen ┆ Lea ┆ Cel ┆ Åbo ┆ Tyk ┆ Tur ┆ Var ┆ 205 ┆ Fin ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ U2O ┆ ost ┆ hea ┆ hea ┆ hum ┆ SAM ┆ Ill ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Imp ┆ SRA ┆ cDN ┆ 202 ┆ 145 ┆ 216 ┆ ILL ┆ Gen ┆ HS_ ┆ SRP ┆ 723 ┆ Imp ┆ HS_ ┆ Ill ┆ Ill ┆ 365 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Aft ┆ GSM ┆ GEO ┆ U2O ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 735 ┆ 735 ┆ 2ko ┆ A   ┆ o   ┆ GLE ┆     ┆ ti  ┆ 423 ┆ 2KO ┆ 319 ┆ lic ┆ 18  ┆ 15  ┆     ┆     ┆ l   ┆ o   ┆ 6   ┆ al  ┆ uen ┆ 212 ┆ ny, ┆ ny. ┆ Sis ┆ l   ┆ Aka ┆ ist ┆ ku  ┆ sin ┆ 20  ┆ lan ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 319 ┆ :// ┆ :// ┆ :// ┆ 115 ┆     ┆ 423 ┆ S   ┆ eos ┆ t   ┆ t   ┆ an  ┆ N09 ┆ umi ┆ ps: ┆ C   ┆ min ┆ C   ┆ 735 ┆ umi ┆ act ┆ 724 ┆ A   ┆ 0-0 ┆ 038 ┆ 033 ┆ UMI ┆ eri ┆ 2KO ┆ 150 ┆ 418 ┆ act ┆ 2KO ┆ umi ┆ umi ┆ 729 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 319 ┆ 319 ┆ er  ┆ 319 ┆     ┆ S   ┆ 0-0 ┆ NA4 ┆ 343 ┆ 0-0 ┆ 115 │
│ 979 ┆ 979 ┆ _re ┆     ┆ sap ┆     ┆     ┆     ┆ 277 ┆ _re ┆ 706 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ cin ┆ 90  ┆ Maa ┆ jou ┆ ton ┆ Bio ┆ dem ┆ öka ┆     ┆ ais ┆     ┆ d   ┆ na  ┆     ┆ rip ┆ q   ┆ 706 ┆ ftp ┆ ftp ┆ ftp ┆ 973 ┆     ┆ 277 ┆     ┆ arc ┆ sho ┆ sho ┆ hg3 ┆ 445 ┆ na  ┆ //d ┆     ┆ .   ┆ (in ┆ 979 ┆ na  ┆ of  ┆ 426 ┆     ┆ 1-1 ┆ 492 ┆ 479 ┆ NA  ┆ c   ┆ _re ┆ 792 ┆ 7   ┆ of  ┆ _re ┆ na  ┆ na  ┆ 046 ┆ q   ┆ RIP ┆     ┆     ┆ 706 ┆ 706 ┆ tre ┆ 706 ┆     ┆     ┆ 1-1 ┆ 766 ┆ 141 ┆ 1-1 ┆ 973 │
│ 9   ┆ 0   ┆ p4  ┆     ┆ ien ┆     ┆     ┆     ┆ 5   ┆ p4  ┆ 8   ┆ Jan ┆ 8   ┆ 0   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ g   ┆     ┆ ria ┆ tse ┆ en  ┆ log ┆ i   ┆ tu  ┆     ┆ -Su ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 8   ┆ .nc ┆ .nc ┆ .nc ┆     ┆     ┆ 5   ┆     ┆ oma ┆ ck  ┆ ck  ┆ 8   ┆ 400 ┆ Tru ┆ oi. ┆     ┆     ┆ fer ┆ 9   ┆ HiS ┆ HSF ┆     ┆     ┆ 6   ┆ vs  ┆ vs  ┆     ┆     ┆ p4  ┆     ┆ vs  ┆ HSF ┆ p4  ┆ HiS ┆ HiS ┆ vs  ┆     ┆ TOM ┆     ┆     ┆ 8   ┆ 8_r ┆ atm ┆ 8   ┆     ┆     ┆ 6   ┆ 08  ┆ 3   ┆ 6   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ run ┆     ┆ ,Jo ┆ n@a ┆     ┆ y   ┆ Uni ┆ 6A  ┆     ┆ omi ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆     ┆ far ┆ 1 h ┆     ┆ vs  ┆ Seq ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ 1   ┆     ┆     ┆     ┆ 141 ┆ 210 ┆     ┆     ┆ vs  ┆     ┆ 702 ┆ 1   ┆ vs  ┆ eq  ┆ eq  ┆ 355 ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 3   ┆ ent ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ c_2 ┆     ┆     ┆     ┆     ┆     ┆ SRX ┆ C_2 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mad ┆     ┆ uts ┆ bo. ┆     ┆     ┆ ver ┆     ┆     ┆     ┆     ┆     ┆ 300 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆ cto ┆ in  ┆     ┆ SAM ┆ Str ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 300 ┆ and ┆     ┆     ┆     ┆ 234 ┆ 439 ┆     ┆     ┆ C_2 ┆     ┆ 803 ┆ and ┆ C_2 ┆ 300 ┆ 300 ┆ 333 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ s,  ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ ko_ ┆     ┆     ┆     ┆     ┆     ┆ 423 ┆ KO_ ┆ 319 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ en  ┆ fi  ┆     ┆     ┆ sit ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 319 ┆ .ni ┆ .ni ┆ .ni ┆     ┆     ┆ 423 ┆     ┆     ┆ r 2 ┆ 42  ┆     ┆ N09 ┆ and ┆ .10 ┆     ┆     ┆     ┆ 735 ┆ 0   ┆ HSF ┆     ┆     ┆     ┆ 067 ┆ 125 ┆     ┆     ┆ KO_ ┆     ┆ 7   ┆ HSF ┆ KO_ ┆ 0   ┆ 0   ┆ 226 ┆     ┆     ┆     ┆     ┆ 319 ┆ GSM ┆ cel ┆ 319 ┆     ┆     ┆     ┆     ┆ 343 ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆ 277 ┆ rep ┆ 706 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 706 ┆ h.g ┆ h.g ┆ h.g ┆     ┆     ┆ 277 ┆     ┆     ┆ KO  ┆ deg ┆     ┆ 445 ┆ ed  ┆ 16/ ┆     ┆     ┆     ┆ 979 ┆ seq ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ 2   ┆ rep ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ 706 ┆ 319 ┆ ls  ┆ 706 ┆     ┆     ┆     ┆     ┆ 141 ┆     ┆     │
│     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 4   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ ov/ ┆ ov/ ┆ ov/ ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ ree ┆     ┆ 404 ┆ mRN ┆ j.c ┆     ┆     ┆     ┆ 0   ┆ uen ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆ on  ┆ 4   ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 706 ┆ wer ┆ 5   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ A   ┆ elr ┆     ┆     ┆     ┆     ┆ cin ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_r ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ Sam ┆ ep. ┆     ┆     ┆     ┆     ┆ g:  ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆ ple ┆ 201 ┆     ┆     ┆     ┆     ┆ GSM ┆ exp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ exp ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ Pre ┆ 9.1 ┆     ┆     ┆     ┆     ┆ 319 ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆     ┆     ┆ 319 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ par ┆ 2.0 ┆     ┆     ┆     ┆     ┆ 706 ┆ sio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sio ┆     ┆     ┆ 706 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 319 ┆ 319 ┆ 319 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 37  ┆     ┆     ┆     ┆     ┆ 8:  ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ 8:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PBS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆ 7nn ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gui ┆     ┆     ┆     ┆     ┆     ┆ 2KO ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆ 2KO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆ SM3 ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ de  ┆     ┆     ┆     ┆     ┆     ┆ _re ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 197 ┆ 197 ┆ 197 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p4  ┆ gro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gro ┆     ┆     ┆ p4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 068 ┆ 068 ┆ 068 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ wth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wth ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M31 ┆ M31 ┆ M31 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. GSE79680 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-04-29
- [RNA Directed Modulation of Phenotypic Plasticity in Human Cells](https://doi.org/10.1371/journal.pone.0152424)
- lncRNAについて調べている論文
- しっかりコントロールと熱ストレス条件のデータが揃っていたので収集
- 45℃, 30分

In [13]:
GSE79680_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE79680/GSE79680_PEP/GSE79680_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Truseq RNA prep kit").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1371/journal.pone.0152424").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("45 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE79680 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE79680_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE79680_filtered = GSE79680[[s.name for s in GSE79680 if not (s.null_count() == GSE79680.height)]]

GSE79680_combined = GSE79680_PEP.join(
    GSE79680_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE79680_combined = GSE79680_combined[[s.name for s in GSE79680_combined if not (s.null_count() == GSE79680_combined.height)]]

GSE79680_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE79680_modified_metadata.tsv",
    separator='\t'
)

# display(GSE79680_combined)

In [14]:
# Manual defined pairs
defined_pairs_gse79680 = [
    ("SRR3309259", "SRR3309256"),
    ("SRR3309260", "SRR3309257"),
    ("SRR3309261", "SRR3309258")
]

paired_metadata_df_gse79680 = create_paired_metadata(
    combined_df=GSE79680_combined, 
    defined_sample_pairs=defined_pairs_gse79680,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse79680 is not None:
    paired_metadata_df_gse79680.write_csv(
        "../../Data/metadata/metadata_paired/GSE79680_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse79680)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ str ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ ess ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ --- ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ str ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆     ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hea ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ Hea ┆ GSM ┆ Pub ┆ Mar ┆ May ┆ SRA ┆ 1   ┆ Hea ┆ Hom ┆ 960 ┆ tot ┆ rRN ┆ GPL ┆ Jon ┆ BAB ┆ Uni ┆ UNS ┆ Syd ┆ NSW ┆ 205 ┆ Aus ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HEK ┆ hea ┆ hg1 ┆ SAM ┆ Tru ┆ htt ┆ 45  ┆ 30  ┆ 37  ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ cDN ┆ 201 ┆ 941 ┆ 115 ┆ ILL ┆ Gen ┆ Hea ┆ SRP ┆ 129 ┆ HEK ┆ Hea ┆ Ill ┆ Ill ┆ 144 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ HEK ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 330 ┆ 330 ┆ tsh ┆ A   ┆ o   ┆ GLE ┆     ┆ 330 ┆ 166 ┆ tSh ┆ 210 ┆ lic ┆ 29  ┆ 15  ┆     ┆     ┆ tSh ┆ o   ┆ 6   ┆ al  ┆ A   ┆ 111 ┆ ,,B ┆ S   ┆ ver ┆ W   ┆ ney ┆     ┆ 2   ┆ tra ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 210 ┆ :// ┆ :// ┆ 796 ┆     ┆ 166 ┆ 293 ┆ t   ┆ 9   ┆ N04 ┆ seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 330 ┆ umi ┆ o   ┆ 399 ┆ A   ┆ 9-1 ┆ 131 ┆ 728 ┆ UMI ┆ eri ┆ tSh ┆ 072 ┆ 051 ┆ 293 ┆ tSh ┆ umi ┆ umi ┆ 537 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 210 ┆ 210 ┆ was ┆ 210 ┆     ┆ 293 ┆ 6-0 ┆ NA3 ┆ 136 ┆ 6-0 ┆ 796 │
│ 925 ┆ 925 ┆ ock ┆     ┆ sap ┆     ┆     ┆ 925 ┆ 836 ┆ ock ┆ 109 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ock ┆ sap ┆     ┆ RNA ┆ dep ┆ 54  ┆ urd ┆     ┆ sit ┆     ┆     ┆     ┆     ┆ lia ┆ na  ┆     ┆ rip ┆ q   ┆ 109 ┆ ftp ┆ ftp ┆ 80  ┆     ┆ 836 ┆ cel ┆ sho ┆     ┆ 590 ┆ RNA ┆ //d ┆     ┆ .   ┆ (in ┆ 925 ┆ na  ┆ sap ┆ 583 ┆     ┆ 2-2 ┆ 424 ┆ 856 ┆ NA  ┆ c   ┆ ock ┆ 687 ┆ 37  ┆ Hea ┆ ock ┆ na  ┆ na  ┆ 534 ┆ q   ┆ RIP ┆     ┆     ┆ 109 ┆ 109 ┆ ext ┆ 109 ┆     ┆ cel ┆ 4-0 ┆ 168 ┆ 891 ┆ 4-0 ┆ 80  │
│ 9   ┆ 6   ┆ 1   ┆     ┆ ien ┆     ┆     ┆ 9   ┆ 7   ┆ 1   ┆ 3   ┆ Mar ┆ 6   ┆ 9   ┆     ┆     ┆ vs  ┆ ien ┆     ┆     ┆ let ┆     ┆ ach ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 3   ┆ .nc ┆ .nc ┆     ┆     ┆ 7   ┆ ls  ┆ ck  ┆     ┆ 838 ┆ pre ┆ oi. ┆     ┆     ┆ fer ┆ 9   ┆ HiS ┆ ien ┆     ┆     ┆ 2   ┆ vs  ┆ 7   ┆     ┆     ┆ 1   ┆     ┆ vs  ┆ t-s ┆ 1   ┆ HiS ┆ HiS ┆ 4   ┆     ┆ TOM ┆     ┆     ┆ 3   ┆ 3_r ┆ rac ┆ 3   ┆     ┆ ls  ┆ 9   ┆ 56  ┆ 7   ┆ 9   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ vs  ┆ 30  ┆     ┆     ┆     ┆     ┆ Con ┆ s   ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ vs  ┆     ┆ vs  ┆ p   ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆ vs  ┆ 155 ┆ vs  ┆     ┆     ┆ vs  ┆     ┆ 212 ┆ hoc ┆ vs  ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ted ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ con ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ Con ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆ tot ┆     ┆     ┆     ┆ New ┆     ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ con ┆     ┆ SAM ┆ kit ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 200 ┆     ┆     ┆     ┆ 201 ┆ 077 ┆ 193 ┆     ┆     ┆ Con ┆     ┆ 377 ┆ k   ┆ Con ┆ 200 ┆ 200 ┆ 237 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ usi ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆ 330 ┆ 166 ┆ tro ┆ 210 ┆ 6   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 210 ┆ .ni ┆ .ni ┆     ┆     ┆ 166 ┆     ┆ tro ┆     ┆ N04 ┆     ┆ .13 ┆     ┆     ┆     ┆ 330 ┆ 0   ┆     ┆     ┆     ┆ 9-1 ┆ 584 ┆ 668 ┆     ┆     ┆ tro ┆     ┆ 11  ┆ exp ┆ tro ┆ 0   ┆ 0   ┆ 862 ┆     ┆     ┆     ┆     ┆ 210 ┆ GSM ┆ ng  ┆ 210 ┆     ┆     ┆     ┆     ┆ 136 ┆     ┆     │
│     ┆     ┆ l1  ┆     ┆     ┆     ┆     ┆ 925 ┆ 836 ┆ l1  ┆ 109 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 109 ┆ h.g ┆ h.g ┆     ┆     ┆ 836 ┆     ┆ l   ┆     ┆ 590 ┆     ┆ 71/ ┆     ┆     ┆     ┆ 925 ┆ seq ┆     ┆     ┆     ┆ 0-3 ┆ 0   ┆ 223 ┆     ┆     ┆ l1  ┆     ┆     ┆ eri ┆ l1  ┆     ┆ seq ┆ 363 ┆     ┆     ┆     ┆     ┆ 109 ┆ 210 ┆ Tri ┆ 109 ┆     ┆     ┆     ┆     ┆ 891 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 4   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Wal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 835 ┆     ┆ jou ┆     ┆     ┆     ┆ 6   ┆ uen ┆     ┆     ┆     ┆ 0   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆ uen ┆ 2   ┆     ┆     ┆     ┆     ┆ 0   ┆ 109 ┆ zol ┆ 0   ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_r ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l.p ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ one ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .01 ┆     ┆     ┆     ┆     ┆ 210 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 210 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 524 ┆     ┆     ┆     ┆     ┆ 109 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 109 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 210 ┆ 210 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 24  ┆     ┆     ┆     ┆     ┆ 3:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1nn ┆ 1nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ufa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tSh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tSh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM2 ┆ SM2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆ 101 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 's  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 093 ┆ 093 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ins ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tru ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ons ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M21 ┆ M21 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 010 ┆ 010 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 93_ ┆ 93_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE32060 (SINGLE) Ribo-seq

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [Widespread Regulation of Translation by Elongation Pausing in Heat Shock](https://doi.org/10.1016/j.molcel.2012.11.028)
- 以前の研究でも使用した研究
- ペアごとに熱ストレスの条件に違うので、後で手入力
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 6. GSE267930 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date 2025-04-29
- [Inflammatory stress-mediated chromatin changes underlie dysfunction in endothelial cells](https://doi.org/10.1101/2023.10.11.561959)
- BioRxivのデータ
- データとしてはすべてRNA-seqのデータで TNF-alpha 処理のデータも含まれていたのでこちらを除外する
- 収集できるデータとして使用 (39℃, 2h.)

In [15]:
GSE267930_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE267930/GSE267930_PEP/GSE267930_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("sample_title").str.contains(r'TNF-alpha')) # remove TNF-alpha treatment data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra II Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1101/2023.10.11.561959").alias("reference_doi"), # add DOI of the reference paper column (BioRxiv)
    pl.lit("39 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE267930 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE267930_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE267930_filtered = GSE267930[[s.name for s in GSE267930 if not (s.null_count() == GSE267930.height)]]

GSE267930_combined = GSE267930_PEP.join(
    GSE267930_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE267930_combined = GSE267930_combined[[s.name for s in GSE267930_combined if not (s.null_count() == GSE267930_combined.height)]]

GSE267930_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE267930_modified_metadata.tsv",
    separator='\t'
)

# display(GSE267930_combined)

In [16]:
# Manual defined pairs
defined_pairs_gse267930 = [
    ("SRR29089688", "SRR29089691"), # heat shock vs control
    ("SRR29089687", "SRR29089690"),
    ("SRR29089686", "SRR29089689"),
]

paired_metadata_df_gse267930 = create_paired_metadata(
    combined_df=GSE267930_combined, 
    defined_sample_pairs=defined_pairs_gse267930,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse267930 is not None:
    paired_metadata_df_gse267930.write_csv(
        "../../Data/metadata/metadata_paired/GSE267930_modified_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse267930)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ huv ┆ HUV ┆ GSM ┆ Pub ┆ May ┆ May ┆ SRA ┆ 1   ┆ HUV ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Hai ┆ hai ┆ 515 ┆ MCC ┆ UMa ┆ 164 ┆ Uni ┆ CT  ┆ 608 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ HUV ┆ vas ┆ hea ┆ Tab ┆ SAM ┆ NEB ┆ htt ┆ 39  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ Inf ┆ SRA ┆ cDN ┆ 202 ┆ 208 ┆ 152 ┆ ILL ┆ mis ┆ Gen ┆ HUV ┆ SRP ┆ 233 ┆ Inf ┆ HUV ┆ Ill ┆ Ill ┆ vas ┆ 652 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ HUV ┆ mis ┆ GSM ┆ HUV ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 290 ┆ 290 ┆ ec_ ┆ EC, ┆ 828 ┆ lic ┆ 20  ┆ 25  ┆     ┆     ┆ EC  ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ bo, ┆ bo. ┆ 357 ┆ B   ┆ ss  ┆ Pla ┆ onv ┆     ┆ 5   ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 828 ┆ E   ┆ 267 ┆     ┆ 246 ┆ EC  ┆ cul ┆ t   ┆ -de ┆ N41 ┆ Nex ┆ ps: ┆ C   ┆ min ┆ C   ┆ 290 ┆ umi ┆ lam ┆ 187 ┆ A   ┆ 4-0 ┆ 689 ┆ 112 ┆ UMI ┆ sin ┆ eri ┆ EC, ┆ 508 ┆ 348 ┆ lam ┆ EC, ┆ umi ┆ umi ┆ cul ┆ 630 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 828 ┆ 828 ┆ EC  ┆ sin ┆ 828 ┆ EC  ┆ 828 ┆ 4-0 ┆ NA1 ┆ 213 ┆ 4-0 ┆ 267 │
│ 896 ┆ 896 ┆ 39_ ┆ 39  ┆ 173 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 76  ┆ ,Li ┆ liu ┆ 371 ┆     ┆ Cha ┆ nta ┆ ill ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 173 ┆     ┆ 930 ┆     ┆ 138 ┆     ┆ ar  ┆ str ┆ lim ┆ 463 ┆ t   ┆ //d ┆     ┆ .   ┆ (in ┆ 896 ┆ na  ┆ mat ┆ 189 ┆     ┆ 6-3 ┆ 018 ┆ 680 ┆ NA  ┆ g   ┆ c   ┆ 39  ┆ 793 ┆ 27  ┆ mat ┆ 39  ┆ na  ┆ na  ┆ ar  ┆ 684 ┆ q   ┆ RIP ┆     ┆     ┆ 173 ┆ 173 ┆ cel ┆ g   ┆ 173 ┆     ┆ 173 ┆ 6-3 ┆ 113 ┆ 510 ┆ 6-3 ┆ 930 │
│ 88  ┆ 91  ┆ °c_ ┆ °C  ┆ 7   ┆ May ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆ u   ┆ @um ┆ 9   ┆     ┆ n   ┆ tio ┆ e   ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 31  ┆     ┆ end ┆ ess ┆ ite ┆ 628 ┆ Ult ┆ oi. ┆     ┆     ┆ fer ┆ 88  ┆ Nov ┆ ory ┆ 7   ┆     ┆ 0   ┆ 3   ┆ 6;1 ┆     ┆     ┆     ┆ °C  ┆     ┆ vs  ┆ ory ┆ °C  ┆ Nov ┆ Nov ┆ end ┆ 7   ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ ls  ┆     ┆ 7_r ┆     ┆ 7   ┆ 0   ┆ 656 ┆ 74  ┆ 0   ┆     │
│     ┆     ┆ hea ┆ hea ┆ vs  ┆ 25  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ ass ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ oth ┆ vs  ┆ d   ┆ vs  ┆ ra  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ str ┆     ┆     ┆     ┆ vs  ┆ 539 ┆     ┆     ┆     ┆ hea ┆     ┆ 250 ┆ str ┆ hea ┆ aSe ┆ aSe ┆ oth ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ wer ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ t_s ┆ t   ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ eli ┆ con ┆ (.t ┆ SAM ┆ II  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ ess ┆     ┆     ┆     ┆ 227 ┆ 877 ┆     ┆     ┆     ┆ t   ┆     ┆ 266 ┆ ess ┆ t   ┆ q   ┆ q   ┆ eli ┆ 706 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ e   ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ tre ┆ str ┆ 828 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 828 ┆     ┆     ┆     ┆ 246 ┆     ┆ al  ┆ tro ┆ sv) ┆ N41 ┆ Dir ┆ .11 ┆     ┆     ┆     ┆ 290 ┆ 600 ┆ -me ┆     ┆     ┆     ┆ 396 ┆ 789 ┆     ┆     ┆     ┆ str ┆     ┆ 24  ┆ -me ┆ str ┆ 600 ┆ 600 ┆ al  ┆ 763 ┆     ┆     ┆     ┆     ┆ 828 ┆ GSM ┆ gro ┆     ┆ GSM ┆     ┆ 828 ┆     ┆     ┆ 213 ┆     ┆     │
│     ┆     ┆ ss_ ┆ ess ┆ 173 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 173 ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆ l   ┆ gen ┆ 463 ┆ ect ┆ 01/ ┆     ┆     ┆     ┆ 896 ┆ 0   ┆ dia ┆     ┆     ┆     ┆ 358 ┆ vs  ┆     ┆     ┆     ┆ ess ┆     ┆     ┆ dia ┆ ess ┆ 0   ┆ 0   ┆     ┆ 082 ┆     ┆     ┆     ┆     ┆ 173 ┆ 828 ┆ wn  ┆     ┆ 828 ┆     ┆ 173 ┆     ┆     ┆ 510 ┆     ┆     │
│     ┆     ┆ for ┆ for ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 28  ┆     ┆     ┆     ┆ e-b ┆ 631 ┆ ion ┆ 202 ┆     ┆     ┆     ┆ 91  ┆ seq ┆ ted ┆     ┆     ┆     ┆ 7   ┆ 165 ┆     ┆     ┆     ┆ for ┆     ┆     ┆ ted ┆ for ┆     ┆ seq ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 4   ┆ 173 ┆ in  ┆     ┆ 173 ┆     ┆ 4   ┆     ┆     ┆ 71  ┆     ┆     │
│     ┆     ┆ _2_ ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y-s ┆     ┆ al  ┆ 3.1 ┆     ┆     ┆     ┆     ┆ uen ┆ chr ┆     ┆     ┆     ┆     ┆ 414 ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ chr ┆ 2   ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_r ┆ dis ┆     ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hou ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆     ┆ RNA ┆ 0.1 ┆     ┆     ┆     ┆     ┆ cin ┆ oma ┆     ┆     ┆     ┆     ┆ 682 ┆     ┆     ┆     ┆ hou ┆     ┆     ┆ oma ┆ hou ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ hes ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rs_ ┆ rs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆     ┆ Lib ┆ 1.5 ┆     ┆     ┆     ┆     ┆ g:  ┆ tin ┆     ┆     ┆     ┆     ┆ 8;1 ┆     ┆     ┆     ┆ rs, ┆     ┆     ┆ tin ┆ rs, ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ bio ┆ bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cou ┆     ┆ rar ┆ 619 ┆     ┆     ┆     ┆     ┆ GSM ┆ cha ┆     ┆     ┆     ┆     ┆ 691 ┆     ┆     ┆     ┆ bio ┆     ┆     ┆ cha ┆ bio ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆ y   ┆ 59  ┆     ┆     ┆     ┆     ┆ 828 ┆ nge ┆     ┆     ┆     ┆     ┆ 572 ┆     ┆     ┆     ┆ log ┆     ┆     ┆ nge ┆ log ┆     ┆ 828 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ her ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ica ┆ ica ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tab ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆ 173 ┆ s   ┆     ┆     ┆     ┆     ┆ 272 ┆     ┆     ┆     ┆ ica ┆     ┆     ┆ s   ┆ ica ┆     ┆ 173 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lef ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ l_r ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ und ┆ l   ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ epl ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆ HUV ┆ erl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ erl ┆ rep ┆     ┆ HUV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ica ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EC, ┆ ie  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆ ie  ┆ lic ┆     ┆ EC, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ te_ ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 39  ┆ dys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆ dys ┆ ate ┆     ┆ 39  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_h ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ °C  ┆ fun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ fun ┆ 1   ┆     ┆ °C  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ or  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s1_ ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ cti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (HS ┆     ┆     ┆ cti ┆ (HS ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sub ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ 1)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1)  ┆     ┆     ┆ on  ┆ 1)  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ jec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ huv ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ in  ┆ vs  ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ec_ ┆ HUV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ess ┆ end ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HUV ┆     ┆     ┆ end ┆ HUV ┆     ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 7. GSE271918 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-04-29
- [Effect of CLK2 expression in the regulation of intron retention during heat shock](https://doi.org/10.1002/advs.202309588)
- CLK2のノックダウンなどが行われている研究
- ~~`T343A-N`, `T343A-C` などのmutationを導入したサンプルもあるが、これもコントロールとして使用する予定 (ペア数の増加に寄与)~~
- 42℃, 2h
- **mutationを加えているT343A-C, T343A-Nのデータに対して熱ストレスを加えているデータは含まれていないので今回は使用しない**
- **`HeLa cells, Control`に対して、`HeLa cells,HS-Control`, `HeLa cells,HS-WT`, `HeLa cells,HS-KD`** の3種類のペアを作成する

In [17]:
GSE271918_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE271918/GSE271918_PEP/GSE271918_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("sample_title").str.contains(r'T343A-')) # remove T343A-N, T343A-C mutation data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (from supproting information) "The RNA library construction and sequencing were performed by Bioyi Biotechnology Co., Ltd. Wuhan, China (details can be found in the Supporting Information). "
    pl.lit("https://doi.org/10.1002/advs.202309588").alias("reference_doi"), # add DOI of the reference paper column (BioRxiv)
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min.").alias("stress treatment time"), # add heat treatment time column (minutes) (from supporting information Fig. S3D)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE271918 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE271918_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE271918_filtered = GSE271918[[s.name for s in GSE271918 if not (s.null_count() == GSE271918.height)]]

GSE271918_combined = GSE271918_PEP.join(
    GSE271918_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE271918_combined = GSE271918_combined[[s.name for s in GSE271918_combined if not (s.null_count() == GSE271918_combined.height)]]

GSE271918_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE271918_modified_metadata.tsv",
    separator='\t'
)

# display(GSE271918_combined)

In [18]:
# Manual defined pairs
defined_pairs_gse271918 = [
    ("SRR29765556", "SRR29765559"), # heat shock vs control
    ("SRR29765555", "SRR29765558"),
    ("SRR29765554", "SRR29765557"),
    ("SRR29765553", "SRR29765559"),
    ("SRR29765552", "SRR29765558"),
    ("SRR29765551", "SRR29765557"),
    ("SRR29765550", "SRR29765559"),
    ("SRR29765549", "SRR29765558"),
    ("SRR29765548", "SRR29765557")
]

paired_metadata_df_gse271918 = create_paired_metadata(
    combined_df=GSE271918_combined, 
    defined_sample_pairs=defined_pairs_gse271918,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse271918 is not None:
    paired_metadata_df_gse271918.write_csv(
        "../../Data/metadata/metadata_paired/GSE271918_modified_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse271918)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (9, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hel ┆ HeL ┆ GSM ┆ Pub ┆ Jul ┆ Jul ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ tot ┆ HeL ┆ GPL ┆ Wei ┆ wek ┆ 13  ┆ Wuh ┆ Hub ┆ 430 ┆ Chi ┆ DNB ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ cer ┆ Con ┆ Hea ┆ GRC ┆ tab ┆ SAM ┆ unk ┆ htt ┆ 42  ┆ 240 ┆ 37  ┆ SRR ┆ DNB ┆ Eff ┆ SRA ┆ cDN ┆ 202 ┆ 741 ┆ 441 ┆ DNB ┆ mis ┆ Gen ┆ HeL ┆ SRP ┆ 459 ┆ Eff ┆ HeL ┆ DNB ┆ DNB ┆ cer ┆ 137 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ mis ┆ GSM ┆ HeL ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 297 ┆ 297 ┆ a_c ┆ a   ┆ 838 ┆ lic ┆ 10  ┆ 15  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ al  ┆ a-H ┆ 294 ┆ ,,W ┆ le@ ┆ Han ┆ an  ┆ ei  ┆ 030 ┆ na  ┆ SEQ ┆ A   ┆ nsc ┆ -Se ┆ 838 ┆ E   ┆ 271 ┆     ┆ 252 ┆ a   ┆ vic ┆ tro ┆ t   ┆ h38 ┆ -de ┆ N42 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 297 ┆ SEQ ┆ ect ┆ 192 ┆ A   ┆ 4-0 ┆ 599 ┆ 072 ┆ SEQ ┆ sin ┆ eri ┆ a   ┆ 519 ┆ 497 ┆ ect ┆ a   ┆ SEQ ┆ SEQ ┆ vic ┆ 849 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 838 ┆ 838 ┆ s   ┆ sin ┆ 838 ┆ a   ┆ 838 ┆ 4-0 ┆ NA1 ┆ 219 ┆ 4-0 ┆ 271 │
│ 655 ┆ 655 ┆ ell ┆ cel ┆ 900 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ S1  ┆ 80  ┆ ang ┆ hus ┆ gko ┆     ┆     ┆     ┆     ┆ -T7 ┆     ┆ rip ┆ q   ┆ 900 ┆     ┆ 918 ┆     ┆ 661 ┆     ┆ al  ┆ l   ┆ sho ┆ .10 ┆ lim ┆ 396 ┆ n   ┆ //d ┆     ┆ .   ┆ (in ┆ 655 ┆ -T7 ┆ of  ┆ 114 ┆     ┆ 7-2 ┆ 071 ┆ 583 ┆     ┆ g   ┆ c   ┆ cel ┆ 108 ┆ 98  ┆ of  ┆ cel ┆ -T7 ┆ -T7 ┆ al  ┆ 394 ┆ q   ┆ RIP ┆     ┆     ┆ 900 ┆ 900 ┆ wer ┆ g   ┆ 900 ┆     ┆ 900 ┆ 7-2 ┆ 134 ┆ 511 ┆ 7-2 ┆ 918 │
│ 56  ┆ 59  ┆ s_h ┆ ls, ┆ 3   ┆ Jul ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ vs  ┆     ┆     ┆ t.e ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆ 3   ┆     ┆     ┆     ┆ 81  ┆     ┆ can ┆     ┆ ck  ┆ 5   ┆ ite ┆ 141 ┆     ┆ oi. ┆     ┆     ┆ fer ┆ 56  ┆ seq ┆ CLK ┆ 2   ┆     ┆ 9   ┆ 8   ┆ 8;4 ┆     ┆     ┆     ┆ ls, ┆     ┆ vs  ┆ CLK ┆ ls, ┆     ┆ seq ┆ can ┆ 00  ┆     ┆ TOM ┆     ┆     ┆ 3   ┆ 3_r ┆ e   ┆     ┆ 3_r ┆     ┆ 3   ┆ 9   ┆ 123 ┆ 09  ┆ 9   ┆     │
│     ┆     ┆ s-c ┆ HS- ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ HeL ┆     ┆     ┆ du. ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ cer ┆     ┆ vs  ┆     ┆ d   ┆ vs  ┆     ┆ org ┆     ┆     ┆ red ┆ vs  ┆ uen ┆ 2   ┆     ┆     ┆     ┆ vs  ┆ 854 ┆     ┆     ┆     ┆ HS- ┆     ┆ 343 ┆ 2   ┆ HS- ┆     ┆ uen ┆ cer ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ ont ┆ Con ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a1  ┆     ┆     ┆ cn  ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ cel ┆     ┆ Unt ┆     ┆ tex ┆ SAM ┆     ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ cin ┆ exp ┆     ┆     ┆     ┆ 550 ┆ 233 ┆     ┆     ┆     ┆ Con ┆     ┆ 015 ┆ exp ┆ Con ┆     ┆ cin ┆ cel ┆ 102 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ rol ┆ tro ┆ 838 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 838 ┆     ┆     ┆     ┆ 252 ┆     ┆ l   ┆     ┆ rea ┆     ┆ t   ┆ N42 ┆     ┆ .10 ┆     ┆     ┆     ┆ 297 ┆ g:  ┆ res ┆     ┆     ┆     ┆ 519 ┆ 767 ┆     ┆     ┆     ┆ tro ┆     ┆ 09  ┆ res ┆ tro ┆     ┆ g:  ┆ l   ┆ 904 ┆     ┆     ┆     ┆     ┆ 838 ┆ GSM ┆ ted ┆     ┆ GSM ┆     ┆ 838 ┆     ┆     ┆ 219 ┆     ┆     │
│     ┆     ┆ -1  ┆ l-1 ┆ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 900 ┆     ┆     ┆     ┆ 661 ┆     ┆ lin ┆     ┆ ted ┆     ┆ fil ┆ 396 ┆     ┆ 02/ ┆     ┆     ┆     ┆ 655 ┆ GSM ┆ sio ┆     ┆     ┆     ┆ 977 ┆ vs  ┆     ┆     ┆     ┆ l-1 ┆     ┆     ┆ sio ┆ l-1 ┆     ┆ GSM ┆ lin ┆ 527 ┆     ┆     ┆     ┆     ┆ 900 ┆ 838 ┆ usi ┆     ┆ 838 ┆     ┆ 900 ┆     ┆     ┆ 511 ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 78  ┆     ┆ e   ┆     ┆     ┆     ┆ es  ┆ 144 ┆     ┆ adv ┆     ┆     ┆     ┆ 59  ┆ 838 ┆ n   ┆     ┆     ┆     ┆ 2   ┆ 343 ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ n   ┆ vs  ┆     ┆ 838 ┆ e   ┆ 00  ┆     ┆     ┆     ┆     ┆ 0   ┆ 900 ┆ ng  ┆     ┆ 900 ┆     ┆ 0   ┆     ┆     ┆ 08  ┆     ┆     │
│     ┆     ┆ hel ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆     ┆     ┆ s.2 ┆     ┆     ┆     ┆     ┆ 900 ┆ in  ┆     ┆     ┆     ┆     ┆ 347 ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆ in  ┆ HeL ┆     ┆ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_r ┆ Tri ┆     ┆ 0_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ a_c ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lud ┆     ┆     ┆ 023 ┆     ┆     ┆     ┆     ┆ 3:  ┆ the ┆     ┆     ┆     ┆     ┆ 783 ┆     ┆     ┆     ┆ a   ┆     ┆     ┆ the ┆ a   ┆     ┆ 3:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ zol ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ell ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 095 ┆     ┆     ┆     ┆     ┆ HeL ┆ reg ┆     ┆     ┆     ┆     ┆ 1;3 ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ reg ┆ cel ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_c ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ raw ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆ a   ┆ ula ┆     ┆     ┆     ┆     ┆ 490 ┆     ┆     ┆     ┆ ls, ┆     ┆     ┆ ula ┆ ls, ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ont ┆ Con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ tio ┆     ┆     ┆     ┆     ┆ 574 ┆     ┆     ┆     ┆ Con ┆     ┆     ┆ tio ┆ Con ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rol ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nts ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆ n   ┆     ┆     ┆     ┆     ┆ 318 ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ n   ┆ tro ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -1  ┆ l-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS- ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-1 ┆     ┆     ┆ of  ┆ l-1 ┆     ┆ HS- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     ┆ Con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆ ron ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-1 ┆ ret ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ret ┆     ┆     ┆ l-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ ent ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ dur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dur ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ exe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8. GSE259306 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-04-29
- [TurboCas: A method for locus-specific labeling of genomic regions and isolating their associated protein interactome](https://doi.org/10.1016/j.molcel.2024.11.007)
- Hspa6,などのKnockdownを行った際の熱ストレス応答について研究している論文とデータ
- Turbocas というツールが主眼
- 42℃, 3h
- コントロール、熱ストレス曝露のデータが揃っているため、解析に使用する
- `neg`が `37C 37 hours, 3h`, `pos`が `42C 3 hours (heat shock)`
- 一部のデータが `neg`のデータが一つしかなかったので、`replicate 2`にも`neg`の`replicate 1`に対応させる

In [19]:
GSE259306_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE259306/GSE259306_PEP/GSE259306_PEP_raw.csv",
    separator=','
).with_columns(
    (
        pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
        pl.lit("NEBNext Ultra II Directional RNA Library Prep Kit for Illumina").alias("rna_library"), # add rna_library column (NEB, E7760L)
        pl.lit("https://doi.org/10.1016/j.molcel.2024.11.007").alias("reference_doi"), # add DOI of the reference paper column (BioRxiv)
        pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
        pl.lit("180 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
        pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE259306 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE259306_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE259306_filtered = GSE259306[[s.name for s in GSE259306 if not (s.null_count() == GSE259306.height)]]

GSE259306_combined = GSE259306_PEP.join(
    GSE259306_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE259306_combined = GSE259306_combined[[s.name for s in GSE259306_combined if not (s.null_count() == GSE259306_combined.height)]]

GSE259306_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE259306_modified_metadata.tsv",
    separator='\t'
)

# display(GSE259306_combined)

In [20]:
# Manual defined pairs
defined_pairs_gse259306 = [
    ("SRR28110418", "SRR28110420"), # heat shock vs control (Abcf2 replicate 1)
    ("SRR28110417", "SRR28110419"), # heat shock vs control (Abcf2 replicate 2)
    ("SRR28110414", "SRR28110416"), # heat shock vs control (Acaca replicate 1)
    ("SRR28110413", "SRR28110415"), # heat shock vs control (Acaca replicate 2)
    ("SRR28110402", "SRR28110411"), # heat shock vs control (Acacb replicate 1)
    ("SRR28110403", "SRR28110412"), # heat shock vs control (Acacb replicate 2)
    ("SRR28110406", "SRR28110404"), # heat shock vs control (Amot replicate 1)
    ("SRR28110407", "SRR28110405"), # heat shock vs control (Amot replicate 2)
    ("SRR28110410", "SRR28110408"), # heat shock vs control (Atad3a replicate 1)
    ("SRR28110401", "SRR28110409"), # heat shock vs control (Atad3a replicate 2)
    ("SRR28110400", "SRR28110392"), # heat shock vs control (Bag2 replicate 1)
    ("SRR28110399", "SRR28110393"), # heat shock vs control (Bag2 replicate 2)
    ("SRR28110386", "SRR28110395"), # heat shock vs control (Fubp3 replicate 1)
    ("SRR28110385", "SRR28110394"), # heat shock vs control (Fubp3 replicate 2)
    ("SRR28110391", "SRR28110384"), # heat shock vs control (Hsp90aa1 replicate 1)
    ("SRR28110390", "SRR28110383"), # heat shock vs control (Hsp90aa1 replicate 2)
    ("SRR28110387", "SRR28110389"), # heat shock vs control (Hsp90a1b replicate 1)
    ("SRR28110357", "SRR28110388"), # heat shock vs control (Hsp90a1b replicate 2)
    ("SRR28110354", "SRR28110356"), # heat shock vs control (Hspa6 replicate 1)
    ("SRR28110382", "SRR28110355"), # heat shock vs control (Hspa6 replicate 2)
    ("SRR28110345", "SRR28110358"), # heat shock vs control (Hspa9 replicate 1)
    ("SRR28110344", "SRR28110346"), # heat shock vs control (Hspa9 replicate 2)
    ("SRR28110352", "SRR28110343"), # heat shock vs control (Kpna2 replicate 1)
    ("SRR28110351", "SRR28110353"), # heat shock vs control (Kpna2 replicate 2)
    ("SRR28110348", "SRR28110350"), # heat shock vs control (Nat10 replicate 1)
    ("SRR28110347", "SRR28110349"), # heat shock vs control (Nat10 replicate 2)
    ("SRR28110342", "SRR28110323"), # heat shock vs control (Nkap replicate 1)
    ("SRR28110341", "SRR28110322"), # heat shock vs control (Nkap replicate 2)
    ("SRR28110327", "SRR28110329"), # heat shock vs control (Nono replicate 1)
    ("SRR28110326", "SRR28110328"), # heat shock vs control (Nono replicate 2)
    ("SRR28110317", "SRR28110319"), # heat shock vs control (Rad50 replicate 1)
    ("SRR28110316", "SRR28110318"), # heat shock vs control (Rad50 replicate 2)
    ("SRR28110377", "SRR28110315"), # heat shock vs control (Ranbp2 replicate 1)
    ("SRR28110376", "SRR28110378"), # heat shock vs control (Ranbp2 replicate 2)
    ("SRR28110311", "SRR28110375"), # heat shock vs control (Scrambled replicate 1)
    ("SRR28110310", "SRR28110312"), # heat shock vs control (Scrambled replicate 2)
    ("SRR28110369", "SRR28110380"), # heat shock vs control (Sdad1 replicate 1)
    ("SRR28110368", "SRR28110379"), # heat shock vs control (Sdad1 replicate 2)
    ("SRR28110374", "SRR28110367"), # heat shock vs control (Smarcd2 replicate 1)
    ("SRR28110373", "SRR28110366"), # heat shock vs control (Smarcd2 replicate 2)
    ("SRR28110370", "SRR28110372"), # heat shock vs control (Sumo2 replicate 1)
    ("SRR28110340", "SRR28110371"), # heat shock vs control (Sumo2 replicate 2)
    ("SRR28110363", "SRR28110365"), # heat shock vs control (Trim28 replicate 1)
    ("SRR28110362", "SRR28110364"), # heat shock vs control (Trim28 replicate 2)
    ("SRR28110332", "SRR28110361"), # heat shock vs control (Yy1 replicate 1)
    ("SRR28110331", "SRR28110333"), # heat shock vs control (Yy1 replicate 2)
    ("SRR28110335", "SRR28110330"), # heat shock vs control (Zfp91 replicate 1)
    ("SRR28110334", "SRR28110336"), # heat shock vs control (Zfp91 replicate 2)
    ("SRR28110397", "SRR28110398"), # heat shock vs control (Eef1g replicate 1) (negative data is only SRR28110398)
    ("SRR28110396", "SRR28110398"), # heat shock vs control (Eef1g replicate 2) (negative data is only SRR28110398)
    ("SRR28110360", "SRR28110381"), # heat shock vs control (Hspa8 replicate 1) (negative data is only SRR28110381)
    ("SRR28110359", "SRR28110381"), # heat shock vs control (Hspa8 replicate 2) (negative data is only SRR28110381)
    ("SRR28110324", "SRR28110325"), # heat shock vs control (Prkdc replicate 1) (negative data is only SRR28110325)
    ("SRR28110314", "SRR28110325"), # heat shock vs control (Prkdc replicate 2) (negative data is only SRR28110325)
    ("SRR28110321", "SRR28110313"), # heat shock vs control (Prpf40q replicate 1) (negative data is only SRR28110313)
    ("SRR28110320", "SRR28110313"), # heat shock vs control (Prpf40q replicate 2) (negative data is only SRR28110313)
    ("SRR28110338", "SRR28110339"), # heat shock vs control (Supt16h replicate 1) (negative data is only SRR28110339)
    ("SRR28110337", "SRR28110339")  # heat shock vs control (Supt16h replicate 2) (negative data is only SRR28110339)
]

paired_metadata_df_gse259306 = create_paired_metadata(
    combined_df=GSE259306_combined, 
    defined_sample_pairs=defined_pairs_gse259306,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse259306 is not None:

    paired_metadata_df_gse259306.write_csv(
        "../../Data/metadata/metadata_paired/GSE259306_modified_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse259306)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (58, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ RNA ┆ GSM ┆ Pub ┆ Feb ┆ Dec ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ pol ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HCT ┆ hum ┆ Abc ┆ 42C ┆ hg3 ┆ big ┆ SAM ┆ NEB ┆ htt ┆ 42  ┆ 180 ┆ 37  ┆ SRR ┆ Ill ┆ Tur ┆ SRA ┆ cDN ┆ 202 ┆ 134 ┆ 119 ┆ ILL ┆ nul ┆ nul ┆ SRP ┆ 404 ┆ Tur ┆ nul ┆ Ill ┆ Ill ┆ nul ┆ 408 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ nul ┆ GSM ┆ For ┆ nul ┆ GSM ┆ nul ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 281 ┆ 281 ┆ seq ┆ seq ┆ 811 ┆ lic ┆ 26  ┆ 21  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ yA  ┆ 246 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 811 ┆ :// ┆ :// ┆ 259 ┆     ┆ 237 ┆ 116 ┆ an  ┆ f2  ┆ 3   ┆ 8   ┆ wig ┆ N40 ┆ Nex ┆ ps: ┆ C   ┆ min ┆ C   ┆ 281 ┆ umi ┆ boC ┆ 181 ┆ A   ┆ 4-1 ┆ 411 ┆ 264 ┆ UMI ┆ l   ┆ l   ┆ 491 ┆ 445 ┆ boC ┆ l   ┆ umi ┆ umi ┆ l   ┆ 220 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ l   ┆ 811 ┆ RNA ┆ l   ┆ 811 ┆ l   ┆ 811 ┆ 4-1 ┆ NA1 ┆ 205 ┆ 4-1 ┆ 259 │
│ 104 ┆ 104 ┆ _ab ┆ _Ab ┆ 366 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 76  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 366 ┆ ftp ┆ ftp ┆ 306 ┆     ┆ 552 ┆     ┆ col ┆     ┆ hou ┆     ┆ fil ┆ 146 ┆ t   ┆ //d ┆     ┆ .   ┆ (in ┆ 104 ┆ na  ┆ as: ┆ 049 ┆     ┆ 2-2 ┆ 313 ┆ 509 ┆ NA  ┆     ┆     ┆ 877 ┆ 94  ┆ as: ┆     ┆ na  ┆ na  ┆     ┆ 326 ┆ q   ┆ RIP ┆     ┆     ┆     ┆ 366 ┆ :   ┆     ┆ 366 ┆     ┆ 366 ┆ 2-2 ┆ 080 ┆ 810 ┆ 2-2 ┆ 306 │
│ 18  ┆ 20  ┆ cf2 ┆ cf2 ┆ 1   ┆ Dec ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 1   ┆ .nc ┆ .nc ┆     ┆     ┆ 24  ┆     ┆ ore ┆     ┆ rs  ┆     ┆ es  ┆ 632 ┆ Ult ┆ oi. ┆     ┆     ┆ fer ┆ 18  ┆ Nov ┆ A   ┆ 2   ┆     ┆ 5   ┆ 2   ┆ 1;1 ┆     ┆     ┆     ┆     ┆ vs  ┆ A   ┆     ┆ Nov ┆ Nov ┆     ┆ 8   ┆     ┆ TOM ┆     ┆     ┆     ┆ 1_r ┆ RNA ┆     ┆ 1_r ┆     ┆ 1   ┆ 5   ┆ 614 ┆ 14  ┆ 5   ┆     │
│     ┆     ┆ _hs ┆ _HS ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ cta ┆     ┆ (he ┆     ┆ for ┆ vs  ┆ ra  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ met ┆     ┆     ┆     ┆ vs  ┆ 227 ┆     ┆     ┆     ┆     ┆ 463 ┆ met ┆     ┆ aSe ┆ aSe ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆     ┆ 1   ┆ fro ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ _po ┆ _po ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ l   ┆     ┆ at  ┆     ┆ ChI ┆ SAM ┆ II  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ hod ┆     ┆     ┆     ┆ 150 ┆ 456 ┆     ┆     ┆     ┆     ┆ 363 ┆ hod ┆     ┆ q   ┆ q   ┆     ┆ 467 ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ m   ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ s_r ┆ s_R ┆ 811 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 811 ┆ .ni ┆ .ni ┆     ┆     ┆ 237 ┆     ┆ car ┆     ┆ sho ┆     ┆ P-s ┆ N40 ┆ Dir ┆ .10 ┆     ┆     ┆     ┆ 281 ┆ 600 ┆ for ┆     ┆     ┆     ┆ 782 ┆ 195 ┆     ┆     ┆     ┆     ┆ 88  ┆ for ┆     ┆ 600 ┆ 600 ┆     ┆ 152 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ HCT ┆     ┆ GSM ┆     ┆ 811 ┆     ┆     ┆ 205 ┆     ┆     │
│     ┆     ┆ ep1 ┆ ep1 ┆ 365 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 365 ┆ h.g ┆ h.g ┆     ┆     ┆ 552 ┆     ┆ cin ┆     ┆ ck) ┆     ┆ eq  ┆ 146 ┆ ect ┆ 16/ ┆     ┆     ┆     ┆ 104 ┆ 0   ┆ loc ┆     ┆     ┆     ┆ 070 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ loc ┆     ┆ 0   ┆ 0   ┆     ┆ 207 ┆     ┆     ┆     ┆     ┆     ┆ 811 ┆ 116 ┆     ┆ 811 ┆     ┆ 365 ┆     ┆     ┆ 810 ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 22  ┆     ┆ oma ┆     ┆ vs  ┆     ┆ dat ┆ 634 ┆ ion ┆ j.m ┆     ┆     ┆     ┆ 20  ┆ seq ┆ us- ┆     ┆     ┆     ┆ 8   ┆ 134 ┆     ┆     ┆     ┆     ┆     ┆ us- ┆     ┆     ┆ seq ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 365 ┆ cel ┆     ┆ 365 ┆     ┆ 9   ┆     ┆     ┆ 16  ┆     ┆     │
│     ┆     ┆ rna ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ 37C ┆     ┆ a   ┆     ┆ al  ┆ olc ┆     ┆     ┆     ┆     ┆ uen ┆ spe ┆     ┆     ┆     ┆     ┆ 522 ┆     ┆     ┆     ┆     ┆     ┆ spe ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_r ┆ ls  ┆     ┆ 9_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ 3   ┆     ┆     ┆     ┆ RNA ┆ el. ┆     ┆     ┆     ┆     ┆ cin ┆ cif ┆     ┆     ┆     ┆     ┆ 353 ┆     ┆     ┆     ┆     ┆     ┆ cif ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ was ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ab ┆ _Ab ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆ Lib ┆ 202 ┆     ┆     ┆     ┆     ┆ g:  ┆ ic  ┆     ┆     ┆     ┆     ┆ 6;1 ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cf2 ┆ cf2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ rs  ┆     ┆     ┆     ┆ rar ┆ 4.1 ┆     ┆     ┆     ┆     ┆ GSM ┆ lab ┆     ┆     ┆     ┆     ┆ 377 ┆     ┆     ┆     ┆     ┆     ┆ lab ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _hs ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ (no ┆     ┆     ┆     ┆ y   ┆ 1.0 ┆     ┆     ┆     ┆     ┆ 811 ┆ eli ┆     ┆     ┆     ┆     ┆ 706 ┆     ┆     ┆     ┆     ┆     ┆ eli ┆     ┆     ┆ 811 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ne ┆ _ne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 811 ┆ 811 ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ Pre ┆ 07  ┆     ┆     ┆     ┆     ┆ 366 ┆ ng  ┆     ┆     ┆     ┆     ┆ 850 ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆ 366 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ g_r ┆ g_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ 1:  ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck) ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ seq ┆ omi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 113 ┆ 113 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆     ┆     ┆     ┆     ┆     ┆ _Ab ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆ _Ab ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 661 ┆ 661 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆ cf2 ┆ reg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ reg ┆     ┆     ┆ cf2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _po ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ _po ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_R ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆ s_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Qi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 9. GSE247417 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-04-29
- [CLK2 Condensates Reorganize Nuclear Speckles and Induce Intron Retention](https://doi.org/10.1002/advs.202309588)
- GSE271918 と同じ研究グループで、おそらく同じ論文由来のデータ
- 論文には掲載されていないが... (ミス？)
- 42℃, 2h
- コントロールデータも揃っているので解析に使用する予定
- GSE271918 との対応を考えると、おそらく 42 C , 240 min. の推定

In [21]:
GSE247417_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE247417/GSE247417_PEP/GSE247417_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (from supproting information)
    pl.lit("https://doi.org/10.1002/advs.202309588").alias("reference_doi"), # add DOI of the reference paper column (BioRxiv)
    pl.lit("42 C (inferred)").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min. (inferred)").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE247417 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE247417_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE247417_filtered = GSE247417[[s.name for s in GSE247417 if not (s.null_count() == GSE247417.height)]]

GSE247417_combined = GSE247417_PEP.join(
    GSE247417_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE247417_combined = GSE247417_combined[[s.name for s in GSE247417_combined if not (s.null_count() == GSE247417_combined.height)]]

GSE247417_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE247417_modified_metadata.tsv",
    separator='\t'
)

# display(GSE247417_combined)

In [22]:
# Manual defined pairs
defined_pairs_gse247417 = [
    ("SRR26772129", "SRR26772135"), # heat shock vs control
    ("SRR26772128", "SRR26772134"),
    ("SRR26772127", "SRR26772132"),
    ("SRR26772126", "SRR26772131"),
    ("SRR26772125", "SRR26772133"),
    ("SRR26772124", "SRR26772130")
    
]

paired_metadata_df_gse247417 = create_paired_metadata(
    combined_df=GSE247417_combined, 
    defined_sample_pairs=defined_pairs_gse247417,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse247417 is not None:

    paired_metadata_df_gse247417.write_csv(
        "../../Data/metadata/metadata_paired/GSE247417_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse247417)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 78)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hel ┆ HeL ┆ GSM ┆ Pub ┆ Nov ┆ Nov ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Wei ┆ wek ┆ 13  ┆ Wuh ┆ Hub ┆ 430 ┆ Chi ┆ DNB ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ HeL ┆ Con ┆ Hea ┆ Hom ┆ SAM ┆ unk ┆ htt ┆ 42  ┆ 240 ┆ 37  ┆ SRR ┆ DNB ┆ Eff ┆ SRA ┆ cDN ┆ 202 ┆ 260 ┆ 162 ┆ DNB ┆ mis ┆ Gen ┆ HeL ┆ SRP ┆ 285 ┆ Eff ┆ HeL ┆ DNB ┆ DNB ┆ HeL ┆ 856 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ HeL ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 267 ┆ 267 ┆ a_c ┆ a   ┆ 788 ┆ lic ┆ 09  ┆ 09  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ al  ┆ 294 ┆ ,,W ┆ le@ ┆ Han ┆ an  ┆ ei  ┆ 030 ┆ na  ┆ SEQ ┆ A   ┆ nsc ┆ -Se ┆ 788 ┆ E   ┆ 247 ┆     ┆ 224 ┆ a   ┆ a   ┆ tro ┆ t   ┆ o   ┆ N38 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 267 ┆ SEQ ┆ ect ┆ 174 ┆ A   ┆ 3-1 ┆ 080 ┆ 457 ┆ SEQ ┆ sin ┆ eri ┆ a   ┆ 471 ┆ 338 ┆ ect ┆ a   ┆ SEQ ┆ SEQ ┆ a   ┆ 014 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 788 ┆ 788 ┆ al  ┆ sin ┆ 788 ┆ a   ┆ 788 ┆ 3-1 ┆ NA1 ┆ 194 ┆ 3-1 ┆ 247 │
│ 721 ┆ 721 ┆ ell ┆ cel ┆ 975 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 80  ┆ ang ┆ hus ┆ gko ┆     ┆     ┆     ┆     ┆ -T7 ┆     ┆ rip ┆ q   ┆ 975 ┆     ┆ 417 ┆     ┆ 707 ┆     ┆     ┆ l   ┆ sho ┆ sap ┆ 188 ┆ n   ┆ //d ┆ (in ┆ .   ┆ (in ┆ 721 ┆ -T7 ┆ of  ┆ 843 ┆     ┆ 1-1 ┆ 522 ┆ 469 ┆     ┆ g   ┆ c   ┆ cel ┆ 083 ┆ 07  ┆ of  ┆ cel ┆ -T7 ┆ -T7 ┆     ┆ 210 ┆ q   ┆ RIP ┆     ┆     ┆ 975 ┆ 975 ┆ RNA ┆ g   ┆ 975 ┆     ┆ 975 ┆ 1-1 ┆ 037 ┆ 844 ┆ 1-1 ┆ 417 │
│ 29  ┆ 35  ┆ s_h ┆ ls, ┆ 2   ┆ Nov ┆ 3   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆ t.e ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆ 2   ┆     ┆     ┆     ┆ 84  ┆     ┆     ┆     ┆ ck  ┆ ien ┆ 930 ┆     ┆ oi. ┆ fer ┆ (in ┆ fer ┆ 29  ┆ seq ┆ CLK ┆ 4   ┆     ┆ 2   ┆ 2   ┆ 7;1 ┆     ┆     ┆     ┆ ls, ┆     ┆ vs  ┆ CLK ┆ ls, ┆     ┆ seq ┆     ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_r ┆ was ┆     ┆ 2_r ┆     ┆ 2   ┆ 2   ┆ 521 ┆ 84  ┆ 2   ┆     │
│     ┆     ┆ s-g ┆ HS- ┆ vs  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ du. ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ s   ┆ vs  ┆     ┆ org ┆ red ┆ fer ┆ red ┆ vs  ┆ uen ┆ 2   ┆     ┆     ┆     ┆ vs  ┆ 624 ┆     ┆     ┆     ┆ HS- ┆     ┆ 197 ┆ 2   ┆ HS- ┆     ┆ uen ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ iso ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ fp- ┆ GFP ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cn  ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆ Unt ┆     ┆ SAM ┆     ┆ /10 ┆ )   ┆ red ┆ )   ┆ SRR ┆ cin ┆ exp ┆     ┆     ┆     ┆ 180 ┆ 015 ┆     ┆     ┆     ┆ GFP ┆     ┆ 667 ┆ exp ┆ GFP ┆     ┆ cin ┆     ┆ 593 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ lat ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ 1   ┆ -1  ┆ 788 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 788 ┆     ┆     ┆     ┆ 224 ┆     ┆     ┆     ┆ rea ┆     ┆ N38 ┆     ┆ .10 ┆     ┆ )   ┆     ┆ 267 ┆ g:  ┆ res ┆     ┆     ┆     ┆ 500 ┆ 982 ┆     ┆     ┆     ┆ -1  ┆     ┆ 99  ┆ res ┆ -1  ┆     ┆ g:  ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆ 788 ┆ GSM ┆ ed  ┆     ┆ GSM ┆     ┆ 788 ┆     ┆     ┆ 194 ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 974 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 974 ┆     ┆     ┆     ┆ 707 ┆     ┆     ┆     ┆ ted ┆     ┆ 188 ┆     ┆ 02/ ┆     ┆     ┆     ┆ 721 ┆ GSM ┆ sio ┆     ┆     ┆     ┆ 973 ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ sio ┆ vs  ┆     ┆ GSM ┆     ┆ 970 ┆     ┆     ┆     ┆     ┆ 974 ┆ 788 ┆ usi ┆     ┆ 788 ┆     ┆ 974 ┆     ┆     ┆ 844 ┆     ┆     │
│     ┆     ┆ hel ┆ HeL ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆     ┆ 936 ┆     ┆ adv ┆     ┆     ┆     ┆ 35  ┆ 788 ┆ n   ┆     ┆     ┆     ┆ 0   ┆ 113 ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆ n   ┆ HeL ┆     ┆ 788 ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 6   ┆ 974 ┆ ng  ┆     ┆ 974 ┆     ┆ 6   ┆     ┆     ┆ 81  ┆     ┆     │
│     ┆     ┆ a_c ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s.2 ┆     ┆     ┆     ┆     ┆ 975 ┆ in  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ a   ┆     ┆     ┆ in  ┆ a   ┆     ┆ 975 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6_r ┆ the ┆     ┆ 6_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ell ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 023 ┆     ┆     ┆     ┆     ┆ 2:  ┆ the ┆     ┆     ┆     ┆     ┆ 432 ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ the ┆ cel ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ Tri ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_h ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 095 ┆     ┆     ┆     ┆     ┆ HeL ┆ reg ┆     ┆     ┆     ┆     ┆ 4;1 ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ reg ┆ ls  ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_c ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆ a   ┆ ula ┆     ┆     ┆     ┆     ┆ 134 ┆     ┆     ┆     ┆ (HS ┆     ┆     ┆ ula ┆ (HS ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ont ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ tio ┆     ┆     ┆     ┆     ┆ 465 ┆     ┆     ┆     ┆ con ┆     ┆     ┆ tio ┆ con ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rol ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆ n   ┆     ┆     ┆     ┆     ┆ 725 ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ n   ┆ tro ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ __g ┆ l), ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS- ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l), ┆     ┆     ┆ of  ┆ l), ┆     ┆ HS- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ fp- ┆ GFP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GFP ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GFP ┆     ┆     ┆ int ┆ GFP ┆     ┆ GFP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ee  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆ -1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -1  ┆ ron ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -1  ┆     ┆     ┆ ron ┆ -1  ┆     ┆ -1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ ret ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ret ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ ent ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ram ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ dur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dur ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ use ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DNB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DNB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ as  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE186004 (PAIRED) NO DOWNLOAD

- validation date: 2025-04-29
- HSF1 のノックアウトとestrageol の関係などに関するデータ
- 熱ストレスに関連するデータがないため、今回は使用しない
- `mcf7_cells_hsf1+_+_control_repeat_1`, `mcf7_cells_hsf1+_+_estrogen_4h_repeat_1`, `mcf7_cells_hsf1-_-_control_repeat_1`, `mcf7_cells_hsf1-_-_estrogen_4h_repeat_1`などのサンプルが存在する

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 10. GSE159802 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [Heat shock factor 1 (HSF1) cooperates with estrogen receptor α (ERα) in the regulation of estrogen action in breast cancer cells](https://doi.org/10.7554/eLife.69843)
- estrogenにさらされているデータは取り除いた状態で解析に使用する

In [23]:
GSE159802_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE159802/GSE159802_PEP/GSE159802_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("sample_description").str.contains(r'estrogen')) # remove estrogen data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.7554/eLife.69843").alias("reference_doi"), # add DOI of the reference paper column (eLife)
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE159802 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE159802_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE159802_filtered = GSE159802[[s.name for s in GSE159802 if not (s.null_count() == GSE159802.height)]]

GSE159802_combined = GSE159802_PEP.join(
    GSE159802_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE159802_combined = GSE159802_combined[[s.name for s in GSE159802_combined if not (s.null_count() == GSE159802_combined.height)]]

GSE159802_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE159802_modified_metadata.tsv",
    separator='\t'
)

# display(GSE159802_combined)

In [24]:
# Manual defined pairs
defined_pairs_gse159802 = [
    ("SRR12868789", "SRR12868787"), # heat shock vs control (MCF7 WT)
    ("SRR12868792", "SRR12868790"), # heat shock vs control (MCF7 SCR)
    ("SRR12868795", "SRR12868793"), # heat shock vs control (MCF7 shHSF1)
    ("SRR12868798", "SRR12868796"), # heat shock vs control (MCF7 MIX)
    ("SRR12868801", "SRR12868799"), # heat shock vs control (MCF7 KO#1)
    ("SRR12868804", "SRR12868802")  # heat shock vs control (MCF7 KO#2)  
]

paired_metadata_df_gse159802 = create_paired_metadata(
    combined_df=GSE159802_combined, 
    defined_sample_pairs=defined_pairs_gse159802,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse159802 is not None:

    paired_metadata_df_gse159802.write_csv(
        "../../Data/metadata/metadata_paired/GSE159802_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse159802)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tum ┆ sex ┆ age ┆ tis ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ or  ┆ --- ┆ --- ┆ sue ┆ oty ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ --- ┆ str ┆ str ┆ --- ┆ pe  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ str ┆     ┆     ┆ str ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ a3_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ A3: ┆ GSM ┆ Pub ┆ Oct ┆ Oct ┆ SRA ┆ 1   ┆ MCF ┆ Hom ┆ 960 ┆ tot ┆ MCF ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ ade ┆ fem ┆ 69  ┆ bre ┆ wil ┆ SAM ┆ unk ┆ htt ┆ 43  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Hea ┆ SRA ┆ cDN ┆ 202 ┆ 129 ┆ 941 ┆ ILL ┆ Gen ┆ A3: ┆ SRP ┆ 215 ┆ Hea ┆ A3: ┆ Ill ┆ Ill ┆ 327 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ MCF ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ bre │
│ 128 ┆ 128 ┆ mcf ┆ A   ┆ o   ┆ RED ┆     ┆ 128 ┆ 933 ┆ MCF ┆ 484 ┆ lic ┆ 21  ┆ 19  ┆     ┆     ┆ 7   ┆ o   ┆ 6   ┆ al  ┆ 7   ┆ 184 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 484 ┆ E   ┆ 159 ┆     ┆ 933 ┆ 7   ┆ noc ┆ ale ┆ yea ┆ ast ┆ d   ┆ N16 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 128 ┆ umi ┆ t   ┆ 114 ┆ A   ┆ 1-1 ┆ 875 ┆ 323 ┆ UMI ┆ eri ┆ MCF ┆ 288 ┆ 663 ┆ t   ┆ MCF ┆ umi ┆ umi ┆ 808 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 484 ┆ 484 ┆ al  ┆ 484 ┆     ┆ 7   ┆ 1-1 ┆ NA6 ┆ 755 ┆ 1-1 ┆ 159 ┆ ast │
│ 687 ┆ 687 ┆ 7_w ┆     ┆ sap ┆     ┆     ┆ 687 ┆ 490 ┆ 7_W ┆ 738 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆ wil ┆ 60  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 738 ┆     ┆ 802 ┆     ┆ 490 ┆     ┆ arc ┆     ┆ rs  ┆     ┆ typ ┆ 510 ┆ n   ┆ //d ┆     ┆ .   ┆ (in ┆ 687 ┆ na  ┆ Sho ┆ 610 ┆     ┆ 0-2 ┆ 740 ┆ 876 ┆ NA  ┆ c   ┆ 7_W ┆ 220 ┆ 69  ┆ Sho ┆ 7_W ┆ na  ┆ na  ┆ 808 ┆ q   ┆ RIP ┆     ┆     ┆ 738 ┆ 738 ┆ RNA ┆ 738 ┆     ┆     ┆ 0-2 ┆ 705 ┆ 993 ┆ 0-2 ┆ 802 ┆     │
│ 89  ┆ 87  ┆ t_h ┆     ┆ ien ┆     ┆     ┆ 89  ┆ 4   ┆ T_H ┆ 4   ┆ Oct ┆ 0   ┆ 1   ┆     ┆     ┆ ls  ┆ ien ┆     ┆     ┆ d   ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 4   ┆     ┆ ,   ┆     ┆ 4   ┆     ┆ ino ┆     ┆     ┆     ┆ e   ┆ 678 ┆     ┆ oi. ┆     ┆     ┆ fer ┆ 89  ┆ HiS ┆ ck  ┆ 5   ┆     ┆ 8   ┆ 3   ┆ ;96 ┆     ┆     ┆ T_H ┆     ┆ vs  ┆ ck  ┆ T_H ┆ HiS ┆ HiS ┆ 8   ┆     ┆ TOM ┆     ┆     ┆ 4   ┆ 4_r ┆ was ┆ 4   ┆     ┆     ┆ 3   ┆ 65  ┆ 2   ┆ 3   ┆     ┆     │
│     ┆     ┆ s_1 ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ S_1 ┆ vs  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ typ ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆ GSE ┆     ┆ vs  ┆     ┆ ma  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ Fac ┆     ┆     ┆     ┆ vs  ┆ 880 ┆     ┆     ┆ S_1 ┆     ┆ 202 ┆ Fac ┆ S_1 ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ iso ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ h_2 ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ h/2 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e - ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ 150 ┆     ┆     ┆     ┆ GSM ┆     ┆ 159 ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆     ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 150 ┆ tor ┆     ┆     ┆     ┆ 122 ┆ 264 ┆     ┆     ┆ h/2 ┆     ┆ 313 ┆ tor ┆ h/2 ┆ 150 ┆ 150 ┆ 307 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ lat ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ h_r ┆     ┆     ┆     ┆     ┆ 128 ┆ 933 ┆ h_r ┆ 484 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hyp ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 484 ┆     ┆ 803 ┆     ┆ 933 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N16 ┆     ┆ .75 ┆     ┆     ┆     ┆ 128 ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ 669 ┆ 5   ┆     ┆     ┆ h_r ┆     ┆ 17  ┆ 1   ┆ h_r ┆ 0   ┆ 0   ┆ 516 ┆     ┆     ┆     ┆     ┆ 484 ┆ GSM ┆ ed  ┆ 484 ┆     ┆     ┆     ┆     ┆ 755 ┆     ┆     ┆     │
│     ┆     ┆ ec  ┆     ┆     ┆     ┆     ┆ 687 ┆ 490 ┆ ec  ┆ 738 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 738 ┆     ┆     ┆     ┆ 490 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 510 ┆     ┆ 54/ ┆     ┆     ┆     ┆ 687 ┆ seq ┆ (HS ┆     ┆     ┆     ┆ 052 ┆ vs  ┆     ┆     ┆ ec  ┆     ┆     ┆ (HS ┆ ec  ┆     ┆ seq ┆ 018 ┆     ┆     ┆     ┆     ┆ 738 ┆ 484 ┆ fro ┆ 738 ┆     ┆     ┆     ┆     ┆ 993 ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 87  ┆ 2   ┆ vs  ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 680 ┆     ┆ eLi ┆     ┆     ┆     ┆ 87  ┆ uen ┆ F1) ┆     ┆     ┆     ┆ 7   ┆ 887 ┆     ┆     ┆ vs  ┆     ┆     ┆ F1) ┆ vs  ┆     ┆ uen ┆ 4   ┆     ┆     ┆     ┆     ┆ 2   ┆ 738 ┆ m   ┆ 2   ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆ a1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ A1: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fe. ┆     ┆     ┆     ┆     ┆ cin ┆ sup ┆     ┆     ┆     ┆     ┆ 573 ┆     ┆     ┆ A1: ┆     ┆     ┆ sup ┆ A1: ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ all ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mcf ┆     ┆     ┆     ┆     ┆     ┆     ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (43 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 698 ┆     ┆     ┆     ┆     ┆ g:  ┆ por ┆     ┆     ┆     ┆     ┆ 858 ┆     ┆     ┆ MCF ┆     ┆     ┆ por ┆ MCF ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7_w ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_W ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ °C) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆     ┆     ┆     ┆     ┆ GSM ┆ ts  ┆     ┆     ┆     ┆     ┆ ;91 ┆     ┆     ┆ 7_W ┆     ┆     ┆ ts  ┆ 7_W ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ t_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 484 ┆ the ┆     ┆     ┆     ┆     ┆ 903 ┆     ┆     ┆ T_c ┆     ┆     ┆ the ┆ T_c ┆     ┆ 484 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 738 ┆ ESR ┆     ┆     ┆     ┆     ┆ 424 ┆     ┆     ┆ ont ┆     ┆     ┆ ESR ┆ ont ┆     ┆ 738 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ur  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆ 1   ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ rol ┆     ┆     ┆ 1   ┆ rol ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ var ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ &   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A3: ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ act ┆     ┆     ┆ A3: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ian ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WT_ ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ WT_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ urs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (un ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1h/ ┆ bre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bre ┆     ┆     ┆ 1h/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2h_ ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 2h_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rec ┆ can ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ can ┆     ┆     ┆ rec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ry  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ cer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ (RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (RN ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 11. GSE73471 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [The bromodomain protein BRD4 regulates splicing during heat shock](https://doi.org/10.1093/nar/gkw729)
- [bromodomain containing 4](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:13575) の RNA interference (RNAi) を熱ストレスと共に行っている研究
- これも以前の研究で使用済み
- 解析に使用する
- ペア案: `ctrl_1` vs `hs_1`, `hs_2`, `hs_3`
- ペア案: `si_brd4_1` vs `si_brd4_hs_1`, `si_brd4_hs_2`, `si_brd4_hs_3`
- validation date 2: 2025-05-15
- `SRR2522102` のfastpの処理が以下のようなエラーになった

```bash
WARNING: different read numbers of the 209849 pack
Read1 pack size: 256
Read2 pack size: 123

ERROR: input files don't contain identical amount of reads
```

- そのため、今回はこのデータを外す
- (2026-09-29) 論文を見ても、特に stranded RNA-seq と書いていないので、strandness はわからなかった

In [25]:
GSE73471_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE73471/GSE73471_PEP/GSE73471_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq RNA Sample Preparation Kit").alias("rna_library"), # add rna_library column (from supplementary information)
    pl.lit("https://doi.org/10.1093/nar/gkw729").alias("reference_doi"), # add DOI of the reference paper column (NAR)
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE73471 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE73471_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE73471_filtered = GSE73471[[s.name for s in GSE73471 if not (s.null_count() == GSE73471.height)]]

GSE73471_combined = GSE73471_PEP.join(
    GSE73471_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE73471_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE73471_modified_metadata.tsv",
    separator='\t'
)

# display(GSE73471_combined)

In [26]:
# Manual defined pairs
defined_pairs_gse73471 = [
    ("SRR2522096", "SRR2522093"), # HS 1 vs Ctrl 1
    ("SRR2522098", "SRR2522095"), # si BRD 4 & HS1 vs si BRD4
    ("SRR2522099", "SRR2522093"), # HS 2 vs Ctrl 1
    ("SRR2522101", "SRR2522095"), # si BRD 4 & HS2 vs si BRD4
    # ("SRR2522102", "SRR2522093"), # HS 3 vs Ctrl 1
    ("SRR2522103", "SRR2522095")  # si BRD 4 & HS3 vs si BRD4
]

paired_metadata_df_gse73471 = create_paired_metadata(
    combined_df=GSE73471_combined, 
    defined_sample_pairs=defined_pairs_gse73471,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse73471 is not None:

    paired_metadata_df_gse73471.write_csv(
        "../../Data/metadata/metadata_paired/GSE73471_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse73471)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (5, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tre ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ atm ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ent ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HS  ┆ GSM ┆ Pub ┆ Sep ┆ May ┆ SRA ┆ 1   ┆ WI3 ┆ Hom ┆ 960 ┆ see ┆ tot ┆ GPL ┆ Mic ┆ msc ┆ Sch ┆ Leh ┆ Max ┆ Ihn ┆ Ber ┆ 141 ┆ Ger ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ WI3 ┆ To  ┆ hg1 ┆ SAM ┆ Tru ┆ htt ┆ 42  ┆ 240 ┆ 37  ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ cDN ┆ 202 ┆ 191 ┆ 119 ┆ ILL ┆ Gen ┆ HS  ┆ SRP ┆ 321 ┆ The ┆ HS  ┆ Ill ┆ Ill ┆ 327 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ WI3 ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 252 ┆ 252 ┆ 1   ┆ A   ┆ o   ┆ RED ┆     ┆ 252 ┆ 128 ┆ 1   ┆ 189 ┆ lic ┆ 26  ┆ 15  ┆     ┆     ┆ 8   ┆ o   ┆ 6   ┆ Sam ┆ al  ┆ 167 ┆ hal ┆ hwe ┆ wei ┆ rac ┆ Pla ┆ est ┆ lin ┆ 95  ┆ man ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 189 ┆ E   ┆ 734 ┆     ┆ 128 ┆ 8   ┆ ind ┆ 9,  ┆ N04 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 252 ┆ umi ┆ o   ┆ 301 ┆ A   ┆ 0-0 ┆ 328 ┆ 449 ┆ UMI ┆ eri ┆ 1   ┆ 064 ┆ 511 ┆ bro ┆ 1   ┆ umi ┆ umi ┆ 941 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 189 ┆ 189 ┆ al  ┆ 189 ┆     ┆ 8   ┆ 6-0 ┆ NA2 ┆ 109 ┆ 6-0 ┆ 734 │
│ 209 ┆ 209 ┆ vs  ┆     ┆ sap ┆     ┆     ┆ 209 ┆ 954 ┆ vs  ┆ 536 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ ple ┆ RNA ┆ 91  ┆ ,Ru ┆ ig@ ┆ ger ┆ h   ┆ nck ┆ ras ┆     ┆     ┆ y   ┆ na  ┆     ┆ rip ┆ q   ┆ 536 ┆     ┆ 71  ┆     ┆ 954 ┆ lun ┆ uce ┆ GRC ┆ 115 ┆ RNA ┆ //d ┆     ┆ .   ┆ (in ┆ 209 ┆ na  ┆ sap ┆ 088 ┆     ┆ 4-2 ┆ 606 ┆ 228 ┆ NA  ┆ c   ┆ vs  ┆ 222 ┆ 12  ┆ mod ┆ vs  ┆ na  ┆ na  ┆ 342 ┆ q   ┆ RIP ┆     ┆     ┆ 536 ┆ 536 ┆ RNA ┆ 536 ┆     ┆ lun ┆ 9-0 ┆ 971 ┆ 093 ┆ 9-0 ┆ 71  │
│ 6   ┆ 3   ┆ ctr ┆     ┆ ien ┆     ┆     ┆ 6   ┆ 7   ┆ Ctr ┆ 7   ┆ Sep ┆ 5   ┆ 9   ┆     ┆     ┆ l   ┆ ien ┆     ┆ s   ┆     ┆     ┆ th, ┆ mol ┆     ┆     ┆ Ins ┆ se  ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 7   ┆ g   ┆ hea ┆ h37 ┆ 214 ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆ 6   ┆ HiS ┆ ien ┆     ┆     ┆ 2   ┆ 0   ┆ 6;1 ┆     ┆     ┆ Ctr ┆     ┆ vs  ┆ oma ┆ Ctr ┆ HiS ┆ HiS ┆ 4   ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ was ┆ 7   ┆     ┆ g   ┆ 8   ┆ 09  ┆ 0   ┆ 8   ┆     │
│     ┆     ┆ l_1 ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ l 1 ┆ vs  ┆ 07  ┆     ┆     ┆     ┆     ┆ lin ┆ s   ┆     ┆ sec ┆     ┆     ┆ Sch ┆ gen ┆     ┆     ┆ tit ┆ 63- ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ fib ┆ t   ┆     ┆ vs  ┆ ple ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ 218 ┆     ┆     ┆ l 1 ┆     ┆ 332 ┆ in  ┆ l 1 ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ pur ┆ vs  ┆     ┆ fib ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆     ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ tio ┆     ┆     ┆ wei ┆ .mp ┆     ┆     ┆ ute ┆ 73  ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ rob ┆ str ┆     ┆ SAM ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 250 ┆     ┆     ┆     ┆ 201 ┆ 198 ┆ 159 ┆     ┆     ┆     ┆     ┆ 266 ┆ pro ┆     ┆ 250 ┆ 250 ┆ 338 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ ifi ┆ GSM ┆     ┆ rob ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 252 ┆ 128 ┆     ┆ 189 ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ ger ┆ g.d ┆     ┆     ┆ For ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 189 ┆     ┆     ┆     ┆ 128 ┆ las ┆ ess ┆     ┆ N04 ┆ par ┆ .10 ┆     ┆     ┆     ┆ 252 ┆ 0   ┆     ┆     ┆     ┆ 9-1 ┆ 831 ┆ 232 ┆     ┆     ┆     ┆     ┆ 46  ┆ tei ┆     ┆ 0   ┆ 0   ┆ 911 ┆     ┆     ┆     ┆     ┆ 189 ┆ GSM ┆ ed  ┆ 189 ┆     ┆ las ┆     ┆     ┆ 109 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 209 ┆ 954 ┆     ┆ 536 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 536 ┆     ┆     ┆     ┆ 954 ┆ t   ┆ ,   ┆     ┆ 115 ┆ ati ┆ 93/ ┆     ┆     ┆     ┆ 209 ┆ seq ┆     ┆     ┆     ┆ 0-2 ┆ 199 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ seq ┆ 789 ┆     ┆     ┆     ┆     ┆ 536 ┆ 189 ┆ usi ┆ 536 ┆     ┆ t   ┆     ┆     ┆ 093 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 5   ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ 5   ┆ cel ┆ cel ┆     ┆ 212 ┆ on  ┆ nar ┆     ┆     ┆     ┆ 3   ┆ uen ┆     ┆     ┆     ┆ 8   ┆ 6   ┆ 123 ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆ uen ┆ 2   ┆     ┆     ┆     ┆     ┆ 5   ┆ 536 ┆ ng  ┆ 5   ┆     ┆ cel ┆     ┆     ┆ 2   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆ ls  ┆     ┆     ┆ Kit ┆ /gk ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 650 ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_r ┆ the ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆ w72 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 134 ┆     ┆     ┆     ┆     ┆     ┆ reg ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 4;1 ┆     ┆     ┆     ┆     ┆     ┆ ula ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 189 ┆     ┆     ┆     ┆     ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆ tes ┆     ┆     ┆ 189 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ roP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 536 ┆     ┆     ┆     ┆     ┆     ┆ 260 ┆     ┆     ┆     ┆     ┆     ┆ spl ┆     ┆     ┆ 536 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆ 314 ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆ HS  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Zy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dur ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mo  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erb ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ath ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 12. GSE53667 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [Heat Shock Alters the Expression of Schizophrenia and Autism Candidate Genes in an Induced Pluripotent Stem Cell Model of the Human Telencephalon](https://doi.org/10.1371/journal.pone.0094968)
- サンプル条件: 39C for 24 hrs
- これも以前の研究で使用済み・解析に使用する
- ペア案: `control_1_he006_` vs `hs_1_he007_`
- ペア案: `control_2_he008_,` vs `hs_2_he009_`

In [27]:
GSE53667_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE53667/GSE53667_PEP/GSE53667_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (Qiagen)
    pl.lit("https://doi.org/10.1371/journal.pone.0094968").alias("reference_doi"), # add DOI of the reference paper column (PLOS ONE)
    pl.lit("39 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("1440 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature"), # add control temperature column
    pl.lit("neuronal aggregates (day 50) derived from induced pluripotent stem cells").alias("cell_line"), # Strictly, this is not cell line, but add this as sample
    
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE53667 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE53667_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE53667_filtered = GSE53667[[s.name for s in GSE53667 if not (s.null_count() == GSE53667.height)]]

GSE53667_combined = GSE53667_PEP.join(
    GSE53667_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE53667_combined = GSE53667_combined[[s.name for s in GSE53667_combined if not (s.null_count() == GSE53667_combined.height)]]

GSE53667_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE53667_modified_metadata.tsv",
    separator='\t'
)

# display(GSE53667_combined)

In [28]:
# Manual defined pairs
defined_pairs_gse53667 = [
    ("SRR1061343", "SRR1061341"),
    ("SRR1061344", "SRR1061342")
]

paired_metadata_df_gse53667 = create_paired_metadata(
    combined_df=GSE53667_combined, 
    defined_sample_pairs=defined_pairs_gse53667,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse53667 is not None:

    paired_metadata_df_gse53667.write_csv(
        "../../Data/metadata/metadata_paired/GSE53667_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse53667)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ sam ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ ple ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ _gr ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ oup ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ --- ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆ str ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HS_ ┆ GSM ┆ Pub ┆ Dec ┆ May ┆ SRA ┆ 1   ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Her ┆ her ┆ Beh ┆ Psy ┆ Alb ┆ 130 ┆ Bro ┆ NY  ┆ 104 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ 39C ┆ hg1 ┆ SAM ┆ unk ┆ htt ┆ 39  ┆ 144 ┆ 37  ┆ neu ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ cDN ┆ 202 ┆ 478 ┆ 305 ┆ ILL ┆ Gen ┆ HS_ ┆ SRP ┆ 324 ┆ Gen ┆ HS_ ┆ Ill ┆ Ill ┆ 655 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ tot ┆ GSM ┆ GEO ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE ┆ 3-d │
│ 106 ┆ 106 ┆ 1_h ┆ A   ┆ o   ┆ RED ┆     ┆ 106 ┆ 399 ┆ 1   ┆ 129 ┆ lic ┆ 26  ┆ 15  ┆     ┆     ┆ o   ┆ 6   ┆ al  ┆ 111 ┆ b,, ┆ b.l ┆ avi ┆ chi ┆ ert ┆ 0   ┆ nx  ┆     ┆ 61  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 129 ┆ E   ┆ 536 ┆     ┆ 399 ┆ for ┆ 9   ┆ N02 ┆ now ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ ron ┆ 106 ┆ umi ┆ o   ┆ 122 ┆ A   ┆ 0-0 ┆ 664 ┆ 014 ┆ UMI ┆ eri ┆ 1   ┆ 034 ┆ 401 ┆ e   ┆ 1   ┆ umi ┆ umi ┆ 290 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 129 ┆ 129 ┆ al  ┆ 129 ┆     ┆ 4-0 ┆ NA2 ┆ 519 ┆ 4-0 ┆ 536 ┆ ime │
│ 134 ┆ 134 ┆ e00 ┆     ┆ sap ┆     ┆     ┆ 134 ┆ 548 ┆ (HE ┆ 838 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 54  ┆ Lac ┆ ach ┆ ora ┆ atr ┆ Ein ┆ Mor ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 838 ┆     ┆ 67  ┆     ┆ 548 ┆ 24  ┆     ┆ 486 ┆ n   ┆ //d ┆     ┆ min ┆     ┆ al  ┆ 134 ┆ na  ┆ sap ┆ 385 ┆     ┆ 5-2 ┆ 489 ┆ 262 ┆ NA  ┆ c   ┆ (HE ┆ 737 ┆ 05  ┆ exp ┆ (HE ┆ na  ┆ na  ┆ 121 ┆ q   ┆ RIP ┆     ┆     ┆ 838 ┆ 838 ┆ cel ┆ 838 ┆     ┆ 7-0 ┆ 326 ┆ 982 ┆ 7-0 ┆ 67  ┆ nsi │
│ 3   ┆ 1   ┆ 7_  ┆     ┆ ien ┆     ┆     ┆ 3   ┆ vs  ┆ 007 ┆ 1   ┆ Jun ┆ 3   ┆ 9   ┆     ┆     ┆ ien ┆     ┆     ┆     ┆ hma ┆ man ┆ l   ┆ y   ┆ ste ┆ ris ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 1   ┆     ┆     ┆     ┆ vs  ┆ hrs ┆     ┆ 493 ┆     ┆ oi. ┆     ┆ .   ┆     ┆ agg ┆ 3   ┆ HiS ┆ ien ┆     ┆     ┆ 1   ┆ 0   ┆ 7;3 ┆     ┆     ┆ 007 ┆     ┆ vs  ┆ res ┆ 007 ┆ HiS ┆ HiS ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ lul ┆ 1   ┆     ┆ 3   ┆ 03  ┆ vs  ┆ 8   ┆     ┆ ona │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRX ┆ )   ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ n   ┆ @ei ┆ Gen ┆     ┆ in  ┆ Par ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ SRX ┆ vs  ┆     ┆ vs  ┆     ┆ org ┆     ┆     ┆     ┆ reg ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆     ┆ vs  ┆ 043 ┆     ┆     ┆ )   ┆     ┆ 307 ┆ sio ┆ )   ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ar  ┆ vs  ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆ l   │
│     ┆     ┆ con ┆     ┆     ┆     ┆     ┆ SRR ┆ 399 ┆ vs  ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nst ┆ eti ┆     ┆ Col ┆ k   ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ 399 ┆ 37C ┆     ┆ SAM ┆     ┆ /10 ┆     ┆     ┆     ┆ ate ┆ SRR ┆ 200 ┆     ┆     ┆     ┆     ┆ 455 ┆ 390 ┆     ┆     ┆ vs  ┆     ┆ 691 ┆ n   ┆ vs  ┆ 200 ┆ 200 ┆ 621 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ RNA ┆ GSM ┆     ┆     ┆     ┆ 519 ┆     ┆     ┆ neu │
│     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆ 106 ┆ 546 ┆ Con ┆ 129 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ein ┆ cs  ┆     ┆ leg ┆ Ave ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆     ┆ 546 ┆ con ┆     ┆ N02 ┆     ┆ .13 ┆     ┆     ┆     ┆ s   ┆ 106 ┆ 0   ┆     ┆     ┆     ┆     ┆ 462 ┆ 459 ┆     ┆     ┆ Con ┆     ┆ 08  ┆ pro ┆ Con ┆ 0   ┆ 0   ┆ 535 ┆     ┆     ┆     ┆     ┆ 129 ┆ GSM ┆ was ┆ 129 ┆     ┆     ┆     ┆ 980 ┆     ┆     ┆ ron │
│     ┆     ┆ l_1 ┆     ┆     ┆     ┆     ┆ 134 ┆     ┆ tro ┆ 837 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .yu ┆     ┆     ┆ e   ┆ .,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 837 ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ 486 ┆     ┆ 71/ ┆     ┆     ┆     ┆ (da ┆ 134 ┆ seq ┆     ┆     ┆     ┆     ┆ 341 ┆ vs  ┆     ┆     ┆ tro ┆     ┆     ┆ fil ┆ tro ┆     ┆ seq ┆ 981 ┆     ┆     ┆     ┆     ┆ 837 ┆ 129 ┆ iso ┆ 837 ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  │
│     ┆     ┆ _he ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ l_1 ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆ of  ┆ F10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 491 ┆     ┆ jou ┆     ┆     ┆     ┆ y   ┆ 1   ┆ uen ┆     ┆     ┆     ┆     ┆ 3   ┆ 289 ┆     ┆     ┆ l_1 ┆     ┆     ┆ ing ┆ l_1 ┆     ┆ uen ┆ 6   ┆     ┆     ┆     ┆     ┆ 9   ┆ 837 ┆ lat ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆ agg │
│     ┆     ┆ 006 ┆     ┆     ┆     ┆     ┆     ┆     ┆ (HE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ Med ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rna ┆     ┆     ┆     ┆ 50) ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 623 ┆     ┆     ┆ (HE ┆     ┆     ┆ in  ┆ (HE ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_r ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ reg │
│     ┆     ┆ _   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 006 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l.p ┆     ┆     ┆     ┆ der ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 663 ┆     ┆     ┆ 006 ┆     ┆     ┆ an  ┆ 006 ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ one ┆     ┆     ┆     ┆ ive ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 4;2 ┆     ┆     ┆ )   ┆     ┆     ┆ ind ┆ )   ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .00 ┆     ┆     ┆     ┆ d   ┆     ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ 899 ┆     ┆     ┆     ┆     ┆     ┆ uce ┆     ┆     ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tha │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 949 ┆     ┆     ┆     ┆ fro ┆     ┆ 838 ┆     ┆     ┆     ┆     ┆     ┆ 678 ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ 838 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ miR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 68  ┆     ┆     ┆     ┆ m   ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆ 793 ┆     ┆     ┆     ┆     ┆     ┆ plu ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ind ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sy  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ emb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uce ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ote ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆ (HE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆ (HE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Qi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ plu ┆     ┆ 007 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆     ┆ 007 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fir │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ st  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ote ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mes │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mod ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ el  ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tel │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ enc │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eph │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE233555 Ribo-Calibration (PAIRED)

- validation date: 2025-05-02
- [Calibrated ribosome profiling assesses the dynamics of ribosomal flux on transcripts](https://doi.org/10.1038/s41467-024-51258-0)
- 
- `For heat shock treatment, HEK293 cells cultured in 6-well plates were transferred to a water bath set at 43 °C and incubated for 0.5, 1, or 2 h. For recovery experiments, cells were returned to 37 °C and cultured for 0.5, 1, or 4 h.`
- リボソームのプロファイリング手法に関連する研究
- Homo sapiens のRNA-seqのデータを取得
- おそらく `RNA_HS...` で始まるデータが関連しているのでフィルタリング
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 13. GSE150922 (PAIRED) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [Efficient Heat Shock Response Affects Hyperthermia-Induced Radiosensitization in a Tumor Spheroid Control Probability Assay](https://doi.org/10.3390/cancers13133168)
- 以前の研究でも使用したデータ
- Radiotherapy と Heat stress (hyperthermia) のデータがある
- コントロールとHeat stress のデータを取得する
- Radiotherapy + Heat stress (RT + HT) の複合的なストレスを加えているデータは今回はフィルタリングしておく

In [29]:
GSE150922_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE150922/GSE150922_PEP/GSE150922_PEP_raw.csv",
    separator=','
).filter(
    ((pl.col("sample_title").str.contains(r'_Control_')) | (pl.col("sample_title").str.contains(r'_HT_')))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra II Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (NEW ENGLAND Biolabs)
    pl.lit("https://doi.org/10.3390/cancers13133168").alias("reference_doi"), # add DOI of the reference paper column (Cancers)
    pl.lit("42.5 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE150922 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE150922_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE150922_filtered = GSE150922[[s.name for s in GSE150922 if not (s.null_count() == GSE150922.height)]]

GSE150922_combined = GSE150922_PEP.join(
    GSE150922_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE150922_combined = GSE150922_combined[[s.name for s in GSE150922_combined if not (s.null_count() == GSE150922_combined.height)]]

GSE150922_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE150922_modified_metadata.tsv",
    separator='\t'
)

# display(GSE150922_combined)

In [30]:
# Manual defined pairs
defined_pairs_gse150922 = [
    ("SRR11817840", "SRR11817834"),
    ("SRR11817841", "SRR11817835"),
    ("SRR11817842", "SRR11817836"),
    ("SRR11817852", "SRR11817846"),
    ("SRR11817853", "SRR11817847"),
    ("SRR11817854", "SRR11817848")
]

paired_metadata_df_gse150922 = create_paired_metadata(
    combined_df=GSE150922_combined, 
    defined_sample_pairs=defined_pairs_gse150922,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse150922 is not None:

    paired_metadata_df_gse150922.write_csv(
        "../../Data/metadata/metadata_paired/GSE150922_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse150922)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_m ┆ atm ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ode ┆ ent ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ l   ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ --- ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ str ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ fad ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ FaD ┆ GSM ┆ Pub ┆ May ┆ Jul ┆ SRA ┆ 1   ┆ hea ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Ole ┆ ole ┆ Onc ┆ Han ┆ Dre ┆ 130 ┆ Ger ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ FaD ┆ sph ┆ Hyp ┆ mm9 ┆ SAM ┆ NEB ┆ htt ┆ 42. ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Nex ┆ SRA ┆ cDN ┆ 202 ┆ 199 ┆ 133 ┆ ILL ┆ Gen ┆ FaD ┆ SRP ┆ 208 ┆ Nex ┆ FaD ┆ Ill ┆ Ill ┆ 577 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ FaD ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 118 ┆ 118 ┆ u_h ┆ A   ┆ o   ┆ RED ┆     ┆ 118 ┆ 836 ┆ u_H ┆ 456 ┆ lic ┆ 20  ┆ 01  ┆     ┆     ┆ d-a ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ g,I ┆ h.c ┆ oRa ┆ del ┆ sde ┆ 7   ┆ man ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 456 ┆ E   ┆ 150 ┆     ┆ 836 ┆ u   ┆ ero ┆ ert ┆     ┆ N14 ┆ Nex ┆ ps: ┆ 5 C ┆ min ┆ C   ┆ 118 ┆ umi ┆ t   ┆ 107 ┆ A   ┆ 1-0 ┆ 740 ┆ 657 ┆ UMI ┆ eri ┆ u_H ┆ 262 ┆ 856 ┆ t   ┆ u_H ┆ umi ┆ umi ┆ 172 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 456 ┆ 456 ┆ al  ┆ 456 ┆     ┆ u   ┆ 1-0 ┆ NA6 ┆ 668 ┆ 1-0 ┆ 150 │
│ 178 ┆ 178 ┆ t_r ┆     ┆ sap ┆     ┆     ┆ 178 ┆ 880 ┆ T_R ┆ 102 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ nd- ┆ sap ┆     ┆ RNA ┆ 76  ┆ ,Ch ┆ hen ┆ y   ┆ all ┆ n   ┆     ┆ y   ┆ na  ┆     ┆ rip ┆ q   ┆ 102 ┆     ┆ 922 ┆     ┆ 880 ┆     ┆ ids ┆ her ┆     ┆ 981 ┆ t   ┆ //d ┆     ┆ .   ┆ (in ┆ 178 ┆ na  ┆ Gen ┆ 742 ┆     ┆ 7-0 ┆ 222 ┆ 878 ┆ NA  ┆ c   ┆ T_R ┆ 461 ┆ 13  ┆ Gen ┆ T_R ┆ na  ┆ na  ┆ 916 ┆ q   ┆ RIP ┆     ┆     ┆ 102 ┆ 102 ┆ cel ┆ 102 ┆     ┆     ┆ 7-0 ┆ 340 ┆ 429 ┆ 7-0 ┆ 922 │
│ 40  ┆ 34  ┆ ep1 ┆     ┆ ien ┆     ┆     ┆ 40  ┆ 7   ┆ ep1 ┆ 7   ┆ Jul ┆ 0   ┆ 1   ┆     ┆     ┆ nec ┆ ien ┆     ┆     ┆     ┆ en  ┆ @gm ┆     ┆ ee  ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆ mia ┆     ┆ 421 ┆ Ult ┆ oi. ┆     ┆     ┆ fer ┆ 40  ┆ Nov ┆ era ┆ 8   ┆     ┆ 4   ┆ 1   ┆ 5;1 ┆     ┆     ┆ ep1 ┆     ┆ vs  ┆ era ┆ ep1 ┆ Nov ┆ Nov ┆ 7   ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ lul ┆ 7   ┆     ┆     ┆ 4   ┆ 94  ┆ 4   ┆ 4   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆ k   ┆ s   ┆     ┆     ┆     ┆     ┆ ail ┆     ┆ 26  ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆ vs  ┆ ra  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ tio ┆     ┆     ┆     ┆ vs  ┆ 410 ┆     ┆     ┆ vs  ┆     ┆ 201 ┆ tio ┆ vs  ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ar  ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ fad ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ FaD ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ can ┆     ┆     ┆     ┆     ┆     ┆ .co ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆ Con ┆     ┆ SAM ┆ II  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ n   ┆     ┆     ┆     ┆ 192 ┆ 432 ┆     ┆     ┆ FaD ┆     ┆ 918 ┆ n   ┆ FaD ┆ q   ┆ q   ┆ 563 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ RNA ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ u_c ┆     ┆     ┆     ┆     ┆ 118 ┆ 836 ┆ u_C ┆ 456 ┆ 1   ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 456 ┆     ┆     ┆     ┆ 836 ┆     ┆     ┆ tro ┆     ┆ N14 ┆ Dir ┆ .33 ┆     ┆     ┆     ┆ 118 ┆ 600 ┆ Seq ┆     ┆     ┆     ┆ 563 ┆ 948 ┆     ┆     ┆ u_C ┆     ┆ 42  ┆ Seq ┆ u_C ┆ 600 ┆ 600 ┆ 359 ┆     ┆     ┆     ┆     ┆ 456 ┆ GSM ┆ was ┆ 456 ┆     ┆     ┆     ┆     ┆ 668 ┆     ┆     │
│     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆ 178 ┆ 880 ┆ ont ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆ 880 ┆     ┆     ┆ l   ┆     ┆ 981 ┆ ect ┆ 90/ ┆     ┆     ┆     ┆ 178 ┆ 0   ┆ uen ┆     ┆     ┆     ┆ 308 ┆ vs  ┆     ┆     ┆ ont ┆     ┆     ┆ uen ┆ ont ┆ 0   ┆ 0   ┆ 886 ┆     ┆     ┆     ┆     ┆ 102 ┆ 456 ┆ iso ┆ 102 ┆     ┆     ┆     ┆     ┆ 428 ┆     ┆     │
│     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆ 34  ┆ 1   ┆ rol ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 400 ┆ ion ┆ can ┆     ┆     ┆     ┆ 34  ┆ seq ┆ cin ┆     ┆     ┆     ┆ 9   ┆ 130 ┆     ┆     ┆ rol ┆     ┆     ┆ cin ┆ rol ┆     ┆ seq ┆ 7   ┆     ┆     ┆     ┆     ┆ 1   ┆ 102 ┆ lat ┆ 1   ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Re ┆     ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ cer ┆     ┆     ┆     ┆     ┆ uen ┆ g   ┆     ┆     ┆     ┆     ┆ 280 ┆     ┆     ┆ _Re ┆     ┆     ┆ g   ┆ _Re ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ s13 ┆     ┆     ┆     ┆     ┆ cin ┆ of  ┆     ┆     ┆     ┆     ┆ 876 ┆     ┆     ┆ p1  ┆     ┆     ┆ of  ┆ p1  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆ 133 ┆     ┆     ┆     ┆     ┆ g:  ┆ who ┆     ┆     ┆     ┆     ┆ 0;1 ┆     ┆     ┆     ┆     ┆     ┆ who ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ 168 ┆     ┆     ┆     ┆     ┆ GSM ┆ le  ┆     ┆     ┆     ┆     ┆ 352 ┆     ┆     ┆     ┆     ┆     ┆ le  ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 456 ┆ SAS ┆     ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆     ┆     ┆ SAS ┆     ┆     ┆ 456 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆ 102 ┆ and ┆     ┆     ┆     ┆     ┆ 453 ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FaD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆ FaD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FaD ┆     ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆ FaD ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ FaD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sph ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u_H ┆ sph ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sph ┆     ┆     ┆ u_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ero ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_R ┆ ero ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ero ┆     ┆     ┆ T_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ids ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆ ids ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ids ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nsc ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ tom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tom ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 14. GSE189578 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- おそらく以下の論文がこのデータの元になっている
- [Hyperthermia inhibits growth of nasopharyngeal carcinoma through degradation of c-Myc](https://doi.org/10.1080/02656736.2022.2038282)
- `human nasopharyngeal carcinoma cell lines` のCNE2 lineのデータに対して 43℃の熱曝露、およびおそらく30分間 (ここははっきりわからない...) を行っているデータ
- コントロール、熱曝露のデータが揃っているため、このデータは使用できると考え収集

In [31]:
GSE189578_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE189578/GSE189578_PEP/GSE189578_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq RNA Sample Preparation Kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1080/02656736.2022.2038282").alias("reference_doi"), # add DOI of the reference paper column (International Journal of Hyperthermia)
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE189578 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE189578_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE189578_filtered = GSE189578[[s.name for s in GSE189578 if not (s.null_count() == GSE189578.height)]]

GSE189578_combined = GSE189578_PEP.join(
    GSE189578_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE189578_combined = GSE189578_combined[[s.name for s in GSE189578_combined if not (s.null_count() == GSE189578_combined.height)]]

GSE189578_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE189578_modified_metadata.tsv",
    separator='\t'
)

# display(GSE189578_combined)

In [32]:
# Manual defined pairs
defined_pairs_gse189578 = [
    ("SRR17038864", "SRR17038861"),
    ("SRR17038865", "SRR17038862"),
    ("SRR17038866", "SRR17038863")
]

paired_metadata_df_gse189578 = create_paired_metadata(
    combined_df=GSE189578_combined, 
    defined_sample_pairs=defined_pairs_gse189578,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse189578 is not None:

    paired_metadata_df_gse189578.write_csv(
        "../../Data/metadata/metadata_paired/GSE189578_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse189578)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_t ┆ l_l ┆ atm ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ype ┆ ine ┆ ent ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ cne ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ CNE ┆ GSM ┆ Pub ┆ Nov ┆ Jun ┆ SRA ┆ 1   ┆ Nas ┆ Hom ┆ 960 ┆ pol ┆ C2_ ┆ GPL ┆ le, ┆ lix ┆ the ┆ wul ┆ zhe ┆ 450 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Nas ┆ CNE ┆ hea ┆ GRC ┆ SAM ┆ Tru ┆ htt ┆ 43  ┆ 30  ┆ 37  ┆ SRR ┆ Ill ┆ The ┆ SRA ┆ cDN ┆ 202 ┆ 192 ┆ 141 ┆ ILL ┆ Gen ┆ CNE ┆ SRP ┆ 198 ┆ The ┆ CNE ┆ Ill ┆ Ill ┆ Nas ┆ 595 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ CNE ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 170 ┆ 170 ┆ 2_h ┆ A   ┆ o   ┆ RED ┆     ┆ 170 ┆ 132 ┆ 2   ┆ 570 ┆ lic ┆ 25  ┆ 01  ┆     ┆     ┆ oph ┆ o   ┆ 6   ┆ yA  ┆ H1  ┆ 111 ┆ xia ┆ iao ┆ Fir ┆ iba ┆ ngz ┆ 000 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 570 ┆ E   ┆ 189 ┆     ┆ 132 ┆ oph ┆ 2   ┆ t   ┆ h38 ┆ N23 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 170 ┆ umi ┆ eff ┆ 133 ┆ A   ┆ 2-0 ┆ 525 ┆ 753 ┆ UMI ┆ eri ┆ 2   ┆ 347 ┆ 471 ┆ eff ┆ 2   ┆ umi ┆ umi ┆ oph ┆ 413 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 570 ┆ 570 ┆ al  ┆ 570 ┆     ┆ 2   ┆ 2-0 ┆ NA7 ┆ 111 ┆ 2-0 ┆ 189 │
│ 388 ┆ 388 ┆ t43 ┆     ┆ sap ┆     ┆     ┆ 388 ┆ 286 ┆ HT4 ┆ 414 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ ary ┆ sap ┆     ┆ RNA ┆ vs  ┆ 54  ┆ o,l ┆ le9 ┆ st  ┆ o   ┆ hou ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 414 ┆     ┆ 578 ┆     ┆ 286 ┆ ary ┆     ┆ vs  ┆ .91 ┆ 441 ┆ RNA ┆ //d ┆     ┆ .   ┆ (in ┆ 388 ┆ na  ┆ ect ┆ 498 ┆     ┆ 6-2 ┆ 348 ┆ 983 ┆ NA  ┆ c   ┆ HT4 ┆ 901 ┆ 03  ┆ ect ┆ HT4 ┆ na  ┆ na  ┆ ary ┆ 090 ┆ q   ┆ RIP ┆     ┆     ┆ 414 ┆ 414 ┆ RNA ┆ 414 ┆     ┆     ┆ 6-2 ┆ 836 ┆ 536 ┆ 6-2 ┆ 578 │
│ 64  ┆ 61  ┆ c_1 ┆     ┆ ien ┆     ┆     ┆ 64  ┆ 64  ┆ 3C  ┆ 6   ┆ Jun ┆ 1   ┆ 2   ┆     ┆     ┆ nge ┆ ien ┆     ┆     ┆ C2_ ┆     ┆ i   ┆ 299 ┆ Aff ┆ str ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 6   ┆     ┆     ┆     ┆ 64  ┆ nge ┆     ┆ con ┆     ┆ 146 ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆ 64  ┆ HiS ┆ of  ┆ 9   ┆     ┆ 1   ┆ 4   ┆ 2;1 ┆     ┆     ┆ 3C  ┆     ┆ vs  ┆ of  ┆ 3C  ┆ HiS ┆ HiS ┆ nge ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 6   ┆ 6_r ┆ was ┆ 6   ┆     ┆     ┆ 0   ┆ 44  ┆ 75  ┆ 0   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ 1   ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆ al  ┆ s   ┆     ┆     ┆ NC1 ┆     ┆     ┆ 29@ ┆ ili ┆ eet ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ al  ┆     ┆ tro ┆     ┆ vs  ┆ ple ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ hyp ┆     ┆     ┆     ┆ vs  ┆ 448 ┆     ┆     ┆ 1   ┆     ┆ 205 ┆ hyp ┆ 1   ┆ eq  ┆ eq  ┆ al  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ cne ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ vs  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆     ┆     ┆     ┆     ┆ yea ┆ ate ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ epi ┆     ┆ l   ┆     ┆ SAM ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 200 ┆ ert ┆     ┆     ┆     ┆ 198 ┆ 914 ┆     ┆     ┆ vs  ┆     ┆ 376 ┆ ert ┆ vs  ┆ 200 ┆ 200 ┆ epi ┆ 616 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ 2_c ┆     ┆     ┆     ┆     ┆ 170 ┆ 132 ┆ CNE ┆ 570 ┆ 2   ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.n ┆ d   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 570 ┆     ┆     ┆     ┆ 132 ┆ the ┆     ┆     ┆     ┆ N23 ┆ par ┆ .10 ┆     ┆     ┆     ┆ 170 ┆ 0   ┆ her ┆     ┆     ┆     ┆ 104 ┆ 861 ┆     ┆     ┆ CNE ┆     ┆ 00  ┆ her ┆ CNE ┆ 0   ┆ 0   ┆ the ┆ 128 ┆     ┆     ┆     ┆     ┆ 570 ┆ GSM ┆ ted ┆ 570 ┆     ┆     ┆     ┆     ┆ 111 ┆     ┆     │
│     ┆     ┆ trl ┆     ┆     ┆     ┆     ┆ 388 ┆ 286 ┆ 2   ┆ 414 ┆     ┆     ┆     ┆     ┆     ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆ et  ┆ Hos ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 414 ┆     ┆     ┆     ┆ 286 ┆ liu ┆     ┆     ┆     ┆ 441 ┆ ati ┆ 80/ ┆     ┆     ┆     ┆ 388 ┆ seq ┆ mia ┆     ┆     ┆     ┆ 951 ┆ vs  ┆     ┆     ┆ 2   ┆     ┆     ┆ mia ┆ 2   ┆     ┆ seq ┆ liu ┆ 000 ┆     ┆     ┆     ┆     ┆ 414 ┆ 570 ┆ wit ┆ 414 ┆     ┆     ┆     ┆     ┆ 536 ┆     ┆     │
│     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆ 61  ┆ 61  ┆ Ctr ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 61  ┆ m-d ┆     ┆     ┆     ┆ 143 ┆ on  ┆ 026 ┆     ┆     ┆     ┆ 61  ┆ uen ┆ on  ┆     ┆     ┆     ┆ 3   ┆ 146 ┆     ┆     ┆ Ctr ┆     ┆     ┆ on  ┆ Ctr ┆     ┆ uen ┆ m-d ┆ 0   ┆     ┆     ┆     ┆     ┆ 3   ┆ 414 ┆ h   ┆ 3   ┆     ┆     ┆     ┆     ┆ 72  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l 1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eri ┆     ┆     ┆     ┆     ┆ Kit ┆ 567 ┆     ┆     ┆     ┆     ┆ cin ┆ nas ┆     ┆     ┆     ┆     ┆ 594 ┆     ┆     ┆ l 1 ┆     ┆     ┆ nas ┆ l 1 ┆     ┆ cin ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ AMB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ved ┆     ┆     ┆     ┆     ┆     ┆ 36. ┆     ┆     ┆     ┆     ┆ g:  ┆ oph ┆     ┆     ┆     ┆     ┆ 987 ┆     ┆     ┆     ┆     ┆     ┆ oph ┆     ┆     ┆ g:  ┆ ved ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ION ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Zhe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆ GSM ┆ ary ┆     ┆     ┆     ┆     ┆ 2;1 ┆     ┆     ┆     ┆     ┆     ┆ ary ┆     ┆     ┆ GSM ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ngz ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ 2.2 ┆     ┆     ┆     ┆     ┆ 570 ┆ nge ┆     ┆     ┆     ┆     ┆ 491 ┆     ┆     ┆     ┆     ┆     ┆ nge ┆     ┆     ┆ 570 ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 560 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 038 ┆     ┆     ┆     ┆     ┆ 414 ┆ al  ┆     ┆     ┆     ┆     ┆ 314 ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆ 414 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆     ┆ 6:  ┆ car ┆     ┆     ┆     ┆     ┆ 395 ┆     ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆ 6:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CNE ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆ CNE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oma ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HT4 ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ HT4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3℃  ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ 3℃  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "Tr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uSe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 15. GSE227393 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-02
- [Comprehensive multi-omics analysis reveals WEE1 as a synergistic lethal target with hyperthermia through CDK1 super-activation](https://doi.org/10.1038/s41467-024-46358-w)
- OVCAR8 cells に対して hyperthemia (42℃) for 90 mins を曝露しているデータ (Ctrl は 37℃)
- しっかりペアのデータが存在しているので収集

In [33]:
GSE227393_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE227393/GSE227393_PEP/GSE227393_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("VAHTS mRNA-seq v2 Library Prep Kit for Illumina").alias("rna_library"), # add rna_library column from GEO webpage.
    pl.lit("https://doi.org/10.1038/s41467-024-46358-w").alias("reference_doi"), # add DOI of the reference paper column (Nature Communications)
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("90 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE227393 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE227393_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE227393_filtered = GSE227393[[s.name for s in GSE227393 if not (s.null_count() == GSE227393.height)]]

GSE227393_combined = GSE227393_PEP.join(
    GSE227393_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE227393_combined = GSE227393_combined[[s.name for s in GSE227393_combined if not (s.null_count() == GSE227393_combined.height)]]

GSE227393_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE227393_modified_metadata.tsv",
    separator='\t'
)

# display(GSE227393_combined)

In [34]:
# Manual defined pairs
defined_pairs_gse227393 = [
    ("SRR23868571", "SRR23868570"),
    ("SRR24982378", "SRR24982380"),
    ("SRR24982377", "SRR24982379")
]

paired_metadata_df_gse227393 = create_paired_metadata(
    combined_df=GSE227393_combined, 
    defined_sample_pairs=defined_pairs_gse227393,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse227393 is not None:

    paired_metadata_df_gse227393.write_csv(
        "../../Data/metadata/metadata_paired/GSE227393_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse227393)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 79)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ tre ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ atm ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _ex ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ ent ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ tra ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ct_ ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ pro ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ toc ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ ol_ ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ ch1 ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ ovc ┆ OVC ┆ GSM ┆ Pub ┆ Mar ┆ Dec ┆ SRA ┆ 1   ┆ Ova ┆ Hom ┆ 960 ┆ tot ┆ >2  ┆ GPL ┆ Hu, ┆ 同  ┆ 湖  ┆ 武  ┆ Hub ┆ 430 ┆ USA ┆ DNB ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Ova ┆ OVC ┆ ova ┆ hyp ┆ SAM ┆ VAH ┆ htt ┆ 42  ┆ 90  ┆ 37  ┆ SRR ┆ DNB ┆ Com ┆ SRA ┆ cDN ┆ 202 ┆ 439 ┆ 266 ┆ DNB ┆ mis ┆ Gen ┆ OVC ┆ SRP ┆ 221 ┆ Com ┆ OVC ┆ DNB ┆ DNB ┆ ova ┆ 665 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ >2  ┆ mis ┆ GSM ┆ OVC ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ Ova │
│ 238 ┆ 238 ┆ ar8 ┆ AR8 ┆ 709 ┆ lic ┆ 15  ┆ 12  ┆     ┆     ┆ ry  ┆ o   ┆ 6   ┆ al  ┆ ×   ┆ 280 ┆ ,Xi ┆ 济  ┆ 北  ┆ 汉  ┆ ei  ┆ 000 ┆     ┆ SEQ ┆ A   ┆ nsc ┆ -Se ┆ 709 ┆ E   ┆ 227 ┆     ┆ 196 ┆ ry  ┆ AR8 ┆ ria ┆ ert ┆ N33 ┆ TS  ┆ ps: ┆ C   ┆ min ┆ C   ┆ 238 ┆ SEQ ┆ pre ┆ 160 ┆ A   ┆ 3-1 ┆ 460 ┆ 911 ┆ SEQ ┆ sin ┆ eri ┆ AR8 ┆ 427 ┆ 851 ┆ pre ┆ AR8 ┆ SEQ ┆ SEQ ┆ ria ┆ 555 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 709 ┆ 709 ┆ ×   ┆ sin ┆ 709 ┆ AR8 ┆ 709 ┆ 3-1 ┆ NA9 ┆ 170 ┆ 3-1 ┆ 227 ┆ ry  │
│ 685 ┆ 685 ┆ _ht ┆ _HT ┆ 989 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 10^ ┆ 38  ┆ ngy ┆ 医  ┆ 武  ┆     ┆     ┆     ┆     ┆ -G4 ┆     ┆ rip ┆ q   ┆ 989 ┆     ┆ 393 ┆     ┆ 806 ┆     ┆     ┆ n   ┆ her ┆ 768 ┆ mRN ┆ //d ┆     ┆ .   ┆ (in ┆ 685 ┆ -G4 ┆ hen ┆ 486 ┆     ┆ 2-1 ┆ 156 ┆ 439 ┆     ┆ g   ┆ c   ┆ _HT ┆ 401 ┆ 97  ┆ hen ┆ _HT ┆ -G4 ┆ -G4 ┆ n   ┆ 910 ┆ q   ┆ RIP ┆     ┆     ┆ 989 ┆ 989 ┆ 10^ ┆ g   ┆ 989 ┆     ┆ 989 ┆ 2-1 ┆ 449 ┆ 500 ┆ 2-1 ┆ 393 ┆     │
│ 71  ┆ 70  ┆ _1  ┆ _1  ┆ 8   ┆ Dec ┆ 3   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ 6   ┆     ┆ uan ┆ 院  ┆ 汉  ┆     ┆     ┆     ┆     ┆ 00  ┆     ┆ tom ┆     ┆ 8   ┆     ┆     ┆     ┆ 23  ┆     ┆     ┆ can ┆ mia ┆ 760 ┆ A-s ┆ oi. ┆     ┆     ┆ fer ┆ 71  ┆ 00  ┆ siv ┆ 8   ┆     ┆ 5   ┆ 6   ┆ 2;2 ┆     ┆     ┆     ┆ _1  ┆     ┆ vs  ┆ siv ┆ _1  ┆ 00  ┆ 00  ┆ can ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 8   ┆ 8_r ┆ 6   ┆     ┆ 8_r ┆     ┆ 8   ┆ 5   ┆ 42  ┆ 65  ┆ 5   ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 12  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ cer ┆ sti ┆ vs  ┆ eq  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ seq ┆ e   ┆     ┆     ┆     ┆ vs  ┆ 784 ┆     ┆     ┆     ┆ vs  ┆     ┆ 222 ┆ e   ┆ vs  ┆     ┆ seq ┆ cer ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ cel ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ ovc ┆ OVC ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆ cel ┆ mul ┆ SAM ┆ v2  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ uen ┆ mul ┆     ┆     ┆     ┆ 442 ┆ 359 ┆     ┆     ┆     ┆ OVC ┆     ┆ 063 ┆ mul ┆ OVC ┆     ┆ uen ┆ cel ┆ 666 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ ls  ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ ar8 ┆ AR8 ┆ 709 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 709 ┆     ┆     ┆     ┆ 196 ┆     ┆     ┆ l   ┆ ati ┆ N33 ┆ Lib ┆ .10 ┆     ┆     ┆     ┆ 238 ┆ cin ┆ ti- ┆     ┆     ┆     ┆ 175 ┆ 530 ┆     ┆     ┆     ┆ AR8 ┆     ┆ 09  ┆ ti- ┆ AR8 ┆     ┆ cin ┆ l   ┆ 189 ┆     ┆     ┆     ┆     ┆ 709 ┆ GSM ┆ wer ┆     ┆ GSM ┆     ┆ 709 ┆     ┆     ┆ 170 ┆     ┆     ┆     │
│     ┆     ┆ _ct ┆ _Ct ┆ 989 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 989 ┆     ┆     ┆     ┆ 806 ┆     ┆     ┆     ┆ on  ┆ 768 ┆ rar ┆ 38/ ┆     ┆     ┆     ┆ 685 ┆ g:  ┆ omi ┆     ┆     ┆     ┆ 084 ┆ vs  ┆     ┆     ┆     ┆ _Ct ┆     ┆     ┆ omi ┆ _Ct ┆     ┆ g:  ┆     ┆ 270 ┆     ┆     ┆     ┆     ┆ 989 ┆ 709 ┆ e   ┆     ┆ 709 ┆     ┆ 989 ┆     ┆     ┆ 500 ┆     ┆     ┆     │
│     ┆     ┆ rl_ ┆ rl_ ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 24  ┆     ┆     ┆     ┆ vs  ┆ 761 ┆ y   ┆ s41 ┆     ┆     ┆     ┆ 70  ┆ GSM ┆ cs  ┆     ┆     ┆     ┆ 8   ┆ 267 ┆     ┆     ┆     ┆ rl_ ┆     ┆     ┆ cs  ┆ rl_ ┆     ┆ GSM ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 7   ┆ 989 ┆ col ┆     ┆ 989 ┆     ┆ 7   ┆     ┆     ┆ 66  ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ Pre ┆ 467 ┆     ┆     ┆     ┆     ┆ 709 ┆ ana ┆     ┆     ┆     ┆     ┆ 351 ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ana ┆ 1   ┆     ┆ 709 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_r ┆ lec ┆     ┆ 7_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ p   ┆ -02 ┆     ┆     ┆     ┆     ┆ 989 ┆ lys ┆     ┆     ┆     ┆     ┆ 714 ┆     ┆     ┆     ┆     ┆     ┆     ┆ lys ┆     ┆     ┆ 989 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ted ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ Kit ┆ 4-4 ┆     ┆     ┆     ┆     ┆ 8:  ┆ is  ┆     ┆     ┆     ┆     ┆ 1;2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ is  ┆     ┆     ┆ 8:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ 635 ┆     ┆     ┆     ┆     ┆ OVC ┆ rev ┆     ┆     ┆     ┆     ┆ 823 ┆     ┆     ┆     ┆     ┆     ┆     ┆ rev ┆     ┆     ┆ OVC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ olv ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆ 8-w ┆     ┆     ┆     ┆     ┆ AR8 ┆ eal ┆     ┆     ┆     ┆     ┆ 317 ┆     ┆     ┆     ┆     ┆     ┆     ┆ eal ┆     ┆     ┆ AR8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ olv ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆ _HT ┆ ed  ┆     ┆     ┆     ┆     ┆ 431 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆ _HT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆ WEE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEE ┆     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ as  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ as  ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Ta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Ta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ syn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ syn ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ erg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erg ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 910 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ ist ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ist ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 910 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ let ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ let ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ hal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hal ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DNB ┆ tar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tar ┆     ┆     ┆ DNB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SEQ ┆ get ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ get ┆     ┆     ┆ SEQ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -G4 ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆ -G4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Concat dataframe (RNA-seq only)

In [35]:
dfs_rna_seq_all: list[pl.DataFrame | None] = [
        # Single-end
        paired_metadata_df_gse253874,
        paired_metadata_df_gse235351,
        paired_metadata_df_gse124609_rna_seq,
        paired_metadata_df_gse115973,
        paired_metadata_df_gse79680,

        # Paired-end
        paired_metadata_df_gse267930,
        paired_metadata_df_gse271918,
        paired_metadata_df_gse259306,
        paired_metadata_df_gse247417,
        paired_metadata_df_gse159802,
        paired_metadata_df_gse73471,
        paired_metadata_df_gse53667,
        paired_metadata_df_gse150922,
        paired_metadata_df_gse189578,
        paired_metadata_df_gse227393
]

dfs_rna_seq:  list[pl.DataFrame] = [df for df in dfs_rna_seq_all if df is not None]

In [36]:
rna_seq_true_control = pl.concat(dfs_rna_seq, how="diagonal")

rna_seq_true_control.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_true_control_metadata_{execute_date}.tsv",
    separator='\t'
)