# GEO Metadata validated and modified process (Gemini-2.0-flash TRUE & Infered has control FALSE)

- ヒトの熱ストレスに関連するRNA-Seqにおいて、Gemini-2.0-flash の判断と自分の判断の結果、解析に使用するに値するデータのメタデータを整理するnotebook
- 整理する際、なぜこのような処理をするのかについても記載する
- `geofetch`から取得したデータと`iseq`から取得したデータ
- [../GenAI_validate/geo_metadata_genai_validation_true_no_control.tsv](../GenAI_validate/geo_metadata_genai_validation_true_no_control.tsv) に分類されたものについてここに記載する

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_cols(100)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

### GSE285529 (SINGLE) NO DOWNLOAD

- validate date 2025-05-02
- これらのデータはヒトのデータをフィルタリングすると熱ストレスを加えていないデータのみ残る
- **今回はこのデータは収集しない**

In [4]:
GSE285529_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE285529/GSE285529_PEP/GSE285529_PEP_raw.csv",
    separator=','
).filter(
    pl.col("sample_organism_ch1") == "Homo sapiens"
)

# display(GSE285529_PEP)

&nbsp;

&nbsp;

&nbsp;

## 1. GSE228346 (SINGLE, ~~PAIRED~~) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-02
- validate date 2026-05-04
- [TFIIH kinase CDK7 drives cell proliferation through a common core transcription factor network](https://doi.org/10.1126/sciadv.adr9660)
- 2025年の論文
- nacsent RNAを検出するPRO-seqとRNA-seqのデータが含まれている
- DMSOで処理されたコントロールと42℃で処理された熱ストレスのサンプル (例: `DMSO_0_R1, DMSO_20_R1`) と、CDK阻害剤である `SY5609` を処理された状態でのコントロールと熱ストレスの状態 ( `SY5609_0_R1, SY5609_20_R1`) が存在する
- コントロールと熱ストレスのデータが保存されているので解析に使用する
- PRO-seqとRNA-seqのデータを分けてメタデータを保存しておく
- PRO-seqのデータは[12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に移動
- 複数の温度条件があるので、ペアにした状態のデータフレームに、曝露時間を追記する

&nbsp;

### ストレスの例

- `DMSO_0_R1` → `_0_` 30min pretreatment with DMSO at 37C followed by a 42C heat shock for 0min with a 0min recovery at 37C
- `SY5609_0_R1` → `_0_` 30min pretreatment with SY5609 at 37C followed by a 42C heat shock for 0min with a 0min recovery at 37C
- `	DMSO_30_R1` → `_30_` 30min pretreatment with DMSO at 37C followed by a 42C heat shock for 30min with a 60min recovery at 37C
- `SY5609_30_R1` → `_30_` 30min pretreatment with SY5609 at 37C followed by a 42C heat shock for 30min with a 60min recovery at 37C
- `DMSO_120_R1` → `_120_` 30min pretreatment with DMSO at 37C followed by a 42C heat shock for 120min with a 0min recovery at 37C
- `SY5609_120_R1` → `_120_` 30min pretreatment with SY5609 at 37C followed by a 42C heat shock for 120min with a 0min recovery at 37C

In [5]:
GSE228346_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE228346/GSE228346_PEP/GSE228346_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep Kit").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1126/sciadv.adr9660").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# RNA-seq metadata
GSE228346_PEP_rna_seq = GSE228346_PEP.filter(
    (pl.col("sample_library_selection") == "cDNA") &
    (pl.col("sample_library_strategy") == "RNA-Seq")
)

# metadata from iseq
GSE228346_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE228346_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE228346_iseq_filtered = GSE228346_iseq[[s.name for s in GSE228346_iseq if not (s.null_count() == GSE228346_iseq.height)]]

GSE228346_rna_seq_combined = GSE228346_PEP_rna_seq.join(
    GSE228346_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE228346_rna_seq_combined = GSE228346_rna_seq_combined[[s.name for s in GSE228346_rna_seq_combined if not (s.null_count() == GSE228346_rna_seq_combined.height)]]

GSE228346_rna_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE228346_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE228346_rna_seq_combined)

In [6]:
# RNA-seq
defined_pairs_gse228346_rna_seq = [
    # DMSO
    ("SRR23989391", "SRR23989385"), # dmso_30_r1 (heat-stress) vs dmso_0_r1 (control)
    ("SRR23989368", "SRR23989386"), # dmso_30_r2 (heat-stress) vs dmso_0_r2 (control)
    ("SRR23989360", "SRR23989387"), # dmso_30_r3 (heat-stress) vs dmso_0_r3 (control)
    ("SRR23989364", "SRR23989385"), # dmso_120_r1 (heat-stress) vs dmso_0_r1 (control)
    ("SRR23989365", "SRR23989386"), # dmso_120_r2 (heat-stress) vs dmso_0_r2 (control)
    ("SRR23989366", "SRR23989387"), # dmso_120_r3 (heat-stress) vs dmso_0_r3 (control)
    # SY5609
    ("SRR23989361", "SRR23989388"), # sy5609_30_r1 (heat-stress) vs sy5609_0_r1 (control)
    ("SRR23989362", "SRR23989389"), # sy5609_30_r2 (heat-stress) vs sy5609_0_r2 (control)
    ("SRR23989363", "SRR23989390"), # sy5609_30_r3 (heat-stress) vs sy5609_0_r3 (control)
    ("SRR23989367", "SRR23989388"), # sy5609_120_r1 (heat-stress) vs sy5609_0_r1 (control)
    ("SRR23989380", "SRR23989389"), # sy5609_120_r2 (heat-stress) vs sy5609_0_r2 (control)
    ("SRR23989379", "SRR23989390")  # sy5609_120_r3 (heat-stress) vs sy5609_0_r3 (control)
]

paired_metadata_df_gse228346_rna_seq = create_paired_metadata(
    combined_df=GSE228346_rna_seq_combined, 
    defined_sample_pairs=defined_pairs_gse228346_rna_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)



if paired_metadata_df_gse228346_rna_seq is not None:
    paired_metadata_df_gse228346_rna_seq = paired_metadata_df_gse228346_rna_seq.with_columns(
    (pl.when(pl.col("sample_name").str.contains("_30_"))
    .then(pl.lit("30 min."))
    .when(pl.col("sample_name").str.contains("_120_"))
    .then(pl.lit("120 min."))
    .otherwise(pl.lit(""))
    .alias("stress treatment time"))
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse228346_rna_seq)

    paired_metadata_df_gse228346_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE228346_rna_seq_paired_metadata.tsv",
        separator='\t'
        )

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ tim ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ str │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ e   ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ ess │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ --- ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ tre │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ atm │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆     ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ ent │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ tim │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆ e   │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ dms ┆ DMS ┆ GSM ┆ Pub ┆ Mar ┆ Dec ┆ SRA ┆ 1   ┆ wil ┆ Hom ┆ 960 ┆ tot ┆ RNA ┆ GPL ┆ Tay ┆ taj ┆ 360 ┆ Uni ┆ 341 ┆ Bou ┆ CO  ┆ 803 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Wil ┆ ova ┆ 30m ┆ 120 ┆ hg3 ┆ NOT ┆ SAM ┆ KAP ┆ htt ┆ 42  ┆ 37  ┆ SRR ┆ Ill ┆ The ┆ SRA ┆ cDN ┆ 202 ┆ 954 ┆ 680 ┆ ILL ┆ Gen ┆ DMS ┆ SRP ┆ 931 ┆ The ┆ DMS ┆ Ill ┆ Ill ┆ ova ┆ 281 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ Wil ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ 30  │
│ 239 ┆ 239 ┆ o_3 ┆ O_3 ┆ 711 ┆ lic ┆ 28  ┆ 19  ┆     ┆     ┆ d   ┆ o   ┆ 6   ┆ al  ┆ -se ┆ 246 ┆ lor ┆ o59 ┆ 624 ┆ ver ┆ 5   ┆ lde ┆     ┆ 01  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 711 ┆ E   ┆ 228 ┆     ┆ 197 ┆ d-t ┆ ria ┆ in  ┆ vs  ┆ 8   ┆ PRO ┆ N33 ┆ A   ┆ ps: ┆ C   ┆ C   ┆ 239 ┆ umi ┆ TFI ┆ 161 ┆ A   ┆ 4-1 ┆ 329 ┆ 478 ┆ UMI ┆ eri ┆ O_3 ┆ 429 ┆ 493 ┆ TFI ┆ O_3 ┆ umi ┆ umi ┆ ria ┆ 311 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 711 ┆ 711 ┆ -se ┆ 711 ┆ d-t ┆ 711 ┆ 4-1 ┆ NA9 ┆ 171 ┆ 4-1 ┆ 228 ┆ min │
│ 893 ┆ 893 ┆ 0_r ┆ 0_R ┆ 926 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ typ ┆ sap ┆     ┆ RNA ┆ q   ┆ 76  ┆ ,K, ┆ 12@ ┆ 661 ┆ sit ┆ Col ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 926 ┆     ┆ 346 ┆     ┆ 932 ┆ ype ┆ n   ┆ pre ┆ 30  ┆     ┆ VID ┆ 946 ┆ mRN ┆ //d ┆     ┆     ┆ 893 ┆ na  ┆ IH  ┆ 189 ┆     ┆ 2-2 ┆ 818 ┆ 309 ┆ NA  ┆ c   ┆ 0_R ┆ 713 ┆ 47  ┆ IH  ┆ 0_R ┆ na  ┆ na  ┆ n   ┆ 027 ┆ q   ┆ RIP ┆     ┆     ┆ 926 ┆ 926 ┆ q:  ┆ 926 ┆ ype ┆ 926 ┆ 2-2 ┆ 495 ┆ 557 ┆ 2-2 ┆ 346 ┆ .   │
│ 91  ┆ 85  ┆ 1   ┆ 1   ┆ 1   ┆ Dec ┆ 3   ┆ 4   ┆     ┆     ┆ e   ┆ ien ┆     ┆     ┆ fro ┆     ┆ Jon ┆ col ┆ 2   ┆ y   ┆ ora ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 1   ┆     ┆     ┆     ┆ 97  ┆ OV9 ┆ can ┆ tre ┆     ┆     ┆ ED  ┆ 057 ┆ A   ┆ oi. ┆     ┆     ┆ 91  ┆ Nov ┆ kin ┆ 3   ┆     ┆ 9   ┆ 4   ┆ 2;6 ┆     ┆     ┆ 1   ┆     ┆ vs  ┆ kin ┆ 1   ┆ Nov ┆ Nov ┆ can ┆ 94  ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ Cel ┆ 1_r ┆ OV9 ┆ 1   ┆ 9   ┆ 15  ┆ 13  ┆ 9   ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 19  ┆     ┆     ┆     ┆     ┆ OV9 ┆ s   ┆     ┆     ┆ m   ┆     ┆ es  ┆ ora ┆     ┆ of  ┆ do  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ 0   ┆ cer ┆ atm ┆     ┆     ┆     ┆ vs  ┆ Hyp ┆ org ┆     ┆     ┆ vs  ┆ aSe ┆ ase ┆     ┆     ┆     ┆ vs  ┆ 902 ┆     ┆     ┆ vs  ┆     ┆ 982 ┆ ase ┆ vs  ┆ aSe ┆ aSe ┆ cer ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ls  ┆ 1   ┆ 0   ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ dms ┆ DMS ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ OV9 ┆     ┆     ┆ do. ┆     ┆ Col ┆ Ave ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ cel ┆     ┆ ent ┆     ┆     ┆     ┆ SAM ┆ erP ┆ /10 ┆     ┆     ┆ SRR ┆ q   ┆ CDK ┆     ┆     ┆     ┆ 101 ┆ 857 ┆     ┆     ┆ DMS ┆     ┆ 160 ┆ CDK ┆ DMS ┆ q   ┆ q   ┆     ┆ 296 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ wer ┆ vs  ┆ cel ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ o_0 ┆ O_0 ┆ 711 ┆ 4   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ edu ┆     ┆ ora ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 711 ┆     ┆     ┆     ┆ 197 ┆ ls  ┆     ┆ wit ┆     ┆     ┆     ┆ N33 ┆ rep ┆ .11 ┆     ┆     ┆ 239 ┆ 600 ┆ 7   ┆     ┆     ┆     ┆ 277 ┆ 738 ┆     ┆     ┆ O_0 ┆     ┆ 80  ┆ 7   ┆ O_0 ┆ 600 ┆ 600 ┆     ┆ 612 ┆     ┆     ┆     ┆     ┆ 711 ┆ GSM ┆ e   ┆ GSM ┆ ls  ┆ 711 ┆     ┆     ┆ 171 ┆     ┆     ┆     │
│     ┆     ┆ _r1 ┆ _R1 ┆ 925 ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ do  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 925 ┆     ┆     ┆     ┆ 932 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆ 946 ┆ Kit ┆ 26/ ┆     ┆     ┆ 893 ┆ 0   ┆ gov ┆     ┆     ┆     ┆ 083 ┆ vs  ┆     ┆     ┆ _R1 ┆     ┆     ┆ gov ┆ _R1 ┆ 0   ┆ 0   ┆     ┆ 561 ┆     ┆     ┆     ┆     ┆ 925 ┆ 711 ┆ the ┆ 711 ┆     ┆ 925 ┆     ┆     ┆ 556 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆ Bou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ 83  ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆ 063 ┆     ┆ sci ┆     ┆     ┆ 85  ┆ seq ┆ ern ┆     ┆     ┆     ┆ 10  ┆ 718 ┆     ┆     ┆     ┆     ┆     ┆ ern ┆     ┆     ┆ seq ┆     ┆ 60  ┆     ┆     ┆     ┆     ┆ 5   ┆ 925 ┆ n   ┆ 925 ┆     ┆ 5   ┆     ┆     ┆ 99  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆ lde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆ adv ┆     ┆     ┆     ┆ uen ┆ s   ┆     ┆     ┆     ┆     ┆ 386 ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_r ┆ har ┆ 5_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆ .ad ┆     ┆     ┆     ┆ cin ┆ RNA ┆     ┆     ┆     ┆     ┆ 787 ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ves ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _er ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆ r96 ┆     ┆     ┆     ┆ g:  ┆ pol ┆     ┆     ┆     ┆     ┆ 5;7 ┆     ┆     ┆     ┆     ┆     ┆ pol ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cc_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆ 60  ┆     ┆     ┆     ┆ GSM ┆ yme ┆     ┆     ┆     ┆     ┆ 368 ┆     ┆     ┆     ┆     ┆     ┆ yme ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 711 ┆ ras ┆     ┆     ┆     ┆     ┆ 144 ┆     ┆     ┆     ┆     ┆     ┆ ras ┆     ┆     ┆ 711 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 926 ┆ e   ┆     ┆     ┆     ┆     ┆ 859 ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 926 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ize ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1:  ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ ini ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ini ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_3 ┆ tia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tia ┆     ┆     ┆ O_3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_R ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ 0_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ txt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ nga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nga ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BS, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ scr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 30m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ape ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE272629 (SINGLE?) No Download

- validate date 2025-05-03
- [Passive shaping of intra- and intercellular m6A dynamics via mRNA metabolism](https://doi.org/10.7554/eLife.100448.2)
- `Camptothecin (CPT)` 処理を含むデータ、`Actinomycin D (ActD)`処理を含むデータが登録されている
- ヒト培養細胞のデータを見ると熱ストレス曝露のデータは含まれていないので今回は解析に使用しない

In [7]:
# GSE272629_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE272629/GSE272629_PEP/GSE272629_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# # display(GSE272629_PEP)

### GSE103233 (SINGLE?) No Download

- validate date 2025-05-03
- RNA-seqのデータはこれは記述を見ても熱ストレス曝露のデータではなかったので今回は収集しない

In [8]:
# GSE103233_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE103233/GSE103233_PEP/GSE103233_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_library_strategy") == "RNA-Seq"
# )

# # display(GSE103233_PEP)

### GSE116472 (SINGLE,PAIRED) NO DOWNLOAD

- validate date 2025-05-03
- [Single-molecule nascent RNA sequencing identifies regulatory domain architecture at promoters and enhancers](https://doi.org/10.1038/s41588-018-0234-5)
- ヒトだけのデータをフィルタリングしたところ、熱ストレス曝露のデータではなかったので、今回は収集しない

In [9]:
# GSE116472_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE116472/GSE116472_PEP/GSE116472_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# # display(GSE116472_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. GSE255207 (SINGLE) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-03
- [Dynamics of RNA localization to nuclear speckles are connected to splicing efficiency](https://doi.org/10.1126/sciadv.adp7727)
- `Nuclear speckles`という細胞小器官にあるRNAに関する研究
- 熱ストレスに曝露されたデータに加え、スプライシング阻害剤である`Pladienolide B (pladB)`処理を加えているサンプルが存在するのでこれをフィルタリングする
- また、`HepG2`細胞のサンプルは熱ストレスのデータが存在していないので、これもフィルタリングする
- `For heat shock treatment, HeLa cells were stressed at 43°C for 2 h.`
- MockとHeat shockのデータを収集する

In [10]:
GSE255207_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE255207/GSE255207_PEP/GSE255207_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("treatment") == "Pladienolide B treated") & # splicing inhibitor
    ~(pl.col("cell_line") == "HepG2")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("SMARTer Stranded Total RNA-Seq Kit v2").alias("rna_library"), # add rna_library column (Takara)
    pl.lit("https://doi.org/10.1126/sciadv.adp7727").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE255207_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE255207_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE255207_iseq_filtered = GSE255207_iseq[[s.name for s in GSE255207_iseq if not (s.null_count() == GSE255207_iseq.height)]]

GSE255207_combined = GSE255207_PEP.join(
    GSE255207_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE255207_combined = GSE255207_combined[[s.name for s in GSE255207_combined if not (s.null_count() == GSE255207_combined.height)]]

GSE255207_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE255207_modified_metadata.tsv",
    separator='\t'
)

# display(GSE255207_combined)

In [11]:
defined_pairs_gse255207 = [
    ("SRR27892100", "SRR27892104"), # hela_heatshock_rep1_polya_rna_seq (heat-stress) vs hela_mock_rep1_polya_rna_seq (control)
    ("SRR27892099", "SRR27892103"), # hela_heatshock_rep2_polya_rna_seq (heat-stress) vs hela_mock_rep2_polya_rna_seq (control)
    ("SRR27892092", "SRR27892096"), # hela_heatshock_rep1_nuclear_rna_seq (heat-stress) vs hela_mock_rep1_nuclear_rna_seq (control)
    ("SRR27892091", "SRR27892095"), # hela_heatshock_rep2_nuclear_rna_seq (heat-stress) vs hela_mock_rep2_nuclear_rna_seq (control)
]

paired_metadata_df_gse255207 = create_paired_metadata(
    combined_df=GSE255207_combined,
    defined_sample_pairs=defined_pairs_gse255207,
    sample_id_column_name="accession"
)


if paired_metadata_df_gse255207 is not None:
    paired_metadata_df_gse255207.write_csv(
        "../../Data/metadata/metadata_paired/GSE255207_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse255207)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hel ┆ HeL ┆ GSM ┆ Pub ┆ Feb ┆ Sep ┆ SRA ┆ 1   ┆ Cer ┆ Hom ┆ 960 ┆ pol ┆ GPL ┆ Jin ┆ jin ┆ 773 ┆ Fei ┆ The ┆ GCI ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ Cer ┆ WT  ┆ Hea ┆ hg3 ┆ SAM ┆ SMA ┆ htt ┆ 43  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ Dyn ┆ SRA ┆ cDN ┆ 202 ┆ 163 ┆ 241 ┆ ILL ┆ mis ┆ Gen ┆ HeL ┆ SRP ┆ 426 ┆ Dyn ┆ HeL ┆ Ill ┆ Ill ┆ Cer ┆ 516 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ mis ┆ GSM ┆ HeL ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 278 ┆ 278 ┆ a_h ┆ a_H ┆ 806 ┆ lic ┆ 06  ┆ 05  ┆     ┆     ┆ vic ┆ o   ┆ 6   ┆ yA  ┆ 246 ┆ gyi ┆ gyi ┆ 702 ┆ Lab ┆ Uni ┆ S   ┆ cag ┆     ┆ 37  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 806 ┆ :// ┆ 255 ┆     ┆ 235 ┆ a   ┆ vic ┆     ┆ t   ┆ 8   ┆ N39 ┆ RTe ┆ ps: ┆ C   ┆ min ┆ C   ┆ 278 ┆ umi ┆ ami ┆ 179 ┆ A   ┆ 4-0 ┆ 261 ┆ 689 ┆ UMI ┆ sin ┆ eri ┆ a_H ┆ 488 ┆ 917 ┆ ami ┆ a_H ┆ umi ┆ umi ┆ vic ┆ 569 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 806 ┆ 806 ┆ was ┆ sin ┆ 806 ┆ a   ┆ 806 ┆ 4-0 ┆ NA1 ┆ 203 ┆ 4-0 ┆ 255 │
│ 921 ┆ 921 ┆ eat ┆ eat ┆ 576 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ al  ┆ sap ┆     ┆ RNA ┆ 76  ┆ ,,F ┆ fei ┆ 437 ┆     ┆ ver ┆ W14 ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 576 ┆ ftp ┆ 207 ┆     ┆ 525 ┆     ┆ al  ┆     ┆ sho ┆     ┆ 845 ┆ r   ┆ //d ┆     ┆ .   ┆ (in ┆ 921 ┆ na  ┆ cs  ┆ 876 ┆     ┆ 9-2 ┆ 286 ┆ 054 ┆ NA  ┆ g   ┆ c   ┆ eat ┆ 515 ┆ 30  ┆ cs  ┆ eat ┆ na  ┆ na  ┆ al  ┆ 933 ┆ q   ┆ RIP ┆     ┆     ┆ 576 ┆ 576 ┆ ext ┆ g   ┆ 576 ┆     ┆ 576 ┆ 9-2 ┆ 073 ┆ 996 ┆ 9-2 ┆ 207 │
│ 00  ┆ 04  ┆ sho ┆ Sho ┆ 9   ┆ Sep ┆ 4   ┆ 4   ┆     ┆     ┆ can ┆ ien ┆     ┆     ┆     ┆ ei  ┆ @uc ┆ 0   ┆     ┆ sit ┆ 2,  ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 9   ┆ .nc ┆ ,   ┆     ┆ 98  ┆     ┆ can ┆     ┆ ck  ┆     ┆ 943 ┆ Str ┆ oi. ┆     ┆     ┆ fer ┆ 00  ┆ Nov ┆ of  ┆ 8   ┆     ┆ 9   ┆ 7   ┆ 7   ┆     ┆     ┆     ┆ Sho ┆     ┆ vs  ┆ of  ┆ Sho ┆ Nov ┆ Nov ┆ can ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 9   ┆ 9_r ┆ rac ┆     ┆ 9_r ┆     ┆ 9   ┆ 9   ┆ 951 ┆ 92  ┆ 9   ┆     │
│     ┆     ┆ ck_ ┆ ck_ ┆ vs  ┆ 05  ┆     ┆     ┆     ┆     ┆ cer ┆ s   ┆     ┆     ┆     ┆     ┆ hic ┆     ┆     ┆ y   ┆ 929 ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆ cer ┆     ┆ vs  ┆     ┆ vs  ┆ and ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ RNA ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆ ck_ ┆     ┆ 436 ┆ RNA ┆ ck_ ┆ aSe ┆ aSe ┆ cer ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ted ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ rep ┆ rep ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ ago ┆     ┆     ┆ of  ┆ E   ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 255 ┆     ┆ SRX ┆     ┆ cel ┆     ┆ Moc ┆     ┆ SAM ┆ ed  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ loc ┆     ┆     ┆     ┆ 164 ┆ 246 ┆     ┆     ┆     ┆ rep ┆     ┆ 166 ┆ loc ┆ rep ┆ q   ┆ q   ┆ cel ┆ 527 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ usi ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ 1_p ┆ 1_p ┆ 806 ┆ 4   ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆ Chi ┆ 57t ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 806 ┆ .ni ┆ 208 ┆     ┆ 235 ┆     ┆ ls  ┆     ┆ k   ┆     ┆ N39 ┆ Tot ┆ .11 ┆     ┆     ┆     ┆ 278 ┆ 600 ┆ ali ┆     ┆     ┆     ┆ 063 ┆ 212 ┆     ┆     ┆     ┆ 1_p ┆     ┆ 06  ┆ ali ┆ 1_p ┆ 600 ┆ 600 ┆ ls  ┆ 760 ┆     ┆     ┆     ┆     ┆ 806 ┆ GSM ┆ ng  ┆     ┆ GSM ┆     ┆ 806 ┆     ┆     ┆ 203 ┆     ┆     │
│     ┆     ┆ oly ┆ oly ┆ 576 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ cag ┆ h   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 576 ┆ h.g ┆     ┆     ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆ 845 ┆ al  ┆ 26/ ┆     ┆     ┆     ┆ 921 ┆ 0   ┆ zat ┆     ┆     ┆     ┆ 755 ┆ 611 ┆     ┆     ┆     ┆ oly ┆     ┆     ┆ zat ┆ oly ┆ 0   ┆ 0   ┆     ┆ 932 ┆     ┆     ┆     ┆     ┆ 576 ┆ 806 ┆ TRI ┆     ┆ 806 ┆     ┆ 576 ┆     ┆     ┆ 996 ┆     ┆     │
│     ┆     ┆ a_r ┆ A_R ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ Str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ ov/ ┆     ┆     ┆ 94  ┆     ┆     ┆     ┆     ┆     ┆ 947 ┆ RNA ┆ sci ┆     ┆     ┆     ┆ 04  ┆ seq ┆ ion ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆ A_R ┆     ┆     ┆ ion ┆ A_R ┆     ┆ seq ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆ 5   ┆ 576 ┆ zol ┆     ┆ 576 ┆     ┆ 5   ┆     ┆     ┆ 88  ┆     ┆     │
│     ┆     ┆ na_ ┆ NA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eet ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ adv ┆     ┆     ┆     ┆     ┆ uen ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA_ ┆     ┆     ┆ to  ┆ NA_ ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_r ┆ rea ┆     ┆ 5_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ .ad ┆     ┆     ┆     ┆     ┆ cin ┆ nuc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆ nuc ┆ seq ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ gen ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ p77 ┆     ┆     ┆     ┆     ┆ g:  ┆ lea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ lea ┆ vs  ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hel ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v2  ┆ 27  ┆     ┆     ┆     ┆     ┆ GSM ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆ r   ┆ HeL ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Th ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ a_m ┆ a_m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 806 ┆ spe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a_m ┆     ┆     ┆ spe ┆ a_m ┆     ┆ 806 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ock ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 806 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 576 ┆ ckl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆ ckl ┆ ock ┆     ┆ 576 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oFi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9:  ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆     ┆ es  ┆ _re ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ she ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1_ ┆ p1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆ are ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1_ ┆     ┆     ┆ are ┆ p1_ ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r). ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pol ┆ pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a_H ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pol ┆     ┆     ┆ con ┆ pol ┆     ┆ a_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ya_ ┆ yA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 065 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eat ┆ nec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yA_ ┆     ┆     ┆ nec ┆ yA_ ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rna ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 769 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sho ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ ted ┆ RNA ┆     ┆ Sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _se ┆ _se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck_ ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _se ┆     ┆     ┆ to  ┆ _se ┆     ┆ ck_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q   ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆ spl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆ spl ┆ q   ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_p ┆ ici ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆     ┆ 1_p ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M80 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oly ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆ oly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 657 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_R ┆ eff ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eff ┆     ┆     ┆ A_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 69_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA_ ┆ ici ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆     ┆ NA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. GSE270672 (SINGLE) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-03
- [An HSF1–JMJD6–HSP feedback circuit promotes cell adaptation to proteotoxic stress](https://doi.org/10.1073/pnas.2313370121)
- HSF1の活性化に関与する因子としてJMJD6を同定した論文で、silencingされたデータや、プロテアソーム阻害剤 MG132のデータが存在する
- `siJMJD6`の熱ショックを加えたデータは、コントロールがなかったので今回は収集しない
- [Appendix 01 (PDF)](https://www.pnas.org/doi/suppl/10.1073/pnas.2313370121/suppl_file/pnas.2313370121.sapp.pdf) にストレス条件が記載されている
- `siNT`の`basal` と`Heatshock42C(1h)`のデータを収集する

In [12]:
GSE270672_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE270672/GSE270672_PEP/GSE270672_PEP_raw.csv",
    separator=','
).filter(
    ((pl.col("treatment") == "Basal") | (pl.col("treatment") == "Heat shock 42C (1h), 2h Recovery")) &
    ~(pl.col("genotype") == "siJMJD6")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Lexogen QuantSeq FWD Kit").alias("rna_library"), # add rna_library column (Lexogen) from supplemetary information (S1 appendix)
    pl.lit("https://doi.org/10.1073/pnas.2313370121").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE270672_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE270672_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE270672_iseq_filtered = GSE270672_iseq[[s.name for s in GSE270672_iseq if not (s.null_count() == GSE270672_iseq.height)]]

GSE270672_combined = GSE270672_PEP.join(
    GSE270672_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE270672_combined = GSE270672_combined[[s.name for s in GSE270672_combined if not (s.null_count() == GSE270672_combined.height)]]

GSE270672_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE270672_modified_metadata.tsv",
    separator='\t'
)

# display(GSE270672_combined)

In [13]:
defined_pairs_gse270672 = [
    ("SRR29525025", "SRR29525028"), # ma_pc3m_sint_hs_1 (Heat shock 42C (1h), 2h Recovery) vs ma_pc3m_sint_1 (Basal)
    ("SRR29525024", "SRR29525027"), # ma_pc3m_sint_hs_2 (Heat shock 42C (1h), 2h Recovery) vs ma_pc3m_sint_2 (Basal)
    ("SRR29525023", "SRR29525026")  # ma_pc3m_sint_hs_3 (Heat shock 42C (1h), 2h Recovery) vs ma_pc3m_sint_3 (Basal)
]

paired_metadata_df_gse270672 = create_paired_metadata(
    combined_df=GSE270672_combined,
    defined_sample_pairs=defined_pairs_gse270672,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse270672 is not None:
    paired_metadata_df_gse270672.write_csv(
        "../../Data/metadata/metadata_paired/GSE270672_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse270672)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ l_c ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ ma_ ┆ MA_ ┆ GSM ┆ Pub ┆ Jun ┆ Jul ┆ SRA ┆ 1   ┆ PC3 ┆ Hom ┆ 960 ┆ Cel ┆ tot ┆ GPL ┆ Mar ┆ men ┆ 312 ┆ Mar ┆ Bio ┆ Nor ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ PC3 ┆ Pro ┆ siN ┆ Hea ┆ hg3 ┆ SAM ┆ Lex ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Nex ┆ An  ┆ SRA ┆ cDN ┆ 202 ┆ 896 ┆ 124 ┆ ILL ┆ mis ┆ Gen ┆ MA_ ┆ SRP ┆ 268 ┆ An  ┆ MA_ ┆ Nex ┆ Nex ┆ Pro ┆ 201 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ mis ┆ GSM ┆ PC3 ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 295 ┆ 295 ┆ pc3 ┆ PC3 ┆ 834 ┆ lic ┆ 24  ┆ 18  ┆     ┆     ┆ M   ┆ o   ┆ 6   ┆ ls  ┆ al  ┆ 185 ┆ c,L ┆ dil ┆ 503 ┆ c   ┆ che ┆ thw ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 834 ┆ E   ┆ 270 ┆     ┆ 250 ┆ M   ┆ sta ┆ T   ┆ t   ┆ 8   ┆ N42 ┆ oge ┆ ps: ┆ C   ┆ min ┆ C   ┆ 295 ┆ tSe ┆ HSF ┆ 190 ┆ A   ┆ 4-0 ┆ 468 ┆ 380 ┆ UMI ┆ sin ┆ eri ┆ PC3 ┆ 515 ┆ 369 ┆ HSF ┆ PC3 ┆ tSe ┆ tSe ┆ sta ┆ 907 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 834 ┆ 834 ┆ was ┆ sin ┆ 834 ┆ M   ┆ 834 ┆ 4-0 ┆ NA1 ┆ 217 ┆ 4-0 ┆ 270 │
│ 250 ┆ 250 ┆ m_s ┆ M_s ┆ 980 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ RNA ┆ 73  ┆ ,Me ┆ lo@ ┆ 486 ┆ Men ┆ mis ┆ est ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 980 ┆     ┆ 672 ┆     ┆ 350 ┆     ┆ te  ┆     ┆ sho ┆     ┆ 017 ┆ n   ┆ //d ┆     ┆ .   ┆ (in ┆ 250 ┆ q   ┆ 1-J ┆ 678 ┆     ┆ 7-2 ┆ 18  ┆ 977 ┆ NA  ┆ g   ┆ c   ┆ M_s ┆ 692 ┆ 1   ┆ 1-J ┆ M_s ┆ q   ┆ q   ┆ te  ┆ 067 ┆ q   ┆ RIP ┆     ┆     ┆ 980 ┆ 980 ┆ ext ┆ g   ┆ 980 ┆     ┆ 980 ┆ 7-2 ┆ 127 ┆ 342 ┆ 7-2 ┆ 672 │
│ 25  ┆ 28  ┆ int ┆ iNT ┆ 6   ┆ Jul ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆     ┆     ┆ ndi ┆ nor ┆ 2   ┆ dil ┆ try ┆ ern ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 6   ┆     ┆     ┆     ┆ 93  ┆     ┆ can ┆     ┆ ck  ┆     ┆ 738 ┆ Qua ┆ oi. ┆     ┆     ┆ fer ┆ 25  ┆ 500 ┆ MJD ┆ 3   ┆     ┆ 3   ┆ vs  ┆ vs  ┆     ┆     ┆     ┆ iNT ┆     ┆ vs  ┆ MJD ┆ iNT ┆ 500 ┆ 500 ┆ can ┆ vs  ┆     ┆ TOM ┆     ┆     ┆ 6   ┆ 6_r ┆ rac ┆     ┆ 6_r ┆     ┆ 6   ┆ 3   ┆ 665 ┆ 61  ┆ 3   ┆     │
│     ┆     ┆ _hs ┆ _HS ┆ vs  ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ gro ┆     ┆     ┆ llo ┆ thw ┆     ┆ lo  ┆ and ┆ Uni ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ cer ┆     ┆ 42C ┆     ┆ vs  ┆ ntS ┆ org ┆     ┆     ┆ red ┆ vs  ┆ seq ┆ 6-H ┆     ┆     ┆     ┆ 616 ┆ 863 ┆     ┆     ┆     ┆ _HS ┆     ┆ 182 ┆ 6-H ┆ _HS ┆     ┆ seq ┆ cer ┆ 137 ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ted ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ _1  ┆ _1  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wn  ┆     ┆     ┆     ┆ est ┆     ┆     ┆ Mol ┆ ver ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ cel ┆     ┆ (1h ┆     ┆ SAM ┆ eq  ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ uen ┆ SP  ┆     ┆     ┆     ┆ 274 ┆ 226 ┆     ┆     ┆     ┆ _1  ┆     ┆ 125 ┆ SP  ┆ _1  ┆     ┆ uen ┆ cel ┆ 162 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ usi ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 834 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ ern ┆     ┆     ┆ ecu ┆ sit ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 834 ┆     ┆     ┆     ┆ 250 ┆     ┆ ls  ┆     ┆ ),  ┆     ┆ N42 ┆ FWD ┆ .10 ┆     ┆     ┆     ┆ 295 ┆ cin ┆ fee ┆     ┆     ┆     ┆ 64  ┆ 99  ┆     ┆     ┆     ┆ vs  ┆     ┆ 1   ┆ fee ┆ vs  ┆     ┆ cin ┆ ls  ┆ 696 ┆     ┆     ┆     ┆     ┆ 834 ┆ GSM ┆ ng  ┆     ┆ GSM ┆     ┆ 834 ┆     ┆     ┆ 217 ┆     ┆     │
│     ┆     ┆ ma_ ┆ MA_ ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆ lar ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 980 ┆     ┆     ┆     ┆ 350 ┆     ┆     ┆     ┆ 2h  ┆     ┆ 017 ┆ Kit ┆ 73/ ┆     ┆     ┆     ┆ 250 ┆ g:  ┆ dba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MA_ ┆     ┆     ┆ dba ┆ MA_ ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 980 ┆ 834 ┆ the ┆     ┆ 834 ┆     ┆ 980 ┆     ┆     ┆ 342 ┆     ┆     │
│     ┆     ┆ pc3 ┆ PC3 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 90  ┆     ┆     ┆     ┆ Rec ┆     ┆ 741 ┆     ┆ pna ┆     ┆     ┆     ┆ 28  ┆ GSM ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PC3 ┆     ┆     ┆ ck  ┆ PC3 ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 980 ┆ Qia ┆     ┆ 980 ┆     ┆ 3   ┆     ┆     ┆ 58  ┆     ┆     │
│     ┆     ┆ m_s ┆ M_s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆ s.2 ┆     ┆     ┆     ┆     ┆ 834 ┆ cir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M_s ┆     ┆     ┆ cir ┆ M_s ┆     ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ gen ┆     ┆ 3_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ int ┆ iNT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5%  ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ry  ┆     ┆     ┆     ┆ 313 ┆     ┆     ┆     ┆     ┆ 980 ┆ cui ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iNT ┆     ┆     ┆ cui ┆ iNT ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ RNe ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _1  ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CO2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ 370 ┆     ┆     ┆     ┆     ┆ 6:  ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆     ┆     ┆ t   ┆ _1  ┆     ┆ 6:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆     ┆ 121 ┆     ┆     ┆     ┆     ┆ MA_ ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆ MA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PC3 ┆ mot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mot ┆     ┆     ┆ PC3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M_s ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆ M_s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iNT ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ iNT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆ ada ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ada ┆     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sup ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ pta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pta ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ teo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ teo ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ tox ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tox ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ies ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE255206 (SINGLE) NO DOWNLOAD

- validate date:2025-05-03
- [Dynamics of RNA localization to nuclear speckles are connected to splicing efficiency](https://doi.org/10.1126/sciadv.adp7727)
- ARTR-seq (reverse transcription–based RNA binding protein binding sites sequencing) という手法のデータ
- ARTR-Seqの論文: [Profiling of RNA-binding protein binding sites by in situ reverse transcription-based sequencing](https://doi.org/10.1038/s41592-023-02146-w)
- GSE255207の論文の別のプロジェクト
- 今回はこのデータは収集しない

### GSE173537 (SINGLE) PRO-seq

- validate date: 2025-05-03
- [Characterizing primary transcriptional responses to short term heat shock in Down syndrome](https://doi.org/10.1371/journal.pone.0307375)
- 全てPRO-seqのデータで、chromosome 21 trisomic のデータも登録されている
- [12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に処理を移動

### GSE197992 (SINGLE) TT-chem-seq

- validation date: 2025-05-03
- [An Important Role for RPRD1B in the Heat Shock Response](https://pmc.ncbi.nlm.nih.gov/articles/PMC9583720/)
- おそらく上記の論文由来のデータ
- RPRD1Bの機能を調査しているデータ
- TTchem-seqのデータのプロジェクト
- コントロールデータと熱ストレス曝露のデータが揃っている
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. GSE197993 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- validation date: 2026-05-04
- [An Important Role for RPRD1B in the Heat Shock Response](https://pmc.ncbi.nlm.nih.gov/articles/PMC9583720/)
- おそらく上記の論文由来のデータ (このデータはGEOのsubseries)
- RPRD1Bの機能を調査しているデータ
- こちらはRNA-seqのデータのプロジェクト
- コントロールデータと熱ストレス曝露のデータが揃っている
- 曝露時間についてはメタデータに記載があったものの、温度条件が見つからない
- [Supplementary Material](https://pmc.ncbi.nlm.nih.gov/articles/instance/9583720/bin/mcb.00173-22-s0008.pdf) にキットや温度条件の記載がある
- 収集する

In [ ]:
GSE197993_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE197993/GSE197993_PEP/GSE197993_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep Kit").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1128/mcb.00173-22").alias("reference_doi"), # add DOI of the reference paper column (間違っていたので修正)
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE197993_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE197993_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE197993_iseq_filtered = GSE197993_iseq[[s.name for s in GSE197993_iseq if not (s.null_count() == GSE197993_iseq.height)]]

GSE197993_combined = GSE197993_PEP.join(
    GSE197993_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE197993_combined = GSE197993_combined[[s.name for s in GSE197993_combined if not (s.null_count() == GSE197993_combined.height)]]

GSE197993_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE197993_modified_metadata.tsv",
    separator='\t'
)

# display(GSE197993_combined)

In [15]:
defined_pairs_gse197993 = [
    ("SRR18248924", "SRR18248925"), # HS_siNT_B1 [RNA-seq] (120min heat shock) vs NHS_siNT_B1 [RNA-seq] (No heat shock)
    ("SRR18248920", "SRR18248921"), # HS_siNT_B2 [RNA-seq] (120min heat shock) vs NHS_siNT_B2 [RNA-seq] (No heat shock)
    ("SRR18248916", "SRR18248917"), # HS_siNT_B3 [RNA-seq] (120min heat shock) vs NHS_siNT_B3 [RNA-seq] (No heat shock)
    ("SRR18248922", "SRR18248923"), # HS_siRPRD1B_B1 [RNA-seq] (120min heat shock) vs NHS_siRPRD1B_B1 [RNA-seq] (No heat shock)
    ("SRR18248918", "SRR18248919"), # HS_siRPRD1B_B2 [RNA-seq] (120min heat shock) vs NHS_siRPRD1B_B2 [RNA-seq] (No heat shock)
    ("SRR18248914", "SRR18248915")  # HS_siRPRD1B_B3 [RNA-seq] (120min heat shock) vs NHS_siRPRD1B_B3 [RNA-seq] (No heat shock)
]

paired_metadata_df_gse197993 = create_paired_metadata(
    combined_df=GSE197993_combined,
    defined_sample_pairs=defined_pairs_gse197993,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse197993 is not None:
    paired_metadata_df_gse197993.write_csv(
        "../../Data/metadata/metadata_paired/GSE197993_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse197993)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 75)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ sir ┆ con ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ na  ┆ dit ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ --- ┆ ion ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ str ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆     ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ HS_ ┆ GSM ┆ Pub ┆ Mar ┆ Sep ┆ SRA ┆ 1   ┆ MRC ┆ Hom ┆ 960 ┆ pol ┆ CUG ┆ GPL ┆ Ric ┆ Bio ┆ The ┆ 1   ┆ Lon ┆ LON ┆ NW1 ┆ Uni ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ MRC ┆ non ┆ 120 ┆ GRC ┆ SAM ┆ KAP ┆ htt ┆ 43  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ RPR ┆ SRA ┆ cDN ┆ 202 ┆ 155 ┆ 240 ┆ ILL ┆ HS_ ┆ SRP ┆ 500 ┆ RPR ┆ HS_ ┆ Ill ┆ Ill ┆ 505 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ MRC ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 182 ┆ 182 ┆ sin ┆ siN ┆ 593 ┆ lic ┆ 06  ┆ 08  ┆     ┆     ┆ 5-V ┆ o   ┆ 6   ┆ yA  ┆ 440 ┆ 246 ┆ har ┆ inf ┆ Fra ┆ Mid ┆ don ┆ DON ┆ 1AT ┆ ted ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 593 ┆ :// ┆ 197 ┆     ┆ 143 ┆ 5-V ┆ -ta ┆ min ┆ h38 ┆ N26 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ 182 ┆ umi ┆ D1B ┆ 138 ┆ A   ┆ 2-0 ┆ 309 ┆ 703 ┆ UMI ┆ siN ┆ 362 ┆ 119 ┆ D1B ┆ siN ┆ umi ┆ umi ┆ 120 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 593 ┆ 593 ┆ was ┆ 593 ┆ 5-V ┆ 593 ┆ 2-0 ┆ NA8 ┆ 122 ┆ 2-0 ┆ 197 │
│ 489 ┆ 489 ┆ t_b ┆ T_B ┆ 541 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ A   ┆ sap ┆     ┆ RNA ┆ 9A2 ┆ 76  ┆ d,J ┆ orm ┆ nci ┆ lan ┆     ┆     ┆     ┆ Kin ┆ na  ┆     ┆ rip ┆ q   ┆ 541 ┆ ftp ┆ 993 ┆     ┆ 902 ┆ A   ┆ rge ┆ hea ┆     ┆ 491 ┆ mRN ┆ //d ┆     ┆ .   ┆ (in ┆ 489 ┆ na  ┆ is  ┆ 150 ┆     ┆ 9-0 ┆ 053 ┆ 743 ┆ NA  ┆ T_B ┆ 755 ┆ 12  ┆ is  ┆ T_B ┆ na  ┆ na  ┆ 311 ┆ q   ┆ RIP ┆     ┆     ┆ 541 ┆ 541 ┆ ext ┆ 541 ┆ A   ┆ 541 ┆ 9-0 ┆ 133 ┆ 007 ┆ 9-0 ┆ 993 │
│ 24  ┆ 25  ┆ 1_r ┆ 1   ┆ 5   ┆ Sep ┆ 2   ┆ 2   ┆     ┆     ┆ cel ┆ ien ┆     ┆     ┆ ,   ┆     ┆ ame ┆ ati ┆ s   ┆ d   ┆     ┆     ┆     ┆ gdo ┆ Nov ┆     ┆ tom ┆     ┆ 5   ┆ .nc ┆ ,   ┆     ┆ 90  ┆     ┆ tin ┆ t   ┆     ┆ 009 ┆ A   ┆ oi. ┆     ┆     ┆ fer ┆ 24  ┆ Nov ┆ req ┆ 3   ┆     ┆ 9   ┆ 1   ┆ 1   ┆     ┆ 1   ┆     ┆ vs  ┆ req ┆ 1   ┆ Nov ┆ Nov ┆ 2   ┆     ┆ TOM ┆     ┆     ┆ 5   ┆ 5_r ┆ rac ┆ 5_r ┆     ┆ 5   ┆ 9   ┆ 10  ┆ 07  ┆ 9   ┆     │
│     ┆     ┆ na- ┆ [RN ┆ vs  ┆ 08  ┆     ┆     ┆     ┆     ┆ l   ┆ s   ┆     ┆     ┆ mRN ┆     ┆ s,M ┆ cs  ┆ Cri ┆ Roa ┆     ┆     ┆     ┆ m   ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆ g   ┆ sho ┆     ┆ vs  ┆ Hyp ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ uir ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆ [RN ┆     ┆ 603 ┆ uir ┆ [RN ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ted ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ seq ┆ A-s ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆ A-S ┆     ┆ itt ┆ &   ┆ ck  ┆ d   ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 197 ┆     ┆ SRX ┆     ┆ siR ┆ ck  ┆     ┆ SAM ┆ erP ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ ed  ┆     ┆     ┆     ┆ 186 ┆ 298 ┆     ┆ A-s ┆     ┆ 932 ┆ ed  ┆ A-s ┆ q   ┆ q   ┆ 609 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ usi ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ _   ┆ eq] ┆ 593 ┆ 2   ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ eq, ┆     ┆ er  ┆ Bio ┆ Ins ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 593 ┆ .ni ┆ 995 ┆     ┆ 143 ┆     ┆ NA  ┆ vs  ┆     ┆ N26 ┆ rep ┆ .10 ┆     ┆     ┆     ┆ 182 ┆ 600 ┆ for ┆     ┆     ┆     ┆ 856 ┆ 622 ┆     ┆ eq] ┆     ┆ 79  ┆ for ┆ eq] ┆ 600 ┆ 600 ┆ 972 ┆     ┆     ┆     ┆     ┆ 593 ┆ GSM ┆ ng  ┆ GSM ┆     ┆ 593 ┆     ┆     ┆ 122 ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 541 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pol ┆     ┆     ┆ sta ┆ tit ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 541 ┆ h.g ┆     ┆     ┆ 902 ┆     ┆     ┆ No  ┆     ┆ 491 ┆ Kit ┆ 16/ ┆     ┆     ┆     ┆ 489 ┆ 0   ┆ pro ┆     ┆     ┆     ┆ 477 ┆ 646 ┆     ┆ vs  ┆     ┆     ┆ pro ┆ vs  ┆ 0   ┆ 0   ┆ 117 ┆     ┆     ┆     ┆     ┆ 541 ┆ 593 ┆ the ┆ 593 ┆     ┆ 541 ┆     ┆     ┆ 007 ┆     ┆     │
│     ┆     ┆ nhs ┆ NHS ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y(A ┆     ┆     ┆ tis ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆     ┆     ┆ 89  ┆     ┆     ┆ hea ┆     ┆ 010 ┆     ┆ j.m ┆     ┆     ┆     ┆ 25  ┆ seq ┆ per ┆     ┆     ┆     ┆ 5   ┆ 9   ┆     ┆ NHS ┆     ┆     ┆ per ┆ NHS ┆     ┆ seq ┆ 9   ┆     ┆     ┆     ┆     ┆ 4   ┆ 541 ┆ RNe ┆ 541 ┆     ┆ 4   ┆     ┆     ┆ 08  ┆     ┆     │
│     ┆     ┆ _si ┆ _si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )+  ┆     ┆     ┆ tic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ olc ┆     ┆     ┆     ┆     ┆ uen ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆ _si ┆     ┆     ┆ hea ┆ _si ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4_r ┆ asy ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ nt_ ┆ NT_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ el. ┆     ┆     ┆     ┆     ┆ cin ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆ NT_ ┆     ┆     ┆ t   ┆ NT_ ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ kit ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ b1_ ┆ B1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆ g:  ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆ B1  ┆     ┆     ┆ sho ┆ B1  ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Qi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rna ┆ [RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆     ┆     ┆     ┆     ┆ GSM ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆ [RN ┆     ┆     ┆ ck  ┆ [RN ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CUG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1.0 ┆     ┆     ┆     ┆     ┆ 593 ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆ res ┆ A-s ┆     ┆ 593 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_  ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 440 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 593 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ 541 ┆ pon ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆ pon ┆ eq] ┆     ┆ 541 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 741 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9A1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 04) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆ [RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [RN ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ siN ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆ siN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 935 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_B ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆ T_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 415 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [RN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y(A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )+  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ufa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M59 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 's  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ins ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ siN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tru ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1.b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE189562 (SINGLE) TT-chem-seq

- validation date 2025-05-03
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用していたTTchem-seqのデータ
- 一つのGSM IDに対して2つのSRAのrun IDが付与されている (`srr`カラムが`multi`)
- 念の為収集する
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE165365 (SINGLE) (DREB) TT-chem-seq

- validation date: 2025-05-03
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- このデータも以前の研究で使用したDRB_TTchem-seqのデータ
- コントロールと熱ストレス曝露のデータが揃っているので念の為収集
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE127844 (SINGLE) PRO-seq

- validate date: 2025-05-03
- [Stress-induced transcriptional memory accelerates promoter-proximal pause release and decelerates termination over mitotic divisions](https://doi.org/10.1016/j.molcel.2021.03.007)
- 以前の研究で使用したPRO-seqのデータ
- HSF1のsilencing 処理も含まれている
- コントロールデータが含まれているので念の為収集
- 処理を[12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に移動

### GSE130493 (SINGLE) NO DOWNLOAD

- validate date: 2025-05-03
- [rDNA Clusters Make Contact with Genes that Are Involved in Differentiation and Cancer and Change Contacts after Heat Shock Treatment](https://doi.org/10.3390/cells8111393)
- 熱ストレスに曝露されているデータは登録されているが、コントロールデータがないため、今回は使用しない

In [16]:
# GSE130493_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE130493/GSE130493_PEP/GSE130493_PEP_raw.csv",
#     separator=','
# )

# display(GSE130493_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. GSE137559 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [17β-Estradiol Activates HSF1 via MAPK Signaling in ERα-Positive Breast Cancer Cells](https://doi.org/10.3390/cancers11101533)
- これも以前の研究で使用した研究
- estrogen処理のデータのみフィルタリング
- `Materials and Methods` の `4.3 Treatments` に記載がある

In [17]:
GSE137559_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE137559/GSE137559_PEP/GSE137559_PEP_raw.csv",
    separator=','
).filter(
    ~pl.col("sample_title").str.contains(r'estrogen') # remove estrogen data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.3390/cancers11101533").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE137559_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE137559_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE137559_iseq_filtered = GSE137559_iseq[[s.name for s in GSE137559_iseq if not (s.null_count() == GSE137559_iseq.height)]]

GSE137559_combined = GSE137559_PEP.join(
    GSE137559_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE137559_combined = GSE137559_combined[[s.name for s in GSE137559_combined if not (s.null_count() == GSE137559_combined.height)]]

GSE137559_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE137559_modified_metadata.tsv",
    separator='\t'
)

# display(GSE137559_combined)

In [18]:
defined_pairs_gse137559 = [
    ("SRR10129832", "SRR10129830") # RNA-seq_hyperthermia_2h vs RNA-seq_control
]

paired_metadata_df_gse137559 = create_paired_metadata(
    combined_df=GSE137559_combined,
    defined_sample_pairs=defined_pairs_gse137559,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse137559 is not None:
    paired_metadata_df_gse137559.write_csv(
        "../../Data/metadata/metadata_paired/GSE137559_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse137559)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tum ┆ sex ┆ age ┆ tis ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ or  ┆ --- ┆ --- ┆ sue ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ --- ┆ str ┆ str ┆ _ce ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ str ┆     ┆     ┆ lls ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ RNA ┆ GSM ┆ Pub ┆ Sep ┆ Oct ┆ SRA ┆ 1   ┆ cel ┆ Hom ┆ 960 ┆ tot ┆ cel ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ ade ┆ fem ┆ 69  ┆ bre ┆ hg1 ┆ SAM ┆ unk ┆ htt ┆ 43  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Hea ┆ SRA ┆ cDN ┆ 201 ┆ 139 ┆ 191 ┆ ILL ┆ Gen ┆ RNA ┆ SRP ┆ 748 ┆ Hea ┆ RNA ┆ Ill ┆ Ill ┆ 381 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ GSM ┆ GEO ┆ MCF ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 101 ┆ 101 ┆ -se ┆ A   ┆ o   ┆ GLE ┆     ┆ 101 ┆ 685 ┆ -se ┆ 408 ┆ lic ┆ 17  ┆ 05  ┆     ┆     ┆ ls  ┆ o   ┆ 6   ┆ al  ┆ ls  ┆ 167 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 408 ┆ E   ┆ 137 ┆     ┆ 685 ┆ 7   ┆ noc ┆ ale ┆ yea ┆ ast ┆ 9   ┆ N12 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 101 ┆ umi ┆ t   ┆ 963 ┆ A   ┆ 9-1 ┆ 913 ┆ 394 ┆ UMI ┆ eri ┆ -se ┆ 221 ┆ 553 ┆ t   ┆ -se ┆ umi ┆ umi ┆ 762 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 408 ┆ 408 ┆ al  ┆ 408 ┆     ┆ 7   ┆ 9-1 ┆ NA5 ┆ 539 ┆ 9-1 ┆ 137 │
│ 298 ┆ 298 ┆ q_h ┆     ┆ sap ┆     ┆     ┆ 298 ┆ 824 ┆ q_h ┆ 176 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ sub ┆ sap ┆     ┆ RNA ┆ sub ┆ 91  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 176 ┆     ┆ 559 ┆     ┆ 824 ┆     ┆ arc ┆     ┆ rs  ┆     ┆     ┆ 771 ┆ n   ┆ //d ┆     ┆ .   ┆ (in ┆ 298 ┆ na  ┆ Sho ┆ 111 ┆     ┆ 0-0 ┆ 524 ┆ 190 ┆ NA  ┆ c   ┆ q_h ┆ 987 ┆ 06  ┆ Sho ┆ q_h ┆ na  ┆ na  ┆ 060 ┆ q   ┆ RIP ┆     ┆     ┆ 176 ┆ 176 ┆ RNA ┆ 176 ┆     ┆     ┆ 0-0 ┆ 659 ┆ 602 ┆ 0-0 ┆ 559 │
│ 32  ┆ 30  ┆ ype ┆     ┆ ien ┆     ┆     ┆ 32  ┆ 5   ┆ ype ┆ 5   ┆ Oct ┆ 9   ┆ 9   ┆     ┆     ┆ jec ┆ ien ┆     ┆     ┆ jec ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 5   ┆     ┆ ,   ┆     ┆ 5   ┆     ┆ ino ┆     ┆     ┆     ┆     ┆ 812 ┆     ┆ oi. ┆     ┆     ┆ fer ┆ 32  ┆ HiS ┆ ck  ┆     ┆     ┆ 7   ┆ 1   ┆ 6   ┆     ┆     ┆ ype ┆     ┆ vs  ┆ ck  ┆ ype ┆ HiS ┆ HiS ┆ 6   ┆     ┆ TOM ┆     ┆     ┆ 5   ┆ 5_r ┆ fro ┆ 5   ┆     ┆     ┆ 7   ┆ 25  ┆ 9   ┆ 7   ┆     │
│     ┆     ┆ rth ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ rth ┆ vs  ┆ 05  ┆     ┆     ┆     ┆     ┆ ted ┆ s   ┆     ┆     ┆ ted ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆ GSE ┆     ┆ vs  ┆     ┆ ma  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ Fac ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ rth ┆     ┆ 467 ┆ Fac ┆ rth ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ m   ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ erm ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ to  ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆ 137 ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆     ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 250 ┆ tor ┆     ┆     ┆     ┆ 888 ┆ 119 ┆     ┆     ┆ erm ┆     ┆ 058 ┆ tor ┆ erm ┆ 250 ┆ 250 ┆ 238 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ 10^ ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ ia_ ┆     ┆     ┆     ┆     ┆ 101 ┆ 685 ┆ ia_ ┆ 408 ┆ 9   ┆     ┆     ┆     ┆     ┆ hyp ┆     ┆     ┆     ┆ hyp ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 408 ┆     ┆ 560 ┆     ┆ 685 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N12 ┆     ┆ .33 ┆     ┆     ┆     ┆ 101 ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ 674 ┆ 150 ┆     ┆     ┆ ia_ ┆     ┆ 89  ┆ 1   ┆ ia_ ┆ 0   ┆ 0   ┆ 200 ┆     ┆     ┆     ┆     ┆ 408 ┆ GSM ┆ 6   ┆ 408 ┆     ┆     ┆     ┆     ┆ 539 ┆     ┆     │
│     ┆     ┆ 2h  ┆     ┆     ┆     ┆     ┆ 298 ┆ 824 ┆ 2h  ┆ 176 ┆     ┆     ┆     ┆     ┆     ┆ erh ┆     ┆     ┆     ┆ erh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 176 ┆     ┆     ┆     ┆ 824 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 771 ┆     ┆ 90/ ┆     ┆     ┆     ┆ 298 ┆ seq ┆ (HS ┆     ┆     ┆     ┆ 258 ┆ 089 ┆     ┆     ┆ 2h  ┆     ┆     ┆ (HS ┆ 2h  ┆     ┆ seq ┆ 033 ┆     ┆     ┆     ┆     ┆ 176 ┆ 408 ┆ cel ┆ 176 ┆     ┆     ┆     ┆     ┆ 602 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 30  ┆ 3   ┆ vs  ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 814 ┆     ┆ can ┆     ┆     ┆     ┆ 30  ┆ uen ┆ F1) ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ vs  ┆     ┆     ┆ F1) ┆ vs  ┆     ┆ uen ┆ 9   ┆     ┆     ┆     ┆     ┆ 3   ┆ 176 ┆ ls  ┆ 3   ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     │
│     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆     ┆     ┆ cin ┆ acq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ acq ┆ RNA ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ (43 ┆     ┆     ┆     ┆ (43 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s11 ┆     ┆     ┆     ┆     ┆ g:  ┆ uir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆ uir ┆ -se ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ °C) ┆     ┆     ┆     ┆ °C) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆     ┆     ┆     ┆     ┆ GSM ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_c ┆     ┆     ┆ es  ┆ q_c ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 533 ┆     ┆     ┆     ┆     ┆ 408 ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ont ┆     ┆     ┆ tra ┆ ont ┆     ┆ 408 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1ho ┆     ┆     ┆     ┆ 1ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 176 ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rol ┆     ┆     ┆ nsc ┆ rol ┆     ┆ 176 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ur  ┆     ┆     ┆     ┆ ur  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ &   ┆     ┆     ┆     ┆ &   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2ho ┆     ┆     ┆     ┆ 2ho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ urs ┆     ┆     ┆     ┆ urs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_h ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆ q_h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ype ┆ pet ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pet ┆     ┆     ┆ ype ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Zo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rec ┆     ┆     ┆     ┆ rec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rth ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ enc ┆     ┆     ┆ rth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lTM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erm ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ry  ┆     ┆     ┆     ┆ ry, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ia_ ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ ia_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ NG. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2h  ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ 2h  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iPr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆ 792 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ 17b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17b ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆ 6_w ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ -es ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -es ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 6. GSE130892 RNA-seq (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION (RNA-seq)

&nbsp;

- validation date: 2025-05-03
- [Limits in the detection of m6A changes using MeRIP/m6A-seq](https://doi.org/10.1038/s41598-020-63355-3)
- 以前の研究で使用していたRNA-seqとMeRIP-seq (methylated RNA immunoprecipitation sequencing) のデータ
- MeRIP-seq の処理を[./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動
- memo: 2026-06-26
- salmon での 発現定量の際に、以下のようなエラーメッセージを確認したため、`SRR9029566` と `SRR9029568` をスキップする
- `  # error message: [2026-01-17 21:36:25.085] [jointLog] [error] Processing reads : Error reading from the FASTA/Q stream. Minimum return code for left and right read was (-2). Make sure the file is valid.`
- GitHub issue: https://github.com/COMBINE-lab/salmon/issues/660

In [19]:
GSE130892_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE130892/GSE130892_PEP/GSE130892_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (Illumina) ?
    pl.lit("https://doi.org/10.1038/s41598-020-63355-3").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# RNA-seq
GSE130892_PEP_rna_seq = GSE130892_PEP.filter(
    pl.col("library_strategy") == "RNA-seq"
)

# metadata from iseq
GSE130892_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE130892_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE130892_iseq_filtered = GSE130892_iseq[[s.name for s in GSE130892_iseq if not (s.null_count() == GSE130892_iseq.height)]]

GSE130892_combined_rna_seq = GSE130892_PEP_rna_seq.join(
    GSE130892_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True)

GSE130892_combined_rna_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE130892_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE130892_combined_rna_seq)

In [20]:
# RNA-seq
defined_pairs_gse130892_rna_seq = [
    # ("SRR9029562", "SRR9029568"), # heatshock_total_input_1 vs untreated_total_input_1 # due to error, skip
    ("SRR9029564", "SRR9029570"), # heatshock_total_input_2 vs untreated_total_input_2
    # ("SRR9029566", "SRR9029572")  # heatshock_total_input_3 vs untreated_total_input_3 # due to error, skip
]

paired_metadata_df_gse130892_rna_seq = create_paired_metadata(
    combined_df=GSE130892_combined_rna_seq,
    defined_sample_pairs=defined_pairs_gse130892_rna_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse130892_rna_seq is not None:
    paired_metadata_df_gse130892_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE130892_rna_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse130892_rna_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ lib ┆ ant ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ rar ┆ ibo ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ y_s ┆ dy  ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ tra ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ teg ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ y   ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hea ┆ cDN ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ hea ┆ GSM ┆ Pub ┆ May ┆ May ┆ SRA ┆ 1   ┆ OCI ┆ Hom ┆ 960 ┆ tot ┆ TRI ┆ hea ┆ GPL ┆ A,, ┆ Mol ┆ Uni ┆ Win ┆ Zur ┆ 805 ┆ Swi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ OCI ┆ dif ┆ 43  ┆ RNA ┆ non ┆ hg3 ┆ MAC ┆ SAM ┆ unk ┆ htt ┆ 43  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ MeR ┆ SRA ┆ cDN ┆ 201 ┆ 110 ┆ 160 ┆ ILL ┆ Gen ┆ hea ┆ SRP ┆ 368 ┆ MeR ┆ hea ┆ Ill ┆ Ill ┆ dif ┆ 154 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ TRI ┆ GSM ┆ GEO ┆ OCI ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 902 ┆ 902 ┆ tsh ┆ A   ┆ o   ┆ GLE ┆     ┆ 902 ┆ 580 ┆ tsh ┆ 375 ┆ lic ┆ 08  ┆ 09  ┆     ┆     ┆ -Ly ┆ o   ┆ 6   ┆ al  ┆ zol ┆ tsh ┆ 167 ┆ McI ┆ ecu ┆ ver ┆ ter ┆ ich ┆ 7   ┆ tze ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 375 ┆ E   ┆ 130 ┆     ┆ 580 ┆ -Ly ┆ fus ┆ C   ┆ -se ┆ e   ┆ 8   ┆ S2  ┆ N11 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 902 ┆ umi ┆ IP- ┆ 884 ┆ A   ┆ 9-0 ┆ 492 ┆ 403 ┆ UMI ┆ eri ┆ tsh ┆ 197 ┆ 511 ┆ IP- ┆ tsh ┆ umi ┆ umi ┆ fus ┆ 774 ┆ -Se ┆ NSC ┆ GLE ┆ lic ┆ 375 ┆ 375 ┆ zol ┆ 375 ┆     ┆ -Ly ┆ 9-0 ┆ NA5 ┆ 473 ┆ 9-0 ┆ 130 │
│ 956 ┆ 957 ┆ ock ┆     ┆ sap ┆     ┆     ┆ 956 ┆ 698 ┆ ock ┆ 585 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ 1   ┆ sap ┆     ┆ RNA ┆ ,   ┆ ock ┆ 91  ┆ nty ┆ lar ┆ sit ┆ thu ┆     ┆     ┆ rla ┆ na  ┆     ┆ rip ┆ q   ┆ 585 ┆     ┆ 892 ┆     ┆ 698 ┆ 1   ┆ e   ┆ for ┆ q   ┆     ┆     ┆ pea ┆ 604 ┆ n   ┆ //d ┆     ┆ .   ┆ (in ┆ 956 ┆ na  ┆ seq ┆ 323 ┆     ┆ 5-1 ┆ 916 ┆ 927 ┆ NA  ┆ c   ┆ ock ┆ 091 ┆ 64  ┆ seq ┆ ock ┆ na  ┆ na  ┆ e   ┆ 888 ┆ q   ┆ RIP ┆     ┆     ┆ 585 ┆ 585 ┆ Ill ┆ 585 ┆     ┆ 1   ┆ 5-1 ┆ 419 ┆ 645 ┆ 5-1 ┆ 892 │
│ 4   ┆ 0   ┆ _to ┆     ┆ ien ┆     ┆     ┆ 4   ┆ 9   ┆ _to ┆ 0   ┆ May ┆ 9   ┆ 9   ┆     ┆     ┆ dif ┆ ien ┆     ┆     ┆ Ill ┆ _to ┆     ┆ re  ┆ Lif ┆ y   ┆ rer ┆     ┆     ┆ nd  ┆ HiS ┆     ┆ tom ┆     ┆ 0   ┆     ┆     ┆     ┆ 9   ┆     ┆ B-c ┆ 1   ┆     ┆     ┆     ┆ k   ┆ 635 ┆     ┆ oi. ┆     ┆     ┆ fer ┆ 4   ┆ HiS ┆ for ┆     ┆     ┆ 0   ┆ 7   ┆ 4   ┆     ┆     ┆ _to ┆     ┆ vs  ┆ for ┆ _to ┆ HiS ┆ HiS ┆ B-c ┆ 8   ┆     ┆ TOM ┆     ┆     ┆ 0   ┆ 0_r ┆ umi ┆ 0   ┆     ┆     ┆ 0   ┆ 15  ┆ 0   ┆ 0   ┆     │
│     ┆     ┆ tal ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ tal ┆ vs  ┆ 09  ┆     ┆     ┆     ┆     ┆ fus ┆ s   ┆     ┆     ┆ umi ┆ tal ┆     ┆     ┆ e   ┆ of  ┆ str ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ ell ┆ hr, ┆     ┆     ┆     ┆ fil ┆ vs  ┆     ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ hea ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ tal ┆     ┆ 333 ┆ hea ┆ tal ┆ eq  ┆ eq  ┆ ell ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ na, ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ _in ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ na, ┆ _2. ┆     ┆     ┆ Sci ┆ Zur ┆ ass ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ lym ┆ rec ┆     ┆     ┆     ┆ es  ┆ SAM ┆     ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 250 ┆ t   ┆     ┆     ┆     ┆ 101 ┆ 146 ┆     ┆     ┆ _in ┆     ┆ 447 ┆ t   ┆ _in ┆ 250 ┆ 250 ┆ lym ┆ 140 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ 1 x ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ put ┆     ┆     ┆     ┆     ┆ 902 ┆ 580 ┆ put ┆ 375 ┆ 9   ┆     ┆     ┆     ┆     ┆ B-c ┆     ┆     ┆     ┆ 1 x ┆ mac ┆     ┆     ┆ enc ┆ ich ┆ e   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆ 580 ┆     ┆ pho ┆ ove ┆     ┆     ┆     ┆ (be ┆ N11 ┆     ┆ .10 ┆     ┆     ┆     ┆ 902 ┆ 0   ┆ sho ┆     ┆     ┆     ┆ 189 ┆ 749 ┆     ┆     ┆ put ┆     ┆ 08  ┆ sho ┆ put ┆ 0   ┆ 0   ┆ pho ┆ 047 ┆     ┆     ┆     ┆     ┆ 375 ┆ GSM ┆ 42  ┆ 375 ┆     ┆     ┆     ┆     ┆ 473 ┆     ┆     │
│     ┆     ┆ _2  ┆     ┆     ┆     ┆     ┆ 957 ┆ 699 ┆ _2  ┆ 585 ┆     ┆     ┆     ┆     ┆     ┆ ell ┆     ┆     ┆     ┆ 42  ┆ s2_ ┆     ┆     ┆ es  ┆     ┆ 190 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 585 ┆     ┆     ┆     ┆ 699 ┆     ┆ ma  ┆ ry  ┆     ┆     ┆     ┆ d)  ┆ 604 ┆     ┆ 38/ ┆     ┆     ┆     ┆ 957 ┆ seq ┆ ck  ┆     ┆     ┆     ┆ 032 ┆ 595 ┆     ┆     ┆ _2  ┆     ┆     ┆ ck  ┆ _2  ┆     ┆ seq ┆ ma  ┆ 773 ┆     ┆     ┆     ┆     ┆ 585 ┆ 375 ┆     ┆ 585 ┆     ┆     ┆     ┆     ┆ 645 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 0   ┆ 5   ┆ vs  ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆ lym ┆     ┆     ┆     ┆     ┆ pea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 5   ┆     ┆ cel ┆ at  ┆     ┆     ┆     ┆     ┆ 629 ┆     ┆ s41 ┆     ┆     ┆     ┆ 0   ┆ uen ┆ in  ┆     ┆     ┆     ┆ 3   ┆ 5   ┆     ┆     ┆ vs  ┆     ┆     ┆ in  ┆ vs  ┆     ┆ uen ┆ cel ┆ 6   ┆     ┆     ┆     ┆     ┆ 6   ┆ 585 ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     │
│     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ pho ┆     ┆     ┆     ┆     ┆ ks. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 598 ┆     ┆     ┆     ┆     ┆ cin ┆ B-c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆ B-c ┆ unt ┆     ┆ cin ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆     ┆ nar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆ g:  ┆ ell ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆ ell ┆ rea ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ row ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0-6 ┆     ┆     ┆     ┆     ┆ GSM ┆ lym ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆ lym ┆ ted ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _to ┆     ┆     ┆     ┆     ┆     ┆     ┆ _to ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆ Pea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 335 ┆     ┆     ┆     ┆     ┆ 375 ┆ pho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _to ┆     ┆     ┆ pho ┆ _to ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hr  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5-3 ┆     ┆     ┆     ┆     ┆ 585 ┆ ma  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆ ma  ┆ tal ┆     ┆ 585 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0:  ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆ cel ┆ _in ┆     ┆ 0:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆ ls  ┆ put ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _2  ┆     ┆     ┆     ┆     ┆     ┆     ┆ _2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _2  ┆     ┆     ┆     ┆ _2  ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _to ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _to ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _to ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _2. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE69021 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-03
- [Gene target specificity of the Super Elongation Complex (SEC) family: how HIV-1 Tat employs selected SEC members to activate viral transcription](https://doi.org/10.1093/nar/gkv541)
- AFF4、AFF1に対してRNAiを行っているデータ
- 熱ストレスを加えているのはChIP-seqで、このRNA-seqのデータはKDをしているので収集しない

In [21]:
# GSE69021_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE69021/GSE69021_PEP/GSE69021_PEP_raw.csv",
#     separator=','
# )

# display(GSE69021_PEP)

### GSE57397 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-03
- [FBXW7 modulates cellular stress response and metastatic potential through HSF1 post-translational modification](https://doi.org/10.1038/ncb3121)
- 熱ストレス時のデータと熱ストレス後の回復のデータのみ登録されているので今回は使用しない

In [22]:
# GSE57397_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE57397/GSE57397_PEP/GSE57397_PEP_raw.csv",
#     separator=','
# )

# display(GSE57397_PEP)

###  GSE37002 (SINGLE) NO DOWNLOAD

- validation date: 2025-05-03
- [Topology of the human and mouse m6A RNA methylomes revealed by m6A-seq](https://doi.org/10.1038/nature11112)
- m6A-seqも以前使用したが、ChIP-seqのような使用方法のため、今回は収集しない

In [23]:
# GSE37002_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE37002/GSE37002_PEP/GSE37002_PEP_raw.csv",
#     separator=','
# )

# display(GSE37002_PEP)

### GSE211651 (SINGLE) PRO-seq

- validation date: 2025-05-03
- [Enhancing HIV-1 latency reversal through regulating the elongating RNA Pol II pause-release by a small-molecule disruptor of PAF1C](https://doi.org/10.1126/sciadv.adf2468)
- きちんと熱ストレス条件とコントロール条件があるデータ
- `inhibitor of PAF1C (iPAF1C)` や `shRNA` 処理も重ねて行われているデータも
- **RNA-seqのデータを見ると、熱ストレスに曝露されているデータは含まれていなかったので、PRO-seqのみ念の為収集しておく**
- 処理を[12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 7. GSE132447 (PAIRED) RNA-seq

- ✅ DOWNLOAD 
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [Multiple Alu Exonization in 3′UTR of a Primate-Specific Isoform of CYP20A1 Creates a Potential miRNA Sponge](https://doi.org/10.1093/gbe/evaa233)
-  HIV1-Tat treatment (おそらくtat)のデータをフィルタリングして、RNA-seqとsmall RNA-seqのデータを収集する
- `HS was given at 45°C (±0.2)  for 30 mins in a water bath.`
- small RNA-seqのデータの処理は[./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

In [24]:
GSE132447_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE132447/GSE132447_PEP/GSE132447_PEP_raw.csv",
    separator=','
)

GSE132447_PEP_rna_seq = GSE132447_PEP.filter(
    pl.col("sample_library_strategy") == "RNA-Seq" # filter out small RNA-seq data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq stranded total RNA protocol").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1093/gbe/evaa233").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("45 C (±0.2)").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE132447_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE132447_metadata.tsv",
    separator='\t'
).with_columns(
    pl.col("cell_line").fill_null(pl.col("cell_type")) # use cell_type (Primary neurons) when cell_line is empty
).drop(
    drop_columns_list
)

GSE132447_iseq_filtered = GSE132447_iseq[[s.name for s in GSE132447_iseq if not (s.null_count() == GSE132447_iseq.height)]]

GSE132447_combined_rna_seq = GSE132447_PEP_rna_seq.join(
    GSE132447_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).filter(
    ~(pl.col("sample_title").str.contains(r'_Tat_')) # filter out HIV1-Tat treatment data
)

GSE132447_combined_rna_seq = GSE132447_combined_rna_seq[[s.name for s in GSE132447_combined_rna_seq if not (s.null_count() == GSE132447_combined_rna_seq.height)]]

GSE132447_combined_rna_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE132447_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE132447_combined_rna_seq)

In [25]:
# RNA-seq
defined_pairs_gse132447_rna_seq = [
    ("SRR9257619", "SRR9257616"), # RNA seq_Heat_shock_1 hr recovery_Replicate_1 vs RNA seq_Untreated_Replicate_1
    ("SRR9257620", "SRR9257617"), # RNA seq_Heat_shock_1 hr recovery_Replicate_2 vs RNA seq_Untreated_Replicate_2
    ("SRR9257621", "SRR9257618"), # RNA seq_Heat_shock_1 hr recovery_Replicate_3 vs RNA seq_Untreated_Replicate_3
    ("SRR9257622", "SRR9257616"), # RNA seq_Heat_shock_3 hr recovery_Replicate_1 vs RNA seq_Untreated_Replicate_1
    ("SRR9257623", "SRR9257617"), # RNA seq_Heat_shock_3 hr recovery_Replicate_2 vs RNA seq_Untreated_Replicate_2
    ("SRR9257624", "SRR9257618"), # RNA seq_Heat_shock_3 hr recovery_Replicate_3 vs RNA seq_Untreated_Replicate_3
    ("SRR9257625", "SRR9257616"), # RNA seq_Heat_shock_24 hr recovery_Replicate_1 vs RNA seq_Untreated_Replicate_1
    ("SRR9257626", "SRR9257617"), # RNA seq_Heat_shock_24 hr recovery_Replicate_2 vs RNA seq_Untreated_Replicate_2
    ("SRR9257627", "SRR9257618")  # RNA seq_Heat_shock_24 hr recovery_Replicate_3 vs RNA seq_Untreated_Replicate_3
]

paired_metadata_df_gse132447_rna_seq = create_paired_metadata(
    combined_df=GSE132447_combined_rna_seq,
    defined_sample_pairs=defined_pairs_gse132447_rna_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse132447_rna_seq is not None:
    paired_metadata_df_gse132447_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE132447_rna_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse132447_rna_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (9, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_t ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ype ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ --- ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ str ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ RNA ┆ GSM ┆ Pub ┆ Jun ┆ Jan ┆ SRA ┆ 1   ┆ Pri ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ vin ┆ Per ┆ LAB ┆ Per ┆ 9   ┆ pun ┆ Mah ┆ 411 ┆ Ind ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Pri ┆ hg1 ┆ cuf ┆ SAM ┆ Tru ┆ htt ┆ 45  ┆ 30  ┆ 37  ┆ SRR ┆ Ill ┆ Ori ┆ SRA ┆ cDN ┆ 202 ┆ 115 ┆ 675 ┆ ILL ┆ Gen ┆ RNA ┆ SRP ┆ 801 ┆ Ori ┆ RNA ┆ Ill ┆ Ill ┆ Pri ┆ 148 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ Pri ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 925 ┆ 925 ┆ _se ┆ A   ┆ o   ┆ RED ┆     ┆ 925 ┆ 602 ┆ seq ┆ 386 ┆ lic ┆ 10  ┆ 21  ┆     ┆     ┆ mar ┆ o   ┆ 6   ┆ al  ┆ 111 ┆ eet ┆ sis ┆ S   ┆ sis ┆ A/1 ┆ e   ┆ ara ┆ 004 ┆ ia  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 386 ┆ E   ┆ 132 ┆     ┆ 602 ┆ mar ┆ 9   ┆ fdi ┆ N12 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 925 ┆ umi ┆ gin ┆ 896 ┆ A   ┆ 1-0 ┆ 034 ┆ 619 ┆ UMI ┆ eri ┆ seq ┆ 200 ┆ 979 ┆ gin ┆ seq ┆ umi ┆ umi ┆ mar ┆ 026 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 386 ┆ 386 ┆ was ┆ 386 ┆     ┆ mar ┆ 1-0 ┆ NA5 ┆ 493 ┆ 1-0 ┆ 132 │
│ 761 ┆ 761 ┆ q_h ┆     ┆ sap ┆     ┆     ┆ 761 ┆ 808 ┆ _He ┆ 491 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆ y   ┆ sap ┆     ┆ RNA ┆ 54  ┆ ,,j ┆ ten ┆     ┆ ten ┆ 2   ┆     ┆ sht ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 491 ┆     ┆ 447 ┆     ┆ 808 ┆ y   ┆     ┆ ff  ┆ 001 ┆ str ┆ //d ┆ (±0 ┆ .   ┆ (in ┆ 761 ┆ na  ┆ of  ┆ 538 ┆     ┆ 1-2 ┆ 750 ┆ 529 ┆ NA  ┆ c   ┆ _He ┆ 969 ┆ 51  ┆ of  ┆ _He ┆ na  ┆ na  ┆ y   ┆ 357 ┆ q   ┆ RIP ┆     ┆     ┆ 491 ┆ 491 ┆ iso ┆ 491 ┆     ┆ y   ┆ 1-2 ┆ 481 ┆ 165 ┆ 1-2 ┆ 447 │
│ 9   ┆ 6   ┆ eat ┆     ┆ ien ┆     ┆     ┆ 9   ┆ 0   ┆ at_ ┆ 5   ┆ Jan ┆ 9   ┆ 1   ┆     ┆     ┆ neu ┆ ien ┆     ┆     ┆     ┆ ha  ┆ t   ┆     ┆ t   ┆ Pin ┆     ┆ ra  ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 5   ┆     ┆     ┆     ┆ 0   ┆ neu ┆     ┆ out ┆ 297 ┆ and ┆ oi. ┆ .2) ┆     ┆ fer ┆ 9   ┆ HiS ┆ a   ┆     ┆     ┆ 3   ┆ 23  ┆ 2;6 ┆     ┆     ┆ at_ ┆     ┆ vs  ┆ a   ┆ at_ ┆ HiS ┆ HiS ┆ neu ┆ 89  ┆     ┆ TOM ┆     ┆     ┆ 5   ┆ 5_r ┆ lat ┆ 5   ┆     ┆ neu ┆ 3   ┆ 08  ┆ 4   ┆ 3   ┆     │
│     ┆     ┆ _sh ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ sho ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆ ron ┆ s   ┆     ┆     ┆     ┆     ┆ sys ┆     ┆ sys ┆ gal ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ ron ┆     ┆ put ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ nov ┆     ┆     ┆     ┆ vs  ┆ 831 ┆     ┆     ┆ sho ┆     ┆ 849 ┆ nov ┆ sho ┆ eq  ┆ eq  ┆ ron ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ed  ┆ vs  ┆     ┆ ron ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ ck_ ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ tem ┆     ┆ tem ┆ e   ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ s   ┆     ┆     ┆ SAM ┆ tot ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 200 ┆ el  ┆     ┆     ┆     ┆ 119 ┆ 003 ┆     ┆     ┆ ck_ ┆     ┆ 475 ┆ el  ┆ ck_ ┆ 200 ┆ 200 ┆ s   ┆ 156 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ fro ┆ GSM ┆     ┆ s   ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ _1_ ┆     ┆     ┆     ┆     ┆ 925 ┆ 602 ┆ 1   ┆ 386 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ Ary ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 386 ┆     ┆     ┆     ┆ 602 ┆     ┆     ┆     ┆ N12 ┆ al  ┆ .10 ┆     ┆     ┆     ┆ 925 ┆ 0   ┆ CYP ┆     ┆     ┆     ┆ 825 ┆ 726 ┆     ┆     ┆ 1   ┆     ┆ 75  ┆ CYP ┆ 1   ┆ 0   ┆ 0   ┆     ┆ 703 ┆     ┆     ┆     ┆     ┆ 386 ┆ GSM ┆ m   ┆ 386 ┆     ┆     ┆     ┆     ┆ 493 ┆     ┆     │
│     ┆     ┆ hr_ ┆     ┆     ┆     ┆     ┆ 761 ┆ 807 ┆ hr  ┆ 491 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ abh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 491 ┆     ┆     ┆     ┆ 807 ┆     ┆     ┆     ┆ 001 ┆ RNA ┆ 93/ ┆     ┆     ┆     ┆ 761 ┆ seq ┆ 20A ┆     ┆     ┆     ┆ 572 ┆ vs  ┆     ┆     ┆ hr  ┆     ┆     ┆ 20A ┆ hr  ┆     ┆ seq ┆     ┆ 570 ┆     ┆     ┆     ┆     ┆ 491 ┆ 386 ┆ mon ┆ 491 ┆     ┆     ┆     ┆     ┆ 164 ┆     ┆     │
│     ┆     ┆ rec ┆     ┆     ┆     ┆     ┆ 6   ┆ 7   ┆ rec ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ att ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 389 ┆ pro ┆ gbe ┆     ┆     ┆     ┆ 6   ┆ uen ┆ 1   ┆     ┆     ┆     ┆ 92  ┆ 689 ┆     ┆     ┆ rec ┆     ┆     ┆ 1   ┆ rec ┆     ┆ uen ┆     ┆ 06  ┆     ┆     ┆     ┆     ┆ 2   ┆ 491 ┆ ola ┆ 2   ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     │
│     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆ /ev ┆     ┆     ┆     ┆     ┆ cin ┆ lnc ┆     ┆     ┆     ┆     ┆ 103 ┆     ┆     ┆ ove ┆     ┆     ┆ lnc ┆ ove ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ yer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ry_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ry_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆ aa2 ┆     ┆     ┆     ┆     ┆ g:  ┆ RNA ┆     ┆     ┆     ┆     ┆ 699 ┆     ┆     ┆ ry_ ┆     ┆     ┆ RNA ┆ ry_ ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆ GSM ┆ thr ┆     ┆     ┆     ┆     ┆ 8;6 ┆     ┆     ┆ Rep ┆     ┆     ┆ thr ┆ Rep ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ten ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 386 ┆ oug ┆     ┆     ┆     ┆     ┆ 978 ┆     ┆     ┆ lic ┆     ┆     ┆ oug ┆ lic ┆     ┆ 386 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 491 ┆ h   ┆     ┆     ┆     ┆     ┆ 775 ┆     ┆     ┆ ate ┆     ┆     ┆ h   ┆ ate ┆     ┆ 491 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tow ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆ 23  ┆     ┆     ┆     ┆     ┆ 702 ┆     ┆     ┆ _1  ┆     ┆     ┆ 23  ┆ _1  ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ Alu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ Alu ┆ vs  ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆ exa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ exa ┆ RNA ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _se ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _He ┆ pta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆ pta ┆ seq ┆     ┆ _He ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_u ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Un ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Un ┆     ┆     ┆ tio ┆ _Un ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆ ns  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆ ns  ┆ tre ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck_ ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆ in  ┆ ate ┆     ┆ ck_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ed_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_R ┆     ┆     ┆ the ┆ d_R ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ufa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ epl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hr  ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ epl ┆     ┆     ┆ hum ┆ epl ┆     ┆ hr  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE294487 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-03
- 論文はアクセスできないが、貴重なので念の為収集しておこう... と思ったが、アセンブリーがmm10など情報がおかしいものや、hyperthermiaの条件がはっきりわからなかったので今回は収集しない

In [26]:
# GSE294487_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE294487/GSE294487_PEP/GSE294487_PEP_raw.csv",
#     separator=','
# )

# display(GSE294487_PEP)

### GSE261649 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-03
- [Pre-print: Multi-omics and biochemical reconstitution reveal CDK7-dependent mechanisms controlling RNA polymerase II function at gene 5’- and 3’-ends](https://doi.org/10.1101/2025.01.08.632016)
- 全てのデータが熱ショックが加えられており、今回は解析には使用しない

In [27]:
# GSE261649_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE261649/GSE261649_PEP/GSE261649_PEP_raw.csv",
#     separator=','
# )

# display(GSE261649_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8. GSE289231 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [Differential Temperature-Induced Responses in Immortalized Oral and Skin Keratinocytes](https://doi.org/10.3390/ijms26072851)
- コントロールとなる37℃, 熱ストレスとなる60℃, 低温ストレスとなる-25℃でそれぞれ10分間に曝露されたデータ
- 低温ストレスのデータをフィルタリングした状態で収集

In [28]:
GSE289231_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE289231/GSE289231_PEP/GSE289231_PEP_raw.csv",
    separator=','
).filter(
    ~pl.col("sample_title").str.contains(r'(-25)')
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library (performed by Novogene)
    pl.lit("https://doi.org/10.3390/ijms26072851").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("60 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("10 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE289231_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE289231_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE289231_iseq_filtered = GSE289231_iseq[[s.name for s in GSE289231_iseq if not (s.null_count() == GSE289231_iseq.height)]]

GSE289231_combined = GSE289231_PEP.join(
    GSE289231_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE289231_combined = GSE289231_combined[[s.name for s in GSE289231_combined if not (s.null_count() == GSE289231_combined.height)]]

GSE289231_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE289231_modified_metadata.tsv",
    separator='\t'
)

# display(GSE289231_combined)

In [29]:
defined_pairs_gse289231 = [
    # Skin Keratinocytes
    ("SRR32325145", "SRR32325151"), # HaCaT 60C-1 vs HaCaT 37C-1
    ("SRR32325144", "SRR32325150"), # HaCaT 60C-2 vs HaCaT 37C-2
    ("SRR32325143", "SRR32325149"), # HaCaT 60C-3 vs HaCaT 37C-3
    # Gingival Keratinocytes
    ("SRR32325136", "SRR32325142"), # TIGK 60C-1 vs TIGK 37C-1
    ("SRR32325135", "SRR32325141"), # TIGK 60C-2 vs TIGK 37C-2
    ("SRR32325134", "SRR32325140")  # TIGK 60C-3 vs TIGK 37C-3
]

paired_metadata_df_gse289231 = create_paired_metadata(
    combined_df=GSE289231_combined,
    defined_sample_pairs=defined_pairs_gse289231,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse289231 is not None:
    paired_metadata_df_gse289231.write_csv(
        "../../Data/metadata/metadata_paired/GSE289231_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse289231)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 83)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hac ┆ HaC ┆ GSM ┆ Pub ┆ Feb ┆ Apr ┆ SRA ┆ 1   ┆ Ski ┆ Hom ┆ 960 ┆ pol ┆ Lib ┆ GPL ┆ Che ┆ cha ┆ 301 ┆ Lui ┆ Cen ┆ Uni ┆ 801 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Ski ┆ HaC ┆ Ski ┆ 60° ┆ hg3 ┆ SAM ┆ unk ┆ htt ┆ 60  ┆ 10  ┆ 37  ┆ SRR ┆ Ill ┆ DIF ┆ SRA ┆ cDN ┆ 202 ┆ 294 ┆ 215 ┆ ILL ┆ nul ┆ nul ┆ SRP ┆ 340 ┆ DIF ┆ nul ┆ Ill ┆ Ill ┆ nul ┆ 102 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ nul ┆ GSM ┆ RNA ┆ nul ┆ GSM ┆ nul ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ nul │
│ 323 ┆ 323 ┆ at_ ┆ aT  ┆ 878 ┆ lic ┆ 10  ┆ 17  ┆     ┆     ┆ n   ┆ o   ┆ 6   ┆ yA  ┆ rar ┆ 246 ┆ n,, ┆ n20 ┆ 828 ┆ sa  ┆ ter ┆ ver ┆ S.  ┆ cag ┆     ┆ 12  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 878 ┆ E   ┆ 289 ┆     ┆ 276 ┆ n   ┆ aT  ┆ n   ┆ C   ┆ 8   ┆ N46 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 323 ┆ umi ┆ FER ┆ 207 ┆ A   ┆ 5-0 ┆ 566 ┆ 894 ┆ UMI ┆ l   ┆ l   ┆ 563 ┆ 321 ┆ FER ┆ l   ┆ umi ┆ umi ┆ l   ┆ 096 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ l   ┆ 878 ┆ was ┆ l   ┆ 878 ┆ l   ┆ 878 ┆ 5-0 ┆ NA1 ┆ 240 ┆ 5-0 ┆ 289 ┆ l   │
│ 251 ┆ 251 ┆ 60c ┆ 60C ┆ 740 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ y   ┆ 76  ┆ Han ┆ 6@u ┆ 805 ┆ DiP ┆ for ┆ sit ┆ Pau ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 740 ┆     ┆ 231 ┆     ┆ 601 ┆     ┆     ┆ Ker ┆ Hea ┆     ┆ 758 ┆ n   ┆ //d ┆     ┆ .   ┆     ┆ 251 ┆ na  ┆ ENT ┆ 609 ┆     ┆ 4-1 ┆ 026 ┆ 096 ┆ NA  ┆     ┆     ┆ 552 ┆ 18  ┆ ENT ┆     ┆ na  ┆ na  ┆     ┆ 354 ┆ q   ┆ RIP ┆     ┆     ┆     ┆ 740 ┆ har ┆     ┆ 740 ┆     ┆ 740 ┆ 4-1 ┆ 221 ┆ 652 ┆ 4-1 ┆ 231 ┆     │
│ 45  ┆ 51  ┆ -1  ┆ -1  ┆ 6   ┆ Apr ┆ 5   ┆ 5   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ nam ┆     ┆     ┆ ic. ┆ 1   ┆ iet ┆ Wou ┆ y   ┆ lin ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 6   ┆     ┆     ┆     ┆ 71  ┆     ┆     ┆ ati ┆ t   ┆     ┆ 295 ┆     ┆ oi. ┆     ┆     ┆     ┆ 45  ┆ Nov ┆ IAL ┆ 9   ┆     ┆ 8   ┆ 1   ┆ 9;2 ┆     ┆     ┆     ┆     ┆ vs  ┆ IAL ┆     ┆ Nov ┆ Nov ┆     ┆ 00  ┆     ┆ TOM ┆     ┆     ┆     ┆ 6_r ┆ ves ┆     ┆ 6_r ┆     ┆ 6   ┆ 8   ┆ 942 ┆ 75  ┆ 8   ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 17  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ e:  ┆     ┆     ┆ edu ┆     ┆ ro  ┆ nd  ┆ of  ┆ a   ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ noc ┆ Inj ┆     ┆ vs  ┆     ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆ TEM ┆     ┆     ┆     ┆ vs  ┆ 158 ┆     ┆     ┆     ┆     ┆ 446 ┆ TEM ┆     ┆ aSe ┆ aSe ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆     ┆ 1   ┆ ted ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ hac ┆ HaC ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sam ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ Ill ┆ St. ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆ yte ┆ ury ┆     ┆ SAM ┆     ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆ PER ┆     ┆     ┆     ┆ 396 ┆ 669 ┆     ┆     ┆     ┆     ┆ 574 ┆ PER ┆     ┆ q   ┆ q   ┆     ┆ 133 ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ aft ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ at_ ┆ aT  ┆ 878 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆ lin ┆ ino ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 878 ┆     ┆     ┆     ┆ 276 ┆     ┆     ┆ s   ┆ vs  ┆     ┆ N46 ┆     ┆ .33 ┆     ┆     ┆     ┆ 323 ┆ 600 ┆ ATU ┆     ┆     ┆     ┆ 926 ┆ 115 ┆     ┆     ┆     ┆     ┆ 57  ┆ ATU ┆     ┆ 600 ┆ 600 ┆     ┆ 972 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ er  ┆     ┆ GSM ┆     ┆ 878 ┆     ┆     ┆ 240 ┆     ┆     ┆     │
│     ┆     ┆ 37c ┆ 37C ┆ 740 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ g   ┆ is  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 740 ┆     ┆     ┆     ┆ 601 ┆     ┆     ┆     ┆ 37° ┆     ┆ 758 ┆     ┆ 90/ ┆     ┆     ┆     ┆ 251 ┆ 0   ┆ RE- ┆     ┆     ┆     ┆ 869 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ RE- ┆     ┆ 0   ┆ 0   ┆     ┆ 371 ┆     ┆     ┆     ┆     ┆     ┆ 878 ┆ 10  ┆     ┆ 878 ┆     ┆ 740 ┆     ┆     ┆ 652 ┆     ┆     ┆     │
│     ┆     ┆ -1  ┆ -1  ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ and ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 65  ┆     ┆     ┆     ┆ C   ┆     ┆ 301 ┆     ┆ ijm ┆     ┆     ┆     ┆ 51  ┆ seq ┆ IND ┆     ┆     ┆     ┆ 6   ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆ IND ┆     ┆     ┆ seq ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 740 ┆ min ┆     ┆ 740 ┆     ┆ 0   ┆     ┆     ┆ 69  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆ Tis ┆ cag ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆     ┆ s26 ┆     ┆     ┆     ┆     ┆ uen ┆ UCE ┆     ┆     ┆     ┆     ┆ 448 ┆     ┆     ┆     ┆     ┆     ┆ UCE ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_r ┆ ute ┆     ┆ 0_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆ sue ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eli ┆     ┆     ┆     ┆ 072 ┆     ┆     ┆     ┆     ┆ cin ┆ D   ┆     ┆     ┆     ┆     ┆ 551 ┆     ┆     ┆     ┆     ┆     ┆ D   ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ s   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ Reg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆ 851 ┆     ┆     ┆     ┆     ┆ g:  ┆ RES ┆     ┆     ┆     ┆     ┆ 3;2 ┆     ┆     ┆     ┆     ┆     ┆ RES ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nam ┆     ┆     ┆     ┆     ┆     ┆ ene ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ PON ┆     ┆     ┆     ┆     ┆ 872 ┆     ┆     ┆     ┆     ┆     ┆ PON ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -25 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e:  ┆     ┆     ┆     ┆     ┆     ┆ rat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 878 ┆ SES ┆     ┆     ┆     ┆     ┆ 989 ┆     ┆     ┆     ┆     ┆     ┆ SES ┆     ┆     ┆ 878 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ °C, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sam ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 740 ┆ IN  ┆     ┆     ┆     ┆     ┆ 603 ┆     ┆     ┆     ┆     ┆     ┆ IN  ┆     ┆     ┆ 740 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6:  ┆ ORA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ORA ┆     ┆     ┆ 6:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HaC ┆ L   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ L   ┆     ┆     ┆ HaC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aT  ┆ AND ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AND ┆     ┆     ┆ aT  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60C ┆ SKI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SKI ┆     ┆     ┆ 60C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -1  ┆ N   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N   ┆     ┆     ┆ -1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ KER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ KER ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ ATI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATI ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ NOC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NOC ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ YTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ YTE ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S   ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 9. GSE279569 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [Histone lactylation drives liver cancer metastasis by facilitating NSF1-mediated ferroptosis resistance after microwave ablation](https://doi.org/10.1016/j.redox.2025.103553)
- コントロールとなる37℃,15分のデータと47℃,15分のデータが揃っているので、このデータを収集して、他のデータはフィルタリングする

In [30]:
GSE279569_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE279569/GSE279569_PEP/GSE279569_PEP_raw.csv",
    separator=','
).filter(
    ~((pl.col("sample_title").str.contains(r'NC-')) | (pl.col("sample_title").str.contains(r'NFS1'))) # filter out NC- and NFS1-treated samples
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("VAHTS Universal V6 RNA-seq Library Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (VAHTS)
    pl.lit("https://doi.org/10.1016/j.redox.2025.103553").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("47 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("15 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE279569_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE279569_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE279569_iseq_filtered = GSE279569_iseq[[s.name for s in GSE279569_iseq if not (s.null_count() == GSE279569_iseq.height)]]

GSE279569_combined = GSE279569_PEP.join(
    GSE279569_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE279569_combined = GSE279569_combined[[s.name for s in GSE279569_combined if not (s.null_count() == GSE279569_combined.height)]]

GSE279569_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE279569_modified_metadata.tsv",
    separator='\t'
)

# display(GSE279569_combined)

In [31]:
defined_pairs_gse279569 = [
    ("SRR31013091", "SRR31013096"), # 47C-15min-1 vs 37C-15min-1
    ("SRR31013090", "SRR31013095"), # 47C-15min-2 vs 37C-15min-2
    ("SRR31013089", "SRR31013094"), # 47C-15min-3 vs 37C-15min-3
    ("SRR31013088", "SRR31013093"), # 47C-15min-4 vs 37C-15min-4
    ("SRR31013087", "SRR31013092")  # 47C-15min-5 vs 37C-15min-5
]

paired_metadata_df_gse279569 = create_paired_metadata(
    combined_df=GSE279569_combined,
    defined_sample_pairs=defined_pairs_gse279569,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse279569 is not None:
    paired_metadata_df_gse279569.write_csv(
        "../../Data/metadata/metadata_paired/GSE279569_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse279569)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (5, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ r-4 ┆ R-4 ┆ GSM ┆ Pub ┆ Oct ┆ Mar ┆ SRA ┆ 1   ┆ liv ┆ Hom ┆ 960 ┆ pol ┆ GPL ┆ Jia ┆ hjy ┆ Ult ┆ Wes ┆ No. ┆ Sic ┆ 610 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ liv ┆ MHC ┆ hum ┆ WT  ┆ The ┆ Hg3 ┆ SAM ┆ VAH ┆ htt ┆ 47  ┆ 15  ┆ 37  ┆ SRR ┆ Ill ┆ His ┆ SRA ┆ cDN ┆ 202 ┆ 174 ┆ 130 ┆ ILL ┆ mis ┆ R-4 ┆ SRP ┆ 229 ┆ His ┆ R-4 ┆ Ill ┆ Ill ┆ hum ┆ 685 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ MHC ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ liv │
│ 310 ┆ 310 ┆ 7-1 ┆ 7-1 ┆ 857 ┆ lic ┆ 16  ┆ 12  ┆     ┆     ┆ er  ┆ o   ┆ 6   ┆ yA  ┆ 246 ┆ ,ya ┆ 810 ┆ ras ┆ t   ┆ 37  ┆ hua ┆ 041 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 857 ┆ E   ┆ 279 ┆     ┆ 264 ┆ er  ┆ C-9 ┆ an  ┆     ┆ sam ┆ 8   ┆ N44 ┆ TS  ┆ ps: ┆ C   ┆ min ┆ C   ┆ 310 ┆ umi ┆ ton ┆ 199 ┆ A   ┆ 5-0 ┆ 842 ┆ 304 ┆ UMI ┆ sin ┆ 7-1 ┆ 538 ┆ 677 ┆ ton ┆ 7-1 ┆ umi ┆ umi ┆ an  ┆ 659 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 857 ┆ 857 ┆ al  ┆ sin ┆ 857 ┆ C-9 ┆ 857 ┆ 5-0 ┆ NA1 ┆ 229 ┆ 5-0 ┆ 279 ┆ er  │
│ 130 ┆ 130 ┆ vs  ┆ vs  ┆ 613 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ can ┆ sap ┆     ┆ RNA ┆ 76  ┆ n,H ┆ 3@s ┆ oun ┆ Chi ┆ Guo ┆ n   ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 613 ┆     ┆ 569 ┆     ┆ 005 ┆ can ┆ 7H  ┆ hep ┆     ┆ ple ┆     ┆ 308 ┆ Uni ┆ //d ┆     ┆ .   ┆     ┆ 130 ┆ na  ┆ e   ┆ 248 ┆     ┆ 3-1 ┆ 861 ┆ 989 ┆ NA  ┆ g   ┆ vs  ┆ 866 ┆ 53  ┆ e   ┆ vs  ┆ na  ┆ na  ┆ hep ┆ 869 ┆ q   ┆ RIP ┆     ┆     ┆ 613 ┆ 613 ┆ RNA ┆ g   ┆ 613 ┆ 7H  ┆ 613 ┆ 3-1 ┆ 173 ┆ 225 ┆ 3-1 ┆ 569 ┆ can │
│ 91  ┆ 96  ┆ r-3 ┆ R-3 ┆ 7   ┆ Mar ┆ 4   ┆ 5   ┆     ┆     ┆ cer ┆ ien ┆     ┆     ┆     ┆ uan ┆ cu. ┆ d   ┆ na  ┆ xue ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 60  ┆ cer ┆     ┆ ato ┆     ┆ s   ┆     ┆ 030 ┆ ver ┆ oi. ┆     ┆     ┆     ┆ 91  ┆ Nov ┆ lac ┆ 4   ┆     ┆ 4   ┆ 4   ┆ 6;1 ┆     ┆     ┆ R-3 ┆     ┆ vs  ┆ lac ┆ R-3 ┆ Nov ┆ Nov ┆ ato ┆ 9   ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ was ┆     ┆ 7_r ┆     ┆ 7   ┆ 4   ┆ 544 ┆ 65  ┆ 4   ┆     ┆ cer │
│     ┆     ┆ 7-1 ┆ 7-1 ┆ vs  ┆ 12  ┆     ┆     ┆     ┆     ┆ cel ┆ s   ┆     ┆     ┆     ┆ g   ┆ edu ┆     ┆ hos ┆ Lan ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ cel ┆     ┆ cel ┆     ┆ wer ┆     ┆ vs  ┆ sal ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆ tyl ┆     ┆     ┆     ┆ vs  ┆ 301 ┆     ┆     ┆ 7-1 ┆     ┆ 226 ┆ tyl ┆ 7-1 ┆ aSe ┆ aSe ┆ cel ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆ cel │
│     ┆     ┆     ┆     ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ .cn ┆     ┆ pit ┆ e,  ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ l   ┆     ┆ lul ┆     ┆ e   ┆     ┆ SAM ┆ V6  ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆ ati ┆     ┆     ┆     ┆ 171 ┆ 704 ┆     ┆     ┆     ┆     ┆ 550 ┆ ati ┆     ┆ q   ┆ q   ┆ lul ┆ 676 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆ l   │
│     ┆     ┆     ┆     ┆ 857 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ Wuh ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 857 ┆     ┆     ┆     ┆ 264 ┆     ┆     ┆ ar  ┆     ┆ exp ┆     ┆ N44 ┆ RNA ┆ .10 ┆     ┆     ┆     ┆ 310 ┆ 600 ┆ on  ┆     ┆     ┆     ┆ 741 ┆ 108 ┆     ┆     ┆     ┆     ┆ 54  ┆ on  ┆     ┆ 600 ┆ 600 ┆ ar  ┆ 340 ┆     ┆     ┆     ┆     ┆ 857 ┆ GSM ┆ ted ┆     ┆ GSM ┆     ┆ 857 ┆     ┆     ┆ 229 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 613 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ou  ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 613 ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆ car ┆     ┆ ose ┆     ┆ 308 ┆ -se ┆ 16/ ┆     ┆     ┆     ┆ 130 ┆ 0   ┆ dri ┆     ┆     ┆     ┆ 008 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ dri ┆     ┆ 0   ┆ 0   ┆ car ┆ 854 ┆     ┆     ┆     ┆     ┆ 613 ┆ 857 ┆ usi ┆     ┆ 857 ┆     ┆ 613 ┆     ┆     ┆ 225 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 55  ┆     ┆     ┆ cin ┆     ┆ d   ┆     ┆ 035 ┆ q   ┆ j.r ┆     ┆     ┆     ┆ 96  ┆ seq ┆ ves ┆     ┆     ┆     ┆ 2   ┆ 127 ┆     ┆     ┆     ┆     ┆     ┆ ves ┆     ┆     ┆ seq ┆ cin ┆ 0   ┆     ┆     ┆     ┆     ┆ 2   ┆ 613 ┆ ng  ┆     ┆ 613 ┆     ┆ 2   ┆     ┆     ┆ 51  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oma ┆     ┆ to  ┆     ┆     ┆ Lib ┆ edo ┆     ┆     ┆     ┆     ┆ uen ┆ liv ┆     ┆     ┆     ┆     ┆ 602 ┆     ┆     ┆     ┆     ┆     ┆ liv ┆     ┆     ┆ uen ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ the ┆     ┆ 2_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ a   ┆     ┆     ┆ rar ┆ x.2 ┆     ┆     ┆     ┆     ┆ cin ┆ er  ┆     ┆     ┆     ┆     ┆ 620 ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ cin ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ TRI ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ wat ┆     ┆     ┆ y   ┆ 025 ┆     ┆     ┆     ┆     ┆ g:  ┆ can ┆     ┆     ┆     ┆     ┆ 5;1 ┆     ┆     ┆     ┆     ┆     ┆ can ┆     ┆     ┆ g:  ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ Pre ┆ .10 ┆     ┆     ┆     ┆     ┆ GSM ┆ cer ┆     ┆     ┆     ┆     ┆ 275 ┆     ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bat ┆     ┆     ┆ p   ┆ 355 ┆     ┆     ┆     ┆     ┆ 857 ┆ met ┆     ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆ met ┆     ┆     ┆ 857 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆ Kit ┆ 3   ┆     ┆     ┆     ┆     ┆ 613 ┆ ast ┆     ┆     ┆     ┆     ┆ 572 ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 613 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆ asi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asi ┆     ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (In ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47℃ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R-4 ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ R-4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-1 ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆ 7-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ fac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fac ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ en, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ ili ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ili ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CA, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ tat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tat ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ USA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ NSF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NSF ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sub ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ iat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iat ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 10. GSE285497 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [Heat shock-induced PI(4)P increase drives HSPA1A translocation to the plasma membrane in cancer and stressed cells through PI4KIII alpha activation](https://doi.org/10.1016/j.cstres.2025.100130)
- 42℃ 60分間と37℃のデータが存在する
- `treatment` が `heat shock`で `0hr`と `_8hr`があるが、reocover が8時間している場合のデータもある
- `Cells were either maintained at 37°C or subjected to heat stress at 42°C for 60 minutes in a humidified CO₂ incubator.`
- 解析に使用する

In [32]:
GSE285497_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE285497/GSE285497_PEP/GSE285497_PEP_raw.csv",
    separator=','
).filter(
    ~((pl.col("sample_title").str.contains(r'NC-')) | (pl.col("sample_title").str.contains(r'NFS1'))) # filter out NC- and NFS1-treated samples
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext® UltraTM RNA Library Prep Kit for Illumina® (NEB, USA)").alias("rna_library"), # add rna_library column from GEO webpage
    pl.lit("https://doi.org/10.1016/j.cstres.2025.100130").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE285497_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE285497_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE285497_iseq_filtered = GSE285497_iseq[[s.name for s in GSE285497_iseq if not (s.null_count() == GSE285497_iseq.height)]]

GSE285497_combined = GSE285497_PEP.join(
    GSE285497_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE285497_combined = GSE285497_combined[[s.name for s in GSE285497_combined if not (s.null_count() == GSE285497_combined.height)]]

GSE285497_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE285497_modified_metadata.tsv",
    separator='\t'
)

# display(GSE285497_combined)

In [33]:
defined_pairs_gse285497 = [
    # human embryonic kidney cells
    ("SRR31847460", "SRR31847461"), # hek_1_1_0hr vs hek_1_1_control
    ("SRR31847459", "SRR31847461"), # hek_1_1_8hr vs hek_1_1_control
    ("SRR31847457", "SRR31847458"), # hek_1_1_b2_0hr vs hek_1_1_b2_control
    ("SRR31847456", "SRR31847458"), # hek_1_1_b2_8hr vs hek_1_1_b2_control
    ("SRR31847454", "SRR31847455"), # hek_2_1_0hr vs hek_2_1_control
    ("SRR31847453", "SRR31847455"), # hek_2_1_8hr vs hek_2_1_control
    ("SRR31847451", "SRR31847452"), # hek_2_1_b2_0hr vs hek_2_1_b2_control
    ("SRR31847450", "SRR31847452"), # hek_2_1_b2_8hr vs hek_2_1_b2_control
    ("SRR31847448", "SRR31847449"), # hek_3_1_0hr vs hek_3_1_control
    ("SRR31847447", "SRR31847449"), # hek_3_1_8hr vs hek_3_1_control
    ("SRR31847445", "SRR31847446"), # hek_3_1_b2_0hr vs hek_3_1_b2_control
    ("SRR31847444", "SRR31847446"), # hek_3_1_b2_8hr vs hek_3_1_b2_control
    ("SRR31847442", "SRR31847443"), # hek_4_1_0hr vs hek_4_1_control
    ("SRR31847441", "SRR31847443"), # hek_4_1_8hr vs hek_4_1_control
    ("SRR31847439", "SRR31847440"), # hek_5_1_0hr vs hek_5_1_control
    ("SRR31847438", "SRR31847440"), # hek_5_1_8hr vs hek_5_1_control
    ("SRR31847436", "SRR31847437"), # hek_6_1_0hr vs hek_6_1_control
    ("SRR31847435", "SRR31847437"), # hek_6_1_8hr vs hek_6_1_control
    # Henrietta Lacks cells
    ("SRR31847433", "SRR31847434"), # hela_1_1_0hr vs hela_1_1_control
    ("SRR31847432", "SRR31847434"), # hela_1_1_8hr vs hela_1_1_control
    ("SRR31847430", "SRR31847431"), # hela_1_1_b2_0hr vs hela_1_1_b2_control
    ("SRR31847429", "SRR31847431"), # hela_1_1_b2_8hr vs hela_1_1_b2_control
    ("SRR31847427", "SRR31847428"), # hela_2_1_0hr vs hela_2_1_control
    ("SRR31847426", "SRR31847428"), # hela_2_1_8hr vs hela_2_1_control
    ("SRR31847424", "SRR31847425"), # hela_2_1_b2_0hr vs hela_2_1_b2_control
    ("SRR31847422", "SRR31847423"), # hela_3_1_0hr vs hela_3_1_control
    ("SRR31847421", "SRR31847423"), # hela_3_1_8hr vs hela_3_1_control
    ("SRR31847419", "SRR31847420"), # hela_3_1_b2_8hr vs hela_3_1_b2_control
    ("SRR31847417", "SRR31847418"), # hela_4_1_0hr vs hela_4_1_control
    ("SRR31847416", "SRR31847418"), # hela_4_1_8hr vs hela_4_1_control
    ("SRR31847414", "SRR31847415"), # hela_5_1_0hr vs hela_5_1_control
    ("SRR31847413", "SRR31847415"), # hela_5_1_8hr vs hela_5_1_control
    ("SRR31847411", "SRR31847412"), # hela_6_1_0hr vs hela_6_1_control
    ("SRR31847410", "SRR31847412"), # hela_6_1_8hr vs hela_6_1_control
    # hepatocellular carcinoma cells
    ("SRR31847408", "SRR31847409"), # hep_1_1_0hr vs hep_1_1_control
    ("SRR31847407", "SRR31847409"), # hep_1_1_8hr vs hep_1_1_control
    ("SRR31847405", "SRR31847406"), # hep_1_1_b2_0hr vs hep_1_1_b2_control
    ("SRR31847404", "SRR31847406"), # hep_1_1_b2_8hr vs hep_1_1_b2_control
    ("SRR31847402", "SRR31847403"), # hep_2_1_0hr vs hep_2_1_control
    ("SRR31847401", "SRR31847403"), # hep_2_1_8hr vs hep_2_1_control
    ("SRR31847399", "SRR31847400"), # hep_2_1_b2_0hr vs hep_2_1_b2_control
    ("SRR31847398", "SRR31847400"), # hep_2_1_b2_8hr vs hep_2_1_b2_control
    ("SRR31847396", "SRR31847397"), # hep_3_1_0hr vs hep_3_1_control
    ("SRR31847395", "SRR31847397"), # hep_3_1_8hr vs hep_3_1_control
    ("SRR31847393", "SRR31847394"), # hep_3_1_b2_0hr vs hep_3_1_b2_control
    ("SRR31847392", "SRR31847394"), # hep_3_1_b2_8hr vs hep_3_1_b2_control
    ("SRR31847390", "SRR31847391"), # hep_4_1_0hr vs hep_4_1_control
    ("SRR31847389", "SRR31847391"), # hep_4_1_8hr vs hep_4_1_control
    ("SRR31847387", "SRR31847388"), # hep_5_1_0hr vs hep_5_1_control
    ("SRR31847386", "SRR31847388"), # hep_5_1_8hr vs hep_5_1_control
    ("SRR31847384", "SRR31847385"), # hep_6_1_0hr vs hep_6_1_control
    ("SRR31847383", "SRR31847385"), # hep_6_1_8hr vs hep_6_1_control
]

paired_metadata_df_gse285497 = create_paired_metadata(
    combined_df=GSE285497_combined,
    defined_sample_pairs=defined_pairs_gse285497,
    sample_id_column_name="accession"
)


if paired_metadata_df_gse285497 is not None:
    paired_metadata_df_gse285497.write_csv(
        "../../Data/metadata/metadata_paired/GSE285497_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse285497)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (52, 84)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ bat ┆ lib ┆ col ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ ch  ┆ rar ┆ umn ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ --- ┆ y_n ┆ --- ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ str ┆ ame ┆ str ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ _ri ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ ght ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hek ┆ HEK ┆ GSM ┆ Pub ┆ Dec ┆ Dec ┆ SRA ┆ 1   ┆ hum ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Nik ┆ nni ┆ Bio ┆ Cal ┆ 800 ┆ Ful ┆ CA  ┆ 928 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ hum ┆ HEK ┆ hum ┆ wil ┆ hea ┆ 1   ┆ HEK ┆ HEK ┆ hg3 ┆ SAM ┆ NEB ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Tra ┆ SRA ┆ cDN ┆ 202 ┆ 388 ┆ 290 ┆ ILL ┆ nul ┆ nul ┆ SRP ┆ 406 ┆ Tra ┆ nul ┆ Ill ┆ Ill ┆ nul ┆ 121 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ nul ┆ GSM ┆ Cel ┆ nul ┆ GSM ┆ nul ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ nul │
│ 318 ┆ 318 ┆ _1_ ┆ _1_ ┆ 870 ┆ lic ┆ 29  ┆ 31  ┆     ┆     ┆ an  ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ ola ┆ kol ┆ log ┆ ifo ┆ N.  ┆ ler ┆     ┆ 31  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 870 ┆ E   ┆ 285 ┆     ┆ 272 ┆ an  ┆ 293 ┆ an  ┆ d   ┆ tsh ┆     ┆ 1_0 ┆ 7_0 ┆ 8   ┆ N46 ┆ Nex ┆ ps: ┆ C   ┆ min ┆ C   ┆ 318 ┆ umi ┆ nsc ┆ 204 ┆ A   ┆ 5-0 ┆ 579 ┆ 539 ┆ UMI ┆ l   ┆ l   ┆ 554 ┆ 297 ┆ nsc ┆ l   ┆ umi ┆ umi ┆ l   ┆ 889 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ l   ┆ 870 ┆ ls  ┆ l   ┆ 870 ┆ l   ┆ 870 ┆ 5-0 ┆ NA1 ┆ 236 ┆ 5-0 ┆ 285 ┆ l   │
│ 474 ┆ 474 ┆ 1_0 ┆ 1;0 ┆ 344 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ emb ┆ sap ┆     ┆ RNA ┆ 76  ┆ s,, ┆ aid ┆ ica ┆ rni ┆ Sta ┆ ton ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 344 ┆     ┆ 497 ┆     ┆ 073 ┆ emb ┆ cel ┆ emb ┆ typ ┆ ock ┆     ┆ R_1 ┆ R   ┆     ┆ 011 ┆ t®  ┆ //d ┆     ┆ .   ┆     ┆ 474 ┆ na  ┆ rip ┆ 234 ┆     ┆ 1-2 ┆ 554 ┆ 919 ┆ NA  ┆     ┆     ┆ 280 ┆ 63  ┆ rip ┆     ┆ na  ┆ na  ┆     ┆ 289 ┆ q   ┆ RIP ┆     ┆     ┆     ┆ 344 ┆ fro ┆     ┆ 344 ┆     ┆ 344 ┆ 1-2 ┆ 204 ┆ 571 ┆ 1-2 ┆ 497 ┆     │
│ 60  ┆ 61  ┆ hr  ┆ hr  ┆ 0   ┆ Dec ┆ 4   ┆ 4   ┆     ┆     ┆ ryo ┆ ien ┆     ┆     ┆     ┆ Nik ┆ is@ ┆ l   ┆ a   ┆ te  ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 0   ┆     ┆     ┆     ┆ 23  ┆ ryo ┆ ls  ┆ ryo ┆ e   ┆ vs  ┆     ┆ _B1 ┆ vs  ┆     ┆ 606 ┆ Ult ┆ oi. ┆     ┆     ┆     ┆ 60  ┆ Nov ┆ tom ┆ 9   ┆     ┆ 9   ┆ 3   ┆ 6;2 ┆     ┆     ┆     ┆     ┆ vs  ┆ tom ┆     ┆ Nov ┆ Nov ┆     ┆ 00  ┆     ┆ TOM ┆     ┆     ┆     ┆ 0_r ┆ m   ┆     ┆ 0_r ┆     ┆ 0   ┆ 9   ┆ 088 ┆ 89  ┆ 9   ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 31  ┆     ┆     ┆     ┆     ┆ nic ┆ s   ┆     ┆     ┆     ┆ ola ┆ ful ┆ Sci ┆ Sta ┆ Col ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ nic ┆     ┆ nic ┆     ┆ no  ┆     ┆ vs  ┆ HEK ┆     ┆ vs  ┆ raT ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆ ics ┆     ┆     ┆     ┆ vs  ┆ 962 ┆     ┆     ┆     ┆     ┆ 399 ┆ ics ┆     ┆ aSe ┆ aSe ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆     ┆ 1   ┆ the ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ hek ┆ HEK ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ kid ┆     ┆     ┆     ┆     ┆ idi ┆ ler ┆ enc ┆ te  ┆ leg ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ kid ┆     ┆ kid ┆     ┆ hea ┆     ┆ HEK ┆ 7cn ┆     ┆ SAM ┆ M   ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆ Unv ┆     ┆     ┆     ┆ 378 ┆ 522 ┆     ┆     ┆     ┆     ┆ 261 ┆ Unv ┆     ┆ q   ┆ q   ┆     ┆ 119 ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ con ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ _1_ ┆ _1_ ┆ 870 ┆ 4   ┆     ┆     ┆     ┆     ┆ ney ┆     ┆     ┆     ┆     ┆ s   ┆ ton ┆ e   ┆ Uni ┆ e   ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 870 ┆     ┆     ┆     ┆ 272 ┆ ney ┆     ┆ ney ┆     ┆ tsh ┆     ┆ 1_c ┆ t   ┆     ┆ N46 ┆ RNA ┆ .10 ┆     ┆     ┆     ┆ 318 ┆ 600 ┆ eil ┆     ┆     ┆     ┆ 660 ┆ 271 ┆     ┆     ┆     ┆     ┆ 63  ┆ eil ┆     ┆ 600 ┆ 600 ┆     ┆ 778 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ tro ┆     ┆ GSM ┆     ┆ 870 ┆     ┆     ┆ 236 ┆     ┆     ┆     │
│     ┆     ┆ 1_c ┆ 1;c ┆ 343 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆ ver ┆ Blv ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 343 ┆     ┆     ┆     ┆ 073 ┆ cel ┆     ┆ cel ┆     ┆ ock ┆     ┆ nt_ ┆     ┆     ┆ 011 ┆ Lib ┆ 16/ ┆     ┆     ┆     ┆ 474 ┆ 0   ┆ Can ┆     ┆     ┆     ┆ 568 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ Can ┆     ┆ 0   ┆ 0   ┆     ┆ 489 ┆     ┆     ┆     ┆     ┆     ┆ 870 ┆ l,  ┆     ┆ 870 ┆     ┆ 343 ┆     ┆     ┆ 571 ┆     ┆     ┆     │
│     ┆     ┆ ont ┆ ont ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆ ist ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆ 22  ┆ ls  ┆     ┆ ls  ┆     ┆     ┆     ┆ 1_B ┆     ┆     ┆ 607 ┆ rar ┆ j.c ┆     ┆     ┆     ┆ 61  ┆ seq ┆ oni ┆     ┆     ┆     ┆ 8   ┆ 283 ┆     ┆     ┆     ┆     ┆     ┆ oni ┆     ┆     ┆ seq ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆ 343 ┆ 0R, ┆     ┆ 343 ┆     ┆ 9   ┆     ┆     ┆ 88  ┆     ┆     ┆     │
│     ┆     ┆ rol ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ y   ┆ str ┆     ┆     ┆     ┆     ┆ uen ┆ cal ┆     ┆     ┆     ┆     ┆ 172 ┆     ┆     ┆     ┆     ┆     ┆ cal ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_r ┆ and ┆     ┆ 9_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ful ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆ es. ┆     ┆     ┆     ┆     ┆ cin ┆ and ┆     ┆     ┆     ┆     ┆ 132 ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 8R  ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ler ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆ 202 ┆     ┆     ┆     ┆     ┆ g:  ┆ Non ┆     ┆     ┆     ┆     ┆ 1;2 ┆     ┆     ┆     ┆     ┆     ┆ Non ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ton ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ 5.1 ┆     ┆     ┆     ┆     ┆ GSM ┆ -Ca ┆     ┆     ┆     ┆     ┆ 903 ┆     ┆     ┆     ┆     ┆     ┆ -Ca ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ 001 ┆     ┆     ┆     ┆     ┆ 870 ┆ non ┆     ┆     ┆     ┆     ┆ 082 ┆     ┆     ┆     ┆     ┆     ┆ non ┆     ┆     ┆ 870 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆ 30  ┆     ┆     ┆     ┆     ┆ 344 ┆ ica ┆     ┆     ┆     ┆     ┆ 280 ┆     ┆     ┆     ┆     ┆     ┆ ica ┆     ┆     ┆ 344 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆ 0:  ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 0:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na® ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hea ┆     ┆     ┆ HEK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (NE ┆     ┆     ┆     ┆     ┆     ┆ _1_ ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ _1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ B,  ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ Sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sho ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ USA ┆     ┆     ┆     ┆     ┆     ┆ 0hr ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck- ┆     ┆     ┆ 0hr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ Ind ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ind ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ uce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uce ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oge ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ Pat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pat ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ hwa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hwa ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE247043 (PAIRED) single-cell RNA-seq

- validation date: 2025-05-03
- [Pre-print: Spatiotemporal Single-Cell Rna Sequencing Reveals that Cd4+T Subpopulation with High Metabolic Flux Plays Pivotal Roles Under in Hyperthermia Treatment Warts](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4636648)
- これはsingle-cell RNA-seq (scRNA-seq) のデータ
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 11. GSE279445 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-05-03
- [Ultrasound Control of Genomic Regulatory Toolboxes for Cancer Immunotherapy](https://doi.org/10.1038/s41467-024-54477-7)
- Nalm6 cells という細胞種に対してbulk RNA-seqを行っているデータ
- 43℃ 10 min. で高温に曝露しているデータと、コントロールのデータが存在するので解析に使用する

In [34]:
GSE279445_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE279445/GSE279445_PEP/GSE279445_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1038/s41467-024-54477-7").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("10 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE279445_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE279445_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE279445_iseq_filtered = GSE279445_iseq[[s.name for s in GSE279445_iseq if not (s.null_count() == GSE279445_iseq.height)]]

GSE279445_combined = GSE279445_PEP.join(
    GSE279445_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE279445_combined = GSE279445_combined[[s.name for s in GSE279445_combined if not (s.null_count() == GSE279445_combined.height)]]

GSE279445_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE279445_modified_metadata.tsv",
    separator='\t'
)

# display(GSE279445_combined)

In [35]:
defined_pairs_gse279445 = [
    ("SRR30989156", "SRR30989157"), # N6215HS24h vs N6215CT24h
    ("SRR30989154", "SRR30989155"), # N6203HS24h vs N6203CT24h
    ("SRR30989152", "SRR30989153"), # N6215HS48h vs N6215CT48h
    ("SRR30989150", "SRR30989151"), # N6203HS48h vs N6203CT48h
    ("SRR30989148", "SRR30989149"), # N6215HS96h vs N6215CT96h
    ("SRR30989146", "SRR30989147")  # N6203HS96h vs N6203CT96h
]

paired_metadata_df_gse279445 = create_paired_metadata(
    combined_df=GSE279445_combined,
    defined_sample_pairs=defined_pairs_gse279445,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse279445 is not None:
    paired_metadata_df_gse279445.write_csv(
        "../../Data/metadata/metadata_paired/GSE279445_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse279445)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 76)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ --- ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ str ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆     ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆     ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ s_c ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆ str ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ n62 ┆ N62 ┆ GSM ┆ Pub ┆ Oct ┆ Oct ┆ SRA ┆ 1   ┆ Nal ┆ Hom ┆ 960 ┆ cel ┆ tot ┆ GPL ┆ Kun ┆ sun ┆ +86 ┆ She ┆ She ┆ Gua ┆ 518 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ NCB ┆ Raw ┆ SAM ┆ unk ┆ htt ┆ 43  ┆ 10  ┆ 37  ┆ SRR ┆ Ill ┆ Eff ┆ SRA ┆ cDN ┆ 202 ┆ 254 ┆ 182 ┆ ILL ┆ mis ┆ Gen ┆ N62 ┆ SRP ┆ 237 ┆ Eff ┆ N62 ┆ Ill ┆ Ill ┆ 711 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ Nal ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 309 ┆ 309 ┆ 15h ┆ 15H ┆ 857 ┆ lic ┆ 14  ┆ 14  ┆     ┆     ┆ m6  ┆ o   ┆ 6   ┆ l   ┆ al  ┆ 167 ┆ ,,S ┆ kun ┆ 755 ┆ nzh ┆ nzh ┆ ngd ┆ 132 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 857 ┆ E   ┆ 279 ┆     ┆ 263 ┆ I   ┆ rea ┆ N44 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 309 ┆ umi ┆ ect ┆ 199 ┆ A   ┆ 4-1 ┆ 109 ┆ 524 ┆ UMI ┆ sin ┆ eri ┆ 15H ┆ 538 ┆ 328 ┆ ect ┆ 15H ┆ umi ┆ umi ┆ 986 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 857 ┆ 857 ┆ al  ┆ sin ┆ 857 ┆ m6  ┆ 857 ┆ 4-1 ┆ NA1 ┆ 229 ┆ 4-1 ┆ 279 │
│ 891 ┆ 891 ┆ s24 ┆ S24 ┆ 076 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ lin ┆ RNA ┆ 91  ┆ un  ┆ @sz ┆ 869 ┆ en  ┆ en  ┆ ong ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 076 ┆     ┆ 445 ┆     ┆ 774 ┆ GRC ┆ d   ┆ 280 ┆ n   ┆ //d ┆     ┆ .   ┆     ┆ 891 ┆ na  ┆ of  ┆ 156 ┆     ┆ 0-1 ┆ 315 ┆ 317 ┆ NA  ┆ g   ┆ c   ┆ S24 ┆ 492 ┆ 79  ┆ of  ┆ S24 ┆ na  ┆ na  ┆ 370 ┆ q   ┆ RIP ┆     ┆     ┆ 076 ┆ 076 ┆ RNA ┆ g   ┆ 076 ┆     ┆ 076 ┆ 0-1 ┆ 172 ┆ 012 ┆ 0-1 ┆ 445 │
│ 56  ┆ 57  ┆ h   ┆ h   ┆ 2   ┆ Oct ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ e:  ┆     ┆     ┆     ┆ bl. ┆ 677 ┆ Bay ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 2   ┆     ┆     ┆     ┆ 50  ┆ h38 ┆ cou ┆ 146 ┆     ┆ oi. ┆     ┆     ┆     ┆ 56  ┆ HiS ┆ HS- ┆ 9   ┆     ┆ 6   ┆ 8   ┆ 9;1 ┆     ┆     ┆     ┆ h   ┆     ┆ vs  ┆ HS- ┆ h   ┆ HiS ┆ HiS ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_r ┆ was ┆     ┆ 2_r ┆     ┆ 2   ┆ 6   ┆ 720 ┆ 88  ┆ 6   ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ Nal ┆     ┆     ┆     ┆ ac. ┆ 10  ┆ Lab ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ nts ┆ vs  ┆     ┆ org ┆     ┆     ┆     ┆ vs  ┆ eq  ┆ med ┆     ┆     ┆     ┆ vs  ┆ 919 ┆     ┆     ┆     ┆ vs  ┆     ┆ 232 ┆ med ┆ vs  ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ col ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ n62 ┆ N62 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m6  ┆     ┆     ┆     ┆ cn  ┆     ┆ ora ┆     ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ for ┆ SAM ┆     ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ 250 ┆ iat ┆     ┆     ┆     ┆ 246 ┆ 994 ┆     ┆     ┆     ┆ N62 ┆     ┆ 439 ┆ iat ┆ N62 ┆ 250 ┆ 250 ┆ 697 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ lec ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ 15c ┆ 15C ┆ 857 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tor ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 857 ┆     ┆     ┆     ┆ 263 ┆     ┆ all ┆ N44 ┆     ┆ .10 ┆     ┆     ┆     ┆ 309 ┆ 0   ┆ ed  ┆     ┆     ┆     ┆ 357 ┆ 789 ┆     ┆     ┆     ┆ 15C ┆     ┆ 14  ┆ ed  ┆ 15C ┆ 0   ┆ 0   ┆ 317 ┆     ┆     ┆     ┆     ┆ 857 ┆ GSM ┆ ted ┆     ┆ GSM ┆     ┆ 857 ┆     ┆     ┆ 229 ┆     ┆     │
│     ┆     ┆ t24 ┆ T24 ┆ 076 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 076 ┆     ┆     ┆     ┆ 774 ┆     ┆ gen ┆ 280 ┆     ┆ 38/ ┆     ┆     ┆     ┆ 891 ┆ seq ┆ tel ┆     ┆     ┆     ┆ 008 ┆ vs  ┆     ┆     ┆     ┆ T24 ┆     ┆     ┆ tel ┆ T24 ┆     ┆ seq ┆ 420 ┆     ┆     ┆     ┆     ┆ 076 ┆ 857 ┆ fro ┆     ┆ 857 ┆     ┆ 076 ┆     ┆     ┆ 012 ┆     ┆     │
│     ┆     ┆ h   ┆ h   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ 49  ┆     ┆ es  ┆ 147 ┆     ┆ s41 ┆     ┆     ┆     ┆ 57  ┆ uen ┆ ome ┆     ┆     ┆     ┆ 8   ┆ 178 ┆     ┆     ┆     ┆ h   ┆     ┆     ┆ ome ┆ h   ┆     ┆ uen ┆ 0   ┆     ┆     ┆     ┆     ┆ 1   ┆ 076 ┆ m   ┆     ┆ 076 ┆     ┆ 1   ┆     ┆     ┆ 87  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 467 ┆     ┆     ┆     ┆     ┆ cin ┆ re  ┆     ┆     ┆     ┆     ┆ 417 ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ the ┆     ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆ g:  ┆ dis ┆     ┆     ┆     ┆     ┆ 638 ┆     ┆     ┆     ┆     ┆     ┆     ┆ dis ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ eng ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-5 ┆     ┆     ┆     ┆     ┆ GSM ┆ rup ┆     ┆     ┆     ┆     ┆ 8;1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ rup ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ine ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 447 ┆     ┆     ┆     ┆     ┆ 857 ┆ tio ┆     ┆     ┆     ┆     ┆ 856 ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ 857 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ere ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-7 ┆     ┆     ┆     ┆     ┆ 076 ┆ n   ┆     ┆     ┆     ┆     ┆ 428 ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ 076 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2:  ┆ on  ┆     ┆     ┆     ┆     ┆ 557 ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N62 ┆ Nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nal ┆     ┆     ┆ N62 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15H ┆ m6  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m6  ┆     ┆     ┆ 15H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S24 ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ S24 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 24, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 96  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aft ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE234710 (PAIRED) (BRB-seq)

- validate date: 2025-05-03
- validate date: 2026-05-04
- Bulk RNA barcoding sequencing (BRB) という手法だが、メタデータを見ると、`RNA-Seq` となっている
- [Transcriptional landscape of human keratinocyte models exposed to 60-GHz millimeter-waves](https://doi.org/10.1016/j.tiv.2024.105808)
- `Sham unexposed cells(Sham)`, `millimeter waves (MMW) exposed Cells (Expo)`, `heat shock control (HSC)`の3つの実験条件 + `HEK, NHEK, HaCaT` の3つの細胞種の条件
- 温度条件は論文の [Table 1](https://www.sciencedirect.com/science/article/pii/S0887233324000389?via%3Dihub#t0005), Table 3 に記載されている
- `sham` は 36℃前後であることから、これをコントロールとして使用できると考えられる
- ~~熱を加えている、という側面があるため、全てのデータを使用する~~
- **`heat shock control (HSC)` と `sham` のみ 収集する方針に転換**
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 12. GSE229915 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-03
- [Heat promotes melanogenesis by increasing the paracrine effects in keratinocytes via the TRPV3/Ca2+/Hh signaling pathway](https://doi.org/10.1016/j.isci.2023.106749)
- 熱ストレスとメラニン生成の関係を調査している論文
- 37℃, 41℃のデータがそれぞれしっかり揃っているので解析に使用する

In [36]:
GSE229915_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE229915/GSE229915_PEP/GSE229915_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded mRNA LT Sample Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1016/j.isci.2023.106749").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("41 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("72 h.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature"), # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE229915_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE229915_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE229915_iseq_filtered = GSE229915_iseq[[s.name for s in GSE229915_iseq if not (s.null_count() == GSE229915_iseq.height)]]

GSE229915_combined = GSE229915_PEP.join(
    GSE229915_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE229915_combined = GSE229915_combined[[s.name for s in GSE229915_combined if not (s.null_count() == GSE229915_combined.height)]]

GSE229915_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE229915_modified_metadata.tsv",
    separator='\t'
)

# display(GSE229915_combined)

In [37]:
defined_pairs_gse229915 = [
    ("SRR24196212", "SRR24196215"), #heat_41_1 vs heat_37_1
    ("SRR24196211", "SRR24196214"), #heat_41_2 vs heat_37_2
    ("SRR24196210", "SRR24196213")  #heat_41_3 vs heat_37_3
]

paired_metadata_df_gse229915 = create_paired_metadata(
    combined_df=GSE229915_combined,
    defined_sample_pairs=defined_pairs_gse229915,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse229915 is not None:
    paired_metadata_df_gse229915.write_csv(
        "../../Data/metadata/metadata_paired/GSE229915_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse229915)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hea ┆ hea ┆ GSM ┆ Pub ┆ Apr ┆ May ┆ SRA ┆ 1   ┆ ski ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Lan ┆ 208 ┆ 183 ┆ 中  ┆ Cha ┆ --- ┆ 410 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ ski ┆ HaC ┆ hum ┆ not ┆ 41℃ ┆ NCB ┆ SAM ┆ Tru ┆ htt ┆ 41  ┆ 72  ┆ 37  ┆ SRR ┆ Ill ┆ Hea ┆ SRA ┆ cDN ┆ 202 ┆ 184 ┆ 139 ┆ ILL ┆ mis ┆ Gen ┆ hea ┆ SRP ┆ 252 ┆ Hea ┆ hea ┆ Ill ┆ Ill ┆ hum ┆ 704 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ HaC ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ ski │
│ 241 ┆ 241 ┆ t_4 ┆ t_4 ┆ 718 ┆ lic ┆ 17  ┆ 20  ┆     ┆     ┆ n   ┆ o   ┆ 6   ┆ al  ┆ 167 ┆ ,,Z ┆ 311 ┆ 846 ┆ 南  ┆ ngs ┆ Sel ┆ 006 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 718 ┆ E   ┆ 229 ┆     ┆ 199 ┆ n   ┆ aT  ┆ an  ┆ app ┆ for ┆ I_G ┆ N34 ┆ Seq ┆ ps: ┆ C   ┆ h.  ┆ C   ┆ 241 ┆ umi ┆ t   ┆ 162 ┆ A   ┆ 3-0 ┆ 929 ┆ 612 ┆ UMI ┆ sin ┆ eri ┆ t_4 ┆ 433 ┆ 972 ┆ t   ┆ t_4 ┆ umi ┆ umi ┆ an  ┆ 475 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 718 ┆ 718 ┆ al  ┆ sin ┆ 718 ┆ aT  ┆ 718 ┆ 3-0 ┆ NA9 ┆ 173 ┆ 3-0 ┆ 229 ┆ n   │
│ 962 ┆ 962 ┆ 1_1 ┆ 1_1 ┆ 038 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 91  ┆ han ┆ 035 ┆ 609 ┆ 大  ┆ ha  ┆ ect ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 038 ┆     ┆ 915 ┆     ┆ 929 ┆     ┆     ┆ imm ┆ lic ┆ 3   ┆ RCh ┆ 224 ┆ Str ┆ //d ┆     ┆     ┆     ┆ 962 ┆ na  ┆ pro ┆ 255 ┆     ┆ 6-0 ┆ 085 ┆ 988 ┆ NA  ┆ g   ┆ c   ┆ 1_1 ┆ 036 ┆ 80  ┆ pro ┆ 1_1 ┆ na  ┆ na  ┆ imm ┆ 911 ┆ q   ┆ RIP ┆     ┆     ┆ 038 ┆ 038 ┆ RNA ┆ g   ┆ 038 ┆     ┆ 038 ┆ 6-0 ┆ 565 ┆ 381 ┆ 6-0 ┆ 915 ┆     │
│ 12  ┆ 15  ┆ vs  ┆ vs  ┆ 6   ┆ May ┆ 3   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆ g   ┆ @cs ┆ 86  ┆ 学  ┆     ┆ One ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 6   ┆     ┆     ┆     ┆ 57  ┆     ┆     ┆ ort ┆ abl ┆ day ┆ 38. ┆ 446 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 12  ┆ HiS ┆ mot ┆ 3   ┆     ┆ 5   ┆ 3   ┆ 7;1 ┆     ┆     ┆     ┆ vs  ┆     ┆ vs  ┆ mot ┆ vs  ┆ HiS ┆ HiS ┆ ort ┆ 1   ┆     ┆ TOM ┆     ┆     ┆ 6   ┆ 6_r ┆ was ┆     ┆ 6_r ┆     ┆ 6   ┆ 5   ┆ 78  ┆ 10  ┆ 5   ┆     ┆     │
│     ┆     ┆ hea ┆ hea ┆ vs  ┆ 20  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ u.e ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ ali ┆ e   ┆ s,  ┆ p13 ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ eq  ┆ es  ┆     ┆     ┆ vs  ┆ vs  ┆ 396 ┆     ┆     ┆     ┆ hea ┆     ┆ 241 ┆ es  ┆ hea ┆ eq  ┆ eq  ┆ ali ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ t_3 ┆ t_3 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du. ┆     ┆     ┆     ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆ zed ┆     ┆ 1   ┆     ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ 250 ┆ mel ┆     ┆     ┆ 202 ┆ 176 ┆ 479 ┆     ┆     ┆     ┆ t_3 ┆     ┆ 373 ┆ mel ┆ t_3 ┆ 250 ┆ 250 ┆ zed ┆ 673 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ 7_1 ┆ 7_1 ┆ 718 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cn  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 718 ┆     ┆     ┆     ┆ 199 ┆     ┆     ┆ ker ┆     ┆ hou ┆     ┆ N34 ┆ A   ┆ .10 ┆     ┆     ┆     ┆ 241 ┆ 0   ┆ ano ┆     ┆     ┆ 3-0 ┆ 662 ┆ 674 ┆     ┆     ┆     ┆ 7_1 ┆     ┆ 00  ┆ ano ┆ 7_1 ┆ 0   ┆ 0   ┆ ker ┆ 239 ┆     ┆     ┆     ┆     ┆ 718 ┆ GSM ┆ ted ┆     ┆ GSM ┆     ┆ 718 ┆     ┆     ┆ 173 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 038 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 038 ┆     ┆     ┆     ┆ 929 ┆     ┆     ┆ ati ┆     ┆ r   ┆     ┆ 224 ┆ LT  ┆ 16/ ┆     ┆     ┆     ┆ 962 ┆ seq ┆ gen ┆     ┆     ┆ 6-1 ┆ 549 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆ seq ┆ ati ┆ 461 ┆     ┆     ┆     ┆     ┆ 038 ┆ 718 ┆ usi ┆     ┆ 718 ┆     ┆ 038 ┆     ┆     ┆ 381 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 54  ┆     ┆     ┆ noc ┆     ┆ per ┆     ┆ 449 ┆ Sam ┆ j.i ┆     ┆     ┆     ┆ 15  ┆ uen ┆ esi ┆     ┆     ┆ 6   ┆ 6   ┆ 133 ┆     ┆     ┆     ┆     ┆     ┆     ┆ esi ┆     ┆     ┆ uen ┆ noc ┆ 0   ┆     ┆     ┆     ┆     ┆ 3   ┆ 038 ┆ ng  ┆     ┆ 038 ┆     ┆ 3   ┆     ┆     ┆ 05  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yte ┆     ┆ day ┆     ┆     ┆ ple ┆ sci ┆     ┆     ┆     ┆     ┆ cin ┆ s   ┆     ┆     ┆     ┆     ┆ 448 ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ cin ┆ yte ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ the ┆     ┆ 3_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ Pre ┆ .20 ┆     ┆     ┆     ┆     ┆ g:  ┆ by  ┆     ┆     ┆     ┆     ┆ 789 ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ mir ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37℃ ┆     ┆     ┆ p   ┆ 23. ┆     ┆     ┆     ┆     ┆ GSM ┆ inc ┆     ┆     ┆     ┆     ┆ 5;1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Van ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆ Kit ┆ 106 ┆     ┆     ┆     ┆     ┆ 718 ┆ rea ┆     ┆     ┆     ┆     ┆ 334 ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆ 718 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 749 ┆     ┆     ┆     ┆     ┆ 038 ┆ sin ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆     ┆ sin ┆     ┆     ┆ 038 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ miR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ day ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6:  ┆ g   ┆     ┆     ┆     ┆     ┆ 792 ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆ 6:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t_4 ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆ t_4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_1 ┆ acr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ acr ┆     ┆     ┆ 1_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ ine ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ine ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ eff ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eff ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Am ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ day ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ ker ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ker ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ noc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ noc ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 13. GSE242710 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-03
- [Synergetic support of cartilage homeostasis via coupled thermal-pressure stimuli: a transcriptomic study in human cartilage explants](https://doi.org/10.3389/fmede.2023.1291191)
- 物理的な負荷 (hydrostatic pressure (HP))をかけているサンプル、段階的な温度上昇 (Isolated temperature increase group (“T”):) を加えているサンプル、複合的なサンプルなどが含まれている
- 負荷をかけていないサンプルとTグループのサンプルを収集

In [38]:
GSE242710_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE242710/GSE242710_PEP/GSE242710_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra II Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (NEW ENGLAND Biolabs)
    pl.lit("https://doi.org/10.3389/fmede.2023.1291191").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("32.5 C to 38.7 C (gradient)").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("90 min. × 5 days").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("32.5 C").alias("control treatment temperature"), # add control temperature column
    pl.lit("cartilage").alias("cell_line"),
    pl.lit("chondrocyte").alias("cell_type")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE242710_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE242710_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE242710_iseq_filtered = GSE242710_iseq[[s.name for s in GSE242710_iseq if not (s.null_count() == GSE242710_iseq.height)]]

GSE242710_combined = GSE242710_PEP.join(
    GSE242710_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE242710_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE242710_modified_metadata.tsv",
    separator='\t'
)

# display(GSE242710_combined)

In [39]:
defined_pairs_gse242710 = [
    ("SRR25954666", "SRR25954670"), # cartilage_isolated_t_stimulation_rep1 vs cartilage_unstimulated_rep1
    ("SRR25954665", "SRR25954669"), # cartilage_isolated_t_stimulation_rep2 vs cartilage_unstimulated_rep2
    ("SRR25954664", "SRR25954668"), # cartilage_combined_hp-t_stimulation_rep1 vs cartilage_isolated_hp_stimulation_rep1
    ("SRR25954663", "SRR25954667")  # cartilage_combined_hp-t_stimulation_rep2 vs cartilage_isolated_hp_stimulation_rep2
]

paired_metadata_df_gse242710 = create_paired_metadata(
    combined_df=GSE242710_combined,
    defined_sample_pairs=defined_pairs_gse242710,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse242710 is not None:
    paired_metadata_df_gse242710.write_csv(
        "../../Data/metadata/metadata_paired/GSE242710_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse242710)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ tre ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_t ┆ atm ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ype ┆ ent ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ car ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ car ┆ GSM ┆ Pub ┆ Sep ┆ Dec ┆ SRA ┆ 1   ┆ car ┆ Hom ┆ 960 ┆ pol ┆ T_1 ┆ GPL ┆ Dom ┆ LBO ┆ STI ┆ EPF ┆ EPF ┆ Lau ┆ Vau ┆ 101 ┆ Swi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ car ┆ cho ┆ iso ┆ GRC ┆ .tx ┆ SAM ┆ NEB ┆ htt ┆ 32. ┆ 90  ┆ 32. ┆ car ┆ SRR ┆ Ill ┆ Syn ┆ SRA ┆ cDN ┆ 202 ┆ 712 ┆ 597 ┆ ILL ┆ mis ┆ Gen ┆ car ┆ SRP ┆ 215 ┆ Syn ┆ car ┆ Ill ┆ Ill ┆ cho ┆ 258 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Exp ┆ mis ┆ GSM ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ car │
│ 259 ┆ 259 ┆ til ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ til ┆ 776 ┆ lic ┆ 08  ┆ 01  ┆     ┆     ┆ til ┆ o   ┆ 6   ┆ yA  ┆ _S7 ┆ 246 ┆ ini ┆     ┆ IBI ┆ L   ┆ L   ┆ san ┆ d   ┆ 5   ┆ tze ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 776 ┆ E   ┆ 242 ┆     ┆ 216 ┆ til ┆ ndr ┆ lat ┆ h38 ┆ t   ┆ N37 ┆ Nex ┆ ps: ┆ 5 C ┆ min ┆ 5 C ┆ til ┆ 259 ┆ umi ┆ erg ┆ 170 ┆ A   ┆ 4-0 ┆ 402 ┆ 648 ┆ UMI ┆ sin ┆ eri ┆ til ┆ 459 ┆ 494 ┆ erg ┆ til ┆ umi ┆ umi ┆ ndr ┆ 284 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 776 ┆ 776 ┆ lan ┆ sin ┆ 776 ┆ 776 ┆ 3-1 ┆ NA1 ┆ 188 ┆ 3-1 ┆ 242 ┆ til │
│ 546 ┆ 546 ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆ 745 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ age ┆ sap ┆     ┆ RNA ┆ _b3 ┆ 76  ┆ que ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆ rla ┆ na  ┆     ┆ rip ┆ q   ┆ 745 ┆     ┆ 710 ┆     ┆ 732 ┆ age ┆ ocy ┆ ed  ┆     ┆ gen ┆ 324 ┆ t   ┆ //d ┆ to  ┆ . × ┆     ┆ age ┆ 546 ┆ na  ┆ eti ┆ 802 ┆     ┆ 3-2 ┆ 011 ┆ 984 ┆ NA  ┆ g   ┆ c   ┆ age ┆ 273 ┆ 93  ┆ eti ┆ age ┆ na  ┆ na  ┆ ocy ┆ 130 ┆ q   ┆ RIP ┆     ┆     ┆ 745 ┆ 745 ┆ t   ┆ g   ┆ 745 ┆ 745 ┆ 2-0 ┆ 014 ┆ 369 ┆ 2-0 ┆ 710 ┆ age │
│ 66  ┆ 70  ┆ _is ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ 5   ┆ Dec ┆ 3   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ 8   ┆     ┆ ,P. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nd  ┆ Nov ┆     ┆ tom ┆     ┆ 5   ┆     ┆     ┆     ┆ 20  ┆     ┆ te  ┆ T   ┆     ┆ e   ┆ 517 ┆ Ult ┆ oi. ┆ 38. ┆ 5   ┆     ┆     ┆ 66  ┆ Nov ┆ c   ┆ 5   ┆     ┆ 7   ┆ vs  ┆ ;60 ┆     ┆     ┆     ┆ ,   ┆     ┆ vs  ┆ c   ┆ ,   ┆ Nov ┆ Nov ┆ te  ┆ 5   ┆     ┆ TOM ┆     ┆     ┆ 5   ┆ 5_r ┆ sam ┆     ┆ 5_r ┆ 5   ┆ 2   ┆ 403 ┆ 22  ┆ 2   ┆     ┆     │
│     ┆     ┆ ola ┆     ┆     ┆     ┆     ┆     ┆     ┆ iso ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆ ,Pi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ sti ┆     ┆ cou ┆ vs  ┆ ra  ┆ org ┆ 7 C ┆ day ┆     ┆     ┆ vs  ┆ aSe ┆ Sup ┆     ┆     ┆ vs  ┆ 142 ┆ 337 ┆     ┆     ┆     ┆ iso ┆     ┆ 434 ┆ Sup ┆ iso ┆ aSe ┆ aSe ┆     ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ple ┆     ┆ 1   ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆ lat ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C_1 ┆     ┆ ole ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆ mul ┆     ┆ nts ┆ SAM ┆ II  ┆ /10 ┆ (gr ┆ s   ┆     ┆     ┆ SRR ┆ q   ┆ por ┆     ┆     ┆ 202 ┆ 660 ┆ 286 ┆     ┆     ┆     ┆ lat ┆     ┆ 188 ┆ por ┆ lat ┆ q   ┆ q   ┆     ┆ 524 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ s   ┆     ┆ vs  ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ _t_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ 776 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _S3 ┆     ┆ tti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 776 ┆     ┆     ┆     ┆ 216 ┆     ┆     ┆ ati ┆     ┆ of  ┆ N37 ┆ Dir ┆ .33 ┆ adi ┆     ┆     ┆     ┆ 259 ┆ 600 ┆ t   ┆     ┆     ┆ 3-1 ┆ 545 ┆ 4   ┆     ┆     ┆     ┆ ed  ┆     ┆ 85  ┆ t   ┆ ed  ┆ 600 ┆ 600 ┆     ┆ 155 ┆     ┆     ┆     ┆     ┆ 776 ┆ GSM ┆ wer ┆     ┆ GSM ┆ 776 ┆     ┆     ┆ 188 ┆     ┆     ┆     │
│     ┆     ┆ sti ┆     ┆     ┆     ┆     ┆     ┆     ┆ T   ┆ 745 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _b3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 745 ┆     ┆     ┆     ┆ 732 ┆     ┆     ┆ on  ┆     ┆ 8   ┆ 324 ┆ ect ┆ 89/ ┆ ent ┆     ┆     ┆     ┆ 546 ┆ 0   ┆ of  ┆     ┆     ┆ 2-1 ┆ 2   ┆ vs  ┆     ┆     ┆     ┆ T   ┆     ┆     ┆ of  ┆ T   ┆ 0   ┆ 0   ┆     ┆ 855 ┆     ┆     ┆     ┆     ┆ 745 ┆ 776 ┆ e   ┆     ┆ 776 ┆ 745 ┆     ┆     ┆ 369 ┆     ┆     ┆     │
│     ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆     ┆ sti ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ 16  ┆     ┆     ┆ vs  ┆     ┆ sam ┆ 521 ┆ ion ┆ fme ┆ )   ┆     ┆     ┆     ┆ 70  ┆ seq ┆ Car ┆     ┆     ┆ 3   ┆     ┆ 100 ┆     ┆     ┆     ┆ sti ┆     ┆     ┆ Car ┆ sti ┆     ┆ seq ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 1   ┆ 745 ┆ sna ┆     ┆ 745 ┆ 1   ┆     ┆     ┆ 18  ┆     ┆     ┆     │
│     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uns ┆     ┆ ple ┆     ┆ al  ┆ de. ┆     ┆     ┆     ┆     ┆     ┆ uen ┆ til ┆     ┆     ┆     ┆     ┆ 564 ┆     ┆     ┆     ┆ mul ┆     ┆     ┆ til ┆ mul ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ p-f ┆     ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ on_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tim ┆     ┆ s   ┆     ┆ RNA ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆ cin ┆ age ┆     ┆     ┆     ┆     ┆ 564 ┆     ┆     ┆     ┆ ati ┆     ┆     ┆ age ┆ ati ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ roz ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ on, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ula ┆     ┆     ┆     ┆ Lib ┆ 3.1 ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆ Hom ┆     ┆     ┆     ┆     ┆ 1;1 ┆     ┆     ┆     ┆ on, ┆     ┆     ┆ Hom ┆ on, ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ en  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ rar ┆ 291 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ eos ┆     ┆     ┆     ┆     ┆ 063 ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ eos ┆ rep ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ 191 ┆     ┆     ┆     ┆     ┆     ┆ 776 ┆ tas ┆     ┆     ┆     ┆     ┆ 006 ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ tas ┆ 1   ┆     ┆ 776 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ liq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ car ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆ 745 ┆ is  ┆     ┆     ┆     ┆     ┆ 588 ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ is  ┆ vs  ┆     ┆ 745 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uid ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ til ┆     ┆     ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆ via ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆ via ┆ car ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆ til ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆ car ┆ Cou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ til ┆     ┆     ┆ Cou ┆ til ┆     ┆ car ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rog ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _un ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ til ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆     ┆     ┆ ple ┆ age ┆     ┆ til ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ en  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sti ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆ d   ┆ ,   ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆     ┆ uns ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ The ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uns ┆     ┆     ┆ The ┆ uns ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sub ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE182204 (PAIRED) NO DOWNLOAD

- validation date: 2025-05-03
- [Acetyl-methyllysine marks chromatin at active transcription start sites](https://doi.org/10.1038/s41586-023-06565-9)
- ChIP-seqなども含まれており、これらはフィルタリングする
- RNA-seqに加え、TT-TL-seq (transient-transcriptome TimeLapse sequencing), start-TimeLapse sequencing (STL-seq) も含まれている
- 熱ストレス処理のデータは Drosophila melanogaster の ChIP-seqなので今回はこのデータは収集しない

In [40]:
# GSE182204_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE182204/GSE182204_PEP/GSE182204_PEP_raw.csv",
#     separator=','
# ).filter(
#     (pl.col("sample_organism_ch1") == "Homo sapiens") &
#     ~((pl.col("sample_library_strategy") == "ChIP-Seq") | (pl.col("sample_molecule_ch1") == "genomic DNA"))
# )

# display(GSE182204_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 14. GSE221579 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-03
- [Transcriptional Response in Human Jurkat T Lymphocytes to a near Physiological Hypergravity Environment and to One Common in Routine Cell Culture Protocols](https://doi.org/10.3390/ijms24021351)
- hypergravity (hypg) などが含まれている
- 同じサンプル名の`Ctrl`と`heat`を選抜、解析に使用する
- 温度条件は42℃, 5分 ( `Materials & Methods` より)

In [ ]:
GSE221579_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE221579/GSE221579_PEP/GSE221579_PEP_raw.csv",
    separator=','
).filter(
    ~(pl.col("treatment").str.contains(r'hypg') | pl.col("treatment").str.contains(r'wait')) & 
    pl.col("sample_title").str.contains(r'-Achilles_')
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("E7765L NEBNext Ultra II Directional RNA Library Prep with Beads").alias("rna_library"), # add rna_library column from GEO webpage (SRX)
    pl.lit("https://doi.org/10.3390/ijms24021351").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("5 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE221579_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE221579_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE221579_iseq_filtered = GSE221579_iseq[[s.name for s in GSE221579_iseq if not (s.null_count() == GSE221579_iseq.height)]]

GSE221579_combined = GSE221579_PEP.join(
    GSE221579_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE221579_combined = GSE221579_combined[[s.name for s in GSE221579_combined if not (s.null_count() == GSE221579_combined.height)]]

GSE221579_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE221579_modified_metadata.tsv",
    separator='\t'
)

# display(GSE221579_combined)

In [42]:
defined_pairs_gse221579 = [
    ("SRR22865323", "SRR22865339"), # 65_65_gbf2021-achilles_a-heat-65 vs 49_49_gbf2021-achilles_a-ctrl-49
    ("SRR22865322", "SRR22865338"), # 66_66_gbf2021-achilles_a-heat-66 vs 50_50_gbf2021-achilles_a-ctrl-50
    ("SRR22865321", "SRR22865337"), # 67_67_gbf2021-achilles_a-heat-67 vs 51_51_gbf2021-achilles_a-ctrl-51
    ("SRR22865320", "SRR22865336")  # 68_68_gbf2021-achilles_a-heat-68 vs 52_52_gbf2021-achilles_a-ctrl-52
]

paired_metadata_df_gse221579 = create_paired_metadata(
    combined_df=GSE221579_combined,
    defined_sample_pairs=defined_pairs_gse221579,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse221579 is not None:
    paired_metadata_df_gse221579.write_csv(
        "../../Data/metadata/metadata_paired/GSE221579_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse221579)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ cen ┆ tre ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ tri ┆ atm ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ fug ┆ ent ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ e   ┆ --- ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ 65_ ┆ 65_ ┆ GSM ┆ Pub ┆ Dec ┆ Feb ┆ SRA ┆ 1   ┆ in  ┆ Hom ┆ 960 ┆ tot ┆ 65_ ┆ GPL ┆ Cor ┆ cor ┆ Ins ┆ Uni ┆ Win ┆ Zur ┆ 805 ┆ Swi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ in  ┆ T   ┆ Jur ┆ GBF ┆ hea ┆ hg3 ┆ fea ┆ SAM ┆ E77 ┆ htt ┆ 42  ┆ 5   ┆ 37  ┆ SRR ┆ Ill ┆ Sho ┆ SRA ┆ cDN ┆ 202 ┆ 332 ┆ 245 ┆ ILL ┆ Gen ┆ 65_ ┆ SRP ┆ 468 ┆ Sho ┆ 65_ ┆ Ill ┆ Ill ┆ Jur ┆ 103 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Elu ┆ GSM ┆ T   ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ in  │
│ 228 ┆ 228 ┆ 65_ ┆ 65_ ┆ 688 ┆ lic ┆ 22  ┆ 07  ┆     ┆     ┆ vit ┆ o   ┆ 6   ┆ al  ┆ 65_ ┆ 246 ┆ a,S ┆ a.t ┆ tit ┆ ver ┆ ter ┆ ich ┆ 7   ┆ tze ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 688 ┆ E   ┆ 221 ┆     ┆ 188 ┆ vit ┆ lym ┆ kat ┆ 202 ┆ t   ┆ 8   ┆ tur ┆ N32 ┆ 65L ┆ ps: ┆ C   ┆ min ┆ C   ┆ 228 ┆ umi ┆ rt- ┆ 156 ┆ A   ┆ 3-0 ┆ 227 ┆ 851 ┆ UMI ┆ eri ┆ 65_ ┆ 414 ┆ 179 ┆ rt- ┆ 65_ ┆ umi ┆ umi ┆ kat ┆ 935 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 688 ┆ 688 ┆ sio ┆ 688 ┆ lym ┆ 688 ┆ 3-0 ┆ NA9 ┆ 162 ┆ 3-0 ┆ 221 ┆ vit │
│ 653 ┆ 653 ┆ gbf ┆ GBF ┆ 665 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ ro  ┆ sap ┆     ┆ RNA ┆ GBF ┆ 76  ┆ .,T ┆ hie ┆ ute ┆ sit ┆ thu ┆     ┆     ┆ rla ┆ na  ┆     ┆ rip ┆ q   ┆ 665 ┆     ┆ 579 ┆     ┆ 240 ┆ ro  ┆ pho ┆ T   ┆ 1-A ┆ vs  ┆     ┆ eCo ┆ 368 ┆ NEB ┆ //d ┆     ┆ .   ┆ (in ┆ 653 ┆ na  ┆ ter ┆ 438 ┆     ┆ 2-1 ┆ 861 ┆ 922 ┆ NA  ┆ c   ┆ GBF ┆ 464 ┆ 03  ┆ ter ┆ GBF ┆ na  ┆ na  ┆ T   ┆ 744 ┆ q   ┆ RIP ┆     ┆     ┆ 665 ┆ 665 ┆ n/a ┆ 665 ┆ pho ┆ 665 ┆ 2-0 ┆ 150 ┆ 561 ┆ 2-0 ┆ 579 ┆ ro  │
│ 23  ┆ 39  ┆ 202 ┆ 202 ┆ 8   ┆ Feb ┆ 2   ┆ 3   ┆     ┆     ┆ imm ┆ ien ┆     ┆     ┆ 202 ┆     ┆ hie ┆ l@u ┆ of  ┆ y   ┆ rer ┆     ┆     ┆ nd  ┆ Nov ┆     ┆ tom ┆     ┆ 8   ┆     ┆     ┆     ┆ 90  ┆ imm ┆ cyt ┆ cel ┆ chi ┆ Ctr ┆     ┆ unt ┆ 461 ┆ Nex ┆ oi. ┆     ┆     ┆ fer ┆ 23  ┆ Nov ┆ m   ┆ 4   ┆     ┆ 1   ┆ 7   ┆ 6;2 ┆     ┆     ┆ 202 ┆     ┆ vs  ┆ m   ┆ 202 ┆ Nov ┆ Nov ┆ cel ┆ 66  ┆     ┆ TOM ┆     ┆     ┆ 8   ┆ 8_r ┆ ddi ┆ 8_r ┆ cyt ┆ 8   ┆ 9   ┆ 30  ┆ 85  ┆ 9   ┆     ┆ imm │
│     ┆     ┆ 1-a ┆ 1-A ┆ vs  ┆ 07  ┆     ┆     ┆     ┆     ┆ ort ┆ s   ┆     ┆     ┆ 1-A ┆     ┆ l   ┆ zh. ┆ Ana ┆ of  ┆ str ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ ort ┆ e   ┆ ls  ┆ lle ┆ l   ┆     ┆ s   ┆ vs  ┆ t   ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ hyp ┆     ┆     ┆ vs  ┆ vs  ┆ 562 ┆     ┆     ┆ 1-A ┆     ┆ 439 ┆ hyp ┆ 1-A ┆ aSe ┆ aSe ┆ ls  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ tio ┆ 1   ┆ e   ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆ ort │
│     ┆     ┆ chi ┆ chi ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆ chi ┆     ┆     ┆ ch  ┆ tom ┆ Zur ┆ ass ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ ali ┆     ┆     ┆ s   ┆     ┆     ┆ out ┆ SAM ┆ Ult ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ erg ┆     ┆     ┆ 202 ┆ 310 ┆ 037 ┆     ┆     ┆ chi ┆     ┆ 826 ┆ erg ┆ chi ┆ q   ┆ q   ┆     ┆ 976 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ n   ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆ ali │
│     ┆     ┆ lle ┆ lle ┆ 688 ┆ 3   ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆ lle ┆     ┆     ┆     ┆ y   ┆ ich ┆ e   ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 688 ┆     ┆     ┆     ┆ 188 ┆ zed ┆     ┆     ┆     ┆     ┆     ┆ put ┆ N32 ┆ ra  ┆ .10 ┆     ┆     ┆     ┆ 228 ┆ 600 ┆ rav ┆     ┆     ┆ 3-0 ┆ 593 ┆ 859 ┆     ┆     ┆ lle ┆     ┆ 73  ┆ rav ┆ lle ┆ 600 ┆ 600 ┆     ┆ 415 ┆     ┆     ┆     ┆     ┆ 688 ┆ GSM ┆ of  ┆ GSM ┆     ┆ 688 ┆     ┆     ┆ 162 ┆     ┆     ┆ zed │
│     ┆     ┆ s_a ┆ s_A ┆ 664 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ s_A ┆     ┆     ┆     ┆     ┆     ┆ 190 ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 664 ┆     ┆     ┆     ┆ 240 ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ 368 ┆ II  ┆ 38/ ┆     ┆     ┆     ┆ 653 ┆ 0   ┆ ity ┆     ┆     ┆ 2-1 ┆ 589 ┆ vs  ┆     ┆     ┆ s_A ┆     ┆     ┆ ity ┆ s_A ┆ 0   ┆ 0   ┆     ┆ 340 ┆     ┆     ┆     ┆     ┆ 664 ┆ 688 ┆ RLT ┆ 688 ┆     ┆ 664 ┆     ┆     ┆ 561 ┆     ┆     ┆ cel │
│     ┆     ┆ -he ┆ -he ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ -he ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 74  ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ raw ┆ 477 ┆ Dir ┆ s41 ┆     ┆     ┆     ┆ 39  ┆ seq ┆ eff ┆     ┆     ┆ 0   ┆ 1   ┆ 230 ┆     ┆     ┆ -he ┆     ┆     ┆ eff ┆ -he ┆     ┆ seq ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆ 2   ┆ 664 ┆ buf ┆ 664 ┆     ┆ 2   ┆     ┆     ┆ 69  ┆     ┆     ┆ ls  │
│     ┆     ┆ at- ┆ at- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cou ┆     ┆ ect ┆ 586 ┆     ┆     ┆     ┆     ┆ uen ┆ ect ┆     ┆     ┆     ┆     ┆ 814 ┆     ┆     ┆ at- ┆     ┆     ┆ ect ┆ at- ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ fer ┆ 2_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 65  ┆ 65  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 65_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nts ┆     ┆ ion ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆ s   ┆     ┆     ┆     ┆     ┆ 252 ┆     ┆     ┆ 65  ┆     ┆     ┆ s   ┆ 65  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ,   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S65 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ al  ┆ 3-0 ┆     ┆     ┆     ┆     ┆ g:  ┆ on  ┆     ┆     ┆     ┆     ┆ 9;2 ┆     ┆     ┆ vs  ┆     ┆     ┆ on  ┆ vs  ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 49_ ┆ 49_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _R1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆ RNA ┆ 656 ┆     ┆     ┆     ┆     ┆ GSM ┆ Jur ┆     ┆     ┆     ┆     ┆ 398 ┆     ┆     ┆ 49_ ┆     ┆     ┆ Jur ┆ 49_ ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 49_ ┆ 49_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tab ┆     ┆ Lib ┆ 5-9 ┆     ┆     ┆     ┆     ┆ 688 ┆ kat ┆     ┆     ┆     ┆     ┆ 707 ┆     ┆     ┆ 49_ ┆     ┆     ┆ kat ┆ 49_ ┆     ┆ 688 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ gbf ┆ GBF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_v ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆ 665 ┆ T   ┆     ┆     ┆     ┆     ┆ 865 ┆     ┆     ┆ GBF ┆     ┆     ┆ T   ┆ GBF ┆     ┆ 665 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 202 ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 8:  ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆ cel ┆ 202 ┆     ┆ 8:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1-a ┆ 1-A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆ 65_ ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-A ┆     ┆     ┆ ls  ┆ 1-A ┆     ┆ 65_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ chi ┆ chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ qAl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ 65_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ chi ┆     ┆     ┆     ┆ chi ┆     ┆ 65_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ lle ┆ lle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ign ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆ GBF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lle ┆     ┆     ┆     ┆ lle ┆     ┆ GBF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_a ┆ s_A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_A ┆     ┆     ┆     ┆ s_A ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -ct ┆ -Ct ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bea ┆     ┆     ┆     ┆     ┆     ┆ 1-A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Ct ┆     ┆     ┆     ┆ -Ct ┆     ┆ 1-A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rl- ┆ rl- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆ chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rl- ┆     ┆     ┆     ┆ rl- ┆     ┆ chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 49  ┆ 49  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ByC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49  ┆     ┆     ┆     ┆ 49  ┆     ┆ lle ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 15. GSE164834 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-03
- [Evidence for mitochondrial Lonp1 expression in the nucleus](https://doi.org/10.1038/s41598-022-14860-0)
- Lonp1を標的としたRNAiなどのデータを含む37℃と42℃のデータを含む
- 全てのデータを解析に使用する

In [43]:
GSE164834_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE164834/GSE164834_PEP/GSE164834_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded mRNA Library Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina) Methods に記載されている
    pl.lit("https://doi.org/10.1038/s41598-022-14860-0").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE164834_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE164834_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE164834_iseq_filtered = GSE164834_iseq[[s.name for s in GSE164834_iseq if not (s.null_count() == GSE164834_iseq.height)]]

GSE164834_combined = GSE164834_PEP.join(
    GSE164834_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE164834_combined = GSE164834_combined[[s.name for s in GSE164834_combined if not (s.null_count() == GSE164834_combined.height)]]

GSE164834_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE164834_modified_metadata.tsv",
    separator='\t'
)

# display(GSE164834_combined)

In [44]:
defined_pairs_gse164834 = [
    ("SRR13436390", "SRR13436384"), # HS_siCtrl_rep1 vs Ctrl_siCtrl_rep1
    ("SRR13436391", "SRR13436385"), # HS_siCtrl_rep2 vs Ctrl_siCtrl_rep2
    ("SRR13436392", "SRR13436386"), # HS_siCtrl_rep3 vs Ctrl_siCtrl_rep3
    ("SRR13436393", "SRR13436387"), # HS_siLONP1_rep1 vs Ctrl_siLONP1_rep1
    ("SRR13436394", "SRR13436388"), # HS_siLONP1_rep2 vs Ctrl_siLONP1_rep2
    ("SRR13436395", "SRR13436389"), # HS_siLONP1_rep3 vs Ctrl_siLONP1_rep3
    # ("SRR13436399", "SRR13436396"), # HS_REC_siLONP1_rep1 vs HS_REC_siCtrl_rep1
    # ("SRR13436400", "SRR13436397"), # HS_REC_siLONP1_rep2 vs HS_REC_siCtrl_rep2
    # ("SRR13436401", "SRR13436398")  # HS_REC_siLONP1_rep3 vs HS_REC_siCtrl_rep3
]

paired_metadata_df_gse164834 = create_paired_metadata(
    combined_df=GSE164834_combined,
    defined_sample_pairs=defined_pairs_gse164834,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse164834 is not None:
    paired_metadata_df_gse164834.write_csv(
        "../../Data/metadata/metadata_paired/GSE164834_paired_metadata.tsv",
        separator='\t'
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse164834)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 79)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tre ┆ con ┆ cel ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ atm ┆ dit ┆ l_l ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ent ┆ ion ┆ ine ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HS_ ┆ GSM ┆ Pub ┆ Jan ┆ Jun ┆ SRA ┆ 1   ┆ Col ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Mat ┆ Uni ┆ Via ┆ Pad ┆ 351 ┆ Ita ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Scr ┆ Kep ┆ SW6 ┆ hg3 ┆ SAM ┆ Tru ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Mit ┆ SRA ┆ cDN ┆ 202 ┆ 345 ┆ 249 ┆ ILL ┆ Gen ┆ HS_ ┆ SRP ┆ 552 ┆ Mit ┆ HS_ ┆ Ill ┆ Ill ┆ 110 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ SW6 ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 134 ┆ 134 ┆ sic ┆ A   ┆ o   ┆ RED ┆     ┆ 134 ┆ 984 ┆ siC ┆ 502 ┆ lic ┆ 14  ┆ 28  ┆     ┆     ┆ on  ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ tia ┆ ver ┆ Ugo ┆ ova ┆ 31  ┆ ly  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 502 ┆ E   ┆ 164 ┆     ┆ 984 ┆ amb ┆ t   ┆ 20  ┆ 8   ┆ N17 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 134 ┆ umi ┆ och ┆ 118 ┆ A   ┆ 2-0 ┆ 570 ┆ 625 ┆ UMI ┆ eri ┆ siC ┆ 301 ┆ 728 ┆ och ┆ siC ┆ umi ┆ umi ┆ 386 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 502 ┆ 502 ┆ was ┆ 502 ┆     ┆ 20  ┆ 2-0 ┆ NA6 ┆ 803 ┆ 2-0 ┆ 164 │
│ 363 ┆ 363 ┆ trl ┆     ┆ sap ┆     ┆     ┆ 363 ┆ 990 ┆ trl ┆ 046 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ can ┆ sap ┆     ┆ RNA ┆ 76  ┆ ,,F ┆ sit ┆ Bas ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 046 ┆     ┆ 834 ┆     ┆ 990 ┆ led ┆ at  ┆     ┆     ┆ 315 ┆ Str ┆ //d ┆     ┆ .   ┆     ┆ 363 ┆ na  ┆ ond ┆ 384 ┆     ┆ 6-3 ┆ 947 ┆ 296 ┆ NA  ┆ c   ┆ trl ┆ 760 ┆ 65  ┆ ond ┆ trl ┆ na  ┆ na  ┆ 851 ┆ q   ┆ RIP ┆     ┆     ┆ 046 ┆ 046 ┆ ext ┆ 046 ┆     ┆     ┆ 6-3 ┆ 921 ┆ 141 ┆ 6-3 ┆ 834 │
│ 90  ┆ 84  ┆ _re ┆     ┆ ien ┆     ┆     ┆ 90  ┆ 1   ┆ _re ┆ 9   ┆ Jun ┆ 1   ┆ 2   ┆     ┆     ┆ cer ┆ ien ┆     ┆     ┆     ┆ orc ┆ y   ┆ si, ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 9   ┆     ┆     ┆     ┆ 1   ┆ siR ┆ 42° ┆     ┆     ┆ 583 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 90  ┆ Nov ┆ ria ┆ 3   ┆     ┆ 0   ┆ 5   ┆ 6;2 ┆     ┆     ┆ _re ┆     ┆ vs  ┆ ria ┆ _re ┆ Nov ┆ Nov ┆ 30  ┆     ┆ TOM ┆     ┆     ┆ 9   ┆ 9_r ┆ rac ┆ 9   ┆     ┆     ┆ 0   ┆ 81  ┆ 7   ┆ 0   ┆     │
│     ┆     ┆ p1  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ p1  ┆ vs  ┆ 28  ┆     ┆     ┆     ┆     ┆ cel ┆ s   ┆     ┆     ┆     ┆ ato ┆ of  ┆ 58/ ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ NA  ┆ C   ┆     ┆     ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆ l   ┆     ┆     ┆     ┆ vs  ┆ 641 ┆     ┆     ┆ p1  ┆     ┆ 503 ┆ l   ┆ p1  ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ted ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ vs  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ Pad ┆ B   ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ for ┆     ┆     ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆ pro ┆     ┆     ┆     ┆ 316 ┆ 010 ┆     ┆     ┆ vs  ┆     ┆ 167 ┆ pro ┆ vs  ┆ q   ┆ q   ┆ 100 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ by  ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ ctr ┆     ┆     ┆     ┆     ┆ 134 ┆ 984 ┆ Ctr ┆ 502 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ova ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 502 ┆     ┆     ┆     ┆ 984 ┆     ┆ one ┆     ┆     ┆ N17 ┆ A   ┆ .10 ┆     ┆     ┆     ┆ 134 ┆ 600 ┆ tea ┆     ┆     ┆     ┆ 630 ┆ 718 ┆     ┆     ┆ Ctr ┆     ┆ 26  ┆ tea ┆ Ctr ┆ 600 ┆ 600 ┆ 758 ┆     ┆     ┆     ┆     ┆ 502 ┆ GSM ┆ usi ┆ 502 ┆     ┆     ┆     ┆     ┆ 803 ┆     ┆     │
│     ┆     ┆ l_s ┆     ┆     ┆     ┆     ┆ 363 ┆ 989 ┆ l_s ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 046 ┆     ┆     ┆     ┆ 989 ┆     ┆ hou ┆     ┆     ┆ 315 ┆ Lib ┆ 38/ ┆     ┆     ┆     ┆ 363 ┆ 0   ┆ se  ┆     ┆     ┆     ┆ 340 ┆ vs  ┆     ┆     ┆ l_s ┆     ┆     ┆ se  ┆ l_s ┆ 0   ┆ 0   ┆ 323 ┆     ┆     ┆     ┆     ┆ 046 ┆ 502 ┆ ng  ┆ 046 ┆     ┆     ┆     ┆     ┆ 141 ┆     ┆     │
│     ┆     ┆ ict ┆     ┆     ┆     ┆     ┆ 84  ┆ 5   ┆ iCt ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 5   ┆     ┆ r   ┆     ┆     ┆ 586 ┆ rar ┆ s41 ┆     ┆     ┆     ┆ 84  ┆ seq ┆ Lon ┆     ┆     ┆     ┆ 8   ┆ 228 ┆     ┆     ┆ iCt ┆     ┆     ┆ Lon ┆ iCt ┆     ┆ seq ┆ 50  ┆     ┆     ┆     ┆     ┆ 3   ┆ 046 ┆ RNe ┆ 3   ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     │
│     ┆     ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ y   ┆ 598 ┆     ┆     ┆     ┆     ┆ uen ┆ p1  ┆     ┆     ┆     ┆     ┆ 292 ┆     ┆     ┆ rl_ ┆     ┆     ┆ p1  ┆ rl_ ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_r ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kep ┆     ┆     ┆     ┆ Pre ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆ loc ┆     ┆     ┆     ┆     ┆ 331 ┆     ┆     ┆ rep ┆     ┆     ┆ loc ┆ rep ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ p   ┆ 2-1 ┆     ┆     ┆     ┆     ┆ g:  ┆ ali ┆     ┆     ┆     ┆     ┆ 1;2 ┆     ┆     ┆ 1   ┆     ┆     ┆ ali ┆ 1   ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iki ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ Kit ┆ 486 ┆     ┆     ┆     ┆     ┆ GSM ┆ zes ┆     ┆     ┆     ┆     ┆ 425 ┆     ┆     ┆     ┆     ┆     ┆ zes ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆     ┆     ┆ 0-0 ┆     ┆     ┆     ┆     ┆ 502 ┆ to  ┆     ┆     ┆     ┆     ┆ 160 ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆ 502 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 046 ┆ the ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9:  ┆ nuc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nuc ┆     ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆ leu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ leu ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ man ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ siC ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ siC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ufa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ trl ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ trl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ctu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆ pon ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pon ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 's  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ins ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tru ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ons ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE168716 (PAIRED) NO DOWNLOAD

- validate date: 2025-05-03
- [Internally controlled RNA sequencing comparisons using nucleoside recoding chemistry](https://doi.org/10.1093/nar/gkac693)
- ヒトのデータとDrosophilaのデータが含まれており、このうち、熱ストレス処理をしているデータはDrosophilaだったので、このデータは今回は使用しない

In [45]:
# GSE168716_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE168716/GSE168716_PEP/GSE168716_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# display(GSE168716_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 16. GSE182960 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [Cohesin regulates alternative splicing](https://doi.org/10.1126/sciadv.ade3876)
- オーキシン処理によりRAD21の分解が行われ、コヒーシンの機能が失われるHCT116RmAC cellsが用いられている研究
- `Heat shock treatment` セクションに詳細が書いてある
- `treatment`を見ると、熱ショックを加えているものとそうでないサンプルがわかりやすく明記されている
- DMSO処理、タンパク質分解誘導キメラタンパク質であるPROTAC MZ1処理、MZ1+インドール酢酸(IAA)処理、1× phosphate-buffered saline (PBS)処理、IAA処理のサンプルはフィルタリングする
- 熱ショック + MZ1などの処理も含めて解析に使用する

In [46]:
ID = "GSE182960"

GSE182960_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    ~((pl.col("treatment") == "DMSO") | (pl.col("treatment") == "MZ1") | (pl.col("treatment") == "MZ1+IAA") | (pl.col("treatment") == "PBS") | (pl.col("treatment") == "IAA"))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded mRNA Library").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1126/sciadv.ade3876").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE182960_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE182960_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE182960_iseq_filtered = GSE182960_iseq[[s.name for s in GSE182960_iseq if not (s.null_count() == GSE182960_iseq.height)]]

GSE182960_combined = GSE182960_PEP.join(
    GSE182960_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE182960_combined = GSE182960_combined[[s.name for s in GSE182960_combined if not (s.null_count() == GSE182960_combined.height)]]

GSE182960_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE182960_modified_metadata.tsv",
    separator='\t'
)

# display(GSE182960_combined)

In [47]:
defined_pairs_gse182960 = [
    ("SRR15658378", "SRR15658366"), # 13_DMSOHSR1 vs 1_DMSONHSR1
    ("SRR15658379", "SRR15658367"), # 14_DMSOHSR2 vs 2_DMSONHSR2
    ("SRR15658380", "SRR15658368"), # 15_DMSOHSR3 vs 3_DMSONHSR3
    ("SRR15658381", "SRR15658369"), # 16_MZ1HSR1 vs 4_MZ1NHSR1
    ("SRR15658382", "SRR15658370"), # 17_MZ1HSR2 vs 5_MZ1NHSR2
    ("SRR15658383", "SRR15658371"), # 18_MZ1HSR3 vs 6_MZ1NHSR3
    ("SRR15658384", "SRR15658372"), # 19_IAAHSR1 vs 7_IAANHSR1
    ("SRR15658385", "SRR15658373"), # 20_IAAHSR2 vs 8_IAANHSR2
    ("SRR15658386", "SRR15658374"), # 21_IAAHSR3 vs 9_IAANHSR3
    ("SRR15658387", "SRR15658375"), # 22_MZ1_IAAHSR1 vs 10_MZ1_IAANHSR1
    ("SRR15658388", "SRR15658376"), # 23_MZ1_IAAHSR2 vs 11_MZ1_IAANHSR2
    ("SRR15658389", "SRR15658377")  # 24_MZ1_IAAHSR3 vs 12_MZ1_IAANHSR3
]

paired_metadata_df_gse182960 = create_paired_metadata(
    combined_df=GSE182960_combined, 
    defined_sample_pairs=defined_pairs_gse182960,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse182960 is not None:
    paired_metadata_df_gse182960.write_csv(
        "../../Data/metadata/metadata_paired/GSE182960_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse182960)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ 13_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ 13_ ┆ GSM ┆ Pub ┆ Aug ┆ Aug ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ tot ┆ HCT ┆ GPL ┆ Din ┆ din ┆ 301 ┆ Div ┆ Nat ┆ Bui ┆ Bet ┆ MD  ┆ 208 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HCT ┆ hum ┆ DMS ┆ hg1 ┆ raw ┆ SAM ┆ Tru ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Coh ┆ SRA ┆ cDN ┆ 202 ┆ 389 ┆ 277 ┆ ILL ┆ Gen ┆ 13_ ┆ SRP ┆ 420 ┆ Coh ┆ 13_ ┆ Ill ┆ Ill ┆ hum ┆ 126 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ HCT ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 156 ┆ 156 ┆ dms ┆ A   ┆ o   ┆ RED ┆     ┆ 156 ┆ 119 ┆ DMS ┆ 554 ┆ lic ┆ 27  ┆ 31  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ al  ┆ 116 ┆ 246 ┆ ah, ┆ ah. ┆ -49 ┆ isi ┆ ion ┆ ldi ┆ hes ┆     ┆ 92  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 554 ┆ :// ┆ 182 ┆     ┆ 119 ┆ 116 ┆ an  ┆ O   ┆ 9   ┆ cou ┆ N21 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 156 ┆ umi ┆ esi ┆ 128 ┆ A   ┆ 2-1 ┆ 698 ┆ 154 ┆ UMI ┆ eri ┆ DMS ┆ 334 ┆ 494 ┆ esi ┆ DMS ┆ umi ┆ umi ┆ an  ┆ 989 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 554 ┆ 554 ┆ was ┆ 554 ┆     ┆ 116 ┆ 2-1 ┆ NA7 ┆ 996 ┆ 2-1 ┆ 182 │
│ 583 ┆ 583 ┆ ohs ┆     ┆ sap ┆     ┆     ┆ 583 ┆ 552 ┆ OHS ┆ 375 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ RmA ┆ sap ┆     ┆ RNA ┆ RmA ┆ 76  ┆ S., ┆ sin ┆ 6-9 ┆ on  ┆ al  ┆ ng  ┆ da  ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 375 ┆ ftp ┆ 960 ┆     ┆ 552 ┆ RmA ┆ col ┆ und ┆     ┆ nts ┆ 027 ┆ Str ┆ //d ┆     ┆ .   ┆     ┆ 583 ┆ na  ┆ n   ┆ 510 ┆     ┆ 1-1 ┆ 937 ┆ 807 ┆ NA  ┆ c   ┆ OHS ┆ 521 ┆ 82  ┆ n   ┆ OHS ┆ na  ┆ na  ┆ col ┆ 435 ┆ q   ┆ RIP ┆     ┆     ┆ 375 ┆ 375 ┆ iso ┆ 375 ┆     ┆ RmA ┆ 1-1 ┆ 584 ┆ 502 ┆ 1-1 ┆ 960 │
│ 78  ┆ 66  ┆ r1  ┆     ┆ ien ┆     ┆     ┆ 78  ┆ 99  ┆ R1  ┆ 4   ┆ Aug ┆ 1   ┆ 2   ┆     ┆     ┆ C_D ┆ ien ┆     ┆     ┆ C   ┆     ┆ Sin ┆ ger ┆ 097 ┆ of  ┆ Can ┆ 10, ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 4   ┆ .nc ┆     ┆     ┆ 99  ┆ C   ┆ ore ┆ er  ┆     ┆ of  ┆ 102 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 78  ┆ Nov ┆ reg ┆ 4   ┆     ┆ 9   ┆ 5   ┆ 0;2 ┆     ┆     ┆ R1  ┆     ┆ vs  ┆ reg ┆ R1  ┆ Nov ┆ Nov ┆ ore ┆ 64  ┆     ┆ TOM ┆     ┆     ┆ 4   ┆ 4_r ┆ lat ┆ 4   ┆     ┆ C   ┆ 2   ┆ 23  ┆ 7   ┆ 2   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ vs  ┆ 31  ┆     ┆     ┆     ┆     ┆ MSO ┆ s   ┆     ┆     ┆ cel ┆     ┆ ger ┆ @ni ┆     ┆ Can ┆ cer ┆ Roo ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ cta ┆ hea ┆     ┆ seq ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆ ula ┆     ┆     ┆     ┆ vs  ┆ 983 ┆     ┆     ┆ vs  ┆     ┆ 375 ┆ ula ┆ vs  ┆ aSe ┆ aSe ┆ cta ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ed  ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ 1_d ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ 1_D ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ h.g ┆     ┆ cer ┆ Ins ┆ m   ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ l   ┆ t   ┆     ┆ uen ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆ tes ┆     ┆     ┆     ┆ 348 ┆ 285 ┆     ┆     ┆ 1_D ┆     ┆ 534 ┆ tes ┆ 1_D ┆ q   ┆ q   ┆ l   ┆ 113 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ fro ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ mso ┆     ┆     ┆     ┆     ┆ 156 ┆ 119 ┆ MSO ┆ 554 ┆ 2   ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆ tre ┆     ┆     ┆ ov  ┆     ┆ Bio ┆ tit ┆ 4B- ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 554 ┆ .ni ┆     ┆     ┆ 119 ┆     ┆ car ┆ sho ┆     ┆ cin ┆ N21 ┆ A   ┆ .11 ┆     ┆     ┆     ┆ 156 ┆ 600 ┆ alt ┆     ┆     ┆     ┆ 390 ┆ 269 ┆     ┆     ┆ MSO ┆     ┆ 13  ┆ alt ┆ MSO ┆ 600 ┆ 600 ┆ car ┆ 411 ┆     ┆     ┆     ┆     ┆ 554 ┆ GSM ┆ m   ┆ 554 ┆     ┆     ┆     ┆     ┆ 996 ┆     ┆     │
│     ┆     ┆ nhs ┆     ┆     ┆     ┆     ┆ 583 ┆ 552 ┆ NHS ┆ 374 ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆ log ┆ ute ┆ 17  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 374 ┆ h.g ┆     ┆     ┆ 552 ┆     ┆ cin ┆ ck  ┆     ┆ g   ┆ 027 ┆ Lib ┆ 26/ ┆     ┆     ┆     ┆ 583 ┆ 0   ┆ ern ┆     ┆     ┆     ┆ 504 ┆ vs  ┆     ┆     ┆ NHS ┆     ┆     ┆ ern ┆ NHS ┆ 0   ┆ 0   ┆ cin ┆ 307 ┆     ┆     ┆     ┆     ┆ 374 ┆ 554 ┆ WT, ┆ 374 ┆     ┆     ┆     ┆     ┆ 501 ┆     ┆     │
│     ┆     ┆ r1  ┆     ┆     ┆     ┆     ┆ 66  ┆ 87  ┆ R1  ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ ov/ ┆     ┆     ┆ 87  ┆     ┆ oma ┆ con ┆     ┆ rea ┆ 096 ┆ rar ┆ sci ┆     ┆     ┆     ┆ 66  ┆ seq ┆ ati ┆     ┆     ┆     ┆ 4   ┆ 248 ┆     ┆     ┆ R1  ┆     ┆     ┆ ati ┆ R1  ┆     ┆ seq ┆ oma ┆ 26  ┆     ┆     ┆     ┆     ┆ 2   ┆ 374 ┆ RAD ┆ 2   ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ cel ┆ dit ┆     ┆ ds  ┆     ┆ y   ┆ adv ┆     ┆     ┆     ┆     ┆ uen ┆ ve  ┆     ┆     ┆     ┆     ┆ 356 ┆     ┆     ┆     ┆     ┆     ┆ ve  ┆     ┆     ┆ uen ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ l   ┆ ion ┆     ┆ for ┆     ┆     ┆ .ad ┆     ┆     ┆     ┆     ┆ cin ┆ spl ┆     ┆     ┆     ┆     ┆ 887 ┆     ┆     ┆     ┆     ┆     ┆ spl ┆     ┆     ┆ cin ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ dep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ lin ┆ s   ┆     ┆ eac ┆     ┆     ┆ e38 ┆     ┆     ┆     ┆     ┆ g:  ┆ ici ┆     ┆     ┆     ┆     ┆ 4;2 ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆     ┆ g:  ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ let ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ e   ┆ vs  ┆     ┆ h   ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆ GSM ┆ ng  ┆     ┆     ┆     ┆     ┆ 667 ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆ GSM ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 554 ┆ alo ┆     ┆     ┆     ┆     ┆ 071 ┆     ┆     ┆     ┆     ┆     ┆ alo ┆     ┆     ┆ 554 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 554 ┆     ┆     ┆     ┆     ┆     ┆ O   ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 375 ┆ ne  ┆     ┆     ┆     ┆     ┆ 170 ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆ or  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ or  ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 13_ ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆ 13_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ let ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆ non ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RmA ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 543 ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OHS ┆ BRD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆ OHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C_D ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 754 ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1  ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆ R1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BRD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MSO ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 17. GSE198441 (PAIRED) (MSR-seq)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [A multiplex platform for small RNA sequencing elucidates multifaceted tRNA stress response and translational regulation](https://doi.org/10.1038/s41467-022-30261-3)
- small RNA-seqの手法に関する論文
- シュードウリジン付加のためのCMC(well-established N-cyclohexyl-N′-β-(4-methylmorpholinium) ethylcarbodiimide (CMC) reaction) 処理が行われているサンプル、過酸化水素、ヒ素処理などのサンプルを含む
- `_nostress_` と `_heatstress_`を含むデータを今回は収集
- `HEK293T_totalRNA_nostress_shortRT_minusDM_` と `HEK293T_totalRNA_nostress_shortRT_plusDM_` は対応する熱ストレスのデータがないことが判明したため、今回はフィルタリングする
- 温度条件は42℃,1時間 (論文より)
- データ解析手法は、通常の RNA-seq と ほぼ変わらないと判断したため、収集する
- ライブラリー調製の部分

In [48]:
ID = "GSE198441"

GSE198441_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_title").str.contains(r'_nostress_') | 
     pl.col("sample_title").str.contains(r'_heatstress_')) & # filter out samples without stress
     
    ~((pl.col("sample_title").str.contains(r'HEK293T_totalRNA_nostress_shortRT_minusDM_')) | 
      (pl.col("sample_title").str.contains(r'HEK293T_totalRNA_nostress_shortRT_plusDM_'))) # filter out samples without stress
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("MSR-seq (custom mRNA library preparation)").alias("rna_library"), # add rna_library column from GEO webpage
    pl.lit("https://doi.org/10.1038/s41467-022-30261-3").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("HEK293T").alias("cell_line")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE198441_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE198441_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE198441_iseq_filtered = GSE198441_iseq[[s.name for s in GSE198441_iseq if not (s.null_count() == GSE198441_iseq.height)]]

GSE198441_combined = GSE198441_PEP.join(
    GSE198441_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE198441_combined = GSE198441_combined[[s.name for s in GSE198441_combined if not (s.null_count() == GSE198441_combined.height)]]

GSE198441_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE198441_modified_metadata.tsv",
    separator='\t'
)

# display(GSE198441_combined)

In [49]:
defined_pairs_gse198441 = [
    ("SRR18302276", "SRR18302279"), # HEK293T_totalRNA_heatstress_longRT_minusDM_rep1 vs HEK293T_totalRNA_nostress_longRT_minusDM_rep1
    ("SRR18302275", "SRR18302278"), # HEK293T_totalRNA_heatstress_longRT_minusDM_rep2 vs HEK293T_totalRNA_nostress_longRT_minusDM_rep2
    ("SRR18302274", "SRR18302277"), # HEK293T_totalRNA_heatstress_longRT_minusDM_rep3 vs HEK293T_totalRNA_nostress_longRT_minusDM_rep3
    ("SRR18302264", "SRR18302267"), # HEK293T_polysomeRNA_heatstress_longRT_minusDM_rep1 vs HEK293T_polysomeRNA_nostress_longRT_minusDM_rep1
    ("SRR18302263", "SRR18302266"), # HEK293T_polysomeRNA_heatstress_longRT_minusDM_rep2 vs HEK293T_polysomeRNA_nostress_longRT_minusDM_rep2
    ("SRR18302262", "SRR18302265"), # HEK293T_polysomeRNA_heatstress_longRT_minusDM_rep3 vs HEK293T_polysomeRNA_nostress_longRT_minusDM_rep3
    ("SRR18302254", "SRR18302255"), # HEK293T_polyARNA_heatstress_longRT_minusDM_rep1 vs HEK293T_polyARNA_nostress_longRT_minusDM_rep1
    ("SRR18302252", "SRR18302253"), # HEK293T_polyARNA_heatstress_longRT_minusDM_rep2 vs HEK293T_polyARNA_nostress_longRT_minusDM_rep2
    ("SRR18302251", "SRR18302247"), # HEK293T_polyARNA_heatstress_longRT_minusDM_rep3 vs HEK293T_polyARNA_nostress_longRT_minusDM_rep3
    ("SRR18302240", "SRR18302243"), # HEK293T_polysomepolyARNA_heatstress_longRT_minusDM_rep1 vs HEK293T_polysomepolyARNA_nostress_longRT_minusDM_rep1
    ("SRR18302238", "SRR18302242"), # HEK293T_polysomepolyARNA_heatstress_longRT_minusDM_rep2 vs HEK293T_polysomepolyARNA_nostress_longRT_minusDM_rep2
    ("SRR18302239", "SRR18302241")  # HEK293T_polysomepolyARNA_heatstress_longRT_minusDM_rep3 vs HEK293T_polysomepolyARNA_nostress_longRT_minusDM_rep3
]

paired_metadata_df_gse198441 = create_paired_metadata(
    combined_df=GSE198441_combined,
    defined_sample_pairs=defined_pairs_gse198441,
    sample_id_column_name="accession"
)


if paired_metadata_df_gse198441 is not None:
    paired_metadata_df_gse198441.write_csv(
        "../../Data/metadata/metadata_paired/GSE198441_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse198441)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ str ┆ fra ┆ enz ┆ rt_ ┆ ass ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ lib ┆ fir ┆ str ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ ain ┆ cti ┆ yme ┆ con ┆ emb ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ rar ┆ st_ ┆ ain ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ on  ┆ _ch ┆ dit ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ y_n ┆ cre ┆ _ri ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ emi ┆ ion ┆ --- ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ ame ┆ ate ┆ ght ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ cal ┆ --- ┆ str ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ --- ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ _tr ┆ str ┆     ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ str ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ eat ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ men ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hek ┆ HEK ┆ GSM ┆ Pub ┆ Mar ┆ Mar ┆ SRA ┆ 1   ┆ RNA ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Chr ┆ kat ┆ 734 ┆ Pan ┆ Bio ┆ The ┆ 164 ┆ Chi ┆ Ill ┆ 606 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HEK ┆ Tot ┆ non ┆ Ove ┆ Hg1 ┆ SAM ┆ MSR ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ HEK ┆ SRR ┆ Ill ┆ A   ┆ SRA ┆ cDN ┆ 202 ┆ 245 ┆ 104 ┆ ILL ┆ Gen ┆ HEK ┆ SRP ┆ 258 ┆ A   ┆ HEK ┆ Ill ┆ Ill ┆ 568 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GSM ┆ 202 ┆ HEK ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 183 ┆ 183 ┆ 293 ┆ 293 ┆ 594 ┆ lic ┆ 11  ┆ 27  ┆     ┆     ┆ ext ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ ist ┆ ans ┆ 829 ┆ lab ┆ che ┆ Uni ┆ 9   ┆ cag ┆ ino ┆ 15  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 594 ┆ :// ┆ 198 ┆     ┆ 144 ┆ 293 ┆ al  ┆ e   ┆ rni ┆ 9;  ┆ N26 ┆ -se ┆ ps: ┆ C   ┆ min ┆ C   ┆ 293 ┆ 183 ┆ umi ┆ mul ┆ 138 ┆ A   ┆ 2-0 ┆ 078 ┆ 202 ┆ UMI ┆ eri ┆ 293 ┆ 363 ┆ 457 ┆ mul ┆ 293 ┆ umi ┆ umi ┆ 606 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 594 ┆ 594 ┆ ls  ┆ 594 ┆ 594 ┆ 2-0 ┆ 293 ┆ NA8 ┆ 122 ┆ 2-0 ┆ 198 │
│ 022 ┆ 022 ┆ t_t ┆ T_t ┆ 692 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ rac ┆ sap ┆     ┆ RNA ┆ 76  ┆ oph ┆ ki@ ┆ 791 ┆     ┆ mis ┆ ver ┆ E.  ┆ o   ┆ is  ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 692 ┆ ftp ┆ 441 ┆     ┆ 397 ┆ T   ┆ RNA ┆     ┆ ght ┆ hg3 ┆ 583 ┆ q   ┆ //d ┆     ┆ .   ┆ (in ┆ T   ┆ 022 ┆ na  ┆ tip ┆ 394 ┆     ┆ 4-0 ┆ 530 ┆ 653 ┆ NA  ┆ c   ┆ T_t ┆ 629 ┆ 65  ┆ tip ┆ T_t ┆ na  ┆ na  ┆ 830 ┆ q   ┆ RIP ┆     ┆     ┆ 692 ┆ 692 ┆ wer ┆ 692 ┆ 692 ┆ 4-0 ┆ T   ┆ 153 ┆ 468 ┆ 4-0 ┆ 441 │
│ 76  ┆ 79  ┆ ota ┆ ota ┆ 2   ┆ Mar ┆ 2   ┆ 2   ┆     ┆     ┆ ted ┆ ien ┆     ┆     ┆     ┆ er, ┆ uch ┆ 6   ┆     ┆ try ┆ sit ┆ 50t ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 2   ┆ .nc ┆     ┆     ┆ 22  ┆     ┆     ┆     ┆ RT  ┆ 8   ┆ 138 ┆ (cu ┆ oi. ┆     ┆     ┆ fer ┆     ┆ 76  ┆ Nov ┆ lex ┆ 9   ┆     ┆ 3   ┆ 8   ┆ 6;1 ┆     ┆     ┆ ota ┆     ┆ vs  ┆ lex ┆ ota ┆ Nov ┆ Nov ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_r ┆ e   ┆ 2_r ┆ 2   ┆ 1   ┆     ┆ 10  ┆ 07  ┆ 1   ┆     │
│     ┆     ┆ lrn ┆ lRN ┆ vs  ┆ 13  ┆     ┆     ┆     ┆     ┆ fro ┆ s   ┆     ┆     ┆     ┆ D,K ┆ ica ┆     ┆     ┆     ┆ y   ┆ h   ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ sto ┆ org ┆     ┆     ┆ red ┆     ┆ vs  ┆ aSe ┆ pla ┆     ┆     ┆     ┆ vs  ┆ 040 ┆     ┆     ┆ lRN ┆     ┆ 333 ┆ pla ┆ lRN ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ col ┆ 1   ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ a_h ┆ A_h ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆ ata ┆ go. ┆     ┆     ┆     ┆ of  ┆ St. ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ m   ┆ /10 ┆     ┆     ┆ )   ┆     ┆ SRR ┆ q   ┆ tfo ┆     ┆     ┆     ┆ 318 ┆ 587 ┆     ┆     ┆ A_h ┆     ┆ 896 ┆ tfo ┆ A_h ┆ q   ┆ q   ┆ 734 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ lec ┆ vs  ┆ GSM ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ eat ┆ eat ┆ 594 ┆ 2   ┆     ┆     ┆     ┆     ┆ HEK ┆     ┆     ┆     ┆     ┆ nsk ┆ edu ┆     ┆     ┆     ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 594 ┆ .ni ┆     ┆     ┆ 144 ┆     ┆     ┆     ┆     ┆     ┆ N26 ┆ mRN ┆ .10 ┆     ┆     ┆     ┆     ┆ 183 ┆ 600 ┆ rm  ┆     ┆     ┆     ┆ 300 ┆ 098 ┆     ┆     ┆ eat ┆     ┆ 09  ┆ rm  ┆ eat ┆ 600 ┆ 600 ┆ 571 ┆     ┆     ┆     ┆     ┆ 594 ┆ GSM ┆ ted ┆ GSM ┆ 594 ┆     ┆     ┆     ┆ 122 ┆     ┆     │
│     ┆     ┆ str ┆ str ┆ 691 ┆     ┆     ┆     ┆     ┆     ┆ 293 ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆     ┆ cag ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 691 ┆ h.g ┆     ┆     ┆ 397 ┆     ┆     ┆     ┆     ┆     ┆ 583 ┆ A   ┆ 38/ ┆     ┆     ┆     ┆     ┆ 022 ┆ 0   ┆ for ┆     ┆     ┆     ┆ 302 ┆ vs  ┆     ┆     ┆ str ┆     ┆     ┆ for ┆ str ┆ 0   ┆ 0   ┆ 398 ┆     ┆     ┆     ┆     ┆ 691 ┆ 594 ┆ and ┆ 594 ┆ 691 ┆     ┆     ┆     ┆ 468 ┆     ┆     │
│     ┆     ┆ ess ┆ ess ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ T   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ ov/ ┆     ┆     ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆ 141 ┆ lib ┆ s41 ┆     ┆     ┆     ┆     ┆ 79  ┆ seq ┆ sma ┆     ┆     ┆     ┆ 3   ┆ 137 ┆     ┆     ┆ ess ┆     ┆     ┆ sma ┆ ess ┆     ┆ seq ┆ 0   ┆     ┆     ┆     ┆     ┆ 9   ┆ 691 ┆ tot ┆ 691 ┆ 9   ┆     ┆     ┆     ┆ 04  ┆     ┆     │
│     ┆     ┆ _lo ┆ _lo ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ 467 ┆     ┆     ┆     ┆     ┆     ┆ uen ┆ ll  ┆     ┆     ┆     ┆     ┆ 126 ┆     ┆     ┆ _lo ┆     ┆     ┆ ll  ┆ _lo ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9_r ┆ al  ┆ 9_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ngr ┆ ngR ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆ cin ┆ RNA ┆     ┆     ┆     ┆     ┆ 157 ┆     ┆     ┆ ngR ┆     ┆     ┆ RNA ┆ ngR ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ RNA ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ t_m ┆ T_m ┆     ┆     ┆     ┆     ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆ 2-3 ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆ seq ┆     ┆     ┆     ┆     ┆ 9;1 ┆     ┆     ┆ T_m ┆     ┆     ┆ seq ┆ T_m ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ inu ┆ inu ┆     ┆     ┆     ┆     ┆     ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆ 026 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ uen ┆     ┆     ┆     ┆     ┆ 358 ┆     ┆     ┆ inu ┆     ┆     ┆ uen ┆ inu ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sdm ┆ sDM ┆     ┆     ┆     ┆     ┆     ┆     ┆ e,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 1-3 ┆     ┆     ┆     ┆     ┆     ┆ 594 ┆ cin ┆     ┆     ┆     ┆     ┆ 915 ┆     ┆     ┆ sDM ┆     ┆     ┆ cin ┆ sDM ┆     ┆ 594 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆ aft ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 594 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆     ┆     ┆     ┆     ┆ 692 ┆ g   ┆     ┆     ┆     ┆     ┆ 183 ┆     ┆     ┆ _re ┆     ┆     ┆ g   ┆ _re ┆     ┆ 692 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2:  ┆ elu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆ elu ┆ p1  ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆ cid ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ cid ┆ vs  ┆     ┆ HEK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hek ┆ HEK ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 293 ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆     ┆     ┆ ate ┆ HEK ┆     ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 293 ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 946 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_t ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 293 ┆     ┆     ┆ s   ┆ 293 ┆     ┆ T_t ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ t_t ┆ T_t ┆     ┆     ┆     ┆     ┆     ┆     ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 922 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ota ┆ mul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T_t ┆     ┆     ┆ mul ┆ T_t ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Th ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ota ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lRN ┆ tif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ota ┆     ┆     ┆ tif ┆ ota ┆     ┆ lRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ lrn ┆ lRN ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_h ┆ ace ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lRN ┆     ┆     ┆ ace ┆ lRN ┆     ┆ A_h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oFi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ a_n ┆ A_n ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eat ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_n ┆     ┆     ┆ ted ┆ A_n ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ she ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ost ┆ ost ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M59 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ tRN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ost ┆     ┆     ┆ tRN ┆ ost ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ res ┆ res ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 469 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ess ┆ A   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆     ┆     ┆ A   ┆ res ┆     ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 155 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_l ┆ s_l ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 22_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _lo ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_l ┆     ┆     ┆ str ┆ s_l ┆     ┆ _lo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 960 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ong ┆ ong ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bas ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ngR ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ong ┆     ┆     ┆ ess ┆ ong ┆     ┆ ngR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 18. GSE164846 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [Local translation in nuclear condensate amyloid bodies](https://doi.org/10.1073/pnas.2014457118)
- おそらく上記の論文由来のデータ(GEOのページには登録されていなかった)
- `Basal: 37°C, 21% O2, pH 7.4. Heat shock: 43°C, 21% O2, pH 7.4`
- 全てのデータを収集する

In [50]:
ID = "GSE164846"

GSE164846_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA Stranded mRNA-Seq Kit").alias("rna_library"), # add rna_library column from GEO webpage (KAPA Biosystems)
    pl.lit("https://doi.org/10.1073/pnas.2014457118").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE164846_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE164846_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE164846_iseq_filtered = GSE164846_iseq[[s.name for s in GSE164846_iseq if not (s.null_count() == GSE164846_iseq.height)]]

GSE164846_combined = GSE164846_PEP.join(
    GSE164846_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE164846_combined = GSE164846_combined[[s.name for s in GSE164846_combined if not (s.null_count() == GSE164846_combined.height)]]

GSE164846_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE164846_modified_metadata.tsv",
    separator='\t'
)

# display(GSE164846_combined)

In [51]:
defined_pairs_gse164846 = [
    ("SRR13436541", "SRR13436538"), # Purified Amyloid-bodies following 60min heat shock 1 vs Total RNA from MCF7 cells, purified nucleoli from cells maintained at basal conditions 1
    ("SRR13436542", "SRR13436539"), # Purified Amyloid-bodies following 60min heat shock 2 vs Total RNA from MCF7 cells, purified nucleoli from cells maintained at basal conditions 2
    ("SRR13436543", "SRR13436540")  # Purified Amyloid-bodies following 60min heat shock 3 vs Total RNA from MCF7 cells, purified nucleoli from cells maintained at basal conditions 3
]

paired_metadata_df_gse164846 = create_paired_metadata(
    combined_df=GSE164846_combined,
    defined_sample_pairs=defined_pairs_gse164846,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse164846 is not None:
    paired_metadata_df_gse164846.write_csv(
        "../../Data/metadata/metadata_paired/GSE164846_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse164846)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pur ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ Pur ┆ GSM ┆ Pub ┆ Jan ┆ Jan ┆ SRA ┆ 1   ┆ MCF ┆ Hom ┆ 960 ┆ tot ┆ ade ┆ GPL ┆ Ste ┆ ste ┆ Gau ┆ Bio ┆ Uni ┆ 101 ┆ Mia ┆ Flo ┆ 331 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ GRC ┆ SAM ┆ KAP ┆ htt ┆ 43  ┆ 60  ┆ 37  ┆ SRR ┆ Nex ┆ Loc ┆ SRA ┆ cDN ┆ 202 ┆ 216 ┆ 139 ┆ ILL ┆ Gen ┆ Pur ┆ SRP ┆ 178 ┆ Loc ┆ Pur ┆ Nex ┆ Nex ┆ 477 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Pla ┆ GSM ┆ GEO ┆ MCF ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 134 ┆ 134 ┆ ifi ┆ A   ┆ o   ┆ RED ┆     ┆ 134 ┆ 985 ┆ ifi ┆ 502 ┆ lic ┆ 14  ┆ 17  ┆     ┆     ┆ 7   ┆ o   ┆ 6   ┆ al  ┆ noc ┆ 185 ┆ phe ┆ phe ┆ tie ┆ che ┆ ver ┆ 1   ┆ mi  ┆ rid ┆ 36  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 502 ┆ E   ┆ 164 ┆     ┆ 985 ┆ 7   ┆ h38 ┆ N17 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ 134 ┆ tSe ┆ al  ┆ 118 ┆ A   ┆ 1-0 ┆ 174 ┆ 079 ┆ UMI ┆ eri ┆ ifi ┆ 301 ┆ 589 ┆ al  ┆ ifi ┆ tSe ┆ tSe ┆ 761 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 502 ┆ 502 ┆ tes ┆ 502 ┆     ┆ 7   ┆ 1-0 ┆ NA6 ┆ 803 ┆ 1-0 ┆ 164 │
│ 365 ┆ 365 ┆ ed_ ┆     ┆ sap ┆     ┆     ┆ 365 ┆ 005 ┆ ed  ┆ 092 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ mam ┆ sap ┆     ┆ RNA ┆ arc ┆ 73  ┆ n,, ┆ nle ┆ r   ┆ mis ┆ sit ┆ NW  ┆     ┆ a   ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 092 ┆     ┆ 846 ┆     ┆ 005 ┆     ┆ (ge ┆ 315 ┆ Str ┆ //d ┆     ┆ .   ┆     ┆ 365 ┆ q   ┆ Tra ┆ 388 ┆     ┆ 1-1 ┆ 631 ┆ 486 ┆ NA  ┆ c   ┆ ed  ┆ 773 ┆ 77  ┆ Tra ┆ ed  ┆ q   ┆ q   ┆ 800 ┆ q   ┆ RIP ┆     ┆     ┆ 092 ┆ 092 ┆ wer ┆ 092 ┆     ┆     ┆ 1-1 ┆ 921 ┆ 156 ┆ 1-1 ┆ 846 │
│ 41  ┆ 38  ┆ amy ┆     ┆ ien ┆     ┆     ┆ 41  ┆ 0   ┆ Amy ┆ 1   ┆ Jan ┆ 1   ┆ 1   ┆     ┆     ┆ mar ┆ ien ┆     ┆     ┆ ino ┆     ┆ Lee ┆ e@m ┆ Bld ┆ try ┆ y   ┆ 15  ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 1   ┆     ┆     ┆     ┆ 0   ┆     ┆ nco ┆ 995 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 41  ┆ 500 ┆ nsl ┆ 7   ┆     ┆ 9   ┆ 9   ┆ 7;1 ┆     ┆     ┆ Amy ┆     ┆ vs  ┆ nsl ┆ Amy ┆ 500 ┆ 500 ┆ 7   ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ e   ┆ 1   ┆     ┆     ┆ 9   ┆ 99  ┆ 6   ┆ 9   ┆     │
│     ┆     ┆ loi ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ loi ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆ y   ┆ s   ┆     ┆     ┆ ma  ┆     ┆     ┆ ed. ┆ g,  ┆ &   ┆ of  ┆ st. ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ de  ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ seq ┆ ati ┆     ┆     ┆     ┆ vs  ┆ 413 ┆     ┆     ┆ loi ┆     ┆ 183 ┆ ati ┆ loi ┆     ┆ seq ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ was ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ d-b ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ d-b ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ gla ┆     ┆     ┆     ┆     ┆     ┆     ┆ mia ┆ Rm  ┆ Mol ┆ Mia ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ v27 ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ uen ┆ on  ┆     ┆     ┆     ┆ 220 ┆ 239 ┆     ┆     ┆ d-b ┆     ┆ 471 ┆ on  ┆ d-b ┆     ┆ uen ┆ 495 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ hed ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ odi ┆     ┆     ┆     ┆     ┆ 134 ┆ 985 ┆ odi ┆ 502 ┆ 1   ┆     ┆     ┆     ┆     ┆ nd  ┆     ┆     ┆     ┆     ┆     ┆     ┆ mi. ┆ 228 ┆ ecu ┆ mi  ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 502 ┆     ┆     ┆     ┆ 985 ┆     ┆ )   ┆ N17 ┆ A-S ┆ .10 ┆     ┆     ┆     ┆ 134 ┆ cin ┆ in  ┆     ┆     ┆     ┆ 481 ┆ 310 ┆     ┆     ┆ odi ┆     ┆ 16  ┆ in  ┆ odi ┆     ┆ cin ┆ 102 ┆     ┆     ┆     ┆     ┆ 502 ┆ GSM ┆ wit ┆ 502 ┆     ┆     ┆     ┆     ┆ 803 ┆     ┆     │
│     ┆     ┆ es_ ┆     ┆     ┆     ┆     ┆ 365 ┆ 005 ┆ es  ┆ 091 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆ edu ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 091 ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆ 315 ┆ eq  ┆ 73/ ┆     ┆     ┆     ┆ 365 ┆ g:  ┆ Nuc ┆     ┆     ┆     ┆ 630 ┆ vs  ┆     ┆     ┆ es  ┆     ┆     ┆ Nuc ┆ es  ┆     ┆ g:  ┆ 048 ┆     ┆     ┆     ┆     ┆ 091 ┆ 502 ┆ h   ┆ 091 ┆     ┆     ┆     ┆     ┆ 156 ┆     ┆     │
│     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆ 38  ┆ 3   ┆ fol ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 998 ┆ Kit ┆ pna ┆     ┆     ┆     ┆ 38  ┆ GSM ┆ lea ┆     ┆     ┆     ┆ 7   ┆ 143 ┆     ┆     ┆ fol ┆     ┆     ┆ lea ┆ fol ┆     ┆ GSM ┆ 4   ┆     ┆     ┆     ┆     ┆ 8   ┆ 091 ┆ PBS ┆ 8   ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     │
│     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s.2 ┆     ┆     ┆     ┆     ┆ 502 ┆ r   ┆     ┆     ┆     ┆     ┆ 680 ┆     ┆     ┆ low ┆     ┆     ┆ r   ┆ low ┆     ┆ 502 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8_r ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 014 ┆     ┆     ┆     ┆     ┆ 092 ┆ Con ┆     ┆     ┆     ┆     ┆ 568 ┆     ┆     ┆ ing ┆     ┆     ┆ Con ┆ ing ┆     ┆ 092 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _60 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60m ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 457 ┆     ┆     ┆     ┆     ┆ 1:  ┆ den ┆     ┆     ┆     ┆     ┆ 9;1 ┆     ┆     ┆ 60m ┆     ┆     ┆ den ┆ 60m ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 118 ┆     ┆     ┆     ┆     ┆ Pur ┆ sat ┆     ┆     ┆     ┆     ┆ 464 ┆     ┆     ┆ in  ┆     ┆     ┆ sat ┆ in  ┆     ┆ Pur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _he ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ifi ┆ e   ┆     ┆     ┆     ┆     ┆ 612 ┆     ┆     ┆ hea ┆     ┆     ┆ e   ┆ hea ┆     ┆ ifi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ Amy ┆     ┆     ┆     ┆     ┆ 808 ┆     ┆     ┆ t   ┆     ┆     ┆ Amy ┆ t   ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ har ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Amy ┆ loi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ loi ┆ sho ┆     ┆ Amy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ves ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ck_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ loi ┆ d-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ d-b ┆ ck  ┆     ┆ loi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d-b ┆ odi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ odi ┆ 1   ┆     ┆ d-b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ odi ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ es  ┆ vs  ┆     ┆ odi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tot ┆     ┆     ┆     ┆ Tot ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ al_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆ al  ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆ RNA ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _fr ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆     ┆ fro ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ om_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆ m   ┆     ┆ 60m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mcf ┆     ┆     ┆     ┆     ┆     ┆     ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ MCF ┆     ┆     ┆     ┆ MCF ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (0. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 7   ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5M  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 19. GSE149797 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [Proteasome stress in skeletal muscle mounts a long-range protective response that delays retinal and brain aging](https://doi.org/10.1016/j.cmet.2021.03.005)
- HS + maltose, HSのみの処理が含まれている
- 以前の研究でも使用したデータ
- 今回も全てのデータを使用する
- おそらくこのデータは41.5℃で7時間

In [52]:
ID = "GSE149797"

GSE149797_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq stranded mRNA library preparation kit").alias("rna_library"), # add rna_library column from Article (Illumina)
    pl.lit("https://doi.org/10.1016/j.cmet.2021.03.005").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("41.5 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("420 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("cortical brain organoids").alias("cell_line")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE149797_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE149797_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE149797_iseq_filtered = GSE149797_iseq[[s.name for s in GSE149797_iseq if not (s.null_count() == GSE149797_iseq.height)]]

GSE149797_combined = GSE149797_PEP.join(
    GSE149797_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE149797_combined = GSE149797_combined[[s.name for s in GSE149797_combined if not (s.null_count() == GSE149797_combined.height)]]

GSE149797_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE149797_modified_metadata.tsv",
    separator='\t'
)

# display(GSE149797_combined)

In [53]:
defined_pairs_gse149797 = [
    ("SRR11684069", "SRR11684066"), # HS_control_1 vs control_1
    ("SRR11684070", "SRR11684067"), # HS_control_2 vs control_2
    ("SRR11684071", "SRR11684068"), # HS_control_3 vs control_3
    ("SRR11684072", "SRR11684075"), # HS_maltose_1 vs maltose_1
    ("SRR11684073", "SRR11684076"), # HS_maltose_2 vs maltose_2
    ("SRR11684074", "SRR11684077")  # HS_maltose_3 vs maltose_3
]

paired_metadata_df_gse149797 = create_paired_metadata(
    combined_df=GSE149797_combined,
    defined_sample_pairs=defined_pairs_gse149797,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse149797 is not None:
    paired_metadata_df_gse149797.write_csv(
        "../../Data/metadata/metadata_paired/GSE149797_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse149797)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ gen ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ ome ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ ild ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ --- ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆ str ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ s_c ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HS_ ┆ GSM ┆ Pub ┆ May ┆ Feb ┆ SRA ┆ 1   ┆ con ┆ Hom ┆ 960 ┆ tis ┆ tot ┆ con ┆ GPL ┆ Yon ┆ mic ┆ 901 ┆ St. ┆ 262 ┆ Mem ┆ TN  ┆ 381 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ hg3 ┆ SAM ┆ Tru ┆ htt ┆ 41. ┆ 420 ┆ 37  ┆ cor ┆ SRR ┆ Ill ┆ Pro ┆ SRA ┆ cDN ┆ 202 ┆ 311 ┆ 232 ┆ ILL ┆ Gen ┆ HS_ ┆ SRP ┆ 508 ┆ Pro ┆ HS_ ┆ Ill ┆ Ill ┆ 102 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Tis ┆ GSM ┆ GEO ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ cor │
│ 116 ┆ 116 ┆ con ┆ A   ┆ o   ┆ RED ┆     ┆ 116 ┆ 824 ┆ con ┆ 451 ┆ lic ┆ 04  ┆ 12  ┆     ┆     ┆ tro ┆ o   ┆ 6   ┆ sue ┆ al  ┆ tro ┆ 111 ┆ g-D ┆ hae ┆ 595 ┆ Jud ┆ Dan ┆ phi ┆     ┆ 34  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 451 ┆ E   ┆ 149 ┆     ┆ 824 ┆ 8   ┆ N14 ┆ Seq ┆ ps: ┆ 5 C ┆ min ┆ C   ┆ tic ┆ 116 ┆ umi ┆ tea ┆ 107 ┆ A   ┆ 1-0 ┆ 118 ┆ 210 ┆ UMI ┆ eri ┆ con ┆ 259 ┆ 776 ┆ tea ┆ con ┆ umi ┆ umi ┆ 772 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 451 ┆ 451 ┆ sue ┆ 451 ┆     ┆ 1-0 ┆ NA6 ┆ 659 ┆ 1-0 ┆ 149 ┆ tic │
│ 840 ┆ 840 ┆ tro ┆     ┆ sap ┆     ┆     ┆ 840 ┆ 486 ┆ tro ┆ 282 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ l   ┆ sap ┆     ┆ :   ┆ RNA ┆ l   ┆ 54  ┆ ong ┆ l.w ┆ 422 ┆ e   ┆ ny  ┆ s   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 282 ┆     ┆ 797 ┆     ┆ 486 ┆     ┆ 827 ┆ str ┆ //d ┆     ┆ .   ┆ (in ┆ al  ┆ 840 ┆ na  ┆ som ┆ 214 ┆     ┆ 2-1 ┆ 583 ┆ 340 ┆ NA  ┆ c   ┆ tro ┆ 995 ┆ 37  ┆ som ┆ tro ┆ na  ┆ na  ┆ 826 ┆ q   ┆ RIP ┆     ┆     ┆ 282 ┆ 282 ┆ s   ┆ 282 ┆     ┆ 2-1 ┆ 301 ┆ 250 ┆ 2-1 ┆ 797 ┆ al  │
│ 69  ┆ 66  ┆ l_1 ┆     ┆ ien ┆     ┆     ┆ 69  ┆ 4   ┆ l_1 ┆ 4   ┆ Feb ┆ 0   ┆ 1   ┆     ┆     ┆ wit ┆ ien ┆     ┆ cor ┆     ┆ wit ┆     ┆ ,,W ┆ ang ┆ 4   ┆ Chi ┆ Tho ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 4   ┆     ┆ ,   ┆     ┆ 4   ┆     ┆ 271 ┆ and ┆ oi. ┆     ┆     ┆ fer ┆ bra ┆ 69  ┆ HiS ┆ e   ┆ 6   ┆     ┆ 4   ┆ 5   ┆ 3;2 ┆     ┆     ┆ l_1 ┆     ┆ vs  ┆ e   ┆ l_1 ┆ HiS ┆ HiS ┆ 74  ┆     ┆ TOM ┆     ┆     ┆ 4   ┆ 4_r ┆ wer ┆ 4   ┆     ┆ 4   ┆ 73  ┆ 0   ┆ 4   ┆     ┆ bra │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ vs  ┆ 12  ┆     ┆     ┆     ┆     ┆ h   ┆ s   ┆     ┆ tic ┆     ┆ h   ┆     ┆ ang ┆ @st ┆     ┆ ldr ┆ mas ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆ GSE ┆     ┆ vs  ┆     ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆ red ┆ in  ┆ vs  ┆ eq  ┆ Str ┆     ┆     ┆     ┆ vs  ┆ 408 ┆     ┆     ┆ vs  ┆     ┆ 525 ┆ Str ┆ vs  ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ e   ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ in  │
│     ┆     ┆ con ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ con ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ al  ┆     ┆ hea ┆     ┆     ┆ jud ┆     ┆ en' ┆ Pl, ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆ 149 ┆     ┆ SRX ┆     ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆ )   ┆ org ┆ SRR ┆ 200 ┆ ess ┆     ┆     ┆     ┆ 319 ┆ 757 ┆     ┆     ┆ con ┆     ┆ 203 ┆ ess ┆ con ┆ 200 ┆ 200 ┆ 106 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ hom ┆ GSM ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆ org │
│     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆ 116 ┆ 824 ┆ tro ┆ 451 ┆ 1   ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ bra ┆     ┆ t   ┆     ┆     ┆ e.o ┆     ┆ s   ┆ MS1 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 451 ┆     ┆ 799 ┆     ┆ 824 ┆     ┆ N14 ┆ A   ┆ .10 ┆     ┆     ┆     ┆ ano ┆ 116 ┆ 0   ┆ in  ┆     ┆     ┆     ┆ 320 ┆ 282 ┆     ┆     ┆ tro ┆     ┆ 76  ┆ in  ┆ tro ┆ 0   ┆ 0   ┆ 091 ┆     ┆     ┆     ┆     ┆ 451 ┆ GSM ┆ oge ┆ 451 ┆     ┆     ┆     ┆ 659 ┆     ┆     ┆ ano │
│     ┆     ┆ l_1 ┆     ┆     ┆     ┆     ┆ 840 ┆ 486 ┆ l_1 ┆ 282 ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ in  ┆     ┆ sho ┆     ┆     ┆ rg  ┆     ┆ Res ┆ 135 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆ 486 ┆     ┆ 827 ┆ lib ┆ 16/ ┆     ┆     ┆     ┆ ids ┆ 840 ┆ seq ┆ Ske ┆     ┆     ┆     ┆ 206 ┆ vs  ┆     ┆     ┆ l_1 ┆     ┆     ┆ Ske ┆ l_1 ┆     ┆ seq ┆ 159 ┆     ┆     ┆     ┆     ┆ 282 ┆ 451 ┆ niz ┆ 282 ┆     ┆     ┆     ┆ 249 ┆     ┆     ┆ ids │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆ 1   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ org ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ 1   ┆     ┆ 262 ┆ rar ┆ j.c ┆     ┆     ┆     ┆     ┆ 66  ┆ uen ┆ let ┆     ┆     ┆     ┆ 4   ┆ 242 ┆     ┆     ┆     ┆     ┆     ┆ let ┆     ┆     ┆ uen ┆ 52  ┆     ┆     ┆     ┆     ┆ 1   ┆ 282 ┆ ed  ┆ 1   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ ano ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ met ┆     ┆     ┆     ┆     ┆     ┆ cin ┆ al  ┆     ┆     ┆     ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆ ids ┆     ┆ lic ┆     ┆     ┆     ┆     ┆ Hos ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆ .20 ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆ Mus ┆     ┆     ┆     ┆     ┆ 970 ┆     ┆     ┆     ┆     ┆     ┆ Mus ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ Tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆ pit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆ 21. ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ cle ┆     ┆     ┆     ┆     ┆ 1;2 ┆     ┆     ┆     ┆     ┆     ┆ cle ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 03. ┆     ┆     ┆     ┆     ┆     ┆ 451 ┆ Mou ┆     ┆     ┆     ┆     ┆ 513 ┆     ┆     ┆     ┆     ┆     ┆ Mou ┆     ┆     ┆ 451 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ 005 ┆     ┆     ┆     ┆     ┆     ┆ 282 ┆ nts ┆     ┆     ┆     ┆     ┆ 330 ┆     ┆     ┆     ┆     ┆     ┆ nts ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆ a   ┆     ┆     ┆     ┆     ┆ 211 ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆ Lon ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lon ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆ g-R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g-R ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆ ang ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ang ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_1 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ l_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pro ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tec ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ tiv ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tiv ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ Res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Res ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ pon ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pon ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ita ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE154746 (PAIRED) PRO-seq

- validate date: 2025-05-04
- [Stress-induced transcriptional memory accelerates promoter-proximal pause release and decelerates termination over mitotic divisions](https://doi.org/10.1016/j.molcel.2021.03.007)
- [実験医学: PRO-seq](https://www.yodosha.co.jp/jikkenigaku/keyword/PRO-seq/id/107099)
- `unconditioned (uC) or preconditioned with a single heat shock exposure (pC)` という条件がある
- 42℃で複数の曝露時間条件が含まれている
- 処理を[12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に移動

### GSE134813 (PAIRED) NO DOWNLOAD

- validate date: 2025-05-04
- [The Alazami Syndrome-Associated Protein LARP7 Guides U6 Small Nuclear RNA Modification and Contributes to Splicing Robustness](https://doi.org/10.1016/j.molcel.2020.01.001)
- LARP7に関する研究
- コントロールとなるデータが含まれていなかったので今回はこのデータは収集しない

In [54]:
# ID = "GSE134813"

# GSE134813_PEP = pl.read_csv(
#     f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
#     separator=','
# )

# pl.Config.set_fmt_str_lengths(200)
# display(GSE134813_PEP)

### GSE128365 (PAIRED) scEdU-seq

- validate date: 2025-05-04
- [Quantifying DNA replication speeds in single cells by scEdU-seq](https://doi.org/10.1038/s41592-024-02308-4)
- `single-cell 5-ethynyl-2′-deoxyuridine sequencing (scEdU-seq)` という手法に関するデータ
- nacsent RNAの検出ができる手法
- ~~一応 scRNA-seqの亜種なので、今回は収集しない (もしかしたら後ほど収集するかも？)~~
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 20. GSE123980 (PAIRED) RNA-seq

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [The pause-initiation limit restricts transcription activation in human cells](https://doi.org/10.1038/s41467-019-11536-8)
- TT-seq,RNA-seq,mNET-seqなどの複数の手法が含まれている
- [TT-seqに関する論文: TT-seq maps the human transient transcriptome](https://doi.org/10.1126/science.aad9841)
- [mNET-seq](https://jp.illumina.com/science/sequencing-method-explorer/kits-and-arrays/mnet-seq.html)
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)にbulk RNA-seq以外のデータの処理を移行

In [55]:
ID = "GSE123980"

GSE123980_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Ovation Universal RNA-Seq System").alias("rna_library"), # add rna_library column from GEO webpage (NuGEN)
    pl.lit("https://doi.org/10.1038/s41467-019-11536-8").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("37 C").alias("control treatment temperature"), # add control temperature column


    pl.when(
        pl.col("sample_name").str.contains(r'_hs15_')
    ).then(
        pl.lit("15 min.")
    ).when(
        pl.col("sample_name").str.contains(r'_hs30_')
    ).then(
        pl.lit("30 min.")
    ).otherwise(
        pl.lit(None)
    ).alias("stress treatment time")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE123980_PEP_rna_seq = GSE123980_PEP.filter(
    pl.col("sample_title").str.contains(r'RNA-seq_')
)

# metadata from iseq
GSE123980_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE123980_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE123980_iseq_filtered = GSE123980_iseq[[s.name for s in GSE123980_iseq if not (s.null_count() == GSE123980_iseq.height)]]

GSE123980_rna_seq_combined = GSE123980_PEP_rna_seq.join(
    GSE123980_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE123980_rna_seq_combined = GSE123980_rna_seq_combined[[s.name for s in GSE123980_rna_seq_combined if not (s.null_count() == GSE123980_rna_seq_combined.height)]]

GSE123980_rna_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE123980_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# pl.Config.set_tbl_rows(100)
# display(GSE123980_rna_seq_combined)

In [56]:
# RNA-seq
defined_pairs_gse123980_rna_seq = [
    ("SRR8334021", "SRR8334019"), # RNA-seq_K562_HS15_rep1 vs RNA-seq_K562_Ctrl_rep1
    ("SRR8334022", "SRR8334020"), # RNA-seq_K562_HS15_rep2 vs RNA-seq_K562_Ctrl_rep2
    ("SRR8334023", "SRR8334019"), # RNA-seq_K562_HS30__rep1 vs RNA-seq_K562_Ctrl_rep1
    ("SRR8334024", "SRR8334020")  # RNA-seq_K562_HS30_rep2 vs RNA-seq_K562_Ctrl_rep2
]

paired_metadata_df_gse123980_rna_seq = create_paired_metadata(
    combined_df=GSE123980_rna_seq_combined,
    defined_sample_pairs=defined_pairs_gse123980_rna_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse123980_rna_seq is not None:
    # Strip residual "null vs " prefix and " vs null" suffix from all string columns,
    # which appear when only one side of a pair has a value.
    paired_metadata_df_gse123980_rna_seq = paired_metadata_df_gse123980_rna_seq.with_columns(
        pl.col(pl.String)
        .str.replace_all(r"^null vs ", "") # control treatment temperature column から "null vs " を削除
        .str.replace_all(r" vs null$", "") # stress treatment temperature column から "vs null" を削除
    )
    # Control samples have no stress time, so "15 min. vs null" became null.
    # Set the heat-side time from sample_title for each pair.
    paired_metadata_df_gse123980_rna_seq = paired_metadata_df_gse123980_rna_seq.with_columns(
        pl.when(
            pl.col("sample_title").str.contains(r'^RNA-seq_K562_HS15_')
        ).then(
            pl.lit("15 min.")
        ).when(
            pl.col("sample_title").str.contains(r'^RNA-seq_K562_HS30_')
        ).then(
            pl.lit("30 min.")
        ).otherwise(
            pl.col("stress treatment time")
        ).alias("stress treatment time")
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse123980_rna_seq)
    paired_metadata_df_gse123980_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE123980_rna_seq_paired_metadata.tsv",
        separator='\t'
    )
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tre ┆ mol ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ con ┆ str ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ atm ┆ ecu ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ tro ┆ ess ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _ex ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ent ┆ le  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ l   ┆ tre ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ tra ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ _co ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ tre ┆ atm ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ct_ ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ ndi ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ atm ┆ ent ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ pro ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ tio ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ ent ┆ tim ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ toc ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ ns  ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ tem ┆ e   ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ ol_ ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ per ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ ch1 ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ atu ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ RNA ┆ GSM ┆ Pub ┆ Dec ┆ Jul ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ tot ┆ Ova ┆ GPL ┆ Bjö ┆ bsc ┆ MPI ┆ Fas ┆ Göt ┆ 370 ┆ Ger ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ 4sU ┆ Tot ┆ big ┆ SAM ┆ Ova ┆ htt ┆ 42  ┆ 37  ┆ 15  ┆ SRR ┆ Nex ┆ The ┆ SRA ┆ cDN ┆ 201 ┆ 612 ┆ 452 ┆ ILL ┆ Gen ┆ RNA ┆ SRP ┆ 100 ┆ The ┆ RNA ┆ Nex ┆ Nex ┆ 153 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Ova ┆ GSM ┆ GEO ┆ K56 ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 833 ┆ 833 ┆ -se ┆ A   ┆ o   ┆ RED ┆     ┆ 833 ┆ 514 ┆ -se ┆ 351 ┆ lic ┆ 17  ┆ 10  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ al  ┆ tio ┆ 185 ┆ rn, ┆ hwa ┆     ┆ sbe ┆ tin ┆ 77  ┆ man ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 351 ┆ :// ┆ :// ┆ 123 ┆     ┆ 514 ┆ 2   ┆ (Si ┆ al  ┆ wig ┆ N10 ┆ tio ┆ ps: ┆ C   ┆ C   ┆ min ┆ 833 ┆ tSe ┆ pau ┆ 824 ┆ A   ┆ 9-0 ┆ 688 ┆ 830 ┆ UMI ┆ eri ┆ -se ┆ 173 ┆ 709 ┆ pau ┆ -se ┆ tSe ┆ tSe ┆ 077 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 351 ┆ 351 ┆ tio ┆ 351 ┆     ┆ 2   ┆ 9-0 ┆ NA5 ┆ 415 ┆ 9-0 ┆ 123 │
│ 402 ┆ 401 ┆ q_k ┆     ┆ sap ┆     ┆     ┆ 402 ┆ 553 ┆ q_K ┆ 811 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ery ┆ sap ┆     ┆ RNA ┆ n   ┆ 73  ┆ ,Sc ┆ l@g ┆     ┆ rg  ┆ gen ┆     ┆ y   ┆ na  ┆     ┆ rip ┆ q   ┆ 811 ┆ ftp ┆ ftp ┆ 980 ┆     ┆ 553 ┆     ┆ gma ┆ fra ┆ fil ┆ 604 ┆ n   ┆ //d ┆     ┆     ┆ .   ┆ 402 ┆ q   ┆ se- ┆ 487 ┆     ┆ 7-1 ┆ 757 ┆ 975 ┆ NA  ┆ c   ┆ q_K ┆ 667 ┆ 060 ┆ se- ┆ q_K ┆ q   ┆ q   ┆ 771 ┆ q   ┆ RIP ┆     ┆     ┆ 811 ┆ 811 ┆ n   ┆ 811 ┆     ┆     ┆ 7-1 ┆ 104 ┆ 591 ┆ 7-1 ┆ 980 │
│ 1   ┆ 9   ┆ 562 ┆     ┆ ien ┆     ┆     ┆ 1   ┆ 9   ┆ 562 ┆ 3   ┆ Jul ┆ 8   ┆ 9   ┆     ┆     ┆ thr ┆ ien ┆     ┆     ┆ Uni ┆     ┆ hwa ┆ wdg ┆     ┆ 11  ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 3   ┆ .nc ┆ .nc ┆     ┆     ┆ 9   ┆     ┆ )   ┆ gme ┆ es  ┆ 688 ┆ Uni ┆ oi. ┆     ┆     ┆     ┆ 1   ┆ 500 ┆ ini ┆     ┆     ┆ 1   ┆ 7   ┆ 8;4 ┆     ┆     ┆ 562 ┆     ┆ vs  ┆ ini ┆ 562 ┆ 500 ┆ 500 ┆ 20  ┆     ┆ TOM ┆     ┆     ┆ 3   ┆ 3_r ┆ Uni ┆ 3   ┆     ┆     ┆ 1   ┆ 28  ┆ 8   ┆ 1   ┆     │
│     ┆     ┆ _hs ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ _HS ┆ vs  ┆ 10  ┆     ┆     ┆     ┆     ┆ ole ┆ s   ┆     ┆     ┆ ver ┆     ┆ lb  ┆ .de ┆     ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ lab ┆ nte ┆ con ┆ vs  ┆ ver ┆ org ┆     ┆     ┆     ┆ vs  ┆ seq ┆ tia ┆     ┆     ┆     ┆ vs  ┆ 572 ┆     ┆     ┆ _HS ┆     ┆ 102 ┆ tia ┆ _HS ┆     ┆ seq ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ver ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ 15_ ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ 15_ ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ uke ┆     ┆     ┆     ┆ sal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ eli ┆ d   ┆ tai ┆ SAM ┆ sal ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ uen ┆ tio ┆     ┆     ┆     ┆ 624 ┆ 681 ┆     ┆     ┆ 15_ ┆     ┆ 213 ┆ tio ┆ 15_ ┆     ┆ uen ┆ 155 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ sal ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ 833 ┆ 514 ┆ rep ┆ 351 ┆ 9   ┆     ┆     ┆     ┆     ┆ mia ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 351 ┆ .ni ┆ .ni ┆     ┆     ┆ 514 ┆     ┆ ng  ┆ RNA ┆ nin ┆ N10 ┆ RNA ┆ .10 ┆     ┆     ┆     ┆ 833 ┆ cin ┆ n   ┆     ┆     ┆     ┆ 689 ┆ 847 ┆     ┆     ┆ rep ┆     ┆ 680 ┆ n   ┆ rep ┆     ┆ cin ┆ 364 ┆     ┆     ┆     ┆     ┆ 351 ┆ GSM ┆ RNA ┆ 351 ┆     ┆     ┆     ┆     ┆ 415 ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 401 ┆ 553 ┆ 1   ┆ 811 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 811 ┆ h.g ┆ h.g ┆     ┆     ┆ 553 ┆     ┆ for ┆     ┆ g   ┆ 604 ┆ -Se ┆ 38/ ┆     ┆     ┆     ┆ 401 ┆ g:  ┆ lim ┆     ┆     ┆     ┆ 365 ┆ vs  ┆     ┆     ┆ 1   ┆     ┆     ┆ lim ┆ 1   ┆     ┆ g:  ┆ 793 ┆     ┆     ┆     ┆     ┆ 811 ┆ 351 ┆ -Se ┆ 811 ┆     ┆     ┆     ┆     ┆ 591 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 9   ┆ 7   ┆ vs  ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 7   ┆     ┆ 5   ┆     ┆ the ┆ 690 ┆ q   ┆ s41 ┆     ┆     ┆     ┆ 9   ┆ GSM ┆ it  ┆     ┆     ┆     ┆ 2   ┆ 460 ┆     ┆     ┆ vs  ┆     ┆     ┆ it  ┆ vs  ┆     ┆ GSM ┆ 60  ┆     ┆     ┆     ┆     ┆ 1   ┆ 811 ┆ q   ┆ 1   ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     │
│     ┆     ┆ rna ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆ min ┆     ┆ cov ┆     ┆ Sys ┆ 467 ┆     ┆     ┆     ┆     ┆ 351 ┆ res ┆     ┆     ┆     ┆     ┆ 470 ┆     ┆     ┆ RNA ┆     ┆     ┆ res ┆ RNA ┆     ┆ 351 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ Sys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆ ute ┆     ┆ era ┆     ┆ tem ┆ -01 ┆     ┆     ┆     ┆     ┆ 811 ┆ tri ┆     ┆     ┆     ┆     ┆ 926 ┆     ┆     ┆ -se ┆     ┆     ┆ tri ┆ -se ┆     ┆ 811 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_k ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Nu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆ s.  ┆     ┆ ge  ┆     ┆     ┆ 9-1 ┆     ┆     ┆     ┆     ┆ 3:  ┆ cts ┆     ┆     ┆     ┆     ┆ 3;4 ┆     ┆     ┆ q_K ┆     ┆     ┆ cts ┆ q_K ┆     ┆ 3:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Nu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GEN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 153 ┆     ┆     ┆     ┆     ┆ RNA ┆ tra ┆     ┆     ┆     ┆     ┆ 642 ┆     ┆     ┆ 562 ┆     ┆     ┆ tra ┆ 562 ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GEN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ct ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ct ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ),  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-8 ┆     ┆     ┆     ┆     ┆ -se ┆ nsc ┆     ┆     ┆     ┆     ┆ 097 ┆     ┆     ┆ _Ct ┆     ┆     ┆ nsc ┆ _Ct ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TT- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 351 ┆ 351 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_K ┆ rip ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆ rl_ ┆     ┆     ┆ rip ┆ rl_ ┆     ┆ q_K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TT- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8nn ┆ 8nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ tio ┆ rep ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ n   ┆ 1   ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15_ ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ act ┆     ┆     ┆ 15_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 518 ┆ 518 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆ iva ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iva ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 113 ┆ 113 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Sc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Sc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hwa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hwa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lb  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hum ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lb  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 21. GSE115731 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [Stress-Induced Low Complexity RNA Activates Physiological Amyloidogenesis](https://doi.org/10.1016/j.celrep.2018.07.040)
- コントロールと熱ショックのデータがしっかり揃っているデータなので収集する
-

In [57]:
ID = "GSE115731"

GSE115731_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded Total RNA Library Prep Kit (without rRNA depletion)").alias("rna_library"), # add rna_library column from GEO accession (Illumina)
    pl.lit("https://doi.org/10.1016/j.celrep.2018.07.040").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column
    pl.lit("37 C").alias("control treatment temperature"), # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE115731_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE115731_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE115731_iseq_filtered = GSE115731_iseq[[s.name for s in GSE115731_iseq if not (s.null_count() == GSE115731_iseq.height)]]

GSE115731_combined = GSE115731_PEP.join(
    GSE115731_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE115731_combined = GSE115731_combined[[s.name for s in GSE115731_combined if not (s.null_count() == GSE115731_combined.height)]]

GSE115731_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE115731_modified_metadata.tsv",
    separator='\t'
)

# display(GSE115731_combined)

In [58]:
defined_pairs_gse115731 = [
    ("SRR7309387", "SRR7309386") # RNA from MCF7 cells, 30 minutes, 43C heat shock (30HS), no ribosomal RNA depletion vs RNA from MCF7 cells, no treatment (NT), no ribosomal RNA depletion
]

paired_metadata_df_gse115731 = create_paired_metadata(
    combined_df=GSE115731_combined,
    defined_sample_pairs=defined_pairs_gse115731,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse115731 is not None:
    paired_metadata_df_gse115731.write_csv(
        "../../Data/metadata/metadata_paired/GSE115731_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse115731)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ iso ┆ dis ┆ tre ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ iso ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ lat ┆ eas ┆ atm ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ lat ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ e   ┆ e   ┆ ent ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ e_r ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ igh ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ t   ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ --- ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ str ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ RNA ┆ GSM ┆ Pub ┆ Jun ┆ Aug ┆ SRA ┆ 1   ┆ MCF ┆ Hom ┆ 960 ┆ nuc ┆ GPL ┆ Ste ┆ ste ┆ Gau ┆ Bio ┆ Uni ┆ 101 ┆ Mia ┆ Flo ┆ 331 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ HTB ┆ ade ┆ 30  ┆ GRC ┆ BED ┆ SAM ┆ Tru ┆ htt ┆ 43  ┆ 30  ┆ 37  ┆ SRR ┆ Nex ┆ Hea ┆ SRA ┆ cDN ┆ 201 ┆ 104 ┆ HTB ┆ 492 ┆ ILL ┆ Gen ┆ RNA ┆ SRP ┆ 821 ┆ Hea ┆ RNA ┆ Nex ┆ Nex ┆ 222 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ MCF ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE ┆ mam │
│ 730 ┆ 730 ┆ _fr ┆ A   ┆ o   ┆ RED ┆     ┆ 730 ┆ 421 ┆ fro ┆ 318 ┆ lic ┆ 13  ┆ 02  ┆     ┆     ┆ 7   ┆ o   ┆ 6   ┆ lea ┆ 185 ┆ phe ┆ phe ┆ tie ┆ che ┆ ver ┆ 1   ┆ mi  ┆ rid ┆ 36  ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 318 ┆ :// ┆ :// ┆ 115 ┆     ┆ 421 ┆ 7   ┆ -22 ┆ noc ┆ min ┆ h38 ┆ ,   ┆ N09 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 730 ┆ tSe ┆ t   ┆ 721 ┆ A   ┆ 8-0 ┆ 710 ┆ -22 ┆ 599 ┆ UMI ┆ eri ┆ fro ┆ 150 ┆ 080 ┆ t   ┆ fro ┆ tSe ┆ tSe ┆ 233 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 318 ┆ 318 ┆ fro ┆ 318 ┆     ┆ 7   ┆ 8-0 ┆ NA4 ┆ 341 ┆ 8-0 ┆ 115 ┆ mar │
│ 938 ┆ 938 ┆ om_ ┆     ┆ sap ┆     ┆     ┆ 938 ┆ 175 ┆ m   ┆ 843 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ mam ┆ sap ┆     ┆ r   ┆ 73  ┆ n,, ┆ nle ┆ r   ┆ mis ┆ sit ┆ NW  ┆     ┆ a   ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 843 ┆ ftp ┆ ftp ┆ 731 ┆     ┆ 175 ┆     ┆     ┆ arc ┆ ute ┆ (ge ┆ ali ┆ 406 ┆ Str ┆ //d ┆     ┆ .   ┆     ┆ 938 ┆ q   ┆ sho ┆ 370 ┆     ┆ 8-0 ┆ 219 ┆     ┆ 240 ┆ NA  ┆ c   ┆ m   ┆ 441 ┆ 83  ┆ sho ┆ m   ┆ q   ┆ q   ┆ 689 ┆ q   ┆ RIP ┆     ┆     ┆ 843 ┆ 843 ┆ m   ┆ 843 ┆     ┆     ┆ 8-0 ┆ 759 ┆ 447 ┆ 8-0 ┆ 731 ┆ y   │
│ 7   ┆ 6   ┆ mcf ┆     ┆ ien ┆     ┆     ┆ 7   ┆ 5   ┆ MCF ┆ 1   ┆ Aug ┆ 8   ┆ 8   ┆     ┆     ┆ mar ┆ ien ┆     ┆ RNA ┆     ┆ Lee ┆ e@m ┆ Bld ┆ try ┆ y   ┆ 15  ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 1   ┆ .nc ┆ .nc ┆     ┆     ┆ 5   ┆     ┆     ┆ ino ┆ s,  ┆ nco ┆ gnm ┆ 962 ┆ and ┆ oi. ┆     ┆     ┆     ┆ 7   ┆ 500 ┆ ck- ┆     ┆     ┆ 8   ┆ 88  ┆     ┆ 8;5 ┆     ┆     ┆ MCF ┆     ┆ vs  ┆ ck- ┆ MCF ┆ 500 ┆ 500 ┆ 28  ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ the ┆ 1   ┆     ┆     ┆ 8   ┆ 62  ┆ 7   ┆ 8   ┆     ┆ gla │
│     ┆     ┆ 7_c ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ 7   ┆ vs  ┆ 02  ┆     ┆     ┆     ┆     ┆ y   ┆ s   ┆     ┆     ┆     ┆     ┆ ed. ┆ g,  ┆ &   ┆ of  ┆ st. ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆     ┆ ma  ┆ 43C ┆ de  ┆ ent ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆     ┆ vs  ┆ seq ┆ ind ┆     ┆     ┆     ┆ vs  ┆     ┆ 046 ┆     ┆     ┆ 7   ┆     ┆ 745 ┆ ind ┆ 7   ┆     ┆ seq ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ dig ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ nd, │
│     ┆     ┆ ell ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ cel ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ gla ┆     ┆     ┆     ┆     ┆     ┆ mia ┆ Rm  ┆ Mol ┆ Mia ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆ hea ┆ v27 ┆ fil ┆ SAM ┆ Tot ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ uen ┆ uce ┆     ┆     ┆     ┆ 972 ┆     ┆ 444 ┆     ┆     ┆ cel ┆     ┆ 442 ┆ uce ┆ cel ┆     ┆ uen ┆ 204 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ ito ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆ bre │
│     ┆     ┆ s_3 ┆     ┆     ┆     ┆     ┆ 730 ┆ 421 ┆ ls, ┆ 318 ┆ 8   ┆     ┆     ┆     ┆     ┆ nd  ┆     ┆     ┆     ┆     ┆     ┆ mi. ┆ 228 ┆ ecu ┆ mi  ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 318 ┆ .ni ┆ .ni ┆     ┆     ┆ 421 ┆     ┆     ┆     ┆ t   ┆ )   ┆ es  ┆ N09 ┆ al  ┆ .10 ┆     ┆     ┆     ┆ 730 ┆ cin ┆ d   ┆     ┆     ┆     ┆ 268 ┆     ┆ 466 ┆     ┆     ┆ ls, ┆     ┆ 70  ┆ d   ┆ ls, ┆     ┆ cin ┆ 758 ┆     ┆     ┆     ┆     ┆ 318 ┆ GSM ┆ nin ┆ 318 ┆     ┆     ┆     ┆     ┆ 341 ┆     ┆     ┆ ast │
│     ┆     ┆ 0_m ┆     ┆     ┆     ┆     ┆ 938 ┆ 175 ┆ 30  ┆ 843 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ edu ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 843 ┆ h.g ┆ h.g ┆     ┆     ┆ 175 ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ 406 ┆ RNA ┆ 16/ ┆     ┆     ┆     ┆ 938 ┆ g:  ┆ rib ┆     ┆     ┆     ┆ 985 ┆     ┆ vs  ┆     ┆     ┆ 30  ┆     ┆     ┆ rib ┆ 30  ┆     ┆ g:  ┆ 402 ┆     ┆     ┆     ┆     ┆ 843 ┆ 318 ┆ -in ┆ 843 ┆     ┆     ┆     ┆     ┆ 447 ┆     ┆     ┆ der │
│     ┆     ┆ inu ┆     ┆     ┆     ┆     ┆ 6   ┆ 4   ┆ min ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ 963 ┆ Lib ┆ j.c ┆     ┆     ┆     ┆ 6   ┆ GSM ┆ oso ┆     ┆     ┆     ┆ 3   ┆     ┆ 508 ┆     ┆     ┆ min ┆     ┆     ┆ oso ┆ min ┆     ┆ GSM ┆ 09  ┆     ┆     ┆     ┆     ┆ 0   ┆ 843 ┆ sol ┆ 0   ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆ ive │
│     ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ rar ┆ elr ┆     ┆     ┆     ┆     ┆ 318 ┆ mal ┆     ┆     ┆     ┆     ┆     ┆ 071 ┆     ┆     ┆ ute ┆     ┆     ┆ mal ┆ ute ┆     ┆ 318 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_r ┆ ubl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   │
│     ┆     ┆ _43 ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ non ┆     ┆     ┆     ┆ y   ┆ ep. ┆     ┆     ┆     ┆     ┆ 843 ┆ int ┆     ┆     ┆     ┆     ┆     ┆ 726 ┆     ┆     ┆ s,  ┆     ┆     ┆ int ┆ s,  ┆     ┆ 843 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fro │
│     ┆     ┆ c_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43C ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ Pre ┆ 201 ┆     ┆     ┆     ┆     ┆ 1:  ┆ erg ┆     ┆     ┆     ┆     ┆     ┆ 0;5 ┆     ┆     ┆ 43C ┆     ┆     ┆ erg ┆ 43C ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   │
│     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆ 8.0 ┆     ┆     ┆     ┆     ┆ RNA ┆ eni ┆     ┆     ┆     ┆     ┆     ┆ 160 ┆     ┆     ┆ hea ┆     ┆     ┆ eni ┆ hea ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ met │
│     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ 7.0 ┆     ┆     ┆     ┆     ┆ fro ┆ c   ┆     ┆     ┆     ┆     ┆     ┆ 442 ┆     ┆     ┆ t   ┆     ┆     ┆ c   ┆ t   ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast │
│     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 318 ┆ 318 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (wi ┆ 40  ┆     ┆     ┆     ┆     ┆ m   ┆ spa ┆     ┆     ┆     ┆     ┆     ┆ 456 ┆     ┆     ┆ sho ┆     ┆     ┆ spa ┆ sho ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati │
│     ┆     ┆ _30 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8nn ┆ 8nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tho ┆     ┆     ┆     ┆     ┆     ┆ MCF ┆ cer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ cer ┆ ck  ┆     ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   │
│     ┆     ┆ hs_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ (30 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ut  ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (30 ┆     ┆     ┆ RNA ┆ (30 ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit │
│     ┆     ┆ no_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rRN ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS) ┆     ┆     ┆     ┆ HS) ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e:  │
│     ┆     ┆ rib ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 188 ┆ 188 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆ ,   ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple │
│     ┆     ┆ oso ┆     ┆     ┆     ┆     ┆     ┆     ┆ no  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 431 ┆ 431 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dep ┆     ┆     ┆     ┆     ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ no  ┆     ┆     ┆     ┆ no  ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ura │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE100469 (PAIRED) 4sU-seq

- validate date: 2025-05-04
- [HSV-1-induced disruption of transcription termination resembles a cellular stress response but selectively increases chromatin accessibility downstream of genes](https://doi.org/10.1371/journal.ppat.1006954)
- 4sU-seqなので、新生RNAを検出しているデータ
- 念の為収集
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

### GSE95854 (PAIRED) NO DOWNLOAD

- validate date: 2025-05-04
- [TimeLapse-seq: Adding a temporal dimension to RNA sequencing through nucleoside recoding](https://doi.org/10.1038/nmeth.4582)
- TimeLapse-seqという以前の研究で使用したデータ
- 今回も念の為収集しておく... と思ったが、ヒトのデータでは熱ストレスを加えているデータはなかったので今回は収集しない (マウスのデータには含まれていた)

In [59]:
# ID = "GSE95854"

# GSE95854_PEP = pl.read_csv(
#     f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
#     separator=','
# ).filter(
#     pl.col("sample_organism_ch1") == "Homo sapiens"
# )

# pl.Config.set_fmt_str_lengths(200)
# display(GSE95854_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 22. GSE100408 (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-04
- [Probing the roles of SUMOylation in cancer cell biology by using a selective SAE inhibitor](https://doi.org/10.1038/nchembio.2463)
- 全文が見られないが、Gene Expression Omnibus (GEO) の ホームページから 条件を調べることが可能
- [GSM2680465](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2680465)
- 熱ストレスに関連するデータ (`0.5 h at 43 ⁰C`) とコントロールのデータのみ収集

In [60]:
ID = "GSE100408"

GSE100408_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_title").str.contains(r'Heatshock')) | (pl.col("sample_title").str.contains(r'_No heatshock'))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded mRNA Library Kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1038/nchembio.2463").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE100408_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE100408_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE100408_iseq_filtered = GSE100408_iseq[[s.name for s in GSE100408_iseq if not (s.null_count() == GSE100408_iseq.height)]]

GSE100408_combined = GSE100408_PEP.join(
    GSE100408_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE100408_combined = GSE100408_combined[[s.name for s in GSE100408_combined if not (s.null_count() == GSE100408_combined.height)]]

GSE100408_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE100408_modified_metadata.tsv",
    separator='\t'
)

# display(GSE100408_combined)

In [61]:
defined_pairs_gse100408 = [
    ("SRR5749642", "SRR5749648"), # HCT116_DMSO_With Heatshock (SAE032527) vs HCT116_DMSO_No heatshock (SAE034010)
    ("SRR5749643", "SRR5749649"), # HCT116_DMSO_With Heatshock (SAE032530) vs HCT116_DMSO_No heatshock (SAE034013)
    ("SRR5749644", "SRR5749650"), # HCT116_DMSO_With Heatshock (SAE032533) vs HCT116_DMSO_No heatshock (SAE034016)
    ("SRR5749645", "SRR5749651"), # HCT116_ML00754792_With Heatshock (SAE032537) vs HCT116_ML00754792_No heatshock (SAE034019)
    ("SRR5749646", "SRR5749652"), # HCT116_ML00754792_With Heatshock (SAE032540) vs HCT116_ML00754792_No heatshock (SAE034022)
    ("SRR5749647", "SRR5749653")  # HCT116_ML00754792_With Heatshock (SAE032542) vs HCT116_ML00754792_No heatshock (SAE034025)
]

paired_metadata_df_gse100408 = create_paired_metadata(
    combined_df=GSE100408_combined,
    defined_sample_pairs=defined_pairs_gse100408,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse100408 is not None:
    paired_metadata_df_gse100408.write_csv(
        "../../Data/metadata/metadata_paired/GSE100408_paired_metadata.tsv",
        separator='\t'
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse100408)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 84)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tre ┆ dos ┆ tim ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ atm ┆ age ┆ e   ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ent ┆ --- ┆ --- ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ str ┆ str ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆     ┆     ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hct ┆ cDN ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HCT ┆ GSM ┆ Pub ┆ Jun ┆ May ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ tot ┆ SAE ┆ GPL ┆ Poo ┆ poo ┆ Tak ┆ 40  ┆ Cam ┆ MA  ┆ 213 ┆ USA ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ col ┆ DMS ┆ nul ┆ 3.5 ┆ Hum ┆ mRN ┆ SAM ┆ Tru ┆ htt ┆ 43  ┆ 30  ┆ 37  ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ cDN ┆ 201 ┆ 362 ┆ 294 ┆ ILL ┆ Gen ┆ HCT ┆ SRP ┆ 714 ┆ Pro ┆ HCT ┆ Ill ┆ Ill ┆ 729 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ GEO ┆ col ┆ 201 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 574 ┆ 574 ┆ 116 ┆ A   ┆ o   ┆ RED ┆     ┆ 574 ┆ 294 ┆ 116 ┆ 268 ┆ lic ┆ 23  ┆ 15  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ al  ┆ 032 ┆ 111 ┆ ja, ┆ ja. ┆ eda ┆ Lan ┆ bri ┆     ┆ 9   ┆     ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 268 ┆ E   ┆ 100 ┆     ┆ 294 ┆ ore ┆ O   ┆ l   ┆ hr  ┆ an  ┆ A   ┆ N07 ┆ Seq ┆ ps: ┆ C   ┆ min ┆ C   ┆ 574 ┆ umi ┆ o   ┆ 580 ┆ A   ┆ 7-1 ┆ 491 ┆ 908 ┆ UMI ┆ eri ┆ 116 ┆ 110 ┆ 809 ┆ bin ┆ 116 ┆ umi ┆ umi ┆ 105 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ 268 ┆ 268 ┆ was ┆ 268 ┆     ┆ ore ┆ 7-1 ┆ NA3 ┆ 230 ┆ 7-1 ┆ 100 │
│ 964 ┆ 964 ┆ _dm ┆     ┆ sap ┆     ┆     ┆ 964 ┆ 989 ┆ _DM ┆ 046 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ _DM ┆ sap ┆     ┆ RNA ┆ 527 ┆ 54  ┆ ,Sh ┆ sha ┆ Pha ┆ dsd ┆ dge ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 046 ┆     ┆ 408 ┆     ┆ 989 ┆ cta ┆     ┆     ┆     ┆ Gen ┆ FPK ┆ 270 ┆ Str ┆ //d ┆     ┆ .   ┆ (in ┆ 964 ┆ na  ┆ sap ┆ 466 ┆     ┆ 1-0 ┆ 944 ┆ 809 ┆ NA  ┆ c   ┆ _DM ┆ 248 ┆ 63  ┆ g   ┆ _DM ┆ na  ┆ na  ┆ 822 ┆ q   ┆ RIP ┆     ┆     ┆ 046 ┆ 046 ┆ iso ┆ 046 ┆     ┆ cta ┆ 1-0 ┆ 915 ┆ 836 ┆ 1-0 ┆ 408 │
│ 2   ┆ 8   ┆ so_ ┆     ┆ ien ┆     ┆     ┆ 2   ┆ 2   ┆ SO_ ┆ 2   ┆ Sep ┆ 7   ┆ 9   ┆     ┆     ┆ SO_ ┆ ien ┆     ┆     ┆ vs  ┆     ┆ ah  ┆ h@t ┆ rma ┆ own ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 2   ┆     ┆     ┆     ┆ 2   ┆ l   ┆     ┆     ┆     ┆ ome ┆ M   ┆ 995 ┆ and ┆ oi. ┆     ┆     ┆ fer ┆ 2   ┆ HiS ┆ ien ┆     ┆     ┆ 9   ┆ 2   ┆ 2;3 ┆     ┆     ┆ SO_ ┆     ┆ vs  ┆ the ┆ SO_ ┆ HiS ┆ HiS ┆ 6   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_r ┆ lat ┆ 2   ┆     ┆ l   ┆ 9   ┆ 84  ┆ 3   ┆ 9   ┆     │
│     ┆     ┆ wit ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ Wit ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆ Wit ┆ s   ┆     ┆     ┆ SAE ┆     ┆     ┆ ake ┆ ceu ┆ e   ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ can ┆     ┆     ┆     ┆ (Hu ┆ cou ┆ vs  ┆ ed  ┆ org ┆     ┆     ┆ red ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆     ┆ vs  ┆ 055 ┆     ┆     ┆ Wit ┆     ┆ 838 ┆ Rol ┆ Wit ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ed  ┆ vs  ┆     ┆ can ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ h_h ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ h   ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆ 034 ┆     ┆     ┆ da. ┆ tic ┆ Str ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ cer ┆     ┆     ┆     ┆ man ┆ nt  ┆ SAM ┆ mRN ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ 200 ┆     ┆     ┆     ┆     ┆ 479 ┆ 764 ┆     ┆     ┆ h   ┆     ┆ 703 ┆ es  ┆ h   ┆ 200 ┆ 200 ┆ 855 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ fro ┆ GSM ┆     ┆ cer ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆ 574 ┆ 294 ┆ Hea ┆ 268 ┆ 7   ┆     ┆     ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆ 010 ┆     ┆     ┆ com ┆ als ┆ eet ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 268 ┆     ┆     ┆     ┆ 294 ┆ cel ┆     ┆     ┆     ┆ .B3 ┆ dat ┆ N07 ┆ A   ┆ .10 ┆     ┆     ┆     ┆ 574 ┆ 0   ┆     ┆     ┆     ┆     ┆ 195 ┆ 235 ┆     ┆     ┆ Hea ┆     ┆ 28  ┆ of  ┆ Hea ┆ 0   ┆ 0   ┆ 477 ┆     ┆     ┆     ┆     ┆ 268 ┆ GSM ┆ m   ┆ 268 ┆     ┆ cel ┆     ┆     ┆ 230 ┆     ┆     │
│     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆ 964 ┆ 989 ┆ tsh ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 046 ┆     ┆     ┆     ┆ 989 ┆ l   ┆     ┆     ┆     ┆ 7.3 ┆ a   ┆ 270 ┆ Lib ┆ 38/ ┆     ┆     ┆     ┆ 964 ┆ seq ┆     ┆     ┆     ┆     ┆ 971 ┆ vs  ┆     ┆     ┆ tsh ┆     ┆     ┆ SUM ┆ tsh ┆     ┆ seq ┆ 345 ┆     ┆     ┆     ┆     ┆ 046 ┆ 268 ┆ bio ┆ 046 ┆     ┆ l   ┆     ┆     ┆ 837 ┆     ┆     │
│     ┆     ┆ ck_ ┆     ┆     ┆     ┆     ┆ 8   ┆ 8   ┆ ock ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 8   ┆ lin ┆     ┆     ┆     ┆ )   ┆ for ┆ 989 ┆ rar ┆ nch ┆     ┆     ┆     ┆ 8   ┆ uen ┆     ┆     ┆     ┆     ┆ 5   ┆ 373 ┆     ┆     ┆ ock ┆     ┆     ┆ Oyl ┆ ock ┆     ┆ uen ┆ 6   ┆     ┆     ┆     ┆     ┆ 8   ┆ 046 ┆ log ┆ 8   ┆     ┆ lin ┆     ┆     ┆ 1   ┆     ┆     │
│     ┆     ┆ sae ┆     ┆     ┆     ┆     ┆     ┆     ┆ (SA ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆ eac ┆     ┆ y   ┆ emb ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 656 ┆     ┆     ┆ (SA ┆     ┆     ┆ ati ┆ (SA ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8_r ┆ ica ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆ E03 ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ Kit ┆ io. ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 002 ┆     ┆     ┆ E03 ┆     ┆     ┆ on  ┆ E03 ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ l   ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 527 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 252 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆ sam ┆     ┆     ┆ 246 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 3;3 ┆     ┆     ┆ 252 ┆     ┆     ┆ in  ┆ 252 ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7)  ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ 268 ┆     ┆     ┆     ┆     ┆     ┆ 875 ┆     ┆     ┆ 7)  ┆     ┆     ┆ Can ┆ 7)  ┆     ┆ 268 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pli ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ SO_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆ 821 ┆     ┆     ┆ vs  ┆     ┆     ┆ cer ┆ vs  ┆     ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hct ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     ┆     ┆ No  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆ 478 ┆     ┆     ┆ HCT ┆     ┆     ┆ Cel ┆ HCT ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆ l   ┆ 116 ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _dm ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DM ┆     ┆     ┆     ┆     ┆     ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DM ┆     ┆     ┆ Bio ┆ _DM ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ so_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ SO_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SO_ ┆     ┆     ┆ log ┆ SO_ ┆     ┆ _DM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ no_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ No  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SO_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ No  ┆     ┆     ┆ y   ┆ No  ┆     ┆ SO_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eas ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ Usi ┆ hea ┆     ┆ Wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆ tsh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tsh ┆     ┆     ┆ ng  ┆ tsh ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆ a   ┆ ock ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Concat dataframe (RNA-seq only)

In [62]:
df_rna_seq_true_no_control: list[pl.DataFrame | None] = [
    paired_metadata_df_gse228346_rna_seq,
    paired_metadata_df_gse255207,
    paired_metadata_df_gse270672,
    paired_metadata_df_gse197993,
    paired_metadata_df_gse137559,
    paired_metadata_df_gse130892_rna_seq,
    paired_metadata_df_gse132447_rna_seq,
    paired_metadata_df_gse289231,
    paired_metadata_df_gse279569,
    paired_metadata_df_gse285497,
    paired_metadata_df_gse279445,
    paired_metadata_df_gse229915,
    paired_metadata_df_gse242710,
    paired_metadata_df_gse221579,
    paired_metadata_df_gse164834,
    paired_metadata_df_gse182960,
    paired_metadata_df_gse198441,
    paired_metadata_df_gse164846,
    paired_metadata_df_gse149797,
    paired_metadata_df_gse123980_rna_seq,
    paired_metadata_df_gse115731,
    paired_metadata_df_gse100408
]

rna_seq_true_no_control: list[pl.DataFrame] = [
    df for df in df_rna_seq_true_no_control if df is not None
]

In [63]:
rna_seq_true_no_control = pl.concat(rna_seq_true_no_control, how="diagonal")

rna_seq_true_no_control.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_true_no_control_metadata_{execute_date}.tsv",
    separator="\t"
)