# BioProject (and BioStudies) Metadata validated and modified process (bulk RNA-seq)

&nbsp;

- ヒトの熱ストレスに関連するRNA-Seqにおいて, GEOには登録されていないが、BioProjectに登録されているデータのメタデータを収集,判断する
- 以下のようなクエリで検索 (2026-05-02 update)
- `Search ((((((((((heat stress) OR heat shock) OR high temperature stress) OR hyperthermia) OR heat stroke)) AND "homo sapiens"[Organism]) AND "transcriptome gene expression"[Filter]) AND "bioproject sra"[Filter])) NOT "bioproject gds"[Filter]`
- ID-list: [../../Data/curation/accession_idlist/idlist_bioproject/bioproject_result_260502.txt](../../Data/curation/accession_idlist/idlist_bioproject/bioproject_result_260502.txt)
- 他のクエリでの結果や、manual curation での結果もこちらに統合 (2026-05-03)
- Gene Expression Omnibus (GEO) の PEP format で得られるメタデータにのみあるカラム `sample_molecule_ch1` (Total RNA などの情報) や、`genotype` の情報もマニュアルで追加

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

#### PRJNA1000718 (SINGLE) (RNA-seq)

- validate date 2025-05-18
- [Molecular choreography to acute heat exposure in a simulated extreme high temperature environment](https://doi.org/10.21203/rs.3.rs-3615487/v1)
- おそらくResearch Square 由来のデータ
- 使えそうだな... と思ったが、メタデータに詳細な実験条件と、どのデータがどの条件に合致するか不明なので今回は収集しない

In [4]:
PRJNA1000718 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJNA1000718_metadata.tsv",
    separator="\t"
)

# display(PRJNA1000718)

&nbsp;

#### PRJDB12381 (DRA012808) (SINGLE) (RNA-seq)

- validate date: 2026-05-02
- [Remarkable improvement in detection of readthrough downstream-of-gene transcripts by semi-extractable RNA-sequencing](https://doi.org/10.1261/rna.079469.122)
- Book (Japanese): [“情報”から“マテリアル”へ　ノンコーディングRNA研究](https://www.yodosha.co.jp/yodobook/book/9784758104210/)
- 論文中では `DRA012808` というアクセッション番号に記載がないが、おそらくこの論文に該当?
- コントロールデータが登録されていなかったため、今回は泣く泣く収集しない

In [5]:
# PRJDB12381 = pl.read_csv(
#     "../../Data/metadata/metadata_bioproject/PRJDB12381.metadata.tsv",
#     separator='\t'
# ).filter(
#     pl.col("sample_description").str.contains("Heat stressed ") # heat-stress condition data is performed on HAP1 cells
# )

# PRJDB12381_filtered = PRJDB12381[[s.name for s in PRJDB12381 if not (s.null_count() == PRJDB12381.height)]]

# pl.Config.set_tbl_rows(8)
# display(PRJDB12381_filtered)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# 1． PRJDB12380 (DRA012807) (RNA-seq) (SINGLE)

- ✅ DOWNLOAD (yone-hdd-fantom6)
- ✅ TRIMMING (yone-hdd-fantom6)
- ✅ QUANTIFICATION. (yone-hdd-fantom6)

&nbsp;

- Date of data discovery: 2026-03-14
- validate date: 2026-05-02
- [Remarkable improvement in detection of readthrough downstream-of-gene transcripts by semi-extractable RNA-sequencing](https://doi.org/10.1261/rna.079469.122)
- Book (Japanese): [“情報”から“マテリアル”へ　ノンコーディングRNA研究](https://www.yodosha.co.jp/yodobook/book/9784758104210/)
- `MATERIALS AND METHODS;Cell culture and induction of osmotic stress; ... To induce heat stress (HS), HAP1 cells were exposed at 42°C for 2 h. For aliphatic alcohol treatment, the indicated concentrations of 1,6-hexanediol dissolved in culture medium were added to cells post-OS treatment, followed by incubation for 5 min at room temperature. ...`

In [6]:
PRJDB12380 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB12380.metadata.tsv", # metadata from iseq
    separator='\t'
).filter(
    pl.col("sample_description").str.contains("HAP1") # heat-stress condition data is performed on HAP1 cells
).sort(
    "run_accession",
    descending=False
).with_columns(
    pl.lit("TruSeq Stranded mRNA Library Prep Kit (without poly(A) selection)").alias("rna_library"), # please see "MATERIALS AND METHODS" section in the reference paper
    pl.lit("https://doi.org/10.1261/rna.079469.122").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time"),
    pl.lit("37 C").alias("control treatment temperature"),
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "MATERIALS AND METHODS" section in the reference paper
    pl.lit("WT").alias("genotype") 
).drop(
    drop_columns_list
)


PRJDB12380_filtered = PRJDB12380[[s.name for s in PRJDB12380 if not (s.null_count() == PRJDB12380.height)]]

# PRJDB12380_filtered.write_csv(
#     "../Data/metadata/metadata_bioproject/PRJDB12380_modified_metadata.tsv",
#     separator="\t"
# )

# display(PRJDB12380_filtered)

In [7]:
defined_pairs_prjdb12380 = [
    ("DRR321028", "DRR321026"), # Heat stressed and recovered WT HAP1 RNA prepared by conventional method vs. WT HAP1 RNA prepared by conventional method
    ("DRR321029", "DRR321027")  # Heat stressed and recovered WT HAP1 RNA prepared by improved method vs. WT HAP1 RNA prepared by improved method
]

paired_metadata_df_prjdb12380 = create_paired_metadata(
    combined_df=PRJDB12380_filtered,
    defined_sample_pairs=defined_pairs_prjdb12380,
    sample_id_column_name="run_accession"
)

if paired_metadata_df_prjdb12380 is not None:
    paired_metadata_df_prjdb12380.write_csv(
        "../../Data/metadata/metadata_paired/PRJDB12380_paired_metadata.tsv",
        separator="\t"
    )
    display(paired_metadata_df_prjdb12380)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ experimen ┆ sample_ac ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ t_title   ┆ cession   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR321028 ┆ DRR321026 ┆ Illumina  ┆ SAMD00407 ┆ … ┆ 120 min.  ┆ 37 C      ┆ total RNA ┆ WT       │
│           ┆           ┆ HiSeq     ┆ 109 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆ SAMD00407 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆ 107       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00407 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 109 vs    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00407 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 107       ┆           ┆   ┆           ┆           ┆           ┆          │
│ DRR321029 ┆ DRR321027 ┆ Illumina  ┆ SAMD00407 ┆ … ┆ 120 min.  ┆ 37 C      ┆ total RNA ┆ WT       │
│           ┆           ┆ HiSeq     ┆ 110 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆ SAMD00407 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆ 108       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00407 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 110 vs    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00407 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 108       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. PRJDB13489 (SINGLE)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-18
- [Lack of Hikeshi activates HSF1 activity under normal conditions and disturbs the heat-shock response](https://doi.org/10.26508/lsa.202101241)
- おそらく上記の論文が元になっている (この論文にアクセッション番号:DRA013986の記載アリ)
- `Hikeshi` タンパク質について調査している論文
- このプロジェクトは [hTERT-RPE1 cell](https://www.atcc.org/products/crl-4000) に関するデータ
- 明確に以下のような記述が論文中にあるため、収集する
- `Cells and cell cultures Hikeshi-KO HeLa and hTERT-RPE1 cells were previously generated with the CRISPR–Cas9 system (Rahman et al, 2017). HeLa cells stably expressing EGFP-NLS-Hsc70 were previously established by transfection of the pEF5/FRT/EGFP-GW/NLS-Hsc70 plasmid (Rahman et al, 2017).`

&nbsp;

### ERROR

- salmonで発現定量をしている際、以下のようなエラーが発生
- 実行コマンド

```
cwltool --debug --outdir ./HS_human_salmon_quant/HS_human_salmon_quant_se_bioproject/ --cachedir ./cwl_cache/ ./Workflow/03_salmon_quant_subworkflow_se.cwl ./config/salmon/salmon_se_prjdb13489.yml
```

```bash
[2025-05-25 04:31:04.338] [jointLog] [warning] salmon was only able to assign 5 fragments to transcripts in the index, but the minimum number of required assigned fragments (--minAssignedFrags) was 10. This could be indicative of a mismatch between the reference and sample, or a very bad sample.  You can change the --minAssignedFrags parameter to force salmon to quantify with fewer assigned fragments (must have at least 1).
```

- **緊急的に `--minAssignedFrags` を加え、値を1に設定 (デフォルトは10) した `Tools/05_salmon_quant_se_assigncluster.cwl`を作成して実行*  したものの、`processed 16500001 fragments` の部分が異常に早く終わるなど、これまであまり見なかった挙動が見られた
- 一応 発現定量後の情報を見てみたが、ほぼデータがないような変なファイルも入っていた...
- FASTQのファイル取得に失敗したのか？ と思いきや、`iseq`で取得したデータを見てみると、`fastq_bytes` が `307`だったり変なファイルがある...

&nbsp;

- **一旦、このバージョンで定量した結果を残しておき、`--minAssignedFrags` が 10のこれまでのファイルを処理してきたもので処理できないものは外す方針**

In [8]:
PRJDB13489 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB13489_metadata.tsv", # metadata from iseq
    separator='\t'
).with_columns(
    pl.lit("SureSelect Strand-Specific RNA Library Preparation Kits").alias("rna_library"), # please see "Materials and Methods" section in the reference paper
    pl.lit("https://doi.org/10.26508/lsa.202101241").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "Materials and Methods" section in the reference paper
    pl.lit("hTERT-RPE1").alias("cell_line"),

    # add genotype
    pl.when(
        pl.col("sample_title").str.contains("Hikeshi-KO")
    ).then(
        pl.lit("HIKESHI knockout")
    ).otherwise(
        pl.lit("WT")
    ).alias("genotype")
).sort(
    "run_accession",
    descending=False
).drop(
    drop_columns_list
)

PRJDB13489_filtered = PRJDB13489[[s.name for s in PRJDB13489 if not (s.null_count() == PRJDB13489.height)]]

PRJDB13489_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB13489_modified_metadata.tsv",
    separator="\t"
)

# display(PRJDB13489_filtered)

In [9]:
defined_pairs_prjdb13489 = [
    ("DRR361197", "DRR361194"), # hTERT-RPE1 cells under heat-shock condition vs hTERT-RPE1 cells under nonstressed condition
    # ("DRR361200", "DRR361194"), # hTERT-RPE1 cells during recovery for 1.5h from heat stress vs hTERT-RPE1 cells under nonstressed condition
    # ("DRR361203", "DRR361194"), # hTERT-RPE1 cells during recovery for 3h from heat stress vs hTERT-RPE1 cells under nonstressed condition
    ("DRR361206", "DRR361194"), # hTERT-RPE1 cells during recovery for 24h from heat stress vs hTERT-RPE1 cells under nonstressed condition
    ("DRR361198", "DRR361195"), # Hikeshi-KO hTRET-RPE1 cells (R630_1) under heat-shock condition vs Hikeshi-KO hTRET-RPE1 cells (R630_1) under nonstressed condition
    ("DRR361199", "DRR361196"), # Hikeshi-KO hTRET-RPE1 cells (R630_2) under heat-shock condition vs Hikeshi-KO hTRET-RPE1 cells (R630_2) under nonstressed condition
    # ("DRR361201", "DRR361195"), # Hikeshi-KO hTRET-RPE1 cells (R630_1) during recovery for 1.5h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_1) under nonstressed condition
    # ("DRR361202", "DRR361196"), # Hikeshi-KO hTRET-RPE1 cells (R630_2) during recovery for 1.5h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_2) under nonstressed condition
    ("DRR361204", "DRR361195"), # Hikeshi-KO hTRET-RPE1 cells (R630_1) during recovery for 3h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_1) under nonstressed condition
    ("DRR361205", "DRR361196"), # Hikeshi-KO hTRET-RPE1 cells (R630_2) during recovery for 3h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_2) under nonstressed condition
    ("DRR361207", "DRR361195"), # Hikeshi-KO hTRET-RPE1 cells (R630_1) during recovery for 24h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_1) under nonstressed condition
    ("DRR361208", "DRR361196")  # Hikeshi-KO hTRET-RPE1 cells (R630_2) during recovery for 24h from heat stress vs Hikeshi-KO hTRET-RPE1 cells (R630_2) under nonstressed condition
]

paired_metadata_df_prjdb13489 = create_paired_metadata(
    combined_df=PRJDB13489_filtered,
    defined_sample_pairs=defined_pairs_prjdb13489,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_prjdb13489 is not None:
    paired_metadata_df_prjdb13489.write_csv(
        "../../Data/metadata/metadata_paired/prjdb13489_paired_metadata.tsv",
        separator='\t'
    )
    
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_prjdb13489)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (8, 49)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR361197 ┆ DRR361194 ┆ DRR361197 ┆ Illumina  ┆ … ┆ 60 min.   ┆ 37 C (inf ┆ total RNA ┆ WT       │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ DRR361194 ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00467 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 877 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00467 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 874       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ DRR361208 ┆ DRR361196 ┆ DRR361208 ┆ Illumina  ┆ … ┆ 60 min.   ┆ 37 C (inf ┆ total RNA ┆ HIKESHI  │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆ knockout │
│           ┆           ┆ DRR361196 ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00467 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 888 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00467 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 876       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

## 3. PRJDB3761 (SINGLE) 

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-05
- [Lack of Hikeshi activates HSF1 activity under normal conditions and disturbs the heat-shock response](https://doi.org/10.26508/lsa.202101241)
- おそらく上記の論文が元になっている (この論文にアクセッション番号:DRA003217の記載アリ)
- `Hikeshi` タンパク質について調査している論文
- 明確に以下のような記述が論文中にあるため、収集する
- `Cells were cultured at 37°C with 5% CO2 in DMEM supplemented with 10% FBS. For heat-shock treatment, cells were incubated for 1 h at 43°C with prewarmed DMEM supplemented with 10% FBS and 20 mM HEPES (pH 7.3) in a water bath.`

In [10]:
PRJDB3761 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB3761_metadata.tsv", # metadata from iseq
    separator='\t'
).with_columns(
    pl.lit("SureSelect Strand-Specific RNA Library Preparation Kits").alias("rna_library"), # please see "Materials and Methods" section in the reference paper
    pl.lit("https://doi.org/10.26508/lsa.202101241").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "Materials and Methods" section in the reference paper
    pl.col("cell_line").fill_null(pl.lit("HeLa")), # fill missing cell_line (all samples are HeLa cells)
    
    # add genotype
    pl.when(
        pl.col("sample_description").str.contains("siRNA")
    ).then(
        pl.lit("HIKESHI knockdown")
    ).when(
        pl.col("sample_description").str.contains("H630")
    ).then(
        pl.lit("HIKESHI knockout")
    ).otherwise(
        pl.lit("WT")
    ).alias("genotype")

).filter(
    ~(pl.col("sample_title").str.contains(r'EGFP-')) # filtered GFP expression data
).sort(
    "run_accession",
    descending=False
).drop(
    drop_columns_list
)

PRJDB3761_filtered = PRJDB3761[[s.name for s in PRJDB3761 if not (s.null_count() == PRJDB3761.height)]]

PRJDB3761_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB3761_modified_metadata.tsv",
    separator="\t"
)

# display(PRJDB3761_filtered)

In [11]:
defined_pairs_prjdb3761 = [
    ("DRR031462", "DRR031460"), # Heat shocked (control siRNA) vs Normal condtion (control siRNA)
    ("DRR031463", "DRR031461"), # Heat shocked (Hikeshi siRNA) vs Normal condtion (Hikeshi siRNA)
    ("DRR031464", "DRR031460"), # Release 1.5hr after heat shock (control siRNA) vs Normal condtion (control siRNA)
    ("DRR031465", "DRR031461"), # Release 1.5hr after heat shock (Hikeshi siRNA) vs Normal condtion (Hikeshi siRNA)
    ("DRR031466", "DRR031460"), # Release 3hr after heat shock (control siRNA) vs Normal condtion (control siRNA)
    ("DRR031467", "DRR031461"), # Release 3hr after heat shock (Hikeshi siRNA) vs Normal condtion (Hikeshi siRNA)
    ("DRR093588", "DRR093585"), # HeLa cells under heat stress vs HeLa cells under normal condition
    ("DRR093591", "DRR093585"), # HeLa cells during recovery for 1.5h from heat stress vs HeLa cells under normal condition
    ("DRR093594", "DRR093585"), # HeLa cells during recovery for 3h from heat stress vs HeLa cells under normal condition
    ("DRR093589", "DRR093586"), # Hikeshi-KO HeLa cells under heat stress vs Hikeshi-KO HeLa cells under normal condition
    ("DRR093590", "DRR093587"), # Hikeshi-KO HeLa cells under heat stress vs Hikeshi-KO HeLa cells under normal condition
    ("DRR093592", "DRR093586"), # Hikeshi-KO HeLa cells during recovery for 1.5h from heat stress vs Hikeshi-KO HeLa cells under normal condition
    ("DRR093593", "DRR093587"), # Hikeshi-KO HeLa cells during recovery for 1.5h from heat stress vs Hikeshi-KO HeLa cells under normal condition
    ("DRR093595", "DRR093586"), # Hikeshi-KO HeLa cells during recovery for 3h from heat stress vs Hikeshi-KO HeLa cells under normal condition
    ("DRR093596", "DRR093587")  # Hikeshi-KO HeLa cells during recovery for 3h from heat stress vs Hikeshi-KO HeLa cells under normal condition
]

paired_metadata_df_prjdb3761 = create_paired_metadata(
    combined_df=PRJDB3761_filtered,
    defined_sample_pairs=defined_pairs_prjdb3761,
    sample_id_column_name="accession" # default value, but specified to clarify
)

# Guard against None so that write_csv is called only on a DataFrame
if paired_metadata_df_prjdb3761 is not None:
    paired_metadata_df_prjdb3761.write_csv(
        "../../Data/metadata/metadata_paired/prjdb3761_paired_metadata.tsv",
        separator="\t"
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_prjdb3761)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (15, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR031462 ┆ DRR031460 ┆ DRR031462 ┆ Illumina  ┆ … ┆ 60 min.   ┆ 37 C (inf ┆ total RNA ┆ HIKESHI  │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆ knockdow │
│           ┆           ┆ DRR031460 ┆ 2000 sequ ┆   ┆           ┆           ┆           ┆ n        │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00027 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 695 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00027 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 693       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ DRR093596 ┆ DRR093587 ┆ DRR093596 ┆ Illumina  ┆ … ┆ 60 min.   ┆ 37 C (inf ┆ total RNA ┆ HIKESHI  │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆ knockout │
│           ┆           ┆ DRR093587 ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00081 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 497 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Illumina  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ HiSeq     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2500 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing of ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00081 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 488       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

#### PRJDB9865 (SINGLE) CAGE-seq

- validate date 2025-05-18
- [Heat shock induces the nuclear accumulation of YAP1 via SRC](https://doi.org/10.1016/j.yexcr.2020.112439)
- 処理を[12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に移動

#### PRJDB7415 (SINGLE) NO DOWNLOAD

- validate date 2025-05-18
- validate date 2025-11-19
- [LncRNA‐dependent nuclear stress bodies promote intron retention through SR protein phosphorylation
](https://doi.org/10.15252/embj.2019102729)
- 論文を発見
- 北海道大学 (現 大阪大学) の廣瀬先生 (https://hirose-lab.com/publications/)
- メタデータを見ると全てのサンプルが `heatshock-exposed` であり、コントロール条件のデータはなさそうなので、残念ながら今回は使用しない

In [12]:
# PRJDB7415 = pl.read_csv(
#     "../../Data/metadata/metadata_bioproject/PRJDB7415_metadata.tsv",
#     separator="\t"
# )

# display(PRJDB7415)

#### PRJDB3999 (RNA-seq) NO DOWNLOAD

- validate date: 2026-05-02
- メタデータが `iseq` コマンドで入手できない
- おそらく以下の論文に関連?
- [Identification of a heat-inducible novel nuclear body containing the long noncoding RNA MALAT1](https://doi.org/10.1242/jcs.253559)
- データをうまく入手できない
- https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SAMD00032086&o=acc_s%3Aa
- SRA run selector に登録されていなかったため、今回は収集しない
- [ENA](https://www.ebi.ac.uk/ena/browser/view/PRJDB3999) を確認しても、`No public data is associated with this project` のため、収集しない

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. PRJEB5979 (ERP5426) (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2025-05-18
- [Proteotoxic stress reprograms the chromatin landscape of SUMO modification](https://pmc.ncbi.nlm.nih.gov/articles/PMC6707813/)
- [E-MTAB-2349](https://www.ebi.ac.uk/biostudies/ArrayExpress/studies/E-MTAB-2349?query=E-MTAB-2349) のデータ
- BioStudiesでも検索できたデータ
- 熱ストレス時のデータと、コントロールのデータが存在するので収集する

In [13]:
PRJEB5979 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJEB5979_metadata.tsv",
    separator="\t"
).with_columns(
    pl.lit("Illumina protocol").alias("rna_library"), # add rna_library column from article
    pl.lit("https://doi.org/10.1126/scisignal.aaa2213").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("240 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "Materials and Methods" section in the reference paper
    pl.lit("WT").alias("genotype") # no genotype information in the reference paper
).drop(
    drop_columns_list
)

PRJEB5979_filtered = PRJEB5979[[s.name for s in PRJEB5979 if not (s.null_count() == PRJEB5979.height)]]

PRJEB5979_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJEB5979_modified_metadata.tsv",
    separator="\t"
)

# display(PRJEB5979_filtered)

In [14]:
defined_pairs_prjeb5979 = [
    ("ERR468937", "ERR468934"), # E-MTAB-2349:HS_1 vs E-MTAB-2349:UT_1 (UT: untreated)
    ("ERR468932", "ERR468935"), # E-MTAB-2349:HS_2 vs E-MTAB-2349:UT_2 (UT: untreated)
    ("ERR468933", "ERR468936")  # E-MTAB-2349:HS_3 vs E-MTAB-2349:UT_3 (UT: untreated)
]

paired_metadata_df_prjeb5979 = create_paired_metadata(
    combined_df=PRJEB5979_filtered,
    defined_sample_pairs=defined_pairs_prjeb5979,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_prjeb5979 is not None:
    paired_metadata_df_prjeb5979.write_csv(
        "../../Data/metadata/metadata_paired/prjeb5979_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_prjeb5979)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 58)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERR468937 ┆ ERR468934 ┆ ERR468937 ┆ Illumina  ┆ … ┆ 240 min.  ┆ 37 C (inf ┆ total RNA ┆ WT       │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ ERR468934 ┆ 2000      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ paired    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ end seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing:    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ heat      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ shock     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SUMO-2    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ RNA-seq   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ERR468933 ┆ ERR468936 ┆ ERR468933 ┆ Illumina  ┆ … ┆ 240 min.  ┆ 37 C (inf ┆ total RNA ┆ WT       │
│           ┆           ┆ vs        ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ ERR468936 ┆ 2000      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ paired    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ end seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing:    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ heat      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ shock     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SUMO-2    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ RNA-seq   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# BioStudies

- GEOに登録されていない、かつBioProjectの検索でうまくヒットしないものをここから探索
- 以下のリンクで検索
- [BioStudies search result](https://www.ebi.ac.uk/biostudies/ArrayExpress/studies?facet.study_type=rna-seq+of+coding+rna&facet.study_type=rna-seq+of+non+coding+rna&facet.study_type=rna-seq+of+total+rna&facet.experimental_design=n%2Fa&facet.experimental_design=stimulus+or+stress+design&facet.organism=homo+sapiens&facet.technology=sequencing+assay&facet.assay_by_molecule=rna+assay&facet.raw=true&facet.link_type=biostudies&facet.link_type=ena&query=heat+shock&sortBy=release_date&sortOrder=descending)
- 以下の2つのファイルは`iseq`でダウンロードしたが、うまくダウンロードできていない (2025-05-25)
- [ENAのホームページ: https://www.ebi.ac.uk/ena/browser/view/PRJEB44754](https://www.ebi.ac.uk/ena/browser/view/PRJEB44754)から直接ダウンロード (2025-12-30)

&nbsp;

## 5. PRJEB44754 (ERP128835) (PAIRED)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-18
- validate date: 2025-12-31
- validate date: 2026-05-03
- BioProject の以下のようなクエリでヒットすることを確認 (2026-05-03)
- `((((((("heat stress"[All Fields] OR "heat shock"[All Fields]) OR "high temperature stress"[All Fields]) OR "hyperthermia"[All Fields]) OR "heat stroke"[All Fields]) AND "homo sapiens"[Organism]) AND "bioproject sra"[Filter]) AND "other"[Project Data Type]) NOT "bioproject gds"[Filter]`

&nbsp;

- [Loss of regulation of protein synthesis and turnover underpins an attenuated stress response in senescent human mesenchymal stem cells](https://doi.org/10.1073/pnas.2210745120)
- おそらく上記の論文由来 (筆頭著者、論文内に `E-MTAB-10415` の記載あり)
- `Comparisons were made between donor-matched proliferating and senescent primary hMSCs, under control conditions and when subjected to a 2-h heat shock treatment at 42 °C and following a 24-h recovery period.`
- iseqから取得したメタデータに詳細な実験条件の記載がなかったため、ENAのデータの`BioSample`を検索し、`stimulus` 欄を探しペアを作成する
- ENA browser の `Stimulus`, `Individual`, `Passage`の3つの項目からペアを作成する

&nbsp;

- ENAから直接ダウンロード (2025-12-31)
- このプロジェクトのうち、`ERR5881990`, `ERR5882002`, `ERR5881993`, `ERR5881995`, `ERR5881994`, `ERR5882005` は例えば以下のようなエラーが出たので`fastp`の処理を飛ばした

&nbsp;

```bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[22:01:42] start to load data of read1 
[22:01:42] start to load data of read2 
[22:01:52] Read1: loaded 1M reads 
[22:01:52] Read2: loaded 1M reads 
[22:02:02] Read1: loaded 2M reads 
[22:02:02] Read2: loaded 2M reads 
[22:02:13] Read2: loaded 3M reads 
[22:02:13] Read1: loaded 3M reads 
[22:02:24] Read1: loaded 4M reads 
[22:02:24] Read2: loaded 4M reads 
[22:02:35] Read2: loaded 5M reads 
[22:02:35] Read1: loaded 5M reads 
ERROR: sequence and quality have different length:
@ERR5881990.5749217 K00311:137:HKNFLBBXY:6:1207:28483:306JJJJJJJ1C1:137:H9JJJJFFJF5JJJJJJGGCA2
TTTTCA7<F-FJ<<7FAJ--F-7--<7--7--77-77-ATGGAA
+
31382TAAGGTTATTATTGGAAACATTACTTTGAGTGCAGAJJFJ<AJAAJJJFFFFFJFAJFJF16/2
ERROR: sequence and quality have different length
```

&nbsp;

In [15]:
PRJEB44754 = pl.read_csv(
    "../../Data/metadata/metadata_biostudies/ERP128835.metadata.tsv",
    separator="\t"
).with_columns(
    pl.lit("TruSeq Stranded mRNA assay").alias("rna_library"), # add rna_library column from ENA webpage
    pl.lit("https://doi.org/10.1073/pnas.2210745120").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature"), # add control temperature column
    pl.lit("polyA RNA").alias("sample_molecule_ch1"), # please see "Materials and Methods" section in the reference paper
    pl.lit("WT").alias("genotype") # no genotype information in the reference paper
).drop(
    drop_columns_list
)

PRJEB44754_filtered = PRJEB44754[[s.name for s in PRJEB44754 if not (s.null_count() == PRJEB44754.height)]]

PRJEB44754_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJEB44754_modified_metadata.tsv",
    separator="\t"
)

# display(PRJEB44754_filtered)

In [16]:
# failed trimming run
# ERR5881990
# ERR5882002
# ERR5881993
# ERR5881995
# ERR5881994
# ERR5882005


defined_pairs_prjeb44754 = [
    # Individual:TH223, Early passage
    # ("ERR5881991", "ERR5881993"), # heat-shock vs none
    # ("ERR5881992", "ERR5881993"), # heat-shock vs none
    # Individual:TH223, Late passage
    ("ERR5882000", "ERR5882007"), # heat-shock vs none
    # Individual:TH270, Early passage
    # ("ERR5881989", "ERR5881995"), # heat-shock vs none
    # Individual:TH270, Late passage
    ("ERR5881999", "ERR5882003"), # heat-shock vs none
    # Individual:TH296, Early passage data is None
    # Individual:TH296, Late passage data
    ("ERR5882001", "ERR5882004"), # heat-shock vs none
    # Individual:TH305, Early passage
    # ("ERR5881988", "ERR5881994"), # heat-shock vs none
    # Individual:TH305, Late passage
    ("ERR5881998", "ERR5882006"), # heat-shock vs none
    # Individual:WH176, Early passage
    # ("ERR5881990", "ERR5881996"), # heat-shock vs none
    # # Individual:WH176, Late passage
    # ("ERR5882002", "ERR5882005")  # heat-shock vs none
]

paired_metadata_df_prjeb44754 = create_paired_metadata(
    combined_df=PRJEB44754_filtered,
    defined_sample_pairs=defined_pairs_prjeb44754,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_prjeb44754 is not None:
    paired_metadata_df_prjeb44754.write_csv(
        "../../Data/metadata/metadata_paired/prjeb44754_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_prjeb44754)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 61)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERR588200 ┆ ERR588200 ┆ ERR588200 ┆ Illumina  ┆ … ┆ 120 min.  ┆ 37 C (inf ┆ polyA RNA ┆ WT       │
│ 0         ┆ 7         ┆ 0 vs ERR5 ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ 882007    ┆ 4000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ RNA-seq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ of early- ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ and late- ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ passage   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ human mes ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ enchymal  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ stem      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ cells (5  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ donors,   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ donor-mat ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ched)     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ with and  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ without   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ treatment ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ with 2    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ hours of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 42        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ degrees C ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ heat      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ shock     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ERR588199 ┆ ERR588200 ┆ ERR588199 ┆ Illumina  ┆ … ┆ 120 min.  ┆ 37 C (inf ┆ polyA RNA ┆ WT       │
│ 8         ┆ 6         ┆ 8 vs ERR5 ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ 882006    ┆ 4000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ RNA-seq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ of early- ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ and late- ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ passage   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ human mes ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ enchymal  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ stem      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ cells (5  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ donors,   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ donor-mat ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ched)     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ with and  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ without   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ treatment ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ with 2    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ hours of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 42        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ degrees C ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ heat      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ shock     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### PRJEB73803 (ERP158539) (PAIRED) 4sU-seq

- validate date: 2025-05-18
- [E-MTAB-13903](https://www.ebi.ac.uk/biostudies/ArrayExpress/studies/E-MTAB-13903?query=E-MTAB-13903)
- 論文は見つけられなかったが、熱ショックとコントロールのデータが登録されているので念の為収集する
- `control exposed to 200nM 4sU` と `HS-treated exposed to 200nM 4sU` の2つがある
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

&nbsp;

&nbsp;

## BioProject Manual Curation (2026~)

- マニュアルで収集した BioProject のデータ (GEOにはない)

&nbsp;

## 6. PRJEB64703 (RNA-seq)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- 以下のクエリでヒットしたデータ (2026-05-03)
- `(((((((((("heat stress") OR "heat shock") OR "high temperature stress") OR "hyperthermia") OR "heat stroke")) AND "homo sapiens"[Organism]) AND "bioproject sra"[Filter]) AND "other"[Project Data Type])) NOT "bioproject gds"[Filter]`
- [ENA Browser: PRJEB64703](https://www.ebi.ac.uk/ena/browser/view/PRJEB64703)
- [BioRxiv: The piggyBac derived transposase 5 (PGBD5) can interact with human piggyBac-like elements](https://doi.org/10.1101/2025.07.31.667870)
- 同じ論文由来の ChIP-seq のデータは、熱ストレス条件下ではない
- `For the heat shock, cells were incubated for 3 hours at 42°C and with 5% CO2.`

In [17]:
PRJEB64703 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/PRJEB64703.metadata.tsv",
    separator='\t'
).with_columns(
    pl.lit("NEBNext Ultra II RNA Library Prep Kit for Illumina").alias("rna_library"), # please see "Materials and Methods" section in the reference paper
    pl.lit("https://doi.org/10.1101/2025.07.31.667870").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("180 min.").alias("stress treatment time"),
    pl.lit("37 C (inferred)").alias("control treatment temperature"),
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "Materials and Methods" section in the reference paper
    pl.lit("WT").alias("genotype"), # no genotype information in the reference paper
    pl.lit("HeLa").alias("cell_line")
).drop(
    drop_columns_list
)

PRJEB64703_filtered = PRJEB64703[[s.name for s in PRJEB64703 if not (s.null_count() == PRJEB64703.height)]]

# pl.Config.set_tbl_rows(8)
# display(PRJEB64703_filtered)

In [18]:
defined_pairs_prjeb64703 = [
    ("ERR11785749", "ERR11785751"), # HeLa-HS1 vs. HeLa-control1
    ("ERR11785750", "ERR11785752")  # HeLa-HS2 vs. HeLa-control2
]

paired_metadata_df_prjeb64703 = create_paired_metadata(
    combined_df=PRJEB64703_filtered,
    defined_sample_pairs=defined_pairs_prjeb64703,
    sample_id_column_name="accession"
)

if paired_metadata_df_prjeb64703 is not None:
    paired_metadata_df_prjeb64703.write_csv(
        "../../Data/metadata/metadata_paired/prjeb64703_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_prjeb64703)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 64)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERR117857 ┆ ERR117857 ┆ ERR117857 ┆ Illumina  ┆ … ┆ 180 min.  ┆ 37 C (inf ┆ total RNA ┆ WT       │
│ 49        ┆ 51        ┆ 49 vs ERR ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ 11785751  ┆ 4000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing    ┆   ┆           ┆           ┆           ┆          │
│ ERR117857 ┆ ERR117857 ┆ ERR117857 ┆ Illumina  ┆ … ┆ 180 min.  ┆ 37 C (inf ┆ total RNA ┆ WT       │
│ 50        ┆ 52        ┆ 50 vs ERR ┆ HiSeq     ┆   ┆           ┆ erred)    ┆           ┆          │
│           ┆           ┆ 11785752  ┆ 4000 sequ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ encing    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 7. PRJDB9451 (DRA009793) (RNA-seq)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- Date of data discovery: 2026-03-14
- validate date: 2026-05-02

&nbsp;

- [Remarkable improvement in detection of readthrough downstream-of-gene transcripts by semi-extractable RNA-sequencing](https://doi.org/10.1261/rna.079469.122)
- このデータは、BioProject の検索でもヒットしなかった
- Book (Japanese): [“情報”から“マテリアル”へ　ノンコーディングRNA研究](https://www.yodosha.co.jp/yodobook/book/9784758104210/)
- `MATERIALS AND METHODS;Cell culture and induction of osmotic stress; ... To induce heat stress (HS), HAP1 cells were exposed at 42°C for 2 h. For aliphatic alcohol treatment, the indicated concentrations of 1,6-hexanediol dissolved in culture medium were added to cells post-OS treatment, followed by incubation for 5 min at room temperature. ...`

In [19]:
PRJDB9451 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB9451.metadata.tsv", # metadata from iseq
    separator='\t'
).filter(
    pl.col("sample_description").str.contains("HAP1") # heat-stress condition data is performed on HAP1 cells
).sort(
    "run_accession",
    descending=False
).drop(
    drop_columns_list
).with_columns(
    pl.lit("TruSeq Stranded mRNA Library Prep Kit (without poly(A) selection)").alias("rna_library"), # please see "MATERIALS AND METHODS" section in the reference paper
    pl.lit("https://doi.org/10.1261/rna.079469.122").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time"),
    pl.lit("37 C").alias("control treatment temperature"),
    pl.lit("total RNA").alias("sample_molecule_ch1"), # please see "MATERIALS AND METHODS" section in the reference paper
    pl.lit("WT").alias("genotype") 
)

PRJDB9451_filtered = PRJDB9451[[s.name for s in PRJDB9451 if not (s.null_count() == PRJDB9451.height)]]

# PRJDB9451_filtered.write_csv(
#     "../Data/metadata/metadata_bioproject/PRJDB9451_modified_metadata.tsv",
#     separator="\t"
# )

# pl.Config.set_fmt_str_lengths(200)
# display(PRJDB9451_filtered)

In [20]:
defined_pairs_prjdb9451 = [
    ("DRR214953", "DRR214951"), # HAP1 cells culture at 42 degree for 2 hours and then at 37 degree for 1 hour, Total RNAs were extracted by conventional TRIregeant protocol vs. HAP1 cells Normal culture condition, Total RNAs were extracted by conventional TRIregeant protocol
    ("DRR214954", "DRR214952")  # HAP1 cells culture at 42 degree for 2 hours and then at 37 degree for 1 hour, Total RNAs were extracted by improved TRIregeant protocol vs. HAP1 cells Normal culture condition, Total RNAs were extracted by improved TRIregeant protocol
]

paired_metadata_df_prjdb9451 = create_paired_metadata(
    combined_df=PRJDB9451_filtered,
    defined_sample_pairs=defined_pairs_prjdb9451,
    sample_id_column_name="run_accession"
)

if paired_metadata_df_prjdb9451 is not None:
    paired_metadata_df_prjdb9451.write_csv(
        "../../Data/metadata/metadata_paired/PRJDB9451_paired_metadata.tsv",
        separator="\t"
    )
    display(paired_metadata_df_prjdb9451)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ experimen ┆ sample_ac ┆ … ┆ stress    ┆ control   ┆ sample_mo ┆ genotype │
│ at_id     ┆ ntrol_id  ┆ t_title   ┆ cession   ┆   ┆ treatment ┆ treatment ┆ lecule_ch ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ time      ┆ temperatu ┆ 1         ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ re        ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR214953 ┆ DRR214951 ┆ Illumina  ┆ SAMD00209 ┆ … ┆ 120 min.  ┆ 37 C      ┆ total RNA ┆ WT       │
│           ┆           ┆ HiSeq     ┆ 816 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆ SAMD00209 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆ 814       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00209 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 816 vs    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00209 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 814       ┆           ┆   ┆           ┆           ┆           ┆          │
│ DRR214954 ┆ DRR214952 ┆ Illumina  ┆ SAMD00209 ┆ … ┆ 120 min.  ┆ 37 C      ┆ total RNA ┆ WT       │
│           ┆           ┆ HiSeq     ┆ 817 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆ SAMD00209 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆ 815       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00209 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 817 vs    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing:   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Illumina  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 3000 sequ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ encing of ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ SAMD00209 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 815       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# Concat dataframe (RNA-seq only)

In [21]:
dfs_rna_seq_bioproject_biostudies: list[pl.DataFrame | None] = [
    paired_metadata_df_prjdb12380,
    paired_metadata_df_prjdb13489,
    paired_metadata_df_prjdb3761,
    paired_metadata_df_prjeb5979,
    paired_metadata_df_prjeb44754,
    paired_metadata_df_prjeb64703,
    paired_metadata_df_prjdb9451
]

rna_seq_bioproject_biostudies: list[pl.DataFrame] = [
    df for df in dfs_rna_seq_bioproject_biostudies if df is not None
]

In [22]:
rna_seq_bioproject_biostudies = pl.concat(rna_seq_bioproject_biostudies, how="diagonal_relaxed")
rna_seq_bioproject_biostudies.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_bioproject_biostudies_metadata_{execute_date}.tsv",
    separator="\t"
)