&nbsp;

# Metadata validated and modified process (manual curation)

- ヒトの熱ストレスに関連するRNA-Seqにおいて、手動で検索したときにヒットしたデータ (GEOなどでの検索クエリではヒットしていなかった)のメタデータを整理するnotebook
- また、2025年5月以降にGEOで見つかったbulk RNA-seqのデータもこちらで処理する
- 整理する際、なぜこのようなデータフレームの処理をするのかについても記載する
- Manual Curation で収集することができたエントリーはこちらで処理している
- `GSA for Human` で発見されたデータについてもこちらに記載

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
from IPython.display import display
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(400)
pl.Config.set_tbl_cols(100)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## PRJDB3999 (RNA-seq)

- ✅ DOWNLOAD (M5 Macbook Pro + yone-hdd-fantom6)
- ✅ TRIMMING (M5 Macbook Pro + yone-hdd-fantom6)
- ✅ QUANTIFICATION (M5 Macbook Pro + yone-hdd-fantom6)

&nbsp;

- validate date: 2026-09-28
- [Identification of novel heat shock-induced long non-coding RNA in human cells](https://doi.org/10.1093/jb/mvaa126)
- [PRJDB3999](https://ddbj.nig.ac.jp/search/entry/bioproject/PRJDB3999/)
- 見逃してしまっていたデータ
- `iseq` から metadata が取得できていないので、DDBJ から `JSON` ファイルを取得
- run ごとにメタデータを取得して `concat`する方式に変更 (2 run しかないため)

In [4]:
# DRR037194
DRR037194 = pl.read_json(
    "../../Data/metadata/metadata_bioproject/DRR037194.json"
).unnest(
    "properties"
).unnest(
    "RUN_SET"
).unnest(
    "RUN"
).drop(
    "accession", "alias"
).unnest(
    "EXPERIMENT_REF"
).rename(
    {
        "identifier": "run_accession",
        "accession": "experiment_accession", # this comes from EXPERIMENT_REF, not from RUN
        "refname": "experiment_alias",
        "TITLE": "experiment_title", # same text as the TITLE of DRX033429
        "dateCreated": "first_created",
        "datePublished": "first_public",
        "dateModified": "last_updated"
    }
).with_columns(
    pl.col("run_accession").alias("accession"), # create_paired_metadata uses "accession" as the run ID
    pl.col("first_created", "first_public", "last_updated").str.slice(0, 10) # keep YYYY-MM-DD like the ENA columns
)

# dbXrefs holds the linked IDs as a list of {identifier, type, url}; turn each type into a column
DRR037194_xrefs = DRR037194.select(
    "run_accession", "dbXrefs"
).explode(
    "dbXrefs"
).unnest(
    "dbXrefs"
).pivot(
    on="type",
    index="run_accession",
    values="identifier"
).rename(
    {
        "bioproject": "study_accession",
        "biosample": "sample_accession",
        "sra-sample": "secondary_sample_accession",
        "sra-study": "secondary_study_accession",
        "sra-submission": "submission_accession"
    }
).drop(
    "sra-experiment" # already present as experiment_accession
)

DRR037194 = DRR037194.join(
    DRR037194_xrefs,
    on="run_accession",
    how="left"
).select(
    # keep the column order of PRJDB3761_modified_metadata.tsv
    "run_accession",
    "experiment_title",
    "sample_accession",
    "submission_accession",
    "last_updated",
    "secondary_study_accession",
    "status",
    "experiment_alias",
    "center_name",
    "first_created",
    "experiment_accession",
    "study_accession",
    "accession",
    "secondary_sample_accession",
    "first_public"
)

display(DRR037194)

shape: (1, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ run ┆ exp ┆ sam ┆ sub ┆ las ┆ sec ┆ sta ┆ exp ┆ cen ┆ fir ┆ exp ┆ study_ ┆ acces ┆ secon ┆ first │
│ _ac ┆ eri ┆ ple ┆ mis ┆ t_u ┆ ond ┆ tus ┆ eri ┆ ter ┆ st_ ┆ eri ┆ access ┆ sion  ┆ dary_ ┆ _publ │
│ ces ┆ men ┆ _ac ┆ sio ┆ pda ┆ ary ┆ --- ┆ men ┆ _na ┆ cre ┆ men ┆ ion    ┆ ---   ┆ sampl ┆ ic    │
│ sio ┆ t_t ┆ ces ┆ n_a ┆ ted ┆ _st ┆ str ┆ t_a ┆ me  ┆ ate ┆ t_a ┆ ---    ┆ str   ┆ e_acc ┆ ---   │
│ n   ┆ itl ┆ sio ┆ cce ┆ --- ┆ udy ┆     ┆ lia ┆ --- ┆ d   ┆ cce ┆ str    ┆       ┆ essio ┆ str   │
│ --- ┆ e   ┆ n   ┆ ssi ┆ str ┆ _ac ┆     ┆ s   ┆ str ┆ --- ┆ ssi ┆        ┆       ┆ n     ┆       │
│ str ┆ --- ┆ --- ┆ on  ┆     ┆ ces ┆     ┆ --- ┆     ┆ str ┆ on  ┆        ┆       ┆ ---   ┆       │
│     ┆ str ┆ str ┆ --- ┆     ┆ sio ┆     ┆ str ┆     ┆     ┆ --- ┆        ┆       ┆ str   ┆       │
│     ┆     ┆     ┆ str ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ str ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJDB3 ┆ DRR03 ┆ DRS09 ┆ 2019- │
│ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ 999    ┆ 7194  ┆ 3428  ┆ 04-27 │
│ 194 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 429 ┆     ┆ 6-1 ┆ 429 ┆        ┆       ┆       ┆       │
│     ┆ HiS ┆ 080 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆        ┆       ┆       ┆       │
│     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 080 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

In [5]:
# DRR037200
DRR037200 = pl.read_json(
    "../../Data/metadata/metadata_bioproject/DRR037200.json"
).unnest(
    "properties"
).unnest(
    "RUN_SET"
).unnest(
    "RUN"
).drop(
    "accession", "alias"
).unnest(
    "EXPERIMENT_REF"
).rename(
    {
        "identifier": "run_accession",
        "accession": "experiment_accession", # this comes from EXPERIMENT_REF, not from RUN
        "refname": "experiment_alias",
        "TITLE": "experiment_title", # same text as the TITLE of DRX033435
        "dateCreated": "first_created",
        "datePublished": "first_public",
        "dateModified": "last_updated"
    }
).with_columns(
    pl.col("run_accession").alias("accession"), # create_paired_metadata uses "accession" as the run ID
    pl.col("first_created", "first_public", "last_updated").str.slice(0, 10) # keep YYYY-MM-DD like the ENA columns
)

# dbXrefs holds the linked IDs as a list of {identifier, type, url}; turn each type into a column
DRR037200_xrefs = DRR037200.select(
    "run_accession", "dbXrefs"
).explode(
    "dbXrefs"
).unnest(
    "dbXrefs"
).pivot(
    on="type",
    index="run_accession",
    values="identifier"
).rename(
    {
        "bioproject": "study_accession",
        "biosample": "sample_accession",
        "sra-sample": "secondary_sample_accession",
        "sra-study": "secondary_study_accession",
        "sra-submission": "submission_accession"
    }
).drop(
    "sra-experiment" # already present as experiment_accession
)

DRR037200 = DRR037200.join(
    DRR037200_xrefs,
    on="run_accession",
    how="left"
).select(
    # keep the column order of PRJDB3761_modified_metadata.tsv
    "run_accession",
    "experiment_title",
    "sample_accession",
    "submission_accession",
    "last_updated",
    "secondary_study_accession",
    "status",
    "experiment_alias",
    "center_name",
    "first_created",
    "experiment_accession",
    "study_accession",
    "accession",
    "secondary_sample_accession",
    "first_public"
)

display(DRR037200)

shape: (1, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ run ┆ exp ┆ sam ┆ sub ┆ las ┆ sec ┆ sta ┆ exp ┆ cen ┆ fir ┆ exp ┆ study_ ┆ acces ┆ secon ┆ first │
│ _ac ┆ eri ┆ ple ┆ mis ┆ t_u ┆ ond ┆ tus ┆ eri ┆ ter ┆ st_ ┆ eri ┆ access ┆ sion  ┆ dary_ ┆ _publ │
│ ces ┆ men ┆ _ac ┆ sio ┆ pda ┆ ary ┆ --- ┆ men ┆ _na ┆ cre ┆ men ┆ ion    ┆ ---   ┆ sampl ┆ ic    │
│ sio ┆ t_t ┆ ces ┆ n_a ┆ ted ┆ _st ┆ str ┆ t_a ┆ me  ┆ ate ┆ t_a ┆ ---    ┆ str   ┆ e_acc ┆ ---   │
│ n   ┆ itl ┆ sio ┆ cce ┆ --- ┆ udy ┆     ┆ lia ┆ --- ┆ d   ┆ cce ┆ str    ┆       ┆ essio ┆ str   │
│ --- ┆ e   ┆ n   ┆ ssi ┆ str ┆ _ac ┆     ┆ s   ┆ str ┆ --- ┆ ssi ┆        ┆       ┆ n     ┆       │
│ str ┆ --- ┆ --- ┆ on  ┆     ┆ ces ┆     ┆ --- ┆     ┆ str ┆ on  ┆        ┆       ┆ ---   ┆       │
│     ┆ str ┆ str ┆ --- ┆     ┆ sio ┆     ┆ str ┆     ┆     ┆ --- ┆        ┆       ┆ str   ┆       │
│     ┆     ┆     ┆ str ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ str ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJDB3 ┆ DRR03 ┆ DRS09 ┆ 2019- │
│ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ 999    ┆ 7200  ┆ 3429  ┆ 04-27 │
│ 200 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 435 ┆     ┆ 6-1 ┆ 435 ┆        ┆       ┆       ┆       │
│     ┆ HiS ┆ 086 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆        ┆       ┆       ┆       │
│     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

In [6]:
PRJDB3999 = pl.concat(
    [
        DRR037194,
        DRR037200
    ],
    how="vertical_relaxed"
).with_columns(
    pl.lit("mRNA Seq Sample Preparation Kit").alias("rna_library"),
    pl.lit("https://doi.org/10.1093/jb/mvaa126").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time"),
    pl.lit("37 C (inferred)").alias("control treatment temperature"),
    pl.lit("37 C").alias("recovery treatment temperature"),
    pl.lit("120 min.").alias("recovery treatment time"),
    pl.lit("A549").alias("cell_line"),
    pl.when(pl.col("run_accession") == "DRR037194")
        .then(pl.lit("HS_wt, A549, RNA-seq"))
        .otherwise(pl.lit("CTRL_wt, A549, RNA-seq"))
        .alias("sample_title"),
    pl.col("sample_accession").alias("sample_alias"), # PRJDB3761 stores the SAMD ID here
    pl.when(pl.col("run_accession") == "DRR037194")
        .then(pl.lit("Total RNA sample, HeatShock"))
        .otherwise(pl.lit("Total RNA sample, CTRL"))
        .alias("sample_description"),
    pl.lit("Illumina HiSeq 2500").alias("instrument_model"), # but, in article, it is mentioned that "Illumina HiSeq 2000" was used
    pl.lit("ILLUMINA").alias("instrument_platform"),
    pl.lit("SINGLE").alias("library_layout"),
    pl.lit("total RNA").alias("sample_molecule_ch1"),
    pl.lit("DRP005024").alias("study_alias"),
    pl.lit("TRANSCRIPTOMIC").alias("library_source")
)

PRJDB3999.write_csv(
    "../../Data/metadata/metadata_modified/PRJDB3999_modified_metadata.tsv",
    separator='\t'
)

display(PRJDB3999)

shape: (2, 32)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ run ┆ exp ┆ sam ┆ sub ┆ las ┆ sec ┆ sta ┆ exp ┆ cen ┆ fir ┆ exp ┆ stu ┆ acc ┆ sec ┆ fir ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ rec ┆ rec ┆ cel ┆ sam ┆ sam ┆ sam ┆ ins ┆ ins ┆ lib ┆ sam ┆ stu ┆ lib │
│ _ac ┆ eri ┆ ple ┆ mis ┆ t_u ┆ ond ┆ tus ┆ eri ┆ ter ┆ st_ ┆ eri ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ ove ┆ ove ┆ l_l ┆ ple ┆ ple ┆ ple ┆ tru ┆ tru ┆ rar ┆ ple ┆ dy_ ┆ rar │
│ ces ┆ men ┆ _ac ┆ sio ┆ pda ┆ ary ┆ --- ┆ men ┆ _na ┆ cre ┆ men ┆ acc ┆ ion ┆ ary ┆ pub ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ry  ┆ ry  ┆ ine ┆ _ti ┆ _al ┆ _de ┆ men ┆ men ┆ y_l ┆ _mo ┆ ali ┆ y_s │
│ sio ┆ t_t ┆ ces ┆ n_a ┆ ted ┆ _st ┆ str ┆ t_a ┆ me  ┆ ate ┆ t_a ┆ ess ┆ --- ┆ _sa ┆ lic ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ tre ┆ tre ┆ --- ┆ tle ┆ ias ┆ scr ┆ t_m ┆ t_p ┆ ayo ┆ lec ┆ as  ┆ our │
│ n   ┆ itl ┆ sio ┆ cce ┆ --- ┆ udy ┆     ┆ lia ┆ --- ┆ d   ┆ cce ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ atm ┆ atm ┆ str ┆ --- ┆ --- ┆ ipt ┆ ode ┆ lat ┆ ut  ┆ ule ┆ --- ┆ ce  │
│ --- ┆ e   ┆ n   ┆ ssi ┆ str ┆ _ac ┆     ┆ s   ┆ str ┆ --- ┆ ssi ┆ --- ┆     ┆ e_a ┆ str ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ ent ┆ ent ┆     ┆ str ┆ str ┆ ion ┆ l   ┆ for ┆ --- ┆ _ch ┆ str ┆ --- │
│ str ┆ --- ┆ --- ┆ on  ┆     ┆ ces ┆     ┆ --- ┆     ┆ str ┆ on  ┆ str ┆     ┆ cce ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ tem ┆ tim ┆     ┆     ┆     ┆ --- ┆ --- ┆ m   ┆ str ┆ 1   ┆     ┆ str │
│     ┆ str ┆ str ┆ --- ┆     ┆ sio ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ ssi ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆ per ┆ e   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆ str ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJ ┆ DRR ┆ DRS ┆ 201 ┆ mRN ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ 37  ┆ 120 ┆ A54 ┆ HS_ ┆ SAM ┆ Tot ┆ Ill ┆ ILL ┆ SIN ┆ tot ┆ DRP ┆ TRA │
│ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ DB3 ┆ 037 ┆ 093 ┆ 9-0 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ C   ┆ min ┆ 9   ┆ wt, ┆ D00 ┆ al  ┆ umi ┆ UMI ┆ GLE ┆ al  ┆ 005 ┆ NSC │
│ 194 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 429 ┆     ┆ 6-1 ┆ 429 ┆ 999 ┆ 194 ┆ 428 ┆ 4-2 ┆ Seq ┆ //d ┆     ┆ .   ┆ (in ┆     ┆ .   ┆     ┆ A54 ┆ 032 ┆ RNA ┆ na  ┆ NA  ┆     ┆ RNA ┆ 024 ┆ RIP │
│     ┆ HiS ┆ 080 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆ 7   ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ 9,  ┆ 080 ┆ sam ┆ HiS ┆     ┆     ┆     ┆     ┆ TOM │
│     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ org ┆     ┆     ┆ red ┆     ┆     ┆     ┆ RNA ┆     ┆ ple ┆ eq  ┆     ┆     ┆     ┆     ┆ IC  │
│     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ -se ┆     ┆ ,   ┆ 250 ┆     ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆ Hea ┆ 0   ┆     ┆     ┆     ┆     ┆     │
│     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 93/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tSh ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ jb/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ mva ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a12 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 080 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJ ┆ DRR ┆ DRS ┆ 201 ┆ mRN ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ 37  ┆ 120 ┆ A54 ┆ CTR ┆ SAM ┆ Tot ┆ Ill ┆ ILL ┆ SIN ┆ tot ┆ DRP ┆ TRA │
│ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ DB3 ┆ 037 ┆ 093 ┆ 9-0 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ C   ┆ min ┆ 9   ┆ L_w ┆ D00 ┆ al  ┆ umi ┆ UMI ┆ GLE ┆ al  ┆ 005 ┆ NSC │
│ 200 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 435 ┆     ┆ 6-1 ┆ 435 ┆ 999 ┆ 200 ┆ 429 ┆ 4-2 ┆ Seq ┆ //d ┆     ┆ .   ┆ (in ┆     ┆ .   ┆     ┆ t,  ┆ 032 ┆ RNA ┆ na  ┆ NA  ┆     ┆ RNA ┆ 024 ┆ RIP │
│     ┆ HiS ┆ 086 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆ 7   ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ A54 ┆ 086 ┆ sam ┆ HiS ┆     ┆     ┆     ┆     ┆ TOM │
│     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ org ┆     ┆     ┆ red ┆     ┆     ┆     ┆ 9,  ┆     ┆ ple ┆ eq  ┆     ┆     ┆     ┆     ┆ IC  │
│     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ RNA ┆     ┆ ,   ┆ 250 ┆     ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆ CTR ┆ 0   ┆     ┆     ┆     ┆     ┆     │
│     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 93/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆ L   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ jb/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ mva ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a12 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [7]:
defined_pairs_prjdb3999 = [
    ("DRR037194", "DRR037200") # HS_wt vs. CTRL_wt
]

paired_metadata_df_prjdb3999 = create_paired_metadata(
    combined_df=PRJDB3999,
    defined_sample_pairs=defined_pairs_prjdb3999,
    sample_id_column_name="accession"
)

if paired_metadata_df_prjdb3999 is not None:
    paired_metadata_df_prjdb3999.write_csv(
        "../../Data/metadata/metadata_paired/PRJDB3999_paired_metadata.tsv",
        separator="\t"
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_prjdb3999)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 33)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ run ┆ exp ┆ sam ┆ sub ┆ las ┆ sec ┆ sta ┆ exp ┆ cen ┆ fir ┆ exp ┆ stu ┆ sec ┆ fir ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ rec ┆ rec ┆ cel ┆ sam ┆ sam ┆ sam ┆ ins ┆ ins ┆ lib ┆ sam ┆ stu ┆ lib │
│ ple ┆ ple ┆ _ac ┆ eri ┆ ple ┆ mis ┆ t_u ┆ ond ┆ tus ┆ eri ┆ ter ┆ st_ ┆ eri ┆ dy_ ┆ ond ┆ st_ ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ ove ┆ ove ┆ l_l ┆ ple ┆ ple ┆ ple ┆ tru ┆ tru ┆ rar ┆ ple ┆ dy_ ┆ rar │
│ _he ┆ _co ┆ ces ┆ men ┆ _ac ┆ sio ┆ pda ┆ ary ┆ --- ┆ men ┆ _na ┆ cre ┆ men ┆ acc ┆ ary ┆ pub ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ry  ┆ ry  ┆ ine ┆ _ti ┆ _al ┆ _de ┆ men ┆ men ┆ y_l ┆ _mo ┆ ali ┆ y_s │
│ at_ ┆ ntr ┆ sio ┆ t_t ┆ ces ┆ n_a ┆ ted ┆ _st ┆ str ┆ t_a ┆ me  ┆ ate ┆ t_a ┆ ess ┆ _sa ┆ lic ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ tre ┆ tre ┆ --- ┆ tle ┆ ias ┆ scr ┆ t_m ┆ t_p ┆ ayo ┆ lec ┆ as  ┆ our │
│ id  ┆ ol_ ┆ n   ┆ itl ┆ sio ┆ cce ┆ --- ┆ udy ┆     ┆ lia ┆ --- ┆ d   ┆ cce ┆ ion ┆ mpl ┆ --- ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ atm ┆ atm ┆ str ┆ --- ┆ --- ┆ ipt ┆ ode ┆ lat ┆ ut  ┆ ule ┆ --- ┆ ce  │
│ --- ┆ id  ┆ --- ┆ e   ┆ n   ┆ ssi ┆ str ┆ _ac ┆     ┆ s   ┆ str ┆ --- ┆ ssi ┆ --- ┆ e_a ┆ str ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ ent ┆ ent ┆     ┆ str ┆ str ┆ ion ┆ l   ┆ for ┆ --- ┆ _ch ┆ str ┆ --- │
│ str ┆ --- ┆ str ┆ --- ┆ --- ┆ on  ┆     ┆ ces ┆     ┆ --- ┆     ┆ str ┆ on  ┆ str ┆ cce ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ tem ┆ tim ┆     ┆     ┆     ┆ --- ┆ --- ┆ m   ┆ str ┆ 1   ┆     ┆ str │
│     ┆ str ┆     ┆ str ┆ str ┆ --- ┆     ┆ sio ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ ssi ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆ per ┆ e   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ DRR ┆ DRR ┆ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJ ┆ DRS ┆ 201 ┆ mRN ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ 37  ┆ 120 ┆ A54 ┆ HS_ ┆ SAM ┆ Tot ┆ Ill ┆ ILL ┆ SIN ┆ tot ┆ DRP ┆ TRA │
│ 037 ┆ 037 ┆ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ DB3 ┆ 093 ┆ 9-0 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ C   ┆ min ┆ 9   ┆ wt, ┆ D00 ┆ al  ┆ umi ┆ UMI ┆ GLE ┆ al  ┆ 005 ┆ NSC │
│ 194 ┆ 200 ┆ 194 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 429 ┆     ┆ 6-1 ┆ 429 ┆ 999 ┆ 428 ┆ 4-2 ┆ Seq ┆ //d ┆     ┆ .   ┆ (in ┆     ┆ .   ┆     ┆ A54 ┆ 032 ┆ RNA ┆ na  ┆ NA  ┆     ┆ RNA ┆ 024 ┆ RIP │
│     ┆     ┆ vs  ┆ HiS ┆ 080 ┆     ┆ 8   ┆     ┆     ┆ vs  ┆     ┆ 2   ┆ vs  ┆     ┆ vs  ┆ 7   ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ 9,  ┆ 080 ┆ sam ┆ HiS ┆     ┆     ┆     ┆     ┆ TOM │
│     ┆     ┆ DRR ┆ eq  ┆ vs  ┆     ┆     ┆     ┆     ┆ DRX ┆     ┆     ┆ DRX ┆     ┆ DRS ┆     ┆ ple ┆ org ┆     ┆     ┆ red ┆     ┆     ┆     ┆ RNA ┆ vs  ┆ ple ┆ eq  ┆     ┆     ┆     ┆     ┆ IC  │
│     ┆     ┆ 037 ┆ 250 ┆ SAM ┆     ┆     ┆     ┆     ┆ 033 ┆     ┆     ┆ 033 ┆     ┆ 093 ┆     ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ -se ┆ SAM ┆ ,   ┆ 250 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 200 ┆ 0   ┆ D00 ┆     ┆     ┆     ┆     ┆ 435 ┆     ┆     ┆ 435 ┆     ┆ 429 ┆     ┆ par ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ D00 ┆ Hea ┆ 0   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ seq ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 93/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 032 ┆ tSh ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ uen ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ jb/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ CTR ┆ 086 ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ mva ┆     ┆     ┆     ┆     ┆     ┆     ┆ L_w ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a12 ┆     ┆     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆ Tot ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆ A54 ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9,  ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 080 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CTR ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ Ill ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ L   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE278916 (HRA014825) (RNA-seq)

- ✅ DOWNLOAD (M3 MacBook Pro)
- ✅ TRIMMING (M3 MacBook Pro)
- ✅ QUANTIFICATION (yone-hdd-fantom6)

&nbsp;

- validate date: 2026-02-23
- [De novo assembly of nuclear stress bodies rearranges and enhances NFIL3 to restrain acute inflammatory responses](https://doi.org/10.1016/j.cell.2025.05.003)
- [GSE277764](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE277764) の Nanoporeのデータに加えて、上記の論文で登録されているデータ
- GSA for human にも同じエントリーと思われるデータを発見: [HRA014825](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA014825)
- おそらく多くのデータを取得したGEOのクエリで現在実行するとヒットする可能性が高いが、このnotebookに記載する
- `Cell stimulation; For heat shock (HS) treatment, Human HeLa, THP-1 cells and HUVECs were replaced with pre-heated (42°C) conditioned medium and incubated in a culture incubator with an environmental temperature at 42°C and humidified 5% CO2 for 2 h, then recovered at 37°C for 1 h.`

In [8]:
GSE278916_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE278916/GSE278916_PEP/GSE278916_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    (pl.col("sample_taxid_ch1") == 9606) &
    (~pl.col("sample_title").str.contains("_SA_"))
).with_columns(
    pl.lit("Illumina TruSeq RNA sample preparation guide (specific kit/version unspecified)").alias("rna_library"),
    pl.lit("https://doi.org/10.1016/j.cell.2025.05.003").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time"),
    pl.lit("37 C (inferred)").alias("control treatment temperature")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE278916 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE278916.metadata.tsv",
    separator='\t'
)

GSE278916_combined = GSE278916_PEP.join(
    GSE278916,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE278916_combined = GSE278916_combined[[s.name for s in GSE278916_combined if not (s.null_count() == GSE278916_combined.height)]]

GSE278916_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE278916_modified_metadata.tsv",
    separator='\t'
)

# pl.Config.set_tbl_rows(18)
# display(GSE278916_combined)

In [9]:
defined_pairs_gse278916 = [
    ("SRR30897701", "SRR30897703"), # RNA-seq_HeLa_HS_rep1 vs. RNA-seq_HeLa_UN_rep1
    ("SRR30897700", "SRR30897702"), # RNA-seq_HeLa_HS_rep2 vs. RNA-seq_HeLa_UN_rep2
    ("SRR30897695", "SRR30897696"), # RNA-seq_HUVEC_HS_rep1 vs. RNA-seq_HUVEC_UN_rep1
    ("SRR30897694", "SRR30897699"), # RNA-seq_HUVEC_HS_rep2 vs. RNA-seq_HUVEC_UN_rep2
    ("SRR30897688", "SRR30897690"), # RNA-seq_THP-1_HS_rep1 vs. RNA-seq_THP-1_UN_rep1
    ("SRR30897691", "SRR30897689")  # RNA-seq_THP-1_HS_rep2 vs. RNA-seq_THP-1_UN_rep2
]

paired_metadata_df_gse278916 = create_paired_metadata(
    combined_df=GSE278916_combined,
    defined_sample_pairs=defined_pairs_gse278916,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse278916 is not None:
    paired_metadata_df_gse278916.write_csv(
        "../../Data/metadata/metadata_paired/GSE278916_paired_metadata.tsv",
        separator="\t"
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse278916)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ cel ┆ tre ┆ ass ┆ bio ┆ sra ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ l_l ┆ atm ┆ emb ┆ sam ┆ --- ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ ine ┆ ent ┆ ly  ┆ ple ┆ str ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆     ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ rna ┆ RNA ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ tot ┆ tot ┆ GPL ┆ Li, ┆ liy ┆ Ins ┆ Fud ┆ 131 ┆ Sha ┆ 200 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ HS  ┆ CHM ┆ htt ┆ htt ┆ Ill ┆ htt ┆ 42  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ SAM ┆ RNA ┆ SRA ┆ cDN ┆ 202 ┆ 475 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ RNA ┆ 59f ┆ SRP ┆ 699 ┆ RNA ┆ GEN ┆ RNA ┆ Ill ┆ Ill ┆ ftp ┆ 209 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ HeL ┆ mis ┆ GSM ┆ HeL ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 308 ┆ 308 ┆ -se ┆ -se ┆ 855 ┆ lic ┆ 06  ┆ 26  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ al  ┆ alR ┆ 246 ┆ ,Ya ┆ ang ┆ tit ┆ an  ┆ Don ┆ ngh ┆ 032 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 855 ┆ E   ┆ 278 ┆     ┆ 263 ┆ a   ┆ str ┆ 13  ┆ ps: ┆ ps: ┆ umi ┆ ps: ┆ C   ┆ min ┆ C   ┆ 308 ┆ umi ┆ N44 ┆ seq ┆ 198 ┆ A   ┆ 5-0 ┆ 271 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ -se ┆ 0d0 ┆ 536 ┆ 225 ┆ seq ┆ ERA ┆ -se ┆ umi ┆ umi ┆ .sr ┆ 767 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 855 ┆ 855 ┆ a,  ┆ sin ┆ 855 ┆ a   ┆ 855 ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA1 ┆ 228 ┆ 5-0 ┆ 278 │
│ 977 ┆ 977 ┆ q_h ┆ q_H ┆ 742 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ NA_ ┆ 76  ┆ ng  ┆ _fu ┆ ute ┆ Uni ┆ g-A ┆ ai  ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 742 ┆     ┆ 916 ┆     ┆ 011 ┆     ┆ ess ┆ T2T ┆ //w ┆ //w ┆ na  ┆ //d ┆     ┆ .   ┆ (in ┆ 977 ┆ na  ┆ 078 ┆ uen ┆ 681 ┆     ┆ 5-2 ┆ 122 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ q_H ┆ 4fe ┆ 890 ┆ 03  ┆ uen ┆ TED ┆ q_H ┆ na  ┆ na  ┆ a.e ┆ 509 ┆ q   ┆ RIP ┆     ┆     ┆ ra. ┆ 67; ┆ 742 ┆ 742 ┆ THP ┆ g   ┆ 742 ┆     ┆ 742 ┆ x:t ┆ 5-2 ┆ sap ┆     ┆ 169 ┆ 299 ┆ 5-2 ┆ 916 │
│ 01  ┆ 03  ┆ ela ┆ eLa ┆ 7   ┆ May ┆ 4   ┆ 5   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ HeL ┆     ┆     ┆ dan ┆ s   ┆ ver ┆ n   ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 93  ┆     ┆ ed  ┆ v2. ┆ ww. ┆ ww. ┆ Tru ┆ oi. ┆     ┆     ┆ fer ┆ 01  ┆ Nov ┆ 906 ┆ cin ┆ 8   ┆     ┆ 8   ┆ 7;4 ┆     ┆ bi. ┆     ┆     ┆ eLa ┆ 712 ┆     ┆ vs  ┆ cin ┆ _FI ┆ eLa ┆ Nov ┆ Nov ┆ bi. ┆ 00  ┆     ┆ TOM ┆     ┆     ┆ ebi ┆ 275 ┆ 7   ┆ 7_r ┆ -1  ┆     ┆ 7_r ┆     ┆ 7   ┆ err ┆ 8   ┆ ien ┆     ┆ 616 ┆ 12  ┆ 8   ┆     │
│     ┆     ┆ _hs ┆ _HS ┆ vs  ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ a_H ┆     ┆     ┆ @fu ┆ of  ┆ sit ┆ Roa ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ vs  ┆ 0   ┆ ncb ┆ ncb ┆ Seq ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ vs  ┆ g   ┆     ┆     ┆     ┆ 957 ┆     ┆ ac. ┆     ┆     ┆ _HS ┆ 4f0 ┆     ┆ 735 ┆ g   ┆ LE; ┆ _HS ┆ aSe ┆ aSe ┆ ac. ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ cel ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ _re ┆ _re ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_r ┆     ┆     ┆ dan ┆ Bio ┆ y   ┆ d   ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ unt ┆     ┆ i.n ┆ i.n ┆ RNA ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ SAM ┆ in  ┆     ┆     ┆     ┆ 546 ┆     ┆ uk/ ┆     ┆     ┆ _re ┆ 7a0 ┆     ┆ 559 ┆ in  ┆ GEN ┆ _re ┆ q   ┆ q   ┆ uk/ ┆ 220 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ls  ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ p1  ┆ p1  ┆ 855 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆ .ed ┆ log ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 855 ┆     ┆     ┆     ┆ 263 ┆     ┆ rea ┆     ┆ lm. ┆ lm. ┆ sam ┆ .10 ┆     ┆     ┆     ┆ 308 ┆ 600 ┆ N44 ┆ unt ┆     ┆     ┆     ┆ 654 ┆     ┆ vol ┆     ┆     ┆ p1  ┆ 28d ┆     ┆ 14  ┆ unt ┆ ERA ┆ p1  ┆ 600 ┆ 600 ┆ vol ┆ 667 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 855 ┆ GSM ┆ and ┆     ┆ GSM ┆     ┆ 855 ┆ l;e ┆     ┆     ┆     ┆     ┆ 228 ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ u.c ┆ ica ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆     ┆ 011 ┆     ┆ ted ┆     ┆ nih ┆ nih ┆ ple ┆ 16/ ┆     ┆     ┆     ┆ 977 ┆ 0   ┆ 078 ┆ rea ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ vs  ┆ 815 ┆     ┆     ┆ rea ┆ TED ┆ vs  ┆ 0   ┆ 0   ┆ 1/f ┆ 742 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 742 ┆ 855 ┆ HUV ┆     ┆ 855 ┆     ┆ 742 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 299 ┆     ┆     │
│     ┆     ┆ rna ┆ RNA ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tot ┆     ┆     ┆ n   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ 91  ┆     ┆     ┆     ┆ .go ┆ .go ┆ pre ┆ j.c ┆     ┆     ┆     ┆ 03  ┆ seq ┆ 908 ┆ ted ┆     ┆     ┆     ┆ 511 ┆     ┆ ast ┆     ┆     ┆ RNA ┆ 69a ┆     ┆     ┆ ted ┆ _FI ┆ RNA ┆     ┆ seq ┆ ast ┆ 00  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 5   ┆ 742 ┆ EC  ┆     ┆ 742 ┆     ┆ 5   ┆ tax ┆     ┆     ┆     ┆     ┆ 10  ┆     ┆     │
│     ┆     ┆ -se ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ alR ┆     ┆     ┆     ┆ Sci ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ par ┆ ell ┆     ┆     ┆     ┆     ┆ uen ┆     ┆ (UN ┆     ┆     ┆     ┆ 110 ┆     ┆ q/S ┆     ┆     ┆ -se ┆ af7 ┆     ┆     ┆ (UN ┆ LE  ┆ -se ┆     ┆ uen ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 5_r ┆ cel ┆     ┆ 5_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_h ┆ q_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA_ ┆     ┆     ┆     ┆ enc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ ati ┆ .20 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ ),  ┆     ┆     ┆     ┆ 464 ┆     ┆ RR3 ┆     ┆     ┆ q_H ┆ ef; ┆     ┆     ┆ ),  ┆     ┆ q_H ┆     ┆ cin ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ ls  ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ela ┆ eLa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ on  ┆ 25. ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ sod ┆     ┆     ┆     ┆ 4;5 ┆     ┆ 08/ ┆     ┆     ┆ eLa ┆ ac5 ┆     ┆     ┆ sod ┆     ┆ eLa ┆     ┆ g:  ┆ 08/ ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆ 213 ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _un ┆ _UN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ gui ┆ 05. ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ ium ┆     ┆     ┆     ┆ 326 ┆     ┆ 001 ┆     ┆     ┆ _UN ┆ c50 ┆     ┆     ┆ ium ┆     ┆ _UN ┆     ┆ GSM ┆ 001 ┆     ┆     ┆     ┆     ┆     ┆ 8/0 ┆ ;33 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ de  ┆ 003 ┆     ┆     ┆     ┆     ┆ 855 ┆     ┆ ars ┆     ┆     ┆     ┆ 875 ┆     ┆ /SR ┆     ┆     ┆ _re ┆ fe0 ┆     ┆     ┆ ars ┆     ┆ _re ┆     ┆ 855 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 01/ ┆ 511 ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N44 ┆ 630 ┆ (sp ┆     ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆ eni ┆     ┆     ┆     ┆ 706 ┆     ┆ R30 ┆     ┆     ┆ p1  ┆ 4e2 ┆     ┆     ┆ eni ┆     ┆ p1  ┆     ┆ 742 ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 078 ┆ 119 ┆ eci ┆     ┆     ┆     ┆     ┆     ┆ 7:  ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆ 897 ┆     ┆     ┆     ┆ da7 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆ 7:  ┆ 897 ┆     ┆     ┆     ┆     ┆     ┆ 308 ┆ 11; ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 906 ┆ 3   ┆ fic ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆ (SA ┆     ┆     ┆     ┆     ┆     ┆ 701 ┆     ┆     ┆     ┆ 33f ┆     ┆     ┆ (SA ┆     ┆     ┆     ┆ RNA ┆ 701 ┆     ┆     ┆     ┆     ┆     ┆ 977 ┆ 895 ┆     ┆     ┆ 6-w ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆ kit ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ eae ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ -se ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 01/ ┆ 93; ┆     ┆     ┆ ell ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆ /ve ┆     ┆     ┆     ┆     ┆     ┆ q_H ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆     ┆     ┆     ┆ 68d ┆     ┆     ┆ and ┆     ┆     ┆     ┆ q_H ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆ rsi ┆     ┆     ┆     ┆     ┆     ┆ eLa ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ 897 ┆     ┆     ┆     ┆ fd5 ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ eLa ┆ 897 ┆     ┆     ┆     ┆     ┆     ┆ 308 ┆ 2;7 ┆     ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 701 ┆     ┆     ┆     ┆ bd2 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ _HS ┆ 701 ┆     ┆     ┆     ┆     ┆     ┆ 977 ┆ 776 ┆     ┆     ┆ .   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ uns ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ ef  ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ _re ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 01_ ┆ ;11 ┆     ┆     ┆ The ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ pec ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆ p1  ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ nex ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ ifi ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆ tq. ┆     ┆     ┆     ┆ 3a5 ┆     ┆     ┆ (HS ┆     ┆     ┆     ┆ Hom ┆ tq. ┆     ┆     ┆     ┆     ┆     ┆ ast ┆ 0;1 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE191134 (PAIRED) (RNA-seq)

- ✅ DOWNLOAD (yone-hdd-fantom6)
- ✅ TRIMMING (yone-hdd-fantom6)
- ✅ QUANTIFICATION (yone-hdd-fantom6)

&nbsp;

- validate date: 2025-10-12
- [GSE191134](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE191134)
- [Reversible phase separation of HSF1 is required for an acute transcriptional response during heat shock](https://doi.org/10.1038/s41556-022-00846-7)
- HSF1の相分離について調査している論文の中に、RNA-seqのデータが含まれていたが、なぜかヒットしていなかったので手動で収集
- 熱ストレス ＋ 相分離を解消させるためのヘキサンジオール処理をしているデータは、untreated + ヘキサンジオール処理のデータがないため今回は除外する... (SRR16555315, SRR16555316)
- HSF1に変異が導入されたM3, M1のデータには、それぞれHSとuntreatedがあるかと思っていたが、M3はHSのみ、M1はuntreatedのみだったのでなくなく今回は除外する... (SRR16555317, SRR16555318 ,SRR16555319. SRR16555320)
- 他のデータは収集、解析

In [10]:
GSE191134_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE191134/GSE191134_PEP/GSE191134_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("VAHTS universal V8 RNA-seq library prep kit for Illumina (Vazyme, cat. no. NR605) and KAPA HyperPrep kit (Roche, cat. no. KR0961)").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1038/s41556-022-00846-7").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("unknown").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE191134 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE191134.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE191134_filtered = GSE191134[[s.name for s in GSE191134 if not (s.null_count() == GSE191134.height)]]

GSE191134_combined = GSE191134_PEP.join(
    GSE191134_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left"
).sort(
    [
        "gsm_id"
    ],
    descending=False
)

GSE191134_combined = GSE191134_combined[[s.name for s in GSE191134_combined if not (s.null_count() == GSE191134_combined.height)]]

GSE191134_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE191134_modified_metadata.tsv",
    separator='\t'
)

display(GSE191134_combined)

shape: (10, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ sub ┆ lib ┆ las ┆ sra ┆ iso ┆ fas ┆ ins ┆ sex ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ exp ┆ cen ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ oty ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ mis ┆ rar ┆ t_u ┆ _by ┆ lat ┆ tq_ ┆ tru ┆ --- ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ eri ┆ ter ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ pe  ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ sio ┆ y_s ┆ pda ┆ tes ┆ e   ┆ byt ┆ men ┆ str ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ men ┆ _na ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali ┆ _ty │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ n_a ┆ ele ┆ ted ┆ --- ┆ --- ┆ es  ┆ t_p ┆     ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ t_a ┆ me  ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ cce ┆ cti ┆ --- ┆ i64 ┆ str ┆ --- ┆ lat ┆     ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ lia ┆ --- ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ ssi ┆ on  ┆ str ┆     ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ i64 ┆ str ┆ ght ┆ l   ┆ str ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ s   ┆ str ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆ on  ┆ --- ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ i64 ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ m1- ┆ M1- ┆ GSM ┆ Pub ┆ Dec ┆ Dec ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Hon ┆ zha ┆ 185 ┆ Pek ┆ Bei ┆ Ple ┆ 100 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ Can ┆ unt ┆ HSF ┆ GRC ┆ raw ┆ SAM ┆ VAH ┆ htt ┆ 42  ┆ 60  ┆ unk ┆ SRR ┆ Ill ┆ SRA ┆ PCR ┆ 202 ┆ 250 ┆ HeL ┆ 179 ┆ ILL ┆ fem ┆ Hum ┆ M1- ┆ SRP ┆ 276 ┆ RNA ┆ M1- ┆ Ill ┆ Ill ┆ 828 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ M1- ┆ M1- ┆ RNA ┆ SUB ┆ HeL ┆ RNA ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ PRJ ┆ cer │
│ nhs ┆ NHS ┆ 573 ┆ lic ┆ 17  ┆ 21  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ gch ┆ ngh ┆ 102 ┆ ing ┆ jin ┆ ase ┆ 871 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 573 ┆ :// ┆ 191 ┆     ┆ 127 ┆ a   ┆ cer ┆ rea ┆ 1   ┆ h38 ┆ rea ┆ N22 ┆ TS  ┆ ps: ┆ C   ┆ min ┆ now ┆ 165 ┆ umi ┆ 131 ┆     ┆ 2-0 ┆ 932 ┆ a   ┆ 627 ┆ UMI ┆ ale ┆ an  ┆ NHS ┆ 342 ┆ 245 ┆ seq ┆ NHS ┆ umi ┆ umi ┆ 736 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ NHS ┆ NHS ┆ _se ┆ 105 ┆ a   ┆ _se ┆ _ta ┆ 2-0 ┆ o   ┆ 6   ┆ NA7 ┆ 165 ┆ 107 ┆ 2-0 ┆ NA7 ┆ vic │
│ -re ┆ -Re ┆ 982 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆ 76  ┆ en, ┆ ong ┆ 115 ┆ Uni ┆ g   ┆ Sel ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 982 ┆ ftp ┆ 134 ┆     ┆ 574 ┆ cel ┆ Cel ┆ ted ┆ KO  ┆     ┆ d   ┆ 550 ┆ uni ┆ //d ┆     ┆ .   ┆ n   ┆ 553 ┆ na  ┆ 619 ┆     ┆ 3-1 ┆ 654 ┆ cel ┆ 630 ┆ NA  ┆     ┆     ┆ -bi ┆ 933 ┆ 41  ┆ uen ┆ -bi ┆ na  ┆ na  ┆ 230 ┆ q   ┆ RIP ┆     ┆     ┆ -Re ┆ -Re ┆ q5  ┆ 626 ┆ S6  ┆ q5  ┆ x;e ┆ 3-1 ┆ sap ┆     ┆ 741 ┆ 553 ┆ 047 ┆ 3-1 ┆ 741 ┆ al  │
│ p1  ┆ p1  ┆ 3   ┆ Dec ┆ 1   ┆ 1   ┆     ┆     ┆ ls  ┆ ien ┆     ┆     ┆     ┆ ,Zh ┆ che ┆ 43  ┆ ver ┆     ┆ ect ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 3   ┆ .nc ┆     ┆     ┆ 51  ┆ ls  ┆ l   ┆     ┆ and ┆     ┆ cou ┆ 559 ┆ ver ┆ oi. ┆     ┆     ┆     ┆ 20  ┆ Nov ┆ 7   ┆     ┆ 0   ┆ 2   ┆ l   ┆ 8;1 ┆     ┆     ┆     ┆ olo ┆     ┆     ┆ cin ┆ olo ┆ Nov ┆ Nov ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ p1  ┆ p1_ ┆     ┆ 54  ┆     ┆     ┆ nv_ ┆ 0   ┆ ien ┆     ┆ 01  ┆ 20  ┆ 67  ┆ 0   ┆ 01  ┆ can │
│     ┆     ┆     ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ ang ┆ n@p ┆     ┆ sit ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆ tra ┆     ┆ nt  ┆     ┆ sal ┆ org ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆     ┆ lin ┆ 815 ┆     ┆     ┆     ┆ gic ┆     ┆     ┆ g   ┆ gic ┆ aSe ┆ aSe ┆     ┆     ┆ IC  ┆     ┆     ┆     ┆ R1. ┆     ┆     ┆     ┆     ┆ tax ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ cer │
│     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ku. ┆     ┆ y   ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ nsf ┆     ┆     ┆     ┆ V8  ┆ /10 ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ e   ┆ 041 ┆     ┆     ┆     ┆ al  ┆     ┆     ┆ of  ┆ al  ┆ q   ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆ fq. ┆     ┆     ┆     ┆     ┆ :te ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ edu ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆ ect ┆     ┆     ┆     ┆ RNA ┆ .10 ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆ 427 ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ HeL ┆ rep ┆ 600 ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆     ┆ gz  ┆     ┆     ┆     ┆     ┆ rre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .cn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆ a   ┆     ┆ ed  ┆     ┆     ┆     ┆ -se ┆ 38/ ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆ a   ┆ lic ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆ S6  ┆     ┆ wit ┆     ┆     ┆     ┆ q   ┆ s41 ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆ cel ┆ ate ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ial ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆ lib ┆ 556 ┆     ┆     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ l   ┆ 1   ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆     ┆     ┆ rar ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ y   ┆ 2-0 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ M1  ┆     ┆     ┆     ┆ pre ┆ 084 ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆ 6-7 ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 573 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 739 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 823 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Va ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zym ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [11]:
defined_pairs_gse191134 = [
    ("SRR16555321", "SRR16555323"), # wt-hs-rep2 vs wt-nhs-rep2
    ("SRR16555322", "SRR16555324")  # wt-hs-rep1 vs wt-nhs-rep1
]

paired_metadata_df_gse191134 = create_paired_metadata(
    combined_df=GSE191134_combined, 
    defined_sample_pairs=defined_pairs_gse191134,
    sample_id_column_name="accession" # default value, but specified to clarify
)

# Guard against None so that write_csv is called only on a DataFrame
if paired_metadata_df_gse191134 is not None:
    paired_metadata_df_gse191134.write_csv(
        "../../Data/metadata/metadata_paired/GSE191134_paired_metadata.tsv",
        separator="\t"
    )
    display(paired_metadata_df_gse191134)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ gen ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ sub ┆ lib ┆ las ┆ sra ┆ iso ┆ fas ┆ ins ┆ sex ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ exp ┆ cen ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ oty ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ mis ┆ rar ┆ t_u ┆ _by ┆ lat ┆ tq_ ┆ tru ┆ --- ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ eri ┆ ter ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ pe  ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ sio ┆ y_s ┆ pda ┆ tes ┆ e   ┆ byt ┆ men ┆ str ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ men ┆ _na ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ n_a ┆ ele ┆ ted ┆ --- ┆ --- ┆ es  ┆ t_p ┆     ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ t_a ┆ me  ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ cce ┆ cti ┆ --- ┆ str ┆ str ┆ --- ┆ lat ┆     ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ lia ┆ --- ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ ssi ┆ on  ┆ str ┆     ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ s   ┆ str ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆ on  ┆ --- ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wt- ┆ WT- ┆ GSM ┆ Pub ┆ Dec ┆ Dec ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Hon ┆ zha ┆ 185 ┆ Pek ┆ Bei ┆ Ple ┆ 100 ┆ Chi ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HeL ┆ Can ┆ Hea ┆ WT  ┆ GRC ┆ raw ┆ SAM ┆ VAH ┆ htt ┆ 42  ┆ 60  ┆ unk ┆ SRR ┆ Ill ┆ SRA ┆ PCR ┆ 202 ┆ 236 ┆ HeL ┆ 169 ┆ ILL ┆ fem ┆ Hum ┆ WT- ┆ SRP ┆ 259 ┆ RNA ┆ WT- ┆ Ill ┆ Ill ┆ 777 ┆ RNA ┆ TRA ┆ PAI ┆ pub ┆ WT- ┆ WT- ┆ RNA ┆ SUB ┆ HeL ┆ RNA ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 202 ┆ PRJ ┆ cer │
│ 165 ┆ 165 ┆ hs- ┆ HS- ┆ 573 ┆ lic ┆ 17  ┆ 21  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ al  ┆ 246 ┆ gch ┆ ngh ┆ 102 ┆ ing ┆ jin ┆ ase ┆ 871 ┆ na  ┆ umi ┆ A   ┆ nsc ┆ -Se ┆ 573 ┆ :// ┆ 191 ┆     ┆ 127 ┆ a   ┆ cer ┆ t   ┆ cel ┆ h38 ┆ rea ┆ N22 ┆ TS  ┆ ps: ┆ C   ┆ min ┆ now ┆ 165 ┆ umi ┆ 131 ┆     ┆ 2-0 ┆ 717 ┆ a   ┆ 094 ┆ UMI ┆ ale ┆ an  ┆ HS- ┆ 342 ┆ 213 ┆ seq ┆ HS- ┆ umi ┆ umi ┆ 640 ┆ -Se ┆ NSC ┆ RED ┆ lic ┆ HS- ┆ HS- ┆ _se ┆ 105 ┆ a   ┆ _se ┆ _ta ┆ 2-0 ┆ o   ┆ 6   ┆ NA7 ┆ 107 ┆ 2-0 ┆ NA7 ┆ vic │
│ 553 ┆ 553 ┆ rep ┆ Rep ┆ 983 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆ 76  ┆ en, ┆ ong ┆ 115 ┆ Uni ┆ g   ┆ Sel ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 983 ┆ ftp ┆ 134 ┆     ┆ 574 ┆ cel ┆ Cel ┆ sho ┆ ls  ┆     ┆ d   ┆ 550 ┆ uni ┆ //d ┆     ┆ .   ┆ n   ┆ 553 ┆ na  ┆ 619 ┆     ┆ 3-1 ┆ 106 ┆ cel ┆ 358 ┆ NA  ┆     ┆     ┆ bio ┆ 933 ┆ 41  ┆ uen ┆ bio ┆ na  ┆ na  ┆ 230 ┆ q   ┆ RIP ┆     ┆     ┆ Rep ┆ Rep ┆ q4  ┆ 626 ┆ S6  ┆ q4  ┆ x;e ┆ 3-1 ┆ sap ┆     ┆ 741 ┆ 047 ┆ 3-1 ┆ 741 ┆ al  │
│ 21  ┆ 23  ┆ 2   ┆ 2   ┆ 0   ┆ Dec ┆ 1   ┆ 1   ┆     ┆     ┆ ls  ┆ ien ┆     ┆     ┆     ┆ ,Zh ┆ che ┆ 43  ┆ ver ┆     ┆ ect ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 0   ┆ .nc ┆     ┆     ┆ 50  ┆ ls  ┆ l   ┆ ck  ┆     ┆     ┆ cou ┆ 558 ┆ ver ┆ oi. ┆     ┆     ┆     ┆ 21  ┆ Nov ┆ 7   ┆     ┆ 0   ┆ 1   ┆ l   ┆ 5;1 ┆     ┆     ┆     ┆ log ┆     ┆ vs  ┆ cin ┆ log ┆ Nov ┆ Nov ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_R ┆ vs  ┆ 54  ┆     ┆ vs  ┆ nv_ ┆ 0   ┆ ien ┆     ┆ 01  ┆ 66  ┆ 0   ┆ 01  ┆ can │
│     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 19  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ ang ┆ n@p ┆     ┆ sit ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ Lin ┆ at  ┆     ┆     ┆ nt  ┆ vs  ┆ sal ┆ org ┆     ┆     ┆     ┆ vs  ┆ aSe ┆     ┆     ┆     ┆ vs  ┆ lin ┆ 727 ┆     ┆     ┆     ┆ ica ┆     ┆ 207 ┆ g   ┆ ica ┆ aSe ┆ aSe ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1.f ┆ RNA ┆     ┆     ┆ RNA ┆ tax ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     ┆ cer │
│     ┆     ┆ wt- ┆ WT- ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ku. ┆     ┆ y   ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ e   ┆ 42  ┆     ┆     ┆     ┆ SAM ┆ V8  ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ q   ┆     ┆     ┆     ┆ 188 ┆ e   ┆ 585 ┆     ┆     ┆     ┆ l   ┆     ┆ 883 ┆ of  ┆ l   ┆ q   ┆ q   ┆ 623 ┆     ┆     ┆     ┆     ┆ WT- ┆ q.g ┆ _se ┆     ┆     ┆ _se ┆ :te ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ nhs ┆ NHS ┆ 573 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ edu ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 573 ┆ .ni ┆     ┆     ┆ 127 ┆     ┆ HeL ┆ °C  ┆     ┆     ┆     ┆ N22 ┆ RNA ┆ .10 ┆     ┆     ┆     ┆ 165 ┆ 600 ┆     ┆     ┆     ┆ 881 ┆     ┆ 337 ┆     ┆     ┆     ┆ rep ┆     ┆ 42  ┆ HeL ┆ rep ┆ 600 ┆ 600 ┆ 650 ┆     ┆     ┆     ┆     ┆ NHS ┆ z   ┆ q2  ┆     ┆     ┆ q2  ┆ rre ┆     ┆     ┆     ┆     ┆ 107 ┆     ┆     ┆     │
│     ┆     ┆ -re ┆ -Re ┆ 983 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .cn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 983 ┆ h.g ┆     ┆     ┆ 574 ┆     ┆ a   ┆ for ┆     ┆     ┆     ┆ 550 ┆ -se ┆ 38/ ┆     ┆     ┆     ┆ 553 ┆ 0   ┆     ┆     ┆     ┆ 056 ┆     ┆ vs  ┆     ┆     ┆     ┆ lic ┆     ┆     ┆ a   ┆ lic ┆ 0   ┆ 0   ┆ 260 ┆     ┆     ┆     ┆     ┆ -Re ┆ vs  ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ 047 ┆     ┆     ┆     │
│     ┆     ┆ p2  ┆ p2  ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ ov/ ┆     ┆     ┆ 48  ┆     ┆ S6  ┆ 60  ┆     ┆     ┆     ┆ 556 ┆ q   ┆ s41 ┆     ┆     ┆     ┆ 23  ┆ seq ┆     ┆     ┆     ┆ 4   ┆     ┆ 134 ┆     ┆     ┆     ┆ ate ┆     ┆     ┆ cel ┆ ate ┆     ┆ seq ┆ 0   ┆     ┆     ┆     ┆     ┆ p2  ┆ WT- ┆     ┆     ┆     ┆     ┆ ial ┆     ┆     ┆     ┆     ┆ 64  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆ lib ┆ 556 ┆     ┆     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ 879 ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ l   ┆ 2   ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ rar ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 123 ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ und ┆ vs  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆ y   ┆ 2-0 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 4;1 ┆     ┆     ┆     ┆ WT- ┆     ┆     ┆ er  ┆ WT- ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ p2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆ pre ┆ 084 ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆ 361 ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆ hea ┆ NHS ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆ R1. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆ p   ┆ 6-7 ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆ 810 ┆     ┆     ┆     ┆ -bi ┆     ┆     ┆ t   ┆ -bi ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆ fq. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 573 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆ 755 ┆     ┆     ┆     ┆ olo ┆     ┆     ┆ sho ┆ olo ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆ gz  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gic ┆     ┆     ┆ ck  ┆ gic ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆     ┆     ┆     ┆     ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆ al  ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆ rep ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 739 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆ lic ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 830 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Va ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆ ate ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zym ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## PRJCA005446 (HRA000922) (RNA-seq)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date 2026-06-26
- perplexity で検索していたところ、たまたま、論文経由からこのデータセットを発見することができた
- [Hyperthermia differentially affects specific human stem cells and their differentiated derivatives](https://doi.org/10.1007/s13238-021-00887-y) の論文のsupplementaly fileに記載してあった
- https://pmc.ncbi.nlm.nih.gov/articles/instance/9232687/bin/13238_2021_887_MOESM1_ESM.pdf
- `RNA-seq library construction and sequencing` セクション に 詳細が記載されているので手作業で追記
- このデータセットはGSA for humanからアクセスできる
- [PRJCA005446](https://ngdc.cncb.ac.cn/bioproject/browse/PRJCA005446)
- [GSA for human のHRA000922](https://ngdc.cncb.ac.cn/gsa-human/browse/HRA000922)

In [12]:
# まずはじめにExcelファイルの各ページを元に統合する
HRA000922_cell_line = pl.read_csv(
    "../../Data/metadata/metadata_gsa/HRA000922_cell_line.csv",
    separator=","
).rename(
    {
        "Accession": "Individual Accession",
        "Cell Line Name": "cell_line"
    }
).drop(
    "Ethnicity",
    "Web Url"
)

HRA000922_sample = pl.read_csv(
    "../../Data/metadata/metadata_gsa/HRA000922_sample.csv",
    separator=","
).drop(
    "Culture Collection",
    "Karyotype",
    "Phenotype",
    "Sample Name",
    "Tissue"
)

HRA000922_combined1 = HRA000922_cell_line.join(
    HRA000922_sample,
    on="Individual Accession",
    how="inner",
    coalesce=True
).rename(
    {
        "Accession": "BioSample accession"
    }
)

pl.Config.set_tbl_rows(4)
display(HRA000922_combined1)

shape: (14, 9)
┌───────────┬───────────┬────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Individua ┆ cell_line ┆ Gender ┆ Tissue   ┆ BioSampl ┆ Public   ┆ Sample   ┆ Collecti ┆ Biomater │
│ l         ┆ ---       ┆ ---    ┆ ---      ┆ e access ┆ Descript ┆ Title    ┆ on Date  ┆ ial      │
│ Accession ┆ str       ┆ str    ┆ str      ┆ ion      ┆ ion      ┆ ---      ┆ ---      ┆ Provider │
│ ---       ┆           ┆        ┆          ┆ ---      ┆ ---      ┆ str      ┆ str      ┆ ---      │
│ str       ┆           ┆        ┆          ┆ str      ┆ str      ┆          ┆          ┆ str      │
╞═══════════╪═══════════╪════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ HRI123466 ┆ human     ┆ male   ┆ embryoni ┆ HRS19210 ┆ hESC     ┆ RNAseq_E ┆ 2019-11- ┆ IBP      │
│           ┆ embryonic ┆        ┆ c stem   ┆ 4        ┆ under 37 ┆ SC_37    ┆ 13       ┆          │
│           ┆ stem cell ┆        ┆ cell     ┆          ┆ degree   ┆          ┆          ┆          │
│           ┆ (hESC)    ┆        ┆          ┆          ┆ at early ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ passage  ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ in       ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ RNAseq   ┆          ┆          ┆          │
│ HRI123466 ┆ human     ┆ male   ┆ embryoni ┆ HRS19210 ┆ hESC     ┆ RNAseq_E ┆ 2019-11- ┆ IBP      │
│           ┆ embryonic ┆        ┆ c stem   ┆ 5        ┆ under 39 ┆ SC_39    ┆ 13       ┆          │
│           ┆ stem cell ┆        ┆ cell     ┆          ┆ degree   ┆          ┆          ┆          │
│           ┆ (hESC)    ┆        ┆          ┆          ┆ at early ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ passage  ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ in       ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ RNAseq   ┆          ┆          ┆          │
│ …         ┆ …         ┆ …      ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ HRI123472 ┆ human     ┆ male   ┆ neuron   ┆ HRS19211 ┆ Neuron   ┆ RNAseq_N ┆ 2019-10- ┆ IBP      │
│           ┆ neuron    ┆        ┆          ┆ 6        ┆ under 37 ┆ euron_37 ┆ 30       ┆          │
│           ┆ (hNeuron) ┆        ┆          ┆          ┆ degree   ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ at early ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ passage  ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ in       ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ RNAseq   ┆          ┆          ┆          │
│ HRI123472 ┆ human     ┆ male   ┆ neuron   ┆ HRS19211 ┆ Neuron   ┆ RNAseq_N ┆ 2019-10- ┆ IBP      │
│           ┆ neuron    ┆        ┆          ┆ 7        ┆ under 39 ┆ euron_39 ┆ 30       ┆          │
│           ┆ (hNeuron) ┆        ┆          ┆          ┆ degree   ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ at early ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ passage  ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ in       ┆          ┆          ┆          │
│           ┆           ┆        ┆          ┆          ┆ RNAseq   ┆          ┆          ┆          │
└───────────┴───────────┴────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

In [13]:
HRA000922_experiment = pl.read_csv(
    "../../Data/metadata/metadata_gsa/HRA000922_experiment.csv",
    separator=","
).drop(
    "Insert size (bp)",
    "Nominal size (bp)",
    "Nominal standard deviation (bp)",
    "Planned number of cycles",
    "Library name"
).rename(
    {
        "Strategy": "library_strategy",
        "Accession": "Experiment accession"
    }
).join(
    HRA000922_combined1,
    on="BioSample accession",
    how="inner",
    coalesce=True
)

pl.Config.set_tbl_rows(4)
display(HRA000922_experiment)

shape: (28, 20)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Exp ┆ Exp ┆ Bio ┆ Bio ┆ Pla ┆ Lib ┆ lib ┆ Sou ┆ Sel ┆ Lay ┆ Rea ┆ Rea ┆ Ind ┆ cel ┆ Gen ┆ Tis ┆ Pub ┆ Sam ┆ Col ┆ Bio │
│ eri ┆ eri ┆ Sam ┆ Sam ┆ tfo ┆ rar ┆ rar ┆ rce ┆ ect ┆ out ┆ d   ┆ d   ┆ ivi ┆ l_l ┆ der ┆ sue ┆ lic ┆ ple ┆ lec ┆ mat │
│ men ┆ men ┆ ple ┆ ple ┆ rm  ┆ y   ┆ y_s ┆ --- ┆ ion ┆ --- ┆ len ┆ len ┆ dua ┆ ine ┆ --- ┆ --- ┆ Des ┆ Tit ┆ tio ┆ eri │
│ t   ┆ t   ┆ nam ┆ acc ┆ --- ┆ Con ┆ tra ┆ str ┆ --- ┆ str ┆ gth ┆ gth ┆ l   ┆ --- ┆ str ┆ str ┆ cri ┆ le  ┆ n   ┆ al  │
│ acc ┆ tit ┆ e   ┆ ess ┆ str ┆ str ┆ teg ┆     ┆ str ┆     ┆ for ┆ for ┆ Acc ┆ str ┆     ┆     ┆ pti ┆ --- ┆ Dat ┆ Pro │
│ ess ┆ le  ┆ --- ┆ ion ┆     ┆ uct ┆ y   ┆     ┆     ┆     ┆ mat ┆ mat ┆ ess ┆     ┆     ┆     ┆ on  ┆ str ┆ e   ┆ vid │
│ ion ┆ --- ┆ str ┆ --- ┆     ┆ ion ┆ --- ┆     ┆     ┆     ┆ e1( ┆ e   ┆ ion ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆ er  │
│ --- ┆ str ┆     ┆ str ┆     ┆ /   ┆ str ┆     ┆     ┆     ┆ bp) ┆ 2(b ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ --- │
│ str ┆     ┆     ┆     ┆     ┆ Exp ┆     ┆     ┆     ┆     ┆ --- ┆ p)  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆ eri ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Des ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ign ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ HRX ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ Bri ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP │
│ 214 ┆ seq ┆ seq ┆ 192 ┆ umi ┆ efl ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     │
│ 074 ┆ _ES ┆ _ES ┆ 104 ┆ na  ┆ y,  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     │
│     ┆ C_3 ┆ C_3 ┆     ┆ HiS ┆ tot ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     │
│     ┆ 7_r ┆ 7   ┆     ┆ eq  ┆ al  ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 37  ┆ 7   ┆     ┆     │
│     ┆ ep1 ┆     ┆     ┆ X   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ Ten ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ -f… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ HRX ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ Bri ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP │
│ 214 ┆ seq ┆ seq ┆ 192 ┆ umi ┆ efl ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     │
│ 075 ┆ _ES ┆ _ES ┆ 104 ┆ na  ┆ y,  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     │
│     ┆ C_3 ┆ C_3 ┆     ┆ HiS ┆ tot ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     │
│     ┆ 7_r ┆ 7   ┆     ┆ eq  ┆ al  ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 37  ┆ 7   ┆     ┆     │
│     ┆ ep2 ┆     ┆     ┆ X   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ Ten ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ -f… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ HRX ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ Bri ┆ RNA ┆ GEN ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ neu ┆ Neu ┆ RNA ┆ 201 ┆ IBP │
│ 214 ┆ seq ┆ seq ┆ 192 ┆ umi ┆ efl ┆ -Se ┆ OMI ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ron ┆ ron ┆ seq ┆ 9-1 ┆     │
│ 100 ┆ _Ne ┆ _Ne ┆ 117 ┆ na  ┆ y,  ┆ q   ┆ C   ┆     ┆     ┆     ┆     ┆ 472 ┆ neu ┆     ┆     ┆ und ┆ _Ne ┆ 0-3 ┆     │
│     ┆ uro ┆ uro ┆     ┆ HiS ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ er  ┆ uro ┆ 0   ┆     │
│     ┆ n_3 ┆ n_3 ┆     ┆ eq  ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hN ┆     ┆     ┆ 39  ┆ n_3 ┆     ┆     │
│     ┆ 9_r ┆ 9   ┆     ┆ X   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eur ┆     ┆     ┆ deg ┆ 9   ┆     ┆     │
│     ┆ ep1 ┆     ┆     ┆ Ten ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆ ree ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ -f… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ HRX ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ Bri ┆ RNA ┆ GEN ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ neu ┆ Neu ┆ RNA ┆ 201 ┆ IBP │
│ 214 ┆ seq ┆ seq ┆ 192 ┆ umi ┆ efl ┆ -Se ┆ OMI ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ron ┆ ron ┆ seq ┆ 9-1 ┆     │
│ 101 ┆ _Ne ┆ _Ne ┆ 117 ┆ na  ┆ y,  ┆ q   ┆ C   ┆     ┆     ┆     ┆     ┆ 472 ┆ neu ┆     ┆     ┆ und ┆ _Ne ┆ 0-3 ┆     │
│     ┆ uro ┆ uro ┆     ┆ HiS ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ er  ┆ uro ┆ 0   ┆     │
│     ┆ n_3 ┆ n_3 ┆     ┆ eq  ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hN ┆     ┆     ┆ 39  ┆ n_3 ┆     ┆     │
│     ┆ 9_r ┆ 9   ┆     ┆ X   ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eur ┆     ┆     ┆ deg ┆ 9   ┆     ┆     │
│     ┆ ep2 ┆     ┆     ┆ Ten ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆ ree ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ext ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ TRI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ zol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ DNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ -f… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [14]:
HRA000922_run = pl.read_csv(
    "../../Data/metadata/metadata_gsa/HRA000922_run.csv",
    separator=","
).drop(
    "Reference file name",
    "MD5 for reference file",
    "Assembly Name or Accession",
    "Assembly Accession URL",
    "File name 1",
    "MD5 checksum 1",
    "DownLoad1",
    "File name 2",
    "MD5 checksum 2",
    "DownLoad2"
).join(
    HRA000922_experiment,
    on="Experiment accession",
    how="inner",
    coalesce=True
).rename(
    {
        "Accession": "accession",
        "Experiment title": "sample_name",
        "BioSample accession": "secondary_sample_accession",
        "Layout": "library_layout",
        "Tissue": "cell_type",
        "Source": "library_source",
        "Public Description": "sample_description",
        "Platform": "instrument_model",
        "Experiment accession": "experiment_accession",
        "Library Construction / Experimental Design": "rna_library",
        "Run title": "sample_title",
        "Sample Title": "sample_alias",
        "Selection": "sample_library_selection",
        "Gender": "sex",
        "Collection Date": "first_public",
        "BioSample name": "experiment_alias"
    }
).with_columns(
    pl.lit("NEBNext® UltraTM Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1007/s13238-021-00887-y").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("39 C").alias("stress treatment temperature"),
    pl.lit("2880 min.").alias("stress treatment time"), # 48 hours
    pl.lit("37 C").alias("control treatment temperature"),
    pl.lit("ILLUMINA").alias("instrument_platform"),
    pl.lit("PRJCA005446").alias("study_accession"),
    pl.lit("PRJCA005446").alias("study_alias"),
    pl.lit("total RNA").alias("sample_molecule_ch1") # add sample_molecule_ch1 column
    
)

HRA000922_run.write_csv(
    "../../Data/metadata/metadata_modified/PRJCA005446_modified_metadata.tsv",
    separator='\t'
)

display(HRA000922_run)

shape: (28, 31)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ acc ┆ sam ┆ exp ┆ Run ┆ sam ┆ exp ┆ sec ┆ ins ┆ rna ┆ lib ┆ lib ┆ sam ┆ lib ┆ Rea ┆ Rea ┆ Ind ┆ cel ┆ sex ┆ cel ┆ sam ┆ sam ┆ fir ┆ Bio ┆ ref ┆ str ┆ str ┆ con ┆ ins ┆ stu ┆ stu ┆ sam │
│ ess ┆ ple ┆ eri ┆ dat ┆ ple ┆ eri ┆ ond ┆ tru ┆ _li ┆ rar ┆ rar ┆ ple ┆ rar ┆ d   ┆ d   ┆ ivi ┆ l_l ┆ --- ┆ l_t ┆ ple ┆ ple ┆ st_ ┆ mat ┆ ere ┆ ess ┆ ess ┆ tro ┆ tru ┆ dy_ ┆ dy_ ┆ ple │
│ ion ┆ _ti ┆ men ┆ a   ┆ _na ┆ men ┆ ary ┆ men ┆ bra ┆ y_s ┆ y_s ┆ _li ┆ y_l ┆ len ┆ len ┆ dua ┆ ine ┆ str ┆ ype ┆ _de ┆ _al ┆ pub ┆ eri ┆ nce ┆ tre ┆ tre ┆ l   ┆ men ┆ acc ┆ ali ┆ _mo │
│ --- ┆ tle ┆ t_a ┆ fil ┆ me  ┆ t_a ┆ _sa ┆ t_m ┆ ry  ┆ tra ┆ our ┆ bra ┆ ayo ┆ gth ┆ gth ┆ l   ┆ --- ┆     ┆ --- ┆ scr ┆ ias ┆ lic ┆ al  ┆ _do ┆ atm ┆ atm ┆ tre ┆ t_p ┆ ess ┆ as  ┆ lec │
│ str ┆ --- ┆ cce ┆ e   ┆ --- ┆ lia ┆ mpl ┆ ode ┆ --- ┆ teg ┆ ce  ┆ ry_ ┆ ut  ┆ for ┆ for ┆ Acc ┆ str ┆     ┆ str ┆ ipt ┆ --- ┆ --- ┆ Pro ┆ i   ┆ ent ┆ ent ┆ atm ┆ lat ┆ ion ┆ --- ┆ ule │
│     ┆ str ┆ ssi ┆ typ ┆ str ┆ s   ┆ e_a ┆ l   ┆ str ┆ y   ┆ --- ┆ sel ┆ --- ┆ mat ┆ mat ┆ ess ┆     ┆     ┆     ┆ ion ┆ str ┆ str ┆ vid ┆ --- ┆ tem ┆ tim ┆ ent ┆ for ┆ --- ┆ str ┆ _ch │
│     ┆     ┆ on  ┆ e   ┆     ┆ --- ┆ cce ┆ --- ┆     ┆ --- ┆ str ┆ ect ┆ str ┆ e1( ┆ e   ┆ ion ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ er  ┆ str ┆ per ┆ e   ┆ tem ┆ m   ┆ str ┆     ┆ 1   │
│     ┆     ┆ --- ┆ --- ┆     ┆ str ┆ ssi ┆ str ┆     ┆ str ┆     ┆ ion ┆     ┆ bp) ┆ 2(b ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ atu ┆ --- ┆ per ┆ --- ┆     ┆     ┆ --- │
│     ┆     ┆ str ┆ str ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆ p)  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ re  ┆ str ┆ atu ┆ str ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 887 ┆ _ES ┆ 074 ┆     ┆ _ES ┆ _ES ┆ 104 ┆ na  ┆ t®  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆ C_3 ┆     ┆     ┆ C_3 ┆ C_3 ┆     ┆ HiS ┆ Ult ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆ 7_r ┆     ┆     ┆ 7_r ┆ 7   ┆     ┆ eq  ┆ raT ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 37  ┆ 7   ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ep1 ┆     ┆     ┆ ep1 ┆     ┆     ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆     ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆     ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆     ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 888 ┆ _ES ┆ 075 ┆     ┆ _ES ┆ _ES ┆ 104 ┆ na  ┆ t®  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆ C_3 ┆     ┆     ┆ C_3 ┆ C_3 ┆     ┆ HiS ┆ Ult ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆ 7_r ┆     ┆     ┆ 7_r ┆ 7   ┆     ┆ eq  ┆ raT ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 37  ┆ 7   ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ep2 ┆     ┆     ┆ ep2 ┆     ┆     ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆     ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆     ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆     ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ GEN ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ neu ┆ Neu ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ OMI ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ron ┆ ron ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 913 ┆ _Ne ┆ 100 ┆     ┆ _Ne ┆ _Ne ┆ 117 ┆ na  ┆ t®  ┆ q   ┆ C   ┆     ┆     ┆     ┆     ┆ 472 ┆ neu ┆     ┆     ┆ und ┆ _Ne ┆ 0-3 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆ uro ┆     ┆     ┆ uro ┆ uro ┆     ┆ HiS ┆ Ult ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ er  ┆ uro ┆ 0   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆ n_3 ┆     ┆     ┆ n_3 ┆ n_3 ┆     ┆ eq  ┆ raT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hN ┆     ┆     ┆ 39  ┆ n_3 ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9_r ┆     ┆     ┆ 9_r ┆ 9   ┆     ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eur ┆     ┆     ┆ deg ┆ 9   ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ep1 ┆     ┆     ┆ ep1 ┆     ┆     ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆ ree ┆     ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ GEN ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ neu ┆ Neu ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ OMI ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ron ┆ ron ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 914 ┆ _Ne ┆ 101 ┆     ┆ _Ne ┆ _Ne ┆ 117 ┆ na  ┆ t®  ┆ q   ┆ C   ┆     ┆     ┆     ┆     ┆ 472 ┆ neu ┆     ┆     ┆ und ┆ _Ne ┆ 0-3 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆ uro ┆     ┆     ┆ uro ┆ uro ┆     ┆ HiS ┆ Ult ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ er  ┆ uro ┆ 0   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆ n_3 ┆     ┆     ┆ n_3 ┆ n_3 ┆     ┆ eq  ┆ raT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hN ┆     ┆     ┆ 39  ┆ n_3 ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 9_r ┆     ┆     ┆ 9_r ┆ 9   ┆     ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eur ┆     ┆     ┆ deg ┆ 9   ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ ep2 ┆     ┆     ┆ ep2 ┆     ┆     ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆ ree ┆     ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [15]:
defined_pairs_hra000922 = [
    ("HRR255889", "HRR255887"), # RNAseq_ESC_39_rep1 vs RNAseq_ESC_37_rep1
    ("HRR255890", "HRR255888"), # RNAseq_ESC_39_rep2 vs RNAseq_ESC_37_rep2
    ("HRR255893", "HRR255891"), # RNAseq_MSC_39_rep1 vs RNAseq_MSC_37_rep1
    ("HRR255894", "HRR255892"), # RNAseq_MSC_39_rep2 vs RNAseq_MSC_37_rep2
    ("HRR255897", "HRR255895"), # RNAseq_NSC_39_rep1 vs RNAseq_NSC_37_rep1
    ("HRR255898", "HRR255896"), # RNAseq_NSC_39_rep2 vs RNAseq_NSC_37_rep2
    ("HRR255901", "HRR255899"), # RNAseq_EC_39_rep1 vs RNAseq_EC_37_rep1
    ("HRR255902", "HRR255900"), # RNAseq_EC_39_rep2 vs RNAseq_EC_37_rep2
    ("HRR255905", "HRR255903"), # RNAseq_VSMC_39_rep1 vs RNAseq_VSMC_37_rep1
    ("HRR255906", "HRR255904"), # RNAseq_VSMC_39_rep2 vs RNAseq_VSMC_37_rep2
    ("HRR255909", "HRR255907"), # RNAseq_CMC_39_rep1 vs RNAseq_CMC_37_rep1
    ("HRR255910", "HRR255908"), # RNAseq_CMC_39_rep2 vs RNAseq_CMC_37_rep2
    ("HRR255913", "HRR255911"), # RNAseq_Neuron_39_rep1 vs RNAseq_Neuron_37_rep1
    ("HRR255914", "HRR255912")  # RNAseq_Neuron_39_rep2 vs RNAseq_Neuron_37_rep2
]

paired_metadata_df_hra000922 = create_paired_metadata(
    combined_df=HRA000922_run,
    defined_sample_pairs=defined_pairs_hra000922,
    sample_id_column_name="accession"
)

# Guard against None so that write_csv is called only on a DataFrame
if paired_metadata_df_hra000922 is not None:
    paired_metadata_df_hra000922.write_csv(
        "../../Data/metadata/metadata_paired/prjca005446_paired_metadata.tsv",
        separator="\t"
    )
    display(paired_metadata_df_hra000922)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (14, 32)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ exp ┆ Run ┆ sam ┆ exp ┆ sec ┆ ins ┆ rna ┆ lib ┆ lib ┆ sam ┆ lib ┆ Rea ┆ Rea ┆ Ind ┆ cel ┆ sex ┆ cel ┆ sam ┆ sam ┆ fir ┆ Bio ┆ ref ┆ str ┆ str ┆ con ┆ ins ┆ stu ┆ stu ┆ sam │
│ ple ┆ ple ┆ ple ┆ eri ┆ dat ┆ ple ┆ eri ┆ ond ┆ tru ┆ _li ┆ rar ┆ rar ┆ ple ┆ rar ┆ d   ┆ d   ┆ ivi ┆ l_l ┆ --- ┆ l_t ┆ ple ┆ ple ┆ st_ ┆ mat ┆ ere ┆ ess ┆ ess ┆ tro ┆ tru ┆ dy_ ┆ dy_ ┆ ple │
│ _he ┆ _co ┆ _ti ┆ men ┆ a   ┆ _na ┆ men ┆ ary ┆ men ┆ bra ┆ y_s ┆ y_s ┆ _li ┆ y_l ┆ len ┆ len ┆ dua ┆ ine ┆ str ┆ ype ┆ _de ┆ _al ┆ pub ┆ eri ┆ nce ┆ tre ┆ tre ┆ l   ┆ men ┆ acc ┆ ali ┆ _mo │
│ at_ ┆ ntr ┆ tle ┆ t_a ┆ fil ┆ me  ┆ t_a ┆ _sa ┆ t_m ┆ ry  ┆ tra ┆ our ┆ bra ┆ ayo ┆ gth ┆ gth ┆ l   ┆ --- ┆     ┆ --- ┆ scr ┆ ias ┆ lic ┆ al  ┆ _do ┆ atm ┆ atm ┆ tre ┆ t_p ┆ ess ┆ as  ┆ lec │
│ id  ┆ ol_ ┆ --- ┆ cce ┆ e   ┆ --- ┆ lia ┆ mpl ┆ ode ┆ --- ┆ teg ┆ ce  ┆ ry_ ┆ ut  ┆ for ┆ for ┆ Acc ┆ str ┆     ┆ str ┆ ipt ┆ --- ┆ --- ┆ Pro ┆ i   ┆ ent ┆ ent ┆ atm ┆ lat ┆ ion ┆ --- ┆ ule │
│ --- ┆ id  ┆ str ┆ ssi ┆ typ ┆ str ┆ s   ┆ e_a ┆ l   ┆ str ┆ y   ┆ --- ┆ sel ┆ --- ┆ mat ┆ mat ┆ ess ┆     ┆     ┆     ┆ ion ┆ str ┆ str ┆ vid ┆ --- ┆ tem ┆ tim ┆ ent ┆ for ┆ --- ┆ str ┆ _ch │
│ str ┆ --- ┆     ┆ on  ┆ e   ┆     ┆ --- ┆ cce ┆ --- ┆     ┆ --- ┆ str ┆ ect ┆ str ┆ e1( ┆ e   ┆ ion ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ er  ┆ str ┆ per ┆ e   ┆ tem ┆ m   ┆ str ┆     ┆ 1   │
│     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ ssi ┆ str ┆     ┆ str ┆     ┆ ion ┆     ┆ bp) ┆ 2(b ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ atu ┆ --- ┆ per ┆ --- ┆     ┆     ┆ --- │
│     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆ p)  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ re  ┆ str ┆ atu ┆ str ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ HRR ┆ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 889 ┆ 887 ┆ _ES ┆ 076 ┆     ┆ _ES ┆ _ES ┆ 105 ┆ na  ┆ t®  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆     ┆ C_3 ┆ vs  ┆     ┆ C_3 ┆ C_3 ┆ vs  ┆ HiS ┆ Ult ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆     ┆ 9_r ┆ HRX ┆     ┆ 9_r ┆ 9   ┆ HRS ┆ eq  ┆ raT ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 39  ┆ 9   ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆ 214 ┆     ┆ ep1 ┆ vs  ┆ 192 ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆ vs  ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ 074 ┆     ┆ vs  ┆ RNA ┆ 104 ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆ RNA ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ RNA ┆     ┆     ┆ RNA ┆ seq ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆ seq ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆ seq ┆ _ES ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆ _ES ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ES ┆     ┆     ┆ _ES ┆ C_3 ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆ C_3 ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C_3 ┆     ┆     ┆ C_3 ┆ 7   ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆ 7   ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7_r ┆     ┆     ┆ 7_r ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hES ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ HRR ┆ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ TRA ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ emb ┆ hES ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ NSC ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ryo ┆ C   ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 890 ┆ 888 ┆ _ES ┆ 077 ┆     ┆ _ES ┆ _ES ┆ 105 ┆ na  ┆ t®  ┆ q   ┆ RIP ┆     ┆     ┆     ┆     ┆ 466 ┆ emb ┆     ┆ nic ┆ und ┆ _ES ┆ 1-1 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆     ┆ C_3 ┆ vs  ┆     ┆ C_3 ┆ C_3 ┆ vs  ┆ HiS ┆ Ult ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆     ┆ ste ┆ er  ┆ C_3 ┆ 3   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆     ┆ 9_r ┆ HRX ┆     ┆ 9_r ┆ 9   ┆ HRS ┆ eq  ┆ raT ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆ nic ┆     ┆ m   ┆ 39  ┆ 9   ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep2 ┆ 214 ┆     ┆ ep2 ┆ vs  ┆ 192 ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ste ┆     ┆ cel ┆ deg ┆ vs  ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ 075 ┆     ┆ vs  ┆ RNA ┆ 104 ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ l   ┆ ree ┆ RNA ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ RNA ┆     ┆     ┆ RNA ┆ seq ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ at  ┆ seq ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆ seq ┆ _ES ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ ear ┆ _ES ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ES ┆     ┆     ┆ _ES ┆ C_3 ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hE ┆     ┆     ┆ ly  ┆ C_3 ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ C_3 ┆     ┆     ┆ C_3 ┆ 7   ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SC) ┆     ┆     ┆ pas ┆ 7   ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7_r ┆     ┆     ┆ 7_r ┆     ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep2 ┆     ┆     ┆ ep2 ┆     ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hES ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ HRR ┆ HRR ┆ RNA ┆ HRX ┆ fas ┆ RNA ┆ RNA ┆ HRS ┆ Ill ┆ NEB ┆ RNA ┆ GEN ┆ oth ┆ PAI ┆ 150 ┆ 150 ┆ HRI ┆ hum ┆ mal ┆ neu ┆ Neu ┆ RNA ┆ 201 ┆ IBP ┆ htt ┆ 39  ┆ 288 ┆ 37  ┆ ILL ┆ PRJ ┆ PRJ ┆ tot │
│ 255 ┆ 255 ┆ seq ┆ 214 ┆ tq  ┆ seq ┆ seq ┆ 192 ┆ umi ┆ Nex ┆ -Se ┆ OMI ┆ er  ┆ RED ┆     ┆     ┆ 123 ┆ an  ┆ e   ┆ ron ┆ ron ┆ seq ┆ 9-1 ┆     ┆ ps: ┆ C   ┆ 0   ┆ C   ┆ UMI ┆ CA0 ┆ CA0 ┆ al  │
│ 913 ┆ 911 ┆ _Ne ┆ 100 ┆     ┆ _Ne ┆ _Ne ┆ 117 ┆ na  ┆ t®  ┆ q   ┆ C   ┆     ┆     ┆     ┆     ┆ 472 ┆ neu ┆     ┆     ┆ und ┆ _Ne ┆ 0-3 ┆     ┆ //d ┆     ┆ min ┆     ┆ NA  ┆ 054 ┆ 054 ┆ RNA │
│     ┆     ┆ uro ┆ vs  ┆     ┆ uro ┆ uro ┆ vs  ┆ HiS ┆ Ult ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆ er  ┆ uro ┆ 0   ┆     ┆ oi. ┆     ┆ .   ┆     ┆     ┆ 46  ┆ 46  ┆     │
│     ┆     ┆ n_3 ┆ HRX ┆     ┆ n_3 ┆ n_3 ┆ HRS ┆ eq  ┆ raT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (hN ┆     ┆     ┆ 39  ┆ n_3 ┆     ┆     ┆ org ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 9_r ┆ 214 ┆     ┆ 9_r ┆ 9   ┆ 192 ┆ X   ┆ M   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eur ┆     ┆     ┆ deg ┆ 9   ┆     ┆     ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆ 098 ┆     ┆ ep1 ┆ vs  ┆ 116 ┆ Ten ┆ Dir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on) ┆     ┆     ┆ ree ┆ vs  ┆     ┆     ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆ vs  ┆ RNA ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ RNA ┆     ┆     ┆ 07/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ RNA ┆     ┆     ┆ RNA ┆ seq ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆ seq ┆     ┆     ┆ s13 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆ seq ┆ _Ne ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆ _Ne ┆     ┆     ┆ 238 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _Ne ┆     ┆     ┆ _Ne ┆ uro ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pas ┆ uro ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ uro ┆     ┆     ┆ uro ┆ n_3 ┆     ┆     ┆ Lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sag ┆ n_3 ┆     ┆     ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ n_3 ┆     ┆     ┆ n_3 ┆ 7   ┆     ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 7   ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7_r ┆     ┆     ┆ 7_r ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ 7-y ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Neu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ron ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Join dataframe

In [16]:
dfs_manual_curation: list[pl.DataFrame | None] = [
    paired_metadata_df_prjdb3999,
    paired_metadata_df_gse278916,
    paired_metadata_df_gse191134,
    paired_metadata_df_hra000922
]

manual_curation: list[pl.DataFrame] = [df for df in dfs_manual_curation if df is not None]

In [17]:
manual_curation_df = pl.concat(manual_curation, how="diagonal_relaxed").drop(
    "Run data file type",
    "fastq_md5"
)

manual_curation_df.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_manual_curation_metadata_{execute_date}.tsv",
    separator='\t'
)

display(manual_curation_df)

shape: (23, 104)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ run ┆ exp ┆ sam ┆ sub ┆ las ┆ sec ┆ sta ┆ exp ┆ cen ┆ fir ┆ exp ┆ stu ┆ sec ┆ fir ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ rec ┆ rec ┆ cel ┆ sam ┆ sam ┆ sam ┆ ins ┆ ins ┆ lib ┆ sam ┆ stu ┆ lib ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ … ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ tre ┆ ass ┆ bio ┆ sra ┆ pro ┆ lib ┆ fas ┆ fas ┆ cou ┆ ncb ┆ sam ┆ rea ┆ stu ┆ fas ┆ sam ┆ des ┆ fas ┆ bas ┆ lib ┆ fas ┆ tax ┆ run ┆ lib ┆ col ┆ cel ┆ lib ┆ tag ┆ sci ┆ tax ┆ sam ┆ sam ┆ gse ┆ cel ┆ gen ┆ gen ┆ sup ┆ sra ┆ iso ┆ sex ┆ tis ┆ Rea ┆ Rea ┆ Ind ┆ Bio │
│ ple ┆ ple ┆ _ac ┆ eri ┆ ple ┆ mis ┆ t_u ┆ ond ┆ tus ┆ eri ┆ ter ┆ st_ ┆ eri ┆ dy_ ┆ ond ┆ st_ ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ ove ┆ ove ┆ l_l ┆ ple ┆ ple ┆ ple ┆ tru ┆ tru ┆ rar ┆ ple ┆ dy_ ┆ rar ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆   ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ atm ┆ emb ┆ sam ┆ --- ┆ jec ┆ rar ┆ tq_ ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ tq_ ┆ _li ┆ _al ┆ rar ┆ lec ┆ l_l ┆ rar ┆ --- ┆ ent ┆ _id ┆ ple ┆ ple ┆ _id ┆ l_t ┆ oty ┆ ome ┆ ple ┆ _by ┆ lat ┆ --- ┆ sue ┆ d   ┆ d   ┆ ivi ┆ mat │
│ _he ┆ _co ┆ ces ┆ men ┆ _ac ┆ sio ┆ pda ┆ ary ┆ --- ┆ men ┆ _na ┆ cre ┆ men ┆ acc ┆ ary ┆ pub ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ry  ┆ ry  ┆ ine ┆ _ti ┆ _al ┆ _de ┆ men ┆ men ┆ y_l ┆ _mo ┆ ali ┆ y_s ┆ _na ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆   ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ent ┆ ly  ┆ ple ┆ str ┆ t_n ┆ y_s ┆ byt ┆ gal ┆ y   ┆ epo ┆ _de ┆ oun ┆ tit ┆ fil ┆ _ti ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ asp ┆ nea ┆ ias ┆ y_c ┆ tio ┆ ine ┆ y_n ┆ str ┆ ifi ┆ --- ┆ _co ┆ _co ┆ --- ┆ ype ┆ pe  ┆ _bu ┆ men ┆ tes ┆ e   ┆ str ┆ _ty ┆ len ┆ len ┆ dua ┆ eri │
│ at_ ┆ ntr ┆ sio ┆ t_t ┆ ces ┆ n_a ┆ ted ┆ _st ┆ str ┆ t_a ┆ me  ┆ ate ┆ t_a ┆ ess ┆ _sa ┆ lic ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ tre ┆ tre ┆ --- ┆ tle ┆ ias ┆ scr ┆ t_m ┆ t_p ┆ ayo ┆ lec ┆ as  ┆ our ┆ me  ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆   ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆     ┆ ame ┆ ele ┆ es  ┆ axy ┆ --- ┆ rti ┆ scr ┆ t   ┆ le  ┆ e_r ┆ tle ┆ on  ┆ --- ┆ t   ┆ tra ┆ era ┆ ge  ┆ --- ┆ ons ┆ n_d ┆ _ri ┆ ame ┆     ┆ c_n ┆ str ┆ nta ┆ nta ┆ str ┆ --- ┆ --- ┆ ild ┆ tar ┆ --- ┆ --- ┆     ┆ pe  ┆ gth ┆ gth ┆ l   ┆ al  │
│ id  ┆ ol_ ┆ n   ┆ itl ┆ sio ┆ cce ┆ --- ┆ udy ┆     ┆ lia ┆ --- ┆ d   ┆ cce ┆ ion ┆ mpl ┆ --- ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ atm ┆ atm ┆ str ┆ --- ┆ --- ┆ ipt ┆ ode ┆ lat ┆ ut  ┆ ule ┆ --- ┆ ce  ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆   ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆     ┆ --- ┆ cti ┆ --- ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ --- ┆ --- ┆ ole ┆ _ri ┆ --- ┆ str ┆ --- ┆ teg ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ ght ┆ --- ┆     ┆ ame ┆     ┆ ct_ ┆ ct_ ┆     ┆ str ┆ str ┆ --- ┆ y_f ┆ str ┆ str ┆     ┆ --- ┆ for ┆ for ┆ Acc ┆ Pro │
│ --- ┆ id  ┆ --- ┆ e   ┆ n   ┆ ssi ┆ str ┆ _ac ┆     ┆ s   ┆ str ┆ --- ┆ ssi ┆ --- ┆ e_a ┆ str ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ ent ┆ ent ┆     ┆ str ┆ str ┆ ion ┆ l   ┆ for ┆ --- ┆ _ch ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _id ┆ nam ┆ ema ┆ dep ┆ ins ┆ add ┆ cit ┆   ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆ str ┆ str ┆     ┆ sta ┆ ion ┆ str ┆ str ┆ --- ┆ ght ┆ str ┆     ┆ str ┆ y   ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ --- ┆ str ┆     ┆ --- ┆     ┆ pho ┆ sta ┆     ┆     ┆     ┆ str ┆ ile ┆     ┆     ┆     ┆ str ┆ mat ┆ mat ┆ ess ┆ vid │
│ str ┆ --- ┆ str ┆ --- ┆ --- ┆ on  ┆     ┆ ces ┆     ┆ --- ┆     ┆ str ┆ on  ┆ str ┆ cce ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ tem ┆ tim ┆     ┆     ┆     ┆ --- ┆ --- ┆ m   ┆ str ┆ 1   ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ art ┆ tit ┆ res ┆ y   ┆   ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ nda ┆ _ri ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ on_ ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆ ne  ┆ te  ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆     ┆     ┆ e1( ┆ e   ┆ ion ┆ er  │
│     ┆ str ┆     ┆ str ┆ str ┆ --- ┆     ┆ sio ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ ssi ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆ per ┆ e   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ men ┆ ute ┆ s   ┆ --- ┆   ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ rd  ┆ ght ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆     ┆ bp) ┆ 2(b ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ n   ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆ t   ┆ --- ┆ --- ┆ str ┆   ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆ --- ┆ p)  ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆   ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ DRR ┆ DRR ┆ DRR ┆ Ill ┆ SAM ┆ DRA ┆ 201 ┆ DRP ┆ pub ┆ DRX ┆ UT_ ┆ 201 ┆ DRX ┆ PRJ ┆ DRS ┆ 201 ┆ mRN ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ 37  ┆ 120 ┆ A54 ┆ HS_ ┆ SAM ┆ Tot ┆ Ill ┆ ILL ┆ SIN ┆ tot ┆ DRP ┆ TRA ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ … ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ 037 ┆ 037 ┆ 037 ┆ umi ┆ D00 ┆ 003 ┆ 7-0 ┆ 005 ┆ lic ┆ 033 ┆ RIC ┆ 5-0 ┆ 033 ┆ DB3 ┆ 093 ┆ 9-0 ┆ A   ┆ ps: ┆ C   ┆ min ┆ C   ┆ C   ┆ min ┆ 9   ┆ wt, ┆ D00 ┆ al  ┆ umi ┆ UMI ┆ GLE ┆ al  ┆ 005 ┆ NSC ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ 194 ┆ 200 ┆ 194 ┆ na  ┆ 032 ┆ 694 ┆ 9-0 ┆ 024 ┆     ┆ 429 ┆     ┆ 6-1 ┆ 429 ┆ 999 ┆ 428 ┆ 4-2 ┆ Seq ┆ //d ┆     ┆ .   ┆ (in ┆     ┆ .   ┆     ┆ A54 ┆ 032 ┆ RNA ┆ na  ┆ NA  ┆     ┆ RNA ┆ 024 ┆ RIP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ HiS ┆ 080 ┆     ┆ 8   ┆     ┆     ┆ vs  ┆     ┆ 2   ┆ vs  ┆     ┆ vs  ┆ 7   ┆ Sam ┆ oi. ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ 9,  ┆ 080 ┆ sam ┆ HiS ┆     ┆     ┆     ┆     ┆ TOM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ DRR ┆ eq  ┆ vs  ┆     ┆     ┆     ┆     ┆ DRX ┆     ┆     ┆ DRX ┆     ┆ DRS ┆     ┆ ple ┆ org ┆     ┆     ┆ red ┆     ┆     ┆     ┆ RNA ┆ vs  ┆ ple ┆ eq  ┆     ┆     ┆     ┆     ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 037 ┆ 250 ┆ SAM ┆     ┆     ┆     ┆     ┆ 033 ┆     ┆     ┆ 033 ┆     ┆ 093 ┆     ┆ Pre ┆ /10 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ -se ┆ SAM ┆ ,   ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 200 ┆ 0   ┆ D00 ┆     ┆     ┆     ┆     ┆ 435 ┆     ┆     ┆ 435 ┆     ┆ 429 ┆     ┆ par ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ D00 ┆ Hea ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ seq ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ 93/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 032 ┆ tSh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ uen ┆ 086 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ jb/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ CTR ┆ 086 ┆ ock ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ mva ┆     ┆     ┆     ┆     ┆     ┆     ┆ L_w ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a12 ┆     ┆     ┆     ┆     ┆     ┆     ┆ t,  ┆     ┆ Tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆ A54 ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SAM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9,  ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ D00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 032 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │