&nbsp;

# Metadata Concat Process

- RNA library の名寄せもここで行う

In [1]:
import datetime

import polars as pl
import pathlib
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_cols(200)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

&nbsp;

&nbsp;

&nbsp;

## RNA library

監査レポート「3. rna_library の表記統一案」に基づく表記辞書を作る。

- 原記載 44 種類（空欄と unknown を含む）を、表記だけの統一で 30 種類にする
- 大文字・小文字、商標記号、kit / Kit、TrueSeq / TruSeq を揃える
- Stranded / Directional、Ultra / Ultra II、mRNA / Total RNA、LT、FWD、rRNA 除去、poly(A) 選択の有無は別ラベルのまま残す
- 抽出・精製キットと委託先は、作製キットと種類を分ける
- 文献照合による訂正は、この表記辞書より監査一覧を優先する

In [3]:
# Notation-only map from audit report section 3.
# Literature corrections in section 2 override this map and are not applied here.
# The em dash in the report is a missing original value, stored as null.
# U+2032 PRIME is kept in the QuantSeq label. Trailing space on the Zymo kit name is part of the recorded string.
rna_library_notation_rows = [
    # TruSeq Stranded 
    {
        "original_rna_library": "TruSeq Stranded Total RNA Library Prep Kit",
        "normalized_label": "TruSeq Stranded Total RNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-total-rna-workflow/truseq-stranded-total-rna-workflow-reference-1000000040499-00.pdf"
    },
    {
        "original_rna_library": "TruSeq stranded total RNA protocol",
        "normalized_label": "TruSeq Stranded Total RNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-total-rna-workflow/truseq-stranded-total-rna-workflow-reference-1000000040499-00.pdf"
    },

    {
        "original_rna_library": "Illumina TruSeq Stranded mRNA Sample Preparation Guide",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf"
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA Library Prep Kit",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf",
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA Library Kit",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf"
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA Library",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf",
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA LT Sample Prep Kit",
        "normalized_label": "TruSeq Stranded mRNA LT Sample Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://ostr.ccr.cancer.gov/wp-content/uploads/2020/05/truseq-stranded-mrna-sample-prep-guide-15031047-e.pdf",
    },
    {
        "original_rna_library": "TruSeq stranded mRNA library preparation kit",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf",
    },
    {
        "original_rna_library": "TruSeq Stranded Total RNA Library Prep Kit (without rRNA depletion)",
        "normalized_label": "TruSeq Stranded Total RNA Library Prep Kit (without rRNA depletion)",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-total-rna-workflow/truseq-stranded-total-rna-workflow-reference-1000000040499-00.pdf",
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA Library Prep Kit (without poly(A) selection)",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit (without poly(A) selection)",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf",
    },
    {
        "original_rna_library": "TruSeq Stranded mRNA assay",
        "normalized_label": "TruSeq Stranded mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_truseq/truseq-stranded-mrna-workflow/truseq-stranded-mrna-workflow-reference-1000000040498-00.pdf",
    },

    # NEBNext Ultra II Directional RNA Library Prep Kit
    {
        "original_rna_library": "NEBNext Ultra II Directional RNA Library Prep Kit",
        "normalized_label": "NEBNext Ultra II Directional RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.neb.com/en-us/products/e7760-nebnext-ultra-ii-directional-rna-library-prep-kit-for-illumina?srsltid=AU7gw4Xlae0blQQ89Otcs2wOzZiRMVMtmTjsIIuOrzEuHSJgMt5ryFNt"
    },
    {
        "original_rna_library": "E7765L NEBNext Ultra II Directional RNA Library Prep with Beads",
        "normalized_label": "NEBNext Ultra II Directional RNA Library Prep with Sample Purification Beads (E7765L)",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.neb.com/en-us/-/media/nebus/files/manuals/manuale7760_e7765.pdf?rev=a5a99045a0bf4ee8afaf80fd2e3653dc&hash=9914BA403C3FD9B5D3D0C9670DF8C765"
    },
    {
        "original_rna_library": "NEBNext Ultra II Directional RNA library preparation kit",
        "normalized_label": "NEBNext Ultra II Directional RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.neb.com/en/products/e7760-nebnext-ultra-ii-directional-rna-library-prep-kit-for-illumina",
    },
    {
        "original_rna_library": "NEBNext® UltraTM Directional RNA Library Prep Kit",
        "normalized_label": "NEBNext Ultra Directional RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.neb.com/en/products/e7420-nebnext-ultra-directional-rna-library-prep-kit-for-illumina",
    },
    {
        "original_rna_library": "NEBNext Ultra II Directional RNA Library Prep Kit for Illumina",
        "normalized_label": "NEBNext Ultra II Directional RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.neb.com/en/products/e7760-nebnext-ultra-ii-directional-rna-library-prep-kit-for-illumina",
    },

    # KAPA Stranded mRNA-Seq Kit
    {
        "original_rna_library": "KAPA mRNA HyperPrep Kit",
        "normalized_label": "KAPA mRNA HyperPrep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://elabdoc-prod.roche.com/eLD/web/global/en/products/SEQ-KAPA-0164?searchTerm=8098115702&catalog=ProductCatalog&orderBy=Relevance&fromResults=true",
    },
    {
        "original_rna_library": "KAPA Stranded mRNA-Seq Kit",
        "normalized_label": "KAPA Stranded mRNA-Seq Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://rochesequencingstore.com/wp-content/uploads/2022/07/KAPA-Stranded-mRNA-Seq-Kit-Technical-Data-Sheet.pdf",
    },
    {
        "original_rna_library": "Hyper Prep RNA sequencing kit",
        "normalized_label": "KAPA RNA HyperPrep Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://rochesequencingstore.com/catalog/kapa-rna-hyperprep-kit/",
    },

    # Other
    {
        "original_rna_library": "SMARTer Stranded Total RNA-Seq Kit v2",
        "normalized_label": "SMARTer Stranded Total RNA-Seq Kit v2",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.takarabio.com/products/next-generation-sequencing/rna-seq/legacy-rna-seq-kits/pico-input-strand-specific-total-rna-seq-for-mammalian-samples-v2",
    },
    {
        "original_rna_library": "SMARTer® Stranded Total RNA-Seq Kit v2—Pico Input Mammalian (634413, Takara – Clontech, Japan)",
        "normalized_label": "SMARTer Stranded Total RNA-Seq Kit v2",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.takarabio.com/products/next-generation-sequencing/rna-seq/legacy-rna-seq-kits/pico-input-strand-specific-total-rna-seq-for-mammalian-samples-v2",
    },
    {
        "original_rna_library": "Lexogen QuantSeq FWD Kit",
        "normalized_label": "QuantSeq 3\u2032 mRNA-Seq Library Prep Kit FWD for Illumina",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.lexogen.com/quantseq-3mRNA%20sequencing/",
    },
    {
        "original_rna_library": "Ovation Universal RNA-Seq System",
        "normalized_label": "Ovation Universal RNA-Seq System",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://doi.org/10.1038/s41467-019-11536-8"
    },
    {
        "original_rna_library": "SureSelect Strand-Specific RNA Library Preparation Kits",
        "normalized_label": "SureSelect Strand-Specific RNA Library Preparation Kit",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://www.agilent.com/cs/library/usermanuals/public/G9691-90010.pdf",
    },

    # MSR-seq (custom mRNA library preparation) (strandness is inferred from the reference paper)
    {
        "original_rna_library": "MSR-seq (custom mRNA library preparation)",
        "normalized_label": "MSR-seq (custom mRNA library preparation)",
        "item_type": "library_preparation",
        "strandness": "stranded",
        "strandness_evidence": "https://doi.org/10.1038/s41467-022-30261-3",
    },


    # unknown / unstranded / conflict / mixed_components
    {
        "original_rna_library": "NEBNext® UltraTM RNA Library Prep Kit for Illumina® (NEB, USA)",
        "normalized_label": "NEBNext Ultra RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "unstranded",
        "strandness_evidence": "https://www.neb.com/en-gb/products/e7530-nebnext-ultra-rna-library-prep-kit-for-illumina",
    },
    {
        "original_rna_library": "NEBNext Ultra II RNA Library Prep Kit for Illumina",
        "normalized_label": "NEBNext Ultra II RNA Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "unstranded",
        "strandness_evidence": "https://www.neb.com/en/products/e7770-nebnext-ultra-ii-rna-library-prep-kit-for-illumina",
    },

    {
        "original_rna_library": "VAHTS Universal V6 RNA-seq Library Prep Kit",
        "normalized_label": "VAHTS Universal V6 RNA-seq Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "https://www.lifesct.com/download/Manuals/NR604-VAHTS-Universal-V6-RNA-seq-Library-Prep-Kit.pdf",
    },

    {
        "original_rna_library": "TruSeq RNA Sample Preparation Kit",
        "normalized_label": "TruSeq RNA Sample Preparation Kit (version unspecified)",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "VAHTS mRNA-seq v2 Library Prep Kit for Illumina",
        "normalized_label": "VAHTS mRNA-seq v2 Library Prep Kit for Illumina",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },

    {
        "original_rna_library": "TruSeq mRNA Library Prep Kit",
        "normalized_label": "TruSeq mRNA Library Prep Kit",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "TruSeq stranded mRNA library prep kit (Illumina) (from GEO) / Illumina TruSeq RNA Sample Prep v2 Kit (from article)",
        "normalized_label": "conflict",
        "item_type": "library_preparation",
        "strandness": "conflict",
        "strandness_evidence": "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM6914924; https://doi.org/10.1038/s41467-023-43262-7",
    },
    {
        "original_rna_library": "Illumina protocol",
        "normalized_label": "Illumina protocol (specific kit unspecified)",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": (
            "VAHTS universal V8 RNA-seq library prep kit for Illumina "
            "(Vazyme, cat. no. NR605) and KAPA HyperPrep kit (Roche, cat. no. KR0961)"
        ),
        "normalized_label": (
            "VAHTS Universal V8 RNA-seq Library Prep Kit for Illumina "
            "(Vazyme, cat. no. NR605) & KAPA HyperPrep kit (Roche, cat. no. KR0961)"
        ),
        "item_type": "mixed_components",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "Truseq RNA prep kit",
        "normalized_label": "TruSeq RNA (product/version unspecified)",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "Illumina kit (TruSeq RNA)",
        "normalized_label": "TruSeq RNA (product/version unspecified)",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "mRNA Seq Sample Preparation Kit",
        "normalized_label": "mRNA Seq Sample Preparation Kit",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "Illumina TruSeq RNA sample preparation guide (specific kit/version unspecified)",
        "normalized_label": "TruSeq RNA (product/version unspecified)",
        "item_type": "library_preparation",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": "unknown",
        "normalized_label": "unknown",
        "item_type": "missing",
        "strandness": "unknown",
        "strandness_evidence": "",
    },
    {
        "original_rna_library": None,
        "normalized_label": "unknown",
        "item_type": "missing",
        "strandness": "unknown",
        "strandness_evidence": "",
    }
]

rna_library_notation = pl.DataFrame(rna_library_notation_rows)

# None is the key for a blank original value.
rna_library_notation_dict = dict(
    zip(
        rna_library_notation["original_rna_library"].to_list(),
        rna_library_notation["normalized_label"].to_list(),
        strict=True,
    )
)

# if rna_library_notation.height != 43:
#     raise ValueError(f"expected 44 original labels, got {rna_library_notation.height}")
# if rna_library_notation["original_rna_library"].n_unique() != 43:
#     raise ValueError("original labels are not unique")
# if rna_library_notation["normalized_label"].n_unique() != 30:
#     raise ValueError(
#         f"expected 30 normalized labels, got {rna_library_notation['normalized_label'].n_unique()}"
#     )
# if len(rna_library_notation_dict) != 43:
#     raise ValueError("notation dict dropped a key")

notation_summary = rna_library_notation.group_by("item_type").agg(
    pl.len().alias("n_original_labels"),
    pl.col("normalized_label").n_unique().alias("n_normalized_labels"),
).sort("item_type")


display(rna_library_notation)
display(notation_summary)

shape: (40, 5)
┌─────────────────────┬─────────────────────┬────────────────────┬────────────┬────────────────────┐
│ original_rna_librar ┆ normalized_label    ┆ item_type          ┆ strandness ┆ strandness_evidenc │
│ y                   ┆ ---                 ┆ ---                ┆ ---        ┆ e                  │
│ ---                 ┆ str                 ┆ str                ┆ str        ┆ ---                │
│ str                 ┆                     ┆                    ┆            ┆ str                │
╞═════════════════════╪═════════════════════╪════════════════════╪════════════╪════════════════════╡
│ TruSeq Stranded     ┆ TruSeq Stranded     ┆ library_preparatio ┆ stranded   ┆ https://support.il │
│ Total RNA Library   ┆ Total RNA Library   ┆ n                  ┆            ┆ lumina.com/content │
│ Prep Kit            ┆ Prep Kit            ┆                    ┆            ┆ /dam/illumina-supp │
│                     ┆                     ┆                    ┆            ┆ ort/documents/docu │
│                     ┆                     ┆                    ┆            ┆ mentation/chemistr │
│                     ┆                     ┆                    ┆            ┆ y_documentation/sa │
│                     ┆                     ┆                    ┆            ┆ mplepreps_truseq/t │
│                     ┆                     ┆                    ┆            ┆ ruseq-stranded-tot │
│                     ┆                     ┆                    ┆            ┆ al-rna-workflow/tr │
│                     ┆                     ┆                    ┆            ┆ useq-stranded-tota │
│                     ┆                     ┆                    ┆            ┆ l-rna-workflow-ref │
│                     ┆                     ┆                    ┆            ┆ er…                │
│ TruSeq stranded     ┆ TruSeq Stranded     ┆ library_preparatio ┆ stranded   ┆ https://support.il │
│ total RNA protocol  ┆ Total RNA Library   ┆ n                  ┆            ┆ lumina.com/content │
│                     ┆ Prep Kit            ┆                    ┆            ┆ /dam/illumina-supp │
│                     ┆                     ┆                    ┆            ┆ ort/documents/docu │
│                     ┆                     ┆                    ┆            ┆ mentation/chemistr │
│                     ┆                     ┆                    ┆            ┆ y_documentation/sa │
│                     ┆                     ┆                    ┆            ┆ mplepreps_truseq/t │
│                     ┆                     ┆                    ┆            ┆ ruseq-stranded-tot │
│                     ┆                     ┆                    ┆            ┆ al-rna-workflow/tr │
│                     ┆                     ┆                    ┆            ┆ useq-stranded-tota │
│                     ┆                     ┆                    ┆            ┆ l-rna-workflow-ref │
│                     ┆                     ┆                    ┆            ┆ er…                │
│ …                   ┆ …                   ┆ …                  ┆ …          ┆ …                  │
│ unknown             ┆ unknown             ┆ missing            ┆ unknown    ┆                    │
│ null                ┆ unknown             ┆ missing            ┆ unknown    ┆                    │
└─────────────────────┴─────────────────────┴────────────────────┴────────────┴────────────────────┘

shape: (3, 3)
┌─────────────────────┬───────────────────┬─────────────────────┐
│ item_type           ┆ n_original_labels ┆ n_normalized_labels │
│ ---                 ┆ ---               ┆ ---                 │
│ str                 ┆ u32               ┆ u32                 │
╞═════════════════════╪═══════════════════╪═════════════════════╡
│ library_preparation ┆ 37                ┆ 26                  │
│ missing             ┆ 2                 ┆ 1                   │
│ mixed_components    ┆ 1                 ┆ 1                   │
└─────────────────────┴───────────────────┴─────────────────────┘

&nbsp;

&nbsp;

## 1. Concat Process (2026-09-30)

- bulk RNA-seqデータのメタデータをconcatする
- 一旦全てのカラムを含めて `concat`

In [4]:
true_control = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_true_control_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

true_no_control = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_true_no_control_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

false_control = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_false_control_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

false_no_control = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_false_no_control_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

bioprolect_biostudies = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_bioproject_biostudies_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

manual_curation = pl.read_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_manual_curation_metadata_{execute_date}.tsv",
    separator="\t",
    ignore_errors=True
)

In [5]:
rna_seq_all_metadata = pl.concat(
    [
        true_control,
        true_no_control,
        false_control,
        false_no_control,
        bioprolect_biostudies,
        manual_curation
    ],
    how="diagonal_relaxed"
)

rna_seq_all_metadata = rna_seq_all_metadata[[s.name for s in rna_seq_all_metadata if not (s.null_count() == rna_seq_all_metadata.height)]]

rna_seq_all_metadata.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_all_metadata_{execute_date}_no_filter.tsv",
    separator="\t"
)

display(rna_seq_all_metadata)

shape: (406, 179)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ map ┆ exp ┆ deg ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ sam ┆ sam ┆ tis ┆ bio ┆ tis ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ pas ┆ phe ┆ rep ┆ gen ┆ cen ┆ sam ┆ sam ┆ sam ┆ dis ┆ str ┆ sam ┆ tum ┆ sex ┆ age ┆ sam ┆ sam ┆ cel ┆ sam ┆ tim ┆ lib ┆ sam ┆ sir ┆ con ┆ tis ┆ ant ┆ bat ┆ col ┆ lib ┆ sam ┆ cen ┆ str ┆ fra ┆ enz ┆ rt_ ┆ str ┆ tre ┆ mol ┆ iso ┆ iso ┆ dos ┆ exp ┆ tim ┆ vec ┆ sir ┆ sra ┆ fas ┆ tag ┆ sci ┆ tax ┆ acc ┆ col ┆ col ┆ sub ┆ sub ┆ sub ┆ sub ┆ che ┆ sub ┆ nom ┆ bro ┆ dat ┆ nom ┆ sub ┆ sub ┆ bam ┆ bam ┆ dev ┆ bam ┆ bam ┆ bam ┆ sub ┆ rec ┆ rec ┆ sam ┆ bio ┆ sra ┆ fas ┆ fas ┆ fas ┆ tax ┆ Rea ┆ Rea ┆ Ind ┆ Bio │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ pin ┆ res ┆ _an ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ ple ┆ ple ┆ sue ┆ log ┆ sue ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ sag ┆ not ┆ lic ┆ ome ┆ ter ┆ ple ┆ ple ┆ ple ┆ eas ┆ ess ┆ ple ┆ or  ┆ --- ┆ --- ┆ ple ┆ ple ┆ l_m ┆ ple ┆ e   ┆ rar ┆ ple ┆ na  ┆ dit ┆ sue ┆ ibo ┆ ch  ┆ umn ┆ rar ┆ ple ┆ tri ┆ ain ┆ cti ┆ yme ┆ con ┆ ain ┆ atm ┆ ecu ┆ lat ┆ lat ┆ age ┆ eri ┆ epo ┆ tor ┆ na_ ┆ _fi ┆ tq_ ┆ --- ┆ ent ┆ _id ┆ ess ┆ lec ┆ lec ┆ mit ┆ mit ┆ mit ┆ mit ┆ ckl ┆ mit ┆ ina ┆ ker ┆ ahu ┆ ina ┆ mit ┆ mit ┆ _ft ┆ _by ┆ _st ┆ _as ┆ _ga ┆ _fi ┆ mit ┆ ove ┆ ove ┆ ple ┆ sam ┆ --- ┆ tq_ ┆ tq_ ┆ tq_ ┆ _li ┆ d   ┆ d   ┆ ivi ┆ mat │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ g   ┆ sio ┆ aly ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _da ┆ _co ┆ --- ┆ ica ┆ _ty ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _co ┆ e   ┆ ype ┆ ate ┆ _bu ┆ _na ┆ _co ┆ _su ┆ _su ┆ e   ┆ --- ┆ _co ┆ --- ┆ str ┆ str ┆ _tr ┆ _gr ┆ ode ┆ _ex ┆ --- ┆ y_s ┆ _gr ┆ --- ┆ ion ┆ _ce ┆ dy  ┆ --- ┆ --- ┆ y_n ┆ _ch ┆ fug ┆ --- ┆ on  ┆ _ch ┆ dit ┆ _ri ┆ ent ┆ le  ┆ e   ┆ e_r ┆ --- ┆ men ┆ int ┆ --- ┆ sgr ┆ le_ ┆ fil ┆ str ┆ ifi ┆ --- ┆ ion ┆ tio ┆ tio ┆ ted ┆ ted ┆ ted ┆ ted ┆ ist ┆ ted ┆ l_s ┆ _na ┆ b   ┆ l_l ┆ ted ┆ ted ┆ p   ┆ tes ┆ age ┆ per ┆ lax ┆ le_ ┆ ted ┆ ry  ┆ ry  ┆ _se ┆ ple ┆ str ┆ gal ┆ ftp ┆ asp ┆ nea ┆ len ┆ len ┆ dua ┆ eri │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ n_e ┆ sis ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ ta_ ┆ nta ┆ str ┆ l_r ┆ pe  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ nta ┆ --- ┆ --- ┆ --- ┆ ild ┆ me  ┆ nta ┆ ppl ┆ ppl ┆ --- ┆ str ┆ nta ┆ str ┆     ┆     ┆ eat ┆ oup ┆ l   ┆ tra ┆ str ┆ tra ┆ owt ┆ str ┆ --- ┆ lls ┆ --- ┆ i64 ┆ str ┆ ame ┆ ara ┆ e   ┆ str ┆ --- ┆ emi ┆ ion ┆ ght ┆ _co ┆ --- ┆ --- ┆ igh ┆ str ┆ t   ┆ --- ┆ str ┆ na  ┆ rol ┆ e_r ┆     ┆ c_n ┆ i64 ┆ --- ┆ n_d ┆ n_d ┆ _ga ┆ _ft ┆ _as ┆ _md ┆ --- ┆ _by ┆ dev ┆ me  ┆ --- ┆ eng ┆ _re ┆ _fo ┆ --- ┆ --- ┆ --- ┆ a   ┆ y   ┆ rol ┆ _fi ┆ tre ┆ tre ┆ rie ┆ --- ┆     ┆ axy ┆ --- ┆ era ┆ ge  ┆ gth ┆ gth ┆ l   ┆ al  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sti ┆ --- ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ pro ┆ ct_ ┆     ┆ epl ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ ct_ ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆ ct_ ┆ eme ┆ eme ┆ str ┆     ┆ ct_ ┆     ┆     ┆     ┆ men ┆ --- ┆ --- ┆ ct_ ┆     ┆ teg ┆ h_p ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ _ri ┆ cte ┆ --- ┆     ┆ str ┆ cal ┆ --- ┆ --- ┆ ndi ┆ str ┆ str ┆ t   ┆     ┆ --- ┆ str ┆     ┆ --- ┆ e   ┆ ole ┆     ┆ ame ┆     ┆ str ┆ ate ┆ ate ┆ lax ┆ p   ┆ per ┆ 5   ┆ str ┆ tes ┆ --- ┆ --- ┆ str ┆ th  ┆ ad_ ┆ rma ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ e   ┆ le_ ┆ atm ┆ atm ┆ s_i ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ for ┆ for ┆ Acc ┆ Pro │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ mat ┆ str ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ ces ┆ ema ┆     ┆ ica ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ dep ┆     ┆     ┆     ┆ str ┆ str ┆ lab ┆ nta ┆ nta ┆     ┆     ┆ pho ┆     ┆     ┆     ┆ t_p ┆ str ┆ str ┆ pro ┆     ┆ y_r ┆ rot ┆     ┆     ┆ str ┆     ┆     ┆     ┆ ght ┆ ris ┆ str ┆     ┆     ┆ _tr ┆ str ┆ str ┆ tio ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ _en ┆ _st ┆ y   ┆ --- ┆ a   ┆ --- ┆     ┆ --- ┆ i64 ┆ str ┆     ┆ --- ┆ typ ┆ t   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆ rol ┆ ent ┆ ent ┆ d   ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆ mat ┆ mat ┆ ess ┆ vid │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆ sin ┆ il  ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ art ┆     ┆     ┆     ┆     ┆     ┆ ora ┆ ry_ ┆ ry_ ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆ rot ┆     ┆     ┆ toc ┆     ┆ igh ┆ oco ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tic ┆     ┆     ┆     ┆ eat ┆     ┆     ┆ ns  ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ d   ┆ art ┆ --- ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ i64 ┆ e   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆ tem ┆ tim ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ e1( ┆ e   ┆ ion ┆ er  │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆ g   ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ fil ┆ fil ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ oco ┆     ┆     ┆ ol_ ┆     ┆ t   ┆ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ s_c ┆     ┆     ┆     ┆ men ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ per ┆ e   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ bp) ┆ 2(b ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ e_2 ┆ e_3 ┆     ┆     ┆ str ┆     ┆     ┆     ┆ l_c ┆     ┆     ┆ ch1 ┆     ┆ --- ┆ h1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ p)  ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆ --- ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ WI- ┆ Hom ┆ 960 ┆ tot ┆ 40C ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ WI- ┆ imm ┆ WT  ┆ hea ┆ STA ┆ RSE ┆ edg ┆ UCS ┆ exc ┆ SAM ┆ Tru ┆ htt ┆ 40  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ His ┆ SRA ┆ cDN ┆ 202 ┆ 670 ┆ 116 ┆ ILL ┆ mis ┆ Gen ┆ WI- ┆ SRP ┆ 360 ┆ His ┆ WI- ┆ Ill ┆ Ill ┆ imm ┆ 238 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ WI- ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. Strandness

- strandness 情報を結合する

In [6]:
rna_library_notation4join = rna_library_notation.rename(
    {
        "original_rna_library": "rna_library"
    }
)

display(rna_library_notation4join)

shape: (40, 5)
┌─────────────────────┬─────────────────────┬────────────────────┬────────────┬────────────────────┐
│ rna_library         ┆ normalized_label    ┆ item_type          ┆ strandness ┆ strandness_evidenc │
│ ---                 ┆ ---                 ┆ ---                ┆ ---        ┆ e                  │
│ str                 ┆ str                 ┆ str                ┆ str        ┆ ---                │
│                     ┆                     ┆                    ┆            ┆ str                │
╞═════════════════════╪═════════════════════╪════════════════════╪════════════╪════════════════════╡
│ TruSeq Stranded     ┆ TruSeq Stranded     ┆ library_preparatio ┆ stranded   ┆ https://support.il │
│ Total RNA Library   ┆ Total RNA Library   ┆ n                  ┆            ┆ lumina.com/content │
│ Prep Kit            ┆ Prep Kit            ┆                    ┆            ┆ /dam/illumina-supp │
│                     ┆                     ┆                    ┆            ┆ ort/documents/docu │
│                     ┆                     ┆                    ┆            ┆ mentation/chemistr │
│                     ┆                     ┆                    ┆            ┆ y_documentation/sa │
│                     ┆                     ┆                    ┆            ┆ mplepreps_truseq/t │
│                     ┆                     ┆                    ┆            ┆ ruseq-stranded-tot │
│                     ┆                     ┆                    ┆            ┆ al-rna-workflow/tr │
│                     ┆                     ┆                    ┆            ┆ useq-stranded-tota │
│                     ┆                     ┆                    ┆            ┆ l-rna-workflow-ref │
│                     ┆                     ┆                    ┆            ┆ er…                │
│ TruSeq stranded     ┆ TruSeq Stranded     ┆ library_preparatio ┆ stranded   ┆ https://support.il │
│ total RNA protocol  ┆ Total RNA Library   ┆ n                  ┆            ┆ lumina.com/content │
│                     ┆ Prep Kit            ┆                    ┆            ┆ /dam/illumina-supp │
│                     ┆                     ┆                    ┆            ┆ ort/documents/docu │
│                     ┆                     ┆                    ┆            ┆ mentation/chemistr │
│                     ┆                     ┆                    ┆            ┆ y_documentation/sa │
│                     ┆                     ┆                    ┆            ┆ mplepreps_truseq/t │
│                     ┆                     ┆                    ┆            ┆ ruseq-stranded-tot │
│                     ┆                     ┆                    ┆            ┆ al-rna-workflow/tr │
│                     ┆                     ┆                    ┆            ┆ useq-stranded-tota │
│                     ┆                     ┆                    ┆            ┆ l-rna-workflow-ref │
│                     ┆                     ┆                    ┆            ┆ er…                │
│ …                   ┆ …                   ┆ …                  ┆ …          ┆ …                  │
│ unknown             ┆ unknown             ┆ missing            ┆ unknown    ┆                    │
│ null                ┆ unknown             ┆ missing            ┆ unknown    ┆                    │
└─────────────────────┴─────────────────────┴────────────────────┴────────────┴────────────────────┘

In [7]:
rna_seq_all_metadata_library_notation = rna_seq_all_metadata.join(
    rna_library_notation4join,
    on="rna_library",
    how="left"
)

display(rna_seq_all_metadata_library_notation)

shape: (406, 183)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ map ┆ exp ┆ deg ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ sam ┆ sam ┆ tis ┆ bio ┆ tis ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ pas ┆ phe ┆ rep ┆ gen ┆ cen ┆ sam ┆ sam ┆ sam ┆ dis ┆ str ┆ sam ┆ tum ┆ sex ┆ age ┆ sam ┆ sam ┆ cel ┆ sam ┆ tim ┆ lib ┆ sam ┆ sir ┆ con ┆ tis ┆ ant ┆ bat ┆ col ┆ lib ┆ sam ┆ cen ┆ str ┆ fra ┆ enz ┆ rt_ ┆ str ┆ tre ┆ mol ┆ iso ┆ iso ┆ dos ┆ exp ┆ tim ┆ vec ┆ sir ┆ sra ┆ fas ┆ tag ┆ sci ┆ tax ┆ acc ┆ col ┆ col ┆ sub ┆ sub ┆ sub ┆ sub ┆ che ┆ sub ┆ nom ┆ bro ┆ dat ┆ nom ┆ sub ┆ sub ┆ bam ┆ bam ┆ dev ┆ bam ┆ bam ┆ bam ┆ sub ┆ rec ┆ rec ┆ sam ┆ bio ┆ sra ┆ fas ┆ fas ┆ fas ┆ tax ┆ Rea ┆ Rea ┆ Ind ┆ Bio ┆ nor ┆ ite ┆ str ┆ str │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ pin ┆ res ┆ _an ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ ple ┆ ple ┆ sue ┆ log ┆ sue ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ sag ┆ not ┆ lic ┆ ome ┆ ter ┆ ple ┆ ple ┆ ple ┆ eas ┆ ess ┆ ple ┆ or  ┆ --- ┆ --- ┆ ple ┆ ple ┆ l_m ┆ ple ┆ e   ┆ rar ┆ ple ┆ na  ┆ dit ┆ sue ┆ ibo ┆ ch  ┆ umn ┆ rar ┆ ple ┆ tri ┆ ain ┆ cti ┆ yme ┆ con ┆ ain ┆ atm ┆ ecu ┆ lat ┆ lat ┆ age ┆ eri ┆ epo ┆ tor ┆ na_ ┆ _fi ┆ tq_ ┆ --- ┆ ent ┆ _id ┆ ess ┆ lec ┆ lec ┆ mit ┆ mit ┆ mit ┆ mit ┆ ckl ┆ mit ┆ ina ┆ ker ┆ ahu ┆ ina ┆ mit ┆ mit ┆ _ft ┆ _by ┆ _st ┆ _as ┆ _ga ┆ _fi ┆ mit ┆ ove ┆ ove ┆ ple ┆ sam ┆ --- ┆ tq_ ┆ tq_ ┆ tq_ ┆ _li ┆ d   ┆ d   ┆ ivi ┆ mat ┆ mal ┆ m_t ┆ and ┆ and │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ g   ┆ sio ┆ aly ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _da ┆ _co ┆ --- ┆ ica ┆ _ty ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _co ┆ e   ┆ ype ┆ ate ┆ _bu ┆ _na ┆ _co ┆ _su ┆ _su ┆ e   ┆ --- ┆ _co ┆ --- ┆ str ┆ str ┆ _tr ┆ _gr ┆ ode ┆ _ex ┆ --- ┆ y_s ┆ _gr ┆ --- ┆ ion ┆ _ce ┆ dy  ┆ --- ┆ --- ┆ y_n ┆ _ch ┆ fug ┆ --- ┆ on  ┆ _ch ┆ dit ┆ _ri ┆ ent ┆ le  ┆ e   ┆ e_r ┆ --- ┆ men ┆ int ┆ --- ┆ sgr ┆ le_ ┆ fil ┆ str ┆ ifi ┆ --- ┆ ion ┆ tio ┆ tio ┆ ted ┆ ted ┆ ted ┆ ted ┆ ist ┆ ted ┆ l_s ┆ _na ┆ b   ┆ l_l ┆ ted ┆ ted ┆ p   ┆ tes ┆ age ┆ per ┆ lax ┆ le_ ┆ ted ┆ ry  ┆ ry  ┆ _se ┆ ple ┆ str ┆ gal ┆ ftp ┆ asp ┆ nea ┆ len ┆ len ┆ dua ┆ eri ┆ ize ┆ ype ┆ nes ┆ nes │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ n_e ┆ sis ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ ta_ ┆ nta ┆ str ┆ l_r ┆ pe  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ nta ┆ --- ┆ --- ┆ --- ┆ ild ┆ me  ┆ nta ┆ ppl ┆ ppl ┆ --- ┆ str ┆ nta ┆ str ┆     ┆     ┆ eat ┆ oup ┆ l   ┆ tra ┆ str ┆ tra ┆ owt ┆ str ┆ --- ┆ lls ┆ --- ┆ i64 ┆ str ┆ ame ┆ ara ┆ e   ┆ str ┆ --- ┆ emi ┆ ion ┆ ght ┆ _co ┆ --- ┆ --- ┆ igh ┆ str ┆ t   ┆ --- ┆ str ┆ na  ┆ rol ┆ e_r ┆     ┆ c_n ┆ i64 ┆ --- ┆ n_d ┆ n_d ┆ _ga ┆ _ft ┆ _as ┆ _md ┆ --- ┆ _by ┆ dev ┆ me  ┆ --- ┆ eng ┆ _re ┆ _fo ┆ --- ┆ --- ┆ --- ┆ a   ┆ y   ┆ rol ┆ _fi ┆ tre ┆ tre ┆ rie ┆ --- ┆     ┆ axy ┆ --- ┆ era ┆ ge  ┆ gth ┆ gth ┆ l   ┆ al  ┆ d_l ┆ --- ┆ s   ┆ s_e │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ sti ┆ --- ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ pro ┆ ct_ ┆     ┆ epl ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ ct_ ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆ ct_ ┆ eme ┆ eme ┆ str ┆     ┆ ct_ ┆     ┆     ┆     ┆ men ┆ --- ┆ --- ┆ ct_ ┆     ┆ teg ┆ h_p ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ _ri ┆ cte ┆ --- ┆     ┆ str ┆ cal ┆ --- ┆ --- ┆ ndi ┆ str ┆ str ┆ t   ┆     ┆ --- ┆ str ┆     ┆ --- ┆ e   ┆ ole ┆     ┆ ame ┆     ┆ str ┆ ate ┆ ate ┆ lax ┆ p   ┆ per ┆ 5   ┆ str ┆ tes ┆ --- ┆ --- ┆ str ┆ th  ┆ ad_ ┆ rma ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ e   ┆ le_ ┆ atm ┆ atm ┆ s_i ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ for ┆ for ┆ Acc ┆ Pro ┆ abe ┆ str ┆ --- ┆ vid │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ mat ┆ str ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ ces ┆ ema ┆     ┆ ica ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ dep ┆     ┆     ┆     ┆ str ┆ str ┆ lab ┆ nta ┆ nta ┆     ┆     ┆ pho ┆     ┆     ┆     ┆ t_p ┆ str ┆ str ┆ pro ┆     ┆ y_r ┆ rot ┆     ┆     ┆ str ┆     ┆     ┆     ┆ ght ┆ ris ┆ str ┆     ┆     ┆ _tr ┆ str ┆ str ┆ tio ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ _en ┆ _st ┆ y   ┆ --- ┆ a   ┆ --- ┆     ┆ --- ┆ i64 ┆ str ┆     ┆ --- ┆ typ ┆ t   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆ rol ┆ ent ┆ ent ┆ d   ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆ mat ┆ mat ┆ ess ┆ vid ┆ l   ┆     ┆ str ┆ enc │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆ sin ┆ il  ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ art ┆     ┆     ┆     ┆     ┆     ┆ ora ┆ ry_ ┆ ry_ ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆ rot ┆     ┆     ┆ toc ┆     ┆ igh ┆ oco ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tic ┆     ┆     ┆     ┆ eat ┆     ┆     ┆ ns  ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ d   ┆ art ┆ --- ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ i64 ┆ e   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆ tem ┆ tim ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ e1( ┆ e   ┆ ion ┆ er  ┆ --- ┆     ┆     ┆ e   │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆ g   ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ fil ┆ fil ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ oco ┆     ┆     ┆ ol_ ┆     ┆ t   ┆ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ s_c ┆     ┆     ┆     ┆ men ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ per ┆ e   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ bp) ┆ 2(b ┆ --- ┆ --- ┆ str ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ e_2 ┆ e_3 ┆     ┆     ┆ str ┆     ┆     ┆     ┆ l_c ┆     ┆     ┆ ch1 ┆     ┆ --- ┆ h1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ p)  ┆ str ┆ str ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆ --- ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ WI- ┆ Hom ┆ 960 ┆ tot ┆ 40C ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ WI- ┆ imm ┆ WT  ┆ hea ┆ STA ┆ RSE ┆ edg ┆ UCS ┆ exc ┆ SAM ┆ Tru ┆ htt ┆ 40  ┆ 120 ┆ 37  ┆ SRR ┆ Ill ┆ His ┆ SRA ┆ cDN ┆ 202 ┆ 670 ┆ 116 ┆ ILL ┆ mis ┆ Gen ┆ WI- ┆ SRP ┆ 360 ┆ His ┆ WI- ┆ Ill ┆ Ill ┆ imm ┆ 238 ┆ RNA ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ GSM ┆ WI- ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Tru ┆ lib ┆ str ┆ htt │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. Clean Up

- 重要な情報を左側に集めるため、一旦 `core` データフレームとして選抜し、その後、join する

In [8]:
rna_seq_all_metadata_core = rna_seq_all_metadata_library_notation.select(
    "sample_heat_id",
    "sample_control_id",
    "sample_name",
    "sample_title",
    # columns with a value in every row
    "experiment_accession",
    "experiment_alias",
    "secondary_sample_accession",
    "study_accession",
    "first_public",
    "study_alias",
    "instrument_platform",
    "instrument_model",
    "library_source",
    "library_layout",
    "sample_molecule_ch1",
    "cell_line",
    "stress treatment temperature",
    "stress treatment time",
    "control treatment temperature",
    "rna_library",
    "normalized_label",
    "item_type",
    "reference_doi",
    "strandness",
    "strandness_evidence"
).rename(
    {
        "cell_line": "sample"
    }
)

display(rna_seq_all_metadata_core)

shape: (406, 25)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ exp ┆ exp ┆ sec ┆ stu ┆ fir ┆ stu ┆ ins ┆ ins ┆ lib ┆ lib ┆ sam ┆ sam ┆ str ┆ str ┆ con ┆ rna ┆ nor ┆ ite ┆ ref ┆ str ┆ str │
│ ple ┆ ple ┆ ple ┆ ple ┆ eri ┆ eri ┆ ond ┆ dy_ ┆ st_ ┆ dy_ ┆ tru ┆ tru ┆ rar ┆ rar ┆ ple ┆ ple ┆ ess ┆ ess ┆ tro ┆ _li ┆ mal ┆ m_t ┆ ere ┆ and ┆ and │
│ _he ┆ _co ┆ _na ┆ _ti ┆ men ┆ men ┆ ary ┆ acc ┆ pub ┆ ali ┆ men ┆ men ┆ y_s ┆ y_l ┆ _mo ┆ --- ┆ tre ┆ tre ┆ l   ┆ bra ┆ ize ┆ ype ┆ nce ┆ nes ┆ nes │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ t_a ┆ t_a ┆ _sa ┆ ess ┆ lic ┆ as  ┆ t_p ┆ t_m ┆ our ┆ ayo ┆ lec ┆ str ┆ atm ┆ atm ┆ tre ┆ ry  ┆ d_l ┆ --- ┆ _do ┆ s   ┆ s_e │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ lia ┆ mpl ┆ ion ┆ --- ┆ --- ┆ lat ┆ ode ┆ ce  ┆ ut  ┆ ule ┆     ┆ ent ┆ ent ┆ atm ┆ --- ┆ abe ┆ str ┆ i   ┆ --- ┆ vid │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ s   ┆ e_a ┆ --- ┆ str ┆ str ┆ for ┆ l   ┆ --- ┆ --- ┆ _ch ┆     ┆ tem ┆ tim ┆ ent ┆ str ┆ l   ┆     ┆ --- ┆ str ┆ enc │
│ str ┆ --- ┆     ┆     ┆ on  ┆ --- ┆ cce ┆ str ┆     ┆     ┆ m   ┆ --- ┆ str ┆ str ┆ 1   ┆     ┆ per ┆ e   ┆ tem ┆     ┆ --- ┆     ┆ str ┆     ┆ e   │
│     ┆ str ┆     ┆     ┆ --- ┆ str ┆ ssi ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆     ┆     ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ SRX ┆ GSM ┆ SRS ┆ PRJ ┆ 202 ┆ GSE ┆ ILL ┆ Ill ┆ TRA ┆ SIN ┆ tot ┆ WI- ┆ 40  ┆ 120 ┆ 37  ┆ Tru ┆ Tru ┆ lib ┆ htt ┆ str ┆ htt │
│ 276 ┆ 276 ┆ 38- ┆ 38- ┆ 233 ┆ 802 ┆ 202 ┆ NA1 ┆ 4-1 ┆ 253 ┆ UMI ┆ umi ┆ NSC ┆ GLE ┆ al  ┆ 38- ┆ C   ┆ min ┆ C   ┆ Seq ┆ Seq ┆ rar ┆ ps: ┆ and ┆ ps: │
│ 819 ┆ 819 ┆ hte ┆ hTE ┆ 492 ┆ 968 ┆ 106 ┆ 067 ┆ 0-1 ┆ 874 ┆ NA  ┆ na  ┆ RIP ┆     ┆ RNA ┆ hTE ┆     ┆ .   ┆     ┆ Str ┆ Str ┆ y_p ┆ //d ┆ ed  ┆ //s │
│ 84  ┆ 86  ┆ rt_ ┆ RT, ┆ 32  ┆ 8_r ┆ 16  ┆ 599 ┆ 6   ┆     ┆     ┆ HiS ┆ TOM ┆     ┆     ┆ RT  ┆     ┆     ┆     ┆ and ┆ and ┆ rep ┆ oi. ┆     ┆ upp │
│     ┆     ┆ 40° ┆ 40° ┆ vs  ┆ 1   ┆ vs  ┆     ┆     ┆     ┆     ┆ eq  ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ ara ┆ org ┆     ┆ ort │
│     ┆     ┆ c_r ┆ C,  ┆ SRX ┆ vs  ┆ SRS ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tot ┆ Tot ┆ tio ┆ /10 ┆     ┆ .il │
│     ┆     ┆ na- ┆ RNA ┆ 233 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ al  ┆ n   ┆ .11 ┆     ┆ lum │
│     ┆     ┆ seq ┆ -se ┆ 492 ┆ 802 ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ RNA ┆     ┆ 11/ ┆     ┆ ina │
│     ┆     ┆ _re ┆ q,  ┆ 30  ┆ 968 ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆ Lib ┆     ┆ gtc ┆     ┆ .co │
│     ┆     ┆ p1  ┆ rep ┆     ┆ 6_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ rar ┆     ┆ .13 ┆     ┆ m/c │
│     ┆     ┆ vs  ┆ 1   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ y   ┆     ┆ 140 ┆     ┆ ont │
│     ┆     ┆ wi- ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆ Pre ┆     ┆     ┆     ┆ ent │
│     ┆     ┆ 38- ┆ WI- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆ p   ┆     ┆     ┆     ┆ /da │
│     ┆     ┆ hte ┆ 38- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ Kit ┆     ┆     ┆     ┆ m/i │
│     ┆     ┆ rt_ ┆ hTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ llu │
│     ┆     ┆ 37° ┆ RT, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min │
│     ┆     ┆ c_r ┆ 37° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a-s │
│     ┆     ┆ na- ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ upp │
│     ┆     ┆ seq ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ort │
│     ┆     ┆ _re ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /do │
│     ┆     ┆ p1  ┆ q,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cum │
│     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent │
│     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ocu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tat │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ch │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ emi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y_d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ocu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tat │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ epr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eps │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _tr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ use │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/t │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rus │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rna │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -wo │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rkf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /tr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ use │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q-s │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nde │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d-t │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ota │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-r │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kfl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ow- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ref │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er… │
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ SRX ┆ GSM ┆ SRS ┆ PRJ ┆ 202 ┆ GSE ┆ ILL ┆ Ill ┆ TRA ┆ SIN ┆ tot ┆ WI- ┆ 40  ┆ 120 ┆ 37  ┆ Tru ┆ Tru ┆ lib ┆ htt ┆ str ┆ htt │
│ 276 ┆ 276 ┆ 38- ┆ 38- ┆ 233 ┆ 802 ┆ 202 ┆ NA1 ┆ 4-1 ┆ 253 ┆ UMI ┆ umi ┆ NSC ┆ GLE ┆ al  ┆ 38- ┆ C   ┆ min ┆ C   ┆ Seq ┆ Seq ┆ rar ┆ ps: ┆ and ┆ ps: │
│ 819 ┆ 819 ┆ hte ┆ hTE ┆ 492 ┆ 968 ┆ 106 ┆ 067 ┆ 0-1 ┆ 874 ┆ NA  ┆ na  ┆ RIP ┆     ┆ RNA ┆ hTE ┆     ┆ .   ┆     ┆ Str ┆ Str ┆ y_p ┆ //d ┆ ed  ┆ //s │
│ 83  ┆ 85  ┆ rt_ ┆ RT, ┆ 33  ┆ 9_r ┆ 15  ┆ 599 ┆ 6   ┆     ┆     ┆ HiS ┆ TOM ┆     ┆     ┆ RT  ┆     ┆     ┆     ┆ and ┆ and ┆ rep ┆ oi. ┆     ┆ upp │
│     ┆     ┆ 40° ┆ 40° ┆ vs  ┆ 1   ┆ vs  ┆     ┆     ┆     ┆     ┆ eq  ┆ IC  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ ed  ┆ ara ┆ org ┆     ┆ ort │
│     ┆     ┆ c_r ┆ C,  ┆ SRX ┆ vs  ┆ SRS ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tot ┆ Tot ┆ tio ┆ /10 ┆     ┆ .il │
│     ┆     ┆ na- ┆ RNA ┆ 233 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ al  ┆ n   ┆ .11 ┆     ┆ lum │
│     ┆     ┆ seq ┆ -se ┆ 492 ┆ 802 ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ RNA ┆     ┆ 11/ ┆     ┆ ina │
│     ┆     ┆ _re ┆ q,  ┆ 31  ┆ 968 ┆ 17  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆ Lib ┆     ┆ gtc ┆     ┆ .co │
│     ┆     ┆ p2  ┆ rep ┆     ┆ 7_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ rar ┆     ┆ .13 ┆     ┆ m/c │
│     ┆     ┆ vs  ┆ 2   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ y   ┆     ┆ 140 ┆     ┆ ont │
│     ┆     ┆ wi- ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆ Pre ┆     ┆     ┆     ┆ ent │
│     ┆     ┆ 38- ┆ WI- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆ p   ┆     ┆     ┆     ┆ /da │
│     ┆     ┆ hte ┆ 38- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ Kit ┆     ┆     ┆     ┆ m/i │
│     ┆     ┆ rt_ ┆ hTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ llu │
│     ┆     ┆ 37° ┆ RT, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min │
│     ┆     ┆ c_r ┆ 37° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a-s │
│     ┆     ┆ na- ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ upp │
│     ┆     ┆ seq ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ort │
│     ┆     ┆ _re ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /do │
│     ┆     ┆ p2  ┆ q,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cum │
│     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ent │
│     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s/d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ocu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tat │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ch │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ emi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y_d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ocu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tat │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ epr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eps │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _tr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ use │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/t │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rus │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tot │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rna │

In [9]:
rna_seq_all_metadata_core.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_all_metadata_simple_{execute_date}.tsv",
    separator="\t"
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. JOIN

- `rna_seq_all_metadata_core` をキーに、`rna_seq_all_metadata_library_notation` と `join` する

In [10]:
rna_seq_all_metadata_all_columns = rna_seq_all_metadata_core.join(
    rna_seq_all_metadata_library_notation.rename(
        {
            "cell_line": "sample"
        }
    ),
    on=rna_seq_all_metadata_core.columns, # use every core column as a join key
    how="inner",
    nulls_equal=True, # treat null == null so rows with a null key still match
    validate="1:1"
)

rna_seq_all_metadata_all_columns.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/rna_seq_all_metadata_all_columns_{execute_date}.tsv",
    separator="\t"
)

display(rna_seq_all_metadata_all_columns)

shape: (406, 183)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ exp ┆ exp ┆ sec ┆ stu ┆ fir ┆ stu ┆ ins ┆ ins ┆ lib ┆ lib ┆ sam ┆ sam ┆ str ┆ str ┆ con ┆ rna ┆ nor ┆ ite ┆ ref ┆ str ┆ str ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ cel ┆ gen ┆ tre ┆ map ┆ exp ┆ deg ┆ ass ┆ sup ┆ sam ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ cou ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ des ┆ cel ┆ bas ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ col ┆ cel ┆ lib ┆ fir ┆ sam ┆ sam ┆ tis ┆ bio ┆ tis ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ pas ┆ phe ┆ rep ┆ gen ┆ cen ┆ sam ┆ sam ┆ sam ┆ dis ┆ str ┆ sam ┆ tum ┆ sex ┆ age ┆ sam ┆ sam ┆ cel ┆ sam ┆ tim ┆ lib ┆ sam ┆ sir ┆ con ┆ tis ┆ ant ┆ bat ┆ col ┆ lib ┆ sam ┆ cen ┆ str ┆ fra ┆ enz ┆ rt_ ┆ str ┆ tre ┆ mol ┆ iso ┆ iso ┆ dos ┆ exp ┆ tim ┆ vec ┆ sir ┆ sra ┆ fas ┆ tag ┆ sci ┆ tax ┆ acc ┆ col ┆ col ┆ sub ┆ sub ┆ sub ┆ sub ┆ che ┆ sub ┆ nom ┆ bro ┆ dat ┆ nom ┆ sub ┆ sub ┆ bam ┆ bam ┆ dev ┆ bam ┆ bam ┆ bam ┆ sub ┆ rec ┆ rec ┆ sam ┆ bio ┆ sra ┆ fas ┆ fas ┆ fas ┆ tax ┆ Rea ┆ Rea ┆ Ind ┆ Bio │
│ ple ┆ ple ┆ ple ┆ ple ┆ eri ┆ eri ┆ ond ┆ dy_ ┆ st_ ┆ dy_ ┆ tru ┆ tru ┆ rar ┆ rar ┆ ple ┆ ple ┆ ess ┆ ess ┆ tro ┆ _li ┆ mal ┆ m_t ┆ ere ┆ and ┆ and ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ l_t ┆ oty ┆ atm ┆ pin ┆ res ┆ _an ┆ emb ┆ ple ┆ ple ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ lec ┆ l_l ┆ rar ┆ st_ ┆ ple ┆ ple ┆ sue ┆ log ┆ sue ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ sag ┆ not ┆ lic ┆ ome ┆ ter ┆ ple ┆ ple ┆ ple ┆ eas ┆ ess ┆ ple ┆ or  ┆ --- ┆ --- ┆ ple ┆ ple ┆ l_m ┆ ple ┆ e   ┆ rar ┆ ple ┆ na  ┆ dit ┆ sue ┆ ibo ┆ ch  ┆ umn ┆ rar ┆ ple ┆ tri ┆ ain ┆ cti ┆ yme ┆ con ┆ ain ┆ atm ┆ ecu ┆ lat ┆ lat ┆ age ┆ eri ┆ epo ┆ tor ┆ na_ ┆ _fi ┆ tq_ ┆ --- ┆ ent ┆ _id ┆ ess ┆ lec ┆ lec ┆ mit ┆ mit ┆ mit ┆ mit ┆ ckl ┆ mit ┆ ina ┆ ker ┆ ahu ┆ ina ┆ mit ┆ mit ┆ _ft ┆ _by ┆ _st ┆ _as ┆ _ga ┆ _fi ┆ mit ┆ ove ┆ ove ┆ ple ┆ sam ┆ --- ┆ tq_ ┆ tq_ ┆ tq_ ┆ _li ┆ d   ┆ d   ┆ ivi ┆ mat │
│ _he ┆ _co ┆ _na ┆ _ti ┆ men ┆ men ┆ ary ┆ acc ┆ pub ┆ ali ┆ men ┆ men ┆ y_s ┆ y_l ┆ _mo ┆ --- ┆ tre ┆ tre ┆ l   ┆ bra ┆ ize ┆ ype ┆ nce ┆ nes ┆ nes ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ ype ┆ pe  ┆ ent ┆ g   ┆ sio ┆ aly ┆ ly  ┆ men ┆ _ac ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ y   ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ pti ┆ ype ┆ oun ┆ y_s ┆ --- ┆ _al ┆ ias ┆ y_c ┆ tio ┆ ine ┆ y_n ┆ cre ┆ _da ┆ _co ┆ --- ┆ ica ┆ _ty ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _co ┆ e   ┆ ype ┆ ate ┆ _bu ┆ _na ┆ _co ┆ _su ┆ _su ┆ e   ┆ --- ┆ _co ┆ --- ┆ str ┆ str ┆ _tr ┆ _gr ┆ ode ┆ _ex ┆ --- ┆ y_s ┆ _gr ┆ --- ┆ ion ┆ _ce ┆ dy  ┆ --- ┆ --- ┆ y_n ┆ _ch ┆ fug ┆ --- ┆ on  ┆ _ch ┆ dit ┆ _ri ┆ ent ┆ le  ┆ e   ┆ e_r ┆ --- ┆ men ┆ int ┆ --- ┆ sgr ┆ le_ ┆ fil ┆ str ┆ ifi ┆ --- ┆ ion ┆ tio ┆ tio ┆ ted ┆ ted ┆ ted ┆ ted ┆ ist ┆ ted ┆ l_s ┆ _na ┆ b   ┆ l_l ┆ ted ┆ ted ┆ p   ┆ tes ┆ age ┆ per ┆ lax ┆ le_ ┆ ted ┆ ry  ┆ ry  ┆ _se ┆ ple ┆ str ┆ gal ┆ ftp ┆ asp ┆ nea ┆ len ┆ len ┆ dua ┆ eri │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ t_a ┆ t_a ┆ _sa ┆ ess ┆ lic ┆ as  ┆ t_p ┆ t_m ┆ our ┆ ayo ┆ lec ┆ str ┆ atm ┆ atm ┆ tre ┆ ry  ┆ d_l ┆ --- ┆ _do ┆ s   ┆ s_e ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ n_e ┆ sis ┆ --- ┆ tar ┆ ces ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ --- ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ on  ┆ _ri ┆ t   ┆ tra ┆ str ┆ ias ┆ --- ┆ ons ┆ n_d ┆ _ri ┆ ame ┆ ate ┆ ta_ ┆ nta ┆ str ┆ l_r ┆ pe  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ nta ┆ --- ┆ --- ┆ --- ┆ ild ┆ me  ┆ nta ┆ ppl ┆ ppl ┆ --- ┆ str ┆ nta ┆ str ┆     ┆     ┆ eat ┆ oup ┆ l   ┆ tra ┆ str ┆ tra ┆ owt ┆ str ┆ --- ┆ lls ┆ --- ┆ i64 ┆ str ┆ ame ┆ ara ┆ e   ┆ str ┆ --- ┆ emi ┆ ion ┆ ght ┆ _co ┆ --- ┆ --- ┆ igh ┆ str ┆ t   ┆ --- ┆ str ┆ na  ┆ rol ┆ e_r ┆     ┆ c_n ┆ i64 ┆ --- ┆ n_d ┆ n_d ┆ _ga ┆ _ft ┆ _as ┆ _md ┆ --- ┆ _by ┆ dev ┆ me  ┆ --- ┆ eng ┆ _re ┆ _fo ┆ --- ┆ --- ┆ --- ┆ a   ┆ y   ┆ rol ┆ _fi ┆ tre ┆ tre ┆ rie ┆ --- ┆     ┆ axy ┆ --- ┆ era ┆ ge  ┆ gth ┆ gth ┆ l   ┆ al  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ lia ┆ mpl ┆ ion ┆ --- ┆ --- ┆ lat ┆ ode ┆ ce  ┆ ut  ┆ ule ┆     ┆ ent ┆ ent ┆ atm ┆ --- ┆ abe ┆ str ┆ i   ┆ --- ┆ vid ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ str ┆ str ┆ str ┆ str ┆ sti ┆ --- ┆ str ┆ y_f ┆ sio ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ --- ┆ ght ┆ --- ┆ teg ┆     ┆ --- ┆ str ┆ tru ┆ ate ┆ ght ┆ --- ┆ d   ┆ pro ┆ ct_ ┆     ┆ epl ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ ct_ ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆ ct_ ┆ eme ┆ eme ┆ str ┆     ┆ ct_ ┆     ┆     ┆     ┆ men ┆ --- ┆ --- ┆ ct_ ┆     ┆ teg ┆ h_p ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ _ri ┆ cte ┆ --- ┆     ┆ str ┆ cal ┆ --- ┆ --- ┆ ndi ┆ str ┆ str ┆ t   ┆     ┆ --- ┆ str ┆     ┆ --- ┆ e   ┆ ole ┆     ┆ ame ┆     ┆ str ┆ ate ┆ ate ┆ lax ┆ p   ┆ per ┆ 5   ┆ str ┆ tes ┆ --- ┆ --- ┆ str ┆ th  ┆ ad_ ┆ rma ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ e   ┆ le_ ┆ atm ┆ atm ┆ s_i ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ for ┆ for ┆ Acc ┆ Pro │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ s   ┆ e_a ┆ --- ┆ str ┆ str ┆ for ┆ l   ┆ --- ┆ --- ┆ _ch ┆     ┆ tem ┆ tim ┆ ent ┆ str ┆ l   ┆     ┆ --- ┆ str ┆ enc ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆     ┆     ┆     ┆     ┆ mat ┆ str ┆     ┆ ile ┆ n   ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆     ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ str ┆ --- ┆ str ┆ y   ┆     ┆ str ┆     ┆ cti ┆ --- ┆ --- ┆ str ┆ --- ┆ ces ┆ ema ┆     ┆ ica ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ dep ┆     ┆     ┆     ┆ str ┆ str ┆ lab ┆ nta ┆ nta ┆     ┆     ┆ pho ┆     ┆     ┆     ┆ t_p ┆ str ┆ str ┆ pro ┆     ┆ y_r ┆ rot ┆     ┆     ┆ str ┆     ┆     ┆     ┆ ght ┆ ris ┆ str ┆     ┆     ┆ _tr ┆ str ┆ str ┆ tio ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ _en ┆ _st ┆ y   ┆ --- ┆ a   ┆ --- ┆     ┆ --- ┆ i64 ┆ str ┆     ┆ --- ┆ typ ┆ t   ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆ rol ┆ ent ┆ ent ┆ d   ┆     ┆     ┆ str ┆     ┆ str ┆ str ┆ mat ┆ mat ┆ ess ┆ vid │
│ str ┆ --- ┆     ┆     ┆ on  ┆ --- ┆ cce ┆ str ┆     ┆     ┆ m   ┆ --- ┆ str ┆ str ┆ 1   ┆     ┆ per ┆ e   ┆ tem ┆     ┆ --- ┆     ┆ str ┆     ┆ e   ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ s_f ┆ --- ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆     ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆ on_ ┆ str ┆ str ┆     ┆ str ┆ sin ┆ il  ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ art ┆     ┆     ┆     ┆     ┆     ┆ ora ┆ ry_ ┆ ry_ ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆ rot ┆     ┆     ┆ toc ┆     ┆ igh ┆ oco ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tic ┆     ┆     ┆     ┆ eat ┆     ┆     ┆ ns  ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆ d   ┆ art ┆ --- ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ i64 ┆ e   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆ tem ┆ tim ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ e1( ┆ e   ┆ ion ┆ er  │
│     ┆ str ┆     ┆     ┆ --- ┆ str ┆ ssi ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ orm ┆ str ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆ g   ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ fil ┆ fil ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ oco ┆     ┆     ┆ ol_ ┆     ┆ t   ┆ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ s_c ┆     ┆     ┆     ┆ men ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ per ┆ e   ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ bp) ┆ 2(b ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ e_2 ┆ e_3 ┆     ┆     ┆ str ┆     ┆     ┆     ┆ l_c ┆     ┆     ┆ ch1 ┆     ┆ --- ┆ h1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ atu ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ p)  ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ h1  ┆     ┆     ┆ --- ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ wi- ┆ WI- ┆ SRX ┆ GSM ┆ SRS ┆ PRJ ┆ 202 ┆ GSE ┆ ILL ┆ Ill ┆ TRA ┆ SIN ┆ tot ┆ WI- ┆ 40  ┆ 120 ┆ 37  ┆ Tru ┆ Tru ┆ lib ┆ htt ┆ str ┆ htt ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ WI- ┆ Hom ┆ 960 ┆ 40C ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ cDN ┆ tra ┆ RNA ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ imm ┆ WT  ┆ hea ┆ STA ┆ RSE ┆ edg ┆ UCS ┆ exc ┆ SAM ┆ SRR ┆ Ill ┆ His ┆ SRA ┆ cDN ┆ 202 ┆ 670 ┆ 116 ┆ mis ┆ Gen ┆ WI- ┆ SRP ┆ 360 ┆ His ┆ WI- ┆ Ill ┆ imm ┆ 238 ┆ RNA ┆ pub ┆ GSM ┆ GSM ┆ Tot ┆ mis ┆ WI- ┆ GSM ┆ 202 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │