&nbsp;

# `salmon quant` result parse notebook

- `salmon` によって 発現定量を行った RNA-sequencing (RNA-seq) の ライブラリーの推定や、定量結果のメタデータをデータフレームとして parse するための notebook
- [salmon の LIBTYPE](https://salmon.readthedocs.io/en/latest/salmon.html#what-s-this-libtype) の判定結果が記載してある `lib_format_counts.json` をデータフレームとしてまとめていく
- About `lib_format_counts.json` -> [Salmon lib_format_counts.json - explanation](https://www.biostars.org/p/9556263/)

In [1]:
import os
import pathlib

import plotly.express as px
import polars as pl
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
os.environ["POLARS_MAX_THREADS"] = "16"

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Metadata

In [2]:
rnaseq_all_metadata = pl.read_csv(
    "../../Data/metadata/metadata_2610/rna_seq_all_metadata_simple_261001.tsv",
    separator="\t",
    ignore_errors=True
)

pl.Config.set_tbl_rows(2)
display(rnaseq_all_metadata)

shape: (406, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ sample_ti ┆ … ┆ item_type ┆ reference ┆ strandnes ┆ strandne │
│ at_id     ┆ ntrol_id  ┆ me        ┆ tle       ┆   ┆ ---       ┆ _doi      ┆ s         ┆ ss_evide │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ nce      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ SRR276819 ┆ wi-38-hte ┆ WI-38-hTE ┆ … ┆ library_p ┆ https://d ┆ stranded  ┆ https:// │
│ 84        ┆ 86        ┆ rt_40°c_r ┆ RT, 40°C, ┆   ┆ reparatio ┆ oi.org/10 ┆           ┆ support. │
│           ┆           ┆ na-seq_re ┆ RNA-seq,  ┆   ┆ n         ┆ .1111/gtc ┆           ┆ illumina │
│           ┆           ┆ p1 vs wi- ┆ rep1 vs   ┆   ┆           ┆ .13140    ┆           ┆ .com/con │
│           ┆           ┆ 38-htert_ ┆ WI-38-hTE ┆   ┆           ┆           ┆           ┆ tent/dam │
│           ┆           ┆ 37°c_rna- ┆ RT, 37°C, ┆   ┆           ┆           ┆           ┆ /illumin │
│           ┆           ┆ seq_rep1  ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆ a-suppor │
│           ┆           ┆           ┆ rep1      ┆   ┆           ┆           ┆           ┆ t/docume │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ nts/docu │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ mentatio │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ n/chemis │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ try_docu │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ mentatio │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ n/sample │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ preps_tr │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ useq/tru │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ seq-stra │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ nded-tot │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ al-rna-w │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ orkflow/ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ truseq-s │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tranded- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ total-rn │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ a-workfl │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ow-refer │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255914 ┆ HRR255912 ┆ RNAseq_Ne ┆ RNAseq_Ne ┆ … ┆ library_p ┆ https://d ┆ stranded  ┆ https:// │
│           ┆           ┆ uron_39_r ┆ uron_39_r ┆   ┆ reparatio ┆ oi.org/10 ┆           ┆ www.neb. │
│           ┆           ┆ ep2 vs    ┆ ep2 vs    ┆   ┆ n         ┆ .1007/s13 ┆           ┆ com/en/p │
│           ┆           ┆ RNAseq_Ne ┆ RNAseq_Ne ┆   ┆           ┆ 238-021-0 ┆           ┆ roducts/ │
│           ┆           ┆ uron_37_r ┆ uron_37_r ┆   ┆           ┆ 0887-y    ┆           ┆ e7420-ne │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆ bnext-ul │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tra-dire │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ctional- │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ rna-libr │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ary-prep │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -kit-for │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -illumin │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ a        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

## ALL Metadata Parse Process

- メタデータの `sample_heat_id` と `sample_control_id` から unique な sample ID を取り出す
- `out/salmon_gencode_result` 配下の `{sample_id}` / `{sample_id}_1` / `{sample_id}_2` ディレクトリにある `lib_format_counts.json` を探す
- PE 定量は mate-1 FASTQ 名に合わせて `_1` が付くことが多く、一部サンプルは `_2` になる
- 各 JSON を読み込み、Polars DataFrame として縦方向に concat する

In [3]:
# Unique sample IDs from heat / control columns (one row per accession)
unique_sample_ids = (
    rnaseq_all_metadata
    .select("sample_heat_id", "sample_control_id")
    .unpivot(
        on=["sample_heat_id", "sample_control_id"],
        variable_name="sample_role",
        value_name="sample_id",
    )
    .drop_nulls("sample_id")
    .select("sample_id")
    .unique(maintain_order=True)
)

pl.Config.set_tbl_rows(2)
print(f"unique sample IDs: {unique_sample_ids.height}")
display(unique_sample_ids)

unique sample IDs: 744

shape: (744, 1)
┌─────────────┐
│ sample_id   │
│ ---         │
│ str         │
╞═════════════╡
│ SRR27681984 │
│ …           │
│ HRR255912   │
└─────────────┘

In [4]:
# Index lib_format_counts.json paths, then map directory names to metadata sample_id.
# Prefer an exact directory match; otherwise accept "{sample_id}_1" or "{sample_id}_2"
# (PE quant often uses mate FASTQ names; a few SE samples use _2).
SALMON_RESULT_ROOT = pathlib.Path("../../out/salmon_gencode_result")
json_paths = sorted(SALMON_RESULT_ROOT.glob("*/*/lib_format_counts.json"))

json_index = pl.DataFrame(
    {
        "lib_format_json_path": [str(p) for p in json_paths],
        "quant_dir_name": [p.parent.name for p in json_paths],
        "quant_layout": [p.parent.parent.name for p in json_paths],
    }
)

json_by_sample_id = pl.concat(
    [
        json_index.with_columns(pl.col("quant_dir_name").alias("sample_id")),
        json_index.filter(pl.col("quant_dir_name").str.ends_with("_1")).with_columns(
            pl.col("quant_dir_name").str.strip_suffix("_1").alias("sample_id")
        ),
        json_index.filter(pl.col("quant_dir_name").str.ends_with("_2")).with_columns(
            pl.col("quant_dir_name").str.strip_suffix("_2").alias("sample_id")
        ),
    ],
    how="vertical",
).unique(subset="sample_id", keep="first", maintain_order=True)

sample_json = unique_sample_ids.join(
    json_by_sample_id,
    on="sample_id",
    how="left",
    maintain_order="left",
)

found_lib_format = sample_json.filter(pl.col("lib_format_json_path").is_not_null())
missing_lib_format = sample_json.filter(pl.col("lib_format_json_path").is_null())

print(f"json files under salmon_gencode_result: {json_index.height}")
print(f"matched to metadata: {found_lib_format.height}")
print(f"metadata IDs without json: {missing_lib_format.height}")
display(found_lib_format)
display(missing_lib_format)

json files under salmon_gencode_result: 900
matched to metadata: 744
metadata IDs without json: 0

shape: (744, 4)
┌─────────────┬─────────────────────────────────┬────────────────┬─────────────────────────────────┐
│ sample_id   ┆ lib_format_json_path            ┆ quant_dir_name ┆ quant_layout                    │
│ ---         ┆ ---                             ┆ ---            ┆ ---                             │
│ str         ┆ str                             ┆ str            ┆ str                             │
╞═════════════╪═════════════════════════════════╪════════════════╪═════════════════════════════════╡
│ SRR27681984 ┆ ../../out/salmon_gencode_result ┆ SRR27681984    ┆ HS_human_salmon_quant_se_gencod │
│             ┆ /HS_human_salmon_quant_se_genco ┆                ┆ e                               │
│             ┆ de/SRR27681984/lib_format_count ┆                ┆                                 │
│             ┆ s.json                          ┆                ┆                                 │
│ …           ┆ …                               ┆ …              ┆ …                               │
│ HRR255912   ┆ ../../out/salmon_gencode_result ┆ HRR255912_1    ┆ HS_human_salmon_quant_pe_gencod │
│             ┆ /HS_human_salmon_quant_pe_genco ┆                ┆ e                               │
│             ┆ de/HRR255912_1/lib_format_count ┆                ┆                                 │
│             ┆ s.json                          ┆                ┆                                 │
└─────────────┴─────────────────────────────────┴────────────────┴─────────────────────────────────┘

shape: (0, 4)
┌───────────┬──────────────────────┬────────────────┬──────────────┐
│ sample_id ┆ lib_format_json_path ┆ quant_dir_name ┆ quant_layout │
│ ---       ┆ ---                  ┆ ---            ┆ ---          │
│ str       ┆ str                  ┆ str            ┆ str          │
╞═══════════╪══════════════════════╪════════════════╪══════════════╡
└───────────┴──────────────────────┴────────────────┴──────────────┘

In [5]:
# Read each matched JSON (one row per file) and concatenate
lib_format_counts = pl.concat(
    [
        pl.read_json(path).with_columns(
            pl.lit(sample_id).alias("sample_id"),
            pl.lit(quant_dir_name).alias("quant_dir_name"),
            pl.lit(quant_layout).alias("quant_layout"),
            pl.lit(path).alias("lib_format_json_path"),
        )
        for sample_id, quant_dir_name, quant_layout, path in found_lib_format.select(
            "sample_id", "quant_dir_name", "quant_layout", "lib_format_json_path"
        ).iter_rows()
    ],
    how="vertical_relaxed",
).select(
    "sample_id",
    "quant_dir_name",
    "quant_layout",
    "lib_format_json_path",
    pl.exclude("sample_id", "quant_dir_name", "quant_layout", "lib_format_json_path"),
)

# Read each matched JSON (one row per file) and concatenate
lib_format_counts = pl.concat(
    [
        pl.read_json(path).with_columns(
            pl.lit(sample_id).alias("sample_id"),
            pl.lit(quant_dir_name).alias("quant_dir_name"),
            pl.lit(quant_layout).alias("quant_layout"),
            pl.lit(path).alias("lib_format_json_path"),
        )
        for sample_id, quant_dir_name, quant_layout, path in found_lib_format.select(
            "sample_id", "quant_dir_name", "quant_layout", "lib_format_json_path"
        ).iter_rows()
    ],
    how="vertical_relaxed",
).select(
    "sample_id",
    "quant_dir_name",
    "quant_layout",
    "lib_format_json_path",
    pl.exclude("sample_id", "quant_dir_name", "quant_layout", "lib_format_json_path"),
)

pl.Config.set_tbl_rows(2)
print(f"lib_format_counts rows: {lib_format_counts.height}")
display(lib_format_counts)

pl.Config.set_tbl_rows(20)
display(
    lib_format_counts.group_by("quant_layout", "expected_format")
    .len()
    .sort("quant_layout", "expected_format")
)

lib_format_counts rows: 744

shape: (744, 24)
┌─────────────┬────────────────┬───────────────────┬───────────────────┬───┬─────┬─────┬─────┬─────┐
│ sample_id   ┆ quant_dir_name ┆ quant_layout      ┆ lib_format_json_p ┆ … ┆ MU  ┆ OU  ┆ IU  ┆ U   │
│ ---         ┆ ---            ┆ ---               ┆ ath               ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ str         ┆ str            ┆ str               ┆ ---               ┆   ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
│             ┆                ┆                   ┆ str               ┆   ┆     ┆     ┆     ┆     │
╞═════════════╪════════════════╪═══════════════════╪═══════════════════╪═══╪═════╪═════╪═════╪═════╡
│ SRR27681984 ┆ SRR27681984    ┆ HS_human_salmon_q ┆ ../../out/salmon_ ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│             ┆                ┆ uant_se_gencode   ┆ gencode_result/HS ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ _human_salmon_qua ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ nt_se_gencode/SRR ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ 27681984/lib_form ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ at_counts.json    ┆   ┆     ┆     ┆     ┆     │
│ …           ┆ …              ┆ …                 ┆ …                 ┆ … ┆ …   ┆ …   ┆ …   ┆ …   │
│ HRR255912   ┆ HRR255912_1    ┆ HS_human_salmon_q ┆ ../../out/salmon_ ┆ … ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│             ┆                ┆ uant_pe_gencode   ┆ gencode_result/HS ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ _human_salmon_qua ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ nt_pe_gencode/HRR ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ 255912_1/lib_form ┆   ┆     ┆     ┆     ┆     │
│             ┆                ┆                   ┆ at_counts.json    ┆   ┆     ┆     ┆     ┆     │
└─────────────┴────────────────┴───────────────────┴───────────────────┴───┴─────┴─────┴─────┴─────┘

shape: (7, 3)
┌──────────────────────────────────┬─────────────────┬─────┐
│ quant_layout                     ┆ expected_format ┆ len │
│ ---                              ┆ ---             ┆ --- │
│ str                              ┆ str             ┆ u32 │
╞══════════════════════════════════╪═════════════════╪═════╡
│ HS_human_salmon_quant_pe_gencode ┆ ISF             ┆ 48  │
│ HS_human_salmon_quant_pe_gencode ┆ ISR             ┆ 287 │
│ HS_human_salmon_quant_pe_gencode ┆ IU              ┆ 192 │
│ HS_human_salmon_quant_pe_gencode ┆ SR              ┆ 2   │
│ HS_human_salmon_quant_se_gencode ┆ SF              ┆ 28  │
│ HS_human_salmon_quant_se_gencode ┆ SR              ┆ 159 │
│ HS_human_salmon_quant_se_gencode ┆ U               ┆ 28  │
└──────────────────────────────────┴─────────────────┴─────┘

&nbsp;

&nbsp;

## Heat / control pair join

- `rnaseq_all_metadata` から `sample_heat_id` と `sample_control_id` だけを抜き出す（406 ペア）
- `lib_format_counts` の `expected_format` と `strand_mapping_bias` だけを heat 側・control 側それぞれに left join する
- salmon の [LIBTYPE](https://salmon.readthedocs.io/en/latest/salmon.html#what-s-this-libtype) に従い、heat / control の両方が `S` なら stranded、両方が `U` なら unstranded とラベルする

In [6]:
# 405 heat/control pairs; join lib_format_counts onto each ID
hn_pairs = rnaseq_all_metadata.select("sample_heat_id", "sample_control_id")

lib_format_heat = lib_format_counts.select(
    pl.col("sample_id"),
    pl.col("expected_format", "strand_mapping_bias").name.suffix("_heat"),
)
lib_format_control = lib_format_counts.select(
    pl.col("sample_id"),
    pl.col("expected_format", "strand_mapping_bias").name.suffix("_control"),
)

hn_lib_format = hn_pairs.join(
    lib_format_heat,
    left_on="sample_heat_id",
    right_on="sample_id",
    how="left",
    maintain_order="left",
    validate="m:1",
).join(
    lib_format_control,
    left_on="sample_control_id",
    right_on="sample_id",
    how="left",
    maintain_order="left",
    validate="m:1",
).with_columns(
    pl.when(
        pl.col("expected_format_heat") == pl.col("expected_format_control")
    ).then(
        pl.lit("same format")
    ).otherwise(
        pl.lit("different format")
    ).alias("format_pair_comparison"),

    # validate strandedness
    # Salmon LIBTYPE: S = stranded, U = unstranded (https://salmon.readthedocs.io/en/latest/salmon.html#what-s-this-libtype)
    pl.when(
        pl.col("expected_format_heat").str.contains("S", literal=True),
        pl.col("expected_format_control").str.contains("S", literal=True),
    )
    .then(pl.lit("stranded library pairs"))
    .when(
        pl.col("expected_format_heat").str.contains("U", literal=True),
        pl.col("expected_format_control").str.contains("U", literal=True),
    )
    .then(pl.lit("unstranded library pairs"))
    .otherwise(pl.lit("mixed strandedness library pairs"))
    .alias("expected_library_strandedness"),
)

pl.Config.set_tbl_rows(2)
print(f"hn_lib_format rows: {hn_lib_format.height}")
display(hn_lib_format)

pl.Config.set_tbl_rows(20)
display(
    hn_lib_format.select(
        "expected_format_heat",
        "expected_format_control",
        "format_pair_comparison",
        "expected_library_strandedness",
    )
    .group_by(
        "expected_format_heat",
        "expected_format_control",
        "format_pair_comparison",
        "expected_library_strandedness",
    )
    .len()
    .sort("len", descending=True)
)


display(
    hn_lib_format.select(
        "expected_library_strandedness"
    )
    .group_by("expected_library_strandedness")
    .len()
    .sort("len", descending=True)
)

hn_lib_format rows: 406

shape: (406, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ sample_hea ┆ sample_con ┆ expected_f ┆ strand_ma ┆ expected_ ┆ strand_ma ┆ format_pa ┆ expected_ │
│ t_id       ┆ trol_id    ┆ ormat_heat ┆ pping_bia ┆ format_co ┆ pping_bia ┆ ir_compar ┆ library_s │
│ ---        ┆ ---        ┆ ---        ┆ s_heat    ┆ ntrol     ┆ s_control ┆ ison      ┆ trandedne │
│ str        ┆ str        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ss        │
│            ┆            ┆            ┆ f64       ┆ str       ┆ f64       ┆ str       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR2768198 ┆ SRR2768198 ┆ SR         ┆ 0.000005  ┆ SR        ┆ 0.000004  ┆ same      ┆ stranded  │
│ 4          ┆ 6          ┆            ┆           ┆           ┆           ┆ format    ┆ library   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ pairs     │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ HRR255914  ┆ HRR255912  ┆ IU         ┆ 0.502674  ┆ IU        ┆ 0.502765  ┆ same      ┆ unstrande │
│            ┆            ┆            ┆           ┆           ┆           ┆ format    ┆ d library │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ pairs     │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

shape: (8, 5)
┌──────────────────────┬───────────────────────┬──────────────────────┬──────────────────────┬─────┐
│ expected_format_heat ┆ expected_format_contr ┆ format_pair_comparis ┆ expected_library_str ┆ len │
│ ---                  ┆ ol                    ┆ on                   ┆ andedness            ┆ --- │
│ str                  ┆ ---                   ┆ ---                  ┆ ---                  ┆ u32 │
│                      ┆ str                   ┆ str                  ┆ str                  ┆     │
╞══════════════════════╪═══════════════════════╪══════════════════════╪══════════════════════╪═════╡
│ ISR                  ┆ ISR                   ┆ same format          ┆ stranded library     ┆ 146 │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ IU                   ┆ IU                    ┆ same format          ┆ unstranded library   ┆ 111 │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ SR                   ┆ SR                    ┆ same format          ┆ stranded library     ┆ 85  │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ ISF                  ┆ ISF                   ┆ same format          ┆ stranded library     ┆ 28  │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ U                    ┆ U                     ┆ same format          ┆ unstranded library   ┆ 15  │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ SF                   ┆ SF                    ┆ same format          ┆ stranded library     ┆ 14  │
│                      ┆                       ┆                      ┆ pairs                ┆     │
│ ISR                  ┆ IU                    ┆ different format     ┆ mixed strandedness   ┆ 5   │
│                      ┆                       ┆                      ┆ library pairs        ┆     │
│ U                    ┆ SR                    ┆ different format     ┆ mixed strandedness   ┆ 2   │
│                      ┆                       ┆                      ┆ library pairs        ┆     │
└──────────────────────┴───────────────────────┴──────────────────────┴──────────────────────┴─────┘

shape: (3, 2)
┌──────────────────────────────────┬─────┐
│ expected_library_strandedness    ┆ len │
│ ---                              ┆ --- │
│ str                              ┆ u32 │
╞══════════════════════════════════╪═════╡
│ stranded library pairs           ┆ 273 │
│ unstranded library pairs         ┆ 126 │
│ mixed strandedness library pairs ┆ 7   │
└──────────────────────────────────┴─────┘

&nbsp;

&nbsp;

&nbsp;

## Pie Chart

In [7]:
# Colors for salmon LIBTYPE strandedness of heat/control pairs
library_strandedness_colors = {
    "stranded library pairs": "#EF553B",
    "unstranded library pairs": "#636EFA",
    "mixed strandedness library pairs": "#D3D3D3",
}

library_strandedness_counts = (
    hn_lib_format
    .group_by("expected_library_strandedness")
    .agg(pl.len().alias("count"))
    .sort("count", descending=True)
)

fig_basic = px.pie(
    library_strandedness_counts.to_pandas(),
    values="count",
    names="expected_library_strandedness",
    title="Expected library strandedness (heat / control pairs)",
    color="expected_library_strandedness",
    color_discrete_map=library_strandedness_colors,
)

fig_basic.update_traces(
    textposition="outside",
    textinfo="value+percent+label",
    hovertemplate="<b>%{label}</b><br>Count: %{value}<br>Percentage: %{percent}<extra></extra>",
)

fig_basic.update_layout(
    font_size=18,
    showlegend=True,
    legend={
        "orientation": "v",
        "yanchor": "middle",
        "y": 0.5,
        "xanchor": "left",
        "x": 1.01,
    },
)

fig_basic.show()

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. Join Dataframe

- `rnaseq_all_metadata` と `hn_lib_format` を `join` する

In [8]:
rnaseq_all_metadata_all_columns = pl.read_csv(
    "../../Data/metadata/metadata_2610/rna_seq_all_metadata_all_columns_261001.tsv",
    separator="\t",
    schema_overrides={
        "sample_contact_phone": pl.Utf8
    }
)

In [10]:
rnaseq_all_metadata_join_salmon = rnaseq_all_metadata.join(
    hn_lib_format,
    on=["sample_heat_id", "sample_control_id"],
    how="inner",
    nulls_equal=True,
    validate="1:1"
)

rnaseq_all_metadata_join_salmon.write_csv(
    "../../Data/metadata/metadata_2610/rna_seq_all_metadata_simple_join_salmon_261001.tsv",
    separator="\t"
)

display(rnaseq_all_metadata_join_salmon)

shape: (406, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ sample_ti ┆ … ┆ expected_ ┆ strand_ma ┆ format_pa ┆ expected │
│ at_id     ┆ ntrol_id  ┆ me        ┆ tle       ┆   ┆ format_co ┆ pping_bia ┆ ir_compar ┆ _library │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ntrol     ┆ s_control ┆ ison      ┆ _strande │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ dness    │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ f64       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ SRR276819 ┆ wi-38-hte ┆ WI-38-hTE ┆ … ┆ SR        ┆ 0.000004  ┆ same      ┆ stranded │
│ 84        ┆ 86        ┆ rt_40°c_r ┆ RT, 40°C, ┆   ┆           ┆           ┆ format    ┆ library  │
│           ┆           ┆ na-seq_re ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ p1 vs wi- ┆ rep1 vs   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 38-htert_ ┆ WI-38-hTE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 37°c_rna- ┆ RT, 37°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq_rep1  ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ rep1      ┆   ┆           ┆           ┆           ┆          │
│ SRR276819 ┆ SRR276819 ┆ wi-38-hte ┆ WI-38-hTE ┆ … ┆ SR        ┆ 0.000006  ┆ same      ┆ stranded │
│ 83        ┆ 85        ┆ rt_40°c_r ┆ RT, 40°C, ┆   ┆           ┆           ┆ format    ┆ library  │
│           ┆           ┆ na-seq_re ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ p2 vs wi- ┆ rep2 vs   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 38-htert_ ┆ WI-38-hTE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 37°c_rna- ┆ RT, 37°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq_rep2  ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ rep2      ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ U         ┆ 0.499687  ┆ same      ┆ unstrand │
│ 72        ┆ 76        ┆ 1_rna_seq ┆ 1_RNA_seq ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ rl_1_rna_ ┆ rl_1_RNA_ ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ U         ┆ 0.497806  ┆ same      ┆ unstrand │
│ 74        ┆ 75        ┆ 2_rna_seq ┆ 2_RNA_seq ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ rl_2_rna_ ┆ rl_2_RNA_ ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ U         ┆ 0.494458  ┆ same      ┆ unstrand │
│ 71        ┆ 73        ┆ 3_rna_seq ┆ 3_RNA_seq ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ rl_3_rna_ ┆ rl_3_RNA_ ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR839269 ┆ SRR839269 ┆ young_hs1 ┆ Young_HS1 ┆ … ┆ U         ┆ 0.502057  ┆ same      ┆ unstrand │
│ 9         ┆ 7         ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs young1 ┆ vs Young1 ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆ pairs    │
│ SRR839270 ┆ SRR839269 ┆ young_hs2 ┆ Young_HS2 ┆ … ┆ U         ┆ 0.501298  ┆ same      ┆ unstrand │
│ 0         ┆ 8         ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs young2 ┆ vs Young2 ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆ pairs    │
│ SRR839270 ┆ SRR839270 ┆ senescent ┆ Senescent ┆ … ┆ U         ┆ 0.502171  ┆ same      ┆ unstrand │
│ 3         ┆ 1         ┆ _hs1_rna_ ┆ _HS1_RNA_ ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ seq vs    ┆ Seq vs    ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ senescent ┆ Senescent ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ 1_rna_seq ┆ 1_RNA_Seq ┆   ┆           ┆           ┆           ┆          │
│ SRR839270 ┆ SRR839270 ┆ senescent ┆ Senescent ┆ … ┆ U         ┆ 0.500821  ┆ same      ┆ unstrand │
│ 4         ┆ 2         ┆ _hs2_rna_ ┆ _HS2_RNA_ ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ seq vs    ┆ Seq vs    ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ senescent ┆ Senescent ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ 2_rna_seq ┆ 2_RNA_Seq ┆   ┆           ┆           ┆           ┆          │
│ SRR735979 ┆ SRR735979 ┆ hs_2ko_re ┆ HS_2KO_re ┆ … ┆ SR        ┆ 0.000025  ┆ same      ┆ stranded │
│ 9         ┆ 0         ┆ p4 vs c_2 ┆ p4 vs C_2 ┆   ┆           ┆           ┆ format    ┆ library  │
│           ┆           ┆ ko_rep4   ┆ KO_rep4   ┆   ┆           ┆           ┆           ┆ pairs    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255897 ┆ HRR255895 ┆ RNAseq_NS ┆ RNAseq_NS ┆ … ┆ IU        ┆ 0.502408  ┆ same      ┆ unstrand │
│           ┆           ┆ C_39_rep1 ┆ C_39_rep1 ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _NSC_37_r ┆ _NSC_37_r ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255898 ┆ HRR255896 ┆ RNAseq_NS ┆ RNAseq_NS ┆ … ┆ IU        ┆ 0.502674  ┆ same      ┆ unstrand │
│           ┆           ┆ C_39_rep2 ┆ C_39_rep2 ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _NSC_37_r ┆ _NSC_37_r ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
│ HRR255901 ┆ HRR255899 ┆ RNAseq_EC ┆ RNAseq_EC ┆ … ┆ IU        ┆ 0.503576  ┆ same      ┆ unstrand │
│           ┆           ┆ _39_rep1  ┆ _39_rep1  ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _EC_37_re ┆ _EC_37_re ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ p1        ┆ p1        ┆   ┆           ┆           ┆           ┆          │
│ HRR255902 ┆ HRR255900 ┆ RNAseq_EC ┆ RNAseq_EC ┆ … ┆ IU        ┆ 0.503084  ┆ same      ┆ unstrand │
│           ┆           ┆ _39_rep2  ┆ _39_rep2  ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _EC_37_re ┆ _EC_37_re ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ p2        ┆ p2        ┆   ┆           ┆           ┆           ┆          │
│ HRR255905 ┆ HRR255903 ┆ RNAseq_VS ┆ RNAseq_VS ┆ … ┆ IU        ┆ 0.502446  ┆ same      ┆ unstrand │
│           ┆           ┆ MC_39_rep ┆ MC_39_rep ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ 1 vs RNAs ┆ 1 vs RNAs ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ eq_VSMC_3 ┆ eq_VSMC_3 ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ 7_rep1    ┆ 7_rep1    ┆   ┆           ┆           ┆           ┆          │
│ HRR255906 ┆ HRR255904 ┆ RNAseq_VS ┆ RNAseq_VS ┆ … ┆ IU        ┆ 0.50259   ┆ same      ┆ unstrand │
│           ┆           ┆ MC_39_rep ┆ MC_39_rep ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ 2 vs RNAs ┆ 2 vs RNAs ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ eq_VSMC_3 ┆ eq_VSMC_3 ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ 7_rep2    ┆ 7_rep2    ┆   ┆           ┆           ┆           ┆          │
│ HRR255909 ┆ HRR255907 ┆ RNAseq_CM ┆ RNAseq_CM ┆ … ┆ IU        ┆ 0.501057  ┆ same      ┆ unstrand │
│           ┆           ┆ C_39_rep1 ┆ C_39_rep1 ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _CMC_37_r ┆ _CMC_37_r ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255910 ┆ HRR255908 ┆ RNAseq_CM ┆ RNAseq_CM ┆ … ┆ IU        ┆ 0.500867  ┆ same      ┆ unstrand │
│           ┆           ┆ C_39_rep2 ┆ C_39_rep2 ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ _CMC_37_r ┆ _CMC_37_r ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
│ HRR255913 ┆ HRR255911 ┆ RNAseq_Ne ┆ RNAseq_Ne ┆ … ┆ IU        ┆ 0.502773  ┆ same      ┆ unstrand │
│           ┆           ┆ uron_39_r ┆ uron_39_r ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ ep1 vs    ┆ ep1 vs    ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ RNAseq_Ne ┆ RNAseq_Ne ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ uron_37_r ┆ uron_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255914 ┆ HRR255912 ┆ RNAseq_Ne ┆ RNAseq_Ne ┆ … ┆ IU        ┆ 0.502765  ┆ same      ┆ unstrand │
│           ┆           ┆ uron_39_r ┆ uron_39_r ┆   ┆           ┆           ┆ format    ┆ ed       │
│           ┆           ┆ ep2 vs    ┆ ep2 vs    ┆   ┆           ┆           ┆           ┆ library  │
│           ┆           ┆ RNAseq_Ne ┆ RNAseq_Ne ┆   ┆           ┆           ┆           ┆ pairs    │
│           ┆           ┆ uron_37_r ┆ uron_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
rnaseq_all_metadata_join_salmon_all_columns = rnaseq_all_metadata_join_salmon.join(
    rnaseq_all_metadata_all_columns,
    on=rnaseq_all_metadata.columns,
    how="inner",
    nulls_equal=True,
    validate="1:1"
)

rnaseq_all_metadata_join_salmon_all_columns.write_csv(
    "../../Data/metadata/metadata_2610/rna_seq_all_metadata_simple_join_salmon_all_columns_261001.tsv",
    separator="\t"
)

display(rnaseq_all_metadata_join_salmon_all_columns)

shape: (406, 189)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ sample_ti ┆ … ┆ Read      ┆ Read      ┆ Individua ┆ Biomater │
│ at_id     ┆ ntrol_id  ┆ me        ┆ tle       ┆   ┆ length    ┆ length    ┆ l         ┆ ial      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ for       ┆ for mate  ┆ Accession ┆ Provider │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ mate1(bp) ┆ 2(bp)     ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR276819 ┆ SRR276819 ┆ wi-38-hte ┆ WI-38-hTE ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 84        ┆ 86        ┆ rt_40°c_r ┆ RT, 40°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ na-seq_re ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ p1 vs wi- ┆ rep1 vs   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 38-htert_ ┆ WI-38-hTE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 37°c_rna- ┆ RT, 37°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq_rep1  ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ rep1      ┆   ┆           ┆           ┆           ┆          │
│ SRR276819 ┆ SRR276819 ┆ wi-38-hte ┆ WI-38-hTE ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 83        ┆ 85        ┆ rt_40°c_r ┆ RT, 40°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ na-seq_re ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ p2 vs wi- ┆ rep2 vs   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 38-htert_ ┆ WI-38-hTE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 37°c_rna- ┆ RT, 37°C, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq_rep2  ┆ RNA-seq,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ rep2      ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 72        ┆ 76        ┆ 1_rna_seq ┆ 1_RNA_seq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ rl_1_rna_ ┆ rl_1_RNA_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 74        ┆ 75        ┆ 2_rna_seq ┆ 2_RNA_seq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ rl_2_rna_ ┆ rl_2_RNA_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR249737 ┆ SRR249737 ┆ m3d_heat_ ┆ M3D_Heat_ ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 71        ┆ 73        ┆ 3_rna_seq ┆ 3_RNA_seq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs m3d_ct ┆ vs M3D_Ct ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ rl_3_rna_ ┆ rl_3_RNA_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq       ┆ seq       ┆   ┆           ┆           ┆           ┆          │
│ SRR839269 ┆ SRR839269 ┆ young_hs1 ┆ Young_HS1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 9         ┆ 7         ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs young1 ┆ vs Young1 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆          │
│ SRR839270 ┆ SRR839269 ┆ young_hs2 ┆ Young_HS2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0         ┆ 8         ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs young2 ┆ vs Young2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _rna_seq  ┆ _RNA_Seq  ┆   ┆           ┆           ┆           ┆          │
│ SRR839270 ┆ SRR839270 ┆ senescent ┆ Senescent ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3         ┆ 1         ┆ _hs1_rna_ ┆ _HS1_RNA_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq vs    ┆ Seq vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ senescent ┆ Senescent ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 1_rna_seq ┆ 1_RNA_Seq ┆   ┆           ┆           ┆           ┆          │
│ SRR839270 ┆ SRR839270 ┆ senescent ┆ Senescent ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 4         ┆ 2         ┆ _hs2_rna_ ┆ _HS2_RNA_ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ seq vs    ┆ Seq vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ senescent ┆ Senescent ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2_rna_seq ┆ 2_RNA_Seq ┆   ┆           ┆           ┆           ┆          │
│ SRR735979 ┆ SRR735979 ┆ hs_2ko_re ┆ HS_2KO_re ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 9         ┆ 0         ┆ p4 vs c_2 ┆ p4 vs C_2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ko_rep4   ┆ KO_rep4   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HRR255897 ┆ HRR255895 ┆ RNAseq_NS ┆ RNAseq_NS ┆ … ┆ 150       ┆ 150       ┆ HRI123468 ┆ IBP      │
│           ┆           ┆ C_39_rep1 ┆ C_39_rep1 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _NSC_37_r ┆ _NSC_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255898 ┆ HRR255896 ┆ RNAseq_NS ┆ RNAseq_NS ┆ … ┆ 150       ┆ 150       ┆ HRI123468 ┆ IBP      │
│           ┆           ┆ C_39_rep2 ┆ C_39_rep2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _NSC_37_r ┆ _NSC_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
│ HRR255901 ┆ HRR255899 ┆ RNAseq_EC ┆ RNAseq_EC ┆ … ┆ 150       ┆ 150       ┆ HRI123469 ┆ IBP      │
│           ┆           ┆ _39_rep1  ┆ _39_rep1  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _EC_37_re ┆ _EC_37_re ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ p1        ┆ p1        ┆   ┆           ┆           ┆           ┆          │
│ HRR255902 ┆ HRR255900 ┆ RNAseq_EC ┆ RNAseq_EC ┆ … ┆ 150       ┆ 150       ┆ HRI123469 ┆ IBP      │
│           ┆           ┆ _39_rep2  ┆ _39_rep2  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _EC_37_re ┆ _EC_37_re ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ p2        ┆ p2        ┆   ┆           ┆           ┆           ┆          │
│ HRR255905 ┆ HRR255903 ┆ RNAseq_VS ┆ RNAseq_VS ┆ … ┆ 150       ┆ 150       ┆ HRI123470 ┆ IBP      │
│           ┆           ┆ MC_39_rep ┆ MC_39_rep ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 1 vs RNAs ┆ 1 vs RNAs ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ eq_VSMC_3 ┆ eq_VSMC_3 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7_rep1    ┆ 7_rep1    ┆   ┆           ┆           ┆           ┆          │
│ HRR255906 ┆ HRR255904 ┆ RNAseq_VS ┆ RNAseq_VS ┆ … ┆ 150       ┆ 150       ┆ HRI123470 ┆ IBP      │
│           ┆           ┆ MC_39_rep ┆ MC_39_rep ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2 vs RNAs ┆ 2 vs RNAs ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ eq_VSMC_3 ┆ eq_VSMC_3 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7_rep2    ┆ 7_rep2    ┆   ┆           ┆           ┆           ┆          │
│ HRR255909 ┆ HRR255907 ┆ RNAseq_CM ┆ RNAseq_CM ┆ … ┆ 150       ┆ 150       ┆ HRI123471 ┆ IBP      │
│           ┆           ┆ C_39_rep1 ┆ C_39_rep1 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _CMC_37_r ┆ _CMC_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255910 ┆ HRR255908 ┆ RNAseq_CM ┆ RNAseq_CM ┆ … ┆ 150       ┆ 150       ┆ HRI123471 ┆ IBP      │
│           ┆           ┆ C_39_rep2 ┆ C_39_rep2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ vs RNAseq ┆ vs RNAseq ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _CMC_37_r ┆ _CMC_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
│ HRR255913 ┆ HRR255911 ┆ RNAseq_Ne ┆ RNAseq_Ne ┆ … ┆ 150       ┆ 150       ┆ HRI123472 ┆ IBP      │
│           ┆           ┆ uron_39_r ┆ uron_39_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep1 vs    ┆ ep1 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAseq_Ne ┆ RNAseq_Ne ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ uron_37_r ┆ uron_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep1       ┆ ep1       ┆   ┆           ┆           ┆           ┆          │
│ HRR255914 ┆ HRR255912 ┆ RNAseq_Ne ┆ RNAseq_Ne ┆ … ┆ 150       ┆ 150       ┆ HRI123472 ┆ IBP      │
│           ┆           ┆ uron_39_r ┆ uron_39_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep2 vs    ┆ ep2 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ RNAseq_Ne ┆ RNAseq_Ne ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ uron_37_r ┆ uron_37_r ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ep2       ┆ ep2       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘