&nbsp;

# Heat stress-related Hi-C Metadata Validation

- [ENCODE-rE2G](https://github.com/EngreitzLab/ENCODE_rE2G)で使用するための Hi-C データの確認

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display


pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_rows(4)
pl.Config.set_tbl_cols(100)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE105028 (Hi-C, Hi-ChIP, ~~eU-seq,~~ ~~ChIP-seq~~, ~~ATAC-seq~~ )

- [Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress](https://doi.org/10.1016/j.molcel.2018.07.012)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- ATAC-seq のデータは、[./12_8_metadata_atacseq.ipynb](./12_8_metadata_atacseq.ipynb)に移動
- ChIP-seq のデータは、[./12_8_metadata_chipseq.ipynb](./12_8_metadata_chipseq.ipynb)に移動

In [4]:
GSE105028_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE105028/GSE105028_PEP/GSE105028_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("library_strategy") != "ATAC-Seq") &
    (pl.col("library_strategy") != "ChIP-Seq") &
    (pl.col("library_strategy") != "eU-Seq")
).sort(
    "srr",
    descending=False
).with_columns(
    pl.lit("https://doi.org/10.1016/j.molcel.2018.07.012").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
)

GSE105028_PEP.write_csv(
    "../../Data/metadata/metadata_hic/GSE105028_PEP_raw_filtered.tsv",
    separator='\t'
)

pl.Config.set_tbl_rows(2)
display(GSE105028_PEP)

shape: (36, 48)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ lib ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ rar ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ y_s ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ tra ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ teg ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm │
│ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ y   ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ hic ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HiC ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ in- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ _re ┆ er  ┆ o   ┆ RED ┆     ┆ 617 ┆ 328 ┆ _Re ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ sit ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 281 ┆ E   ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ -Se ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ p1  ┆     ┆ sap ┆     ┆     ┆ 792 ┆ 854 ┆ p1  ┆ 660 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ u   ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 660 ┆     ┆ 028 ┆     ┆ 854 ┆ an  ┆ nor ┆ q   ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│     ┆     ┆ ien ┆     ┆     ┆ 6   ┆ 8   ┆     ┆ 7   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 8   ┆ Emb ┆ mal ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ C   ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆ con ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nic ┆ dit ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ste ┆ ion ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆ s   ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ H9_ ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 288 ┆ 12  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C.1 ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 790 ┆ 548 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kb. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 044 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ sin ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ siN ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ Hi- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ nul ┆ nul ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ ipb ┆ er  ┆ o   ┆ RED ┆     ┆ 620 ┆ 331 ┆ IPB ┆ 282 ┆ lic ┆ 24  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ ChI ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 282 ┆ E   ┆ 105 ┆     ┆ 331 ┆ l   ┆ l   ┆ hIP ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ l_h ┆     ┆ sap ┆     ┆     ┆ 681 ┆ 610 ┆ L_H ┆ 905 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ P,  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 905 ┆     ┆ 028 ┆     ┆ 610 ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ s_h ┆     ┆ ien ┆     ┆     ┆ 4   ┆ 8   ┆ S_H ┆ 9   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│ 3k4 ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ 3K4 ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ChI ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│ me1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ me1 ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│ _hi ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Hi ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│ -ch ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Ch ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │
│ ip  ┆     ┆     ┆     ┆     ┆     ┆     ┆ IP  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 316 ┆ 12  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 828 ┆ 108 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ siN ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 393 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IPB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ L_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3K4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Hi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P.h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [5]:
# Hi-C metadata
defined_pairs_gse105028_hic = [
    ("SRR6177928", "SRR6177926"), # hs_hic_rep1 vs. hic_rep1
    ("SRR6177929", "SRR6177927")  # hs_hic_rep2 vs. hic_rep2
]

paired_metadata_gse105028_hic = create_paired_metadata(
    GSE105028_PEP,
    defined_pairs_gse105028_hic,
    sample_id_column_name="srr"
)

if paired_metadata_gse105028_hic is not None:
    paired_metadata_gse105028_hic.write_csv(
        "../../Data/metadata/metadata_hic/GSE105028_hic_paired_metadata.tsv",
        separator='\t'
    )

pl.Config.set_tbl_rows(2)
display(paired_metadata_gse105028_hic)

shape: (2, 49)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ lib ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ rar ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ y_s ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ tra ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ teg ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ y   ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRX ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ in- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ 617 ┆ 617 ┆ hic ┆ er  ┆ o   ┆ RED ┆     ┆ 328 ┆ HiC ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ sit ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 281 ┆ E   ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ -Se ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ 792 ┆ 792 ┆ _re ┆     ┆ sap ┆     ┆     ┆ 855 ┆ _Re ┆ 660 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ u   ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 660 ┆     ┆ 028 ┆     ┆ 855 ┆ an  ┆ hea ┆ q   ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ 8   ┆ 6   ┆ p1  ┆     ┆ ien ┆     ┆     ┆ 0   ┆ p1  ┆ 9   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆ 0   ┆ Emb ┆ t   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ C   ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ ryo ┆ sho ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ hic ┆     ┆     ┆     ┆     ┆ SRX ┆ HiC ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ nic ┆ ck  ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆ 328 ┆ _Re ┆ 281 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 281 ┆     ┆     ┆     ┆ 328 ┆ Ste ┆ con ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆ 854 ┆ p1  ┆ 660 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 660 ┆     ┆     ┆     ┆ 854 ┆ m   ┆ dit ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 8   ┆ Cel ┆ ion ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ s   ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆ vs  ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ und ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆ N07 ┆ 288 ┆ 12  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆ 790 ┆ 550 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ H9_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆ 035 ┆ vs  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C.1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kb. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ lm. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ nih ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ .go ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ v/s ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ ra? ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ter ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ m=S ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ RX3 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ 288 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 548 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 790 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 044 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ H9_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C.1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kb. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ SRR ┆ SRR ┆ hs_ ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRX ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ in- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ 617 ┆ 617 ┆ hic ┆ er  ┆ o   ┆ RED ┆     ┆ 328 ┆ HiC ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ sit ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 281 ┆ E   ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ -Se ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ 792 ┆ 792 ┆ _re ┆     ┆ sap ┆     ┆     ┆ 855 ┆ _Re ┆ 661 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ u   ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 661 ┆     ┆ 028 ┆     ┆ 855 ┆ an  ┆ hea ┆ q   ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ 9   ┆ 7   ┆ p2  ┆     ┆ ien ┆     ┆     ┆ 1   ┆ p2  ┆ 0   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 1   ┆ Emb ┆ t   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ C   ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ ryo ┆ sho ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ hic ┆     ┆     ┆     ┆     ┆ SRX ┆ HiC ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ nic ┆ ck  ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆ 328 ┆ _Re ┆ 281 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 281 ┆     ┆     ┆     ┆ 328 ┆ Ste ┆ con ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ p2  ┆     ┆     ┆     ┆     ┆ 854 ┆ p2  ┆ 660 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 660 ┆     ┆     ┆     ┆ 854 ┆ m   ┆ dit ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 9   ┆ Cel ┆ ion ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆     │

In [6]:
# Hi-ChIP metadata
defined_pairs_gse105028_hichip = [
    # RAD21
    ("SRR6206787", "SRR6206783"), # hs_rad21_hi-chip_rep1 vs. rad21_hi-chip_rep1
    ("SRR6206788", "SRR6206784"), # hs_rad21_hi-chip_rep2 vs. rad21_hi-chip_rep2
    ("SRR6206789", "SRR6206785"), # hs_rad21_hi-chip_rep3 vs. rad21_hi-chip_rep3
    ("SRR6206790", "SRR6206786"), # hs_rad21_hi-chip_rep4 vs. rad21_hi-chip_rep4
    # hs_rad21_hi-chip_rep1_and_rep2_technical_replicate (SRR6206791) と hs_ki_rad21_hi-chip (SRR6206792) は使用しない

    # CTCF
    ("SRR6206796", "SRR6206793"), # hs_ctcf_hi-chip_rep1 vs. ctcf_hi-chip_rep1
    ("SRR6206797", "SRR6206794"), # hs_ctcf_hi-chip_rep2 vs. ctcf_hi-chip_rep2
    # ctcf_hi-chip_rep3 (SRR6206795) は使用しない

    # OCT4
    ("SRR6206800", "SRR6206798"), # hs_oct4_hi-chip_rep1 vs. oct4_hi-chip_rep1
    ("SRR6206801", "SRR6206799"), # hs_oct4_hi-chip_rep2 vs. oct4_hi-chip_rep2

    # NANOG
    ("SRR6206804", "SRR6206802"), # hs_nanog_hi-chip_rep1 vs. nanog_hi-chip_rep1
    ("SRR6206805", "SRR6206803"), # hs_nanog_hi-chip_rep2 vs. nanog_hi-chip_rep2

    # KLF4 (replicate 2 がない)
    ("SRR6206808", "SRR6206806"), # hs_klf4_hi-chip vs. klf4_hi-chip_rep1
    ("SRR6206808", "SRR6206807"), # hs_klf4_hi-chip vs. klf4_hi-chip_rep2

    # H3K4me1
    ("SRR6206811", "SRR6206809"), # hs_h3k4me1_hi-chip_rep1 vs. h3k4me1_hi-chip_rep1
    ("SRR6206812", "SRR6206810"), # hs_h3k4me1_hi-chip_rep2 vs. h3k4me1_hi-chip_rep2

    # sinipbl_hs_ctcf_hi-chip (SRR6206813); sinipbl_hs_h3k4me1_hi-chip (SRR6206814) は使用しない

]

paired_metadata_gse105028_hichip = create_paired_metadata(
    GSE105028_PEP,
    defined_pairs_gse105028_hichip,
    sample_id_column_name="srr"
)

if paired_metadata_gse105028_hichip is not None:
    paired_metadata_gse105028_hichip.write_csv(
        "../../Data/metadata/metadata_hic/GSE105028_hichip_paired_metadata.tsv",
        separator='\t'
    )

pl.Config.set_tbl_rows(2)
display(paired_metadata_gse105028_hichip)

shape: (14, 49)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ lib ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ rar ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ y_s ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ tra ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ teg ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ y   ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hs_ ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRX ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ Hi- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ nul ┆ nul ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ 620 ┆ 620 ┆ rad ┆ er  ┆ o   ┆ RED ┆     ┆ 331 ┆ Rad ┆ 282 ┆ lic ┆ 24  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ ChI ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 282 ┆ E   ┆ 105 ┆     ┆ 331 ┆ l   ┆ l   ┆ hIP ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ 678 ┆ 678 ┆ 21_ ┆     ┆ sap ┆     ┆     ┆ 608 ┆ 21  ┆ 902 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ P,  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 902 ┆     ┆ 028 ┆     ┆ 608 ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ 7   ┆ 3   ┆ hi- ┆     ┆ ien ┆     ┆     ┆ 1   ┆ Hi- ┆ 0   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ chi ┆     ┆ s   ┆     ┆     ┆ vs  ┆ ChI ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ChI ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ p_r ┆     ┆     ┆     ┆     ┆ SRX ┆ P   ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆ 331 ┆ Rep ┆ 282 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆ 331 ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 607 ┆ 1   ┆ 901 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 901 ┆     ┆     ┆     ┆ 607 ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │
│     ┆     ┆ rad ┆     ┆     ┆     ┆     ┆ 7   ┆ vs  ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆     │
│     ┆     ┆ 21_ ┆     ┆     ┆     ┆     ┆     ┆ Rad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆     │
│     ┆     ┆ hi- ┆     ┆     ┆     ┆     ┆     ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆     │
│     ┆     ┆ chi ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆     │
│     ┆     ┆ p_r ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 316 ┆ 12  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 828 ┆ 081 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 420 ┆ vs  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 21_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P.h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ lm. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ nih ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ .go ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ v/s ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ ra? ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ter ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ m=S ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ RX3 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ 316 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 077 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 828 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 424 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rad ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 21_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hi- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P.h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ SRR ┆ SRR ┆ hs_ ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRX ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ Hi- ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ oth ┆ gen ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ nul ┆ nul ┆ HiC ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  │
│ 620 ┆ 620 ┆ h3k ┆ er  ┆ o   ┆ RED ┆     ┆ 331 ┆ H3K ┆ 282 ┆ lic ┆ 24  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ ChI ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ er  ┆ omi ┆ ER  ┆ 282 ┆ E   ┆ 105 ┆     ┆ 331 ┆ l   ┆ l   ┆ hIP ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ 681 ┆ 681 ┆ 4me ┆     ┆ sap ┆     ┆     ┆ 610 ┆ 4me ┆ 905 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ P,  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 905 ┆     ┆ 028 ┆     ┆ 610 ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ 2   ┆ 0   ┆ 1_h ┆     ┆ ien ┆     ┆     ┆ 6   ┆ 1   ┆ 7   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ Hi- ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ i-c ┆     ┆ s   ┆     ┆     ┆ vs  ┆ Hi- ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ChI ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ hip ┆     ┆     ┆     ┆     ┆ SRX ┆ ChI ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆ 331 ┆ P   ┆ 282 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆ 331 ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ p2  ┆     ┆     ┆     ┆     ┆ 610 ┆ Rep ┆ 905 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 905 ┆     ┆     ┆     ┆ 610 ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE130758 Hi-C

- validate date: 2026-02-22
- [Chromatin conformation remains stable upon extensive transcriptional changes driven by heat shock](https://doi.org/10.1073/pnas.1901244116)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- [./12_8_metadata_hic.ipynb](./12_8_metadata_hic.ipynb)に移動

In [7]:
GSE130758_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE130758/GSE130758_PEP/GSE130758_PEP_raw.csv",
    separator=','
).with_columns(
    pl.lit("https://doi.org/10.1073/pnas.1901244116").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
)

GSE130758_PEP.write_csv(
    "../../Data/metadata/metadata_hic/GSE130758_PEP_raw_filtered.tsv",
    separator='\t'
)

pl.Config.set_tbl_rows(4)
display(GSE130758_PEP)

shape: (4, 46)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm │
│ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ bio ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ Bio ┆ GSM ┆ Pub ┆ May ┆ Jun ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Cha ┆ dan ┆ Dan ┆ Com ┆ Cor ┆ 235 ┆ Ith ┆ NY  ┆ 148 ┆ USA ┆ Ill ┆ oth ┆ gen ┆ Hi- ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ 37  │
│ sam ┆ er  ┆ o   ┆ RED ┆     ┆ 901 ┆ 579 ┆ sam ┆ 375 ┆ lic ┆ 06  ┆ 09  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ rle ┆ koc ┆ ko  ┆ put ┆ nel ┆ Hun ┆ aca ┆     ┆ 50  ┆     ┆ umi ┆ er  ┆ omi ┆ C   ┆ 375 ┆ :// ┆ 130 ┆     ┆ 579 ┆ 2   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ ple ┆     ┆ sap ┆     ┆     ┆ 950 ┆ 762 ┆ ple ┆ 320 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ imm ┆ sap ┆     ┆ c   ┆ 73  ┆ s,, ┆ @gm ┆ Lab ┆ ati ┆ l   ┆ ger ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 320 ┆ ftp ┆ 758 ┆     ┆ 762 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ _86 ┆     ┆ ien ┆     ┆     ┆ 4   ┆ 4   ┆ _86 ┆ 7   ┆ Jun ┆ 9   ┆ 9   ┆     ┆     ┆ ort ┆ ien ┆     ┆ DNA ┆     ┆ Dan ┆ ail ┆     ┆ ona ┆ Uni ┆ for ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 7   ┆ .nc ┆ ,   ┆     ┆ 4   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│ 06_ ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ 06_ ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ ali ┆ s   ┆     ┆     ┆     ┆ ko  ┆ .co ┆     ┆ l   ┆ ver ┆ d   ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆ GSE ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│ 413 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ Bio ┆ sit ┆ Dri ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆ 130 ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│ 2_5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_5 ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ y   ┆ ve  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆ 778 ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│ 866 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆     │
│ 5_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_H ┆     ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆     │
│ yl2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ YL2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ s.1 ┆     ┆     ┆     │
│ cbg ┆     ┆     ┆     ┆     ┆     ┆     ┆ CBG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 901 ┆     ┆     ┆     │
│ x2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ X2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 244 ┆     ┆     ┆     │
│ k56 ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 116 ┆     ┆     ┆     │
│ 2_i ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX5 ┆     ┆     ┆     ┆     │
│ nsi ┆     ┆     ┆     ┆     ┆     ┆     ┆ nSi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆ N11 ┆ 797 ┆     ┆     ┆     ┆     │
│ tuh ┆     ┆     ┆     ┆     ┆     ┆     ┆ tuH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆ 582 ┆ 624 ┆     ┆     ┆     ┆     │
│ ic_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ iC_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ 749 ┆     ┆     ┆     ┆     ┆     │
│ hs_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1_c ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 753 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ gat ┆     ┆     ┆     ┆     ┆     ┆     ┆ GAT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 207 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ gt  ┆     ┆     ┆     ┆     ┆     ┆     ┆ GT  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M37 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 532 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _30 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .hi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ bio ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ Bio ┆ GSM ┆ Pub ┆ May ┆ Jun ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Cha ┆ dan ┆ Dan ┆ Com ┆ Cor ┆ 235 ┆ Ith ┆ NY  ┆ 148 ┆ USA ┆ Ill ┆ oth ┆ gen ┆ Hi- ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ 37  │
│ sam ┆ er  ┆ o   ┆ RED ┆     ┆ 901 ┆ 579 ┆ sam ┆ 375 ┆ lic ┆ 06  ┆ 09  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ rle ┆ koc ┆ ko  ┆ put ┆ nel ┆ Hun ┆ aca ┆     ┆ 50  ┆     ┆ umi ┆ er  ┆ omi ┆ C   ┆ 375 ┆ :// ┆ 130 ┆     ┆ 579 ┆ 2   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ ple ┆     ┆ sap ┆     ┆     ┆ 950 ┆ 762 ┆ ple ┆ 320 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ imm ┆ sap ┆     ┆ c   ┆ 73  ┆ s,, ┆ @gm ┆ Lab ┆ ati ┆ l   ┆ ger ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 320 ┆ ftp ┆ 758 ┆     ┆ 762 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ _86 ┆     ┆ ien ┆     ┆     ┆ 5   ┆ 5   ┆ _86 ┆ 8   ┆ Jun ┆ 9   ┆ 9   ┆     ┆     ┆ ort ┆ ien ┆     ┆ DNA ┆     ┆ Dan ┆ ail ┆     ┆ ona ┆ Uni ┆ for ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 8   ┆ .nc ┆ ,   ┆     ┆ 5   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│ 06_ ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ 06_ ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ ali ┆ s   ┆     ┆     ┆     ┆ ko  ┆ .co ┆     ┆ l   ┆ ver ┆ d   ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆ GSE ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│ 413 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ Bio ┆ sit ┆ Dri ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆ 130 ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│ 2_5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_5 ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ y   ┆ ve  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆ 778 ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│ 866 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆     │
│ 7_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_H ┆     ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆     │
│ yl2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ YL2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ s.1 ┆     ┆     ┆     │
│ cbg ┆     ┆     ┆     ┆     ┆     ┆     ┆ CBG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 901 ┆     ┆     ┆     │
│ x2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ X2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 244 ┆     ┆     ┆     │
│ k56 ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 116 ┆     ┆     ┆     │
│ 2_i ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX5 ┆     ┆     ┆     ┆     │
│ nsi ┆     ┆     ┆     ┆     ┆     ┆     ┆ nSi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆ N11 ┆ 797 ┆     ┆     ┆     ┆     │
│ tuh ┆     ┆     ┆     ┆     ┆     ┆     ┆ tuH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆ 582 ┆ 625 ┆     ┆     ┆     ┆     │
│ ic_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ iC_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ 761 ┆     ┆     ┆     ┆     ┆     │
│ hs_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2_g ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 753 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cca ┆     ┆     ┆     ┆     ┆     ┆     ┆ CCA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 208 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆ AT  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [8]:
defined_pairs_gse130758_hic = [
    ("SRR9019504", "SRR9019506"), # biosample_8606_4132_58665_hyl2cbgx2_k562_insituhic_hs_1_cgatgt vs. biosample_8606_4132_58664_hyl2cbgx2_k562_insituhic_nhs_1_atcacg
    ("SRR9019505", "SRR9019507")  # biosample_8606_4132_58667_hyl2cbgx2_k562_insituhic_hs_2_gccaat vs. biosample_8606_4132_58666_hyl2cbgx2_k562_insituhic_nhs_2_acagtg
]

paired_metadata_gse130758_hic = create_paired_metadata(
    GSE130758_PEP,
    defined_pairs_gse130758_hic,
    sample_id_column_name="srr"
)

if paired_metadata_gse130758_hic is not None:
    paired_metadata_gse130758_hic.write_csv(
        "../../Data/metadata/metadata_hic/GSE130758_hic_paired_metadata.tsv",
        separator='\t'
    )

pl.Config.set_tbl_rows(4)
display(paired_metadata_gse130758_hic)

shape: (2, 47)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ bio ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRX ┆ Bio ┆ GSM ┆ Pub ┆ May ┆ Jun ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Cha ┆ dan ┆ Dan ┆ Com ┆ Cor ┆ 235 ┆ Ith ┆ NY  ┆ 148 ┆ USA ┆ Ill ┆ oth ┆ gen ┆ Hi- ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ 37  │
│ 901 ┆ 901 ┆ sam ┆ er  ┆ o   ┆ RED ┆     ┆ 579 ┆ sam ┆ 375 ┆ lic ┆ 06  ┆ 09  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ rle ┆ koc ┆ ko  ┆ put ┆ nel ┆ Hun ┆ aca ┆     ┆ 50  ┆     ┆ umi ┆ er  ┆ omi ┆ C   ┆ 375 ┆ :// ┆ 130 ┆     ┆ 579 ┆ 2   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   │
│ 950 ┆ 950 ┆ ple ┆     ┆ sap ┆     ┆     ┆ 762 ┆ ple ┆ 320 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ imm ┆ sap ┆     ┆ c   ┆ 73  ┆ s,, ┆ @gm ┆ Lab ┆ ati ┆ l   ┆ ger ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆     ┆ 320 ┆ ftp ┆ 758 ┆     ┆ 762 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in │
│ 4   ┆ 6   ┆ _86 ┆     ┆ ien ┆     ┆     ┆ 4   ┆ _86 ┆ 7   ┆ Jun ┆ 9   ┆ 9   ┆     ┆     ┆ ort ┆ ien ┆     ┆ DNA ┆     ┆ Dan ┆ ail ┆     ┆ ona ┆ Uni ┆ for ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 7   ┆ .nc ┆ ,   ┆     ┆ 4   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ 06_ ┆     ┆ s   ┆     ┆     ┆ vs  ┆ 06_ ┆ vs  ┆ 07  ┆     ┆     ┆     ┆     ┆ ali ┆ s   ┆     ┆     ┆     ┆ ko  ┆ .co ┆     ┆ l   ┆ ver ┆ d   ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆ SRX ┆ 413 ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ Bio ┆ sit ┆ Dri ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 130 ┆     ┆ SRX ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ 2_5 ┆     ┆     ┆     ┆     ┆ 579 ┆ 2_5 ┆ 375 ┆ 9   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ y   ┆ ve  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 375 ┆ .ni ┆ 778 ┆     ┆ 579 ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆ 762 ┆ 866 ┆ 320 ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆ h.g ┆     ┆     ┆ 762 ┆     ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆     │
│     ┆     ┆ 5_h ┆     ┆     ┆     ┆     ┆ 6   ┆ 5_H ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ ov/ ┆     ┆     ┆ 6   ┆     ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆     │
│     ┆     ┆ yl2 ┆     ┆     ┆     ┆     ┆     ┆ YL2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ s.1 ┆     ┆     ┆     │
│     ┆     ┆ cbg ┆     ┆     ┆     ┆     ┆     ┆ CBG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 901 ┆     ┆     ┆     │
│     ┆     ┆ x2_ ┆     ┆     ┆     ┆     ┆     ┆ X2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 244 ┆     ┆     ┆     │
│     ┆     ┆ k56 ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 116 ┆     ┆     ┆     │
│     ┆     ┆ 2_i ┆     ┆     ┆     ┆     ┆     ┆ 2_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX5 ┆     ┆     ┆     ┆     │
│     ┆     ┆ nsi ┆     ┆     ┆     ┆     ┆     ┆ nSi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆ N11 ┆ 797 ┆     ┆     ┆     ┆     │
│     ┆     ┆ tuh ┆     ┆     ┆     ┆     ┆     ┆ tuH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆ 582 ┆ 624 ┆     ┆     ┆     ┆     │
│     ┆     ┆ ic_ ┆     ┆     ┆     ┆     ┆     ┆ iC_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ 749 ┆ vs  ┆     ┆     ┆     ┆     │
│     ┆     ┆ hs_ ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_c ┆     ┆     ┆     ┆     ┆     ┆ 1_C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 753 ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     │
│     ┆     ┆ gat ┆     ┆     ┆     ┆     ┆     ┆ GAT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 207 ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     │
│     ┆     ┆ gt  ┆     ┆     ┆     ┆     ┆     ┆ GT  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆     │
│     ┆     ┆ bio ┆     ┆     ┆     ┆     ┆     ┆ Bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆     │
│     ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆ sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M37 ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ lm. ┆     ┆     ┆     ┆     │
│     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 532 ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ nih ┆     ┆     ┆     ┆     │
│     ┆     ┆ _86 ┆     ┆     ┆     ┆     ┆     ┆ _86 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07_ ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ .go ┆     ┆     ┆     ┆     │
│     ┆     ┆ 06_ ┆     ┆     ┆     ┆     ┆     ┆ 06_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ v/s ┆     ┆     ┆     ┆     │
│     ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_H ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ ra? ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2_5 ┆     ┆     ┆     ┆     ┆     ┆ 2_5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_1 ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ter ┆     ┆     ┆     ┆     │
│     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆     ┆ 866 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _in ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ m=S ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4_h ┆     ┆     ┆     ┆     ┆     ┆ 4_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ RX5 ┆     ┆     ┆     ┆     │
│     ┆     ┆ yl2 ┆     ┆     ┆     ┆     ┆     ┆ YL2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _30 ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ 797 ┆     ┆     ┆     ┆     │
│     ┆     ┆ cbg ┆     ┆     ┆     ┆     ┆     ┆ CBG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .hi ┆     ┆     ┆     ┆     ┆     ┆ N11 ┆ 626 ┆     ┆     ┆     ┆     │
│     ┆     ┆ x2_ ┆     ┆     ┆     ┆     ┆     ┆ X2_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆ 582 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ k56 ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ 760 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2_i ┆     ┆     ┆     ┆     ┆     ┆ 2_I ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ nsi ┆     ┆     ┆     ┆     ┆     ┆ nSi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :// ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tuh ┆     ┆     ┆     ┆     ┆     ┆ tuH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ic_ ┆     ┆     ┆     ┆     ┆     ┆ iC_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .nc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ nhs ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _1_ ┆     ┆     ┆     ┆     ┆     ┆ _1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ atc ┆     ┆     ┆     ┆     ┆     ┆ ATC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ acg ┆     ┆     ┆     ┆     ┆     ┆ ACG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 375 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 753 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 209 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

## Concat Dataframe

In [9]:
df_hic_all: list[pl.DataFrame | None] = [
    paired_metadata_gse105028_hic,
    paired_metadata_gse105028_hichip,
    paired_metadata_gse130758_hic
]

dfs_hic:  list[pl.DataFrame] = [df for df in df_hic_all if df is not None]

In [10]:
hic_concat = pl.concat(dfs_hic, how="diagonal")

hic_concat.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/hic_metadata_all_{execute_date}.tsv",
    separator='\t'
)