&nbsp;

# Heat stress-related ChIP-seq Metadata Validation

- ChIP-Atlas のエンリッチメント解析の結果から、熱ストレスなどに関連しているものを探索するため、ここで調査する
- `Input` sample は、今回はペアのメタデータを作る際は基本的に除いておくが、その際はIDの記載のみしておく
- 主に、`genome binding/occupancy profiling by high throughput sequencing` で取得されたものをこちらに記載する
- `heat shock` vs `ctrl` のペアを念頭に収集するが、後に使用する可能性もあるので、除去したプロセスを明示的に記載する

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display


pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_rows(4)
pl.Config.set_tbl_cols(100)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Strategy 0. これまで収集してきたメタデータに、ChIP-seq が含まれているか確認

- [../00_metadata/](../00_metadata/) にある、主に bulk RNA-seq データを収集してきたメタデータ内に、熱ストレスに関連するChIP-seq のデータがないか確認する

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. GSE140053 (ChIP-seq; Pol2)

- [Stress-induced nuclear condensation of NELF drives transcriptional downregulation](https://doi.org/10.1016/j.molcel.2021.01.016)
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から移動
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb) から更に移動
- validate date: 2026-04-28

In [4]:
GSE140053_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE140053/GSE140053_PEP/GSE140053_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_title") != "VCaP: Input") # input sample is excluded (SRX7107233)
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("https://doi.org/10.1016/j.molcel.2021.01.016").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE140053 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE140053_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE140053_filtered = GSE140053[[s.name for s in GSE140053 if not (s.null_count() == GSE140053.height)]]

GSE140053_combined = GSE140053_PEP.join(
    GSE140053_filtered,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE140053_combined = GSE140053_combined[[s.name for s in GSE140053_combined if not (s.null_count() == GSE140053_combined.height)]]

# pl.Config.set_tbl_rows(9)
# display(GSE140053_combined)

In [5]:
defined_pairs_gse140053_chipseq = [
    ("SRX7107227", "SRX7107225"), # VCaP: Pol2_siCtrl_HS1 vs. VCaP: Pol2_siCtrl_Ctrl1
    ("SRX7107228", "SRX7107226"), # VCaP: Pol2_siCtrl_HS2 vs. VCaP: Pol2_siCtrl_Ctrl2
    ("SRX7107231", "SRX7107229"), # VCaP: Pol2_siUBC9_HS1 vs. VCaP: Pol2_siUBC9_Ctrl1
    ("SRX7107232", "SRX7107230") # VCaP: Pol2_siUBC9_HS2 vs. VCaP: Pol2_siUBC9_Ctrl2
]

paired_metadata_df_gse140053_chipseq = create_paired_metadata(
    combined_df=GSE140053_combined,
    defined_sample_pairs=defined_pairs_gse140053_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metadata_df_gse140053_chipseq is not None:
    paired_metadata_df_gse140053_chipseq.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE140053_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse140053_chipseq)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 52)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ chi ┆ tre ┆ con ┆ gen ┆ alt ┆ bio ┆ sra ┆ sam ┆ ref ┆ str ┆ str ┆ con │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ p_a ┆ atm ┆ dit ┆ ome ┆ ern ┆ sam ┆ --- ┆ ple ┆ ere ┆ ess ┆ ess ┆ tro │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ nti ┆ ent ┆ ion ┆ _bu ┆ ati ┆ ple ┆ str ┆ _ac ┆ nce ┆ tre ┆ tre ┆ l   │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ bod ┆ --- ┆ --- ┆ ild ┆ ve_ ┆ --- ┆     ┆ ces ┆ _do ┆ atm ┆ atm ┆ tre │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ y   ┆ str ┆ str ┆ --- ┆ to  ┆ str ┆     ┆ sio ┆ i   ┆ ent ┆ ent ┆ atm │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ ces ┆ _id ┆ nam ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ n   ┆ --- ┆ tem ┆ tim ┆ ent │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ sin ┆ --- ┆ e   ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ per ┆ e   ┆ tem │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ g   ┆ str ┆ --- ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ atu ┆ --- ┆ per │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆ --- ┆     ┆ str ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ vca ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ mul ┆ VCa ┆ GSM ┆ Pub ┆ Nov ┆ Feb ┆ SRA ┆ 1   ┆ VCa ┆ Hom ┆ 960 ┆ Hea ┆ VCa ┆ gen ┆ VCa ┆ res ┆ ChI ┆ GPL ┆ Bar ┆ Stü ┆ Fre ┆ 791 ┆ Ger ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ VCa ┆ ant ┆ con ┆ Hea ┆ hg3 ┆ GSM ┆ htt ┆ htt ┆ SAM ┆ htt ┆ 43  ┆ 30  ┆ 37  │
│ 710 ┆ 710 ┆ p_p ┆ P   ┆ o   ┆ GLE ┆     ┆ ti  ┆ P:  ┆ 415 ┆ lic ┆ 06  ┆ 06  ┆     ┆     ┆ P   ┆ o   ┆ 6   ┆ t   ┆ P   ┆ omi ┆ P   ┆ equ ┆ P-s ┆ 185 ┆ bar ┆ bew ┆ ibu ┆ 08  ┆ man ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 415 ┆ :// ┆ 140 ┆     ┆ 710 ┆ P   ┆ i-P ┆ tro ┆ t-S ┆ 8   ┆ 177 ┆ ps: ┆ ps: ┆ N13 ┆ ps: ┆ C   ┆ min ┆ C   │
│ 722 ┆ 722 ┆ ol2 ┆     ┆ sap ┆     ┆     ┆     ┆ Pol ┆ 212 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ sho ┆ cel ┆ c   ┆ cel ┆ enc ┆ eq  ┆ 73  ┆ a,, ┆ eg  ┆ rg  ┆     ┆ y   ┆ na  ┆     ┆ c   ┆ eq  ┆ 212 ┆ ftp ┆ 053 ┆     ┆ 722 ┆     ┆ ol2 ┆ l   ┆ hoc ┆     ┆ 759 ┆ //w ┆ //w ┆ 226 ┆ //d ┆     ┆ .   ┆ (in │
│ 7   ┆ 5   ┆ _si ┆     ┆ ien ┆     ┆     ┆     ┆ 2_s ┆ 9   ┆ Feb ┆ 9   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ ck  ┆ ls  ┆ DNA ┆ ls  ┆ ing ┆ rea ┆     ┆ Hum ┆ 51  ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 7   ┆     ┆ ,   ┆ siR ┆ k   ┆     ┆ 0   ┆ ww. ┆ ww. ┆ 630 ┆ oi. ┆     ┆     ┆ fer │
│     ┆     ┆ ctr ┆     ┆ s   ┆     ┆     ┆     ┆ iCt ┆ vs  ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ for ┆ wer ┆     ┆ wer ┆ of  ┆ ds  ┆     ┆ mel ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ clo ┆ NA  ┆ vs  ┆     ┆ vs  ┆ ncb ┆ ncb ┆ vs  ┆ org ┆     ┆     ┆ red │
│     ┆     ┆ l_h ┆     ┆     ┆     ┆     ┆     ┆ rl_ ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆ e   ┆     ┆ e   ┆ sam ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ ne: ┆ tra ┆ Non ┆     ┆ GSM ┆ i.n ┆ i.n ┆ SAM ┆ /10 ┆     ┆     ┆ )   │
│     ┆     ┆ s1  ┆     ┆     ┆     ┆     ┆     ┆ HS1 ┆ 415 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-s ┆ gro ┆     ┆ gro ┆ ple ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 415 ┆ .ni ┆     ┆     ┆ 710 ┆     ┆ 8WG ┆ nsf ┆ Hea ┆     ┆ 177 ┆ lm. ┆ lm. ┆ N13 ┆ .10 ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 212 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆ wn  ┆     ┆ wn  ┆ pre ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 212 ┆ h.g ┆     ┆     ┆ 722 ┆     ┆ 16  ┆ ect ┆ t-S ┆     ┆ 758 ┆ nih ┆ nih ┆ 226 ┆ 16/ ┆     ┆     ┆     │
│     ┆     ┆ vca ┆     ┆     ┆     ┆     ┆     ┆ VCa ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sam ┆ in  ┆     ┆ in  ┆ vio ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ ov/ ┆     ┆     ┆ 5   ┆     ┆ (Co ┆ ed  ┆ hoc ┆     ┆ 8   ┆ .go ┆ .go ┆ 632 ┆ j.m ┆     ┆     ┆     │
│     ┆     ┆ p_p ┆     ┆     ┆     ┆     ┆     ┆ P:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ DME ┆     ┆ DME ┆ usl ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ van ┆     ┆ k   ┆     ┆     ┆ v/b ┆ v/s ┆     ┆ olc ┆     ┆     ┆     │
│     ┆     ┆ ol2 ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ M   ┆     ┆ M   ┆ y   ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ ce, ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆     ┆ el. ┆     ┆     ┆     │
│     ┆     ┆ _si ┆     ┆     ┆     ┆     ┆     ┆ 2_s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆ med ┆     ┆ med ┆ sub ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆     ┆ 202 ┆     ┆     ┆     │
│     ┆     ┆ ctr ┆     ┆     ┆     ┆     ┆     ┆ iCt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ don ┆ ium ┆     ┆ ium ┆ mit ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ alo ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆     ┆ 1.0 ┆     ┆     ┆     │
│     ┆     ┆ l_c ┆     ┆     ┆     ┆     ┆     ┆ rl_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ sup ┆     ┆ sup ┆ ted ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ g#  ┆     ┆     ┆     ┆     ┆ SAM ┆ RX7 ┆     ┆ 1.0 ┆     ┆     ┆     │
│     ┆     ┆ trl ┆     ┆     ┆     ┆     ┆     ┆ Ctr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ ple ┆     ┆ ple ┆ to  ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 415 ┆     ┆     ┆     ┆     ┆ MMS ┆     ┆     ┆     ┆     ┆ N13 ┆ 107 ┆     ┆ 16  ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ l1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆ men ┆     ┆ men ┆ GEO ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2nn ┆     ┆     ┆     ┆     ┆ -12 ┆     ┆     ┆     ┆     ┆ 226 ┆ 227 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆ ted ┆     ┆ ted ┆ as  ┆ bui ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆ 6R, ┆     ┆     ┆     ┆     ┆ 630 ┆ vs  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆ wit ┆     ┆ wit ┆ GSM ┆ ld  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆ lot ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆ h   ┆     ┆ h   ┆ 177 ┆ hg3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 152 ┆     ┆     ┆     ┆     ┆ #   ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆ 10% ┆     ┆ 10% ┆ 759 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆     ┆     ┆ E12 ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uba ┆ fet ┆     ┆ fet ┆ 0   ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆ CF0 ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ a   ┆     ┆ a   ┆ vs  ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆ 048 ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ bov ┆     ┆ bov ┆ res ┆ Bow ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆ 1)  ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 30m ┆ ine ┆     ┆ ine ┆ equ ┆ tie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M41 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ lm. ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in. ┆ ser ┆     ┆ ser ┆ enc ┆ 2.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 521 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ nih ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sil ┆ um  ┆     ┆ um  ┆ ing ┆ Dup ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 29_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ .go ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ enc ┆ and ┆     ┆ and ┆ of  ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ v/s ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆ 1%  ┆     ┆ 1%  ┆ sam ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ ra? ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ pen ┆     ┆ pen ┆ ple ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ter ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VCa ┆ ici ┆     ┆ ici ┆ pre ┆ dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ m=S ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆ lli ┆     ┆ lli ┆ vio ┆ cor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ RX7 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ n/s ┆     ┆ n/s ┆ usl ┆ dan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ctr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ 107 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆ tre ┆     ┆ tre ┆ y   ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N13 ┆ 225 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆ pto ┆     ┆ pto ┆ sub ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S1. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 226 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ don ┆ myc ┆     ┆ myc ┆ mit ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 632 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ in  ┆     ┆ in  ┆ ted ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆ ant ┆     ┆ ant ┆ to  ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆ ibi ┆     ┆ ibi ┆ GEO ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nsf ┆ oti ┆     ┆ oti ┆ as  ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _de ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆ cs  ┆     ┆ cs  ┆ GSM ┆ d.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆ at  ┆     ┆ at  ┆ 177 ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _no ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ siR ┆ 37  ┆     ┆ 37  ┆ 758 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rm. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NA  ┆ deg ┆     ┆ deg ┆ 8   ┆ ann ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bw  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ ree ┆     ┆ ree ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ UBE ┆ C   ┆     ┆ C   ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2I  ┆ tem ┆     ┆ tem ┆     ┆ ns  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :// ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (si ┆ per ┆     ┆ per ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ UBE ┆ atu ┆     ┆ atu ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .nc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2I  ┆ re  ┆     ┆ re  ┆     ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

#### GSE259306 (NO DOWNLOAD)

- validation date: 2026-04-28
- [TurboCas: A method for locus-specific labeling of genomic regions and isolating their associated protein interactome](https://doi.org/10.1016/j.molcel.2024.11.007)
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)でフィルタリングされていると思われるデータをこちらで処理
- このエントリーには、ChIP-seqのデータはなかった

#### GSE69021 (NO DOWNLOAD)

- validate date: 2026-04-28
- [Gene target specificity of the Super Elongation Complex (SEC) family: how HIV-1 Tat employs selected SEC members to activate viral transcription](https://doi.org/10.1093/nar/gkv541)
- AFF4、AFF1に対してRNAiを行っているデータ
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb) で、bulk RNA-seq が含まれていないと判断し、収集していなかったデータ
- このエントリーではなく、同じ論文由来の別のアクセッションデータに ChIP-seq データが含まれている可能性

#### GSE182204 (NO DOWNLOAD)

- validation date: 2025-05-03
- [Acetyl-methyllysine marks chromatin at active transcription start sites](https://doi.org/10.1038/s41586-023-06565-9)
- RNA-seqに加え、TT-TL-seq (transient-transcriptome TimeLapse sequencing), start-TimeLapse sequencing (STL-seq) も含まれている
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb) で 収集しないと判断していたデータ
- このデータには、Drosophila melanogaster のデータも含まれており、こちらのデータで、熱ストレス曝露のサンプルが含まれていた

#### GSE112608 (NO DOWNLOAD) 

- validate date 2026-04-28
- [Targeting Processive Transcription Elongation via SEC Disruption for MYC-Induced Cancer Therapy](https://doi.org/10.1016/j.cell.2018.09.027)
- 論文内に以下のような記述を発見
- `Heat Shock Induction: Heat shock of mammalian cells was performed using ∼70%–80% confluent HCT-116 cells by adding pre-heated (42°C) conditioned media collected from identically growing cells (Mahat et al., 2016b). The heat shock cells were incubated at 42°C for 1 hour. After washing with PBS, the heat shock and non-heat shock HCT-116 cells were fixed with 1% formaldehyde in PBS for downstream ChIP-seq analysis. For heat shock induction of Drosophila S2 cells, the S2 cells were mixed with pre-heated medium to instantly increase the medium temperature from 24°C to 37°C and maintained in a water bath at 37°C for 10 min before fixation for ChIP-seq.`
- 探索したものの、明示的に熱ストレスと記載があるアクセッションがなかったので、今回は収集しない

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 2. GSE145525 (ChIP-seq; Pol II)

- validation date: 2025-05-06
- [Acute perturbation strategies in interrogating RNA polymerase II elongation factor function in gene expression](https://doi.org/10.1101/gad.346106.120)
- mRNA-seqとChIP-seqのデータが含まれている、RNA polymerase IIに関連したデータ
- [./12_4_metadata_modified_false_no_control.ipynb](./12_4_metadata_modified_false_no_control.ipynb) で、フィルタリングされていたデータを再確認
- BRD4に対してAIDシステム (タンパク質ノックダウンシステム) を行っている + 42℃ 60min.を行っているデータなどが含まれている

In [6]:
GSE145525_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE145525/GSE145525_PEP/GSE145525_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    (pl.col("sample_library_strategy") == "ChIP-Seq") &

    # Because of antigen class is unclassified in ChIP-atlas, so these entry is removed
    (pl.col("sample_name") != "0hdmso_aid660_brd4aid_dld_rep1") & # SRX7748770
    (pl.col("sample_name") != "2haux_2hdmso_aid660_brd4aid_dld_rep1") & # SRX7748772

    # treatment : Auxin
    (pl.col("sample_name") != "2haux_brd2cst_brd2aid_dld_rep1") & # SRX7748767
    (pl.col("sample_name") != "2haux_brd3bethyl_brd3aid_dld_rep1") & # SRX7748769
    (pl.col("sample_name") != "pol2_0h_h6_brd2aid_hct116_rep1") & # SRX9390303
    (pl.col("sample_name") != "pol2_1h_h6_brd2aid_hct116_rep1") & # SRX9390304
    (pl.col("sample_name") != "pol2_4h_h6_brd2aid_hct116_rep1") & # SRX9390305
    (pl.col("sample_name") != "pol2_24h_h6_brd2aid_hct116_rep1") & # SRX9390306

    # treatment: dBET6
    (pl.col("sample_name") != "2hdbet6_37c1h_pol2cst_brd4aid_dld_rep1") & # SRX7748701
    (pl.col("sample_name") != "2hdbet6_37c1h_pol2cst_wt_dld_rep1") & # SRX7748693
    (pl.col("sample_name") != "2hdbet6_aid660_brd4aid_dld_rep1") &  # SRX7748771

    # genotype: BRD2-AID OsTIR1
    (pl.col("sample_name") != "2hh2o_brd2cst_brd2aid_dld_rep1") & # SRX7748766

    # genotype: BRD3-AID OsTIR1
    (pl.col("sample_name") != "2hh2o_brd3bethyl_brd3aid_dld_rep1") & # SRX7748768

    # Input sample
    (pl.col("sample_name") != "input_2hdmso_37c1h_brd4aid_dld_rep1") & # SRX7748805
    (pl.col("sample_name") != "input_2hh2o_37c1h_wt_dld_rep1")  # SRX7748806   
).sort(
    by="sample_name"
).with_columns(
    pl.lit("https://doi.org/10.1101/gad.346106.120").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)


GSE145525 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE145525_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE145525_filtered = GSE145525[[s.name for s in GSE145525 if not (s.null_count() == GSE145525.height)]]

GSE145525_combined = GSE145525_PEP.join(
    GSE145525_filtered,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE145525_combined = GSE145525_combined[[s.name for s in GSE145525_combined if not (s.null_count() == GSE145525_combined.height)]]

pl.Config.set_tbl_rows(2)
display(GSE145525_combined)

shape: (104, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ gen ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ sra ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ oty ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ pe  ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ 5   ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ i64 ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ i64 ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ ght ┆ l   ┆ str ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 2ha ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ 2hA ┆ GSM ┆ Pub ┆ Feb ┆ Jan ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ Cel ┆ DLD ┆ gen ┆ For ┆ AFF ┆ For ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Col ┆ AFF ┆ AF4 ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Nex ┆ SAM ┆ Acu ┆ SRA ┆ ChI ┆ 202 ┆ 422 ┆ 634 ┆ ILL ┆ Gen ┆ 2hA ┆ db5 ┆ SRP ┆ 218 ┆ Acu ┆ 2hA ┆ Nex ┆ Nex ┆ 2cd ┆ 110 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ Col ┆ 202 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ ux_ ┆ P   ┆ o   ┆ GLE ┆     ┆ 111 ┆ 774 ┆ ux_ ┆ 432 ┆ lic ┆ 19  ┆ 16  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ ls  ┆ -1  ┆ omi ┆ ChI ┆ 1   ┆ ChI ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 432 ┆ :// ┆ 145 ┆     ┆ 774 ┆ ore ┆ 1-A ┆ Bet ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N14 ┆ te  ┆ 104 ┆ P   ┆ 1-0 ┆ 955 ┆ 815 ┆ UMI ┆ eri ┆ ux_ ┆ c85 ┆ 249 ┆ 839 ┆ te  ┆ ux_ ┆ tSe ┆ tSe ┆ 6d4 ┆ 558 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 432 ┆ 432 ┆ ChI ┆ 432 ┆     ┆ ore ┆ 1-0 ┆ NA6 ┆ 111 ┆ 616 ┆ 1-0 ┆ 145 │
│ 37c ┆     ┆ sap ┆     ┆     ┆ 117 ┆ 878 ┆ 37C ┆ 029 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ cel ┆ c   ┆ P-s ┆ ChI ┆ P-s ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 029 ┆ ftp ┆ 525 ┆     ┆ 878 ┆ cta ┆ ID  ┆ hyl ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 135 ┆ per ┆ 457 ┆     ┆ 1-1 ┆ 609 ┆ 249 ┆ NA  ┆ c   ┆ 37C ┆ 80e ┆ 997 ┆ 42  ┆ per ┆ 37C ┆ q   ┆ q   ┆ 554 ┆ 620 ┆ eq  ┆ C   ┆     ┆     ┆ 029 ┆ 029 ┆ P-s ┆ 029 ┆     ┆ cta ┆ 1-1 ┆ 075 ┆ 117 ┆ 808 ┆ 1-1 ┆ 525 │
│ 1h_ ┆     ┆ ien ┆     ┆     ┆ 66  ┆ 6   ┆ 1h_ ┆ 1   ┆ Jan ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ ls  ┆ DNA ┆ eq, ┆ P-s ┆ eq, ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 1   ┆ .nc ┆     ┆     ┆ 6   ┆ l   ┆ OsT ┆ A30 ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 441 ┆ tur ┆ 2   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ 1h_ ┆ 3ad ┆     ┆     ┆ tur ┆ 1h_ ┆ 500 ┆ 500 ┆ 5c4 ┆ 5   ┆     ┆     ┆     ┆     ┆ 1   ┆ 1_r ┆ eq, ┆ 1   ┆     ┆ l   ┆ 7   ┆ 07  ┆ 66  ┆ 8   ┆ 7   ┆     │
│ aff ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ AFF ┆     ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tre ┆ wer ┆     ┆ 20- ┆ eq  ┆ sin ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆ ade ┆ IR1 ┆ 2-3 ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆     ┆ bat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AFF ┆ efe ┆     ┆     ┆ bat ┆ AFF ┆     ┆ seq ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 20- ┆     ┆     ┆ ade ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1be ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1Be ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ e   ┆     ┆ 50  ┆     ┆ gle ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆ noc ┆     ┆ 45A ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1Be ┆ d17 ┆     ┆     ┆ ion ┆ 1Be ┆     ┆ uen ┆ bf3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50  ┆     ┆     ┆ noc ┆     ┆     ┆     ┆     ┆     ┆     │
│ thy ┆     ┆     ┆     ┆     ┆     ┆     ┆ thy ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ cul ┆     ┆ mil ┆     ┆ -en ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆ arc ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ cin ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ thy ┆ 082 ┆     ┆     ┆ str ┆ thy ┆     ┆ cin ┆ 15e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mil ┆     ┆     ┆ arc ┆     ┆     ┆     ┆     ┆     ┆     │
│ l_a ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆ tur ┆     ┆ lio ┆     ┆ d   ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆ ino ┆     ┆     ┆     ┆ nih ┆ nih ┆ 01/ ┆     ┆     ┆ g:  ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆ 98e ┆     ┆     ┆ ate ┆ l_A ┆     ┆ g:  ┆ 1b7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lio ┆     ┆     ┆ ino ┆     ┆     ┆     ┆     ┆     ┆     │
│ ff1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ ed  ┆     ┆ n   ┆     ┆ raw ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆ .go ┆ .go ┆ gad ┆     ┆     ┆ GSM ┆     ┆ gie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆ b4a ┆     ┆     ┆ gie ┆ FF1 ┆     ┆ GSM ┆ e7c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆     ┆     ┆     │
│ aid ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆ in  ┆     ┆ cel ┆     ┆ rea ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ DLD ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ .34 ┆     ┆     ┆ 432 ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆ 1fb ┆     ┆     ┆ s   ┆ AID ┆     ┆ 432 ┆ 98c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ DLD ┆     ┆     ┆     ┆     ┆     ┆     │
│ _dl ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ µM  ┆ DME ┆     ┆ ls  ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ -1  ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 610 ┆     ┆     ┆ 029 ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DL ┆ 78  ┆     ┆     ┆ in  ┆ _DL ┆     ┆ 029 ┆ 81  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ -1  ┆     ┆     ┆     ┆     ┆     ┆     │
│ d_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Aux ┆ M   ┆     ┆ wer ┆     ┆ wer ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 6.1 ┆     ┆     ┆ 1:  ┆     ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆ int ┆ D_r ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ (Co ┆     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 20  ┆     ┆     ┆ 2hA ┆     ┆ err ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆ err ┆ ep1 ┆     ┆ 2hA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (3- ┆ rni ┆     ┆ cro ┆     ┆ tri ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX7 ┆     ┆     ┆     ┆ ux_ ┆     ┆ oga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oga ┆     ┆     ┆ ux_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ind ┆ ng) ┆     ┆ ssl ┆     ┆ mme ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 432 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N14 ┆ 748 ┆     ┆     ┆     ┆ 37C ┆     ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tin ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ole ┆ sup ┆     ┆ ink ┆     ┆ d   ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 135 ┆ 786 ┆     ┆     ┆     ┆ 1h_ ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆ 1h_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -ac ┆ ple ┆     ┆ ed  ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 441 ┆     ┆     ┆     ┆     ┆ AFF ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ AFF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆ men ┆     ┆ wit ┆     ┆ Tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1Be ┆     ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆     ┆ 1Be ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆ ted ┆     ┆ h   ┆     ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ thy ┆     ┆ yme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yme ┆     ┆     ┆ thy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aci ┆ wit ┆     ┆ 1%  ┆     ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 291 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆     ┆ ras ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ras ┆     ┆     ┆ l_A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ h   ┆     ┆ par ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ FF1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sod ┆ 10% ┆     ┆ afo ┆     ┆ 0.3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆     ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆     ┆ AID ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ afo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ium ┆ FBS ┆     ┆ rma ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DL ┆     ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ _DL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sal ┆ (Co ┆     ┆ lde ┆     ┆ (Bo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M43 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆ nga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nga ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [7]:
defined_pairs_gse145525_chipseq = [
    ("SRX7748788", "SRX7748786"), # 2haux_42c1h_aff1bethyl_aff1aid_dld_rep1 vs. 2haux_37c1h_aff1bethyl_aff1aid_dld_rep1
    ("SRX7748792", "SRX7748790"), # 2haux_42c1h_aff4protec_aff4aid_dld_rep1 vs. 2haux_37c1h_aff4protec_aff4aid_dld_rep1
    ("SRX7748800", "SRX7748798"), # 2haux_42c1h_aid660_aff1aid_dld_rep1 vs. 2haux_37c1h_aid660_aff1aid_dld_rep1
    ("SRX7748804", "SRX7748802"), # 2haux_42c1h_aid660_aff4aid_dld_rep1 vs. 2haux_37c1h_aid660_aff4aid_dld_rep1
    ("SRX7748776", "SRX7748774"), # 2haux_42c1h_aid660_brd2aid_dld_rep1 vs. 2haux_37c1h_aid660_brd2aid_dld_rep1
    ("SRX7748784", "SRX7748782"), # 2haux_42c1h_aid660_brd3aid_dld_rep1 vs. 2haux_37c1h_aid660_brd3aid_dld_rep1
    ("SRX7748780", "SRX7748778"), # 2haux_42c1h_aid660_brd4aid_dld_rep1 vs. 2haux_37c1h_aid660_brd4aid_dld_rep1
    ("SRX7748796", "SRX7748794"), # 2haux_42c1h_aid660_doubleaid_dld_rep1 vs. 2haux_37c1h_aid660_doubleaid_dld_rep1

    # pair3_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_aff1aid_dld.txt 
    # pair3_GSE145525_pol2_ctrl_2haux_aff1aid_dld.txt
    ("SRX7748741", "SRX7748739"), # 2haux_42c1h_pol2cst_aff1aid_dld_rep1 vs. 2haux_37c1h_pol2cst_aff1aid_dld_rep1
    ("SRX7748753", "SRX7748751"), # 2haux_42c1h_pol2cst_aff1aid_dld_rep2 vs. 2haux_37c1h_pol2cst_aff1aid_dld_rep2
    ("SRX7748761", "SRX7748759"), # 2haux_42c1h_pol2cst_aff1aid_dld_rep3 vs. 2haux_37c1h_pol2cst_aff1aid_dld_rep3

    
    # pair4_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_aff4aid_dld.txt
    # pair4_GSE145525_pol2_ctrl_2haux_aff4aid_dld.txt
    ("SRX7748745", "SRX7748743"), # 2haux_42c1h_pol2cst_aff4aid_dld_rep1 vs. 2haux_37c1h_pol2cst_aff4aid_dld_rep1
    ("SRX7748757", "SRX7748755"), # 2haux_42c1h_pol2cst_aff4aid_dld_rep2 vs. 2haux_37c1h_pol2cst_aff4aid_dld_rep2
    ("SRX7748765", "SRX7748763"), # 2haux_42c1h_pol2cst_aff4aid_dld_rep3 vs. 2haux_37c1h_pol2cst_aff4aid_dld_rep3


    # pair5_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_brd2aid_dld.txt
    # pair5_GSE145525_pol2_ctrl_2haux_brd2aid_dld.txt
    ("SRX7748715", "SRX7748695"), # 2haux_42c1h_pol2cst_brd2aid_dld_rep1 vs. 2haux_37c1h_pol2cst_brd2aid_dld_rep1
    ("SRX7748722", "SRX7748703"), # 2haux_42c1h_pol2cst_brd2aid_dld_rep2 vs. 2haux_37c1h_pol2cst_brd2aid_dld_rep2
 
    # replicate が 2つ以上ない?
    # ありました！
    # pair6_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_brd3aid_dld.txt
    # pair6_GSE145525_pol2_ctrl_2haux_brd3aid_dld.txt
    ("SRX7748717", "SRX7748697"), # 2haux_42c1h_pol2cst_brd3aid_dld_rep1 vs. 2haux_37c1h_pol2cst_brd3aid_dld_rep1
    ("SRX7748724", "SRX7748705"), # 2haux_42c1h_pol2cst_brd3aid_dld_rep2 vs. 2haux_37c1h_pol2cst_brd3aid_dld_rep2


    # pair7_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_brd4aid_dld.txt
    # pair7_GSE145525_pol2_ctrl_2haux_brd4aid_dld.txt
    ("SRX7748719", "SRX7748699"), # 2haux_42c1h_pol2cst_brd4aid_dld_rep1 vs. 2haux_37c1h_pol2cst_brd4aid_dld_rep1
    ("SRX7748726", "SRX7748707"), # 2haux_42c1h_pol2cst_brd4aid_dld_rep2 vs. 2haux_37c1h_pol2cst_brd4aid_dld_rep2
    ("SRX7748729", "SRX7748709"), # 2haux_42c1h_pol2cst_brd4aid_dld_rep3 vs. 2haux_37c1h_pol2cst_brd4aid_dld_rep3

    # pair8_GSE145525_pol2_hs_42C_60min_2haux_pol2cst_doubleaid_dld.txt
    # pair8_GSE145525_pol2_ctrl_2haux_doubleaid_dld.txt
    ("SRX7748733", "SRX7748732"), # 2haux_42c1h_pol2cst_doubleaid_dld_rep1 vs. 2haux_37c1h_pol2cst_doubleaid_dld_rep1
    ("SRX7748737", "SRX7748736"), # 2haux_42c1h_pol2cst_doubleaid_dld_rep2 vs. 2haux_37c1h_pol2cst_doubleaid_dld_rep2

    # replicate が 2つ以上ない?
    ("SRX7748727", "SRX7748700"), # 2hdmso_42c1h_pol2cst_brd4aid_dld_rep2 vs. 2hdmso_37c1h_pol2cst_brd4aid_dld_rep2
    ("SRX7748720", "SRX7748692"), # 2hdmso_42c1h_pol2cst_wt_dld_rep1 vs. 2hdmso_37c1h_pol2cst_wt_dld_rep1
    
    ("SRX7748787", "SRX7748785"), # 2hh2o_42c1h_aff1bethyl_aff1aid_dld_rep1 vs. 2hh2o_37c1h_aff1bethyl_aff1aid_dld_rep1
    ("SRX7748791", "SRX7748789"), # 2hh2o_42c1h_aff4protec_aff4aid_dld_rep1 vs. 2hh2o_37c1h_aff4protec_aff4aid_dld_rep1
    ("SRX7748799", "SRX7748797"), # 2hh2o_42c1h_aid660_aff1aid_dld_rep1 vs. 2hh2o_37c1h_aid660_aff1aid_dld_rep1
    ("SRX7748803", "SRX7748801"), # 2hh2o_42c1h_aid660_aff4aid_dld_rep1 vs. 2hh2o_37c1h_aid660_aff4aid_dld_rep1
    ("SRX7748775", "SRX7748773"), # 2hh2o_42c1h_aid660_brd2aid_dld_rep1 vs. 2hh2o_37c1h_aid660_brd2aid_dld_rep1
    ("SRX7748783", "SRX7748781"), # 2hh2o_42c1h_aid660_brd3aid_dld_rep1 vs. 2hh2o_37c1h_aid660_brd3aid_dld_rep1
    ("SRX7748779", "SRX7748777"), # 2hh2o_42c1h_aid660_brd4aid_dld_rep1 vs. 2hh2o_37c1h_aid660_brd4aid_dld_rep1
    ("SRX7748795", "SRX7748793"), # 2hh2o_42c1h_aid660_doubleaid_dld_rep1 vs. 2hh2o_37c1h_aid660_doubleaid_dld_rep1

    # pair9_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_aff1aid_dld.txt
    # pair9_GSE145525_pol2_ctrl_2hh2o_aff1aid_dld.txt
    ("SRX7748740", "SRX7748738"), # 2hh2o_42c1h_pol2cst_aff1aid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_aff1aid_dld_rep1
    ("SRX7748752", "SRX7748750"), # 2hh2o_42c1h_pol2cst_aff1aid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_aff1aid_dld_rep2
    ("SRX7748760", "SRX7748758"), # 2hh2o_42c1h_pol2cst_aff1aid_dld_rep3 vs. 2hh2o_37c1h_pol2cst_aff1aid_dld_rep3

    # pair10_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_aff4aid_dld.txt
    # pair10_GSE145525_pol2_ctrl_2hh2o_aff4aid_dld.txt
    ("SRX7748744", "SRX7748742"), # 2hh2o_42c1h_pol2cst_aff4aid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_aff4aid_dld_rep1
    ("SRX7748756", "SRX7748754"), # 2hh2o_42c1h_pol2cst_aff4aid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_aff4aid_dld_rep2
    ("SRX7748764", "SRX7748762"), # 2hh2o_42c1h_pol2cst_aff4aid_dld_rep3 vs. 2hh2o_37c1h_pol2cst_aff4aid_dld_rep3

    # pair11_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_brd2aid_dld.txt
    # pair11_GSE145525_pol2_ctrl_2hh2o_brd2aid_dld.txt
    ("SRX7748714", "SRX7748694"), # 2hh2o_42c1h_pol2cst_brd2aid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_brd2aid_dld_rep1
    ("SRX7748721", "SRX7748702"), # 2hh2o_42c1h_pol2cst_brd2aid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_brd2aid_dld_rep2

    # pair12_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_brd3aid_dld.txt
    # pair12_GSE145525_pol2_ctrl_2hh2o_brd3aid_dld.txt
    ("SRX7748716", "SRX7748696"), # 2hh2o_42c1h_pol2cst_brd3aid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_brd3aid_dld_rep1
    ("SRX7748723", "SRX7748704"), # 2hh2o_42c1h_pol2cst_brd3aid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_brd3aid_dld_rep2

    # pair13_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_brd4aid_dld.txt
    # pair13_GSE145525_pol2_ctrl_2hh2o_brd4aid_dld.txt
    ("SRX7748718", "SRX7748698"), # 2hh2o_42c1h_pol2cst_brd4aid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_brd4aid_dld_rep1
    ("SRX7748725", "SRX7748706"), # 2hh2o_42c1h_pol2cst_brd4aid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_brd4aid_dld_rep2
    ("SRX7748728", "SRX7748708"), # 2hh2o_42c1h_pol2cst_brd4aid_dld_rep3 vs. 2hh2o_37c1h_pol2cst_brd4aid_dld_rep3

    # pair14_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_doubleaid_dld.txt
    # pair14_GSE145525_pol2_ctrl_2hh2o_doubleaid_dld.txt
    ("SRX7748731", "SRX7748730"), # 2hh2o_42c1h_pol2cst_doubleaid_dld_rep1 vs. 2hh2o_37c1h_pol2cst_doubleaid_dld_rep1
    ("SRX7748735", "SRX7748734"), # 2hh2o_42c1h_pol2cst_doubleaid_dld_rep2 vs. 2hh2o_37c1h_pol2cst_doubleaid_dld_rep2

    # pair15_GSE145525_pol2_hs_42C_60min_2hh2o_pol2cst_wt_dld.txt
    # pair15_GSE145525_pol2_ctrl_2hh2o_wt_dld.txt
    ("SRX7748711", "SRX7748710"), # 2hh2o_42c1h_pol2cst_wt_dld_rep1 vs. 2hh2o_37c1h_pol2cst_wt_dld_rep1
    ("SRX7748713", "SRX7748712"), # 2hh2o_42c1h_pol2cst_wt_dld_rep3 vs. 2hh2o_37c1h_pol2cst_wt_dld_rep3


    # replicate が 2つ以上ない?
    ("SRX7748748", "SRX7748746"), # 6hdmso_42c1h_pol2cst_aff4aid_dld_rep1 vs. 6hdmso_37c1h_pol2cst_aff4aid_dld_rep1

    # replicate が 2つ以上ない?
    ("SRX7748749", "SRX7748747"), # 6hkl1_20um_42c1h_pol2cst_aff4aid_dld_rep1 vs. 6hkl1_20um_37c1h_pol2cst_aff4aid_dld_rep1
]

paired_metada_df_gse145525 = create_paired_metadata(
    combined_df=GSE145525_combined,
    defined_sample_pairs=defined_pairs_gse145525_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse145525 is not None:
    paired_metada_df_gse145525.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE145525_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metada_df_gse145525)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (52, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ gen ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ sra ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ oty ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ pe  ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ 5   ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ 2ha ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ 2hA ┆ GSM ┆ Pub ┆ Feb ┆ Jan ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ Cel ┆ DLD ┆ gen ┆ For ┆ AFF ┆ For ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Col ┆ AFF ┆ AF4 ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Nex ┆ SAM ┆ Acu ┆ SRA ┆ ChI ┆ 202 ┆ 508 ┆ 763 ┆ ILL ┆ Gen ┆ 2hA ┆ cc0 ┆ SRP ┆ 264 ┆ Acu ┆ 2hA ┆ Nex ┆ Nex ┆ 8d4 ┆ 133 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ Col ┆ 202 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 774 ┆ 774 ┆ ux_ ┆ P   ┆ o   ┆ GLE ┆     ┆ 111 ┆ ux_ ┆ 432 ┆ lic ┆ 19  ┆ 16  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ ls  ┆ -1  ┆ omi ┆ ChI ┆ 1   ┆ ChI ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 432 ┆ :// ┆ 145 ┆     ┆ 774 ┆ ore ┆ 1-A ┆ Bet ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N14 ┆ te  ┆ 104 ┆ P   ┆ 1-0 ┆ 544 ┆ 516 ┆ UMI ┆ eri ┆ ux_ ┆ dde ┆ 249 ┆ 248 ┆ te  ┆ ux_ ┆ tSe ┆ tSe ┆ dc0 ┆ 509 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 432 ┆ 432 ┆ ChI ┆ 432 ┆     ┆ ore ┆ 1-0 ┆ NA6 ┆ 111 ┆ 616 ┆ 1-0 ┆ 145 │
│ 878 ┆ 878 ┆ 42c ┆     ┆ sap ┆     ┆     ┆ 117 ┆ 42C ┆ 029 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ cel ┆ c   ┆ P-s ┆ ChI ┆ P-s ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 029 ┆ ftp ┆ 525 ┆     ┆ 878 ┆ cta ┆ ID  ┆ hyl ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 135 ┆ per ┆ 457 ┆     ┆ 1-1 ┆ 446 ┆ 731 ┆ NA  ┆ c   ┆ 42C ┆ bbc ┆ 997 ┆ 72  ┆ per ┆ 42C ┆ q   ┆ q   ┆ a8b ┆ 157 ┆ eq  ┆ C   ┆     ┆     ┆ 029 ┆ 029 ┆ P-s ┆ 029 ┆     ┆ cta ┆ 1-1 ┆ 075 ┆ 117 ┆ 809 ┆ 1-1 ┆ 525 │
│ 8   ┆ 6   ┆ 1h_ ┆     ┆ ien ┆     ┆     ┆ 68  ┆ 1h_ ┆ 3   ┆ Jan ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ ls  ┆ DNA ┆ eq, ┆ P-s ┆ eq, ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 3   ┆ .nc ┆     ┆     ┆ 8   ┆ l   ┆ OsT ┆ A30 ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 439 ┆ tur ┆ 2   ┆     ┆ 7   ┆ vs  ┆ vs  ┆     ┆     ┆ 1h_ ┆ 885 ┆     ┆ vs  ┆ tur ┆ 1h_ ┆ 500 ┆ 500 ┆ 1bc ┆ 6   ┆     ┆     ┆     ┆     ┆ 3   ┆ 3_r ┆ eq, ┆ 3   ┆     ┆ l   ┆ 7   ┆ 07  ┆ 68  ┆ 0   ┆ 7   ┆     │
│     ┆     ┆ aff ┆     ┆ s   ┆     ┆     ┆ vs  ┆ AFF ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tre ┆ wer ┆     ┆ 20- ┆ eq  ┆ sin ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ ade ┆ IR1 ┆ 2-3 ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆ vs  ┆ bat ┆     ┆     ┆     ┆ 422 ┆ 634 ┆     ┆     ┆ AFF ┆ 6b3 ┆     ┆ 218 ┆ bat ┆ AFF ┆     ┆ seq ┆ a4b ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆ 1   ┆ 20- ┆ vs  ┆     ┆ ade ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ 1be ┆     ┆     ┆     ┆     ┆ SRR ┆ 1Be ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ e   ┆     ┆ 50  ┆     ┆ gle ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ noc ┆     ┆ 45A ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆ SAM ┆ ion ┆     ┆     ┆     ┆ 955 ┆ 815 ┆     ┆     ┆ 1Be ┆ 824 ┆     ┆ 839 ┆ ion ┆ 1Be ┆     ┆ uen ┆ d1a ┆ 110 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ 50  ┆ GSM ┆     ┆ noc ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ thy ┆     ┆     ┆     ┆     ┆ 111 ┆ thy ┆ 432 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ cul ┆     ┆ mil ┆     ┆ -en ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 432 ┆ .ni ┆     ┆     ┆ 774 ┆ arc ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ cin ┆ N14 ┆ str ┆     ┆     ┆     ┆ 609 ┆ 249 ┆     ┆     ┆ thy ┆ a19 ┆     ┆ 42  ┆ str ┆ thy ┆     ┆ cin ┆ 1c7 ┆ 558 ┆     ┆     ┆     ┆     ┆ 432 ┆ GSM ┆ mil ┆ 432 ┆     ┆ arc ┆     ┆     ┆ 111 ┆ 616 ┆     ┆     │
│     ┆     ┆ l_a ┆     ┆     ┆     ┆     ┆ 117 ┆ l_A ┆ 029 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆ tur ┆     ┆ lio ┆     ┆ d   ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 029 ┆ h.g ┆     ┆     ┆ 878 ┆ ino ┆     ┆     ┆     ┆ nih ┆ nih ┆ 01/ ┆     ┆     ┆ g:  ┆ 135 ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆ bc8 ┆     ┆     ┆ ate ┆ l_A ┆     ┆ g:  ┆ 0de ┆ 620 ┆     ┆     ┆     ┆     ┆ 029 ┆ 432 ┆ lio ┆ 029 ┆     ┆ ino ┆     ┆     ┆ 117 ┆ 808 ┆     ┆     │
│     ┆     ┆ ff1 ┆     ┆     ┆     ┆     ┆ 66  ┆ FF1 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ ed  ┆     ┆ n   ┆     ┆ raw ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆     ┆     ┆ 6   ┆ ma  ┆     ┆     ┆     ┆ .go ┆ .go ┆ gad ┆     ┆     ┆ GSM ┆ 441 ┆ gie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆ e37 ┆     ┆     ┆ gie ┆ FF1 ┆     ┆ GSM ┆ 58e ┆ 5   ┆     ┆     ┆     ┆     ┆ 1   ┆ 029 ┆ n   ┆ 1   ┆     ┆ ma  ┆     ┆     ┆ 66  ┆ 8   ┆     ┆     │
│     ┆     ┆ aid ┆     ┆     ┆     ┆     ┆     ┆ AID ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆ in  ┆     ┆ cel ┆     ┆ rea ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ DLD ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ .34 ┆     ┆     ┆ 432 ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆ e24 ┆     ┆     ┆ s   ┆ AID ┆     ┆ 432 ┆ a06 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ cel ┆     ┆     ┆ DLD ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _dl ┆     ┆     ┆     ┆     ┆     ┆ _DL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ µM  ┆ DME ┆     ┆ ls  ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ -1  ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 610 ┆     ┆     ┆ 029 ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _DL ┆ db  ┆     ┆     ┆ in  ┆ _DL ┆     ┆ 029 ┆ 6b  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ls  ┆     ┆     ┆ -1  ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ d_r ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Aux ┆ M   ┆     ┆ wer ┆     ┆ wer ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 6.1 ┆     ┆     ┆ 3:  ┆     ┆ int ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_r ┆ vs  ┆     ┆     ┆ int ┆ D_r ┆     ┆ 3:  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ (Co ┆     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 20  ┆     ┆     ┆ 2hA ┆     ┆ err ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆ db5 ┆     ┆     ┆ err ┆ ep1 ┆     ┆ 2hA ┆ 2cd ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (3- ┆ rni ┆     ┆ cro ┆     ┆ tri ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX7 ┆     ┆     ┆     ┆ ux_ ┆     ┆ oga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ c85 ┆     ┆     ┆ oga ┆ vs  ┆     ┆ ux_ ┆ 6d4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2ha ┆     ┆     ┆     ┆     ┆     ┆ 2hA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ind ┆ ng) ┆     ┆ ssl ┆     ┆ mme ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 432 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N14 ┆ 748 ┆     ┆     ┆     ┆ 42C ┆     ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2hA ┆ 80e ┆     ┆     ┆ tin ┆ 2hA ┆     ┆ 42C ┆ 554 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ux_ ┆     ┆     ┆     ┆     ┆     ┆ ux_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ole ┆ sup ┆     ┆ ink ┆     ┆ d   ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 135 ┆ 788 ┆     ┆     ┆     ┆ 1h_ ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ux_ ┆ 3ad ┆     ┆     ┆ g   ┆ ux_ ┆     ┆ 1h_ ┆ 5c4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 37c ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -ac ┆ ple ┆     ┆ ed  ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 439 ┆ vs  ┆     ┆     ┆     ┆ AFF ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆ efe ┆     ┆     ┆ RNA ┆ 37C ┆     ┆ AFF ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1h_ ┆     ┆     ┆     ┆     ┆     ┆ 1h_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆ men ┆     ┆ wit ┆     ┆ Tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ 1Be ┆     ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1h_ ┆ d17 ┆     ┆     ┆ Pol ┆ 1h_ ┆     ┆ 1Be ┆ bf3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ aff ┆     ┆     ┆     ┆     ┆     ┆ AFF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆ ted ┆     ┆ h   ┆     ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ thy ┆     ┆ yme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AFF ┆ 082 ┆     ┆     ┆ yme ┆ AFF ┆     ┆ thy ┆ 15e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1be ┆     ┆     ┆     ┆     ┆     ┆ 1Be ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aci ┆ wit ┆     ┆ 1%  ┆     ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ l_A ┆     ┆ ras ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1Be ┆ 98e ┆     ┆     ┆ ras ┆ 1Be ┆     ┆ l_A ┆ 1b7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ thy ┆     ┆     ┆     ┆     ┆     ┆ thy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ h   ┆     ┆ par ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ FF1 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ thy ┆ b4a ┆     ┆     ┆ e   ┆ thy ┆     ┆ FF1 ┆ e7c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ l_a ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sod ┆ 10% ┆     ┆ afo ┆     ┆ 0.3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ AID ┆     ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l_A ┆ 1fb ┆     ┆     ┆ II  ┆ l_A ┆     ┆ AID ┆ 98c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ afo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ff1 ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ium ┆ FBS ┆     ┆ rma ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆ _DL ┆     ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FF1 ┆ 78  ┆     ┆     ┆ elo ┆ FF1 ┆     ┆ _DL ┆ 81  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## Strategy 1. Gene Expression Omnibus (GEO) から 一旦リストを集める

- 全てのリストを調べるのは不可能なので、以下のクエリでヒットしたアクセッションを調べる (2026-04-23)
- [../../Data/curation/GEO_ChIPseq_result/gds_result_summary_260423_chipseq_modified.md](../../Data/curation/GEO_ChIPseq_result/gds_result_summary_260423_chipseq_modified.md) のリストから取得
- `genome binding/occupancy profiling by high throughput sequencing` であることに注意

```text
Search (((("homo sapiens"[Organism]) AND "genome binding/occupancy profiling by high throughput sequen"[Filter]) \
AND "gds sra"[Filter])) AND \
(((((("heat shock response"[MeSH Terms]) OR \
"heat shock"[Description]) OR \
"heat stress"[Description]) OR \
"high temperature stress"[Description]) OR \
"hyperthermia"[Description]) OR \
"heat stroke"[Description])
```

&nbsp;

&nbsp;

## 3. GSE38901 (ChIP-seq; HSF1)

&nbsp;

- [HSF1 Drives a Transcriptional Program Distinct from Heat Shock to Support Highly Malignant Human Cancers](https://doi.org/10.1016/j.cell.2012.06.031)
- 42 C & 1h.
- replicate が2つ以上あることを満たす MCF10A のデータセットを ChIP-Atlas Diff Analysis に供する

In [8]:
GSE38901_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE38901/GSE38901_PEP/GSE38901_PEP_raw.csv",
    separator=','
).filter(
    (
        (pl.col("sample_name").str.contains("hme_")) |
        (pl.col("sample_name").str.contains("bpe_")) |
        (pl.col("sample_name").str.contains("mcf10a_"))
    ) &
    (~pl.col("sample_name").str.contains("_igg_")) & # remove IgG control
    (pl.col("organism") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1016/j.cell.2012.06.031").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE38901 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE38901.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE38901_filtered = GSE38901[[s.name for s in GSE38901 if not (s.null_count() == GSE38901.height)]]

GSE38901_combined = GSE38901_PEP.join(
    GSE38901_filtered,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE38901_combined = GSE38901_combined[[s.name for s in GSE38901_combined if not (s.null_count() == GSE38901_combined.height)]]

# pl.Config.set_tbl_rows(11)
# display(GSE38901_combined)

In [9]:
defined_pairs_gse38901_chipseq = [
    ("SRX155719", "SRX155715"), # HME_HS_HSF1_ChIPSeq_1 vs. HME_HSF1_ChIPSeq
    ("SRX155764", "SRX155715"), # HME_HS_HSF1_ChIPSeq_2 vs. HME_HSF1_ChIPSeq
    ("SRX155721", "SRX155717"), # BPE_HS_HSF1_ChIPSeq_1 vs. BPE_HSF1_ChIPSeq
    ("SRX155763", "SRX155717"), # BPE_HS_HSF1_ChIPSeq_2 vs. BPE_HSF1_ChIPSeq
    ("SRX155765", "SRX155717"), # BPE_HS_HSF1_ChIPSeq_3 vs. BPE_HSF1_ChIPSeq

    # pair1_GSE38901_hsf1_mcf10a_hs_42C_60min.txt
    # pair1_GSE38901_hsf1_mcf10a_ctrl.txt
    ("SRX155730", "SRX155727"), # MCF10A_HS_HSF1_ChIPSeq_1 vs. MCF10A_HSF1_ChIPSeq_1
    ("SRX155731", "SRX155728")  # MCF10A_HS_HSF1_ChIPSeq_2 vs. MCF10A_HSF1_ChIPSeq_2
]

paired_metada_df_gse38901 = create_paired_metadata(
    combined_df=GSE38901_combined,
    defined_sample_pairs=defined_pairs_gse38901_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse38901 is not None:
    paired_metada_df_gse38901.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE38901_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_cols(100)
    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse38901)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (7, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ ant ┆ tum ┆ 42˚ ┆ gen ┆ sra ┆ bio ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ tax ┆ sam ┆ run ┆ exp ┆ cen ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_t ┆ ibo ┆ ori ┆ _c_ ┆ ome ┆ --- ┆ sam ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ _li ┆ ple ┆ _al ┆ eri ┆ ter ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ype ┆ dy  ┆ gen ┆ 1h_ ┆ _bu ┆ str ┆ ple ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ nea ┆ _al ┆ ias ┆ men ┆ _na ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ic_ ┆ hea ┆ ild ┆     ┆ --- ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ge  ┆ ias ┆ --- ┆ t_a ┆ me  ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ or_ ┆ t-s ┆ --- ┆     ┆ str ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ lia ┆ --- ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ non ┆ hoc ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ s   ┆ str ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ tum ┆ k_  ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆ ori ┆ --- ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆ gen ┆ str ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hme ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ HME ┆ GSM ┆ Pub ┆ Jun ┆ May ┆ SRA ┆ 1   ┆ HME ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Mar ┆ Whi ┆ 9   ┆ Cam ┆ MA  ┆ 214 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Imm ┆ HSF ┆ Non ┆ YES ┆ HG1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 395 ┆ ILL ┆ Gen ┆ HME ┆ 8fb ┆ SRP ┆ 182 ┆ HSF ┆ GEN ┆ HME ┆ Ill ┆ Ill ┆ Imm ┆ 639 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ 1;1 ┆ GSM ┆ GSM ┆ GSM ┆ GEO ┆ GSM ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 155 ┆ 155 ┆ _hs ┆ P   ┆ o   ┆ GLE ┆     ┆ 515 ┆ _HS ┆ 951 ┆ lic ┆ 24  ┆ 15  ┆     ┆     ┆ cel ┆ o   ┆ 6   ┆ omi ┆ 905 ┆ c,, ┆ teh ┆ Cam ┆ bri ┆     ┆ 2   ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 951 ┆ E   ┆ 389 ┆     ┆ 155 ┆ ort ┆ 1   ┆ -tu ┆ vs  ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N01 ┆ o   ┆ 054 ┆ P   ┆ 9-1 ┆ 492 ┆ UMI ┆ eri ┆ _HS ┆ 572 ┆ 013 ┆ 712 ┆ 1   ┆ ERA ┆ _HS ┆ umi ┆ umi ┆ ort ┆ 492 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 315 ┆ 951 ┆ 951 ┆ 951 ┆     ┆ 951 ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA1 ┆ 515 ┆ 346 ┆ 2-0 ┆ 389 │
│ 719 ┆ 715 ┆ _hs ┆     ┆ sap ┆     ┆     ┆ 394 ┆ _HS ┆ 853 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ls  ┆ sap ┆     ┆ c   ┆ 2   ┆ Men ┆ ead ┆ bri ┆ dge ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 853 ┆     ┆ 01, ┆     ┆ 719 ┆ ali ┆ (H- ┆ mor ┆ No  ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 057 ┆ sap ┆ 929 ┆     ┆ 0-1 ┆ 634 ┆ NA  ┆ c   ┆ _HS ┆ 36c ┆ 883 ┆ 01  ┆ dri ┆ TED ┆ _HS ┆ na  ┆ na  ┆ ali ┆ 035 ┆ eq  ┆ C   ┆     ┆     ┆ 67; ┆ 853 ┆ 853 ┆ 853 ┆     ┆ 853 ┆ x:t ┆ 1-1 ┆ sap ┆     ┆ 693 ┆ 394 ┆ 788 ┆ 8-3 ┆ 01  │
│     ┆     ┆ f1_ ┆     ┆ ien ┆     ┆     ┆ vs  ┆ F1_ ┆ vs  ┆ Aug ┆ 2   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ dil ┆ Ins ┆ dge ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆ vs  ┆     ┆ GSE ┆     ┆ vs  ┆ zed ┆ 311 ┆ ige ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ Gen ┆ 454 ┆ ien ┆     ┆     ┆ 8   ┆ vs  ┆     ┆     ┆ F1_ ┆ ebf ┆     ┆ vs  ┆ ves ┆ _FI ┆ F1_ ┆ Gen ┆ Gen ┆ zed ┆ vs  ┆     ┆     ┆     ┆     ┆ 275 ┆ vs  ┆ _r1 ┆ _1  ┆     ┆ :   ┆ err ┆ 1   ┆ ien ┆     ┆ 33  ┆ vs  ┆ vs  ┆ 1   ┆     │
│     ┆     ┆ chi ┆     ┆ s   ┆     ┆     ┆ SRR ┆ ChI ┆ GSM ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ lo  ┆ tit ┆ Cen ┆     ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆ GSM ┆     ┆ 389 ┆     ┆ SRX ┆ mam ┆ ,   ┆ nic ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ ome ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ 308 ┆     ┆     ┆ ChI ┆ afb ┆     ┆ 142 ┆ a   ┆ LE  ┆ ChI ┆ ome ┆ ome ┆ mam ┆ 498 ┆     ┆     ┆     ┆     ┆ 9;3 ┆ GSM ┆ vs  ┆ vs  ┆     ┆ HME ┆ est ┆     ┆ s   ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ pse ┆     ┆     ┆     ┆     ┆ 515 ┆ PSe ┆ 951 ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ute ┆ ter ┆     ┆     ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆ 951 ┆     ┆ 12  ┆     ┆ 155 ┆ mar ┆ San ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ Ana ┆ SAM ┆     ┆     ┆     ┆ 202 ┆ 979 ┆     ┆     ┆ PSe ┆ 706 ┆     ┆ 340 ┆ tra ┆     ┆ PSe ┆ Ana ┆ Ana ┆ mar ┆ 193 ┆     ┆     ┆     ┆     ┆ 315 ┆ 951 ┆ GSM ┆ GSM ┆     ┆ _HS ┆ ria ┆     ┆     ┆     ┆     ┆ 515 ┆ 346 ┆     ┆     │
│     ┆     ┆ q_1 ┆     ┆     ┆     ┆     ┆ 390 ┆ q_1 ┆ 849 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆ 715 ┆ y   ┆ ta  ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ lyz ┆ N01 ┆     ┆     ┆     ┆ 1-0 ┆ 986 ┆     ┆     ┆ q_1 ┆ 054 ┆     ┆ 92  ┆ nsc ┆     ┆ q_1 ┆ lyz ┆ lyz ┆ y   ┆ 220 ┆     ┆     ┆     ┆     ┆ 4;3 ┆ 849 ┆ 951 ┆ 951 ┆     ┆ _HS ┆ l;e ┆     ┆     ┆     ┆     ┆ 390 ┆ 784 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bio ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ epi ┆ Cru ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ er  ┆ 057 ┆     ┆     ┆     ┆ 1-1 ┆     ┆     ┆     ┆ vs  ┆ 318 ┆     ┆     ┆ rip ┆     ┆ vs  ┆ er  ┆ er  ┆ epi ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆ 849 ┆ 849 ┆     ┆ F1_ ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hme ┆     ┆     ┆     ┆     ┆     ┆ HME ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆ z,  ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆ seq ┆ 450 ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ HME ┆ b1b ┆     ┆     ┆ tio ┆     ┆ HME ┆     ┆ seq ┆ the ┆     ┆     ┆     ┆     ┆     ┆ 8;6 ┆     ┆ _r1 ┆ _1  ┆     ┆ ChI ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _hs ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ica ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lia ┆ sc- ┆     ┆     ┆     ┆ v/s ┆ v/b ┆ ell ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆ 51c ┆     ┆     ┆ nal ┆     ┆ _HS ┆     ┆ uen ┆ lia ┆     ┆     ┆     ┆     ┆     ┆ 072 ┆     ┆     ┆     ┆     ┆ PSe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ f1_ ┆     ┆     ┆     ┆     ┆     ┆ F1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ 914 ┆     ┆     ┆     ┆ ra? ┆ ios ┆ .20 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ F1_ ┆ c9  ┆     ┆     ┆ pro ┆     ┆ F1_ ┆     ┆ cin ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆     ┆     ┆ q_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ chi ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Res ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ 4,  ┆     ┆     ┆     ┆ ter ┆ amp ┆ 12. ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆ vs  ┆     ┆     ┆ gra ┆     ┆ ChI ┆     ┆ g:  ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pse ┆     ┆     ┆     ┆     ┆     ┆ PSe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ear ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆ Lot ┆     ┆     ┆     ┆ m=S ┆ le/ ┆ 06. ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PSe ┆ 453 ┆     ┆     ┆ m   ┆     ┆ PSe ┆     ┆ GSM ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ #   ┆     ┆     ┆     ┆ RX1 ┆ SAM ┆ 031 ┆     ┆     ┆ 951 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ c77 ┆     ┆     ┆ dis ┆     ┆ q   ┆     ┆ 951 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 511 ┆     ┆     ┆     ┆     ┆ 951 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ J05 ┆     ┆     ┆     ┆ 557 ┆ N01 ┆     ┆     ┆     ┆ 853 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b1f ┆     ┆     ┆ tin ┆     ┆     ┆     ┆ 853 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;77 ┆     ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10) ┆     ┆     ┆     ┆ 19  ┆ 057 ┆     ┆     ┆     ┆ :   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50f ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆ :   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11; ┆     ┆     ┆     ┆     ┆ :   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 454 ┆     ┆     ┆     ┆ HME ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dd2 ┆     ┆     ┆ fro ┆     ┆     ┆     ┆ HME ┆     ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆     ┆     ┆ HME ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ vs  ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a8a ┆     ┆     ┆ m   ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆ 93; ┆     ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ htt ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07f ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆     ┆     ┆     ┆     ┆ F1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ps: ┆     ┆     ┆     ┆ F1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bcd ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ F1_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2;7 ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ //w ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e1b ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆ 776 ┆     ┆     ┆     ┆     ┆ PSe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ww. ┆     ┆     ┆     ┆ PSe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 076 ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆ PSe ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;11 ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ ncb ┆     ┆     ┆     ┆ q_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d6  ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ q_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 757 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ i.n ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sup ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0;1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ lm. ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ por ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. GSE43579 (ChIP-seq; HSF1)

- [Transcriptional response to stress in the dynamic chromatin environment of cycling and mitotic cells](https://doi.org/10.1073/pnas.1305275110)
- IgG control も含まれているが、熱ストレス条件下 vs コントロール条件下のデータが揃っているため、偽陽性のピーク (diff analysis で検出されたピーク？)を 取り除ける可能性があるため、収集しておく

In [10]:
GSE43579_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE43579/GSE43579_PEP/GSE43579_PEP_raw.csv",
    separator=','
).filter(
    ~pl.col("sample_name").str.contains("input_sample_")
).with_columns(
    pl.lit("https://doi.org/10.1073/pnas.1305275110").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"), # from treatment column
    pl.lit("30 min.").alias("stress treatment time") # from treatment column
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE43579 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE43579.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE43579_filtered = GSE43579[[s.name for s in GSE43579 if not (s.null_count() == GSE43579.height)]]

GSE43579_combined = GSE43579_PEP.join(
    GSE43579_filtered,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE43579_combined = GSE43579_combined[[s.name for s in GSE43579_combined if not (s.null_count() == GSE43579_combined.height)]]

# pl.Config.set_tbl_rows(14)
# display(GSE43579_combined)

In [11]:
defined_pairs_gse43579_chipseq = [

    # pair2_GSE43579_hsf1_k562_hs_42C_30min.txt
    # pair2_GSE43579_hsf1_k562_ctrl.txt
    ("SRX218220", "SRX218217"), # HSF1_heat-treated cycling K562 vs. HSF1_non-treated cycling K562
    ("SRX218221", "SRX218218"), # HSF2_heat-treated cycling K562 vs. HSF2_non-treated cycling K562

    ("SRX218222", "SRX218219"), # IgG_heat-treated cycling K562 vs. IgG_non-treated cycling K562

    # pair3_GSE43579_hsf1_k562_mitotic_hs_42C_30min.txt
    # pair3_GSE43579_hsf1_k562_mitotic_ctrl.txt
    ("SRX218227", "SRX218224"), # HSF1_heat-treated mitotic K562 vs. HSF1_non-treated mitotic K562
    ("SRX218228", "SRX218225"), # HSF2_heat-treated mitotic K562 vs. HSF2_non-treated mitotic K562
    
    ("SRX218229", "SRX218226"), # IgG_heat-treated mitotic K562 vs. IgG_non-treated mitotic K562
]

paired_metada_df_gse43579 = create_paired_metadata(
    combined_df=GSE43579_combined,
    defined_sample_pairs=defined_pairs_gse43579_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse43579 is not None:
    paired_metada_df_gse43579.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE43579_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_cols(100)
    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse43579)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ cel ┆ tre ┆ chi ┆ gen ┆ sra ┆ bio ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ tax ┆ sam ┆ run ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ l_c ┆ atm ┆ p_a ┆ ome ┆ --- ┆ sam ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ _li ┆ ple ┆ _al ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ycl ┆ ent ┆ nti ┆ _bu ┆ str ┆ ple ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ nea ┆ _al ┆ ias ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ e_p ┆ --- ┆ bod ┆ ild ┆     ┆ --- ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ge  ┆ ias ┆ --- ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ has ┆ str ┆ y   ┆ --- ┆     ┆ str ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ e   ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hsf ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ HSF ┆ GSM ┆ Pub ┆ Jan ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ fre ┆ 30  ┆ HSF ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 202 ┆ 107 ┆ ILL ┆ Gen ┆ HSF ┆ 092 ┆ SRP ┆ 316 ┆ Gen ┆ GEN ┆ HSF ┆ Ill ┆ Ill ┆ 113 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ 1;1 ┆ GSM ┆ GSM ┆ GSM ┆ GEO ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 218 ┆ 218 ┆ 1_h ┆ P   ┆ o   ┆ GLE ┆     ┆ 650 ┆ 1_h ┆ 106 ┆ lic ┆ 17  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ 109 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 106 ┆ :// ┆ :// ┆ 435 ┆     ┆ 218 ┆ 2   ┆ ely ┆ min ┆ 1   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N01 ┆ o   ┆ 065 ┆ P   ┆ 1-0 ┆ 836 ┆ UMI ┆ eri ┆ 1_h ┆ 569 ┆ 018 ┆ 244 ┆ ome ┆ ERA ┆ 1_h ┆ umi ┆ umi ┆ 848 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 315 ┆ 106 ┆ 106 ┆ 106 ┆     ┆ 2   ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA1 ┆ 650 ┆ 386 ┆ 3-0 ┆ 435 │
│ 220 ┆ 217 ┆ eat ┆     ┆ sap ┆     ┆     ┆ 334 ┆ eat ┆ 571 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ c   ┆ 99  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 571 ┆ ftp ┆ ftp ┆ 79  ┆     ┆ 220 ┆ cel ┆ cyc ┆ at  ┆ (SP ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 889 ┆ sap ┆ 119 ┆     ┆ 1-1 ┆ 130 ┆ NA  ┆ c   ┆ eat ┆ 5bb ┆ 017 ┆ 82  ┆ -wi ┆ TED ┆ eat ┆ na  ┆ na  ┆ 135 ┆ eq  ┆ C   ┆     ┆     ┆ 67; ┆ 571 ┆ 571 ┆ 571 ┆     ┆ cel ┆ x:t ┆ 1-1 ┆ sap ┆     ┆ 867 ┆ 334 ┆ 296 ┆ 8-2 ┆ 79  │
│     ┆     ┆ -tr ┆     ┆ ien ┆     ┆     ┆ vs  ┆ -tr ┆ 4   ┆ Aug ┆ 3   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆ DNA ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆ 4   ┆ .nc ┆ .nc ┆     ┆     ┆ vs  ┆ ls  ┆ lin ┆ 42C ┆ A-9 ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ Gen ┆ 090 ┆ ien ┆     ┆     ┆ 0   ┆ 7   ┆     ┆     ┆ -tr ┆ a61 ┆     ┆ vs  ┆ de  ┆ _FI ┆ -tr ┆ Gen ┆ Gen ┆ 2   ┆     ┆     ┆     ┆     ┆ 275 ┆ 4   ┆ 4_r ┆ 4_1 ┆     ┆ ls  ┆ err ┆ 1   ┆ ien ┆     ┆ 55  ┆ vs  ┆ vs  ┆ 0   ┆     │
│     ┆     ┆ eat ┆     ┆ s   ┆     ┆     ┆ SRR ┆ eat ┆ vs  ┆ 04  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ SRX ┆     ┆ g   ┆ vs  ┆ 01, ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ ome ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ eat ┆ 22f ┆     ┆ 243 ┆ map ┆ LE  ┆ eat ┆ ome ┆ ome ┆ vs  ┆     ┆     ┆     ┆     ┆ 9;3 ┆ vs  ┆ 1   ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ ed_ ┆     ┆     ┆     ┆     ┆ 650 ┆ ed  ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ 218 ┆     ┆     ┆ no  ┆ Enz ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ Ana ┆ SAM ┆     ┆     ┆     ┆ 201 ┆ 783 ┆     ┆     ┆ ed  ┆ 3e7 ┆     ┆ 054 ┆ s   ┆     ┆ ed  ┆ Ana ┆ Ana ┆ 874 ┆     ┆     ┆     ┆     ┆ 315 ┆ GSM ┆ vs  ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ 650 ┆ 386 ┆     ┆     │
│     ┆     ┆ cyc ┆     ┆     ┆     ┆     ┆ 331 ┆ cyc ┆ 106 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆ 106 ┆ .ni ┆ .ni ┆     ┆     ┆ 217 ┆     ┆     ┆ tre ┆ o,  ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ lyz ┆ N01 ┆     ┆     ┆     ┆ 9-1 ┆ 043 ┆     ┆     ┆ cyc ┆ 949 ┆     ┆ 99  ┆ of  ┆     ┆ cyc ┆ lyz ┆ lyz ┆ 997 ┆     ┆     ┆     ┆     ┆ 4;3 ┆ 106 ┆ GSM ┆ 106 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 331 ┆ 293 ┆     ┆     │
│     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆ lin ┆ 571 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆ 571 ┆ h.g ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆ atm ┆ Lot ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆ er  ┆ 889 ┆     ┆     ┆     ┆ 0-2 ┆ 494 ┆     ┆     ┆ lin ┆ ef1 ┆     ┆     ┆ HSF ┆     ┆ lin ┆ er  ┆ er  ┆ 964 ┆     ┆     ┆     ┆     ┆ 320 ┆ 571 ┆ 106 ┆ 571 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ g_k ┆     ┆     ┆     ┆     ┆     ┆ g   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆ IIx ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ ent ┆ #09 ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆ IIx ┆ 087 ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ g   ┆ f3d ┆     ┆     ┆ 1   ┆     ┆ g   ┆ IIx ┆ IIx ┆     ┆     ┆     ┆     ┆     ┆ 8;6 ┆ 1   ┆ 571 ┆ 1_1 ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ 011 ┆     ┆ v/s ┆ v/b ┆ s.1 ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆ b54 ┆     ┆     ┆ and ┆     ┆ K56 ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ 072 ┆     ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ 025 ┆     ┆ ra? ┆ ios ┆ 305 ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ bf  ┆     ┆     ┆ HSF ┆     ┆ 2   ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hsf ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆ ter ┆ amp ┆ 275 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ 2   ┆     ┆ vs  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_n ┆     ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m=S ┆ le/ ┆ 110 ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HSF ┆ 18f ┆     ┆     ┆ bin ┆     ┆ HSF ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ on- ┆     ┆     ┆     ┆     ┆     ┆ 1_n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RX2 ┆ SAM ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_n ┆ 1b0 ┆     ┆     ┆ din ┆     ┆ 1_n ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 511 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆ on- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 106 ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 182 ┆ N01 ┆     ┆     ┆     ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on- ┆ f04 ┆     ┆     ┆ g   ┆     ┆ on- ┆     ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆ ;77 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20  ┆ 889 ┆     ┆     ┆     ┆ 571 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆ 3d2 ┆     ┆     ┆ sit ┆     ┆ tre ┆     ┆ 571 ┆     ┆     ┆     ┆     ┆     ┆ 11; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ d_c ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 090 ┆     ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ c0f ┆     ┆     ┆ es  ┆     ┆ ate ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ycl ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM1 ┆ SM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ vs  ┆     ┆     ┆     ┆ HSF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ 097 ┆     ┆     ┆ in  ┆     ┆ d   ┆     ┆ HSF ┆     ┆     ┆     ┆     ┆     ┆ 93; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆ cyc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 065 ┆ 065 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ htt ┆     ┆     ┆     ┆ 1_h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cyc ┆ 91d ┆     ┆     ┆ cyc ┆     ┆ cyc ┆     ┆ 1_h ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _k5 ┆     ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 714 ┆ 714 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ps: ┆     ┆     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lin ┆ 37c ┆     ┆     ┆ lin ┆     ┆ lin ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆ 2;7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 62  ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ //w ┆     ┆     ┆     ┆ -tr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆ 858 ┆     ┆     ┆ g   ┆     ┆ g   ┆     ┆ -tr ┆     ┆     ┆     ┆     ┆     ┆ 776 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ww. ┆     ┆     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆ 358 ┆     ┆     ┆ and ┆     ┆ K56 ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆ ;11 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ ncb ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 5d  ┆     ┆     ┆ mit ┆     ┆ 2   ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆ 757 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 5. GSE62309 (ChIP-seq; p-KDM3A)

- [Specific Phosphorylation of Histone Demethylase KDM3A Determines Target Gene Expression in Response to Heat Shock](https://doi.org/10.1371/journal.pbio.1002026)
- Histone Demethylase KDM3A を標的にした ChIP-seq のデータ
- 抗体で使用されている、`KDM3A`と、`p-KDM3A`の違いは、リン酸化されているものを標的にしているかどうか
- `KDM3A` を標的としている ChIP-seq のデータは、ペアとなるデータがなかったため、除外しておく

In [12]:
GSE62309_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE62309/GSE62309_PEP/GSE62309_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_name") != "input_pool") & # SRX732512
    (pl.col("sample_name") != "kdm3a_hs_-_") # SRX732509
).with_columns(
    pl.lit("https://doi.org/10.1371/journal.pbio.1002026").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("30 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE62309 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE62309.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE62309_combined = GSE62309_PEP.join(
    GSE62309,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE62309_combined = GSE62309_combined[[s.name for s in GSE62309_combined if not (s.null_count() == GSE62309_combined.height)]]

# pl.Config.set_tbl_rows(14)
# display(GSE62309_combined)

In [13]:
defined_pairs_gse62309_chipseq = [
    ("SRX732511", "SRX732510")  # p-KDM3A_HS(+) vs. p-KDM3A_HS(-)
]

paired_metada_df_gse62309 = create_paired_metadata(
    combined_df=GSE62309_combined,
    defined_sample_pairs=defined_pairs_gse62309_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse62309 is not None:
    paired_metada_df_gse62309.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE62309_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metada_df_gse62309)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ cel ┆ tre ┆ chi ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ l_t ┆ atm ┆ p_a ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ype ┆ ent ┆ nti ┆ dy_ ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ bod ┆ man ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ y   ┆ ufa ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ --- ┆ ctu ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆ str ┆ rer ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ p-k ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ p-K ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ Jur ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ye, ┆ yez ┆ 861 ┆ 5   ┆ Bei ┆ Not ┆ 100 ┆ Chi ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Jur ┆ Acu ┆ 42℃ ┆ p-K ┆ cus ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 202 ┆ 893 ┆ ILL ┆ Gen ┆ p-K ┆ 462 ┆ SRP ┆ 283 ┆ Spe ┆ GEN ┆ p-K ┆ Ill ┆ Ill ┆ Acu ┆ 971 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ 1;1 ┆ GSM ┆ GSM ┆ Lys ┆ GSM ┆ GEO ┆ Jur ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 732 ┆ 732 ┆ dm3 ┆ P   ┆ o   ┆ GLE ┆     ┆ 161 ┆ DM3 ┆ 152 ┆ lic ┆ 14  ┆ 15  ┆     ┆     ┆ kat ┆ o   ┆ 6   ┆ omi ┆ 109 ┆ ,Zh ┆ han ┆ 069 ┆ Don ┆ jin ┆ app ┆ 005 ┆ na  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 152 ┆ :// ┆ :// ┆ 623 ┆     ┆ 732 ┆ kat ┆ te  ┆ 1h  ┆ DM3 ┆ tom ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N03 ┆ o   ┆ 190 ┆ P   ┆ 0-0 ┆ 711 ┆ UMI ┆ eri ┆ DM3 ┆ 150 ┆ 048 ┆ 992 ┆ cif ┆ ERA ┆ DM3 ┆ umi ┆ umi ┆ te  ┆ 379 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 315 ┆ 152 ┆ 152 ┆ ate ┆ 152 ┆     ┆ kat ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 161 ┆ 721 ┆ 5-0 ┆ 623 │
│ 511 ┆ 510 ┆ a_h ┆     ┆ sap ┆     ┆     ┆ 195 ┆ A_H ┆ 510 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ c   ┆ 99  ┆ ang ┆ g@p ┆ 155 ┆ gda ┆ g   ┆ lic ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 510 ┆ ftp ┆ ftp ┆ 09  ┆     ┆ 511 ┆     ┆ T   ┆ vs  ┆ A   ┆ ize ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 107 ┆ sap ┆ 777 ┆     ┆ 5-1 ┆ 604 ┆ NA  ┆ c   ┆ A_H ┆ e21 ┆ 900 ┆ 20  ┆ ic  ┆ TED ┆ A_H ┆ na  ┆ na  ┆ T   ┆ 809 ┆ eq  ┆ C   ┆     ┆     ┆ 67; ┆ 510 ┆ 510 ┆ s   ┆ 510 ┆     ┆     ┆ x:t ┆ 3-2 ┆ sap ┆     ┆ 638 ┆ 195 ┆ 331 ┆ 3-2 ┆ 09  │
│     ┆     ┆ s_+ ┆     ┆ ien ┆     ┆     ┆ 2   ┆ S(+ ┆ 5   ┆ Oct ┆ 4   ┆ 9   ┆     ┆     ┆ l   ┆ ien ┆     ┆ DNA ┆     ┆     ┆ umc ┆ 939 ┆ n   ┆     ┆ abl ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆ 5   ┆ .nc ┆ .nc ┆     ┆     ┆ vs  ┆     ┆ Cel ┆ 37℃ ┆     ┆ d   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ Gen ┆ 086 ┆ ien ┆     ┆     ┆ 4   ┆ vs  ┆     ┆     ┆ S(+ ┆ fd0 ┆     ┆ vs  ┆ pho ┆ _FI ┆ S(+ ┆ Gen ┆ Gen ┆ Cel ┆ vs  ┆     ┆     ┆     ┆     ┆ 275 ┆ 5   ┆ 5_r ┆ wer ┆ 5   ┆     ┆     ┆ err ┆ 1   ┆ ien ┆     ┆ 10  ┆ 2   ┆ vs  ┆ 3   ┆     │
│     ┆     ┆ _   ┆     ┆ s   ┆     ┆     ┆ vs  ┆ )   ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆ lin ┆ s   ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆ San ┆     ┆ e   ┆     ┆     ┆ ome ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ SRX ┆     ┆ l   ┆ 1h  ┆     ┆ fro ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ ome ┆ vs  ┆ s   ┆     ┆     ┆     ┆ 782 ┆     ┆     ┆ )   ┆ 08c ┆     ┆ 249 ┆ sph ┆ LE  ┆ )   ┆ ome ┆ ome ┆ l   ┆ 852 ┆     ┆     ┆     ┆     ┆ 9;3 ┆ vs  ┆ 1   ┆ e   ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ SRR ┆ vs  ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ u.c ┆     ┆ tia ┆     ┆     ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ 732 ┆     ┆ Leu ┆     ┆     ┆ m   ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ Ana ┆ SAM ┆     ┆     ┆     ┆     ┆ 761 ┆     ┆     ┆ vs  ┆ 2ca ┆     ┆ 704 ┆ ory ┆     ┆ vs  ┆ Ana ┆ Ana ┆ Leu ┆ 988 ┆     ┆     ┆     ┆     ┆ 315 ┆ GSM ┆ vs  ┆ cla ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ 721 ┆     ┆     │
│     ┆     ┆ p-k ┆     ┆     ┆     ┆     ┆ 161 ┆ p-K ┆ 152 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆ o   ┆     ┆     ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆ 152 ┆ .ni ┆ .ni ┆     ┆     ┆ 510 ┆     ┆ kem ┆     ┆     ┆ Bei ┆     ┆ lm. ┆ lm. ┆ .13 ┆     ┆     ┆ lyz ┆ N03 ┆     ┆     ┆     ┆     ┆ 489 ┆     ┆     ┆ p-K ┆ a2b ┆     ┆ 99  ┆ lat ┆     ┆ p-K ┆ lyz ┆ lyz ┆ kem ┆ 748 ┆     ┆     ┆     ┆     ┆ 4;3 ┆ 152 ┆ GSM ┆ rif ┆ 152 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 161 ┆ 330 ┆     ┆     │
│     ┆     ┆ dm3 ┆     ┆     ┆     ┆     ┆ 195 ┆ DM3 ┆ 510 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆ 510 ┆ h.g ┆ h.g ┆     ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆ jin ┆     ┆ nih ┆ nih ┆ 71/ ┆     ┆     ┆ er  ┆ 107 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DM3 ┆ 91d ┆     ┆     ┆ ion ┆     ┆ DM3 ┆ er  ┆ er  ┆ ia  ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆ 510 ┆ 152 ┆ ied ┆ 510 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 195 ┆     ┆     ┆     │
│     ┆     ┆ a_h ┆     ┆     ┆     ┆     ┆ 1   ┆ A_H ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IIx ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆ ov/ ┆     ┆     ┆     ┆     ┆ T   ┆     ┆     ┆ g   ┆     ┆ .go ┆ .go ┆ jou ┆     ┆     ┆ IIx ┆ 085 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A_H ┆ fcf ┆     ┆     ┆ of  ┆     ┆ A_H ┆ IIx ┆ IIx ┆ T   ┆     ┆     ┆     ┆     ┆     ┆ 8;6 ┆ 4   ┆ 510 ┆ fro ┆ 4   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│     ┆     ┆ s_- ┆     ┆     ┆     ┆     ┆     ┆ S(- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆ lym ┆     ┆     ┆ B&M ┆     ┆ v/b ┆ v/s ┆ rna ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S(- ┆ 7cf ┆     ┆     ┆ his ┆     ┆ S(- ┆     ┆ seq ┆ lym ┆     ┆     ┆     ┆     ┆     ┆ 072 ┆     ┆ 4_r ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _   ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆ pho ┆     ┆     ┆ Bio ┆     ┆ ios ┆ ra? ┆ l.p ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆ d2  ┆     ┆     ┆ ton ┆     ┆ )   ┆     ┆ uen ┆ pho ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆ 1   ┆ son ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆ cyt ┆     ┆     ┆ tec ┆     ┆ amp ┆ ter ┆ bio ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ cin ┆ cyt ┆     ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆ ica ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ h   ┆     ┆ le/ ┆ m=S ┆ .10 ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 74a ┆     ┆     ┆ dem ┆     ┆     ┆     ┆ g:  ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Be ┆     ┆ SAM ┆ RX7 ┆ 020 ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20c ┆     ┆     ┆ eth ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ 511 ┆     ┆     ┆ nuc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 152 ┆ 152 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iji ┆     ┆ N03 ┆ 325 ┆ 26  ┆     ┆     ┆ 152 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10b ┆     ┆     ┆ yla ┆     ┆     ┆     ┆ 152 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;77 ┆     ┆     ┆ lei ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng, ┆     ┆ 107 ┆ 11  ┆     ┆     ┆     ┆ 510 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b4a ┆     ┆     ┆ se  ┆     ┆     ┆     ┆ 510 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11; ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Chi ┆     ┆ 086 ┆ vs  ┆     ┆     ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7a1 ┆     ┆     ┆ KDM ┆     ┆     ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆ his ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM1 ┆ SM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na) ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ p-K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e0f ┆     ┆     ┆ 3A  ┆     ┆     ┆     ┆ p-K ┆     ┆     ┆     ┆     ┆     ┆     ┆ 93; ┆     ┆     ┆ ton ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ DM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9c4 ┆     ┆     ┆ det ┆     ┆     ┆     ┆ DM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆     ┆     ┆ e-D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 105 ┆ 105 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ A_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 352 ┆     ┆     ┆ erm ┆     ┆     ┆     ┆ A_H ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2;7 ┆     ┆     ┆ NA  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ S(+ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 72b ┆     ┆     ┆ ine ┆     ┆     ┆     ┆ S(+ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 776 ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 033 ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;11 ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 57  ┆     ┆     ┆ tar ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆ 757 ┆     ┆     ┆ xes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 6. GSE57398 (ChIP-seq; HSF1)

- [FBXW7 modulates cellular stress response and metastatic potential through HSF1 post-translational modification.](https://doi.org/10.1038/ncb3121)
- Input control data が、熱ストレス条件下 vs. コントロール条件下のデータがあるので、念のため収集しておく
- control の replicate が2つ以上ないため、ChIP-Atlas Diff Analysis は実行しない

In [14]:
GSE57398_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE57398/GSE57398_PEP/GSE57398_PEP_raw.csv",
    separator=','
).filter(
    pl.col("sample_library_strategy") == "ChIP-Seq"
).with_columns(
    pl.lit("https://doi.org/10.1038/ncb3121").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE57398 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE57398.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE57398_combined = GSE57398_PEP.join(
    GSE57398,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE57398_combined = GSE57398_combined[[s.name for s in GSE57398_combined if not (s.null_count() == GSE57398_combined.height)]]

# pl.Config.set_tbl_rows(14)
# display(GSE57398_combined)

In [15]:
defined_pairs_gse57398_chipseq = [

    # FBXW7 KO
    ("SRX535173", "SRX535176"), # ChIP-Seq analysis of HSF1 in HCT116 FBXW7 KO cells upon heat shock treatment replicate1 vs. ChIP-Seq analysis of HSF1 in HCT116 FBXW7 KO untreated cells replicate1
    ("SRX535174", "SRX535176"), # ChIP-Seq analysis of HSF1 in HCT116 FBXW7 KO cells upon heat shock treatment replicate2 vs. ChIP-Seq analysis of HSF1 in HCT116 FBXW7 KO untreated cells replicate1
    ("SRX535175", "SRX535177"), # Sequencing analysis of input in HCT116 FBXW7 KO cells upon heat shock treatment vs. Sequencing analysis of input in HCT116 FBXW7 KO untreated cells

    # FBXW7 WT
    ("SRX535178", "SRX535181"), # ChIP-Seq analysis of HSF1 in HCT116 WT cells upon heat shock treatment replicate1 vs. ChIP-Seq analysis of HSF1 in HCT116 WT untreated cells replicate1
    ("SRX535179", "SRX535181"), # ChIP-Seq analysis of HSF1 in HCT116 WT cells upon heat shock treatment replicate2 vs. ChIP-Seq analysis of HSF1 in HCT116 WT untreated cells replicate1
    ("SRX535180", "SRX535182")  # Sequencing analysis of input in HCT116 WT cells upon heat shock treatment vs. Sequencing analysis of input in HCT116 WT untreated cells
]

paired_metada_df_gse57398 = create_paired_metadata(
    combined_df=GSE57398_combined,
    defined_sample_pairs=defined_pairs_gse57398_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse57398 is not None:
    paired_metada_df_gse57398.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE57398_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse57398)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ cel ┆ chi ┆ gen ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_t ┆ l_l ┆ p_a ┆ ome ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ype ┆ ine ┆ nti ┆ _bu ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ bod ┆ ild ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ _id ┆ nam ┆ ema ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ --- ┆ str ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ --- ┆ e   ┆ il  ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ l_c ┆ --- ┆ str ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ chi ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ ChI ┆ GSM ┆ Pub ┆ May ┆ May ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ att ┆ gen ┆ GPL ┆ Nik ┆ nko ┆ NYU ┆ 550 ┆ New ┆ 100 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ hum ┆ HCT ┆ HSF ┆ hg1 ┆ bed ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 107 ┆ ILL ┆ Gen ┆ ChI ┆ e20 ┆ SRP ┆ 291 ┆ Gen ┆ GEN ┆ ChI ┆ Ill ┆ Ill ┆ hum ┆ 148 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ 1;1 ┆ GSM ┆ GSM ┆ Fiv ┆ GSM ┆ GEO ┆ HCT ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 535 ┆ 535 ┆ p-s ┆ P   ┆ o   ┆ GLE ┆     ┆ 127 ┆ P-S ┆ 138 ┆ lic ┆ 07  ┆ 15  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ ach ┆ omi ┆ 111 ┆ os, ┆ urt ┆ Sch ┆ Fir ┆ Yor ┆ 16  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 138 ┆ :// ┆ 573 ┆     ┆ 535 ┆ an  ┆ 116 ┆ 1:  ┆ 9   ┆ for ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N02 ┆ o   ┆ 162 ┆ P   ┆ 9-1 ┆ 578 ┆ UMI ┆ eri ┆ P-S ┆ 633 ┆ 041 ┆ 867 ┆ ome ┆ ERA ┆ P-S ┆ umi ┆ umi ┆ an  ┆ 852 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 315 ┆ 138 ┆ 138 ┆ e   ┆ 138 ┆     ┆ 116 ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 127 ┆ 603 ┆ 5-0 ┆ 573 │
│ 173 ┆ 176 ┆ eq_ ┆     ┆ sap ┆     ┆     ┆ 463 ┆ eq  ┆ 204 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ FBX ┆ sap ┆     ┆ ed  ┆ c   ┆ 54  ┆ ,Ko ┆ is@ ┆ ool ┆ st  ┆ k   ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 204 ┆ ftp ┆ 98, ┆     ┆ 173 ┆ col ┆     ┆ Cel ┆     ┆ mat ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 767 ┆ sap ┆ 008 ┆     ┆ 0-1 ┆ 784 ┆ NA  ┆ c   ┆ eq  ┆ ffd ┆ 754 ┆ 71  ┆ -wi ┆ TED ┆ eq  ┆ na  ┆ na  ┆ col ┆ 532 ┆ eq  ┆ C   ┆     ┆     ┆ 67; ┆ 204 ┆ 204 ┆ mil ┆ 204 ┆     ┆     ┆ x:t ┆ 3-2 ┆ sap ┆     ┆ 463 ┆ 463 ┆ 792 ┆ 3-2 ┆ 98  │
│     ┆     ┆ ana ┆     ┆ ien ┆     ┆     ┆ 9   ┆ ana ┆ 9   ┆ Feb ┆ 4   ┆ 9   ┆     ┆     ┆ W7  ┆ ien ┆     ┆ cel ┆ DNA ┆     ┆ urt ┆ gma ┆ of  ┆ Ave ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 9   ┆ .nc ┆ GSE ┆     ┆ vs  ┆ on  ┆     ┆ l   ┆     ┆ con ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 270 ┆ ien ┆     ┆     ┆ 1   ┆ 9   ┆     ┆     ┆ ana ┆ eb9 ┆     ┆ vs  ┆ de  ┆ _FI ┆ ana ┆ HiS ┆ HiS ┆ on  ┆ 1   ┆     ┆     ┆     ┆     ┆ 275 ┆ 9   ┆ 9_r ┆ lio ┆ 9   ┆     ┆     ┆ err ┆ 1   ┆ ien ┆     ┆ 92  ┆ 9   ┆ vs  ┆ 1   ┆     │
│     ┆     ┆ lys ┆     ┆ s   ┆     ┆     ┆ vs  ┆ lys ┆ vs  ┆ 16  ┆     ┆     ┆     ┆     ┆ KO  ┆ s   ┆     ┆ ls, ┆     ┆     ┆ is  ┆ il. ┆ Med ┆ nue ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ 573 ┆     ┆ SRX ┆ can ┆     ┆ Sig ┆     ┆ tai ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ lys ┆ 747 ┆     ┆ 311 ┆ cha ┆ LE  ┆ lys ┆ eq  ┆ eq  ┆ can ┆ vs  ┆     ┆     ┆     ┆     ┆ 9;3 ┆ vs  ┆ 1   ┆ n   ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRS ┆     ┆     │
│     ┆     ┆ is_ ┆     ┆     ┆     ┆     ┆ SRR ┆ is  ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gro ┆     ┆     ┆     ┆ com ┆ ici ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 99  ┆     ┆ 535 ┆ cer ┆     ┆ nal ┆     ┆ ng  ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆ SAM ┆     ┆     ┆     ┆ 202 ┆ 116 ┆     ┆     ┆ is  ┆ aea ┆     ┆ 664 ┆ rac ┆     ┆ is  ┆ 200 ┆ 200 ┆ cer ┆ 158 ┆     ┆     ┆     ┆     ┆ 315 ┆ GSM ┆ vs  ┆ cel ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ 603 ┆     ┆     │
│     ┆     ┆ of_ ┆     ┆     ┆     ┆     ┆ 127 ┆ of  ┆ 138 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ win ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 138 ┆ .ni ┆     ┆     ┆ 176 ┆ cel ┆     ┆ ing ┆     ┆ rel ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 0   ┆ N02 ┆     ┆     ┆     ┆ 0-0 ┆ 611 ┆     ┆     ┆ of  ┆ 0ca ┆     ┆ 13  ┆ ter ┆     ┆ of  ┆ 0   ┆ 0   ┆ cel ┆ 948 ┆     ┆     ┆     ┆     ┆ 4;3 ┆ 138 ┆ GSM ┆ ls  ┆ 138 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 127 ┆ 794 ┆     ┆     │
│     ┆     ┆ hsf ┆     ┆     ┆     ┆     ┆ 464 ┆ HSF ┆ 205 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 205 ┆ h.g ┆     ┆     ┆     ┆ ls  ┆     ┆ ,   ┆     ┆ ati ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ seq ┆ 767 ┆     ┆     ┆     ┆ 5-2 ┆ 343 ┆     ┆     ┆ HSF ┆ ce3 ┆     ┆     ┆ iza ┆     ┆ HSF ┆     ┆ seq ┆ ls  ┆ 706 ┆     ┆     ┆     ┆     ┆ 320 ┆ 205 ┆ 138 ┆ wer ┆ 205 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 464 ┆     ┆     ┆     │
│     ┆     ┆ 1_i ┆     ┆     ┆     ┆     ┆ 2   ┆ 1   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ 435 ┆     ┆ ve  ┆ .go ┆ .go ┆ ncb ┆     ┆     ┆ uen ┆ 272 ┆     ┆     ┆     ┆ 0   ┆ 7   ┆     ┆     ┆ 1   ┆ b8e ┆     ┆     ┆ tio ┆     ┆ 1   ┆     ┆ uen ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ 8;6 ┆ 2   ┆ 205 ┆ e   ┆ 2   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     │
│     ┆     ┆ n_h ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ McC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ enr ┆ v/b ┆ v/s ┆ 312 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ af3 ┆     ┆     ┆ n   ┆     ┆ in  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 072 ┆     ┆ 2_r ┆ use ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ct1 ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oy' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ich ┆ ios ┆ ra? ┆ 1   ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HCT ┆ 07  ┆     ┆     ┆ of  ┆     ┆ HCT ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆ 1   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 16_ ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆ amp ┆ ter ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 116 ┆ vs  ┆     ┆     ┆ HSF ┆     ┆ 116 ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ fbx ┆     ┆     ┆     ┆     ┆     ┆ FBX ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5A  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts  ┆ le/ ┆ m=S ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ FBX ┆ 240 ┆     ┆     ┆ 1   ┆     ┆ FBX ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ w7_ ┆     ┆     ┆     ┆     ┆     ┆ W7  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX5 ┆     ┆     ┆     ┆ 204 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ W7  ┆ e13 ┆     ┆     ┆ bin ┆     ┆ W7  ┆     ┆ 204 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 511 ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ko_ ┆     ┆     ┆     ┆     ┆     ┆ KO  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N02 ┆ 351 ┆     ┆     ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ KO  ┆ c9a ┆     ┆     ┆ din ┆     ┆ KO  ┆     ┆ 9:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;77 ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 767 ┆ 73  ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ e10 ┆     ┆     ┆ g   ┆     ┆ cel ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆ 11; ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ls_ ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 270 ┆ vs  ┆     ┆     ┆     ┆ P-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆ 419 ┆     ┆     ┆ in  ┆     ┆ ls  ┆     ┆ P-S ┆     ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆ pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ upo ┆     ┆     ┆     ┆     ┆     ┆ upo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ upo ┆ 87b ┆     ┆     ┆ hum ┆     ┆ upo ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 93; ┆     ┆     ┆ cip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ n_h ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 382 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ ana ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ eca ┆     ┆     ┆ an  ┆     ┆ n   ┆     ┆ ana ┆     ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆     ┆     ┆ ita ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 049 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ lys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ 1ad ┆     ┆     ┆ WT  ┆     ┆ hea ┆     ┆ lys ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2;7 ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ caf ┆     ┆     ┆ and ┆     ┆ t   ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 776 ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 7. GSE66448 (ChIP-seq; SUMO2 / Pol II)

- [Global SUMOylation on active chromatin is an acute heat stress response restricting transcription](https://doi.org/10.1186/s13059-015-0717-y)
- Input control data が、熱ストレス条件下 vs. コントロール条件下のデータがあるので、念のため収集しておく
-

In [16]:
GSE66448_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE66448/GSE66448_PEP/GSE66448_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (~pl.col("sample_name").str.contains("vcap-chipseq-pias1")) & # remove vcap-chipseq-pias1 because it is not included ctrl "-c-" ChIP-seq data
    (~pl.col("sample_name").str.contains("vcap-chipseq-sumo2-")) & # remove vcap-chipseq-sumo2- because it is not included ctrl "-c-" ChIP-seq data
    (~pl.col("sample_name").str.contains("vcap-drb-chipseq-sumo2")) & # remove vcap-drb-chipseq-sumo2 because it is not included heat-shocked "-hs-" ChIP-seq data
    (~pl.col("sample_name").str.contains("vcap-trp-chipseq-sumo2"))   # remove vcap-trp-chipseq-sumo2 because it is not included heat-shocked "-hs-" ChIP-seq data
).with_columns(
    pl.lit("https://doi.org/10.1186/s13059-015-0717-y").alias("reference_doi"),
    pl.lit("43 C").alias("stress treatment temperature"),
    pl.lit("30 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE66448 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE66448.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE66448_combined = GSE66448_PEP.join(
    GSE66448,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE66448_combined = GSE66448_combined[[s.name for s in GSE66448_combined if not (s.null_count() == GSE66448_combined.height)]]

pl.Config.set_tbl_rows(2)
display(GSE66448_PEP)

shape: (36, 52)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ tre ┆ chi ┆ pro ┆ gen ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ atm ┆ p_a ┆ ces ┆ ome ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ent ┆ nti ┆ sed ┆ _bu ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ 1   ┆ bod ┆ _da ┆ ild ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ --- ┆ y   ┆ ta_ ┆ --- ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ str ┆ --- ┆ fil ┆ str ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆ e   ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆ str ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ k56 ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ K56 ┆ GSM ┆ Pub ┆ Mar ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ Hea ┆ K56 ┆ gen ┆ Nuc ┆ ChI ┆ GPL ┆ Ein ┆ ein ┆ Bio ┆ Sch ┆ Uni ┆ Yli ┆ Kuo ┆ 702 ┆ Fin ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ con ┆ ant ┆ K56 ┆ hg1 ┆ ChI ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 30  │
│ 2-c ┆ P   ┆ o   ┆ GLE ┆     ┆ 182 ┆ 895 ┆ 2-C ┆ 162 ┆ lic ┆ 03  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ t   ┆ 2   ┆ omi ┆ lei ┆ P-s ┆ 111 ┆ ari ┆ ari ┆ med ┆ ool ┆ ver ┆ opi ┆ pio ┆ 10  ┆ lan ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 162 ┆ E   ┆ 664 ┆     ┆ 895 ┆ 2   ┆ tro ┆ i-S ┆ 2-S ┆ 9   ┆ P-s ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min │
│ hip ┆     ┆ sap ┆     ┆     ┆ 389 ┆ 417 ┆ hIP ┆ 260 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ sho ┆ cel ┆ c   ┆ fro ┆ eq  ┆ 54  ┆ ,A, ┆ .ni ┆ ici ┆ of  ┆ sit ┆ sto ┆     ┆     ┆ d   ┆ na  ┆     ┆ c   ┆ eq  ┆ 260 ┆     ┆ 48  ┆     ┆ 417 ┆     ┆ l   ┆ UMO ┆ UMO ┆     ┆ eq  ┆ //w ┆ //w ┆ //d ┆     ┆ .   │
│ seq ┆     ┆ ien ┆     ┆     ┆ 5   ┆     ┆ seq ┆ 6   ┆ Jul ┆ 5   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆ ck  ┆ ls  ┆ DNA ┆ m   ┆     ┆     ┆ Nis ┆ ska ┆ ne  ┆ Med ┆ y   ┆ nra ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆ (37 ┆ -2/ ┆ 2-C ┆     ┆ and ┆ ww. ┆ ww. ┆ oi. ┆     ┆     │
│ -su ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ -SU ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ for ┆ wer ┆     ┆ app ┆     ┆     ┆ kan ┆ nen ┆     ┆ ici ┆ of  ┆ nta ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆ 3   ┆ .be ┆     ┆ GRO ┆ ncb ┆ ncb ┆ org ┆     ┆     │
│ mo2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ MO2 ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆ e   ┆     ┆ rox ┆     ┆     ┆ en  ┆ @ue ┆     ┆ ne  ┆ Eas ┆ 8   ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆ (MB ┆ dGr ┆     ┆ -se ┆ i.n ┆ i.n ┆ /10 ┆     ┆     │
│ -c- ┆     ┆     ┆     ┆     ┆     ┆     ┆ -C- ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-s ┆ gro ┆     ┆ ima ┆     ┆     ┆     ┆ f.f ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C)  ┆ L,  ┆ aph ┆     ┆ q   ┆ lm. ┆ lm. ┆ .11 ┆     ┆     │
│ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆ wn  ┆     ┆ tel ┆     ┆     ┆     ┆ i   ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cat ┆ .gz ┆     ┆ sig ┆ nih ┆ nih ┆ 86/ ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sam ┆ in  ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ alo ┆     ┆     ┆ nal ┆ .go ┆ .go ┆ s13 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ RPM ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆ lan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g#  ┆     ┆     ┆ int ┆ v/b ┆ v/s ┆ 059 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ I16 ┆     ┆ mil ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M11 ┆     ┆     ┆ ens ┆ ios ┆ ra? ┆ -01 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆ 40  ┆     ┆ lio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-3 ┆     ┆     ┆ iti ┆ amp ┆ ter ┆ 5-0 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ don ┆ med ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆ es  ┆ le/ ┆ m=S ┆ 717 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ ium ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lot ┆     ┆     ┆ as  ┆ SAM ┆ RX8 ┆ -y  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ sup ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ #   ┆     ┆     ┆ bed ┆ N03 ┆ 954 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆ ple ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 024 ┆     ┆     ┆ Gra ┆ 383 ┆ 17  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆ men ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆ ph  ┆ 019 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆ ted ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fil ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆ wit ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es. ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inc ┆ h   ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uba ┆ 10% ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tor ┆ fet ┆     ┆ (1% ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ al  ┆     ┆ ;   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 30m ┆ bov ┆     ┆ 10m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in. ┆ ine ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ser ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ um, ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1%  ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pen ┆     ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ici ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lli ┆     ┆ atu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/s ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pto ┆     ┆ VCa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ myc ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ant ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ibi ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oti ┆     ┆ 8mi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆ n.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2mM ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-g ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lut ┆     ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ami ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆     ┆ atu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [17]:
defined_pairs_gse66448_chipseq = [
    ("SRX895422", "SRX895421"), # k562-chipseq-input-hs vs. k562-chipseq-input
    ("SRX895419", "SRX895417"), # k562-chipseq-sumo2-hs-rep1 vs. k562-chipseq-sumo2-c-rep1
    ("SRX895420", "SRX895418"), # k562-chipseq-sumo2-hs-rep2 vs. k562-chipseq-sumo2-c-rep2
    ("SRX895429", "SRX895427"), # k562-shhsf1-chipseq-sumo2-hs-rep1 vs. k562-shhsf1-chipseq-sumo2-c-rep1
    ("SRX895430", "SRX895428"), # k562-shhsf1-chipseq-sumo2-hs-rep2 vs. k562-shhsf1-chipseq-sumo2-c-rep2
    ("SRX895433", "SRX895431"), # k562-shscr-chipseq-sumo2-hs-rep1 vs. k562-shscr-chipseq-sumo2-c-rep1
    ("SRX895434", "SRX895432"), # k562-shscr-chipseq-sumo2-hs-rep2 vs. k562-shscr-chipseq-sumo2-c-rep2

    # pair15_GSE66448_pol2_hs_43C_30min_vcap.txt
    # pair15_GSE66448_pol2_ctrl_vcap.txt
    ("SRX895445", "SRX895443"), # vcap-chipseq-pol2-hs-rep1 vs. vcap-chipseq-pol2-c-rep1
    ("SRX895446", "SRX895444"), # vcap-chipseq-pol2-hs-rep2 vs. vcap-chipseq-pol2-c-rep2

    # "-re-" means heat shock and recovery (30min at 43 degree C followed by 1h at 37 degree C)

    # ("SRX895447", "SRX895443"), # vcap-chipseq-pol2-re-rep1 vs. vcap-chipseq-pol2-c-rep1
    # ("SRX895448", "SRX895444"), # vcap-chipseq-pol2-re-rep2 vs. vcap-chipseq-pol2-c-rep2
    

    # pair16_GSE66448_pol2_hs_43C_30min_vcap_re.txt
    # pair16_GSE66448_pol2_ctrl_vcap_re.txt
    ("SRX1079376", "SRX1079374"), # vcap-sinon-chipseq-pol2-hs-rep1 vs. vcap-sinon-chipseq-pol2-c-rep1
    ("SRX1079377", "SRX1079375"), # vcap-sinon-chipseq-pol2-hs-rep2 vs. vcap-sinon-chipseq-pol2-c-rep2

    
    ("SRX1079384", "SRX1079382"), # vcap-sinon-chipseq-sumo2-hs-rep1 vs. vcap-sinon-chipseq-sumo2-c-rep1
    ("SRX1079385", "SRX1079383"), # vcap-sinon-chipseq-sumo2-hs-rep2 vs. vcap-sinon-chipseq-sumo2-c-rep2
    ("SRX1079388", "SRX1079386"), # vcap-sipias1-chipseq-sumo2-hs-rep1 vs. vcap-sipias1-chipseq-sumo2-c-rep1
    ("SRX1079389", "SRX1079387"), # vcap-sipias1-chipseq-sumo2-hs-rep2 vs. vcap-sipias1-chipseq-sumo2-c-rep2

    # pair17_GSE66448_pol2_hs_43C_30min_vcap_siube2i.txt
    # pair17_GSE66448_pol2_ctrl_vcap_siube2i.txt
    ("SRX1079380", "SRX1079378"), # vcap-siube2i-chipseq-pol2-hs-rep1 vs. vcap-siube2i-chipseq-pol2-c-rep1
    ("SRX1079381", "SRX1079379")  # vcap-siube2i-chipseq-pol2-hs-rep2 vs. vcap-siube2i-chipseq-pol2-c-rep2
]

paired_metada_df_gse66448 = create_paired_metadata(
    combined_df=GSE66448_combined,
    defined_sample_pairs=defined_pairs_gse66448_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse66448 is not None:
    paired_metada_df_gse66448.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE66448_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse66448)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (17, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ tre ┆ chi ┆ pro ┆ gen ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ atm ┆ p_a ┆ ces ┆ ome ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ent ┆ nti ┆ sed ┆ _bu ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ 1   ┆ bod ┆ _da ┆ ild ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ --- ┆ y   ┆ ta_ ┆ --- ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ str ┆ --- ┆ fil ┆ str ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆ e   ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ k56 ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ K56 ┆ GSM ┆ Pub ┆ Mar ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ Hea ┆ K56 ┆ gen ┆ Nuc ┆ seq ┆ GPL ┆ Ein ┆ ein ┆ Bio ┆ Sch ┆ Uni ┆ Yli ┆ Kuo ┆ 702 ┆ Fin ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ inp ┆ non ┆ K56 ┆ hg1 ┆ ChI ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 30  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 166 ┆ ILL ┆ Gen ┆ K56 ┆ c25 ┆ SRP ┆ 394 ┆ Hea ┆ GEN ┆ K56 ┆ Ill ┆ Ill ┆ 193 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ 1;1 ┆ GSM ┆ GSM ┆ Nuc ┆ GSM ┆ GEO ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 895 ┆ 895 ┆ 2-c ┆ P   ┆ o   ┆ GLE ┆     ┆ 182 ┆ 2-C ┆ 162 ┆ lic ┆ 03  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ t   ┆ 2   ┆ omi ┆ lei ┆ uen ┆ 111 ┆ ari ┆ ari ┆ med ┆ ool ┆ ver ┆ opi ┆ pio ┆ 10  ┆ lan ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 162 ┆ E   ┆ 664 ┆     ┆ 895 ┆ 2   ┆ ut  ┆ e   ┆ 2-I ┆ 9   ┆ P-s ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N03 ┆ o   ┆ 245 ┆ P   ┆ 9-1 ┆ 273 ┆ UMI ┆ eri ┆ 2-C ┆ 1d8 ┆ 055 ┆ 589 ┆ t   ┆ ERA ┆ 2-C ┆ umi ┆ umi ┆ 349 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ 315 ┆ 162 ┆ 162 ┆ lei ┆ 162 ┆     ┆ 2   ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 182 ┆ 861 ┆ 5-0 ┆ 664 │
│ 422 ┆ 421 ┆ hip ┆     ┆ sap ┆     ┆     ┆ 390 ┆ hIP ┆ 261 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ sho ┆ cel ┆ c   ┆ fro ┆ cin ┆ 54  ┆ ,A, ┆ .ni ┆ ici ┆ of  ┆ sit ┆ sto ┆     ┆     ┆ d   ┆ na  ┆     ┆ c   ┆ eq  ┆ 261 ┆     ┆ 48  ┆     ┆ 422 ┆     ┆ con ┆ (in ┆ npu ┆     ┆ eq  ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 383 ┆ sap ┆ 323 ┆     ┆ 0-1 ┆ 517 ┆ NA  ┆ c   ┆ hIP ┆ 682 ┆ 752 ┆ 98  ┆ sho ┆ TED ┆ hIP ┆ na  ┆ na  ┆ 090 ┆ eq  ┆ C   ┆     ┆     ┆ 67; ┆ 261 ┆ 261 ┆ fro ┆ 261 ┆     ┆     ┆ x:t ┆ 7-0 ┆ sap ┆     ┆ 769 ┆ 390 ┆ 224 ┆ 7-0 ┆ 48  │
│     ┆     ┆ seq ┆     ┆ ien ┆     ┆     ┆ 0   ┆ seq ┆ 1   ┆ Jul ┆ 5   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆ ck  ┆ ls  ┆ DNA ┆ m   ┆ g   ┆     ┆ Nis ┆ ska ┆ ne  ┆ Med ┆ y   ┆ nra ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ vs  ┆     ┆ tro ┆ put ┆ t-H ┆     ┆ and ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 037 ┆ ien ┆     ┆     ┆ 2   ┆ 7   ┆     ┆     ┆ seq ┆ 40d ┆     ┆ vs  ┆ ck- ┆ _FI ┆ seq ┆ HiS ┆ HiS ┆ 2   ┆     ┆     ┆     ┆     ┆ 275 ┆ 1   ┆ 1_r ┆ m   ┆ 1   ┆     ┆     ┆ err ┆ 9   ┆ ien ┆     ┆ 90  ┆ 0   ┆ vs  ┆ 9   ┆     │
│     ┆     ┆ -in ┆     ┆ s   ┆     ┆     ┆ vs  ┆ -in ┆ vs  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ for ┆ wer ┆     ┆ app ┆ of  ┆     ┆ kan ┆ nen ┆     ┆ ici ┆ of  ┆ nta ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ SRX ┆     ┆ l   ┆ )   ┆ S.b ┆     ┆ GRO ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ -in ┆ d4d ┆     ┆ 493 ┆ ind ┆ LE  ┆ -in ┆ eq  ┆ eq  ┆ vs  ┆     ┆     ┆     ┆     ┆ 9;3 ┆ vs  ┆ 1   ┆ app ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRS ┆     ┆     │
│     ┆     ┆ put ┆     ┆     ┆     ┆     ┆ SRR ┆ put ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆ e   ┆     ┆ rox ┆ fra ┆     ┆ en  ┆ @ue ┆     ┆ ne  ┆ Eas ┆ 8   ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ 895 ┆     ┆ for ┆     ┆ edG ┆     ┆ -se ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆ SAM ┆     ┆     ┆     ┆ 202 ┆ 228 ┆     ┆     ┆ put ┆ 73a ┆     ┆ 344 ┆ uce ┆     ┆ put ┆ 200 ┆ 200 ┆ 241 ┆     ┆     ┆     ┆     ┆ 315 ┆ GSM ┆ vs  ┆ rox ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ 861 ┆     ┆     │
│     ┆     ┆ -hs ┆     ┆     ┆     ┆     ┆ 182 ┆ -HS ┆ 162 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-s ┆ gro ┆     ┆ ima ┆ gme ┆     ┆     ┆ f.f ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 162 ┆     ┆     ┆     ┆ 421 ┆     ┆ HS  ┆     ┆ rap ┆     ┆ q   ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ 0   ┆ N03 ┆     ┆     ┆     ┆ 0-0 ┆ 901 ┆     ┆     ┆ -HS ┆ d31 ┆     ┆ 61  ┆ d   ┆     ┆ -HS ┆ 0   ┆ 0   ┆ 738 ┆     ┆     ┆     ┆     ┆ 4;3 ┆ 162 ┆ GSM ┆ ima ┆ 162 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 182 ┆ 225 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 389 ┆ vs  ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆ wn  ┆     ┆ tel ┆ nte ┆     ┆     ┆ i   ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆ sam ┆     ┆ h.g ┆     ┆ sig ┆ nih ┆ nih ┆ 86/ ┆     ┆     ┆ seq ┆ 383 ┆     ┆     ┆     ┆ 5-0 ┆ 060 ┆     ┆     ┆ vs  ┆ 544 ┆     ┆     ┆ cha ┆     ┆ vs  ┆     ┆ seq ┆ 858 ┆     ┆     ┆     ┆     ┆ 320 ┆ 261 ┆ 162 ┆ tel ┆ 261 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 389 ┆     ┆     ┆     │
│     ┆     ┆ k56 ┆     ┆     ┆     ┆     ┆ 9   ┆ K56 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sam ┆ in  ┆     ┆ y   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆ Fin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ z   ┆     ┆ nal ┆ .go ┆ .go ┆ s13 ┆     ┆     ┆ uen ┆ 041 ┆     ┆     ┆     ┆ 2   ┆ 8   ┆     ┆     ┆ K56 ┆ 333 ┆     ┆     ┆ nge ┆     ┆ K56 ┆     ┆ uen ┆ 9   ┆     ┆     ┆     ┆     ┆ 8;6 ┆ 0   ┆ 261 ┆ y   ┆ 0   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     │
│     ┆     ┆ 2-c ┆     ┆     ┆     ┆     ┆     ┆ 2-C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆ RPM ┆     ┆ 10  ┆ chr ┆     ┆     ┆     ┆     ┆     ┆ lan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ vs  ┆     ┆ int ┆ v/b ┆ v/s ┆ 059 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-C ┆ 1b3 ┆     ┆     ┆ s   ┆     ┆ 2-C ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 072 ┆     ┆ 0_r ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hip ┆     ┆     ┆     ┆     ┆     ┆ hIP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ I16 ┆     ┆ mil ┆ oma ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (30 ┆     ┆ K56 ┆     ┆ ens ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hIP ┆ 60  ┆     ┆     ┆ in  ┆     ┆ hIP ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆ 1   ┆ mil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆ 40  ┆     ┆ lio ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆ 2-I ┆     ┆ iti ┆ amp ┆ ter ┆ 5-0 ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆ vs  ┆     ┆     ┆ chr ┆     ┆ seq ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆ lio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -in ┆     ┆     ┆     ┆     ┆     ┆ -in ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ don ┆ med ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆ npu ┆     ┆ es  ┆ le/ ┆ m=S ┆ 717 ┆     ┆     ┆ 162 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -in ┆ 7a5 ┆     ┆     ┆ oma ┆     ┆ -in ┆     ┆ 162 ┆     ┆     ┆     ┆     ┆     ┆ ;33 ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆ put ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ ium ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆     ┆ t-C ┆     ┆ as  ┆ SAM ┆ RX8 ┆ -y  ┆     ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ put ┆ 441 ┆     ┆     ┆ tin ┆     ┆ put ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ sup ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆     ┆ .be ┆     ┆ bed ┆ N03 ┆ 954 ┆     ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d8a ┆     ┆     ┆ bin ┆     ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆ ;77 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆ ple ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆     ┆ dGr ┆     ┆ Gra ┆ 383 ┆ 22  ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 668 ┆     ┆     ┆ din ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆ 11; ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆ men ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C)  ┆     ┆ aph ┆     ┆ ph  ┆ 037 ┆ vs  ┆     ┆     ┆     ┆ 2-C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d05 ┆     ┆     ┆ g   ┆     ┆     ┆     ┆ 2-C ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆ ted ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ .gz ┆     ┆ fil ┆ vs  ┆ htt ┆     ┆     ┆     ┆ hIP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 81e ┆     ┆     ┆ of  ┆     ┆     ┆     ┆ hIP ┆     ┆     ┆     ┆     ┆     ┆ 93; ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆ wit ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inp ┆     ┆     ┆     ┆ es. ┆ htt ┆ ps: ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 266 ┆     ┆     ┆ SUM ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 8. GSE60984 (ChIP-seq; HSF1)

- [Cross talk between cytokine and hyperthermia-induced pathways: identification of different subsets of NF-κB-dependent genes regulated by TNFα and heat shock](https://doi.org/10.1007/s00438-015-1055-1)
- control の replicate が 2つ以上ないため、ChIP-Atlas Diff Analysis は実行しない

In [18]:
GSE60984_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE60984/GSE60984_PEP/GSE60984_PEP_raw.csv",
    separator=','
).filter(
    pl.col("sample_library_strategy") == "ChIP-Seq"
).with_columns(
    pl.lit("https://doi.org/10.1007/s00438-015-1055-1").alias("reference_doi"),
    pl.lit("43 C").alias("stress treatment temperature"),
    pl.when(pl.col("sample_name") == "hs_10").then(pl.lit("10 min."))
      .when(pl.col("sample_name") == "hs_20").then(pl.lit("20 min."))
      .when(pl.col("sample_name") == "control").then(pl.lit("ctrl"))
      .otherwise(pl.lit(None))
      .alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE60984 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE60984.metadata.tsv",
    separator='\t'
)

GSE60984_combined = GSE60984_PEP.join(
    GSE60984,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE60984_combined = GSE60984_combined[[s.name for s in GSE60984_combined if not (s.null_count() == GSE60984_combined.height)]]

pl.Config.set_tbl_rows(3)
display(GSE60984_combined)

shape: (3, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ ant ┆ sex ┆ tis ┆ age ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ ibo ┆ --- ┆ sue ┆ --- ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ dy  ┆ str ┆ _ce ┆ str ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆     ┆ lls ┆     ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ i64 ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ hs_ ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ HS_ ┆ GSM ┆ Pub ┆ Sep ┆ May ┆ SRA ┆ 1   ┆ HSF ┆ Hom ┆ 960 ┆ A   ┆ gen ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ U-2 ┆ ant ┆ fem ┆ bon ┆ 15  ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 10  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 297 ┆ ILL ┆ ftp ┆ Gen ┆ HS_ ┆ 978 ┆ SRP ┆ 416 ┆ Sub ┆ GEN ┆ HS_ ┆ Ill ┆ Ill ┆ ftp ┆ 332 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GEO ┆ U-2 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 10  ┆ P   ┆ o   ┆ GLE ┆     ┆ 156 ┆ 690 ┆ 10  ┆ 149 ┆ lic ┆ 02  ┆ 15  ┆     ┆     ┆ 1   ┆ o   ┆ 6   ┆ gro ┆ omi ┆ 109 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 149 ┆ :// ┆ :// ┆ 609 ┆     ┆ 690 ┆ OS  ┆ i-H ┆ ale ┆ e/o ┆ yea ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N03 ┆ o   ┆ 180 ┆ P   ┆ 9-1 ┆ 898 ┆ UMI ┆ .sr ┆ eri ┆ 10  ┆ ccb ┆ 045 ┆ 224 ┆ set ┆ ERA ┆ 10  ┆ umi ┆ umi ┆ .sr ┆ 979 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 149 ┆ 149 ┆ ls  ┆ 149 ┆     ┆ OS  ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 156 ┆ 693 ┆ 5-0 ┆ 609 │
│     ┆     ┆ sap ┆     ┆     ┆ 255 ┆ 823 ┆     ┆ 518 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ChI ┆ sap ┆     ┆ wth ┆ c   ┆ 99  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 518 ┆ ftp ┆ ftp ┆ 84  ┆     ┆ 823 ┆     ┆ SF1 ┆     ┆ ste ┆ rs  ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 015 ┆ sap ┆ 957 ┆     ┆ 0-0 ┆ 662 ┆ NA  ┆ a.e ┆ c   ┆     ┆ abf ┆ 982 ┆ 02  ┆ s   ┆ TED ┆     ┆ na  ┆ na  ┆ a.e ┆ 216 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 518 ┆ 518 ┆ wer ┆ 518 ┆     ┆     ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 600 ┆ 255 ┆ 297 ┆ 8-0 ┆ 84  │
│     ┆     ┆ ien ┆     ┆     ┆ 6   ┆     ┆     ┆ 1   ┆ Aug ┆ 4   ┆ 9   ┆     ┆     ┆ P   ┆ ien ┆     ┆ med ┆ DNA ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆ 1   ┆ .nc ┆ .nc ┆     ┆     ┆     ┆     ┆     ┆     ┆ osa ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ Gen ┆ 209 ┆ ien ┆     ┆     ┆ 7   ┆ 6   ┆     ┆ bi. ┆     ┆     ┆ 65b ┆     ┆     ┆ of  ┆ _FI ┆     ┆ Gen ┆ Gen ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 1   ┆ 1_r ┆ e   ┆ 1   ┆     ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 42  ┆ 6   ┆     ┆ 3   ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆ DNA ┆ s   ┆     ┆ ium ┆     ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆     ┆ bi. ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆     ┆ rco ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ ome ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ 35b ┆     ┆     ┆ NFk ┆ LE  ┆     ┆ ome ┆ ome ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ fix ┆     ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆ fro ┆     ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆     ┆ nlm ┆ nlm ┆     ┆     ┆     ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆ 2da ┆     ┆     ┆ app ┆     ┆     ┆ Ana ┆ Ana ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆ m   ┆     ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆     ┆ .ni ┆ .ni ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ e92 ┆     ┆     ┆ aB- ┆     ┆     ┆ lyz ┆ lyz ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ by  ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ exp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆ h.g ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 07/ ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 2bc ┆     ┆     ┆ dep ┆     ┆     ┆ er  ┆ er  ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ add ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IIx ┆     ┆     ┆     ┆     ┆ ov/ ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ s00 ┆     ┆     ┆ IIx ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 46b ┆     ┆     ┆ end ┆     ┆     ┆ IIx ┆ IIx ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ing ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 438 ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 046 ┆     ┆     ┆ ent ┆     ┆     ┆     ┆ seq ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 1a  ┆     ┆     ┆ gen ┆     ┆     ┆     ┆ uen ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 5-1 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ cin ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ R15 ┆ 213 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cke ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 055 ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 006 ┆     ┆     ┆     ┆     ┆     ┆ are ┆     ┆     ┆     ┆ g:  ┆ 006 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX6 ┆ -1  ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ dif ┆     ┆     ┆     ┆ GSM ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 06/ ┆ 511 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 149 ┆ 149 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N03 ┆ 908 ┆     ┆     ┆     ┆ 149 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R15 ┆     ┆     ┆     ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ 149 ┆ R15 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43° ┆     ┆     ┆ lac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 015 ┆ 23  ┆     ┆     ┆     ┆ 518 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 625 ┆     ┆     ┆     ┆     ┆     ┆ ent ┆     ┆     ┆     ┆ 518 ┆ 625 ┆     ┆     ┆     ┆     ┆     ┆ 156 ┆ 11; ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 209 ┆     ┆     ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ ial ┆     ┆     ┆     ┆ 1:  ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ 255 ┆ 895 ┆     ┆     ┆ fin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM1 ┆ SM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ HS_ ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 6/S ┆ 93; ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10  ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 495 ┆ 495 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 156 ┆     ┆     ┆     ┆     ┆     ┆ reg ┆     ┆     ┆     ┆ 10  ┆ 156 ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆ 774 ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 181 ┆ 181 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 255 ┆     ┆     ┆     ┆     ┆     ┆ ula ┆     ┆     ┆     ┆ Hom ┆ 255 ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆ 2;7 ┆     ┆     ┆ cen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ute ┆     ┆     ┆ equ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.f ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ o   ┆ 6.f ┆     ┆     ┆     ┆     ┆     ┆ 556 ┆ 776 ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ aft ┆     ┆     ┆     ┆ sap ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆ ;11 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [19]:
defined_pairs_gse60984_chipseq = [
    ("SRX690823", "SRX690825"), # HS_10 vs. control
    ("SRX690824", "SRX690825")  # HS_20 vs. control
]

paired_metada_df_gse60984 = create_paired_metadata(
    combined_df=GSE60984_combined,
    defined_sample_pairs=defined_pairs_gse60984_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse60984 is not None:
    paired_metada_df_gse60984 = paired_metada_df_gse60984.with_columns(
        pl.col("stress treatment time").str.strip_suffix(" vs ctrl")
    )
    paired_metada_df_gse60984.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE60984_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse60984)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 93)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ ant ┆ sex ┆ tis ┆ age ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ ibo ┆ --- ┆ sue ┆ --- ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ dy  ┆ str ┆ _ce ┆ str ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆     ┆ lls ┆     ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆     ┆ --- ┆     ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hs_ ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ HS_ ┆ GSM ┆ Pub ┆ Sep ┆ May ┆ SRA ┆ 1   ┆ HSF ┆ Hom ┆ 960 ┆ A   ┆ gen ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ nul ┆ GSE ┆ 0   ┆ SRX ┆ U-2 ┆ ant ┆ fem ┆ bon ┆ 15  ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 10  ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 297 ┆ ILL ┆ ftp ┆ Gen ┆ HS_ ┆ 978 ┆ SRP ┆ 416 ┆ Sub ┆ GEN ┆ HS_ ┆ Ill ┆ Ill ┆ ftp ┆ 332 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GEO ┆ U-2 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 690 ┆ 690 ┆ 10  ┆ P   ┆ o   ┆ GLE ┆     ┆ 156 ┆ 10  ┆ 149 ┆ lic ┆ 02  ┆ 15  ┆     ┆     ┆ 1   ┆ o   ┆ 6   ┆ gro ┆ omi ┆ 109 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 149 ┆ :// ┆ l   ┆ 609 ┆     ┆ 690 ┆ OS  ┆ i-H ┆ ale ┆ e/o ┆ yea ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N03 ┆ o   ┆ 180 ┆ P   ┆ 9-1 ┆ 898 ┆ UMI ┆ .sr ┆ eri ┆ 10  ┆ ccb ┆ 045 ┆ 224 ┆ set ┆ ERA ┆ 10  ┆ umi ┆ umi ┆ .sr ┆ 979 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 149 ┆ 149 ┆ ls  ┆ 149 ┆     ┆ OS  ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 156 ┆ 693 ┆ 5-0 ┆ 609 │
│ 823 ┆ 825 ┆ vs  ┆     ┆ sap ┆     ┆     ┆ 255 ┆ vs  ┆ 518 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ChI ┆ sap ┆     ┆ wth ┆ c   ┆ 99  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 518 ┆ ftp ┆     ┆ 84  ┆     ┆ 823 ┆     ┆ SF1 ┆     ┆ ste ┆ rs  ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 015 ┆ sap ┆ 957 ┆     ┆ 0-0 ┆ 662 ┆ NA  ┆ a.e ┆ c   ┆ vs  ┆ abf ┆ 982 ┆ 02  ┆ s   ┆ TED ┆ vs  ┆ na  ┆ na  ┆ a.e ┆ 216 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 518 ┆ 518 ┆ wer ┆ 518 ┆     ┆     ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 600 ┆ 255 ┆ 297 ┆ 8-0 ┆ 84  │
│     ┆     ┆ con ┆     ┆ ien ┆     ┆     ┆ 6   ┆ con ┆ 1   ┆ Aug ┆ 4   ┆ 9   ┆     ┆     ┆ P   ┆ ien ┆     ┆ med ┆ DNA ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆ 1   ┆ .nc ┆     ┆     ┆     ┆ vs  ┆     ┆ vs  ┆     ┆ osa ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ Gen ┆ 209 ┆ ien ┆     ┆     ┆ 7   ┆ 6   ┆     ┆ bi. ┆     ┆ con ┆ 65b ┆     ┆ vs  ┆ of  ┆ _FI ┆ con ┆ Gen ┆ Gen ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 1   ┆ 1_r ┆ e   ┆ 1   ┆     ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 42  ┆ 6   ┆ vs  ┆ 3   ┆     │
│     ┆     ┆ tro ┆     ┆ s   ┆     ┆     ┆ vs  ┆ tro ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆ DNA ┆ s   ┆     ┆ ium ┆     ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆     ┆ SRX ┆     ┆ non ┆     ┆ rco ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ ome ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆ ac. ┆     ┆ tro ┆ 35b ┆     ┆ 423 ┆ NFk ┆ LE  ┆ tro ┆ ome ┆ ome ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ fix ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRS ┆     ┆     │
│     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆ SRR ┆ l   ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ fro ┆     ┆     ┆ fro ┆     ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ Ana ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆     ┆ 690 ┆     ┆ e   ┆     ┆ ma  ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ Ana ┆ SAM ┆     ┆     ┆     ┆ 202 ┆ 308 ┆     ┆ uk/ ┆     ┆ l   ┆ 2da ┆     ┆ 502 ┆ app ┆     ┆ l   ┆ Ana ┆ Ana ┆ uk/ ┆ 338 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ed  ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ 693 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 156 ┆     ┆ 149 ┆ 5   ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆ m   ┆     ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ lyz ┆     ┆     ┆     ┆ 149 ┆ .ni ┆     ┆     ┆     ┆ 825 ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ lyz ┆ N03 ┆     ┆     ┆     ┆ 0-0 ┆ 209 ┆     ┆ vol ┆     ┆     ┆ e92 ┆     ┆ 56  ┆ aB- ┆     ┆     ┆ lyz ┆ lyz ┆ vol ┆ 802 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 149 ┆ GSM ┆ by  ┆ 149 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 156 ┆ 299 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 255 ┆     ┆ 518 ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ exp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆ 518 ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 07/ ┆     ┆     ┆ er  ┆ 015 ┆     ┆     ┆     ┆ 5-1 ┆ 483 ┆     ┆ 1/f ┆     ┆     ┆ 2bc ┆     ┆     ┆ dep ┆     ┆     ┆ er  ┆ er  ┆ 1/f ┆ 048 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 518 ┆ 149 ┆ add ┆ 518 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 255 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ IIx ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ s00 ┆     ┆     ┆ IIx ┆ 211 ┆     ┆     ┆     ┆ 6   ┆ 9   ┆     ┆ ast ┆     ┆     ┆ 46b ┆     ┆     ┆ end ┆     ┆     ┆ IIx ┆ IIx ┆ ast ┆ 0   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 3   ┆ 518 ┆ ing ┆ 3   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 438 ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 046 ┆     ┆     ┆ ent ┆     ┆     ┆     ┆ seq ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 3_r ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ tal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 1a  ┆     ┆     ┆ gen ┆     ┆     ┆     ┆ uen ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆ dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 5-1 ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 56/ ┆     ┆     ┆ vs  ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ cin ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ R15 ┆ 213 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cke ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 055 ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 006 ┆     ┆     ┆ 79a ┆     ┆     ┆ are ┆     ┆     ┆     ┆ g:  ┆ 006 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX6 ┆ -1  ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 14f ┆     ┆     ┆ dif ┆     ┆     ┆     ┆ GSM ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 06/ ┆ 511 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 149 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N03 ┆ 908 ┆     ┆     ┆     ┆ 149 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R15 ┆     ┆     ┆ 136 ┆     ┆     ┆ fer ┆     ┆     ┆     ┆ 149 ┆ R15 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43° ┆     ┆     ┆ lac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 015 ┆ 23  ┆     ┆     ┆     ┆ 518 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 625 ┆     ┆     ┆ 868 ┆     ┆     ┆ ent ┆     ┆     ┆     ┆ 518 ┆ 625 ┆     ┆     ┆     ┆     ┆     ┆ 156 ┆ 11; ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 209 ┆ vs  ┆     ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 56/ ┆     ┆     ┆ 451 ┆     ┆     ┆ ial ┆     ┆     ┆     ┆ 1:  ┆ 56/ ┆     ┆     ┆     ┆     ┆     ┆ 255 ┆ 895 ┆     ┆     ┆ fin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ 706 ┆     ┆     ┆ ly  ┆     ┆     ┆     ┆ HS_ ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 6/S ┆ 93; ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10  ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 495 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 156 ┆     ┆     ┆ 61b ┆     ┆     ┆ reg ┆     ┆     ┆     ┆ 10  ┆ 156 ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆ 774 ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 181 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 255 ┆     ┆     ┆ 563 ┆     ┆     ┆ ula ┆     ┆     ┆     ┆ Hom ┆ 255 ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆ 2;7 ┆     ┆     ┆ cen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ute ┆     ┆     ┆ equ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.f ┆     ┆     ┆ d7b ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ o   ┆ 6.f ┆     ┆     ┆     ┆     ┆     ┆ 556 ┆ 776 ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 9. GSE105028 (ChIP-seq; RAD21/CTCF/ZNF143/PolII/NANOG/KLF4/OCT4/CFOS/BRG1/HSF1/WAPL/NIPBL)

- [Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress](https://doi.org/10.1016/j.molcel.2018.07.012)
- `Cell culture and heat shock treatment ... For heat shock treatment, 80% confluent H9 cells were changed into 42°C prewarmed conditioned SFM medium and transferred into a 42°C incubator for 1 h.`

In [20]:
GSE105028_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE105028/GSE105028_PEP/GSE105028_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &

    # removed histone modification ChIP-seq data
    (~pl.col("sample_name").str.contains("h3k27ac")) &
    (~pl.col("sample_name").str.contains("h3k27me3")) &
    (~pl.col("sample_name").str.contains("h3k4me1")) &
    (~pl.col("sample_name").str.contains("h3k4me3")) 
).with_columns(
    pl.lit("https://doi.org/10.1016/j.molcel.2018.07.012").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE105028 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE105028.metadata.tsv",
    separator='\t'
)

GSE105028_combined = GSE105028_PEP.join(
    GSE105028,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE105028_combined = GSE105028_combined[[s.name for s in GSE105028_combined if not (s.null_count() == GSE105028_combined.height)]]

pl.Config.set_tbl_rows(35)
display(GSE105028_combined)

shape: (35, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ i64 ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ igg ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ IgG ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ ChI ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Arc ┆ SRA ┆ ChI ┆ 201 ┆ 421 ┆ ILL ┆ ftp ┆ Gen ┆ IgG ┆ dcd ┆ SRP ┆ 141 ┆ Arc ┆ GEN ┆ IgG ┆ Ill ┆ Ill ┆ ftp ┆ 141 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ H9  ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ _ch ┆ P   ┆ o   ┆ RED ┆     ┆ 617 ┆ 328 ┆ ChI ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ P-S ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 281 ┆ :// ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N07 ┆ hit ┆ 619 ┆ P   ┆ 8-0 ┆ 179 ┆ UMI ┆ .sr ┆ eri ┆ ChI ┆ c26 ┆ 120 ┆ 453 ┆ hit ┆ ERA ┆ ChI ┆ umi ┆ umi ┆ .sr ┆ 453 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 281 ┆ 281 ┆ Hi- ┆ 281 ┆     ┆ hum ┆ _ta ┆ 8-0 ┆ o   ┆ 6   ┆ NA4 ┆ 617 ┆ 259 ┆ 8-0 ┆ 105 │
│ ip- ┆     ┆ sap ┆     ┆     ┆ 793 ┆ 855 ┆ P-S ┆ 661 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ eq  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 661 ┆ ftp ┆ 028 ┆     ┆ 855 ┆ an  ┆ nor ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 790 ┆ ect ┆ 794 ┆     ┆ 8-0 ┆ 770 ┆ NA  ┆ a.e ┆ c   ┆ P-S ┆ b53 ┆ 027 ┆ 63  ┆ ect ┆ TED ┆ P-S ┆ na  ┆ na  ┆ a.e ┆ 630 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 661 ┆ 661 ┆ C,  ┆ 661 ┆     ┆ an  ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 144 ┆ 793 ┆ 809 ┆ 8-0 ┆ 028 │
│ seq ┆     ┆ ien ┆     ┆     ┆ 2   ┆ 4   ┆ eq  ┆ 3   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ und ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 3   ┆ .nc ┆     ┆     ┆ 4   ┆ Emb ┆ mal ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 039 ┆ ura ┆     ┆     ┆ 4   ┆ ;43 ┆     ┆ bi. ┆     ┆ eq  ┆ 280 ┆     ┆     ┆ ura ┆ _FI ┆ eq  ┆ HiS ┆ HiS ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 3   ┆ 3_r ┆ cel ┆ 3   ┆     ┆ Emb ┆ err ┆ 4   ┆ ien ┆     ┆ 42  ┆ 2   ┆ 0   ┆ 4   ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ er  ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆ ryo ┆ con ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆     ┆ l   ┆     ┆     ┆     ┆ 527 ┆     ┆ ac. ┆     ┆     ┆ c08 ┆     ┆     ┆ l   ┆ LE; ┆     ┆ eq  ┆ eq  ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ ls  ┆     ┆     ┆ ryo ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆ nic ┆ dit ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆     ┆ pro ┆     ┆     ┆     ┆ 722 ┆     ┆ uk/ ┆     ┆     ┆ f2f ┆     ┆     ┆ pro ┆ GEN ┆     ┆ 200 ┆ 200 ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ wer ┆     ┆     ┆ nic ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆ Ste ┆ ion ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 0   ┆     ┆ tei ┆     ┆     ┆     ┆ 3   ┆     ┆ vol ┆     ┆     ┆ 6f6 ┆     ┆     ┆ tei ┆ ERA ┆     ┆ 0   ┆ 0   ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ e   ┆     ┆     ┆ Ste ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆ m   ┆ s   ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ seq ┆     ┆ ns  ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ f41 ┆     ┆     ┆ ns  ┆ TED ┆     ┆     ┆ seq ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ cro ┆     ┆     ┆ m   ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆ uen ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 551 ┆     ┆     ┆ and ┆ _FI ┆     ┆     ┆ uen ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ssl ┆     ┆     ┆ Cel ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆ cin ┆     ┆ plu ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ c06 ┆     ┆     ┆ plu ┆ LE  ┆     ┆     ┆ cin ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ ink ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆ g:  ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆     ┆     ┆ 74; ┆     ┆     ┆ rip ┆     ┆     ┆     ┆ g:  ┆ RR6 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ ed  ┆     ┆     ┆ Lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆ GSM ┆     ┆ ote ┆     ┆     ┆     ┆     ┆     ┆ 17/ ┆     ┆     ┆ 4a1 ┆     ┆     ┆ ote ┆     ┆     ┆     ┆ GSM ┆ 17/ ┆     ┆     ┆     ┆     ┆     ┆ R61 ┆ 213 ┆     ┆     ┆ wit ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆ 281 ┆     ┆ ncy ┆     ┆     ┆     ┆     ┆     ┆ 002 ┆     ┆     ┆ b27 ┆     ┆     ┆ ncy ┆     ┆     ┆     ┆ 281 ┆ 002 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆ 661 ┆     ┆ fac ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ c12 ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 661 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 02/ ┆ 511 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 281 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 288 ┆ 12  ┆     ┆     ┆ 3:  ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆ R61 ┆     ┆     ┆ 1ef ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ 3:  ┆ R61 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 790 ┆ 554 ┆     ┆     ┆     ┆ IgG ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 779 ┆     ┆     ┆ fc3 ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ IgG ┆ 779 ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ 039 ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ coo ┆     ┆     ┆     ┆     ┆     ┆ 32/ ┆     ┆     ┆ fb7 ┆     ┆     ┆ coo ┆     ┆     ┆     ┆ ChI ┆ 32/ ┆     ┆     ┆     ┆     ┆     ┆ 793 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ 4b4 ┆     ┆     ┆ per ┆     ┆     ┆     ┆ P-S ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 2/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 816 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆     ┆     ┆ 889 ┆     ┆     ┆ ate ┆     ┆     ┆     ┆ eq  ┆ 617 ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 613 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆ 793 ┆     ┆     ┆ 0f1 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ Hom ┆ 793 ┆     ┆     ┆     ┆     ┆     ┆ 177 ┆ 2;7 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ orc ┆     ┆     ┆     ┆     ┆     ┆ 2_1 ┆     ┆     ┆ 47c ┆     ┆     ┆ orc ┆     ┆     ┆     ┆ o   ┆ 2_1 ┆     ┆     ┆     ┆     ┆     ┆ 932 ┆ 776 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆ hes ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ 18  ┆     ┆     ┆ hes ┆     ┆     ┆     ┆ sap ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆ ;11 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ ien ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [21]:
defined_pairs_gse105028_chipseq = [
    ("SRX3288555", "SRX3288554"), # hs_igg_chip-seq vs. igg_chip-seq
    ("SRX3288558", "SRX3288556"), # hs_rad21_chip-seq_rep1 vs. rad21_chip-seq_rep1
    ("SRX3288559", "SRX3288557"), # hs_rad21_chip-seq_rep2 vs. rad21_chip-seq_rep2
    ("SRX3288561", "SRX3288560"), # hs_ctcf_chip-seq vs. ctcf_chip-seq
    ("SRX3288563", "SRX3288562"), # hs_znf143_chip-seq vs. znf143_chip-seq
    ("SRX3288565", "SRX3288564"), # hs_rnapol_ii_chip-seq vs. rnapol_ii_chip-seq (replicate が 2つ以上ないので、diff analysis では除外)
    ("SRX3288567", "SRX3288566"), # hs_nanog_chip-seq vs. nanog_chip-seq
    ("SRX3288569", "SRX3288568"), # hs_klf4_chip-seq vs. klf4_chip-seq
    ("SRX3288571", "SRX3288570"), # hs_oct4_chip-seq vs. oct4_chip-seq
    ("SRX3288573", "SRX3288572"), # hs_ring1b_chip-seq vs. ring1b_chip-seq
    ("SRX3288575", "SRX3288574"), # hs_cfos_chip-seq vs. cfos_chip-seq
    ("SRX3288577", "SRX3288576"), # hs_brg1_chip-seq vs. brg1_chip-seq
    ("SRX3288579", "SRX3288578"), # hs_hsf1_chip-seq vs. hsf1_chip-seq
    ("SRX3288580", "SRX3288578"), # hs_ki_hsf1_chip-seq vs. hsf1_chip-seq
    ("SRX3288582", "SRX3288581"), # hs_wapl_chip-seq vs. wapl_chip-seq
    ("SRX3288584", "SRX3288583"), # hs_nipbl_chip-seq vs. nipbl_chip-seq
    ("SRX3288586", "SRX3288585"), # hs_ctcf_chip-nexus vs. ctcf_chip-nexus
    ("SRX3288588", "SRX3288587")  # hs_rad21_chip-nexus vs. rad21_chip-nexus
]

paired_metada_df_gse105028 = create_paired_metadata(
    combined_df=GSE105028_combined,
    defined_sample_pairs=defined_pairs_gse105028_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse105028 is not None:
    paired_metada_df_gse105028.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE105028_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse105028)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (18, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hs_ ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ ChI ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Arc ┆ SRA ┆ ChI ┆ 201 ┆ 412 ┆ ILL ┆ ftp ┆ Gen ┆ HS  ┆ 023 ┆ SRP ┆ 140 ┆ Arc ┆ GEN ┆ HS  ┆ Ill ┆ Ill ┆ ftp ┆ 140 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ H9  ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 328 ┆ 328 ┆ igg ┆ P   ┆ o   ┆ RED ┆     ┆ 617 ┆ IgG ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ P-S ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 281 ┆ :// ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N07 ┆ hit ┆ 619 ┆ P   ┆ 8-0 ┆ 727 ┆ UMI ┆ .sr ┆ eri ┆ IgG ┆ c37 ┆ 120 ┆ 070 ┆ hit ┆ ERA ┆ IgG ┆ umi ┆ umi ┆ .sr ┆ 070 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 281 ┆ 281 ┆ Hi- ┆ 281 ┆     ┆ hum ┆ _ta ┆ 8-0 ┆ o   ┆ 6   ┆ NA4 ┆ 617 ┆ 259 ┆ 8-0 ┆ 105 │
│ 855 ┆ 855 ┆ _ch ┆     ┆ sap ┆     ┆     ┆ 793 ┆ ChI ┆ 661 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ eq  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 661 ┆ ftp ┆ 028 ┆     ┆ 855 ┆ an  ┆ hea ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 790 ┆ ect ┆ 794 ┆     ┆ 8-0 ┆ 700 ┆ NA  ┆ a.e ┆ c   ┆ ChI ┆ 59b ┆ 027 ┆ 84  ┆ ect ┆ TED ┆ ChI ┆ na  ┆ na  ┆ a.e ┆ 840 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 661 ┆ 661 ┆ C,  ┆ 661 ┆     ┆ an  ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 144 ┆ 793 ┆ 809 ┆ 8-0 ┆ 028 │
│ 5   ┆ 4   ┆ ip- ┆     ┆ ien ┆     ┆     ┆ 3   ┆ P-S ┆ 4   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ und ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 4   ┆ .nc ┆     ┆     ┆ 5   ┆ Emb ┆ t   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 038 ┆ ura ┆     ┆     ┆ 4   ┆ ;42 ┆     ┆ bi. ┆     ┆ P-S ┆ 344 ┆     ┆ vs  ┆ ura ┆ _FI ┆ P-S ┆ HiS ┆ HiS ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 4   ┆ 4_r ┆ cel ┆ 4   ┆     ┆ Emb ┆ err ┆ 4   ┆ ien ┆     ┆ 42  ┆ 3   ┆ 1   ┆ 4   ┆     │
│     ┆     ┆ seq ┆     ┆ s   ┆     ┆     ┆ vs  ┆ eq  ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ er  ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ ryo ┆ sho ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆ vs  ┆ l   ┆     ┆     ┆     ┆ 640 ┆     ┆ ac. ┆     ┆ eq  ┆ 8af ┆     ┆ 141 ┆ l   ┆ LE; ┆ eq  ┆ eq  ┆ eq  ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ ls  ┆ vs  ┆     ┆ ryo ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ SRR ┆ vs  ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ nic ┆ ck  ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆ SAM ┆ pro ┆     ┆     ┆     ┆ 075 ┆     ┆ uk/ ┆     ┆ vs  ┆ 5a6 ┆     ┆ 453 ┆ pro ┆ GEN ┆ vs  ┆ 200 ┆ 200 ┆ uk/ ┆ 141 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ wer ┆ GSM ┆     ┆ nic ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ igg ┆     ┆     ┆     ┆     ┆ 617 ┆ IgG ┆ 281 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 281 ┆ .ni ┆     ┆     ┆ 328 ┆ Ste ┆ con ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 0   ┆ N07 ┆ tei ┆     ┆     ┆     ┆ 9   ┆     ┆ vol ┆     ┆ IgG ┆ 4a4 ┆     ┆ 63  ┆ tei ┆ ERA ┆ IgG ┆ 0   ┆ 0   ┆ vol ┆ 453 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 281 ┆ GSM ┆ e   ┆ 281 ┆     ┆ Ste ┆ l;e ┆     ┆     ┆     ┆     ┆ 617 ┆ 259 ┆     ┆     │
│     ┆     ┆ _ch ┆     ┆     ┆     ┆     ┆ 793 ┆ ChI ┆ 661 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 661 ┆ h.g ┆     ┆     ┆ 855 ┆ m   ┆ dit ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ seq ┆ 790 ┆ ns  ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆ ChI ┆ c38 ┆     ┆     ┆ ns  ┆ TED ┆ ChI ┆     ┆ seq ┆ 1/f ┆ 630 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 661 ┆ 281 ┆ cro ┆ 661 ┆     ┆ m   ┆ nv_ ┆     ┆     ┆     ┆     ┆ 793 ┆ 809 ┆     ┆     │
│     ┆     ┆ ip- ┆     ┆     ┆     ┆     ┆ 2   ┆ P-S ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆ 4   ┆ Cel ┆ ion ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆ uen ┆ 039 ┆ and ┆     ┆     ┆     ┆ 421 ┆     ┆ ast ┆     ┆ P-S ┆ e96 ┆     ┆     ┆ and ┆ _FI ┆ P-S ┆     ┆ uen ┆ ast ┆ 0   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 3   ┆ 661 ┆ ssl ┆ 3   ┆     ┆ Cel ┆ tax ┆     ┆     ┆     ┆     ┆ 2   ┆ 0   ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ l   ┆ s   ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆ cin ┆     ┆ plu ┆     ┆     ┆     ┆ 179 ┆     ┆ q/S ┆     ┆ eq  ┆ 51e ┆     ┆     ┆ plu ┆ LE  ┆ eq  ┆     ┆ cin ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 3_r ┆ ink ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ Lin ┆ vs  ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆ g:  ┆     ┆ rip ┆     ┆     ┆     ┆ 770 ┆     ┆ RR6 ┆     ┆     ┆ 07; ┆     ┆     ┆ rip ┆     ┆     ┆     ┆ g:  ┆ RR6 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ ed  ┆     ┆     ┆ Lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆ e   ┆ und ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆ GSM ┆     ┆ ote ┆     ┆     ┆     ┆ ;43 ┆     ┆ 17/ ┆     ┆     ┆ a94 ┆     ┆     ┆ ote ┆     ┆     ┆     ┆ GSM ┆ 17/ ┆     ┆     ┆     ┆     ┆     ┆ R61 ┆ 213 ┆     ┆     ┆ wit ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆ 281 ┆     ┆ ncy ┆     ┆     ┆     ┆ 527 ┆     ┆ 003 ┆     ┆     ┆ c83 ┆     ┆     ┆ ncy ┆     ┆     ┆     ┆ 281 ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ nor ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆ 661 ┆     ┆ fac ┆     ┆     ┆     ┆ 722 ┆     ┆ /SR ┆     ┆     ┆ 4bc ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 661 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 03/ ┆ 511 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 281 ┆     ┆     ┆     ┆     ┆ mal ┆     ┆ N07 ┆ 288 ┆ 12  ┆     ┆     ┆ 4:  ┆     ┆ tor ┆     ┆     ┆     ┆ 3   ┆     ┆ R61 ┆     ┆     ┆ daa ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ 4:  ┆ R61 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆ con ┆     ┆ 790 ┆ 555 ┆     ┆     ┆     ┆ HS  ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 779 ┆     ┆     ┆ 075 ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ HS  ┆ 779 ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆ dit ┆     ┆ 038 ┆ vs  ┆     ┆     ┆     ┆ IgG ┆     ┆ coo ┆     ┆     ┆     ┆     ┆     ┆ 33/ ┆     ┆     ┆ 7fd ┆     ┆     ┆ coo ┆     ┆     ┆     ┆ IgG ┆ 33/ ┆     ┆     ┆     ┆     ┆     ┆ 793 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM2 ┆     ┆     ┆     ┆     ┆ ion ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ ChI ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ b52 ┆     ┆     ┆ per ┆     ┆     ┆     ┆ ChI ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 3/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 816 ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ P-S ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆     ┆     ┆ aa3 ┆     ┆     ┆ ate ┆     ┆     ┆     ┆ P-S ┆ 617 ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 614 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ eq  ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆ 793 ┆     ┆     ┆ d4d ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ eq  ┆ 793 ┆     ┆     ┆     ┆     ┆     ┆ 177 ┆ 2;7 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ Hom ┆     ┆ orc ┆     ┆     ┆     ┆     ┆     ┆ 3_1 ┆     ┆     ┆ 28d ┆     ┆     ┆ orc ┆     ┆     ┆     ┆ Hom ┆ 3_1 ┆     ┆     ┆     ┆     ┆     ┆ 933 ┆ 776 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ o   ┆     ┆ hes ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ f5  ┆     ┆     ┆ hes ┆     ┆     ┆     ┆ o   ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆ ;11 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆ sap ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆ vs  ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ sap ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 10. GSE112379 (ChIP-seq; Pol II; NELFE)

- [Nascent-protein ubiquitination is required for heat shock–induced gene downregulation in human cells](https://doi.org/10.1038/s41594-018-0182-x)
- Method に以下のような記載がある
- `Heat shock treatment: Unless otherwise stated, heat shock treatment was done by moving tissue-culture plates with growing cells from an incubator at normal growth temperature (37 °C) into an incubator at heat-shock temperatures (43 °C) for 1.5 h. Heat-shock treatment of K562 cells was done for 0.5 h. Heat-shock treatment of HeLa cells was done at 42 °C for the indicated times for activation and attenuation phase experiments29. To explore whether different heat-shock paradigms could influence the results obtained, we also applied acute heat shock, as described51. Briefly, two plates were grown up to 80% confluence. Medium from one of the plates was removed, preheated to 43 °C and added to the other plate from which the medium was withdrawn. The plate was then placed at 43 °C for 1.5 h.`

&nbsp;

### Cycloheximide (chx)

- Translation inhibitor

In [22]:
is_hek  = pl.col("sample_name").str.starts_with("hek_")
is_k562 = pl.col("sample_name").str.starts_with("k562_")
is_hs   = pl.col("sample_name").str.contains("_hs_")
is_nhs  = pl.col("sample_name").str.contains("_nhs_")


GSE112379_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE112379/GSE112379_PEP/GSE112379_PEP_raw.csv",
    separator=','
).filter(
    pl.col("sample_library_strategy") == "ChIP-Seq"
).with_columns(
    pl.lit("https://doi.org/10.1038/s41594-018-0182-x").alias("reference_doi"),
    # HS temperature for heat-shocked samples; NHS controls are marked as ctrl (ATAC-seq GSE101731 pattern)
    pl.when(is_hs).then(pl.lit("43 C"))
      .when(is_nhs).then(pl.lit("ctrl"))
      .otherwise(pl.lit(None))
      .alias("stress treatment temperature"),
    # Duration: HEK 1.5 h (90 min.) vs K562 0.5 h (30 min.); NHS controls are marked as ctrl
    pl.when(is_hek & is_hs).then(pl.lit("90 min."))
      .when(is_k562 & is_hs).then(pl.lit("30 min."))
      .when(is_nhs).then(pl.lit("ctrl"))
      .otherwise(pl.lit(None))
      .alias("stress treatment time"),
    # Normal growth temperature for NHS controls (Methods: 37 C incubator)
    pl.lit("37 C").alias("control treatment temperature"),
    pl.when(is_hek).then(pl.lit("HEK"))
      .when(is_k562).then(pl.lit("K562"))
      .otherwise(pl.lit(None))
      .alias("cell_line"),
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE112379 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE112379.metadata.tsv",
    separator='\t'
)

GSE112379_combined = GSE112379_PEP.join(
    GSE112379,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE112379_combined = GSE112379_combined[[s.name for s in GSE112379_combined if not (s.null_count() == GSE112379_combined.height)]]

display(GSE112379_combined)

shape: (42, 93)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ tre ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ sra ┆ fas ┆ ncb ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ sra ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ atm ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _fi ┆ _as ┆ tq_ ┆ i_r ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _ex ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ent ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ le_ ┆ per ┆ gal ┆ epo ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ tra ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rol ┆ a   ┆ axy ┆ rti ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ ct_ ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ i64 ┆ --- ┆ lat ┆ e   ┆ --- ┆ --- ┆ ng_ ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ pro ┆ ces ┆ _id ┆ nam ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ --- ┆ str ┆ str ┆ sta ┆ ion ┆ str ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ i64 ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ toc ┆ sin ┆ --- ┆ e   ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ str ┆     ┆     ┆ nda ┆ --- ┆     ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ l_c ┆ --- ┆ ol_ ┆ g   ┆ str ┆ --- ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ rd  ┆ str ┆     ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆ ch1 ┆ --- ┆     ┆ str ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ hek ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ HEK ┆ GSM ┆ Pub ┆ Mar ┆ Feb ┆ SRA ┆ 1   ┆ Flp ┆ Hom ┆ 960 ┆ Flp ┆ gen ┆ Cel ┆ ChI ┆ GPL ┆ Bar ┆ Stü ┆ Fre ┆ 791 ┆ Ger ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Cyc ┆ Hea ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 90  ┆ 37  ┆ HEK ┆ Ill ┆ SAM ┆ Nas ┆ SRA ┆ ChI ┆ 201 ┆ 512 ┆ 295 ┆ ILL ┆ ARC ┆ fas ┆ ftp ┆ Gen ┆ HEK ┆ ftp ┆ 1c6 ┆ SRP ┆ 971 ┆ Nas ┆ GEN ┆ HEK ┆ Ill ┆ Ill ┆ f7e ┆ ftp ┆ 145 ┆ ChI ┆ GEN ┆ ftp ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GEO ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ _ch ┆ P   ┆ o   ┆ RED ┆     ┆ 690 ┆ 385 ┆ _CH ┆ 306 ┆ lic ┆ 27  ┆ 07  ┆     ┆     ┆ -In ┆ o   ┆ 6   ┆ -In ┆ omi ┆ ls  ┆ P-s ┆ 212 ┆ bar ┆ bew ┆ ibu ┆ 08  ┆ man ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 306 ┆ :// ┆ 112 ┆     ┆ 385 ┆ loh ┆ t-S ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   ┆     ┆ umi ┆ N08 ┆ cen ┆ 675 ┆ P   ┆ 9-0 ┆ 416 ┆ 852 ┆ UMI ┆ HIV ┆ p.s ┆ .sr ┆ eri ┆ _CH ┆ .sr ┆ cb8 ┆ 136 ┆ 077 ┆ cen ┆ ERA ┆ _CH ┆ umi ┆ umi ┆ 76d ┆ .sr ┆ 661 ┆ P-S ┆ OMI ┆ .sr ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 306 ┆ 306 ┆ ls  ┆ 306 ┆     ┆ _ta ┆ 9-0 ┆ o   ┆ 6   ┆ NA4 ┆ 690 ┆ 309 ┆ 9-0 ┆ 112 │
│ x_h ┆     ┆ sap ┆     ┆     ┆ 413 ┆ 286 ┆ X_H ┆ 895 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ T-R ┆ sap ┆     ┆ T-R ┆ c   ┆ wer ┆ eq  ┆ 90  ┆ a,, ┆ eg  ┆ rg  ┆     ┆ y   ┆ na  ┆     ┆ c   ┆ eq  ┆ 895 ┆ ftp ┆ 379 ┆     ┆ 286 ┆ exi ┆ hoc ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆     ┆     ┆ na  ┆ 800 ┆ t-p ┆ 427 ┆     ┆ 2-1 ┆ 603 ┆ 978 ┆ NA  ┆ AL_ ┆ ra. ┆ a.e ┆ c   ┆ X_H ┆ a.e ┆ 117 ┆ 551 ┆ 37  ┆ t-p ┆ TED ┆ X_H ┆ na  ┆ na  ┆ ab5 ┆ a.e ┆ 605 ┆ eq  ┆ C   ┆ a.e ┆     ┆     ┆ ra. ┆ 67; ┆ 895 ┆ 895 ┆ wer ┆ 895 ┆     ┆ x;e ┆ 2-1 ┆ sap ┆     ┆ 458 ┆ 413 ┆ 700 ┆ 2-1 ┆ 379 │
│ s_r ┆     ┆ ien ┆     ┆     ┆ 3   ┆ 5   ┆ S_R ┆ 8   ┆ Feb ┆ 8   ┆ 9   ┆     ┆     ┆ Ex  ┆ ien ┆     ┆ Ex  ┆ DNA ┆ e   ┆ rea ┆     ┆ Hum ┆ 51  ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 8   ┆ .nc ┆     ┆     ┆ 5   ┆ mid ┆ k   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆     ┆     ┆ HiS ┆ 999 ┆ rot ┆     ┆     ┆ 4   ┆ 9   ┆ 0;3 ┆     ┆ FIL ┆ ebi ┆ bi. ┆     ┆ S_R ┆ bi. ┆ a33 ┆     ┆     ┆ rot ┆ _FI ┆ S_R ┆ HiS ┆ HiS ┆ 35e ┆ bi. ┆ 50  ┆     ┆     ┆ bi. ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ e   ┆ 8   ┆     ┆ nv_ ┆ 4   ┆ ien ┆     ┆ 60  ┆ 3   ┆ 8   ┆ 4   ┆     │
│ pb1 ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ PB1 ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ 293 ┆ s   ┆     ┆ 293 ┆     ┆ fix ┆ ds  ┆     ┆ mel ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ ein ┆     ┆     ┆     ┆     ┆ 766 ┆     ┆ E   ┆ .ac ┆ ac. ┆     ┆ PB1 ┆ ac. ┆ 71c ┆     ┆     ┆ ein ┆ LE; ┆ PB1 ┆ eq  ┆ eq  ┆ 190 ┆ ac. ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ fix ┆     ┆     ┆ tax ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ _ch ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ch ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆ wer ┆     ┆ ed  ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆ 300 ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆     ┆ 300 ┆     ┆ ubi ┆     ┆     ┆     ┆     ┆ 752 ┆     ┆     ┆ .uk ┆ uk/ ┆     ┆ _Ch ┆ uk/ ┆ 563 ┆     ┆     ┆ ubi ┆ GEN ┆ _Ch ┆ 300 ┆ 300 ┆ 915 ┆ uk/ ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ed  ┆     ┆     ┆ :te ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ip_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ IP_ ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ e   ┆     ┆ usi ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ qui ┆     ┆     ┆     ┆     ┆ 113 ┆     ┆     ┆ :/v ┆ vol ┆     ┆ IP_ ┆ vol ┆ 2f3 ┆     ┆     ┆ qui ┆ ERA ┆ IP_ ┆ 0   ┆ 0   ┆ 539 ┆ vol ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ usi ┆     ┆     ┆ rre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆ cul ┆     ┆ ng  ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆     ┆ seq ┆     ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 1/f ┆     ┆ Rep ┆ 1/s ┆ 603 ┆     ┆     ┆ tin ┆ TED ┆ Rep ┆     ┆ seq ┆ 370 ┆ 1/f ┆     ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ ng  ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ tur ┆     ┆ 1%  ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆     ┆     ┆ uen ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sr ┆ ast ┆     ┆ 1   ┆ rr/ ┆ 160 ┆     ┆     ┆ ati ┆ _FI ┆ 1   ┆     ┆ uen ┆ a26 ┆ ast ┆     ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ 1%  ┆     ┆     ┆ ial ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ met ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 594 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r/S ┆ q/S ┆     ┆     ┆ SRR ┆ f47 ┆     ┆     ┆ on  ┆ LE  ┆     ┆     ┆ cin ┆ d8f ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ met ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ han ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ RR6 ┆     ┆     ┆ 690 ┆ 34; ┆     ┆     ┆ is  ┆     ┆     ┆     ┆ g:  ┆ 05  ┆ RR6 ┆     ┆     ┆     ┆ 690 ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ han ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DME ┆     ┆ ol- ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 8-0 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ req ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 90/ ┆ 90/ ┆     ┆     ┆ /00 ┆ 041 ┆     ┆     ┆ req ┆     ┆     ┆     ┆ GSM ┆     ┆ 90/ ┆     ┆     ┆     ┆ /00 ┆     ┆     ┆ R69 ┆ 213 ┆     ┆     ┆ ol- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M   ┆     ┆ fre ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 182 ┆     ┆     ┆     ┆     ┆ 306 ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 003 ┆ 003 ┆     ┆     ┆ 3/S ┆ 505 ┆     ┆     ┆ uir ┆     ┆     ┆     ┆ 306 ┆     ┆ 003 ┆     ┆     ┆     ┆ 3/S ┆     ┆     ┆ 0/0 ┆ ;33 ┆     ┆     ┆ fre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hig ┆     ┆ e   ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ -x  ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ /SR ┆     ┆     ┆ RR6 ┆ 5fc ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ 895 ┆     ┆ /SR ┆     ┆     ┆     ┆ RR6 ┆     ┆     ┆ 03/ ┆ 511 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ for ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 306 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N08 ┆ 852 ┆     ┆     ┆     ┆     ┆     ┆ 8:  ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R69 ┆ R69 ┆     ┆     ┆ 904 ┆ f62 ┆     ┆     ┆ for ┆     ┆     ┆     ┆ 8:  ┆     ┆ R69 ┆     ┆     ┆     ┆ 904 ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Glu ┆     ┆ mal ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 800 ┆ 865 ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 041 ┆ 041 ┆     ┆     ┆ 133 ┆ dc7 ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ HEK ┆     ┆ 041 ┆     ┆     ┆     ┆ 133 ┆     ┆     ┆ 690 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cos ┆     ┆ deh ┆ bui ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ 999 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _CH ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 33/ ┆     ┆     ┆     ┆ 356 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ _CH ┆     ┆ 33/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ yde ┆ ld  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X_H ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆ 931 ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ X_H ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sup ┆     ┆ (CA ┆ hg3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 068 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_R ┆     ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 690 ┆     ┆     ┆     ┆ 6cd ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ S_R ┆     ┆ 690 ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ (CA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ T   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 958 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PB1 ┆     ┆ ind ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆     ┆     ┆     ┆ 02e ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ PB1 ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 904 ┆ 2;7 ┆     ┆     ┆ T   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆ no) ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ch ┆     ┆ uce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3_1 ┆     ┆     ┆     ┆ 7c8 ┆     ┆     ┆ uce ┆     ┆     ┆     ┆ _Ch ┆     ┆ 3_1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 133 ┆ 776 ┆     ┆     ┆ no) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [23]:
defined_pairs_gse112379_chipseq = [

    # pair18_GSE112379_pol2_hs_43C_90min_hek_rpb1.txt
    # pair18_GSE112379_pol2_ctrl_hek_rpb1_chx.txt
    ("SRX3852865", "SRX3852867"), # hek_chx_hs_rpb1_chip_rep1 vs. hek_chx_nhs_rpb1_chip_rep1
    ("SRX3852866", "SRX3852868"), # hek_chx_hs_rpb1_chip_rep2 vs. hek_chx_nhs_rpb1_chip_rep2

    ("SRX3852869", "SRX3852870"), # hek_hs_input vs. hek_nhs_input

    # pair19_GSE112379_pol2_hs_43C_90min_hek_rpb1_scramble.txt
    # pair19_GSE112379_pol2_ctrl_hek_rpb1_scramble.txt
    ("SRX3852871", "SRX3852874"), # hek_scramble_hs_rpb1_chip_rep1 vs. hek_scramble_nhs_rpb1_chip_rep1
    ("SRX3852872", "SRX3852875"), # hek_scramble_hs_rpb1_chip_rep2 vs. hek_scramble_nhs_rpb1_chip_rep2
    ("SRX3852873", "SRX3852876"), # hek_scramble_hs_rpb1_chip_rep3 vs. hek_scramble_nhs_rpb1_chip_rep3

    # sinelfe: silencing NELFE
    # pair20_GSE112379_pol2_hs_43C_90min_hek_rpb1_sinelfe.txt
    # pair20_GSE112379_pol2_ctrl_hek_rpb1_sinelfe.txt
    ("SRX3852877", "SRX3852879"), # hek_sinelfe_hs_rpb1_chip_rep1 vs. hek_sinelfe_nhs_rpb1_chip_rep1
    ("SRX3852878", "SRX3852880"), # hek_sinelfe_hs_rpb1_chip_rep2 vs. hek_sinelfe_nhs_rpb1_chip_rep2


    # ub-e1: Ubiquitin-activating enzyme E1
    # pair21_GSE112379_pol2_hs_43C_90min_hek_rpb1_ub-e1.txt
    # pair21_GSE112379_pol2_ctrl_hek_rpb1_ub-e1.txt
    ("SRX3852881", "SRX3852883"), # hek_ub-e1_hs_rpb1_chip_rep1 vs. hek_ub-e1_nhs_rpb1_chip_rep1
    ("SRX3852882", "SRX3852884"), # hek_ub-e1_hs_rpb1_chip_rep2 vs. hek_ub-e1_nhs_rpb1_chip_rep2


    # vehicle: vehicle control?
    # pair22_GSE112379_pol2_hs_43C_90min_hek_rpb1_vehicle.txt
    # pair22_GSE112379_pol2_ctrl_hek_rpb1_vehicle.txt
    ("SRX3852885", "SRX3852887"), # hek_vehicle_hs_rpb1_chip_rep1 vs. hek_vehicle_nhs_rpb1_chip_rep1
    ("SRX3852886", "SRX3852888"), # hek_vehicle_hs_rpb1_chip_rep2 vs. hek_vehicle_nhs_rpb1_chip_rep2


    ("SRX3852889", "SRX3852896"), # k562_hs_input vs. k562_nhs_input
    ("SRX4643714", "SRX4643712"), # k562_hs_mapk14_chip_rep1 vs. k562_nhs_mapk14_chip_rep1
    ("SRX4643715", "SRX4643713"), # k562_hs_mapk14_chip_rep2 vs. k562_nhs_mapk14_chip_rep2
    ("SRX3852895", "SRX3852897"), # k562_nelfa_hs_chip_rep1 vs. k562_nhs_nelfa_chip_rep1
    ("SRX3852890", "SRX3852898"), # k562_hs_nelfa_chip_rep2 vs. k562_nhs_nelfa_chip_rep2
    ("SRX3852891", "SRX3852899"), # k562_hs_nelfe_chip_rep1 vs. k562_nhs_nelfe_chip_rep1
    ("SRX3852892", "SRX3852900"), # k562_hs_nelfe_chip_rep2 vs. k562_nhs_nelfe_chip_rep2


    # pair23_GSE112379_pol2_hs_43C_30min_k562_rpb1.txt
    # pair23_GSE112379_pol2_ctrl_k562_rpb1.txt
    ("SRX3852893", "SRX3852901"), # k562_hs_rpb1_chip_rep1 vs. k562_nhs_rpb1_chip_rep1
    ("SRX3852894", "SRX3852902")  # k562_hs_rpb1_chip_rep2 vs. k562_nhs_rpb1_chip_rep2
]


paired_metada_df_gse112379 = create_paired_metadata(
    combined_df=GSE112379_combined,
    defined_sample_pairs=defined_pairs_gse112379_chipseq,
    sample_id_column_name="experiment_accession"
)


if paired_metada_df_gse112379 is not None:
    # Keep only heat-side values after pairing (e.g. "90 min. vs ctrl" -> "90 min.")
    paired_metada_df_gse112379 = paired_metada_df_gse112379.with_columns(
        pl.col(["stress treatment temperature", "stress treatment time"])
        .str.strip_suffix(" vs ctrl") # https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.strip_suffix.html
    )
    paired_metada_df_gse112379.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE112379_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse112379)

else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (21, 94)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ tre ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ cel ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ sra ┆ fas ┆ ncb ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ sra ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ atm ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ l_l ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _fi ┆ _as ┆ tq_ ┆ i_r ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _ex ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ent ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ ine ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ le_ ┆ per ┆ gal ┆ epo ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ tra ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ --- ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rol ┆ a   ┆ axy ┆ rti ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ ct_ ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ str ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ e   ┆ --- ┆ --- ┆ ng_ ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ pro ┆ ces ┆ _id ┆ nam ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆     ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ --- ┆ str ┆ str ┆ sta ┆ ion ┆ str ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ toc ┆ sin ┆ --- ┆ e   ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆     ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ str ┆     ┆     ┆ nda ┆ --- ┆     ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ l_c ┆ --- ┆ ol_ ┆ g   ┆ str ┆ --- ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ rd  ┆ str ┆     ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆ ch1 ┆ --- ┆     ┆ str ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hek ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ HEK ┆ GSM ┆ Pub ┆ Mar ┆ Feb ┆ SRA ┆ 1   ┆ Flp ┆ Hom ┆ 960 ┆ Flp ┆ gen ┆ Cel ┆ ChI ┆ GPL ┆ Bar ┆ Stü ┆ Fre ┆ 791 ┆ Ger ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Cyc ┆ Hea ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 90  ┆ 37  ┆ HEK ┆ Ill ┆ SAM ┆ Nas ┆ SRA ┆ ChI ┆ 201 ┆ 512 ┆ 295 ┆ ILL ┆ ARC ┆ fas ┆ ftp ┆ Gen ┆ HEK ┆ ftp ┆ 1c6 ┆ SRP ┆ 971 ┆ Nas ┆ GEN ┆ HEK ┆ Ill ┆ Ill ┆ f7e ┆ ftp ┆ 145 ┆ ChI ┆ GEN ┆ ftp ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GEO ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 385 ┆ 385 ┆ _ch ┆ P   ┆ o   ┆ RED ┆     ┆ 690 ┆ _CH ┆ 306 ┆ lic ┆ 27  ┆ 07  ┆     ┆     ┆ -In ┆ o   ┆ 6   ┆ -In ┆ omi ┆ ls  ┆ P-s ┆ 212 ┆ bar ┆ bew ┆ ibu ┆ 08  ┆ man ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 306 ┆ :// ┆ 112 ┆     ┆ 385 ┆ loh ┆ t-S ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   ┆     ┆ umi ┆ N08 ┆ cen ┆ 675 ┆ P   ┆ 9-0 ┆ 416 ┆ 852 ┆ UMI ┆ HIV ┆ p.s ┆ .sr ┆ eri ┆ _CH ┆ .sr ┆ cb8 ┆ 136 ┆ 077 ┆ cen ┆ ERA ┆ _CH ┆ umi ┆ umi ┆ 76d ┆ .sr ┆ 661 ┆ P-S ┆ OMI ┆ .sr ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 306 ┆ 306 ┆ ls  ┆ 306 ┆     ┆ _ta ┆ 9-0 ┆ o   ┆ 6   ┆ NA4 ┆ 690 ┆ 309 ┆ 9-0 ┆ 112 │
│ 286 ┆ 286 ┆ x_h ┆     ┆ sap ┆     ┆     ┆ 413 ┆ X_H ┆ 895 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ T-R ┆ sap ┆     ┆ T-R ┆ c   ┆ wer ┆ eq  ┆ 90  ┆ a,, ┆ eg  ┆ rg  ┆     ┆ y   ┆ na  ┆     ┆ c   ┆ eq  ┆ 895 ┆ ftp ┆ 379 ┆     ┆ 286 ┆ exi ┆ hoc ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆     ┆     ┆ na  ┆ 800 ┆ t-p ┆ 427 ┆     ┆ 2-1 ┆ 603 ┆ 978 ┆ NA  ┆ AL_ ┆ ra. ┆ a.e ┆ c   ┆ X_H ┆ a.e ┆ 117 ┆ 551 ┆ 37  ┆ t-p ┆ TED ┆ X_H ┆ na  ┆ na  ┆ ab5 ┆ a.e ┆ 605 ┆ eq  ┆ C   ┆ a.e ┆     ┆     ┆ ra. ┆ 67; ┆ 895 ┆ 895 ┆ wer ┆ 895 ┆     ┆ x;e ┆ 2-1 ┆ sap ┆     ┆ 458 ┆ 413 ┆ 700 ┆ 2-1 ┆ 379 │
│ 5   ┆ 7   ┆ s_r ┆     ┆ ien ┆     ┆     ┆ 3   ┆ S_R ┆ 8   ┆ Feb ┆ 8   ┆ 9   ┆     ┆     ┆ Ex  ┆ ien ┆     ┆ Ex  ┆ DNA ┆ e   ┆ rea ┆     ┆ Hum ┆ 51  ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 8   ┆ .nc ┆     ┆     ┆ 5   ┆ mid ┆ k   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆     ┆     ┆ HiS ┆ 999 ┆ rot ┆     ┆     ┆ 4   ┆ 9   ┆ 0;3 ┆     ┆ FIL ┆ ebi ┆ bi. ┆     ┆ S_R ┆ bi. ┆ a33 ┆     ┆ vs  ┆ rot ┆ _FI ┆ S_R ┆ HiS ┆ HiS ┆ 35e ┆ bi. ┆ 50  ┆     ┆     ┆ bi. ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ e   ┆ 8   ┆     ┆ nv_ ┆ 4   ┆ ien ┆     ┆ 60  ┆ 3   ┆ 8   ┆ 4   ┆     │
│     ┆     ┆ pb1 ┆     ┆ s   ┆     ┆     ┆ vs  ┆ PB1 ┆ vs  ┆ 07  ┆     ┆     ┆     ┆     ┆ 293 ┆ s   ┆     ┆ 293 ┆     ┆ fix ┆ ds  ┆     ┆ mel ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ e   ┆ vs  ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆     ┆ eq  ┆ vs  ┆ ein ┆     ┆     ┆     ┆ vs  ┆ 766 ┆     ┆ E   ┆ .ac ┆ ac. ┆     ┆ PB1 ┆ ac. ┆ 71c ┆     ┆ 711 ┆ ein ┆ LE; ┆ PB1 ┆ eq  ┆ eq  ┆ 190 ┆ ac. ┆ vs  ┆     ┆     ┆ ac. ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ fix ┆ vs  ┆     ┆ tax ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ _ch ┆     ┆     ┆     ┆     ┆ SRR ┆ _Ch ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆ wer ┆     ┆ ed  ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆ 300 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ Non ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆     ┆ 300 ┆ SAM ┆ ubi ┆     ┆     ┆     ┆ 375 ┆ 752 ┆     ┆     ┆ .uk ┆ uk/ ┆     ┆ _Ch ┆ uk/ ┆ 563 ┆     ┆ 115 ┆ ubi ┆ GEN ┆ _Ch ┆ 300 ┆ 300 ┆ 915 ┆ uk/ ┆ 106 ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ed  ┆ GSM ┆     ┆ :te ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ ip_ ┆     ┆     ┆     ┆     ┆ 690 ┆ IP_ ┆ 306 ┆ 9   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ e   ┆     ┆ usi ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 306 ┆ .ni ┆     ┆     ┆ 385 ┆     ┆ Hea ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆     ┆ 0   ┆ N08 ┆ qui ┆     ┆     ┆     ┆ 947 ┆ 113 ┆     ┆     ┆ :/v ┆ vol ┆     ┆ IP_ ┆ vol ┆ 2f3 ┆     ┆ 90  ┆ qui ┆ ERA ┆ IP_ ┆ 0   ┆ 0   ┆ 539 ┆ vol ┆ 667 ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 4;3 ┆ 306 ┆ GSM ┆ usi ┆ 306 ┆     ┆ rre ┆     ┆     ┆     ┆     ┆ 690 ┆ 309 ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ 413 ┆ Rep ┆ 896 ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆ cul ┆     ┆ ng  ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 896 ┆ h.g ┆     ┆     ┆ 286 ┆     ┆ t-S ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆     ┆ seq ┆ 800 ┆ tin ┆     ┆     ┆     ┆ 763 ┆ vs  ┆     ┆     ┆ ol1 ┆ 1/f ┆     ┆ Rep ┆ 1/s ┆ 603 ┆     ┆     ┆ tin ┆ TED ┆ Rep ┆     ┆ seq ┆ 370 ┆ 1/f ┆ 385 ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 320 ┆ 896 ┆ 306 ┆ ng  ┆ 896 ┆     ┆ str ┆     ┆     ┆     ┆     ┆ 413 ┆ 701 ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 5   ┆ 1   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ tur ┆     ┆ 1%  ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ov/ ┆     ┆     ┆ 7   ┆     ┆ hoc ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆     ┆     ┆ uen ┆ 996 ┆ ati ┆     ┆     ┆     ┆ 0   ┆ 220 ┆     ┆     ┆ /sr ┆ ast ┆     ┆ 1   ┆ rr/ ┆ 160 ┆     ┆     ┆ ati ┆ _FI ┆ 1   ┆     ┆ uen ┆ a26 ┆ ast ┆ 00  ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 8;6 ┆ 0   ┆ 896 ┆ 1%  ┆ 0   ┆     ┆ ial ┆     ┆     ┆     ┆     ┆ 5   ┆ 1   ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ met ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ k   ┆     ┆ v/b ┆ v/s ┆ 594 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ on  ┆     ┆     ┆     ┆     ┆ 065 ┆     ┆     ┆ r/S ┆ q/S ┆     ┆ vs  ┆ SRR ┆ f47 ┆     ┆     ┆ on  ┆ LE  ┆ vs  ┆     ┆ cin ┆ d8f ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 0_r ┆ met ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hek ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ han ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ is  ┆     ┆     ┆     ┆     ┆ 857 ┆     ┆     ┆ RR6 ┆ RR6 ┆     ┆ HEK ┆ 690 ┆ 34; ┆     ┆     ┆ is  ┆     ┆ HEK ┆     ┆ g:  ┆ 05  ┆ RR6 ┆     ┆     ┆     ┆ 690 ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ han ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ch ┆     ┆     ┆     ┆     ┆     ┆ _CH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DME ┆     ┆ ol- ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 8-0 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ req ┆     ┆     ┆     ┆     ┆ 5;2 ┆     ┆     ┆ 90/ ┆ 90/ ┆     ┆ _CH ┆ /00 ┆ 041 ┆     ┆     ┆ req ┆     ┆ _CH ┆     ┆ GSM ┆ vs  ┆ 90/ ┆     ┆     ┆     ┆ /00 ┆     ┆     ┆ R69 ┆ 213 ┆     ┆     ┆ ol- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ x_n ┆     ┆     ┆     ┆     ┆     ┆ X_N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M   ┆     ┆ fre ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 182 ┆     ┆     ┆     ┆     ┆ 306 ┆     ┆ uir ┆     ┆     ┆     ┆     ┆ 780 ┆     ┆     ┆ 003 ┆ 003 ┆     ┆ X_N ┆ 3/S ┆ 505 ┆     ┆     ┆ uir ┆     ┆ X_N ┆     ┆ 306 ┆ fae ┆ 003 ┆     ┆     ┆     ┆ 3/S ┆     ┆     ┆ 0/0 ┆ ;33 ┆     ┆     ┆ fre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hs_ ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hig ┆     ┆ e   ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ -x  ┆     ┆     ┆     ┆     ┆ 895 ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ 628 ┆     ┆     ┆ /SR ┆ /SR ┆     ┆ HS_ ┆ RR6 ┆ 5fc ┆     ┆     ┆ ed  ┆     ┆ HS_ ┆     ┆ 895 ┆ c2f ┆ /SR ┆     ┆     ┆     ┆ RR6 ┆     ┆     ┆ 03/ ┆ 511 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rpb ┆     ┆     ┆     ┆     ┆     ┆ RPB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ for ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 306 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N08 ┆ 852 ┆     ┆     ┆     ┆     ┆     ┆ 8:  ┆     ┆ for ┆     ┆     ┆     ┆     ┆ 367 ┆     ┆     ┆ R69 ┆ R69 ┆     ┆ RPB ┆ 904 ┆ f62 ┆     ┆     ┆ for ┆     ┆ RPB ┆     ┆ 8:  ┆ 454 ┆ R69 ┆     ┆     ┆     ┆ 904 ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_c ┆     ┆     ┆     ┆     ┆     ┆ 1_C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Glu ┆     ┆ mal ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 800 ┆ 865 ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 041 ┆ 041 ┆     ┆ 1_C ┆ 133 ┆ dc7 ┆     ┆     ┆ hea ┆     ┆ 1_C ┆     ┆ HEK ┆ 721 ┆ 041 ┆     ┆     ┆     ┆ 133 ┆     ┆     ┆ 690 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hip ┆     ┆     ┆     ┆     ┆     ┆ hIP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cos ┆     ┆ deh ┆ bui ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ 999 ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ _CH ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 33/ ┆     ┆ hIP ┆ vs  ┆ 356 ┆     ┆     ┆ t   ┆     ┆ hIP ┆     ┆ _CH ┆ 2d7 ┆ 33/ ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ 413 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆ _Re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ yde ┆ ld  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     ┆     ┆ X_H ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ SRR ┆     ┆ _Re ┆ ftp ┆ 931 ┆     ┆     ┆ sho ┆     ┆ _Re ┆     ┆ X_H ┆ cb7 ┆ SRR ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆ 3/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sup ┆     ┆ (CA ┆ hg3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 068 ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ S_R ┆     ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 690 ┆     ┆ p1  ┆ .sr ┆ 6cd ┆     ┆     ┆ ck- ┆     ┆ p1  ┆     ┆ S_R ┆ b36 ┆ 690 ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ (CA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ T   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 958 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     ┆     ┆ PB1 ┆     ┆ ind ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 413 ┆     ┆     ┆ a.e ┆ 02e ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ PB1 ┆ 6cf ┆ 413 ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆ 904 ┆ 2;7 ┆     ┆     ┆ T   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ men ┆     ┆ no) ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     ┆     ┆ _Ch ┆     ┆ uce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆ 3_1 ┆     ┆     ┆ bi. ┆ 7c8 ┆     ┆     ┆ uce ┆     ┆     ┆     ┆ _Ch ┆ e88 ┆ 3_1 ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆ 133 ┆ 776 ┆     ┆     ┆ no) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 11. GSE121182 (ChIP-seq; CBX8/CBX2)

- [Protein quality control in the nucleolus safeguards recovery of epigenetic regulators after heat shock](https://doi.org/10.7554/eLife.45205)
-

In [24]:
GSE121182_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE121182/GSE121182_PEP/GSE121182_PEP_raw.csv",
    separator=','
).filter(
    pl.col("sample_library_strategy") == "ChIP-Seq"
).with_columns(
    pl.lit("https://doi.org/10.7554/eLife.45205").alias("reference_doi"),
    # GEO treatment protocol: heat shocked for 1 hour at 44 C
    pl.when(pl.col("sample_name").str.ends_with("-hs"))
      .then(pl.lit("44 C"))
      .otherwise(pl.lit("ctrl"))
      .alias("stress treatment temperature"),
    pl.when(pl.col("sample_name").str.ends_with("-hs"))
      .then(pl.lit("60 min."))
      .otherwise(pl.lit("ctrl"))
      .alias("stress treatment time"),
    pl.lit("37 C (inferred)").alias("control treatment temperature")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE121182 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE121182.metadata.tsv",
    separator='\t'
)

GSE121182_combined = GSE121182_PEP.join(
    GSE121182,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE121182_combined = GSE121182_combined[[s.name for s in GSE121182_combined if not (s.null_count() == GSE121182_combined.height)]]

pl.Config.set_tbl_rows(4)
display(GSE121182_combined)

shape: (4, 94)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ ant ┆ tre ┆ cel ┆ gen ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ ibo ┆ atm ┆ l_l ┆ ome ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ dy  ┆ ent ┆ ine ┆ _bu ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ s_c ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ h1  ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ i64 ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ h1  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cbx ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ CBX ┆ GSM ┆ Pub ┆ Oct ┆ Nov ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ sam ┆ Cel ┆ gen ┆ GPL ┆ Joo ┆ joo ┆ 243 ┆ Mol ┆ RIM ┆ Rad ┆ Gee ┆ Nij ┆ Ned ┆ 652 ┆ Net ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ ant ┆ unt ┆ K56 ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ ctr ┆ ctr ┆ 37  ┆ Nex ┆ SAM ┆ Dyn ┆ SRA ┆ ChI ┆ 201 ┆ 127 ┆ ILL ┆ ftp ┆ Gen ┆ CBX ┆ 81e ┆ SRP ┆ 491 ┆ Dyn ┆ GEN ┆ CBX ┆ Nex ┆ Nex ┆ ftp ┆ 412 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Con ┆ GSM ┆ GEO ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 8-u ┆ P   ┆ o   ┆ RED ┆     ┆ 804 ┆ 487 ┆ 8-u ┆ 342 ┆ lic ┆ 12  ┆ 11  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ ple ┆ ls  ┆ omi ┆ 185 ┆ st, ┆ st. ┆ 780 ┆ ecu ┆ LS  ┆ bou ┆ rt  ┆ meg ┆ erl ┆ 5GA ┆ her ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 342 ┆ :// ┆ 121 ┆     ┆ 487 ┆ i-C ┆ rea ┆ 2   ┆ 9   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ l   ┆ l   ┆ C   ┆ tSe ┆ N10 ┆ ami ┆ 793 ┆ P   ┆ 9-0 ┆ 287 ┆ UMI ┆ .sr ┆ eri ┆ 8-u ┆ 036 ┆ 165 ┆ 044 ┆ ami ┆ ERA ┆ 8-u ┆ tSe ┆ tSe ┆ .sr ┆ 477 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 342 ┆ 342 ┆ tro ┆ 342 ┆     ┆ 2   ┆ _ta ┆ 9-0 ┆ o   ┆ 6   ┆ NA4 ┆ 804 ┆ 392 ┆ 9-0 ┆ 121 │
│ ntr ┆     ┆ sap ┆     ┆     ┆ 296 ┆ 274 ┆ ntr ┆ 743 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ col ┆ wer ┆ c   ┆ 73  ┆ ,Ma ┆ mar ┆ 645 ┆ lar ┆     ┆ d   ┆ Gro ┆ en  ┆ and ┆     ┆ lan ┆ na  ┆     ┆ c   ┆ eq  ┆ 743 ┆ ftp ┆ 182 ┆     ┆ 274 ┆ BX8 ┆ ted ┆     ┆     ┆ (bw ┆ //w ┆ //w ┆ //d ┆     ┆     ┆ (in ┆ q   ┆ 236 ┆ c   ┆ 600 ┆     ┆ 6-0 ┆ 103 ┆ NA  ┆ a.e ┆ c   ┆ ntr ┆ dc6 ┆ 293 ┆ 4   ┆ c   ┆ TED ┆ ntr ┆ q   ┆ q   ┆ a.e ┆ 296 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 743 ┆ 743 ┆ l   ┆ 743 ┆     ┆     ┆ x:t ┆ 6-0 ┆ sap ┆     ┆ 960 ┆ 296 ┆ 767 ┆ 6-0 ┆ 182 │
│ eat ┆     ┆ ien ┆     ┆     ┆ 7   ┆ 2   ┆ eat ┆ 8   ┆ May ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ lec ┆ e   ┆ DNA ┆     ┆ rte ┆ ten ┆     ┆ Bio ┆     ┆ Uni ┆ ote ┆     ┆     ┆     ┆ ds  ┆ Nex ┆     ┆     ┆     ┆ 8   ┆ .nc ┆     ┆     ┆ 2   ┆ (C1 ┆     ┆     ┆     ┆ )   ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer ┆ 500 ┆ 330 ┆ beh ┆     ┆     ┆ 1   ┆ ;13 ┆     ┆ bi. ┆     ┆ eat ┆ c99 ┆     ┆     ┆ beh ┆ _FI ┆ eat ┆ 500 ┆ 500 ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ and ┆ 8   ┆     ┆     ┆ err ┆ 1   ┆ ien ┆     ┆ 26  ┆ 7   ┆ 1   ┆ 1   ┆     │
│ ed  ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tio ┆ hea ┆     ┆     ┆ ns  ┆ s@r ┆     ┆ log ┆     ┆ ver ┆ ple ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆ 541 ┆     ┆     ┆     ┆ fil ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red ┆ seq ┆     ┆ avi ┆     ┆     ┆     ┆ 274 ┆     ┆ ac. ┆     ┆ ed  ┆ 07c ┆     ┆     ┆ avi ┆ LE; ┆ ed  ┆     ┆ seq ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ HS  ┆     ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ t   ┆     ┆     ┆     ┆ u.n ┆     ┆ y   ┆     ┆ sit ┆ in  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆ 033 ┆     ┆     ┆     ┆ es  ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   ┆ uen ┆     ┆ or  ┆     ┆     ┆     ┆ 988 ┆     ┆ uk/ ┆     ┆     ┆ 99a ┆     ┆     ┆ or  ┆ GEN ┆     ┆     ┆ uen ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (da ┆ sho ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ y   ┆ 28  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆ 3,  ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .75 ┆     ┆     ┆     ┆ cin ┆     ┆ of  ┆     ┆     ┆     ┆ 3   ┆     ┆ vol ┆     ┆     ┆ 5f6 ┆     ┆     ┆ of  ┆ ERA ┆     ┆     ┆ cin ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y): ┆ cke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆ Dia ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 54/ ┆     ┆     ┆     ┆ g:  ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 184 ┆     ┆     ┆ the ┆ TED ┆     ┆     ┆ g:  ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ eLi ┆     ┆     ┆     ┆ GSM ┆     ┆ epi ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 9e4 ┆     ┆     ┆ epi ┆ _FI ┆     ┆     ┆ GSM ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ ode ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ fe. ┆     ┆     ┆     ┆ 342 ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 617 ┆     ┆     ┆ gen ┆ LE  ┆     ┆     ┆ 342 ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 452 ┆     ┆     ┆     ┆ 743 ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆ RR8 ┆     ┆     ┆ c4; ┆     ┆     ┆ eti ┆     ┆     ┆     ┆ 743 ┆ RR8 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 05  ┆     ┆     ┆     ┆ 8:  ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆ 04/ ┆     ┆     ┆ 005 ┆     ┆     ┆ c   ┆     ┆     ┆     ┆ 8:  ┆ 04/ ┆     ┆     ┆     ┆     ┆     ┆ R80 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆     ┆     ┆     ┆     ┆ CBX ┆     ┆ mac ┆     ┆     ┆     ┆     ┆     ┆ 007 ┆     ┆     ┆ a9c ┆     ┆     ┆ mac ┆     ┆     ┆     ┆ CBX ┆ 007 ┆     ┆     ┆     ┆     ┆     ┆ 4/0 ┆ ;33 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX4 ┆     ┆     ┆     ┆     ┆ 8-u ┆     ┆ hin ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 742 ┆     ┆     ┆ hin ┆     ┆     ┆     ┆ 8-u ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 07/ ┆ 511 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 342 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N10 ┆ 872 ┆     ┆     ┆     ┆     ┆ ntr ┆     ┆ ery ┆     ┆     ┆     ┆     ┆     ┆ R80 ┆     ┆     ┆ ae5 ┆     ┆     ┆ ery ┆     ┆     ┆     ┆ ntr ┆ R80 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 236 ┆ 742 ┆     ┆     ┆     ┆     ┆ eat ┆     ┆ upo ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     ┆     ┆ 039 ┆     ┆     ┆ upo ┆     ┆     ┆     ┆ eat ┆ 429 ┆     ┆     ┆     ┆     ┆     ┆ 804 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 330 ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆ 67/ ┆     ┆     ┆ 440 ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ ed  ┆ 67/ ┆     ┆     ┆     ┆     ┆     ┆ 296 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ e7a ┆     ┆     ┆ the ┆     ┆     ┆     ┆ Hom ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 7/S ┆ 93; ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [25]:
defined_pairs_gse121182_chipseq = [
    ("SRX4872743", "SRX4872742"), # cbx8-hs vs. cbx8-untreated
    ("SRX4872745", "SRX4872744")  # gfp-cbx2-hs vs. gfp-cbx2-untreated
]

paired_metada_df_gse121182 = create_paired_metadata(
    combined_df=GSE121182_combined,
    defined_sample_pairs=defined_pairs_gse121182_chipseq,
    sample_id_column_name="experiment_accession"
)


if paired_metada_df_gse121182 is not None:
    paired_metada_df_gse121182 = paired_metada_df_gse121182.with_columns(
        pl.col(["stress treatment temperature", "stress treatment time"])
        .str.strip_suffix(" vs ctrl")
    )
    paired_metada_df_gse121182.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE121182_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse121182)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 95)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ ant ┆ tre ┆ cel ┆ gen ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ ibo ┆ atm ┆ l_l ┆ ome ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ dy  ┆ ent ┆ ine ┆ _bu ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ s_c ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ h1  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ cbx ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ CBX ┆ GSM ┆ Pub ┆ Oct ┆ Nov ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ sam ┆ Cel ┆ gen ┆ GPL ┆ Joo ┆ joo ┆ 243 ┆ Mol ┆ RIM ┆ Rad ┆ Gee ┆ Nij ┆ Ned ┆ 652 ┆ Net ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ ant ┆ 1h, ┆ K56 ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 44  ┆ 60  ┆ 37  ┆ Nex ┆ SAM ┆ Dyn ┆ SRA ┆ ChI ┆ 201 ┆ 113 ┆ ILL ┆ ftp ┆ Gen ┆ CBX ┆ 8a3 ┆ SRP ┆ 443 ┆ Dyn ┆ GEN ┆ CBX ┆ Nex ┆ Nex ┆ ftp ┆ 372 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Con ┆ GSM ┆ GEO ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 487 ┆ 487 ┆ 8-h ┆ P   ┆ o   ┆ RED ┆     ┆ 804 ┆ 8-H ┆ 342 ┆ lic ┆ 12  ┆ 11  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ ple ┆ ls  ┆ omi ┆ 185 ┆ st, ┆ st. ┆ 780 ┆ ecu ┆ LS  ┆ bou ┆ rt  ┆ meg ┆ erl ┆ 5GA ┆ her ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 342 ┆ :// ┆ 121 ┆     ┆ 487 ┆ i-C ┆ 44C ┆ 2   ┆ 9   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   ┆ tSe ┆ N10 ┆ ami ┆ 793 ┆ P   ┆ 9-0 ┆ 250 ┆ UMI ┆ .sr ┆ eri ┆ 8-H ┆ e3e ┆ 165 ┆ 959 ┆ ami ┆ ERA ┆ 8-H ┆ tSe ┆ tSe ┆ .sr ┆ 925 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 342 ┆ 342 ┆ tro ┆ 342 ┆     ┆ 2   ┆ _ta ┆ 9-0 ┆ o   ┆ 6   ┆ NA4 ┆ 804 ┆ 392 ┆ 9-0 ┆ 121 │
│ 274 ┆ 274 ┆ s   ┆     ┆ sap ┆     ┆     ┆ 296 ┆ S   ┆ 743 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ col ┆ wer ┆ c   ┆ 73  ┆ ,Ma ┆ mar ┆ 645 ┆ lar ┆     ┆ d   ┆ Gro ┆ en  ┆ and ┆     ┆ lan ┆ na  ┆     ┆ c   ┆ eq  ┆ 743 ┆ ftp ┆ 182 ┆     ┆ 274 ┆ BX8 ┆ vs  ┆     ┆     ┆ (bw ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in ┆ q   ┆ 236 ┆ c   ┆ 600 ┆     ┆ 6-0 ┆ 766 ┆ NA  ┆ a.e ┆ c   ┆ S   ┆ 647 ┆ 293 ┆ 1   ┆ c   ┆ TED ┆ S   ┆ q   ┆ q   ┆ a.e ┆ 644 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 743 ┆ 743 ┆ l   ┆ 743 ┆     ┆     ┆ x:t ┆ 6-0 ┆ sap ┆     ┆ 960 ┆ 296 ┆ 767 ┆ 6-0 ┆ 182 │
│ 3   ┆ 2   ┆ vs  ┆     ┆ ien ┆     ┆     ┆ 8   ┆ vs  ┆ 9   ┆ May ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ lec ┆ e   ┆ DNA ┆     ┆ rte ┆ ten ┆     ┆ Bio ┆     ┆ Uni ┆ ote ┆     ┆     ┆     ┆ ds  ┆ Nex ┆     ┆     ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 3   ┆ (C1 ┆ unt ┆     ┆     ┆ )   ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer ┆ 500 ┆ 329 ┆ beh ┆     ┆     ┆ 1   ┆ ;11 ┆     ┆ bi. ┆     ┆ vs  ┆ b48 ┆     ┆ vs  ┆ beh ┆ _FI ┆ vs  ┆ 500 ┆ 500 ┆ bi. ┆ vs  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 9   ┆ 9_r ┆ and ┆ 9   ┆     ┆     ┆ err ┆ 1   ┆ ien ┆     ┆ 26  ┆ 8   ┆ 2   ┆ 1   ┆     │
│     ┆     ┆ cbx ┆     ┆ s   ┆     ┆     ┆ vs  ┆ CBX ┆ vs  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tio ┆ hea ┆     ┆     ┆ ns  ┆ s@r ┆     ┆ log ┆     ┆ ver ┆ ple ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ 541 ┆ rea ┆     ┆     ┆ fil ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red ┆ seq ┆ vs  ┆ avi ┆     ┆     ┆     ┆ 952 ┆     ┆ ac. ┆     ┆ CBX ┆ 470 ┆     ┆ 491 ┆ avi ┆ LE; ┆ CBX ┆     ┆ seq ┆ ac. ┆ 412 ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ HS  ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ 8-u ┆     ┆     ┆     ┆     ┆ SRR ┆ 8-u ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆ t   ┆     ┆     ┆     ┆ u.n ┆     ┆ y   ┆     ┆ sit ┆ in  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ 033 ┆ ted ┆     ┆     ┆ es  ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   ┆ uen ┆ SAM ┆ or  ┆     ┆     ┆     ┆ 960 ┆     ┆ uk/ ┆     ┆ 8-u ┆ 94d ┆     ┆ 044 ┆ or  ┆ GEN ┆ 8-u ┆     ┆ uen ┆ uk/ ┆ 477 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ K56 ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ ntr ┆     ┆     ┆     ┆     ┆ 804 ┆ ntr ┆ 342 ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (da ┆ sho ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ y   ┆ 28  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 342 ┆ .ni ┆     ┆     ┆ 487 ┆ 3,  ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .75 ┆     ┆     ┆     ┆ cin ┆ N10 ┆ of  ┆     ┆     ┆     ┆ 4   ┆     ┆ vol ┆     ┆ ntr ┆ a76 ┆     ┆ 4   ┆ of  ┆ ERA ┆ ntr ┆     ┆ cin ┆ vol ┆ 296 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 342 ┆ GSM ┆ 2   ┆ 342 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 804 ┆ 392 ┆     ┆     │
│     ┆     ┆ eat ┆     ┆     ┆     ┆     ┆ 296 ┆ eat ┆ 743 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y): ┆ cke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 743 ┆ h.g ┆     ┆     ┆ 274 ┆ Dia ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 54/ ┆     ┆     ┆     ┆ g:  ┆ 236 ┆ the ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆ eat ┆ 82a ┆     ┆     ┆ the ┆ TED ┆ eat ┆     ┆ g:  ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 743 ┆ 342 ┆ cel ┆ 743 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 296 ┆ 767 ┆     ┆     │
│     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ 7   ┆ ed  ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ ov/ ┆     ┆     ┆ 2   ┆ gen ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ eLi ┆     ┆     ┆     ┆ GSM ┆ 330 ┆ epi ┆     ┆     ┆     ┆ 127 ┆     ┆ ast ┆     ┆ ed  ┆ ce1 ┆     ┆     ┆ epi ┆ _FI ┆ ed  ┆     ┆ GSM ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 8   ┆ 743 ┆ ls  ┆ 8   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 7   ┆ 1   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ ode ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ fe. ┆     ┆     ┆     ┆ 342 ┆     ┆ gen ┆     ┆     ┆     ┆ 287 ┆     ┆ q/S ┆     ┆     ┆ 747 ┆     ┆     ┆ gen ┆ LE  ┆     ┆     ┆ 342 ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 8_r ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 452 ┆     ┆     ┆     ┆ 743 ┆     ┆ eti ┆     ┆     ┆     ┆ 103 ┆     ┆ RR8 ┆     ┆     ┆ f6; ┆     ┆     ┆ eti ┆     ┆     ┆     ┆ 743 ┆ RR8 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 05  ┆     ┆     ┆     ┆ 9:  ┆     ┆ c   ┆     ┆     ┆     ┆ ;13 ┆     ┆ 04/ ┆     ┆     ┆ 4f7 ┆     ┆     ┆ c   ┆     ┆     ┆     ┆ 9:  ┆ 04/ ┆     ┆     ┆     ┆     ┆     ┆ R80 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆     ┆     ┆     ┆     ┆ CBX ┆     ┆ mac ┆     ┆     ┆     ┆ 274 ┆     ┆ 008 ┆     ┆     ┆ 823 ┆     ┆     ┆ mac ┆     ┆     ┆     ┆ CBX ┆ 008 ┆     ┆     ┆     ┆     ┆     ┆ 4/0 ┆ ;33 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX4 ┆     ┆     ┆     ┆     ┆ 8-H ┆     ┆ hin ┆     ┆     ┆     ┆ 988 ┆     ┆ /SR ┆     ┆     ┆ 7d5 ┆     ┆     ┆ hin ┆     ┆     ┆     ┆ 8-H ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 08/ ┆ 511 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 342 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N10 ┆ 872 ┆     ┆     ┆     ┆     ┆ S   ┆     ┆ ery ┆     ┆     ┆     ┆ 3   ┆     ┆ R80 ┆     ┆     ┆ cba ┆     ┆     ┆ ery ┆     ┆     ┆     ┆ S   ┆ R80 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 236 ┆ 743 ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ upo ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     ┆     ┆ c20 ┆     ┆     ┆ upo ┆     ┆     ┆     ┆ Hom ┆ 429 ┆     ┆     ┆     ┆     ┆     ┆ 804 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 329 ┆ vs  ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆ 68/ ┆     ┆     ┆ 772 ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ o   ┆ 68/ ┆     ┆     ┆     ┆     ┆     ┆ 296 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 12. GSE137558 (ChIP-seq; HSF1)

- [17β-Estradiol Activates HSF1 via MAPK Signaling in ERα-Positive Breast Cancer Cells](https://doi.org/10.3390/cancers11101533)
-

In [26]:
GSE137558_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE137558/GSE137558_PEP/GSE137558_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (~pl.col("sample_name").str.contains("estrogen")) &
    (~pl.col("sample_name").str.contains("_input_"))
).with_columns(
    pl.lit("https://doi.org/10.3390/cancers11101533").alias("reference_doi"),
    pl.lit("43 C").alias("stress treatment temperature"),
    pl.lit("15 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE137558 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE137558.metadata.tsv",
    separator='\t'
)

GSE137558_combined = GSE137558_PEP.join(
    GSE137558,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE137558_combined = GSE137558_combined[[s.name for s in GSE137558_combined if not (s.null_count() == GSE137558_combined.height)]]

pl.Config.set_tbl_rows(5)
display(GSE137558_combined)

shape: (2, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ tum ┆ sex ┆ age ┆ tis ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ or  ┆ --- ┆ --- ┆ sue ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ --- ┆ str ┆ str ┆ _ce ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ str ┆     ┆     ┆ lls ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ i64 ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ chi ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ ChI ┆ GSM ┆ Pub ┆ Sep ┆ Oct ┆ SRA ┆ 1   ┆ unt ┆ Hom ┆ 960 ┆ gen ┆ unt ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ ade ┆ fem ┆ 69  ┆ bre ┆ HSF ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 15  ┆ Ill ┆ SAM ┆ Hea ┆ SRA ┆ ChI ┆ 201 ┆ 155 ┆ ILL ┆ ftp ┆ Gen ┆ ChI ┆ bad ┆ SRP ┆ 403 ┆ Hea ┆ GEN ┆ ChI ┆ Ill ┆ Ill ┆ ftp ┆ 260 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ At  ┆ GSM ┆ GEO ┆ MCF ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ p-s ┆ P   ┆ o   ┆ GLE ┆     ┆ 101 ┆ 685 ┆ P-s ┆ 408 ┆ lic ┆ 17  ┆ 05  ┆     ┆     ┆ rea ┆ o   ┆ 6   ┆ omi ┆ rea ┆ 184 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 408 ┆ E   ┆ 137 ┆     ┆ 685 ┆ 7   ┆ noc ┆ ale ┆ yea ┆ ast ┆ 1   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N12 ┆ t   ┆ 963 ┆ P   ┆ 9-1 ┆ 155 ┆ UMI ┆ .sr ┆ eri ┆ P-s ┆ 77e ┆ 221 ┆ 587 ┆ t   ┆ ERA ┆ P-s ┆ umi ┆ umi ┆ .sr ┆ 341 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 408 ┆ 408 ┆ the ┆ 408 ┆     ┆ 7   ┆ _ta ┆ 9-1 ┆ o   ┆ 6   ┆ NA5 ┆ 101 ┆ 539 ┆ 9-1 ┆ 137 │
│ eq_ ┆     ┆ sap ┆     ┆     ┆ 298 ┆ 824 ┆ eq_ ┆ 175 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ted ┆ sap ┆     ┆ c   ┆ ted ┆ 60  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 175 ┆     ┆ 558 ┆     ┆ 824 ┆     ┆ arc ┆     ┆ rs  ┆     ┆ pol ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 771 ┆ Sho ┆ 112 ┆     ┆ 0-0 ┆ 075 ┆ NA  ┆ a.e ┆ c   ┆ eq_ ┆ c99 ┆ 988 ┆ 92  ┆ Sho ┆ TED ┆ eq_ ┆ na  ┆ na  ┆ a.e ┆ 881 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 175 ┆ 175 ┆ app ┆ 175 ┆     ┆     ┆ x:t ┆ 0-0 ┆ sap ┆     ┆ 659 ┆ 298 ┆ 603 ┆ 0-0 ┆ 558 │
│ con ┆     ┆ ien ┆     ┆     ┆ 34  ┆ 7   ┆ con ┆ 9   ┆ Oct ┆ 9   ┆ 9   ┆     ┆     ┆ con ┆ ien ┆     ┆ DNA ┆ con ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 9   ┆     ┆ ,   ┆     ┆ 7   ┆     ┆ ino ┆     ┆     ┆     ┆ ycl ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 835 ┆ ck  ┆     ┆     ┆ 7   ┆ 9   ┆     ┆ bi. ┆     ┆ con ┆ df7 ┆     ┆     ┆ ck  ┆ _FI ┆ con ┆ HiS ┆ HiS ┆ bi. ┆ 5   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 9   ┆ 9_r ┆ oin ┆ 9   ┆     ┆     ┆ err ┆ 7   ┆ ien ┆     ┆ 26  ┆ 34  ┆ 1   ┆ 7   ┆     │
│ tro ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ 05  ┆     ┆     ┆     ┆     ┆ tro ┆ s   ┆     ┆     ┆ tro ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆ GSE ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆ ona ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆     ┆ Fac ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆ tro ┆ 4ad ┆     ┆     ┆ Fac ┆ LE  ┆ tro ┆ eq  ┆ eq  ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ ted ┆     ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ 150 ┆     ┆     ┆     ┆     ┆     ┆ 137 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 150 ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆ l   ┆ 602 ┆     ┆     ┆ tor ┆     ┆ l   ┆ 150 ┆ 150 ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ exp ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ 560 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ant ┆     ┆ lm. ┆ lm. ┆ .33 ┆     ┆     ┆ 0   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ 39e ┆     ┆     ┆ 1   ┆     ┆     ┆ 0   ┆ 0   ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ eri ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ibo ┆     ┆ nih ┆ nih ┆ 90/ ┆     ┆     ┆ seq ┆     ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 89a ┆     ┆     ┆ (HS ┆     ┆     ┆     ┆ seq ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ men ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dy  ┆     ┆ .go ┆ .go ┆ can ┆     ┆     ┆ uen ┆     ┆ F1) ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ e90 ┆     ┆     ┆ F1) ┆     ┆     ┆     ┆ uen ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ tal ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (En ┆     ┆ v/b ┆ v/s ┆ cer ┆     ┆     ┆ cin ┆     ┆ acq ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 453 ┆     ┆     ┆ acq ┆     ┆     ┆     ┆ cin ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ poi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zo, ┆     ┆ ios ┆ ra? ┆ s11 ┆     ┆     ┆ g:  ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 25  ┆     ┆     ┆ uir ┆     ┆     ┆     ┆ g:  ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ nts ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ADI ┆     ┆ amp ┆ ter ┆ 101 ┆     ┆     ┆ GSM ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆ 01/ ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ GSM ┆ 01/ ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆ 213 ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -SP ┆     ┆ le/ ┆ m=S ┆ 533 ┆     ┆     ┆ 408 ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ 034 ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ 408 ┆ 034 ┆     ┆     ┆     ┆     ┆     ┆ 1/0 ┆ ;33 ┆     ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-9 ┆     ┆ SAM ┆ RX6 ┆     ┆     ┆     ┆ 175 ┆     ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ nsc ┆     ┆     ┆     ┆ 175 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 34/ ┆ 511 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01) ┆     ┆ N12 ┆ 858 ┆     ┆     ┆     ┆ 9:  ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆ 9:  ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 771 ┆ 247 ┆     ┆     ┆     ┆ ChI ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ ChI ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆ 11; ┆     ┆     ┆ ium ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 835 ┆     ┆     ┆     ┆     ┆ P-s ┆     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆ nal ┆     ┆     ┆     ┆ P-s ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 895 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq_ ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆ eq_ ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 34/ ┆ 93; ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ pet ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ pet ┆     ┆     ┆     ┆ con ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ enc ┆     ┆     ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ enc ┆     ┆     ┆     ┆ tro ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆ 2;7 ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ l   ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 776 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆ Hom ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ 34. ┆ ;11 ┆     ┆     ┆ fix ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [27]:
defined_pairs_gse137558_chipseq = [
    ("SRX6858250", "SRX6858247")  # chip-seq_hyperthermia_15min vs. chip-seq_control
]

paired_metada_df_gse137558 = create_paired_metadata(
    combined_df=GSE137558_combined,
    defined_sample_pairs=defined_pairs_gse137558_chipseq,
    sample_id_column_name="experiment_accession"
)


if paired_metada_df_gse137558 is not None:
    paired_metada_df_gse137558.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE137558_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse137558)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 93)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ tum ┆ sex ┆ age ┆ tis ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ or  ┆ --- ┆ --- ┆ sue ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ --- ┆ str ┆ str ┆ _ce ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ str ┆     ┆     ┆ lls ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ chi ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ ChI ┆ GSM ┆ Pub ┆ Sep ┆ Oct ┆ SRA ┆ 1   ┆ sub ┆ Hom ┆ 960 ┆ gen ┆ sub ┆ GPL ┆ Tom ┆ tom ┆ Sci ┆ IT  ┆ Uni ┆ Nyg ┆ Ber ┆ 502 ┆ Nor ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ ade ┆ fem ┆ 69  ┆ bre ┆ HSF ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 15  ┆ Ill ┆ SAM ┆ Hea ┆ SRA ┆ ChI ┆ 201 ┆ 176 ┆ ILL ┆ ftp ┆ Gen ┆ ChI ┆ f1c ┆ SRP ┆ 458 ┆ Hea ┆ GEN ┆ ChI ┆ Ill ┆ Ill ┆ ftp ┆ 295 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ At  ┆ GSM ┆ GEO ┆ MCF ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 685 ┆ 685 ┆ p-s ┆ P   ┆ o   ┆ GLE ┆     ┆ 101 ┆ P-s ┆ 408 ┆ lic ┆ 17  ┆ 05  ┆     ┆     ┆ jec ┆ o   ┆ 6   ┆ omi ┆ jec ┆ 184 ┆ asz ┆ asz ┆ ent ┆ Div ┆ ver ┆ ard ┆ gen ┆ 0   ┆ way ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 408 ┆ :// ┆ 137 ┆     ┆ 685 ┆ 7   ┆ noc ┆ ale ┆ yea ┆ ast ┆ 1   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N12 ┆ t   ┆ 963 ┆ P   ┆ 9-1 ┆ 064 ┆ UMI ┆ .sr ┆ eri ┆ P-s ┆ 8f0 ┆ 221 ┆ 499 ┆ t   ┆ ERA ┆ P-s ┆ umi ┆ umi ┆ .sr ┆ 772 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 408 ┆ 408 ┆ the ┆ 408 ┆     ┆ 7   ┆ _ta ┆ 9-1 ┆ o   ┆ 6   ┆ NA5 ┆ 101 ┆ 539 ┆ 9-1 ┆ 137 │
│ 825 ┆ 824 ┆ eq_ ┆     ┆ sap ┆     ┆     ┆ 298 ┆ eq_ ┆ 176 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ ted ┆ sap ┆     ┆ c   ┆ ted ┆ 60  ┆ ,,S ┆ .st ┆ ifi ┆ isi ┆ sit ┆ sga ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 176 ┆ ftp ┆ 558 ┆     ┆ 825 ┆     ┆ arc ┆     ┆ rs  ┆     ┆ pol ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 771 ┆ Sho ┆ 112 ┆     ┆ 0-0 ┆ 552 ┆ NA  ┆ a.e ┆ c   ┆ eq_ ┆ 928 ┆ 988 ┆ 53  ┆ Sho ┆ TED ┆ eq_ ┆ na  ┆ na  ┆ a.e ┆ 832 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 176 ┆ 176 ┆ app ┆ 176 ┆     ┆     ┆ x:t ┆ 0-0 ┆ sap ┆     ┆ 659 ┆ 298 ┆ 603 ┆ 0-0 ┆ 558 │
│ 0   ┆ 7   ┆ hyp ┆     ┆ ien ┆     ┆     ┆ 37  ┆ hyp ┆ 2   ┆ Oct ┆ 9   ┆ 9   ┆     ┆     ┆ to  ┆ ien ┆     ┆ DNA ┆ to  ┆     ┆ tok ┆ oko ┆ c   ┆ on  ┆ y   ┆ ten ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 2   ┆ .nc ┆ ,   ┆     ┆ 0   ┆     ┆ ino ┆     ┆     ┆     ┆ ycl ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 833 ┆ ck  ┆     ┆     ┆ 7   ┆ 6   ┆     ┆ bi. ┆     ┆ hyp ┆ bf2 ┆     ┆ vs  ┆ ck  ┆ _FI ┆ hyp ┆ HiS ┆ HiS ┆ bi. ┆ 6   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 2   ┆ 2_r ┆ oin ┆ 2   ┆     ┆     ┆ err ┆ 7   ┆ ien ┆     ┆ 26  ┆ 37  ┆ 4   ┆ 7   ┆     │
│     ┆     ┆ ert ┆     ┆ s   ┆     ┆     ┆ vs  ┆ ert ┆ vs  ┆ 05  ┆     ┆     ┆     ┆     ┆ hyp ┆ s   ┆     ┆     ┆ hyp ┆     ┆ owy ┆ wy@ ┆ Com ┆     ┆ of  ┆ 5   ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆ ma  ┆     ┆     ┆     ┆ ona ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆ vs  ┆ Fac ┆     ┆     ┆     ┆ vs  ┆     ┆ ac. ┆     ┆ ert ┆ fe4 ┆     ┆ 403 ┆ Fac ┆ LE  ┆ ert ┆ eq  ┆ eq  ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ ted ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ her ┆     ┆     ┆     ┆     ┆ SRR ┆ her ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ ert ┆     ┆     ┆     ┆ ert ┆     ┆     ┆ uib ┆ put ┆     ┆ Ber ┆     ┆     ┆     ┆     ┆ 150 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 137 ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 150 ┆ SAM ┆ tor ┆     ┆     ┆     ┆ 155 ┆     ┆ uk/ ┆     ┆ her ┆ b57 ┆     ┆ 587 ┆ tor ┆     ┆ her ┆ 150 ┆ 150 ┆ uk/ ┆ 260 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ exp ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ mia ┆     ┆     ┆     ┆     ┆ 101 ┆ mia ┆ 408 ┆ 9   ┆     ┆     ┆     ┆     ┆ her ┆     ┆     ┆     ┆ her ┆     ┆     ┆ .no ┆ ing ┆     ┆ gen ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 408 ┆ .ni ┆ 560 ┆     ┆ 685 ┆     ┆     ┆     ┆     ┆     ┆ ant ┆     ┆ lm. ┆ lm. ┆ .33 ┆     ┆     ┆ 0   ┆ N12 ┆ 1   ┆     ┆     ┆     ┆ 155 ┆     ┆ vol ┆     ┆ mia ┆ 516 ┆     ┆ 92  ┆ 1   ┆     ┆ mia ┆ 0   ┆ 0   ┆ vol ┆ 341 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 408 ┆ GSM ┆ eri ┆ 408 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 101 ┆ 539 ┆     ┆     │
│     ┆     ┆ _15 ┆     ┆     ┆     ┆     ┆ 298 ┆ _15 ┆ 175 ┆     ┆     ┆     ┆     ┆     ┆ mia ┆     ┆     ┆     ┆ mia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 175 ┆ h.g ┆     ┆     ┆ 824 ┆     ┆     ┆     ┆     ┆     ┆ ibo ┆     ┆ nih ┆ nih ┆ 90/ ┆     ┆     ┆ seq ┆ 771 ┆ (HS ┆     ┆     ┆     ┆ 075 ┆     ┆ 1/f ┆     ┆ _15 ┆ a26 ┆     ┆     ┆ (HS ┆     ┆ _15 ┆     ┆ seq ┆ 1/f ┆ 881 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 175 ┆ 408 ┆ men ┆ 175 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 298 ┆ 603 ┆     ┆     │
│     ┆     ┆ min ┆     ┆     ┆     ┆     ┆ 34  ┆ min ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ (43 ┆     ┆     ┆     ┆ (43 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ ov/ ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ dy  ┆     ┆ .go ┆ .go ┆ can ┆     ┆     ┆ uen ┆ 835 ┆ F1) ┆     ┆     ┆     ┆ 9   ┆     ┆ ast ┆     ┆ min ┆ 444 ┆     ┆     ┆ F1) ┆     ┆ min ┆     ┆ uen ┆ ast ┆ 5   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 9   ┆ 175 ┆ tal ┆ 9   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 34  ┆ 1   ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ °C) ┆     ┆     ┆     ┆ °C) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (En ┆     ┆ v/b ┆ v/s ┆ cer ┆     ┆     ┆ cin ┆     ┆ acq ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆ vs  ┆ 3c3 ┆     ┆     ┆ acq ┆     ┆ vs  ┆     ┆ cin ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 9_r ┆ poi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ chi ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zo, ┆     ┆ ios ┆ ra? ┆ s11 ┆     ┆     ┆ g:  ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆ ChI ┆ 1d  ┆     ┆     ┆ uir ┆     ┆ ChI ┆     ┆ g:  ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ nts ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p-s ┆     ┆     ┆     ┆     ┆     ┆ P-s ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15m ┆     ┆     ┆     ┆ 15m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ADI ┆     ┆ amp ┆ ter ┆ 101 ┆     ┆     ┆ GSM ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆ 01/ ┆     ┆ P-s ┆ vs  ┆     ┆     ┆ es  ┆     ┆ P-s ┆     ┆ GSM ┆ 01/ ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆ 213 ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ inu ┆     ┆     ┆     ┆ inu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -SP ┆     ┆ le/ ┆ m=S ┆ 533 ┆     ┆     ┆ 408 ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ 037 ┆     ┆ eq_ ┆ bad ┆     ┆     ┆ tra ┆     ┆ eq_ ┆     ┆ 408 ┆ 037 ┆     ┆     ┆     ┆     ┆     ┆ 1/0 ┆ ;33 ┆     ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆ tes ┆     ┆     ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A-9 ┆     ┆ SAM ┆ RX6 ┆     ┆     ┆     ┆ 176 ┆     ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆ con ┆ 77e ┆     ┆     ┆ nsc ┆     ┆ con ┆     ┆ 176 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 37/ ┆ 511 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 408 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01) ┆     ┆ N12 ┆ 858 ┆     ┆     ┆     ┆ 2:  ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆ tro ┆ c99 ┆     ┆     ┆ rip ┆     ┆ tro ┆     ┆ 2:  ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 771 ┆ 250 ┆     ┆     ┆     ┆ ChI ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ 129 ┆     ┆ l   ┆ df7 ┆     ┆     ┆ tio ┆     ┆ l   ┆     ┆ ChI ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆ 11; ┆     ┆     ┆ ium ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 833 ┆ vs  ┆     ┆     ┆     ┆ P-s ┆     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆ 837 ┆     ┆     ┆ 4ad ┆     ┆     ┆ nal ┆     ┆     ┆     ┆ P-s ┆ 837 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 895 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ eq_ ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 602 ┆     ┆     ┆ com ┆     ┆     ┆     ┆ eq_ ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 37/ ┆ 93; ┆     ┆     ┆ rem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 081 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ hyp ┆     ┆ pet ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆     ┆ 39e ┆     ┆     ┆ pet ┆     ┆     ┆     ┆ hyp ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆ tro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 762 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ ert ┆     ┆ enc ┆     ┆     ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆ 89a ┆     ┆     ┆ enc ┆     ┆     ┆     ┆ ert ┆ 129 ┆     ┆     ┆     ┆     ┆     ┆ 101 ┆ 2;7 ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ her ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ 837 ┆     ┆     ┆ e90 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ her ┆ 837 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 776 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 13. GSE152144 (ChIP-seq; HSF1/HSF2)

- [A ChIP-exo screen of 887 Protein Capture Reagents Program transcription factor antibodies in human cells](https://doi.org/10.1101/gr.275472.121)
- HSF1のデータのみ、熱ストレス条件下のサンプルを使用していると考えられるため、このデータを選抜、利用
- 以下のような記述から判断
- `ChIP assessment in multiple cell states and types: Any number of targets may be sequestered in a state that prevents their interaction with chromatin (and thus detection by ChIP) unless activated to do so through a change in cell state. We examined this with HSF1, which is rapidly induced to bind in the nucleus upon heat shock to activate heat shock–response genes (Baler et al. 1993). HSF1 was bound to cognate motifs at relatively low levels under nonstressed conditions but increased in binding upon treatment of cells with hydrogen peroxide (0.3 mM) for 3 min and 30 min (assayed by ChIP-exo) (Supplemental Fig. 5A) or upon heat shock (shift from 37°C to 42°C for 1 h; assayed by ChIP-seq) (Supplemental Fig. 5B). This illustrates a potential problem with using mRNA expression levels as a basis for expecting a factor to be actively bound to chromatin. Many TFs are sequestered and only bind chromatin when released by signaling events.`
- 一方で、HSF2のデータも含まれており、`treatment: One hour heat shock`とあるので、こちらも収集する
- Input control データにおいても、熱ストレス条件下 vs. コントロールのデータ が存在しているため、偽陽性排除に使える可能性があると判断し、収集
- 抗体を作成する ハイブリドーマ細胞のクローン 「1A10」、「1A8」など、クローンごとに実行されている
- replicate が2つ以上ないため、ChIP-Atlas Diff analysis には使用しない

In [28]:
GSE152144_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE152144/GSE152144_PEP/GSE152144_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("organism") == "Homo sapiens") &
    (
        (pl.col("sample_name").str.contains("hsf1_")) |
        (pl.col("sample_name").str.contains("hsf2_"))
    )
).with_columns(
    pl.lit("https://doi.org/10.1101/gr.275472.121").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"), # may be 42 C because of the paper description
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE152144 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE152144.metadata.tsv",
    separator='\t'
)

GSE152144_combined = GSE152144_PEP.join(
    GSE152144,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE152144_combined = GSE152144_combined[[s.name for s in GSE152144_combined if not (s.null_count() == GSE152144_combined.height)]]

pl.Config.set_tbl_rows(2)
display(GSE152144_combined)

shape: (18, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ cel ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ l_t ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ype ┆ dy  ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ i64 ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ hsf ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ HSF ┆ GSM ┆ Pub ┆ Jun ┆ Sep ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HCT ┆ col ┆ HSF ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Nex ┆ SAM ┆ Scr ┆ SRA ┆ ChI ┆ 202 ┆ 140 ┆ ILL ┆ ftp ┆ Gen ┆ HSF ┆ 589 ┆ SRP ┆ 433 ┆ Scr ┆ GEN ┆ HSF ┆ Nex ┆ Nex ┆ col ┆ ftp ┆ 215 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ 1x1 ┆ GSM ┆ GEO ┆ HCT ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 1_1 ┆ P   ┆ o   ┆ GLE ┆     ┆ 119 ┆ 851 ┆ 1_1 ┆ 460 ┆ lic ┆ 09  ┆ 02  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 460 ┆ :// ┆ 152 ┆     ┆ 851 ┆ 116 ┆ ore ┆ 1_1 ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N15 ┆ een ┆ 108 ┆ P   ┆ 0-0 ┆ 002 ┆ UMI ┆ .sr ┆ eri ┆ 1_1 ┆ 1e0 ┆ 266 ┆ 566 ┆ een ┆ ERA ┆ 1_1 ┆ tSe ┆ tSe ┆ ore ┆ .sr ┆ 000 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 460 ┆ 460 ┆ 0^8 ┆ 460 ┆     ┆ 116 ┆ _ta ┆ 0-0 ┆ o   ┆ 6   ┆ NA6 ┆ 119 ┆ 681 ┆ 0-0 ┆ 152 │
│ a10 ┆     ┆ sap ┆     ┆     ┆ 689 ┆ 277 ┆ A10 ┆ 471 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 471 ┆ ftp ┆ 144 ┆     ┆ 277 ┆     ┆ cta ┆ A10 ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 192 ┆ ing ┆ 518 ┆     ┆ 9-0 ┆ 573 ┆ NA  ┆ a.e ┆ c   ┆ A10 ┆ 610 ┆ 663 ┆ 17  ┆ ing ┆ TED ┆ A10 ┆ q   ┆ q   ┆ cta ┆ a.e ┆ 221 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 471 ┆ 471 ┆ cel ┆ 471 ┆     ┆     ┆ x:t ┆ 9-0 ┆ sap ┆     ┆ 384 ┆ 689 ┆ 129 ┆ 9-0 ┆ 144 │
│ _37 ┆     ┆ ien ┆     ┆     ┆ 93  ┆ 3   ┆ _37 ┆ 5   ┆ Sep ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 5   ┆ .nc ┆     ┆     ┆ 3   ┆     ┆ l   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 250 ┆ of  ┆ 7   ┆     ┆ 2   ┆ 9   ┆     ┆ bi. ┆     ┆ _37 ┆ 0a2 ┆     ┆     ┆ of  ┆ _FI ┆ _37 ┆ 500 ┆ 500 ┆ l   ┆ bi. ┆ 6   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ ls  ┆ 5   ┆     ┆     ┆ err ┆ 2   ┆ ien ┆     ┆ 11  ┆ 93  ┆ 4   ┆ 2   ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆ car ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆     ┆ PCR ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ b99 ┆     ┆     ┆ PCR ┆ LE  ┆     ┆     ┆ seq ┆ car ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ wer ┆     ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆ 39c ┆     ┆     ┆ P   ┆     ┆     ┆     ┆ uen ┆ cin ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆ oma ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ cin ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ cc1 ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ cin ┆ oma ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ fix ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 01/ ┆     ┆     ┆ g:  ┆     ┆ nsc ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 75e ┆     ┆     ┆ nsc ┆     ┆     ┆     ┆ g:  ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ gr. ┆     ┆     ┆ GSM ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 594 ┆     ┆     ┆ rip ┆     ┆     ┆     ┆ GSM ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 275 ┆     ┆     ┆ 460 ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 957 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 460 ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 472 ┆     ┆     ┆ 471 ┆     ┆ n 1 ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 70  ┆     ┆     ┆ n 1 ┆     ┆     ┆     ┆ 471 ┆     ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ .12 ┆     ┆     ┆ 5:  ┆     ┆ fac ┆     ┆     ┆     ┆     ┆     ┆ 19/ ┆     ┆     ┆     ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 5:  ┆     ┆ 19/ ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆ 213 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 1   ┆     ┆     ┆ HSF ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆ 093 ┆     ┆     ┆     ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ HSF ┆     ┆ 093 ┆     ┆     ┆     ┆     ┆     ┆ 9/0 ┆ ;33 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX8 ┆     ┆     ┆     ┆ 1_1 ┆     ┆ ant ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ ant ┆     ┆     ┆     ┆ 1_1 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 93/ ┆ 511 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 460 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N15 ┆ 512 ┆     ┆     ┆     ┆ A10 ┆     ┆ ibo ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ ibo ┆     ┆     ┆     ┆ A10 ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ (Si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 192 ┆ 773 ┆     ┆     ┆     ┆ _37 ┆     ┆ die ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ die ┆     ┆     ┆     ┆ _37 ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ 119 ┆ 11; ┆     ┆     ┆ gma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 993 ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ Hom ┆     ┆ 993 ┆     ┆     ┆     ┆     ┆     ┆ 689 ┆ 895 ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ o   ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 93/ ┆ 93; ┆     ┆     ┆ 252 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 604 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆ bio ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ bio ┆     ┆     ┆     ┆ sap ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ 549 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 715 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ che ┆     ┆     ┆     ┆ ien ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ 119 ┆ 2;7 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ mic ┆     ┆     ┆     ┆     ┆     ┆ 993 ┆     ┆     ┆     ┆     ┆     ┆ mic ┆     ┆     ┆     ┆ s   ┆     ┆ 993 ┆     ┆     ┆     ┆     ┆     ┆ 689 ┆ 776 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆ ChI ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ 93. ┆ ;11 ┆     ┆     ┆ PBS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆ ass ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ ass ┆     ┆     ┆     ┆ P-S ┆     ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [29]:
defined_pairs_gse152144_chipseq = [


    ("SRX8512774", "SRX8512773"), # HSF1_1A10_43 vs. HSF1_1A10_37
    ("SRX8512776", "SRX8512775"), # HSF1_1A6_43 vs. HSF1_1A6_37
    ("SRX8512778", "SRX8512777"), # HSF1_1A8_43 vs. HSF1_1A8_37
    ("SRX8512780", "SRX8512779"), # HSF1_1A9_43 vs. HSF1_1A9_37
    ("SRX8512782", "SRX8512781"), # HSF1_1C1_43 vs. HSF1_1C1_37
    ("SRX8512784", "SRX8512783"), # HSF1_1D11_43 vs. HSF1_1D11_37

    ("SRX8512786", "SRX8512785"), # HSF2_2C1_43 vs. HSF2_2C1_37
    ("SRX8512890", "SRX8512889"), # Input_HSF1_1A10_HSF1_1A8_HSF1_1A9_HSF1_1D11_HSF2_2C1_43 vs. Input_HSF1_1A10_HSF1_1A8_HSF1_1A9_HSF1_1D11_HSF2_2C1_37
    ("SRX8512724", "SRX8512891")  # Input_HSF1_1A6_HSF1_1C1_43 vs. Input_HSF1_1A6_HSF1_1C1_37
]

paired_metada_df_gse152144 = create_paired_metadata(
    combined_df=GSE152144_combined,
    defined_sample_pairs=defined_pairs_gse152144_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse152144 is not None:
    paired_metada_df_gse152144.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE152144_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse152144)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (9, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ cel ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ l_t ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ype ┆ dy  ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hsf ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ HSF ┆ GSM ┆ Pub ┆ Jun ┆ Sep ┆ SRA ┆ 1   ┆ HCT ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HCT ┆ col ┆ HSF ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Nex ┆ SAM ┆ Scr ┆ SRA ┆ ChI ┆ 202 ┆ 830 ┆ ILL ┆ ftp ┆ Gen ┆ HSF ┆ 7c3 ┆ SRP ┆ 281 ┆ Scr ┆ GEN ┆ HSF ┆ Nex ┆ Nex ┆ col ┆ ftp ┆ 134 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ 1x1 ┆ GSM ┆ GEO ┆ HCT ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 851 ┆ 851 ┆ 1_1 ┆ P   ┆ o   ┆ GLE ┆     ┆ 119 ┆ 1_1 ┆ 460 ┆ lic ┆ 09  ┆ 02  ┆     ┆     ┆ 116 ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 460 ┆ :// ┆ 152 ┆     ┆ 851 ┆ 116 ┆ ore ┆ 1_1 ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N15 ┆ een ┆ 108 ┆ P   ┆ 0-0 ┆ 654 ┆ UMI ┆ .sr ┆ eri ┆ 1_1 ┆ b47 ┆ 266 ┆ 367 ┆ een ┆ ERA ┆ 1_1 ┆ tSe ┆ tSe ┆ ore ┆ .sr ┆ 706 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 460 ┆ 460 ┆ 0^8 ┆ 460 ┆     ┆ 116 ┆ _ta ┆ 0-0 ┆ o   ┆ 6   ┆ NA6 ┆ 119 ┆ 681 ┆ 0-0 ┆ 152 │
│ 277 ┆ 277 ┆ a10 ┆     ┆ sap ┆     ┆     ┆ 689 ┆ A10 ┆ 471 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 471 ┆ ftp ┆ 144 ┆     ┆ 277 ┆     ┆ cta ┆ A10 ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 192 ┆ ing ┆ 518 ┆     ┆ 9-0 ┆ 417 ┆ NA  ┆ a.e ┆ c   ┆ A10 ┆ 732 ┆ 663 ┆ 81  ┆ ing ┆ TED ┆ A10 ┆ q   ┆ q   ┆ cta ┆ a.e ┆ 978 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 471 ┆ 471 ┆ cel ┆ 471 ┆     ┆     ┆ x:t ┆ 9-0 ┆ sap ┆     ┆ 384 ┆ 689 ┆ 129 ┆ 9-0 ┆ 144 │
│ 4   ┆ 3   ┆ _43 ┆     ┆ ien ┆     ┆     ┆ 94  ┆ _43 ┆ 6   ┆ Sep ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 6   ┆ .nc ┆     ┆     ┆ 4   ┆     ┆ l   ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 249 ┆ of  ┆ 7   ┆     ┆ 2   ┆ vs  ┆     ┆ bi. ┆     ┆ _43 ┆ 0a0 ┆     ┆ vs  ┆ of  ┆ _FI ┆ _43 ┆ 500 ┆ 500 ┆ l   ┆ bi. ┆ 1   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 6   ┆ 6_r ┆ ls  ┆ 6   ┆     ┆     ┆ err ┆ 2   ┆ ien ┆     ┆ 11  ┆ 94  ┆ 5   ┆ 2   ┆     │
│     ┆     ┆ vs  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ car ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆ vs  ┆ PCR ┆     ┆     ┆     ┆ 140 ┆     ┆ ac. ┆     ┆ vs  ┆ 951 ┆     ┆ 433 ┆ PCR ┆ LE  ┆ vs  ┆     ┆ seq ┆ car ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ wer ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ hsf ┆     ┆     ┆     ┆     ┆ SRR ┆ HSF ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ cin ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆ SAM ┆ P   ┆     ┆     ┆     ┆ 002 ┆     ┆ uk/ ┆     ┆ HSF ┆ 5a9 ┆     ┆ 566 ┆ P   ┆     ┆ HSF ┆     ┆ uen ┆ cin ┆ uk/ ┆ 215 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ e   ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ 1_1 ┆     ┆     ┆     ┆     ┆ 119 ┆ 1_1 ┆ 460 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 460 ┆ .ni ┆     ┆     ┆ 851 ┆     ┆ oma ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ cin ┆ N15 ┆ tra ┆     ┆     ┆     ┆ 573 ┆     ┆ vol ┆     ┆ 1_1 ┆ 2cb ┆     ┆ 17  ┆ tra ┆     ┆ 1_1 ┆     ┆ cin ┆ oma ┆ vol ┆ 000 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 460 ┆ GSM ┆ fix ┆ 460 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 119 ┆ 681 ┆     ┆     │
│     ┆     ┆ a10 ┆     ┆     ┆     ┆     ┆ 689 ┆ A10 ┆ 471 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 471 ┆ h.g ┆     ┆     ┆ 277 ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 01/ ┆     ┆     ┆ g:  ┆ 192 ┆ nsc ┆     ┆     ┆     ┆ 9   ┆     ┆ 1/f ┆     ┆ A10 ┆ 4d3 ┆     ┆     ┆ nsc ┆     ┆ A10 ┆     ┆ g:  ┆     ┆ 1/f ┆ 221 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 471 ┆ 460 ┆ ed  ┆ 471 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 689 ┆ 129 ┆     ┆     │
│     ┆     ┆ _37 ┆     ┆     ┆     ┆     ┆ 93  ┆ _37 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ ov/ ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ gr. ┆     ┆     ┆ GSM ┆ 250 ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆ _37 ┆ c28 ┆     ┆     ┆ rip ┆     ┆ _37 ┆     ┆ GSM ┆     ┆ ast ┆ 6   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 5   ┆ 471 ┆ in  ┆ 5   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 93  ┆ 4   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 275 ┆     ┆     ┆ 460 ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 990 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 460 ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 5_r ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 472 ┆     ┆     ┆ 471 ┆     ┆ n 1 ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ dd  ┆     ┆     ┆ n 1 ┆     ┆     ┆     ┆ 471 ┆     ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ .12 ┆     ┆     ┆ 6:  ┆     ┆ fac ┆     ┆     ┆     ┆     ┆     ┆ 19/ ┆     ┆     ┆ vs  ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 6:  ┆     ┆ 19/ ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆ 213 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 1   ┆     ┆     ┆ HSF ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆ 094 ┆     ┆     ┆ 589 ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ HSF ┆     ┆ 094 ┆     ┆     ┆     ┆     ┆     ┆ 9/0 ┆ ;33 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX8 ┆     ┆     ┆     ┆ 1_1 ┆     ┆ ant ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 1e0 ┆     ┆     ┆ ant ┆     ┆     ┆     ┆ 1_1 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 94/ ┆ 511 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 460 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N15 ┆ 512 ┆     ┆     ┆     ┆ A10 ┆     ┆ ibo ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆     ┆ 610 ┆     ┆     ┆ ibo ┆     ┆     ┆     ┆ A10 ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ (Si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 192 ┆ 774 ┆     ┆     ┆     ┆ _43 ┆     ┆ die ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆ 0a2 ┆     ┆     ┆ die ┆     ┆     ┆     ┆ _43 ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ 119 ┆ 11; ┆     ┆     ┆ gma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 249 ┆ vs  ┆     ┆     ┆     ┆ Hom ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 994 ┆     ┆     ┆ b99 ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ Hom ┆     ┆ 994 ┆     ┆     ┆     ┆     ┆     ┆ 689 ┆ 895 ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ o   ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 39c ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ o   ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 94/ ┆ 93; ┆     ┆     ┆ 252 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 604 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ sap ┆     ┆ bio ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆     ┆ cc1 ┆     ┆     ┆ bio ┆     ┆     ┆     ┆ sap ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ 549 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 716 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ ien ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆ 75e ┆     ┆     ┆ che ┆     ┆     ┆     ┆ ien ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ 119 ┆ 2;7 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ s   ┆     ┆ mic ┆     ┆     ┆     ┆     ┆     ┆ 994 ┆     ┆     ┆ 594 ┆     ┆     ┆ mic ┆     ┆     ┆     ┆ s   ┆     ┆ 994 ┆     ┆     ┆     ┆     ┆     ┆ 689 ┆ 776 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ ChI ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ 957 ┆     ┆     ┆ al  ┆     ┆     ┆     ┆ ChI ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ 94. ┆ ;11 ┆     ┆     ┆ PBS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 14. GSE143591 (ChIP-seq; PolII/SETD1A/MRE11A)

- [Chromatin-associated MRN complex protects highly transcribing genes from genomic instability](https://doi.org/10.1126/sciadv.abb2947)
- 以下のような記述を発見
- `MATERIALS AND METHODS:Cell culture, treatment, and lentiviral infection: ... All cells were grown in a humidified incubator at 37°C with 5% CO2. Where indicated, cells were subjected to heat shock at 42°C for 1 hour, and the medium was replaced before fixation. `

In [30]:
GSE143591_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE143591/GSE143591_PEP/GSE143591_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("organism") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1126/sciadv.abb2947").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE143591 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE143591.metadata.tsv",
    separator='\t'
)

GSE143591_combined = GSE143591_PEP.join(
    GSE143591,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE143591_combined = GSE143591_combined[[s.name for s in GSE143591_combined if not (s.null_count() == GSE143591_combined.height)]]

# display(GSE143591_combined)

In [31]:
defined_pairs_gse143591_chipseq = [
    ("SRX7551111", "SRX7551108"), # Zd4_Heatshock_NBS1 vs. Zd1_Untreated_NBS1
    ("SRX7551112", "SRX7551109"), # Zd5_Heatshock_MRE11 vs. Zd2_Untreated_MRE11
    ("SRX7551113", "SRX7551110")  # Zd6_Heatshock_Pol2 vs. Zd3_Untreated_Pol2 (replicate が 2つ以上ないので、diff analysis では除外)
]

paired_metada_df_gse143591 = create_paired_metadata(
    combined_df=GSE143591_combined,
    defined_sample_pairs=defined_pairs_gse143591_chipseq,
    sample_id_column_name="experiment_accession"
)


if paired_metada_df_gse143591 is not None:
    paired_metada_df_gse143591.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE143591_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(3)
    display(paired_metada_df_gse143591)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ tre ┆ pas ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ atm ┆ sag ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ent ┆ es  ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ lab ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ ora ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ tor ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ zd4 ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ Zd4 ┆ GSM ┆ Pub ┆ Jan ┆ Jan ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ros ┆ Gen ┆ UMR ┆ 141 ┆ Mon ┆ 343 ┆ Fra ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ hea ┆ 13- ┆ Bet ┆ HG3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Nex ┆ SAM ┆ Gen ┆ SRA ┆ ChI ┆ 202 ┆ 564 ┆ ILL ┆ ftp ┆ Gen ┆ Zd4 ┆ c0f ┆ SRP ┆ 116 ┆ Gen ┆ GEN ┆ Zd4 ┆ Nex ┆ Nex ┆ ftp ┆ 883 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ ChI ┆ GSM ┆ GEO ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 755 ┆ 755 ┆ _he ┆ P   ┆ o   ┆ GLE ┆     ┆ 108 ┆ _He ┆ 426 ┆ lic ┆ 13  ┆ 14  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ ema ┆ e   ┆ 900 ┆ rue ┆ tpe ┆ 96  ┆ nce ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 426 ┆ :// ┆ 143 ┆     ┆ 755 ┆ t   ┆ 15  ┆ hyl ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N13 ┆ ome ┆ 102 ┆ P   ┆ 1-0 ┆ 093 ┆ UMI ┆ .sr ┆ eri ┆ _He ┆ 91d ┆ 241 ┆ 300 ┆ ome ┆ ERA ┆ _He ┆ tSe ┆ tSe ┆ .sr ┆ 884 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 426 ┆ 426 ┆ P   ┆ 426 ┆     ┆ _ta ┆ 1-0 ┆ o   ┆ 6   ┆ NA6 ┆ 108 ┆ 598 ┆ 1-0 ┆ 143 │
│ 111 ┆ 110 ┆ ats ┆     ┆ sap ┆     ┆     ┆ 820 ┆ ats ┆ 356 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ cel ┆ sap ┆     ┆ c   ┆ 73  ┆ ry, ┆ Reg ┆ 2   ┆ de  ┆ lli ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 356 ┆ ftp ┆ 591 ┆     ┆ 111 ┆ sho ┆     ┆ A30 ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 839 ┆ -wi ┆ 567 ┆     ┆ 1-1 ┆ 025 ┆ NA  ┆ a.e ┆ c   ┆ ats ┆ a64 ┆ 821 ┆ 616 ┆ -wi ┆ TED ┆ ats ┆ q   ┆ q   ┆ a.e ┆ 681 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 356 ┆ 356 ┆ exp ┆ 356 ┆     ┆ x:t ┆ 1-1 ┆ sap ┆     ┆ 009 ┆ 820 ┆ 862 ┆ 1-1 ┆ 591 │
│ 1   ┆ 8   ┆ hoc ┆     ┆ ien ┆     ┆     ┆ 47  ┆ hoc ┆ 6   ┆ Jan ┆ 0   ┆ 1   ┆     ┆     ┆ l   ┆ ien ┆     ┆ DNA ┆     ┆ ,Ki ┆ ula ┆ CNR ┆ la  ┆ er  ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 6   ┆ .nc ┆     ┆     ┆ 1   ┆ ck  ┆     ┆ 0-2 ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 657 ┆ de  ┆ 1   ┆     ┆ 4   ┆ 2   ┆     ┆ bi. ┆     ┆ hoc ┆ d61 ┆     ┆ vs  ┆ de  ┆ _FI ┆ hoc ┆ 500 ┆ 500 ┆ bi. ┆ 6   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 6   ┆ 6_r ┆ eri ┆ 6   ┆     ┆ err ┆ 4   ┆ ien ┆     ┆ 88  ┆ 47  ┆ 0   ┆ 4   ┆     │
│     ┆     ┆ k_n ┆     ┆ s   ┆     ┆     ┆ vs  ┆ k_N ┆ vs  ┆ 13  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ ern ┆ tio ┆ S-U ┆ car ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ vs  ┆     ┆ 89A ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆ vs  ┆ map ┆     ┆     ┆     ┆ vs  ┆     ┆ ac. ┆     ┆ k_N ┆ 3b1 ┆     ┆ 405 ┆ map ┆ LE  ┆ k_N ┆     ┆ seq ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ men ┆ vs  ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ bs1 ┆     ┆     ┆     ┆     ┆ SRR ┆ BS1 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆ n   ┆ M   ┆ don ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ Non ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆ SAM ┆ s   ┆     ┆     ┆     ┆ 197 ┆     ┆ uk/ ┆     ┆ BS1 ┆ 697 ┆     ┆ 068 ┆ s   ┆     ┆ BS1 ┆     ┆ uen ┆ uk/ ┆ 307 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ts  ┆ GSM ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 108 ┆ vs  ┆ 426 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lab ┆     ┆ ill ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 426 ┆ .ni ┆     ┆     ┆ 755 ┆ e   ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ cin ┆ N13 ┆ of  ┆     ┆     ┆     ┆ 062 ┆     ┆ vol ┆     ┆ vs  ┆ bf3 ┆     ┆ 03  ┆ of  ┆     ┆ vs  ┆     ┆ cin ┆ vol ┆ 851 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 426 ┆ GSM ┆ wer ┆ 426 ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 108 ┆ 598 ┆     ┆     │
│     ┆     ┆ zd1 ┆     ┆     ┆     ┆     ┆ 820 ┆ Zd1 ┆ 356 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 356 ┆ h.g ┆     ┆     ┆ 110 ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 26/ ┆     ┆     ┆ g:  ┆ 839 ┆ MRE ┆     ┆     ┆     ┆ 734 ┆     ┆ 1/f ┆     ┆ Zd1 ┆ 511 ┆     ┆     ┆ MRE ┆     ┆ Zd1 ┆     ┆ g:  ┆ 1/f ┆ 702 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 356 ┆ 426 ┆ e   ┆ 356 ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 820 ┆ 861 ┆     ┆     │
│     ┆     ┆ _un ┆     ┆     ┆     ┆     ┆ 44  ┆ _Un ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ sci ┆     ┆     ┆ GSM ┆ 660 ┆ 11, ┆     ┆     ┆     ┆ 1   ┆     ┆ ast ┆     ┆ _Un ┆ 566 ┆     ┆     ┆ 11, ┆     ┆ _Un ┆     ┆ GSM ┆ ast ┆ 8   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 3   ┆ 356 ┆ per ┆ 3   ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 44  ┆ 7   ┆     ┆     │
│     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆ tre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ adv ┆     ┆     ┆ 426 ┆     ┆ NBS ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆ tre ┆ 1a7 ┆     ┆     ┆ NBS ┆     ┆ tre ┆     ┆ 426 ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 3_r ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ .ab ┆     ┆     ┆ 356 ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆ ate ┆ e5  ┆     ┆     ┆ 1   ┆     ┆ ate ┆     ┆ 356 ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ d_n ┆     ┆     ┆     ┆     ┆     ┆ d_N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ b29 ┆     ┆     ┆ 6:  ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆ 08/ ┆     ┆ d_N ┆ vs  ┆     ┆     ┆ tot ┆     ┆ d_N ┆     ┆ 6:  ┆ 08/ ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆ 213 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ bs1 ┆     ┆     ┆     ┆     ┆     ┆ BS1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 47  ┆     ┆     ┆ Zd4 ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ 047 ┆     ┆ BS1 ┆ 771 ┆     ┆     ┆ al  ┆     ┆ BS1 ┆     ┆ Zd4 ┆ 047 ┆     ┆     ┆     ┆     ┆     ┆ 8/0 ┆ ;33 ┆     ┆     ┆ HeL ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX7 ┆     ┆     ┆     ┆ _He ┆     ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ ec8 ┆     ┆     ┆ RNA ┆     ┆     ┆     ┆ _He ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 47/ ┆ 511 ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 426 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N13 ┆ 551 ┆     ┆     ┆     ┆ ats ┆     ┆ PII ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆     ┆ 37c ┆     ┆     ┆ PII ┆     ┆     ┆     ┆ ats ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 839 ┆ 111 ┆     ┆     ┆     ┆ hoc ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆ 882 ┆     ┆     ┆ 3d9 ┆     ┆     ┆ and ┆     ┆     ┆     ┆ hoc ┆ 882 ┆     ┆     ┆     ┆     ┆     ┆ 108 ┆ 11; ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 657 ┆ vs  ┆     ┆     ┆     ┆ k_N ┆     ┆ pho ┆     ┆     ┆     ┆     ┆     ┆ 047 ┆     ┆     ┆ 198 ┆     ┆     ┆ pho ┆     ┆     ┆     ┆ k_N ┆ 047 ┆     ┆     ┆     ┆     ┆     ┆ 820 ┆ 895 ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ BS1 ┆     ┆ sph ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ b89 ┆     ┆     ┆ sph ┆     ┆     ┆     ┆ BS1 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 47/ ┆ 93; ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 263 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ Hom ┆     ┆ o-S ┆     ┆     ┆     ┆     ┆     ┆ R10 ┆     ┆     ┆ d40 ┆     ┆     ┆ o-S ┆     ┆     ┆     ┆ Hom ┆ R10 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 566 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ o   ┆     ┆ er2 ┆     ┆     ┆     ┆     ┆     ┆ 882 ┆     ┆     ┆ 631 ┆     ┆     ┆ er2 ┆     ┆     ┆     ┆ o   ┆ 882 ┆     ┆     ┆     ┆     ┆     ┆ 108 ┆ 2;7 ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ sap ┆     ┆ -RN ┆     ┆     ┆     ┆     ┆     ┆ 047 ┆     ┆     ┆ d21 ┆     ┆     ┆ -RN ┆     ┆     ┆     ┆ sap ┆ 047 ┆     ┆     ┆     ┆     ┆     ┆ 820 ┆ 776 ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ ien ┆     ┆ API ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ f05 ┆     ┆     ┆ API ┆     ┆     ┆     ┆ ien ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ 47. ┆ ;11 ┆     ┆     ┆ IP  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ i.n ┆     ┆     ┆     ┆ s   ┆     ┆ I   ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆ 99  ┆     ┆     ┆ I   ┆     ┆     ┆     ┆ s   ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ Hig ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M42 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ lm. ┆     ┆     ┆     ┆ ChI ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ ChI ┆ .gz ┆     ┆     ┆     ┆     ┆     ┆ tq. ┆ 0;1 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 15. GSE194364 (ChIP-seq; HSF1)

- [The stress response regulator HSF1 modulates natural killer cell anti-tumour immunity](https://doi.org/10.1038/s41556-024-01490-z)
- [GSM8289675](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM8289675)
- replicate が2つ以上ないため、ChIP-Atlas Diff analysis には使用しない

In [32]:
GSE194364_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE194364/GSE194364_PEP/GSE194364_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1038/s41556-024-01490-z").alias("reference_doi"),
    # GSM8289675 Treatment protocol: heat shocked at 42 C for 1 hour
    pl.when(pl.col("sample_name").str.contains("(?i)_hs_")).then(pl.lit("42 C"))
      .otherwise(pl.lit("ctrl"))
      .alias("stress treatment temperature"),
    pl.when(pl.col("sample_name").str.contains("(?i)_hs_")).then(pl.lit("60 min."))
      .otherwise(pl.lit("ctrl"))
      .alias("stress treatment time"),
    pl.lit("37 C (inferred)").alias("control treatment temperature")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE194364 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE194364.metadata.tsv",
    separator='\t'
)

GSE194364_combined = GSE194364_PEP.join(
    GSE194364,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE194364_combined = GSE194364_combined[[s.name for s in GSE194364_combined if not (s.null_count() == GSE194364_combined.height)]]

display(GSE194364_combined)

shape: (3, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ exp ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ eri ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ men ┆ dy  ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ g   ┆ str ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ nk9 ┆ NK9 ┆ GSM ┆ Pub ┆ Jan ┆ Jan ┆ SRA ┆ 1   ┆ NK- ┆ Hom ┆ 960 ┆ gen ┆ Rea ┆ GPL ┆ Kat ┆ Aif ┆ Pat ┆ NYU ┆ 550 ┆ New ┆ New ┆ 100 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HSF ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ ctr ┆ ctr ┆ 37  ┆ SRR ┆ Ill ┆ SAM ┆ The ┆ SRA ┆ ChI ┆ 202 ┆ 191 ┆ ILL ┆ ftp ┆ nul ┆ Gen ┆ NK9 ┆ 5e2 ┆ SRP ┆ 910 ┆ The ┆ GEN ┆ NK9 ┆ Ill ┆ Ill ┆ nul ┆ ftp ┆ 928 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ nul ┆ GSM ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 2_h ┆ 2_H ┆ 583 ┆ lic ┆ 25  ┆ 26  ┆     ┆     ┆ 92  ┆ o   ┆ 6   ┆ omi ┆ ds  ┆ 246 ┆ hry ┆ ant ┆ hol ┆ Lan ┆ 1st ┆ Yor ┆ Yor ┆ 16  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 583 ┆ :// ┆ :// ┆ 167 ┆     ┆ 138 ┆ 1   ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ l   ┆ l   ┆ C   ┆ 177 ┆ umi ┆ N25 ┆ NK  ┆ 136 ┆ P   ┆ 2-0 ┆ 422 ┆ UMI ┆ .sr ┆ l   ┆ eri ┆ 2_H ┆ 95b ┆ 356 ┆ 224 ┆ NK  ┆ ERA ┆ 2_H ┆ umi ┆ umi ┆ l   ┆ .sr ┆ 428 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 583 ┆ 583 ┆ ls  ┆ l   ┆ 583 ┆ 583 ┆ _ta ┆ 2-0 ┆ o   ┆ 6   ┆ NA8 ┆ 177 ┆ 117 ┆ 2-0 ┆ 194 │
│ sf1 ┆ SF1 ┆ 409 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ MI  ┆ sap ┆     ┆ c   ┆ wer ┆ 76  ┆ n,G ┆ is  ┆ ogy ┆ gon ┆ Ave ┆ k   ┆ k   ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 409 ┆ ftp ┆ ftp ┆ 552 ┆     ┆ 982 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆     ┆ (in ┆ 356 ┆ na  ┆ 243 ┆ cel ┆ 165 ┆     ┆ 1-2 ┆ 596 ┆ NA  ┆ a.e ┆     ┆ c   ┆ SF1 ┆ e44 ┆ 652 ┆ 49  ┆ cel ┆ TED ┆ SF1 ┆ na  ┆ na  ┆     ┆ a.e ┆ 979 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 409 ┆ 409 ┆ wer ┆     ┆ 409 ┆ 409 ┆ x:t ┆ 1-2 ┆ sap ┆     ┆ 003 ┆ 356 ┆ 613 ┆ 1-2 ┆ 364 │
│ _ip ┆ _IP ┆ 1   ┆ Jan ┆ 2   ┆ 2   ┆     ┆     ┆ cel ┆ ien ┆     ┆ DNA ┆ e   ┆     ┆ rac ┆     ┆     ┆ e   ┆ nue ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆ 1   ┆ .nc ┆ .nc ┆ ,   ┆     ┆ 38  ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer ┆ 73  ┆ Nov ┆ 265 ┆ l   ┆ 1   ┆     ┆ 7   ┆ 4;1 ┆     ┆ bi. ┆     ┆     ┆ _IP ┆ 726 ┆     ┆     ┆ l   ┆ _FI ┆ _IP ┆ Nov ┆ Nov ┆     ┆ bi. ┆ 8   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 1   ┆ 1_r ┆ e   ┆     ┆ 1_r ┆ 1   ┆ err ┆ 7   ┆ ien ┆     ┆ 65  ┆ 73  ┆ 59  ┆ 7   ┆     │
│     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆ ls  ┆ s   ┆     ┆     ┆ ali ┆     ┆ e,H ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆     ┆ bi. ┆ bi. ┆ GSE ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red ┆     ┆ aSe ┆     ┆ str ┆     ┆     ┆     ┆ 820 ┆     ┆ ac. ┆     ┆     ┆     ┆ 0ec ┆     ┆     ┆ str ┆ LE; ┆     ┆ aSe ┆ aSe ┆     ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ was ┆     ┆ 1   ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆ ock ┆     ┆     ┆ lth ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆ nlm ┆ 194 ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   ┆     ┆ q   ┆     ┆ ess ┆     ┆     ┆     ┆ 935 ┆     ┆ uk/ ┆     ┆     ┆     ┆ 662 ┆     ┆     ┆ ess ┆ GEN ┆     ┆ q   ┆ q   ┆     ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ hed ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆ .ni ┆ .ni ┆ 364 ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆ res ┆     ┆     ┆     ┆ 624 ┆     ┆ vol ┆     ┆     ┆     ┆ e22 ┆     ┆     ┆ res ┆ ERA ┆     ┆ 600 ┆ 600 ┆     ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆ yer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ h.g ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ pon ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆     ┆ 83c ┆     ┆     ┆ pon ┆ TED ┆     ┆ 0   ┆ 0   ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ 1XP ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆     ┆     ┆ seq ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆ c2c ┆     ┆     ┆ se  ┆ _FI ┆     ┆     ┆ seq ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ BS  ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mus ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 556 ┆     ┆     ┆     ┆     ┆ uen ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆     ┆ 182 ┆     ┆     ┆ sta ┆ LE  ┆     ┆     ┆ uen ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mus ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ tus ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆     ┆ f9; ┆     ┆     ┆ tus ┆     ┆     ┆     ┆ cin ┆     ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ fix ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 4-0 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ mod ┆     ┆     ┆     ┆     ┆     ┆ 77/ ┆     ┆     ┆     ┆ 578 ┆     ┆     ┆ mod ┆     ┆     ┆     ┆ g:  ┆     ┆ 77/ ┆     ┆     ┆     ┆     ┆     ┆ R17 ┆ 213 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ us  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 149 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ ula ┆     ┆     ┆     ┆     ┆     ┆ 073 ┆     ┆     ┆     ┆ 3b8 ┆     ┆     ┆ ula ┆     ┆     ┆     ┆ GSM ┆     ┆ 073 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX1 ┆ 0-z ┆     ┆     ┆     ┆     ┆ 583 ┆     ┆ tes ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 8ca ┆     ┆     ┆ tes ┆     ┆     ┆     ┆ 583 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 73/ ┆ 511 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 583 ┆ 583 ┆     ┆     ┆     ┆     ┆     ┆ N25 ┆ 389 ┆     ┆     ┆     ┆     ┆     ┆ 409 ┆     ┆ ant ┆     ┆     ┆     ┆     ┆     ┆ R17 ┆     ┆     ┆     ┆ fa4 ┆     ┆     ┆ ant ┆     ┆     ┆     ┆ 409 ┆     ┆ R17 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (mm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4nn ┆ 4nn ┆     ┆     ┆     ┆     ┆     ┆ 243 ┆ 823 ┆     ┆     ┆     ┆     ┆     ┆ 1:  ┆     ┆ i-t ┆     ┆     ┆     ┆     ┆     ┆ 735 ┆     ┆     ┆     ┆ f0e ┆     ┆     ┆ i-t ┆     ┆     ┆     ┆ 1:  ┆     ┆ 735 ┆     ┆     ┆     ┆     ┆     ┆ 177 ┆ 11; ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 10/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ 265 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆ NK9 ┆     ┆ umo ┆     ┆     ┆     ┆     ┆     ┆ 673 ┆     ┆     ┆     ┆ f98 ┆     ┆     ┆ umo ┆     ┆     ┆     ┆ NK9 ┆     ┆ 673 ┆     ┆     ┆     ┆     ┆     ┆ 356 ┆ 895 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GRC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_H ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 6ef ┆     ┆     ┆ r   ┆     ┆     ┆     ┆ 2_H ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 73/ ┆ 93; ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m38 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 834 ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SF1 ┆     ┆ imm ┆     ┆     ┆     ┆     ┆     ┆ R17 ┆     ┆     ┆     ┆ 0ee ┆     ┆     ┆ imm ┆     ┆     ┆     ┆ SF1 ┆     ┆ R17 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 091 ┆ 091 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _IP ┆     ┆ uni ┆     ┆     ┆     ┆     ┆     ┆ 735 ┆     ┆     ┆     ┆ a62 ┆     ┆     ┆ uni ┆     ┆     ┆     ┆ _IP ┆     ┆ 735 ┆     ┆     ┆     ┆     ┆     ┆ 177 ┆ 2;7 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆ 673 ┆     ┆     ┆     ┆ c78 ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆ Hom ┆     ┆ 673 ┆     ┆     ┆     ┆     ┆     ┆ 356 ┆ 776 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ [Ch ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ 62  ┆     ┆     ┆ [Ch ┆     ┆     ┆     ┆ o   ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 73_ ┆ ;11 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆     ┆ IP- ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆     ┆ IP- ┆     ┆     ┆     ┆ sap ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bow ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M58 ┆ M58 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ tq. ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆ ien ┆     ┆ tq. ┆     ┆     ┆     ┆     ┆     ┆ ast ┆ 0;1 ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [33]:
defined_pairs_gse194364_chipseq = [
    ("SRX24692877", "SRX13898238") # nk92_hs_hsf1_ip_2 vs. nk92_hsf1_ip
]

paired_metada_df_gse194364 = create_paired_metadata(
    combined_df=GSE194364_combined,
    defined_sample_pairs=defined_pairs_gse194364_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse194364 is not None:
    paired_metada_df_gse194364 = paired_metada_df_gse194364.with_columns(
        pl.col(["stress treatment temperature", "stress treatment time"])
        .str.strip_suffix(" vs ctrl")
    )
    paired_metada_df_gse194364.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE194364_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse194364)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ sam ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ ple ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ _se ┆ _da ┆ dy  ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆ s_i ┆ row ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆ d   ┆ _co ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ g   ┆ str ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ nk9 ┆ NK9 ┆ GSM ┆ Pub ┆ May ┆ May ┆ SRA ┆ 1   ┆ NK- ┆ Hom ┆ 960 ┆ gen ┆ Rea ┆ GPL ┆ Kat ┆ Aif ┆ Pat ┆ NYU ┆ 550 ┆ New ┆ New ┆ 100 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ nul ┆ nul ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ SAM ┆ The ┆ SRA ┆ ChI ┆ 202 ┆ 215 ┆ ILL ┆ ftp ┆ nul ┆ Gen ┆ NK9 ┆ 594 ┆ SRP ┆ 972 ┆ The ┆ GEN ┆ NK9 ┆ Ill ┆ Ill ┆ nul ┆ ftp ┆ 991 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ nul ┆ GSM ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 246 ┆ 138 ┆ 2_h ┆ 2_H ┆ 828 ┆ lic ┆ 24  ┆ 28  ┆     ┆     ┆ 92  ┆ o   ┆ 6   ┆ omi ┆ ds  ┆ 246 ┆ hry ┆ ant ┆ hol ┆ Lan ┆ 1st ┆ Yor ┆ Yor ┆ 16  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 828 ┆ :// ┆ :// ┆ 194 ┆     ┆ l   ┆ l   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ C   ┆ 291 ┆ umi ┆ N41 ┆ NK  ┆ 187 ┆ P   ┆ 4-0 ┆ 190 ┆ UMI ┆ .sr ┆ l   ┆ eri ┆ 2_H ┆ cc7 ┆ 356 ┆ 490 ┆ NK  ┆ ERA ┆ 2_H ┆ umi ┆ umi ┆ l   ┆ .sr ┆ 939 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 828 ┆ 828 ┆ ls  ┆ l   ┆ 828 ┆ 828 ┆ _ta ┆ 4-0 ┆ o   ┆ 6   ┆ NA8 ┆ 291 ┆ 214 ┆ 4-0 ┆ 194 │
│ 928 ┆ 982 ┆ s_h ┆ S_H ┆ 967 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ MI  ┆ sap ┆     ┆ c   ┆ wer ┆ 76  ┆ n,G ┆ is  ┆ ogy ┆ gon ┆ Ave ┆ k   ┆ k   ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 967 ┆ ftp ┆ ftp ┆ 364 ┆     ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ (in ┆ 653 ┆ na  ┆ 527 ┆ cel ┆ 734 ┆     ┆ 6-3 ┆ 140 ┆ NA  ┆ a.e ┆     ┆ c   ┆ S_H ┆ 72c ┆ 652 ┆ 09  ┆ cel ┆ TED ┆ S_H ┆ na  ┆ na  ┆     ┆ a.e ┆ 891 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 967 ┆ 967 ┆ wer ┆     ┆ 967 ┆ 967 ┆ x:t ┆ 6-3 ┆ sap ┆     ┆ 003 ┆ 653 ┆ 228 ┆ 6-3 ┆ 364 │
│ 77  ┆ 38  ┆ sf1 ┆ SF1 ┆ 5   ┆ May ┆ 4   ┆ 4   ┆     ┆     ┆ cel ┆ ien ┆     ┆ DNA ┆ e   ┆     ┆ rac ┆     ┆     ┆ e   ┆ nue ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆ 5   ┆ .nc ┆ .nc ┆ vs  ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ fer ┆ 20  ┆ Nov ┆ 440 ┆ l   ┆ 2   ┆     ┆ 0   ┆ 2;1 ┆     ┆ bi. ┆     ┆     ┆ SF1 ┆ e10 ┆     ┆ vs  ┆ l   ┆ _FI ┆ SF1 ┆ Nov ┆ Nov ┆     ┆ bi. ┆ 8   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ e   ┆     ┆ 5_r ┆ 5   ┆ err ┆ 0   ┆ ien ┆     ┆ 65  ┆ 20  ┆ 83  ┆ 0   ┆     │
│     ┆     ┆ _ip ┆ _IP ┆ vs  ┆ 28  ┆ vs  ┆ vs  ┆     ┆     ┆ ls  ┆ s   ┆     ┆     ┆ ali ┆     ┆ e,H ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ bi. ┆ GSE ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ vs  ┆ str ┆ vs  ┆     ┆ vs  ┆ 948 ┆     ┆ ac. ┆     ┆     ┆ _IP ┆ c30 ┆     ┆ 910 ┆ str ┆ LE; ┆ _IP ┆ aSe ┆ aSe ┆     ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ was ┆     ┆ 1   ┆ vs  ┆ est ┆ vs  ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ vs  ┆     │
│     ┆     ┆ _2  ┆ _2  ┆ GSM ┆ 202 ┆ Jan ┆ Jan ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆ ock ┆     ┆     ┆ lth ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆ 167 ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ SAM ┆ ess ┆ SRA ┆     ┆ 202 ┆ 688 ┆     ┆ uk/ ┆     ┆     ┆ _2  ┆ 688 ┆     ┆ 224 ┆ ess ┆ GEN ┆ _2  ┆ q   ┆ q   ┆     ┆ uk/ ┆ 928 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ hed ┆     ┆ vs  ┆ GSM ┆ ria ┆ 202 ┆     ┆     ┆     ┆ SRR ┆ SRS ┆ 202 ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ 583 ┆ 4   ┆ 25  ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆ eme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 583 ┆ .ni ┆ .ni ┆ 552 ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ 177 ┆ 600 ┆ N25 ┆ res ┆ 136 ┆     ┆ 2-0 ┆ 232 ┆     ┆ vol ┆     ┆     ┆ vs  ┆ 112 ┆     ┆ 49  ┆ res ┆ ERA ┆ vs  ┆ 600 ┆ 600 ┆     ┆ vol ┆ 428 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 583 ┆ GSM ┆ in  ┆     ┆ GSM ┆ 583 ┆ l;e ┆ 2-0 ┆     ┆     ┆     ┆ 177 ┆ 117 ┆ 2-0 ┆     │
│     ┆     ┆ nk9 ┆ NK9 ┆ 409 ┆ vs  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆ yer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 409 ┆ h.g ┆ h.g ┆ ,   ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆ 356 ┆ 0   ┆ 243 ┆ pon ┆ 165 ┆     ┆ 1-2 ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ NK9 ┆ 1da ┆     ┆     ┆ pon ┆ TED ┆ NK9 ┆ 0   ┆ 0   ┆     ┆ 1/f ┆ 979 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 409 ┆ 583 ┆ 1XP ┆     ┆ 583 ┆ 409 ┆ nv_ ┆ 1-2 ┆     ┆     ┆     ┆ 356 ┆ 613 ┆ 1-2 ┆     │
│     ┆     ┆ 2_h ┆ 2_H ┆ 1   ┆ Pub ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆ ov/ ┆ GSE ┆     ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆     ┆ 73  ┆ seq ┆ 265 ┆ se  ┆ 1   ┆     ┆ 7   ┆ 191 ┆     ┆ ast ┆     ┆     ┆ 2_H ┆ 0a2 ┆     ┆     ┆ se  ┆ _FI ┆ 2_H ┆     ┆ seq ┆     ┆ ast ┆ 8   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 1   ┆ 409 ┆ BS  ┆     ┆ 409 ┆ 1   ┆ tax ┆ 7   ┆     ┆     ┆     ┆ 73  ┆ 59  ┆ 7   ┆     │
│     ┆     ┆ sf1 ┆ SF1 ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆ 194 ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 556 ┆     ┆     ┆     ┆     ┆ uen ┆     ┆ sta ┆     ┆     ┆     ┆ 422 ┆     ┆ q/S ┆     ┆     ┆ SF1 ┆ e7f ┆     ┆     ┆ sta ┆ LE  ┆ SF1 ┆     ┆ uen ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 1_r ┆ and ┆     ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ip ┆ _IP ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆ 364 ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ tus ┆     ┆     ┆     ┆ 596 ┆     ┆ RR2 ┆     ┆     ┆ _IP ┆ 72; ┆     ┆     ┆ tus ┆     ┆ _IP ┆     ┆ cin ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ fix ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ Jan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 4-0 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ mod ┆     ┆     ┆     ┆ 4;1 ┆     ┆ 91/ ┆     ┆     ┆     ┆ 94e ┆     ┆     ┆ mod ┆     ┆     ┆     ┆ g:  ┆     ┆ 91/ ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆ 213 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 149 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ ula ┆     ┆     ┆     ┆ 820 ┆     ┆ 020 ┆     ┆     ┆     ┆ 71b ┆     ┆     ┆ ula ┆     ┆     ┆     ┆ GSM ┆     ┆ 020 ┆     ┆     ┆     ┆     ┆     ┆ 1/0 ┆ ;33 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 0-z ┆     ┆     ┆     ┆     ┆ 828 ┆     ┆ tes ┆     ┆     ┆     ┆ 935 ┆     ┆ /SR ┆     ┆     ┆     ┆ 029 ┆     ┆     ┆ tes ┆     ┆     ┆     ┆ 828 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 20/ ┆ 511 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 828 ┆ 828 ┆     ┆     ┆     ┆     ┆ N41 ┆ 469 ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆ ant ┆     ┆     ┆     ┆ 624 ┆     ┆ R29 ┆     ┆     ┆     ┆ 8c6 ┆     ┆     ┆ ant ┆     ┆     ┆     ┆ 967 ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆ 9nn ┆     ┆     ┆     ┆     ┆ 527 ┆ 287 ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆     ┆ i-t ┆     ┆     ┆     ┆     ┆     ┆ 165 ┆     ┆     ┆     ┆ c84 ┆     ┆     ┆ i-t ┆     ┆     ┆     ┆ 5:  ┆     ┆ 165 ┆     ┆     ┆     ┆     ┆     ┆ 291 ┆ 11; ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆ 440 ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ NK9 ┆     ┆ umo ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆     ┆     ┆ 116 ┆     ┆     ┆ umo ┆     ┆     ┆     ┆ NK9 ┆     ┆ 320 ┆     ┆     ┆     ┆     ┆     ┆ 653 ┆ 895 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆ SM8 ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ 2_H ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 089 ┆     ┆     ┆ r   ┆     ┆     ┆     ┆ 2_H ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 20/ ┆ 93; ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 289 ┆ 289 ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆     ┆ S_H ┆     ┆ imm ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆     ┆     ┆     ┆ eb5 ┆     ┆     ┆ imm ┆     ┆     ┆     ┆ S_H ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bow ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 675 ┆ 675 ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ SF1 ┆     ┆ uni ┆     ┆     ┆     ┆     ┆     ┆ 165 ┆     ┆     ┆     ┆ 39c ┆     ┆     ┆ uni ┆     ┆     ┆     ┆ SF1 ┆     ┆ 165 ┆     ┆     ┆     ┆     ┆     ┆ 291 ┆ 2;7 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆     ┆     ┆     ┆     ┆     ┆ _IP ┆     ┆ ty  ┆     ┆     ┆     ┆     ┆     ┆ 320 ┆     ┆     ┆     ┆ b74 ┆     ┆     ┆ ty  ┆     ┆     ┆     ┆ _IP ┆     ┆ 320 ┆     ┆     ┆     ┆     ┆     ┆ 653 ┆ 776 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆     ┆     ┆     ┆     ┆     ┆ _2  ┆     ┆ [Ch ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ ab  ┆     ┆     ┆ [Ch ┆     ┆     ┆     ┆ _2  ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 20_ ┆ ;11 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆ /GS ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ IP- ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ IP- ┆     ┆     ┆     ┆ Hom ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M82 ┆ M82 ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ tq. ┆     ┆     ┆     ┆ 5e2 ┆     ┆     ┆ seq ┆     ┆     ┆     ┆ o   ┆     ┆ tq. ┆     ┆     ┆     ┆     ┆     ┆ ast ┆ 0;1 ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 16. GSE166456 (ChIP-seq; YTHDC1)

- [Chromatin-associated YTHDC1 coordinates heat-induced reprogramming of gene expression](https://doi.org/10.1016/j.celrep.2022.111784)
- YTHDC1 の ChIP-seq のデータは、シスエレメントというより、gene body で見られるかを 調査することで、効果を発揮する
- `Heat-stress experiments were performed by immersion of the culture flasks or culture plates in a warm water bath for 1h at 43°C.`

In [34]:
GSE166456_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE166456/GSE166456_PEP/GSE166456_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1016/j.celrep.2022.111784").alias("reference_doi"),
    pl.lit("43 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE166456 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE166456.metadata.tsv",
    separator='\t'
)

GSE166456_combined = GSE166456_PEP.join(
    GSE166456,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE166456_combined = GSE166456_combined[[s.name for s in GSE166456_combined if not (s.null_count() == GSE166456_combined.height)]]

# display(GSE166456_combined)

In [35]:
defined_pairs_gse166456_chipseq = [
    ("SRX10059566", "SRX10059568"), # YTHDC1_HS vs. YTHDC1_UT
    ("SRX10059567", "SRX10059569")  # YTHDC1_HS_2 vs. YTHDC1_UT_2
]

paired_metada_df_gse166456 = create_paired_metadata(
    combined_df=GSE166456_combined,
    defined_sample_pairs=defined_pairs_gse166456_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse166456 is not None:
    paired_metada_df_gse166456.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE166456_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse166456)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 87)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ tre ┆ pas ┆ chi ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ atm ┆ sag ┆ p_a ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ent ┆ es  ┆ nti ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ bod ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ y   ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ lab ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ ora ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ tor ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ yth ┆ ChI ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ YTH ┆ GSM ┆ Pub ┆ Feb ┆ Dec ┆ SRA ┆ 1   ┆ HeL ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ros ┆ Gen ┆ UMR ┆ 141 ┆ Mon ┆ 343 ┆ Fra ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Hea ┆ 13- ┆ A30 ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 43  ┆ 60  ┆ Nex ┆ SAM ┆ Gen ┆ SRA ┆ ChI ┆ 202 ┆ 128 ┆ ILL ┆ ftp ┆ Gen ┆ YTH ┆ 1d3 ┆ SRP ┆ 255 ┆ Gen ┆ GEN ┆ YTH ┆ Nex ┆ Nex ┆ HeL ┆ ftp ┆ 194 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ GSM ┆ GEO ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 100 ┆ 100 ┆ dc1 ┆ P   ┆ o   ┆ GLE ┆     ┆ 136 ┆ DC1 ┆ 507 ┆ lic ┆ 09  ┆ 14  ┆     ┆     ┆ a   ┆ o   ┆ 6   ┆ omi ┆ 185 ┆ ema ┆ e   ┆ 900 ┆ rue ┆ tpe ┆ 96  ┆ nce ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 507 ┆ :// ┆ 166 ┆     ┆ 100 ┆ t   ┆ 15  ┆ 5-0 ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ tSe ┆ N17 ┆ ome ┆ 119 ┆ P   ┆ 2-1 ┆ 509 ┆ UMI ┆ .sr ┆ eri ┆ DC1 ┆ 868 ┆ 305 ┆ 409 ┆ ome ┆ ERA ┆ DC1 ┆ tSe ┆ tSe ┆ a   ┆ .sr ┆ 111 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 507 ┆ 507 ┆ ls  ┆ 507 ┆     ┆ _ta ┆ 2-1 ┆ o   ┆ 6   ┆ NA7 ┆ 136 ┆ 822 ┆ 2-1 ┆ 166 │
│ 595 ┆ 595 ┆ _hs ┆     ┆ sap ┆     ┆     ┆ 680 ┆ _HS ┆ 136 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 73  ┆ ry, ┆ Reg ┆ 2   ┆ de  ┆ lli ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 136 ┆ ftp ┆ 456 ┆     ┆ 595 ┆ sho ┆     ┆ 96A ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ q   ┆ 841 ┆ -wi ┆ 400 ┆     ┆ 2-1 ┆ 456 ┆ NA  ┆ a.e ┆ c   ┆ _HS ┆ b7f ┆ 514 ┆ 77  ┆ -wi ┆ TED ┆ _HS ┆ q   ┆ q   ┆ (ce ┆ a.e ┆ 425 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 136 ┆ 136 ┆ wer ┆ 136 ┆     ┆ x:t ┆ 2-1 ┆ sap ┆     ┆ 009 ┆ 680 ┆ 181 ┆ 2-1 ┆ 456 │
│ 66  ┆ 68  ┆ vs  ┆     ┆ ien ┆     ┆     ┆ 61  ┆ vs  ┆ 9   ┆ Dec ┆ 1   ┆ 2   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ ,Ki ┆ ula ┆ CNR ┆ la  ┆ er  ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 66  ┆ ck  ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 500 ┆ 818 ┆ de  ┆ 6   ┆     ┆ 5   ┆ 3   ┆     ┆ bi. ┆     ┆ vs  ┆ 1e4 ┆     ┆ vs  ┆ de  ┆ _FI ┆ vs  ┆ 500 ┆ 500 ┆ rvi ┆ bi. ┆ 2   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 9   ┆ 9_r ┆ e   ┆ 9   ┆     ┆ err ┆ 5   ┆ ien ┆     ┆ 96  ┆ 61  ┆ 9   ┆ 5   ┆     │
│     ┆     ┆ yth ┆     ┆ s   ┆     ┆     ┆ vs  ┆ YTH ┆ vs  ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ ern ┆ tio ┆ S-U ┆ car ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ seq ┆ vs  ┆ map ┆     ┆     ┆     ┆ vs  ┆     ┆ ac. ┆     ┆ YTH ┆ 92d ┆     ┆ 249 ┆ map ┆ LE  ┆ YTH ┆     ┆ seq ┆ x   ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ the ┆ vs  ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ dc1 ┆     ┆     ┆     ┆     ┆ SRR ┆ DC1 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆ n   ┆ M   ┆ don ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ Non ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ uen ┆ SAM ┆ s   ┆     ┆     ┆     ┆ 124 ┆     ┆ uk/ ┆     ┆ DC1 ┆ ef2 ┆     ┆ 316 ┆ s   ┆     ┆ DC1 ┆     ┆ uen ┆ ade ┆ uk/ ┆ 189 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ n   ┆ GSM ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ _ut ┆     ┆     ┆     ┆     ┆ 136 ┆ _UT ┆ 507 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lab ┆     ┆ ill ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 507 ┆ .ni ┆     ┆     ┆ 100 ┆ e   ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ cin ┆ N17 ┆ of  ┆     ┆     ┆     ┆ 836 ┆     ┆ vol ┆     ┆ _UT ┆ d48 ┆     ┆ 67  ┆ of  ┆     ┆ _UT ┆     ┆ cin ┆ noc ┆ vol ┆ 480 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 507 ┆ GSM ┆ cro ┆ 507 ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 136 ┆ 822 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 680 ┆     ┆ 137 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 137 ┆ h.g ┆     ┆     ┆ 595 ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ g:  ┆ 841 ┆ YTH ┆     ┆     ┆     ┆ 598 ┆     ┆ 1/f ┆     ┆     ┆ c39 ┆     ┆     ┆ YTH ┆     ┆     ┆     ┆ g:  ┆ arc ┆ 1/f ┆ 669 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 137 ┆ 507 ┆ ssl ┆ 137 ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 680 ┆ 182 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 63  ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆     ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆ GSM ┆ 816 ┆ DC1 ┆     ┆     ┆     ┆ 9   ┆     ┆ ast ┆     ┆     ┆ 50e ┆     ┆     ┆ DC1 ┆     ┆     ┆     ┆ GSM ┆ ino ┆ ast ┆ 2   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 1   ┆ 137 ┆ ink ┆ 1   ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 63  ┆ 0   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ elr ┆     ┆     ┆ 507 ┆     ┆ upo ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 4b7 ┆     ┆     ┆ upo ┆     ┆     ┆     ┆ 507 ┆ ma  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 1_r ┆ ed, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ ep. ┆     ┆     ┆ 136 ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 63  ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 136 ┆ fro ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 202 ┆     ┆     ┆ 9:  ┆     ┆ Hea ┆     ┆     ┆     ┆     ┆     ┆ 36/ ┆     ┆     ┆ vs  ┆     ┆     ┆ Hea ┆     ┆     ┆     ┆ 9:  ┆ m   ┆ 36/ ┆     ┆     ┆     ┆     ┆     ┆ R13 ┆ 213 ┆     ┆     ┆ lec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 2.1 ┆     ┆     ┆ YTH ┆     ┆ t-s ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     ┆     ┆ 649 ┆     ┆     ┆ t-s ┆     ┆     ┆     ┆ YTH ┆ Ame ┆ 061 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX1 ┆ 117 ┆     ┆     ┆ DC1 ┆     ┆ hoc ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ fe2 ┆     ┆     ┆ hoc ┆     ┆     ┆     ┆ DC1 ┆ ric ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 61/ ┆ 511 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 507 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N17 ┆ 005 ┆ 84  ┆     ┆     ┆ _HS ┆     ┆ k   ┆     ┆     ┆     ┆     ┆     ┆ R13 ┆     ┆     ┆ 586 ┆     ┆     ┆ k   ┆     ┆     ┆     ┆ _HS ┆ an  ┆ R13 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ lys ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 841 ┆ 956 ┆     ┆     ┆     ┆ Hom ┆     ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆ 668 ┆     ┆     ┆ 234 ┆     ┆     ┆ (HS ┆     ┆     ┆     ┆ Hom ┆ Typ ┆ 668 ┆     ┆     ┆     ┆     ┆     ┆ 136 ┆ 11; ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 818 ┆ 6   ┆     ┆     ┆     ┆ o   ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     ┆     ┆ 906 ┆     ┆     ┆ )   ┆     ┆     ┆     ┆ o   ┆ e   ┆ 061 ┆     ┆     ┆     ┆     ┆     ┆ 680 ┆ 895 ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆ sap ┆     ┆ or  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 6a9 ┆     ┆     ┆ or  ┆     ┆     ┆     ┆ sap ┆ Cul ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 61/ ┆ 93; ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 071 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆ ien ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆ R13 ┆     ┆     ┆ dc9 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ ien ┆ tur ┆ R13 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 369 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆ s   ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ 668 ┆     ┆     ┆ c1e ┆     ┆     ┆ unt ┆     ┆     ┆     ┆ s   ┆ e   ┆ 668 ┆     ┆     ┆     ┆     ┆     ┆ 136 ┆ 2;7 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆     ┆     ┆     ┆ ChI ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     ┆     ┆ bb7 ┆     ┆     ┆ rea ┆     ┆     ┆     ┆ ChI ┆ Col ┆ 061 ┆     ┆     ┆     ┆     ┆     ┆ 680 ┆ 776 ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆     ┆     ┆     ┆ P-S ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ b6b ┆     ┆     ┆ ted ┆     ┆     ┆     ┆ P-S ┆ lec ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ 61. ┆ ;11 ┆     ┆     ┆ "Ch ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆     ┆     ┆     ┆ eq  ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆ d3  ┆     ┆     ┆ con ┆     ┆     ┆     ┆ eq  ┆ tio ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ IP- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M50 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆     ┆     ┆     ┆ vs  ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆ vs  ┆ n,  ┆ .gz ┆     ┆     ┆     ┆     ┆     ┆ tq. ┆ 0;1 ┆     ┆     ┆ IT  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 17. GSE209667 (ChIP-seq; HSF1/PolII)

- [Transcriptional responses of cancer cells to heat shock-inducing stimuli involve amplification of robust HSF1 binding](https://doi.org/10.1038/s41467-023-43157-7)
- Super series: [GSE209687](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE209687)
- 下記のような記述があることから、42℃ 60 min であると考えられる
- `Results; HSF1 binding is a temperature-independent hallmark of HSR; We began by examining MCF7 breast adenocarcinoma cells during temperature-induced Heat Shock Response (HSR) (Fig. 1, Supplementary Data 1, Supplementary Fig. 1a). A 60-min incubation at 42 °C induced a control HSP gene seen as spreading of the Pol II and nascent RNA signal into the gene body (Fig. 1a).`

In [36]:
GSE209667_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE209667/GSE209667_PEP/GSE209667_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens") &
    (pl.col("treatment") != "Arsenic")
).with_columns(
    pl.lit("https://doi.org/10.1038/s41467-023-43157-7").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE209667 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE209667.metadata.tsv",
    separator='\t'
)

GSE209667_combined = GSE209667_PEP.join(
    GSE209667,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE209667_combined = GSE209667_combined[[s.name for s in GSE209667_combined if not (s.null_count() == GSE209667_combined.height)]]

display(GSE209667_combined)

shape: (23, 88)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ cel ┆ cel ┆ chi ┆ tre ┆ ass ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ p_a ┆ atm ┆ emb ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ ine ┆ ype ┆ nti ┆ ent ┆ ly  ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ bod ┆ --- ┆ --- ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ str ┆ y   ┆ str ┆ str ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ mcf ┆ MCF ┆ GSM ┆ Pub ┆ Jul ┆ Oct ┆ SRA ┆ 1   ┆ MCF ┆ Hom ┆ 960 ┆ gen ┆ Raw ┆ GPL ┆ Ser ┆ ser ┆ Nec ┆ Bio ┆ Uni ┆ Gra ┆ Nor ┆ 582 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ MCF ┆ mam ┆ Rpb ┆ Unt ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ Tra ┆ SRA ┆ ChI ┆ 202 ┆ 211 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ MCF ┆ 71e ┆ SRP ┆ 393 ┆ Tra ┆ GEN ┆ MCF ┆ Ill ┆ Ill ┆ mam ┆ ftp ┆ 118 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ App ┆ mis ┆ GSM ┆ MCF ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 7_n ┆ 7   ┆ 638 ┆ lic ┆ 25  ┆ 30  ┆     ┆     ┆ 7   ┆ o   ┆ 6   ┆ omi ┆ fil ┆ 203 ┆ gei ┆ gei ┆ hae ┆ med ┆ ver ┆ nd  ┆ th  ┆ 02  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 638 ┆ :// ┆ 209 ┆     ┆ 166 ┆ 7   ┆ mar ┆ 1   ┆ rea ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 206 ┆ umi ┆ N29 ┆ nsc ┆ 146 ┆ P   ┆ 3-1 ┆ 340 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 7   ┆ 186 ┆ 387 ┆ 633 ┆ nsc ┆ ERA ┆ 7   ┆ umi ┆ umi ┆ mar ┆ .sr ┆ 090 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 638 ┆ 638 ┆ rox ┆ sin ┆ 638 ┆ 7   ┆ 638 ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA8 ┆ 206 ┆ 142 ┆ 3-1 ┆ 209 │
│ hs_ ┆ NHS ┆ 308 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ es  ┆ 01  ┆ ,,N ┆ .ne ┆ v   ┆ ica ┆ sit ┆ For ┆ Dak ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 308 ┆ ftp ┆ 667 ┆     ┆ 460 ┆     ┆ y   ┆ NTD ┆ ted ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 223 ┆ na  ┆ 938 ┆ rip ┆ 198 ┆     ┆ 1-0 ┆ 021 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ NHS ┆ 1da ┆ 953 ┆ 47  ┆ rip ┆ TED ┆ NHS ┆ na  ┆ na  ┆ y   ┆ a.e ┆ 041 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 308 ┆ 308 ┆ ima ┆ g   ┆ 308 ┆     ┆ 308 ┆ x:t ┆ 1-0 ┆ sap ┆     ┆ 620 ┆ 223 ┆ 804 ┆ 1-0 ┆ 667 │
│ rna ┆ RNA ┆ 8   ┆ Oct ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ wer ┆     ┆ ech ┆ cha ┆ Lab ┆ l   ┆ y   ┆ ks  ┆ ota ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 8   ┆ .nc ┆ ,   ┆     ┆ 91  ┆     ┆ gla ┆ (D8 ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 71  ┆ HiS ┆ 377 ┆ tio ┆ 4   ┆     ┆ 2   ┆ 0;2 ┆     ┆ bi. ┆     ┆     ┆ RNA ┆ 6c4 ┆     ┆     ┆ tio ┆ _FI ┆ RNA ┆ HiS ┆ HiS ┆ gla ┆ bi. ┆ 00  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ tel ┆     ┆ 8_r ┆     ┆ 8   ┆ err ┆ 1   ┆ ien ┆     ┆ 76  ┆ 71  ┆ 50  ┆ 1   ┆     │
│ _po ┆ Pol ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ e   ┆     ┆ aev ┆ ev@ ┆     ┆ Sci ┆ of  ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆ bi. ┆ GSE ┆     ┆     ┆     ┆ nd, ┆ L4Y ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ eq  ┆     ┆ nal ┆     ┆     ┆     ┆ 119 ┆     ┆ ac. ┆     ┆     ┆ Pol ┆ 32d ┆     ┆     ┆ nal ┆ LE; ┆ Pol ┆ eq  ┆ eq  ┆ nd, ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ y   ┆     ┆ 1   ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ l_i ┆ II  ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ada ┆     ┆     ┆ und ┆     ┆ enc ┆ Nor ┆     ┆     ┆     ┆     ┆ 400 ┆     ┆     ┆     ┆     ┆ nlm ┆ 209 ┆     ┆     ┆     ┆ ade ┆ ),  ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ 400 ┆     ┆ res ┆     ┆     ┆     ┆ 441 ┆     ┆ uk/ ┆     ┆     ┆ II  ┆ 790 ┆     ┆     ┆ res ┆ GEN ┆ II  ┆ 400 ┆ 400 ┆ ade ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ 2x1 ┆     ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ i_r ┆ rep ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pte ┆     ┆     ┆ .ed ┆     ┆ es  ┆ th  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ .ni ┆ 687 ┆     ┆     ┆     ┆ noc ┆ Cel ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ 0   ┆     ┆ pon ┆     ┆     ┆     ┆ 394 ┆     ┆ vol ┆     ┆     ┆ rep ┆ 0c0 ┆     ┆     ┆ pon ┆ ERA ┆ rep ┆ 0   ┆ 0   ┆ noc ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ 07  ┆     ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ep_ ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r-t ┆     ┆     ┆ u   ┆     ┆     ┆ Dak ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆ arc ┆ l   ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆ seq ┆     ┆ ses ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 1   ┆ a0d ┆     ┆     ┆ ses ┆ TED ┆ 1   ┆     ┆ seq ┆ arc ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rim ┆     ┆     ┆     ┆     ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆ ino ┆ Sig ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆     ┆ uen ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆ 7bc ┆     ┆     ┆ of  ┆ _FI ┆     ┆     ┆ uen ┆ ino ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ ma  ┆ nal ┆     ┆     ┆ v/b ┆ v/s ┆ 467 ┆     ┆     ┆     ┆ cin ┆     ┆ can ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆     ┆ 838 ┆     ┆     ┆ can ┆ LE  ┆     ┆     ┆ cin ┆ ma  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ g:  ┆     ┆ cer ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆     ┆ f8; ┆     ┆     ┆ cer ┆     ┆     ┆     ┆ g:  ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 3-4 ┆     ┆     ┆     ┆ GSM ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ 06/ ┆     ┆     ┆     ┆ 1a5 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ GSM ┆     ┆ 06/ ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 315 ┆     ┆     ┆     ┆ 638 ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆ 071 ┆     ┆     ┆     ┆ a54 ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ 638 ┆     ┆ 071 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX1 ┆ 7-7 ┆     ┆     ┆     ┆ 308 ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ 308 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 71/ ┆ 511 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N29 ┆ 664 ┆     ┆     ┆     ┆     ┆ 8:  ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆     ┆     ┆     ┆ 061 ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ 8:  ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 938 ┆ 609 ┆     ┆     ┆     ┆     ┆ MCF ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆     ┆ 877 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ MCF ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 377 ┆ 1   ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ 371 ┆     ┆     ┆     ┆ be8 ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ 7   ┆     ┆ 371 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 8b0 ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ NHS ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 71/ ┆ 93; ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 383 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆ ind ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆     ┆     ┆     ┆ a3d ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ RNA ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ eth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆ uci ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆     ┆ 1ba ┆     ┆     ┆ uci ┆     ┆     ┆     ┆ Pol ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 2;7 ┆     ┆     ┆ ano ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆ 371 ┆     ┆     ┆     ┆ 3b0 ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆ II  ┆     ┆ 371 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 776 ┆     ┆     ┆ l-f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hg1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆ sti ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ c1  ┆     ┆     ┆ sti ┆     ┆     ┆     ┆ rep ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 71_ ┆ ;11 ┆     ┆     ┆ ree ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆     ┆ mul ┆     ┆     ┆     ┆ 1   ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [37]:
defined_pairs_gse209667_chipseq = [

    # pair4_GSE209667_hsf1_k562_hs_42C_60min.txt (ChIP-Atlas には登録されていない)
    # pair4_GSE209667_hsf1_k562_ctrl.txt (ChIP-Atlas には登録されていない)
    ("SRX16646100", "SRX16646099"), # k562_hs_hsf1_rep_1 vs. k562_nhs_hsf1_rep_1
    ("SRX16646111", "SRX16646103"), # k562_hs_hsf1_rep_2 vs. k562_nhs_hsf1_rep_2

    # pair24_GSE209667_pol2_hs_42C_60min_mcf7.txt
    # pair24_GSE209667_pol2_ctrl_mcf7.txt
    ("SRX16646101", "SRX16646091"), # mcf7_hs_rna_pol_ii_rep_1 vs. mcf7_nhs_rna_pol_ii_rep_1
    ("SRX16646106", "SRX16646105"), # mcf7_hs_rna_pol_ii_rep_2 vs. mcf7_nhs_rna_pol_ii_rep_2
    # ("SRX16646109", "SRX16646108"), # mcf7_hs_h3k4me3_rep_1 vs. mcf7_nhs_h3k4me3_rep_1
    # ("SRX16646092", "SRX16646110"), # mcf7_hs_h3k4me3_rep_2 vs. mcf7_nhs_h3k4me3_rep_2


    # pair5_GSE209667_hsf1_mcf7_hs_42C_60min.txt
    # pair5_GSE209667_hsf1_mcf7_ctrl.txt
    ("SRX16646094", "SRX16646093"), # mcf7_hs_hsf1_rep_1 vs. mcf7_nhs_hsf1_rep_1
    ("SRX16646097", "SRX16646096"), # mcf7_hs_hsf1_rep_2 vs. mcf7_nhs_hsf1_rep_2

    # pair6_GSE209667_hsf1_polyclonal_ab_hs_42C_60min.txt
    # pair6_GSE209667_hsf1_polyclonal_ab_ctrl.txt
    ("SRX16646115", "SRX16646113"), # mcf7_hsf1_hs_polyclonal_ab_rep_1 vs. mcf7_hsf1_nhs_polyclonal_ab_rep_1
    ("SRX16646116", "SRX16646114")  # mcf7_hsf1_hs_polyclonal_ab_rep_2 vs. mcf7_hsf1_nhs_polyclonal_ab_rep_2
]

paired_metada_df_gse209667 = create_paired_metadata(
    combined_df=GSE209667_combined,
    defined_sample_pairs=defined_pairs_gse209667_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse209667 is not None:
    paired_metada_df_gse209667.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE209667_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse209667)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (8, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ cel ┆ cel ┆ chi ┆ tre ┆ ass ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ l_l ┆ l_t ┆ p_a ┆ atm ┆ emb ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ine ┆ ype ┆ nti ┆ ent ┆ ly  ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ bod ┆ --- ┆ --- ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ y   ┆ str ┆ str ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ k56 ┆ K56 ┆ GSM ┆ Pub ┆ Jul ┆ Oct ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ Raw ┆ GPL ┆ Ser ┆ ser ┆ Nec ┆ Bio ┆ Uni ┆ Gra ┆ Nor ┆ 582 ┆ USA ┆ HiS ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ K56 ┆ bon ┆ HSF ┆ Hea ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ HiS ┆ SAM ┆ Tra ┆ SRA ┆ ChI ┆ 202 ┆ 274 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ K56 ┆ 284 ┆ SRP ┆ 513 ┆ Tra ┆ GEN ┆ K56 ┆ HiS ┆ HiS ┆ bon ┆ ftp ┆ 155 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ App ┆ mis ┆ GSM ┆ K56 ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 166 ┆ 166 ┆ 2_h ┆ 2   ┆ 638 ┆ lic ┆ 25  ┆ 30  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ fil ┆ 207 ┆ gei ┆ gei ┆ hae ┆ med ┆ ver ┆ nd  ┆ th  ┆ 02  ┆     ┆ eq  ┆ P   ┆ omi ┆ P-S ┆ 638 ┆ :// ┆ 209 ┆     ┆ 2   ┆ e   ┆ 1   ┆ t   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 206 ┆ eq  ┆ N29 ┆ nsc ┆ 146 ┆ P   ┆ 3-1 ┆ 975 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 2   ┆ 881 ┆ 387 ┆ 942 ┆ nsc ┆ ERA ┆ 2   ┆ eq  ┆ eq  ┆ e   ┆ .sr ┆ 210 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 638 ┆ 638 ┆ rox ┆ sin ┆ 638 ┆ 2   ┆ 638 ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA8 ┆ 206 ┆ 142 ┆ 3-1 ┆ 209 │
│ 461 ┆ 460 ┆ s_h ┆ HS  ┆ 310 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ es  ┆ 95  ┆ ,,N ┆ .ne ┆ v   ┆ ica ┆ sit ┆ For ┆ Dak ┆     ┆     ┆ X   ┆     ┆ c   ┆ eq  ┆ 310 ┆ ftp ┆ 667 ┆     ┆     ┆ mar ┆ (En ┆ sho ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 223 ┆ X   ┆ 938 ┆ rip ┆ 198 ┆     ┆ 1-0 ┆ 507 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ HS  ┆ dfb ┆ 953 ┆ 06  ┆ rip ┆ TED ┆ HS  ┆ X   ┆ X   ┆ mar ┆ a.e ┆ 502 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 310 ┆ 310 ┆ ima ┆ g   ┆ 310 ┆     ┆ 310 ┆ x:t ┆ 1-0 ┆ sap ┆     ┆ 620 ┆ 223 ┆ 804 ┆ 1-0 ┆ 667 │
│ 00  ┆ 99  ┆ sf1 ┆ HSF ┆ 5   ┆ Oct ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ wer ┆     ┆ ech ┆ cha ┆ Lab ┆ l   ┆ y   ┆ ks  ┆ ota ┆     ┆     ┆ Ten ┆     ┆     ┆     ┆ 5   ┆ .nc ┆ ,   ┆     ┆     ┆ row ┆ zo  ┆ ck  ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 64  ┆ Ten ┆ 360 ┆ tio ┆ 4   ┆     ┆ 1   ┆ 4;2 ┆     ┆ bi. ┆     ┆     ┆ HSF ┆ 2c7 ┆     ┆ vs  ┆ tio ┆ _FI ┆ HSF ┆ Ten ┆ Ten ┆ row ┆ bi. ┆ 12  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ tel ┆     ┆ 5_r ┆     ┆ 5   ┆ err ┆ 1   ┆ ien ┆     ┆ 76  ┆ 64  ┆ 59  ┆ 1   ┆     │
│     ┆     ┆ _re ┆ 1   ┆ vs  ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ e   ┆     ┆ aev ┆ ev@ ┆     ┆ Sci ┆ of  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆     ┆ ,   ┆ #   ┆ vs  ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ seq ┆ vs  ┆ nal ┆     ┆     ┆     ┆ 762 ┆     ┆ ac. ┆     ┆     ┆ 1   ┆ 527 ┆     ┆ 493 ┆ nal ┆ LE; ┆ 1   ┆     ┆ seq ┆ ,   ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ y   ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ p_1 ┆ rep ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ada ┆     ┆     ┆ und ┆     ┆ enc ┆ Nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 209 ┆     ┆     ┆ mye ┆ ADI ┆ Unt ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ uen ┆ SAM ┆ res ┆     ┆     ┆     ┆ 634 ┆     ┆ uk/ ┆     ┆     ┆ rep ┆ 191 ┆     ┆ 900 ┆ res ┆ GEN ┆ rep ┆     ┆ uen ┆ mye ┆ uk/ ┆ 149 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ 2x1 ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆ 1   ┆ 638 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pte ┆     ┆     ┆ .ed ┆     ┆ es  ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆ .ni ┆ 687 ┆     ┆     ┆ log ┆ -SP ┆ rea ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 206 ┆ cin ┆ N29 ┆ pon ┆     ┆     ┆     ┆ 622 ┆     ┆ vol ┆     ┆     ┆ 1   ┆ fd0 ┆     ┆ 22  ┆ pon ┆ ERA ┆ 1   ┆     ┆ cin ┆ log ┆ vol ┆ 157 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 638 ┆ GSM ┆ 07  ┆     ┆ GSM ┆     ┆ 638 ┆ l;e ┆     ┆     ┆     ┆     ┆ 206 ┆ 142 ┆     ┆     │
│     ┆     ┆ k56 ┆ vs  ┆ 310 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r-t ┆     ┆     ┆ u   ┆     ┆     ┆ Dak ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 310 ┆ h.g ┆     ┆     ┆     ┆ eno ┆ A-9 ┆ ted ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ 223 ┆ g:  ┆ 938 ┆ ses ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ vs  ┆ fbc ┆     ┆     ┆ ses ┆ TED ┆ vs  ┆     ┆ g:  ┆ eno ┆ 1/f ┆ 866 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 310 ┆ 638 ┆ cel ┆     ┆ 638 ┆     ┆ 310 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 223 ┆ 804 ┆     ┆     │
│     ┆     ┆ 2_n ┆ K56 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rim ┆     ┆     ┆     ┆     ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆     ┆     ┆     ┆ us  ┆ 01- ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆ 65  ┆ GSM ┆ 361 ┆ of  ┆     ┆     ┆     ┆ 262 ┆     ┆ ast ┆     ┆     ┆ K56 ┆ 72c ┆     ┆     ┆ of  ┆ _FI ┆ K56 ┆     ┆ GSM ┆ us  ┆ ast ┆ 44  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 4   ┆ 310 ┆ ls  ┆     ┆ 310 ┆     ┆ 4   ┆ tax ┆     ┆     ┆     ┆     ┆ 65  ┆ 58  ┆     ┆     │
│     ┆     ┆ hs_ ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ leu ┆ D)  ┆     ┆     ┆ v/b ┆ v/s ┆ 467 ┆     ┆     ┆     ┆ 638 ┆     ┆ can ┆     ┆     ┆     ┆ 635 ┆     ┆ q/S ┆     ┆     ┆ 2   ┆ 98b ┆     ┆     ┆ can ┆ LE  ┆ 2   ┆     ┆ 638 ┆ leu ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 4_r ┆ wer ┆     ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hsf ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆ kem ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ 310 ┆     ┆ cer ┆     ┆     ┆     ┆ 770 ┆     ┆ RR2 ┆     ┆     ┆ NHS ┆ eb; ┆     ┆     ┆ cer ┆     ┆ NHS ┆     ┆ 310 ┆ kem ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ e   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1_r ┆ HSF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆ amp ┆ ter ┆ 3-4 ┆     ┆     ┆     ┆ 5:  ┆     ┆ cel ┆     ┆     ┆     ┆ 8;2 ┆     ┆ 06/ ┆     ┆     ┆ HSF ┆ 3f4 ┆     ┆     ┆ cel ┆     ┆ HSF ┆     ┆ 5:  ┆ ia  ┆ 06/ ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep_ ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 315 ┆     ┆     ┆     ┆ K56 ┆     ┆ ls  ┆     ┆     ┆     ┆ 642 ┆     ┆ 064 ┆     ┆     ┆ 1   ┆ ab4 ┆     ┆     ┆ ls  ┆     ┆ 1   ┆     ┆ K56 ┆     ┆ 064 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX1 ┆ 7-7 ┆     ┆     ┆     ┆ 2   ┆     ┆ to  ┆     ┆     ┆     ┆ 234 ┆     ┆ /SR ┆     ┆     ┆ rep ┆ ed1 ┆     ┆     ┆ to  ┆     ┆ rep ┆     ┆ 2   ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 64/ ┆ 511 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N29 ┆ 664 ┆     ┆     ┆     ┆     ┆ HS  ┆     ┆ hea ┆     ┆     ┆     ┆ 234 ┆     ┆ R20 ┆     ┆     ┆ 1   ┆ 1a1 ┆     ┆     ┆ hea ┆     ┆ 1   ┆     ┆ HS  ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 938 ┆ 610 ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆     ┆ d0e ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ HSF ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 360 ┆ 0   ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ 364 ┆     ┆     ┆     ┆ 532 ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ 1   ┆     ┆ 364 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ rep ┆     ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ d56 ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ rep ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 64/ ┆ 93; ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 383 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ ind ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆     ┆     ┆     ┆ 357 ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ 1   ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ eth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 105 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ uci ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆     ┆ 2b0 ┆     ┆     ┆ uci ┆     ┆     ┆     ┆ Hom ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 2;7 ┆     ┆     ┆ ano ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆ 364 ┆     ┆     ┆     ┆ ced ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆ o   ┆     ┆ 364 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 776 ┆     ┆     ┆ l-f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hg1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆     ┆     ┆     ┆     ┆ sap ┆     ┆ sti ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ 05  ┆     ┆     ┆ sti ┆     ┆     ┆     ┆ sap ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 64_ ┆ ;11 ┆     ┆     ┆ ree ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆     ┆     ┆     ┆     ┆ ien ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ mul ┆     ┆     ┆     ┆ ien ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 18. GSE270671 (ChIP-seq; HSF1)

- [An HSF1–JMJD6–HSP feedback circuit promotes cell adaptation to proteotoxic stress](https://doi.org/10.1073/pnas.2313370121)
- Appendix 01 (PDF) に以下のような記載があるため、条件は 42℃, 60 min であると考えられる
- `Treatments. ... For the heat shock experiments, cells were heat shocked at 42 ˚C for 1 hour. ...`

In [38]:
GSE270671_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE270671/GSE270671_PEP/GSE270671_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1073/pnas.2313370121").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "sample_geo_accession": "library_name",
        "big_key": "experiment_accession"
    }
)

GSE270671 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE270671.metadata.tsv",
    separator='\t'
).unique(subset=["library_name", "experiment_accession"], keep="first")

GSE270671_combined = GSE270671_PEP.join(
    GSE270671,
    on=["library_name", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE270671_combined = GSE270671_combined[[s.name for s in GSE270671_combined if not (s.null_count() == GSE270671_combined.height)]]

display(GSE270671_combined)

shape: (16, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ lib ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ rar ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ y_n ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ ame ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ --- ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ str ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ i64 ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ l_c ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆ str ┆ str ┆ i64 ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ pc3 ┆ PC3 ┆ GSM ┆ Pub ┆ Jun ┆ Jul ┆ SRA ┆ 1   ┆ PC3 ┆ Hom ┆ 960 ┆ Cel ┆ gen ┆ GPL ┆ Mar ┆ men ┆ 312 ┆ Mar ┆ Bio ┆ Nor ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ PC3 ┆ Pro ┆ siN ┆ Bas ┆ hg3 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Nex ┆ SAM ┆ An  ┆ SRA ┆ ChI ┆ 202 ┆ 147 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ PC3 ┆ 4ca ┆ SRP ┆ 460 ┆ An  ┆ GEN ┆ PC3 ┆ Nex ┆ Nex ┆ Pro ┆ ftp ┆ 229 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ PC3 ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ m_s ┆ M,  ┆ 834 ┆ lic ┆ 24  ┆ 18  ┆     ┆     ┆ M   ┆ o   ┆ 6   ┆ ls  ┆ omi ┆ 185 ┆ c,L ┆ dil ┆ 503 ┆ c   ┆ che ┆ thw ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 834 ┆ :// ┆ 270 ┆     ┆ 253 ┆ M   ┆ sta ┆ T   ┆ al  ┆ 8   ┆ Wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 298 ┆ tSe ┆ N42 ┆ HSF ┆ 190 ┆ P   ┆ 4-0 ┆ 407 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ M,  ┆ 268 ┆ 520 ┆ 587 ┆ HSF ┆ ERA ┆ M,  ┆ tSe ┆ tSe ┆ sta ┆ .sr ┆ 794 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 834 ┆ 834 ┆ ls  ┆ sin ┆ 834 ┆ M   ┆ _ta ┆ 4-0 ┆ o   ┆ 6   ┆ NA1 ┆ 298 ┆ 220 ┆ 4-0 ┆ 270 │
│ int ┆ siN ┆ 977 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ c   ┆ 73  ┆ ,Me ┆ lo@ ┆ 486 ┆ Men ┆ mis ┆ est ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 977 ┆ ftp ┆ 671 ┆     ┆ 809 ┆     ┆ te  ┆     ┆     ┆     ┆ ,   ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 846 ┆ q   ┆ 017 ┆ 1-J ┆ 678 ┆     ┆ 7-2 ┆ 188 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ siN ┆ ad8 ┆ 857 ┆ 2   ┆ 1-J ┆ TED ┆ siN ┆ q   ┆ q   ┆ te  ┆ a.e ┆ 952 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 977 ┆ 977 ┆ wer ┆ g   ┆ 977 ┆     ┆ x:t ┆ 7-2 ┆ sap ┆     ┆ 127 ┆ 846 ┆ 462 ┆ 7-2 ┆ 671 │
│ _ba ┆ T,  ┆ 9   ┆ Jul ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ DNA ┆     ┆ ndi ┆ nor ┆ 2   ┆ dil ┆ try ┆ ern ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ 36  ┆     ┆ can ┆     ┆     ┆     ┆ nar ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 83  ┆ 500 ┆ 728 ┆ MJD ┆ 0   ┆     ┆ 3   ┆     ┆     ┆ bi. ┆     ┆     ┆ T,  ┆ b3d ┆     ┆     ┆ MJD ┆ _FI ┆ T,  ┆ 500 ┆ 500 ┆ can ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 9   ┆ 9_r ┆ e   ┆     ┆ 9_r ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 661 ┆ 83  ┆ 88  ┆ 3   ┆     │
│ sal ┆ Bas ┆     ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ gro ┆     ┆     ┆ llo ┆ thw ┆     ┆ lo  ┆ and ┆ Uni ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆     ┆ row ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ seq ┆     ┆ 6-H ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ Bas ┆ b1d ┆     ┆     ┆ 6-H ┆ LE  ┆ Bas ┆     ┆ seq ┆ cer ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 3   ┆ fix ┆     ┆ 1   ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ _hs ┆ al, ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wn  ┆     ┆     ┆     ┆ est ┆     ┆     ┆ Mol ┆ ver ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ Pea ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ uen ┆     ┆ SP  ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆ al, ┆ 6a0 ┆     ┆     ┆ SP  ┆     ┆ al, ┆     ┆ uen ┆ cel ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ f1_ ┆ HSF ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ ern ┆     ┆     ┆ ecu ┆ sit ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ k   ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ cin ┆     ┆ fee ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ HSF ┆ 79d ┆     ┆     ┆ fee ┆     ┆ HSF ┆     ┆ cin ┆ l   ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ chi ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆ lar ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆     ┆ g:  ┆     ┆ dba ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 1   ┆ 77e ┆     ┆     ┆ dba ┆     ┆ 1   ┆     ┆ g:  ┆ lin ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ p_b ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆     ┆ GSM ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ ChI ┆ 5e4 ┆     ┆     ┆ ck  ┆     ┆ ChI ┆     ┆ GSM ┆ e   ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ iol ┆ P,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ s.2 ┆     ┆     ┆     ┆ 834 ┆     ┆ cir ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ P,  ┆ 564 ┆     ┆     ┆ cir ┆     ┆ P,  ┆     ┆ 834 ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ _re ┆ bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5%  ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 313 ┆     ┆     ┆     ┆ 977 ┆     ┆ cui ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆ bio ┆ d5  ┆     ┆     ┆ cui ┆     ┆ bio ┆     ┆ 977 ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ p_1 ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CO2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 370 ┆     ┆     ┆     ┆ 9:  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 98/ ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ t   ┆     ┆ l   ┆     ┆ 9:  ┆     ┆ 98/ ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆ 213 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 121 ┆     ┆     ┆     ┆ PC3 ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ 083 ┆     ┆     ┆ rep ┆     ┆     ┆     ┆ pro ┆     ┆ rep ┆     ┆ PC3 ┆     ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆ 8/0 ┆ ;33 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆     ┆     ┆     ┆     ┆ M,  ┆     ┆ mot ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ mot ┆     ┆ 1   ┆     ┆ M,  ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 83/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N42 ┆ 538 ┆     ┆     ┆     ┆     ┆ siN ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ siN ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆ 093 ┆     ┆     ┆     ┆     ┆ T,  ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ 884 ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ T,  ┆     ┆ 884 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 11; ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 728 ┆ 6   ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 683 ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ Bas ┆     ┆ 683 ┆     ┆     ┆     ┆     ┆     ┆ 846 ┆ 895 ┆     ┆     ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al, ┆     ┆ ada ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆     ┆ ada ┆     ┆     ┆     ┆ al, ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 83/ ┆ 93; ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 349 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆ pta ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆     ┆ pta ┆     ┆     ┆     ┆ HSF ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 779 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ 884 ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 1   ┆     ┆ 884 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 2;7 ┆     ┆     ┆ que ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [39]:
defined_pairs_gse270671_chipseq = [

    # pair7_GSE270671_hsf1_pc3m_sijmjd6_hs_42C_60min.txt
    # pair7_GSE270671_hsf1_pc3m_sijmjd6_ctrl.txt
    ("SRX25380948", "SRX25380940"), # pc3m_sijmjd6_hs_hsf1_chip_biol_rep_1 vs. pc3m_sijmjd6_basal_hsf1_chip_biol_rep_1
    ("SRX25380949", "SRX25380941"), # pc3m_sijmjd6_hs_hsf1_chip_biol_rep_2 vs. pc3m_sijmjd6_basal_hsf1_chip_biol_rep_2


    ("SRX25380934", "SRX25380942"), # pc3m_sijmjd6_hs_input_biol_rep_1 vs. pc3m_sijmjd6_basal_input_biol_rep_1
    ("SRX25380935", "SRX25380943"), # pc3m_sijmjd6_hs_input_biol_rep_2 vs. pc3m_sijmjd6_basal_input_biol_rep_2

    # pair8_GSE270671_hsf1_pc3m_sint_hs_42C_60min.txt
    # pair8_GSE270671_hsf1_pc3m_sint_ctrl.txt
    ("SRX25380944", "SRX25380936"), # pc3m_sint_hs_hsf1_chip_biol_rep_1 vs. pc3m_sint_basal_hsf1_chip_biol_rep_1
    ("SRX25380945", "SRX25380937"), # pc3m_sint_hs_hsf1_chip_biol_rep_2 vs. pc3m_sint_basal_hsf1_chip_biol_rep_2

    
    ("SRX25380946", "SRX25380938"), # pc3m_sint_hs_input_biol_rep_1 vs. pc3m_sint_basal_input_biol_rep_1
    ("SRX25380947", "SRX25380939")  # pc3m_sint_hs_input_biol_rep_2 vs. pc3m_sint_basal_input_biol_rep_2
]

paired_metada_df_gse270671 = create_paired_metadata(
    combined_df=GSE270671_combined,
    defined_sample_pairs=defined_pairs_gse270671_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse270671 is not None:
    paired_metada_df_gse270671.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE270671_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse270671)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (8, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ lib ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ rar ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ y_n ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ ame ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ --- ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ str ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ l_c ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ pc3 ┆ PC3 ┆ GSM ┆ Pub ┆ Jun ┆ Jul ┆ SRA ┆ 1   ┆ PC3 ┆ Hom ┆ 960 ┆ Cel ┆ gen ┆ GPL ┆ Mar ┆ men ┆ 312 ┆ Mar ┆ Bio ┆ Nor ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ PC3 ┆ Pro ┆ siJ ┆ Hea ┆ hg3 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Nex ┆ SAM ┆ An  ┆ SRA ┆ ChI ┆ 202 ┆ 149 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ PC3 ┆ c90 ┆ SRP ┆ 460 ┆ An  ┆ GEN ┆ PC3 ┆ Nex ┆ Nex ┆ Pro ┆ ftp ┆ 231 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ PC3 ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 253 ┆ 253 ┆ m_s ┆ M,  ┆ 834 ┆ lic ┆ 24  ┆ 18  ┆     ┆     ┆ M   ┆ o   ┆ 6   ┆ ls  ┆ omi ┆ 185 ┆ c,L ┆ dil ┆ 503 ┆ c   ┆ che ┆ thw ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 834 ┆ :// ┆ 270 ┆     ┆ M   ┆ sta ┆ MJD ┆ t   ┆ 8   ┆ Wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 298 ┆ tSe ┆ N42 ┆ HSF ┆ 190 ┆ P   ┆ 4-0 ┆ 151 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ M,  ┆ ba2 ┆ 520 ┆ 558 ┆ HSF ┆ ERA ┆ M,  ┆ tSe ┆ tSe ┆ sta ┆ .sr ┆ 018 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 834 ┆ 834 ┆ ls  ┆ sin ┆ 834 ┆ M   ┆ _ta ┆ 4-0 ┆ o   ┆ 6   ┆ NA1 ┆ 298 ┆ 220 ┆ 4-0 ┆ 270 │
│ 809 ┆ 809 ┆ ijm ┆ siJ ┆ 979 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ c   ┆ 73  ┆ ,Me ┆ lo@ ┆ 486 ┆ Men ┆ mis ┆ est ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 979 ┆ ftp ┆ 671 ┆     ┆     ┆ te  ┆ 6   ┆ sho ┆     ┆ ,   ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 846 ┆ q   ┆ 017 ┆ 1-J ┆ 678 ┆     ┆ 7-2 ┆ 114 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ siJ ┆ 77a ┆ 857 ┆ 3   ┆ 1-J ┆ TED ┆ siJ ┆ q   ┆ q   ┆ te  ┆ a.e ┆ 901 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 979 ┆ 979 ┆ wer ┆ g   ┆ 979 ┆     ┆ x:t ┆ 7-2 ┆ sap ┆     ┆ 127 ┆ 846 ┆ 463 ┆ 7-2 ┆ 671 │
│ 48  ┆ 40  ┆ jd6 ┆ MJD ┆ 1   ┆ Jul ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ DNA ┆     ┆ ndi ┆ nor ┆ 2   ┆ dil ┆ try ┆ ern ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆ 1   ┆ .nc ┆     ┆     ┆     ┆ can ┆     ┆ ck  ┆     ┆ nar ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 35  ┆ 500 ┆ 716 ┆ MJD ┆ 0   ┆     ┆ 3   ┆ vs  ┆     ┆ bi. ┆     ┆     ┆ MJD ┆ 0b0 ┆     ┆ vs  ┆ MJD ┆ _FI ┆ MJD ┆ 500 ┆ 500 ┆ can ┆ bi. ┆ vs  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 1   ┆ 1_r ┆ e   ┆     ┆ 1_r ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 661 ┆ 35  ┆ 00  ┆ 3   ┆     │
│     ┆     ┆ _hs ┆ 6,  ┆ vs  ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ gro ┆     ┆     ┆ llo ┆ thw ┆     ┆ lo  ┆ and ┆ Uni ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆     ┆ cer ┆     ┆ 42C ┆     ┆ row ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ seq ┆ vs  ┆ 6-H ┆     ┆     ┆     ┆ 175 ┆     ┆ ac. ┆     ┆     ┆ 6,  ┆ 1e6 ┆     ┆ 545 ┆ 6-H ┆ LE  ┆ 6,  ┆     ┆ seq ┆ cer ┆ ac. ┆ 272 ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 3   ┆ fix ┆     ┆ 1   ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ _hs ┆ HS, ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wn  ┆     ┆     ┆     ┆ est ┆     ┆     ┆ Mol ┆ ver ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆     ┆ cel ┆     ┆ (1h ┆     ┆ Pea ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ uen ┆ SAM ┆ SP  ┆     ┆     ┆     ┆ 147 ┆     ┆ uk/ ┆     ┆     ┆ HS, ┆ 6a1 ┆     ┆ 651 ┆ SP  ┆     ┆ HS, ┆     ┆ uen ┆ cel ┆ uk/ ┆ 999 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ed  ┆     ┆ vs  ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ f1_ ┆ HSF ┆ 834 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆ ern ┆     ┆     ┆ ecu ┆ sit ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 834 ┆ .ni ┆     ┆     ┆     ┆ l   ┆     ┆ ),  ┆     ┆ k   ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 298 ┆ cin ┆ N42 ┆ fee ┆     ┆     ┆     ┆ 900 ┆     ┆ vol ┆     ┆     ┆ HSF ┆ 47f ┆     ┆ 8   ┆ fee ┆     ┆ HSF ┆     ┆ cin ┆ l   ┆ vol ┆ 683 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 834 ┆ GSM ┆ wit ┆     ┆ GSM ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 298 ┆ 220 ┆     ┆     │
│     ┆     ┆ chi ┆ 1   ┆ 978 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆     ┆     ┆ .ed ┆     ┆     ┆ lar ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 978 ┆ h.g ┆     ┆     ┆     ┆ lin ┆     ┆ 2h  ┆     ┆     ┆ nih ┆ nih ┆ 73/ ┆     ┆     ┆ 846 ┆ g:  ┆ 017 ┆ dba ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 1   ┆ 063 ┆     ┆     ┆ dba ┆     ┆ 1   ┆     ┆ g:  ┆ lin ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 978 ┆ 834 ┆ h   ┆     ┆ 834 ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 846 ┆ 462 ┆     ┆     │
│     ┆     ┆ p_b ┆ ChI ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆     ┆ e   ┆     ┆ Rec ┆     ┆     ┆ .go ┆ .go ┆ pna ┆     ┆     ┆ 65  ┆ GSM ┆ 724 ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ ChI ┆ fe1 ┆     ┆     ┆ ck  ┆     ┆ ChI ┆     ┆ GSM ┆ e   ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 3   ┆ 978 ┆ 1%  ┆     ┆ 978 ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 65  ┆ 92  ┆     ┆     │
│     ┆     ┆ iol ┆ P,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ ove ┆     ┆     ┆ v/b ┆ v/s ┆ s.2 ┆     ┆     ┆     ┆ 834 ┆     ┆ cir ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ P,  ┆ 79a ┆     ┆     ┆ cir ┆     ┆ P,  ┆     ┆ 834 ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 3_r ┆ for ┆     ┆ 3_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _re ┆ bio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5%  ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ ry  ┆     ┆     ┆ ios ┆ ra? ┆ 313 ┆     ┆     ┆     ┆ 979 ┆     ┆ cui ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆ bio ┆ fb  ┆     ┆     ┆ cui ┆     ┆ bio ┆     ┆ 979 ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ mal ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p_1 ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ CO2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ amp ┆ ter ┆ 370 ┆     ┆     ┆     ┆ 1:  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 98/ ┆     ┆     ┆ l   ┆ vs  ┆     ┆     ┆ t   ┆     ┆ l   ┆     ┆ 1:  ┆     ┆ 98/ ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆ 213 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ Bas ┆     ┆     ┆ le/ ┆ m=S ┆ 121 ┆     ┆     ┆     ┆ PC3 ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ 035 ┆     ┆     ┆ rep ┆ a8d ┆     ┆     ┆ pro ┆     ┆ rep ┆     ┆ PC3 ┆     ┆ 035 ┆     ┆     ┆     ┆     ┆     ┆ 8/0 ┆ ;33 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pc3 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆ SAM ┆ RX2 ┆     ┆     ┆     ┆     ┆ M,  ┆     ┆ mot ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 1   ┆ fec ┆     ┆     ┆ mot ┆     ┆ 1   ┆     ┆ M,  ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 35/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ m_s ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 834 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N42 ┆ 538 ┆     ┆     ┆     ┆     ┆ siJ ┆     ┆ es  ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆     ┆     ┆ vs  ┆ 26f ┆     ┆     ┆ es  ┆     ┆ vs  ┆     ┆ siJ ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ijm ┆ PC3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆ 094 ┆     ┆     ┆     ┆     ┆ MJD ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆ 884 ┆     ┆     ┆ PC3 ┆ 6db ┆     ┆     ┆ cel ┆     ┆ PC3 ┆     ┆ MJD ┆     ┆ 884 ┆     ┆     ┆     ┆     ┆     ┆ 298 ┆ 11; ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ jd6 ┆ M,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 716 ┆ 8   ┆     ┆     ┆     ┆     ┆ 6,  ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 635 ┆     ┆     ┆ M,  ┆ 14d ┆     ┆     ┆ l   ┆     ┆ M,  ┆     ┆ 6,  ┆     ┆ 635 ┆     ┆     ┆     ┆     ┆     ┆ 846 ┆ 895 ┆     ┆     ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ba ┆ siJ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ HS, ┆     ┆ ada ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ siJ ┆ 349 ┆     ┆     ┆ ada ┆     ┆ siJ ┆     ┆ HS, ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 35/ ┆ 93; ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sal ┆ MJD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 349 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆ pta ┆     ┆     ┆     ┆     ┆     ┆ R29 ┆     ┆     ┆ MJD ┆ 83a ┆     ┆     ┆ pta ┆     ┆ MJD ┆     ┆ HSF ┆     ┆ R29 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 19. GSE253873 (ChIP-seq; H3/H3.3)

- [Histone H3.3 chaperone HIRA renders stress-responsive genes poised for prospective lethal stresses in acquired tolerance](https://doi.org/10.1111/gtc.13140)
- `4.2 Heat treatment: Cells were seeded at a density of 1.1 × 104 or 1.7 × 104 cells/cm2 in 35 mm dishes for immortalized cells and primary cells, respectively, and incubated for 24 h at 37°C before heat shock treatment. For priming stress treatment, culture media was replaced with fresh media pre-heated at 40°C, and cells were cultured in an incubator at 40°C (±0.5°C) and 5% CO2 for 2 h. For lethal stress treatment, culture media was replaced with fresh media pre-heated at 47°C, and cells were cultured in an incubator at 47°C (±0.5°C) and 5% CO2 for 35 min. After heat treatment, the media was replaced by fresh media (37°C), and the cells were incubated in an incubator at 37°C (±0.5°C) and 5% CO2 for 48 h. Cell viability was quantified using a Cell Counting Kit-8 (Dojindo) and SpectraMax 340 Microplate Reader (Molecular Devices).`

In [40]:
GSE253873_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE253873/GSE253873_PEP/GSE253873_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1111/gtc.13140").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE253873 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE253873.metadata.tsv",
    separator='\t'
)

GSE253873_combined = GSE253873_PEP.join(
    GSE253873,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE253873_combined = GSE253873_combined[[s.name for s in GSE253873_combined if not (s.null_count() == GSE253873_combined.height)]]

display(GSE253873_combined)

shape: (8, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali ┆ _ty │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ i64 ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ wi- ┆ WI- ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ lun ┆ Hom ┆ 960 ┆ gen ┆ WI3 ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ lun ┆ WI- ┆ imm ┆ WT  ┆ con ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 120 ┆ SRR ┆ Ill ┆ SAM ┆ His ┆ SRA ┆ ChI ┆ 202 ┆ 120 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ WI- ┆ 8b5 ┆ SRP ┆ 369 ┆ His ┆ GEN ┆ WI- ┆ Ill ┆ Ill ┆ imm ┆ ftp ┆ 244 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ WI- ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE ┆ lun │
│ 38- ┆ 38- ┆ 802 ┆ lic ┆ 22  ┆ 15  ┆     ┆     ┆ g   ┆ o   ┆ 6   ┆ omi ┆ 8_3 ┆ 111 ┆ hik ┆ to  ┆ hid ┆ to- ┆ to  ┆ -85 ┆ an  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 802 ┆ :// ┆ 253 ┆     ┆ 233 ┆ g   ┆ 38- ┆ ort ┆     ┆ tro ┆ 9   ┆ Wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 276 ┆ umi ┆ N39 ┆ ton ┆ 178 ┆ P   ┆ 4-1 ┆ 105 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 38- ┆ 568 ┆ 485 ┆ 909 ┆ ton ┆ ERA ┆ 38- ┆ umi ┆ umi ┆ ort ┆ .sr ┆ 140 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 802 ┆ 802 ┆ ls  ┆ sin ┆ 802 ┆ 38- ┆ 802 ┆ _ta ┆ 4-1 ┆ o   ┆ 6   ┆ NA1 ┆ 276 ┆ 202 ┆ 4-1 ┆ 253 ┆ g   │
│ hte ┆ hTE ┆ 967 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 7C_ ┆ 54  ┆ azu ┆ Uni ┆ a-K ┆ shi ┆     ┆ 01  ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 967 ┆ ftp ┆ 873 ┆     ┆ 490 ┆     ┆ hTE ┆ ali ┆     ┆ l   ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 818 ┆ na  ┆ 538 ┆ e   ┆ 971 ┆     ┆ 0-1 ┆ 913 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ hTE ┆ 4d3 ┆ 224 ┆ 71  ┆ e   ┆ TED ┆ hTE ┆ na  ┆ na  ┆ ali ┆ a.e ┆ 408 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 967 ┆ 967 ┆ wer ┆ g   ┆ 967 ┆ hTE ┆ 967 ┆ x:t ┆ 0-1 ┆ sap ┆     ┆ 067 ┆ 818 ┆ 104 ┆ 0-1 ┆ 873 ┆     │
│ rt_ ┆ RT, ┆ 8   ┆ Oct ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ H3. ┆     ┆ ,,N ┆ ver ┆ ono ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 8   ┆ .nc ┆     ┆     ┆ 43  ┆     ┆ RT  ┆ zed ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 03  ┆ HiS ┆ 440 ┆ H3. ┆ 3   ┆     ┆ 6   ┆ 9   ┆     ┆ bi. ┆     ┆     ┆ RT, ┆ 278 ┆     ┆     ┆ H3. ┆ _FI ┆ RT, ┆ HiS ┆ HiS ┆ zed ┆ bi. ┆ 6   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ e   ┆     ┆ 8_r ┆ RT  ┆ 8   ┆ err ┆ 6   ┆ ien ┆     ┆ 601 ┆ 03  ┆ 25  ┆ 6   ┆     ┆     │
│ 37° ┆ 37° ┆     ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ 3   ┆     ┆ aga ┆ sit ┆ e-c ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆ hum ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ eq  ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ 37° ┆ 8c9 ┆     ┆     ┆ 3   ┆ LE  ┆ 37° ┆ eq  ┆ eq  ┆ hum ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ fix ┆     ┆ 1   ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ c_h ┆ C,  ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gak ┆ y   ┆ ho, ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ 200 ┆     ┆ cha ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆ C,  ┆ 9b6 ┆     ┆     ┆ cha ┆     ┆ C,  ┆ 200 ┆ 200 ┆ an  ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3_3 ┆ H3. ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆ Sak ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆     ┆ fib ┆     ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆     ┆ 0   ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆ H3. ┆ 460 ┆     ┆     ┆ per ┆     ┆ H3. ┆ 0   ┆ 0   ┆ fib ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ _ch ┆ 3,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yo- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆ rob ┆     ┆     ┆     ┆     ┆ nih ┆ nih ┆ 11/ ┆     ┆     ┆     ┆ seq ┆     ┆ one ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 3,  ┆ bc8 ┆     ┆     ┆ one ┆     ┆ 3,  ┆     ┆ seq ┆ rob ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ip  ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ku  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆ las ┆     ┆     ┆     ┆     ┆ .go ┆ .go ┆ gtc ┆     ┆     ┆     ┆ uen ┆     ┆ HIR ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ ChI ┆ 51d ┆     ┆     ┆ HIR ┆     ┆ ChI ┆     ┆ uen ┆ las ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ .13 ┆     ┆     ┆     ┆ cin ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ P   ┆ fe0 ┆     ┆     ┆ A   ┆     ┆ P   ┆     ┆ cin ┆ t   ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ 140 ┆     ┆     ┆     ┆ g:  ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆     ┆ 3a  ┆     ┆     ┆ is  ┆     ┆     ┆     ┆ g:  ┆ cel ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ req ┆     ┆     ┆     ┆     ┆     ┆ 76/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ req ┆     ┆     ┆     ┆ GSM ┆ ls  ┆ 76/ ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆ 213 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆     ┆     ┆     ┆     ┆ 802 ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆     ┆ uir ┆     ┆     ┆     ┆ 802 ┆     ┆ 003 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆     ┆     ┆     ┆     ┆ 967 ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ 967 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 03/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 802 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N39 ┆ 334 ┆     ┆     ┆     ┆     ┆ 8:  ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆ 8:  ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 538 ┆ 904 ┆     ┆     ┆     ┆     ┆ WI- ┆     ┆ acq ┆     ┆     ┆     ┆     ┆     ┆ 681 ┆     ┆     ┆     ┆     ┆     ┆     ┆ acq ┆     ┆     ┆     ┆ WI- ┆     ┆ 681 ┆     ┆     ┆     ┆     ┆     ┆ 276 ┆ 11; ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 440 ┆ 3   ┆     ┆     ┆     ┆     ┆ 38- ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ 803 ┆     ┆     ┆     ┆     ┆     ┆     ┆ uir ┆     ┆     ┆     ┆ 38- ┆     ┆ 803 ┆     ┆     ┆     ┆     ┆     ┆ 818 ┆ 895 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hTE ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ hTE ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 03/ ┆ 93; ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 029 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RT, ┆     ┆ tol ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆     ┆ tol ┆     ┆     ┆     ┆ RT, ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 678 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37° ┆     ┆ era ┆     ┆     ┆     ┆     ┆     ┆ 681 ┆     ┆     ┆     ┆     ┆     ┆     ┆ era ┆     ┆     ┆     ┆ 37° ┆     ┆ 681 ┆     ┆     ┆     ┆     ┆     ┆ 276 ┆ 2;7 ┆     ┆     ┆ tem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [41]:
defined_pairs_gse253873_chipseq = [
    ("SRX23349047", "SRX23349043"), # wi-38-htert_40°c_h3_3_chip vs. wi-38-htert_37°c_h3_3_chip
    ("SRX23349048", "SRX23349044"), # wi-38-htert_40°c_h3_chip vs. wi-38-htert_37°c_h3_chip
    ("SRX23349049", "SRX23349045"), # wi-38-htert_40°c_control_igg_chip vs. wi-38-htert_37°c_control_igg_chip
    ("SRX23349050", "SRX23349046")  # wi-38-htert_40°c_input vs. wi-38-htert_37°c_input
]

paired_metada_df_gse253873 = create_paired_metadata(
    combined_df=GSE253873_combined,
    defined_sample_pairs=defined_pairs_gse253873_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse253873 is not None:
    paired_metada_df_gse253873.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE253873_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse253873)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ wi- ┆ WI- ┆ GSM ┆ Pub ┆ Jan ┆ Oct ┆ SRA ┆ 1   ┆ lun ┆ Hom ┆ 960 ┆ gen ┆ WI3 ┆ GPL ┆ Yos ┆ Kyo ┆ Yos ┆ Kyo ┆ Kyo ┆ 606 ┆ Jap ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ lun ┆ WI- ┆ imm ┆ WT  ┆ hea ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 120 ┆ SRR ┆ Ill ┆ SAM ┆ His ┆ SRA ┆ ChI ┆ 202 ┆ 111 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ WI- ┆ d6e ┆ SRP ┆ 343 ┆ His ┆ GEN ┆ WI- ┆ Ill ┆ Ill ┆ imm ┆ ftp ┆ 226 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ WI- ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE ┆ lun │
│ 233 ┆ 233 ┆ 38- ┆ 38- ┆ 802 ┆ lic ┆ 22  ┆ 15  ┆     ┆     ┆ g   ┆ o   ┆ 6   ┆ omi ┆ 8_4 ┆ 111 ┆ hik ┆ to  ┆ hid ┆ to- ┆ to  ┆ -85 ┆ an  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 802 ┆ :// ┆ 253 ┆     ┆ g   ┆ 38- ┆ ort ┆     ┆ t   ┆ 9   ┆ Wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 276 ┆ umi ┆ N39 ┆ ton ┆ 178 ┆ P   ┆ 4-1 ┆ 491 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 38- ┆ 101 ┆ 485 ┆ 035 ┆ ton ┆ ERA ┆ 38- ┆ umi ┆ umi ┆ ort ┆ .sr ┆ 403 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 802 ┆ 802 ┆ ls  ┆ sin ┆ 802 ┆ 38- ┆ 802 ┆ _ta ┆ 4-1 ┆ o   ┆ 6   ┆ NA1 ┆ 276 ┆ 202 ┆ 4-1 ┆ 253 ┆ g   │
│ 490 ┆ 490 ┆ hte ┆ hTE ┆ 968 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 0C_ ┆ 54  ┆ azu ┆ Uni ┆ a-K ┆ shi ┆     ┆ 01  ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 968 ┆ ftp ┆ 873 ┆     ┆     ┆ hTE ┆ ali ┆     ┆ str ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 817 ┆ na  ┆ 538 ┆ e   ┆ 971 ┆     ┆ 0-1 ┆ 248 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ hTE ┆ 853 ┆ 224 ┆ 78  ┆ e   ┆ TED ┆ hTE ┆ na  ┆ na  ┆ ali ┆ a.e ┆ 614 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 968 ┆ 968 ┆ wer ┆ g   ┆ 968 ┆ hTE ┆ 968 ┆ x:t ┆ 0-1 ┆ sap ┆     ┆ 067 ┆ 817 ┆ 104 ┆ 0-1 ┆ 873 ┆     │
│ 47  ┆ 43  ┆ rt_ ┆ RT, ┆ 2   ┆ Oct ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ H3. ┆     ┆ ,,N ┆ ver ┆ ono ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 2   ┆ .nc ┆     ┆     ┆     ┆ RT  ┆ zed ┆     ┆ ess ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 99  ┆ HiS ┆ 436 ┆ H3. ┆ 3   ┆     ┆ 6   ┆ 1   ┆     ┆ bi. ┆     ┆     ┆ RT, ┆ 1b9 ┆     ┆ vs  ┆ H3. ┆ _FI ┆ RT, ┆ HiS ┆ HiS ┆ zed ┆ bi. ┆ 8   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 2   ┆ 2_r ┆ e   ┆     ┆ 2_r ┆ RT  ┆ 2   ┆ err ┆ 6   ┆ ien ┆     ┆ 601 ┆ 99  ┆ 30  ┆ 6   ┆     ┆     │
│     ┆     ┆ 40° ┆ 40° ┆ vs  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ 3   ┆     ┆ aga ┆ sit ┆ e-c ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆     ┆     ┆ hum ┆     ┆ tre ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ eq  ┆ vs  ┆ 3   ┆     ┆     ┆     ┆ vs  ┆     ┆ ac. ┆     ┆     ┆ 40° ┆ 8c2 ┆     ┆ 369 ┆ 3   ┆ LE  ┆ 40° ┆ eq  ┆ eq  ┆ hum ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ fix ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ c_h ┆ C,  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ gak ┆ y   ┆ ho, ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆     ┆     ┆ an  ┆     ┆ atm ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ 200 ┆ SAM ┆ cha ┆     ┆     ┆     ┆ 120 ┆     ┆ uk/ ┆     ┆     ┆ C,  ┆ 75e ┆     ┆ 909 ┆ cha ┆     ┆ C,  ┆ 200 ┆ 200 ┆ an  ┆ uk/ ┆ 244 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ed  ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ 3_3 ┆ H3. ┆ 802 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WI3 ┆     ┆ i   ┆     ┆ Sak ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 802 ┆ .ni ┆     ┆     ┆     ┆     ┆ fib ┆     ┆ ent ┆     ┆     ┆ lm. ┆ lm. ┆ .11 ┆     ┆     ┆ 276 ┆ 0   ┆ N39 ┆ per ┆     ┆     ┆     ┆ 105 ┆     ┆ vol ┆     ┆     ┆ H3. ┆ 815 ┆     ┆ 71  ┆ per ┆     ┆ H3. ┆ 0   ┆ 0   ┆ fib ┆ vol ┆ 140 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 802 ┆ GSM ┆ wit ┆     ┆ GSM ┆     ┆ 802 ┆ l;e ┆     ┆     ┆     ┆     ┆ 276 ┆ 202 ┆     ┆     ┆     │
│     ┆     ┆ _ch ┆ 3,  ┆ 967 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8_3 ┆     ┆     ┆     ┆ yo- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆ h.g ┆     ┆     ┆     ┆     ┆ rob ┆     ┆ (40 ┆     ┆     ┆ nih ┆ nih ┆ 11/ ┆     ┆     ┆ 818 ┆ seq ┆ 538 ┆ one ┆     ┆     ┆     ┆ 913 ┆     ┆ 1/f ┆     ┆     ┆ 3,  ┆ e43 ┆     ┆     ┆ one ┆     ┆ 3,  ┆     ┆ seq ┆ rob ┆ 1/f ┆ 408 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 967 ┆ 802 ┆ h   ┆     ┆ 802 ┆     ┆ 967 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 818 ┆ 104 ┆     ┆     ┆     │
│     ┆     ┆ ip  ┆ ChI ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7C_ ┆     ┆     ┆     ┆ ku  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ ov/ ┆     ┆     ┆     ┆     ┆ las ┆     ┆ °C, ┆     ┆     ┆ .go ┆ .go ┆ gtc ┆     ┆     ┆ 03  ┆ uen ┆ 440 ┆ HIR ┆     ┆     ┆     ┆ 9   ┆     ┆ ast ┆     ┆     ┆ ChI ┆ 3dd ┆     ┆     ┆ HIR ┆     ┆ ChI ┆     ┆ uen ┆ las ┆ ast ┆ 6   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 8   ┆ 967 ┆ 1%  ┆     ┆ 967 ┆     ┆ 8   ┆ tax ┆     ┆     ┆     ┆     ┆ 03  ┆ 25  ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ H3. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ t   ┆     ┆ 2   ┆     ┆     ┆ v/b ┆ v/s ┆ .13 ┆     ┆     ┆     ┆ cin ┆     ┆ A   ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ P   ┆ 74b ┆     ┆     ┆ A   ┆     ┆ P   ┆     ┆ cin ┆ t   ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 8_r ┆ for ┆     ┆ 8_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ wi- ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ hou ┆     ┆     ┆ ios ┆ ra? ┆ 140 ┆     ┆     ┆     ┆ g:  ┆     ┆ is  ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆ vs  ┆ 20  ┆     ┆     ┆ is  ┆     ┆ vs  ┆     ┆ g:  ┆ cel ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ mal ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 38- ┆ WI- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ rs) ┆     ┆     ┆ amp ┆ ter ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆ req ┆     ┆     ┆     ┆     ┆     ┆ 76/ ┆     ┆     ┆ WI- ┆ vs  ┆     ┆     ┆ req ┆     ┆ WI- ┆     ┆ GSM ┆ ls  ┆ 76/ ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆ 213 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hte ┆ 38- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ le/ ┆ m=S ┆     ┆     ┆     ┆     ┆ 802 ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ 099 ┆     ┆     ┆ 38- ┆ 8b5 ┆     ┆     ┆ uir ┆     ┆ 38- ┆     ┆ 802 ┆     ┆ 099 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rt_ ┆ hTE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆ SAM ┆ RX2 ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ hTE ┆ 568 ┆     ┆     ┆ ed  ┆     ┆ hTE ┆     ┆ 968 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 99/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 37° ┆ RT, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 802 ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆     ┆ N39 ┆ 334 ┆     ┆     ┆     ┆     ┆ 2:  ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆     ┆     ┆ RT, ┆ 4d3 ┆     ┆     ┆ for ┆     ┆ RT, ┆     ┆ 2:  ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c_h ┆ 37° ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ 538 ┆ 904 ┆     ┆     ┆     ┆     ┆ WI- ┆     ┆ acq ┆     ┆     ┆     ┆     ┆     ┆ 681 ┆     ┆     ┆ 37° ┆ 278 ┆     ┆     ┆ acq ┆     ┆ 37° ┆     ┆ WI- ┆     ┆ 681 ┆     ┆     ┆     ┆     ┆     ┆ 276 ┆ 11; ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3_3 ┆ C,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 436 ┆ 7   ┆     ┆     ┆     ┆     ┆ 38- ┆     ┆ uir ┆     ┆     ┆     ┆     ┆     ┆ 799 ┆     ┆     ┆ C,  ┆ 8c9 ┆     ┆     ┆ uir ┆     ┆ C,  ┆     ┆ 38- ┆     ┆ 799 ┆     ┆     ┆     ┆     ┆     ┆ 817 ┆ 895 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ch ┆ H3. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ hTE ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ H3. ┆ 9b6 ┆     ┆     ┆ ed  ┆     ┆ H3. ┆     ┆ hTE ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 99/ ┆ 93; ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ip  ┆ 3,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 029 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ RT, ┆     ┆ tol ┆     ┆     ┆     ┆     ┆     ┆ R27 ┆     ┆     ┆ 3,  ┆ 460 ┆     ┆     ┆ tol ┆     ┆ 3,  ┆     ┆ RT, ┆     ┆ R27 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 20. GSE259305 (ChIP-seq; FUBP3/PolII(Ser2p)/dCas9) (ChIP-Atlas: False)

- [TurboCas: A method for locus-specific labeling of genomic regions and isolating their associated protein interactome](https://doi.org/10.1016/j.molcel.2024.11.007)
- dCas9 などの他に、FUBP3, Pol II などのデータも含まれている

In [42]:
GSE259305_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE259305/GSE259305_PEP/GSE259305_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1016/j.cell.2023.03.010").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE259305 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE259305.metadata.tsv",
    separator='\t'
)

GSE259305_combined = GSE259305_PEP.join(
    GSE259305,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE259305_combined = GSE259305_combined[[s.name for s in GSE259305_combined if not (s.null_count() == GSE259305_combined.height)]]

display(GSE259305_combined)

shape: (52, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ chi ┆ chi ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ p_a ┆ p   ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ nti ┆ --- ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ bod ┆ str ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ y   ┆     ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ chi ┆ ChI ┆ GSM ┆ Pub ┆ Feb ┆ Dec ┆ SRA ┆ 1   ┆ HEK ┆ Hom ┆ 960 ┆ 100 ┆ Hum ┆ gen ┆ ChI ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HEK ┆ hum ┆ Tur ┆ 37C ┆ Cas ┆ Tri ┆ hg3 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 120 ┆ SRR ┆ Ill ┆ SAM ┆ Tur ┆ SRA ┆ ChI ┆ 202 ┆ 101 ┆ ILL ┆ ftp ┆ mis ┆ ChI ┆ 2f4 ┆ SRP ┆ 340 ┆ Tur ┆ GEN ┆ ChI ┆ Ill ┆ Ill ┆ hum ┆ ftp ┆ 172 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ mis ┆ GSM ┆ HEK ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ pse ┆ Pse ┆ 811 ┆ lic ┆ 26  ┆ 21  ┆     ┆     ┆ 293 ┆ o   ┆ 6   ┆ mM  ┆ an  ┆ omi ┆ P   ┆ 246 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 811 ┆ :// ┆ 259 ┆     ┆ 237 ┆ 293 ┆ an  ┆ boC ┆ 3   ┆ 9   ┆ mme ┆ 8   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 281 ┆ umi ┆ N40 ┆ boC ┆ 180 ┆ P   ┆ 4-1 ┆ 559 ┆ UMI ┆ .sr ┆ sin ┆ Pse ┆ 743 ┆ 491 ┆ 333 ┆ boC ┆ ERA ┆ Pse ┆ umi ┆ umi ┆ an  ┆ .sr ┆ 012 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 811 ┆ 811 ┆ RNA ┆ sin ┆ 811 ┆ 293 ┆ 811 ┆ _ta ┆ 4-1 ┆ o   ┆ 6   ┆ NA1 ┆ 281 ┆ 205 ┆ 4-1 ┆ 259 │
│ q_2 ┆ q_2 ┆ 361 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ T   ┆ sap ┆     ┆ bio ┆ HCT ┆ c   ┆ lib ┆ 76  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 361 ┆ ftp ┆ 305 ┆     ┆ 514 ┆ T   ┆ emb ┆ as  ┆ hou ┆ (Di ┆ d   ┆     ┆ fil ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 064 ┆ na  ┆ 144 ┆ as: ┆ 981 ┆     ┆ 2-2 ┆ 774 ┆ NA  ┆ a.e ┆ g   ┆ q_2 ┆ 575 ┆ 824 ┆ 72  ┆ as: ┆ TED ┆ q_2 ┆ na  ┆ na  ┆ emb ┆ a.e ┆ 689 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 361 ┆ 361 ┆ :   ┆ g   ┆ 361 ┆ T   ┆ 361 ┆ x:t ┆ 2-2 ┆ sap ┆     ┆ 080 ┆ 064 ┆ 775 ┆ 2-2 ┆ 305 │
│ 93t ┆ 93T ┆ 5   ┆ Dec ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ tin ┆ 116 ┆ DNA ┆ rar ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆ 5   ┆ .nc ┆     ┆     ┆ 46  ┆     ┆ ryo ┆ FOS ┆ rs  ┆ +M3 ┆ ChI ┆     ┆ es  ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 13  ┆ Nov ┆ 550 ┆ A   ┆ 3   ┆     ┆ 5   ┆ 3   ┆     ┆ bi. ┆     ┆ 93T ┆ e77 ┆     ┆     ┆ A   ┆ _FI ┆ 93T ┆ Nov ┆ Nov ┆ ryo ┆ bi. ┆ 3   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ RNA ┆     ┆ 5_r ┆     ┆ 5   ┆ err ┆ 5   ┆ ien ┆     ┆ 615 ┆ 13  ┆ 52  ┆ 5   ┆     │
│ _tc ┆ _TC ┆     ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ (Si ┆ cel ┆     ┆ ies ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆ nic ┆ -30 ┆ (no ┆ 6:M ┆ P-s ┆     ┆ for ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ aSe ┆     ┆ met ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆ _TC ┆ b52 ┆     ┆     ┆ met ┆ LE  ┆ _TC ┆ aSe ┆ aSe ┆ nic ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ fro ┆     ┆ 1   ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ _30 ┆ _30 ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gma ┆ ls  ┆     ┆ wer ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆     ┆ kid ┆ 0   ┆ hea ┆ 67a ┆ eq  ┆     ┆ ChI ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ q   ┆     ┆ hod ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆ _30 ┆ b40 ┆     ┆     ┆ hod ┆     ┆ _30 ┆ q   ┆ q   ┆ kid ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0_h ┆ 0_H ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Al ┆ wer ┆     ┆ e   ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆     ┆ ney ┆     ┆ t   ┆ gen ┆ rea ┆     ┆ P-s ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ 600 ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆ 0_H ┆ 624 ┆     ┆     ┆ for ┆     ┆ 0_H ┆ 600 ┆ 600 ┆ ney ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ HCT ┆     ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ s_n ┆ S_n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dri ┆ e   ┆     ┆ pre ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ sho ┆ ode ┆ ds  ┆     ┆ eq  ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     ┆ 0   ┆     ┆ loc ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆ S_n ┆ 6bc ┆     ┆     ┆ loc ┆     ┆ S_n ┆ 0   ┆ 0   ┆ cel ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ 116 ┆     ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ eg_ ┆ eg_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch, ┆ cul ┆     ┆ par ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ ck) ┆ ,   ┆ wer ┆     ┆ dat ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆     ┆ seq ┆     ┆ us- ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆ eg_ ┆ 08c ┆     ┆     ┆ us- ┆     ┆ eg_ ┆     ┆ seq ┆ ls  ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ chi ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ B45 ┆ tur ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ #C1 ┆ e   ┆     ┆ a   ┆ v/b ┆ v/s ┆ ell ┆     ┆     ┆     ┆ uen ┆     ┆ spe ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆ ChI ┆ 7a6 ┆     ┆     ┆ spe ┆     ┆ ChI ┆     ┆ uen ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ p_d ┆ P_d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01) ┆ ed  ┆     ┆ usi ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 531 ┆ ali ┆     ┆     ┆ ios ┆ ra? ┆ .20 ┆     ┆     ┆     ┆ cin ┆     ┆ cif ┆     ┆     ┆     ┆     ┆     ┆ RR2 ┆     ┆ P_d ┆ 34  ┆     ┆     ┆ cif ┆     ┆ P_d ┆     ┆ cin ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cas ┆ Cas ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sto ┆ in  ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 025 ┆ gne ┆     ┆     ┆ amp ┆ ter ┆ 23. ┆     ┆     ┆     ┆ g:  ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆ 81/ ┆     ┆ Cas ┆     ┆     ┆     ┆ ic  ┆     ┆ Cas ┆     ┆ g:  ┆     ┆ 81/ ┆     ┆     ┆     ┆     ┆     ┆ R28 ┆ 213 ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆ DME ┆     ┆ the ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8-1 ┆ d   ┆     ┆     ┆ le/ ┆ m=S ┆ 03. ┆     ┆     ┆     ┆ GSM ┆     ┆ lab ┆     ┆     ┆     ┆     ┆     ┆ 013 ┆     ┆ 9   ┆     ┆     ┆     ┆ lab ┆     ┆ 9   ┆     ┆ GSM ┆     ┆ 013 ┆     ┆     ┆     ┆     ┆     ┆ 1/0 ┆ ;33 ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆ M   ┆     ┆ KAP ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00) ┆ to  ┆     ┆     ┆ SAM ┆ RX2 ┆ 010 ┆     ┆     ┆     ┆ 811 ┆     ┆ eli ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ eli ┆     ┆     ┆     ┆ 811 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 13/ ┆ 511 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ par ┆ (Si ┆     ┆ A   ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 811 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ N40 ┆ 375 ┆     ┆     ┆     ┆     ┆ 361 ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆ R28 ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆ 361 ┆     ┆ R28 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ gma ┆     ┆ HTP ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hum ┆     ┆     ┆ 144 ┆ 144 ┆     ┆     ┆     ┆     ┆ 5:  ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆ 5:  ┆     ┆ 106 ┆     ┆     ┆     ┆     ┆     ┆ 281 ┆ 11; ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ #D6 ┆     ┆ lib ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆ 550 ┆ 6   ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆ ChI ┆     ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆ 064 ┆ 895 ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ 429 ┆     ┆ rar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pse ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ omi ┆     ┆     ┆     ┆ Pse ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 13/ ┆ 93; ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O   ┆ )   ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 113 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_2 ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆ R28 ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆ q_2 ┆     ┆ R28 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [43]:
defined_pairs_gse259305_chipseq = [

    # FUBP3
    ("SRX26888307", "SRX26888305"), # chip-seq_fubp3_dld1_shfubp3_hs_ab1 vs. chip-seq_fubp3_dld1_shfubp3_nonhs_ab1
    ("SRX26888311", "SRX26888309"), # chip-seq_fubp3_dld1_shfubp3_hs_ab2 vs. chip-seq_fubp3_dld1_shfubp3_nonhs_ab2
    ("SRX26888306", "SRX26888304"), # chip-seq_fubp3_dld1_shscr_hs_ab1 vs. chip-seq_fubp3_dld1_shscr_nonhs_ab1
    ("SRX26888310", "SRX26888308"), # chip-seq_fubp3_dld1_shscr_hs_ab2 vs. chip-seq_fubp3_dld1_shscr_nonhs_ab2

    # Pol II
    # pair25_GSE259305_pol2_hs_42C_120min_ser2p_dld1_shfubp3.txt
    # pair25_GSE259305_pol2_ctrl_dld1_shfubp3.txt
    ("SRX23751483", "SRX23751481"), # chip-seq-ser2p-dld1-shfubp3-hs-rep1 vs. chip-seq-ser2p-dld1-shfubp3-nonhs-rep1
    ("SRX23751487", "SRX23751486"), # chip-seq-ser2p-dld1-shfubp3-hs-rep2 vs. chip-seq-ser2p-dld1-shfubp3-nonhs-rep2

    # pair26_GSE259305_pol2_hs_42C_120min_ser2p_dld1_shscr.txt
    # pair26_GSE259305_pol2_ctrl_dld1_shscr.txt
    ("SRX23751485", "SRX23751484"), # chip-seq-ser2p-dld1-shscr-hs-rep1 vs. chip-seq-ser2p-dld1-shscr-nonhs-rep1
    ("SRX23751489", "SRX23751488"), # chip-seq-ser2p-dld1-shscr-hs-rep2 vs. chip-seq-ser2p-dld1-shscr-nonhs-rep2

    # dCas9
    ("SRX23751448", "SRX23751446"), # chipseq_293t_tc_300_hs_pos_chip_dcas9 vs. chipseq_293t_tc_300_hs_neg_chip_dcas9
    ("SRX23751449", "SRX23751447"), # chipseq_293t_tc_300_hs_pos_input vs. chipseq_293t_tc_300_hs_neg_input
    ("SRX23751482", "SRX23751479"), # chipseq_hct116_tc_lgp_hs_pos_input vs. chipseq_hct116_tc_lgp_hs_neg_input
    ("SRX23751480", "SRX23751478"), # chipseq_hct116_tc_lgp_hs_pos_chip_dcas9 vs. chipseq_hct116_tc_lgp_hs_neg_chip_dcas9
    ("SRX23751477", "SRX23751474"), # chipseq_hct116_tc_ex1_hs_pos_input vs. chipseq_hct116_tc_ex1_hs_neg_input
    ("SRX23751476", "SRX23751475"), # chipseq_hct116_tc_ex1_hs_pos_chip_dcas9 vs. chipseq_hct116_tc_ex1_hs_neg_chip_dcas9
    ("SRX23751473", "SRX23751471"), # chipseq_hct116_tc_600_hs_pos_input vs. chipseq_hct116_tc_600_hs_neg_input
    ("SRX23751472", "SRX23751470"), # chipseq_hct116_tc_600_hs_pos_chip_dcas9 vs. chipseq_hct116_tc_600_hs_neg_chip_dcas9
    ("SRX23751469", "SRX23751467"), # chipseq_hct116_tc_300_hs_pos_input vs. chipseq_hct116_tc_300_hs_neg_input
    ("SRX23751468", "SRX23751466"), # chipseq_hct116_tc_300_hs_pos_chip_dcas9 vs. chipseq_hct116_tc_300_hs_neg_chip_dcas9
    ("SRX23751465", "SRX23751463"), # chipseq_hct116_mt_lgp_hs_pos_input vs. chipseq_hct116_mt_lgp_hs_neg_input
    ("SRX23751464", "SRX23751462"), # chipseq_hct116_mt_lgp_hs_pos_chip_dcas9 vs. chipseq_hct116_mt_lgp_hs_neg_chip_dcas9
    ("SRX23751461", "SRX23751459"), # chipseq_293t_tc_lgp_hs_pos_input vs. chipseq_293t_tc_lgp_hs_neg_input
    ("SRX23751460", "SRX23751458"), # chipseq_293t_tc_lgp_hs_pos_chip_dcas9 vs. chipseq_293t_tc_lgp_hs_neg_chip_dcas9
    ("SRX23751456", "SRX23751455"), # chipseq_293t_tc_ex1_hs_pos_input vs. chipseq_293t_tc_ex1_hs_neg_input
    ("SRX23751457", "SRX23751454"), # chipseq_293t_tc_ex1_hs_pos_chip_dcas9 vs. chipseq_293t_tc_ex1_hs_neg_chip_dcas9
    ("SRX23751453", "SRX23751451"), # chipseq_293t_tc_600_hs_pos_input vs. chipseq_293t_tc_600_hs_neg_input
    ("SRX23751452", "SRX23751450")  # chipseq_293t_tc_600_hs_pos_chip_dcas9 vs. chipseq_293t_tc_600_hs_neg_chip_dcas9
]

paired_metada_df_gse259305 = create_paired_metadata(
    combined_df=GSE259305_combined,
    defined_sample_pairs=defined_pairs_gse259305_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse259305 is not None:
    paired_metada_df_gse259305.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE259305_chipseq_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse259305)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (26, 93)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ cel ┆ cel ┆ gen ┆ tre ┆ chi ┆ chi ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ p_a ┆ p   ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ine ┆ ype ┆ pe  ┆ ent ┆ nti ┆ --- ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ bod ┆ str ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ y   ┆     ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ chi ┆ ChI ┆ GSM ┆ Pub ┆ Nov ┆ Dec ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ Cel ┆ Hum ┆ gen ┆ Cel ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Nex ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ DLD ┆ Col ┆ FUB ┆ nul ┆ FUB ┆ The ┆ hg3 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 120 ┆ SRR ┆ Nex ┆ SAM ┆ Tur ┆ SRA ┆ ChI ┆ 202 ┆ 216 ┆ ILL ┆ ftp ┆ nul ┆ nul ┆ dba ┆ SRP ┆ 679 ┆ Tur ┆ GEN ┆ nul ┆ Nex ┆ Nex ┆ nul ┆ ftp ┆ 686 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ nul ┆ nul ┆ GSM ┆ Cel ┆ nul ┆ GSM ┆ nul ┆ GSM ┆ nul ┆ 202 ┆ nul ┆ nul ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 268 ┆ 268 ┆ p-s ┆ P-s ┆ 865 ┆ lic ┆ 26  ┆ 21  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ ls  ┆ an  ┆ omi ┆ ls  ┆ 301 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ tSe ┆ P   ┆ omi ┆ P-S ┆ 865 ┆ :// ┆ 259 ┆     ┆ -1  ┆ ore ┆ P3  ┆ l   ┆ P3  ┆ poo ┆ 8   ┆ Wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 315 ┆ tSe ┆ N45 ┆ boC ┆ 202 ┆ P   ┆ 4-1 ┆ 285 ┆ UMI ┆ .sr ┆ l   ┆ l   ┆ 16e ┆ 491 ┆ 593 ┆ boC ┆ ERA ┆ l   ┆ tSe ┆ tSe ┆ l   ┆ .sr ┆ 708 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ l   ┆ l   ┆ 865 ┆ ls  ┆ l   ┆ 865 ┆ l   ┆ 865 ┆ l   ┆ 4-1 ┆ l   ┆ l   ┆ NA1 ┆ 315 ┆ 233 ┆ 4-1 ┆ 259 │
│ 883 ┆ 883 ┆ eq_ ┆ eq_ ┆ 319 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ DLD ┆ c   ┆ wer ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ q   ┆     ┆ c   ┆ eq  ┆ 319 ┆ ftp ┆ 305 ┆     ┆     ┆ cta ┆ kno ┆     ┆     ┆ r-q ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 207 ┆ q   ┆ 068 ┆ as: ┆ 315 ┆     ┆ 2-2 ┆ 025 ┆ NA  ┆ a.e ┆     ┆     ┆ 8a7 ┆ 824 ┆ 06  ┆ as: ┆ TED ┆     ┆ q   ┆ q   ┆     ┆ a.e ┆ 368 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆     ┆     ┆ 319 ┆ wer ┆     ┆ 319 ┆     ┆ 319 ┆     ┆ 2-2 ┆     ┆     ┆ 080 ┆ 207 ┆ 686 ┆ 2-2 ┆ 305 │
│ 07  ┆ 05  ┆ fub ┆ FUB ┆ 1   ┆ Dec ┆ 4   ┆ 4   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ -1  ┆ DNA ┆ e   ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ 1   ┆ .nc ┆     ┆     ┆     ┆ l   ┆ ckd ┆     ┆     ┆ ual ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 88  ┆ 200 ┆ 049 ┆ A   ┆ 8   ┆     ┆ 5   ┆ 9;2 ┆     ┆ bi. ┆     ┆     ┆ 216 ┆     ┆ vs  ┆ A   ┆ _FI ┆     ┆ 200 ┆ 200 ┆     ┆ bi. ┆ 5   ┆     ┆     ┆     ┆     ┆ ebi ┆     ┆     ┆ 1_r ┆ e   ┆     ┆ 1_r ┆     ┆ 1   ┆     ┆ 5   ┆     ┆     ┆ 615 ┆ 88  ┆ 07  ┆ 5   ┆     │
│     ┆     ┆ p3_ ┆ P3_ ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ tre ┆ cel ┆     ┆ cro ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆     ┆ ade ┆ own ┆     ┆     ┆ ity ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ 0   ┆ vs  ┆ met ┆     ┆     ┆     ┆ 256 ┆     ┆ ac. ┆     ┆     ┆ 1a6 ┆     ┆ 629 ┆ met ┆ LE; ┆     ┆ 0   ┆ 0   ┆     ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆     ┆     ┆ 1   ┆ cro ┆     ┆ 1   ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ dld ┆ DLD ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆ ls  ┆     ┆ ssl ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆     ┆ noc ┆     ┆     ┆     ┆ bas ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ seq ┆ SAM ┆ hod ┆     ┆     ┆     ┆ 276 ┆     ┆ uk/ ┆     ┆     ┆ da5 ┆     ┆ 790 ┆ hod ┆ GEN ┆     ┆     ┆ seq ┆     ┆ uk/ ┆ 636 ┆     ┆     ┆     ┆     ┆ .uk ┆     ┆     ┆ vs  ┆ ssl ┆     ┆ vs  ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ 1_s ┆ 1_s ┆ 865 ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ wer ┆     ┆ ink ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 865 ┆ .ni ┆     ┆     ┆     ┆ arc ┆     ┆     ┆     ┆ es  ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 315 ┆ uen ┆ N45 ┆ for ┆     ┆     ┆     ┆ 003 ┆     ┆ vol ┆     ┆     ┆ f92 ┆     ┆ 36  ┆ for ┆ ERA ┆     ┆     ┆ uen ┆     ┆ vol ┆ 567 ┆     ┆     ┆     ┆     ┆ :/v ┆     ┆     ┆ GSM ┆ ink ┆     ┆ GSM ┆     ┆ 865 ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆ 233 ┆     ┆     │
│     ┆     ┆ hfu ┆ hFU ┆ 318 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆ e   ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 318 ┆ h.g ┆     ┆     ┆     ┆ ino ┆     ┆     ┆     ┆ wer ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ 207 ┆ cin ┆ 068 ┆ loc ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ 37c ┆     ┆     ┆ loc ┆ TED ┆     ┆     ┆ cin ┆     ┆ 1/f ┆ 001 ┆     ┆     ┆     ┆     ┆ ol1 ┆     ┆     ┆ 865 ┆ ed  ┆     ┆ 865 ┆     ┆ 318 ┆     ┆     ┆     ┆     ┆     ┆ 207 ┆ 686 ┆     ┆     │
│     ┆     ┆ bp3 ┆ BP3 ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ cul ┆     ┆ wit ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ ov/ ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆ 90  ┆ g:  ┆ 051 ┆ us- ┆     ┆     ┆     ┆ 201 ┆     ┆ ast ┆     ┆     ┆ 18a ┆     ┆     ┆ us- ┆ _FI ┆     ┆     ┆ g:  ┆     ┆ ast ┆ 3   ┆     ┆     ┆     ┆     ┆ /fa ┆     ┆     ┆ 318 ┆ wit ┆     ┆ 318 ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ 90  ┆ 05  ┆     ┆     │
│     ┆     ┆ _hs ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆ tur ┆     ┆ h   ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆ v/b ┆ v/s ┆ ell ┆     ┆     ┆     ┆ GSM ┆     ┆ spe ┆     ┆     ┆     ┆ 752 ┆     ┆ q/S ┆     ┆     ┆ 5fb ┆     ┆     ┆ spe ┆ LE  ┆     ┆     ┆ GSM ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆ 9_r ┆ h   ┆     ┆ 9_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ab ┆ _Ab ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆ ed  ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mme ┆     ┆     ┆ ios ┆ ra? ┆ .20 ┆     ┆     ┆     ┆ 865 ┆     ┆ cif ┆     ┆     ┆     ┆ 213 ┆     ┆ RR3 ┆     ┆     ┆ b4; ┆     ┆     ┆ cif ┆     ┆     ┆     ┆ 865 ┆     ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 1   ┆ 1%  ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆ at  ┆     ┆ for ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ amp ┆ ter ┆ 23. ┆     ┆     ┆     ┆ 319 ┆     ┆ ic  ┆     ┆     ┆     ┆ 3;2 ┆     ┆ 15/ ┆     ┆     ┆ 782 ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆ 319 ┆     ┆ 15/ ┆     ┆     ┆     ┆     ┆     ┆ R31 ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆ 37° ┆     ┆ mal ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆ le/ ┆ m=S ┆ 03. ┆     ┆     ┆     ┆ 1:  ┆     ┆ lab ┆     ┆     ┆     ┆ 095 ┆     ┆ 088 ┆     ┆     ┆ 5ab ┆     ┆     ┆ lab ┆     ┆     ┆     ┆ 1:  ┆     ┆ 088 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ chi ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆ C   ┆     ┆ deh ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆ SAM ┆ RX2 ┆ 010 ┆     ┆     ┆     ┆ ChI ┆     ┆ eli ┆     ┆     ┆     ┆ 288 ┆     ┆ /SR ┆     ┆     ┆ 03e ┆     ┆     ┆ eli ┆     ┆     ┆     ┆ ChI ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 88/ ┆     ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p-s ┆ P-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42° ┆ in  ┆     ┆ yde ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 865 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tri ┆     ┆     ┆ N45 ┆ 688 ┆     ┆     ┆     ┆     ┆ P-s ┆     ┆ ng  ┆     ┆     ┆     ┆ 067 ┆     ┆ R31 ┆     ┆     ┆ 6b2 ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆ P-s ┆     ┆ R31 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq_ ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆ DME ┆     ┆ (Th ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mmo ┆     ┆     ┆ 068 ┆ 830 ┆     ┆     ┆     ┆     ┆ eq_ ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆ 520 ┆     ┆     ┆ 90d ┆     ┆     ┆ of  ┆     ┆     ┆     ┆ eq_ ┆     ┆ 520 ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆     ┆     ┆     ┆ (Th ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ fub ┆ FUB ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆ M   ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mat ┆     ┆     ┆ 049 ┆ 7   ┆     ┆     ┆     ┆     ┆ FUB ┆     ┆ gen ┆     ┆     ┆     ┆     ┆     ┆ 788 ┆     ┆     ┆ ac0 ┆     ┆     ┆ gen ┆     ┆     ┆     ┆ FUB ┆     ┆ 788 ┆     ┆     ┆     ┆     ┆     ┆ 207 ┆     ┆     ┆     ┆ erm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p3_ ┆ P3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ sup ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ P3_ ┆     ┆ omi ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ e58 ┆     ┆     ┆ omi ┆     ┆     ┆     ┆ P3_ ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 88/ ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 21. GSE276302 (ChIP-seq; HSF1) (ChIP-Atlas: False)

- [HSF1–DBC1 axis drives prostate cancer progression by activating a metastatic transcriptional program](https://doi.org/10.1038/s12276-025-01545-7)
- `Detection of phosphorylated HSF1 and kinase assays; 22RV1 and SM1 cells were treated with HS at 42 °C or GSK-626616 (DYRK inhibitor, Tocris Bioscience) and lysed in FLAG lysis buffer24 containing phosphatase and protease inhibitor cocktails (Roche Diagnostics). `

In [44]:
GSE276302_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE276302/GSE276302_PEP/GSE276302_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1038/s12276-025-01545-7").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE276302 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE276302.metadata.tsv",
    separator='\t'
)

GSE276302_combined = GSE276302_PEP.join(
    GSE276302,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE276302_combined = GSE276302_combined[[s.name for s in GSE276302_combined if not (s.null_count() == GSE276302_combined.height)]]

display(GSE276302_combined)

shape: (37, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ chi ┆ cel ┆ cel ┆ tre ┆ bas ┆ ada ┆ ali ┆ ded ┆ pea ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ p_a ┆ l_l ┆ l_t ┆ atm ┆ eca ┆ pte ┆ gn  ┆ upl ┆ k_c ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ nti ┆ ine ┆ ype ┆ ent ┆ lli ┆ r_t ┆ --- ┆ ica ┆ all ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ bod ┆ --- ┆ --- ┆ --- ┆ ng  ┆ rim ┆ str ┆ tio ┆ ing ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ y   ┆ str ┆ str ┆ str ┆ --- ┆ min ┆     ┆ n   ┆ --- ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆ --- ┆     ┆     ┆     ┆ str ┆ g   ┆     ┆ --- ┆ str ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ hsf ┆ HSF ┆ GSM ┆ Pub ┆ Sep ┆ Sep ┆ SRA ┆ 1   ┆ 22R ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Jeo ┆ Sun ┆ Irw ┆ Seo ┆ 135 ┆ Sou ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HSF ┆ 22R ┆ Cas ┆ Non ┆ bcl ┆ Tri ┆ Bow ┆ Pic ┆ MAC ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ DBC ┆ SRA ┆ ChI ┆ 202 ┆ 282 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ HSF ┆ b13 ┆ SRP ┆ 551 ┆ DBC ┆ GEN ┆ HSF ┆ Ill ┆ Ill ┆ Cas ┆ ftp ┆ 111 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Chr ┆ mis ┆ GSM ┆ 22R ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 1_n ┆ 1_N ┆ 849 ┆ lic ┆ 04  ┆ 02  ┆     ┆     ┆ V1  ┆ o   ┆ 6   ┆ omi ┆ 246 ┆ ng, ┆ gky ┆ on- ┆ ul  ┆ -71 ┆ th  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 849 ┆ :// ┆ 276 ┆     ┆ 259 ┆ 1   ┆ V1  ┆ tra ┆ -he ┆ 2fa ┆ mmo ┆ tie ┆ ard ┆ S2  ┆ 9   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 305 ┆ umi ┆ N43 ┆ 1   ┆ 196 ┆ P   ┆ 5-0 ┆ 063 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 1_N ┆ 453 ┆ 530 ┆ 914 ┆ 1   ┆ ERA ┆ 1_N ┆ umi ┆ umi ┆ tra ┆ .sr ┆ 486 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 849 ┆ 849 ┆ oma ┆ sin ┆ 849 ┆ V1  ┆ 849 ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA1 ┆ 305 ┆ 225 ┆ 5-0 ┆ 276 │
│ hs_ ┆ HS_ ┆ 616 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 76  ┆ Hoo ┆ unk ┆ don ┆     ┆ 0   ┆ Kor ┆ na  ┆     ┆ c   ┆ eq  ┆ 616 ┆ ftp ┆ 302 ┆     ┆ 663 ┆ (En ┆     ┆ tio ┆ at  ┆ stq ┆ mat ┆ 1.1 ┆ 1.1 ┆ 2.1 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 429 ┆ na  ┆ 495 ┆ pro ┆ 254 ┆     ┆ 9-0 ┆ 993 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ HS_ ┆ 6c3 ┆ 416 ┆ 25  ┆ pro ┆ TED ┆ HS_ ┆ na  ┆ na  ┆ tio ┆ a.e ┆ 678 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 616 ┆ 616 ┆ tin ┆ g   ┆ 616 ┆     ┆ 616 ┆ x:t ┆ 9-0 ┆ sap ┆     ┆ 156 ┆ 429 ┆ 445 ┆ 9-0 ┆ 302 │
│ 22r ┆ 22R ┆ 6   ┆ Sep ┆ 4   ┆ 5   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ n,K ┆ wan ┆ g   ┆     ┆     ┆ ea  ┆ Nov ┆     ┆     ┆     ┆ 6   ┆ .nc ┆     ┆     ┆ 63  ┆ zo, ┆     ┆ n-r ┆ sho ┆ v2. ┆ ic  ┆ .2  ┆ 18  ┆ .1. ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 83  ┆ Nov ┆ 088 ┆ mot ┆ 4   ┆     ┆ 3   ┆ 8;3 ┆     ┆ bi. ┆     ┆     ┆ 22R ┆ a58 ┆     ┆     ┆ mot ┆ _FI ┆ 22R ┆ Nov ┆ Nov ┆ n-r ┆ bi. ┆ 50  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 6   ┆ 6_r ┆ pre ┆     ┆ 6_r ┆     ┆ 6   ┆ err ┆ 3   ┆ ien ┆     ┆ 585 ┆ 83  ┆ 55  ┆ 3   ┆     │
│ v1  ┆ V1  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ im  ┆ Uni ┆ Gan ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆ ADI ┆     ┆ esi ┆ ck  ┆ 20. ┆ v0. ┆     ┆ Mar ┆ 201 ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ aSe ┆     ┆ es  ┆     ┆     ┆     ┆ 004 ┆     ┆ ac. ┆     ┆     ┆ V1  ┆ 645 ┆     ┆     ┆ es  ┆ LE; ┆ V1  ┆ aSe ┆ aSe ┆ esi ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ par ┆     ┆ 1   ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆ gna ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆     ┆     ┆     ┆ -SP ┆     ┆ sta ┆ (NH ┆ 0   ┆ 38  ┆     ┆ kDu ┆ 603 ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ q   ┆     ┆ met ┆     ┆     ┆     ┆ 840 ┆     ┆ uk/ ┆     ┆     ┆     ┆ 42d ┆     ┆     ┆ met ┆ GEN ┆     ┆ q   ┆ q   ┆ sta ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit ┆ m-g ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆ .ni ┆     ┆     ┆     ┆ A-9 ┆     ┆ nt  ┆ S)  ┆     ┆     ┆     ┆ pli ┆ 09  ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ 600 ┆     ┆ ast ┆     ┆     ┆     ┆ 797 ┆     ┆ vol ┆     ┆     ┆     ┆ cb5 ┆     ┆     ┆ ast ┆ ERA ┆     ┆ 600 ┆ 600 ┆ nt  ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆ 01- ┆     ┆ pro ┆     ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆     ┆ 0   ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆     ┆ 3aa ┆     ┆     ┆ ati ┆ TED ┆     ┆ 0   ┆ 0   ┆ pro ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆ F)  ┆     ┆ sta ┆     ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ .go ┆ .go ┆ s12 ┆     ┆     ┆     ┆ seq ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆ 428 ┆     ┆     ┆ c   ┆ _FI ┆     ┆     ┆ seq ┆ sta ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 276 ┆     ┆     ┆     ┆ uen ┆     ┆ cas ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆     ┆ 91c ┆     ┆     ┆ cas ┆ LE  ┆     ┆     ┆ uen ┆ te  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ can ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ cin ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ RR3 ┆     ┆     ┆     ┆ f7; ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ cin ┆ can ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ cer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 5-0 ┆     ┆     ┆     ┆ g:  ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆ 05/ ┆     ┆     ┆     ┆ dc7 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ g:  ┆ cer ┆ 05/ ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆ 213 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 154 ┆     ┆     ┆     ┆ GSM ┆     ┆ n-r ┆     ┆     ┆     ┆     ┆     ┆ 083 ┆     ┆     ┆     ┆ 5ad ┆     ┆     ┆ n-r ┆     ┆     ┆     ┆ GSM ┆ cel ┆ 083 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆ ;33 ┆     ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 5-7 ┆     ┆     ┆     ┆ 849 ┆     ┆ esi ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 4f6 ┆     ┆     ┆ esi ┆     ┆     ┆     ┆ 849 ┆ ls  ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 83/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N43 ┆ 596 ┆     ┆     ┆     ┆     ┆ 616 ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆     ┆     ┆     ┆ b05 ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ 616 ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 495 ┆ 636 ┆     ┆     ┆     ┆     ┆ 6:  ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆ 542 ┆     ┆     ┆     ┆ 1ff ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆ 6:  ┆     ┆ 542 ┆     ┆     ┆     ┆     ┆     ┆ 305 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 088 ┆ 3   ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ 983 ┆     ┆     ┆     ┆ 42a ┆     ┆     ┆ pro ┆     ┆     ┆     ┆ HSF ┆     ┆ 983 ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_N ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 7a3 ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ 1_N ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 83/ ┆ 93; ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 496 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆     ┆     ┆     ┆ c4d ┆     ┆     ┆ te  ┆     ┆     ┆     ┆ HS_ ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ Sim ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [45]:
defined_pairs_gse276302_chipseq = [
    ("SRX25966366", "SRX25966363"), # hsf1_hs_22rv1 vs. hsf1_nhs_22rv1
    ("SRX25966368", "SRX25966365"), # hsf1_hs_22rv1_d1ko vs. hsf1_nhs_22rv1_d1ko
    ("SRX25966367", "SRX25966364"), # hsf1_hs_22rv1_h1ko vs. hsf1_nhs_22rv1_h1ko
    ("SRX25966372", "SRX25966369"), # input_hsf1_hs_22rv1 vs. input_hsf1_nhs_22rv1
    ("SRX25966374", "SRX25966371"), # input_hsf1_hs_22rv1_d1ko vs. input_hsf1_nhs_22rv1_d1ko
    ("SRX25966373", "SRX25966370"), # input_hsf1_hs_22rv1_h1ko vs. input_hsf1_nhs_22rv1_h1ko
    # ("SRX25966384", "SRX25966381"), # input_k27ac_hs_22rv1 vs. input_k27ac_nhs_22rv1
    # ("SRX25966386", "SRX25966383"), # input_k27ac_hs_22rv1_d1ko vs. input_k27ac_nhs_22rv1_d1ko
    # ("SRX25966385", "SRX25966382"), # input_k27ac_hs_22rv1_h1ko vs. input_k27ac_nhs_22rv1_h1ko

    # # H3K27ac
    # ("SRX25966378", "SRX25966375"), # k27ac_hs_22rv1 vs. k27ac_nhs_22rv1
    # ("SRX25966380", "SRX25966377"), # k27ac_hs_22rv1_d1ko vs. k27ac_nhs_22rv1_d1ko
    # ("SRX25966379", "SRX25966376")  # k27ac_hs_22rv1_h1ko vs. k27ac_nhs_22rv1_h1ko
]

paired_metada_df_gse276302 = create_paired_metadata(
    combined_df=GSE276302_combined,
    defined_sample_pairs=defined_pairs_gse276302_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse276302 is not None:
    paired_metada_df_gse276302.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE276302_chipseq_paired_metadata.tsv",
        separator='\t'
    )
    
    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse276302)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ chi ┆ cel ┆ cel ┆ tre ┆ bas ┆ ada ┆ ali ┆ ded ┆ pea ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ p_a ┆ l_l ┆ l_t ┆ atm ┆ eca ┆ pte ┆ gn  ┆ upl ┆ k_c ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ nti ┆ ine ┆ ype ┆ ent ┆ lli ┆ r_t ┆ --- ┆ ica ┆ all ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ bod ┆ --- ┆ --- ┆ --- ┆ ng  ┆ rim ┆ str ┆ tio ┆ ing ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ y   ┆ str ┆ str ┆ str ┆ --- ┆ min ┆     ┆ n   ┆ --- ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ --- ┆     ┆     ┆     ┆ str ┆ g   ┆     ┆ --- ┆ str ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hsf ┆ HSF ┆ GSM ┆ Pub ┆ Sep ┆ Sep ┆ SRA ┆ 1   ┆ 22R ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Jeo ┆ Sun ┆ Irw ┆ Seo ┆ 135 ┆ Sou ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ HSF ┆ 22R ┆ Cas ┆ Hea ┆ bcl ┆ Tri ┆ Bow ┆ Pic ┆ MAC ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ DBC ┆ SRA ┆ ChI ┆ 202 ┆ 299 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ HSF ┆ 89d ┆ SRP ┆ 579 ┆ DBC ┆ GEN ┆ HSF ┆ Ill ┆ Ill ┆ Cas ┆ ftp ┆ 117 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Chr ┆ mis ┆ GSM ┆ 22R ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 259 ┆ 259 ┆ 1_h ┆ 1_H ┆ 849 ┆ lic ┆ 04  ┆ 02  ┆     ┆     ┆ V1  ┆ o   ┆ 6   ┆ omi ┆ 246 ┆ ng, ┆ gky ┆ on- ┆ ul  ┆ -71 ┆ th  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 849 ┆ :// ┆ 276 ┆     ┆ 1   ┆ V1  ┆ tra ┆ t   ┆ 2fa ┆ mmo ┆ tie ┆ ard ┆ S2  ┆ 9   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 305 ┆ umi ┆ N43 ┆ 1   ┆ 196 ┆ P   ┆ 5-0 ┆ 653 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 1_H ┆ f7e ┆ 530 ┆ 842 ┆ 1   ┆ ERA ┆ 1_H ┆ umi ┆ umi ┆ tra ┆ .sr ┆ 128 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 849 ┆ 849 ┆ oma ┆ sin ┆ 849 ┆ V1  ┆ 849 ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA1 ┆ 305 ┆ 225 ┆ 5-0 ┆ 276 │
│ 663 ┆ 663 ┆ s_2 ┆ S_2 ┆ 616 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 76  ┆ Hoo ┆ unk ┆ don ┆     ┆ 0   ┆ Kor ┆ na  ┆     ┆ c   ┆ eq  ┆ 616 ┆ ftp ┆ 302 ┆     ┆ (En ┆     ┆ tio ┆ sho ┆ stq ┆ mat ┆ 1.1 ┆ 1.1 ┆ 2.1 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 429 ┆ na  ┆ 495 ┆ pro ┆ 254 ┆     ┆ 9-0 ┆ 604 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ S_2 ┆ 857 ┆ 416 ┆ 41  ┆ pro ┆ TED ┆ S_2 ┆ na  ┆ na  ┆ tio ┆ a.e ┆ 166 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 616 ┆ 616 ┆ tin ┆ g   ┆ 616 ┆     ┆ 616 ┆ x:t ┆ 9-0 ┆ sap ┆     ┆ 156 ┆ 429 ┆ 445 ┆ 9-0 ┆ 302 │
│ 66  ┆ 63  ┆ 2rv ┆ 2RV ┆ 9   ┆ Sep ┆ 4   ┆ 5   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ n,K ┆ wan ┆ g   ┆     ┆     ┆ ea  ┆ Nov ┆     ┆     ┆     ┆ 9   ┆ .nc ┆     ┆     ┆ zo, ┆     ┆ n-r ┆ ck  ┆ v2. ┆ ic  ┆ .2  ┆ 18  ┆ .1. ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 80  ┆ Nov ┆ 085 ┆ mot ┆ 4   ┆     ┆ 3   ┆ 2;3 ┆     ┆ bi. ┆     ┆     ┆ 2RV ┆ 83b ┆     ┆ vs  ┆ mot ┆ _FI ┆ 2RV ┆ Nov ┆ Nov ┆ n-r ┆ bi. ┆ 82  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 9   ┆ 9_r ┆ pre ┆     ┆ 9_r ┆     ┆ 9   ┆ err ┆ 3   ┆ ien ┆     ┆ 585 ┆ 80  ┆ 56  ┆ 3   ┆     │
│     ┆     ┆ 1   ┆ 1   ┆ vs  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ im  ┆ Uni ┆ Gan ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ ADI ┆     ┆ esi ┆ at  ┆ 20. ┆ v0. ┆     ┆ Mar ┆ 201 ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ aSe ┆ vs  ┆ es  ┆     ┆     ┆     ┆ 055 ┆     ┆ ac. ┆     ┆     ┆ 1   ┆ e51 ┆     ┆ 551 ┆ es  ┆ LE; ┆ 1   ┆ aSe ┆ aSe ┆ esi ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ par ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆ gna ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ -SP ┆     ┆ sta ┆ 42℃ ┆ 0   ┆ 38  ┆     ┆ kDu ┆ 603 ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ q   ┆ SAM ┆ met ┆     ┆     ┆     ┆ 034 ┆     ┆ uk/ ┆     ┆     ┆ vs  ┆ 912 ┆     ┆ 914 ┆ met ┆ GEN ┆ vs  ┆ q   ┆ q   ┆ sta ┆ uk/ ┆ 111 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ati ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ hsf ┆ HSF ┆ 849 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit ┆ m-g ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 849 ┆ .ni ┆     ┆     ┆ A-9 ┆     ┆ nt  ┆ for ┆     ┆     ┆     ┆ pli ┆ 09  ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 305 ┆ 600 ┆ N43 ┆ ast ┆     ┆     ┆     ┆ 222 ┆     ┆ vol ┆     ┆     ┆ HSF ┆ 122 ┆     ┆ 25  ┆ ast ┆ ERA ┆ HSF ┆ 600 ┆ 600 ┆ nt  ┆ vol ┆ 486 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 849 ┆ GSM ┆ on  ┆     ┆ GSM ┆     ┆ 849 ┆ l;e ┆     ┆     ┆     ┆     ┆ 305 ┆ 225 ┆     ┆     │
│     ┆     ┆ 1_n ┆ 1_N ┆ 616 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 616 ┆ h.g ┆     ┆     ┆ 01- ┆     ┆ pro ┆ 60  ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ 429 ┆ 0   ┆ 495 ┆ ati ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ 1_N ┆ b9a ┆     ┆     ┆ ati ┆ TED ┆ 1_N ┆ 0   ┆ 0   ┆ pro ┆ 1/f ┆ 678 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 616 ┆ 849 ┆ and ┆     ┆ 849 ┆     ┆ 616 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 429 ┆ 445 ┆     ┆     │
│     ┆     ┆ hs_ ┆ HS_ ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ ov/ ┆     ┆     ┆ F)  ┆     ┆ sta ┆ min ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ .go ┆ .go ┆ s12 ┆     ┆     ┆ 83  ┆ seq ┆ 088 ┆ c   ┆     ┆     ┆     ┆ 282 ┆     ┆ ast ┆     ┆     ┆ HS_ ┆ cce ┆     ┆     ┆ c   ┆ _FI ┆ HS_ ┆     ┆ seq ┆ sta ┆ ast ┆ 50  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 6   ┆ 616 ┆ ChI ┆     ┆ 616 ┆     ┆ 6   ┆ tax ┆     ┆     ┆     ┆     ┆ 83  ┆ 55  ┆     ┆     │
│     ┆     ┆ 22r ┆ 22R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ te  ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 276 ┆     ┆     ┆     ┆ uen ┆     ┆ cas ┆     ┆     ┆     ┆ 063 ┆     ┆ q/S ┆     ┆     ┆ 22R ┆ 985 ┆     ┆     ┆ cas ┆ LE  ┆ 22R ┆     ┆ uen ┆ te  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 6_r ┆ P   ┆     ┆ 6_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ v1  ┆ V1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ can ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ cin ┆     ┆ tra ┆     ┆     ┆     ┆ 993 ┆     ┆ RR3 ┆     ┆     ┆ V1  ┆ 3c; ┆     ┆     ┆ tra ┆     ┆ V1  ┆     ┆ cin ┆ can ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ wer ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ cer ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 5-0 ┆     ┆     ┆     ┆ g:  ┆     ┆ tio ┆     ┆     ┆     ┆ 8;3 ┆     ┆ 05/ ┆     ┆     ┆     ┆ d80 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ g:  ┆ cer ┆ 05/ ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆ 213 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ cel ┆ Non ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 154 ┆     ┆     ┆     ┆ GSM ┆     ┆ n-r ┆     ┆     ┆     ┆ 004 ┆     ┆ 080 ┆     ┆     ┆     ┆ b3b ┆     ┆     ┆ n-r ┆     ┆     ┆     ┆ GSM ┆ cel ┆ 080 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆ ;33 ┆     ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ ls  ┆ -he ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 5-7 ┆     ┆     ┆     ┆ 849 ┆     ┆ esi ┆     ┆     ┆     ┆ 840 ┆     ┆ /SR ┆     ┆     ┆     ┆ db8 ┆     ┆     ┆ esi ┆     ┆     ┆     ┆ 849 ┆ ls  ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 80/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N43 ┆ 596 ┆     ┆     ┆     ┆     ┆ 616 ┆     ┆ sta ┆     ┆     ┆     ┆ 797 ┆     ┆ R30 ┆     ┆     ┆     ┆ d11 ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ 616 ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 495 ┆ 636 ┆     ┆     ┆     ┆     ┆ 9:  ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆ 542 ┆     ┆     ┆     ┆ acc ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆ 9:  ┆     ┆ 542 ┆     ┆     ┆     ┆     ┆     ┆ 305 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 085 ┆ 6   ┆     ┆     ┆     ┆     ┆ HSF ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ 980 ┆     ┆     ┆     ┆ 809 ┆     ┆     ┆ pro ┆     ┆     ┆     ┆ HSF ┆     ┆ 980 ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆ (NH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ 1_H ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 6cd ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ 1_H ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 80/ ┆ 93; ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 496 ┆     ┆     ┆     ┆     ┆     ┆ S)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ S_2 ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆     ┆     ┆     ┆ e50 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆ S_2 ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ Sim ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 22. GSE303857 (ChIP-seq; PolII) (ChIP-Atlas: False)

- [CPSF73 activation and 3′ RNA polymerase II pausing are lost during readthrough transcription after heat shock](https://doi.org/10.1016/j.celrep.2026.117039)

In [46]:
GSE303857_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE303857/GSE303857_PEP/GSE303857_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1016/j.celrep.2026.117039").alias("reference_doi"),
    pl.lit("44 C").alias("stress treatment temperature"), # see "Cell culture section"
    pl.lit("60 min.").alias("stress treatment time") # see "Cell culture section"
).rename(
    {
        "big_key": "experiment_accession"
    }
)

GSE303857 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE303857.metadata.tsv",
    separator='\t'
)

GSE303857_combined = GSE303857_PEP.join(
    GSE303857,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE303857_combined = GSE303857_combined[[s.name for s in GSE303857_combined if not (s.null_count() == GSE303857_combined.height)]]

GSE303857_combined.write_csv(
    "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE303857_chipseq_paired_metadata_sorted.tsv",
    separator='\t'
)

display(GSE303857_combined)

shape: (15, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ bat ┆ chi ┆ lib ┆ ass ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ ch  ┆ p_a ┆ rar ┆ emb ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ --- ┆ nti ┆ y_n ┆ ly  ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ str ┆ bod ┆ ame ┆ --- ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ cce ┆ str ┆ str ┆ str ┆     ┆ y   ┆ --- ┆ str ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ _ri ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ i64 ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ ght ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆ --- ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ inp ┆ inp ┆ GSM ┆ Pub ┆ Jul ┆ Jan ┆ SRA ┆ 1   ┆ HEK ┆ Hom ┆ 960 ┆ Cel ┆ gen ┆ GPL ┆ Kai ┆ kaw ┆ Goo ┆ CU  ┆ 341 ┆ Bou ┆ CO  ┆ 803 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ HEK ┆ Hum ┆ non ┆ R6  ┆ non ┆ INP ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 44  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ CPS ┆ SRA ┆ ChI ┆ 202 ┆ 267 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ inp ┆ 2ca ┆ SRP ┆ 370 ┆ CPS ┆ GEN ┆ inp ┆ Ill ┆ Ill ┆ Hum ┆ ftp ┆ 111 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ HEK ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ ut_ ┆ ut  ┆ 913 ┆ lic ┆ 28  ┆ 30  ┆     ┆     ┆ 293 ┆ o   ┆ 6   ┆ ls  ┆ omi ┆ 246 ┆ tly ┆ a30 ┆ dri ┆ Bou ┆ 5   ┆ lde ┆     ┆ 03  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 913 ┆ :// ┆ 303 ┆     ┆ 298 ┆ 293 ┆ an  ┆ e   ┆ and ┆ e   ┆ UT_ ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 347 ┆ umi ┆ N50 ┆ F73 ┆ 218 ┆ P   ┆ 6-0 ┆ 333 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ ut  ┆ e15 ┆ 604 ┆ 770 ┆ F73 ┆ ERA ┆ ut  ┆ umi ┆ umi ┆ an  ┆ .sr ┆ 972 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 913 ┆ 913 ┆ ls  ┆ sin ┆ 913 ┆ 293 ┆ 913 ┆ _ta ┆ 6-0 ┆ o   ┆ 6   ┆ NA1 ┆ 347 ┆ 259 ┆ 6-0 ┆ 303 │
│ con ┆ con ┆ 702 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ c   ┆ 76  ┆ n,, ┆ 71@ ┆ ch- ┆ lde ┆ Col ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 702 ┆ ftp ┆ 857 ┆     ┆ 760 ┆     ┆ emb ┆     ┆ R8  ┆     ┆ HEK ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 422 ┆ na  ┆ 237 ┆ act ┆ 209 ┆     ┆ 2-2 ┆ 414 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ con ┆ 5e0 ┆ 086 ┆ 20  ┆ act ┆ TED ┆ con ┆ na  ┆ na  ┆ emb ┆ a.e ┆ 600 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 702 ┆ 702 ┆ wer ┆ g   ┆ 702 ┆     ┆ 702 ┆ x:t ┆ 2-2 ┆ sap ┆     ┆ 297 ┆ 422 ┆ 783 ┆ 2-2 ┆ 857 │
│ tro ┆ tro ┆ 6   ┆ Jan ┆ 5   ┆ 6   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ DNA ┆     ┆ Wal ┆ col ┆ Kug ┆ r   ┆ ora ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆ 6   ┆ .nc ┆ ,   ┆     ┆ 77  ┆     ┆ ryo ┆     ┆ chr ┆     ┆ 293 ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 17  ┆ Nov ┆ 551 ┆ iva ┆ 4   ┆     ┆ 2   ┆ 6;2 ┆     ┆ bi. ┆     ┆     ┆ tro ┆ 28e ┆     ┆     ┆ iva ┆ _FI ┆ tro ┆ Nov ┆ Nov ┆ ryo ┆ bi. ┆ 40  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 6   ┆ 6_r ┆ e   ┆     ┆ 6_r ┆     ┆ 6   ┆ err ┆ 2   ┆ ien ┆     ┆ 774 ┆ 17  ┆ 74  ┆ 2   ┆     │
│ l_f ┆ l   ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ hea ┆     ┆     ┆ sh  ┆ ora ┆ el  ┆     ┆ do  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆     ┆ bi. ┆ GSE ┆     ┆     ┆     ┆ nic ┆     ┆ oma ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆     ┆ aSe ┆     ┆ tio ┆     ┆     ┆     ┆ 735 ┆     ┆ ac. ┆     ┆     ┆ l   ┆ c26 ┆     ┆     ┆ tio ┆ LE; ┆ l   ┆ aSe ┆ aSe ┆ nic ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ cro ┆     ┆ 1   ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ or_ ┆ for ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ do. ┆ Lab ┆     ┆ Ave ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆ nlm ┆ 303 ┆     ┆     ┆     ┆ kid ┆     ┆ tin ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆     ┆ q   ┆     ┆ n   ┆     ┆     ┆     ┆ 939 ┆     ┆ uk/ ┆     ┆     ┆ for ┆ e1c ┆     ┆     ┆ n   ┆ GEN ┆ for ┆ q   ┆ q   ┆ kid ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ chi ┆ ChI ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ edu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆ .ni ┆ 860 ┆     ┆     ┆     ┆ ney ┆     ┆ pre ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆     ┆ 600 ┆     ┆ and ┆     ┆     ┆     ┆ 949 ┆     ┆ vol ┆     ┆     ┆ ChI ┆ b69 ┆     ┆     ┆ and ┆ ERA ┆ ChI ┆ 600 ┆ 600 ┆ ney ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ p_i ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆     ┆ 0   ┆     ┆ 3’  ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ P   ┆ b6a ┆     ┆     ┆ 3'  ┆ TED ┆ P   ┆ 0   ┆ 0   ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ n_h ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆     ┆ seq ┆     ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ in  ┆ f8e ┆     ┆     ┆ Pol ┆ _FI ┆ in  ┆     ┆ seq ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ek2 ┆ HEK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ bin ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ elr ┆     ┆     ┆     ┆ uen ┆     ┆ II  ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ HEK ┆ b6c ┆     ┆     ┆ II  ┆ LE  ┆ HEK ┆     ┆ uen ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 93_ ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ ios ┆ ra? ┆ ep. ┆     ┆     ┆     ┆ cin ┆     ┆ pau ┆     ┆     ┆     ┆     ┆     ┆ RR3 ┆     ┆     ┆ 293 ┆ 15; ┆     ┆     ┆ pau ┆     ┆ 293 ┆     ┆ cin ┆     ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ cel ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1:1 ┆     ┆     ┆     ┆ amp ┆ ter ┆ 202 ┆     ┆     ┆     ┆ g:  ┆     ┆ sin ┆     ┆     ┆     ┆     ┆     ┆ 47/ ┆     ┆     ┆ cel ┆ f05 ┆     ┆     ┆ sin ┆     ┆ cel ┆     ┆ g:  ┆     ┆ 47/ ┆     ┆     ┆     ┆     ┆     ┆ R34 ┆ 213 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ ls  ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 6.1 ┆     ┆     ┆     ┆ GSM ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆     ┆ ls  ┆ 33c ┆     ┆     ┆ g   ┆     ┆ ls  ┆     ┆ GSM ┆     ┆ 017 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 170 ┆     ┆     ┆     ┆ 913 ┆     ┆ are ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ a87 ┆     ┆     ┆ are ┆     ┆     ┆     ┆ 913 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 17/ ┆ 511 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 913 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N50 ┆ 987 ┆ 39  ┆     ┆     ┆     ┆ 702 ┆     ┆ los ┆     ┆     ┆     ┆     ┆     ┆ R34 ┆     ┆     ┆     ┆ 8e5 ┆     ┆     ┆ los ┆     ┆     ┆     ┆ 702 ┆     ┆ R34 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 237 ┆ 607 ┆     ┆     ┆     ┆     ┆ 6:  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆     ┆ 009 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ 6:  ┆     ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆ 347 ┆ 11; ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 551 ┆ 7   ┆     ┆     ┆     ┆     ┆ inp ┆     ┆ dur ┆     ┆     ┆     ┆     ┆     ┆ 217 ┆     ┆     ┆     ┆ 69d ┆     ┆     ┆ dur ┆     ┆     ┆     ┆ inp ┆     ┆ 217 ┆     ┆     ┆     ┆     ┆     ┆ 422 ┆ 895 ┆     ┆     ┆ chr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM9 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ut  ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ f2a ┆     ┆     ┆ ing ┆     ┆     ┆     ┆ ut  ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 17/ ┆ 93; ┆     ┆     ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 137 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆ R34 ┆     ┆     ┆     ┆ 338 ┆     ┆     ┆ rea ┆     ┆     ┆     ┆ con ┆     ┆ R34 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 026 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ d-t ┆     ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆     ┆ cc4 ┆     ┆     ┆ d-t ┆     ┆     ┆     ┆ tro ┆     ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆ 347 ┆ 2;7 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ hro ┆     ┆     ┆     ┆     ┆     ┆ 217 ┆     ┆     ┆     ┆ 5ac ┆     ┆     ┆ hro ┆     ┆     ┆     ┆ l   ┆     ┆ 217 ┆     ┆     ┆     ┆     ┆     ┆ 422 ┆ 776 ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆ ugh ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ 1e  ┆     ┆     ┆ ugh ┆     ┆     ┆     ┆ for ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 17_ ┆ ;11 ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [47]:
defined_pairs_gse303857_chipseq = [
    ("SRX29876079", "SRX29876078"), # pol_ii_chip-seq__heat_shock_r1 vs. pol_ii_chip-seq__no_heat_shock_r1
    ("SRX29876081", "SRX29876080"), # pol_ii_chip-seq__heat_shock_r2 vs. pol_ii_chip-seq__no_heat_shock_r2
    ("SRX29876091", "SRX29876090"), # pol_ii_chip-seq__heat_shock_r3 vs. pol_ii_chip-seq__no_heat_shock_r3

    ("SRX29876083", "SRX29876082"), # ser2p_pol_ii_chip-seq_heat_shock_r1 vs. ser2p_pol_ii_chip-seq_no_heat_shock_r1
    ("SRX29876085", "SRX29876084"), # ser2p_pol_ii_chip-seq_heat_shock_r2 vs. ser2p_pol_ii_chip-seq_no_heat_shock_r2

    ("SRX29876087", "SRX29876086"), # tyr1p_pol_ii_chip-seq_heat_shock_r1 vs. tyr1p_pol_ii_chip-seq_no_heat_shock_r1
    ("SRX29876089", "SRX29876088")  # tyr1p_pol_ii_chip-seq_heat_shock_r2 vs. tyr1p_pol_ii_chip-seq_no_heat_shock_r2
]

paired_metada_df_gse303857 = create_paired_metadata(
    combined_df=GSE303857_combined,
    defined_sample_pairs=defined_pairs_gse303857_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse303857 is not None:
    paired_metada_df_gse303857.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE303857_chipseq_paired_metadata.tsv",
        separator='\t'
    )
    
    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse303857)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (7, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ cel ┆ cel ┆ tre ┆ bat ┆ chi ┆ lib ┆ ass ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ l_l ┆ l_t ┆ atm ┆ ch  ┆ p_a ┆ rar ┆ emb ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ine ┆ ype ┆ ent ┆ --- ┆ nti ┆ y_n ┆ ly  ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ str ┆ bod ┆ ame ┆ --- ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆     ┆ y   ┆ --- ┆ str ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ _ri ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ ght ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆ --- ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ str ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ pol ┆ Pol ┆ GSM ┆ Pub ┆ Jul ┆ Jan ┆ SRA ┆ 1   ┆ HEK ┆ Hom ┆ 960 ┆ Cel ┆ gen ┆ GPL ┆ Kai ┆ kaw ┆ Goo ┆ CU  ┆ 341 ┆ Bou ┆ CO  ┆ 803 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ HEK ┆ Hum ┆ hea ┆ R6  ┆ ant ┆ Rpb ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 44  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ CPS ┆ SRA ┆ ChI ┆ 202 ┆ 489 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ Pol ┆ baa ┆ SRP ┆ 678 ┆ CPS ┆ GEN ┆ Pol ┆ Ill ┆ Ill ┆ Hum ┆ ftp ┆ 205 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Cel ┆ mis ┆ GSM ┆ HEK ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 298 ┆ 298 ┆ _ii ┆ II  ┆ 913 ┆ lic ┆ 28  ┆ 30  ┆     ┆     ┆ 293 ┆ o   ┆ 6   ┆ ls  ┆ omi ┆ 246 ┆ tly ┆ a30 ┆ dri ┆ Bou ┆ 5   ┆ lde ┆     ┆ 03  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 913 ┆ :// ┆ 303 ┆     ┆ 293 ┆ an  ┆ t   ┆ chr ┆ i-R ┆ 1_R ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 347 ┆ umi ┆ N50 ┆ F73 ┆ 218 ┆ P   ┆ 6-0 ┆ 664 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ II  ┆ 5a4 ┆ 604 ┆ 945 ┆ F73 ┆ ERA ┆ II  ┆ umi ┆ umi ┆ an  ┆ .sr ┆ 041 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 913 ┆ 913 ┆ ls  ┆ sin ┆ 913 ┆ 293 ┆ 913 ┆ _ta ┆ 6-0 ┆ o   ┆ 6   ┆ NA1 ┆ 347 ┆ 259 ┆ 6-0 ┆ 303 │
│ 760 ┆ 760 ┆ _ch ┆ ChI ┆ 702 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ wer ┆ c   ┆ 76  ┆ n,, ┆ 71@ ┆ ch- ┆ lde ┆ Col ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 702 ┆ ftp ┆ 857 ┆     ┆     ┆ emb ┆ sho ┆ oma ┆ pb1 ┆ 1_H ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 422 ┆ na  ┆ 237 ┆ act ┆ 209 ┆     ┆ 2-2 ┆ 493 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ ChI ┆ fb8 ┆ 086 ┆ 76  ┆ act ┆ TED ┆ ChI ┆ na  ┆ na  ┆ emb ┆ a.e ┆ 619 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 702 ┆ 702 ┆ wer ┆ g   ┆ 702 ┆     ┆ 702 ┆ x:t ┆ 2-2 ┆ sap ┆     ┆ 297 ┆ 422 ┆ 783 ┆ 2-2 ┆ 857 │
│ 79  ┆ 78  ┆ ip- ┆ P-s ┆ 8   ┆ Jan ┆ 5   ┆ 6   ┆     ┆     ┆     ┆ ien ┆     ┆ e   ┆ DNA ┆     ┆ Wal ┆ col ┆ Kug ┆ r   ┆ ora ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆     ┆     ┆ 8   ┆ .nc ┆ ,   ┆     ┆     ┆ ryo ┆ ck  ┆ tin ┆ N-t ┆ S   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 15  ┆ Nov ┆ 549 ┆ iva ┆ 4   ┆     ┆ 2   ┆ 5;4 ┆     ┆ bi. ┆     ┆     ┆ P-s ┆ 71e ┆     ┆ vs  ┆ iva ┆ _FI ┆ P-s ┆ Nov ┆ Nov ┆ ryo ┆ bi. ┆ 52  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ e   ┆     ┆ 8_r ┆     ┆ 8   ┆ err ┆ 2   ┆ ien ┆     ┆ 774 ┆ 15  ┆ 75  ┆ 2   ┆     │
│     ┆     ┆ seq ┆ eq, ┆ vs  ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ hea ┆     ┆     ┆ sh  ┆ ora ┆ el  ┆     ┆ do  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆     ┆ nic ┆ vs  ┆ pre ┆ erm ┆ vs  ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ aSe ┆ vs  ┆ tio ┆     ┆     ┆     ┆ 944 ┆     ┆ ac. ┆     ┆     ┆ eq, ┆ 505 ┆     ┆ 666 ┆ tio ┆ LE; ┆ eq, ┆ aSe ┆ aSe ┆ nic ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ cro ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ __h ┆ hea ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ do. ┆ Lab ┆     ┆ Ave ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 303 ┆     ┆     ┆ kid ┆ non ┆ p   ┆ Cel ┆ Rpb ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ q   ┆ SAM ┆ n   ┆     ┆     ┆     ┆ 618 ┆     ┆ uk/ ┆     ┆     ┆ hea ┆ 249 ┆     ┆ 807 ┆ n   ┆ GEN ┆ hea ┆ q   ┆ q   ┆ kid ┆ uk/ ┆ 201 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ssl ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ eat ┆ t   ┆ 913 ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ edu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 913 ┆ .ni ┆ 860 ┆     ┆     ┆ ney ┆ e   ┆     ┆ l   ┆ 1_R ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 347 ┆ 600 ┆ N50 ┆ and ┆     ┆     ┆     ┆ 177 ┆     ┆ vol ┆     ┆     ┆ t   ┆ 7aa ┆     ┆ 84  ┆ and ┆ ERA ┆ t   ┆ 600 ┆ 600 ┆ ney ┆ vol ┆ 375 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 913 ┆ GSM ┆ ink ┆     ┆ GSM ┆     ┆ 913 ┆ l;e ┆     ┆     ┆     ┆     ┆ 347 ┆ 259 ┆     ┆     │
│     ┆     ┆ _sh ┆ sho ┆ 702 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 702 ┆ h.g ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sig ┆ 1   ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ 422 ┆ 0   ┆ 237 ┆ 3’  ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ sho ┆ 2c1 ┆     ┆     ┆ 3'  ┆ TED ┆ sho ┆ 0   ┆ 0   ┆     ┆ 1/f ┆ 967 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 702 ┆ 913 ┆ ed  ┆     ┆ 913 ┆     ┆ 702 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 422 ┆ 783 ┆     ┆     │
│     ┆     ┆ ock ┆ ck, ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ ov/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆ NHS ┆     ┆ .go ┆ .go ┆ j.c ┆     ┆     ┆ 16  ┆ seq ┆ 550 ┆ Pol ┆     ┆     ┆     ┆ 476 ┆     ┆ ast ┆     ┆     ┆ ck, ┆ 19d ┆     ┆     ┆ Pol ┆ _FI ┆ ck, ┆     ┆ seq ┆     ┆ ast ┆ 68  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 7   ┆ 702 ┆ wit ┆     ┆ 702 ┆     ┆ 7   ┆ tax ┆     ┆     ┆     ┆     ┆ 16  ┆ 73  ┆     ┆     │
│     ┆     ┆ _r1 ┆ R1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆     ┆ v/b ┆ v/s ┆ elr ┆     ┆     ┆     ┆ uen ┆     ┆ II  ┆     ┆     ┆     ┆ 828 ┆     ┆ q/S ┆     ┆     ┆ R1  ┆ 5b1 ┆     ┆     ┆ II  ┆ LE  ┆ R1  ┆     ┆ uen ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 7_r ┆ h   ┆     ┆ 7_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆ ios ┆ ra? ┆ ep. ┆     ┆     ┆     ┆ cin ┆     ┆ pau ┆     ┆     ┆     ┆ 392 ┆     ┆ RR3 ┆     ┆     ┆ vs  ┆ ff; ┆     ┆     ┆ pau ┆     ┆ vs  ┆     ┆ cin ┆     ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ 1%  ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pol ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ D8L ┆     ┆     ┆ amp ┆ ter ┆ 202 ┆     ┆     ┆     ┆ g:  ┆     ┆ sin ┆     ┆     ┆     ┆ 4;4 ┆     ┆ 47/ ┆     ┆     ┆ Pol ┆ fa6 ┆     ┆     ┆ sin ┆     ┆ Pol ┆     ┆ g:  ┆     ┆ 47/ ┆     ┆     ┆     ┆     ┆     ┆ R34 ┆ 213 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ii ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4Y  ┆     ┆     ┆ le/ ┆ m=S ┆ 6.1 ┆     ┆     ┆     ┆ GSM ┆     ┆ g   ┆     ┆     ┆     ┆ 851 ┆     ┆ 015 ┆     ┆     ┆ II  ┆ 958 ┆     ┆     ┆ g   ┆     ┆ II  ┆     ┆ GSM ┆     ┆ 015 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ch ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 170 ┆     ┆     ┆     ┆ 913 ┆     ┆ are ┆     ┆     ┆     ┆ 127 ┆     ┆ /SR ┆     ┆     ┆ ChI ┆ 5e6 ┆     ┆     ┆ are ┆     ┆ ChI ┆     ┆ 913 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 15/ ┆ 511 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ip- ┆ P-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 913 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N50 ┆ 987 ┆ 39  ┆     ┆     ┆     ┆ 702 ┆     ┆ los ┆     ┆     ┆     ┆ 624 ┆     ┆ R34 ┆     ┆     ┆ P-s ┆ 62e ┆     ┆     ┆ los ┆     ┆ P-s ┆     ┆ 702 ┆     ┆ R34 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆ eq, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 237 ┆ 607 ┆     ┆     ┆     ┆     ┆ 8:  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆ eq, ┆ 641 ┆     ┆     ┆ t   ┆     ┆ eq, ┆     ┆ 8:  ┆     ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆ 347 ┆ 11; ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ __n ┆ no  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 549 ┆ 9   ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆ dur ┆     ┆     ┆     ┆     ┆     ┆ 215 ┆     ┆     ┆ no  ┆ 7c0 ┆     ┆     ┆ dur ┆     ┆ no  ┆     ┆ Pol ┆     ┆ 215 ┆     ┆     ┆     ┆     ┆     ┆ 422 ┆ 895 ┆     ┆     ┆ chr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ o_h ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM9 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ II  ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ hea ┆ 41f ┆     ┆     ┆ ing ┆     ┆ hea ┆     ┆ II  ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 15/ ┆ 93; ┆     ┆     ┆ oma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eat ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 137 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆ R34 ┆     ┆     ┆ t   ┆ 52e ┆     ┆     ┆ rea ┆     ┆ t   ┆     ┆ ChI ┆     ┆ R34 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _sh ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 028 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆ P-s ┆     ┆ d-t ┆     ┆     ┆     ┆     ┆     ┆ 742 ┆     ┆     ┆ sho ┆ b73 ┆     ┆     ┆ d-t ┆     ┆ sho ┆     ┆ P-s ┆     ┆ 742 ┆     ┆     ┆     ┆     ┆     ┆ 347 ┆ 2;7 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ock ┆ ck, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆     ┆     ┆     ┆     ┆ eq, ┆     ┆ hro ┆     ┆     ┆     ┆     ┆     ┆ 215 ┆     ┆     ┆ ck, ┆ 7bc ┆     ┆     ┆ hro ┆     ┆ ck, ┆     ┆ eq, ┆     ┆ 215 ┆     ┆     ┆     ┆     ┆     ┆ 422 ┆ 776 ┆     ┆     ┆ iso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _r1 ┆ R1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆     ┆     ┆     ┆     ┆ hea ┆     ┆ ugh ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆ R1  ┆ ee  ┆     ┆     ┆ ugh ┆     ┆ R1  ┆     ┆ hea ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 15_ ┆ ;11 ┆     ┆     ┆ lat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

---

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# Heat-stress related ChIP-seq Data (Histone Modification)

&nbsp;

## 1. GSE89382 (ChIP-seq; H4K5K8K12K16ac) (ChIP-Atlas: True)

- [Transcriptional response to stress is pre-wired by promoter and enhancer architecture](https://doi.org/10.1038/s41467-017-00151-0)
- `Methods; Cell lines and heat shock treatment; ... For treatments, 2 × 107 cells per sample were concentrated in 10 ml culture media and placed in 37 °C incubator (NHS) or a 42 °C water bath (HS) for 30 min. In the water bath, the temperature of the cell suspension reached 42 °C within 4 min.`
- Input sample: SRX2313417

In [48]:
GSE89382_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE89382/GSE89382_PEP/GSE89382_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens")
).with_columns(
    pl.lit("https://doi.org/10.1038/s41467-017-00151-0").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("30 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE89382 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE89382.metadata.tsv",
    separator='\t'
)

GSE89382_combined = GSE89382_PEP.join(
    GSE89382,
    on=["experiment_accession"],
    how="left",
    coalesce=True
)

GSE89382_combined = GSE89382_combined[[s.name for s in GSE89382_combined if not (s.null_count() == GSE89382_combined.height)]]

# pl.Config.set_tbl_rows(3)
# display(GSE89382_combined)

In [49]:
defined_pairs_gse89382_chipseq = [
    ("SRX2313416", "SRX2313415")  # h4ac_k562_hs30 vs. h4ac_k562_nhs
]

paired_metada_df_gse89382_histone_modification = create_paired_metadata(
    combined_df=GSE89382_combined,
    defined_sample_pairs=defined_pairs_gse89382_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse89382_histone_modification is not None:
    paired_metada_df_gse89382_histone_modification.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE89382_chipseq_histone_modification_paired_metadata.tsv",
        separator='\t'
    )
    
    display(paired_metada_df_gse89382_histone_modification)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (1, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ tre ┆ ant ┆ ant ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ atm ┆ ibo ┆ ibo ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ent ┆ dy  ┆ dy_ ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ epi ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ str ┆ top ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n_r ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆     ┆ e   ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ igh ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ t   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ h4a ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ H4a ┆ GSM ┆ Pub ┆ Nov ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ Hea ┆ Ups ┆ Rec ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 30  ┆ SRR ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ ChI ┆ 201 ┆ 135 ┆ ILL ┆ ftp ┆ Gen ┆ H4a ┆ 2fb ┆ SRP ┆ 273 ┆ Gen ┆ GEN ┆ H4a ┆ Ill ┆ Ill ┆ ftp ┆ 551 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Aft ┆ GSM ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 231 ┆ 231 ┆ c_k ┆ P   ┆ o   ┆ RED ┆     ┆ 477 ┆ c   ┆ 236 ┆ lic ┆ 01  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ omi ┆ 167 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 236 ┆ :// ┆ 893 ┆     ┆ 231 ┆ 2   ┆ t   ┆ tat ┆ ogn ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 477 ┆ umi ┆ N05 ┆ o   ┆ 487 ┆ P   ┆ 7-0 ┆ 885 ┆ UMI ┆ .sr ┆ eri ┆ c   ┆ 68c ┆ 092 ┆ 155 ┆ ome ┆ ERA ┆ c   ┆ umi ┆ umi ┆ .sr ┆ 774 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 236 ┆ 236 ┆ er  ┆ 236 ┆ 2   ┆ _ta ┆ 7-0 ┆ o   ┆ 6   ┆ NA3 ┆ 477 ┆ 177 ┆ 7-0 ┆ 893 │
│ 341 ┆ 341 ┆ 562 ┆     ┆ sap ┆     ┆     ┆ 964 ┆ K56 ┆ 773 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ c   ┆ 91  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 773 ┆ ftp ┆ 82  ┆     ┆ 341 ┆     ┆ sho ┆ e   ┆ ize ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 964 ┆ na  ┆ 960 ┆ sap ┆ 897 ┆     ┆ 5-2 ┆ 434 ┆ NA  ┆ a.e ┆ c   ┆ K56 ┆ 3c1 ┆ 391 ┆ 74  ┆ -wi ┆ TED ┆ K56 ┆ na  ┆ na  ┆ a.e ┆ 594 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 773 ┆ 773 ┆ tre ┆ 773 ┆     ┆ x:t ┆ 5-2 ┆ sap ┆     ┆ 520 ┆ 964 ┆ 082 ┆ 5-2 ┆ 82  │
│ 6   ┆ 5   ┆ _hs ┆     ┆ ien ┆     ┆     ┆ 1   ┆ 2   ┆ 4   ┆ May ┆ 6   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆ DNA ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 4   ┆ .nc ┆     ┆     ┆ 6   ┆     ┆ cke ┆ 06- ┆ s   ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 1   ┆ HiS ┆ 685 ┆ ien ┆     ┆     ┆ 3   ┆ 0;1 ┆     ┆ bi. ┆     ┆ 2   ┆ 42d ┆     ┆ vs  ┆ de  ┆ _FI ┆ 2   ┆ HiS ┆ HiS ┆ bi. ┆ 8   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 4   ┆ 4_r ┆ tme ┆ 4   ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 38  ┆ 1   ┆ 6   ┆ 3   ┆     │
│     ┆     ┆ 30  ┆     ┆ s   ┆     ┆     ┆ vs  ┆ HS3 ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ d   ┆ 866 ┆ H4  ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ eq  ┆ vs  ┆ s   ┆     ┆     ┆     ┆ 369 ┆     ┆ ac. ┆     ┆ HS3 ┆ 54b ┆     ┆ 302 ┆ map ┆ LE; ┆ HS3 ┆ eq  ┆ eq  ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ nts ┆ vs  ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ SRR ┆ 0   ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ (HS ┆     ┆ ace ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ 250 ┆ SAM ┆     ┆     ┆     ┆     ┆ 099 ┆     ┆ uk/ ┆     ┆ 0   ┆ dd7 ┆     ┆ 311 ┆ s   ┆ GEN ┆ 0   ┆ 250 ┆ 250 ┆ uk/ ┆ 610 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ,   ┆ GSM ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ h4a ┆     ┆     ┆     ┆     ┆ 477 ┆ vs  ┆ 236 ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 236 ┆ .ni ┆     ┆     ┆ 231 ┆     ┆ 30) ┆     ┆ tyl ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 477 ┆ 0   ┆ N05 ┆     ┆     ┆     ┆     ┆ 831 ┆     ┆ vol ┆     ┆ vs  ┆ 9a1 ┆     ┆ 19  ┆ of  ┆ ERA ┆ vs  ┆ 0   ┆ 0   ┆ vol ┆ 668 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 236 ┆ GSM ┆ the ┆ 236 ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 477 ┆ 177 ┆     ┆     │
│     ┆     ┆ c_k ┆     ┆     ┆     ┆     ┆ 964 ┆ H4a ┆ 773 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 773 ┆ h.g ┆     ┆     ┆ 341 ┆     ┆ vs  ┆     ┆ ati ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ 964 ┆ seq ┆ 960 ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆ H4a ┆ ee5 ┆     ┆     ┆ his ┆ TED ┆ H4a ┆     ┆ seq ┆ 1/f ┆ 603 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 773 ┆ 236 ┆ cel ┆ 773 ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 964 ┆ 082 ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆ 0   ┆ c   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ ov/ ┆     ┆     ┆ 5   ┆     ┆ Non ┆     ┆ on  ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆ 0   ┆ uen ┆ 686 ┆     ┆     ┆     ┆     ┆ 149 ┆     ┆ ast ┆     ┆ c   ┆ 4d3 ┆     ┆     ┆ ton ┆ _FI ┆ c   ┆     ┆ uen ┆ ast ┆ 8   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 3   ┆ 773 ┆ ls  ┆ 3   ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 0   ┆ 4   ┆     ┆     │
│     ┆     ┆ _nh ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ -tr ┆     ┆ at  ┆     ┆ v/b ┆ v/s ┆ 467 ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ 668 ┆     ┆ q/S ┆     ┆ K56 ┆ a7c ┆     ┆     ┆ e   ┆ LE  ┆ K56 ┆     ┆ cin ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 3_r ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ eat ┆     ┆ lys ┆     ┆ ios ┆ ra? ┆ -01 ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ 717 ┆     ┆ RR4 ┆     ┆ 2   ┆ 0e; ┆     ┆     ┆ H4  ┆     ┆ 2   ┆     ┆ g:  ┆ RR4 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ ine ┆     ┆ amp ┆ ter ┆ 7-0 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ 1;1 ┆     ┆ 77/ ┆     ┆ NHS ┆ f8f ┆     ┆     ┆ ace ┆     ┆ NHS ┆     ┆ GSM ┆ 77/ ┆     ┆     ┆     ┆     ┆     ┆ R47 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ (NH ┆     ┆ s   ┆     ┆ le/ ┆ m=S ┆ 015 ┆     ┆     ┆     ┆ 236 ┆     ┆     ┆     ┆     ┆     ┆ 499 ┆     ┆ 001 ┆     ┆     ┆ 1a9 ┆     ┆     ┆ tyl ┆     ┆     ┆     ┆ 236 ┆ 001 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ ss- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ S)  ┆     ┆ 5,  ┆     ┆ SAM ┆ RX2 ┆ 1-0 ┆     ┆     ┆     ┆ 773 ┆     ┆     ┆     ┆     ┆     ┆ 112 ┆     ┆ /SR ┆     ┆     ┆ 342 ┆     ┆     ┆ ati ┆     ┆     ┆     ┆ 773 ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 01/ ┆ 511 ┆     ┆     ┆ lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 236 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8,  ┆     ┆ N05 ┆ 313 ┆     ┆     ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆ 818 ┆     ┆ R47 ┆     ┆     ┆ f19 ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ 4:  ┆ R47 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ked ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12  ┆     ┆ 960 ┆ 416 ┆     ┆     ┆     ┆     ┆ H4a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 796 ┆     ┆     ┆ ec4 ┆     ┆     ┆ in  ┆     ┆     ┆     ┆ H4a ┆ 796 ┆     ┆     ┆     ┆     ┆     ┆ 477 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆ 685 ┆ vs  ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 41/ ┆     ┆     ┆ 2d3 ┆     ┆     ┆ hum ┆     ┆     ┆     ┆ c   ┆ 41/ ┆     ┆     ┆     ┆     ┆     ┆ 964 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16. ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ e1a ┆     ┆     ┆ an  ┆     ┆     ┆     ┆ K56 ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 1/S ┆ 93; ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 367 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 477 ┆     ┆     ┆ b6c ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆ 2   ┆ 477 ┆     ┆     ┆     ┆     ┆     ┆ RR4 ┆ 774 ┆     ┆     ┆ fro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 734 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆     ┆ HS3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 964 ┆     ┆     ┆ c14 ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ HS3 ┆ 964 ┆     ┆     ┆     ┆     ┆     ┆ 779 ┆ 2;7 ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_1 ┆     ┆     ┆ 9e5 ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ 0   ┆ 1_1 ┆     ┆     ┆     ┆     ┆     ┆ 641 ┆ 776 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ a0  ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ Hom ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆ ;11 ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 2. GSE105028 (ChIP-seq; H3K27ac/H3K27me3/H3K4me1/H3K4me3) (ChIP-Atlas: True)

- [Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress](https://doi.org/10.1016/j.molcel.2018.07.012)
- H3K27ac のデータは、diff analysis が可能

In [50]:
GSE105028_PEP_histone_modification = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE105028/GSE105028_PEP/GSE105028_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "ChIP-Seq") &
    (pl.col("sample_organism_ch1") == "Homo sapiens") &
    (
        (pl.col("sample_name").str.contains("h3k27ac")) |
        (pl.col("sample_name").str.contains("h3k27me3")) |
        (pl.col("sample_name").str.contains("h3k4me1")) |
        (pl.col("sample_name").str.contains("h3k4me3")) 
    )
).with_columns(
    pl.lit("https://doi.org/10.1016/j.molcel.2018.07.012").alias("reference_doi"),
    pl.lit("42 C").alias("stress treatment temperature"),
    pl.lit("60 min.").alias("stress treatment time")
).rename(
    {
        "srr": "run_accession",
        "srx": "experiment_accession"
    }
)

GSE105028 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE105028.metadata.tsv",
    separator='\t'
)

GSE105028_combined_histone_modification = GSE105028_PEP_histone_modification.join(
    GSE105028,
    on=["run_accession", "experiment_accession"],
    how="left",
    coalesce=True
)

GSE105028_combined_histone_modification = GSE105028_combined_histone_modification[[s.name for s in GSE105028_combined_histone_modification if not (s.null_count() == GSE105028_combined_histone_modification.height)]]

GSE105028_combined_histone_modification.write_csv(
    "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE105028_chipseq_histone_modification_paired_metadata.tsv",
    separator='\t'
)

display(GSE105028_combined_histone_modification)

shape: (12, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ exp ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ eri ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ men ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ t_a ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ i64 ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ cce ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆ --- ┆ ssi ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ i64 ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ i64 ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆ on  ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ h3k ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ H3K ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ ChI ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ H9  ┆ und ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Arc ┆ SRA ┆ ChI ┆ 201 ┆ 695 ┆ ILL ┆ ftp ┆ Gen ┆ H3K ┆ 418 ┆ SRP ┆ 219 ┆ Arc ┆ GEN ┆ H3K ┆ Ill ┆ Ill ┆ nul ┆ ftp ┆ 219 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ H9  ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 27a ┆ P   ┆ o   ┆ RED ┆     ┆ 617 ┆ 328 ┆ 27a ┆ 281 ┆ lic ┆ 16  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ P-S ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 281 ┆ E   ┆ 105 ┆     ┆ 328 ┆ hum ┆ er  ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N07 ┆ hit ┆ 619 ┆ P   ┆ 8-0 ┆ 342 ┆ UMI ┆ .sr ┆ eri ┆ 27a ┆ 694 ┆ 120 ┆ 310 ┆ hit ┆ ERA ┆ 27a ┆ umi ┆ umi ┆ l   ┆ .sr ┆ 310 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 281 ┆ 281 ┆ Hi- ┆ 281 ┆     ┆ hum ┆ _ta ┆ 8-0 ┆ o   ┆ 6   ┆ NA4 ┆ 617 ┆ 259 ┆ 8-0 ┆ 105 │
│ c_c ┆     ┆ sap ┆     ┆     ┆ 796 ┆ 858 ┆ c   ┆ 664 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ eq  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 664 ┆     ┆ 028 ┆     ┆ 858 ┆ an  ┆ nor ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 790 ┆ ect ┆ 794 ┆     ┆ 8-0 ┆ 487 ┆ NA  ┆ a.e ┆ c   ┆ c   ┆ eba ┆ 027 ┆ 06  ┆ ect ┆ TED ┆ c   ┆ na  ┆ na  ┆     ┆ a.e ┆ 060 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 664 ┆ 664 ┆ C,  ┆ 664 ┆     ┆ an  ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 144 ┆ 796 ┆ 812 ┆ 8-0 ┆ 028 │
│ hip ┆     ┆ ien ┆     ┆     ┆ 7   ┆ 9   ┆ ChI ┆ 8   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ und ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 9   ┆ Emb ┆ mal ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 056 ┆ ura ┆     ┆     ┆ 4   ┆ ;69 ┆     ┆ bi. ┆     ┆ ChI ┆ ab3 ┆     ┆     ┆ ura ┆ _FI ┆ ChI ┆ HiS ┆ HiS ┆     ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 8   ┆ 8_r ┆ cel ┆ 8   ┆     ┆ Emb ┆ err ┆ 4   ┆ ien ┆     ┆ 42  ┆ 7   ┆ 5   ┆ 4   ┆     │
│ -se ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ er  ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ryo ┆ con ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆     ┆ l   ┆     ┆     ┆     ┆ 180 ┆     ┆ ac. ┆     ┆ P-S ┆ 669 ┆     ┆     ┆ l   ┆ LE; ┆ P-S ┆ eq  ┆ eq  ┆     ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆     ┆ 1   ┆ ls  ┆     ┆     ┆ ryo ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     │
│ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nic ┆ dit ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆     ┆ pro ┆     ┆     ┆     ┆ 707 ┆     ┆ uk/ ┆     ┆ eq  ┆ 162 ┆     ┆     ┆ pro ┆ GEN ┆ eq  ┆ 200 ┆ 200 ┆     ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆     ┆     ┆ wer ┆     ┆     ┆ nic ┆ ria ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ste ┆ ion ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 0   ┆     ┆ tei ┆     ┆     ┆     ┆ 7   ┆     ┆ vol ┆     ┆     ┆ 7d0 ┆     ┆     ┆ tei ┆ ERA ┆     ┆ 0   ┆ 0   ┆     ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆     ┆     ┆ e   ┆     ┆     ┆ Ste ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆ s   ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ seq ┆     ┆ ns  ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆ 842 ┆     ┆     ┆ ns  ┆ TED ┆     ┆     ┆ seq ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆     ┆     ┆ cro ┆     ┆     ┆ m   ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆ uen ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ ba3 ┆     ┆     ┆ and ┆ _FI ┆     ┆     ┆ uen ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆     ┆     ┆ ssl ┆     ┆     ┆ Cel ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆ cin ┆     ┆ plu ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆ 0c4 ┆     ┆     ┆ plu ┆ LE  ┆     ┆     ┆ cin ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆     ┆ ink ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s,  ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆ g:  ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆     ┆     ┆ 4d; ┆     ┆     ┆ rip ┆     ┆     ┆     ┆ g:  ┆     ┆ RR6 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆     ┆ ed  ┆     ┆     ┆ Lin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ H3K ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆ GSM ┆     ┆ ote ┆     ┆     ┆     ┆     ┆     ┆ 17/ ┆     ┆     ┆ 123 ┆     ┆     ┆ ote ┆     ┆     ┆     ┆ GSM ┆     ┆ 17/ ┆     ┆     ┆     ┆     ┆     ┆ R61 ┆ 213 ┆     ┆     ┆ wit ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 27a ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆ 281 ┆     ┆ ncy ┆     ┆     ┆     ┆     ┆     ┆ 007 ┆     ┆     ┆ 063 ┆     ┆     ┆ ncy ┆     ┆     ┆     ┆ 281 ┆     ┆ 007 ┆     ┆     ┆     ┆     ┆     ┆ 7/0 ┆ ;33 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c_N ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆ 664 ┆     ┆ fac ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 4a5 ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 664 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 07/ ┆ 511 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T.b ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 288 ┆ 12  ┆     ┆     ┆ 8:  ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆ R61 ┆     ┆     ┆ 5df ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ 8:  ┆     ┆ R61 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w   ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 790 ┆ 589 ┆     ┆     ┆     ┆ H3K ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 779 ┆     ┆     ┆ a66 ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ H3K ┆     ┆ 779 ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 056 ┆     ┆     ┆     ┆     ┆ 27a ┆     ┆ coo ┆     ┆     ┆     ┆     ┆     ┆ 67/ ┆     ┆     ┆ 604 ┆     ┆     ┆ coo ┆     ┆     ┆     ┆ 27a ┆     ┆ 67/ ┆     ┆     ┆     ┆     ┆     ┆ 796 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ e2d ┆     ┆     ┆ per ┆     ┆     ┆     ┆ c   ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 7/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ 617 ┆     ┆     ┆ 349 ┆     ┆     ┆ ate ┆     ┆     ┆     ┆ ChI ┆     ┆ 617 ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆ 796 ┆     ┆     ┆ d9e ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ P-S ┆     ┆ 796 ┆     ┆     ┆     ┆     ┆     ┆ 177 ┆ 2;7 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ orc ┆     ┆     ┆     ┆     ┆     ┆ 7_1 ┆     ┆     ┆ 0f0 ┆     ┆     ┆ orc ┆     ┆     ┆     ┆ eq  ┆     ┆ 7_1 ┆     ┆     ┆     ┆     ┆     ┆ 967 ┆ 776 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ hes ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ 15  ┆     ┆     ┆ hes ┆     ┆     ┆     ┆ Hom ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆ ;11 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆ o   ┆     ┆ stq ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 757 ┆     ┆     ┆ roo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [51]:
defined_pairs_gse105028_chipseq_histone_modification = [
    ("SRX3316076", "SRX3316075"), # hs_brg1-ko_h3k27ac vs. brg1-ko_h3k27ac
    ("SRX3288598", "SRX3288597"), # hs_h3k4me3_chip-seq vs. h3k4me3_chip-seq
    ("SRX3288596", "SRX3288595"), # hs_h3k4me1_chip-seq vs. h3k4me1_chip-seq
    ("SRX3288594", "SRX3288593"), # hs_h3k27me3_chip-seq vs. h3k27me3_chip-seq

    # H3K27ac
    ("SRX3288592", "SRX3288591"), # hs_h3k27ac_chip-seq_rep vs. h3k27ac_chip-seq_rep
    ("SRX3288590", "SRX3288589"), # hs_h3k27ac_chip-seq vs. h3k27ac_chip-seq
]

paired_metada_df_gse105028_histone_modification = create_paired_metadata(
    combined_df=GSE105028_combined_histone_modification,
    defined_sample_pairs=defined_pairs_gse105028_chipseq_histone_modification,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse105028_histone_modification is not None:
    paired_metada_df_gse105028_histone_modification.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE105028_chipseq_histone_modification_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metada_df_gse105028_histone_modification)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 90)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ run ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ big ┆ cel ┆ con ┆ gen ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ _ac ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ _ke ┆ l_l ┆ dit ┆ ome ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ ces ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ y   ┆ ine ┆ ion ┆ _bu ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆ sio ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ --- ┆ ild ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆ n   ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ str ┆ --- ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ hs_ ┆ ChI ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ HS  ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ H9  ┆ Hom ┆ 960 ┆ gen ┆ ChI ┆ GPL ┆ XIA ┆ xia ┆ +86 ┆ XIA ┆ No. ┆ XIA ┆ FUJ ┆ 361 ┆ Chi ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ nul ┆ nul ┆ hg3 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ Ill ┆ SAM ┆ Arc ┆ SRA ┆ ChI ┆ 201 ┆ 143 ┆ ILL ┆ ftp ┆ Gen ┆ HS  ┆ 79f ┆ SRP ┆ 437 ┆ Arc ┆ GEN ┆ HS  ┆ Ill ┆ Ill ┆ H9  ┆ ftp ┆ 437 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ nul ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ GSE │
│ 331 ┆ 331 ┆ brg ┆ P   ┆ o   ┆ RED ┆     ┆ 620 ┆ BRG ┆ 282 ┆ lic ┆ 24  ┆ 15  ┆     ┆     ┆ hES ┆ o   ┆ 6   ┆ omi ┆ P-S ┆ 111 ┆ OWE ┆ owe ┆ -18 ┆ MEN ┆ 422 ┆ MEN ┆ IAN ┆ 102 ┆ na  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 282 ┆ :// ┆ 105 ┆     ┆ 331 ┆ l   ┆ l   ┆ 8   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ umi ┆ N07 ┆ hit ┆ 619 ┆ P   ┆ 8-0 ┆ 548 ┆ UMI ┆ .sr ┆ eri ┆ BRG ┆ 32f ┆ 120 ┆ 052 ┆ hit ┆ ERA ┆ BRG ┆ umi ┆ umi ┆ hum ┆ .sr ┆ 052 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 282 ┆ 282 ┆ Hi- ┆ 282 ┆     ┆ l   ┆ _ta ┆ 8-0 ┆ o   ┆ 6   ┆ NA4 ┆ 620 ┆ 262 ┆ 8-0 ┆ 105 │
│ 607 ┆ 607 ┆ 1-k ┆     ┆ sap ┆     ┆     ┆ 678 ┆ 1-K ┆ 901 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ Cs  ┆ sap ┆     ┆ c   ┆ eq  ┆ 54  ┆ N,, ┆ nly ┆ 701 ┆ UNI ┆ 1,  ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 901 ┆ ftp ┆ 028 ┆     ┆ 607 ┆     ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ na  ┆ 828 ┆ ect ┆ 794 ┆     ┆ 8-0 ┆ 730 ┆ NA  ┆ a.e ┆ c   ┆ 1-K ┆ 455 ┆ 027 ┆ 97  ┆ ect ┆ TED ┆ 1-K ┆ na  ┆ na  ┆ an  ┆ a.e ┆ 970 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 901 ┆ 901 ┆ C,  ┆ 901 ┆     ┆     ┆ x:t ┆ 8-0 ┆ sap ┆     ┆ 144 ┆ 678 ┆ 166 ┆ 8-0 ┆ 028 │
│ 6   ┆ 5   ┆ o_h ┆     ┆ ien ┆     ┆     ┆ 2   ┆ O_H ┆ 5   ┆ Aug ┆ 7   ┆ 9   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ und ┆     ┆ LYU ┆ u@g ┆ 064 ┆ VER ┆ Xia ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆ 5   ┆ .nc ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ HiS ┆ 425 ┆ ura ┆     ┆     ┆ 4   ┆ 9;1 ┆     ┆ bi. ┆     ┆ O_H ┆ 6bc ┆     ┆ vs  ┆ ura ┆ _FI ┆ O_H ┆ HiS ┆ HiS ┆ Emb ┆ bi. ┆ 0   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ cel ┆ 5   ┆     ┆     ┆ err ┆ 4   ┆ ien ┆     ┆ 42  ┆ 2   ┆ 2   ┆ 4   ┆     │
│     ┆     ┆ 3k2 ┆     ┆ s   ┆     ┆     ┆ vs  ┆ 3K2 ┆ vs  ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ er  ┆     ┆     ┆ mai ┆ 502 ┆ SIT ┆ ng' ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ eq  ┆ vs  ┆ l   ┆     ┆     ┆     ┆ 430 ┆     ┆ ac. ┆     ┆ 3K2 ┆ 64f ┆     ┆ 354 ┆ l   ┆ LE; ┆ 3K2 ┆ eq  ┆ eq  ┆ ryo ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ ls  ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ 7ac ┆     ┆     ┆     ┆     ┆ SRR ┆ 7ac ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆ l.c ┆     ┆ Y   ┆ an  ┆     ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ 200 ┆ SAM ┆ pro ┆     ┆     ┆     ┆ 950 ┆     ┆ uk/ ┆     ┆ 7ac ┆ f2f ┆     ┆ 876 ┆ pro ┆ GEN ┆ 7ac ┆ 200 ┆ 200 ┆ nic ┆ uk/ ┆ 354 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ wer ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 620 ┆ vs  ┆ 282 ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ om  ┆     ┆     ┆ Sou ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 282 ┆ .ni ┆     ┆     ┆ 331 ┆     ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 0   ┆ N07 ┆ tei ┆     ┆     ┆     ┆ 991 ┆     ┆ vol ┆     ┆ vs  ┆ 842 ┆     ┆ 11  ┆ tei ┆ ERA ┆ vs  ┆ 0   ┆ 0   ┆ Ste ┆ vol ┆ 876 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 282 ┆ GSM ┆ e   ┆ 282 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 620 ┆ 262 ┆     ┆     │
│     ┆     ┆ brg ┆     ┆     ┆     ┆     ┆ 678 ┆ BRG ┆ 901 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 901 ┆ h.g ┆     ┆     ┆ 607 ┆     ┆     ┆     ┆ nih ┆ nih ┆ 16/ ┆     ┆     ┆ seq ┆ 828 ┆ ns  ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆ BRG ┆ f58 ┆     ┆     ┆ ns  ┆ TED ┆ BRG ┆     ┆ seq ┆ m   ┆ 1/f ┆ 110 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 901 ┆ 282 ┆ cro ┆ 901 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 678 ┆ 166 ┆     ┆     │
│     ┆     ┆ 1-k ┆     ┆     ┆     ┆     ┆ 1   ┆ 1-K ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ Roa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ .go ┆ .go ┆ j.m ┆     ┆     ┆ uen ┆ 426 ┆ and ┆     ┆     ┆     ┆ 116 ┆     ┆ ast ┆     ┆ 1-K ┆ e90 ┆     ┆     ┆ and ┆ _FI ┆ 1-K ┆     ┆ uen ┆ Cel ┆ ast ┆ 0   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 4   ┆ 901 ┆ ssl ┆ 4   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆     ┆     │
│     ┆     ┆ o_h ┆     ┆     ┆     ┆     ┆     ┆ O_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆ d,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ olc ┆     ┆     ┆ cin ┆     ┆ plu ┆     ┆     ┆     ┆ 591 ┆     ┆ q/S ┆     ┆ O_H ┆ b2c ┆     ┆     ┆ plu ┆ LE  ┆ O_H ┆     ┆ cin ┆ l   ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 4_r ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3k2 ┆     ┆     ┆     ┆     ┆     ┆ 3K2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆     ┆     ┆     ┆     ┆ Xia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ el. ┆     ┆     ┆ g:  ┆     ┆ rip ┆     ┆     ┆     ┆ 527 ┆     ┆ RR6 ┆     ┆ 3K2 ┆ e4; ┆     ┆     ┆ rip ┆     ┆ 3K2 ┆     ┆ g:  ┆ Lin ┆ RR6 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 7ac ┆     ┆     ┆     ┆     ┆     ┆ 7ac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆     ┆     ┆     ┆     ┆ ng' ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 201 ┆     ┆     ┆ GSM ┆     ┆ ote ┆     ┆     ┆     ┆ 0;1 ┆     ┆ 20/ ┆     ┆ 7ac ┆ d40 ┆     ┆     ┆ ote ┆     ┆ 7ac ┆     ┆ GSM ┆ e   ┆ 20/ ┆     ┆     ┆     ┆     ┆     ┆ R62 ┆ 213 ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 8.0 ┆     ┆     ┆ 282 ┆     ┆ ncy ┆     ┆     ┆     ┆ 149 ┆     ┆ 002 ┆     ┆     ┆ 1a8 ┆     ┆     ┆ ncy ┆     ┆     ┆     ┆ 282 ┆     ┆ 002 ┆     ┆     ┆     ┆     ┆     ┆ 0/0 ┆ ;33 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ Dis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX3 ┆ 7.0 ┆     ┆     ┆ 901 ┆     ┆ fac ┆     ┆     ┆     ┆ 296 ┆     ┆ /SR ┆     ┆     ┆ 8e9 ┆     ┆     ┆ fac ┆     ┆     ┆     ┆ 901 ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 02/ ┆ 511 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 282 ┆     ┆     ┆     ┆     ┆     ┆     ┆ N07 ┆ 316 ┆ 12  ┆     ┆     ┆ 5:  ┆     ┆ tor ┆     ┆     ┆     ┆ 041 ┆     ┆ R62 ┆     ┆     ┆ 86e ┆     ┆     ┆ tor ┆     ┆     ┆     ┆ 5:  ┆     ┆ R62 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-S ┆     ┆     ┆     ┆     ┆     ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆     ┆ 828 ┆ 076 ┆     ┆     ┆     ┆ HS  ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 067 ┆     ┆     ┆ 1da ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ HS  ┆     ┆ 067 ┆     ┆     ┆     ┆     ┆     ┆ 620 ┆ 11; ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆ 425 ┆ vs  ┆     ┆     ┆     ┆ BRG ┆     ┆ coo ┆     ┆     ┆     ┆     ┆     ┆ 82/ ┆     ┆     ┆ 8b8 ┆     ┆     ┆ coo ┆     ┆     ┆     ┆ BRG ┆     ┆ 82/ ┆     ┆     ┆     ┆     ┆     ┆ 678 ┆ 895 ┆     ┆     ┆ deh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ htt ┆     ┆     ┆     ┆ 1-K ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ 40e ┆     ┆     ┆ per ┆     ┆     ┆     ┆ 1-K ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 2/S ┆ 93; ┆     ┆     ┆ yde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 829 ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ ps: ┆     ┆     ┆     ┆ O_H ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆ 620 ┆     ┆     ┆ fb2 ┆     ┆     ┆ ate ┆     ┆     ┆     ┆ O_H ┆     ┆ 620 ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 015 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ //w ┆     ┆     ┆     ┆ 3K2 ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆ 678 ┆     ┆     ┆ e94 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ 3K2 ┆     ┆ 678 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 2;7 ┆     ┆     ┆ 10  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ ww. ┆     ┆     ┆     ┆ 7ac ┆     ┆ orc ┆     ┆     ┆     ┆     ┆     ┆ 2_1 ┆     ┆     ┆ c37 ┆     ┆     ┆ orc ┆     ┆     ┆     ┆ 7ac ┆     ┆ 2_1 ┆     ┆     ┆     ┆     ┆     ┆ 782 ┆ 776 ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ncb ┆     ┆     ┆     ┆ Hom ┆     ┆ hes ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆     ┆     ┆ f7  ┆     ┆     ┆ hes ┆     ┆     ┆     ┆ Hom ┆     ┆ .fa ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆ ;11 ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 3. GSE209667 (ChIP-seq; H3K4me3)

- ✅ ChIP-Atlas: Diff Analysis

&nbsp;

- [Transcriptional responses of cancer cells to heat shock-inducing stimuli involve amplification of robust HSF1 binding](https://doi.org/10.1038/s41467-023-43157-7)
- Super series: [GSE209687](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE209687)
- 下記のような記述があることから、42℃ 60 min であると考えられる
- 既に上記で、データフレームを定義済み
- `Results; HSF1 binding is a temperature-independent hallmark of HSR; We began by examining MCF7 breast adenocarcinoma cells during temperature-induced Heat Shock Response (HSR) (Fig. 1, Supplementary Data 1, Supplementary Fig. 1a). A 60-min incubation at 42 °C induced a control HSP gene seen as spreading of the Pol II and nascent RNA signal into the gene body (Fig. 1a).`

In [52]:
defined_pairs_gse209667_chipseq_histone_modification = [
    ("SRX16646109", "SRX16646108"), # mcf7_hs_h3k4me3_rep_1 vs. mcf7_nhs_h3k4me3_rep_1
    ("SRX16646092", "SRX16646110"), # mcf7_hs_h3k4me3_rep_2 vs. mcf7_nhs_h3k4me3_rep_2
]

paired_metada_df_gse209667_histone_modification = create_paired_metadata(
    combined_df=GSE209667_combined,
    defined_sample_pairs=defined_pairs_gse209667_chipseq_histone_modification,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse209667_histone_modification is not None:
    paired_metada_df_gse209667_histone_modification.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE209667_chipseq_histone_modification_paired_metadata.tsv",
        separator='\t'
    )

    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse209667_histone_modification)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 89)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ cel ┆ cel ┆ chi ┆ tre ┆ ass ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ l_l ┆ l_t ┆ p_a ┆ atm ┆ emb ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ ine ┆ ype ┆ nti ┆ ent ┆ ly  ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ --- ┆ --- ┆ bod ┆ --- ┆ --- ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ str ┆ str ┆ y   ┆ str ┆ str ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ces ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ sin ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ g   ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ mcf ┆ MCF ┆ GSM ┆ Pub ┆ Jul ┆ Oct ┆ SRA ┆ 1   ┆ MCF ┆ Hom ┆ 960 ┆ gen ┆ Raw ┆ GPL ┆ Ser ┆ ser ┆ Nec ┆ Bio ┆ Uni ┆ Gra ┆ Nor ┆ 582 ┆ USA ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ MCF ┆ mam ┆ H3K ┆ Hea ┆ hg1 ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ Tra ┆ SRA ┆ ChI ┆ 202 ┆ 280 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ MCF ┆ 674 ┆ SRP ┆ 892 ┆ Tra ┆ GEN ┆ MCF ┆ Ill ┆ Ill ┆ mam ┆ ftp ┆ 133 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ App ┆ mis ┆ GSM ┆ MCF ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 166 ┆ 166 ┆ 7_h ┆ 7   ┆ 638 ┆ lic ┆ 25  ┆ 30  ┆     ┆     ┆ 7   ┆ o   ┆ 6   ┆ omi ┆ fil ┆ 155 ┆ gei ┆ gei ┆ hae ┆ med ┆ ver ┆ nd  ┆ th  ┆ 02  ┆     ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 638 ┆ :// ┆ 209 ┆     ┆ 7   ┆ mar ┆ 4me ┆ t   ┆ 9   ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 206 ┆ umi ┆ N29 ┆ nsc ┆ 146 ┆ P   ┆ 3-1 ┆ 148 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ 7   ┆ 281 ┆ 387 ┆ 944 ┆ nsc ┆ ERA ┆ 7   ┆ umi ┆ umi ┆ mar ┆ .sr ┆ 116 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 638 ┆ 638 ┆ rox ┆ sin ┆ 638 ┆ 7   ┆ 638 ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA8 ┆ 206 ┆ 142 ┆ 3-1 ┆ 209 │
│ 461 ┆ 461 ┆ s_h ┆ HS  ┆ 309 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ es  ┆ 20  ┆ ,,N ┆ .ne ┆ v   ┆ ica ┆ sit ┆ For ┆ Dak ┆     ┆     ┆ na  ┆     ┆ c   ┆ eq  ┆ 309 ┆ ftp ┆ 667 ┆     ┆     ┆ y   ┆ 3   ┆ sho ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 223 ┆ na  ┆ 938 ┆ rip ┆ 198 ┆     ┆ 1-0 ┆ 615 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ HS  ┆ 245 ┆ 953 ┆ 2   ┆ rip ┆ TED ┆ HS  ┆ na  ┆ na  ┆ y   ┆ a.e ┆ 300 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 309 ┆ 309 ┆ ima ┆ g   ┆ 309 ┆     ┆ 309 ┆ x:t ┆ 1-0 ┆ sap ┆     ┆ 620 ┆ 223 ┆ 804 ┆ 1-0 ┆ 667 │
│ 09  ┆ 08  ┆ 3k4 ┆ H3K ┆ 5   ┆ Oct ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆ wer ┆     ┆ ech ┆ cha ┆ Lab ┆ l   ┆ y   ┆ ks  ┆ ota ┆     ┆     ┆ MiS ┆     ┆     ┆     ┆ 5   ┆ .nc ┆ ,   ┆     ┆     ┆ gla ┆ (Ab ┆ ck  ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 53  ┆ MiS ┆ 370 ┆ tio ┆ 4   ┆     ┆ 1   ┆ ;28 ┆     ┆ bi. ┆     ┆     ┆ H3K ┆ 835 ┆     ┆ vs  ┆ tio ┆ _FI ┆ H3K ┆ MiS ┆ MiS ┆ gla ┆ bi. ┆ 8   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 5   ┆ 5_r ┆ tel ┆     ┆ 5_r ┆     ┆ 5   ┆ err ┆ 1   ┆ ien ┆     ┆ 76  ┆ 53  ┆ 68  ┆ 1   ┆     │
│     ┆     ┆ me3 ┆ 4me ┆ vs  ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ e   ┆     ┆ aev ┆ ev@ ┆     ┆ Sci ┆ of  ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆ vs  ┆ bi. ┆ GSE ┆     ┆     ┆ nd, ┆ cam ┆ vs  ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ eq  ┆ vs  ┆ nal ┆     ┆     ┆     ┆ 032 ┆     ┆ ac. ┆     ┆     ┆ 4me ┆ b9e ┆     ┆ 113 ┆ nal ┆ LE; ┆ 4me ┆ eq  ┆ eq  ┆ nd, ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ y   ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ _re ┆ 3   ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ada ┆     ┆     ┆ und ┆     ┆ enc ┆ Nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ 209 ┆     ┆     ┆ ade ┆ #ab ┆ Unt ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ seq ┆ SAM ┆ res ┆     ┆     ┆     ┆ 569 ┆     ┆ uk/ ┆     ┆     ┆ 3   ┆ 481 ┆     ┆ 888 ┆ res ┆ GEN ┆ 3   ┆     ┆ seq ┆ ade ┆ uk/ ┆ 169 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ 2x1 ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ p_1 ┆ rep ┆ 638 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pte ┆     ┆     ┆ .ed ┆     ┆ es  ┆ th  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆ .ni ┆ 687 ┆     ┆     ┆ noc ┆ 858 ┆ rea ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 206 ┆ uen ┆ N29 ┆ pon ┆     ┆     ┆     ┆ 3   ┆     ┆ vol ┆     ┆     ┆ rep ┆ 2f3 ┆     ┆ 63  ┆ pon ┆ ERA ┆ rep ┆     ┆ uen ┆ noc ┆ vol ┆ 779 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 638 ┆ GSM ┆ 07  ┆     ┆ GSM ┆     ┆ 638 ┆ l;e ┆     ┆     ┆     ┆     ┆ 206 ┆ 142 ┆     ┆     │
│     ┆     ┆ vs  ┆ 1   ┆ 309 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r-t ┆     ┆     ┆ u   ┆     ┆     ┆ Dak ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 309 ┆ h.g ┆     ┆     ┆     ┆ arc ┆ 0)  ┆ ted ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ 223 ┆ cin ┆ 938 ┆ ses ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ 1   ┆ e24 ┆     ┆     ┆ ses ┆ TED ┆ 1   ┆     ┆ cin ┆ arc ┆ 1/f ┆ 122 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 309 ┆ 638 ┆ cel ┆     ┆ 638 ┆     ┆ 309 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 223 ┆ 804 ┆     ┆     │
│     ┆     ┆ mcf ┆ vs  ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rim ┆     ┆     ┆     ┆     ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆     ┆     ┆     ┆ ino ┆     ┆     ┆     ┆ .go ┆ .go ┆ s41 ┆     ┆     ┆ 54  ┆ g:  ┆ 371 ┆ of  ┆     ┆     ┆     ┆ 357 ┆     ┆ ast ┆     ┆     ┆ vs  ┆ 9c2 ┆     ┆     ┆ of  ┆ _FI ┆ vs  ┆     ┆ g:  ┆ ino ┆ ast ┆ 2   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 4   ┆ 309 ┆ ls  ┆     ┆ 309 ┆     ┆ 4   ┆ tax ┆     ┆     ┆     ┆     ┆ 54  ┆ 67  ┆     ┆     │
│     ┆     ┆ 7_n ┆ MCF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 467 ┆     ┆     ┆     ┆ GSM ┆     ┆ can ┆     ┆     ┆     ┆ 657 ┆     ┆ q/S ┆     ┆     ┆ MCF ┆ 668 ┆     ┆     ┆ can ┆ LE  ┆ MCF ┆     ┆ GSM ┆ ma  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 4_r ┆ wer ┆     ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ hs_ ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ 638 ┆     ┆ cer ┆     ┆     ┆     ┆ 509 ┆     ┆ RR2 ┆     ┆     ┆ 7   ┆ b3; ┆     ┆     ┆ cer ┆     ┆ 7   ┆     ┆ 638 ┆     ┆ RR2 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ e   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ h3k ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 3-4 ┆     ┆     ┆     ┆ 309 ┆     ┆ cel ┆     ┆     ┆     ┆ ;35 ┆     ┆ 06/ ┆     ┆     ┆ NHS ┆ 298 ┆     ┆     ┆ cel ┆     ┆ NHS ┆     ┆ 309 ┆     ┆ 06/ ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆ 213 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 4me ┆ H3K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 315 ┆     ┆     ┆     ┆ 5:  ┆     ┆ ls  ┆     ┆     ┆     ┆ 781 ┆     ┆ 053 ┆     ┆     ┆ H3K ┆ ded ┆     ┆     ┆ ls  ┆     ┆ H3K ┆     ┆ 5:  ┆     ┆ 053 ┆     ┆     ┆     ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 3_r ┆ 4me ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mmo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX1 ┆ 7-7 ┆     ┆     ┆     ┆ MCF ┆     ┆ to  ┆     ┆     ┆     ┆ 572 ┆     ┆ /SR ┆     ┆     ┆ 4me ┆ 0d0 ┆     ┆     ┆ to  ┆     ┆ 4me ┆     ┆ MCF ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 53/ ┆ 511 ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep_ ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N29 ┆ 664 ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ hea ┆     ┆     ┆     ┆ 0   ┆     ┆ R20 ┆     ┆     ┆ 3   ┆ 33d ┆     ┆     ┆ hea ┆     ┆ 3   ┆     ┆ 7   ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 938 ┆ 610 ┆     ┆     ┆     ┆     ┆ HS  ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆ rep ┆ 252 ┆     ┆     ┆ t   ┆     ┆ rep ┆     ┆ HS  ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 370 ┆ 9   ┆     ┆     ┆     ┆     ┆ H3K ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ 353 ┆     ┆     ┆ 1   ┆ 1de ┆     ┆     ┆ sho ┆     ┆ 1   ┆     ┆ H3K ┆     ┆ 353 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ 4me ┆     ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 37f ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ 4me ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 53/ ┆ 93; ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 383 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ ind ┆     ┆     ┆     ┆     ┆     ┆ R20 ┆     ┆     ┆     ┆ d3c ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ 3   ┆     ┆ R20 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ eth ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 095 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆ rep ┆     ┆ uci ┆     ┆     ┆     ┆     ┆     ┆ 622 ┆     ┆     ┆     ┆ 7cd ┆     ┆     ┆ uci ┆     ┆     ┆     ┆ rep ┆     ┆ 622 ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 2;7 ┆     ┆     ┆ ano ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ //w ┆ //w ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆ 353 ┆     ┆     ┆     ┆ 780 ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆ 1   ┆     ┆ 353 ┆     ┆     ┆     ┆     ┆     ┆ 223 ┆ 776 ┆     ┆     ┆ l-f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hg1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ww. ┆ ww. ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ sti ┆     ┆     ┆     ┆     ┆     ┆ _1. ┆     ┆     ┆     ┆ ce  ┆     ┆     ┆ sti ┆     ┆     ┆     ┆ Hom ┆     ┆ _1. ┆     ┆     ┆     ┆     ┆     ┆ 53_ ┆ ;11 ┆     ┆     ┆ ree ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ncb ┆ ncb ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ mul ┆     ┆     ┆     ┆     ┆     ┆ fas ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ mul ┆     ┆     ┆     ┆ o   ┆     ┆ fas ┆     ┆     ┆     ┆     ┆     ┆ 1.f ┆ 757 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## 4. GSE276302 (ChIP-seq; H3K27ac) (ChIP-Atlas: False)

- [HSF1–DBC1 axis drives prostate cancer progression by activating a metastatic transcriptional program](https://doi.org/10.1038/s12276-025-01545-7)
- `Detection of phosphorylated HSF1 and kinase assays; 22RV1 and SM1 cells were treated with HS at 42 °C or GSK-626616 (DYRK inhibitor, Tocris Bioscience) and lysed in FLAG lysis buffer24 containing phosphatase and protease inhibitor cocktails (Roche Diagnostics). `

In [53]:
defined_pairs_gse276302_chipseq_histone_modification = [
    # H3K27ac
    ("SRX25966378", "SRX25966375"), # k27ac_hs_22rv1 vs. k27ac_nhs_22rv1
    ("SRX25966380", "SRX25966377"), # k27ac_hs_22rv1_d1ko vs. k27ac_nhs_22rv1_d1ko
    ("SRX25966379", "SRX25966376")  # k27ac_hs_22rv1_h1ko vs. k27ac_nhs_22rv1_h1ko
]

paired_metada_df_gse276302_histone_modification = create_paired_metadata(
    combined_df=GSE276302_combined,
    defined_sample_pairs=defined_pairs_gse276302_chipseq_histone_modification,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_gse276302_histone_modification is not None:
    paired_metada_df_gse276302_histone_modification.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/GSE276302_chipseq_histone_modification_paired_metadata.tsv",
        separator='\t'
    )
    
    pl.Config.set_tbl_rows(2)
    display(paired_metada_df_gse276302_histone_modification)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ sam ┆ chi ┆ cel ┆ cel ┆ tre ┆ bas ┆ ada ┆ ali ┆ ded ┆ pea ┆ ass ┆ sup ┆ bio ┆ sra ┆ ref ┆ str ┆ str ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ cou ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ ple ┆ p_a ┆ l_l ┆ l_t ┆ atm ┆ eca ┆ pte ┆ gn  ┆ upl ┆ k_c ┆ emb ┆ ple ┆ sam ┆ --- ┆ ere ┆ ess ┆ ess ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _se ┆ _da ┆ nti ┆ ine ┆ ype ┆ ent ┆ lli ┆ r_t ┆ --- ┆ ica ┆ all ┆ ly  ┆ men ┆ ple ┆ str ┆ nce ┆ tre ┆ tre ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ y   ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ rie ┆ ta_ ┆ bod ┆ --- ┆ --- ┆ --- ┆ ng  ┆ rim ┆ str ┆ tio ┆ ing ┆ --- ┆ tar ┆ --- ┆     ┆ _do ┆ atm ┆ atm ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ --- ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ s_i ┆ row ┆ y   ┆ str ┆ str ┆ str ┆ --- ┆ min ┆     ┆ n   ┆ --- ┆ str ┆ y_f ┆ str ┆     ┆ i   ┆ ent ┆ ent ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ d   ┆ _co ┆ --- ┆     ┆     ┆     ┆ str ┆ g   ┆     ┆ --- ┆ str ┆     ┆ ile ┆     ┆     ┆ --- ┆ tem ┆ tim ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆     ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ --- ┆ unt ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆     ┆ s_f ┆     ┆     ┆ str ┆ per ┆ e   ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆ atu ┆ --- ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ k27 ┆ K27 ┆ GSM ┆ Pub ┆ Sep ┆ Sep ┆ SRA ┆ 1   ┆ 22R ┆ Hom ┆ 960 ┆ gen ┆ GPL ┆ Jeo ┆ Sun ┆ Irw ┆ Seo ┆ 135 ┆ Sou ┆ Ill ┆ ChI ┆ gen ┆ ChI ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ H3K ┆ 22R ┆ Cas ┆ Hea ┆ bcl ┆ Tri ┆ Bow ┆ Pic ┆ MAC ┆ hg1 ┆ big ┆ htt ┆ htt ┆ htt ┆ 42  ┆ 60  ┆ SRR ┆ Ill ┆ SAM ┆ DBC ┆ SRA ┆ ChI ┆ 202 ┆ 258 ┆ ILL ┆ ftp ┆ mis ┆ Gen ┆ K27 ┆ 579 ┆ SRP ┆ 515 ┆ DBC ┆ GEN ┆ K27 ┆ Ill ┆ Ill ┆ Cas ┆ ftp ┆ 104 ┆ ChI ┆ GEN ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Chr ┆ mis ┆ GSM ┆ 22R ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ 259 ┆ 259 ┆ ac_ ┆ ac_ ┆ 849 ┆ lic ┆ 04  ┆ 02  ┆     ┆     ┆ V1  ┆ o   ┆ 6   ┆ omi ┆ 246 ┆ ng, ┆ gky ┆ on- ┆ ul  ┆ -71 ┆ th  ┆ umi ┆ P   ┆ omi ┆ P-S ┆ 849 ┆ :// ┆ 276 ┆     ┆ 27a ┆ V1  ┆ tra ┆ t   ┆ 2fa ┆ mmo ┆ tie ┆ ard ┆ S2  ┆ 9   ┆ wig ┆ ps: ┆ ps: ┆ ps: ┆ C   ┆ min ┆ 305 ┆ umi ┆ N43 ┆ 1   ┆ 196 ┆ P   ┆ 5-0 ┆ 096 ┆ UMI ┆ .sr ┆ sin ┆ eri ┆ ac_ ┆ f08 ┆ 530 ┆ 982 ┆ 1   ┆ ERA ┆ ac_ ┆ umi ┆ umi ┆ tra ┆ .sr ┆ 228 ┆ P-S ┆ OMI ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 849 ┆ 849 ┆ oma ┆ sin ┆ 849 ┆ V1  ┆ 849 ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA1 ┆ 305 ┆ 225 ┆ 5-0 ┆ 276 │
│ 663 ┆ 663 ┆ hs_ ┆ HS_ ┆ 618 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ c   ┆ 76  ┆ Hoo ┆ unk ┆ don ┆     ┆ 0   ┆ Kor ┆ na  ┆     ┆ c   ┆ eq  ┆ 618 ┆ ftp ┆ 302 ┆     ┆ c   ┆     ┆ tio ┆ sho ┆ stq ┆ mat ┆ 1.1 ┆ 1.1 ┆ 2.1 ┆     ┆     ┆ //w ┆ //w ┆ //d ┆     ┆ .   ┆ 429 ┆ na  ┆ 495 ┆ pro ┆ 254 ┆     ┆ 9-0 ┆ 784 ┆ NA  ┆ a.e ┆ g   ┆ c   ┆ HS_ ┆ 088 ┆ 416 ┆ 42  ┆ pro ┆ TED ┆ HS_ ┆ na  ┆ na  ┆ tio ┆ a.e ┆ 448 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ 618 ┆ 618 ┆ tin ┆ g   ┆ 618 ┆     ┆ 618 ┆ x:t ┆ 9-0 ┆ sap ┆     ┆ 156 ┆ 429 ┆ 445 ┆ 9-0 ┆ 302 │
│ 78  ┆ 75  ┆ 22r ┆ 22R ┆ 1   ┆ Sep ┆ 4   ┆ 5   ┆     ┆     ┆     ┆ ien ┆     ┆ DNA ┆     ┆ n,K ┆ wan ┆ g   ┆     ┆     ┆ ea  ┆ Nov ┆     ┆     ┆     ┆ 1   ┆ .nc ┆     ┆     ┆ (Ab ┆     ┆ n-r ┆ ck  ┆ v2. ┆ ic  ┆ .2  ┆ 18  ┆ .1. ┆     ┆     ┆ ww. ┆ ww. ┆ oi. ┆     ┆     ┆ 68  ┆ Nov ┆ 073 ┆ mot ┆ 4   ┆     ┆ 3   ┆ 1;2 ┆     ┆ bi. ┆     ┆     ┆ 22R ┆ 93c ┆     ┆ vs  ┆ mot ┆ _FI ┆ 22R ┆ Nov ┆ Nov ┆ n-r ┆ bi. ┆ 84  ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ 1   ┆ 1_r ┆ pre ┆     ┆ 1_r ┆     ┆ 1   ┆ err ┆ 3   ┆ ien ┆     ┆ 585 ┆ 68  ┆ 68  ┆ 3   ┆     │
│     ┆     ┆ v1  ┆ V1  ┆ vs  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ im  ┆ Uni ┆ Gan ┆     ┆     ┆     ┆ aSe ┆     ┆     ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ cam ┆     ┆ esi ┆ at  ┆ 20. ┆ v0. ┆     ┆ Mar ┆ 201 ┆     ┆     ┆ ncb ┆ ncb ┆ org ┆     ┆     ┆ vs  ┆ aSe ┆ vs  ┆ es  ┆     ┆     ┆     ┆ 638 ┆     ┆ ac. ┆     ┆     ┆ V1  ┆ a2f ┆     ┆ 574 ┆ es  ┆ LE; ┆ V1  ┆ aSe ┆ aSe ┆ esi ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ par ┆     ┆ 1   ┆     ┆ vs  ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆ vs  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆ gna ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ ,   ┆     ┆ sta ┆ 42℃ ┆ 0   ┆ 38  ┆     ┆ kDu ┆ 603 ┆     ┆     ┆ i.n ┆ i.n ┆ /10 ┆     ┆     ┆ SRR ┆ q   ┆ SAM ┆ met ┆     ┆     ┆     ┆ 989 ┆     ┆ uk/ ┆     ┆     ┆ vs  ┆ e9f ┆     ┆ 384 ┆ met ┆ GEN ┆ vs  ┆ q   ┆ q   ┆ sta ┆ uk/ ┆ 116 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ati ┆     ┆ vs  ┆     ┆ GSM ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆ SRS ┆     ┆     │
│     ┆     ┆ k27 ┆ K27 ┆ 849 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit ┆ m-g ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 849 ┆ .ni ┆     ┆     ┆ ab4 ┆     ┆ nt  ┆ for ┆     ┆     ┆     ┆ pli ┆ 09  ┆     ┆     ┆ lm. ┆ lm. ┆ .10 ┆     ┆     ┆ 305 ┆ 600 ┆ N43 ┆ ast ┆     ┆     ┆     ┆ 142 ┆     ┆ vol ┆     ┆     ┆ K27 ┆ b06 ┆     ┆ 13  ┆ ast ┆ ERA ┆ K27 ┆ 600 ┆ 600 ┆ nt  ┆ vol ┆ 025 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 849 ┆ GSM ┆ on  ┆     ┆ GSM ┆     ┆ 849 ┆ l;e ┆     ┆     ┆     ┆     ┆ 305 ┆ 225 ┆     ┆     │
│     ┆     ┆ ac_ ┆ ac_ ┆ 617 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ u   ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 617 ┆ h.g ┆     ┆     ┆ 729 ┆     ┆ pro ┆ 60  ┆     ┆     ┆     ┆ cat ┆     ┆     ┆     ┆ nih ┆ nih ┆ 38/ ┆     ┆     ┆ 429 ┆ 0   ┆ 495 ┆ ati ┆     ┆     ┆     ┆ vs  ┆     ┆ 1/f ┆     ┆     ┆ ac_ ┆ 1cb ┆     ┆     ┆ ati ┆ TED ┆ ac_ ┆ 0   ┆ 0   ┆ pro ┆ 1/f ┆ 594 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 617 ┆ 849 ┆ and ┆     ┆ 849 ┆     ┆ 617 ┆ nv_ ┆     ┆     ┆     ┆     ┆ 429 ┆ 445 ┆     ┆     │
│     ┆     ┆ nhs ┆ NHS ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ ov/ ┆     ┆     ┆ )   ┆     ┆ sta ┆ min ┆     ┆     ┆     ┆ es  ┆     ┆     ┆     ┆ .go ┆ .go ┆ s12 ┆     ┆     ┆ 71  ┆ seq ┆ 076 ┆ c   ┆     ┆     ┆     ┆ 287 ┆     ┆ ast ┆     ┆     ┆ NHS ┆ f18 ┆     ┆     ┆ c   ┆ _FI ┆ NHS ┆     ┆ seq ┆ sta ┆ ast ┆ 26  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 8   ┆ 617 ┆ ChI ┆     ┆ 617 ┆     ┆ 8   ┆ tax ┆     ┆     ┆     ┆     ┆ 71  ┆ 72  ┆     ┆     │
│     ┆     ┆ _22 ┆ _22 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆ te  ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ v/b ┆ v/s ┆ 276 ┆     ┆     ┆     ┆ uen ┆     ┆ cas ┆     ┆     ┆     ┆ 191 ┆     ┆ q/S ┆     ┆     ┆ _22 ┆ 435 ┆     ┆     ┆ cas ┆ LE  ┆ _22 ┆     ┆ uen ┆ te  ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 8_r ┆ P   ┆     ┆ 8_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rv1 ┆ RV1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆ can ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ios ┆ ra? ┆ -02 ┆     ┆     ┆     ┆ cin ┆     ┆ tra ┆     ┆     ┆     ┆ 914 ┆     ┆ RR3 ┆     ┆     ┆ RV1 ┆ 69; ┆     ┆     ┆ tra ┆     ┆ RV1 ┆     ┆ cin ┆ can ┆ RR3 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ wer ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆ cer ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ amp ┆ ter ┆ 5-0 ┆     ┆     ┆     ┆ g:  ┆     ┆ tio ┆     ┆     ┆     ┆ 5;2 ┆     ┆ 05/ ┆     ┆     ┆     ┆ 007 ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ g:  ┆ cer ┆ 05/ ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆ 213 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆ cel ┆ Non ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le/ ┆ m=S ┆ 154 ┆     ┆     ┆     ┆ GSM ┆     ┆ n-r ┆     ┆     ┆     ┆ 921 ┆     ┆ 068 ┆     ┆     ┆     ┆ 745 ┆     ┆     ┆ n-r ┆     ┆     ┆     ┆ GSM ┆ cel ┆ 068 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆ ;33 ┆     ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ ls  ┆ -he ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ RX2 ┆ 5-7 ┆     ┆     ┆     ┆ 849 ┆     ┆ esi ┆     ┆     ┆     ┆ 090 ┆     ┆ /SR ┆     ┆     ┆     ┆ 84a ┆     ┆     ┆ esi ┆     ┆     ┆     ┆ 849 ┆ ls  ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 68/ ┆ 511 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 849 ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N43 ┆ 596 ┆     ┆     ┆     ┆     ┆ 618 ┆     ┆ sta ┆     ┆     ┆     ┆ 141 ┆     ┆ R30 ┆     ┆     ┆     ┆ 42a ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ 618 ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 495 ┆ 637 ┆     ┆     ┆     ┆     ┆ 1:  ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆ 542 ┆     ┆     ┆     ┆ 740 ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆ 1:  ┆     ┆ 542 ┆     ┆     ┆     ┆     ┆     ┆ 305 ┆ 11; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 073 ┆ 8   ┆     ┆     ┆     ┆     ┆ K27 ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ 968 ┆     ┆     ┆     ┆ 3de ┆     ┆     ┆ pro ┆     ┆     ┆     ┆ K27 ┆     ┆ 968 ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆ 895 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM8 ┆     ┆     ┆     ┆     ┆     ┆ (NH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆     ┆     ┆ ac_ ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆ 674 ┆     ┆     ┆ sta ┆     ┆     ┆     ┆ ac_ ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 68/ ┆ 93; ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 496 ┆     ┆     ┆     ┆     ┆     ┆ S)  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ htt ┆ htt ┆     ┆     ┆     ┆     ┆ HS_ ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆ R30 ┆     ┆     ┆     ┆ ca6 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆ HS_ ┆     ┆ R30 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ Sim ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## Strategy 2: Double Check using [GEOfinder](https://bioapps.byu.edu/geofinder/) 

- [GEOfinder](https://bioapps.byu.edu/geofinder/) で、収集の漏れがないか簡易的に調査
- 収集されていないものはないと判断

&nbsp;

&nbsp;

## Strategy 3: `BioProject` で調査

- 以下のクエリで `BioProject`のページを調査 (2026−05−03)
- 1つだけ発見

```text
(((((((((("heat stress") OR "heat shock") OR "high temperature stress") OR "hyperthermia") OR "heat stroke")) AND "homo sapiens"[Organism]) AND "bioproject sra"[Filter]) AND "epigenomics"[Project Data Type])) NOT "bioproject gds"[Filter]
```

&nbsp;

&nbsp;

## 1. PRJNA369311 (SRP098615) (ChIP-seq; HIRA) (ChIP-Atlas: False)

- [Histone H3.3 chaperone HIRA renders stress-responsive genes poised for prospective lethal stresses in acquired tolerance](https://doi.org/10.1111/gtc.13140)
- `4.2 Heat treatment; Cells were seeded at a density of 1.1 × 104 or 1.7 × 104 cells/cm2 in 35 mm dishes for immortalized cells and primary cells, respectively, and incubated for 24 h at 37°C before heat shock treatment. For priming stress treatment, culture media was replaced with fresh media pre-heated at 40°C, and cells were cultured in an incubator at 40°C (±0.5°C) and 5% CO2 for 2 h. For lethal stress treatment, culture media was replaced with fresh media pre-heated at 47°C, and cells were cultured in an incubator at 47°C (±0.5°C) and 5% CO2 for 35 min. After heat treatment, the media was replaced by fresh media (37°C), and the cells were incubated in an incubator at 37°C (±0.5°C) and 5% CO2 for 48 h. Cell viability was quantified using a Cell Counting Kit-8 (Dojindo) and SpectraMax 340 Microplate Reader (Molecular Devices).`

In [54]:
PRJNA369311 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/PRJNA369311.metadata.tsv",
    separator='\t'
).filter(
    (pl.col("library_strategy") == "ChIP-Seq") &
    (pl.col("tax_id") == 9606)
).with_columns(
    pl.lit("https://doi.org/10.1111/gtc.13140").alias("reference_doi"),
    pl.lit("40 C").alias("stress treatment temperature"),
    pl.lit("120 min.").alias("stress treatment time")
)

PRJNA369311_filtered = PRJNA369311[[s.name for s in PRJNA369311 if not (s.null_count() == PRJNA369311.height)]]


# pl.Config.set_tbl_rows(6)
# display(PRJNA369311_filtered)

In [55]:
defined_pairs_prjna369311_chipseq = [
    ("SRX2558059", "SRX2529349"), # 2015_007A_40C_HIRA vs. 2015_007A_37C_HIRA
    ("SRX2558060", "SRX2558057"), # 2015_007A_40C_IgG vs. 2015_007A_37C_IgG
    ("SRX2558061", "SRX2558058")  # 2015_007A_40C_input vs. 2015_007A_37C_input
]

paired_metada_df_prjna369311_chipseq = create_paired_metadata(
    combined_df=PRJNA369311_filtered,
    defined_sample_pairs=defined_pairs_prjna369311_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_prjna369311_chipseq is not None:
    paired_metada_df_prjna369311_chipseq.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/PRJNA369311_chipseq_paired_metadata.tsv",
        separator='\t'
    )
    
    display(paired_metada_df_prjna369311_chipseq)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 50)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ sex ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu ┆ tis ┆ ref ┆ str ┆ str │
│ ple ┆ ple ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ --- ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ ┆ sue ┆ ere ┆ ess ┆ ess │
│ _he ┆ _co ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ str ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali ┆ _ty ┆ nce ┆ tre ┆ tre │
│ at_ ┆ ntr ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆     ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ t_a ┆ me  ┆ --- ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  ┆ pe  ┆ _do ┆ atm ┆ atm │
│ id  ┆ ol_ ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆     ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ --- ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ lia ┆ --- ┆ str ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- ┆ --- ┆ i   ┆ ent ┆ ent │
│ --- ┆ id  ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆     ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ str ┆ l   ┆ str ┆     ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ s   ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ e_a ┆ str ┆ str ┆ str ┆ --- ┆ tem ┆ tim │
│ str ┆ --- ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆     ┆ nda ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆ cce ┆     ┆     ┆     ┆ str ┆ per ┆ e   │
│     ┆ str ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ rd  ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     ┆     ┆ atu ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆ re  ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRX ┆ SRX ┆ SRR ┆ Ill ┆ SAM ┆ Hom ┆ SRA ┆ uns ┆ 201 ┆ 185 ┆ ILL ┆ fem ┆ ftp ┆ Hum ┆ WI- ┆ 4f3 ┆ SRP ┆ 408 ┆ HIR ┆ GEN ┆ WI- ┆ Ill ┆ Ill ┆ fib ┆ ftp ┆ 269 ┆ ChI ┆ GEN ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ WI- ┆ 201 ┆ pri ┆ The ┆ WI- ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRR ┆ SRS ┆ 201 ┆ PRJ ┆ lun ┆ htt ┆ 40  ┆ 120 │
│ 255 ┆ 252 ┆ 525 ┆ umi ┆ N06 ┆ o   ┆ 533 ┆ pec ┆ 8-0 ┆ 288 ┆ UMI ┆ ale ┆ .sr ┆ an  ┆ 38_ ┆ 26d ┆ 098 ┆ 171 ┆ A_W ┆ ERA ┆ 38_ ┆ umi ┆ umi ┆ rob ┆ .sr ┆ 393 ┆ P-S ┆ OMI ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 38_ ┆ 5_0 ┆ min ┆ Uni ┆ 38  ┆ _ta ┆ 8-0 ┆ o   ┆ 6   ┆ NA3 ┆ 525 ┆ 195 ┆ 8-0 ┆ NA3 ┆ g   ┆ ps: ┆ C   ┆ min │
│ 805 ┆ 934 ┆ 235 ┆ na  ┆ 284 ┆ sap ┆ 844 ┆ ifi ┆ 2-0 ┆ 970 ┆ NA  ┆     ┆ a.e ┆     ┆ Hum ┆ d97 ┆ 615 ┆ 99  ┆ I-3 ┆ TED ┆ Hum ┆ na  ┆ na  ┆ las ┆ a.e ┆ 513 ┆ eq  ┆ C   ┆     ┆     ┆ ra. ┆ 67; ┆ Hum ┆ 07A ┆ g_H ┆ ver ┆     ┆ x:t ┆ 2-0 ┆ sap ┆     ┆ 693 ┆ 235 ┆ 031 ┆ 2-0 ┆ 693 ┆     ┆ //d ┆     ┆ .   │
│ 9   ┆ 9   ┆ 9   ┆ HiS ┆ 127 ┆ ien ┆     ┆ ed  ┆ 1   ┆ 8   ┆     ┆     ┆ bi. ┆     ┆ an  ┆ b4d ┆     ┆ vs  ┆ 8_C ┆ _FI ┆ an  ┆ HiS ┆ HiS ┆ t   ┆ bi. ┆ 4   ┆     ┆     ┆     ┆     ┆ ebi ┆ 275 ┆ an_ ┆ _40 ┆ IRA ┆ sit ┆     ┆ err ┆ 1   ┆ ien ┆     ┆ 11  ┆ 9   ┆ 3   ┆ 1   ┆ 11  ┆     ┆ oi. ┆     ┆     │
│     ┆     ┆ vs  ┆ eq  ┆     ┆ s   ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ ac. ┆     ┆ sam ┆ 36c ┆     ┆ 438 ┆ hIP ┆ LE  ┆ sam ┆ eq  ┆ eq  ┆     ┆ ac. ┆ vs  ┆     ┆     ┆     ┆     ┆ .ac ┆ 9;3 ┆ cau ┆ C_H ┆ _Ch ┆ y   ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ org ┆     ┆     │
│     ┆     ┆ SRR ┆ 250 ┆     ┆ str ┆     ┆     ┆     ┆ 198 ┆     ┆     ┆ uk/ ┆     ┆ ple ┆ 4d9 ┆     ┆ 512 ┆ -se ┆     ┆ ple ┆ 250 ┆ 250 ┆     ┆ uk/ ┆ 289 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ cas ┆ IRA ┆ IP  ┆ of  ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆ /10 ┆     ┆     │
│     ┆     ┆ 525 ┆ 0   ┆     ┆ ain ┆     ┆     ┆     ┆ 490 ┆     ┆     ┆ vol ┆     ┆ fro ┆ fb2 ┆     ┆ 61  ┆ q   ┆     ┆ fro ┆ 0   ┆ 0   ┆     ┆ vol ┆ 418 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ ian ┆ vs  ┆ vs  ┆ Tok ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 525 ┆     ┆     ┆     ┆     ┆ .11 ┆     ┆     │
│     ┆     ┆ 235 ┆ seq ┆     ┆ :WI ┆     ┆     ┆     ┆ 852 ┆     ┆     ┆ 1/f ┆     ┆ m   ┆ c03 ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ seq ┆     ┆ 1/f ┆ 322 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ fib ┆ 201 ┆ no_ ┆ yo, ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 235 ┆     ┆     ┆     ┆     ┆ 11/ ┆     ┆     │
│     ┆     ┆ 5   ┆ uen ┆     ┆ 38  ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ ast ┆     ┆ Hom ┆ 02d ┆     ┆     ┆     ┆     ┆ Hom ┆     ┆ uen ┆     ┆ ast ┆ 6   ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ rob ┆ 5_0 ┆ str ┆ IMC ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ gtc ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆ o   ┆ 3b1 ┆     ┆     ┆     ┆     ┆ o   ┆     ┆ cin ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆ las ┆ 07A ┆ ess ┆ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .13 ┆     ┆     │
│     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR5 ┆     ┆ sap ┆ 93  ┆     ┆     ┆     ┆     ┆ sap ┆     ┆ g:  ┆     ┆ RR5 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆ t-l ┆ _37 ┆ _HI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 140 ┆     ┆     │
│     ┆     ┆     ┆ pri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25/ ┆     ┆ ien ┆ vs  ┆     ┆     ┆     ┆     ┆ ien ┆     ┆ pri ┆     ┆ 25/ ┆     ┆     ┆     ┆     ┆     ┆ R52 ┆ 213 ┆ ike ┆ C_H ┆ RA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 009 ┆     ┆ s   ┆ f58 ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ min ┆     ┆ 009 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆ ;33 ┆ fet ┆ IRA ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆ 5d7 ┆     ┆     ┆     ┆     ┆     ┆     ┆ g_H ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 09/ ┆ 511 ┆ al  ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ IRA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R52 ┆     ┆     ┆ c55 ┆     ┆     ┆     ┆     ┆     ┆     ┆ IRA ┆     ┆ R52 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆ lun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ _Ch ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 523 ┆     ┆     ┆ 9c5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ch ┆     ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆ 11; ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ IP  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 59/ ┆     ┆     ┆ 501 ┆     ┆     ┆     ┆     ┆     ┆     ┆ IP  ┆     ┆ 59/ ┆     ┆     ┆     ┆     ┆     ┆ 235 ┆ 895 ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ 430 ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 9/S ┆ 93; ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ Ill ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆     ┆     ┆ fb1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆     ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆ RR5 ┆ 774 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ umi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 235 ┆     ┆     ┆ 6db ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆     ┆ 235 ┆     ┆     ┆     ┆     ┆     ┆ 252 ┆ 2;7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ na  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9.f ┆     ┆     ┆ b62 ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆     ┆ 9.f ┆     ┆     ┆     ┆     ┆     ┆ 359 ┆ 776 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ HiS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆ 757 ┆     ┆     ┆     ┆     ┆     ┆     ┆ HiS ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆ ;11 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q.g ┆     ┆     ┆ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ q.g ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 757 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 250 ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆ 0;1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 175 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 71; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uen ┆     ┆ .sr ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 828 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cin ┆     ┆ a.e ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆ 7;1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ 338 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ no_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ no_ ┆     ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 369 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ ;32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ess ┆     ┆ vol ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ _HI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _HI ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ ;32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ RA_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RA_ ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 524 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ ;40 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ P   ┆     ┆ RR5 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ 674 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25/ ┆     ┆     ┆     ┆     ┆     ┆ R52 ┆ ;32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆     ┆     ┆     ┆ 5/0 ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 05/ ┆ ;93 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R52 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R52 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 47; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 523 ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆ 143 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55/ ┆     ┆     ┆     ┆     ┆     ┆ 235 ┆ 701 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆     ┆     ┆     ┆ 5/S ┆ 0;3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 525 ┆     ┆     ┆     ┆     ┆     ┆ RR5 ┆ 141 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 235 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 235 ┆     ┆     ┆     ┆     ┆     ┆ 252 ┆ 46; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5.f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5.f ┆     ┆     ┆     ┆     ┆     ┆ 355 ┆ 944 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆ 3;3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q.g ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 769 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆ 13; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 314 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 293 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ;95 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26; ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

## Strategy 4: `BioProject` で調査 (2)

- 以下のクエリで `BioProject`のページを調査 (2026−05−03)
- `other"[Project Data Type]` を指定して調査

```text
((((((("heat stress"[All Fields] OR "heat shock"[All Fields]) OR "high temperature stress"[All Fields]) OR "hyperthermia"[All Fields]) OR "heat stroke"[All Fields]) AND "homo sapiens"[Organism]) AND "bioproject sra"[Filter]) AND "other"[Project Data Type]) NOT "bioproject gds"[Filter]
```

&nbsp;

## 1. PRJEB5930 (ChIP-seq; SUMO2)

- [ENA browser: PRJEB5930](https://www.ebi.ac.uk/ena/browser/view/PRJEB5930)
- [Proteotoxic stress reprograms the chromatin landscape of SUMO modification](https://doi.org/10.1126/scisignal.aaa2213)
- `Results;ChIP-seq reveals substantial increases in the binding of SUMO-2 to active DNA-regulatory elements in response to HS; To characterize changes in the association of SUMO-2 with chromatin in response to HS in an unbiased manner, we used chromatin immunoprecipitation (ChIP) coupled to high-throughput sequencing (ChIP-seq) to determine the genome-wide profiles of SUMO-2 in U2OS (human osteosarcoma) cells that were either unstressed or were subjected to HS by shifting the incubation temperature of the cells to 43°C for 30 min (HS cells),`

In [56]:
PRJEB5930 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/PRJEB5930.metadata.tsv",
    separator='\t'
).filter(
    (pl.col("library_strategy") == "ChIP-Seq") &
    (pl.col("tax_id") == 9606)
).with_columns(
    pl.lit("https://doi.org/10.1126/scisignal.aaa2213").alias("reference_doi"),
    pl.lit("43 C").alias("stress treatment temperature"),
    pl.lit("30 min.").alias("stress treatment time")
)

PRJEB5930_filtered = PRJEB5930[[s.name for s in PRJEB5930 if not (s.null_count() == PRJEB5930.height)]]

# display(PRJEB5930_filtered)

In [57]:
defined_pairs_prjeb5930_chipseq = [
    ("ERX432314", "ERX432310"), # heat_shock_SUMO2_ChIP_protein G Dynabeads beads vs. untreated_SUMO2_ChIP_protein G Dynabeads beads
    ("ERX432312", "ERX432309"), # heat_shock_SUMO2_ChIP_protein G sepharose 4B beads vs. untreated_SUMO2_ChIP_protein G sepharose 4B beads
    ("ERX432311", "ERX432313")  # heat_shock_input vs. untreated_input
]

paired_metada_df_prjeb5930_chipseq = create_paired_metadata(
    combined_df=PRJEB5930_filtered,
    defined_sample_pairs=defined_pairs_prjeb5930_chipseq,
    sample_id_column_name="experiment_accession"
)

if paired_metada_df_prjeb5930_chipseq is not None:
    paired_metada_df_prjeb5930_chipseq.write_csv(
        "../../Data/metadata/metadata_chipseq/HS_related_paired_metadata/PRJEB5930_chipseq_paired_metadata.tsv",
        separator='\t'
    )
    
    display(paired_metada_df_prjeb5930_chipseq)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ run ┆ exp ┆ sam ┆ pro ┆ sub ┆ lib ┆ las ┆ sub ┆ sub ┆ fas ┆ ins ┆ sub ┆ sex ┆ sub ┆ che ┆ fas ┆ sub ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bro ┆ bas ┆ lib ┆ lib ┆ lib ┆ dat ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ sub ┆ sub ┆ lib ┆ exp ┆ cen ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sub ┆ acc ┆ sec ┆ fir ┆ stu ┆ ref ┆ str ┆ str │
│ ple ┆ ple ┆ _ac ┆ eri ┆ ple ┆ jec ┆ mis ┆ rar ┆ t_u ┆ mit ┆ mit ┆ tq_ ┆ tru ┆ mit ┆ --- ┆ mit ┆ ckl ┆ tq_ ┆ mit ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ ker ┆ e_c ┆ rar ┆ rar ┆ rar ┆ ahu ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ mit ┆ mit ┆ rar ┆ eri ┆ ter ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ mit ┆ ess ┆ ond ┆ st_ ┆ dy_ ┆ ere ┆ ess ┆ ess │
│ _he ┆ _co ┆ ces ┆ men ┆ _ac ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ ted ┆ ted ┆ byt ┆ men ┆ ted ┆ str ┆ ted ┆ ist ┆ gal ┆ ted ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ _na ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ b   ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ ted ┆ ted ┆ y_c ┆ men ┆ _na ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ted ┆ ion ┆ ary ┆ pub ┆ ali ┆ nce ┆ tre ┆ tre │
│ at_ ┆ ntr ┆ sio ┆ t_t ┆ ces ┆ ame ┆ n_a ┆ ele ┆ ted ┆ _ga ┆ _ft ┆ es  ┆ t_p ┆ _as ┆     ┆ _md ┆ --- ┆ axy ┆ _by ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ me  ┆ t   ┆ tra ┆ our ┆ ayo ┆ --- ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ _fi ┆ _re ┆ ons ┆ t_a ┆ me  ┆ --- ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _fo ┆ --- ┆ _sa ┆ lic ┆ as  ┆ _do ┆ atm ┆ atm │
│ id  ┆ ol_ ┆ n   ┆ itl ┆ sio ┆ --- ┆ cce ┆ cti ┆ --- ┆ lax ┆ p   ┆ --- ┆ lat ┆ per ┆     ┆ 5   ┆ str ┆ --- ┆ tes ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ --- ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆ str ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ le_ ┆ ad_ ┆ tru ┆ lia ┆ --- ┆ str ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ rma ┆ str ┆ mpl ┆ --- ┆ --- ┆ i   ┆ ent ┆ ent │
│ --- ┆ id  ┆ --- ┆ e   ┆ n   ┆ str ┆ ssi ┆ on  ┆ str ┆ y   ┆ --- ┆ str ┆ for ┆ a   ┆     ┆ --- ┆     ┆ str ┆ --- ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ str ┆ l   ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆ rol ┆ typ ┆ cti ┆ s   ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ t   ┆     ┆ e_a ┆ str ┆ str ┆ --- ┆ tem ┆ tim │
│ str ┆ --- ┆ str ┆ --- ┆ --- ┆     ┆ on  ┆ --- ┆     ┆ --- ┆ str ┆     ┆ m   ┆ --- ┆     ┆ str ┆     ┆     ┆ str ┆ --- ┆     ┆ ces ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ e   ┆ on_ ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆ cce ┆     ┆     ┆ str ┆ per ┆ e   │
│     ┆ str ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ sio ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ ssi ┆     ┆     ┆     ┆ atu ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ re  ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ ERX ┆ ERX ┆ ERR ┆ Ill ┆ SAM ┆ hea ┆ ERA ┆ ChI ┆ 201 ┆ ftp ┆ ftp ┆ 867 ┆ ILL ┆ fas ┆ fem ┆ 93e ┆ ERC ┆ ftp ┆ 897 ┆ Pro ┆ 9fc ┆ ERP ┆ 233 ┆ hea ┆ GEN ┆ gro ┆ Ill ┆ Ill ┆ hum ┆ ftp ┆ Arr ┆ 841 ┆ ChI ┆ GEN ┆ SIN ┆ dcc ┆ pub ┆ fas ┆ 1;1 ┆ E-M ┆ E-M ┆ SUB ┆ SIN ┆ Hum ┆ E-M ┆ Eur ┆ U2O ┆ hea ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ FAS ┆ ERR ┆ ERS ┆ 201 ┆ E-M ┆ htt ┆ 43  ┆ 30  │
│ 432 ┆ 432 ┆ 466 ┆ umi ┆ EA2 ┆ t   ┆ 294 ┆ P   ┆ 8-1 ┆ .sr ┆ .sr ┆ 924 ┆ UMI ┆ p.s ┆ ale ┆ 7ae ┆ 000 ┆ .sr ┆ 109 ┆ toc ┆ fa2 ┆ 005 ┆ 862 ┆ t   ┆ ERA ┆ win ┆ umi ┆ umi ┆ an  ┆ .sr ┆ ayE ┆ 904 ┆ P-S ┆ OMI ┆ GLE ┆ _ar ┆ lic ┆ p.s ┆ 315 ┆ TAB ┆ TAB ┆ MIS ┆ GLE ┆ an  ┆ TAB ┆ ope ┆ S   ┆ t_s ┆ _ta ┆ 4-0 ┆ o   ┆ 6   ┆ EB5 ┆ TQ  ┆ 466 ┆ 425 ┆ 5-0 ┆ TAB ┆ ps: ┆ C   ┆ min │
│ 314 ┆ 310 ┆ 073 ┆ na  ┆ 420 ┆ sho ┆ 640 ┆     ┆ 1-1 ┆ a.e ┆ a.e ┆ 044 ┆ NA  ┆ ra. ┆     ┆ b8b ┆ 011 ┆ a.e ┆ 036 ┆ ols ┆ 2fb ┆ 368 ┆ 24  ┆ sho ┆ TED ┆ g_U ┆ na  ┆ na  ┆ ost ┆ a.e ┆ xpr ┆ 064 ┆ eq  ┆ C   ┆     ┆ ray ┆     ┆ ra. ┆ 67; ┆ -23 ┆ -23 ┆ SIO ┆     ┆ ost ┆ -23 ┆ an  ┆     ┆ hoc ┆ x:t ┆ 3-1 ┆ sap ┆     ┆ 930 ┆     ┆ 073 ┆ 897 ┆ 7-1 ┆ -23 ┆ //d ┆     ┆ .   │
│     ┆     ┆ vs  ┆ Gen ┆ 694 ┆ ck  ┆     ┆     ┆ 6   ┆ bi. ┆ bi. ┆ vs  ┆     ┆ ebi ┆     ┆ 88d ┆     ┆ bi. ┆ vs  ┆ :   ┆ b33 ┆     ┆ vs  ┆ ck  ┆ _FI ┆ 2OS ┆ Gen ┆ Gen ┆ eos ┆ bi. ┆ ess ┆ vs  ┆     ┆     ┆     ┆ exp ┆     ┆ ebi ┆ 275 ┆ 68: ┆ 68: ┆ N_F ┆     ┆ eos ┆ 68: ┆ Bio ┆     ┆ k_S ┆ err ┆ 9   ┆ ien ┆     ┆     ┆     ┆ vs  ┆ vs  ┆ 6   ┆ 68  ┆ oi. ┆     ┆     │
│     ┆     ┆ ERR ┆ ome ┆ vs  ┆ SUM ┆     ┆     ┆     ┆ ac. ┆ ac. ┆ 105 ┆     ┆ .ac ┆     ┆ 393 ┆     ┆ ac. ┆ 108 ┆ Hum ┆ 441 ┆     ┆ 284 ┆ SUM ┆ LE  ┆ _ce ┆ ome ┆ ome ┆ arc ┆ ac. ┆     ┆ 102 ┆     ┆     ┆     ┆ res ┆     ┆ .ac ┆ 9;3 ┆ gro ┆ HSC ┆ ILE ┆     ┆ arc ┆ SO_ ┆ inf ┆     ┆ UMO ┆ est ┆     ┆ s   ┆     ┆     ┆     ┆ ERR ┆ ERS ┆     ┆     ┆ org ┆     ┆     │
│     ┆     ┆ 466 ┆ Ana ┆ SAM ┆ O-2 ┆     ┆     ┆     ┆ uk/ ┆ uk/ ┆ 020 ┆     ┆ .uk ┆     ┆ 598 ┆     ┆ uk/ ┆ 094 ┆ an  ┆ 6aa ┆     ┆ 598 ┆ O-2 ┆     ┆ lls ┆ Ana ┆ Ana ┆ oma ┆ uk/ ┆     ┆ 455 ┆     ┆     ┆     ┆ s   ┆     ┆ .uk ┆ 315 ┆ win ┆ hip ┆     ┆     ┆ oma ┆ 130 ┆ orm ┆     ┆ 2_C ┆ ria ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆ 425 ┆     ┆     ┆ /10 ┆     ┆     │
│     ┆     ┆ 078 ┆ lyz ┆ EA2 ┆ ChI ┆     ┆     ┆     ┆ vol ┆ vol ┆ 866 ┆     ┆ :/v ┆     ┆ 8d0 ┆     ┆ vol ┆ 683 ┆ ost ┆ 3bf ┆     ┆ 57  ┆ ChI ┆     ┆ _6  ┆ lyz ┆ lyz ┆ cel ┆ vol ┆     ┆ 485 ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ g_U ┆ _2. ┆     ┆     ┆ (U2 ┆ 8_1 ┆ ati ┆     ┆ hIP ┆ l;e ┆     ┆     ┆     ┆     ┆     ┆ 078 ┆ 893 ┆     ┆     ┆ .11 ┆     ┆     │
│     ┆     ┆     ┆ er  ┆ 420 ┆ P-s ┆     ┆     ┆     ┆ 1/r ┆ 1/r ┆ 3   ┆     ┆ ol1 ┆     ┆ 987 ┆     ┆ 1/f ┆ 6   ┆ eos ┆ 247 ┆     ┆     ┆ P-s ┆     ┆ vs  ┆ er  ┆ er  ┆ l   ┆ 1/f ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 2OS ┆ fq. ┆     ┆     ┆ OS) ┆ 308 ┆ cs  ┆     ┆ _pr ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26/ ┆     ┆     │
│     ┆     ┆     ┆ IIx ┆ 690 ┆ eq  ┆     ┆     ┆     ┆ un/ ┆ un/ ┆     ┆     ┆ /ru ┆     ┆ 485 ┆     ┆ ast ┆     ┆ arc ┆ 105 ┆     ┆     ┆ eq  ┆     ┆ gro ┆ IIx ┆ IIx ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ _ce ┆ gz  ┆     ┆     ┆ cel ┆ _43 ┆ Ins ┆     ┆ ote ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sci ┆     ┆     │
│     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆ ERR ┆ ERR ┆     ┆     ┆ n/E ┆     ┆ 114 ┆     ┆ q/E ┆     ┆ oma ┆ b07 ┆     ┆     ┆     ┆     ┆ win ┆     ┆ seq ┆     ┆ q/E ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆ lls ┆ vs  ┆     ┆     ┆ ls  ┆ -2  ┆ tit ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sig ┆     ┆     │
│     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆ 466 ┆     ┆     ┆ RR4 ┆     ┆ e8  ┆     ┆ RR4 ┆     ┆ (U2 ┆ d5  ┆     ┆     ┆     ┆     ┆ g_U ┆     ┆ uen ┆     ┆ RR4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ER ┆ ;33 ┆ _6  ┆ E-M ┆     ┆     ┆ wer ┆ vs  ┆ ute ┆     ┆ G   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆     ┆     │
│     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆ /ER ┆ /ER ┆     ┆     ┆ 66/ ┆     ┆ vs  ┆     ┆ 66/ ┆     ┆ OS) ┆ vs  ┆     ┆     ┆     ┆     ┆ 2OS ┆     ┆ cin ┆     ┆ 66/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R46 ┆ 213 ┆ vs  ┆ TAB ┆     ┆     ┆ e   ┆ E-M ┆ ;Ce ┆     ┆ Dyn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .aa ┆     ┆     │
│     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆ R46 ┆ R46 ┆     ┆     ┆ ERR ┆     ┆ e0c ┆     ┆ ERR ┆     ┆ cel ┆ 72e ┆     ┆     ┆     ┆     ┆ _ce ┆     ┆ g:  ┆     ┆ ERR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6/E ┆ ;33 ┆ E-M ┆ -23 ┆     ┆     ┆ obt ┆ TAB ┆ ntr ┆     ┆ abe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a22 ┆     ┆     │
│     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆ 607 ┆ 607 ┆     ┆     ┆ 466 ┆     ┆ 1d9 ┆     ┆ 466 ┆     ┆ ls  ┆ 270 ┆     ┆     ┆     ┆     ┆ lls ┆     ┆ hea ┆     ┆ 466 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR4 ┆ 511 ┆ TAB ┆ 68: ┆     ┆     ┆ ain ┆ -23 ┆ e   ┆     ┆ ads ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 13  ┆     ┆     │
│     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ 3/H ┆ 3/H ┆     ┆     ┆ 073 ┆     ┆ 06a ┆     ┆ 073 ┆     ┆ wer ┆ d00 ┆     ┆     ┆     ┆     ┆ _5  ┆     ┆ t   ┆     ┆ 073 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 660 ┆ ;77 ┆ -23 ┆ UTC ┆     ┆     ┆ ed  ┆ 68: ┆ for ┆     ┆ bea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆ SCh ┆ SCh ┆     ┆     ┆ /HS ┆     ┆ 9aa ┆     ┆ /ER ┆     ┆ e   ┆ 543 ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆ /ER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 73/ ┆ 11; ┆ 68: ┆ hip ┆     ┆     ┆ fro ┆ SO_ ┆ Gen ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆ ip_ ┆ ip_ ┆     ┆     ┆ Chi ┆     ┆ 237 ┆     ┆ R46 ┆     ┆ obt ┆ 166 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆ R46 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ERR ┆ 895 ┆ gro ┆ _2. ┆     ┆     ┆ m   ┆ 130 ┆ e   ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ SUM ┆     ┆     ┆     ┆     ┆     ┆ 2.f ┆ 2.f ┆     ┆     ┆ p_2 ┆     ┆ dca ┆     ┆ 607 ┆     ┆ ain ┆ 328 ┆     ┆     ┆     ┆     ┆     ┆     ┆ SUM ┆     ┆ 607 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆ 93; ┆ win ┆ fq. ┆     ┆     ┆ CRU ┆ 8_1 ┆ Reg ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ O-2 ┆     ┆     ┆     ┆     ┆     ┆ q.g ┆ q.g ┆     ┆     ┆ .fq ┆     ┆ 14b ┆     ┆ 3.f ┆     ┆ ed  ┆ c31 ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-2 ┆     ┆ 3.f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 073 ┆ 774 ┆ g_U ┆ gz  ┆     ┆     ┆ K   ┆ 308 ┆ ula ┆     ┆ rea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ ChI ┆     ┆     ┆     ┆     ┆     ┆ z   ┆ z   ┆     ┆     ┆ .gz ┆     ┆ 030 ┆     ┆ ast ┆     ┆ fro ┆ 96a ┆     ┆     ┆     ┆     ┆     ┆     ┆ ChI ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .fa ┆ 2;7 ┆ 2OS ┆     ┆     ┆     ┆ and ┆ _37 ┆ tio ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ P-s ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ vs  ┆     ┆ 582 ┆     ┆ q.g ┆     ┆ m   ┆ eb2 ┆     ┆     ┆     ┆     ┆     ┆     ┆ P-s ┆     ┆ q.g ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 776 ┆ _ce ┆     ┆     ┆     ┆ gro ┆ -2  ┆ n   ┆     ┆ _SU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ eq  ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆ ftp ┆     ┆     ┆ fas ┆     ┆ 0d0 ┆     ┆ z   ┆     ┆ CRU ┆ f87 ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq  ┆     ┆ z   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆ ;11 ┆ lls ┆     ┆     ┆     ┆ wn  ┆     ┆ and ┆     ┆ MO2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .sr ┆ .sr ┆     ┆     ┆ p.s ┆     ┆ fa  ┆     ┆ vs  ┆     ┆ K   ┆ 5e  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 757 ┆ _5  ┆     ┆     ┆     ┆ at  ┆     ┆ Exp ┆     ┆ _Ch ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a.e ┆ a.e ┆     ┆     ┆ ra. ┆     ┆     ┆     ┆ ftp ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 0;1 ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆ res ┆     ┆ IP_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bi. ┆ bi. ┆     ┆     ┆ ebi ┆     ┆     ┆     ┆ .sr ┆     ┆ gro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 175 ┆     ┆     ┆     ┆     ┆ acc ┆     ┆ sio ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆ ac. ┆     ┆     ┆ .ac ┆     ┆     ┆     ┆ a.e ┆     ┆ wn  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆ 71; ┆     ┆     ┆     ┆     ┆ ord ┆     ┆ n;U ┆     ┆ tei ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆ uk/ ┆     ┆     ┆ .uk ┆     ┆     ┆     ┆ bi. ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ 828 ┆     ┆     ┆     ┆     ┆ ing ┆     ┆ niv ┆     ┆ n G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vol ┆ vol ┆     ┆     ┆ :/v ┆     ┆     ┆     ┆ ac. ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ac ┆ 7;1 ┆     ┆     ┆     ┆     ┆ to  ┆     ┆ ers ┆     ┆ Dyn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1/r ┆ 1/r ┆     ┆     ┆ ol1 ┆     ┆     ┆     ┆ uk/ ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uk/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .uk ┆ 338 ┆     ┆     ┆     ┆     ┆ sta ┆     ┆ ity ┆     ┆ abe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ un/ ┆ un/ ┆     ┆     ┆ /ru ┆     ┆     ┆     ┆ vol ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :/v ┆ 369 ┆     ┆     ┆     ┆     ┆ nda ┆     ┆ of  ┆     ┆ ads ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ERR ┆ ERR ┆     ┆     ┆ n/E ┆     ┆     ┆     ┆ 1/f ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1/f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ ;32 ┆     ┆     ┆     ┆     ┆ rd  ┆     ┆ Dun ┆     ┆ bea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆ 466 ┆     ┆     ┆ RR4 ┆     ┆     ┆     ┆ ast ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ast ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /fa ┆ 523 ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ dee ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ER ┆ /ER ┆     ┆     ┆ 66/ ┆     ┆     ┆     ┆ q/E ┆     ┆ sta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q/E ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ ;32 ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ ;Du ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R46 ┆ R46 ┆     ┆     ┆ ERR ┆     ┆     ┆     ┆ RR4 ┆     ┆ nda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ER ┆ 524 ┆     ┆     ┆     ┆     ┆ cul ┆     ┆ nde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 607 ┆ 607 ┆     ┆     ┆ 466 ┆     ┆     ┆     ┆ 66/ ┆     ┆ rd  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R46 ┆ ;40 ┆     ┆     ┆     ┆     ┆ tur ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8/U ┆ 8/U ┆     ┆     ┆ 078 ┆     ┆     ┆     ┆ ERR ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ERR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6/E ┆ 674 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ DD1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TCh ┆ TCh ┆     ┆     ┆ /UT ┆     ┆     ┆     ┆ 466 ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR4 ┆ ;32 ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ 5EH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ip_ ┆ ip_ ┆     ┆     ┆ Chi ┆     ┆     ┆     ┆ 078 ┆     ┆ cul ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 078 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 660 ┆ 525 ┆     ┆     ┆     ┆     ┆ toc ┆     ┆ ;Un ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.f ┆ 2.f ┆     ┆     ┆ p_2 ┆     ┆     ┆     ┆ /ER ┆     ┆ tur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /ER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 78/ ┆ ;93 ┆     ┆     ┆     ┆     ┆ ols ┆     ┆ ite ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q.g ┆ q.g ┆     ┆     ┆ .fq ┆     ┆     ┆     ┆ R46 ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R46 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ERR ┆ 47; ┆     ┆     ┆     ┆     ┆ .   ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

## Concat Dataframe

- ここにある全てのデータフレームを `concat` する

In [58]:
df_chipseq_all: list[pl.DataFrame | None] = [
    paired_metadata_df_gse140053_chipseq,
    paired_metada_df_gse145525,
    paired_metada_df_gse38901,
    paired_metada_df_gse43579,
    paired_metada_df_gse62309,
    paired_metada_df_gse57398,
    paired_metada_df_gse66448,
    paired_metada_df_gse60984,
    paired_metada_df_gse105028,
    paired_metada_df_gse112379,
    paired_metada_df_gse121182,
    paired_metada_df_gse137558,
    paired_metada_df_gse152144,
    paired_metada_df_gse143591,
    paired_metada_df_gse194364,
    paired_metada_df_gse166456,
    paired_metada_df_gse209667,
    paired_metada_df_gse270671,
    paired_metada_df_gse253873,
    paired_metada_df_gse259305,
    paired_metada_df_gse276302,
    paired_metada_df_gse303857,
    paired_metada_df_prjna369311_chipseq,
    paired_metada_df_prjeb5930_chipseq
]

dfs_chipseq:  list[pl.DataFrame] = [df for df in df_chipseq_all if df is not None]

In [59]:
chipseq_concat = pl.concat(dfs_chipseq, how="diagonal")

chipseq_concat.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/chipseq_metadata_all_{execute_date}.tsv",
    separator='\t'
)

In [60]:
dfs_chipseq_histone_modification_all: list[pl.DataFrame | None] = [
    paired_metada_df_gse89382_histone_modification,
    paired_metada_df_gse105028_histone_modification,
    paired_metada_df_gse209667_histone_modification,
    paired_metada_df_gse276302_histone_modification
]

dfs_chipseq_histone_modification: list[pl.DataFrame] = [df for df in dfs_chipseq_histone_modification_all if df is not None]

chipseq_histone_modification_concat = pl.concat(dfs_chipseq_histone_modification, how="diagonal")

chipseq_histone_modification_concat.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/chipseq_histone_modification_metadata_all_{execute_date}.tsv",
    separator='\t'
)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### ChIP-seq ではないが、熱ストレス条件下のデータを活用している エピゲノムデータ

- 使用できるかわからないものの、念のためこちらに記載する

&nbsp;

## GSE192370 (CUT&TAG)

In [61]:
# GSE192370_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE192370/GSE192370_PEP/GSE192370_PEP_raw.csv",
#     separator=','
# )

# display(GSE192370_PEP)

&nbsp;

&nbsp;

## 2. GSE326102 (CUT&Run)

In [62]:
# GSE326102_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE326102/GSE326102_PEP/GSE326102_PEP_raw.csv",
#     separator=','
# )

# display(GSE326102_PEP)