&nbsp;

# Other Sequencing related Metadata validated and Modified Process

- bulk RNA-seqを主に使用してきたが、CAGEなどの他のsequencing データも活用する方針なので、別途 こちらに記載するようにする
- 熱ストレス条件下のデータと、コントロール条件下のデータがプロジェクト内で取得でき、かつbulk RNA-seq以外のデータ
- ただし、ChIP-seqなどのデータは、別の notebook に記載している

&nbsp;

---

&nbsp;

- While bulk RNA-sequencing (RNA-seq) has been the primary methodology employed, other sequencing modalities such as Cap Analysis of Gene Expression (CAGE) will also be utilized; therefore, these shall be documented separately herein.
- This pertains to data acquired under both heat-stress and control conditions within the project, specifically excluding bulk RNA-seq data.
- However, data types such as Chromatin Immunoprecipitation Sequencing (ChIP-seq) are documented in a separate notebook.

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 260929

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE165367 (SINGLE) 4sU-seq 

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (4sU-RNA標識法)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する
- [12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から移動

&nbsp;

#### sample discription from PEP format csv

- `ctrl_4SU.mRNA-seq_rep3`
- `HS_4SU.mRNA-seq_rep1`

In [4]:
GSE165367_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE165367/GSE165367_PEP/GSE165367_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep kit").alias("rna_library"), # add rna_library column (Roche)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("135 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE165367 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE165367_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE165367_filtered = GSE165367[[s.name for s in GSE165367 if not (s.null_count() == GSE165367.height)]]

# display(GSE165367_PEP)

In [5]:
GSE165367_combined = GSE165367_PEP.join(
    GSE165367_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE165367_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE165367_modified_metadata.tsv",
    separator='\t'
)

# display(GSE165367_combined)

In [6]:
# Manual defined pairs
defined_pairs_gse165367_4sU_seq = [
    ("SRR13510346", "SRR13510343"), # heat-stress sample vs control sample
    ("SRR13510347", "SRR13510344"), # heat-stress sample vs control sample
    ("SRR13510348", "SRR13510345") # heat-stress sample vs control sample
]

paired_metadata_df_gse165367_4sU_seq = create_paired_metadata(
    combined_df=GSE165367_combined, 
    defined_sample_pairs=defined_pairs_gse165367_4sU_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)


if paired_metadata_df_gse165367_4sU_seq is not None:
    paired_metadata_df_gse165367_4sU_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE165367_4sU_seq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse165367_4sU_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

# display(paired_metadata_df_gse165367_4sU_seq)

shape: (3, 83)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR135103 ┆ SRR135103 ┆ hs_4su_mr ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809862 ┆ 2022-01-2 ┆ GSE165367 │
│ 46        ┆ 43        ┆ na-seq_re ┆          ┆   ┆ 64        ┆ 7 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ p1 vs ctr ┆          ┆   ┆           ┆ 098624    ┆           ┆           │
│           ┆           ┆ l_4su_mrn ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ a-seq_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 1         ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR135103 ┆ SRR135103 ┆ hs_4su_mr ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809862 ┆ 2022-01-2 ┆ GSE165367 │
│ 47        ┆ 44        ┆ na-seq_re ┆          ┆   ┆ 64        ┆ 8 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ p2 vs ctr ┆          ┆   ┆           ┆ 098625    ┆           ┆           │
│           ┆           ┆ l_4su_mrn ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ a-seq_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 2         ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR135103 ┆ SRR135103 ┆ hs_4su_mr ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809862 ┆ 2022-01-2 ┆ GSE165367 │
│ 48        ┆ 45        ┆ na-seq_re ┆          ┆   ┆ 64        ┆ 9 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ p3 vs ctr ┆          ┆   ┆           ┆ 098626    ┆           ┆           │
│           ┆           ┆ l_4su_mrn ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ a-seq_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 3         ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE165364 (SINGLE) TTchem-seq 

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (TTchem-seq)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- しかしながら、nacsent RNA のバイアスを考慮できているかが気になるので後でまた使用するかどうか検討する
- [Using TTchem-seq for profiling nascent transcription and measuring transcript elongation](https://doi.org/10.1038/s41596-019-0262-3) などの論文を見ると、STARのマッピングなどを使用しているため、おそらく発現定量の方法はRNA-seqと同じ？
- 120分の実験を行ったあと、追加で30,60,120min.の実験をしている
- 異なるペアで熱ストレスの条件が異なるので後で手入力
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から処理を移動

&nbsp;

#### sample discription from PEP format csv

- `mrc5va_ctrl_ttchem-seq_rep1`
- `mrc5va_hs120min_ttchem-seq_rep1`
- ...

In [7]:
GSE165364_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE165364/GSE165364_PEP/GSE165364_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep kit").alias("rna_library"), # add rna_library column (Roche)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    # pl.lit("unknown").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE165364 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE165364_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE165364_filtered = GSE165364[[s.name for s in GSE165364 if not (s.null_count() == GSE165364.height)]]

# display(GSE165364_PEP)

In [8]:
GSE165364_combined = GSE165364_PEP.join(
    GSE165364_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE165364_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE165364_modified_metadata.tsv",
    separator='\t'
)

# display(GSE165364_combined)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE165366 (SINGLE) FP-TTchem-seq 

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

<!-- &nbsp; -->

- validate date 2025-04-29
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用したデータ (FP:Flavopiridol.TTchem-seq)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- しかしながら、nacsent RNA のバイアスを考慮できているかがきになるので後でまた使用するかどうか検討する
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から処理を移動

#### sample discription from PEP format csv

- `2h HS, followed by 15min of treatment with 300nM Flavopiridol (including 10 min 1mM 4-thiouridine pulse)`
- `2h HS, followed by 20min of treatment with 300nM Flavopiridol (including 10 min 1mM 4-thiouridine pulse)`
- ...

In [9]:
GSE165366_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE165366/GSE165366_PEP/GSE165366_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep kit").alias("rna_library"), # add rna_library column (Roche)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE165366 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE165366_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE165366_filtered = GSE165366[[s.name for s in GSE165366 if not (s.null_count() == GSE165366.height)]]

# display(GSE165366_PEP)

In [10]:
GSE165366_combined = GSE165366_PEP.join(
    GSE165366_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE165366_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE165366_modified_metadata.tsv",
    separator='\t'
)

# display(GSE165366_combined)

In [11]:
# Manual defined pairs
defined_pairs_gse165366_fp_ttchem_seq = [
    ("SRR13510331", "SRR13510319"), # heat-stress sample vs control sample
    ("SRR13510332", "SRR13510320"), # heat-stress sample vs control sample
    ("SRR13510333", "SRR13510321"), # heat-stress sample vs control sample
    ("SRR13510334", "SRR13510322"), # heat-stress sample vs control sample
    ("SRR13510335", "SRR13510323"), # heat-stress sample vs control sample
    ("SRR13510336", "SRR13510324"), # heat-stress sample vs control sample
    ("SRR13510337", "SRR13510325"), # heat-stress sample vs control sample
    ("SRR13510338", "SRR13510326"), # heat-stress sample vs control sample
    ("SRR13510339", "SRR13510327"), # heat-stress sample vs control sample
    ("SRR13510340", "SRR13510328"), # heat-stress sample vs control sample
    ("SRR13510341", "SRR13510329"), # heat-stress sample vs control sample
    ("SRR13510342", "SRR13510330")  # heat-stress sample vs control sample
]

paired_metadata_df_gse165366_fp_ttchem_seq = create_paired_metadata(
    combined_df=GSE165366_combined, 
    defined_sample_pairs=defined_pairs_gse165366_fp_ttchem_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse165366_fp_ttchem_seq is not None:
    paired_metadata_df_gse165366_fp_ttchem_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE165366_fp_ttchem_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse165366_fp_ttchem_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 83)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR135103 ┆ SRR135103 ┆ hs_fp_ttc ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809861 ┆ 2022-01-2 ┆ GSE165366 │
│ 31        ┆ 19        ┆ hem-seq_r ┆          ┆   ┆ 65        ┆ 1 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ ep1 vs    ┆          ┆   ┆           ┆ 098601    ┆           ┆           │
│           ┆           ┆ ctrl_fp_t ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tchem-seq ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep1     ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR135103 ┆ SRR135103 ┆ hs_fp_ttc ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809861 ┆ 2022-01-2 ┆ GSE165366 │
│ 32        ┆ 20        ┆ hem-seq_1 ┆          ┆   ┆ 65        ┆ 3 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ 5min_fp_r ┆          ┆   ┆           ┆ 098600    ┆           ┆           │
│           ┆           ┆ ep1 vs    ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ctrl_fp_t ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tchem-seq ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _15min_fp ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep1     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR135103 ┆ SRR135103 ┆ hs_fp_ttc ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809862 ┆ 2022-01-2 ┆ GSE165366 │
│ 41        ┆ 29        ┆ hem-seq_3 ┆          ┆   ┆ 65        ┆ 2 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ 0min_fp_r ┆          ┆   ┆           ┆ 098610    ┆           ┆           │
│           ┆           ┆ ep2 vs    ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ctrl_fp_t ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tchem-seq ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _30min_fp ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep2     ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR135103 ┆ SRR135103 ┆ hs_fp_ttc ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809862 ┆ 2022-01-2 ┆ GSE165366 │
│ 42        ┆ 30        ┆ hem-seq_4 ┆          ┆   ┆ 65        ┆ 3 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ 0min_fp_r ┆          ┆   ┆           ┆ 098612    ┆           ┆           │
│           ┆           ┆ ep2 vs    ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ctrl_fp_t ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tchem-seq ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _40min_fp ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep2     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE140053 (SINGLE) SLAM-seq

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validation date: 2025-04-29
- [Stress-induced nuclear condensation of NELF drives transcriptional downregulation](https://doi.org/10.1016/j.molcel.2021.01.016)
- これも以前の研究で使用したデータ (SLAM-seq)
- 定量できるかわからないが、これも集めよう...
- ChiP-seqのデータは取り除く ([./12_8_metadata_chipseq.ipynb](./12_8_metadata_chipseq.ipynb) で処理)
- `hs_nelfa_didr_rep3` のデータがないので、ペアとなる`nhs_nelfa_wt_rep3` は今回は使用しない
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から移動

In [12]:
GSE140053_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE140053/GSE140053_PEP/GSE140053_PEP_raw.csv",
    separator=','
).filter(
    pl.col("protocol").str.contains(r'other') # remove ChIP-seq data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Quantseq 3’ mRNA-Seq Library Prep Kit").alias("rna_library"), # add rna_library column (Lexogen)
    pl.lit("https://doi.org/10.1016/j.molcel.2021.01.016").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
)

# metadata from iseq
GSE140053 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE140053_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE140053_filtered = GSE140053[[s.name for s in GSE140053 if not (s.null_count() == GSE140053.height)]]

# display(GSE140053_PEP)

In [13]:
GSE140053_combined = GSE140053_PEP.join(
    GSE140053_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE140053_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE140053_modified_slam_seq_metadata.tsv",
    separator='\t'
)

# display(GSE140053_combined)

In [14]:
# Manual defined pairs
defined_pairs_gse140053 = [
    ("SRR11067753", "SRR11067765"),
    ("SRR11067754", "SRR11067766"),
    ("SRR11067755", "SRR11067767"),
    ("SRR11067756", "SRR11067768"),
    ("SRR11067757", "SRR11067769"),
    ("SRR11067758", "SRR11067770"),
    ("SRR12801710", "SRR12801715"),
    ("SRR12801711", "SRR12801716"),
    ("SRR12801712", "SRR12801718"),
    ("SRR12801713", "SRR12801719"),
    ("SRR12801714", "SRR12801720") 
]

paired_metadata_df_gse140053_slam_seq = create_paired_metadata(
    combined_df=GSE140053_combined, 
    defined_sample_pairs=defined_pairs_gse140053,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse140053_slam_seq is not None:
    paired_metadata_df_gse140053_slam_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE140053_slam_seq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse140053_slam_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

# display(paired_metadata_df_gse140053_slam_seq)

shape: (11, 89)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR110677 ┆ SRR110677 ┆ hela_hs_s ┆ other    ┆ … ┆ PRJNA5880 ┆ SRS613172 ┆ 2021-02-0 ┆ GSE140053 │
│ 53        ┆ 65        ┆ iscr_slam ┆          ┆   ┆ 93        ┆ 6 vs SRS6 ┆ 7         ┆           │
│           ┆           ┆ -seq_rep1 ┆          ┆   ┆           ┆ 131738    ┆           ┆           │
│           ┆           ┆ vs hela_n ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ hs_siscr_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ slam-seq_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rep1      ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR110677 ┆ SRR110677 ┆ hela_hs_s ┆ other    ┆ … ┆ PRJNA5880 ┆ SRS613172 ┆ 2021-02-0 ┆ GSE140053 │
│ 54        ┆ 66        ┆ iscr_slam ┆          ┆   ┆ 93        ┆ 7 vs SRS6 ┆ 7         ┆           │
│           ┆           ┆ -seq_rep2 ┆          ┆   ┆           ┆ 131739    ┆           ┆           │
│           ┆           ┆ vs hela_n ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ hs_siscr_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ slam-seq_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rep2      ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR128017 ┆ SRR128017 ┆ hs_nelfa_ ┆ other    ┆ … ┆ PRJNA5880 ┆ SRS749941 ┆ 2021-02-0 ┆ GSE140053 │
│ 13        ┆ 19        ┆ wt_rep2   ┆          ┆   ┆ 93        ┆ 3 vs SRS7 ┆ 7         ┆           │
│           ┆           ┆ vs nhs_ne ┆          ┆   ┆           ┆ 499419    ┆           ┆           │
│           ┆           ┆ lfa_wt_re ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ p2        ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR128017 ┆ SRR128017 ┆ hs_nelfa_ ┆ other    ┆ … ┆ PRJNA5880 ┆ SRS749941 ┆ 2021-02-0 ┆ GSE140053 │
│ 14        ┆ 20        ┆ wt_rep3   ┆          ┆   ┆ 93        ┆ 4 vs SRS7 ┆ 7         ┆           │
│           ┆           ┆ vs nhs_ne ┆          ┆   ┆           ┆ 499420    ┆           ┆           │
│           ┆           ┆ lfa_wt_re ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ p3        ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE233555 Ribo-Calibration (PAIRED)

- validation date: 2025-05-02
- [Calibrated ribosome profiling assesses the dynamics of ribosomal flux on transcripts](https://doi.org/10.1038/s41467-024-51258-0)
- 
- `For heat shock treatment, HEK293 cells cultured in 6-well plates were transferred to a water bath set at 43 °C and incubated for 0.5, 1, or 2 h. For recovery experiments, cells were returned to 37 °C and cultured for 0.5, 1, or 4 h.`
- リボソームのプロファイリング手法に関連する研究
- Homo sapiens のRNA-seqのデータを取得
- おそらく `RNA_HS...` で始まるデータが関連しているのでフィルタリング
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から処理を移動

In [15]:
GSE233555_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE233555/GSE233555_PEP/GSE233555_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_organism_ch1") == "Homo sapiens") &
    (pl.col("sample_library_strategy") == "RNA-Seq") &
    (pl.col("sample_title").str.contains(r'RNA_HS_')) # filter Heat-stress related RNA-sequencing Data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded mRNA Library Prep Kit").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1038/s41467-024-51258-0").alias("reference_doi"), # add DOI of the reference paper column (Nature Communications)
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    # pl.lit("30 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE233555 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE233555_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE233555_filtered = GSE233555[[s.name for s in GSE233555 if not (s.null_count() == GSE233555.height)]]

# display(GSE233555_PEP)

In [16]:
GSE233555_combined = GSE233555_PEP.join(
    GSE233555_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE233555_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE233555_ribo_calibration_modified_metadata.tsv",
    separator='\t'
)

# display(GSE233555_combined)

In [17]:
# Manual defined pairs
defined_pairs_gse233555 = [
    ("SRR24746782", "SRR24746784"), # RNA_HS_0.5h vs RNA_HS_CT1
    ("SRR24746781", "SRR24746784"), # RNA_HS_1h vs RNA_HS_CT1
    ("SRR24746780", "SRR24746784"), # RNA_HS_2h vs RNA_HS_CT1
    ("SRR24746763", "SRR24746783"), # RNA_HS_2_0.5h vs RNA_HS_CT2
    ("SRR24746762", "SRR24746783"), # RNA_HS_2_1h vs RNA_HS_CT2
    ("SRR24746761", "SRR24746783")  # RNA_HS_2_4h vs RNA_HS_CT2
]

paired_metadata_df_gse233555_ribo_calibration = create_paired_metadata(
    combined_df=GSE233555_combined, 
    defined_sample_pairs=defined_pairs_gse233555,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse233555_ribo_calibration is not None:

    paired_metadata_df_gse233555_ribo_calibration.write_csv(
        "../../Data/metadata/metadata_paired/GSE233555_ribo_calibration_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse233555_ribo_calibration)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 96)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ secondary ┆ first_pub ┆ study_ali ┆ tissue_ty │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ _sample_a ┆ lic       ┆ as        ┆ pe        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ccession  ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ ---       ┆ str       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR247467 ┆ SRR247467 ┆ rna_hs_0_ ┆ null     ┆ … ┆ SRS178334 ┆ 2024-07-1 ┆ GSE233555 ┆ cultures  │
│ 82        ┆ 84        ┆ 5 vs rna_ ┆          ┆   ┆ 92 vs SRS ┆ 1         ┆           ┆           │
│           ┆           ┆ hs_ct1    ┆          ┆   ┆ 17833490  ┆           ┆           ┆           │
│ SRR247467 ┆ SRR247467 ┆ rna_hs_1  ┆ null     ┆ … ┆ SRS178334 ┆ 2024-07-1 ┆ GSE233555 ┆ cultures  │
│ 81        ┆ 84        ┆ vs rna_hs ┆          ┆   ┆ 95 vs SRS ┆ 1         ┆           ┆           │
│           ┆           ┆ _ct1      ┆          ┆   ┆ 17833490  ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR247467 ┆ SRR247467 ┆ rna_hs_2_ ┆ null     ┆ … ┆ SRS178335 ┆ 2024-07-1 ┆ GSE233555 ┆ cultures  │
│ 62        ┆ 83        ┆ 1 vs rna_ ┆          ┆   ┆ 12 vs SRS ┆ 1         ┆           ┆           │
│           ┆           ┆ hs_ct2    ┆          ┆   ┆ 17833491  ┆           ┆           ┆           │
│ SRR247467 ┆ SRR247467 ┆ rna_hs_2_ ┆ null     ┆ … ┆ SRS178335 ┆ 2024-07-1 ┆ GSE233555 ┆ cultures  │
│ 61        ┆ 83        ┆ 4 vs rna_ ┆          ┆   ┆ 13 vs SRS ┆ 1         ┆           ┆           │
│           ┆           ┆ hs_ct2    ┆          ┆   ┆ 17833491  ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE124609 (SINGLE) Ribo-seq

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validate date 2025-04-29
- [Cellular proteostasis decline in human senescence](https://doi.org/10.1073/pnas.2018138117)
- コントロールと熱ストレス条件のデータが存在するため、すべてのデータを使用する予定...
- Ribo-seqのデータの処理を[./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から移動

#### sample discription from PEP format csv

- `Young1_RNA_Seq`
- `Young_HS1_RNA_Seq`
- ...

In [18]:
GSE124609_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE124609/GSE124609_PEP/GSE124609_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina kit (TruSeq RNA)").alias("rna_library"), # add rna_library column (Illumina: from Article)
    pl.lit("https://doi.org/10.1073/pnas.2018138117").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("44 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# ribo-seq
GSE124609_PEP_ribo_seq = GSE124609_PEP.filter(
    pl.col("sample_name").str.contains(r'ribo_seq')
)


# metadata from iseq
GSE124609 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE124609_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE124609_filtered = GSE124609[[s.name for s in GSE124609 if not (s.null_count() == GSE124609.height)]]

# display(GSE124609_PEP_rna_seq)
# display(GSE124609_PEP_ribo_seq)

In [19]:
GSE124609_ribo_seq_combined = GSE124609_PEP_ribo_seq.join(
    GSE124609_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE124609_ribo_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE124609_ribo_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE124609_ribo_seq_combined)

In [20]:
# Manual defined pairs
defined_pairs_gse124609_ribo_seq = [
    ("SRR8392707", "SRR8392705"),
    ("SRR8392708", "SRR8392706"),
    ("SRR8392711", "SRR8392709"),
    ("SRR8392712", "SRR8392710")
]

paired_metadata_df_gse124609_ribo_seq = create_paired_metadata(
    combined_df=GSE124609_ribo_seq_combined, 
    defined_sample_pairs=defined_pairs_gse124609_ribo_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse124609_ribo_seq is not None:
    paired_metadata_df_gse124609_ribo_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE124609_paired_ribo_seq_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse124609_ribo_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 88)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR839270 ┆ SRR839270 ┆ young_hs1 ┆ cDNA     ┆ … ┆ PRJNA5128 ┆ SRS420756 ┆ 2021-01-0 ┆ GSE124609 │
│ 7         ┆ 5         ┆ _ribo_seq ┆          ┆   ┆ 37        ┆ 9 vs SRS4 ┆ 4         ┆           │
│           ┆           ┆ vs young1 ┆          ┆   ┆           ┆ 207567    ┆           ┆           │
│           ┆           ┆ _ribo_seq ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR839270 ┆ SRR839270 ┆ young_hs2 ┆ cDNA     ┆ … ┆ PRJNA5128 ┆ SRS420757 ┆ 2021-01-0 ┆ GSE124609 │
│ 8         ┆ 6         ┆ _ribo_seq ┆          ┆   ┆ 37        ┆ 0 vs SRS4 ┆ 4         ┆           │
│           ┆           ┆ vs young2 ┆          ┆   ┆           ┆ 207568    ┆           ┆           │
│           ┆           ┆ _ribo_seq ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR839271 ┆ SRR839270 ┆ senescent ┆ cDNA     ┆ … ┆ PRJNA5128 ┆ SRS420757 ┆ 2021-01-0 ┆ GSE124609 │
│ 1         ┆ 9         ┆ _hs1_ribo ┆          ┆   ┆ 37        ┆ 3 vs SRS4 ┆ 4         ┆           │
│           ┆           ┆ _seq vs   ┆          ┆   ┆           ┆ 207571    ┆           ┆           │
│           ┆           ┆ senescent ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 1_ribo_se ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ q         ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR839271 ┆ SRR839271 ┆ senescent ┆ cDNA     ┆ … ┆ PRJNA5128 ┆ SRS420757 ┆ 2021-01-0 ┆ GSE124609 │
│ 2         ┆ 0         ┆ _hs2_ribo ┆          ┆   ┆ 37        ┆ 4 vs SRS4 ┆ 4         ┆           │
│           ┆           ┆ _seq vs   ┆          ┆   ┆           ┆ 207572    ┆           ┆           │
│           ┆           ┆ senescent ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 2_ribo_se ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ q         ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE32060 (SINGLE) Ribo-seq

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validation date: 2025-05-02
- [Widespread Regulation of Translation by Elongation Pausing in Heat Shock](https://doi.org/10.1016/j.molcel.2012.11.028)
- 以前の研究でも使用した研究
- ペアごとに熱ストレスの条件に違うので、後で手入力
- [./12_1_metadata_modified_true_control.ipynb](./12_1_metadata_modified_true_control.ipynb)から処理を移動

In [21]:
GSE32060_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE32060/GSE32060_PEP/GSE32060_PEP_raw.csv",
    separator=','
).filter(
    pl.col("organism") == "Homo sapiens"
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1016/j.molcel.2012.11.028").alias("reference_doi"), # add DOI of the reference paper column
    # pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    # pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE32060 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE32060_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE32060_filtered = GSE32060[[s.name for s in GSE32060 if not (s.null_count() == GSE32060.height)]]

# display(GSE32060_PEP)

In [22]:
GSE32060_combined = GSE32060_PEP.join(
    GSE32060_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE32060_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE32060_ribo_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE32060_combined)

In [23]:
# Manual defined pairs
defined_pairs_gse32060 = [
    ("SRR648668", "SRR648667"),
    ("SRR648670", "SRR648669")
]

paired_metadata_df_gse32060_ribo_seq = create_paired_metadata(
    combined_df=GSE32060_combined, 
    defined_sample_pairs=defined_pairs_gse32060,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse32060_ribo_seq is not None:
    paired_metadata_df_gse32060_ribo_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE32060_ribo_seq_paired_metadata.tsv",
        separator='\t'
    )

    display(paired_metadata_df_gse32060_ribo_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 81)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR648668 ┆ SRR648667 ┆ 293t_gfp_ ┆ other    ┆ … ┆ PRJNA1476 ┆ SRS385796 ┆ 2013-01-3 ┆ GSE32060  │
│           ┆           ┆ 2hrs_seve ┆          ┆   ┆ 13        ┆ vs        ┆ 0         ┆           │
│           ┆           ┆ re_heat_s ┆          ┆   ┆           ┆ SRS385795 ┆           ┆           │
│           ┆           ┆ hock vs   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 293t_gfp  ┆          ┆   ┆           ┆           ┆           ┆           │
│ SRR648670 ┆ SRR648669 ┆ 293t_hspa ┆ other    ┆ … ┆ PRJNA1476 ┆ SRS385798 ┆ 2013-01-3 ┆ GSE32060  │
│           ┆           ┆ 1a_2hrs_s ┆          ┆   ┆ 13        ┆ vs        ┆ 0         ┆           │
│           ┆           ┆ evere_hea ┆          ┆   ┆           ┆ SRS385797 ┆           ┆           │
│           ┆           ┆ t_shock   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ vs 293t_h ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ spa1a     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE234710 (PAIRED) (BRB-seq)

- ✅ DOWNLOAD
- ✅ TRIMMING
- ✅ QUANTIFICATION

&nbsp;

- validate date: 2025-05-03
- validate date: 2026-05-04
- Bulk RNA barcoding sequencing (BRB) という手法だが、メタデータを見ると、`RNA-Seq` となっている
- [Transcriptional landscape of human keratinocyte models exposed to 60-GHz millimeter-waves](https://doi.org/10.1016/j.tiv.2024.105808)
- `Sham unexposed cells(Sham)`, `millimeter waves (MMW) exposed Cells (Expo)`, `heat shock control (HSC)`の3つの実験条件 + `HEK, NHEK, HaCaT` の3つの細胞種の条件
- 温度条件は論文の [Table 1](https://www.sciencedirect.com/science/article/pii/S0887233324000389?via%3Dihub#t0005), Table 3 に記載されている
- `sham` は 36℃前後であることから、これをコントロールとして使用できると考えられる
- ~~熱を加えている、という側面があるため、全てのデータを使用する~~
- **`heat shock control (HSC)` と `sham` のみ 収集する方針に転換**
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から移動

In [24]:
GSE234710_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE234710/GSE234710_PEP/GSE234710_PEP_raw.csv",
    separator=','
).filter(
    (~pl.col("sample_title").str.contains("Expo"))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column from GEO webpage
    pl.lit("https://doi.org/10.1016/j.tiv.2024.105808").alias("reference_doi"), # add DOI of the reference paper column

    # stress treatment temperature
    pl.when(
        (pl.col("sample_name").str.contains("hacat_3h_hsc_5"))
    ).then(
        pl.lit("36.55 ± 0.53 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hacat_3h_hsc_10_"))
    ).then(
        pl.lit("38.78 ± 0.95 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hacat_3h_hsc_20_"))
    ).then(
        pl.lit("40.82 ± 0.67 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hacat_on_hsc_10_"))
    ).then(
        pl.lit("38.87 ± 0.7 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hek3n_3h_hsc_20_"))
    ).then(
        pl.lit("40.8 ± 0.38 C") # Table 1
    ).when(
        (pl.col("sample_name").str.contains("nhek_3h_hsc_20_"))
    ).then(
        pl.lit("40.9 ± 0.2 C") # Table 1
    ).otherwise(
        pl.lit(None)
    ).alias("stress treatment temperature"),

    # stress treatment time
    pl.when(
        (pl.col("sample_name").str.contains("_3h_"))
    ).then(
        pl.lit("180 min.") # 3h.
    ).when(
        (pl.col("sample_name").str.contains("_on_"))
    ).then(
        pl.lit("840 min.") # 14h.
    ).otherwise(
        pl.lit(None)
    ).alias("stress treatment time"),

    # control treatment temperature
    pl.when(
        (pl.col("sample_name").str.contains("hacat_3h_sham_"))
    ).then(
        pl.lit("35.1 ± 0.39 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hacat_on_sham_"))
    ).then(
        pl.lit("35.77 ± 0.23 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("hek3n_3h_sham_"))
    ).then(
        pl.lit("35.9 ± 0.2 C") # Table 3
    ).when(
        (pl.col("sample_name").str.contains("nhek_3h_sham_"))
    ).then(
        pl.lit("36.2 ± 0.24 C") # Table 3
    ).otherwise(
        pl.lit(None)
    ).alias("control treatment temperature")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE234710_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE234710_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE234710_iseq_filtered = GSE234710_iseq[[s.name for s in GSE234710_iseq if not (s.null_count() == GSE234710_iseq.height)]]

GSE234710_combined = GSE234710_PEP.join(
    GSE234710_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE234710_combined = GSE234710_combined[[s.name for s in GSE234710_combined if not (s.null_count() == GSE234710_combined.height)]]

GSE234710_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE234710_modified_metadata.tsv",
    separator='\t'
)

pl.Config.set_tbl_rows(2)
display(GSE234710_combined)

shape: (38, 80)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_na ┆ sample_ti ┆ sample_ge ┆ sample_st ┆ … ┆ accession ┆ secondary ┆ first_pub ┆ study_al │
│ me        ┆ tle       ┆ o_accessi ┆ atus      ┆   ┆ ---       ┆ _sample_a ┆ lic       ┆ ias      │
│ ---       ┆ ---       ┆ on        ┆ ---       ┆   ┆ str       ┆ ccession  ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆           ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hacat_3h_ ┆ HaCaT,    ┆ GSM747359 ┆ Public on ┆ … ┆ SRR248997 ┆ SRS179585 ┆ 2024-06-2 ┆ GSE23471 │
│ hsc_10_r2 ┆ 3H, HSC   ┆ 9         ┆ Jun 20    ┆   ┆ 79        ┆ 85        ┆ 2         ┆ 0        │
│           ┆ 10, R2    ┆           ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ nhek_3h_s ┆ NHEK, 3H, ┆ GSM747364 ┆ Public on ┆ … ┆ SRR248997 ┆ SRS179586 ┆ 2024-06-2 ┆ GSE23471 │
│ ham_0_r3  ┆ Sham 0,   ┆ 7         ┆ Jun 20    ┆   ┆ 31        ┆ 31        ┆ 2         ┆ 0        │
│           ┆ R3        ┆           ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
defined_pairs_gse234710 = [
    # HaCat cell line (Human keratinocyte cell line)
    # HaCaT cells were exposed either on MMW gradient 5 to 20 mW/cm² during 3 hours or 10 MW/cm² during 14 hours.
    # ("SRR24899791", "SRR24899764"), # hacat_3h_expo_10_r1 vs hacat_3h_sham_0_r1
    # ("SRR24899788", "SRR24899765"), # hacat_3h_expo_10_r2 vs hacat_3h_sham_0_r2
    # ("SRR24899789", "SRR24899766"), # hacat_3h_expo_10_r3 vs hacat_3h_sham_0_r3
    # ("SRR24899790", "SRR24899767"), # hacat_3h_expo_10_r4 vs hacat_3h_sham_0_r4
    # ("SRR24899785", "SRR24899764"), # hacat_3h_expo_20_r1 vs hacat_3h_sham_0_r1
    # ("SRR24899786", "SRR24899765"), # hacat_3h_expo_20_r2 vs hacat_3h_sham_0_r2
    # ("SRR24899787", "SRR24899766"), # hacat_3h_expo_20_r3 vs hacat_3h_sham_0_r3
    # ("SRR24899784", "SRR24899767"), # hacat_3h_expo_20_r4 vs hacat_3h_sham_0_r4
    # ("SRR24899780", "SRR24899764"), # hacat_3h_expo_5_r1 vs hacat_3h_sham_0_r1
    # ("SRR24899781", "SRR24899765"), # hacat_3h_expo_5_r2 vs hacat_3h_sham_0_r2
    # ("SRR24899782", "SRR24899766"), # hacat_3h_expo_5_r3 vs hacat_3h_sham_0_r3
    # ("SRR24899783", "SRR24899767"), # hacat_3h_expo_5_r4 vs hacat_3h_sham_0_r4
    # heat exposed to a temperature equivalent to those reached during the MMW exposure.
    ("SRR24899778", "SRR24899764"), # hacat_3h_hsc_10_r1 vs hacat_3h_sham_0_r1
    ("SRR24899779", "SRR24899765"), # hacat_3h_hsc_10_r2 vs hacat_3h_sham_0_r2
    ("SRR24899776", "SRR24899766"), # hacat_3h_hsc_10_r3 vs hacat_3h_sham_0_r3
    ("SRR24899777", "SRR24899767"), # hacat_3h_hsc_10_r4 vs hacat_3h_sham_0_r4
    ("SRR24899772", "SRR24899764"), # hacat_3h_hsc_20_r1 vs hacat_3h_sham_0_r1
    ("SRR24899773", "SRR24899765"), # hacat_3h_hsc_20_r2 vs hacat_3h_sham_0_r2
    ("SRR24899774", "SRR24899766"), # hacat_3h_hsc_20_r3 vs hacat_3h_sham_0_r3
    ("SRR24899775", "SRR24899767"), # hacat_3h_hsc_20_r4 vs hacat_3h_sham_0_r4
    ("SRR24899768", "SRR24899764"), # hacat_3h_hsc_5_r1 vs hacat_3h_sham_0_r1
    ("SRR24899769", "SRR24899765"), # hacat_3h_hsc_5_r2 vs hacat_3h_sham_0_r2
    ("SRR24899770", "SRR24899766"), # hacat_3h_hsc_5_r3 vs hacat_3h_sham_0_r3
    ("SRR24899771", "SRR24899767"), # hacat_3h_hsc_5_r4 vs hacat_3h_sham_0_r4
    # ("SRR24899762", "SRR24899755"), # hacat_on_expo_10_r1 vs hacat_on_sham_0_r1
    # ("SRR24899760", "SRR24899753"), # hacat_on_expo_10_r2 vs hacat_on_sham_0_r2
    # ("SRR24899763", "SRR24899752"), # hacat_on_expo_10_r3 vs hacat_on_sham_0_r3
    # ("SRR24899761", "SRR24899754"), # hacat_on_expo_10_r4 vs hacat_on_sham_0_r4
    ("SRR24899758", "SRR24899755"), # hacat_on_hsc_10_r1 vs hacat_on_sham_0_r1
    ("SRR24899756", "SRR24899753"), # hacat_on_hsc_10_r2 vs hacat_on_sham_0_r2
    ("SRR24899759", "SRR24899752"), # hacat_on_hsc_10_r3 vs hacat_on_sham_0_r3
    ("SRR24899757", "SRR24899754"), # hacat_on_hsc_10_r4 vs hacat_on_sham_0_r4
    # HEK3N cell line
    # ("SRR24899750", "SRR24899743"), # hek3n_3h_expo_20_r1 vs hek3n_3h_sham_0_r1
    # ("SRR24899748", "SRR24899741"), # hek3n_3h_expo_20_r2 vs hek3n_3h_sham_0_r2
    # ("SRR24899751", "SRR24899740"), # hek3n_3h_expo_20_r3 vs hek3n_3h_sham_0_r3
    # ("SRR24899749", "SRR24899742"), # hek3n_3h_expo_20_r4 vs hek3n_3h_sham_0_r4
    ("SRR24899746", "SRR24899743"), # hek3n_3h_hsc_20_r1 vs hek3n_3h_sham_0_r1
    ("SRR24899744", "SRR24899741"), # hek3n_3h_hsc_20_r2 vs hek3n_3h_sham_0_r2
    ("SRR24899747", "SRR24899740"), # hek3n_3h_hsc_20_r3 vs hek3n_3h_sham_0_r3
    ("SRR24899745", "SRR24899742"), # hek3n_3h_hsc_20_r4 vs hek3n_3h_sham_0_r4
    # NHEK cell line
    # ("SRR24899739", "SRR24899733"), # nhek_3h_expo_20_r1 vs nhek_3h_sham_0_r1
    # ("SRR24899738", "SRR24899732"), # nhek_3h_expo_20_r2 vs nhek_3h_sham_0_r2
    # ("SRR24899737", "SRR24899731"), # nhek_3h_expo_20_r3 vs nhek_3h_sham_0_r3
    ("SRR24899735", "SRR24899733"), # nhek_3h_hsc_20_r1 vs nhek_3h_sham_0_r1
    ("SRR24899734", "SRR24899732"), # nhek_3h_hsc_20_r2 vs nhek_3h_sham_0_r2
    ("SRR24899736", "SRR24899731")  # nhek_3h_hsc_20_r3 vs nhek_3h_sham_0_r3
]

paired_metadata_df_gse234710 = create_paired_metadata(
    combined_df=GSE234710_combined,
    defined_sample_pairs=defined_pairs_gse234710,
    sample_id_column_name="accession"
)
if paired_metadata_df_gse234710 is not None:
    # Strip residual "null vs " prefix and " vs null" suffix from all string columns,
    # which appear when only one side of a pair has a value.
    paired_metadata_df_gse234710 = paired_metadata_df_gse234710.with_columns(
        pl.col(pl.String)
        .str.replace_all(r"^null vs ", "") # control treatment temperature column から "null vs " を削除
        .str.replace_all(r" vs null$", "") # stress treatment temperature column から "vs null" を削除
    )
    pl.Config.set_tbl_rows(2)
    display(paired_metadata_df_gse234710)
    paired_metadata_df_gse234710.write_csv(
        "../../Data/metadata/metadata_paired/GSE234710_paired_metadata.tsv",
        separator='\t'
    )
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (23, 81)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ sample_ti ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_al │
│ at_id     ┆ ntrol_id  ┆ me        ┆ tle       ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ ias      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR248997 ┆ SRR248997 ┆ hacat_3h_ ┆ HaCaT,    ┆ … ┆ PRJNA9828 ┆ SRS179585 ┆ 2024-06-2 ┆ GSE23471 │
│ 78        ┆ 64        ┆ hsc_10_r1 ┆ 3H, HSC   ┆   ┆ 00        ┆ 91 vs SRS ┆ 2         ┆ 0        │
│           ┆           ┆ vs hacat_ ┆ 10, R1 vs ┆   ┆           ┆ 17958601  ┆           ┆          │
│           ┆           ┆ 3h_sham_0 ┆ HaCaT,    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _r1       ┆ 3H, Sham  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 0, R1     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRR248997 ┆ SRR248997 ┆ nhek_3h_h ┆ NHEK, 3H, ┆ … ┆ PRJNA9828 ┆ SRS179586 ┆ 2024-06-2 ┆ GSE23471 │
│ 36        ┆ 31        ┆ sc_20_r3  ┆ HSC 20,   ┆   ┆ 00        ┆ 32 vs SRS ┆ 2         ┆ 0        │
│           ┆           ┆ vs nhek_3 ┆ R3 vs     ┆   ┆           ┆ 17958631  ┆           ┆          │
│           ┆           ┆ h_sham_0_ ┆ NHEK, 3H, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ r3        ┆ Sham 0,   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ R3        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE255206 (SINGLE) ARTR-seq

- validate date:2025-05-03
- `Dynamics of RNA localization to nuclear speckles are connected to splicing efficiency [ARTR-seq]`
- [Dynamics of RNA localization to nuclear speckles are connected to splicing efficiency](https://doi.org/10.1126/sciadv.adp7727)
- ARTR-seq (reverse transcription–based RNA binding protein binding sites sequencing) という手法のデータ
- ARTR-Seqの論文: [Profiling of RNA-binding protein binding sites by in situ reverse transcription-based sequencing](https://doi.org/10.1038/s41592-023-02146-w)
- GSE255207の論文の別のプロジェクト
- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から移動

In [26]:
GSE255206_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE255206/GSE255206_PEP/GSE255206_PEP_raw.csv",
    separator=','
)

display(GSE255206_PEP)

shape: (24, 46)
┌────────────┬──────────┬──────────┬───────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ antibody   ┆ assembly ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ str        ┆ str      ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆            ┆          ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
│ hela_mock_ ┆ null     ┆ null     ┆ null      ┆ … ┆ None       ┆ hg38     ┆ https://w ┆ https://w │
│ control_re ┆          ┆          ┆           ┆   ┆            ┆          ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ p1_artr    ┆          ┆          ┆           ┆   ┆            ┆          ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆            ┆          ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆            ┆          ┆ le/SAMN39 ┆ m=SRX2355 │
│            ┆          ┆          ┆           ┆   ┆            ┆          ┆ 846466    ┆ 3091      │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …          ┆ …        ┆ …         ┆ …         │
│ hepg2_mock ┆ null     ┆ null     ┆ null      ┆ … ┆ SRRM2      ┆ hg38     ┆ https://w ┆ https://w │
│ _srrm2_rep ┆          ┆          ┆           ┆   ┆ (Sigma     ┆          ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ 2_artr     ┆          ┆          ┆           ┆   ┆ Aldrich,   ┆          ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ #HPA041411 ┆          ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆ )          ┆          ┆ le/SAMN39 ┆ m=SRX2355 │
│            ┆          ┆          ┆           ┆   ┆            ┆          ┆ 846443    ┆ 3114      │
└────────────┴──────────┴──────────┴───────────┴───┴────────────┴──────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE197992 (SINGLE) TT-chem-seq

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validation date: 2025-05-03
- [An Important Role for RPRD1B in the Heat Shock Response](https://pmc.ncbi.nlm.nih.gov/articles/PMC9583720/)
- おそらく上記の論文由来のデータ
- RPRD1Bの機能を調査しているデータ
- TTchem-seqのデータのプロジェクト
- コントロールデータと熱ストレス曝露のデータが揃っている
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [27]:
GSE197992_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE197992/GSE197992_PEP/GSE197992_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column (Illumina)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE197992_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE197992_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE197992_iseq_filtered = GSE197992_iseq[[s.name for s in GSE197992_iseq if not (s.null_count() == GSE197992_iseq.height)]]

# display(GSE197992_PEP)

In [28]:
GSE197992_combined = GSE197992_PEP.join(
    GSE197992_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE197992_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE197992_ttchem_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE197992_combined)

In [29]:
defined_pairs_gse197992_ttchem_seq = [
    ("SRR18248318", "SRR18248319"), # HS_siNT_B1 [TTchem-seq] (heat-stress) vs NHS_siNT_B1 [TTchem-seq] (control)
    ("SRR18248314", "SRR18248315"), # HS_siNT_B2 [TTchem-seq] (heat-stress) vs NHS_siNT_B2 [TTchem-seq] (control)
    ("SRR18248316", "SRR18248317"), # HS_siRPRD1B_B1 [TTchem-seq] (heat-stress) vs NHS_siRPRD1B_B1 [TTchem-seq] (control)
    ("SRR18248312", "SRR18248313")  # HS_siRPRD1B_B2 [TTchem-seq] (heat-stress) vs NHS_siRPRD1B_B2 [TTchem-seq] (control)
 ]

paired_metadata_df_gse197992_ttchem_seq = create_paired_metadata(
    combined_df=GSE197992_combined,
    defined_sample_pairs=defined_pairs_gse197992_ttchem_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse197992_ttchem_seq is not None:
    paired_metadata_df_gse197992_ttchem_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE197992_ttchem_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse197992_ttchem_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 82)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR182483 ┆ SRR182483 ┆ hs_sint_b ┆ null     ┆ … ┆ PRJNA8133 ┆ SRS122006 ┆ 2022-09-0 ┆ GSE197992 │
│ 18        ┆ 19        ┆ 1_ttchem- ┆          ┆   ┆ 05        ┆ 99 vs SRS ┆ 9         ┆           │
│           ┆           ┆ seq_ vs   ┆          ┆   ┆           ┆ 12200698  ┆           ┆           │
│           ┆           ┆ nhs_sint_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ b1_ttchem ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ -seq_     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR182483 ┆ SRR182483 ┆ hs_sirprd ┆ null     ┆ … ┆ PRJNA8133 ┆ SRS122007 ┆ 2022-09-0 ┆ GSE197992 │
│ 12        ┆ 13        ┆ 1b_b2_ttc ┆          ┆   ┆ 05        ┆ 04 vs SRS ┆ 9         ┆           │
│           ┆           ┆ hem-seq_  ┆          ┆   ┆           ┆ 12200705  ┆           ┆           │
│           ┆           ┆ vs nhs_si ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rprd1b_b2 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _ttchem-s ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ eq_       ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE189562 (SINGLE) TT-chem-seq

- validation date 2025-05-03
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- 以前の研究でも使用していたTTchem-seqのデータ
- 一つのGSM IDに対して2つのSRAのrun IDが付与されている (`srr`カラムが`multi`)
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [30]:
GSE189562_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE189562/GSE189562_PEP/GSE189562_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA RNA HyperPrep kit").alias("rna_library"), # add rna_library column (Roche)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE189562_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE189562_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE189562_iseq_filtered = GSE189562_iseq[[s.name for s in GSE189562_iseq if not (s.null_count() == GSE189562_iseq.height)]]

# display(GSE189562_PEP)

In [31]:
GSE189562_combined = GSE189562_PEP.join(
    GSE189562_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE189562_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE189562_ttchem_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE189562_combined)

In [32]:
defined_pairs_gse189562_ttchem_seq = [
    ("SRR17038300", "SRR17038298"), # (Run1) CPSF3_wt_HS_TTchem-seq_rep1 vs CPSF3_wt_ctrl_TTchem-seq_rep1
    ("SRR17038301", "SRR17038299"), # (Run2) CPSF3_wt_HS_TTchem-seq_rep1 vs CPSF3_wt_ctrl_TTchem-seq_rep1
    ("SRR17038304", "SRR17038302"), # (Run1) CPSF3_depleted_HS_TTchem-seq_rep1 vs CPSF3_depleted_ctrl_TTchem-seq_rep1
    ("SRR17038305", "SRR17038303"), # (Run2) CPSF3_depleted_HS_TTchem-seq_rep1 vs CPSF3_depleted_ctrl_TTchem-seq_rep1
    ("SRR17038308", "SRR17038306"), # (Run1) CPSF3_wt_HS_TTchem-seq_rep2 vs CPSF3_wt_ctrl_TTchem-seq_rep2
    ("SRR17038309", "SRR17038307"), # (Run2) CPSF3_wt_HS_TTchem-seq_rep2 vs CPSF3_wt_ctrl_TTchem-seq_rep2
    ("SRR17038288", "SRR17038286"), # (Run1) CPSF3_depleted_HS_TTchem-seq_rep2 vs CPSF3_depleted_ctrl_TTchem-seq_rep2
    ("SRR17038289", "SRR17038287"), # (Run2) CPSF3_depleted_HS_TTchem-seq_rep2 vs CPSF3_depleted_ctrl_TTchem-seq_rep2
    ("SRR17038292", "SRR17038290"), # (Run1) CPSF3_wt_HS_TTchem-seq_rep3 vs CPSF3_wt_ctrl_TTchem-seq_rep3
    ("SRR17038293", "SRR17038291"), # (Run2) CPSF3_wt_HS_TTchem-seq_rep3 vs CPSF3_wt_ctrl_TTchem-seq_rep3
    ("SRR17038296", "SRR17038294"), # (Run1) CPSF3_depleted_HS_TTchem-seq_rep3 vs CPSF3_depleted_ctrl_TTchem-seq_rep3
    ("SRR17038297", "SRR17038295")  # (Run2) CPSF3_depleted_HS_TTchem-seq_rep3 vs CPSF3_depleted_ctrl_TTchem-seq_rep3
]

paired_metadata_df_gse189562_ttchem_seq = create_paired_metadata(
    combined_df=GSE189562_combined,
    defined_sample_pairs=defined_pairs_gse189562_ttchem_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse189562_ttchem_seq is not None:
    paired_metadata_df_gse189562_ttchem_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE189562_ttchem_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse189562_ttchem_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 82)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR170383 ┆ SRR170382 ┆ cpsf3_wt_ ┆ cDNA     ┆ … ┆ PRJNA7836 ┆ SRS111531 ┆ 2022-01-2 ┆ GSE189562 │
│ 00        ┆ 98        ┆ hs_ttchem ┆          ┆   ┆ 13        ┆ 42 vs SRS ┆ 6         ┆           │
│           ┆           ┆ -seq_rep1 ┆          ┆   ┆           ┆ 11153139  ┆           ┆           │
│           ┆           ┆ vs cpsf3_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ wt_ctrl_t ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tchem-seq ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep1     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR170382 ┆ SRR170382 ┆ cpsf3_dep ┆ cDNA     ┆ … ┆ PRJNA7836 ┆ SRS111531 ┆ 2022-01-2 ┆ GSE189562 │
│ 97        ┆ 95        ┆ leted_hs_ ┆          ┆   ┆ 13        ┆ 50 vs SRS ┆ 6         ┆           │
│           ┆           ┆ ttchem-se ┆          ┆   ┆           ┆ 11153149  ┆           ┆           │
│           ┆           ┆ q_rep3 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ cpsf3_dep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ leted_ctr ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ l_ttchem- ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ seq_rep3  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE165365 (SINGLE) (DREB) TT-chem-seq

- validation date: 2025-05-03
- [Heat shock induces premature transcript termination and reconfigures the human transcriptome](https://doi.org/10.1016/j.molcel.2022.01.007)
- このデータも以前の研究で使用したDRB_TTchem-seqのデータ
- コントロールと熱ストレス曝露のデータが揃っているので念の為収集
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [33]:
GSE165365_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE165365/GSE165365_PEP/GSE165365_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA RNA HyperPrep kit").alias("rna_library"), # add rna_library column (Roche)
    pl.lit("https://doi.org/10.1016/j.molcel.2022.01.007").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE165365_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE165365_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE165365_iseq_filtered = GSE165365_iseq[[s.name for s in GSE165365_iseq if not (s.null_count() == GSE165365_iseq.height)]]

# display(GSE165365_PEP)

In [34]:
GSE165365_combined = GSE165365_PEP.join(
    GSE165365_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE165365_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE165365_drb_ttchem_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE165365_combined)

In [35]:
defined_pairs_gse165365_ttchem_seq = [
    ("SRR13510285", "SRR13510275"), # hs_drb_ttchem-seq_0min_release_rep1 vs ctrl_drb_ttchem-seq_0min_release_rep1
    ("SRR13510286", "SRR13510276"), # hs_drb_ttchem-seq_10min_release_rep1 vs ctrl_drb_ttchem-seq_10min_release_rep1
    ("SRR13510287", "SRR13510277"), # hs_drb_ttchem-seq_20min_release_rep1 vs ctrl_drb_ttchem-seq_20min_release_rep1
    ("SRR13510288", "SRR13510278"), # hs_drb_ttchem-seq_30min_release_rep1 vs ctrl_drb_ttchem-seq_30min_release_rep1
    ("SRR13510289", "SRR13510279"), # hs_drb_ttchem-seq_40min_release_rep1 vs ctrl_drb_ttchem-seq_40min_release_rep1
    ("SRR13510290", "SRR13510280"), # hs_drb_ttchem-seq_0min_release_rep2 vs ctrl_drb_ttchem-seq_0min_release_rep2
    ("SRR13510291", "SRR13510281"), # hs_drb_ttchem-seq_10min_release_rep2 vs ctrl_drb_ttchem-seq_10min_release_rep2
    ("SRR13510292", "SRR13510282"), # hs_drb_ttchem-seq_20min_release_rep2 vs ctrl_drb_ttchem-seq_20min_release_rep2
    ("SRR13510293", "SRR13510283"), # hs_drb_ttchem-seq_30min_release_rep2 vs ctrl_drb_ttchem-seq_30min_release_rep2
    ("SRR13510294", "SRR13510284"), # hs_drb_ttchem-seq_40min_release_rep2 vs ctrl_drb_ttchem-seq_40min_release_rep2
]

paired_metadata_df_gse165365_ttchem_seq = create_paired_metadata(
    combined_df=GSE165365_combined,
    defined_sample_pairs=defined_pairs_gse165365_ttchem_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse165365_ttchem_seq is not None:
    paired_metadata_df_gse165365_ttchem_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE165365_ttchem_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse165365_ttchem_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (10, 80)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR135102 ┆ SRR135102 ┆ hs_drb_tt ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809856 ┆ 2022-01-2 ┆ GSE165365 │
│ 85        ┆ 75        ┆ chem-seq_ ┆          ┆   ┆ 67        ┆ 7 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ 0min_rele ┆          ┆   ┆           ┆ 098557    ┆           ┆           │
│           ┆           ┆ ase_rep1  ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ vs ctrl_d ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rb_ttchem ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ -seq_0min ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _release_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rep1      ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR135102 ┆ SRR135102 ┆ hs_drb_tt ┆ cDNA     ┆ … ┆ PRJNA6941 ┆ SRS809857 ┆ 2022-01-2 ┆ GSE165365 │
│ 94        ┆ 84        ┆ chem-seq_ ┆          ┆   ┆ 67        ┆ 5 vs SRS8 ┆ 6         ┆           │
│           ┆           ┆ 40min_rel ┆          ┆   ┆           ┆ 098566    ┆           ┆           │
│           ┆           ┆ ease_rep2 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ vs ctrl_d ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ rb_ttchem ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ -seq_40mi ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ n_release ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _rep2     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE130892 (SINGLE) MeRIP-seq

- validation date: 2025-05-03
- [Limits in the detection of m6A changes using MeRIP/m6A-seq](https://doi.org/10.1038/s41598-020-63355-3)
- 以前の研究で使用していたRNA-seqとMeRIP-seq (methylated RNA immunoprecipitation sequencing) のデータ
- ~~以前の研究では使用していたが、MeRIP-seqの使用方法としてはChIP-seqのような使用方法なので、今回はフィルタリングして収集する~~
- 念の為、MeRIP-seqも収集する
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動
- [./12_7_metadata_meripseq.ipynb](./12_7_metadata_meripseq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE132447 (SINGLE) small RNA-seq

<!-- - ✅ DOWNLOAD -->
<!-- - ✅ TRIMMING -->
<!-- - ✅ QUANTIFICATION -->

&nbsp;

- validation date: 2025-05-03
- [Multiple Alu Exonization in 3′UTR of a Primate-Specific Isoform of CYP20A1 Creates a Potential miRNA Sponge](https://doi.org/10.1093/gbe/evaa233)
-  HIV1-Tat treatment (おそらくtat)のデータをフィルタリングして、RNA-seqとsmall RNA-seqのデータを収集する
- `Heat shock was given at 45°C (±0.2)  for 30 mins in a water bath.`
- small RNA-seqのデータの処理は[./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から移動

In [36]:
GSE132447_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE132447/GSE132447_PEP/GSE132447_PEP_raw.csv",
    separator=','
)

GSE132447_PEP_small_rna_seq = GSE132447_PEP.filter(
    (pl.col("sample_title").str.contains(r'Small_RNA seq_')) & ~(pl.col("sample_title").str.contains(r'_MCF-7'))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq small RNA library preparation kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1093/gbe/evaa233").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE132447_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE132447_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE132447_iseq_filtered = GSE132447_iseq[[s.name for s in GSE132447_iseq if not (s.null_count() == GSE132447_iseq.height)]]

# display(GSE132447_PEP_small_rna_seq)

In [37]:
GSE132447_combined_small_rna_seq = GSE132447_PEP_small_rna_seq.join(
    GSE132447_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).filter(
    ~(pl.col("sample_title").str.contains(r'_Tat_')) # filter out HIV1-Tat treatment data
)

GSE132447_combined_small_rna_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE132447_small_rna_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE132447_combined_small_rna_seq)

In [38]:
# small RNA-seq
defined_pairs_gse132447_small_rna_seq = [
    ("SRR9257637", "SRR9257634"), # Small_RNA seq_Heat_shock_1 hr recovery_Replicate_1 vs Small_RNA seq_Untreated_Replicate_1
    ("SRR9257638", "SRR9257635"), # Small_RNA seq_Heat_shock_1 hr recovery_Replicate_2 vs Small_RNA seq_Untreated_Replicate_2
    ("SRR9257639", "SRR9257636"), # Small_RNA seq_Heat_shock_1 hr recovery_Replicate_3 vs Small_RNA seq_Untreated_Replicate_3
    ("SRR9257640", "SRR9257634"), # Small_RNA seq_Heat_shock_3 hr recovery_Replicate_1 vs Small_RNA seq_Untreated_Replicate_1
    ("SRR9257641", "SRR9257635"), # Small_RNA seq_Heat_shock_3 hr recovery_Replicate_2 vs Small_RNA seq_Untreated_Replicate_2
    ("SRR9257642", "SRR9257636"), # Small_RNA seq_Heat_shock_3 hr recovery_Replicate_3 vs Small_RNA seq_Untreated_Replicate_3
    ("SRR9257643", "SRR9257634"), # Small_RNA seq_Heat_shock_24 hr recovery_Replicate_1 vs Small_RNA seq_Untreated_Replicate_1
    ("SRR9257644", "SRR9257635"), # Small_RNA seq_Heat_shock_24 hr recovery_Replicate_2 vs Small_RNA seq_Untreated_Replicate_2
    ("SRR9257645", "SRR9257636")  # Small_RNA seq_Heat_shock_24 hr recovery_Replicate_3 vs Small_RNA seq_Untreated_Replicate_3
]

paired_metadata_df_gse132447_small_rna_seq = create_paired_metadata(
    combined_df=GSE132447_combined_small_rna_seq,
    defined_sample_pairs=defined_pairs_gse132447_small_rna_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse132447_small_rna_seq is not None:
    paired_metadata_df_gse132447_small_rna_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE132447_small_rna_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse132447_small_rna_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (9, 81)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR925763 ┆ SRR925763 ┆ small_rna ┆ cDNA     ┆ … ┆ PRJNA5481 ┆ SRS493166 ┆ 2021-01-2 ┆ GSE132447 │
│ 7         ┆ 4         ┆ _seq_heat ┆          ┆   ┆ 08        ┆ 9 vs SRS4 ┆ 3         ┆           │
│           ┆           ┆ _shock_1_ ┆          ┆   ┆           ┆ 931666    ┆           ┆           │
│           ┆           ┆ hr_recove ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ry_replic ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ate_1 vs  ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ small_rna ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _seq_untr ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ eated_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ licate_1  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR925764 ┆ SRR925763 ┆ small_rna ┆ cDNA     ┆ … ┆ PRJNA5481 ┆ SRS493167 ┆ 2021-01-2 ┆ GSE132447 │
│ 5         ┆ 6         ┆ _seq_heat ┆          ┆   ┆ 08        ┆ 7 vs SRS4 ┆ 3         ┆           │
│           ┆           ┆ _shock_24 ┆          ┆   ┆           ┆ 931668    ┆           ┆           │
│           ┆           ┆ _hr_recov ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ery_repli ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ cate_3 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ small_rna ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _seq_untr ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ eated_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ licate_3  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE247043 (PAIRED) single-cell RNA-seq

- validation date: 2025-05-03
- [Pre-print: Spatiotemporal Single-Cell Rna Sequencing Reveals that Cd4+T Subpopulation with High Metabolic Flux Plays Pivotal Roles Under in Hyperthermia Treatment Warts](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4636648)
- これはsingle-cell RNA-seq (scRNA-seq) のデータ
- ~~bulk RNA-seqと同様に解析することはできなくはないが、2ペアという数の少なさなので、今回は解析に使用しない~~
- 念の為収集
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [39]:
GSE247043_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE247043/GSE247043_PEP/GSE247043_PEP_raw.csv",
    separator=','
)

display(GSE247043_PEP)

shape: (4, 45)
┌────────────┬──────────┬──────────┬───────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ assembly ┆ supplement ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ary_files_ ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ str      ┆ format_and ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆          ┆ _content   ┆           ┆           │
│            ┆          ┆          ┆           ┆   ┆          ┆ ---        ┆           ┆           │
│            ┆          ┆          ┆           ┆   ┆          ┆ str        ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ ca1_contro ┆ null     ┆ null     ┆ null      ┆ … ┆ mm10     ┆ Tab-separt ┆ https://w ┆ https://w │
│ l_scrnaseq ┆          ┆          ┆           ┆   ┆          ┆ ed value   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆          ┆ files and  ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆          ┆ matrix     ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆          ┆ files      ┆ le/SAMN38 ┆ m=SRX2237 │
│            ┆          ┆          ┆           ┆   ┆          ┆            ┆ 113603    ┆ 8428      │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …        ┆ …          ┆ …         ┆ …         │
│ ca2_hypert ┆ null     ┆ null     ┆ null      ┆ … ┆ mm10     ┆ Tab-separt ┆ https://w ┆ https://w │
│ hermia_scr ┆          ┆          ┆           ┆   ┆          ┆ ed value   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ naseq      ┆          ┆          ┆           ┆   ┆          ┆ files and  ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆          ┆ matrix     ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆          ┆ files      ┆ le/SAMN38 ┆ m=SRX2237 │
│            ┆          ┆          ┆           ┆   ┆          ┆            ┆ 113600    ┆ 8431      │
└────────────┴──────────┴──────────┴───────────┴───┴──────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE123980 (PAIRED) TT-seq, mNET-seq

- validate date: 2025-05-04
- [The pause-initiation limit restricts transcription activation in human cells](https://doi.org/10.1038/s41467-019-11536-8)
- TT-seq,RNA-seq,mNET-seqなどの複数の手法が含まれている
- [TT-seqに関する論文: TT-seq maps the human transient transcriptome](https://doi.org/10.1126/science.aad9841)
- [mNET-seq](https://jp.illumina.com/science/sequencing-method-explorer/kits-and-arrays/mnet-seq.html)
- 一応念の為全てのデータを収集
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [40]:
ID = "GSE123980"

GSE123980_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Ovation Universal RNA-Seq System").alias("rna_library"), # add rna_library column from GEO webpage (NuGEN)
    pl.lit("https://doi.org/10.1038/s41467-019-11536-8").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE123980_PEP_tt_seq = GSE123980_PEP.filter(
    pl.col("sample_title").str.contains(r'TT-seq_')
)

GSE123980_PEP_mnet_seq = GSE123980_PEP.filter(
    pl.col("sample_title").str.contains(r'mNET-seq_')
)

# metadata from iseq
GSE123980_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE123980_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE123980_iseq_filtered = GSE123980_iseq[[s.name for s in GSE123980_iseq if not (s.null_count() == GSE123980_iseq.height)]]

# display(GSE123980_PEP_tt_seq)
# display(GSE123980_PEP_mnet_seq)

In [41]:
GSE123980_tt_seq_combined = GSE123980_PEP_tt_seq.join(
    GSE123980_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE123980_tt_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE123980_tt_seq_modified_metadata.tsv",
    separator='\t'
)

GSE123980_mnet_seq_combined = GSE123980_PEP_mnet_seq.join(
    GSE123980_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE123980_mnet_seq_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE123980_mnet_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE123980_tt_seq_combined)
# display(GSE123980_mnet_seq_combined)

In [42]:
# TT-seq
defined_pairs_gse123980_tt_seq = [
    ("SRR8334015", "SRR8334013"), # TT-seq_K562_HS15_rep1 vs TT-seq_K562_Ctrl_rep1
    ("SRR8334016", "SRR8334014"), # TT-seq_K562_HS15_rep2 vs TT-seq_K562_Ctrl_rep2
    ("SRR8334017", "SRR8334013"), # TT-seq_K562_HS30__rep1 vs TT-seq_K562_Ctrl_rep1
    ("SRR8334018", "SRR8334014"), # TT-seq_K562_HS30_rep2 vs TT-seq_K562_Ctrl_rep2
    ("SRR8334035", "SRR8334031"), # TT-seq_Raji-CDK9as_Solvent_HS30_rep1 vs TT-seq_Raji-CDK9as_Solvent_rep1
    ("SRR8334036", "SRR8334032"), # TT-seq_Raji-CDK9as_Solvent_HS30_rep2 vs TT-seq_Raji-CDK9as_Solvent_rep2
    ("SRR8334037", "SRR8334033"), # TT-seq_Raji-CDK9as_CDK9inhibited_HS30_rep1 vs TT-seq_Raji-CDK9as_CDK9inhibited_rep1
    ("SRR8334038", "SRR8334034")  # TT-seq_Raji-CDK9as_CDK9inhibited_HS30_rep2 vs TT-seq_Raji-CDK9as_CDK9inhibited_rep2
]

paired_metadata_df_gse123980_tt_seq = create_paired_metadata(
    combined_df=GSE123980_tt_seq_combined,
    defined_sample_pairs=defined_pairs_gse123980_tt_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse123980_tt_seq is not None:
    paired_metadata_df_gse123980_tt_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE123980_tt_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse123980_tt_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (8, 81)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR833401 ┆ SRR833401 ┆ tt-seq_k5 ┆ cDNA     ┆ … ┆ PRJNA5104 ┆ SRS415591 ┆ 2019-07-1 ┆ GSE123980 │
│ 5         ┆ 3         ┆ 62_hs15_r ┆          ┆   ┆ 28        ┆ 2 vs SRS4 ┆ 1         ┆           │
│           ┆           ┆ ep1 vs    ┆          ┆   ┆           ┆ 155910    ┆           ┆           │
│           ┆           ┆ tt-seq_k5 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 62_ctrl_r ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ep1       ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR833403 ┆ SRR833403 ┆ tt-seq_ra ┆ cDNA     ┆ … ┆ PRJNA5104 ┆ SRS415593 ┆ 2019-07-1 ┆ GSE123980 │
│ 8         ┆ 4         ┆ ji-cdk9as ┆          ┆   ┆ 28        ┆ 5 vs SRS4 ┆ 1         ┆           │
│           ┆           ┆ _cdk9inhi ┆          ┆   ┆           ┆ 155931    ┆           ┆           │
│           ┆           ┆ bited_hs3 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 0_rep2 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ tt-seq_ra ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ji-cdk9as ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _cdk9inhi ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ bited_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 2         ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [43]:
# mNET-seq
defined_pairs_gse123980_mnet_seq = [
    ("SRR8334027", "SRR8334025"), # mNET-seq_K562_HS15_rep1 vs mNET-seq_K562_Ctrl_rep1
    ("SRR8334028", "SRR8334026"), # mNET-seq_K562_HS15_rep2 vs mNET-seq_K562_Ctrl_rep2
    ("SRR8334029", "SRR8334025"), # mNET-seq_K562_HS30__rep1 vs mNET-seq_K562_Ctrl_rep1
    ("SRR8334030", "SRR8334026")  # mNET-seq_K562_HS30_rep2 vs mNET-seq_K562_Ctrl_rep2
]

paired_metadata_df_gse123980_mnet_seq = create_paired_metadata(
    combined_df=GSE123980_mnet_seq_combined,
    defined_sample_pairs=defined_pairs_gse123980_mnet_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse123980_mnet_seq is not None:
    paired_metadata_df_gse123980_mnet_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE123980_mnet_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse123980_mnet_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 81)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol  ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_al │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---       ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ ias      │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SRR833402 ┆ SRR833402 ┆ mnet-seq_ ┆ size frac ┆ … ┆ PRJNA5104 ┆ SRS415592 ┆ 2019-07-1 ┆ GSE12398 │
│ 7         ┆ 5         ┆ k562_hs15 ┆ tionation ┆   ┆ 28        ┆ 4 vs SRS4 ┆ 1         ┆ 0        │
│           ┆           ┆ _rep1 vs  ┆           ┆   ┆           ┆ 155922    ┆           ┆          │
│           ┆           ┆ mnet-seq_ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k562_ctrl ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _rep1     ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SRR833403 ┆ SRR833402 ┆ mnet-seq_ ┆ size frac ┆ … ┆ PRJNA5104 ┆ SRS415592 ┆ 2019-07-1 ┆ GSE12398 │
│ 0         ┆ 6         ┆ k562_hs30 ┆ tionation ┆   ┆ 28        ┆ 7 vs SRS4 ┆ 1         ┆ 0        │
│           ┆           ┆ _rep2 vs  ┆           ┆   ┆           ┆ 155923    ┆           ┆          │
│           ┆           ┆ mnet-seq_ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ k562_ctrl ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _rep2     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE128365 (PAIRED) scEdU-seq

- validate date: 2025-05-04
- [Quantifying DNA replication speeds in single cells by scEdU-seq](https://doi.org/10.1038/s41592-024-02308-4)
- `single-cell 5-ethynyl-2′-deoxyuridine sequencing (scEdU-seq)` という手法に関するデータ
- nacsent RNAの検出ができる手法
- ~~一応 scRNA-seqの亜種なので、今回は収集しない (もしかしたら後ほど収集するかも？)~~
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [44]:
ID = "GSE128365"

GSE128365_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    (pl.col("sample_source_name_ch1").str.contains(r'HeatShock-'))
)

# pl.Config.set_fmt_str_lengths(200)
display(GSE128365_PEP)

shape: (6, 47)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ library_s ┆ supplemen ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ trategy   ┆ tary_file ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ s_format_ ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ and_conte ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ nt        ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ heatshock ┆ cDNA     ┆ Homo      ┆ PAIRED    ┆ … ┆ null      ┆ The       ┆ https://w ┆ https://w │
│ -37c-tot- ┆          ┆ sapiens   ┆           ┆   ┆           ┆ number of ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ dmso-45mi ┆          ┆           ┆           ┆   ┆           ┆ UMI count ┆ lm.nih.go ┆ lm.nih.go │
│ n-k562-pl ┆          ┆           ┆           ┆   ┆           ┆ per gene  ┆ v/biosamp ┆ v/sra?ter │
│ ate1      ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN14 ┆ m=SRX7815 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 237934    ┆ 439       │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ heatshock ┆ cDNA     ┆ Homo      ┆ PAIRED    ┆ … ┆ null      ┆ The       ┆ https://w ┆ https://w │
│ -42c-tot- ┆          ┆ sapiens   ┆           ┆   ┆           ┆ number of ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ eu-45min- ┆          ┆           ┆           ┆   ┆           ┆ UMI count ┆ lm.nih.go ┆ lm.nih.go │
│ k562-plat ┆          ┆           ┆           ┆   ┆           ┆ per gene  ┆ v/biosamp ┆ v/sra?ter │
│ e4        ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN14 ┆ m=SRX7815 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 238052    ┆ 444       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE100469 (PAIRED) 4sU-seq

- validate date: 2025-05-04
- [HSV-1-induced disruption of transcription termination resembles a cellular stress response but selectively increases chromatin accessibility downstream of genes](https://doi.org/10.1371/journal.ppat.1006954)
- 4sU-seqなので、新生RNAを検出しているデータ
- 念の為収集
- [./12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

In [45]:
ID = "GSE100469"

GSE100469_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).filter(
    ~pl.col("sample_title").str.contains(r' Salt ')
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq Stranded Total RNA kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1371/journal.ppat.1006954").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE100469_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE100469_metadata.tsv",
    separator='\t'
)
GSE100469_iseq_filtered = GSE100469_iseq[[s.name for s in GSE100469_iseq if not (s.null_count() == GSE100469_iseq.height)]]

# display(GSE100469_PEP)

In [46]:
GSE100469_combined = GSE100469_PEP.join(
    GSE100469_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE100469_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE100469_modified_metadata.tsv",
    separator='\t'
)

# display(GSE100469_combined)

In [47]:
defined_pairs_gse100469_4sU_seq = [
    ("SRR5756320", "SRR5756304"), # 0-1 h Heat stress 4sU-RNA - Rep 1 vs Mock 1 4sU-RNA - Rep 1
    ("SRR5756321", "SRR5756305"), # 0-1 h Heat stress 4sU-RNA - Rep 1 vs Mock 1 4sU-RNA - Rep 1
    ("SRR5756322", "SRR5756306"), # 0-1 h Heat stress 4sU-RNA - Rep 1 vs Mock 1 4sU-RNA - Rep 1
    ("SRR5756323", "SRR5756307"), # 0-1 h Heat stress 4sU-RNA - Rep 1 vs Mock 1 4sU-RNA - Rep 1
    ("SRR5756324", "SRR5756308"), # 1-2 h Heat stress 4sU-RNA - Rep 1 vs Mock 2 4sU-RNA - Rep 1
    ("SRR5756325", "SRR5756309"), # 1-2 h Heat stress 4sU-RNA - Rep 1 vs Mock 2 4sU-RNA - Rep 1
    ("SRR5756326", "SRR5756310"), # 1-2 h Heat stress 4sU-RNA - Rep 1 vs Mock 2 4sU-RNA - Rep 1
    ("SRR5756327", "SRR5756311"), # 1-2 h Heat stress 4sU-RNA - Rep 1 vs Mock 2 4sU-RNA - Rep 1
    ("SRR5756344", "SRR5756328"), # 0-1 h Heat stress 4sU-RNA -  Rep 2 vs Mock 1 4sU-RNA - Rep 2
    ("SRR5756345", "SRR5756329"), # 0-1 h Heat stress 4sU-RNA -  Rep 2 vs Mock 1 4sU-RNA - Rep 2
    ("SRR5756346", "SRR5756330"), # 0-1 h Heat stress 4sU-RNA -  Rep 2 vs Mock 1 4sU-RNA - Rep 2
    ("SRR5756347", "SRR5756331"), # 0-1 h Heat stress 4sU-RNA -  Rep 2 vs Mock 1 4sU-RNA - Rep 2
    ("SRR5756348", "SRR5756332"), # 1-2 h Heat stress 4sU-RNA -  Rep 2 vs Mock 2 4sU-RNA - Rep 2
    ("SRR5756349", "SRR5756333"), # 1-2 h Heat stress 4sU-RNA -  Rep 2 vs Mock 2 4sU-RNA - Rep 2
    ("SRR5756350", "SRR5756334"), # 1-2 h Heat stress 4sU-RNA -  Rep 2 vs Mock 2 4sU-RNA - Rep 2
    ("SRR5756351", "SRR5756335")  # 1-2 h Heat stress 4sU-RNA -  Rep 2 vs Mock 2 4sU-RNA - Rep 2
]

paired_metadata_df_gse100469_4sU_seq = create_paired_metadata(
    combined_df=GSE100469_combined,
    defined_sample_pairs=defined_pairs_gse100469_4sU_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse100469_4sU_seq is not None:
    paired_metadata_df_gse100469_4sU_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE100469_4sU_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse100469_4sU_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (16, 88)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR575632 ┆ SRR575630 ┆ 0-1_h_hea ┆ cDNA     ┆ … ┆ PRJNA3919 ┆ SRS231369 ┆ 2018-03-1 ┆ GSE100469 │
│ 0         ┆ 4         ┆ t_stress_ ┆          ┆   ┆ 13        ┆ 1 vs SRS2 ┆ 0         ┆           │
│           ┆           ┆ 4su-rna_- ┆          ┆   ┆           ┆ 313687    ┆           ┆           │
│           ┆           ┆ _rep_1 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ mock_1_4s ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ u-rna_-_r ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ep_1      ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR575635 ┆ SRR575633 ┆ 1-2_h_hea ┆ cDNA     ┆ … ┆ PRJNA3919 ┆ SRS231369 ┆ 2018-03-1 ┆ GSE100469 │
│ 1         ┆ 5         ┆ t_stress_ ┆          ┆   ┆ 13        ┆ 8 vs SRS2 ┆ 0         ┆           │
│           ┆           ┆ 4su-rna_- ┆          ┆   ┆           ┆ 313694    ┆           ┆           │
│           ┆           ┆ _rep_2 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ mock_2_4s ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ u-rna_-_r ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ep_2      ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE127890 (SINGLE) Nanopore (nano-ID)

- validate date 2025-05-04
- [Native molecule sequencing by nano-ID reveals synthesis and stability of RNA isoforms](https://doi.org/10.1101/gr.257857.119)
- 以前の研究でも使用しているnanoporeのデータで、RNAのisoformを検出するための手法 nano-ID (nanopore sequencing–based isoform dynamics) を開発した論文
- `To show the advantages of nano-ID, we subjected human K562 cells to heat shock (42°C) for 60 min in the presence of 5EU (5EU 60 min HS) (Fig. 4A).`
- 上記のような記述に関するデータを収集
- [./12_4_metadata_modified_false_no_control.ipynb](./12_4_metadata_modified_false_no_control.ipynb)から処理を移動

In [48]:
GSE127890_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE127890/GSE127890_PEP/GSE127890_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_organism_ch1") == "Homo sapiens") & # remove synthetic construct sample data
    (pl.col("sample_title").str.contains(r'5EU 60 min')) &
    ~(pl.col("sample_title").str.contains(r'5EU 60 min replicate 6')) # No replicate 6 exposed to heat shock, so this data was removed
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("SQK-RNA001").alias("rna_library"), # add rna_library column from GEO webpage (Oxford Nanopore Technologies)
    pl.lit("https://doi.org/10.1101/gr.257857.119").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE127890 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE127890_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE127890_iseq_filtered = GSE127890[[s.name for s in GSE127890 if not (s.null_count() == GSE127890.height)]]

# display(GSE127890_PEP)

In [49]:
GSE127890_combined = GSE127890_PEP.join(
    GSE127890_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE127890_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE127890_modified_metadata.tsv",
    separator='\t'
)

# display(GSE127890_combined)

In [50]:
defined_pairs_gse127890 = [
    ("SRR10953094", "SRR10953082"), # 5EU 60 min HS replicate 1 vs 5EU 60 min replicate 1
    ("SRR10953095", "SRR10953083"), # 5EU 60 min HS replicate 2 vs 5EU 60 min replicate 2
    ("SRR10953096", "SRR10953084"), # 5EU 60 min HS replicate 3 vs 5EU 60 min replicate 3
    ("SRR10953097", "SRR10953085"), # 5EU 60 min HS replicate 4 vs 5EU 60 min replicate 4
    ("SRR10953098", "SRR10953086")  # 5EU 60 min HS replicate 5 vs 5EU 60 min replicate 5
]

paired_metadata_df_gse127890 = create_paired_metadata(
    combined_df=GSE127890_combined, 
    defined_sample_pairs=defined_pairs_gse127890,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse127890 is not None:
    paired_metadata_df_gse127890.write_csv(
        "../../Data/metadata/metadata_paired/GSE127890_paired_metadata.tsv",
        separator='\t'
    )

# display(paired_metadata_df_gse127890)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE180253 (SINGLE) m6A-seq

- validation date: 2025-05-06
- [Inhibition of HSP90 as a Strategy to Radiosensitize Glioblastoma: Targeting the DNA Damage Response and Beyond](https://doi.org/10.3389/fonc.2021.612354)
- m6A-seqのデータが含まれている...
- [MeRIP-Seq/m6A-seq](https://jp.illumina.com/science/sequencing-method-explorer/kits-and-arrays/merip-seq-m6a-seq.html)
- `heat_shock_` と `Untreated_` のデータを念の為収集する
- m6A-seqのデータ処理を[./12_4_metadata_modified_false_no_control.ipynb](./12_4_metadata_modified_false_no_control.ipynb)から移動

In [51]:
GSE180253_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE180253/GSE180253_PEP/GSE180253_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("protocol") == "cDNA") & # remove CAGE-seq data
    ((pl.col("sample_title").str.contains(r'heat_shock_')) | 
     (pl.col("sample_title").str.contains(r'Untreated_'))) & # remove HSF1 knockdown data
    ~(pl.col("sample_title").str.contains(r'Hypoxia_')) # remove HSF1 knockdown data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column from GEO page
    pl.lit("https://doi.org/10.3389/fonc.2021.612354").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

GSE180253_PEP_m6am_seq = GSE180253_PEP.filter(
    ~(pl.col("sample_description") == "RNA-seq")
)

# metadata from iseq
GSE180253 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE180253_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE180253_iseq_filtered = GSE180253[[s.name for s in GSE180253 if not (s.null_count() == GSE180253.height)]]


# display(GSE180253_PEP)

In [52]:
GSE180253_combined_m6am_seq = GSE180253_PEP_m6am_seq.join(
    GSE180253_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE180253_combined_m6am_seq.write_csv(
    "../../Data/metadata/metadata_modified/GSE180253_m6am_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE180253_combined_m6am_seq)

In [53]:
# m6Am-seq
defined_pairs_gse180253_m6am_seq = [
    ("SRR15177493", "SRR15177507"), # heat_shock_FTO_m6AIP-rep1 vs Untreated_FTO_m6AIP-rep1
    ("SRR15177494", "SRR15177508"), # heat_shock_FTO_m6AIP-rep2 vs Untreated_FTO_m6AIP-rep2
    ("SRR15177496", "SRR15177510"), # heat_shock_nonFTO_m6AIP-rep1 vs Untreated_nonFTO_m6AIP-rep1
    ("SRR15177497", "SRR15177511"), # heat_shock_nonFTO_m6AIP-rep2 vs Untreated_nonFTO_m6AIP-rep2
    ("SRR15177498", "SRR15177512"), # heat_shock_nonFTO_m7GIP-rep1 vs Untreated_nonFTO_m7GIP-rep1
    ("SRR15177499", "SRR15177513")  # heat_shock_nonFTO_m7GIP-rep2 vs Untreated_nonFTO_m7GIP-rep2
]

paired_metadata_df_gse180253_m6am_seq = create_paired_metadata(
    combined_df=GSE180253_combined_m6am_seq, 
    defined_sample_pairs=defined_pairs_gse180253_m6am_seq,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse180253_m6am_seq is not None:
    paired_metadata_df_gse180253_m6am_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE180253_m6am_seq_paired_metadata.tsv",
        separator='\t'
    )

display(paired_metadata_df_gse180253_m6am_seq)

shape: (6, 84)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR151774 ┆ SRR151775 ┆ heat_shoc ┆ cDNA     ┆ … ┆ PRJNA7472 ┆ SRS952464 ┆ 2021-07-2 ┆ GSE180253 │
│ 93        ┆ 07        ┆ k_fto_m6a ┆          ┆   ┆ 71        ┆ 9 vs SRS9 ┆ 4         ┆           │
│           ┆           ┆ ip-rep1   ┆          ┆   ┆           ┆ 524663    ┆           ┆           │
│           ┆           ┆ vs untrea ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ted_fto_m ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ 6aip-rep1 ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR151774 ┆ SRR151775 ┆ heat_shoc ┆ cDNA     ┆ … ┆ PRJNA7472 ┆ SRS952465 ┆ 2021-07-2 ┆ GSE180253 │
│ 99        ┆ 13        ┆ k_nonfto_ ┆          ┆   ┆ 71        ┆ 5 vs SRS9 ┆ 4         ┆           │
│           ┆           ┆ m7gip-rep ┆          ┆   ┆           ┆ 524669    ┆           ┆           │
│           ┆           ┆ 2 vs untr ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ eated_non ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ fto_m7gip ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ -rep2     ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE70485 (SINGLE) m1A-seq

- validation date: 2025-05-06
- [The dynamic N1-methyladenosine methylome in eukaryotic messenger RNA](https://doi.org/10.1038/nature16998)
- m1A-seqを行っているデータ
- 熱ショックを加えているため、念の為収集する
- `HEPG2 mRNA heat shock 4h IP`, `HEPG2 mRNA heat shock 4h input`, `hepg2_mrna_untreated_ip_replicate_b`, `hepg2_mrna_untreated_input_replicate_b`の4つを念の為収集
- ※ 他にもreplicate C~E があるが今回は使用しない
- 処理を[./12_4_metadata_modified_false_no_control.ipynb](./12_4_metadata_modified_false_no_control.ipynb)から移動

In [54]:
GSE70485_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE70485/GSE70485_PEP/GSE70485_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    ~(
        (pl.col("sample_title").str.contains(r'HEPG2 mRNA Glucose starvation 4h')) | 
        (pl.col("sample_title").str.contains(r'HepG2 PARSseq')) | 
        (pl.col("sample_title").str.contains(r'replicate [C-E]')) | # Use regex character class [A-D] to match replicate C, D, E
        (pl.col("sample_title").str.contains(r'HEPG2 total RNA rearranged at [5-6]0c IP')) |
        (pl.col("sample_title").str.contains(r'HEPG2 total RNA rearranged at [5-6]0c input')) |
        (pl.col("sample_title").str.contains(r'HEK293')) |
        (pl.col("sample_title").str.contains(r'HeLa mRNA')) |
        (pl.col("sample_title") == "HEPG2 total RNA Untreated IP competitive elution") |
        (pl.col("sample_title") == "HEPG2 total RNA Untreated input competitive elution") |
        (pl.col("sample_title") == "HEPG2 total RNA Untreated IP replicate") |
        (pl.col("sample_title") == "HEPG2 total RNA Untreated input replicate")
    )
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra RNA Library Prep Kit").alias("rna_library"), # add rna_library column from GEO page (New England Biolabs)
    pl.lit("https://doi.org/10.1038/nature16998").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE70485 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE70485_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE70485_iseq_filtered = GSE70485[[s.name for s in GSE70485 if not (s.null_count() == GSE70485.height)]]


# display(GSE70485_PEP)

In [55]:
GSE70485_combined = GSE70485_PEP.join(
    GSE70485_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE70485_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE70485_modified_metadata.tsv",
    separator='\t'
)

# display(GSE70485_combined)

In [56]:
defined_pairs_gse70485_m1a_seq = [
    ("SRR3000786", "SRR3000774"), # HEPG2 mRNA heat shock 4h IP vs HEPG2 mRNA untreated IP replicate B
    ("SRR3000787", "SRR3000775")  # HEPG2 mRNA heat shock 4h input vs HEPG2 mRNA untreated input replicate B
]

paired_metadata_df_gse70485 = create_paired_metadata(
    combined_df=GSE70485_combined,
    defined_sample_pairs=defined_pairs_gse70485_m1a_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse70485 is not None:
    paired_metadata_df_gse70485.write_csv(
        "../../Data/metadata/metadata_paired/GSE70485_m1a_seq_paired_metadata.tsv",
        separator='\t'
    )

# display(paired_metadata_df_gse70485)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE218180 (PAIRED) FANCI

- validation date: 2025-05-06
- [RNA damage compartmentalization by DHX9 stress granules](https://doi.org/10.1016/j.cell.2024.02.028)
- DHX9というヘリカーゼが関与する stress granuleに関する研究
- RNA-seqのデータの他に`fluorescence-activated non-membrane condensates isolation (FANCI)`というSGをフィルタリングする手法も含まれている
- FANCIのサンプルデータに熱ストレス曝露のデータが含まれており, `sample_library_source`を見ると transcriptomicになっており、悩みどころである
- **後でもう一度判断するとして、念の為収集しておく**
- 実験条件は43℃, 60min. (論文より)
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動

In [57]:
GSE218180_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE218180/GSE218180_PEP/GSE218180_PEP_raw.csv",
    separator=','
).filter(
    ((pl.col("treatment") == "untreated") | # untreated
    (pl.col("treatment") == "Hs")) & # Heat shock
    (pl.col("sample_title").str.contains(r"FANCI")) # FANCI
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina's Stranded Total RNA with RiboZero Plus kit").alias("rna_library"), # add rna_library column from GEO page (Illumina)
    pl.lit("https://doi.org/10.1016/j.cell.2024.02.028").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE218180 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE218180_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE218180_iseq_filtered = GSE218180[[s.name for s in GSE218180 if not (s.null_count() == GSE218180.height)]]

# display(GSE218180_PEP)

In [58]:
GSE218180_combined = GSE218180_PEP.join(
    GSE218180_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE218180_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE218180_fanci_modified_metadata.tsv",
    separator='\t'
)

# display(GSE218180_combined)

In [59]:
defined_pairs_gse218180 = [
    ("SRR22319541", "SRR22319547"), # FANCI, Total RNA from Hela with heat shock(Hs) stress, 1 vs FANCI, Total RNA from Hela, 1
    ("SRR22319540", "SRR22319546"), # FANCI, Total RNA from Hela with heat shock(Hs) stress, 2 vs FANCI, Total RNA from Hela, 2
    ("SRR22319539", "SRR22319545"), # FANCI, Total RNA from Hela with heat shock(Hs) stress, 3 vs FANCI, Total RNA from Hela, 3
    ("SRR22319523", "SRR22319547"), # FANCI, Total RNA from SG with heat shock(Hs) stress, 1 vs FANCI, Total RNA from Hela, 1
    ("SRR22319522", "SRR22319546"), # FANCI, Total RNA from SG with heat shock(Hs) stress, 2 vs FANCI, Total RNA from Hela, 2
    ("SRR22319521", "SRR22319545")  # FANCI, Total RNA from SG with heat shock(Hs) stress, 3 vs FANCI, Total RNA from Hela, 3
]

paired_metadata_df_gse218180_fanci = create_paired_metadata(
    combined_df=GSE218180_combined,
    defined_sample_pairs=defined_pairs_gse218180,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse218180_fanci is not None:
    paired_metadata_df_gse218180_fanci.write_csv(
        "../../Data/metadata/metadata_paired/GSE218180_fanci_paired_metadata.tsv",
        separator="\t"
    )

display(paired_metadata_df_gse218180_fanci)

shape: (6, 84)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_he ┆ sample_co ┆ sample_na ┆ protocol ┆ … ┆ study_acc ┆ secondary ┆ first_pub ┆ study_ali │
│ at_id     ┆ ntrol_id  ┆ me        ┆ ---      ┆   ┆ ession    ┆ _sample_a ┆ lic       ┆ as        │
│ ---       ┆ ---       ┆ ---       ┆ str      ┆   ┆ ---       ┆ ccession  ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str       ┆          ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆          ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SRR223195 ┆ SRR223195 ┆ fanci_tot ┆ null     ┆ … ┆ PRJNA9026 ┆ SRS157841 ┆ 2023-11-2 ┆ GSE218180 │
│ 41        ┆ 47        ┆ al_rna_fr ┆          ┆   ┆ 87        ┆ 66 vs SRS ┆ 6         ┆           │
│           ┆           ┆ om_hela_w ┆          ┆   ┆           ┆ 15784160  ┆           ┆           │
│           ┆           ┆ ith_heat_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ shock_hs_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ stress_1  ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ vs fanci_ ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ total_rna ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ _from_hel ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ a_1       ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SRR223195 ┆ SRR223195 ┆ fanci_tot ┆ null     ┆ … ┆ PRJNA9026 ┆ SRS157841 ┆ 2023-11-2 ┆ GSE218180 │
│ 21        ┆ 45        ┆ al_rna_fr ┆          ┆   ┆ 87        ┆ 87 vs SRS ┆ 6         ┆           │
│           ┆           ┆ om_sg_wit ┆          ┆   ┆           ┆ 15784162  ┆           ┆           │
│           ┆           ┆ h_heat_sh ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ock_hs_st ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ress_3 vs ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ fanci_tot ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ al_rna_fr ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ om_hela_3 ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# PRJDB9865 CAGE-seq (SINGLE)

&nbsp;

- validate date 2025-05-18
- [Heat shock induces the nuclear accumulation of YAP1 via SRC](https://doi.org/10.1016/j.yexcr.2020.112439)
- CAGE-seqのデータ
- なにかに使用できる可能性が出てきたため、収集する
- ("DRR228710", "DRR228707")  # U2OS siYAP1 / HeatShock 2h vs U2OS parent cell / HeatShock 0h のペア構築は少し怪しいが少ないので集めておこう
- [12_5_metadata_modified_bioproject_biostudies.ipynb](./12_5_metadata_modified_bioproject_biostudies.ipynb)から移動
- (2026-07-23) [ChIP-Atlas](https://chip-atlas.org/) にはデータが登録されていない

In [60]:
PRJDB9865 = pl.read_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB9865_metadata.tsv",
    separator="\t"
).with_columns(
    pl.lit("nAnT-iCAGE protocol").alias("rna_library"), # add rna_library column from article,
    pl.lit("https://doi.org/10.1016/j.yexcr.2020.112439").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("42 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("120 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
).sort(
    "run_accession",
    descending=False
).drop(
    drop_columns_list
)

PRJDB9865_filtered = PRJDB9865[[s.name for s in PRJDB9865 if not (s.null_count() == PRJDB9865.height)]]

PRJDB9865_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJDB9865_modified_metadata.tsv",
    separator="\t"
)

display(PRJDB9865_filtered)

shape: (4, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ run_acces ┆ experimen ┆ sample_ac ┆ project_n ┆ … ┆ rna_libra ┆ reference ┆ stress    ┆ stress   │
│ sion      ┆ t_title   ┆ cession   ┆ ame       ┆   ┆ ry        ┆ _doi      ┆ treatment ┆ treatmen │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ temperatu ┆ t time   │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ re        ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR228707 ┆ NextSeq   ┆ SAMD00226 ┆ Homo      ┆ … ┆ nAnT-iCAG ┆ https://d ┆ 42 C      ┆ 120 min. │
│           ┆ 500 seque ┆ 153       ┆ sapiens   ┆   ┆ E         ┆ oi.org/10 ┆           ┆          │
│           ┆ ncing:    ┆           ┆           ┆   ┆ protocol  ┆ .1016/j.y ┆           ┆          │
│           ┆ NextSeq   ┆           ┆           ┆   ┆           ┆ excr.2020 ┆           ┆          │
│           ┆ 500 seque ┆           ┆           ┆   ┆           ┆ .112439   ┆           ┆          │
│           ┆ ncing of  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ SAMD00226 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 153       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ DRR228710 ┆ NextSeq   ┆ SAMD00226 ┆ Homo      ┆ … ┆ nAnT-iCAG ┆ https://d ┆ 42 C      ┆ 120 min. │
│           ┆ 500 seque ┆ 156       ┆ sapiens   ┆   ┆ E         ┆ oi.org/10 ┆           ┆          │
│           ┆ ncing:    ┆           ┆           ┆   ┆ protocol  ┆ .1016/j.y ┆           ┆          │
│           ┆ NextSeq   ┆           ┆           ┆   ┆           ┆ excr.2020 ┆           ┆          │
│           ┆ 500 seque ┆           ┆           ┆   ┆           ┆ .112439   ┆           ┆          │
│           ┆ ncing of  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ SAMD00226 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 156       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [61]:
defined_pairs_prjdb9865 = [
    ("DRR228709", "DRR228708"), # U2OS siCtrl / HeatShock 2h vs U2OS siCtrl / HeatShock 0h
    ("DRR228710", "DRR228707")  # U2OS siYAP1 / HeatShock 2h vs U2OS parent cell / HeatShock 0h
]

paired_metadata_df_prjdb9865 = create_paired_metadata(
    combined_df=PRJDB9865_filtered,
    defined_sample_pairs=defined_pairs_prjdb9865,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_prjdb9865 is not None:
    paired_metadata_df_prjdb9865.write_csv(
        "../../Data/metadata/metadata_paired/PRJDB9865_cage_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_prjdb9865)
else:
    print("No paired metadata created for PRJDB9865")

shape: (2, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ rna_libra ┆ reference ┆ stress    ┆ stress   │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ ry        ┆ _doi      ┆ treatment ┆ treatmen │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ temperatu ┆ t time   │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ re        ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DRR228709 ┆ DRR228708 ┆ DRR228709 ┆ NextSeq   ┆ … ┆ nAnT-iCAG ┆ https://d ┆ 42 C      ┆ 120 min. │
│           ┆           ┆ vs        ┆ 500 seque ┆   ┆ E         ┆ oi.org/10 ┆           ┆          │
│           ┆           ┆ DRR228708 ┆ ncing:    ┆   ┆ protocol  ┆ .1016/j.y ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆ excr.2020 ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆ .112439   ┆           ┆          │
│           ┆           ┆           ┆ ncing of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00226 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 155 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing:    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00226 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 154       ┆   ┆           ┆           ┆           ┆          │
│ DRR228710 ┆ DRR228707 ┆ DRR228710 ┆ NextSeq   ┆ … ┆ nAnT-iCAG ┆ https://d ┆ 42 C      ┆ 120 min. │
│           ┆           ┆ vs        ┆ 500 seque ┆   ┆ E         ┆ oi.org/10 ┆           ┆          │
│           ┆           ┆ DRR228707 ┆ ncing:    ┆   ┆ protocol  ┆ .1016/j.y ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆ excr.2020 ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆ .112439   ┆           ┆          │
│           ┆           ┆           ┆ ncing of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00226 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 156 vs    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing:    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NextSeq   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 500 seque ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ncing of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SAMD00226 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 153       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## PRJEB73803 (ERP158539) (PAIRED) 4sU-seq

- validate date: 2025-05-18
- [E-MTAB-13903](https://www.ebi.ac.uk/biostudies/ArrayExpress/studies/E-MTAB-13903?query=E-MTAB-13903)
- 論文は見つけられなかったが、熱ショックとコントロールのデータが登録されているので念の為収集する
- `control exposed to 200nM 4sU` と `HS-treated exposed to 200nM 4sU` の2つがある
- [./12_5_metadata_modified_bioproject_biostudies.ipynb](./12_5_metadata_modified_bioproject_biostudies.ipynb)から処理を移動

In [62]:
PRJEB73803 = pl.read_csv(
    "../../Data/metadata/metadata_biostudies/ERP158539.metadata.tsv",
    separator="\t"
).with_columns(
    pl.lit("unknown").alias("rna_library"), # add rna_library column from ENA webpage
    pl.lit("unknown").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("43 C").alias("stress treatment temperature"), # add heat treatment temperature column
    pl.lit("60 min.").alias("stress treatment time"), # add heat treatment time column (minutes)
    pl.lit("37 C (inferred)").alias("control treatment temperature") # add control temperature column
).drop(
    drop_columns_list
)

PRJEB73803_filtered = PRJEB73803[[s.name for s in PRJEB73803 if not (s.null_count() == PRJEB73803.height)]]

PRJEB73803_filtered.write_csv(
    "../../Data/metadata/metadata_bioproject/PRJEB73803_modified_metadata.tsv",
    separator="\t"
)


# display(PRJEB73803_filtered)

In [63]:
defined_pairs_prjeb73803 = [
    ("ERR12737081", "ERR12737079"), # E-MTAB-13903:MCF10A_HS_2h vs E-MTAB-13903:MCF10A_CTR_2h
    ("ERR12737082", "ERR12737080"), # E-MTAB-13903:MCF10A_HS_4h vs E-MTAB-13903:MCF10A_CTR_4h
    ("ERR12737085", "ERR12737083"), # E-MTAB-13903:MCF7_HS_2h vs E-MTAB-13903:MCF7_CTR_2h
    ("ERR12737086", "ERR12737084")  # E-MTAB-13903:MCF7_HS_4h vs E-MTAB-13903:MCF7_CTR_4h
]

paired_metadata_df_prjeb73803 = create_paired_metadata(
    combined_df=PRJEB73803_filtered,
    defined_sample_pairs=defined_pairs_prjeb73803,
    sample_id_column_name="accession"
)

if paired_metadata_df_prjeb73803 is not None:
    paired_metadata_df_prjeb73803.write_csv(
        "../../Data/metadata/metadata_paired/prjeb73803_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_prjeb73803)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 63)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample_he ┆ sample_co ┆ run_acces ┆ experimen ┆ … ┆ reference ┆ stress    ┆ stress    ┆ control  │
│ at_id     ┆ ntrol_id  ┆ sion      ┆ t_title   ┆   ┆ _doi      ┆ treatment ┆ treatment ┆ treatmen │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ temperatu ┆ time      ┆ t temper │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ re        ┆ ---       ┆ ature    │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ERR127370 ┆ ERR127370 ┆ ERR127370 ┆ Illumina  ┆ … ┆ unknown   ┆ 43 C      ┆ 60 min.   ┆ unknown  │
│ 81        ┆ 79        ┆ 81 vs ERR ┆ NovaSeq   ┆   ┆           ┆           ┆           ┆ (maybe   │
│           ┆           ┆ 12737079  ┆ 6000 sequ ┆   ┆           ┆           ┆           ┆ 37 C)    │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Searching ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ for the   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ fusion    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ transcrip ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ts        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ created   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ during    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ proteotox ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ic stress ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ERR127370 ┆ ERR127370 ┆ ERR127370 ┆ Illumina  ┆ … ┆ unknown   ┆ 43 C      ┆ 60 min.   ┆ unknown  │
│ 86        ┆ 84        ┆ 86 vs ERR ┆ NovaSeq   ┆   ┆           ┆           ┆           ┆ (maybe   │
│           ┆           ┆ 12737084  ┆ 6000 sequ ┆   ┆           ┆           ┆           ┆ 37 C)    │
│           ┆           ┆           ┆ encing:   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Searching ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ for the   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ fusion    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ transcrip ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ts        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ created   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ during    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ proteotox ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ic stress ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

&nbsp;

&nbsp;

&nbsp;

---

&nbsp;

&nbsp;

&nbsp;

### [../../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md](../../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md)から移行したヒット

- [../../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md](../../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md)で、PRO-seqなどではないものの、今後使用できそうなデータを以下に記載する

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE63655 (SINGLE) Cap-seq

- validate date: 2026-02-21
- 熱ストレスに関連するPRO-seqを探索した結果で発見されたデータ
- - [gds_other_result_summary_260123_modified_proseq.md](../../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified_proseq.md)
- [Chemical pulldown reveals dynamic pseudouridylation of the mammalian transcriptome](https://doi.org/10.1038/nchembio.1836)
- `Cap-seq`という最近見ない手法
- [illumina: CAP-seq](https://jp.illumina.com/science/sequencing-method-explorer/kits-and-arrays/cap-seq.html)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [64]:
GSE63655_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE63655/GSE63655_PEP/GSE63655_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_organism_ch1") == "Homo sapiens")
)

display(GSE63655_PEP)

shape: (26, 43)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ library_s ┆ genome_bu ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ trategy   ┆ ild       ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ wt_input_ ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ CAP-seq   ┆ hg19, mm9 ┆ https://w ┆ https://w │
│ rep1      ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN03 ┆ m=SRX7686 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 222655    ┆ 19        │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ ko_pulldo ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ CAP-seq   ┆ hg19, mm9 ┆ https://w ┆ https://w │
│ wn_rep2   ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN03 ┆ m=SRX7686 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 222670    ┆ 44        │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE73405 (SINGLE) par-iclip / m6A profiling

- [5′ UTR m6A Promotes Cap-Independent Translation](https://doi.org/10.1016/j.cell.2015.10.012)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [65]:
GSE73405_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE73405/GSE73405_PEP/GSE73405_PEP_raw.csv",
    separator=','
)

display(GSE73405_PEP)

shape: (7, 48)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ genome_bu ┆ supplemen ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ild       ┆ tary_file ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ s_format_ ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ and_conte ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ nt        ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ eif3a_par ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ hg19      ┆ Peak-call ┆ https://w ┆ https://w │
│ -iclip_re ┆          ┆ sapiens   ┆           ┆   ┆           ┆ ing for   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ plicate1  ┆          ┆           ┆           ┆   ┆           ┆ processed ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ files was ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ performed ┆ le/SAMN04 ┆ m=SRX1287 │
│           ┆          ┆           ┆           ┆   ┆           ┆ using     ┆ 110551    ┆ 379       │
│           ┆          ┆           ┆           ┆   ┆           ┆ Pyicoclip ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ hepg2_con ┆ other    ┆ Homo      ┆ PAIRED    ┆ … ┆ hg19      ┆ m6A sites ┆ https://w ┆ https://w │
│ trol_2    ┆          ┆ sapiens   ┆           ┆   ┆           ┆ were iden ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ tified    ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ from      ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ single    ┆ le/SAMN04 ┆ m=SRX1508 │
│           ┆          ┆           ┆           ┆   ┆           ┆ reads     ┆ 377521    ┆ 526       │
│           ┆          ┆           ┆           ┆   ┆           ┆ using     ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ CIMS (C2T ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ transitio ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ns,       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ p=0.1).   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ Metagene  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ profiles  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ were      ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ performed ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ using     ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ hg19      ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ genomic   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ annotatio ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ns. For   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ HEK       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ control   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ samples,  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ miCLIP    ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ data from ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ Linder et ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ al…       ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE75418 CLIP-seq

- [iCLIP identifies novel roles for SAFB1 in regulating RNA processing and neuronal function](https://doi.org/10.1186/s12915-015-0220-7)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- 熱ストレスに関連していない可能性があるな... と思っていたが、この研究で注目しているSAFB1 には以下のような記述があった
- `Following heat stress, SAFB1 translocates to nuclear stress bodies together with HSF1 and Sam68. It has been hypothesised that nuclear stress bodies may sequester splicing factors to downregulate normal cellular splicing and facilitate the processing of RNA transcripts that are essential for the stress response [10, 24].`
- つまり、このSAFB1の結合部位などを調べることができれば、よりlncRNA-miRNA-mRNAの解析に有用である可能性があるため、収集する

In [66]:
GSE75418_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE75418/GSE75418_PEP/GSE75418_PEP_raw.csv",
    separator=','
)

display(GSE75418_PEP)

shape: (7, 46)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ genome_bu ┆ supplemen ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ild       ┆ tary_file ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ s_format_ ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ and_conte ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ nt        ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ---       ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1_safb1_i ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ hg19/GRCh ┆ Gene coor ┆ https://w ┆ https://w │
│ clip      ┆          ┆ sapiens   ┆           ┆   ┆ 37        ┆ dinates   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ (columns  ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ 1-4),     ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ gene      ┆ le/SAMN04 ┆ m=SRX1453 │
│           ┆          ┆           ┆           ┆   ┆           ┆ name,     ┆ 299703    ┆ 676       │
│           ┆          ┆           ┆           ┆   ┆           ┆ gene      ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ segment   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ type and  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ biotype,  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ and tag   ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ sums for  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ each expt ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 6_safb1_i ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ hg19/GRCh ┆ Kmer      ┆ https://w ┆ https://w │
│ clip      ┆          ┆ sapiens   ┆           ┆   ┆ 37        ┆ Z-scores: ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆ z-score 1 ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆ processed ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆ from      ┆ le/SAMN04 ┆ m=SRX1473 │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample 1  ┆ 329926    ┆ 616       │
│           ┆          ┆           ┆           ┆   ┆           ┆ SAFB1 (GS ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ M1954829) ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ ; z-score ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ processed ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ from      ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ sample 2  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ SAFB1(GSM ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ 1954830)  ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆           ┆ etc.      ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE105028 (eU-seq, ~~Hi-C,~~ ~~Hi-ChIP,~~ ~~ChIP-seq~~, ~~ATAC-seq~~ )

- [Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress](https://doi.org/10.1016/j.molcel.2018.07.012)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- ATAC-seq のデータは、[./12_8_metadata_atacseq.ipynb](./12_8_metadata_atacseq.ipynb)に移動
- ChIP-seq のデータは、[./12_8_metadata_chipseq.ipynb](./12_8_metadata_chipseq.ipynb)に移動

In [67]:
GSE105028_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE105028/GSE105028_PEP/GSE105028_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("library_strategy") == "eU-Seq")
)

pl.Config.set_tbl_rows(38)
display(GSE105028_PEP)

shape: (2, 44)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ library_s ┆ genome_bu ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ trategy   ┆ ild       ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ eu-seq    ┆ other    ┆ Homo      ┆ PAIRED    ┆ … ┆ eU-Seq    ┆ hg38      ┆ https://w ┆ https://w │
│           ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN07 ┆ m=SRX3288 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 790041    ┆ 552       │
│ hs_eu-seq ┆ other    ┆ Homo      ┆ PAIRED    ┆ … ┆ eU-Seq    ┆ hg38      ┆ https://w ┆ https://w │
│           ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN07 ┆ m=SRX3288 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 790040    ┆ 553       │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE105028 (Hi-C, Hi-ChIP, ~~eU-seq,~~ ~~ChIP-seq~~, ~~ATAC-seq~~ )

- [Architectural Proteins and Pluripotency Factors Cooperate to Orchestrate the Transcriptional Response of hESCs to Temperature Stress](https://doi.org/10.1016/j.molcel.2018.07.012)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- ATAC-seq のデータは、[./12_8_metadata_atacseq.ipynb](./12_8_metadata_atacseq.ipynb)に移動
- ChIP-seq のデータは、[./12_8_metadata_chipseq.ipynb](./12_8_metadata_chipseq.ipynb)に移動
- [./12_8_metadata_hic.ipynb](./12_8_metadata_hic.ipynb)に移動

In [68]:
# GSE105028_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE105028/GSE105028_PEP/GSE105028_PEP_raw.csv",
#     separator=','
# ).filter(
#     (pl.col("library_strategy") != "ATAC-Seq") &
#     (pl.col("library_strategy") != "ChIP-Seq") &
#     (pl.col("library_strategy") != "eU-Seq")
# ).sort(
#     "srr",
#     descending=False
# )

# GSE105028_PEP.write_csv(
#     "../../Data/metadata/metadata_hic/GSE105028_PEP_raw_filtered.tsv",
#     separator='\t'
# )

# pl.Config.set_tbl_rows(38)
# display(GSE105028_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE130758 Hi-C

- validate date: 2026-02-22
- [Chromatin conformation remains stable upon extensive transcriptional changes driven by heat shock](https://doi.org/10.1073/pnas.1901244116)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- [./12_8_metadata_hic.ipynb](./12_8_metadata_hic.ipynb)に移動

In [69]:
# GSE130758_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE130758/GSE130758_PEP/GSE130758_PEP_raw.csv",
#     separator=','
# )

# GSE130758_PEP.write_csv(
#     "../../out/Hi-C/GSE130758_PEP_raw_filtered.tsv",
#     separator='\t'
# )

# display(GSE130758_PEP)

&nbsp;

&nbsp;

&nbsp;

### GSE164200 (SINGLE) m6A-RIP-seq

- validate date: 2026-02-22
- [m6 A modification of HSATIII lncRNAs regulates temperature-dependent splicing](https://doi.org/10.15252/embj.2021107976)
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- [./12_7_metadata_meripseq.ipynb](./12_7_metadata_meripseq.ipynb)に処理を移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE169435 (SINGLE) Genome Sequence with MiNION

- validate date: 2026-02-22
- [Chimeric chromosome landscapes of human somatic cell cultures show dependence on stress and regulation of genomic repeats by CGGBP1](https://doi.org/10.18632/oncotarget.28174)
- [./12_8_metadata_other_seq.ipynb](./12_8_metadata_other_seq.ipynb)に処理を移動
- Library source が`genomic`で使えるかわからないが...

In [70]:
GSE169435_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE169435/GSE169435_PEP/GSE169435_PEP_raw.csv",
    separator=','
)

display(GSE169435_PEP)

shape: (15, 46)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_na ┆ protocol ┆ organism  ┆ read_type ┆ … ┆ library_s ┆ genome_bu ┆ biosample ┆ sra       │
│ me        ┆ ---      ┆ ---       ┆ ---       ┆   ┆ trategy   ┆ ild       ┆ ---       ┆ ---       │
│ ---       ┆ str      ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str       │
│ str       ┆          ┆           ┆           ┆   ┆ str       ┆ str       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ gm02639_- ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ _37°c     ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439514    ┆ 1006      │
│ gm02639_- ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ _40°c     ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439513    ┆ 1007      │
│ gm02639_- ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ _recovery ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439512    ┆ 1008      │
│ hek293t_c ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ t_-_37°c  ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439511    ┆ 1009      │
│ hek293t_c ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ t_-_42°c  ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439510    ┆ 1010      │
│ hek293t_c ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ t_-_recov ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ery       ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439508    ┆ 1011      │
│ hek293t_k ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ d_-_37°c  ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439507    ┆ 1012      │
│ hek293t_k ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ d_-_42°c  ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439506    ┆ 1013      │
│ hek293t_k ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ Oxford    ┆ hg38      ┆ https://w ┆ https://w │
│ d_-_recov ┆          ┆ sapiens   ┆           ┆   ┆ Nanopore  ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ery       ┆          ┆           ┆           ┆   ┆ Long-read ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆ sequencin ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆ g         ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439505    ┆ 1014      │
│ tp53bp1_c ┆ ChIP     ┆ Homo      ┆ SINGLE    ┆ … ┆ null      ┆ hg38      ┆ https://w ┆ https://w │
│ t         ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439504    ┆ 1015      │
│ tp53bp1_k ┆ ChIP     ┆ Homo      ┆ SINGLE    ┆ … ┆ null      ┆ hg38      ┆ https://w ┆ https://w │
│ d         ┆          ┆ sapiens   ┆           ┆   ┆           ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN18 ┆ m=SRX1042 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 439503    ┆ 1016      │
│ gm01391-c ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ MeDIP-seq ┆ hg38      ┆ https://w ┆ https://w │
│ t_daughte ┆          ┆ sapiens   ┆           ┆   ┆           ┆ (UCSC;    ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ r_fibrobl ┆          ┆           ┆           ┆   ┆           ┆ unmasked) ┆ lm.nih.go ┆ lm.nih.go │
│ ast       ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN22 ┆ m=SRX1281 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 636228    ┆ 2094      │
│ gm01391-k ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ MeDIP-seq ┆ hg38      ┆ https://w ┆ https://w │
│ d_daughte ┆          ┆ sapiens   ┆           ┆   ┆           ┆ (UCSC;    ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ r_fibrobl ┆          ┆           ┆           ┆   ┆           ┆ unmasked) ┆ lm.nih.go ┆ lm.nih.go │
│ ast       ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN22 ┆ m=SRX1281 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 636229    ┆ 2095      │
│ gm01392_m ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ null      ┆ hg38      ┆ https://w ┆ https://w │
│ aternal_f ┆          ┆ sapiens   ┆           ┆   ┆           ┆ (UCSC;    ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ibroblast ┆          ┆           ┆           ┆   ┆           ┆ unmasked) ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN22 ┆ m=SRX1281 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 636230    ┆ 2096      │
│ gm01393_p ┆ other    ┆ Homo      ┆ SINGLE    ┆ … ┆ null      ┆ hg38      ┆ https://w ┆ https://w │
│ aternal_f ┆          ┆ sapiens   ┆           ┆   ┆           ┆ (UCSC;    ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ ibroblast ┆          ┆           ┆           ┆   ┆           ┆ unmasked) ┆ lm.nih.go ┆ lm.nih.go │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ le/SAMN22 ┆ m=SRX1281 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 636231    ┆ 2097      │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE197247 m6A MeRIP-seq

- validate date: 2026-02-22
- [m6A modification confers thermal vulnerability to HPV E7 oncotranscripts via reverse regulation of its reader protein IGF2BP1 upon heat stress](https://doi.org/10.1016/j.celrep.2022.111546)
- 熱ストレスとコントロールのデータが揃っている
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [71]:
GSE197247_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE197247/GSE197247_PEP/GSE197247_PEP_raw.csv",
    separator=','
)

display(GSE197247_PEP)

shape: (4, 46)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ genome_bu ┆ supplemen ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ild       ┆ tary_file ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ ---       ┆ s_format_ ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆ str       ┆ and_conte ┆           ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆ nt        ┆           ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆ ---       ┆           ┆           │
│            ┆          ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ caski_ip_c ┆ null     ┆ null     ┆ null      ┆ … ┆ hg19      ┆ excel     ┆ https://w ┆ https://w │
│ trl        ┆          ┆          ┆           ┆   ┆           ┆ format:   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆           ┆ Number of ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆ raw       ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆ junction  ┆ le/SAMN26 ┆ m=SRX1425 │
│            ┆          ┆          ┆           ┆   ┆           ┆ read      ┆ 179596    ┆ 6968      │
│ caski_inpu ┆ null     ┆ null     ┆ null      ┆ … ┆ hg19      ┆ excel     ┆ https://w ┆ https://w │
│ t_ctrl     ┆          ┆          ┆           ┆   ┆           ┆ format:   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆           ┆ Number of ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆ raw       ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆ junction  ┆ le/SAMN26 ┆ m=SRX1425 │
│            ┆          ┆          ┆           ┆   ┆           ┆ read      ┆ 179595    ┆ 6969      │
│ caski_ip_t ┆ null     ┆ null     ┆ null      ┆ … ┆ hg19      ┆ excel     ┆ https://w ┆ https://w │
│ reat       ┆          ┆          ┆           ┆   ┆           ┆ format:   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆           ┆ Number of ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆ raw       ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆ junction  ┆ le/SAMN26 ┆ m=SRX1425 │
│            ┆          ┆          ┆           ┆   ┆           ┆ read      ┆ 179594    ┆ 6970      │
│ caski_inpu ┆ null     ┆ null     ┆ null      ┆ … ┆ hg19      ┆ excel     ┆ https://w ┆ https://w │
│ t_treat    ┆          ┆          ┆           ┆   ┆           ┆ format:   ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆           ┆ Number of ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆ raw       ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆ junction  ┆ le/SAMN26 ┆ m=SRX1425 │
│            ┆          ┆          ┆           ┆   ┆           ┆ read      ┆ 179593    ┆ 6971      │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE200269 PRO-IP-seq

- validate date: 2026-02-22
- [PRO-IP-seq tracks molecular modifications of engaged Pol II complexes at nucleotide resolution](https://doi.org/10.1038/s41467-023-42715-3)
- この`PRO-IP-seq`について、特性をまだ把握できていないので一旦こちらに記載
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)に処理を再度移動 (2026-07-23)

In [72]:
# GSE200269_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE200269/GSE200269_PEP/GSE200269_PEP_raw.csv",
#     separator=','
# )

# pl.Config.set_tbl_rows(32)
# display(GSE200269_PEP)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE233582 FLAM-seq

- validate date: 2026-02-23
- [RNA tailing machinery drives amyloidogenic phase transition](https://doi.org/10.1073/pnas.2316734121)
- Full-Length-and-mRNA Sequencing (FLAM-seq) という手法のデータ
- 熱ストレス条件に関しても以下のような条件があるため収集
- `Cells were subjected to heat shock by translocation to a 5% CO2 humidified incubator at 43 °C for indicated times.`
- `FLAM seq was performed as described (38). Nucleolar isolation was performed as described above. RNA was extracted using TRIzol reagent from nucleoli/Abodies and was submitted for pooled RNA to yield a no treatment sample and 60-min heat shock sample.`
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [73]:
GSE233582_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE233582/GSE233582_PEP/GSE233582_PEP_raw.csv",
    separator=','
)

display(GSE233582_PEP)

shape: (6, 47)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ assembly  ┆ library_s ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---       ┆ trategy   ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ nucleoli_- ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ rep1       ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439845    ┆ 5451      │
│ nucleoli_- ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ rep2       ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439844    ┆ 5452      │
│ nucleoli_- ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ rep3       ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439843    ┆ 5453      │
│ amyloid-bo ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ dies_rep1  ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439842    ┆ 5454      │
│ amyloid-bo ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ dies_rep2  ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439841    ┆ 5455      │
│ amyloid-bo ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ FLAM-seq  ┆ https://w ┆ https://w │
│ dies_rep3  ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│            ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN35 ┆ m=SRX2052 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 439840    ┆ 5456      │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE261857 ISO-seq

- validate date: 2026-02-23
- [Nucleolar Pol II interactome reveals TBPL1, PAF1, and Pol I at intergenic rDNA drive rRNA biogenesis](https://doi.org/10.1038/s41467-024-54002-w)
- 論文に以下のような記載があったため、収集する
- `Cells under standard conditions (37 °C) or sincRNA-hyper-inducing conditions (43 °C for 1 h) were washed with PBS, harvested in solution 1 (0.5 M sucrose, 3 mM MgCl2) at 4 °C, and sonicated on ice for 5 × 10 sec using a microtip probe.`
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [74]:
GSE261857_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE261857/GSE261857_PEP/GSE261857_PEP_raw.csv",
    separator=','
)

display(GSE261857_PEP)

shape: (6, 47)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ assembly  ┆ library_s ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---       ┆ trategy   ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ unstressed ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ _nucleoli_ ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ rep1       ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533214    ┆ 5220      │
│ unstressed ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ _nucleoli_ ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ rep2       ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533213    ┆ 5221      │
│ unstressed ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ _nucleoli_ ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ rep3       ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533212    ┆ 5222      │
│ heat_shock ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ ed_nucleol ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ i_rep1     ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533211    ┆ 5223      │
│ heat_shock ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ ed_nucleol ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ i_rep2     ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533210    ┆ 5224      │
│ heat_shock ┆ null     ┆ null     ┆ null      ┆ … ┆ GRCh38.pr ┆ ISO-seq   ┆ https://w ┆ https://w │
│ ed_nucleol ┆          ┆          ┆           ┆   ┆ imary_ass ┆           ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ i_rep3     ┆          ┆          ┆           ┆   ┆ embly.gen ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆ ome.fa    ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN40 ┆ m=SRX2398 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 533209    ┆ 5225      │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE277764 Nanopore

- validate date: 2026-02-23
- [De novo assembly of nuclear stress bodies rearranges and enhances NFIL3 to restrain acute inflammatory responses](https://doi.org/10.1016/j.cell.2025.05.003)
- sodium arsenite (SA) のデータはフィルタリングして収集する
- 論文に以下のような記述があるため収集する
- `For heat shock (HS) treatment, Human HeLa, THP-1 cells and HUVECs were replaced with pre-heated (42°C) conditioned medium and incubated in a culture incubator with an environmental temperature at 42°C and humidified 5% CO2 for 2 h, then recovered at 37°C for 1 h.`
- [./12_7_metadata_proseq.ipynb](./12_7_metadata_proseq.ipynb)から処理を移動

In [75]:
GSE277764_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE277764/GSE277764_PEP/GSE277764_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_taxid_ch1") == 9606) &
    (~pl.col("sample_title").str.contains("_SA_"))
)

display(GSE277764_PEP)

shape: (8, 41)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample_nam ┆ protocol ┆ organism ┆ read_type ┆ … ┆ treatment ┆ assembly  ┆ biosample ┆ sra       │
│ e          ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---        ┆ str      ┆ str      ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
│ str        ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ nanopore_p ┆ null     ┆ null     ┆ null      ┆ … ┆ untreated ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ olya_plus_ ┆          ┆          ┆           ┆   ┆           ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ un_rep1    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878907    ┆ 4613      │
│ nanopore_p ┆ null     ┆ null     ┆ null      ┆ … ┆ untreated ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ olya_plus_ ┆          ┆          ┆           ┆   ┆           ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ un_rep2    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878906    ┆ 4614      │
│ nanopore_p ┆ null     ┆ null     ┆ null      ┆ … ┆ HS        ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ olya_plus_ ┆          ┆          ┆           ┆   ┆ stressed  ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ hs_rep1    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878905    ┆ 4615      │
│ nanopore_p ┆ null     ┆ null     ┆ null      ┆ … ┆ HS        ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ olya_plus_ ┆          ┆          ┆           ┆   ┆ stressed  ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ hs_rep2    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878904    ┆ 4616      │
│ nanopore_r ┆ null     ┆ null     ┆ null      ┆ … ┆ untreated ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ ibo_minus_ ┆          ┆          ┆           ┆   ┆           ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ un_rep1    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878901    ┆ 4619      │
│ nanopore_r ┆ null     ┆ null     ┆ null      ┆ … ┆ untreated ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ ibo_minus_ ┆          ┆          ┆           ┆   ┆           ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ un_rep2    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878900    ┆ 4620      │
│ nanopore_r ┆ null     ┆ null     ┆ null      ┆ … ┆ HS        ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ ibo_minus_ ┆          ┆          ┆           ┆   ┆ stressed  ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ hs_rep1    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878899    ┆ 4621      │
│ nanopore_r ┆ null     ┆ null     ┆ null      ┆ … ┆ HS        ┆ CHM13 T2T ┆ https://w ┆ https://w │
│ ibo_minus_ ┆          ┆          ┆           ┆   ┆ stressed  ┆ v2.0      ┆ ww.ncbi.n ┆ ww.ncbi.n │
│ hs_rep2    ┆          ┆          ┆           ┆   ┆           ┆           ┆ lm.nih.go ┆ lm.nih.go │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ v/biosamp ┆ v/sra?ter │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ le/SAMN43 ┆ m=SRX2616 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ 878898    ┆ 4622      │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

### GSE280307 ATAC-seq

- validate date: 2026-02-23
- [De novo assembly of nuclear stress bodies rearranges and enhances NFIL3 to restrain acute inflammatory responses](https://doi.org/10.1016/j.cell.2025.05.003)
- [GSE277764](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE277764)のNanoporeのデータに加えて、上記の論文で登録されているデータ
- [./12_8_metadata_atacseq.ipynb](./12_8_metadata_atacseq.ipynb) に移動

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## GSE280712 (TSA-seq)

- validate date: 2026-02-23
- [De novo assembly of nuclear stress bodies rearranges and enhances NFIL3 to restrain acute inflammatory responses](https://doi.org/10.1016/j.cell.2025.05.003)
- [GSE277764](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE277764)のNanoporeのデータに加えて、上記の論文で登録されているデータ
- 念の為、熱ストレスに関連しているデータがあることを記載しておくと思ったが、コントロール条件下のデータが存在しないため、今回は収集しない

In [76]:
# GSE280712_PEP = pl.read_csv(
#     "../../Data/metadata/metadata_geofetch/GSE280712/GSE280712_PEP/GSE280712_PEP_raw.csv",
#     separator=','
# ).filter(
#     (pl.col("sample_taxid_ch1") == 9606) &
#     (~pl.col("sample_title").str.contains("_SA_"))
# )

# display(GSE280712_PEP)