&nbsp;

# PRO-seq related Metadata validated and modified process

## Background

- lncRNA が転写されているのか、bulk RNA-seq だけではない観点から検証するため、GENCODE v49 をアノテーションとして **PRO-seqのメタ解析** を実行しようと考えている
- これまで、いくつか熱ストレスに関連しているPRO-seqのデータや、意識してこなかったが、その他にもメタ解析ができるくらいのPRO-seqのデータが蓄積している可能性がある。
- そのため、ここでは、これまで取得されてきたPRO−seqのメタデータの処理を移行し、まとめる他、新たに検索し、使用できそうなデータもここに記載する
- (2026-02-21) GRO-seqのデータもこちらに記載する
- (2026-07-11) `bigwigaverageoverbed` ツールで、`fanta.bio`のCRE アノテーションと PRO-seq のピークを統合する
- (2026-07-22) adapter を調査する (e.g., [Illumina TruSeq-SmallRNA adapter](https://support-docs.illumina.com/SHARE/AdapterSequences/Content/TruSeq-SmallRNA.htm))

In [1]:
import sys
import polars as pl
import datetime
import pathlib
from typing import Any
sys.path.append(str(pathlib.Path('../../').resolve()))
from scripts.metadata_pairing import create_paired_metadata
from IPython.display import display

pl.Config.set_fmt_str_lengths(200)
pl.Config.set_tbl_cols(200)
pl.Config.set_tbl_rows(4)

polars.config.Config

In [2]:
VERSION = datetime.datetime.now().strftime("%y%m")
execute_date = datetime.datetime.now().strftime("%y%m%d")
print(f"Execute Date: {execute_date}")

# create directory
pathlib.Path(f"../../Data/metadata/metadata_{VERSION}").mkdir(parents=True, exist_ok=True)

Execute Date: 261001

In [3]:
# drop columns list for iseq metadata
drop_columns_list = [
    "sra_aspera",
    "fastq_galaxy",
    "sra_galaxy",
    "fastq_ftp",
    "sra_ftp",
    "fastq_aspera",
    "tax_lineage",
    "bam_md5",
    "fastq_md5",
    "sra_md5"
]

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 1. GSE228346 PRO-seq (SINGLE)

- ✅ DOWNLOAD
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validate date: 2025-05-02
- validate date: 2026-02-19

&nbsp;

- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb) で得られたデータ
- [TFIIH kinase CDK7 drives cell proliferation through a common core transcription factor network](https://doi.org/10.1126/sciadv.adr9660)
- DMSOで処理されたコントロールと42℃で処理された熱ストレスのサンプル (例: `DMSO_0_R1, DMSO_20_R1`) と、CDK阻害剤である `SY5609` を処理された状態でのコントロールと熱ストレスの状態 ( `SY5609_0_R1, SY5609_20_R1`) が存在する

&nbsp;

### Adapter

- 以下のような記述がある
- `A single-ended library preparation using Illumina TruSeq Small RNA adapters was prepared as described in Mahat et al. (62) and adapter clean-up was performed with 1× AMPure XP beads (Beckman A63880).`

In [4]:
GSE228346_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE228346/GSE228346_PEP/GSE228346_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("KAPA mRNA HyperPrep Kit").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1126/sciadv.adr9660").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# PRO-seq metadata
GSE228346_PEP_pro_seq = GSE228346_PEP.filter(
    (pl.col("sample_library_selection") == "other") &
    (pl.col("library_strategy") == "PRO-seq")
).with_columns(
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
)

# metadata from iseq
GSE228346_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE228346_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE228346_iseq_filtered = GSE228346_iseq[[s.name for s in GSE228346_iseq if not (s.null_count() == GSE228346_iseq.height)]]

In [5]:
GSE228346_pro_seq_combined = GSE228346_PEP_pro_seq.join(
    GSE228346_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE228346_pro_seq_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE228346_pro_seq_modified_metadata.tsv",
    separator='\t'
)

pl.Config.set_tbl_rows(2)
display(GSE228346_pro_seq_combined)

shape: (12, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ tim ┆ mol ┆ lib ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ acc ┆ sec ┆ fir ┆ stu │
│ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ e   ┆ ecu ┆ rar ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ess ┆ ond ┆ st_ ┆ dy_ │
│ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ --- ┆ le_ ┆ y_s ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ion ┆ ary ┆ pub ┆ ali │
│ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ i64 ┆ sub ┆ tra ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ --- ┆ _sa ┆ lic ┆ as  │
│ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆     ┆ typ ┆ teg ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ i64 ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ str ┆ mpl ┆ --- ┆ --- │
│ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ e   ┆ y   ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ i64 ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ i64 ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆     ┆ e_a ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ s_f ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆     ┆ cce ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ i64 ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ orm ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ i64 ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ i64 ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ i64 ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ dms ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ DMS ┆ GSM ┆ Pub ┆ Mar ┆ Dec ┆ SRA ┆ 1   ┆ wil ┆ Hom ┆ 960 ┆ tot ┆ PRO ┆ GPL ┆ Tay ┆ taj ┆ 360 ┆ Uni ┆ 341 ┆ Bou ┆ CO  ┆ 803 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Wil ┆ ova ┆ 30m ┆ 30  ┆ Nas ┆ PRO ┆ hg3 ┆ NOT ┆ SAM ┆ KAP ┆ htt ┆ Ill ┆ SRR ┆ Ill ┆ The ┆ SRA ┆ oth ┆ 202 ┆ 199 ┆ 284 ┆ ILL ┆ Gen ┆ DMS ┆ SRP ┆ 795 ┆ The ┆ DMS ┆ Ill ┆ Ill ┆ ova ┆ 580 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ Wil ┆ GSM ┆ 202 ┆ PRJ ┆ SRR ┆ SRS ┆ 202 ┆ GSE │
│ o_0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ O_0 ┆ 711 ┆ lic ┆ 28  ┆ 19  ┆     ┆     ┆ d   ┆ o   ┆ 6   ┆ al  ┆ -se ┆ 246 ┆ lor ┆ o59 ┆ 624 ┆ ver ┆ 5   ┆ lde ┆     ┆ 01  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 711 ┆ E   ┆ 228 ┆     ┆ 197 ┆ d-t ┆ ria ┆ in  ┆     ┆ cen ┆ -se ┆ 8   ┆ PRO ┆ N33 ┆ A   ┆ ps: ┆ umi ┆ 239 ┆ umi ┆ TFI ┆ 161 ┆ er  ┆ 4-1 ┆ 525 ┆ 777 ┆ UMI ┆ eri ┆ O_0 ┆ 429 ┆ 906 ┆ TFI ┆ O_0 ┆ umi ┆ umi ┆ ria ┆ 522 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 711 ┆ 711 ┆ -se ┆ 711 ┆ d-t ┆ 711 ┆ 4-1 ┆ NA9 ┆ 239 ┆ 171 ┆ 4-1 ┆ 228 │
│ _r1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _R1 ┆ 923 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ typ ┆ sap ┆     ┆ RNA ┆ q   ┆ 76  ┆ ,K, ┆ 12@ ┆ 661 ┆ sit ┆ Col ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 923 ┆     ┆ 346 ┆     ┆ 932 ┆ ype ┆ n   ┆ pre ┆     ┆ t   ┆ q   ┆     ┆ VID ┆ 946 ┆ mRN ┆ //d ┆ na  ┆ 893 ┆ na  ┆ IH  ┆ 189 ┆     ┆ 2-2 ┆ 366 ┆ 564 ┆ NA  ┆ c   ┆ _R1 ┆ 713 ┆ 55  ┆ IH  ┆ _R1 ┆ na  ┆ na  ┆ n   ┆ 415 ┆     ┆ RIP ┆     ┆     ┆ 923 ┆ 923 ┆ q:  ┆ 923 ┆ ype ┆ 923 ┆ 2-2 ┆ 495 ┆ 893 ┆ 556 ┆ 2-2 ┆ 346 │
│ _pr ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆ 1   ┆ Dec ┆ 3   ┆ 4   ┆     ┆     ┆ e   ┆ ien ┆     ┆     ┆ fro ┆     ┆ Jon ┆ col ┆ 2   ┆ y   ┆ ora ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 1   ┆     ┆     ┆     ┆ 72  ┆ OV9 ┆ can ┆ tre ┆     ┆ RNA ┆     ┆     ┆ ED  ┆ 087 ┆ A   ┆ oi. ┆ Tru ┆ 99  ┆ Nov ┆ kin ┆ 3   ┆     ┆ 9   ┆ 4   ┆ 5   ┆     ┆     ┆ [PR ┆     ┆     ┆ kin ┆ [PR ┆ Nov ┆ Nov ┆ can ┆ 5   ┆     ┆ TOM ┆     ┆     ┆ 1   ┆ 1_r ┆ Cel ┆ 1_r ┆ OV9 ┆ 1   ┆ 9   ┆ 15  ┆ 99  ┆ 89  ┆ 9   ┆     │
│ o-s ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆     ┆ 19  ┆     ┆     ┆     ┆     ┆ OV9 ┆ s   ┆     ┆     ┆ m   ┆     ┆ es  ┆ ora ┆     ┆ of  ┆ do  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ cer ┆ atm ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hyp ┆ org ┆ Seq ┆     ┆ aSe ┆ ase ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆     ┆     ┆ ase ┆ O-s ┆ aSe ┆ aSe ┆ cer ┆     ┆     ┆ IC  ┆     ┆     ┆     ┆ 1   ┆ ls  ┆ 1   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ OV9 ┆     ┆     ┆ do. ┆     ┆ Col ┆ Ave ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆ ent ┆     ┆     ┆     ┆     ┆     ┆     ┆ erP ┆ /10 ┆ Sma ┆     ┆ q   ┆ CDK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆ CDK ┆ eq] ┆ q   ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wer ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ edu ┆     ┆ ora ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆ .11 ┆ ll  ┆     ┆ 600 ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ 600 ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ do  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆ 26/ ┆ RNA ┆     ┆ 0   ┆ gov ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gov ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆ Bou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sci ┆ ada ┆     ┆ seq ┆ ern ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ern ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆ lde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ adv ┆ pte ┆     ┆ uen ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ har ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ad ┆ rs  ┆     ┆ cin ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ves ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _vi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r96 ┆     ┆     ┆ g:  ┆ pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pol ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rtu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60  ┆     ┆     ┆ GSM ┆ yme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ yme ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 711 ┆ ras ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ras ┆     ┆     ┆ 711 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ spi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 923 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 923 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kei ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1:  ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆     ┆ 1:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n_n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ ini ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ini ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_0 ┆ tia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tia ┆     ┆     ┆ O_0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _R1 ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ _R1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆ [PR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ O-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆ nga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nga ┆     ┆     ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ BS, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [6]:
# PRO-seq metadata
defined_pairs_gse228346_proseq = [
    # DMSO
    ("SRR23989395", "SRR23989399"), # DMSO_20_R1 [PRO-seq] vs DMSO_0_R1 [PRO-seq]
    ("SRR23989394", "SRR23989398"), # DMSO_20_R2 [PRO-seq] vs DMSO_0_R2 [PRO-seq]
    ("SRR23989382", "SRR23989399"), # DMSO_45_R1 [PRO-seq] vs DMSO_0_R1 [PRO-seq]
    ("SRR23989378", "SRR23989398"), # DMSO_45_R2 [PRO-seq] vs DMSO_0_R2 [PRO-seq]

    # SY5609
    ("SRR23989393", "SRR23989397"), # SY5609_20_R1 [PRO-seq] vs SY5609_0_R1 [PRO-seq]
    ("SRR23989392", "SRR23989396"), # SY5609_20_R2 [PRO-seq] vs SY5609_0_R2 [PRO-seq]
    ("SRR23989377", "SRR23989397"), # SY5609_45_R1 [PRO-seq] vs SY5609_0_R1 [PRO-seq]
    ("SRR23989376", "SRR23989396"), # SY5609_45_R2 [PRO-seq] vs SY5609_0_R2 [PRO-seq]
]


paired_metadata_gse228346_proseq = create_paired_metadata(
    GSE228346_pro_seq_combined,
    defined_pairs_gse228346_proseq,
    sample_id_column_name="accession"
)

if paired_metadata_gse228346_proseq is not None:
    paired_metadata_gse228346_proseq.write_csv(
        "../../Data/metadata/metadata_proseq/GSE228346_proseq_paired_metadata.tsv",
        separator='\t'
    )

pl.Config.set_tbl_rows(2)
display(paired_metadata_gse228346_proseq)

shape: (8, 86)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ tim ┆ mol ┆ lib ┆ ass ┆ sup ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ e   ┆ ecu ┆ rar ┆ emb ┆ ple ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ --- ┆ le_ ┆ y_s ┆ ly  ┆ men ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ str ┆ sub ┆ tra ┆ --- ┆ tar ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆     ┆ typ ┆ teg ┆ str ┆ y_f ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ e   ┆ y   ┆     ┆ ile ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ s_f ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ orm ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ dms ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ DMS ┆ GSM ┆ Pub ┆ Mar ┆ Dec ┆ SRA ┆ 1   ┆ wil ┆ Hom ┆ 960 ┆ tot ┆ PRO ┆ GPL ┆ Tay ┆ taj ┆ 360 ┆ Uni ┆ 341 ┆ Bou ┆ CO  ┆ 803 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ Wil ┆ ova ┆ 30m ┆ 50  ┆ Nas ┆ PRO ┆ hg3 ┆ NOT ┆ SAM ┆ KAP ┆ htt ┆ Ill ┆ SRR ┆ Ill ┆ The ┆ SRA ┆ oth ┆ 202 ┆ 180 ┆ 266 ┆ ILL ┆ Gen ┆ DMS ┆ SRP ┆ 720 ┆ The ┆ DMS ┆ Ill ┆ Ill ┆ ova ┆ 526 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ RNA ┆ GSM ┆ Wil ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 239 ┆ 239 ┆ o_2 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ O_2 ┆ 711 ┆ lic ┆ 28  ┆ 19  ┆     ┆     ┆ d   ┆ o   ┆ 6   ┆ al  ┆ -se ┆ 246 ┆ lor ┆ o59 ┆ 624 ┆ ver ┆ 5   ┆ lde ┆     ┆ 01  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 711 ┆ E   ┆ 228 ┆     ┆ 197 ┆ d-t ┆ ria ┆ in  ┆ vs  ┆ cen ┆ -se ┆ 8   ┆ PRO ┆ N33 ┆ A   ┆ ps: ┆ umi ┆ 239 ┆ umi ┆ TFI ┆ 161 ┆ er  ┆ 4-1 ┆ 808 ┆ 887 ┆ UMI ┆ eri ┆ O_2 ┆ 429 ┆ 944 ┆ TFI ┆ O_2 ┆ umi ┆ umi ┆ ria ┆ 862 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 711 ┆ 711 ┆ -se ┆ 711 ┆ d-t ┆ 711 ┆ 4-1 ┆ NA9 ┆ 171 ┆ 4-1 ┆ 228 │
│ 893 ┆ 893 ┆ 0_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_R ┆ 923 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ typ ┆ sap ┆     ┆ RNA ┆ q   ┆ 76  ┆ ,K, ┆ 12@ ┆ 661 ┆ sit ┆ Col ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 923 ┆     ┆ 346 ┆     ┆ 932 ┆ ype ┆ n   ┆ pre ┆ 30  ┆ t   ┆ q   ┆     ┆ VID ┆ 946 ┆ mRN ┆ //d ┆ na  ┆ 893 ┆ na  ┆ IH  ┆ 189 ┆     ┆ 2-2 ┆ 484 ┆ 630 ┆ NA  ┆ c   ┆ 0_R ┆ 713 ┆ 61  ┆ IH  ┆ 0_R ┆ na  ┆ na  ┆ n   ┆ 276 ┆     ┆ RIP ┆     ┆     ┆ 923 ┆ 923 ┆ q:  ┆ 923 ┆ ype ┆ 923 ┆ 2-2 ┆ 495 ┆ 556 ┆ 2-2 ┆ 346 │
│ 95  ┆ 99  ┆ 1_p ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 5   ┆ Dec ┆ 3   ┆ 4   ┆     ┆     ┆ e   ┆ ien ┆     ┆     ┆ fro ┆     ┆ Jon ┆ col ┆ 2   ┆ y   ┆ ora ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 5   ┆     ┆     ┆     ┆ 76  ┆ OV9 ┆ can ┆ tre ┆     ┆ RNA ┆     ┆     ┆ ED  ┆ 083 ┆ A   ┆ oi. ┆ Tru ┆ 95  ┆ Nov ┆ kin ┆ 3   ┆     ┆ 9   ┆ 3   ┆ 5   ┆     ┆     ┆ 1   ┆     ┆ vs  ┆ kin ┆ 1   ┆ Nov ┆ Nov ┆ can ┆ 1   ┆     ┆ TOM ┆     ┆     ┆ 5   ┆ 5_r ┆ Cel ┆ 5_r ┆ OV9 ┆ 5   ┆ 9   ┆ 15  ┆ 92  ┆ 9   ┆     │
│     ┆     ┆ ro- ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆ vs  ┆ 19  ┆     ┆     ┆     ┆     ┆ OV9 ┆ s   ┆     ┆     ┆ m   ┆     ┆ es  ┆ ora ┆     ┆ of  ┆ do  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ 0   ┆ cer ┆ atm ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ Hyp ┆ org ┆ Seq ┆ vs  ┆ aSe ┆ ase ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ [PR ┆     ┆ 795 ┆ ase ┆ [PR ┆ aSe ┆ aSe ┆ cer ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ls  ┆ 1   ┆ 0   ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ OV9 ┆     ┆     ┆ do. ┆     ┆ Col ┆ Ave ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ cel ┆     ┆ ent ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ erP ┆ /10 ┆ Sma ┆ SRR ┆ q   ┆ CDK ┆     ┆     ┆     ┆ 199 ┆ 284 ┆     ┆     ┆ O-s ┆     ┆ 906 ┆ CDK ┆ O-s ┆ q   ┆ q   ┆     ┆ 580 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ wer ┆ vs  ┆ cel ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ _   ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆ 711 ┆ 4   ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ edu ┆     ┆ ora ┆     ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 711 ┆     ┆     ┆     ┆ 197 ┆ ls  ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆ N33 ┆ rep ┆ .11 ┆ ll  ┆ 239 ┆ 600 ┆ 7   ┆     ┆     ┆     ┆ 525 ┆ 777 ┆     ┆     ┆ eq] ┆     ┆ 55  ┆ 7   ┆ eq] ┆ 600 ┆ 600 ┆     ┆ 522 ┆     ┆     ┆     ┆     ┆ 711 ┆ GSM ┆ e   ┆ GSM ┆ ls  ┆ 711 ┆     ┆     ┆ 171 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 923 ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ do  ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 923 ┆     ┆     ┆     ┆ 932 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆ 946 ┆ Kit ┆ 26/ ┆ RNA ┆ 893 ┆ 0   ┆ gov ┆     ┆     ┆     ┆ 366 ┆ 564 ┆     ┆     ┆ vs  ┆     ┆     ┆ gov ┆ vs  ┆ 0   ┆ 0   ┆     ┆ 415 ┆     ┆     ┆     ┆     ┆ 923 ┆ 711 ┆ the ┆ 711 ┆     ┆ 923 ┆     ┆     ┆ 556 ┆     ┆     │
│     ┆     ┆ dms ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls, ┆     ┆     ┆     ┆     ┆ Bou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆ 72  ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆ 087 ┆     ┆ sci ┆ ada ┆ 99  ┆ seq ┆ ern ┆     ┆     ┆     ┆ 4   ┆ 5   ┆     ┆     ┆ DMS ┆     ┆     ┆ ern ┆ DMS ┆     ┆ seq ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ 1   ┆ 923 ┆ n   ┆ 923 ┆     ┆ 1   ┆     ┆     ┆ 89  ┆     ┆     │
│     ┆     ┆ o_0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆ lde ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ adv ┆ pte ┆     ┆ uen ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_0 ┆     ┆     ┆ s   ┆ O_0 ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_r ┆ har ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _r1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _R1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ad ┆ rs  ┆     ┆ cin ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _R1 ┆     ┆     ┆ RNA ┆ _R1 ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ves ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _pr ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _vi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r96 ┆     ┆     ┆ g:  ┆ pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆     ┆     ┆ pol ┆ [PR ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ o-s ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rtu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 60  ┆     ┆     ┆ GSM ┆ yme ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O-s ┆     ┆     ┆ yme ┆ O-s ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ low ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 711 ┆ ras ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq] ┆     ┆     ┆ ras ┆ eq] ┆     ┆ 711 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ spi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 923 ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 923 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kei ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5:  ┆ II  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ II  ┆     ┆     ┆ 5:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n_n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DMS ┆ ini ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ini ┆     ┆     ┆ DMS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ orm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_2 ┆ tia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tia ┆     ┆     ┆ O_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_R ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆ 0_R ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [PR ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ [PR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D-P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

## 2. GSE173537 PRO-seq (SINGLE)

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb) で得られたデータ
- validate date: 2025-05-03
- [Characterizing primary transcriptional responses to short term heat shock in Down syndrome](https://doi.org/10.1371/journal.pone.0307375)
- 全てPRO-seqのデータで、chromosome 21 trisomic のデータも登録されている

&nbsp;

### Adapter

- About adapter: `Precision run-on sequencing experiments (PRO-seq) were carried out according to the PRO-seq protocol [Mahat DB, Salamanca HH, Duarte FM, Danko CG, Lis JT. Mammalian heat shock response and mechanisms underlying its genome-wide transcriptional regulation. Molecular cell. 2016;62(1):63–78. pmid:27052732].`
- [Mammalian heat shock response and mechanisms underlying its genome-wide transcriptional regulation](https://doi.org/10.1016/j.molcel.2016.02.025) の [Document S1. Supplemental Experimental Procedures, Figures S1–S7, and Tables S1–S7](https://www.cell.com/cms/10.1016/j.molcel.2016.02.025/attachment/a26eb1ee-03f5-423e-8282-5d6a5e331ac4/mmc1.pdf) を調べると、以下のような記述がある
- `After the third biotinstreptavidin affinity purification, cDNA was generated by reverse transcription and PRO-seq libraries were prepared for sequencing using Illumina TruSeq small-RNA adaptors with nine cycles of PCR.` とあるので、adapter は おそらく Illumina TruSeq small-RNA adaptors

In [7]:
GSE173537_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE173537/GSE173537_PEP/GSE173537_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1371/journal.pone.0307375").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE173537_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE173537_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE173537_iseq_filtered = GSE173537_iseq[[s.name for s in GSE173537_iseq if not (s.null_count() == GSE173537_iseq.height)]]

# display(GSE173537_PEP)

In [8]:
GSE173537_combined = GSE173537_PEP.join(
    GSE173537_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).sort(
    "sample_geo_accession", descending=True
)

GSE173537_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE173537_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE173537_combined)

In [9]:
defined_pairs_gse173537_pro_seq = [
    ("SRR14352132", "SRR14352131"), # proseq_lymphblastoid_cells_d21_42c_rep1 (heat-stress) vs proseq_lymphblastoid_cells_d21_37c_rep1 (control)
    ("SRR14352134", "SRR14352133"), # proseq_lymphblastoid_cells_t21_42c_rep1 (heat-stress) vs proseq_lymphblastoid_cells_t21_37c_rep1 (control)
    ("SRR14352136", "SRR14352135"), # proseq_lymphblastoid_cells_d21_42c_rep2 (heat-stress) vs proseq_lymphblastoid_cells_d21_37c_rep2 (control)
    ("SRR14352138", "SRR14352137")  # proseq_lymphblastoid_cells_t21_42c_rep2 (heat-stress) vs proseq_lymphblastoid_cells_t21_37c_rep2 (control)
]

paired_metadata_df_gse173537_pro_seq = create_paired_metadata(
    combined_df=GSE173537_combined,
    defined_sample_pairs=defined_pairs_gse173537_pro_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse173537_pro_seq is not None:
    paired_metadata_df_gse173537_pro_seq.write_csv(
        "../../Data/metadata/metadata_proseq/GSE173537_proseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse173537_pro_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ gen ┆ tre ┆ lib ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_t ┆ oty ┆ atm ┆ rar ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ype ┆ pe  ┆ ent ┆ y_s ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ tra ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ teg ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆ y   ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆ --- ┆     ┆ s_f ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ str ┆     ┆ orm ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ at_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ PRO ┆ GSM ┆ Pub ┆ Apr ┆ Apr ┆ SRA ┆ 1   ┆ lym ┆ Hom ┆ 960 ┆ tot ┆ Eri ┆ GPL ┆ Mar ┆ mar ┆ 608 ┆ All ┆ Bio ┆ Uni ┆ UCB ┆ Bou ┆ Co  ┆ 803 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ lym ┆ dis ┆ 42C ┆ PRO ┆ hg3 ┆ bed ┆ SAM ┆ unk ┆ htt ┆ Ill ┆ SRR ┆ Nex ┆ Blo ┆ SRA ┆ oth ┆ 202 ┆ 214 ┆ 330 ┆ ILL ┆ Gen ┆ PRO ┆ SRP ┆ 112 ┆ Blo ┆ PRO ┆ Nex ┆ Nex ┆ lym ┆ 852 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Nuc ┆ GSM ┆ GEO ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 143 ┆ 143 ┆ seq ┆ er  ┆ o   ┆ GLE ┆     ┆ 143 ┆ 107 ┆ seq ┆ 526 ┆ lic ┆ 28  ┆ 21  ┆     ┆     ┆ pho ┆ o   ┆ 6   ┆ al  ┆ c_D ┆ 185 ┆ y,A ┆ y.a ┆ -20 ┆ en  ┆ Fro ┆ ver ┆ 596 ┆ lde ┆     ┆ 09  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 526 ┆ :// ┆ 173 ┆     ┆ 107 ┆ pho ┆ omi ┆ 1   ┆ -se ┆ 8   ┆ gra ┆ N18 ┆ now ┆ ps: ┆ umi ┆ 143 ┆ tSe ┆ od  ┆ 122 ┆ er  ┆ 3-0 ┆ 854 ┆ 387 ┆ UMI ┆ eri ┆ seq ┆ 316 ┆ 213 ┆ od  ┆ seq ┆ tSe ┆ tSe ┆ pho ┆ 824 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 526 ┆ 526 ┆ lei ┆ 526 ┆     ┆ 3-0 ┆ NA7 ┆ 879 ┆ 3-0 ┆ 173 │
│ 521 ┆ 521 ┆ _ly ┆     ┆ sap ┆     ┆     ┆ 521 ┆ 059 ┆ _Ly ┆ 943 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆ bla ┆ sap ┆     ┆ RNA ┆ 21, ┆ 73  ┆ nn, ┆ .al ┆ 9-6 ┆     ┆ nti ┆ sit ┆ JSC ┆ r   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 943 ┆ ftp ┆ 537 ┆     ┆ 059 ┆ bla ┆ c   ┆ hou ┆ q   ┆ (GR ┆ phs ┆ 915 ┆ n   ┆ //d ┆ na  ┆ 521 ┆ q   ┆ cel ┆ 519 ┆     ┆ 5-0 ┆ 901 ┆ 737 ┆ NA  ┆ c   ┆ _Ly ┆ 802 ┆ 757 ┆ cel ┆ _Ly ┆ q   ┆ q   ┆ bla ┆ 553 ┆     ┆ RIP ┆     ┆     ┆ 943 ┆ 943 ┆ iso ┆ 943 ┆     ┆ 5-0 ┆ 259 ┆ 578 ┆ 5-0 ┆ 537 │
│ 32  ┆ 31  ┆ mph ┆     ┆ ien ┆     ┆     ┆ 32  ┆ 79  ┆ mph ┆ 8   ┆ Apr ┆ 1   ┆ 3   ┆     ┆     ┆ sto ┆ ien ┆     ┆     ┆ nas ┆     ┆ All ┆ len ┆ 921 ┆     ┆ ers ┆ y   ┆ BB  ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 8   ┆ .nc ┆     ┆     ┆ 79  ┆ sto ┆     ┆ r   ┆     ┆ Ch3 ┆ sup ┆ 532 ┆     ┆ oi. ┆ Tru ┆ 32  ┆ 500 ┆ ls  ┆ 7   ┆     ┆ 6   ┆ 9   ┆ 6   ┆     ┆     ┆ mph ┆     ┆ vs  ┆ ls  ┆ mph ┆ 500 ┆ 500 ┆ sto ┆ 2   ┆     ┆ TOM ┆     ┆     ┆ 8   ┆ 8_r ┆ lat ┆ 8   ┆     ┆ 5   ┆ 16  ┆ 4   ┆ 5   ┆     │
│     ┆     ┆ bla ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ bla ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆ id- ┆ s   ┆     ┆     ┆ cen ┆     ┆ en  ┆ @co ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ id  ┆     ┆ hea ┆     ┆ 8)  ┆ pli ┆ vs  ┆     ┆ org ┆ Seq ┆ vs  ┆ seq ┆ wit ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆     ┆ bla ┆     ┆ 106 ┆ wit ┆ bla ┆     ┆ seq ┆ id  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ion ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ sto ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ sto ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆ EBV ┆     ┆     ┆     ┆ t   ┆     ┆     ┆ lor ┆     ┆     ┆     ┆ Col ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆ t   ┆     ┆     ┆ ed  ┆ SAM ┆     ┆ /10 ┆ Sma ┆ SRR ┆ uen ┆ h   ┆     ┆     ┆     ┆ 203 ┆ 312 ┆     ┆     ┆ sto ┆     ┆ 351 ┆ h   ┆ sto ┆     ┆ uen ┆     ┆ 808 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ s:  ┆ GSM ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ id_ ┆     ┆     ┆     ┆     ┆ 143 ┆ 107 ┆ id  ┆ 526 ┆ 3   ┆     ┆     ┆     ┆     ┆ imm ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ ado ┆     ┆     ┆     ┆ ora ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 526 ┆ .ni ┆     ┆     ┆ 107 ┆     ┆     ┆ sho ┆     ┆     ┆ for ┆ N18 ┆     ┆ .13 ┆ ll  ┆ 143 ┆ cin ┆ tri ┆     ┆     ┆     ┆ 600 ┆ 948 ┆     ┆     ┆ id  ┆     ┆ 450 ┆ tri ┆ id  ┆     ┆ cin ┆     ┆ 271 ┆     ┆     ┆     ┆     ┆ 526 ┆ GSM ┆ Cel ┆ 526 ┆     ┆     ┆     ┆ 879 ┆     ┆     │
│     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆ 521 ┆ 059 ┆ cel ┆ 943 ┆     ┆     ┆     ┆     ┆     ┆ ort ┆     ┆     ┆     ┆ (PR ┆     ┆     ┆ .ed ┆     ┆     ┆     ┆ do  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 943 ┆ h.g ┆     ┆     ┆ 059 ┆     ┆     ┆ ck  ┆     ┆     ┆ PRO ┆ 915 ┆     ┆ 71/ ┆ RNA ┆ 521 ┆ g:  ┆ som ┆     ┆     ┆     ┆ 563 ┆ 350 ┆     ┆     ┆ cel ┆     ┆     ┆ som ┆ cel ┆     ┆ g:  ┆     ┆ 020 ┆     ┆     ┆     ┆     ┆ 943 ┆ 526 ┆ ls  ┆ 943 ┆     ┆     ┆     ┆ 578 ┆     ┆     │
│     ┆     ┆ ls_ ┆     ┆     ┆     ┆     ┆ 31  ┆ 78  ┆ ls_ ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ ali ┆     ┆     ┆     ┆ O-s ┆     ┆     ┆ u   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ ov/ ┆     ┆     ┆ 78  ┆     ┆     ┆ vs  ┆     ┆     ┆ -se ┆ 533 ┆     ┆ jou ┆ ada ┆ 31  ┆ GSM ┆ y   ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆     ┆ ls_ ┆     ┆     ┆ y   ┆ ls_ ┆     ┆ GSM ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆ 7   ┆ 943 ┆ wer ┆ 7   ┆     ┆     ┆     ┆ 2   ┆     ┆     │
│     ┆     ┆ d21 ┆     ┆     ┆     ┆     ┆     ┆     ┆ D21 ┆     ┆     ┆     ┆     ┆     ┆     ┆ zed ┆     ┆     ┆     ┆ eq) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆ unt ┆     ┆     ┆ q   ┆     ┆     ┆ rna ┆ pte ┆     ┆ 526 ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D21 ┆     ┆     ┆ 21  ┆ D21 ┆     ┆ 526 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7_r ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _42 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _42 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆ rea ┆     ┆     ┆ lib ┆     ┆     ┆ l.p ┆ rs  ┆     ┆ 943 ┆ ove ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _42 ┆     ┆     ┆ ove ┆ _42 ┆     ┆ 943 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ gro ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ C_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆ rar ┆     ┆     ┆ one ┆     ┆     ┆ 8:  ┆ rre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C_r ┆     ┆     ┆ rre ┆ C_r ┆     ┆ 8:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wn  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆ (37 ┆     ┆     ┆ ies ┆     ┆     ┆ .03 ┆     ┆     ┆ PRO ┆ act ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆ act ┆ ep1 ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆     ┆ .   ┆     ┆     ┆ 073 ┆     ┆     ┆ seq ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ to  ┆ vs  ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sus ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 526 ┆     ┆     ┆     ┆     ┆     ┆ inc ┆     ┆     ┆     ┆     ┆     ┆ 75  ┆     ┆     ┆ _Ly ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆ hea ┆ PRO ┆     ┆ _Ly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pen ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9nn ┆     ┆     ┆     ┆     ┆     ┆ uba ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mph ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆ t   ┆ seq ┆     ┆ mph ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sio ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _ly ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ly ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆ tor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bla ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Ly ┆     ┆     ┆ sho ┆ _Ly ┆     ┆ bla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ mph ┆     ┆     ┆     ┆     ┆     ┆     ┆ mph ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM5 ┆     ┆     ┆     ┆     ┆     ┆ )   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sto ┆ ck  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mph ┆     ┆     ┆ ck  ┆ mph ┆     ┆ sto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ bla ┆     ┆     ┆     ┆     ┆     ┆     ┆ bla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 269 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ id  ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bla ┆     ┆     ┆ str ┆ bla ┆     ┆ id  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ T75 ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ sto ┆     ┆     ┆     ┆     ┆     ┆     ┆ sto ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 438 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆ ess ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sto ┆     ┆     ┆ ess ┆ sto ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ [MA ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ id_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ id  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls_ ┆ [PR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ id  ┆     ┆     ┆ [PR ┆ id  ┆     ┆ ls_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A1] ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D21 ┆ O-s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ O-s ┆ cel ┆     ┆ D21 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fla ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 3. GSE211651 PRO-seq (SINGLE)

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validation date: 2025-05-03
- [Enhancing HIV-1 latency reversal through regulating the elongating RNA Pol II pause-release by a small-molecule disruptor of PAF1C](https://doi.org/10.1126/sciadv.adf2468)
- きちんと熱ストレス条件とコントロール条件があるデータ
- `inhibitor of PAF1C (iPAF1C)` や `shRNA` 処理も重ねて行われているデータも
- **RNA-seqのデータを見ると、熱ストレスに曝露されているデータは含まれていなかったので、PRO-seqのみ念の為収集しておく**
- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

&nbsp;

### Adapter

- About adapter: 以下のような記述がある
- `PRO-seq was performed according to the previously published protocol with minor modifications (80 D. B. Mahat, H. Kwak, G. T. Booth, I. H. Jonkers, C. G. Danko, R. K. Patel, C. T. Waters, K. Munson, L. J. Core, J. T. Lis, Base-pair-resolution genome-wide mapping of active RNA polymerases using precision nuclear run-on (PRO-seq). Nat. Protoc. 11, 1455–1476 (2016).).`
- [Base-pair-resolution genome-wide mapping of active RNA polymerases using precision nuclear run-on (PRO-seq)](https://doi.org/10.1038/nprot.2016.086)
- この論文には、以下のような記載がある
- `148 Pre-process the raw sequence data. Filter out low-quality reads and trim potential adaptor sequences (TGGAATTCTCGGGTGCCAAGG) from the sequence reads. Tools such as 'cutadapt' are publicly available for this purpose. Depending on the quality of the library, sequences containing only the adaptor sequences (adaptor dimers) may take up to 5% of total reads.`
- この adapter sequence `TGGAATTCTCGGGTGCCAAGG` は、[TruSeq Small RNA](https://support-docs.illumina.com/SHARE/AdapterSequences/Content/TruSeq-SmallRNA.htm)

In [10]:
GSE211651_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE211651/GSE211651_PEP/GSE211651_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_library_strategy") == "RNA-Seq") | (pl.col("sample_title").str.contains(r'PRO-seq_'))
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("NEBNext Ultra II Directional RNA Library Prep Kit").alias("rna_library"), # add rna_library column from GEO webpage (NEW ENGLAND Biolabs)
    pl.lit("https://doi.org/10.1126/sciadv.adf2468").alias("reference_doi") # add DOI of the reference paper column
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# PRO-seq
GSE211651_PEP_pro_seq = GSE211651_PEP.filter(
    pl.col("sample_title").str.contains(r'PRO-seq_')
).with_columns(
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
)

# metadata from iseq
GSE211651_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE211651_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE211651_iseq_filtered = GSE211651_iseq[[s.name for s in GSE211651_iseq if not (s.null_count() == GSE211651_iseq.height)]]

# display(GSE211651_PEP_pro_seq)

In [11]:
GSE211651_combined_pro_seq = GSE211651_PEP_pro_seq.join(
    GSE211651_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE211651_combined_pro_seq.write_csv(
    "../../Data/metadata/metadata_proseq/GSE211651_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE211651_combined_pro_seq)

In [12]:
# PRO-seq
defined_pairs_gse211651_pro_seq = [
    # PAF1 knockdown
    ("SRR21140707", "SRR21140711"), # PRO-seq_DLD1_shPAF1_HS vs PRO-seq_DLD1_shPAF1
    ("SRR21140708", "SRR21140712"), # PRO-seq_DLD1_shPAF1_HS vs PRO-seq_DLD1_shPAF1
    ("SRR21140709", "SRR21140713"), # PRO-seq_DLD1_shPAF1_HS vs PRO-seq_DLD1_shPAF1
    ("SRR21140710", "SRR21140714"), # PRO-seq_DLD1_shPAF1_HS vs PRO-seq_DLD1_shPAF1
    # WT (DMSO)
    ("SRR21140715", "SRR21140719"), # PRO-seq_DLD1_DMSO_HS vs PRO-seq_DLD1_DMSO
    ("SRR21140716", "SRR21140720"), # PRO-seq_DLD1_DMSO_HS vs PRO-seq_DLD1_DMSO
    ("SRR21140717", "SRR21140721"), # PRO-seq_DLD1_DMSO_HS vs PRO-seq_DLD1_DMSO
    ("SRR21140718", "SRR21140722"), # PRO-seq_DLD1_DMSO_HS vs PRO-seq_DLD1_DMSO
    # WT (iPAF1C 20uM)
    ("SRR21140723", "SRR21140727"), # PRO-seq_DLD1_iPAF1C_HS vs PRO-seq_DLD1_iPAF1C
    ("SRR21140724", "SRR21140728"), # PRO-seq_DLD1_iPAF1C_HS vs PRO-seq_DLD1_iPAF1C
    ("SRR21140725", "SRR21140729"), # PRO-seq_DLD1_iPAF1C_HS vs PRO-seq_DLD1_iPAF1C
    ("SRR21140726", "SRR21140730")  # PRO-seq_DLD1_iPAF1C_HS vs PRO-seq_DLD1_iPAF1C
]

paired_metadata_df_gse211651_pro_seq = create_paired_metadata(
    combined_df=GSE211651_combined_pro_seq,
    defined_sample_pairs=defined_pairs_gse211651_pro_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse211651_pro_seq is not None:
    paired_metadata_df_gse211651_pro_seq.write_csv(
        "../../Data/metadata/metadata_proseq/GSE211651_proseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse211651_pro_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (12, 85)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tis ┆ cel ┆ cel ┆ gen ┆ tre ┆ chi ┆ ass ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ cel ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu ┆ tis │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ sue ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ p_a ┆ emb ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ ┆ sue │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ --- ┆ ine ┆ ype ┆ pe  ┆ ent ┆ nti ┆ ly  ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ ype ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali ┆ _ty │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ bod ┆ --- ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  ┆ pe  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆     ┆ str ┆ str ┆ str ┆ str ┆ y   ┆ str ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ ght ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ --- ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ --- ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ str ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ PRO ┆ GSM ┆ Pub ┆ Aug ┆ Mar ┆ SRA ┆ 1   ┆ col ┆ Hom ┆ 960 ┆ tot ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ col ┆ DLD ┆ col ┆ PAF ┆ hea ┆ nul ┆ hg3 ┆ SAM ┆ NEB ┆ htt ┆ Ill ┆ SRR ┆ Nex ┆ Enh ┆ SRA ┆ oth ┆ 202 ┆ 224 ┆ 348 ┆ ILL ┆ Gen ┆ PRO ┆ SRP ┆ 160 ┆ Enh ┆ PRO ┆ Nex ┆ Nex ┆ col ┆ 812 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Ext ┆ GSM ┆ DLD ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE ┆ col │
│ 211 ┆ 211 ┆ -se ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ -se ┆ 648 ┆ lic ┆ 19  ┆ 23  ┆     ┆     ┆ on  ┆ o   ┆ 6   ┆ al  ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 648 ┆ :// ┆ 211 ┆     ┆ 171 ┆ on  ┆ -1  ┆ ore ┆ 1   ┆ t   ┆ l   ┆ 8   ┆ N30 ┆ Nex ┆ ps: ┆ umi ┆ 211 ┆ tSe ┆ anc ┆ 147 ┆ er  ┆ 3-0 ┆ 707 ┆ 179 ┆ UMI ┆ eri ┆ -se ┆ 393 ┆ 646 ┆ anc ┆ -se ┆ tSe ┆ tSe ┆ ore ┆ 775 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 648 ┆ 648 ┆ rac ┆ 648 ┆ -1  ┆ 648 ┆ 3-0 ┆ NA8 ┆ 147 ┆ 3-0 ┆ 211 ┆ on  │
│ 407 ┆ 407 ┆ q_d ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_D ┆ 206 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 206 ┆ ftp ┆ 651 ┆     ┆ 529 ┆     ┆     ┆ cta ┆ kno ┆ sho ┆     ┆     ┆ 413 ┆ t   ┆ //d ┆ na  ┆ 407 ┆ q   ┆ ing ┆ 913 ┆     ┆ 3-2 ┆ 969 ┆ 135 ┆ NA  ┆ c   ┆ q_D ┆ 054 ┆ 42  ┆ ing ┆ q_D ┆ q   ┆ q   ┆ cta ┆ 291 ┆     ┆ RIP ┆     ┆     ┆ 206 ┆ 206 ┆ tio ┆ 206 ┆     ┆ 206 ┆ 3-2 ┆ 712 ┆ 248 ┆ 3-2 ┆ 651 ┆     │
│ 07  ┆ 11  ┆ ld1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ LD1 ┆ 3   ┆ Mar ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 3   ┆ .nc ┆     ┆     ┆ 94  ┆     ┆     ┆ l   ┆ ckd ┆ ck  ┆     ┆     ┆ 337 ┆ Ult ┆ oi. ┆ Tru ┆ 07  ┆ 500 ┆ HIV ┆ 7   ┆     ┆ 6   ┆ vs  ┆ vs  ┆     ┆     ┆ LD1 ┆     ┆ vs  ┆ HIV ┆ LD1 ┆ 500 ┆ 500 ┆ l   ┆ vs  ┆     ┆ TOM ┆     ┆     ┆ 3   ┆ 3_r ┆ n   ┆ 3_r ┆     ┆ 3   ┆ 4   ┆ 56  ┆ 20  ┆ 4   ┆     ┆     │
│     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sh ┆ vs  ┆ 23  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆     ┆     ┆ ade ┆ own ┆ vs  ┆     ┆     ┆ vs  ┆ ra  ┆ org ┆ Seq ┆ vs  ┆ seq ┆ -1  ┆     ┆     ┆     ┆ 133 ┆ 212 ┆     ┆     ┆ _sh ┆     ┆ 949 ┆ -1  ┆ _sh ┆     ┆ seq ┆ ade ┆ 480 ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ of  ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆ paf ┆     ┆     ┆     ┆     ┆     ┆     ┆ PAF ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆     ┆     ┆ noc ┆     ┆ unt ┆     ┆     ┆ SAM ┆ II  ┆ /10 ┆ Sma ┆ SRR ┆ uen ┆ lat ┆     ┆     ┆     ┆ 473 ┆ 104 ┆     ┆     ┆ PAF ┆     ┆ 715 ┆ lat ┆ PAF ┆     ┆ uen ┆ noc ┆ 559 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ tot ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     ┆     │
│     ┆     ┆ 1_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_H ┆ 648 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 648 ┆ .ni ┆     ┆     ┆ 171 ┆     ┆     ┆ arc ┆     ┆ rea ┆     ┆     ┆ N30 ┆ Dir ┆ .11 ┆ ll  ┆ 211 ┆ cin ┆ enc ┆     ┆     ┆     ┆ 142 ┆ 138 ┆     ┆     ┆ 1_H ┆     ┆ 2   ┆ enc ┆ 1_H ┆     ┆ cin ┆ arc ┆ 228 ┆     ┆     ┆     ┆     ┆ 648 ┆ GSM ┆ al  ┆ GSM ┆     ┆ 648 ┆     ┆     ┆ 147 ┆     ┆     ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ S   ┆ 206 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ h.g ┆     ┆     ┆ 529 ┆     ┆     ┆ ino ┆     ┆ ted ┆     ┆     ┆ 413 ┆ ect ┆ 26/ ┆ RNA ┆ 407 ┆ g:  ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S   ┆     ┆     ┆ y   ┆ S   ┆     ┆ g:  ┆ ino ┆     ┆     ┆     ┆     ┆     ┆ 206 ┆ 648 ┆ RNA ┆ 648 ┆     ┆ 206 ┆     ┆     ┆ 248 ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ ov/ ┆     ┆     ┆ 93  ┆     ┆     ┆ ma  ┆     ┆     ┆     ┆     ┆ 338 ┆ ion ┆ sci ┆ ada ┆ 11  ┆ GSM ┆ rev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ rev ┆ vs  ┆     ┆ GSM ┆ ma  ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 206 ┆ was ┆ 206 ┆     ┆ 2   ┆     ┆     ┆ 19  ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆ adv ┆ pte ┆     ┆ 648 ┆ ers ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆ ers ┆ PRO ┆     ┆ 648 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ per ┆ 2_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆ .ad ┆ rs  ┆     ┆ 206 ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆ al  ┆ -se ┆     ┆ 206 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ for ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_d ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lib ┆ f24 ┆     ┆     ┆ 3:  ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_D ┆     ┆     ┆ thr ┆ q_D ┆     ┆ 3:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ld1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ LD1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rar ┆ 68  ┆     ┆     ┆ PRO ┆ oug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ LD1 ┆     ┆     ┆ oug ┆ LD1 ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ usi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆ -se ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sh ┆     ┆     ┆ h   ┆ _sh ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ paf ┆     ┆     ┆     ┆     ┆     ┆     ┆ PAF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 648 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆     ┆ q_D ┆ reg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PAF ┆     ┆     ┆ reg ┆ PAF ┆     ┆ q_D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆     ┆ LD1 ┆ ula ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ ula ┆ 1   ┆     ┆ LD1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ asy ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆     ┆ _sh ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tin ┆     ┆     ┆ _sh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PAF ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆ PAF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 482 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1_H ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ the ┆     ┆     ┆ 1_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 063 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S   ┆ elo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ elo ┆     ┆     ┆ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (Qi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ nga ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nga ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ age ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tin ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /GS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cat ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RNA ┆     ┆     ┆ ien ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ #   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 820 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pol ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 741 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 4. GSE154746 PRO-seq (PAIRED)

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から移行
- validate date: 2025-05-04
- [Stress-induced transcriptional memory accelerates promoter-proximal pause release and decelerates termination over mitotic divisions](https://doi.org/10.1016/j.molcel.2021.03.007)
- [実験医学: PRO-seq](https://www.yodosha.co.jp/jikkenigaku/keyword/PRO-seq/id/107099)
- `unconditioned (uC) or preconditioned with a single heat shock exposure (pC)` という条件があるが、これらの条件は外すことに決定
- 42℃で複数の曝露時間条件が含まれている

&nbsp;

### Adapter

- 以下のような記述がある
- `The libraries were generated using **TruSeq small-RNA adaptors** and sequenced using NextSeq500 (Illumina).`

In [13]:
ID = "GSE154746"

GSE154746_PEP = pl.read_csv(
    f"../../Data/metadata/metadata_geofetch/{ID}/{ID}_PEP/{ID}_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("TruSeq small-RNA adaptor").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("https://doi.org/10.1016/j.molcel.2021.03.007").alias("reference_doi"), # add DOI of the reference paper column
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE154746_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE154746_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE154746_iseq_filtered = GSE154746_iseq[[s.name for s in GSE154746_iseq if not (s.null_count() == GSE154746_iseq.height)]]

# display(GSE154746_PEP)

In [14]:
GSE154746_combined_pro_seq = GSE154746_PEP.join(
    GSE154746_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE154746_combined_pro_seq.write_csv(
    "../../Data/metadata/metadata_proseq/GSE154746_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE154746_combined_pro_seq)

In [15]:
defined_pairs_gse154746_pro_seq = [
    ("SRR12267709", "SRR12267707"), # proseq_k562_s_uc12p5_rep1 vs proseq_k562_s_uc0_rep1
    ("SRR12267710", "SRR12267708"), # PROseq_K562_s_uC12p5_rep2 vs PROseq_K562_s_uC0_rep2
    ("SRR12267711", "SRR12267707"), # PROseq_K562_s_uC25_rep1 vs PROseq_K562_s_uC0_rep1
    ("SRR12267712", "SRR12267708"), # PROseq_K562_s_uC25_rep2 vs PROseq_K562_s_uC0_rep2
    ("SRR12267713", "SRR12267707"), # PROseq_K562_s_uC40_rep1 vs PROseq_K562_s_uC0_rep1
    ("SRR12267714", "SRR12267708"), # PROseq_K562_s_uC40_rep2 vs PROseq_K562_s_uC0_rep2
    # ("SRR12267717", "SRR12267715"), # PROseq_K562_s_pC12p5_rep1 vs PROseq_K562_s_pC0_rep1
    # ("SRR12267718", "SRR12267716"), # PROseq_K562_s_pC12p5_rep2 vs PROseq_K562_s_pC0_rep2
    # ("SRR12267719", "SRR12267715"), # PROseq_K562_s_pC25_rep1 vs PROseq_K562_s_pC0_rep1
    # ("SRR12267720", "SRR12267716"), # PROseq_K562_s_pC25_rep2 vs PROseq_K562_s_pC0_rep2
    # ("SRR12267721", "SRR12267715"), # PROseq_K562_s_pC40_rep1 vs PROseq_K562_s_pC0_rep1
    # ("SRR12267722", "SRR12267716")  # PROseq_K562_s_pC40_rep2 vs PROseq_K562_s_pC0_rep2
]

paired_metadata_df_gse154746_pro_seq = create_paired_metadata(
    combined_df=GSE154746_combined_pro_seq,
    defined_sample_pairs=defined_pairs_gse154746_pro_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse154746_pro_seq is not None:
    paired_metadata_df_gse154746_pro_seq.write_csv(
        "../../Data/metadata/metadata_proseq/GSE154746_proseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse154746_pro_seq)
else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (6, 84)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ pre ┆ seq ┆ lib ┆ gen ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ con ┆ uen ┆ rar ┆ ome ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ dit ┆ ced ┆ y_s ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ ion ┆ _mo ┆ tra ┆ ild ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ ing ┆ lec ┆ teg ┆ --- ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ --- ┆ ule ┆ y   ┆ str ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y_r ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ str ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ igh ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ s_c ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ oth ┆ Hom ┆ PAI ┆ SRA ┆ SRR ┆ SRX ┆ PRO ┆ GSM ┆ Pub ┆ Jul ┆ Apr ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ hea ┆ tot ┆ 3'  ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ non ┆ nas ┆ PRO ┆ hg1 ┆ SAM ┆ Tru ┆ htt ┆ Ill ┆ SRR ┆ Ill ┆ Hea ┆ SRA ┆ oth ┆ 202 ┆ 269 ┆ 143 ┆ ILL ┆ Gen ┆ PRO ┆ SRP ┆ 239 ┆ Hea ┆ PRO ┆ Ill ┆ Ill ┆ 718 ┆ OTH ┆ TRA ┆ PAI ┆ pub ┆ GSM ┆ GSM ┆ Aft ┆ GSM ┆ GEO ┆ K56 ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 122 ┆ 122 ┆ seq ┆ er  ┆ o   ┆ RED ┆     ┆ 122 ┆ 877 ┆ seq ┆ 467 ┆ lic ┆ 20  ┆ 01  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ t   ┆ al  ┆ bar ┆ 167 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 467 ┆ E   ┆ 154 ┆     ┆ 877 ┆ 2   ┆ e   ┆ cen ┆ -se ┆ 9   ┆ N15 ┆ Seq ┆ ps: ┆ umi ┆ 122 ┆ umi ┆ t-i ┆ 110 ┆ er  ┆ 1-0 ┆ 211 ┆ 569 ┆ UMI ┆ eri ┆ seq ┆ 272 ┆ 522 ┆ t-i ┆ seq ┆ umi ┆ umi ┆ 566 ┆ ER  ┆ NSC ┆ RED ┆ lic ┆ 467 ┆ 467 ┆ er  ┆ 467 ┆     ┆ 2   ┆ 1-0 ┆ NA6 ┆ 704 ┆ 1-0 ┆ 154 │
│ 677 ┆ 677 ┆ _k5 ┆     ┆ sap ┆     ┆     ┆ 677 ┆ 276 ┆ _K5 ┆ 814 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ sho ┆ RNA ┆ cod ┆ 91  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 814 ┆     ┆ 746 ┆     ┆ 276 ┆     ┆     ┆ t   ┆ q   ┆     ┆ 582 ┆ sma ┆ //d ┆ na  ┆ 677 ┆ na  ┆ ndu ┆ 091 ┆     ┆ 4-0 ┆ 868 ┆ 931 ┆ NA  ┆ c   ┆ _K5 ┆ 608 ┆ 28  ┆ ndu ┆ _K5 ┆ na  ┆ na  ┆ 840 ┆     ┆ RIP ┆     ┆     ┆ 814 ┆ 814 ┆ tre ┆ 814 ┆     ┆     ┆ 4-0 ┆ 473 ┆ 323 ┆ 4-0 ┆ 746 │
│ 09  ┆ 07  ┆ 62_ ┆     ┆ ien ┆     ┆     ┆ 09  ┆ 8   ┆ 62_ ┆ 7   ┆ Apr ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ ien ┆     ┆ ck  ┆     ┆ e:, ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 7   ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆ RNA ┆     ┆     ┆ 320 ┆ ll- ┆ oi. ┆ Tru ┆ 09  ┆ HiS ┆ ced ┆ 5   ┆     ┆ 2   ┆ 6   ┆ 1;1 ┆     ┆     ┆ 62_ ┆     ┆ vs  ┆ ced ┆ 62_ ┆ HiS ┆ HiS ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ 7   ┆ 7_r ┆ atm ┆ 7   ┆     ┆     ┆ 2   ┆ 74  ┆ 0   ┆ 2   ┆     │
│     ┆     ┆ s_u ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ s_u ┆ vs  ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ (ad ┆     ┆ 3'  ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ RNA ┆ org ┆ Seq ┆ vs  ┆ eq  ┆ tra ┆     ┆     ┆     ┆ vs  ┆ 530 ┆     ┆     ┆ s_u ┆     ┆ 281 ┆ tra ┆ s_u ┆ eq  ┆ eq  ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ent ┆ vs  ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ c12 ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ C12 ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆ UMI ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ 250 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆     ┆     ┆     ┆     ┆ SAM ┆ ada ┆ /10 ┆ Sma ┆ SRR ┆ 250 ┆ nsc ┆     ┆     ┆     ┆ 318 ┆ 256 ┆     ┆     ┆ C12 ┆     ┆ 332 ┆ nsc ┆ C12 ┆ 250 ┆ 250 ┆ 843 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ s,  ┆ GSM ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ p5_ ┆     ┆     ┆     ┆     ┆ 122 ┆ 877 ┆ p5_ ┆ 467 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆ :,  ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 467 ┆     ┆     ┆     ┆ 877 ┆     ┆     ┆     ┆     ┆     ┆ N15 ┆ pto ┆ .10 ┆ ll  ┆ 122 ┆ 0   ┆ rip ┆     ┆     ┆     ┆ 724 ┆ 531 ┆     ┆     ┆ p5_ ┆     ┆ 39  ┆ rip ┆ p5_ ┆ 0   ┆ 0   ┆ 997 ┆     ┆     ┆     ┆     ┆ 467 ┆ GSM ┆ the ┆ 467 ┆     ┆     ┆     ┆     ┆ 704 ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ 677 ┆ 276 ┆ rep ┆ 814 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆ 6nt ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 814 ┆     ┆     ┆     ┆ 276 ┆     ┆     ┆     ┆     ┆     ┆ 582 ┆ r   ┆ 16/ ┆ RNA ┆ 677 ┆ seq ┆ tio ┆     ┆     ┆     ┆ 526 ┆ vs  ┆     ┆     ┆ rep ┆     ┆     ┆ tio ┆ rep ┆     ┆ seq ┆ 170 ┆     ┆     ┆     ┆     ┆ 814 ┆ 467 ┆ cel ┆ 814 ┆     ┆     ┆     ┆     ┆ 322 ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 07  ┆ 6   ┆ 1   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆ + C ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆ 322 ┆     ┆ j.m ┆ ada ┆ 07  ┆ uen ┆ nal ┆     ┆     ┆     ┆ 5   ┆ 166 ┆     ┆     ┆ 1   ┆     ┆     ┆ nal ┆ 1   ┆     ┆ uen ┆ 0   ┆     ┆     ┆     ┆     ┆ 5   ┆ 814 ┆ ls  ┆ 5   ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆     ┆ (7  ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ olc ┆ pte ┆     ┆ cin ┆ mem ┆     ┆     ┆     ┆     ┆ 397 ┆     ┆     ┆ vs  ┆     ┆     ┆ mem ┆ vs  ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5_r ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ el. ┆ rs  ┆     ┆ g:  ┆ ory ┆     ┆     ┆     ┆     ┆ 460 ┆     ┆     ┆ PRO ┆     ┆     ┆ ory ┆ PRO ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆ GSM ┆ pro ┆     ┆     ┆     ┆     ┆ 3;1 ┆     ┆     ┆ seq ┆     ┆     ┆ pro ┆ seq ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ har ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _k5 ┆     ┆     ┆     ┆     ┆     ┆     ┆ _K5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1.0 ┆     ┆     ┆ 467 ┆ fil ┆     ┆     ┆     ┆     ┆ 788 ┆     ┆     ┆ _K5 ┆     ┆     ┆ fil ┆ _K5 ┆     ┆ 467 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ves ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 62_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆ al) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3.0 ┆     ┆     ┆ 814 ┆ ed  ┆     ┆     ┆     ┆     ┆ 871 ┆     ┆     ┆ 62_ ┆     ┆     ┆ ed  ┆ 62_ ┆     ┆ 814 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_u ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_u ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ):  ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆     ┆     ┆ 7:  ┆ in  ┆     ┆     ┆     ┆     ┆ 689 ┆     ┆     ┆ s_u ┆     ┆     ┆ in  ┆ s_u ┆     ┆ 7:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c0_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ C0_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 12. ┆     ┆ 5'  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C0_ ┆     ┆     ┆ hum ┆ C0_ ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ UMI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ an  ┆ rep ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆ :,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _K5 ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ K56 ┆ 1   ┆     ┆ _K5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆ 6nt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62_ ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ 62_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42° ┆     ┆ + C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_u ┆ ery ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ery ┆     ┆     ┆ s_u ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆ (7  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C12 ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ thr ┆     ┆     ┆ C12 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wat ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p5_ ┆ ole ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ole ┆     ┆     ┆ p5_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆ uke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uke ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bat ┆     ┆ tot ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ mia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mia ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ twi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ al) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 5. GSE202187 PRO-seq (SINGLE) 

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- [12_4_metadata_modified_false_no_control.ipynb](./12_4_metadata_modified_false_no_control.ipynb)から移動
- validation date: 2025-05-06
- [SPT6 functions in transcriptional pause/release via PAF1C recruitment](https://doi.org/10.1016/j.molcel.2022.06.037)
- GSE202189に関連するデータで、PRO-seqのデータ
- PRO-seqとSPT6に対するauxin-inducible degradation (AID) systemが行われている論文
- 42℃, 60min. 

&nbsp;

### Adapter

- 以下のような記述が論文にある
- `Low-quality bases and adapters from 3’ ends were removed using cutadapt 1.14 (Martin, 2011) requiring a read length of 16–36 bp, followed by removal of reads that were derived from ribosomal RNA.`
- Gene Expression Omnibus のページ、例えば [GSM6102924](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM6102924) の Extraction protocol には以下のような記載がある
- `For PRO-seq, adapter sequences previously described (Mahat et al., 2016) were used.`
- したがって、`Illumina TruSeq Small RNA adapters` が妥当であると考えられる

In [16]:
GSE202187_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE202187/GSE202187_PEP/GSE202187_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina TruSeq small RNA library prep kit").alias("rna_library"), # add rna_library column from GEO webpage (Illumina)
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE202187 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE202187_metadata.tsv",
    separator='\t'
)

GSE202187_iseq_filtered = GSE202187[[s.name for s in GSE202187 if not (s.null_count() == GSE202187.height)]]

# display(GSE202187_PEP)

In [17]:
GSE202187_combined = GSE202187_PEP.join(
    GSE202187_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE202187_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE202187_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE202187_combined)

In [18]:
defined_pairs_gse202187 = [
    ("SRR19077094", "SRR19077096"), # PRO-seq-01-SPT6AID-Veh2h-HS1h vs PRO-seq-01-SPT6AID-Veh2h-NHS1h
    ("SRR19077093", "SRR19077095"), # PRO-seq-01-SPT6AID-Aux2h-HS1h vs PRO-seq-01-SPT6AID-Aux2h-NHS1h
    ("SRR19077090", "SRR19077092"), # PRO-seq-02-SPT6AID-Veh2h-HS1h vs PRO-seq-02-SPT6AID-Veh2h-NHS1h
    ("SRR19077089", "SRR19077091"), # PRO-seq-02-SPT6AID-Aux2h-HS1h vs PRO-seq-02-SPT6AID-Aux2h-NHS1h
    ("SRR19077086", "SRR19077088"), # PRO-seq-03-PAF1AID-Veh2h-HS1h vs PRO-seq-03-PAF1AID-Veh2h-NHS1h
    ("SRR19077085", "SRR19077087"), # PRO-seq-03-PAF1AID-Aux2h-HS1h vs PRO-seq-03-PAF1AID-Aux2h-NHS1h
    ("SRR19077082", "SRR19077084"), # PRO-seq-04-PAF1AID-Veh2h-HS1h vs PRO-seq-04-PAF1AID-Veh2h-NHS1h
    ("SRR19077081", "SRR19077083")  # PRO-seq-04-PAF1AID-Aux2h-HS1h vs PRO-seq-04-PAF1AID-Aux2h-NHS1h
]

paired_metadata_df_gse202187 = create_paired_metadata(
    combined_df=GSE202187_combined, 
    defined_sample_pairs=defined_pairs_gse202187,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse202187 is not None:
    paired_metadata_df_gse202187.write_csv(
        "../../Data/metadata/metadata_proseq/GSE202187_proseq_paired_metadata.tsv",
        separator='\t'
    )

display(paired_metadata_df_gse202187)

shape: (8, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ gen ┆ tre ┆ ass ┆ lib ┆ sam ┆ rna ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ fas ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ sra ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ sam ┆ run ┆ lib ┆ exp ┆ cel ┆ lib ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ oty ┆ atm ┆ emb ┆ rar ┆ ple ┆ _li ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _as ┆ tq_ ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ ple ┆ _al ┆ rar ┆ eri ┆ l_l ┆ rar ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ pe  ┆ ent ┆ ly  ┆ y_s ┆ _ac ┆ bra ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ per ┆ gal ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ _al ┆ ias ┆ y_c ┆ men ┆ ine ┆ y_n ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ tra ┆ ces ┆ ry  ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ a   ┆ axy ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ --- ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ias ┆ --- ┆ ons ┆ t_a ┆ _ri ┆ ame ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ str ┆ teg ┆ sio ┆ --- ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ --- ┆ --- ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ str ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ ght ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ n   ┆ str ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ str ┆ str ┆ ion ┆ str ┆     ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆     ┆ --- ┆     ┆ str ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ --- ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆     ┆     ┆ _ri ┆     ┆     ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆ str ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ ght ┆     ┆     ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ PRO ┆ GSM ┆ Pub ┆ May ┆ Aug ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ nuc ┆ PRO ┆ GPL ┆ Yuk ┆ yuk ┆ Ali ┆ Bio ┆ Nor ┆ 303 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ DLD ┆ Col ┆ SPT ┆ Veh ┆ hg3 ┆ PRO ┆ SAM ┆ Ill ┆ Ill ┆ SRR ┆ Ill ┆ SPT ┆ SRA ┆ oth ┆ 202 ┆ 165 ┆ 234 ┆ ILL ┆ fas ┆ ftp ┆ PRO ┆ ftp ┆ 5a9 ┆ SRP ┆ 941 ┆ SPT ┆ PRO ┆ Ill ┆ Ill ┆ 2e9 ┆ Col ┆ ftp ┆ 475 ┆ OTH ┆ TRA ┆ ftp ┆ SIN ┆ pub ┆ fas ┆ GSM ┆ GSM ┆ PRO ┆ GSM ┆ DLD ┆ GSM ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 190 ┆ 190 ┆ -se ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ -se ┆ 610 ┆ lic ┆ 04  ┆ 09  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ lea ┆ -se ┆ 246 ┆ i,, ┆ i.a ┆ Shi ┆ che ┆ thw ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 610 ┆ :// ┆ :// ┆ 202 ┆     ┆ 151 ┆ -1  ┆ ore ┆ 6-A ┆ cle ┆ 8   ┆ -se ┆ N28 ┆ umi ┆ umi ┆ 190 ┆ umi ┆ 6   ┆ 141 ┆ er  ┆ 2-0 ┆ 707 ┆ 236 ┆ UMI ┆ p.s ┆ .sr ┆ -se ┆ .sr ┆ 000 ┆ 373 ┆ 757 ┆ 6   ┆ -se ┆ umi ┆ umi ┆ 58f ┆ ore ┆ .sr ┆ 729 ┆ ER  ┆ NSC ┆ .sr ┆ GLE ┆ lic ┆ p.s ┆ 610 ┆ 610 ┆ -se ┆ 610 ┆ -1  ┆ 610 ┆ 2-0 ┆ NA8 ┆ 128 ┆ 2-0 ┆ 202 │
│ 770 ┆ 770 ┆ q-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q-0 ┆ 292 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ r   ┆ q   ┆ 76  ┆ Aoi ┆ oi@ ┆ lat ┆ mis ┆ est ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 292 ┆ ftp ┆ ftp ┆ 187 ┆     ┆ 470 ┆     ┆ cta ┆ ID  ┆ 2h  ┆     ┆ q   ┆ 088 ┆ na  ┆ na  ┆ 770 ┆ na  ┆ fun ┆ 455 ┆     ┆ 8-2 ┆ 273 ┆ 731 ┆ NA  ┆ ra. ┆ a.e ┆ q-0 ┆ a.e ┆ f88 ┆ 557 ┆ 88  ┆ fun ┆ q-0 ┆ na  ┆ na  ┆ c80 ┆ cta ┆ a.e ┆ 757 ┆     ┆ RIP ┆ a.e ┆     ┆     ┆ ra. ┆ 292 ┆ 292 ┆ q   ┆ 292 ┆     ┆ 292 ┆ 8-1 ┆ 349 ┆ 903 ┆ 8-1 ┆ 187 │
│ 94  ┆ 96  ┆ 1-s ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-S ┆ 6   ┆ Aug ┆ 2   ┆ 2   ┆     ┆     ┆     ┆ ien ┆     ┆ RNA ┆     ┆     ┆     ┆ nor ┆ ifa ┆ try ┆ ern ┆ eri ┆     ┆     ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 6   ┆ .nc ┆ .nc ┆ ,   ┆     ┆ 78  ┆     ┆ l   ┆ OsT ┆ HS  ┆     ┆     ┆ 070 ┆ Tru ┆ Tru ┆ 94  ┆ Nov ┆ cti ┆ 6   ┆     ┆ 4   ┆ 3   ┆ 8   ┆     ┆ ebi ┆ bi. ┆ 1-S ┆ bi. ┆ 4c3 ┆     ┆ vs  ┆ cti ┆ 1-S ┆ Nov ┆ Nov ┆ 9cf ┆ l   ┆ bi. ┆ 2   ┆     ┆ TOM ┆ bi. ┆     ┆     ┆ ebi ┆ 6   ┆ 6_r ┆ sam ┆ 6_r ┆     ┆ 6   ┆ 1   ┆ 61  ┆ 42  ┆ 1   ┆     │
│     ┆     ┆ pt6 ┆     ┆     ┆     ┆     ┆     ┆     ┆ PT6 ┆ vs  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ thw ┆ rd  ┆ &   ┆ Uni ┆ or  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆ ade ┆ IR1 ┆ 1h  ┆     ┆     ┆ vs  ┆ Seq ┆ Seq ┆ vs  ┆ aSe ┆ ons ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆ .ac ┆ ac. ┆ PT6 ┆ ac. ┆ 444 ┆     ┆ 850 ┆ ons ┆ PT6 ┆ aSe ┆ aSe ┆ 8ef ┆ ade ┆ ac. ┆ vs  ┆     ┆ IC  ┆ ac. ┆     ┆     ┆ .ac ┆ vs  ┆ 1   ┆ ple ┆ 1   ┆     ┆ vs  ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ aid ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ est ┆     ┆ Mol ┆ ver ┆ St. ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆ 202 ┆     ┆ SRX ┆     ┆ noc ┆     ┆ vs  ┆     ┆     ┆ SAM ┆ sma ┆ Sma ┆ SRR ┆ q   ┆ in  ┆     ┆     ┆     ┆ 150 ┆ 210 ┆     ┆ .uk ┆ uk/ ┆ AID ┆ uk/ ┆ b23 ┆     ┆ 488 ┆ in  ┆ AID ┆ q   ┆ q   ┆ 299 ┆ noc ┆ uk/ ┆ 429 ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ GSM ┆ vs  ┆ pre ┆ vs  ┆     ┆ GSM ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ -ve ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Ve ┆ 610 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ern ┆     ┆ ecu ┆ sit ┆ SQB ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 610 ┆ .ni ┆ .ni ┆ 190 ┆     ┆ 151 ┆     ┆ arc ┆     ┆ Veh ┆     ┆     ┆ N28 ┆ ll  ┆ ll  ┆ 190 ┆ 600 ┆ tra ┆     ┆     ┆     ┆ 006 ┆ 879 ┆     ┆ :/v ┆ vol ┆ -Ve ┆ vol ┆ 7aa ┆     ┆ 97  ┆ tra ┆ -Ve ┆ 600 ┆ 600 ┆ 9b2 ┆ arc ┆ vol ┆ 355 ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 610 ┆ GSM ┆ par ┆ GSM ┆     ┆ 610 ┆     ┆     ┆ 128 ┆     ┆     │
│     ┆     ┆ h2h ┆     ┆     ┆     ┆     ┆     ┆     ┆ h2h ┆ 292 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆ lar ┆ y   ┆ RC  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 292 ┆ h.g ┆ h.g ┆     ┆     ┆ 470 ┆     ┆ ino ┆     ┆ cle ┆     ┆     ┆ 088 ┆ RNA ┆ RNA ┆ 770 ┆ 0   ┆ nsc ┆     ┆     ┆     ┆ 637 ┆ 434 ┆     ┆ ol1 ┆ 1/f ┆ h2h ┆ 1/s ┆ 55a ┆     ┆     ┆ nsc ┆ h2h ┆ 0   ┆ 0   ┆ e56 ┆ ino ┆ 1/f ┆ 835 ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 292 ┆ 610 ┆ ati ┆ 610 ┆     ┆ 292 ┆     ┆     ┆ 903 ┆     ┆     │
│     ┆     ┆ -hs ┆     ┆     ┆     ┆     ┆     ┆     ┆ -HS ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆ Gen ┆     ┆ 7-3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 76  ┆     ┆ ma  ┆     ┆ 2h  ┆     ┆     ┆ 072 ┆ lib ┆ ada ┆ 96  ┆ seq ┆ rip ┆     ┆     ┆     ┆ 3   ┆ 4   ┆     ┆ /sr ┆ ast ┆ -HS ┆ rr/ ┆ 7f7 ┆     ┆     ┆ rip ┆ -HS ┆     ┆ seq ┆ 6c9 ┆ ma  ┆ ast ┆ 5   ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 4   ┆ 292 ┆ on  ┆ 292 ┆     ┆ 4   ┆     ┆     ┆ 40  ┆     ┆     │
│     ┆     ┆ 1h  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1h  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆ rar ┆ pte ┆     ┆ uen ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆ r/S ┆ q/S ┆ 1h  ┆ SRR ┆ 5c7 ┆     ┆     ┆ tio ┆ 1h  ┆     ┆ uen ┆ 6e0 ┆     ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆     ┆ 4_r ┆ was ┆ 4_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1h  ┆     ┆     ┆     ┆ y   ┆ rs  ┆     ┆ cin ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆ RR1 ┆ vs  ┆ 190 ┆ 8f  ┆     ┆     ┆ nal ┆ vs  ┆     ┆ cin ┆ 23  ┆     ┆ RR1 ┆     ┆     ┆     ┆ 190 ┆     ┆     ┆ /SR ┆     ┆ 1   ┆ per ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆     ┆     ┆ g:  ┆ pau ┆     ┆     ┆     ┆     ┆     ┆     ┆ 90/ ┆ 90/ ┆ PRO ┆ /09 ┆ vs  ┆     ┆     ┆ pau ┆ PRO ┆     ┆ g:  ┆ vs  ┆     ┆ 90/ ┆     ┆     ┆     ┆ /09 ┆     ┆     ┆ R19 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p   ┆     ┆     ┆ GSM ┆ se- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 094 ┆ 094 ┆ -se ┆ 4/S ┆ d31 ┆     ┆     ┆ se- ┆ -se ┆     ┆ GSM ┆ d83 ┆     ┆ 094 ┆     ┆     ┆     ┆ 4/S ┆     ┆     ┆ 0/0 ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kit ┆     ┆     ┆ 610 ┆ rel ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ /SR ┆ q-0 ┆ RR1 ┆ 428 ┆     ┆     ┆ rel ┆ q-0 ┆     ┆ 610 ┆ 7f7 ┆     ┆ /SR ┆     ┆     ┆     ┆ RR1 ┆     ┆     ┆ 94/ ┆     ┆     ┆ acc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1-s ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 610 ┆ 610 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 292 ┆ eas ┆     ┆     ┆     ┆     ┆     ┆     ┆ R19 ┆ R19 ┆ 1-S ┆ 907 ┆ 898 ┆     ┆     ┆ eas ┆ 1-S ┆     ┆ 292 ┆ 5d3 ┆     ┆ R19 ┆     ┆     ┆     ┆ 907 ┆     ┆     ┆ SRR ┆     ┆     ┆ ord ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pt6 ┆     ┆     ┆     ┆     ┆     ┆     ┆ PT6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2nn ┆ 2nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6:  ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 077 ┆ 077 ┆ PT6 ┆ 709 ┆ fb0 ┆     ┆     ┆ e   ┆ PT6 ┆     ┆ 6:  ┆ 376 ┆     ┆ 077 ┆     ┆     ┆     ┆ 709 ┆     ┆     ┆ 190 ┆     ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ aid ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆ via ┆     ┆     ┆     ┆     ┆     ┆     ┆ 094 ┆ 094 ┆ AID ┆ 4   ┆ 622 ┆     ┆     ┆ via ┆ AID ┆     ┆ PRO ┆ f9d ┆     ┆ 094 ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆ 770 ┆     ┆     ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -ve ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Ve ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆ PAF ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ /SR ┆ -Ve ┆ vs  ┆ 348 ┆     ┆     ┆ PAF ┆ -Ve ┆     ┆ -se ┆ 133 ┆     ┆ /SR ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ 94/ ┆     ┆     ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ h2h ┆     ┆     ┆     ┆     ┆     ┆     ┆ h2h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 102 ┆ 102 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q-0 ┆ 1C  ┆     ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ R19 ┆ h2h ┆ ftp ┆ 65e ┆     ┆     ┆ 1C  ┆ h2h ┆     ┆ q-0 ┆ 949 ┆     ┆ R19 ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆ SRR ┆     ┆     ┆ pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -nh ┆     ┆     ┆     ┆     ┆     ┆     ┆ -NH ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 926 ┆ 926 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-S ┆ rec ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 077 ┆ -NH ┆ .sr ┆ ef4 ┆     ┆     ┆ rec ┆ -NH ┆     ┆ 1-S ┆ 8b6 ┆     ┆ 077 ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆ 190 ┆     ┆     ┆ vio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s1h ┆     ┆     ┆     ┆     ┆     ┆     ┆ S1h ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PT6 ┆ rui ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆ 094 ┆ S1h ┆ a.e ┆ b86 ┆     ┆     ┆ rui ┆ S1h ┆     ┆ PT6 ┆ 418 ┆     ┆ 094 ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆ 770 ┆     ┆     ┆ usl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ppl ┆ ppl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ AID ┆ tme ┆     ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ .fa ┆     ┆ bi. ┆ 1a6 ┆     ┆     ┆ tme ┆     ┆     ┆ AID ┆ 2c7 ┆     ┆ .fa ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆ 94. ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 6. GSE127844 PRO-seq (SINGLE) 

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validate date: 2025-05-03
- [Stress-induced transcriptional memory accelerates promoter-proximal pause release and decelerates termination over mitotic divisions](https://doi.org/10.1016/j.molcel.2021.03.007)
- 以前の研究で使用したPRO-seqのデータ
- HSF1のsilencing 処理も含まれている
- コントロールデータが含まれているので念の為収集
- [12_2_metadata_modified_true_no_control.ipynb](./12_2_metadata_modified_true_no_control.ipynb)から処理を移動

&nbsp;

### Adapter

- 以下のような記述が論文内にある
- `The libraries were generated using TruSeq small-RNA adaptors and sequenced using NextSeq500 (Illumina).`

In [19]:
GSE127844_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE127844/GSE127844_PEP/GSE127844_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("unknown").alias("rna_library"), # add rna_library column
    pl.lit("https://doi.org/10.1016/j.molcel.2021.03.007").alias("reference_doi"),  # add DOI of the reference paper column
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE127844_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE127844_metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE127844_iseq_filtered = GSE127844_iseq[[s.name for s in GSE127844_iseq if not (s.null_count() == GSE127844_iseq.height)]]

# display(GSE127844_PEP)

In [20]:
GSE127844_combined = GSE127844_PEP.join(
    GSE127844_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE127844_combined.write_csv(
    "../../Data/metadata/metadata_modified/GSE127844_pro_seq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE127844_combined)

In [21]:
defined_pairs_gse127844_pro_seq = [
    ("SRR8669164", "SRR8669162"), # PROseq_unCond_K562_scr_HS30_rep1 vs PROseq_unCond_K562_scr_HS0_rep1
    ("SRR8669165", "SRR8669163"), # PROseq_unCond_K562_scr_HS30_rep2 vs PROseq_unCond_K562_scr_HS0_rep2
    ("SRR8669166", "SRR8669162"), # PROseq_unCond_K562_scr_HS60_rep1 vs PROseq_unCond_K562_scr_HS0_rep1
    ("SRR8669169", "SRR8669167"), # PROseq_preCond_K562_scr_HS30_rep1 vs PROseq_preCond_K562_scr_HS0_rep1
    ("SRR8669170", "SRR8669168"), # PROseq_preCond_K562_scr_HS30_rep2 vs PROseq_preCond_K562_scr_HS0_rep2
    ("SRR8669171", "SRR8669167"), # PROseq_preCond_K562_scr_HS60_rep1 vs PROseq_preCond_K562_scr_HS0_rep1
    ("SRR8669173", "SRR8669172"), # PROseq_unCond_K562_shHSF1_HS30_rep1 vs PROseq_unCond_K562_shHSF1_HS0_rep1
    ("SRR8669174", "SRR8669172"), # PROseq_unCond_K562_shHSF1_HS60_rep1 vs PROseq_unCond_K562_shHSF1_HS0_rep1
    ("SRR8669176", "SRR8669175"), # PROseq_preCond_K562_shHSF1_HS30_rep1 vs PROseq_preCond_K562_shHSF1_HS0_rep1
    ("SRR8669177", "SRR8669175")  # PROseq_preCond_K562_shHSF1_HS60_rep1 vs PROseq_preCond_K562_shHSF1_HS0_rep1
]

paired_metadata_df_gse127844_pro_seq = create_paired_metadata(
    combined_df=GSE127844_combined,
    defined_sample_pairs=defined_pairs_gse127844_pro_seq,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse127844_pro_seq is not None:
    paired_metadata_df_gse127844_pro_seq.write_csv(
        "../../Data/metadata/metadata_paired/GSE127844_pro_seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse127844_pro_seq)

else:
    # Simple message helps you notice when no pairs were produced
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (10, 82)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ hsf ┆ pre ┆ gen ┆ rea ┆ sam ┆ rna ┆ ref ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ fir ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ 1_d ┆ con ┆ ome ┆ nal ┆ ple ┆ _li ┆ ere ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ st_ ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _ch ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ epl ┆ dit ┆ _bu ┆ yze ┆ _ac ┆ bra ┆ nce ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ cre ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ ara ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ eti ┆ ion ┆ ild ┆ d_b ┆ ces ┆ ry  ┆ _do ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ ate ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ cte ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ on  ┆ ing ┆ --- ┆ y   ┆ sio ┆ --- ┆ i   ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ d   ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ ris ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆ --- ┆ --- ┆ str ┆ --- ┆ n   ┆ str ┆ --- ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ tic ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆ str ┆ str ┆     ┆ str ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ s_c ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ PRO ┆ GSM ┆ Pub ┆ Mar ┆ Mar ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ hea ┆ tot ┆ nas ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ no  ┆ non ┆ hg1 ┆ nul ┆ SAM ┆ unk ┆ htt ┆ Ill ┆ SRR ┆ Nex ┆ Hea ┆ SRA ┆ oth ┆ 202 ┆ 830 ┆ 967 ┆ ILL ┆ Gen ┆ PRO ┆ SRP ┆ 301 ┆ Hea ┆ PRO ┆ Nex ┆ Nex ┆ 229 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Aft ┆ GSM ┆ GEO ┆ 202 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 866 ┆ 866 ┆ seq ┆ er  ┆ o   ┆ GLE ┆     ┆ 866 ┆ 546 ┆ seq ┆ 363 ┆ lic ┆ 05  ┆ 04  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ t   ┆ al  ┆ cen ┆ 185 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 363 ┆ E   ┆ 127 ┆     ┆ 546 ┆ dep ┆ e   ┆ 9   ┆ l   ┆ N11 ┆ now ┆ ps: ┆ umi ┆ 866 ┆ tSe ┆ t-i ┆ 856 ┆ er  ┆ 0-0 ┆ 749 ┆ 160 ┆ UMI ┆ eri ┆ seq ┆ 187 ┆ 573 ┆ t-i ┆ seq ┆ tSe ┆ tSe ┆ 196 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 363 ┆ 363 ┆ er  ┆ 363 ┆     ┆ 0-0 ┆ NA5 ┆ 443 ┆ 0-0 ┆ 127 │
│ 916 ┆ 916 ┆ _un ┆     ┆ sap ┆     ┆     ┆ 916 ┆ 513 ┆ _un ┆ 985 ┆ on  ┆ 201 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ sho ┆ RNA ┆ t   ┆ 73  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 985 ┆     ┆ 844 ┆     ┆ 513 ┆ let ┆     ┆     ┆     ┆ 055 ┆ n   ┆ //d ┆ na  ┆ 916 ┆ q   ┆ ndu ┆ 092 ┆     ┆ 3-0 ┆ 447 ┆ 325 ┆ NA  ┆ c   ┆ _un ┆ 541 ┆ 89  ┆ ndu ┆ _un ┆ q   ┆ q   ┆ 156 ┆     ┆ RIP ┆     ┆     ┆ 985 ┆ 985 ┆ tre ┆ 985 ┆     ┆ 3-0 ┆ 256 ┆ 897 ┆ 3-0 ┆ 844 │
│ 4   ┆ 2   ┆ con ┆     ┆ ien ┆     ┆     ┆ 4   ┆ 8   ┆ Con ┆ 2   ┆ Mar ┆ 9   ┆ 0   ┆     ┆     ┆     ┆ ien ┆     ┆ ck  ┆     ┆ RNA ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 2   ┆     ┆     ┆     ┆ 8   ┆ ion ┆     ┆     ┆     ┆ 121 ┆     ┆ oi. ┆ Tru ┆ 4   ┆ 500 ┆ ced ┆     ┆     ┆ 5   ┆ vs  ┆ vs  ┆     ┆     ┆ Con ┆     ┆ vs  ┆ ced ┆ Con ┆ 500 ┆ 500 ┆ 4   ┆     ┆ TOM ┆     ┆     ┆ 2   ┆ 2_r ┆ atm ┆ 2   ┆     ┆ 5   ┆ 36  ┆ 1   ┆ 5   ┆     │
│     ┆     ┆ d_k ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ d_K ┆ vs  ┆ 04  ┆     ┆ vs  ┆     ┆     ┆     ┆ s   ┆     ┆ (ad ┆     ┆ ,   ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ (sc ┆     ┆     ┆     ┆ vs  ┆     ┆ org ┆ Seq ┆ vs  ┆ seq ┆ tra ┆     ┆     ┆     ┆ 763 ┆ 878 ┆     ┆     ┆ d_K ┆     ┆ 276 ┆ tra ┆ d_K ┆     ┆ seq ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ent ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ 562 ┆ GSM ┆ 202 ┆     ┆ Jul ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆ Nor ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ ram ┆     ┆     ┆     ┆ SAM ┆     ┆ /10 ┆ Sma ┆ SRR ┆ uen ┆ nsc ┆     ┆     ┆     ┆ 923 ┆ 641 ┆     ┆     ┆ 562 ┆     ┆ 896 ┆ nsc ┆ 562 ┆     ┆ uen ┆ 210 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ s,  ┆ GSM ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ _sc ┆     ┆     ┆     ┆     ┆ 866 ┆ 546 ┆ _sc ┆ 363 ┆ 0   ┆     ┆ 29  ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆ mal ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 363 ┆     ┆     ┆     ┆ 546 ┆ ble ┆     ┆     ┆     ┆ N11 ┆     ┆ .10 ┆ ll  ┆ 866 ┆ cin ┆ rip ┆     ┆     ┆     ┆ 167 ┆ 086 ┆     ┆     ┆ _sc ┆     ┆ 11  ┆ rip ┆ _sc ┆     ┆ cin ┆ 441 ┆     ┆     ┆     ┆     ┆ 363 ┆ GSM ┆ the ┆ 363 ┆     ┆     ┆     ┆ 443 ┆     ┆     │
│     ┆     ┆ r_h ┆     ┆     ┆     ┆     ┆ 916 ┆ 513 ┆ r_H ┆ 985 ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆ ize ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 985 ┆     ┆     ┆     ┆ 513 ┆ d   ┆     ┆     ┆     ┆ 055 ┆     ┆ 16/ ┆ RNA ┆ 916 ┆ g:  ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r_H ┆     ┆     ┆ tio ┆ r_H ┆     ┆ g:  ┆ 043 ┆     ┆     ┆     ┆     ┆ 985 ┆ 363 ┆ cel ┆ 985 ┆     ┆     ┆     ┆ 896 ┆     ┆     │
│     ┆     ┆ s30 ┆     ┆     ┆     ┆     ┆ 2   ┆ 6   ┆ S30 ┆ 0   ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ to  ┆     ┆ d_P ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 6   ┆ seq ┆     ┆     ┆     ┆ 123 ┆     ┆ j.m ┆ ada ┆ 2   ┆ GSM ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S30 ┆     ┆     ┆ nal ┆ S30 ┆     ┆ GSM ┆ 6   ┆     ┆     ┆     ┆     ┆ 0   ┆ 985 ┆ ls  ┆ 0   ┆     ┆     ┆     ┆ 9   ┆     ┆     │
│     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pre ┆     ┆ ROs ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ olc ┆ pte ┆     ┆ 363 ┆ mem ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆     ┆     ┆ mem ┆ _re ┆     ┆ 363 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_r ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆ el. ┆ rs  ┆     ┆ 985 ┆ ory ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆ ory ┆ p1  ┆     ┆ 985 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dit ┆     ┆ unC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆ 2:  ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ pro ┆ vs  ┆     ┆ 2:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ har ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ion ┆     ┆ ond ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nsf ┆     ┆     ┆     ┆     ┆     ┆ 1.0 ┆     ┆     ┆ PRO ┆ fil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆ fil ┆ PRO ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ves ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ing ┆     ┆ _K5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ect ┆     ┆     ┆     ┆     ┆     ┆ 3.0 ┆     ┆     ┆ seq ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆ ed  ┆ seq ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _un ┆     ┆     ┆     ┆     ┆     ┆     ┆ _un ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ):  ┆     ┆ 62_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed) ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆     ┆     ┆ _un ┆ in  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _un ┆     ┆     ┆ in  ┆ _un ┆     ┆ _un ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 30  ┆     ┆ scr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆     ┆     ┆ hum ┆ Con ┆     ┆ Con ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cen ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ d_k ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ min ┆     ┆ _HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_K ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_K ┆     ┆     ┆ an  ┆ d_K ┆     ┆ d_K ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆ 30_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 562 ┆     ┆     ┆ K56 ┆ 562 ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fug ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _sc ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42° ┆     ┆ min ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sc ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _sc ┆     ┆     ┆ 2   ┆ _sc ┆     ┆ _sc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ r_h ┆     ┆     ┆     ┆     ┆     ┆     ┆ r_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C   ┆     ┆ usS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r_H ┆ ery ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r_H ┆     ┆     ┆ ery ┆ r_H ┆     ┆ r_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on, ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s0_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ S0_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wat ┆     ┆ tra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S30 ┆ thr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S0_ ┆     ┆     ┆ thr ┆ S0_ ┆     ┆ S30 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ nd. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _re ┆ ole ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆ ole ┆ rep ┆     ┆ _re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bat ┆     ┆ big ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆ uke ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆ uke ┆ 1   ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hed ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ Wig ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ mia ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mia ┆     ┆     ┆ Hom ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ twi ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hea ┆     ┆ Nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ ls. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls. ┆     ┆     ┆ sap ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

# Add Another PRO-seq data (or GRO-seq)

- これまでは、RNA-seqを含むプロジェクトに付随するPRO-seqのデータを処理してきた
- ここからは、新しく以下のクエリでGene Expression Omnibus (GEO)から取得してきたデータのメタデータを解析する
- `#12,"Search ((((""homo sapiens""[Organism]) AND ""other""[DataSet Type]) AND ""gds sra""[Filter])) AND ((((((""heat shock response""[MeSH Terms]) OR ""heat shock""[Description]) OR ""heat stress""[Description]) OR ""high temperature stress""[Description]) OR ""hyperthermia""[Description]) OR ""heat stroke""[Description])",45,02:52:10`

&nbsp;

- [../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md](../Data/curation/GEO_other_result/gds_other_result_summary_260123_modified.md)

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 7. GSE66448 (SINGLE) GRO-seq

- ✅ DOWNLOAD (yone-SSD)
<!-- - ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD) -->
<!-- - ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD) -->

&nbsp;

- validate date: 2026-02-21
- [Global SUMOylation on active chromatin is an acute heat stress response restricting transcription](https://doi.org/10.1186/s13059-015-0717-y)
- [GRO-Seq/BRIC-Seq/Bru-Seq/BruChase-Seq](https://jp.illumina.com/science/sequencing-method-explorer/kits-and-arrays/gro-seq-bric-seq-bru-seq-bruchase-seq.html)
- [Global Run-On sequencing (GRO-seq)](https://doi.org/10.1007/978-1-4939-4035-6_9)

&nbsp;

### Adapter

- PRO-seq と手法が異なるので注意
- [GSM1622614](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1622614) などを参考にする
- `Poly(A)-tailing was followed by cDNA synthesis using complementary poly(T)-primers.` と書いてある
- [Global Run-On sequencing (GRO-seq)](https://doi.org/10.1007/978-1-4939-4035-6_9) などを見ると、`NTI223 - /5Phos/GAT CGT CGG ACT GTA GAA CTC T/idSp/CA AGC AGA AGA CGG CAT ACG ATT TTT TTT TTT TTT TTT TTT VN` といった配列が記載されている
- [proseq2.0](https://github.com/Danko-Lab/proseq2.0)を使用する前に、poly(A) を除去するステップを噛ませる必要がある

In [22]:
GSE66448_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE66448/GSE66448_PEP/GSE66448_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    (pl.col("protocol") != "ChIP")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    (pl.lit("unknown").alias("rna_library")),
    (pl.lit("https://doi.org/10.1186/s13059-015-0717-y").alias("reference_doi")),
    (pl.lit("43 C").alias("stress treatment temperature")),
    (pl.lit("30 min.").alias("stress treatment time")),
    (pl.lit("37 C").alias("control treatment temperature"))
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE66448_iseq = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE66448.metadata.tsv",
    separator='\t'
).drop(
    drop_columns_list
)

GSE66448_iseq_filtered = GSE66448_iseq[[s.name for s in GSE66448_iseq if not (s.null_count() == GSE66448_iseq.height)]]

# display(GSE66448_PEP)

In [23]:
GSE66448_combined = GSE66448_PEP.join(
    GSE66448_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).sort(
    "sample_geo_accession", descending=True
)

GSE66448_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE66448_groseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE66448_combined)

In [24]:
defined_pairs_gse66448 = [
    ("SRR1823903", "SRR1823901"), # K562-GROseq-HS-rep1 vs K562-GROseq-C-rep1
    ("SRR1823904", "SRR1823902")  # K562-GROseq-Hs-rep2 vs K562-GROseq-C-rep2
]

paired_metadata_df_gse66448 = create_paired_metadata(
    combined_df=GSE66448_combined,
    defined_sample_pairs=defined_pairs_gse66448,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse66448 is not None:
    paired_metadata_df_gse66448.write_csv(
        "../../Data/metadata/metadata_proseq/GSE66448_groseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse66448)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (2, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ tre ┆ chi ┆ pro ┆ gen ┆ sup ┆ sam ┆ rna ┆ ref ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ ncb ┆ sam ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ atm ┆ p_a ┆ ces ┆ ome ┆ ple ┆ ple ┆ _li ┆ ere ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ i_r ┆ ple ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _tr ┆ _gr ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ent ┆ nti ┆ sed ┆ _bu ┆ men ┆ _ac ┆ bra ┆ nce ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ epo ┆ _de ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ eat ┆ owt ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ 1   ┆ bod ┆ _da ┆ ild ┆ tar ┆ ces ┆ ry  ┆ _do ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ rti ┆ scr ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ men ┆ h_p ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ --- ┆ y   ┆ ta_ ┆ --- ┆ y_f ┆ sio ┆ --- ┆ i   ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ ng_ ┆ ipt ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ t_p ┆ rot ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ str ┆ --- ┆ fil ┆ str ┆ ile ┆ n   ┆ str ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ sta ┆ ion ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ rot ┆ oco ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ str ┆ e   ┆     ┆ s_f ┆ --- ┆     ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆ nda ┆ _ri ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ oco ┆ l_c ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆ orm ┆ str ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆ rd  ┆ ght ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ l_c ┆ h1  ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ at_ ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ h1  ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nte ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nt  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ k56 ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ K56 ┆ GSM ┆ Pub ┆ Mar ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ Hea ┆ K56 ┆ tot ┆ Nuc ┆ nas ┆ GPL ┆ Ein ┆ ein ┆ Bio ┆ Sch ┆ Uni ┆ Yli ┆ Kuo ┆ 702 ┆ Fin ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ hea ┆ nul ┆ K56 ┆ hg1 ┆ ChI ┆ SAM ┆ unk ┆ htt ┆ 43  ┆ 30  ┆ 37  ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ oth ┆ 202 ┆ 907 ┆ ILL ┆ Gen ┆ K56 ┆ SRP ┆ 192 ┆ Hea ┆ GEN ┆ K56 ┆ Ill ┆ Ill ┆ 979 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ GSM ┆ GSM ┆ Nuc ┆ GSM ┆ GEO ┆ K56 ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 182 ┆ 182 ┆ 2-g ┆ er  ┆ o   ┆ GLE ┆     ┆ 182 ┆ 895 ┆ 2-G ┆ 162 ┆ lic ┆ 03  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ t   ┆ 2   ┆ al  ┆ lei ┆ cen ┆ 111 ┆ ari ┆ ari ┆ med ┆ ool ┆ ver ┆ opi ┆ pio ┆ 10  ┆ lan ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 162 ┆ E   ┆ 664 ┆     ┆ 895 ┆ 2   ┆ t   ┆ l   ┆ 2-G ┆ 9   ┆ P-s ┆ N03 ┆ now ┆ ps: ┆ C   ┆ min ┆ C   ┆ 182 ┆ umi ┆ o   ┆ 245 ┆ er  ┆ 0-0 ┆ 042 ┆ UMI ┆ eri ┆ 2-G ┆ 055 ┆ 115 ┆ t   ┆ ERA ┆ 2-G ┆ umi ┆ umi ┆ 790 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ 162 ┆ 162 ┆ lei ┆ 162 ┆     ┆ 2   ┆ _ta ┆ 5-0 ┆ o   ┆ 6   ┆ NA2 ┆ 861 ┆ 5-0 ┆ 664 │
│ 390 ┆ 390 ┆ ros ┆     ┆ sap ┆     ┆     ┆ 390 ┆ 425 ┆ ROs ┆ 261 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ sho ┆ cel ┆ RNA ┆ wer ┆ t   ┆ 54  ┆ ,A, ┆ .ni ┆ ici ┆ of  ┆ sit ┆ sto ┆     ┆     ┆ d   ┆ na  ┆     ┆ rip ┆     ┆ 261 ┆     ┆ 48  ┆     ┆ 425 ┆     ┆ sho ┆     ┆ ROs ┆     ┆ eq  ┆ 383 ┆ n   ┆ //d ┆     ┆ .   ┆     ┆ 390 ┆ na  ┆ sap ┆ 323 ┆     ┆ 5-0 ┆ 648 ┆ NA  ┆ c   ┆ ROs ┆ 752 ┆ 80  ┆ sho ┆ TED ┆ ROs ┆ na  ┆ na  ┆ 580 ┆     ┆ RIP ┆     ┆     ┆ 261 ┆ 261 ┆ wer ┆ 261 ┆     ┆     ┆ x:t ┆ 7-0 ┆ sap ┆     ┆ 769 ┆ 221 ┆ 7-0 ┆ 48  │
│ 3   ┆ 1   ┆ eq- ┆     ┆ ien ┆     ┆     ┆ 3   ┆ vs  ┆ eq- ┆ 4   ┆ Jul ┆ 5   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆ ck  ┆ ls  ┆     ┆ e   ┆ RNA ┆     ┆ Nis ┆ ska ┆ ne  ┆ Med ┆ y   ┆ nra ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 4   ┆     ┆     ┆     ┆ vs  ┆     ┆ ck  ┆     ┆ eq- ┆     ┆ and ┆ 046 ┆     ┆ oi. ┆     ┆     ┆     ┆ 3   ┆ HiS ┆ ien ┆     ┆     ┆ 3   ┆ vs  ┆     ┆     ┆ eq- ┆     ┆ vs  ┆ ck- ┆ _FI ┆ eq- ┆ HiS ┆ HiS ┆ vs  ┆     ┆ TOM ┆     ┆     ┆ 4   ┆ 4_r ┆ e   ┆ 4   ┆     ┆     ┆ err ┆ 9   ┆ ien ┆     ┆ 90  ┆ vs  ┆ 9   ┆     │
│     ┆     ┆ hs- ┆     ┆ s   ┆     ┆     ┆ vs  ┆ SRX ┆ HS- ┆ vs  ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆ for ┆ wer ┆     ┆ ext ┆ ,   ┆     ┆ kan ┆ nen ┆     ┆ ici ┆ of  ┆ nta ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ SRX ┆     ┆ (30 ┆     ┆ HS- ┆     ┆ GRO ┆ vs  ┆     ┆ org ┆     ┆     ┆     ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆ vs  ┆ 109 ┆     ┆     ┆ HS- ┆     ┆ 236 ┆ ind ┆ LE  ┆ HS- ┆ eq  ┆ eq  ┆ 120 ┆     ┆ IC  ┆     ┆     ┆ vs  ┆ 1   ┆ ext ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ SRR ┆ 895 ┆ rep ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GRO ┆ e   ┆     ┆ rac ┆ GRO ┆     ┆ en  ┆ @ue ┆     ┆ ne  ┆ Eas ┆ 8   ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ 895 ┆     ┆ min ┆     ┆ plu ┆     ┆ -se ┆ SAM ┆     ┆ /10 ┆     ┆     ┆     ┆ SRR ┆ 200 ┆     ┆     ┆     ┆ 201 ┆ 417 ┆     ┆     ┆ rep ┆     ┆ 186 ┆ uce ┆     ┆ rep ┆ 200 ┆ 200 ┆ 455 ┆     ┆     ┆     ┆     ┆ GSM ┆ vs  ┆ rac ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ 861 ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆ 182 ┆ 423 ┆ 1   ┆ 162 ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆ gro ┆     ┆ ted ┆ -se ┆     ┆     ┆ f.f ┆     ┆     ┆ ter ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 162 ┆     ┆     ┆     ┆ 423 ┆     ┆ at  ┆     ┆ s.b ┆     ┆ q   ┆ N03 ┆     ┆ .11 ┆     ┆     ┆     ┆ 182 ┆ 0   ┆     ┆     ┆     ┆ 9-1 ┆ 027 ┆     ┆     ┆ 1   ┆     ┆ 77  ┆ d   ┆     ┆ 1   ┆ 0   ┆ 0   ┆ 252 ┆     ┆     ┆     ┆     ┆ 162 ┆ GSM ┆ ted ┆ 162 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 222 ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 390 ┆     ┆ vs  ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ wn  ┆     ┆ fro ┆ q   ┆     ┆     ┆ i   ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆     ┆ edG ┆     ┆ sig ┆ 383 ┆     ┆ 86/ ┆     ┆     ┆     ┆ 390 ┆ seq ┆     ┆     ┆     ┆ 0-3 ┆ 5   ┆     ┆     ┆ vs  ┆     ┆     ┆ cha ┆     ┆ vs  ┆     ┆ seq ┆ 7   ┆     ┆     ┆     ┆     ┆ 261 ┆ 162 ┆ fro ┆ 261 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ k56 ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ K56 ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ was ┆ in  ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆ Fin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ deg ┆     ┆ rap ┆     ┆ nal ┆ 044 ┆     ┆ s13 ┆     ┆     ┆     ┆ 1   ┆ uen ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆ nge ┆     ┆ K56 ┆     ┆ uen ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 261 ┆ m   ┆ 2   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 2-g ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ don ┆ RPM ┆     ┆ 5-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ lan ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆     ┆ h.g ┆     ┆ int ┆     ┆     ┆ 059 ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-G ┆     ┆     ┆ s   ┆     ┆ 2-G ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2_r ┆ 5-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ros ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ I16 ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C)  ┆     ┆ z;  ┆     ┆ ens ┆     ┆     ┆ -01 ┆     ┆     ┆     ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROs ┆     ┆     ┆ in  ┆     ┆ ROs ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq- ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆ 40  ┆     ┆ mil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆ K56 ┆     ┆ iti ┆     ┆     ┆ 5-0 ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq- ┆     ┆     ┆ chr ┆     ┆ eq- ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c-r ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 43  ┆ med ┆     ┆ lio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ con ┆     ┆ 2-G ┆     ┆ es  ┆     ┆     ┆ 717 ┆     ┆     ┆     ┆     ┆ 162 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-r ┆     ┆     ┆ oma ┆     ┆ C-r ┆     ┆ 162 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆ ium ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tro ┆     ┆ ROs ┆     ┆ as  ┆     ┆     ┆ -y  ┆     ┆     ┆     ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆     ┆     ┆ tin ┆     ┆ ep1 ┆     ┆ 261 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆ sup ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ eq- ┆     ┆ bed ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bin ┆     ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ wat ┆ ple ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (37 ┆     ┆ HS- ┆     ┆ Gra ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ din ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆ men ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ deg ┆     ┆ min ┆     ┆ ph  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆ 2-G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bat ┆ ted ┆     ┆ nuc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ree ┆     ┆ us. ┆     ┆ fil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆ ROs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nuc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ wit ┆     ┆ lea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C)  ┆     ┆ bed ┆     ┆ es. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SUM ┆     ┆     ┆     ┆ eq- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 8. [GSE89230](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE89230) (SINGLE) PRO-seq

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validate date: 2026-02-21
- [Transcriptional response to stress is pre-wired by promoter and enhancer architecture](https://doi.org/10.1038/s41467-017-00151-0)
- 42℃ 30 minutes で K562 での研究
- コントロールも存在するので収集する

&nbsp;

### Adapter

- Gene Expression Omnibus の [GSE89230](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE89230) のページ (e.g., [GSM2361442](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2361442)) を見ると、以下のような記載が `Extraction protocol` に書いてある
- `The libraries were generated using TruSeq small-RNA adaptors, amplified 11 cycles, gel-purified and size-selected to 140-350 bp fragments. The libraries were sequenced using HiSeq 2000 (Illumina).`

In [25]:
GSE89230_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE89230/GSE89230_PEP/GSE89230_PEP_raw.csv",
    separator=','
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    pl.lit("Illumina TruSeq Small RNA Library Preparation Kits").alias("rna_library"), # add rna_library column from article (Illumina)
    pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE89230 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE89230_metadata.tsv",
    separator='\t'
)

GSE89230_iseq_filtered = GSE89230[[s.name for s in GSE89230 if not (s.null_count() == GSE89230.height)]]

# pl.Config.set_tbl_rows(4)
# display(GSE89230_PEP)

In [26]:
GSE89230_combined = GSE89230_PEP.join(
    GSE89230_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE89230_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE89230_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE89230_combined)

In [27]:
defined_pairs_gse89230 = [
    ("SRR4454569", "SRR4454567"), # PRO-seq K562 HS30, replicate 1 vs PRO-seq K562 NHS, replicate 1
    ("SRR4454570", "SRR4454568")  # PRO-seq K562 HS30, replicate 2 vs PRO-seq K562 NHS, replicate 2
]

paired_metadata_df_gse89230 = create_paired_metadata(
    combined_df=GSE89230_combined, 
    defined_sample_pairs=defined_pairs_gse89230,
    sample_id_column_name="accession" # default value, but specified to clarify
)

if paired_metadata_df_gse89230 is not None:
    paired_metadata_df_gse89230.write_csv(
        "../../Data/metadata/metadata_proseq/GSE89230_proseq_paired_metadata.tsv",
        separator='\t'
    )

display(paired_metadata_df_gse89230)

shape: (2, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ tre ┆ lib ┆ gen ┆ sam ┆ rna ┆ ada ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ sra ┆ fas ┆ ncb ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ sra ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ atm ┆ rar ┆ ome ┆ ple ┆ _li ┆ pte ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _fi ┆ _as ┆ tq_ ┆ i_r ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ent ┆ y_s ┆ _bu ┆ _ac ┆ bra ┆ r   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ le_ ┆ per ┆ gal ┆ epo ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ tra ┆ ild ┆ ces ┆ ry  ┆ --- ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rol ┆ a   ┆ axy ┆ rti ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ teg ┆ --- ┆ sio ┆ --- ┆ str ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ e   ┆ --- ┆ --- ┆ ng_ ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ y   ┆ str ┆ n   ┆ str ┆     ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ --- ┆ str ┆ str ┆ sta ┆ ion ┆ str ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ str ┆     ┆     ┆ nda ┆ _ri ┆     ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ rd  ┆ ght ┆     ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ PRO ┆ GSM ┆ Pub ┆ Oct ┆ May ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ tot ┆ Nas ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ 30m ┆ PRO ┆ hg1 ┆ SAM ┆ Ill ┆ Ill ┆ SRR ┆ Ill ┆ Hom ┆ SRA ┆ oth ┆ 201 ┆ 784 ┆ 885 ┆ ILL ┆ ARC ┆ fas ┆ ftp ┆ Gen ┆ PRO ┆ ftp ┆ 469 ┆ SRP ┆ 226 ┆ Nuc ┆ GEN ┆ PRO ┆ Ill ┆ Ill ┆ 4b8 ┆ ftp ┆ 168 ┆ OTH ┆ TRA ┆ ftp ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Aft ┆ GSM ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 445 ┆ 445 ┆ -se ┆ er  ┆ o   ┆ GLE ┆     ┆ 445 ┆ 227 ┆ -se ┆ 236 ┆ lic ┆ 27  ┆ 15  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ al  ┆ cen ┆ 111 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 236 ┆ E   ┆ 892 ┆     ┆ 227 ┆ in  ┆ -se ┆ 9   ┆ N05 ┆ umi ┆ umi ┆ 445 ┆ umi ┆ o   ┆ 487 ┆ er  ┆ 7-0 ┆ 528 ┆ 201 ┆ UMI ┆ HIV ┆ p.s ┆ .sr ┆ eri ┆ -se ┆ .sr ┆ e91 ┆ 092 ┆ 247 ┆ leo ┆ ERA ┆ -se ┆ umi ┆ umi ┆ 96b ┆ .sr ┆ 782 ┆ ER  ┆ NSC ┆ .sr ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 236 ┆ 236 ┆ er  ┆ 236 ┆ _ta ┆ 7-0 ┆ o   ┆ 6   ┆ NA3 ┆ 176 ┆ 7-0 ┆ 892 │
│ 456 ┆ 456 ┆ q_k ┆     ┆ sap ┆     ┆     ┆ 456 ┆ 112 ┆ q   ┆ 144 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ cel ┆ sap ┆     ┆ RNA ┆ t   ┆ 54  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 144 ┆     ┆ 30  ┆     ┆ 112 ┆ at  ┆ q   ┆     ┆ 946 ┆ na  ┆ na  ┆ 456 ┆ na  ┆ sap ┆ 200 ┆     ┆ 5-2 ┆ 823 ┆ 932 ┆ NA  ┆ AL_ ┆ ra. ┆ a.e ┆ c   ┆ q   ┆ a.e ┆ 9a9 ┆ 163 ┆ 275 ┆ tid ┆ TED ┆ q   ┆ na  ┆ na  ┆ ad5 ┆ a.e ┆ 973 ┆     ┆ RIP ┆ a.e ┆     ┆     ┆ ra. ┆ 67; ┆ 144 ┆ 144 ┆ tre ┆ 144 ┆ x;e ┆ 5-2 ┆ sap ┆     ┆ 507 ┆ 222 ┆ 5-2 ┆ 30  │
│ 9   ┆ 7   ┆ 562 ┆     ┆ ien ┆     ┆     ┆ 9   ┆ 3   ┆ K56 ┆ 4   ┆ May ┆ 6   ┆ 9   ┆     ┆     ┆ ls  ┆ ien ┆     ┆     ┆ RNA ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ HiS ┆     ┆ tom ┆     ┆ 4   ┆     ┆     ┆     ┆ 3   ┆ 42° ┆     ┆     ┆ 060 ┆ Tru ┆ Tru ┆ 9   ┆ HiS ┆ ien ┆     ┆     ┆ 3   ┆ 4   ┆ 1   ┆     ┆ FIL ┆ ebi ┆ bi. ┆     ┆ K56 ┆ bi. ┆ 2c4 ┆     ┆ vs  ┆ e-r ┆ _FI ┆ K56 ┆ HiS ┆ HiS ┆ 32e ┆ bi. ┆ 41  ┆     ┆ TOM ┆ bi. ┆     ┆     ┆ ebi ┆ 275 ┆ 4   ┆ 4_r ┆ tme ┆ 4   ┆ nv_ ┆ 3   ┆ ien ┆     ┆ 85  ┆ 9   ┆ 3   ┆     │
│     ┆     ┆ _hs ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ 2   ┆ vs  ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ ,   ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ eq  ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆ C   ┆     ┆     ┆ vs  ┆ Seq ┆ Seq ┆ vs  ┆ eq  ┆ s   ┆     ┆     ┆     ┆ vs  ┆ vs  ┆     ┆ E   ┆ .ac ┆ ac. ┆     ┆ 2   ┆ ac. ┆ e60 ┆     ┆ 133 ┆ eso ┆ LE  ┆ 2   ┆ eq  ┆ eq  ┆ 478 ┆ ac. ┆ vs  ┆     ┆ IC  ┆ ac. ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ nts ┆ vs  ┆ tax ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ 30_ ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ HS3 ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nor ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ 200 ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆ (HS ┆     ┆     ┆ SAM ┆ Sma ┆ Sma ┆ SRR ┆ 200 ┆     ┆     ┆     ┆     ┆ 461 ┆ 543 ┆     ┆     ┆ .uk ┆ uk/ ┆     ┆ HS3 ┆ uk/ ┆ 3b1 ┆     ┆ 803 ┆ lut ┆     ┆ HS3 ┆ 200 ┆ 200 ┆ fa9 ┆ uk/ ┆ 998 ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ,   ┆ GSM ┆ :te ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆ 445 ┆ 227 ┆ 0,  ┆ 236 ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 236 ┆     ┆     ┆     ┆ 227 ┆ 30) ┆     ┆     ┆ N05 ┆ ll  ┆ ll  ┆ 445 ┆ 0   ┆     ┆     ┆     ┆     ┆ 274 ┆ 012 ┆     ┆     ┆ :/v ┆ vol ┆     ┆ 0,  ┆ vol ┆ 8bf ┆     ┆ 486 ┆ ion ┆     ┆ 0,  ┆ 0   ┆ 0   ┆ 61b ┆ vol ┆ 853 ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 4;3 ┆ 236 ┆ GSM ┆ the ┆ 236 ┆ rre ┆     ┆     ┆     ┆     ┆ 176 ┆     ┆     │
│     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆ 456 ┆ 112 ┆ rep ┆ 144 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ize ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 144 ┆     ┆     ┆     ┆ 112 ┆ vs  ┆     ┆     ┆ 946 ┆ RNA ┆ RNA ┆ 456 ┆ seq ┆     ┆     ┆     ┆     ┆ 152 ┆ 917 ┆     ┆     ┆ ol1 ┆ 1/f ┆     ┆ rep ┆ 1/s ┆ 984 ┆     ┆     ┆ map ┆     ┆ rep ┆     ┆ seq ┆ 2a8 ┆ 1/f ┆ 615 ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 320 ┆ 144 ┆ 236 ┆ cel ┆ 144 ┆ str ┆     ┆     ┆     ┆     ┆ 222 ┆     ┆     │
│     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆ 7   ┆ 1   ┆ lic ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_P ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 1   ┆ Non ┆     ┆     ┆ 058 ┆ Lib ┆ ada ┆ 7   ┆ uen ┆     ┆     ┆     ┆     ┆ 2   ┆ 1   ┆     ┆     ┆ /sr ┆ ast ┆     ┆ lic ┆ rr/ ┆ 6c6 ┆     ┆     ┆ s   ┆     ┆ lic ┆     ┆ uen ┆ a68 ┆ ast ┆ 3   ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 8;6 ┆ 2   ┆ 144 ┆ ls  ┆ 2   ┆ ial ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     │
│     ┆     ┆ _1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RO- ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -tr ┆     ┆     ┆     ┆ rar ┆ pte ┆     ┆ cin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r/S ┆ q/S ┆     ┆ ate ┆ SRR ┆ 663 ┆     ┆     ┆ of  ┆     ┆ ate ┆     ┆ cin ┆ ccb ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 2_r ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eat ┆     ┆     ┆     ┆ y   ┆ rs  ┆     ┆ g:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR4 ┆ RR4 ┆     ┆ 1   ┆ 445 ┆ 86  ┆     ┆     ┆ nas ┆     ┆ 1   ┆     ┆ g:  ┆ 84  ┆ RR4 ┆     ┆     ┆     ┆ 445 ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _K5 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ Pre ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 45/ ┆ 45/ ┆     ┆ vs  ┆ /00 ┆ vs  ┆     ┆     ┆ cen ┆     ┆ vs  ┆     ┆ GSM ┆ vs  ┆ 45/ ┆     ┆     ┆     ┆ /00 ┆     ┆     ┆ R44 ┆ 213 ┆     ┆     ┆ har ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (NH ┆     ┆     ┆     ┆ par ┆     ┆     ┆ 236 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 009 ┆ 009 ┆     ┆ PRO ┆ 9/S ┆ 670 ┆     ┆     ┆ t   ┆     ┆ PRO ┆     ┆ 236 ┆ 85e ┆ 009 ┆     ┆     ┆     ┆ 9/S ┆     ┆     ┆ 5/0 ┆ ;33 ┆     ┆     ┆ ves ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q_k ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ com ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S)  ┆     ┆     ┆     ┆ ati ┆     ┆     ┆ 144 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ /SR ┆     ┆ -se ┆ RR4 ┆ 8d3 ┆     ┆     ┆ RNA ┆     ┆ -se ┆     ┆ 144 ┆ 95c ┆ /SR ┆     ┆     ┆     ┆ RR4 ┆     ┆     ┆ 09/ ┆ 511 ┆     ┆     ┆ ted ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 562 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ 4:  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R44 ┆ R44 ┆     ┆ q   ┆ 454 ┆ a34 ┆     ┆     ┆ -sy ┆     ┆ q   ┆     ┆ 4:  ┆ bd7 ┆ R44 ┆     ┆     ┆     ┆ 454 ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ by  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _nh ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kit ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 545 ┆ 545 ┆     ┆ K56 ┆ 569 ┆ 0c9 ┆     ┆     ┆ nth ┆     ┆ K56 ┆     ┆ PRO ┆ b6f ┆ 545 ┆     ┆     ┆     ┆ 569 ┆     ┆     ┆ 445 ┆ 11; ┆     ┆     ┆ cen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 69  ┆ 69/ ┆     ┆ 2   ┆ vs  ┆ c80 ┆     ┆     ┆ esi ┆     ┆ 2   ┆     ┆ -se ┆ 0f9 ┆ 69/ ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ 456 ┆ 895 ┆     ┆     ┆ tri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ epl ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ SRR ┆     ┆ NHS ┆ ftp ┆ 041 ┆     ┆     ┆ s   ┆     ┆ NHS ┆     ┆ q   ┆ a2d ┆ SRR ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆ 9/S ┆ 93; ┆     ┆     ┆ fug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ica ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 445 ┆     ┆ ,   ┆ .sr ┆ b84 ┆     ┆     ┆ in  ┆     ┆ ,   ┆     ┆ K56 ┆ c36 ┆ 445 ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆ RR4 ┆ 774 ┆     ┆     ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ te_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 456 ┆     ┆ rep ┆ a.e ┆ 6b6 ┆     ┆     ┆ hum ┆     ┆ rep ┆     ┆ 2   ┆ aa3 ┆ 456 ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆ 454 ┆ 2;7 ┆     ┆     ┆ on, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ lic ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S30 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ra. ┆ 9.f ┆     ┆ lic ┆ bi. ┆ 3a5 ┆     ┆     ┆ an  ┆     ┆ lic ┆     ┆ HS3 ┆ f9a ┆ 9.f ┆     ┆     ┆     ┆ bi. ┆     ┆     ┆ 569 ┆ 776 ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ate ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _pl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ebi ┆ ast ┆     ┆ ate ┆ ac. ┆ 18d ┆     ┆     ┆ K56 ┆     ┆ ate ┆     ┆ 0,  ┆ 447 ┆ ast ┆     ┆     ┆     ┆ ac. ┆     ┆     ┆ .fa ┆ ;11 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 9. GSE112379 (SINGLE) PRO-seq

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- [Nascent-protein ubiquitination is required for heat shock–induced gene downregulation in human cells](https://doi.org/10.1038/s41594-018-0182-x)
- 熱ストレス下のデータが入手できるため、収集する
- 以下のような記載が論文にあった
- `Heat shock treatment: Unless otherwise stated, heat shock treatment was done by moving tissue-culture plates with growing cells from an incubator at normal growth temperature (37 °C) into an incubator at heat-shock temperatures (43 °C) for 1.5 h. Heat-shock treatment of K562 cells was done for 0.5 h. Heat-shock treatment of HeLa cells was done at 42 °C for the indicated times for activation and attenuation phase experiments29. To explore whether different heat-shock paradigms could influence the results obtained, we also applied acute heat shock, as described51. Briefly, two plates were grown up to 80% confluence. Medium from one of the plates was removed, preheated to 43 °C and added to the other plate from which the medium was withdrawn. The plate was then placed at 43 °C for 1.5 h.`
- HEK293 cellなので、43℃, 1.5hだと考えられる

&nbsp;

### Adapter

- [GSM3068957](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3068957) の `Extraction protocol` には以下のような記載がある
- `A 5’ RNA adaptor (VRA5) was ligated at the 5’ end of RNA using the ligation mix described previously.`
- VRA5 adapter sequence は、[Base-Pair Resolution Genome-Wide Mapping Of Active RNA polymerases using Precision Nuclear Run-On (PRO-seq)](https://doi.org/10.1038/nprot.2016.086) を見ると `CCUUGGCACCCGAGAAUUCCA` と書いてある
- これの逆相補鎖が `TGGAATTCTCGGGTGCCAAGG` になるので、Truseq Small RNA adapter に合致
- おそらく以下のような理解

```text
RNA:
5′-[VRA5]-[nascent RNA]-[VRA3]-3′
                         ← sequencing starts here

FASTQ read:
5′-[reverse complement of nascent RNA]-[reverse complement of VRA5]-3′
```

In [28]:
GSE112379_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE112379/GSE112379_PEP/GSE112379_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    (pl.col("protocol") != "ChIP")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    (pl.lit("Custom PRO-seq library preparation based on Mahat et al. (2016)").alias("rna_library")),
    (pl.lit("https://doi.org/10.1038/s41594-018-0182-x").alias("reference_doi")),
    (pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")),
    (pl.lit("43 C").alias("stress treatment temperature")),
    (pl.lit("90 min.").alias("stress treatment time")),
    (pl.lit("37 C (inferred)").alias("control treatment temperature"))
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE112379 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE112379.metadata.tsv",
    separator='\t'
)

GSE112379_iseq_filtered = GSE112379[[s.name for s in GSE112379 if not (s.null_count() == GSE112379.height)]]


# display(GSE112379_PEP)

In [29]:
GSE112379_combined = GSE112379_PEP.join(
    GSE112379_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE112379_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE112379_proseq_modified_metadata.tsv",
    separator='\t'
)

# pl.Config.set_tbl_rows(30)
# display(GSE112379_combined)

In [30]:
# Manual defined pairs
defined_pairs_gse112379 = [
    ("SRR6904129", "SRR6904125"), # HEK_HS_Proseq_Rep1 vs HEK_NHS_Proseq_Rep1
    ("SRR6904130", "SRR6904126"), # HEK_HS_Proseq_Rep2 vs HEK_NHS_Proseq_Rep2
    ("SRR6904131", "SRR6904127"), # HEK_HS_Proseq_Rep3 vs HEK_NHS_Proseq_Rep3
    ("SRR6904132", "SRR6904128") # HEK_HS_Proseq_Rep4 vs HEK_NHS_Proseq_Rep4
]

paired_metadata_df_gse112379 = create_paired_metadata(
    combined_df=GSE112379_combined,
    defined_sample_pairs=defined_pairs_gse112379,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse112379 is not None:
    paired_metadata_df_gse112379.write_csv(
        "../../Data/metadata/metadata_proseq/GSE112379_proseq_paired_metadata.tsv",
        separator='\t'  
    )
    display(paired_metadata_df_gse112379)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 96)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ tre ┆ con ┆ lib ┆ gen ┆ sam ┆ rna ┆ ref ┆ ada ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ sra ┆ fas ┆ ncb ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ sra ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ atm ┆ dit ┆ rar ┆ ome ┆ ple ┆ _li ┆ ere ┆ pte ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _fi ┆ _as ┆ tq_ ┆ i_r ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _gr ┆ _mo ┆ _ex ┆ _da ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ent ┆ ion ┆ y_s ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ r   ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ le_ ┆ per ┆ gal ┆ epo ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ owt ┆ lec ┆ tra ┆ ta_ ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ tra ┆ ild ┆ ces ┆ ry  ┆ _do ┆ --- ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rol ┆ a   ┆ axy ┆ rti ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ h_p ┆ ule ┆ ct_ ┆ pro ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ teg ┆ --- ┆ sio ┆ --- ┆ i   ┆ str ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ e   ┆ --- ┆ --- ┆ ng_ ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ rot ┆ _ch ┆ pro ┆ ces ┆ _id ┆ nam ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆ y   ┆ str ┆ n   ┆ str ┆ --- ┆     ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ --- ┆ str ┆ str ┆ sta ┆ ion ┆ str ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆     ┆ str ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ oco ┆ 1   ┆ toc ┆ sin ┆ --- ┆ e   ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ str ┆     ┆     ┆ nda ┆ --- ┆     ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ l_c ┆ --- ┆ ol_ ┆ g   ┆ str ┆ --- ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ rd  ┆ str ┆     ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ h1  ┆ str ┆ ch1 ┆ --- ┆     ┆ str ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆ --- ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ hek ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ HEK ┆ GSM ┆ Pub ┆ Mar ┆ Feb ┆ SRA ┆ 1   ┆ Flp ┆ Hom ┆ 960 ┆ Flp ┆ tot ┆ 10X ┆ ChI ┆ GPL ┆ Bar ┆ Stü ┆ Fre ┆ 791 ┆ Ger ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ non ┆ Hea ┆ Pro ┆ hg3 ┆ SAM ┆ Cus ┆ htt ┆ Ill ┆ 43  ┆ 90  ┆ 37  ┆ SRR ┆ Nex ┆ Nas ┆ SRA ┆ oth ┆ 201 ┆ 376 ┆ 475 ┆ ILL ┆ ARC ┆ fas ┆ ftp ┆ Gen ┆ HEK ┆ ftp ┆ ef2 ┆ SRP ┆ 145 ┆ Nas ┆ GEN ┆ HEK ┆ Nex ┆ Nex ┆ 169 ┆ ftp ┆ 108 ┆ OTH ┆ TRA ┆ ftp ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ 10X ┆ GSM ┆ GEO ┆ env ┆ 201 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 201 ┆ GSE │
│ 690 ┆ 690 ┆ _hs ┆ er  ┆ o   ┆ GLE ┆     ┆ 690 ┆ 385 ┆ _HS ┆ 306 ┆ lic ┆ 27  ┆ 07  ┆     ┆     ┆ -In ┆ o   ┆ 6   ┆ -In ┆ al  ┆ 106 ┆ P-s ┆ 185 ┆ bar ┆ bew ┆ ibu ┆ 08  ┆ man ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 306 ┆ :// ┆ :// ┆ 112 ┆     ┆ 385 ┆ e   ┆ t-S ┆ -Se ┆ 8   ┆ N08 ┆ tom ┆ ps: ┆ umi ┆ C   ┆ min ┆ C   ┆ 690 ┆ tSe ┆ cen ┆ 675 ┆ er  ┆ 9-0 ┆ 838 ┆ 791 ┆ UMI ┆ HIV ┆ p.s ┆ .sr ┆ eri ┆ _HS ┆ .sr ┆ 36a ┆ 136 ┆ 163 ┆ cen ┆ ERA ┆ _HS ┆ tSe ┆ tSe ┆ e64 ┆ .sr ┆ 872 ┆ ER  ┆ NSC ┆ .sr ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 306 ┆ 306 ┆ 106 ┆ 306 ┆     ┆ _ta ┆ 9-0 ┆ o   ┆ 6   ┆ NA4 ┆ 309 ┆ 9-0 ┆ 112 │
│ 412 ┆ 412 ┆ _pr ┆     ┆ sap ┆     ┆     ┆ 412 ┆ 286 ┆ _Pr ┆ 895 ┆ on  ┆ 201 ┆ 201 ┆     ┆     ┆ T-R ┆ sap ┆     ┆ T-R ┆ RNA ┆ HEK ┆ eq  ┆ 73  ┆ a,, ┆ eg  ┆ rg  ┆     ┆ y   ┆ na  ┆     ┆ rip ┆     ┆ 895 ┆ ftp ┆ ftp ┆ 379 ┆     ┆ 286 ┆     ┆ hoc ┆ q   ┆     ┆ 801 ┆ PRO ┆ //d ┆ na  ┆     ┆ .   ┆ (in ┆ 412 ┆ q   ┆ t-p ┆ 427 ┆     ┆ 2-1 ┆ 035 ┆ 093 ┆ NA  ┆ AL_ ┆ ra. ┆ a.e ┆ c   ┆ _Pr ┆ a.e ┆ 9de ┆ 551 ┆ 37  ┆ t-p ┆ TED ┆ _Pr ┆ q   ┆ q   ┆ 194 ┆ a.e ┆ 527 ┆     ┆ RIP ┆ a.e ┆     ┆     ┆ ra. ┆ 67; ┆ 895 ┆ 895 ┆ HEK ┆ 895 ┆     ┆ x;e ┆ 2-1 ┆ sap ┆     ┆ 458 ┆ 700 ┆ 2-1 ┆ 379 │
│ 9   ┆ 5   ┆ ose ┆     ┆ ien ┆     ┆     ┆ 9   ┆ 1   ┆ ose ┆ 4   ┆ Feb ┆ 8   ┆ 9   ┆     ┆     ┆ Ex  ┆ ien ┆     ┆ Ex  ┆     ┆ 293 ┆ rea ┆     ┆ Hum ┆ 51  ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 4   ┆ .nc ┆ .nc ┆     ┆     ┆ 1   ┆     ┆ k   ┆     ┆     ┆ 007 ┆ -se ┆ oi. ┆ Tru ┆     ┆     ┆ fer ┆ 9   ┆ 500 ┆ rot ┆     ┆     ┆ 4   ┆ vs  ┆ vs  ┆     ┆ FIL ┆ ebi ┆ bi. ┆     ┆ ose ┆ bi. ┆ 041 ┆     ┆ vs  ┆ rot ┆ _FI ┆ ose ┆ 500 ┆ 500 ┆ 576 ┆ bi. ┆ 5   ┆     ┆ TOM ┆ bi. ┆     ┆     ┆ ebi ┆ 275 ┆ 4   ┆ 4_r ┆ 293 ┆ 4   ┆     ┆ nv_ ┆ 4   ┆ ien ┆     ┆ 60  ┆ 4   ┆ 4   ┆     │
│     ┆     ┆ q_r ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ q_R ┆ vs  ┆ 07  ┆     ┆     ┆     ┆     ┆ 293 ┆ s   ┆     ┆ 293 ┆     ┆ cel ┆ ds  ┆     ┆ mel ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆     ┆     ┆ vs  ┆     ┆ vs  ┆     ┆     ┆ vs  ┆ q   ┆ org ┆ Seq ┆     ┆     ┆ red ┆ vs  ┆ seq ┆ ein ┆     ┆     ┆     ┆ 373 ┆ 474 ┆     ┆ E   ┆ .ac ┆ ac. ┆     ┆ q_R ┆ ac. ┆ 69b ┆     ┆ 142 ┆ ein ┆ LE  ┆ q_R ┆     ┆ seq ┆ c20 ┆ ac. ┆ vs  ┆     ┆ IC  ┆ ac. ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ cel ┆ vs  ┆     ┆ tax ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ ep1 ┆ GSM ┆ 201 ┆     ┆     ┆     ┆     ┆ Cel ┆     ┆     ┆ wer ┆     ┆ ls  ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆     ┆     ┆ SRX ┆     ┆ Non ┆     ┆     ┆ SAM ┆ lib ┆ /10 ┆ Sma ┆     ┆     ┆ )   ┆ SRR ┆ uen ┆ ubi ┆     ┆     ┆     ┆ 380 ┆ 553 ┆     ┆     ┆ .uk ┆ uk/ ┆     ┆ ep1 ┆ uk/ ┆ 219 ┆     ┆ 276 ┆ ubi ┆     ┆ ep1 ┆     ┆ uen ┆ 884 ┆ uk/ ┆ 106 ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ ls  ┆ GSM ┆     ┆ :te ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆ 690 ┆ 385 ┆ vs  ┆ 306 ┆ 9   ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ e   ┆     ┆ wer ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 306 ┆ .ni ┆ .ni ┆     ┆     ┆ 385 ┆     ┆ Hea ┆     ┆     ┆ N08 ┆ rar ┆ .10 ┆ ll  ┆     ┆     ┆     ┆ 690 ┆ cin ┆ qui ┆     ┆     ┆     ┆ 870 ┆ 195 ┆     ┆     ┆ :/v ┆ vol ┆     ┆ vs  ┆ vol ┆ 99d ┆     ┆ 27  ┆ qui ┆     ┆ vs  ┆     ┆ cin ┆ 09b ┆ vol ┆ 707 ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 4;3 ┆ 306 ┆ GSM ┆ wer ┆ 306 ┆     ┆ rre ┆     ┆     ┆     ┆     ┆ 309 ┆     ┆     │
│     ┆     ┆ hek ┆     ┆     ┆     ┆     ┆ 412 ┆ 285 ┆ HEK ┆ 895 ┆     ┆     ┆     ┆     ┆     ┆ Lin ┆     ┆     ┆ cul ┆     ┆ e   ┆ ali ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 895 ┆ h.g ┆ h.g ┆     ┆     ┆ 285 ┆     ┆ t-S ┆     ┆     ┆ 801 ┆ y   ┆ 38/ ┆ RNA ┆     ┆     ┆     ┆ 412 ┆ g:  ┆ tin ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol1 ┆ 1/f ┆     ┆ HEK ┆ 1/s ┆ dff ┆     ┆     ┆ tin ┆     ┆ HEK ┆     ┆ g:  ┆ 36f ┆ 1/f ┆ 202 ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 320 ┆ 895 ┆ 306 ┆ e   ┆ 895 ┆     ┆ str ┆     ┆     ┆     ┆     ┆ 700 ┆     ┆     │
│     ┆     ┆ _nh ┆     ┆     ┆     ┆     ┆ 5   ┆ 7   ┆ _NH ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ tur ┆     ┆ use ┆ gne ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 7   ┆     ┆ hoc ┆     ┆     ┆ 012 ┆ pre ┆ s41 ┆ ada ┆     ┆     ┆     ┆ 5   ┆ GSM ┆ ati ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sr ┆ ast ┆     ┆ _NH ┆ rr/ ┆ b8c ┆     ┆     ┆ ati ┆     ┆ _NH ┆     ┆ GSM ┆ f68 ┆ ast ┆ 5   ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 8;6 ┆ 0   ┆ 895 ┆ use ┆ 0   ┆     ┆ ial ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     │
│     ┆     ┆ s_p ┆     ┆     ┆     ┆     ┆     ┆     ┆ S_P ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆ d   ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆ k   ┆     ┆     ┆     ┆ par ┆ 594 ┆ pte ┆     ┆     ┆     ┆     ┆ 306 ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r/S ┆ q/S ┆     ┆ S_P ┆ SRR ┆ 4da ┆     ┆     ┆ on  ┆     ┆ S_P ┆     ┆ 306 ┆ 7b5 ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 0_r ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ros ┆     ┆     ┆     ┆     ┆     ┆     ┆ ros ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ for ┆ to  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ -01 ┆ rs  ┆     ┆     ┆     ┆     ┆ 895 ┆ is  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RR6 ┆ RR6 ┆     ┆ ros ┆ 690 ┆ 9d  ┆     ┆     ┆ is  ┆     ┆ ros ┆     ┆ 895 ┆ 3d  ┆ RR6 ┆     ┆     ┆     ┆ 690 ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ eq_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ DME ┆     ┆ eac ┆ the ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ 8-0 ┆     ┆     ┆     ┆     ┆     ┆ 4:  ┆ req ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 90/ ┆ 90/ ┆     ┆ eq_ ┆ /00 ┆ vs  ┆     ┆     ┆ req ┆     ┆ eq_ ┆     ┆ 4:  ┆ vs  ┆ 90/ ┆     ┆     ┆     ┆ /00 ┆     ┆     ┆ R69 ┆ 213 ┆     ┆     ┆ eac ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ rep ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rep ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ M   ┆     ┆ h   ┆ hum ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bas ┆ 182 ┆     ┆     ┆     ┆     ┆     ┆ HEK ┆ uir ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 009 ┆ 009 ┆     ┆ Rep ┆ 9/S ┆ 095 ┆     ┆     ┆ uir ┆     ┆ Rep ┆     ┆ HEK ┆ 5b3 ┆ 009 ┆     ┆     ┆     ┆ 9/S ┆     ┆     ┆ 0/0 ┆ ;33 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hig ┆     ┆ PRO ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  ┆ -x  ┆     ┆     ┆     ┆     ┆     ┆ _HS ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ /SR ┆     ┆ 1   ┆ RR6 ┆ 4df ┆     ┆     ┆ ed  ┆     ┆ 1   ┆     ┆ _HS ┆ 055 ┆ /SR ┆     ┆     ┆     ┆ RR6 ┆     ┆     ┆ 09/ ┆ 511 ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆ seq ┆ gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 306 ┆ 306 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆     ┆     ┆     ┆ _Pr ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R69 ┆ R69 ┆     ┆     ┆ 904 ┆ 7c8 ┆     ┆     ┆ for ┆     ┆     ┆     ┆ _Pr ┆ 42f ┆ R69 ┆     ┆     ┆     ┆ 904 ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Glu ┆     ┆ exp ┆ ome ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8nn ┆ 8nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mah ┆     ┆     ┆     ┆     ┆     ┆     ┆ ose ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 041 ┆ 041 ┆     ┆     ┆ 129 ┆ fd8 ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ ose ┆ 182 ┆ 041 ┆     ┆     ┆     ┆ 129 ┆     ┆     ┆ 690 ┆ 11; ┆     ┆     ┆ exp ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cos ┆     ┆ eri ┆ bui ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆ q_R ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 29  ┆ 29/ ┆     ┆     ┆ vs  ┆ a77 ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ q_R ┆ 008 ┆ 29/ ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ 412 ┆ 895 ┆     ┆     ┆ eri ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆ men ┆ ld  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM3 ┆ SM3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ et  ┆     ┆     ┆     ┆     ┆     ┆     ┆ ep1 ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ SRR ┆     ┆     ┆ ftp ┆ 14d ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ ep1 ┆ 16d ┆ SRR ┆     ┆     ┆     ┆ ftp ┆     ┆     ┆ 9/S ┆ 93; ┆     ┆     ┆ men ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sup ┆     ┆ t.  ┆ hg3 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 068 ┆ 068 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al. ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fas ┆ 690 ┆     ┆     ┆ .sr ┆ 6c1 ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ Hom ┆ 576 ┆ 690 ┆     ┆     ┆     ┆ .sr ┆     ┆     ┆ RR6 ┆ 774 ┆     ┆     ┆ t.  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ Cel ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 954 ┆ 954 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ (20 ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ ind ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ p.s ┆ 412 ┆     ┆     ┆ a.e ┆ 7cf ┆     ┆     ┆ ind ┆     ┆     ┆     ┆ o   ┆ 609 ┆ 412 ┆     ┆     ┆     ┆ a.e ┆     ┆     ┆ 904 ┆ 2;7 ┆     ┆     ┆ Cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 10. GSE144786 PRO-seq (SINGLE)

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validate date: 2026-02-22
- [NELF Regulates a Promoter-Proximal Step Distinct from RNA Pol II Pause-Release](https://doi.org/10.1016/j.molcel.2020.02.014)
- 以下のような記述が論文にあるため、収集
- `Heat Shock Induction: Heat shock of mammalian cells was performed using ∼70%–80% confluent DLD-1 cells by adding pre-heated (42°C) conditioned media collected from identically growing cells (Mahat et al., 2016a). The heat shock cells were incubated at 42°C for 1 hour. After washing with PBS, the heat shock and non-heat shock DLD-1 cells were processed for PRO-seq as described below.`
- 熱ストレスに関連しているデータのみを選抜
- 熱ストレスと`Auxin`を処理しているデータ、`PRO-seq-20-NELFC-AID-42C-Aux-rep1`などが含まれており、悩んだ結果、Auxin処理されていないが、`-37C-`の記述があるデータとペアにすることに

&nbsp;

### Adapter

- [GSE144786](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144786) のページで、例えば [GSM4296332](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4296332) の Extraction protocol には以下のように書いてある
- `For PRO-seq, adapter sequences previously described (Mahat et al., 2016) were used.`
- つまり、 Illumina TruSeq small-RNA adaptors に該当する

In [31]:
GSE144786_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE144786/GSE144786_PEP/GSE144786_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("organism") == "Homo sapiens") &
    (pl.col("protocol") != "ChIP") &
    (pl.col("sample_title").str.contains(r"-(37|42)C-")) # heat-shock related data
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    (pl.lit("unknown").alias("rna_library")),
    (pl.lit("https://doi.org/10.1016/j.molcel.2020.02.014").alias("reference_doi")),
    (pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")),
    (pl.lit("42 C").alias("stress treatment temperature")),
    (pl.lit("60 min.").alias("stress treatment time")),
    (pl.lit("37 C").alias("control treatment temperature"))
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE144786 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE144786.metadata.tsv",
    separator='\t'
)

GSE144786_iseq_filtered = GSE144786[[s.name for s in GSE144786 if not (s.null_count() == GSE144786.height)]]

# display(GSE144786_PEP)

In [32]:
GSE144786_combined = GSE144786_PEP.join(
    GSE144786_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
)

GSE144786_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE144786_proseq_modified_metadata.tsv",
    separator='\t'
)

# display(GSE144786_combined)

In [33]:
# Manual defined pairs
defined_pairs_gse144786 = [
    ("SRR11024624", "SRR11024623"), # PRO-seq-19-NELFC-AID-42C-rep1 vs PRO-seq-18-NELFC-AID-37C-rep1
    ("SRR11024625", "SRR11024623"), # PRO-seq-20-NELFC-AID-42C-Aux-rep1 vs PRO-seq-18-NELFC-AID-37C-rep1 (Auxin処理されていないデータとペアにする)
    ("SRR11024627", "SRR11024626"), # PRO-seq-19-NELFC-AID-42C-rep2 vs PRO-seq-18-NELFC-AID-37C-rep2
    ("SRR11024628", "SRR11024626")  # PRO-seq-20-NELFC-AID-42C-Aux-rep2 vs PRO-seq-18-NELFC-AID-37C-rep2 (Auxin処理されていないデータとペアにする)
]

paired_metadata_df_gse144786_proseq = create_paired_metadata(
    combined_df=GSE144786_combined,
    defined_sample_pairs=defined_pairs_gse144786,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse144786_proseq is not None:
    paired_metadata_df_gse144786_proseq.write_csv(
        "../../Data/metadata/metadata_proseq/GSE144786_proseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse144786_proseq)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (4, 94)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ gen ┆ ant ┆ cel ┆ gen ┆ sam ┆ rna ┆ ref ┆ ada ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ fas ┆ ins ┆ fas ┆ ncb ┆ sam ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ exp ┆ cen ┆ cel ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_t ┆ oty ┆ ibo ┆ l_l ┆ ome ┆ ple ┆ _li ┆ ere ┆ pte ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ tq_ ┆ tru ┆ tq_ ┆ i_r ┆ ple ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ eri ┆ ter ┆ l_l ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ ype ┆ pe  ┆ dy  ┆ ine ┆ _bu ┆ _ac ┆ bra ┆ nce ┆ r   ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ byt ┆ men ┆ gal ┆ epo ┆ _de ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ men ┆ _na ┆ ine ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ ild ┆ ces ┆ ry  ┆ _do ┆ --- ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ es  ┆ t_p ┆ axy ┆ rti ┆ scr ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ t_a ┆ me  ┆ _ri ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ sio ┆ --- ┆ i   ┆ str ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ --- ┆ lat ┆ --- ┆ ng_ ┆ ipt ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ lia ┆ --- ┆ ght ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ add ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ str ┆ n   ┆ str ┆ --- ┆     ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆ str ┆ for ┆ str ┆ sta ┆ ion ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆ --- ┆     ┆ str ┆ y   ┆ --- ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ s   ┆ str ┆ --- ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ res ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆     ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆ m   ┆     ┆ nda ┆ _ri ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆ str ┆     ┆     ┆ --- ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ --- ┆     ┆ str ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ s   ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆ --- ┆     ┆ rd  ┆ ght ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ pro ┆ oth ┆ Hom ┆ SIN ┆ SRA ┆ SRR ┆ SRX ┆ PRO ┆ GSM ┆ Pub ┆ Feb ┆ Mar ┆ SRA ┆ 1   ┆ DLD ┆ Hom ┆ 960 ┆ nuc ┆ PRO ┆ GPL ┆ Ali ┆ ash ┆ Shi ┆ Dep ┆ 320 ┆ Chi ┆ IL  ┆ 606 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ Col ┆ NEL ┆ nul ┆ DLD ┆ hg1 ┆ SAM ┆ unk ┆ htt ┆ Ill ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Nex ┆ NEL ┆ SRA ┆ oth ┆ 202 ┆ 296 ┆ ILL ┆ ftp ┆ Gen ┆ PRO ┆ 5df ┆ SRP ┆ 711 ┆ NEL ┆ GEN ┆ PRO ┆ Nex ┆ Nex ┆ Col ┆ ftp ┆ 537 ┆ OTH ┆ TRA ┆ SIN ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ For ┆ GSM ┆ GEO ┆ DLD ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 110 ┆ 110 ┆ -se ┆ er  ┆ o   ┆ GLE ┆     ┆ 110 ┆ 767 ┆ -se ┆ 429 ┆ lic ┆ 05  ┆ 09  ┆     ┆     ┆ -1  ┆ o   ┆ 6   ┆ lea ┆ -se ┆ 185 ┆ ,,S ┆ @no ┆ lat ┆ art ┆ E   ┆ cag ┆     ┆ 11  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 429 ┆ :// ┆ 144 ┆     ┆ 767 ┆ ore ┆ F-C ┆ l   ┆ -1  ┆ 9,  ┆ N14 ┆ now ┆ ps: ┆ umi ┆ C   ┆ min ┆ C   ┆ 110 ┆ tSe ┆ F   ┆ 103 ┆ er  ┆ 0-0 ┆ 204 ┆ UMI ┆ .sr ┆ eri ┆ -se ┆ 717 ┆ 247 ┆ 538 ┆ F   ┆ ERA ┆ -se ┆ tSe ┆ tSe ┆ ore ┆ .sr ┆ 874 ┆ ER  ┆ NSC ┆ GLE ┆ lic ┆ p.s ┆ 315 ┆ 429 ┆ 429 ┆ ChI ┆ 429 ┆     ┆ -1  ┆ _ta ┆ 0-0 ┆ o   ┆ 6   ┆ NA6 ┆ 610 ┆ 0-0 ┆ 144 │
│ 246 ┆ 246 ┆ q-1 ┆     ┆ sap ┆     ┆     ┆ 246 ┆ 777 ┆ q-1 ┆ 633 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ r   ┆ q   ┆ 73  ┆ hil ┆ rth ┆ ifa ┆ men ┆ Sup ┆ o   ┆     ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 633 ┆ ftp ┆ 786 ┆     ┆ 777 ┆ cta ┆ -AI ┆     ┆     ┆ dm3 ┆ 001 ┆ n   ┆ //d ┆ na  ┆     ┆ .   ┆     ┆ 246 ┆ q   ┆ reg ┆ 783 ┆     ┆ 3-2 ┆ 706 ┆ NA  ┆ a.e ┆ c   ┆ q-1 ┆ 607 ┆ 346 ┆ 48  ┆ reg ┆ TED ┆ q-1 ┆ q   ┆ q   ┆ cta ┆ a.e ┆ 872 ┆     ┆ RIP ┆     ┆     ┆ ra. ┆ 67; ┆ 633 ┆ 633 ┆ P-s ┆ 633 ┆     ┆     ┆ x:t ┆ 3-2 ┆ sap ┆     ┆ 049 ┆ 513 ┆ 3-2 ┆ 786 │
│ 24  ┆ 23  ┆ 9-n ┆     ┆ ien ┆     ┆     ┆ 24  ┆ 1   ┆ 9-N ┆ 2   ┆ Mar ┆ 0   ┆ 0   ┆     ┆     ┆     ┆ ien ┆     ┆ RNA ┆     ┆     ┆ ati ┆ wes ┆ rd  ┆ t   ┆ eri ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 2   ┆ .nc ┆     ┆     ┆ 1   ┆ l   ┆ D   ┆     ┆     ┆ ,   ┆ 984 ┆     ┆ oi. ┆ Tru ┆     ┆     ┆     ┆ 24  ┆ 500 ┆ ula ┆ 8   ┆     ┆ 3   ┆ 3   ┆     ┆ bi. ┆     ┆ 9-N ┆ 482 ┆     ┆ vs  ┆ ula ┆ _FI ┆ 9-N ┆ 500 ┆ 500 ┆ l   ┆ bi. ┆ 0   ┆     ┆ TOM ┆     ┆     ┆ ebi ┆ 275 ┆ 2   ┆ 2_r ┆ eq, ┆ 2   ┆     ┆     ┆ err ┆ 3   ┆ ien ┆     ┆ 12  ┆ 0   ┆ 3   ┆     │
│     ┆     ┆ elf ┆     ┆ s   ┆     ┆     ┆ vs  ┆ vs  ┆ ELF ┆ vs  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ far ┆ ter ┆ Lab ┆ of  ┆ or  ┆     ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆     ┆     ┆ vs  ┆ ade ┆ OsT ┆     ┆     ┆ mm9 ┆ vs  ┆     ┆ org ┆ Seq ┆     ┆     ┆     ┆ vs  ┆ seq ┆ tes ┆     ┆     ┆     ┆ vs  ┆     ┆ ac. ┆     ┆ ELF ┆ 374 ┆     ┆ 147 ┆ tes ┆ LE  ┆ ELF ┆     ┆ seq ┆ ade ┆ ac. ┆ vs  ┆     ┆ IC  ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ 20- ┆ vs  ┆     ┆     ┆ est ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ c-a ┆     ┆     ┆     ┆     ┆ SRR ┆ SRX ┆ C-A ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆ n.e ┆     ┆ Bio ┆ St  ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆     ┆     ┆ SRX ┆ noc ┆ IR1 ┆     ┆     ┆     ┆ SAM ┆     ┆ /10 ┆ Sma ┆     ┆     ┆     ┆ SRR ┆ uen ┆ a   ┆     ┆     ┆     ┆ 621 ┆     ┆ uk/ ┆     ┆ C-A ┆ 3c9 ┆     ┆ 384 ┆ a   ┆     ┆ C-A ┆     ┆ uen ┆ noc ┆ uk/ ┆ 111 ┆     ┆     ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ 50  ┆ GSM ┆     ┆     ┆ ria ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ id- ┆     ┆     ┆     ┆     ┆ 110 ┆ 767 ┆ ID- ┆ 429 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ du  ┆     ┆ che ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 429 ┆ .ni ┆     ┆     ┆ 767 ┆ arc ┆     ┆     ┆     ┆     ┆ N14 ┆     ┆ .10 ┆ ll  ┆     ┆     ┆     ┆ 110 ┆ cin ┆ pro ┆     ┆     ┆     ┆ 162 ┆     ┆ vol ┆     ┆ ID- ┆ 42d ┆     ┆ 362 ┆ pro ┆     ┆ ID- ┆     ┆ cin ┆ arc ┆ vol ┆ 426 ┆     ┆     ┆     ┆     ┆ :/v ┆ 4;3 ┆ 429 ┆ GSM ┆ mil ┆ 429 ┆     ┆     ┆ l;e ┆     ┆     ┆     ┆     ┆ 610 ┆     ┆     │
│     ┆     ┆ 42c ┆     ┆     ┆     ┆     ┆ 246 ┆ 777 ┆ 42C ┆ 633 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 633 ┆ h.g ┆     ┆     ┆ 777 ┆ ino ┆     ┆     ┆     ┆     ┆ 001 ┆     ┆ 16/ ┆ RNA ┆     ┆     ┆     ┆ 246 ┆ g:  ┆ mot ┆     ┆     ┆     ┆ 721 ┆     ┆ 1/f ┆     ┆ 42C ┆ 10c ┆     ┆     ┆ mot ┆     ┆ 42C ┆     ┆ g:  ┆ ino ┆ 1/f ┆ 138 ┆     ┆     ┆     ┆     ┆ ol1 ┆ 320 ┆ 633 ┆ 429 ┆ lio ┆ 633 ┆     ┆     ┆ nv_ ┆     ┆     ┆     ┆     ┆ 512 ┆     ┆     │
│     ┆     ┆ -re ┆     ┆     ┆     ┆     ┆ 23  ┆ 0   ┆ -re ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ try ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆     ┆     ┆ 0   ┆ ma  ┆     ┆     ┆     ┆     ┆ 972 ┆     ┆ j.m ┆ ada ┆     ┆     ┆     ┆ 23  ┆ GSM ┆ er- ┆     ┆     ┆     ┆ 1   ┆     ┆ ast ┆     ┆ -re ┆ a67 ┆     ┆     ┆ er- ┆     ┆ -re ┆     ┆ GSM ┆ ma  ┆ ast ┆ 86  ┆     ┆     ┆     ┆     ┆ /fa ┆ 8;6 ┆ 1   ┆ 633 ┆ n   ┆ 1   ┆     ┆     ┆ tax ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ olc ┆ pte ┆     ┆     ┆     ┆     ┆ 429 ┆ pro ┆     ┆     ┆     ┆     ┆     ┆ q/S ┆     ┆ p1  ┆ e3a ┆     ┆     ┆ pro ┆     ┆ p1  ┆     ┆ 429 ┆     ┆ q/S ┆     ┆     ┆     ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 1_r ┆ cel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mol ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ el. ┆ rs  ┆     ┆     ┆     ┆     ┆ 633 ┆ xim ┆     ┆     ┆     ┆     ┆     ┆ RR1 ┆     ┆ vs  ┆ 23  ┆     ┆     ┆ xim ┆     ┆ vs  ┆     ┆ 633 ┆     ┆ RR1 ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ ls  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ pro ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ecu ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆ 2:  ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ 10/ ┆     ┆ PRO ┆ vs  ┆     ┆     ┆ al  ┆     ┆ PRO ┆     ┆ 2:  ┆     ┆ 10/ ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆ 213 ┆     ┆     ┆ wer ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0.0 ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆ ste ┆     ┆     ┆     ┆     ┆     ┆ 024 ┆     ┆ -se ┆ b63 ┆     ┆     ┆ ste ┆     ┆ -se ┆     ┆ PRO ┆     ┆ 024 ┆     ┆     ┆     ┆     ┆     ┆ 0/0 ┆ ;33 ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ q-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆ q-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gen ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2.0 ┆     ┆     ┆     ┆     ┆     ┆ -se ┆ p   ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆ q-1 ┆ c0d ┆     ┆     ┆ p   ┆     ┆ q-1 ┆     ┆ -se ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 24/ ┆ 511 ┆     ┆     ┆ cro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 8-n ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8-N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆ q-1 ┆ dis ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆ 8-N ┆ f75 ┆     ┆     ┆ dis ┆     ┆ 8-N ┆     ┆ q-1 ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ ssl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ elf ┆     ┆     ┆     ┆     ┆     ┆     ┆ ELF ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9-N ┆ tin ┆     ┆     ┆     ┆     ┆     ┆ 024 ┆     ┆ ELF ┆ bf4 ┆     ┆     ┆ tin ┆     ┆ ELF ┆     ┆ 9-N ┆     ┆ 024 ┆     ┆     ┆     ┆     ┆     ┆ 110 ┆ 11; ┆     ┆     ┆ ink ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ c-a ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ELF ┆ ct  ┆     ┆     ┆     ┆     ┆     ┆ 624 ┆     ┆ C-A ┆ 470 ┆     ┆     ┆ ct  ┆     ┆ C-A ┆     ┆ ELF ┆     ┆ 624 ┆     ┆     ┆     ┆     ┆     ┆ 246 ┆ 895 ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ id- ┆     ┆     ┆     ┆     ┆     ┆     ┆ ID- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ C-A ┆ fro ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆     ┆ ID- ┆ fdf ┆     ┆     ┆ fro ┆     ┆ ID- ┆     ┆ C-A ┆     ┆ /SR ┆     ┆     ┆     ┆     ┆     ┆ 24/ ┆ 93; ┆     ┆     ┆ wit ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ 37c ┆     ┆     ┆     ┆     ┆     ┆     ┆ 37C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 296 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ID- ┆ m   ┆     ┆     ┆     ┆     ┆     ┆ R11 ┆     ┆ 37C ┆ 00a ┆     ┆     ┆ m   ┆     ┆ 37C ┆     ┆ ID- ┆     ┆ R11 ┆     ┆     ┆     ┆     ┆     ┆ SRR ┆ 774 ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ -re ┆     ┆     ┆     ┆     ┆     ┆     ┆ -re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 332 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42C ┆ RNA ┆     ┆     ┆     ┆     ┆     ┆ 024 ┆     ┆ -re ┆ 222 ┆     ┆     ┆ RNA ┆     ┆ -re ┆     ┆ 42C ┆     ┆ 024 ┆     ┆     ┆     ┆     ┆     ┆ 110 ┆ 2;7 ┆     ┆     ┆ 1%  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆ p1  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /su ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -re ┆ Pol ┆     ┆     ┆     ┆     ┆     ┆ 624 ┆     ┆ p1  ┆ a7c ┆     ┆     ┆ Pol ┆     ┆ p1  ┆     ┆ -re ┆     ┆ 624 ┆     ┆     ┆     ┆     ┆     ┆ 246 ┆ 776 ┆     ┆     ┆ par ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 11. GSE209685 PRO-seq (PAIRED)

- ✅ DOWNLOAD (yone-SSD)
- ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD)
- ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD)

&nbsp;

- validate date: 2026-02-23
- [Transcriptional responses of cancer cells to heat shock-inducing stimuli involve amplification of robust HSF1 binding](https://doi.org/10.1038/s41467-023-43157-7)
- 論文に以下のような記載があった
- `A 60-min incubation at 42 °C induced a control HSP gene seen as spreading of the Pol II and nascent RNA signal into the gene body (Fig. 1a).`
- こちらのデータセットにはヒ素 (As)処理のものも含まれているため、そのデータセットをフィルタリングして収集する

&nbsp;

### Adapter

- [GSE209685](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE209685) のページ、例えば[GSM6383642](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM6383642) の `Extraction protocol` には以下のように書いてある
- `Precision Run-On sequencing (PRO-seq) was performed as previously described {Mahat et al., 2016}. Briefly, nuclei were extracted from ~2x107 cells and run on reactions were carried on at 37°C for 3 minutes using 3ml of each 11-biotin-labelled ribonucleotide stocks (Perkin Elmer). Libraries were prepared as described in Mahat et al., 2016 using custom Illumina small RNA compatible linkers, alkaline degradation, enzymatic treatments and streptavidin selection of nascent RNA on magnetic beads according to the cited protocol.`
- つまり、Illumina Truseq small RNA adapters で大丈夫だと思われる

In [34]:
GSE209685_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE209685/GSE209685_PEP/GSE209685_PEP_raw.csv",
    separator=','
).filter(
    (~pl.col("sample_title").str.contains(r"As")) # ヒ素 (As)処理のデータをフィルタリング
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    (pl.lit("unknown").alias("rna_library")),
    (pl.lit("https://doi.org/10.1038/s41467-023-43157-7").alias("reference_doi")),
    (pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")),
    (pl.lit("42 C").alias("stress treatment temperature")),
    (pl.lit("60 min.").alias("stress treatment time")),
    (pl.lit("37 C (inferred)").alias("control treatment temperature"))
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample"
)

# metadata from iseq
GSE209685 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE209685.metadata.tsv",
    separator='\t'
)

GSE209685_iseq_filtered = GSE209685[[s.name for s in GSE209685 if not (s.null_count() == GSE209685.height)]]

# display(GSE209685_PEP)

In [35]:
GSE209685_combined = GSE209685_PEP.join(
    GSE209685_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).sort(
    [
        "gsm_id"
    ],
    descending=[
        False
    ]
)

GSE209685_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE209685_proseq_modified_metadata.tsv",
    separator='\t'
)

# pl.Config.set_tbl_rows(32)
# display(GSE209685_combined)

In [36]:
# Manual defined pairs
defined_pairs_gse209685 = [
    ("SRR20631364", "SRR20631365"), # K562_pro-seq_hs vs k562_pro-seq_nhs
    ("SRR20631361", "SRR20631362"), # mcf7_pro-seq_hs_rep1 vs mcf7_pro-seq_nhs_rep1
    ("SRR20631358", "SRR20631359")  # mcf7_pro-seq_hs_rep2 vs mcf7_pro-seq_nhs_rep2
]

paired_metadata_df_gse209685 = create_paired_metadata(
    combined_df=GSE209685_combined,
    defined_sample_pairs=defined_pairs_gse209685,
    sample_id_column_name="accession"
)

if paired_metadata_df_gse209685 is not None:
    paired_metadata_df_gse209685.write_csv(
        "../../Data/metadata/metadata_proseq/GSE209685_proseq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse209685)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (3, 103)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ org ┆ rea ┆ dat ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ sam ┆ gse ┆ sam ┆ exp ┆ cel ┆ cel ┆ tre ┆ ass ┆ lib ┆ sam ┆ rna ┆ ref ┆ ada ┆ str ┆ str ┆ con ┆ run ┆ exp ┆ pro ┆ sub ┆ lib ┆ las ┆ sra ┆ fas ┆ ins ┆ sra ┆ sra ┆ fas ┆ cou ┆ ncb ┆ sam ┆ sra ┆ fas ┆ sec ┆ rea ┆ stu ┆ fas ┆ sam ┆ ins ┆ des ┆ sra ┆ cel ┆ fas ┆ bas ┆ lib ┆ lib ┆ sra ┆ lib ┆ sta ┆ fas ┆ tax ┆ sam ┆ run ┆ lib ┆ col ┆ exp ┆ cel ┆ lib ┆ tag ┆ fir ┆ sci ┆ tax ┆ stu ┆ sec ┆ fir ┆ stu │
│ ple ┆ ple ┆ ple ┆ toc ┆ ani ┆ d_t ┆ a_s ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ ple ┆ _id ┆ ple ┆ eri ┆ l_l ┆ l_t ┆ atm ┆ emb ┆ rar ┆ ple ┆ _li ┆ ere ┆ pte ┆ ess ┆ ess ┆ tro ┆ _ac ┆ eri ┆ jec ┆ mis ┆ rar ┆ t_u ┆ _by ┆ tq_ ┆ tru ┆ _fi ┆ _as ┆ tq_ ┆ ntr ┆ i_r ┆ ple ┆ _ga ┆ tq_ ┆ ond ┆ d_c ┆ dy_ ┆ tq_ ┆ ple ┆ tru ┆ cri ┆ _md ┆ l_t ┆ tq_ ┆ e_c ┆ rar ┆ rar ┆ _ft ┆ rar ┆ tus ┆ tq_ ┆ _li ┆ ple ┆ _al ┆ rar ┆ lec ┆ eri ┆ l_l ┆ rar ┆ --- ┆ st_ ┆ ent ┆ _id ┆ dy_ ┆ ond ┆ st_ ┆ dy_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ sm  ┆ ype ┆ our ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ _su ┆ --- ┆ _da ┆ men ┆ ine ┆ ype ┆ ent ┆ ly  ┆ y_s ┆ _ac ┆ bra ┆ nce ┆ r   ┆ tre ┆ tre ┆ l   ┆ ces ┆ men ┆ t_n ┆ sio ┆ y_s ┆ pda ┆ tes ┆ byt ┆ men ┆ le_ ┆ per ┆ gal ┆ y   ┆ epo ┆ _de ┆ lax ┆ md5 ┆ ary ┆ oun ┆ tit ┆ fil ┆ _ti ┆ men ┆ pti ┆ 5   ┆ ype ┆ ftp ┆ oun ┆ y_s ┆ y_s ┆ p   ┆ y_l ┆ --- ┆ asp ┆ nea ┆ _al ┆ ias ┆ y_c ┆ tio ┆ men ┆ ine ┆ y_n ┆ str ┆ cre ┆ ifi ┆ --- ┆ acc ┆ ary ┆ pub ┆ ali │
│ at_ ┆ ntr ┆ me  ┆ --- ┆ --- ┆ --- ┆ ce  ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ --- ┆ --- ┆ --- ┆ tra ┆ ces ┆ ry  ┆ _do ┆ --- ┆ atm ┆ atm ┆ tre ┆ sio ┆ t_t ┆ ame ┆ n_a ┆ ele ┆ ted ┆ --- ┆ es  ┆ t_p ┆ rol ┆ a   ┆ axy ┆ --- ┆ rti ┆ scr ┆ y   ┆ --- ┆ _st ┆ t   ┆ le  ┆ e_r ┆ tle ┆ t_m ┆ on  ┆ --- ┆ _ri ┆ --- ┆ t   ┆ tra ┆ our ┆ --- ┆ ayo ┆ str ┆ era ┆ ge  ┆ ias ┆ --- ┆ ons ┆ n_d ┆ t_a ┆ _ri ┆ ame ┆     ┆ ate ┆ c_n ┆ str ┆ ess ┆ _sa ┆ lic ┆ as  │
│ id  ┆ ol_ ┆ --- ┆ str ┆ str ┆ str ┆ --- ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ str ┆ str ┆ str ┆ teg ┆ sio ┆ --- ┆ i   ┆ str ┆ ent ┆ ent ┆ atm ┆ n   ┆ itl ┆ --- ┆ cce ┆ cti ┆ --- ┆ str ┆ --- ┆ lat ┆ e   ┆ --- ┆ --- ┆ str ┆ ng_ ┆ ipt ┆ --- ┆ str ┆ udy ┆ --- ┆ --- ┆ ole ┆ _ri ┆ ode ┆ --- ┆ str ┆ ght ┆ str ┆ --- ┆ teg ┆ ce  ┆ str ┆ ut  ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ tru ┆ ate ┆ lia ┆ ght ┆ --- ┆     ┆ d   ┆ ame ┆     ┆ ion ┆ mpl ┆ --- ┆ --- │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ ion ┆ _id ┆ nam ┆ ema ┆ lab ┆ dep ┆ ins ┆ cit ┆ sta ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆     ┆     ┆     ┆ y   ┆ n   ┆ str ┆ --- ┆     ┆ tem ┆ tim ┆ ent ┆ --- ┆ e   ┆ str ┆ ssi ┆ on  ┆ str ┆     ┆ str ┆ for ┆ --- ┆ str ┆ str ┆     ┆ sta ┆ ion ┆ str ┆     ┆ _ac ┆ str ┆ str ┆ --- ┆ ght ┆ l   ┆ str ┆     ┆ --- ┆     ┆ str ┆ y_r ┆ --- ┆     ┆ --- ┆     ┆ str ┆ str ┆ str ┆     ┆ cti ┆ --- ┆ s   ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆ --- ┆ e_a ┆ str ┆ str │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ --- ┆ --- ┆ e   ┆ il  ┆ ora ┆ art ┆ tit ┆ y   ┆ te  ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ str ┆     ┆ per ┆ e   ┆ tem ┆ str ┆ --- ┆     ┆ on  ┆ --- ┆     ┆     ┆     ┆ m   ┆ str ┆     ┆     ┆     ┆ nda ┆ _ri ┆     ┆     ┆ ces ┆     ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆ str ┆     ┆     ┆ igh ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ on_ ┆ str ┆ --- ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ cce ┆     ┆     │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ --- ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆ fil ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ atu ┆ --- ┆ per ┆     ┆ str ┆     ┆ --- ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ rd  ┆ ght ┆     ┆     ┆ sio ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pro ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ssi ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ str ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆ e_2 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ toc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆     ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ol  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ k56 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ K56 ┆ GSM ┆ Pub ┆ Jul ┆ Oct ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ tot ┆ nas ┆ GPL ┆ Ser ┆ ser ┆ Nec ┆ Bio ┆ Uni ┆ Gra ┆ Nor ┆ 582 ┆ USA ┆ Ill ┆ oth ┆ tra ┆ OTH ┆ GSM ┆ ftp ┆ ftp ┆ GSE ┆ 0   ┆ SRX ┆ K56 ┆ bon ┆ Hea ┆ hg1 ┆ PRO ┆ SAM ┆ unk ┆ htt ┆ Ill ┆ 42  ┆ 60  ┆ 37  ┆ SRR ┆ Ill ┆ Tra ┆ SRA ┆ oth ┆ 202 ┆ 137 ┆ 392 ┆ ILL ┆ ARC ┆ fas ┆ ftp ┆ mis ┆ Gen ┆ K56 ┆ ftp ┆ 256 ┆ SRP ┆ 183 ┆ Tra ┆ GEN ┆ K56 ┆ Ill ┆ Ill ┆ f46 ┆ bon ┆ ftp ┆ 549 ┆ OTH ┆ TRA ┆ ftp ┆ PAI ┆ pub ┆ fas ┆ 1;1 ┆ GSM ┆ GSM ┆ Pre ┆ mis ┆ GSM ┆ K56 ┆ GSM ┆ env ┆ 202 ┆ Hom ┆ 960 ┆ PRJ ┆ SRS ┆ 202 ┆ GSE │
│ 206 ┆ 206 ┆ 2_p ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 2   ┆ 638 ┆ lic ┆ 25  ┆ 30  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ al  ┆ cen ┆ 246 ┆ gei ┆ gei ┆ hae ┆ med ┆ ver ┆ nd  ┆ th  ┆ 02  ┆     ┆ umi ┆ er  ┆ nsc ┆ ER  ┆ 638 ┆ :// ┆ :// ┆ 209 ┆     ┆ 166 ┆ 2   ┆ e   ┆ t   ┆ 9   ┆ -se ┆ N29 ┆ now ┆ ps: ┆ umi ┆ C   ┆ min ┆ C   ┆ 206 ┆ umi ┆ nsc ┆ 146 ┆ er  ┆ 3-1 ┆ 549 ┆ 305 ┆ UMI ┆ HIV ┆ p.s ┆ .sr ┆ sin ┆ eri ┆ 2   ┆ .sr ┆ 404 ┆ 387 ┆ 115 ┆ nsc ┆ ERA ┆ 2   ┆ umi ┆ umi ┆ 4d5 ┆ e   ┆ .sr ┆ 347 ┆ ER  ┆ NSC ┆ .sr ┆ RED ┆ lic ┆ p.s ┆ 315 ┆ 638 ┆ 638 ┆ cis ┆ sin ┆ 638 ┆ 2   ┆ 638 ┆ _ta ┆ 3-1 ┆ o   ┆ 6   ┆ NA8 ┆ 142 ┆ 3-1 ┆ 209 │
│ 313 ┆ 313 ┆ ro- ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆ 364 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ t   ┆ 76  ┆ ,,N ┆ .ne ┆ v   ┆ ica ┆ sit ┆ For ┆ Dak ┆     ┆     ┆ na  ┆     ┆ rip ┆     ┆ 364 ┆ ftp ┆ ftp ┆ 685 ┆     ┆ 549 ┆     ┆ mar ┆ sho ┆     ┆ q   ┆ 939 ┆ n   ┆ //d ┆ na  ┆     ┆ .   ┆ (in ┆ 313 ┆ na  ┆ rip ┆ 208 ┆     ┆ 1-0 ┆ 886 ┆ 402 ┆ NA  ┆ AL_ ┆ ra. ┆ a.e ┆ g   ┆ c   ┆ PRO ┆ a.e ┆ 2b9 ┆ 990 ┆ 885 ┆ rip ┆ TED ┆ PRO ┆ na  ┆ na  ┆ bdc ┆ mar ┆ a.e ┆ 655 ┆     ┆ RIP ┆ a.e ┆     ┆     ┆ ra. ┆ 67; ┆ 364 ┆ 364 ┆ ion ┆ g   ┆ 364 ┆     ┆ 364 ┆ x;e ┆ 1-0 ┆ sap ┆     ┆ 621 ┆ 882 ┆ 1-0 ┆ 685 │
│ 64  ┆ 65  ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆ 2   ┆ Oct ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ RNA ┆     ┆ ech ┆ cha ┆ Lab ┆ l   ┆ y   ┆ ks  ┆ ota ┆     ┆     ┆ Nov ┆     ┆ tom ┆     ┆ 2   ┆ .nc ┆ .nc ┆ ,   ┆     ┆ 21  ┆     ┆ row ┆ ck  ┆     ┆     ┆ 165 ┆     ┆ oi. ┆ Tru ┆     ┆     ┆ fer ┆ 64  ┆ Nov ┆ tio ┆ 9   ┆     ┆ 2   ┆ 16  ┆ 2;6 ┆     ┆ FIL ┆ ebi ┆ bi. ┆     ┆     ┆ -se ┆ bi. ┆ a41 ┆     ┆ vs  ┆ tio ┆ _FI ┆ -se ┆ Nov ┆ Nov ┆ fe3 ┆ row ┆ bi. ┆ 00  ┆     ┆ TOM ┆ bi. ┆     ┆     ┆ ebi ┆ 275 ┆ 2   ┆ 2_r ┆ Run ┆     ┆ 2_r ┆     ┆ 2   ┆ nv_ ┆ 1   ┆ ien ┆     ┆ 14  ┆ 63  ┆ 1   ┆     │
│     ┆     ┆ _hs ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ vs  ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆ aev ┆ ev@ ┆     ┆ Sci ┆ of  ┆     ┆     ┆     ┆     ┆ aSe ┆     ┆ ic  ┆     ┆ vs  ┆ bi. ┆ bi. ┆ GSE ┆     ┆ vs  ┆     ┆ ,   ┆ vs  ┆     ┆     ┆ vs  ┆     ┆ org ┆ Seq ┆     ┆     ┆ red ┆ vs  ┆ aSe ┆ nal ┆     ┆     ┆     ┆ vs  ┆ 067 ┆     ┆ E   ┆ .ac ┆ ac. ┆     ┆     ┆ q   ┆ ac. ┆ 5e6 ┆     ┆ 124 ┆ nal ┆ LE; ┆ q   ┆ aSe ┆ aSe ┆ 701 ┆ ,   ┆ ac. ┆ vs  ┆     ┆ IC  ┆ ac. ┆     ┆     ┆ .ac ┆ 9;3 ┆ vs  ┆ 1   ┆ -On ┆     ┆ 1   ┆     ┆ vs  ┆ tax ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     │
│     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS  ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ und ┆     ┆ enc ┆ Nor ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆ nlm ┆ nlm ┆ 209 ┆     ┆ SRX ┆     ┆ mye ┆ Unt ┆     ┆     ┆ SAM ┆     ┆ /10 ┆ Sma ┆     ┆     ┆ )   ┆ SRR ┆ q   ┆ res ┆     ┆     ┆     ┆ 932 ┆ 302 ┆     ┆     ┆ .uk ┆ uk/ ┆     ┆     ┆ HS  ┆ uk/ ┆ b2d ┆     ┆ 100 ┆ res ┆ GEN ┆ HS  ┆ q   ┆ q   ┆ dde ┆ mye ┆ uk/ ┆ 372 ┆     ┆     ┆ uk/ ┆     ┆     ┆ .uk ┆ 315 ┆ GSM ┆ vs  ┆ seq ┆     ┆ vs  ┆     ┆ GSM ┆ :te ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     │
│     ┆     ┆ k56 ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ 638 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .ed ┆     ┆ es  ┆ th  ┆     ┆     ┆     ┆     ┆ 600 ┆     ┆     ┆     ┆ 638 ┆ .ni ┆ .ni ┆ 687 ┆     ┆ 166 ┆     ┆ log ┆ rea ┆     ┆     ┆ N29 ┆     ┆ .10 ┆ ll  ┆     ┆     ┆     ┆ 206 ┆ 600 ┆ pon ┆     ┆     ┆     ┆ 106 ┆ 367 ┆     ┆     ┆ :/v ┆ vol ┆     ┆     ┆ vs  ┆ vol ┆ b03 ┆     ┆ 428 ┆ pon ┆ ERA ┆ vs  ┆ 600 ┆ 600 ┆ 715 ┆ log ┆ vol ┆ 301 ┆     ┆     ┆ vol ┆     ┆     ┆ :/v ┆ 4;3 ┆ 638 ┆ GSM ┆ uen ┆     ┆ GSM ┆     ┆ 638 ┆ rre ┆     ┆     ┆     ┆     ┆ 142 ┆     ┆     │
│     ┆     ┆ 2_p ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆ 364 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u   ┆     ┆     ┆ Dak ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆ 364 ┆ h.g ┆ h.g ┆     ┆     ┆ 549 ┆     ┆ eno ┆ ted ┆     ┆     ┆ 939 ┆     ┆ 38/ ┆ RNA ┆     ┆     ┆     ┆ 313 ┆ 0   ┆ ses ┆     ┆     ┆     ┆ 669 ┆ vs  ┆     ┆     ┆ ol1 ┆ 1/f ┆     ┆     ┆ K56 ┆ 1/s ┆ 9c6 ┆     ┆     ┆ ses ┆ TED ┆ K56 ┆ 0   ┆ 0   ┆ 4de ┆ eno ┆ 1/f ┆ 284 ┆     ┆     ┆ 1/s ┆     ┆     ┆ ol1 ┆ 320 ┆ 364 ┆ 638 ┆ cin ┆     ┆ 638 ┆     ┆ 364 ┆ str ┆     ┆     ┆     ┆     ┆ 882 ┆     ┆     │
│     ┆     ┆ ro- ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ota ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ ov/ ┆ ov/ ┆     ┆     ┆ 20  ┆     ┆ us  ┆     ┆     ┆     ┆ 166 ┆     ┆ s41 ┆ ada ┆     ┆     ┆     ┆ 65  ┆ seq ┆ of  ┆     ┆     ┆     ┆ 9   ┆ 278 ┆     ┆     ┆ /sr ┆ ast ┆     ┆     ┆ 2   ┆ rr/ ┆ e49 ┆     ┆     ┆ of  ┆ _FI ┆ 2   ┆     ┆ seq ┆ 1bd ┆ us  ┆ ast ┆ 00  ┆     ┆     ┆ rr/ ┆     ┆     ┆ /fa ┆ 8;6 ┆ 1   ┆ 364 ┆ g   ┆     ┆ 364 ┆     ┆ 1   ┆ ial ┆     ┆     ┆     ┆     ┆ 62  ┆     ┆     │
│     ┆     ┆ seq ┆     ┆     ┆     ┆     ┆     ┆     ┆ PRO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ geo ┆ geo ┆     ┆     ┆     ┆     ┆ leu ┆     ┆     ┆     ┆     ┆     ┆ 467 ┆ pte ┆     ┆     ┆     ┆     ┆ uen ┆ can ┆     ┆     ┆     ┆     ┆ 082 ┆     ┆     ┆ r/S ┆ q/S ┆     ┆     ┆ PRO ┆ SRR ┆ 4a9 ┆     ┆     ┆ can ┆ LE  ┆ PRO ┆     ┆ uen ┆ 7e5 ┆ leu ┆ q/S ┆     ┆     ┆     ┆ SRR ┆     ┆     ┆ stq ┆ 072 ┆     ┆ 1_r ┆ (PR ┆     ┆ 1_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ _nh ┆     ┆     ┆     ┆     ┆     ┆     ┆ -se ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /sa ┆ /sa ┆     ┆     ┆     ┆     ┆ kem ┆     ┆     ┆     ┆     ┆     ┆ -02 ┆ rs  ┆     ┆     ┆     ┆     ┆ cin ┆ cer ┆     ┆     ┆     ┆     ┆ 631 ┆     ┆     ┆ RR2 ┆ RR2 ┆     ┆     ┆ -se ┆ 206 ┆ 61; ┆     ┆     ┆ cer ┆     ┆ -se ┆     ┆ cin ┆ e6  ┆ kem ┆ RR2 ┆     ┆     ┆     ┆ 206 ┆     ┆     ┆ /SR ┆ ;33 ┆     ┆ 1   ┆ O-s ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆ mpl ┆     ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆     ┆     ┆ 3-4 ┆     ┆     ┆     ┆     ┆     ┆ g:  ┆ cel ┆     ┆     ┆     ┆     ┆ 1;4 ┆     ┆     ┆ 06/ ┆ 06/ ┆     ┆     ┆ q   ┆ /06 ┆ 198 ┆     ┆     ┆ cel ┆     ┆ q   ┆     ┆ g:  ┆ vs  ┆ ia  ┆ 06/ ┆     ┆     ┆     ┆ /06 ┆     ┆     ┆ R20 ┆ 213 ┆     ┆     ┆ eq) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NHS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es/ ┆ es/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ ls  ┆     ┆     ┆     ┆     ┆ 188 ┆     ┆     ┆ 064 ┆ 064 ┆     ┆     ┆ NHS ┆ 4/S ┆ 44f ┆     ┆     ┆ ls  ┆     ┆ NHS ┆     ┆ GSM ┆ 588 ┆     ┆ 064 ┆     ┆     ┆     ┆ 4/S ┆     ┆     ┆ 6/0 ┆ ;33 ┆     ┆     ┆ was ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆ GSM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-7 ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆ to  ┆     ┆     ┆     ┆     ┆ 345 ┆     ┆     ┆ /SR ┆ /SR ┆     ┆     ┆     ┆ RR2 ┆ ade ┆     ┆     ┆ to  ┆     ┆     ┆     ┆ 638 ┆ 86e ┆     ┆ /SR ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆ 64/ ┆ 511 ┆     ┆     ┆ per ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 638 ┆ 638 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 364 ┆ hea ┆     ┆     ┆     ┆     ┆ 667 ┆     ┆     ┆ R20 ┆ R20 ┆     ┆     ┆     ┆ 063 ┆ e68 ┆     ┆     ┆ hea ┆     ┆     ┆     ┆ 364 ┆ d88 ┆     ┆ R20 ┆     ┆     ┆     ┆ 063 ┆     ┆     ┆ SRR ┆ ;77 ┆     ┆     ┆ for ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3nn ┆ 3nn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2:  ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 631 ┆ 631 ┆     ┆     ┆     ┆ 136 ┆ afb ┆     ┆     ┆ t   ┆     ┆     ┆     ┆ 2:  ┆ 264 ┆     ┆ 631 ┆     ┆     ┆     ┆ 136 ┆     ┆     ┆ 206 ┆ 11; ┆     ┆     ┆ med ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n/G ┆ n/G ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ K56 ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 364 ┆ 364 ┆     ┆     ┆     ┆ 4/S ┆ 89f ┆     ┆     ┆ sho ┆     ┆     ┆     ┆ K56 ┆ 719 ┆     ┆ 364 ┆     ┆     ┆     ┆ 4/S ┆     ┆     ┆ 313 ┆ 895 ┆     ┆     ┆ as  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SM6 ┆ SM6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ ck- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ /SR ┆ /SR ┆     ┆     ┆     ┆ RR2 ┆ 7b4 ┆     ┆     ┆ ck- ┆     ┆     ┆     ┆ 2   ┆ b5c ┆     ┆ /SR ┆     ┆     ┆     ┆ RR2 ┆     ┆     ┆ 64/ ┆ 93; ┆     ┆     ┆ pre ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## 12. GSE200269 PRO-IP-seq (SINGLE)

<!-- - ✅ DOWNLOAD (yone-SSD) -->
<!-- - ✅ Preprocesses PRO-seq data using [proseq2.0.bsh](https://github.com/Danko-Lab/proseq2.0) (yone-SSD) -->
<!-- - ✅ Caluculate average scores using [bigWigAverageOverBed](https://open.bioqueue.org/home/knowledge/showKnowledge/sig/ucsc-bigwigaverageoverbed) as fanta.bio CRE level (yone-SSD) -->

&nbsp;

- [PRO-IP-seq tracks molecular modifications of engaged Pol II complexes at nucleotide resolution](https://doi.org/10.1038/s41467-023-42715-3)
- [./12_8_metadata_other.ipynb](./12_8_metadata_other.ipynb) から処理を移動
- PRO-IP-seq という C-terminal Domain にリン酸化修飾を受けている RNA Polymerase II が持つ nascent RNA を検出している手法
- GEOのページの Treatment protocol に以下のような記載がある
- `The cells were maintained at 37°C (NHS) or heat treated for 30 min at 42°C (HS30). The heat shock was conducted in pre-conditioned pre-warmed media. The control cells (NHS) were treated as the heat shocked (HS30) cells but using preconditioned media pre-warmed to 37°C.`
-

In [37]:
GSE200269_PEP = pl.read_csv(
    "../../Data/metadata/metadata_geofetch/GSE200269/GSE200269_PEP/GSE200269_PEP_raw.csv",
    separator=','
).filter(
    (pl.col("sample_organism_ch1") == "Homo sapiens") &
    (pl.col("library_preparation") == "PRO-IP-seq")
).with_columns(
    (pl.col("biosample").str.split("/").list.get(-1).alias("sample_accession")),
    # (pl.lit("unknown").alias("rna_library")),
    (pl.lit("https://doi.org/10.1038/s41467-023-43157-7").alias("reference_doi")),
    # (pl.lit("Illumina TruSeq Small RNA adapters").alias("adapter")),
    (pl.lit("42 C").alias("stress treatment temperature")),
    (pl.lit("30 min.").alias("stress treatment time")),
    (pl.lit("37 C").alias("control treatment temperature"))
).rename(
    {
        "sample_series_id": "gse_id",
        "big_key": "experiment_accession"
    }
).drop(
    "sra",
    "biosample",
    "organism",
    "read_type",
    "data_source"
)


# metadata from iseq
GSE200269 = pl.read_csv(
    "../../Data/metadata/metadata_iseq/GSE200269.metadata.tsv",
    separator='\t'
)

GSE200269_iseq_filtered = GSE200269[[s.name for s in GSE200269 if not (s.null_count() == GSE200269.height)]]


# display(GSE200269_PEP)

In [38]:
GSE200269_combined = GSE200269_PEP.join(
    GSE200269_iseq_filtered,
    on=["experiment_accession", "sample_accession"],
    how="left",
    coalesce=True
).with_columns(
    (pl.col("run_accession").alias("srr")), # run_accession の値を srr カラムに上書き
    (pl.col("experiment_accession").alias("srx")) # sample_title の値を sample_name カラムに上書き
).sort(
    [
        "gsm_id"
    ],
    descending=[
        False
    ]
)

GSE200269_combined.write_csv(
    "../../Data/metadata/metadata_proseq/GSE200269_pro-ip-seq_modified_metadata.tsv",
    separator='\t'
)

# pl.Config.set_tbl_rows(32)
# display(GSE200269_combined)

In [39]:
# Manual defined pairs
defined_pairs_gse200269 = [
    # i1 (Downloaded from SRA)
    ("SRR18653122", "SRR18653125"), # i1_hs30_ctd_rep1 vs. i1_nhs_ctd_rep1 (unphosphorylated CTD (unPhCTD))
    ("SRR18653111", "SRR18653121"), # i1_hs30_igg_rep1 vs. i1_nhs_igg_rep1 (unspecific IgG)
    ("SRR18653112", "SRR18653118"), # i1_hs30_input_rep1 vs. i1_nhs_input_rep1 (no antibody = PRO-seq)
    ("SRR18653117", "SRR18653124"), # i1_hs30_s2_rep1 vs. i1_nhs_s2_rep1 (serine-2-phosphorylated CTD (ser2PhCTD))
    ("SRR18653123", "SRR18653120"), # i1_hs30_s5_rep1 vs. i1_nhs_s5_rep1 (serine-5-phosphorylated CTD (ser5PhCTD))
    ("SRR18653116", "SRR18653119"), # i1_hs30_s7_rep1 vs. i1_nhs_s7_rep1 (serine-7-phosphorylated CTD (ser7PhCTD))

    # i2
    ("SRR18653115", "SRR18653110"), # i2_hs30_ctd_rep2 vs. i2_nhs_ctd_rep2 (unphosphorylated CTD (unPhCTD))
    ("SRR18653101", "SRR18653114"), # i2_hs30_igg_rep2 vs. i2_nhs_igg_rep2 (unspecific IgG)
    ("SRR18653100", "SRR18653104"), # i2_hs30_input_rep2 vs. i2_nhs_input_rep2 (no antibody = PRO-seq)
    ("SRR18653103", "SRR18653113"), # i2_hs30_s2_rep2 vs. i2_nhs_s2_rep2 (serine-2-phosphorylated CTD (ser2PhCTD))
    ("SRR18653102", "SRR18653109"), # i2_hs30_s5_rep2 vs. i2_nhs_s5_rep2 (serine-5-phosphorylated CTD (ser5PhCTD))
    # なぜか i2_hs30_s7_rep2 に該当するような accession が メタデータには登録されていない...

    # i3
    ("SRR18653094", "SRR18653099"), # i3_hs30_ctd_rep3 vs. i3_nhs_ctd_rep3 (unphosphorylated CTD (unPhCTD))
    # なぜか i3_hs30_igg_rep3 に該当するような accession が メタデータには登録されていない...
    ("SRR18653107", "SRR18653095"), # i3_hs30_input_rep3 vs. i3_nhs_input_rep3 (no antibody = PRO-seq)
    ("SRR18653108", "SRR18653098"), # i3_hs30_s2_rep3 vs. i3_nhs_s2_rep3 (serine-2-phosphorylated CTD (ser2PhCTD))
    ("SRR18653106", "SRR18653097"), # i3_hs30_s5_rep3 vs. i3_nhs_s5_rep3 (serine-5-phosphorylated CTD (ser5PhCTD))
    ("SRR18653105", "SRR18653096")  # i3_hs30_s7_rep3 vs. i3_nhs_s7_rep3 (serine-7-phosphorylated CTD (ser7PhCTD))
]

paired_metadata_df_gse200269 = create_paired_metadata(
    combined_df=GSE200269_combined,
    defined_sample_pairs=defined_pairs_gse200269,
    sample_id_column_name="run_accession"
)

if paired_metadata_df_gse200269 is not None:
    paired_metadata_df_gse200269.write_csv(
        "../../Data/metadata/metadata_proseq/GSE200269_pro-ip-seq_paired_metadata.tsv",
        separator='\t'
    )
    display(paired_metadata_df_gse200269)
else:
    print("No paired metadata to write (create_paired_metadata returned None).")

shape: (16, 78)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sam ┆ sam ┆ sam ┆ pro ┆ srr ┆ srx ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ sam ┆ gsm ┆ sam ┆ gse ┆ sam ┆ exp ┆ ant ┆ ant ┆ lib ┆ ass ┆ sam ┆ ref ┆ str ┆ str ┆ con ┆ stu ┆ sec ┆ sec ┆ sub ┆ tax ┆ sci ┆ ins ┆ ins ┆ lib ┆ lib ┆ lib ┆ lib ┆ lib ┆ rea ┆ bas ┆ fir ┆ las ┆ exp ┆ stu ┆ stu ┆ exp ┆ run ┆ fas ┆ fas ┆ fas ┆ fas ┆ fas ┆ sam ┆ sam ┆ fir │
│ ple ┆ ple ┆ ple ┆ toc ┆ --- ┆ --- ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ ple ┆ _id ┆ ple ┆ _id ┆ ple ┆ eri ┆ ibo ┆ ibo ┆ rar ┆ emb ┆ ple ┆ ere ┆ ess ┆ ess ┆ tro ┆ dy_ ┆ ond ┆ ond ┆ mis ┆ _id ┆ ent ┆ tru ┆ tru ┆ rar ┆ rar ┆ rar ┆ rar ┆ rar ┆ d_c ┆ e_c ┆ st_ ┆ t_u ┆ eri ┆ dy_ ┆ dy_ ┆ eri ┆ _al ┆ tq_ ┆ tq_ ┆ tq_ ┆ tq_ ┆ tq_ ┆ ple ┆ ple ┆ st_ │
│ _he ┆ _co ┆ _na ┆ ol  ┆ str ┆ str ┆ _ti ┆ _ge ┆ _st ┆ _su ┆ _la ┆ _ty ┆ _ch ┆ _so ┆ _or ┆ _ta ┆ _mo ┆ _ex ┆ _de ┆ _pl ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _in ┆ _li ┆ _li ┆ _li ┆ --- ┆ _su ┆ --- ┆ _da ┆ men ┆ dy  ┆ dy_ ┆ y_p ┆ ly  ┆ _ac ┆ nce ┆ tre ┆ tre ┆ l   ┆ acc ┆ ary ┆ ary ┆ sio ┆ --- ┆ ifi ┆ men ┆ men ┆ y_n ┆ y_l ┆ y_s ┆ y_s ┆ y_s ┆ oun ┆ oun ┆ pub ┆ pda ┆ men ┆ tit ┆ ali ┆ men ┆ ias ┆ byt ┆ md5 ┆ ftp ┆ asp ┆ gal ┆ _al ┆ _ti ┆ cre │
│ at_ ┆ ntr ┆ me  ┆ --- ┆     ┆     ┆ tle ┆ o_a ┆ atu ┆ bmi ┆ st_ ┆ pe  ┆ ann ┆ urc ┆ gan ┆ xid ┆ lec ┆ tra ┆ scr ┆ atf ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ nta ┆ str ┆ bra ┆ bra ┆ bra ┆ str ┆ ppl ┆ str ┆ ta_ ┆ t_a ┆ --- ┆ epi ┆ rep ┆ --- ┆ ces ┆ _do ┆ atm ┆ atm ┆ tre ┆ ess ┆ _st ┆ _sa ┆ n_a ┆ str ┆ c_n ┆ t_p ┆ t_m ┆ ame ┆ ayo ┆ tra ┆ our ┆ ele ┆ t   ┆ t   ┆ lic ┆ ted ┆ t_t ┆ le  ┆ as  ┆ t_a ┆ --- ┆ es  ┆ --- ┆ --- ┆ era ┆ axy ┆ ias ┆ tle ┆ ate │
│ id  ┆ ol_ ┆ --- ┆ str ┆     ┆     ┆ --- ┆ cce ┆ s   ┆ ssi ┆ upd ┆ --- ┆ el_ ┆ e_n ┆ ism ┆ _ch ┆ ule ┆ ct_ ┆ ipt ┆ orm ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ct_ ┆ ume ┆ ry_ ┆ ry_ ┆ ry_ ┆     ┆ eme ┆     ┆ row ┆ cce ┆ str ┆ top ┆ ara ┆ str ┆ sio ┆ i   ┆ ent ┆ ent ┆ atm ┆ ion ┆ udy ┆ mpl ┆ cce ┆     ┆ ame ┆ lat ┆ ode ┆ --- ┆ ut  ┆ teg ┆ ce  ┆ cti ┆ --- ┆ --- ┆ --- ┆ --- ┆ itl ┆ --- ┆ --- ┆ lia ┆ str ┆ --- ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ _ri ┆ d   │
│ --- ┆ id  ┆ str ┆     ┆     ┆     ┆ str ┆ ssi ┆ --- ┆ on_ ┆ ate ┆ str ┆ cou ┆ ame ┆ _ch ┆ 1   ┆ _ch ┆ pro ┆ ion ┆ _id ┆ nam ┆ ema ┆ pho ┆ lab ┆ dep ┆ ins ┆ add ┆ cit ┆ zip ┆ cou ┆ nt_ ┆ sel ┆ sou ┆ str ┆     ┆ nta ┆     ┆ _co ┆ ssi ┆     ┆ e   ┆ tio ┆     ┆ n   ┆ --- ┆ tem ┆ tim ┆ ent ┆ --- ┆ _ac ┆ e_a ┆ ssi ┆     ┆ --- ┆ for ┆ l   ┆ str ┆ --- ┆ y   ┆ --- ┆ on  ┆ str ┆ str ┆ str ┆ str ┆ e   ┆ str ┆ str ┆ s   ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆ str ┆ ght ┆ --- │
│ str ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ on  ┆ str ┆ dat ┆ _da ┆     ┆ nt  ┆ _ch ┆ 1   ┆ --- ┆ 1   ┆ toc ┆ --- ┆ --- ┆ e   ┆ il  ┆ ne  ┆ ora ┆ art ┆ tit ┆ res ┆ y   ┆ _po ┆ ntr ┆ mod ┆ ect ┆ rce ┆ ate ┆     ┆ ry_ ┆     ┆ unt ┆ on  ┆     ┆ --- ┆ n   ┆     ┆ --- ┆ str ┆ per ┆ e   ┆ tem ┆ str ┆ ces ┆ cce ┆ on  ┆     ┆ str ┆ m   ┆ --- ┆     ┆ str ┆ --- ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ str │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ e   ┆ te  ┆     ┆ --- ┆ 1   ┆ --- ┆ str ┆ --- ┆ ol_ ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ tor ┆ men ┆ ute ┆ s   ┆ --- ┆ sta ┆ y   ┆ el  ┆ ion ┆ --- ┆ gy  ┆     ┆ fil ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆     ┆ str ┆     ┆ atu ┆ --- ┆ per ┆     ┆ sio ┆ ssi ┆ --- ┆     ┆     ┆ --- ┆ str ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆ --- ┆     ┆ str ┆ --- ┆ str ┆     ┆ str ┆ ch1 ┆     ┆     ┆ str ┆ str ┆ str ┆ y   ┆ t   ┆ --- ┆ --- ┆ str ┆ l_c ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ e_1 ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ re  ┆ str ┆ atu ┆     ┆ n   ┆ on  ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ str ┆ str ┆     ┆ ode ┆ str ┆ str ┆ str ┆     ┆ str ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ re  ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ --- ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ SRR ┆ SRR ┆ i1_ ┆ Hea ┆ SRR ┆ SRX ┆ i1_ ┆ GSM ┆ Pub ┆ Apr ┆ Feb ┆ SRA ┆ 1   ┆ K56 ┆ Hom ┆ 960 ┆ tot ┆ Ill ┆ nas ┆ GPL ┆ Ann ┆ mav ┆ +35 ┆ Vih ┆ Gen ┆ KTH ┆ Tom ┆ Sto ┆ 171 ┆ Swe ┆ Ill ┆ oth ┆ tra ┆ RIP ┆ GSM ┆ NON ┆ GSE ┆ 0   ┆ SRX ┆ AbC ┆ unp ┆ PRO ┆ hg1 ┆ SAM ┆ htt ┆ 42  ┆ 30  ┆ 37  ┆ PRJ ┆ SRP ┆ SRS ┆ SRA ┆ 960 ┆ Hom ┆ ILL ┆ Nex ┆ GSM ┆ SIN ┆ RIP ┆ TRA ┆ oth ┆ 434 ┆ 357 ┆ 202 ┆ 202 ┆ Nex ┆ PRO ┆ GSE ┆ GSM ┆ GSM ┆ 158 ┆ f37 ┆ ftp ┆ fas ┆ ftp ┆ GSM ┆ i1_ ┆ 202 │
│ 186 ┆ 186 ┆ hs3 ┆ t   ┆ 186 ┆ 147 ┆ HS3 ┆ 602 ┆ lic ┆ 06  ┆ 24  ┆     ┆     ┆ 2   ┆ o   ┆ 6   ┆ al  ┆ umi ┆ cen ┆ 185 ┆ iin ┆ ih@ ┆ 8   ┆ erv ┆ e   ┆ Roy ┆ teb ┆ ckh ┆ 65  ┆ den ┆ umi ┆ er  ┆ nsc ┆ -Se ┆ 602 ┆ E   ┆ 200 ┆     ┆ 147 ┆ am  ┆ hos ┆ -IP ┆ 9   ┆ N27 ┆ ps: ┆ C   ┆ min ┆ C   ┆ NA8 ┆ 367 ┆ 125 ┆ 139 ┆ 6   ┆ o   ┆ UMI ┆ tSe ┆ 602 ┆ GLE ┆ -Se ┆ NSC ┆ er  ┆ 624 ┆ 100 ┆ 3-0 ┆ 3-0 ┆ tSe ┆ -IP ┆ 200 ┆ 602 ┆ 602 ┆ 062 ┆ 7fe ┆ .sr ┆ p.s ┆ .sr ┆ 602 ┆ HS3 ┆ 3-0 │
│ 531 ┆ 531 ┆ 0_c ┆ tre ┆ 531 ┆ 561 ┆ 0_C ┆ 579 ┆ on  ┆ 202 ┆ 202 ┆     ┆     ┆     ┆ sap ┆     ┆ RNA ┆ na  ┆ t   ┆ 73  ┆ a,, ┆ kth ┆ 50  ┆ aar ┆ Tec ┆ al  ┆ oda ┆ olm ┆     ┆     ┆ na  ┆     ┆ rip ┆ q   ┆ 579 ┆     ┆ 269 ┆     ┆ 561 ┆ YWG ┆ pho ┆ -se ┆     ┆ 365 ┆ //d ┆     ┆ .   ┆     ┆ 239 ┆ 808 ┆ 170 ┆ 864 ┆     ┆ sap ┆ NA  ┆ q   ┆ 579 ┆     ┆ q   ┆ RIP ┆     ┆ 12  ┆ 888 ┆ 2-2 ┆ 2-2 ┆ q   ┆ -se ┆ 269 ┆ 579 ┆ 579 ┆ 785 ┆ bd8 ┆ a.e ┆ ra. ┆ a.e ┆ 579 ┆ 0_C ┆ 2-2 │
│ 22  ┆ 25  ┆ td_ ┆ ate ┆ 22  ┆ 51  ┆ TD_ ┆ 9   ┆ Feb ┆ 2   ┆ 3   ┆     ┆     ┆     ┆ ien ┆     ┆     ┆ Nex ┆ RNA ┆     ┆ Vih ┆ .se ┆ 546 ┆ a   ┆ hno ┆ Ins ┆ väg ┆     ┆     ┆     ┆ Nex ┆     ┆ tom ┆     ┆ 9   ┆     ┆     ┆     ┆ 51  ┆ 16  ┆ ryl ┆ q   ┆     ┆ 889 ┆ oi. ┆     ┆     ┆     ┆ 09  ┆     ┆ 05  ┆ 5   ┆     ┆ ien ┆     ┆ 500 ┆ 9   ┆     ┆     ┆ TOM ┆     ┆ vs  ┆ 1   ┆ 7   ┆ 8   ┆ 500 ┆ q:  ┆     ┆ 9_r ┆ 9_r ┆ 2   ┆ 6b4 ┆ bi. ┆ ebi ┆ bi. ┆ 9   ┆ TD_ ┆ 7   │
│     ┆     ┆ rep ┆ d   ┆ vs  ┆ vs  ┆ rep ┆ vs  ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ tSe ┆ ,   ┆     ┆ erv ┆     ┆ 369 ┆     ┆ log ┆ tit ┆ en  ┆     ┆     ┆     ┆ tSe ┆     ┆ ic  ┆     ┆ vs  ┆     ┆     ┆     ┆ vs  ┆     ┆ ate ┆     ┆     ┆ vs  ┆ org ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆ s   ┆     ┆     ┆ vs  ┆     ┆     ┆ IC  ┆     ┆ 176 ┆ vs  ┆     ┆ vs  ┆ seq ┆ Pol ┆     ┆ 1   ┆ 1   ┆ vs  ┆ d32 ┆ ac. ┆ .ac ┆ ac. ┆ vs  ┆ rep ┆     │
│     ┆     ┆ 1   ┆ at  ┆ SRR ┆ SRX ┆ 1   ┆ GSM ┆ 202 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆ iPR ┆     ┆ aar ┆     ┆ 4   ┆     ┆ y   ┆ ute ┆ 23A ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆ SRX ┆     ┆ d   ┆     ┆     ┆ SAM ┆ /10 ┆     ┆     ┆     ┆     ┆     ┆ SRS ┆     ┆     ┆     ┆     ┆     ┆ GSM ┆     ┆     ┆     ┆     ┆ 821 ┆ 145 ┆     ┆ 202 ┆ uen ┆ II  ┆     ┆ vs  ┆ vs  ┆ 392 ┆ 7de ┆ uk/ ┆ .uk ┆ uk/ ┆ GSM ┆ 1   ┆     │
│     ┆     ┆ vs  ┆ 42d ┆ 186 ┆ 147 ┆ vs  ┆ 602 ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 500 ┆ O_H ┆     ┆ a   ┆     ┆     ┆     ┆     ┆ of  ┆     ┆     ┆     ┆     ┆ 500 ┆     ┆     ┆     ┆ 602 ┆     ┆     ┆     ┆ 147 ┆     ┆ CTD ┆     ┆     ┆ N27 ┆ .10 ┆     ┆     ┆     ┆     ┆     ┆ 125 ┆     ┆     ┆     ┆     ┆     ┆ 602 ┆     ┆     ┆     ┆     ┆ 28  ┆ 422 ┆     ┆ 3-0 ┆ cin ┆ CTD ┆     ┆ GSM ┆ GSM ┆ 995 ┆ 6a4 ┆ vol ┆ :/v ┆ vol ┆ 602 ┆ vs  ┆     │
│     ┆     ┆ i1_ ┆ egr ┆ 531 ┆ 561 ┆ i1_ ┆ 579 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆ S30 ┆     ┆     ┆     ┆     ┆     ┆     ┆ Tec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 579 ┆     ┆     ┆     ┆ 561 ┆     ┆ (un ┆     ┆     ┆ 365 ┆ 38/ ┆     ┆     ┆     ┆     ┆     ┆ 169 ┆     ┆     ┆     ┆     ┆     ┆ 579 ┆     ┆     ┆     ┆     ┆     ┆ 342 ┆     ┆ 3-1 ┆ g:  ┆ cod ┆     ┆ 602 ┆ 602 ┆ 677 ┆ 11b ┆ 1/f ┆ ol1 ┆ 1/f ┆ 579 ┆ i1_ ┆     │
│     ┆     ┆ nhs ┆ eeC ┆ 25  ┆ 45  ┆ NHS ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ill ┆ _CT ┆     ┆     ┆     ┆     ┆     ┆     ┆ hno ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 45  ┆     ┆ PhC ┆     ┆     ┆ 895 ┆ s41 ┆     ┆     ┆     ┆     ┆     ┆ 99  ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ 4   ┆ GSM ┆ e   ┆     ┆ 579 ┆ 579 ┆     ┆ 4d0 ┆ ast ┆ /fa ┆ ast ┆ 3   ┆ NHS ┆     │
│     ┆     ┆ _ct ┆ for ┆     ┆     ┆ _CT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ umi ┆ D_B ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TD) ┆     ┆     ┆     ┆ 467 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 602 ┆ at  ┆     ┆ 3_r ┆ 3_r ┆     ┆ 3a1 ┆ q/S ┆ stq ┆ q/S ┆     ┆ _CT ┆     │
│     ┆     ┆ d_r ┆ 30  ┆     ┆     ┆ D_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ na  ┆ Rs_ ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -02 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 579 ┆ nt- ┆     ┆ 1   ┆ 1   ┆     ┆ 33  ┆ RR1 ┆ /SR ┆ RR1 ┆     ┆ D_r ┆     │
│     ┆     ┆ ep1 ┆ min ┆     ┆     ┆ ep1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nov ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3-4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9:  ┆ res ┆     ┆     ┆     ┆     ┆ vs  ┆ 86/ ┆ R18 ┆ 86/ ┆     ┆ ep1 ┆     │
│     ┆     ┆     ┆ ute ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aSe ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 315 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i1_ ┆ olu ┆     ┆     ┆     ┆     ┆ cdd ┆ 022 ┆ 6/0 ┆ 022 ┆     ┆     ┆     │
│     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q60 ┆ ize ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HS3 ┆ tio ┆     ┆     ┆     ┆     ┆ 794 ┆ /SR ┆ 22/ ┆ /SR ┆     ┆     ┆     │
│     ┆     ┆     ┆ (HS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ d_p ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0_C ┆ n   ┆     ┆     ┆     ┆     ┆ 619 ┆ R18 ┆ SRR ┆ R18 ┆     ┆     ┆     │
│     ┆     ┆     ┆ 30) ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l.b ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ TD_ ┆ in  ┆     ┆     ┆     ┆     ┆ cec ┆ 653 ┆ 186 ┆ 653 ┆     ┆     ┆     │
│     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ igW ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rep ┆ hum ┆     ┆     ┆     ┆     ┆ bfa ┆ 122 ┆ 531 ┆ 122 ┆     ┆     ┆     │
│     ┆     ┆     ┆ No  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ig, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ an  ┆     ┆     ┆     ┆     ┆ 51d ┆ /SR ┆ 22/ ┆ /SR ┆     ┆     ┆     │
│     ┆     ┆     ┆ hea ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ iPR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hom ┆ K56 ┆     ┆     ┆     ┆     ┆ dca ┆ R18 ┆ SRR ┆ R18 ┆     ┆     ┆     │
│     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ O_H ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆ 2   ┆     ┆     ┆     ┆     ┆ 8af ┆ 653 ┆ 186 ┆ 653 ┆     ┆     ┆     │
│     ┆     ┆     ┆ sho ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S30 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sap ┆ cel ┆     ┆     ┆     ┆     ┆ a48 ┆ 122 ┆ 531 ┆ 122 ┆     ┆     ┆     │
│     ┆     ┆     ┆ ck, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _CT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ien ┆ ls  ┆     ┆     ┆     ┆     ┆ 4dc ┆ .fa ┆ 22. ┆ .fa ┆     ┆     ┆     │
│     ┆     ┆     ┆ mai ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ D_B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆ 08  ┆ stq ┆ fas ┆ stq ┆     ┆     ┆     │
│     ┆     ┆     ┆ nta ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Rs_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ RIP ┆     ┆     ┆     ┆     ┆     ┆     ┆ .gz ┆ tq. ┆ .gz ┆     ┆     ┆     │
│     ┆     ┆     ┆ ine ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -Se ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆ gz  ┆ vs  ┆     ┆     ┆     │
│     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ q   ┆     ┆     ┆     ┆     ┆     ┆     ┆ ftp ┆ vs  ┆ ftp ┆     ┆     ┆     │
│     ┆     ┆     ┆ at  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ize ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vs  ┆     ┆     ┆     ┆     ┆     ┆     ┆ .sr ┆ fas ┆ .sr ┆     ┆     ┆     │
│     ┆     ┆     ┆ 37d ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_m ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Nex ┆     ┆     ┆     ┆     ┆     ┆     ┆ a.e ┆ p.s ┆ a.e ┆     ┆     ┆     │

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## concat dataframe (including GRO-seq)

In [40]:
dfs_proseq_all: list[pl.DataFrame | None] = [
    paired_metadata_gse228346_proseq,
    paired_metadata_df_gse173537_pro_seq,
    paired_metadata_df_gse211651_pro_seq,
    paired_metadata_df_gse154746_pro_seq,
    paired_metadata_df_gse202187,
    paired_metadata_df_gse127844_pro_seq,
    paired_metadata_df_gse66448, # GRO-seq
    paired_metadata_df_gse89230,
    paired_metadata_df_gse112379,
    paired_metadata_df_gse144786_proseq,
    paired_metadata_df_gse209685,
    # paired_metadata_df_gse200269 # PRO-IP-seq
]


dfs_proseq:  list[pl.DataFrame] = [df for df in dfs_proseq_all if df is not None]

In [41]:
proseq_concat = pl.concat(dfs_proseq, how="diagonal_relaxed")

proseq_concat.write_csv(
    f"../../Data/metadata/metadata_{VERSION}/proseq_metadata_all_{execute_date}.tsv",
    separator='\t'
)